### ISSUE TITLE
@charset in imported files

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1]
Sass needs to handle the case where @charset is specified in an imported file by moving the @charset directive to the start of the document and normalizing different charsets across all imported files.

**Comment by nex3** [comment]
Merge remote branch 'haml/stable' into stable

Closed by 8296d29962dada2d2ac5ba9e2a5b3a8801a47b58

**Comment by ultimatedelman** [comment]
This is again an issue in whatever new release of SASS. 

I have a "_scaffolding.scss" file that is imported by all my main .scss files. In it are all my common imports and my @charset declaration. All of the sudden my files show `@charset "IBM437"` after updating to the most recent version of SASS. It is fixed when I put the declaration on the actual .scss file.

**Comment by nex3** [comment]
@ultimatedelman I don't completely understand the issue you're reporting. Can you post an example of the file or files that are producing the issue, as well as the output you expect and the output you're actually receiving?

**Comment by ultimatedelman** [comment]
ok let's say i have a file `main.scss` that generates a `main.css` file. let's also say i have a file named `_partial1.scss` in my `/partials/` folder.

my `main.scss` file looks like this:

`@import "partials/_partial1";`

and my `_partial1.scss` file looks like this:

`@charset "utf-8";`

the `main.css` file output then looks like this:

`@charset "IBM437";` 

instead of:

`@charset "utf-8";`

**Comment by ultimatedelman** [comment]
you know what, i realized i'm probably posting this in the wrong spot. this is probably a Compass issue. I'm sorry!

**Comment by nex3** [comment]
That may still be a Sass issue. Sass has a lot of internal `@charset` handling.

Do either of your files have any non-ASCII characters in them at all? What do you get if you run `ruby -e 'p [Encoding.default_internal, Encoding.default_external]'` on the command line?

**Comment by nex3** [comment]
Closing this due to unresponsiveness.
