### ISSUE TITLE
Support for Basic User Interface Module

### ISSUE THREAD

**Issue by ghost** [sass/sass#1001]
The CSS 3 Basic User Interface Module defines the ability to use `nav-up`, `nav-left` etc with an id target as the expression, however, SASS rejects this syntax. For example:

```
#cal_1 {
  nav-up: #cal_date;
}
```

However, SASS rejects with with the error:

> error Colors must have either three or six digits: '#ca'

There doesn't appear to be a way to use an id as a value in SASS which is required for the UI module.

**Comment by nex3** [comment]
It's always a little frustrating when the WG adds syntax that breaks Sass's forwards-compatibility.

It looks like this will force us to implement #363 as well, since an identifier beginning with `#` could potentially be either a color or an id.

**Comment by chriseppstein** [comment]
I think the csswg will view this as a breaking syntax change if we take it to them. We should encourage them to require quotes here.

**Comment by nex3** [comment]
If we can push back on them to require quotes, that would be fantastic.

**Comment by chriseppstein** [comment]
@tabatkins thoughts?

**Comment by tabatkins** [comment]
@nex3 The nav-\* properties have accepted an ID since at least 2004, per spec: http://www.w3.org/TR/2004/CR-css3-ui-20040511/#nav-dir.  I think this change predates SASS by at least a little bit.  ^_^

**Comment by nex3** [comment]
I'm surprised we haven't noticed/run into that until now. I guess we'll have to support this, then.

**Comment by tabatkins** [comment]
The only desktop browser to implement it was old Opera, so it's unsurprising.  There are some TV browsers that implement it now.

**Comment by DataTables** [comment]
This is brilliant - thank you :-)
