### ISSUE TITLE
Looking for pre-compile step that generates a single scss file with dependencies resolved

### ISSUE THREAD

**Issue by marrs** [sass/sass#1005]
I'd like a sass command that can take a source.scss file as an input, resolve its dependencies (declared with syntax like `@import grid.scss;`) and output a single dest.scss file that is the concatenation of all imported files and source.scss.

At a later stage I will then run sass on the dest.scss file to produce a final css file.

Does anything like this exist and if not, are there developer docs I can read to help me get started implementing the feature?

**Comment by lolmaus** [comment]
1. What result do you have when you follow the described steps with the original `sass` command line tool?
2. Have you considered making `grid.scss` a partial, i. e. renaming it into `_grid.scss`?

**Comment by marrs** [comment]
1. I get a CSS file. 
2. I'm not doing that at the moment but I think the end result is the same, isn't it?  

The background to this is that I have a base.scss that is composed of many modules with interdependencies.  That base.scss is then used by an external project that has its own domain specific scss files.  It may also have its own asset rendering process.

There are many projects with different technology stacks.  It would simplify things for the project owners considerably if they could have access to a single SCSS file that they can then @import into their stylesheets.

Having an SCSS file is important because then the project can make use of the various helpers that are in the base.scss

**Comment by lolmaus** [comment]
Oh, i'm sorry, i failed to notice that you need `.scss` as the result. But why do you need to concatenate your Sass project into a single file?

**Comment by cimmanon** [comment]
I'm going to have to agree with lolmaus here.  What you're asking for doesn't make a lot of sense.

That said, you might want to take a look at Compass Extensions:  http://compass-style.org/help/tutorials/extensions/

**Comment by marrs** [comment]
So consider the following chain of dependencies:

Project - the site that I'm building
Module - a building block containing SCSS and JS assets
Components - Each module is built out of components. Some of these are provided by 3rd parties and have their own directory structure. Modules may share some of the same components.

I'm trying to simplify my delivery pipeline. I have lots of modules that I'm pulling into a project.  At the moment, my project has to know about and manage each module's components, but I don't want to have to care about components at the project level, only about modules.  Ideally I'd like to define a module as a package that always gets installed to `bower_components/<module_name>` and always provides a main.scss at a known location.

Now building becomes easy because I know that I can look in the same place for the same single file for every module.

**Comment by nex3** [comment]
This is the sort of thing that would be relatively straightforward to build using Sass's Ruby API, but isn't something that's broadly useful enough to include in the core Sass functionality.

**Comment by NickHeiner** [comment]
I need something pretty similar to this - I'd like to be able to resolve all imports at one step in my build pipeline, and then do the compilation later. I understand if that's not a common enough use-case, though.

**Comment by Tzrlk** [comment]
I'm also interested in this feature. Being able to generate optimised scss output will speed up later compilation if the styling properties aren't known until runtime.

**Comment by scottdavis** [comment]
For anyone needing this still I have written a tool that does this: https://github.com/scottdavis/sass-concat

**Comment by Ray-D-Song** [comment]
> For anyone needing this still I have written a tool that does this: https://github.com/scottdavis/sass-concat

I really need this, why is the warehouse 404, brother?😭
