### ISSUE TITLE
Investigate whether DelegateClass makes rubinius slow in MultibyteStringScanner

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1008]
In 811533bffdcf9fd7056e98610b5bd5ff98deb004 we changed to DelegateClass for MultibyteStringScanner in rubinius. It's very likely this is a performance issue. We need to profile it and see if using simple delegation gives considerable speed up for that platform.

**Comment by nex3** [comment]
I don't think we're especially concerned about specifically targeting Rubinius anymore.
