### ISSUE TITLE
[bug] line comments within stream comments

### ISSUE THREAD

**Issue by albeva** [sass/sass#101]
If line comments are present within stream comments `/*` and `*/` the result generated in wrong because line comments within are converted to `/*` and `*/`

``` css
/*
// foo
*/
```

is turned into:

``` css
/*
/* foo */
*/
```

**Comment by nex3** [comment]
I'm not entirely clear on in what context this is occurring, but it doesn't reproduce under Sass or SCSS.

**Comment by demerzel3** [comment]
I'm using sass version 3.1.19 and I am experiencing this bug. After some debugging I trimmed it down to a basic example.
Paste this in a .scss and try for yourself (indentation matters!!):

``` scss
body {
  /*
  //comment here
  */
}
```

the output I have after running sass is:

``` css
body {
  /*
  /*comment here */
  */ }
```

**Comment by nex3** [comment]
Reopening, since I can reproduce using @demerzel3's example.

**Comment by thomasbachem** [comment]
Experienced the same issue.
