### ISSUE TITLE
In debug mode, add comments to display placeholder selectors in CSS

### ISSUE THREAD

**Issue by alice-liu** [sass/sass#1012]
Not sure if this is a feature request already, but I think it would be very helpful to still see the placeholder selectors in CSS via comments. It's possible to output them dynamically via @mixins, but because they're silent, it may be harder to tell what selectors are available for use. This would become an issue when using code written by others and debugging.

**Comment by ghost** [comment]
+1 That is much needed

**Comment by nex3** [comment]
I don't think this is something we want to support in Sass itself. We don't have a notion of "debug" mode, and adding an option just for this would carry a cost. I think it's the job of a documentation generator to make it clear what placeholders are available to extend, not the compiled output.
