### ISSUE TITLE
I'd like to add HSB/HSV Color function

### ISSUE THREAD

**Issue by sja** [sass/sass#1014]
I'd like to see a hsb() function to create colors directly from the values I can read from Adobe Products like Photoshop.
Currently, only hsl() is available which is more web-native.

Should I support a pull request or do you already planned sucha function?

An Implementation I'd like to port is from java.awt.Color#HSBtoRGB.

**Comment by lolmaus** [comment]
You should create a Compass exension: http://compass-style.org/help/tutorials/extensions/

It will allow you to extend Sass with almost unlimited functionality.

You can use this template: https://github.com/Team-Sass/Compass-Extension-Template

**Comment by Snugug** [comment]
@lolmaus the answer to every feature request is not "create a Compass extension" or "why bother there's a Compass extension".

I, for one, think this would get quite a bit of traction with designers as it's not just Adobe products that have HSB as a primary color mode; a lot of the color scheming products I use outside of Adobe do as well.

**Comment by cimmanon** [comment]
@Snugug Why not?  Maybe new features _should_ be an extension first.  Then, if the feature is popular enough, it can become a core feature of Compass, then a core feature of Sass.

I'm not saying no, but I don't see how HSB is any better than any other format provided by Adobe products.  The last several versions have a single field containing the hex value, which seams more convenient to me than trying to copy from 3 individual fields.

![color-picker](https://f.cloud.github.com/assets/2333706/1541679/86b398f6-4d3b-11e3-9a9c-02aca09e0799.jpg)

**Comment by sja** [comment]
@cimmanon You're right, hex colors are more handy at first look, but If you implement a given design, the colors become more comparable and searchable in both directions. For example I have something like this:

``` scss
$orange: #f80;
$darkOrange: #994c00;
$lightOrange: #ff9500;
```

Then, for me it's not obvious, what the difference of them are.

``` scss
$orange:      hsl(32deg, 100%, 50%);
$darkOrange:  hsl(30deg, 100%, 30%);
$lightOrange: hsl(35deg, 100%, 50%);
```

This is much more readable and calculatable width `$lightOrange: adjust-hue($orange, 3deg);`

But at the moment I have to use e.g. colorzilla.org to convert them to hsl. And if I try to compare the colors from a PSD and my SASS Code I always have to translate myself.

**Comment by nex3** [comment]
I agree with @cimmanon in that I like the idea of making this sort of thing an extension and upgrading from there.

**Comment by voxpelli** [comment]
For reference, here's a pure-SASS script that implements the requested functionality: https://gist.github.com/voxpelli/1069204
