### ISSUE TITLE
Interpolation error with parent reference &

### ISSUE THREAD

**Issue by aledoroshenko** [sass/sass#1016]
So I take a code from #1004 to try it out:

```
.fieldset {
  background: red;
  #{&}-field {
    background: blue;
    #{&}-label {
      background: green;
    }
  }
}
```

And it thows error: `Syntax error: Invalid CSS after "  #{": expected expression (e.g. 1px, bold), was "&}"`

Where should i look at?

**Comment by lolmaus** [comment]
You need Sass 3.3.

**Comment by aledoroshenko** [comment]
Got it, thanks.
