### ISSUE TITLE
wrong css produced when minus sign used with variable

### ISSUE THREAD

**Issue by maxgalbu** [sass/sass#1017]
```
$footerheight: 35px;
margin: 0 auto -$footerheight;
```

gets compiled to

```
margin: 0 auto-35px;
```

while if I use directly

```
margin: 0 auto -35px;
```

it gets compiled correctly

(I'm trying to use <a href="http://ryanfait.com/sticky-footer/">css sticky footer</a>)

**Comment by Anahkiasen** [comment]
You can do this in the meantime `margin: 0 auto (-$footerheight);`, that works.

I can confirm bug on latest Sass : http://sassmeister.com/gist/7551941

**Comment by KittyGiraudel** [comment]
Workaround available here: https://github.com/nex3/sass/issues/1023.

**Comment by nex3** [comment]
This is expected; see #1023.
