### ISSUE TITLE
sass-convert needs options for syntax operators

### ISSUE THREAD

**Issue by joshdcomp** [sass/sass#1018]
I'm aware this has been submitted as a bug before, [both when this was haml](https://groups.google.com/forum/#!topic/haml/oDUlRItONQs) and [after it was branched off](https://github.com/nex3/sass/issues/409) but I feel it's warranted enough to bring up again:

There should be options in the `sass-convert` cli to include syntax operators such as brackets, closing comments, and semicolons. 

Given that the primary use case that I can imagine for using `sass-convert` is to reverse engineer legacy styles to be folded into a new framework, not including options for these syntax operators essentially renders all reverse-engineered styling incompatible with any library that doesn't follow this flavor of writing sass. 

While I understand that it is valid sass to omit these syntax operators, that doesn't necessarily mean that everyone does or should write sass the same way. I personally find it annoying to rely solely on whitespace for my code, and find it harder to read sass wihtout brackets—with or without syntax highlighting.

Such opinionated approaches to tools are annoying and inflexible to use.

And while it doesn't seem to be a valid point to certain contributors, I do think it is worth noting that almost all syntax highlighting tools that I can find either take a huge performance hit or fail to properly highlight this bespoke syntax outright.

**Comment by nex3** [comment]
I'm not sure what you're requesting. What is a "syntax operator"? Can you give an example of the output you're getting versus the output you want?

**Comment by lolmaus** [comment]
Basically he wants `sass-convert` to have an option to explicitly close block comments in the `.sass` format.

**Comment by joshdcomp** [comment]
More than that—I want options that would have output similar to this: http://css2sass.heroku.com/

Sorry if I'm using incorrect wording, but when I say syntax operators in this case, I'm specifically speaking about closing comments, including semicolons at the end of declarations, and closing curly braces for style blocks. 

So for an example, I would have this css:

```
/* COMMENT ABOUT BANNER WRAPPERS */
.banner_wrapper {
    float: right;
    clear: right;
    position: relative;
}

    .banner_wrapper #banner {
        display: block;
        clear: both;
        float: none;
        width: 300px;
        height: 110px;
    }

        .banner_wrapper #banner a {
            display: block;
            padding: 30px 0px 0px;
        }
```

And the output would be something like this:

```
/* COMMENT ABOUT BANNER WRAPPERS */
.banner_wrapper {
    float: right;
    clear: right;
    position: relative;

    #banner {
        display: block;
        clear: both;
        float: none;
        width: 300px;
        height: 110px;

        a {
            display: block;
            padding: 30px 0px 0px;
        }
    }
}
```

**Comment by lolmaus** [comment]
Are you kidding?

```
sass-convert -F css -T scss test.css test.scss
```

**Comment by nex3** [comment]
The css2sass app is actually implemented in terms of `sass-convert`. I'm going to close this, since it looks like what you want already exists :smiley:.
