### ISSUE TITLE
[feature] recursive map merge

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1021]
New features in 3.3 are a godsend for framework developers like myself, however one pain point I've experience with the current maps implementation is merging nested maps.

```
$map1: (
    foo: bar,
    bar: ( baz: 1px ));

$map2: (
    baz: 3px,
    bar: ( bam: 2px ));

$map3: map-merge($map1, $map2);

@debug($map3);

// The current behaviour (formatted)
(
    foo: bar,
    baz: 3px,
    bar: ( bam: 2px )
)

// Proposed output
(
    foo: bar,
    baz: 3px,
    bar: ( 
        baz: 1px, bam: 2px 
    )
)
```

Currently the only way to do this is
- `map-get` `bar` from both maps
- `map-merge` them
- `map-merge` `bar` back into `$map1`

I'm aware this can be done relatively easily in sass land (https://github.com/asimov/asimov-core/blob/master/src/scss/asimov/_core.scss#L300). However in my experience the cost of iteration in sass-land can really add up (related to #1019), which may also hold true for recursion. Ideally we could offload these types of expensive operations on to ruby-land.

**Comment by timelf123** [comment]
:+1:

**Comment by nex3** [comment]
I don't think this is widely useful enough to warrant inclusion in the core libraries. I definitely don't want to move functions into the core implementation just for performance -- the core library exists as a set of functions that are widely applicable and/or primitives for working with Sass's data types, not as a set of functions that would be slow in pure Sass.

**Comment by sapzxc** [comment]
:(
