### ISSUE TITLE
"margin: 0 auto -($footer-height + 1) 0;" => "margin: 0 auto-31px 0;"

### ISSUE THREAD

**Issue by christiannelson** [sass/sass#1023]
Given `$footer-height: 30px`, the result does not include a whitespace between auto and -31px as expected.

For reference, the docs state:

> By default, if two values are placed next to one another, they are concatenated with a space:
> 
> p {
>   margin: 3px + 4px auto;
> }
> 
> is compiled to:
> 
> p {
>   margin: 7px auto;
> }

**Comment by KittyGiraudel** [comment]
As a workaround:

```
margin: 0 auto ($footer-height + 1) * -1 0;
```

**Comment by nex3** [comment]
This is expected. Sass doesn't use whitespace to determine whether to consider an operation unary or not, and `-` has higher precedence than ` `, so your property value is actually parsed like`0 (auto - ($footer-height + 1)) 0`.

You can use @HugoGiraudel's workaround or write `0 auto (-($footer-height + 1)) 0`.
