### ISSUE TITLE
Custom @directive or custom pseudo class (like :parent, :clicked, etc)?

### ISSUE THREAD

**Issue by gavinengel** [sass/sass#1024]
Are there any plans to implement custom directives, without having to pull in an extra ruby gem?  I'd like to be able to write a mixin that, for example, is able to be aware of it's parent element.  I don't believe mixins are able to do that..

I'd like to be able to include the directive declaration/pseudo class declaration in a partial scss file.

I do remember reading that the Sass team doesn't want to fragment the language though, so perhaps allowing easy directives/pseudo classes would make things difficult to keep tabs on?

**Comment by nex3** [comment]
I'm not sure what you have in mind for the semantics of these custom directives. SassScript itself isn't a particularly expressive language; it's certainly not powerful enough to give you the ability to define complex semantics for rules or parent selectors.

For your specific question about "being aware of the parent element", check out the [SassScript parent selector](https://github.com/nex3/sass/blob/master/doc-src/SASS_REFERENCE.md#-in-sassscript-parent-script) that's coming in Sass 3.3.

**tl;dr**: no.
