### ISSUE TITLE
Warning if a Sass function overrides a spec CSS function

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#1025]
Recently I've run into situations where a Sass function was overriding a CSS function, preventing the authoring of standard CSS (once with [Bourbon](https://github.com/thoughtbot/bourbon/issues/177) and once accidentally with a `scale()` function used in our team).

Sass as a whole seems to reject the idea of re-assigning spec CSS to Sass functions or mixins (see the discussions on "transparent" mixins). I agree — Sass should never prevent you from writing spec CSS, or secretly transform your spec CSS.

What do people think about reserving spec CSS function names, throw a warning in upcoming versions of Sass, and eventually make overwriting spec CSS functions an error?

**Comment by cimmanon** [comment]
I see where you're coming from, but overwriting the functions can be an advantage _or_ a disadvantage.  Compass overwrites the linear-gradient and radial-gradient functions to make prefixing easier while making writing the `@background` mixin's arguments look like natural CSS.
- http://compass-style.org/examples/compass/css3/gradient/
- https://github.com/chriseppstein/compass/blob/9ee6b422262668e8a7e154d2ac34f350ee331dc0/lib/compass/sass_extensions/functions/gradient_support.rb

**Comment by robwierzbowski** [comment]
Exactly. I think they shouldn't do that. 

I don't want any Sass library hijacking my spec CSS and returning an unexpected value. Compass is less of a problem because it defines a custom Ruby function that returns valid CSS (even if it's changes are superfluous and re-processed with Autoprefixer), but Bourbon defines a Sass function that returns invalid CSS. In Compass's case it's a benefit to users that choose to take advantage of Compass's prefixing mixins, but many of us have moved on to prefixing with Autoprefixer and only use Compass for the framework/plugin architecture.

IMO it would be an improvement to developer experience and community code quality to warn developers if they are authoring code that could cause their CSS to break, and kindly push library authors away from overwriting spec CSS functions.

**Comment by cimmanon** [comment]
It sounds like your problem is more with Bourbon than with Sass.  My recommendation would be to take your complaint to them or choose a library that doesn't generate invalid CSS.

**Comment by robwierzbowski** [comment]
Already PR'd Bourbon. My suggestion for Sass still stands.

**Comment by nex3** [comment]
I really don't like the idea of Sass having a list of known CSS functions. That list will inevitably get out-of-sync with the real world, eroding user confidence in its correctness and by extension Sass's correctness as a whole.

That said, in this specific instance, I could potentially see it working, since the list would only be used for emitting warnings and there will only be false negatives, not false positives (assuming CSS never removes an existing function). I would want to make this remain a warning, though; I don't want a list of supported CSS names affecting the behavior of Sass in a non-advisory way. @chriseppstein, what do you think?

**Comment by robwierzbowski** [comment]
I do love Sass's `hsla()` and `rgb()` functions, which specifically override an existing CSS function in a beneficial, non-destructive fashion. Maybe it's up to the Sass author and the library consumer to take care that they're acting responsibly.

I might have posted this issue when I was a little perturbed at my CSS being chomped.

**Comment by chriseppstein** [comment]
As @robwierzbowski noted. There are good uses for overriding a spec function.
