### ISSUE TITLE
SASS force update

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#103]
SASS does not generate a new CSS file when the source files did not change. It can be handy to force the generation of a file to switch between a compressed production version and a development version with line comments. Currently SASS does not generate the file, if you just switch command line arguments.

I propose a command line argument 'force' that ensures that the file gets generated.

[Originally filed](https://github.com/nex3/haml/issues/375) against haml by @thomaspeklak

**Comment by mikebranderhorst** [comment]
would be a nice feature

**Comment by chriseppstein** [comment]
Duplicate of #62 which is already fixed.
