### ISSUE TITLE
!global breaks backwards compatibility with sass 3.2

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1034]
Sass 3.3 introduces the `!global` flag for modifying globals. Leaving this flag out emits a deprecation warning like below

> Assigning to global variable "$modules" by default is deprecated.
> In future versions of Sass, this will create a new local variable.
> If you want to assign to the global variable, use "$modules: append($modules, $name) !global" instead.

However adding the `!global` emits an error in sass 3.2. This is essentially a BC break since authors can't write code that'll compile in 3.2 and not emit deprecation warnings in 3.3.

I briefly mentioned this with @chriseppstein [on twitter](https://twitter.com/xzyfer/status/408828453031407616)

**Comment by nex3** [comment]
> This is essentially a BC break since authors can't write code that'll compile in 3.2 and not emit deprecation warnings in 3.3.

That's not what backwards compatibility means. Our current compatibility guarantee is that styles that work without deprecation warnings in version `3.X` will work in `3.(X + 1)`. That doesn't preclude it working with warnings in `3.(X + 1)`. This allows us to balance quick feature iteration with not breaking existing users.

If we added support for `!global` to 3.2, there would be Sass stylesheets that work in 3.2.13 that broke in 3.2.12, which is unacceptable -- patch releases are for bug fixes and non-language level improvements. If we waited a full major version cycle to introduce deprecation warnings, it would take prohibitively long to fully migrate users to the new behavior.

It's always going to be the case that targeting a new minor version will produce code that's incompatible with the old one -- you'll run into the same issue when using maps.

**Comment by xzyfer** [comment]
I'd like to clarify.

The BC break will be from Sass 3.2 and Sass.next (3.4 or 4.0..). My rationale is that there is a lot of Sass code currently in the wild that relies on globals. All of that code will deprecation warnings in Sass 3.3 which I agree is the price of moving forward. However all that code will fail to compile (I presume) in Sass.next.

Since Sass 3.2 doesn't have the variable scoping that 3.3 has it makes writing some kinds of libraries that work in both 3.2 and .next impossible eg https://github.com/wilsonpage/sass-import-once/blob/master/_sass-import-once.scss. Correct me if I'm wrong.

I don't believe @chriseppstein was suggesting support for `!global` be added to 3.2, but instead patching 3.2 to ignore `!global` rather than causing a parse error.

**Comment by cimmanon** [comment]
No amount of patching 3.2 is going to help people who already have 3.2.  No logical person is going to think of upgrading to a version that suppresses errors, assuming they even understand why they are getting errors in the first place.  I don't see how this differs from any other new feature Sass has added in the past (`@extend`, etc.).

Compass extensions have a way of specifying minimum versions of Sass or other dependencies in their gemspec:

``` ruby
  # Gems Dependencies
  s.add_dependency("sass",      [">=3.2.0"])
  s.add_dependency("compass",   [">= 0.12.1"])
```

**Comment by nex3** [comment]
> The BC break will be from Sass 3.2 and Sass.next (3.4 or 4.0..)

This is standard for Sass. We don't guarantee cross-version compatibility between more than one minor release.

> Since Sass 3.2 doesn't have the variable scoping that 3.3 has it makes writing some kinds of libraries that work in both 3.2 and .next impossible eg https://github.com/wilsonpage/sass-import-once/blob/master/_sass-import-once.scss. Correct me if I'm wrong.

That's correct. We don't intend there to be compatibility in either direction between 3.2 and the version after 3.3 (likely 4.0).
