### ISSUE TITLE
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by lucascaton** [sass/sass#1037]
I'm trying to start the compass server (`grunt compass:server`), but I got the following error:

`Encoding::UndefinedConversionError on line ["655"] of ~/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.2.12/lib/sass/util.rb: "\xE2" from ASCII-8BIT to UTF-8.`
- ruby-2.0.0-p353
- sass 3.2.12
- grunt v0.4.2

Any idea how to fix this?

**Comment by nex3** [comment]
It looks like your operating system's encoding may be set incorrectly. Can you provide:
- your operating system
- the result of running `ruby -e 'p Encoding.default_external'`
- the contents of the Sass file you're trying to compile

**Comment by lucascaton** [comment]
- my operating system:
  Mac OSX 10.9 (Mavericks)
- ruby -e 'p Encoding.default_external':
  `#<Encoding:ASCII-8BIT>`
- the contents of the Sass file you're trying to compile:
  When the file contains either nothing or whatever, the problem still happens!

**Comment by nex3** [comment]
Does it still happen if you create a file using `touch file.scss` and then run `sass file.scss`?

The fact that your system encoding is set to ASCII is part of the problem. I'm not sure how to set it on OS X, but you probably want it to be UTF-8 instead.

I'm concerned that this is producing an error even on an empty file, though. It's possible your grunt task is eagerly loading Compass files, but I believe all of those have proper `@charset` annotations that Sass should respect.

**Comment by lucascaton** [comment]
I created another user in my computer and it works now.
Probably was something related to the system encoding for that user.

I needed to fix this, sorry for not to be able to reproduce this anymore.
Thanks anyway.

**Comment by lucascaton** [comment]
It happened again.

But now I know how to fix it!
So I'm posting here just to help anyone who have the same error.

**Solution:**

Remove the line below from your `.bash_profile` (or similar):

`export LC_CTYPE=utf-8`

**Comment by chriseppstein** [comment]
@lucascaton thanks for the follow up.

**Comment by wangyazhen** [comment]
I can't find .bash_profile or similar file  .
I use the windows.
Encoding::UndefinedConversionError on line ["655"] of C: "\xAE\xE8" from GBK to UTF-8
What should I do?

**Comment by hamedqaderi** [comment]
@wangyazhen I'm using the windows too and I have the same problem. 
Maybe it's time to buy a Macbook :)

**Comment by numediaweb** [comment]
Got this bug too and went on a hunt to see what causes it! I found out that I have a comment in one of my scss files reading;
`// some bla bla.. in the user’s blabla.`
You see that `’` apostrophe; Its the source of my bug! removed it and didn't got anymore the not-so-clear `UndefinedConversionError` error.. don't know why compass doesn't accept such chars..

**Comment by hamedqaderi** [comment]
I don't know ruby but in Sass you can use:
sass -E utf-8
when you are running it from command line

**Comment by nex3** [comment]
These errors are definitely not as good as they should be. Can someone who's seeing one post:
- Their OS version
- Their Ruby version (`ruby --version`)
- Their Sass version (`sass --version`)
- The result of running sass with `--trace` on a file that produces the error
- The result of running `ruby -e 'p [Encoding.default_internal, Encoding.default_external]'`

**Comment by munawar-js** [comment]
Here are the results of the test you asked. Thanks in advance

![screen shot 2014-08-18 at 5 21 06 am](https://cloud.githubusercontent.com/assets/6573105/3946285/b1fd5da0-2669-11e4-9cb2-3934460e3cec.png)

##### Result of running sass with --trace

```
Encoding::UndefinedConversionError on line ["655"] of /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/util.rb: "\xE2" from ASCII-8BIT to UTF-8
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/util.rb:655:in `check_sass_encoding'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/engine.rb:372:in `check_encoding!'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/engine.rb:339:in `_to_tree'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/engine.rb:274:in `to_tree'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:225:in `visit_import'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `map'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:139:in `block (2 levels) in compile'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:138:in `block in compile'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/logger.rb:45:in `red'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:137:in `compile'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:118:in `compile_if_required'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:103:in `block (2 levels) in run'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `each'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `block in run'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/compiler.rb:100:in `run'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/commands/update_project.rb:45:in `perform'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/commands/base.rb:18:in `execute'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/bin/compass:30:in `block in <top (required)>'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/bin/compass:44:in `call'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/compass-0.12.7/bin/compass:44:in `<top (required)>'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/bin/compass:19:in `load'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/bin/compass:19:in `<main>'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
  /Users/user/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
```

##### Result of running `ruby -e 'p [Encoding.default_internal, Encoding.default_external]'`

`[nil, #<Encoding:ASCII-8BIT>]`

**Comment by nex3** [comment]
@munawarahmed You're using Sass 3.2, which is pretty old at this point. Can anyone reproduce this using Sass 3.3 or 3.4?

**Comment by munawar-js** [comment]
Hi @nex3,
i have tried both 3.3 and 3.4

Sass 3.3.14 is still giving me 
`Encoding::UndefinedConversionError on line ["833"] of /Users/user/.rvm/gems/ruby-1.9.3-p547/gems/sass-3.3.14/lib/sass/util.rb: "\xE2" from ASCII-8BIT to UTF-8`

but with Sass 3.4.0.rc.1, Everything works just fine. Thanks you

**Comment by nex3** [comment]
Has anyone seen this on 3.4?
