### ISSUE TITLE
bug in media queries?

### ISSUE THREAD

**Issue by jcayzac** [sass/sass#1041]
So I must miss something from the docs, because something as simple as `@media not(print)` doesn't work in my .scss (it gives `Syntax error: Invalid CSS after "@media not": expected "{", was "(print) {"`).

If I change to `@media (not print)`, then it compiles without error, but to `@media (false)`.

What am I missing?

Sass 3.2.12, using SCSS syntax. Media queries are not nested inside rules.

**Comment by jcayzac** [comment]
`@media not print` works as expected. Still, the other ones are just as valid CSS.

**Comment by Snugug** [comment]
Assuming I can read the syntax section of http://www.w3.org/TR/css3-mediaqueries/ correctly, the only syntactically correct example you've given is `@media not print`. The others are, in fact, invalid

**Comment by Snugug** [comment]
[Direct link to syntax](http://www.w3.org/TR/css3-mediaqueries/#syntax)

Specifically note that only media features should be placed inside parenthesis, not media types or ONLY/NOT

**Comment by jcayzac** [comment]
@Snugug thanks for blasting the dust I had stuck in my eyes for all these years :+1:
