### ISSUE TITLE
valid media query reported as error

### ISSUE THREAD

**Issue by alastc** [sass/sass#1043]
Running Sass on an imported file that includes this line:

```
@media screen {
```

Sass reports:
    error media-queries.sass (Line 8: Invalid CSS after "screen ": expected media query list,  was "{")

I'm pretty sure that's valid though, you don't have to include size or other terms, like the second example here: http://www.w3.org/TR/css3-mediaqueries/

**Comment by Snugug** [comment]
I'm not sure what version of Sass you're running, but using both Sass 3.2.12 and Sass 3.3.rc.2, the following compiles absolutely fine:

``` scss
@media screen {
  .foo {
    content: bar;
  }
}
```

**Comment by alastc** [comment]
3.2.12, but perhaps it makes a difference that it is in an import? I moved my media queres into another file (media-queries.sass) and imported that into the main file. Then I get the errors.

I took the error message too literally though, it doesn't matter whether there are 'and' conditions, it seems to matter they are in an import though.

**Comment by Snugug** [comment]
Having them in an imported file should not make a difference and does not make a difference when tested. My suggestion is to build a reduced example and add back in code until you find your error; I'm willing to bet you have a syntax error somewhere, not that `@media screen` doesn't work.

**Comment by nex3** [comment]
I'm closing this, but I'll re-open if you can provide a file or files that can consistently reproduce the error.

**Comment by alastc** [comment]
Has the nature of 'watch' changed when I wasn't looking? A sass file of just this:

```
body {
    margin: 0;
}
```

Then:
    # sass --watch test.sass:test.css

Gives me:

   error test.sass (Line 2: Invalid CSS after "0": expected expression (e.g. 1px, bold), was ";")

Is there a forum somewhere? This is really odd, it is CSS that's working fine in the full SASS stylesheet. Need somewhere to ask questions...

**Comment by nex3** [comment]
That's SCSS syntax, but your file uses the extension `.sass`, so Sass is trying to interpret it as the indented syntax and failing. Could that also be your problem with the media query?

**Comment by alastc** [comment]
Ah, yes, that's why everything seems to be wrong when I import that. 

Sorry, I have never used the indented syntax, so I have no idea why I put .sass on that!
