### ISSUE TITLE
Single quotes in SCSS

### ISSUE THREAD

**Issue by costa** [sass/sass#1048]
SCSS seems to have problem with `*-url('....')` — changing to double quotes solves the issue. SASS works as expected, however.

**Comment by nex3** [comment]
Please be more specific. Provide a full SCSS file that shows the error, the output you expect, and the output you're getting.

**Comment by BrodaNoel** [comment]
In another hand, is not recommended wrap the URL with quotes in url() function, because Safari have (yet?) a bug with that.

**Comment by nex3** [comment]
a6f6bf50bc30582c936db437b6ebcd462b20a779 has probably fixed this.

**Comment by costa** [comment]
(after a thorough check) I'm sorry to say, my report was insubstantial.

**Comment by chriseppstein** [comment]
@costa what do you mean?

**Comment by costa** [comment]
@chriseppstein there's been no problem with single quotes :)
