### ISSUE TITLE
Allow variables defined within @if to be accessible outside

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#105]
[Originally filed](https://github.com/nex3/haml/issues/242) against haml by @nex3.

E.g.

```
@if lightness($backgroundColor) < 50% {
  $iconImage:url("#{$imagePath}/icons-light.png");
} @else {
  $iconImage:url("#{$imagePath}/icons-dark.png");
}
```

`$iconImage` should be accessible after running this statement.

**Comment by nex3** [comment]
I haven't heard anyone clamoring for this, so I'm going to close it.
