### ISSUE TITLE
Shorthand colors sometimes become longhand

### ISSUE THREAD

**Issue by Ugoku** [sass/sass#1053]
I've been experimenting with SCSS for the first time today and ran into this (extremely minor) issue.
Consider the following two lines:

```
background: #eee;
box-shadow: 0 ($containersize - $lineheight) #eee;
```

Upon transpiling to CSS, it becomes this:

```
background: #eee;
box-shadow: 0 3.5em #eeeeee;
```

So the shorthand color at box-shadow becomes the longhand notation (#eeeeee instead of #eee). When I remove the math from the equation, the color remains #eee as I would expect.
FWIW, I'm using the latest version of Ruby (2.0.0-p353 x64) on Windows 8 x64.

**Comment by lolmaus** [comment]
I'm sure there's at least one relevant issue ticket, please try to search.

Anyway, why is this a concern for you? In the compressed mode all color codes are trimmed to three digits if possible.

**Comment by Ugoku** [comment]
If there is, it does not mention "shorthand", I searched for that.
As I said, it's an extremely minor issue, but one that seemed strange and I ran into on my first day.

I didn't know there was a compressed mode, thanks for that! :)

**Comment by lolmaus** [comment]
It's not that strange. It seems that when Sass processes colors, it turns them into a universal format. E. g. `#fff` → `#ffffff`, `white` → `#ffffff`.

**Comment by nex3** [comment]
Duplicate of #363.
