### ISSUE TITLE
Iterating over null is possible and potentially confusing

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1054]
This is open to interpretation but since IMHO it violated the principal of least surprise I wanted to open the discussion.

Looping over the result of a function that may return `null`, like `map-get`, iterates once. I would have expected it to not iterate at all. 

**From the map-get docs**

> @return [Sass::Script::Value::Base] The value indexed by `$key`, or `null` if the map doesn't contain the given key

```
$map: (
  colors: (
    primary: red,
    secondary: blue,
  ),
);

// button-colors doesn't exist in $map
@each $k, $v in map-get($map, button-colors) {
  .button--#{$k} {
    display: inline-block;
    background-color: $v;
  }
}

// outputs

.button-- { 
  display: inline-block;
}

// expected no output
```

I suspect it's a result of sass' "everything is a list of length 1" rule. 
I understand this can be worked around by explicitly checking the return value of `return-list-or-null` before looping.

**edit** updated the example to be less trivial.

**Comment by xzyfer** [comment]
For anyone else who comes across this issue, at the time the writing a clean work around is as follows

```
@each $k, $v in map-get($map, button-colors) or () {
  .button--#{$k} {
    display: inline-block;
    background-color: $v;
  }
}
```

This works since `()` is respected as an empty list/map in sass 3.3

**Comment by andrewk** [comment]
+1 for highly unexpected behaviour. `each` of `[]` should be zero iterations.

**Comment by nex3** [comment]
`null` isn't the same thing as the empty list. We have empty lists to represent empty lists.

My ideal behavior here would be for `@each` to throw an error, but unfortunately due to the nature of CSS lists we have to treat single values as singleton lists, which leads to this behavior inexorably.
