### ISSUE TITLE
Support &-suffix

### ISSUE THREAD

**Issue by nex3** [sass/sass#1055]
@chriseppstein and I have decided that, given that `@at-root #{&}-suffix` doesn't work as well as we'd hoped, it's worth the downsides to support `&-suffix` on its own.

This should throw an error if it generates an invalid selector. This error should be clear about how that selector was constructed from the source code.

**Comment by xzyfer** [comment]
Does this mean the `@at-root` directive is being dropped, or simply the need to use interpolation on `&` ?

**edit** already answered https://gist.github.com/nex3/8050187

**Comment by nex3** [comment]
`@at-root` will not be dropped, although support for `&` in a script context is being delayed until the next release.

See also https://gist.github.com/nex3/8050187.
