### ISSUE TITLE
Allow interpolation in static directives

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#106]
[Orginally filed](https://github.com/nex3/haml/issues/229) against haml by @nex3 and commented on by @endymion & @tbranyen.

This should work for `@media` and unrecognized selectors. It may also be worth allowing variables directly at some places in `@media`, although this may create confusion if they aren't allowed directly in other selectors.

**Comment by chriseppstein** [comment]
Patch for review:

https://github.com/chriseppstein/sass/commit/1af19978312e528c32e30e5b99a2175eab284665

**Comment by micha149** [comment]
What about this useful change?!

**Comment by torkiljohnsen** [comment]
+1

**Comment by nevir** [comment]
+1, found myself wanting this as well
