### ISSUE TITLE
Make SCSS output style from sass-convert configurable like CSS output

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#107]
I'd like to have an expanded and nested SCSS output like:

```
#main {
    #header {
        font: {
            size: 12px;
        };
    }
}
```

I hardcoded this behaviour in lib/sass/tree/node.rb of haml 3.0.13 for myself with:

```
--- node_3.0.13.rb  2010-07-01 15:31:02.321652147 +0200
+++ node.rb 2010-07-01 15:22:56.670401567 +0200
@@ -395,7 +395,7 @@ module Sass

         (fmt == :sass ? "\n" : " {\n") +
           children.map {|c| c.send("to_#{fmt}", tabs + 1, opts)}.join.rstrip +
-           (fmt == :sass ? "\n" : " }\n")
+           (fmt == :sass ? "\n" : "\n#{'  '  * tabs}}\n")
       end

      # Converts a selector to a Sass or SCSS string.
```

[Originally filed](https://github.com/nex3/haml/issues/205) by @topaxi and commented on by @nex3 and @graywh

**Comment by hlb** [comment]
It should be cool if we can also specify the size of tabs. `sass-covert -F scss -T scss` is really good to indent codes from others. https://gist.github.com/1122443

**Comment by mathiasschopmans** [comment]
I'd like this too.

SASS 3.1.10 - lib/sass/tree/visitors/convert.rb - line 21-27

```
def visit_children(parent)
  @tabs += 1
  return @format == :sass ? "\n" : " {}\n" if parent.children.empty?
  (@format == :sass ? "\n" : " {\n") + super.join.rstrip + (@format == :sass ? "\n" : "\n#{'  '  * (@tabs - 1)}}\n")
ensure
  @tabs -= 1
end
```

**Comment by jgarber** [comment]
I'd like this too.

**Comment by hlb** [comment]
I have made a pull request to add --indent option https://github.com/nex3/sass/pull/220

**Comment by sgalinski** [comment]
Thanks! Your code saved me quite some work right now. :-)

Just a small proposal for an extension: Can there be an option to add two newlines between each css rule? Currently the nested ones are written one after another with just a single newline if you migrate from css to scss.

Right now:

<pre>
main {
  foo {
  }
  bar {
  }
}
</pre>


Should be:

<pre>
main {
  foo {
  }

  bar {
  }
}
</pre>
