### ISSUE TITLE
content:"" in SASS

### ISSUE THREAD

**Issue by firedev** [sass/sass#1070]
The following code produces an error in SASS: `Invalid CSS after "content:": expected pseudoclass or pseudoelement, was """"`

```
    content:""
    display:table
    clear:both
```

while this doesn't:

```
    content: ""
    display:table
    clear:both
```

Not a big deal, but still. Works in SCSS. `sass-3.2.13`

**Comment by lolmaus** [comment]
In the indented syntax you should always use space after the colon.

For me `display:table` won't work as well as `content:""`. It's treated as a selector with a pseudoclass.

**Comment by firedev** [comment]
I see, thanks, yet only content:"" drops a warning.
