### ISSUE TITLE
Support Shadow DOM's new combinators

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1071]
Orignally filed by @ebidel on compass at: https://github.com/chriseppstein/compass/issues/1490

Shadow DOM's next Cat (^^) and Hat (^) selectors throw compiler errors. With it, one can write rules that penetrate the shadow boundary:

```
x-tabs ^^ h2 {
  ...
}

x-tabs ^ x-panel ^ h2 {
   ...
}
```

Reference:
https://github.com/html5rocks/www.html5rocks.com/blob/master/content/tutorials/webcomponents/shadowdom-201/en/index.md#the--and--combinators

**Comment by ebidel** [comment]
Here's a better reference: http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/#toc-style-cat-hat

**Comment by nex3** [comment]
Is there an actual spec for these?

**Comment by ebidel** [comment]
Not yet :(

http://w3c.github.io/webcomponents/spec/shadow/#styles
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23467

**Comment by ebidel** [comment]
`^` and `^^` have been renamed to `/shadow/` and `/shadow-deep/` in the [Shadow DOM styling spec](http://dev.w3.org/csswg/shadow-styling/#inheritance).

I can confirm that `/shadow/` and `/shadow-deep/` work correctly the minification. Close this.

**Comment by chriseppstein** [comment]
I think we should add some test cases involving these new selectors before we close this so that we can ensure they continue to work.

**Comment by chriseppstein** [comment]
It's also not clear to me that we understand these as combinators instead of selector components which may affect how we handle these identifiers in selector operations.

**Comment by ebidel** [comment]
Fair enough. Can you update the issue title?

**Comment by chriseppstein** [comment]
changed!

**Comment by zoechi** [comment]
once again https://github.com/Polymer/polymer/issues/458

:ancestor() -> :host-context()
/shadow-deep/ -> /deep/
/shadow/ -> ::shadow

I guess it would be helpful to still support the old ones for a few months.

**Comment by ebidel** [comment]
The old ones will never make it to a production browser. There's no reason
to support them.

**Comment by zoechi** [comment]
any plans to support the new combinators?

**Comment by nex3** [comment]
Is there any additional support that needs to happen here? I believe Sass handles all of the new selector syntaxes correctly.

**Comment by zoechi** [comment]
Thanks for the info. I postponed using SASS because this issue is still open. I'm new to SASS and it doesn't make sense to use it without shadowDOM support because I need it for a web components library.

**Comment by stevenbirr** [comment]
We are working on a DART project (https://www.dartlang.org/) and therefore we have to use Dartium as target browser in our development. Unfortunately, Dartium does not support <code>/deep/</code>, but <code>^^</code>.
So, if I want to test my SASS styles, I need to use <code>^^</code>, but the SASS compiler claims <code>Syntax error: Invalid CSS</code>.
Is it possible to use <code>^^</code> in SASS, maybe using any additional SASS or Ruby script? My idea was to write a RUBY parser that parses the generated CSS and changes all <code>/deep/</code> (that compiles correct) to <code>^^</code> _after_ the SCSS compillation. Any ideas?

**Comment by zoechi** [comment]
This was the reason why I thought it would be a good idea to support ^ and ^^ for a while.
You can take a look at this project https://github.com/donny-dont/Pixelate. As far as I know he uses a script to convert between `^^` and `/deep/` in combination with SASS.

**EDIT**  
it's here:
https://github.com/donny-dont/Pixelate-Flat/blob/master/bin/old_selector.rb

**Comment by Nevraeka** [comment]
+1 @stevenbirr . That is good to know. I don't code with Dart (yet) but a good amount of the Web Components community is using it. I guess the question should be is this a Dart problem or a SASS problem.

**Comment by Nevraeka** [comment]
@zoechi - Classic ruby monkey patching. lol. The good ole hammer :)

**Comment by stevenbirr** [comment]
I would rather say, it's a cross browser issue. I add <code>^^</code> in my CSS file and Dartium renders the Shadow DOM styles as I want. If I add <code>/deep/</code> in my CSS file, Dartium simply ignores it. So, the only thing I need is that the SASS compiler don't claim the <code>^^</code>operator. Then I could compile my SCSS to a CSS that Dartium can render.

**Comment by zoechi** [comment]
Dartium used for Dart development is always several weeks behind Chromium. So I would say it's a Dart problem.

**Comment by nex3** [comment]
I have it on good authority that a version of Dartium that supports the new spec will be released shortly, so I'm closing this.

**Comment by stevenbirr** [comment]
Ok, thank's. Nice to hear.

**Comment by KittyGiraudel** [comment]
I am not sure whether I should open a new issue or not, but new Shadow DOM syntax for `/deep/` does not work properly in everything-but-compressed mode:

``` scss
.foo >>> .bar {
  color: red;
}
```

Expected:

``` css
.foo >>> .bar {
  color: red;
}
```

Result:

``` css
.foo > > > .bar {
  color: red;
}
```

I don't know if the spaces between operators are relevant or not, but the [specs](http://dev.w3.org/csswg/css-scoping-1/#deep-combinator) mention `>>>` as a whole, so Sass should probably stick to this. Or at least print it as authored, rather than spacing them all.

Shall I open a new issue?

**Comment by lolmaus** [comment]
Looks like Sass treats it as multiple immediate descendant operators.

**Comment by KittyGiraudel** [comment]
That's what I figured, yes.

**Comment by nex3** [comment]
@HugoGiraudel can you open a new issue for that?

**Comment by KittyGiraudel** [comment]
Sure.

**Comment by aminnaggar-fuzzy** [comment]
https://github.com/sass/sass/issues/1619 link to the new issue
