### ISSUE TITLE
Re-add support for script &

### ISSUE THREAD

**Issue by nex3** [sass/sass#1078]
`&` support in SassScript will be removed from 3.3, so it should be re-added in the next release.

**Comment by nex3** [comment]
Done in e6f0edb67fd5de34916bc5d972625d9b2bd5dfe6.

**Comment by pdaoust** [comment]
Well I, for one, can't wait until Sass 3.4 starts coming down the tube! (I've been hanging on to Sass 3.3.rc1 just for script `&`.) Those selector manipulation functions are especially exciting; they look way nicer than the things I've cobbled together.
