### ISSUE TITLE
@extend-mixin directive

### ISSUE THREAD

**Issue by ariroseonline** [sass/sass#1081]
**Feature**:

An @extend-mixin directive would be really handy when working with SASS code that's been encapsulated into a ruby gem (or other modular code package). 

It's basically a way of reopening the @mixin definition later in your code. The word "Extend" in the definition _might_ be confusing (because of the other Sass @extend directive); however, this is really just the idea of extending a mixin later in your code, just as one can extend a CSS class with the @extend directive.

```
//TUCKED AWAY IN A GEM SOMEWHERE OR EARLY IN YOUR SASS CODE
@mixin container {
    //original rules
}

//THEN LATER ON IN YOUR SASS CODE
@extend-mixin container {
   //original rules remain there automatically
   //Now, I add additional rules
}

//OR IF YOU PREFER THIS DIRECTIVE NAME
@reopen-mixin container {
   //original rules remain there automatically
   //Now, I add additional rules
}
```

This would allow you to tailor some mixins for your application without having to create additional mixins that @include or @extend the original one. It seems wrong to have to namespace all of the mixins with mysite-originalmixinname when the functionality stays pretty much the same. I'm sure it would have many other uses as well when it comes to complex OO, modular client-side apps. 

**Background: How I Ran Into This Problem**
When I use Sass gems for Rails projects or any Sass modular plugin, I often need to adjust a @mixin definition from its default. However, the original @mixin definition is buried in the Gem code, that I shouldn't be touching (e.g. "@mixin container" from the Susy gem).

What I'm trying to do is to edit/update/reopen/add-to a @mixin definition _without_:

a) going into the guts of the gem and editing the mixin definition directly
b) forking the entire Gem's repo
c) creating my own idiosyncratic 'mysite-container' mixin that @includes or @extends the original container. I'd like to keep the same name as the mixin in the original repo, for maintenance and other reasons.

**Comment by Anahkiasen** [comment]
I'm not a fan of the syntax but I see your point have had to "overwrite" Compass or Susy mixins in the past so +1

**Comment by emagnier** [comment]
This is a good idea.
What about `@append-in` and `@prepend-in` (to insert code before the original rules)?

**Comment by ariroseonline** [comment]
@emagnier I really like @append-in. I'm trying to think of a use-case of @prepend-in. Can you think of one? Regardless, I think it's good to be explicit and complete in cases like these.

**Comment by ghost** [comment]
Interesting, sort of like [AOP](http://en.wikipedia.org/wiki/Aspect-oriented_programming) for Sass. This could simplify composition a lot. :+1:

**Comment by chriseppstein** [comment]
Our goal is to tackle this as part of #353. By importing a mixin from a module with a namespace, you'd be able to reference other mixins within your existing stylesheets without overwriting it.
