### ISSUE TITLE
version 3.3.0.rc.2: *.sassc: can't dump anonymous class

### ISSUE THREAD

**Issue by nyarly** [sass/sass#1093]
When rendering Sass under Rails, we get a ton of errors like this:

```
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/content.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/debug.sassc: can't dump anonymous class #<Class:0x00000003c48850>
WARNING on line 33 of /var/www/staging.rfx.com/releases/20140129190101/app/assets/stylesheets/partials/forms.sass:
This selector doesn't have any properties and will not be rendered.
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/forms.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/layout.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache b738d862ab441e3d60a508f7c4f246fd434fd6ed/constants.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/mizugumo.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/print.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/type.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache 69c617d5528a82dd6e80103bd32919213121b22e/utility.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache b738d862ab441e3d60a508f7c4f246fd434fd6ed/universal.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache b738d862ab441e3d60a508f7c4f246fd434fd6ed/screen.sassc: can't dump anonymous class #<Class:0x00000003c48850>
Warning. Error encountered while saving cache b738d862ab441e3d60a508f7c4f246fd434fd6ed/print.sassc: can't dump anonymous class #<Class:0x00000003c48850>
```

It's my understanding this is a regression: it was caused by a dynamically generated class making its way into an options hash.

**Comment by nex3** [comment]
I can't really do anything about this without being able to reproduce it. Can you provide a minimal rails app where this error occurs?

**Comment by nyarly** [comment]
It's not minimal, but https://github.com/TimePulse/TimePulse exhibits a small example of this: one entry for types.scssc

**Comment by nex3** [comment]
After a considerable amount of effort getting TimePulse up and running, I was unable to reproduce this.

In order to debug this further I'll need:
- A truly minimal rails app demonstrating the issue -- please don't make me track down which config files I need to edit to get it running.
- Full instructions for reproducing the issue, starting from downloading the app.
- The Gemfile.lock that produces the issue.
- The Ruby version on which the issue occurs.

**Comment by nyarly** [comment]
It might be easier if we can debug it here then. If we're able to find the
time to do that, do you want a PR with the result? Are the contribution
guidelines up to date?

On Fri, Jan 31, 2014 at 4:16 PM, Nathan Weizenbaum <notifications@github.com

**Comment by IdahoEv** [comment]
Something that has reproduced it for me in the past (on both TimePulse and other apps we're developing):  have the app running in development mode, load a couple pages, change something in a sass file, load more pages.  Pages after the change tend to take ~15 seconds to load and spew large numbers of errors like the ones above. 

However, I haven't had time yet to do a really accurate characterization, so the above should be considered an anecdotal report for now.  But I can confirm that we're seeing this issue a lot in multiple apps, and it's correlated with massive slowdown in development environment actions.

**Comment by nex3** [comment]
Changing the Sass file was the piece I was missing, thanks @IdahoEv.

It looks like this is the same issue as #1028. I'm going to close this one out; we can continue discussion there.

**Comment by metaskills** [comment]
I found out that the problem was this in my env file.

```
config.cache_store = :dalli_store
```

I know this is needed to help speed up compilation, but I can do without it for now till I found back and found out how to fix it proper.
