### ISSUE TITLE
sass cannot compile its own output

### ISSUE THREAD

**Issue by hbristow** [sass/sass#1097]
Example input, style.scss:

``` css
html, body {
  height: 100%;
}
```

Compile to CSS, then compile again to CSS

``` bash
# compile scss --> css, OK
sass style.scss style.css

# compile css --> css, ERROR!
sass style.css style.css
Syntax error: Invalid CSS after "100%": expected expression (e.g. 1px, bold), was "; }"
        on line 2 of common.css
  Use --trace for backtrace.
```

I think `sass` should be able to parse the output that it generates. I've also had issues reparsing the output of `sass-convert`.

**Comment by Anahkiasen** [comment]
I'm guessing it's because it's trying to parse Sass, not Scss, and is crashing on the `;`. That being said I don't really see why you'd ever want to do that.

**Comment by nex3** [comment]
@Anahkiasen is correct. When you pass a file to Sass on the command line, it tries to deduce whether it's SCSS or the indented syntax based on the file extension. If it can't, as in this case, it will assume it's the indented syntax, which is what's causing the parse error.

**Comment by hbristow** [comment]
okay thanks, I didn't realize it defaulted to the old syntax
