### ISSUE TITLE
saturating grayscale colors

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#11]
should be a no-op -- instead they get redder.

**Comment by nex3** [comment]
In order to do this, we would need `saturate` to have a special case for colors with 0 saturation. I don't think we should do this. It breaks `saturate(desaturate($color, $x), $x)`, and I think having a special case in otherwise easily predictable functions isn't a great idea.

**Comment by chriseppstein** [comment]
it doesn't have to break the saturate(desaturate()) chain because the hue can be preserved in the internal hsl representation.

it's easy to detect this special case and it results in a less surprising output than pink.

**Comment by nex3** [comment]
Every color has both an RGB and HSL representation. In order to preserve `saturate(desaturate)` and predictable behavior in general, increasing the saturation should always increase the S component of the HSL representation. By default, according to the RGB->HSL conversion defined in the CSS spec, a gray RGB color has red hue (arbitrarily). Thus, increasing the saturation will make it red.

In order to make the saturation increase not affect certain colors, we would have to do something like checking if the color has a cached HSL value. This is an implementation detail, and we shouldn't rely on it for visible behavior.

**Comment by thedarkone** [comment]
I'm with Nathan on this one, if you saturate something you should get more "color" (even if it is red).

**Comment by chriseppstein** [comment]
An rgb repesentation of a gray color has an indeterminate value for the hue -- there are an infinite number of hsl values that can appear to have this color gray. In an indeterminate case you can choose one of three behaviors:
1. Raise an error
2. Default the value arbitrarily and continue
3. Do nothing

So let's not get all absolutist here. This is about having a behavior with the least surprise for the users. It is not about the simplicity of the code.

I contend that a no-op is the least annoying behavior of the three, but I am open to a debate that discusses the merits of this from a user's perspective.

**Comment by thedarkone** [comment]
I do think that the current Sass implementation does the most correct thing in absolute terms.

However, Chris does have a point. We can abuse the (implementation) detail that Sass is aware whether the hue value has been manipulated with and ignore/defer saturation adjustments on grayscale RGB colors.

The implementation might get really ugly though, as I think code like this `adjust_hue(saturate(#9A9A9A, 100), 120)` should be equivalent to `saturate(adjust_hue(#9A9A9A, 120), 100)` and result into 100% saturated green in both cases.

**Comment by nex3** [comment]
It's not the case that a gray RGB color has an indeterminate hue value. On the contrary, it always has a hue value, because it always has a corresponding HSL color. Sometimes this value is arbitrarily set to red, but it's still there.

I'm not talking about simplicity of code, I'm talking about consistency of model. I want every RGB color to have a corresponding HSL color, and I want `saturate` to always increase the saturation of that color, full stop. This has nothing to do with how easy or difficult either way would be to implement, it has to do with behaving in a consistent way.

**Comment by chriseppstein** [comment]
this model is broken. it is confusing and surprising to our users and it needs to be rethought then because the last thing they expect from this "consistent" model is pink. full stop.

**Comment by thedarkone** [comment]
Yes, `saturate` is behaving absolutely correctly.

But consider this, let's say I have a `box` mixin:

```
=box($color)
  background-color: $color
  border: 1px solid darken(saturate($color, 10), 20)
```

Now I'm using this mixin with different colors for different themes and it works very well and handles almost any color the way I want it to. Unless I use it for a "gray" theme, then suddenly I get an unexpected slight red tint on the border.

Well yes, I should know better than to jam saturation on `#eee`, but it could also be argued that Sass could be clever enough to not let me shoot myself in the foot like that.

**Comment by davidkaneda** [comment]
Wow, didn't realize I was creating such a commotion (Chris input this request for me via Twitter) :)

thedarkone: Yes, your example is a great reason why saturate/desaturate should not affect a grayscale color. My situation is an extended version of that... I work on Sencha Touch, and all of our theming is based on SASS/Compass. We have lots of variables and mixins, but ultimately it is possible to change the entire theme from just a few global variables. Take, for example, our upcoming Apple and Android themes: 
- http://cl.ly/e028f476ffe3564542be
- http://cl.ly/59d19bb55b1864ab0ef8

And, for reference, here is what some of our SASS/Compass looks like:
- http://cl.ly/f9e4afaab4d2b184d5b0

Except, if we declare #555 for our default color (which would be great to do a metal theme, similar to iPad UI or jQuery Mobile), parts of the app look like this:

http://cl.ly/3d60c233a95c975d511d

Keep in mind, if they were to specify a green value, their app would simply look like:

http://cl.ly/3d3f4b468c5f5e691428

Personal taste aside, I think it's just not expected to the users. To get around it, I would have to abstract every place that uses saturate in my SCSS files (there are a lot more than just the variables file). And as the last part of my rant, I'll just say, saturating in Photoshop or Illustrator would never turn a gray to red.

**Comment by nex3** [comment]
I'll consider making Sass behave the same way as photoshop -- that is, making `saturate()` always a no-op on colors with 0 saturation. I'm unwilling to make it decide whether or not to saturate a color based on the history of that color object, though (in particular, whether the object has had HSL calculated already).

**Comment by davidkaneda** [comment]
Not totally sure what that means, but yeah, first part sounds great!

**Comment by nex3** [comment]
I think the best way to resolve this currently is for you to define a `saturate-maybe()` function:

```
@function saturate-maybe($color, $amount) {
  @return if(saturation($color) == 0, $color, saturate($color, $amount));
}
```

This returns a grayscale color when the input is grayscale, and otherwise behaves identically to `saturate()`.

**Comment by ghost** [comment]
Got any magic for ignoring desaturated colors when using saturation within `adjust-color()`?

**Comment by nex3** [comment]
``` scss
@function adjust-color-preserving-grayscale($color, $args...) {
  @if saturation($color) == 0 {
    @return grayscale(adjust-color($color, $args...));
  } @else {
    @return adjust-color($color, $args...);
  }
}
```

**Comment by ghost** [comment]
In order to get nex3's `saturate-maybe()` function to work, I had to change it like so:
```
@function saturate-maybe($color, $amount) {
  @return if(saturation($color) <= 0.01, $color, saturate($color, $amount));
}
```
