### ISSUE TITLE
:not(%placeholder) doesn't work

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#1100]
It outputs `:not(%placeholder)` as a string. I've tried wrapping in all manner of interpolation bits and pieces but no joy.

**Comment by KittyGiraudel** [comment]
I'd say this is intented because `:not()` is CSS while `%placeholder` is Sass. You can pass pretty much whatever you want in `:not()` so why not `"%placeholder"`?

**Comment by wheresrhys** [comment]
I take your point, but you can pass other sassy things into `:not()` http://sassmeister.com/gist/9034134 as long as they're wrapped in `#{}`, _and_ you can put `%placeholder` pretty much anywhere else you'd use a normal class so it does feel like inconsistent behaviour. Even if `:not(%placeholder)` is intended to be treated as a raw string I think  `:not(#{%placeholder})` should process `%placeholder` as sass.

**Comment by KittyGiraudel** [comment]
I may be wrong but the selector doesn't make any sense by itself. 

`A:not(.B)` means _target elements A which don't have class B_. Now, `A:not(%B)` means _target elements A which don't have placeholder B_ but placeholders simply do not exist (or mean anything whatsoever) when the `:not()` selector is being parsed by the browser.

Edit: my question to you would be: what are you expecting from `:not(%placeholder)`?

**Comment by Snugug** [comment]
I think the expected behavior is for %placeholder to be replaced with the class being extended, in which case it would make sense

**Comment by wheresrhys** [comment]
Maybe I'm wrong about this, but in my experience if `%B` is not extended then the entire selector isn't output so the case `A:not(%B)` where `%B` hasn't been extended should output no selector. 

When `%B` is extended I'd expect it to output a selector for each selector that extends it, similar to how placeholders work in general. This is simple for the case where `%B` is extended only once. 

But if `%B` is extended more than once by different selectors then I suppose this does raise the question of how to combine them - `A:not(.C):not(.D)` would probably be more use, and closer to the developer's expectations, than `A:not(.C), A:not(.D)`, but this is at odds with what extended placeholders normally output, though perhaps a justifiable one as an `or` turning into an `and` when negated fits in with how Boolean logic works.

**Comment by KittyGiraudel** [comment]
Fair point. Sorry for taking that long to understand.
