### ISSUE TITLE
sourcesContent option for --sourcemap

### ISSUE THREAD

**Issue by michaek** [sass/sass#1107]
We should have the option to include sourcesContent in generated sourcemaps, especially because the path to a source sass/scss file will often be inaccessible to dev tools.

A similar issue on libsass exists: https://github.com/hcatlin/libsass/issues/212

**Comment by nex3** [comment]
Does the `sourcesContent` property just literally contain the SCSS source?

**Comment by nex3** [comment]
I'm considering what the UI for this should be. It would be nice to have a mode that includes `sourcesContent` for importers that don't support public URIs, a mode that always includes `sourcesContent` regardless of the importer, and a mode that never includes `sourcesContent`. One possibility would be to add a tri-mode flag for this... something like `--sourcemap-inline={always/never/sometimes}` (I'm not a huge fan of the name `sourcemap-inline`; other suggestions would be appreciated).

There have also been requests to support `file:` URIs for sourcemaps, so we could have something like `--sourcemap={inline,file-uri,url}`. That makes it difficult to choose the behavior outlined above, though.

**Comment by nex3** [comment]
I'd like to do something for this for 3.4, but it's not critical that we do so.

**Comment by michaek** [comment]
Sorry to not respond to this yet! UglifyJS uses the flag `--source-map-include-sources`, which seems as reasonable to me as anything else. https://github.com/mishoo/UglifyJS2#usage If it's something you see as valuable, I'll take a look and see if I can submit a PR.
