### ISSUE TITLE
@at-root does not support reference (&) selectors in 3.3.0.rc.3

### ISSUE THREAD

**Issue by PythonNut** [sass/sass#1108]
Hello. I was using 3.3.0.rc.3 and I noticed a possible regression.

This code used to compile on rc2. Now it doesn't.

```
a {
  @extend %test;
  @at-root %test{
    &:hover{
      border: 0;
    }
  }
}
```

(This is a common use-case for me. I use this pattern to hoist redundant code out, so I can have an efficient compiled source while keeping the code near it's actual place in the tree.) Here's another failing snippet:

```
a {
  @at-root #test {
    border: 0;
    &:hover{
      display: none;
    }
  }
}
```

Is this expected? And, if so, what should I be doing instead?

**Comment by PythonNut** [comment]
Ah, I see that this is a side-effect of https://gist.github.com/nex3/8050187. Hoping it'll be fixed soon!

:)

**Comment by nex3** [comment]
The behavior you're seeing isn't expected. This is a valid bug.
