### ISSUE TITLE
Listen and compiling broken sass-3.3.0.rc.3

### ISSUE THREAD

**Issue by justinshea** [sass/sass#1110]
Hi,
I tried setting up source mapping today based on devTools documentation and youtube video from Chris Eppstein. However, when I try to set-up "watch" I get an error message:

```
sass --watch --style expanded AD-header.scss:AD-header-test.css
Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: undefined method `to' for Listen:Module
Use --trace for backtrace.
```

Running the trace:

```
C:\Users\Justin\Documents\My Dropbox\Work\AD Dev Projects\AD-header-refactor\css
>sass --watch --style expanded AD-header.scss:Ad-header-test.css --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/plugin/compiler.rb:
306:in `create_listener': undefined method `to' for Listen:Module (NoMethodError
)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/plugin
/compiler.rb:233:in `watch'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/plugin
.rb:108:in `method_missing'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/exec.r
b:509:in `watch_or_update'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/exec.r
b:346:in `process_result'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/exec.r
b:43:in `parse'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/lib/sass/exec.r
b:22:in `parse!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.3/bin/sass:13:in
`<top (required)>'
        from C:/Ruby193/bin/sass:23:in `load'
        from C:/Ruby193/bin/sass:23:in `<main>'
```

I am basically SOL right now b/c, in addition to not getting source mapping to work,  I can't even watch and ~~compile~~ files. (EDIT: It may be possible to compile scss to css manually using cmd but "--watch" is failing. In fact, the source map is created. But, without watch functionality it is impossible to create a workflow with source mapping + dev tools work spaces.)

I've followed all instructions for updating Ruby DevKit and updating Sass with --pre flag and I've hit a wall as far as troubleshooting goes. Is this an issue with latest version of SASS? Or, is it just my issue that I am il-equipped to solve on my own? At any rate, I very much appreciate someone reviewing this and giving feedback.

FWIW, it seems someone else has also run into the exact issue I am facing over the last 24 hours, http://stackoverflow.com/questions/21653036/listen-not-working-with-sass-3-3-0-rc-3-undfined-method

Cheers,
Justin

**Comment by justinshea** [comment]
UPDATE: I uninstalled SASS "3-3-0-rc-3" and re-installed "media mark". I can now watch files again but ~~obviously cannot create source maps~~ I cannot create source maps and so I can't use the dev tools work spaces feature..
FYI - I am on Windows7
Also, I never tried to manually compile files from command line with "3-3-0-rc-3" (stupid on me). I just know that "--watch" was throwing the error detailed above.
I have been dealing with this for a few hours so don't have the patience to reinstall ""3-3-0-rc-3" right now and see if I can manually compile. I will come back to this when I am refreshed sometime later in the week. -- no source mapping for now :-(
Any insight or fixes re: above is greatly appreicated..

**Comment by j15e** [comment]
+1 on OSX here

```
GEM
  remote: https://rubygems.org/
  specs:
    celluloid (0.15.2)
      timers (~> 1.1.0)
    ffi (1.9.3)
    listen (2.4.1)
      celluloid (>= 0.15.2)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.3)
      ffi (>= 0.5.0)
    sass (3.3.0.rc.3)
    timers (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  listen (>= 1.1.0, < 2.5.0)
  sass (>= 3.3.0alpha)
```

**Comment by kevinSuttle** [comment]
Same here.

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: undefined method `to' for Listen:Module
  Use --trace for backtrace.
```

**Comment by benseven** [comment]
Same here, though my error looked a little different... 

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
write css/core.css
write css/core.css.map
NameError: uninitialized constant Listen::Listener
Use --trace for backtrace.
```

Versions:

```
Sass 3.3.0.rc.3 (Maptastic Maple)
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

Rolling back to RC2 fixed it for me, back to all the sourcemappy, SCSS compiley goodness;

```
sudo gem uninstall sass
...
sudo gem install sass -v 3.3.0.rc.2
```

**Comment by nex3** [comment]
@justinshea @kevinSuttle @benseven can you all post the versions of `listen` you had installed when this was failing? Also, @justinshea, can you include your Ruby version?

**Comment by benseven** [comment]
```
listen (2.4.1, 1.1.6)
```

Really sorry, but I'm pretty new to Ruby Gems, and not sure how to tell which of these was being used at the time?

**Comment by nex3** [comment]
It would probably have tried to use the most recent one.

**Comment by j15e** [comment]
I have compare my Gemfile.lock with travis-ci master builds and it seems like identical, maybe this specific issue isn't covered in current specs?

**Comment by justinshea** [comment]
Hi - I have uninstalled beta version - let me know if I can help in another way

**Comment by airen** [comment]
I have encountered this problem , but now has not yet been resolved.

**Comment by kevinSuttle** [comment]
Hey @chriseppstein: 3.3.2-RC3 Majestic Maple I believe. I uninstalled and worked fine with the stable gem.

**Comment by gps03** [comment]
I am seeing the same error. It has persisted through an update to listen 2.5.0 this morning.
