### ISSUE TITLE
Documentation of percentage() wrong?

### ISSUE THREAD

**Issue by ronaldlokers** [sass/sass#1116]
The documentation of [percentage()](https://github.com/nex3/sass/blob/stable/lib/sass/script/functions.rb#L1192) states that $value needs to be a unitless number, but in the example there is a px value given.

**Comment by cimmanon** [comment]
The example there isn't wrong.  The division happens first:  `100px / 50px` is 2, which is then sent to the function.

**Comment by xiwcx** [comment]
The result of that equation is a unitless number as 50px fits in to 100px twice. Mismatched units will fail; if you play around in http://sassmeister.com you can see that `percentage(100px/50)` fails with an appropriate warning. Though I can see how this would cause confusion, so perhaps the documentation can be clarified.

**Comment by nex3** [comment]
I think the documentation provides a useful learning opportunity for how unit math works in Sass :).
