### ISSUE TITLE
Add selector-processing functions

### ISSUE THREAD

**Issue by nex3** [sass/sass#1117]
With the re-addition of script `&` (#1078), we want to expose a set of selector-processing functions to make it useful. A few off the top of my head:
- `selector-nest($parent, $child)` returns a selector of the form `$parent $child`. For example, `selector-nest((".foo", ".bar"), ".baz")` returns `".foo" ".baz", ".bar" ".baz"`.
- `selector-append($parent, $child)` returns a selector of the form `$parent$child`. For example, `selector-nest((".foo", ".bar"), ".baz")` returns `".foo.baz", ".bar.baz"`.
- `selector-parent($selector)` returns the `$selector` without the last child. So `selector-parent(".foo" ".bar" ".baz")` would return `".foo" ".bar"`, and `selector-parent((".foo" ".bar",  ".foo" ".baz"))` would return `".foo"`.

These functions should be liberal in their inputs; the user should be able to pass a valid selector string and have it parsed, even if it's not in the format provided by script `&`. The output would always be in the script `&` format.

If anyone has additional suggestions for useful selector functions, please post them here.

**Comment by jlong** [comment]
- selector-last($selector) returns the last part of the selector?

**Comment by nex3** [comment]
> `selector-last($selector)` returns the last part of the selector?

How does this handle a selector list? What does `selector-last(".foo, .bar .baz")` return?

**Comment by jlong** [comment]
@nex3 Maybe ".foo, .baz" ?

**Comment by nex3** [comment]
That's a reasonable answer. What's a use case for the function?

**Comment by jlong** [comment]
Off hand I can't think of a great one. The main desire is congruency: `selector-parent()` pulls stuff from one side of the selector and `selector-last()` from the other.

**Comment by nex3** [comment]
We could frame `selector-last()` as `selector-subjects()` instead to make it a little more semantic.

Another idea: `simple-selectors($selector)`, which returns a list of simple selectors in a compound selector. So `simple-selectors(".foo.bar.baz")` would return `".foo", ".bar", ".baz"`.

**Comment by nex3** [comment]
Also: `selector-extend($selector, $extendee, $extender)` which works like applying `$extender {@extend $extendee}` to `$selector`.

**Comment by nex3** [comment]
As an update, I've started work on this in the [selector-fns](/nex3/sass/branches/selector-fns) branch. I've implemented `selector-nest`, `selector-append`, `selector-extend`, and `simple-selectors` as discussed above. I've also implemented the new `selector-parse`, `selector-replace`, and `selector-unify` functions. For full documentation on these functions, see [the Sass functions documentation](https://github.com/nex3/sass/blob/selector-fns/lib/sass/script/functions.rb) under "Selector Functions".

I've decided not to implement `selector-parent` or `selector-last`, since they're structural rather than semantic and can be done in user code relatively easily using list functions.

One additional function that I'm planning to implement is `is-superselector($selector1, $selector2)` which returns whether `$selector1` matches a superset of the elements that `$selector2` matches. I'm considering `selector-trim($selectors...)` which would return a selector that matches all elements matched by its input selectors and would also remove any redundancy between them, but I'm not sure if that's useful enough to be worthwhile.

As before, if anyone else has any suggestions for additional selector functions, please voice them here.
