### ISSUE TITLE
[wishlist] Add a way to modify the outermost selector

### ISSUE THREAD

**Issue by rajnathani** [sass/sass#1119]
The `&` in SASS is beyond wonderful, using it just splashes out happiness.  
`&` can be used to nest the parent selector as follows:  

```
.parent {
    .foo {
        .logged-in & {
            ~~~~
        }
         .logged-out & {
            ~~~~
        }
    }
}
```

the above will evaluate to

```
.logged-in .parent .foo {}
.logged-out .parent .foo {}
```

However as far as I know (correct me if I'm wrong here), achieving the below cannot be done:

```
.logged-in.parent .foo {}
.logged-out.parent .foo {}
```

**Comment by nex3** [comment]
Currently, that's correct. However, when #1117 is implemented, you'll be able to do this:

``` scss
.parent {
  .foo {
    @at-root {
      #{selector-append(".logged-in", &)} { /* ... */ }
      #{selector-append(".logged-out", &)} { /* ... */ }
    }
  }
}
```
