### ISSUE TITLE
Sass 3 compressed output not really compressing

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#112]
Sass version: Haml/Sass 3.0.0.beta.2 (Classy Cassidy)
- Certain color definitions should be shorten: #336699 -> #369
- Unnecessary spaces and zeroes should be removed in: rgba(0, 0, 0, 0.25) -> rgba(0,0,0,.25)
- Unnecessary spaces should removed in: font-family:"Lucida Grande", Helvetica, Arial, sans-serif -> font-family:"Lucida Grande",Helvetica,Arial,sans-serif

[Originally filed](https://github.com/nex3/haml/issues/153) by @riobard.

**Comment by ryantownsend** [comment]
One thing to note is that shortening colours can cause problems with IE in certain cases. I'm having the problem myself where #eee is output not #eeeeee at the moment and looking for a work around. Just an edge case to be aware of...

**Comment by chriseppstein** [comment]
Pretty 100% sure #eee works in IE. Please explain your issue in more detail. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by ryantownsend** [comment]
It works for standard colours, but use within filters, such as those for getting gradient fills in IE causes them to output bizarre colours (possibly assuming the last 3 digits are 000, so #eee becomes #eee000).

**Comment by rquigley** [comment]
I can confirm that this issue occurs with IE8 and:
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#fff', endColorstr='#ff0000',GradientType=0 );

disabling sass compression results in a working gradient

**Comment by chriseppstein** [comment]
IE filters are not compliant css. Use this sass function: `ie-hex-str($color)` with MS filters. This function is currently provided by compass, but will be part of sass when 3.2 is released.
