### ISSUE TITLE
Bootstrapping common files

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1120]
With many sass projects it's common to need to bootstrap a file with an import like `@import "settings.scss";` 

Would it reasonable to move this bootstrapping to a cli parameter?

`sass --load-path src/scss --requires src/scss/_settings.scss`

**Comment by nex3** [comment]
I don't like including flags that encourage people to write Sass files that require a certain invocation to work correctly. I want Sass files to be able to run anywhere with minimal configuration as much as possible. Adding a flag just to get around writing `@import` statements isn't worth the fragmentation.

**Comment by cimmanon** [comment]
If you find yourself bootstrapping with the same kinds of files/imports, you might want to look into creating a Compass extension.  The "templates" portion of an extension is designed to do this.

http://compass-style.org/help/tutorials/extensions/
