### ISSUE TITLE
Sass logic within comment blocks being compiled

### ISSUE THREAD

**Issue by shaunbent** [sass/sass#1123]
I've found a case where I am storing a block of Sass code in a large comment block. However, this causes a compile error as it looks as if Sass is trying to compile and run the logic within the block and can't find the variables used within the code example.

I've made a quick example to demonstrate this:

http://sassmeister.com/gist/9090745

If lines 15 & 16 of the above example are removed then the code compiles as expected.

**Comment by nex3** [comment]
This is expected. `/* ... */` comments are emitted to CSS, and as such interpolation (`#{}`) is active within them so that users can emit dynamically-generated comments.
