### ISSUE TITLE
Add support for `:has()`

### ISSUE THREAD

**Issue by nex3** [sass/sass#1126]
As of [19 February](http://lists.w3.org/Archives/Public/www-style/2014Feb/0617.html), the CSS working group has decided to move away from `!` and towards `:has()` for indicating subject selectors. Sass should support this.

Based on the discussion linked above, it looks like the syntax will be `E:has(F)`, where `F` can be any arbitrary selector, including one starting with a combinator (e.g. `E:has(> F)`).

**Comment by nex3** [comment]
This will require deprecating the existing support for `!`.

**Comment by chriseppstein** [comment]
I really like the `!` syntax. What about just compiling it to the `:has(...)` syntax?

**Comment by nex3** [comment]
I don't think there's enough syntactic benefit to justify the conceptual overhead of doing it in a different way than CSS. Plus it runs a serious risk of stepping on the toes of a future CSS feature.
