### ISSUE TITLE
Support mathematical comparison syntax for media queries

### ISSUE THREAD

**Issue by nex3** [sass/sass#1129]
[Media Queries Level 4](http://dev.w3.org/csswg/mediaqueries/) is likely to introduce mathematical comparison operators (e.g. `>`, `<`) for media queries. We should support this syntax.

**Comment by yisibl** [comment]
Like this: https://github.com/postcss/postcss-media-minmax

![gif demo](https://camo.githubusercontent.com/bc3405169198f46ea05f7c1d3b7fab127a7ddc13/687474703a2f2f67746d7330322e616c6963646e2e636f6d2f7470732f69322f54423155496a7947565858585863436158585878323734467058582d3837372d3333392e676966)

**Comment by nex3** [comment]
Duplicate of #1864
