### ISSUE TITLE
when I sass --watch ,  the error "undefined method `force_polling'....

### ISSUE THREAD

**Issue by cycold** [sass/sass#1132]
Administrator@ZLCF-06 /E/work/2014/tmp/sassTest
$ sass --watch --sourcemap sass:css
 Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: undefined method `force_polling' for #Listen::Listener:0x108e628
  Use --trace for backtrace.
Administrator@ZLCF-06 /E/work/2014/tmp/sassTest
$ sass -v
Sass 3.3.0.rc.5 (Maptastic Maple)

**Comment by nex3** [comment]
What version of the `listen` gem do you have installed?

**Comment by cycold** [comment]
listen version:
`$ gem install listen --pre
 Successfully installed listen-2.6.1
 Parsing documentation for listen-2.6.1
 1 gem installed`

**Comment by cycold** [comment]
About details

`$ sass --watch sass:css --trace`

```
    Sass is watching for changes. Press Ctrl-C to stop.
    d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/plugin/compiler.rb:281:in 'watch': undefined method 'force_polling' for #<Listen::Listener:0x14951e8> (NoMethodError)
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/plugin.rb:108:in 'method_missing'
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/exec.rb:509:in 'watch_or_update'
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/exec.rb:346:in 'process_result'
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/exec.rb:43:in 'parse'
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/lib/sass/exec.rb:22:in 'parse!'
    from d:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.5/bin/sass:13:in '<top (required)>'
    from d:/Ruby200/bin/sass:23:in 'load'
    from d:/Ruby200/bin/sass:23:in '<main>'
```

`$ gem list`

**\* LOCAL GEMS ***

```
    bigdecimal (1.2.0)
    celluloid (0.15.2)
    chunky_png (1.3.0)
    compass (1.0.0.alpha.18)
    compass-core (1.0.0.alpha.17)
    compass-import-once (1.0.2)
    ffi (1.9.3 x86-mingw32)
    io-console (0.4.2)
    json (1.7.7)
    listen (2.4.1, 1.1.6)
    minitest (4.3.2)
    multi_json (1.8.4)
    psych (2.0.0)
    rake (0.9.6)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.3)
    rb-kqueue (0.2.2)
    rdoc (4.0.0)
    sass (3.3.0.rc.5)
    test-unit (2.0.0.0)
    timers (1.1.0)
```

**Comment by cycold** [comment]
https://github.com/chriseppstein/compass/issues/1108
When I using:
`sass --compass --watch --sourcemap sass:css`
It's good work!.
No error message.It can monitor all the time
but using `sass --watch --sourcemap sass:css`
the error message display still.It can disrupt watching...

**Comment by cycold** [comment]
Good job!
Updated `compiler.rb` It's good working.
Thanks,
