### ISSUE TITLE
compass not working Sass 3.3.0.rc.5 (Maptastic Maple)

### ISSUE THREAD

**Issue by cycold** [sass/sass#1133]
For Writing and debugging Sass with the DevTools in chrome, I updated sass3.3.0,but I found my compass is not work now.
when I input :
`$ compass version`
I get:
`d:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require: cannot load
 such file -- sass/script/node (LoadError)
        from d:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require
        from d:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_p
atches/browser_support.rb:1:in <top (required)>
        from d:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require
.....................
`
when I go back sass3.2.14 ,compass is good working.
Sorry  poor English

**Comment by nex3** [comment]
You need to use a more recent version of Compass. @chriseppstein can provide more details about which versions are compatible.

**Comment by chriseppstein** [comment]
The latest compass pre release will work.

gem install compass --pre

**Comment by cycold** [comment]
Thanks,I got it. I forgot updated compass, sorry......
