### ISSUE TITLE
Get the current selector in Sass 3.3.0.rc.5

### ISSUE THREAD

**Issue by FWeinb** [sass/sass#1134]
In Sass 3.3.0.rc.3 it was possible to get the current selector as a string via

``` scss
 $selector: #{&};
```

After allowing:

``` scss
block{
  &--element{
  }
}
```

in Sass 3.3.0.rc.4, this is not possible anymore. Is there any other way to access the current context selector.

What I want is:

``` scss
.selector .test{
  debug: inspect(#{&}); // ".selector .test"
} 
```

**Comment by nex3** [comment]
There is not. This feature will be re-added in Sass 3.4.

**Comment by panec** [comment]
There is no option but you can use custom Ruby file. Solution is described in here:
https://gist.github.com/nex3/8050187#comment-1192688
