### ISSUE TITLE
source-map option causes warn_about_public_url cause by mixing up slash and backslash in call to relative_path_from

### ISSUE THREAD

**Issue by pasdut** [sass/sass#1135]
SASS  3.3.0.rc.5 - Windows 8.1 x64

I'm calling SASS from within gulp-sass and I get the warn_about_public_url.

I confirm gulp-sass is sending correct filenames (the spawn is :`sass C:\Users\pascal\AppData\Local\Temp\46f2af77-e238-473f-a0d6-ff6b97cc09c1\main.scss C:\Users\pascal\AppData\Local\Temp\46f2af77-e238-473f-a0d6-ff6b97cc09c1\main.css --load-path C:\Pascal Documenten\projecten\Specialleke\site-dev.002\styles --sourcemap`) But if I print the values from the variables dest_directory and base_directory infrom relative_path_from(pathname.rb) then I see  that sometimes the '\' is replaced by a '/'.

I quick fixed this by following patch on relative_path, but I guess this is a sass issue (probably in filesystem.rb?)

``` ruby
def relative_path_from(base_directory)
  #pascal patched :         
  #dest_directory = self.cleanpath.to_s
  #base_directory = base_directory.cleanpath.to_s
  # hardcoded fix only for windows
  dest_directory = self.cleanpath.to_s.capitalize!.gsub("/", "\\")
  base_directory = base_directory.cleanpath.to_s.capitalize!.gsub("/", "\\")
```

This is a debug log of one call to SASS to compile with source_map

```
[relative_path_from patch]base :C:\users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd
[relative_path_from patch]dest: C:\users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd/main.css
```

Here below you see that the second time the relative_path_from is called, the base has a backslash after "C:" while destination has a slash after "C:"

```
[relative_path_from patch]base :C:\users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd
[relative_path_from patch]dest: C:/users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd/main.scss
```

Same goes for the third call to relative_path_from

```
[relative_path_from patch]base :C:\users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd
[relative_path_from patch]dest: C:/users/pascal/appdata/local/temp/33d81f64-28a8-41f6-b3c1-23074ec13efd/main.scss
```

**Comment by nex3** [comment]
Can you provide a simple case that I can reproduce locally? In particular, one of more Sass files that produce an unexpected warning, and a command-line invocation of the `sass` executable that causes that warning to be emitted.

**Comment by pasdut** [comment]
Hi,

It is a simple trivial file : main.scss :

$myColor:#123456;

body{
  .box {
    color: $myColor;
  }
}

 I compile using :

sass c:\test\main.scss c:\test\main.css  --sourcemap

C:\test>dir
Volume in drive C is WIN8
Volume Serial Number is A6F8-B63E 

Directory of C:\test
01/03/2014  21:22    <DIR>          .
01/03/2014  21:22    <DIR>          ..
01/03/2014  21:13                68 main.scss

C:\test> sass c:\test\main.scss c:\test\main.css  --sourcemap
WARNING: Couldn't determine public URL for "c:\test\main.scss" while generating sourcemap.
  Without a public URL, there's nothing for the source map to link to.

C:\test>dir
Volume in drive C is WIN8
Volume Serial Number is A6F8-B63E

Directory of C:\test
01/03/2014  21:22    <DIR>          .
01/03/2014  21:22    <DIR>          ..
01/03/2014  21:22    <DIR>          .sass-cache
01/03/2014  21:22                74 main.css
01/03/2014  21:22                88 main.css.map
01/03/2014  21:13                68 main.scss

```
           3 File(s)            230 bytes
```

C:\test>sass -v

Sass 3.3.0.rc.5 (Maptastic Maple)

This is the contents of the generated map file : 
{
"version": 3,
"mappings": "",
"sources": [],
"names": [],
"file": "main.css"
}
