### ISSUE TITLE
[request] Shortened versions of @extends, @includes etc

### ISSUE THREAD

**Issue by Undistraction** [sass/sass#1138]
I find that I'm using more and more @includes in my stylesheets which is obviously a great thing, however it feels like a lot of visual noise is added by `@include`, `@extend` etc.

I think it would be great for Sass to support alternative shortened versions of these keywords, for example:

```
@in some-include();
@ex some-base-class;
```

**Comment by lolmaus** [comment]
The indented `.sass` syntax already has `=` for `@mixin` and `+` for `@include`.

I believe that other shorthand directives should follow the same pattern.

We need:
- `@function`;
- `@extend`;
- `@import`.

I don't think that @nex3 and @chriseppstein will accept this because it would make indented Sass kinda cryptic. On the other hand, i use `=` and `+` all the time and it's helping a lot, so...

**Comment by Snugug** [comment]
There actually already exists an issue, #366, to enhance the syntax for mixins at least, if not imports and functions.

**Comment by timfayz** [comment]
+1 to shorten `@include` into `@in`! Word _include_ is very long(

**Comment by Arcovion** [comment]
The `.scss` syntax is designed to be verbose, why not use the `.sass` syntax if it bothers you?

**Comment by timfayz** [comment]
@arcovion I'm not insist..may be you are right. The founders know better what to do)

**Comment by whaaaley** [comment]
+1 to shorten `@include` to `@in` as well.

I'm also in favor of `@fn`, `@im`, `@mx`, `@ea`, and `@ex`

They could be added as shorthand alternates rather than changing the existing syntax.

**Comment by chriseppstein** [comment]
&lt;snark&gt;
Should we also shorten `background` to `bg`, `margin` to `m`, `padding` to `pd`?
&lt;/snark&gt;

CSS is a verbose language to make it readable and one of the ways SCSS maintains the feeling of being an extension to CSS is by keeping the language readable.

That said, in #366 we are on the record of wanting some syntactic sugar include and extend.

**Comment by Undistraction** [comment]
Shouldn't that be:

```
<snk>
Should we also shorten background to bg, margin to m, padding to pd?
</snk>
```

**Comment by chriseppstein** [comment]
@dustindowell22 Thanks. We considered the request and explained why we're not interested in adding this to Sass.
