### ISSUE TITLE
adjust-hue not working as expected

### ISSUE THREAD

**Issue by willsoto** [sass/sass#1139]
Please see the following code pen: http://codepen.io/katydecorah/pen/FgmJI and set `$mainSqueeze` equal to a color with a hue of 0 - I've been using `hsl(0, 0%, 99%)`. The color should increment by the given degree, but it does not.

I first experienced this with libsass and thought the issue might be there, but after testing on codepen, which I think uses the stable ruby version, I found the problem exists there as well.

**Comment by nex3** [comment]
Can you provide the specific `adjust-hue` call you're invoking, without any additional context, as well as the value you expect to get and the value you actually get?

**Comment by willsoto** [comment]
Sure, here it is:

call: `adjust-hue(hsla(0, 0%, 99%, 1), 220deg)`

actual: `hsla(0, 0%, 99%, 1)`
expected: `hsla(220, 0%, 99%, 1)`

**Comment by nex3** [comment]
This works for me on master and stable:

```
$ ./bin/sass -i
>> adjust-hue(hsla(0, 0%, 99%, 1), 220deg)
#fcfcfc
>> hue(adjust-hue(hsla(0, 0%, 99%, 1), 220deg))
220deg
```

**Comment by nex3** [comment]
It's worth noting that with 0% saturation, the hue doesn't actually affect the way the resulting color is displayed.

**Comment by willsoto** [comment]
Ok, thanks. That would explain why the codepen isn't working as expected. Appreciate it.
