### ISSUE TITLE
undefined method 'to_tree' for nil:NilClass

### ISSUE THREAD

**Issue by scottdavis** [sass/sass#114]
https://github.com/nex3/sass/blob/master/lib/sass/plugin/staleness_checker.rb#L169

The staleness checker is assuming you will never return nil which is not what the documentation states

<pre>
   # @return [Sass::Engine, nil] An Engine containing the imported file,
   #   or nil if it couldn't be found or was in the wrong format
</pre>

stack trace: https://gist.github.com/238aa70212c35e4e2a81

**Comment by chriseppstein** [comment]
It looks to me like the importer is always the importer used to import the file. I suspect this bug is in compass.

**Comment by HamptonMakes** [comment]
+1 for getting this in the next release. We are having this issue.

**Comment by scottdavis** [comment]
Are you using compass sprites?

**Comment by scottdavis** [comment]
it happens someplace before https://github.com/nex3/sass/blob/master/lib/sass/plugin/staleness_checker.rb#L150 but once i get here i lose track of the stack in rdebug

**Comment by scottdavis** [comment]
Some were in sass dirname is getting called on the importer uri and removing the *.png from the uris for sprites

**Comment by scottdavis** [comment]
the sprite importer class im compass is checking for `%r{((.+/)?([^\*.]+))/(.+?)\.png}` on the importer uri and it satisfies the match on the first request. but after updating a file its failing because it is receiving "global" in stead of "global/*.png" 

example repo to recreate problem 

https://github.com/jetviper21/to_tree_error

**Comment by plentz** [comment]
facing the same error here.

**Comment by dhiemstra** [comment]
Our whole dev team is facing this issue occasionally. We are using compass sprites.

**Comment by be9** [comment]
I spent some time debugging this (thanks @jetviper21 for your repo)

I found that "global" always comes as the uri parameter. However stack traces differ in the first request and in the subsequent failing requests: https://gist.github.com/1079814. So, it's the StalenessChecker that fails here.

There's a workaround however. Put the following line to config/compass.rb:

```
sass_options = { :always_update => true }
```

It will regenerate everything each time, but at least it won't throw an exception.

**Comment by scottdavis** [comment]
<img src='http://images.memegenerator.net/instances/500x/9340731.jpg' />

**Comment by moeffju** [comment]
This patch fixes it for me, and normal imports still work:

``` diff
diff --git i/lib/sass/plugin/staleness_checker.rb w/lib/sass/plugin/staleness_checker.rb
index c87d7bf..3b3049d 100644
--- i/lib/sass/plugin/staleness_checker.rb
+++ w/lib/sass/plugin/staleness_checker.rb
@@ -159,7 +159,7 @@ module Sass
         tree(uri, importer).grep(Tree::ImportNode) do |n|
           next if n.css_import?
           file = n.imported_file
-          key = [file.options[:filename], file.options[:importer]]
+          key = [n.imported_filename, file.options[:importer]]
           @parse_trees[key] = file.to_tree
           key
         end.compact
```

applied in moeffju/sass@37b435e2f2215af0cad75706b5d7f9ab5dd9683c

**Comment by scottdavis** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEE!!!!!!

**Comment by moeffju** [comment]
@jetviper21: So does it work for you?

**Comment by scottdavis** [comment]
havent had time to test it. but if you try that test repo i made and it works then it fixes the problem

**Comment by moeffju** [comment]
Yes, it fixes your test repo and works with all my apps and our apps at @Toptranslation.

**Comment by scottdavis** [comment]
Nice I notified chris you mind making this a pull request?

**Comment by moeffju** [comment]
Pull request was opened yesterday: https://github.com/nex3/sass/pull/157
