### ISSUE TITLE
Make opposite-position part of core?

### ISSUE THREAD

**Issue by corysimmons** [sass/sass#1143]
Hi, I'm trying to port my framework from Stylus to Sass but `opposite-position` isn't part of Sass core, and it's required by my framework (and most people who want RTL support).

It _is_, however, part of Compass and I'm sure Chris wouldn't mind if Sass swallowed it up.

http://www.rubydoc.info/github/chriseppstein/compass/Compass/SassExtensions/Functions/Constants#opposite_position-instance_method

Before I PR, I just wanted to confirm we can we make this part of Sass core. I really don't want people to have to use Compass just to be able to use my grid system.

Thanks

**Comment by nex3** [comment]
@chriseppstein, do you think this is general-purpose enough to warrant inclusion in the core?

**Comment by Snugug** [comment]
@nex3 @chriseppstein I can tell you that we've needed to [create our own](https://github.com/Team-Sass/Singularity/blob/1.x.x/stylesheets/singularitygs/helpers/_directions.scss) in Singularity for the same reason. I'd love to see this in Core, especially if it includes `ltr`/`rtl`

**Comment by corysimmons** [comment]
@Snugug Yeah, exactly. ltr/rtl support would be amazing. :)

**Comment by chriseppstein** [comment]
I will have some news about this soon. 

  Chris Eppstein  
 Sent via Intro for iPhone

**Comment by corysimmons** [comment]
@chriseppstein Thanks Chris

**Comment by neo** [comment]
And what now?
