### ISSUE TITLE
SASS not executing function inside of url()

### ISSUE THREAD

**Issue by moberemk** [sass/sass#1145]
I have a function which I've set up to take in a resource URL and then spit out a resource URL for use in the actual CSS. The function does not transform the string in any way before returning it, so I expect to be able to do this:

```
background-image: url(preload-image("../img/image.jpg"));
```

and have it come out as this when compiled:

```
background-image: url("../img/image.jpg");
```

This does not hold however, and what actually appears in the compiled CSS is the original SASS (function call and all):

```
background-image: url(preload-image("../img/image.jpg"));
```

I'm not completely sure if this is a bug or a feature, but it goes against my expected behavior in this instance. Should I be using some sort of string interpolation here or is this actually an issue with the compiler not reading the function call?

**Comment by nex3** [comment]
CSS defines `url()` as a special type of string quote, and Sass follows that definition. This allows things like `url(http://foo.com)` to work, which would otherwise be invalid, but it also means you need to use `#{}` to use functions within a `url()`, like you would with a normal string.
