### ISSUE TITLE
Can't update Sass on win7 machine

### ISSUE THREAD

**Issue by klangwiedergabe** [sass/sass#1149]
[first I tried this fix http://bit.ly/NI7dmA coz I was getting a PATH error thing, now I'm getting something else] 

Error says something like:

Gem files will reamain install in C:/ bla bla bla for inspection.

inspection? wierd.

then finish with "Nothing to update"

:c

**Comment by nex3** [comment]
Can you post the full log from trying to install Sass?

**Comment by klangwiedergabe** [comment]
![gemsassfail](https://f.cloud.github.com/assets/1858040/2370534/431d544c-a808-11e3-8128-4788f3d2ddbd.PNG)

that's the error, I tried a fix that I found on stackoverflow [ http://bit.ly/1nyImyj ](googling the error) and now I'm getting a new error with a json file.
That post is just crazy to me as a designer D: 
I have no idea what I'm doing. Just wanted to update Sass :c

**Comment by stevenbriscoeca** [comment]
https://github.com/nex3/sass/issues/1150 I posted the same error, I think they found out what is happening. Stay tuned for version 3.4

**Comment by nex3** [comment]
Merging into #1163.
