### ISSUE TITLE
Cannot install version 3.3 on windows 7

### ISSUE THREAD

**Issue by stevenbriscoeca** [sass/sass#1150]
I am not able to install sass 3.3 on windows 7.

I have installed ruby devkit and followed the instructions here : 
https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

I then tried to install sass and I got all this gibberish : 
http://pastebin.com/hNawyJ0v

If someone else can test out installing sass 3.3 on windows 7 to make sure that this error is not only on my machine, that would be great.

Thank you!

**Comment by chriseppstein** [comment]
I'm fairly certain this check is just because of the use of a gem builder during install. If we distribute listen as an embedded gem this issue should go away.

**Comment by klangwiedergabe** [comment]
anyone knows if this happen in win8 too?

**Comment by nex3** [comment]
Merging into #1163.
