### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by Kapeli** [sass/sass#1152]
You seem to have `???` instead of `'` everywhere at http://sass-lang.com/documentation/file.SASS_REFERENCE.html

**Comment by parkr** [comment]
Yep, confirmed. Perhaps an encoding error? Is your site served with `charset="utf-8"`?

**Comment by Kapeli** [comment]
This is in the HTML source:

```
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII" />
```

However, I don't think it's an encoding issue (`'` is valid in ASCII as far as I know).

**Comment by nex3** [comment]
I think this was just caused by building the docs with Ruby 1.8.7.

Also, for future reference, issues with the website should be filed on [the sass-site repo](/sass/sass-site).
