### ISSUE TITLE
sass 3.3.0: Warning. Error encountered while saving cache ...: can't dump anonymous class #<Class:..>

### ISSUE THREAD

**Issue by mdesantis** [sass/sass#1162]
In my Rails app, after updating Sass from 3.2.15 to 3.3.0 I get a lot of these warnings:

```
Warning. Error encountered while saving cache /path/to/rails/root/tmp/cache/sass/be5cee8cb77bd6548431cadb96c7cc283fde192f/application.css.scss.erbc: can't dump anonymous class #<Class:0x007fc5e352d6f8>
```

I don't use cache stores, so I don't set `config.cache_store`, so the solution to the issue https://github.com/nex3/sass/issues/1093 doesn't work with my app.

**Comment by nex3** [comment]
Duplicate of #1028.

**Comment by nathany** [comment]
If it's a duplicate of a resolved issue, why are we also seeing this in sass 3.3.0? (in development)

**Comment by nex3** [comment]
As #1028 says, this is a bug in Sprockets. Sass importers are required to be marshalable, and the Sprockets importer is not. sstephenson/sprockets#507 is tracking that bug.

**Comment by nathany** [comment]
Ok. Thanks for the info. Locking to sass ~> 3.2.15 for now.

**Comment by dodeja** [comment]
Is this still an issue? cc @nathany

**Comment by nathany** [comment]
@dodeja Not sure. Still locked to 3.2, I need to try it out.

**Comment by YoranBrondsema** [comment]
@dodeja I upgraded to sass 3.3.9 and I'm having the issue with Sprockets.

**Comment by fenelon** [comment]
Having issues as well on 3.3.11. It happens randomly and not every time.

**Comment by AnastasiaLS** [comment]
Am seeing this now with Sass 3.3.14/Sass-rails 4.0.1 and Sprockets 2.11.0/Sprockets-rails 2.0.1

**Comment by ogminor** [comment]
Also getting this, interested in knowing more about the topic.

**Comment by fenelon** [comment]
I had to drop saas-sourcemaps gem and downgrade. For now, it's compiling
without an issue.

**Comment by ogminor** [comment]
Can you explain what is happening because after compiles it still works, is it just slower to compile or is it slower after compile when loading assets?

Which version do you recommend downgrading too?

**Comment by the-teacher** [comment]
@ogminor  +1
Somebody can explain this?

**Comment by ogminor** [comment]
I ended up fixing mine by upgrading my infrastructure but I'm still interested on knowing more about this issue to satisfy my own curiosity.

**Comment by fenelon** [comment]
It seems that it needs cache to significantly speed up the process. I got
it working, but had no time to dive deep into the details. Would be nice to
hear a more detailed explanation.

**Comment by koron** [comment]
I encounter this now.  Related gems and version are:

```
sass (3.4.2)
sass-rails (3.2.6)
sprockets (2.2.2)
```

And when I used `sass (3.2.19)` with pinned, this doesn't happen.
