### ISSUE TITLE
Bundle listen with Sass

### ISSUE THREAD

**Issue by nex3** [sass/sass#1163]
With the release of Sass 3.3, it's become clear that the solution we've chosen for adding a dependency on listen is not workable. Currently we have an `ext/mkrf_conf.rb` file that installs [listen](guard/listen) 1.1 on Ruby < 1.9.3 and the latest version otherwise. RubyGems thinks that `ext/mkrf_conf.rb` means that a native extension needs to be installed, though, which causes a considerable amount of pain, especially on Windows.

As such, we should move back to the old solution of bundling a known-compatible version of listen with Sass. To avoid staleness, we'll bundle both listen 1.1 and listen 2.x, and choose between them based on the current Ruby version. This will unfortunately also involve bundling at least celluloid and celluloid-io, and possibly additional transitive dependencies.

**Comment by nex3** [comment]
Upon further consideration, celluloid and its transitive dependencies are too costly to bundle, especially considering that [nio4r](/celluloid/nio4r) requires a native extension to be built. We will bundle only listen 1.1, although we will be compatible with listen 2.x if that's what the user has installed.

**Comment by jleclanche** [comment]
Is listen a hard dependency or an optional one?

**Comment by chriseppstein** [comment]
listen is required in order to use `sass --watch`. As an embedded library it won't conflict with other libraries or applications use of it and if you're not watching it won't be required.

Nathan, I think we should still try to require listen via rubygems and only fall back to our embedded version. This means that we're going to have to be very liberal in terms of our support of their APIs. I suggest we add a matrix of testing against different versions of listen in our travis build. I can help you set that up.

**Comment by jleclanche** [comment]
If it's only required for sass --watch as it used to, packagers can mark it as such. As long as you have a matrix somewhere in your readme specifying which versions are supposed to be used and such, at least on arch linux, we will be fine.

**Comment by jleclanche** [comment]
Note that that is if you decide it is any use to let packagers pull in a distro dependency. Remember that anything installed through pacman/apt/yum/etc cannot be installed directly through `gem`.

**Comment by nex3** [comment]
> Nathan, I think we should still try to require listen via rubygems and only fall back to our embedded version. This means that we're going to have to be very liberal in terms of our support of their APIs. I suggest we add a matrix of testing against different versions of listen in our travis build. I can help you set that up.

I agree. This was the 3.2 behavior, although it didn't have as wide a range of supported versions as 3.3 will.

**Comment by nex3** [comment]
Small update: it looks like listen 1.3.1 is the latest version that's compatible with Ruby 1.8.7, so we'll be bundling that.

**Comment by stevenbriscoeca** [comment]
thank you very much for this decision! It was an extra step for windows users that might turn people off to sass!

Much easier just doing gem install sass and not having to install devkit and configuring it as well.

**Comment by aaronjensen** [comment]
I'm sure it was considered/discussed at some point, but why not move `sass --watch` to a separate gem that can have different versions for different listen gems? or even different gems, `sass-watch`, `sass-watch-1.8`, etc.

**Comment by nex3** [comment]
At some point we may split out a `sass-core` gem so the command-line frontend can more freely have dependencies without affecting applications that use Sass as a library. That will take a fair amount of work, though, and we needed a solution to the installation problem immediately. It also only shuffles this issue around: we'll still want users to be able to write `gem install sass` and have it work, regardless of what platform they're on.
