### ISSUE TITLE
SASS 3.3.2 incompatible with Compass 0.12.3

### ISSUE THREAD

**Issue by huijing** [sass/sass#1165]
Error message as follows:
.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate compass-0.12.3, because sass-3.3.2 conflicts with sass (= 3.2.14) (Gem::LoadError)

**Comment by Anahkiasen** [comment]
Well that's kind of normal, you should be using Compass 1.0 with Sass 3.3 no ?

**Comment by huijing** [comment]
Aww man. I'm face-palming my own idiocy right now. Thanks for the tip.

**Comment by ichernev** [comment]
`gem list -a -r compass` does show compass 0.12.3 as the latest version. Am I missing something? Also for me it says `ERROR: Can not load compass`. The funny part is that strace shows that it finds it in `/usr/lib/gems/1.8`, but then it prints the error.

**Comment by huijing** [comment]
the latest stable version is indeed 0.12.3 but the if you use gem install compass --pre, you'll get the alpha version, which is 1.0.0

**Comment by ichernev** [comment]
Ah, I see. Thank you!
