### ISSUE TITLE
3.3.2 and listen still not fully working under OSX

### ISSUE THREAD

**Issue by TundraTech** [sass/sass#1168]
Regardless of which version of listen I use 2.7, 2.4.1 or the bundled version, typing this watch command fails, it compiles it once successfully, then fails to detect any changes.

```
sass --watch /wwwroot/sass/alpine/modules/_wheel.scss:/wwwroot/css/_wheel.css
```

COMPILES ONCE, BUT DOES NOT DETECT FURTHER CHANGES

```
sass --watch /wwwroot/sass/alpine/modules/
```

DETECTS CHANGES, BUT FAILS TO REPORT COMPILE ERRORS

So directories are detecting events, but failing to compile whicle, individual files compile once then fail to detect events. Still a bug in there guys, really frustrating please have a look, thanks.

ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

OSX SystemVersionStampAsString = "10.9.2";

**\* LOCAL GEMS ***

rb-fsevent (0.9.4)
sass (3.3.2)

(i know listen is not installed, ive tried 2.4.1, 2.7 and neither worked)

Help!!!

**Comment by nex3** [comment]
I can't reproduce this on OS X 10.9.2, either with or without a compile error. Watching seems to work fine in all the cases I tried.

If you can debug into this yourself and come up with a patch, I'll be happy to merge it, but until then there's not much I can do.
