### ISSUE TITLE
Reference nested adjacent elements

### ISSUE THREAD

**Issue by entozoon** [sass/sass#1173]
If I do sass similar to:

```
.foo {
   .bar {
      & + & { }
   }
}
```

If would create:

```
.foo .bar + .foo .bar { }
```

Which, makes sense.. but isn't very useful and could potentially be better to generate:

```
.foo .bar + .bar { }
```

Or perhaps there's an alternative way of doing this.. ?

**Comment by nex3** [comment]
Duplicate of #286.

**Comment by entozoon** [comment]
It'd take me the rest of my natural life to read through and understand the outcome of that thread
