### ISSUE TITLE
Race Condition in Filesystem Cache

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1175]
Fixed by d4c5fff0160a78b66d78f10d7e60a92fc6a16d49.

I need to release a new 3.2 stable with this fix. @nex3 Please advise on how we can release new stable releases based on the 3.2 codebase.

I have branched off of the 3.2.15 tag: https://github.com/nex3/sass/compare/sass_3_2

We also need to roll this fix into the stable and master branches.

**Comment by nex3** [comment]
Why would we backport this to 3.2? 3.3 is stable now.

**Comment by chriseppstein** [comment]
Because I'm not yet ready to upgrade LinkedIn to Sass 3.3 and this is affecting us in production.

**Comment by nex3** [comment]
That sounds like something to patch locally. The 3.2 branch is officially unmaintained, and I don't want to have precedent for these sorts of backports.

**Comment by chriseppstein** [comment]
Slippery slopes are only slippery if you let them be. We only just released Sass 3.3, and there have been stability issues there. Having zero overlap of stable releases is draconian and irresponsible. **I need to maintain the 3.2 branch with bug fixes** until such time as I have coordinated an upgrade across the codebase of our largest user. Sass is growing up and that means we may need to maintain several stable releases for some amount of time measured in months.

**Comment by lolmaus** [comment]
Thank you for keeping the 3.2 branch healthy, @chriseppstein.

**Comment by nex3** [comment]
I don't have the resources to support three branches at once. If you want to take full ownership of the 3.2 branch, feel free to do so, but I intend to make bug fixes to 3.3 going forward. If you want them backported, you'll need to be the one to do so.

**Comment by chriseppstein** [comment]
@nex3 Yes, I will own the 3.2 stable releases.

**Comment by chriseppstein** [comment]
Released as 3.2.16. Fix has been merged to stable and master as well.
