### ISSUE TITLE
Variable name interpolation

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1176]
I am currently developing a mini-framework to make our current site development process easier. I was attempting to automate our initial stylesheet build process (which is defining variables for color/typography settings) by defining a set functions and a mixin to basically create a bunch of global variables that can be used throughout the stylesheet once initialized, but are actually housed in a config map, like the example below.

I thought this method would be best, as initial build setup varies from developer to developer, and often times this turns out to be for the worse rather than for the better. So, automating this from a config map seemed like a good solution, so all of our stylesheets have identical variable/typography naming conventions regardless of developer.

``` scss
"build": (

    // initializer

    "build-mode": true, // colors-only, type-only, false

    // color palette

    "colors": (
        "blue": (
            "light": skyblue,
            "base": blue,
            "dark": navy,
        ),
        "yellow": (
            "light": tan,
            "base": yellow,
            "dark": gold,
        ),
    ),

    // typography

    "typography": (
        "font-stacks": (
            "primary": sans-serif,
            "secondary": serif,
        ),
        "headers": (
            "h1": (
                "font-stack": "secondary",
                "size": 32px,
            ),
            "h2": 24px,
            "h3": 18px,
        ),
        "body": (
            "font-stack": default,
            "base": 16px,
        ),
    ),
);
```

Which would then run through a function, defining BEM style global variables within the function once initialized, such as `$colors__blue--light !global`, so it could then be used throughout the stylesheet. I know that you could simply fetch the values from the maps (which I am doing elsewhere for the grids), but for sake of consistency with outside developers, we thought keeping variable use intact would be best, instead of attempting to teach them a new set of functions, as a config map would already be a significant change. Not a big issue, but it would be a nice-to-have feature.

Any chance of something like this being a future addition, or has it been ruled out?

**Comment by lolmaus** [comment]
Variable interpolation is not possible with Sass and asking for it would be a repeated duplicate.

If you're lucky to use Comass, you can do it via templates. Example: https://github.com/chriseppstein/compass/blob/stable/lib/compass/sprite_importer/content.erb

**Comment by nex3** [comment]
Dupliate of #132.
