### ISSUE TITLE
atomic_create_and_write_file in util.rb fails on Windows

### ISSUE THREAD

**Issue by emil-mi** [sass/sass#1184]
On Windows Sass 3.2.17 (Media Mark): I get `Errno::EACCES on line ["891"] of C: Permission denied`  when sass (or compass) tries to write any file. 
I think it happens because you use Tempfile that creates the file with the "unlink on close" access flag and that makes the file inaccessible when it's time to move it.
Would you accept a pull request that replaces Tempfile (that tries to do too much in this case) with another implementation?

The mentioned line is: /Ruby1.9.3/lib/ruby/gems/1.9.1/gems/sass-3.2.17/lib/sass/util.rb:891:in `atomic_create_and_write_file'

**Comment by phasebash** [comment]
This is a big problem for our uses.  We are clients through the Gradle Compass Plugin.  Right now we're applying a patch at build time to this Gem to work around this issue on Windows, this is very unfortunate.

In our patch, we just closed the file before renaming it.  I leave it up to you to decide if this was sufficient.  Either way, this needs to be fixed ASAP.  If you would prefer one of us to do it, we can, just let us know if our approach is sound.

**Comment by chriseppstein** [comment]
@phasebash I have [a commit](https://github.com/nex3/sass/commit/dbc8e02cd398d86013859067718e3dc011067358) on the stable_3_2 branch that does exactly that. However, a user reported that it didn't fix the problem. Can you please test against that branch and let me know if it's working for you? I don't have access to a windows box for testing >_<

**Comment by phasebash** [comment]
I shall.  Do you have VirtualBox?  If so, let me pass you my super slim image.  By the way, has this fix been built and released as a Gem?

**Comment by chriseppstein** [comment]
@phasebash I just installed it :) My email is chris@eppsteins.net thanks!

**Comment by chriseppstein** [comment]
@phasebash it hasn't been released yet. if you checkout the git repo, switch to that branch, you can then `rake package` to make a gem file that can be installed locally.

**Comment by phasebash** [comment]
@chriseppstein Thanks, I'll try your official patch now.

**Comment by phasebash** [comment]
I have build stable_3_2 locally and have verified it to be functional on a Windows system, the issue no longer persists.  

After 3_2 stable is released with a new point release (I assume at least), can we expect a new Compass release to include this change?

**Comment by chriseppstein** [comment]
This should be fixed in 3.2.19.

**Comment by phasebash** [comment]
Thanks Chris.  I'm testing this now.

**Comment by chriseppstein** [comment]
/me raps his fingers nervously against the desk.

**Comment by phasebash** [comment]
Its all good. Thanks for all the work!

**Comment by chriseppstein** [comment]
Yay!
