### ISSUE TITLE
Use of --full-exception flag in command line

### ISSUE THREAD

**Issue by backflip** [sass/sass#1185]
It looks like "--full-exception" is not parsed: https://github.com/nex3/sass/blob/stable/lib/sass/exec.rb#L220

Instead, `invalid option` is returned. Is there a reason for this?

**Comment by nex3** [comment]
Why would you expect this option to exist?

**Comment by backflip** [comment]
https://github.com/nex3/sass/blob/stable/lib/sass/error.rb#L162

Or is this only exposed to plugins? https://github.com/nex3/sass/search?q=full_exception&ref=cmdform&type=Code

It's an awesome feature when debugging in the browser.

**Comment by nex3** [comment]
Ah, I see. That was enabled by default when using `--watch` or `--update`, but not otherwise. f2946e1cf6a6ec682ee31f52e259ceafefdcfed9 enables it any time a CSS file is being written to disk.

**Comment by backflip** [comment]
Great, thanks!
