### ISSUE TITLE
Emit source maps by default

### ISSUE THREAD

**Issue by nex3** [sass/sass#1189]
The `sass` executable should emit source maps by default rather than requiring the user to explicitly enable them. The `--sourcemap` flag should become a `--[no-]sourcemap` flag that makes this behavior togglable.

**Comment by chriseppstein** [comment]
:-1: The config file in #1155 will allow users to set this up as a default for their project if that's what they want.

**Comment by nex3** [comment]
Sourcemaps are very useful and cause minimal clutter. The out-of-the-box experience of using Sass should maximize user assistance, not minimal output.

**Comment by chriseppstein** [comment]
@nex3 selector comments are on by default in compass. I've fielded countless "I hate the comments that compass litters my css output with" Many times they don't even realize that feature can be turned off. even though there's a comment that explains how to do in by default in the configuration file.

I think it's useful, but it's also going to be a support issue. A sass config will significantly improve the experience in either scenario.

**Comment by nex3** [comment]
I'm not disputing that we should add a config file. I'm just saying that the default should be including source maps. I think an additional output file will also be less obtrusive than extra comments in the CSS.

**Comment by chriseppstein** [comment]
ok. let's see how it goes :)
