### ISSUE TITLE
Error while saving cache

### ISSUE THREAD

**Issue by tlimp** [sass/sass#1190]
Using sass-3.3.4 with rails-4.0.3 and sass-rails-4.0.1 I get 

```
Warning. Error encountered while saving cache 0affd879e3e5d2a3b9be29f835fc0508bba0d676/_default.scss.erbc: can't dump anonymous class #<Class:0x007fa509c11280
```

when rake assets:precompile is performed pushing to heroku.
Maybe similar to the 3 years old #147 ?

**Comment by nex3** [comment]
This should be fixed shortly by [this pull request](/sstephenson/sprockets/pull/541).
