### ISSUE TITLE
Sass 3.3 & Windows 7 : news features error

### ISSUE THREAD

**Issue by borisdamevin** [sass/sass#1192]
Is not possible to compile news features with Sass 3.3 and Compass 0.12.4 on Windows 7. I always have an error:

```
error sass/screen.scss (Line 12: Invalid CSS after " &-": expected number
or function, was "-test {")
overwrite stylesheets/screen.css
Errno::EACCES on line ["897"] of C: Permission denied - (D:/WORKS/www/sass/style
sheets/screen.css20140327-8112-uive63, D:/WORKS/www/sass/stylesheets/screen.css)
```

I have install: 
- Sass 3.3.4
- Compass 0.12.4

**Comment by nex3** [comment]
Compass 0.12.x requires Sass 3.2, and will load it even if you have Sass 3.3 installed. You can install a prerelease version of Compass 0.13.x (which is compatible with Sass 3.3) by running `gem install compass --pre`.
