### ISSUE TITLE
Using @import statements within control directives or mixins

### ISSUE THREAD

**Issue by jslegers** [sass/sass#1194]
In https://github.com/sass/sass/issues/1193, I mentioned why it would be a great idea to allow function or mixing definitions within control directives.

An alternative solution would be to allow `@import` statements within control directives.  This would also solve https://github.com/sass/sass/issues/739 .

This would allow one to do the following :

``` scss
@if not function-exists(str-replace) {
  @import '_str-replace';
}
```

It would also allow one to do the following :

``` scss
@if $sassversion > 3.2 {
  @import '_new-sass';
} @else {
  @import '_old-sass';
}
```

And that's just one of the many ways to use this technique. It could also be used to make code more modular.

For example, consider the following :

``` scss
@mixin do_magic($option1 : false, $option2 : false) {
  @if $option1 {
    @import '_option1';
  }
  @if $option2 {
    @import '_option2';
  }
  @if $option1 and $option2 {
    @import '_bothoptions';
  }
}
```

Finally, it could be used to load partials only if a certain partial is found in the filesystem. As such, it would be an alternative implementation for https://github.com/sass/sass/issues/779 .

``` scss
$partial : path/to/partial;
@if import-exists($partial) {
  @import $partial;
}
```

**Comment by jslegers** [comment]
See also :
- https://github.com/sass/sass/issues/115
- https://github.com/sass/sass/issues/739
- https://github.com/sass/sass/issues/779
- https://github.com/sass/sass/issues/1194

**Comment by nex3** [comment]
Duplicate of #451.

**Comment by JamesVanWaza** [comment]
@nex3 What was the solution for @import directives are not allowed inside mixins and functions?

**Comment by nex3** [comment]
It's still not allowed inside mixins and functions.

**Comment by JamesVanWaza** [comment]
@nex3 How did you solve the problem?

**Comment by nex3** [comment]
You should define mixins in the files you might need, import them all, and choose which mixin to invoke.

**Comment by jastew** [comment]
@nex3 I know it's an old post but is there a nice way to choose which mixin to invoke?

Right now I define a variable to select which mixin to use:
```
$btn: 'a' !default;

@if ($btn == 'a') {
    @include btn_a;
} @else if ($btn == 'b') {
    @include btn_b;
}
```

There has to be a nicer way to do this. As you can imagine it's a bit messy if I have 20+ versions of the btn.

I can't seem to select a mixin using a string.

I've tried using placeholders instead of mixins but they have problems with nesting.

Any help is much appreciated.

**Comment by nex3** [comment]
@jastew Support for dynamically invoking mixins is tracked in #626.

**Comment by Frimlik** [comment]
I know this is a very old thread, but I have related question.

I'm using `node-sass-json-importer` to import style data from json theme file and manipulate with them like with other SCSS variables.
Is there any help for me if I want to load one file in case of particular variable value and another file in case of another value?

Example:
Theme files:
theme-default.json
```
{
  'main-color': 'blue';
}
```

theme-custom.json
```
{
  'main-color': 'green';
}
```

Config file:
config.json
```
{
  'theme': 'custom';
}
```

Now in my `_variables.scss' I load config file and a theme variable from it:
```
@import 'config.json';
@debug $theme //outputs 'custom'
```

What I'd like to achieve is this:
```
@if ($theme == '' or $theme == 'default') {
  @import 'theme-default.json';
} @else {
  @import 'theme-custom.json';
}
```

Is there any way? Or another way I could get the same result.
Maybe also the way with variables like in this [comment](https://github.com/sass/sass/issues/739#issuecomment-358296800).
But I absolutely do not know how to do it.

Thanks for any advice!

**Comment by danon** [comment]
I would like to install font awesome free version (which doesn't require an installation token), and also fontawesome pro (which does). I would like to conditionally import fontawesome pro scss, but I can't now :/

**Comment by nex3** [comment]
You can use [`meta.load-css()`](https://sass-lang.com/documentation/modules/meta/#load-css) if you really need to dynamically load the CSS contents of files.
