### ISSUE TITLE
Evaluate variable

### ISSUE THREAD

**Issue by lagden** [sass/sass#1199]
There is a possibility to evaluate any variable?

**Example Javascript**

``` javascript
var boxSize = 140
var boxSpace = 5

function calcBoxSize(size) {
    return boxSize * size + boxSpace * ((size - 1) * 2);
}

for(var i = -1; ++i < 10;) {
    eval('var boxSize' + i + ' = ' + calcBoxSize(i));
}

console.log(boxSize1); // 140
console.log(boxSize2); // 290
```

**Suggestion in Sass**

``` sass
$boxSize: 140px
$boxSpace: 5px

@function calcBoxSize($size)
    @return $boxSize * $size + $boxSpace * (($size - 1) * 2)

@for $c from 1 through 10
    $calc: calcBoxSize($c)
    eval('$boxSize#{$c}: #{$calc}')

// Output
// $boxSize1: 140px
// $boxSize2: 290px
...
```

**Comment by Anahkiasen** [comment]
`eval` is pretty much the one structure that is always frowned upon in all languages, Javascript, PHP, etc. Why should it be in Sass?

**Comment by lolmaus** [comment]
That's a very ugly practice. Why are you not using a hash instead (an object in JS and a map in Sass, with key-value pairs)?

**Comment by lagden** [comment]
Wowww!!! eval is not evil!!! huauhahu...

@lolmaus How can I make a push for $map in Sass?

**Javascript Example**

``` javascript
var boxSize = 140;
var boxSpace = 5;
var map = {};

function calcBoxSize(size) {
    return boxSize * size + boxSpace * ((size - 1) * 2);
}

for(var i = -1; ++i < 10;)
    map['boxSize' + i] = calcBoxSize(i);

console.log(map.boxSize1); // 140
console.log(map.boxSize2); // 290
```

**Comment by Anahkiasen** [comment]
You can just do `map-merge($map, ("boxSize#{$i}", calcBoxSize($i))` I'm guessing. Not sure if we have a map-set yet or not. Then `map-get($map, 'boxSize1')`

**Comment by lolmaus** [comment]
@Anahkiasen, you forgot an assignment and lost a bracket. Should be:

```
$map: map-merge($map, ("boxSize#{$i}", calcBoxSize($i)))
```

If you're lucky to use Compass and Bundler, try [Sassy Maps](https://github.com/Team-Sass/Sassy-Maps/). They lt you do this:

```
$map: map-set($map, "boxSize#{$i}", calcBoxSize($i))
```

Saves you one layer of parens.

**Comment by Anahkiasen** [comment]
Yeah sorry I'm typing from my phone so this was just, like, to give the idea :D

**Comment by lagden** [comment]
Yep!! Works!!
But `eval` is nice, people do bad use!

Thanks!!

**Comment by lolmaus** [comment]
Also, you kinda don't need interpolation:

```
$box-sizes: map-set($box-sizes, $i, calcBoxSize($i))
```

And if you have the `calcBoxSize()` function, why don't you use it directly without storing its output in a map? I doubt there would be a performance impact.

**Comment by lagden** [comment]
In the end...

**Map solution**

``` sass
// Boxes vars
// -------------------------
$boxSize: 140px
$boxSpace: 5px
$boxMap: ()

// Boxes Helpers function
// -------------------------
@function calcBoxSize($size)
    @return $boxSize * $size + $boxSpace * ($size - 1) * 2

// Boxes
// -------------------------
@for $c from 1 through 10
    $boxMap: map-merge($boxMap, ($c: calcBoxSize($c))) !global

@debug map-get($boxMap, 1)
@debug map-get($boxMap, 2)
@debug map-get($boxMap, 3)
```
