### ISSUE TITLE
Variable name 'grey' is changed in compilation

### ISSUE THREAD

**Issue by seanislegend** [sass/sass#1201]
I've a colour scheme map, like so:

``` css
$colors: (
    twitter: #00aaed,
    facebook: #455fa2,
    instagram: #497a9e,
    grey: #2a2a2a
);
```

I'm looping through these colours to create button styles, like so:

``` css
.button {
    @each $key, $value in $colors {
        &--#{$key} {
            @include button-colors($key);
        }
    }
}
```

The expected output of this would be:

``` css
.button--grey {
    ...
}
```

However, the key of 'grey' is being changed to 'gray' when I compile my code, giving me:

``` css
.button--gray {
    ...
}
```

I'm currently using SASS 3.3, but I'm sure this was experienced in 3.2 also. Please let me know if you need me to provide any more information.

**Comment by seanislegend** [comment]
It's also worth noting that if I use a key of 'dark-grey', for example, this is not changed. It's only when it's just 'grey'.

**Comment by lolmaus** [comment]
This happens because:
1. Map keys are parseable.
2. When Sass parses a piece of text, it tries to treat it as a color before deciding that it's a string.

Solution: quote strings. Sass won't try to treat quoted text as colors.

Demo: http://sassmeister.com/gist/9973238

**Comment by seanislegend** [comment]
That makes sense. Quotes will do. Thanks for the quick reply!

**Comment by chriseppstein** [comment]
Hmmm. I would have thought that #363 would have fixed this. Still, @lolmaus is right, if you require an exact string, use quotes for words that are also colors -- compressed output could result in a selector you don't want.

**Comment by seanislegend** [comment]
I'm on 3.3 currently, not 3.4, which may be why.

**Comment by chriseppstein** [comment]
3.3 is the latest and should have that bug fix.

**Comment by nex3** [comment]
#363 is only fixed on master, not stable.
