### ISSUE TITLE
Duplicated output from @extend when scss partial imported multiple times

### ISSUE THREAD

**Issue by JakeElder** [sass/sass#1202]
Thanks for the great work.

I've taken to writing scss modules that import all their dependencies, in order to make them as portable and explicit as possible. EG

**_type.scss**

```
%type-0 { color: red; }
```

**_carousel.scss**

```
@import "type";
%carousel { @extend %type-0; }
```

**_accordion.scss**

```
@import "type";
%accordion { @extend %type-0; }
```

**default.scss**

```
@import "carousel";
@import "accordion";
.carousel { @extend %carousel; }
.accordion { @extend %accordion; }
```

When default.scss is compiled, I would expect

```
.carousel, .accordion {
  color: red; }
```

Actual:

```
.carousel, .accordion {
  color: red; }

.carousel, .accordion {
  color: red; }
```

gzip will mitigate the cost attached to the increased file size, but I'm wondering if this is intended behaviour?

**Comment by nex3** [comment]
The issue is that `@import` always creates a new copy of the stylesheet you're importing, so there are two copies of the selectors you're `@extend`ing. I'm closing this as a duplicate of #156.
