### ISSUE TITLE
Dependency on Listen makes --watch unable to run more than once on OSX 10.9

### ISSUE THREAD

**Issue by tbremer** [sass/sass#1212]
Listen won't install on OSX 10.9 which makes the --watch side of SASS unusable.

**Comment by tbremer** [comment]
The dependency failure wasn't on Listen it was in nio4r, investigating there now.

**Comment by tbremer** [comment]
I got this to work and the failure seems to happen in two separate gems, listen and nio4r, installing them is currently hacky at best, but can be preformed by the following:
`ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install listen`

As mentioned nio4r was also failing so you might have to install that dependency separately using the same method:
 `ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install nio4r`

**This appear to be an issue with the ruby 2.0.0p247 and XCODE 5.1 in the release notes it says:**

> The Apple LLVM compiler in Xcode 5.1 treats unrecognized command-line options as errors. This issue has been seen when building both Python native extensions and Ruby Gems, where some invalid compiler options are currently specified.
> Projects using invalid compiler options will need to be changed to remove those options. To help ease that transition, the compiler will temporarily accept an option to downgrade the error to a warning:
> 
> -Wno-error=unused-command-line-argument-hard-error-in-future
> 
> To workaround this issue, set the ARCHFLAGS environment variable to downgrade the error to a warning.
> 
> ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install GemName

**Comment by chadjuehring** [comment]
I'm not necessarily sure I have the exact same issue, but after upgrading sass to 3.3.4, my `sass --watch` command is now broken on Mavericks as well.

sqlite3 was the hang up for me during the `$ gem update sass` process.

Passing the above environment variable before the upgrade helped me to build sqlite3, but now `sass --watch` crashes for me with the following error:

> Errno::EACCES: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-13/2.0.0/sqlite3-1.3.8/gem_make.out
>   Use --trace for backtrace.

**Comment by tbremer** [comment]
I was revisiting this again today, it appears that listen is failing on more complicated scss environments but isn't on a light weight skin.

For instance, Listen always functions as expected when my SCSS, mixins, functions, addons and partials are all within a couple relative directories, but when I have a more complicated environment (symlinked directories, large dependencies (like FontAwesome and Bourbon) then listen seems compiles once and fails quietly in the night.

After reading through some of the issues I thought it could be the Symlink issue (https://github.com/guard/listen/issues/25), however when removing my symlinks the SCSS Files still won't compile.

**Comment by tbremer** [comment]
@chadjuehring If you run: 
`sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem update`
and allow all of your gems do update, can you then compile?

**Comment by chadjuehring** [comment]
Thanks for following up! I can usually get things to at least build with that environment variable, but the libraries do not seem to be usable after that for me.

I was able to get things working by following these recommendations:

https://github.com/Team-Sass/breakpoint/issues/96#issuecomment-38434009

**Comment by tbremer** [comment]
YEAAAAH. I don't know whats happening anymore, I can't compile with complicated stylesheets any longer. I have tried lots and lots of workarounds, downgrading to 3.2.19 until I can get a stable version up and running.

**Comment by nex3** [comment]
You shouldn't need to install any extra gems to use `sass --watch`. It includes a bundled version of `listen` which should work out of the box, in part because gems like `nio4r` are so difficult to install.

@tbremer Can you provide an example stylesheet directory that you're seeing compilation problems on? Also, can you run `gem list listen` and include the output here?

@chadjuehring Can you run `sass --trace --watch` in the directory you were seeing the sqlite3 error in and include the output here? There shouldn't be anything loading sqlite3 at all, so that's very puzzling. It may also help if you can include the output of `gem list listen` as well.

**Comment by chadjuehring** [comment]
When I tried to use `gem update` and the builds were failing, I was able to get things to ~~work~~ build with the frequently-recommended 

`ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install` + $somegem

Though it seemed happy to build all extensions needed (including sqlite3) and everything looked ok, it would mysteriously crash on `sass --watch`, complaining about sqlite3.

I no longer have the environment set up in a way to replicate it with a `sass --trace --watch`, but I did copy my error logs into a [pastebin](http://pastebin.com/umsG0R72) when I was scouring the IRC for help.

I know this is far less helpful than seeing the stack trace, sorry. If it helps, I got into this situation with Xcode 5.1 + latest command line tools + the default 10.9.2 included version of Ruby.

Since I've switch away from the default Apple provided version of Ruby, things have been working just fine.

**Comment by nex3** [comment]
I can't fathom why running Sass would try to _compile_ sqlite3. @chadjuehring, did it look like it was actively compiling, or just printing some output that was stored somewhere?

If anyone else is seeing this issue, getting a stack trace for it would be great.

**Comment by chadjuehring** [comment]
From what i could tell, it seemed to be dumping the contents of a
gem_make.out file, but unfortunately I also have absolutely zero idea why
that would happen.

On Fri, Apr 11, 2014 at 3:56 PM, Nathan Weizenbaum <notifications@github.com

**Comment by tbremer** [comment]
@nex3, thanks for the response.... Here is the file structure we are currently using with a little bit of explanation on whats happening:

```
RED-CARPET
    >GLOBAL
        >ASG
            +12 partials
        >BLUEPRINTS
            • 1 partial
        _blueprints (BLUEPRINT partial include)
        _colors (color variables)
        _global (includes BLUEPRINTS, COLORS, ASG, & class name definitions)
    >MODULES
        scss stylesheets -- no partials
    _bootstrap (partial containing references to symlinked directory sass_lib, plus non-symlinked _colors variables)
    red-carpet.scss
        • references _bootstrap
        • references files on symlinked sass_lib
            Global reset
            fontstack output
            fontawesome
        • references GLOBAL/global

SASS_LIB (SYMLINKED from a few directories back in our git file tree)
    >BOURBON
        >3.1.8
            • Typical Bourbon install

    >FONTAWESOME
        • Typical fontawesome install
    >FONTSTACKS
        SCSS Files that output the font-styles for any give stylesheet
    >MIXINS
        homebrewed mixins, these get pulled into our bootstrap
    >RESETS
        global reset, nothing too exciting
```

Here is a screen shot, if that helps visualize anything for you:
![screen shot 2014-04-12 at 10 35 05 am](https://cloud.githubusercontent.com/assets/2998575/2687511/4819b974-c25a-11e3-8c75-53f656f0c87e.png)

Next: if i run `gem list listen` the output it:

```
[tom.bremer] ~ $ gem list listen

*** LOCAL GEMS ***

```

If I run: `gem list` I get:

```
[tom.bremer] ~ $ gem list

*** LOCAL GEMS ***

bourbon (3.1.8)
CFPropertyList (2.2.0)
chunky_png (1.3.0)
compass (0.12.5)
fssm (0.2.10)
hitimes (1.2.1)
libxml-ruby (2.6.0)
nokogiri (1.5.6)
rb-fsevent (0.9.4)
sass (3.3.4, 3.2.19)
sqlite3 (1.3.7)
thor (0.19.1)
```

And, finally here is the sass --watch I will typically run for this project: 

```
sass --watch --no-cache --style compressed --trace /var/www/html/COMPANY/REPO/SASS/red-carpet:/var/www/html/COMPANY/REPO/SITE/htdocs/includes/css
```

When I run said watch (with changes) this is the output:

```
[tom.bremer] ~ $ sass --watch --no-cache --style compressed --trace /var/www/html/COMPANY/SITE/SASS/red-carpet:/var/www/html/COMPANY/SITE/REPO/htdocs/includes/css
>>> Sass is watching for changes. Press Ctrl-C to stop.
DEPRECATION WARNING on line 25 of /var/www/html/COMPANY/SITE/SASS/sass_lib/bourbon/3.1.8/addons/_html5-input-types.scss:
Assigning to global variable "$unquoted-inputs-list" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$unquoted-inputs-list: append($unquoted-inputs-list, unquote($input-type), comma) !global" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 36 of /var/www/html/COMPANY/SITE/SASS/sass_lib/bourbon/3.1.8/addons/_html5-input-types.scss:
Assigning to global variable "$all-text-inputs-hover" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$all-text-inputs-hover: append($all-text-inputs-hover, $input-type-hover, comma) !global" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 44 of /var/www/html/COMPANY/SITE/SASS/sass_lib/bourbon/3.1.8/addons/_html5-input-types.scss:
Assigning to global variable "$all-text-inputs-focus" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$all-text-inputs-focus: append($all-text-inputs-focus, $input-type-focus, comma) !global" instead.
Note that this will be incompatible with Sass 3.2.

      write /var/www/html/COMPANY/SITE/REPO/htdocs/includes/css/red-carpet.css
```

Edit note: I have tried creating the directories directly & not symlinking anything with no positive results.

**Comment by nex3** [comment]
@tbremer is there any chance you could tar up your directory and send it to me so I can test it locally?

**Comment by tbremer** [comment]
@nex3 gladly -- whats the best way to get this to you?

Also, in preparing to send you the directories I wanted to test everything again.

Uninstalled and reinstalled SASS (it updated to version 3.3.5). I put the directories on my Desktop (~/Desktop) and was able to compile the css as would be expect. Though I did get the "Listen will fall back to polling" error.

Are there any known issues of running sass --watch on a separate partition? Like, I have a my User / System HD (Macintosh HD) and a separate partition on the same HD (CODE) where all of my codebases live.

So I am running sass from /Volumes/Macintosh HD & the code is compiling from & to : /Volumes/CODE

**Comment by nex3** [comment]
> @nex3 gladly -- whats the best way to get this to you?

Email it to nex342@gmail.com.

> Uninstalled and reinstalled SASS (it updated to version 3.3.5). I put the directories on my Desktop (~/Desktop) and was able to compile the css as would be expect. Though I did get the "Listen will fall back to polling" error.

It's strange that it would fall back to polling. Do you still have `rb-fsevent` installed?

Does this mean you can no longer reproduce the issue you were seeing earlier?

> Are there any known issues of running sass --watch on a separate partition? Like, I have a my User / System HD (Macintosh HD) and a separate partition on the same HD (CODE) where all of my codebases live.

This shouldn't matter, but it's not impossible that it does. If you can still reproduce the issue, do you also see it if you build the same project on your User partition?

**Comment by tbremer** [comment]
@nex3 Emailed!

> It's strange that it would fall back to polling. Do you still have rb-fsevent installed?

You were right about rb-fsevent, I forgot to reinstall after installing SASS again, does not fall back to polling now.

> Does this mean you can no longer reproduce the issue you were seeing earlier?
> This shouldn't matter, but it's not impossible that it does. If you can still reproduce the issue, do you also see it if you build the same project on your User partition?

The error seems to only present when I am running a sass --watch from code partition. I should say I can and have successfully updated my stylesheets by running a sass --update and can compile individual files by pointing to their direct *.scss files

**Comment by nex3** [comment]
@tbremer I can't reproduce this; I may not be doing it right, or it may be because I'm not on OS X. Can you explain exactly what you're modifying that's causing it not to recompile? Are there any files that _do_ cause it to recompile?

Also, can you reproduce this if you install a different version of listen via `gem install listen`?

**Comment by tbremer** [comment]
I am convinced this is a lone issue that has to do something with our larger file structure. I have tried testing this in many different scenarios and the one thing I keep coming back to is our actual codebase. So, it's something to do with the way that we architected our directory structure.

I have found a suitable work around using FSWatch (from Homebrew) and running a `sass --update $scss:$css` -- while this isn't ideal, it has proven to be stable.

Also @nex3, sorry for the long delay in response time.

I was discussing this with another developer on my team and he is running sass 3.2.19 just fine (without listen work arounds) were there changes in the listen part of the 3.3.x?

Working with the same developer he encounters the same issue with SASS 3.3.7, but is on OSX 10.8, so, it seems to be isolated to our directory structure,  but not to OS version

**Comment by tbremer** [comment]
I found this related issue that seems to be true for me: https://github.com/chriseppstein/compass/issues/1488

Seems like something about running a compiler in a different partition is what is breaking.

**RUBY** installed: Volumes/Macintosh HD/*
**Code** is compiling from: Volumes/CODE/*

**Comment by nex3** [comment]
> I was discussing this with another developer on my team and he is running sass 3.2.19 just fine (without listen work arounds) were there changes in the listen part of the 3.3.x?

Yes, 3.3.x changed a number of details about how Listen was installed, including the version that was bundled with Sass.

> I found this related issue that seems to be true for me: chriseppstein/compass#1488

This issue is about sourcemap generation, which seems unlikely to be related.

Since I still can't reproduce this or figure out why it would be going wrong, I'm going to close the issue. If you or anyone else can come up with a patch that fixes it, let me know; also consider mentioning this to the folks who write [guard/listen](/guard/listen).
