### ISSUE TITLE
Inconsistent selector styles across CSS frameworks (bootstrap, oocss, inuit, zurb, etc)

### ISSUE THREAD

**Issue by stubbornella** [sass/sass#1213]
I recently started a project where I wanted to use some components from Bootstrap, some from Inuit, and some from OOCSS. I really wanted to pick the _best in class_ component for each use case, but I ran into trouble when I tried to use multiple frameworks.

Different frameworks use `.camelCase`, `.snake_case`, or `.dashed-class` css selectors. This was frustrating, because the developers on my team would need to remember which classes used which selector-style. (It also just offended my sensibilities because, while I don't care which code standard we choose, I do care that we choose just one)

I'd love it if Sass could help me make the framework output more uniform. For example, perhaps I would pass a flag `--selector-style=camelCase | snake_case | dashed`, and Sass could convert OOCSS to use the dashed selectors my team has standardized around.

There are a couple (harder) edge cases. I asked on twitter, but so far no one admits to `.SHOUTING_SNAKE_CASE`, so it may not be worth the time. OTOH, loads of people use BEM, and I'm not sure how that would convert. You certainly couldn't convert from dashes to BEM, because you wouldn't have enough information.

Another interesting edge is if you had certain selectors you didn't want converted. (Say the selectors associated with a twitter feed widget whose markup you don't control). What immediately came to mind is CSSJanus (an RTL tool) and it's `/* no-flip */` comments you can add to sections of the code you do not want converted. There must be a better syntax for that than comments, but I'm unsure what that would be.

**Comment by stubbornella** [comment]
Well, it seems someone does use shouting snake case:

https://twitter.com/stubbornella/status/454513742697340928

**Comment by cimmanon** [comment]
What do you think should happen when you have a collection of libraries that manage to give you the following class names: `.fooBar`, `.foo-bar` and `.foo_bar`?  If even just 1 class manages to overlap after the conversion is done, you're going to have unexpected results if there are extends involved.

**Comment by nex3** [comment]
This sounds like a great use-case for an external script that uses the Sass Ruby API, but I don't think it's a good fit for the core of Sass.

**Comment by stubbornella** [comment]
@nex3 - You already do this for variables (making $foo-bar and $foo_bar equivalent). I think this is simply an extension of the policy to be code aesthetic neutral. It would make it possible to actually choose best in class components rather than being stuck choosing monolithic libraries. IMO, that makes it worthy of Sass-core.

@cimmanon - You already have to be careful about name collisions & scope when using multiple libraries. Hopefully, being able to choose best in class components rather than getting stuck with an entire library would mean that components that are not scoping well and/or using generic class names would be much less likely to be used.

**Comment by stubbornella** [comment]
That said, I absolutely understand the desire to only include essential features in Sass core. However, I think that components have become a fundamental part of how the web is developed and we need to make sure Sass is going to be able to support that.

**Comment by Snugug** [comment]
What is recommend is, while you're choosing the best components, namespace them yourself into what you think is usable via `@extend`

**Comment by chriseppstein** [comment]
@nex3 Enabling mix-and-match frameworks is a core use case for sass. Every framework that generates selectors could build selector style generation into their capabilities but that's a lot of work and it's unlikely that any framework would do this given the readability impact to their code.

@snugug That would be fine if the framework exposes a placeholder API, but this use case is to support frameworks that are generating css selectors. Extend is not a good way to accomplish this.

**Comment by stubbornella** [comment]
Yeah, these libs aren't built with placeholder selectors. You could argue that they should be, but I'm not so sure since you do end up wanting to use most of their classes and it would make interacting with the libraries much more complex.

**Comment by Snugug** [comment]
@chriseppstein I'd argue that the core ask is to be able to normalize class names across multiple frameworks in a controlled way. Assuming an individual framework doesn't share the exact same class name (and said class name doesn't do something different across multiple frameworks) that `@extend` would work for that. If it doesn't fit that case, you'll have a problem regardless of if Sass did it automatically or not. Ideal, no, but a totally workable solution.

**Comment by chriseppstein** [comment]
@snugug you're mistaken. Extend is not suitable for this use unless they are using placeholders. Consider the selector `.a_b .c_d` if you want to extend this to use dashes `.a-b { @extend .a_b; } .c-d {@extend .c_d; }` would produce `.a-b .c-d`, but it would also produce three other selectors that are not desired.

**Comment by Snugug** [comment]
@chriseppstein I happen to know that the frameworks she's talking about so not use compound class selectors so while you are absolutely correct, that is not the use case here.

**Comment by chriseppstein** [comment]
@snugug and then one day the library makes a nondescript change and it is true. Its clear that extend doesn't solve the generalized use case. Even if what you say is true, the stylesheet now has two concrete selectors instead of one for each original class and the HTML could use either convention.

**Comment by nex3** [comment]
@stubbornella Hyphen-neutrality in variables and mixins is less about a policy of being aesthetically neutral and more about historical backwards-compatibility with stylesheets that were written before we allowed hyphens in Sass identifiers.

@chriseppstein We can support this explicitly by supporting the ability to `@use` a stylesheet in a way that makes its selectors visible for extension but not emitted directly to the stylesheet. That's a feature I'd like to support anyway, and it supports arbitrary remappings in addition to the specific ones requested here.

I don't like how implicit this is; I don't like command-line flags modifying the behavior of stylesheets; I don't like plain CSS having different semantics than it would in the browser; and I don't like building in knowledge of naming styles to Sass. There are a lot of things going against this change, and I don't see much reason not to just handle it externally or explicitly.
