### ISSUE TITLE
add support for shorthand similar to !default for variable-exists, maybe !existing

### ISSUE THREAD

**Issue by gabriellecrawford** [sass/sass#1214]
variable-exists is very helpful when you want to figure out if something has been set to null, but it's not so pretty to write this for every var that the user may have set to null.
if(variable-exists(bodyBgImage), $bodyBgImage, ....);

can we have a syntax similar to !default for this case, like !existing? For example:

$bodyBgImage: foo.png !existing;

**Comment by nex3** [comment]
I don't think this is a broad enough use-case to warrant adding new syntax. For the most part, I think using `variable-exists` rather than checking for `null` isn't a great idea anyway, since it limits the user's ability to say "do the default thing".

**Comment by gabriellecrawford** [comment]
I'm confused how it limits the user? If they don't set anything, the default is used. But if the user has explicitly set the value to null, null is used. 

https://github.com/nex3/sass/issues/887

**Comment by gabriellecrawford** [comment]
also see https://github.com/nex3/sass/issues/887

**Comment by nex3** [comment]
It's useful for the user to have a way to explicitly say "don't do anything for this". For example, if they use a function to compute the value of the variable, that function should be able to indicate that the default value should be used. That's why `!default` checks for `null` in the first place: because `null` is the best way to indicate "use the default value".

**Comment by gabriellecrawford** [comment]
I see, thanks!

I guess what I'm looking for is a prettier way for the user to say don't use any value at all including the default. Could something like this work?

$myVar: undefined;
$myVar: blue !default;

Probably the answer is "I don't think this is a broad enough use-case to warrant adding new syntax.", but thought I'd ask. :)

**Comment by nex3** [comment]
A CSS-y approach would be to have them write `$myVar: none;` and detect that string in particular.

**Comment by gabriellecrawford** [comment]
Yes, though that approach requires coding up every var they might want to set to none, adding doc that the value can be set to none or whatnot, etc. 

I'm looking for a generic sass approach to letting them explicitly "null out" the variable if they don't want to use any value at all. It seems like a generic issue sass could handle, no?

**Comment by nex3** [comment]
My experience with JavaScript tells me that it's more trouble than it's worth trying to encode a distinction between `null` and `undefined` at the language level. I think in most cases, configuration variables won't want this distinction, and for those that do, `none` is a pretty good option that matches the aesthetic of CSS.

**Comment by gabriellecrawford** [comment]
Having to code and doc for none is a drag.

I'm not actually trying to encode undefined, so forget that if it's distracting. I'm trying to find a generic way to tell the defaulting system to override the default value to null. That seems perfectly legit.....
