### ISSUE TITLE
Using the & in multiple selectors (SASS 3.3.5)

### ISSUE THREAD

**Issue by pashachee** [sass/sass#1216]
Hello!

Simple example here:

```
.block {
  &_mod-1 {
    // some rules...
  }
  &_mod-2 {
    // some rules...
  }

  &_mod-1&_mod-2 {
    // some rules...
  }
}
```

That's what I expect to get:

```
.block_mod-1 {
  // some rules...
}
.block_mod-2 {
  // some rules...
}
.block_mod-1.block_mod-2 {
  // some rules...
}
```

but I get an error like this: 

```
Invalid CSS after "  &_mod-1": expected "{", was "&_mod-2 {"
```

Is there a way to get what I expect?

Thanks!

**Comment by yyclaw** [comment]
`&_mod-1#{&}_mod-2` ?

**Comment by pashachee** [comment]
Hi, jsw0528 
Thanks for your reply!
This is the first thing I tried to do. But it doesn't work too. Unfortunately :(

**Comment by nex3** [comment]
Even with the additional power in 3.3, `&` still needs to be used at the beginning of an identifier. #1117 will likely make this possible, though.
