### ISSUE TITLE
Why not placeholder-exists?

### ISSUE THREAD

**Issue by yyclaw** [sass/sass#1217]
There are `function-exists`, `mixin-exists` and `variable-exists`, why not `placeholder-exists`?

**Comment by lolmaus** [comment]
Nice catch. Could be useful for a custom mechanism for extending from media queries, for example.

**Comment by cimmanon** [comment]
https://github.com/nex3/sass/issues/901

**Comment by nex3** [comment]
Yep, this is a duplicate. Thanks @cimmanon.
