### ISSUE TITLE
Intelligent SASS imports

### ISSUE THREAD

**Issue by drewwells** [sass/sass#1218]
Modern web development is much more than translating design to code.  We must consider how different pages inherit code, when to override styles vs fork code, managing a/b tests and managing file size and build time considerations.

In doing so, we have hit a major hurdle with SASS.  Something I'm finding easily supported by [less](http://lesscss.org/features/#variables-feature-import-statements).

In order to continue using SASS, our developers find themselves copying large portions to dance around the inflexibility in the import/build philosophy of SASS.  Here's an example.

Home Page is made of many sass partials.

Home
- Base
  - sprite
  - font
  - layout
- Modules
  - Section
  - Widget
- Header
  - Search bar
  - Header links

Let's say I run a test that changes the styling of the Search bar.  In an ideal world my Header partial would look something like this:

```
@import $search_bar; //Default values when variable is undefined would be even better
```

In the test, I would set $search_bar to `"_new_search_bar"`.  Due to the static importing this is not possible.  I must fork `Home` make a copy of `Header` just to change the one line `@import "_new_search_bar"`.

The process of copying and pasting SASS is proving unsustainable as an organization.  We require more flexibility. #1094 Paths is a nice step forward, but inevitably we need more fine grained control of what partials are loaded in a target.

Earlier today, we brainstormed the ideal solution for this.  It hinges on dynamic imports.

control.scss

``` sass
@import "paths";
@import "header"
```

_paths.scss

``` sass
$search_bar: "_search_bar";
```

_header.scss

``` sass
@import $search_bar;
```

test.scss

``` sass
@import "paths";
@import "test_overrides";
@import "base";
@import "header";
```

_test_overrides.scss

``` sass
$search_bar: "_new_search_bar";
```

By making every import a variable, the developer can pick and choose what files to replace and what styles to override.  This is something we are deeply interested in and would like to know how you plan to facilitate this use case.

**Comment by nex3** [comment]
Duplicate of #739.

At least for now, I suggest you put the contents of the files that you want to dynamically import into mixins, and dynamically include the mixins instead.
