### ISSUE TITLE
--require option on sass compiler doesn't work

### ISSUE THREAD

**Issue by adriantoine** [sass/sass#1219]
Hello!

I just opened an issue on the susy repo: ericam/susy#327.

The latest susy version is supposed to work without compass but it looks like the sass command line compiler doesn't load susy with the `--require` option.

When I use this command line:
`$ sass assets/sass/screen.scss public/css/screen.css --require susy`

I get this error:

```
Syntax error: File to import not found or unreadable: susy.
              Load path: c:/Users/a.antoine/Git/flashcards (DEPRECATED)
        on line 4 of assets\sass\_base.scss
        from line 4 of ./assets/sass/screen.scss
  Use --trace for backtrace.
```

Whereas it works fine with the compass compiler:
`compass compile --sass-dir=assets/sass --css-dir=public/css --require susy`

There is a workaround consisting of adding the susy sources from the gem in the `--load-path` option:
`$ sass assets/sass/screen.scss public/css/screen.css --load-path C:/Ruby200/lib/ruby/gems/2.0.0/gems/susy-2.1.1/sass`
That works, but it's not very clean and flexible.

Can anyone help?

Thanks!

**Comment by nex3** [comment]
In general, the means of loading Ruby extensions is handled by Ruby itself, not Sass. In this case, your `GEM_HOME` environment variable is probably set incorrectly. Fixing that will depend on your local operating system configuration.
