### ISSUE TITLE
Sass-convert dying with undefined method 'build' for module `Less::StyleSheet::Mixin4' (NameError)

### ISSUE THREAD

**Issue by nemlah** [sass/sass#122]
/home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/less.rb:40:in `alias_method': undefined method`build' for module `Less::StyleSheet::Mixin4' (NameError)
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/less.rb:40:in`module:Mixin4'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/less.rb:14:in `<module:StyleSheet>'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/less.rb:9:in`module:Less'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/less.rb:5:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:624:in`block in process_file'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/util.rb:297:in `silence_sass_warnings'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:619:in`process_file'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:589:in `block in process_directory'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:564:in`glob'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:564:in `process_directory'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:529:in`process_result'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:41:in `parse'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/lib/sass/exec.rb:21:in`parse!'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/gems/sass-3.1.3/bin/sass-convert:7:in `<top (required)>'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/bin/sass-convert:19:in`load'
    from /home/nemlah/.rvm/gems/ruby-1.9.2-p136/bin/sass-convert:19:in `<main>'

Looked into the lessc gem but couldn't find the module it is trying to patch..

**Comment by chriseppstein** [comment]
Is ruby less installed and what version do you have?

**Comment by r38y** [comment]
I'm getting the same error with less 2.0.5. I'm trying to dig into it to figure it out. Is there a version of less that is known to work with this?

**Comment by pdelanauze** [comment]
Yep, same here.. tried less 2.0.5 - 2.0.2 and sass 3.1.2 - 3.1.4

```

/Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/less.rb:40:in `alias_method': undefined method `build' for module `Less::StyleSheet::Mixin4' (NameError)
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/less.rb:40:in `<module:Mixin4>'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/less.rb:14:in `<module:StyleSheet>'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/less.rb:9:in `<module:Less>'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/less.rb:5:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/exec.rb:624:in `block in process_file'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/util.rb:297:in `silence_sass_warnings'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/exec.rb:619:in `process_file'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/exec.rb:538:in `process_result'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/exec.rb:41:in `parse'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/lib/sass/exec.rb:21:in `parse!'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/gems/sass-3.1.4/bin/sass-convert:7:in `<top (required)>'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/bin/sass-convert:19:in `load'
    from /Users/pat/.rvm/gems/ruby-1.9.2-p0/bin/sass-convert:19:in `<main>'
```

**Comment by chriseppstein** [comment]
I'm not sure how much value this adds anymore given that most people are using less.js which has many syntax differences from the ruby version.

**Comment by pdelanauze** [comment]
agreed, i was simply going to use it once to merge some stuff back to sass, ended up doing it by hand.

**Comment by Haegin** [comment]
I've got the same problems - Is there any plan to support the ruby less stuff still?

**Comment by wolfeidau** [comment]
Looks like the latest version of less.rb is just wrappers for the less.js.

Gemspec requires V8, which is loaded and used to exec less.js.

Mite be an idea to include some sort of deprecation warning so others don't get lead on a goose chase like I was :)

**Comment by elfassy** [comment]
+1

**Comment by smt** [comment]
+1

`sass 3.1.10` && `less 2.0.7`

**Comment by slbug** [comment]
samw thing with sass 3.1.11 && less 2.0.8

**Comment by ndftz** [comment]
+1

**Comment by varley** [comment]
+1 
same deal with sass 3.1.12 and less 2.0.8. I was excited enough about to try a number of combinations of earlier point releases from both libs, but same result. dashed hopes (for an easy conversion path)

**Comment by chriseppstein** [comment]
Less.rb is old and deprecated, it doesn't support the current less syntax. A less to sass converter is a good thing to have, but a rewrite of this feature is required to achieve that.

@nex3, I'm going to remove the less support from sass-convert unless you object. I think a less to sass converter can and should be provided by a separate project -- maybe it would be built on less.js's internals instead of sass's.

**Comment by nex3** [comment]
@chriseppstein No objections here. Probably want to have "--from less" etc print an error through 3.2, though.

Maybe the best way to have "--from less" working in future is to use less.js to parse the file, then dump it to JSON and load it into Sass? It seems easier than rewriting sass/tree in Javascript.

**Comment by chriseppstein** [comment]
It's an interesting approach also.

**Comment by MSch** [comment]
So is there any way to semi-automatically convert less->scss right now?

**Comment by nex3** [comment]
@MSch Not currently, no.

**Comment by chriseppstein** [comment]
It's a simple fix, let's get this into 3.2.

**Comment by nex3** [comment]
@chriseppstein You mean having "--from less" print an error?

**Comment by chriseppstein** [comment]
yes.
