### ISSUE TITLE
support author defined prefix as per CSSWG decision

### ISSUE THREAD

**Issue by bkardell** [sass/sass#1221]
It was decided recently that there should be a standard strategy for author defined prefixes moving forward.  Like vendor defined prefixes these are non-standard CSS, unlike vendor defined, they will generally be defined via script and author linked.  As per the resolution these will always follow double-dash, so that:

-moz-something   //indicates vendor prefix
--something          //indicates author prefix

See:
http://lists.w3.org/Archives/Public/www-style/2014Mar/0474.html

**Comment by nex3** [comment]
Merging this with #1128, since currently these identifiers aren't used outside of variables.

**Comment by bkardell** [comment]
Other projects are working on polyfills and prollyfills for custom css
things - we'd like them to be able to work in tandem with our favorite CSS
tools, but if sass barfs on them, that would be a major roadblock/detriment
to progress.  Please reconsider this one as it is a Really Good Thing™ if
we can work together as a community to drive better standards, expand
participation, tighten the feedback loop and reduce the dependency on
particular vendors to do it.

**Comment by nex3** [comment]
We're certainly planning on supporting this, it's just being tracked by issue #1128 now.
