### ISSUE TITLE
Color functions issue

### ISSUE THREAD

**Issue by ricardozea** [sass/sass#1223]
Not sure what's going on but I am unable to use several color functions: `tint()` and `shade()`.

**Examples**

I have these rules:
1. `.highlight { background:tint(#369, 20%); }`
2. `.highlight { background:shade(#369, 20%); }`

And they compile to this:
1. `.highlight { background: tint(#336699, 20%);}`
2. `.highlight { background: shade(#336699, 20%);}`

Screen capture of the issue:

![some color functions not working in sass](https://cloud.githubusercontent.com/assets/1656481/2757911/0048093e-c98a-11e3-9428-e603fd95a053.gif)

I'm using Sass 3.3.4.

Any idea why is this happening?

Thanks,

**Comment by lolmaus** [comment]
Can you reproduce it on http://sassmeister.com/ ?

**Comment by ricardozea** [comment]
No, it works just fine in sassmeister.com.

Going to update my Sass and let's see if that works.

**Comment by Snugug** [comment]
Sass 3.3.4 does not have built in tint and shade functions, so Sass falls back to assuming you want to print the literal. It does, however, have a built in saturate function. For a full list of native Sass functions, se [the docs](http://sass-lang.com/documentation/Sass/Script/Functions.html)

As for it working on SassMeister, Compass has built in tint and shade functions which are included automatically (no imports needed), so you're actually getting Compass's functions there. Switch your compiler to Libsass to see what Sass would do w/o Compass's extra functions.

**Comment by ricardozea** [comment]
@Snugug Oh ok, well that makes sense now.

I was using the article below as a reference, but I can see that `tint()` and `shade()` are part of [Bourbon](http://bourbon.io/), and I was mistaken to think that they were Sass color functions. 

http://robots.thoughtbot.com/controlling-color-with-sass-color-functions

Looking forward to Sass supporting `tint()` and `shade()` some time soon.

Thanks!
