### ISSUE TITLE
Certain comment format causes extreamly long compile times

### ISSUE THREAD

**Issue by wdamien** [sass/sass#1228]
To reproduce create an empty test.scss file with only this contents:

```
/*
//*****************************************

```

Compile it; `sass test.scss test.css`, notice the extremely long compile times (on my system the cpu goes to 100% for ruby)

Eventually this error occurs:

```
Syntax error: Invalid CSS after "/*": expected /\//, was "//*************..."
        on line 1 of test.scss
```

Expected results:
The error occurs immediately.

More Information:
The time to error seems to grow exponentially when adding more stars (*)

Versions:
Sass 3.3.5 (Maptastic Maple)
osx 10.8.5
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by nex3** [comment]
It's possible this is the same error as #1226, but I'll need to investigate further to be sure.
