### ISSUE TITLE
Option to disable control directives

### ISSUE THREAD

**Issue by nashbridges** [sass/sass#123]
Hello!
I'm working on the safe bridging SASS and Jekyll, which, you may khow, is behind GH pages.
With Haml it was quite easy as we have :suppress_eval option. But for SASS it's still possible to use construction like:

```
$i: 0;
@while $i == 0 {
  .item-#{$i} { width: 2em * $i; }
}
```

and cause infinite loop. This is not a problem if we run SASS at the end-user machine, but it could be a problem for the Github.

Is it possible to pass to the SASS::Engine option like :suppress_conrol_directives whilst allow using valuable @import  directive?

**Comment by chriseppstein** [comment]
I suggest you place a timeout around the compilation step.

**Comment by nex3** [comment]
I came here to say the same thing as Chris. By disabling control directives, you'd be doing away with much of what makes Sass powerful, as well as any ability to use libraries like Compass. It's also still possible to do nasty things if you try hard enough, just by creating large stylesheets. A timeout is really the only foolproof way to deal with things like this.
