### ISSUE TITLE
Using variables for @import paths

### ISSUE THREAD

**Issue by planemad** [sass/sass#1231]
In the case that I want to use a variable to customize import paths easily:

```
$skin-folder: "defaultskin/" ;

@import $skin-folder+"settings";

```

Should ideally work, but I get the following error with compass:

```
Syntax error: Invalid CSS after \"@import \": expected file to import (string or url()), was \"$skin-folder; 
```

Is there a workaround to this because it is really convenient to use variables to customize image urls and it would be great if it could be used for @import as well.

**Comment by lolmaus** [comment]
You are not alone.
- https://github.com/nex3/sass/issues/115
- https://github.com/nex3/sass/issues/1094

**Comment by planemad** [comment]
Aha!

**Comment by planemad** [comment]
Err, not sure if I should leave this open or closed. I thought there was a mark as duplicate somewhere?

**Comment by lolmaus** [comment]
No need for a special duplicate status. Closed = does not need attention anymore.

Some repos use a label (aka tag) for marking issues as duplicates, but this one is not among those. You can always look inside to see how it was resolved.

**Comment by planemad** [comment]
Thanks.

On Sat, Apr 26, 2014 at 12:11 AM, lolmaus notifications@github.com wrote:

> No need for a special duplicate status. Closed = does not need attention
> anymore.
> 
> Some repos use a label (aka tag) for marking issues as duplicates, but
> this one is not among those. You can always look inside to see how it was
> resolved.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nex3/sass/issues/1231#issuecomment-41425964
> .

## 

 Arun Ganesh
(planemad) http://en.wikipedia.org/wiki/User:Planemad
