### ISSUE TITLE
Backslash behaviour for line continuation

### ISSUE THREAD

**Issue by robocoder** [sass/sass#1237]
I would expect:

```
X {
    content: "...\
...";
}
```

To compile to:

```
X {
    content: "......";
}
```

But it instead compiles to:

```
X {
    content: "...\ ...";
}
```

**Comment by nex3** [comment]
We have to follow CSS's parsing here, and it doesn't support backslash continuation of strings.

**Comment by robocoder** [comment]
If sass follows CSS parsing, why does sass join the lines together? (@hcatlin's libsass doesn't)

**Comment by Snugug** [comment]
Libsass is not the canonical Sass representation, Ruby Sass is. When there are differences in parsing between the two, Ruby Sass's behavior should be deferred to.

**Comment by robocoder** [comment]
I know that ruby sass is the reference implementation.  My point is that sass introduces parsing behaviour here that isn't present in CSS, and that behaviour, while undefined/unsupported, is aberrant.

**Comment by robocoder** [comment]
FYI http://www.w3.org/TR/CSS21/syndata.html#characters

> First, inside a string, a backslash followed by a newline is ignored (i.e., the string is deemed not to contain either the backslash or the newline). Outside a string, a backslash followed by a newline stands for itself (i.e., a DELIM followed by a newline).

**Comment by nex3** [comment]
Interesting, thanks for that link, @robocoder.
