### ISSUE TITLE
Lack of support for multiline strings

### ISSUE THREAD

**Issue by caiosm1005** [sass/sass#1238]
The following sample fails to compile in Sass

```
body:after {
    content: "This is a \
multiline string.";
}
```

Strings in CSS can have a newline followed by a backslash before the string delimiter. See the diagram: http://www.w3.org/TR/css3-syntax/#string-token-diagram

I would send a PR if I could, but I am not a Ruby developer. I'm opening this issue based on [this conversation in scssphp](https://github.com/leafo/scssphp/pull/165).

**Comment by Snugug** [comment]
This is a dupe of #1237
