### ISSUE TITLE
"grey" gets replaced by "gray"

### ISSUE THREAD

**Issue by danieldiekmeier** [sass/sass#1240]
![greygray](https://cloud.githubusercontent.com/assets/2098462/2888995/b36f0162-d514-11e3-82f5-0d73238834bf.jpg)

So I'm using a loop to generate several classes with as little markup as possible. It works almost perfecty, except that the word "grey" gets replaced by "gray" if it's standalone, but it doesn't get replaced it it's something like "grey-light".

I could, of course, just change everything to "gray", and I'll probably do that now, but I found this bug to be quite … weird and maybe it's something you want to look into.

**Comment by lolmaus** [comment]
![](http://i.memeful.com/memes/RZNNJAR/Imagination-Spongebob.jpg)

Search before posting: https://github.com/nex3/sass/issues/1201
