### ISSUE TITLE
Path length issues in @import

### ISSUE THREAD

**Issue by westy** [sass/sass#1241]
Hi,

Am having trouble with what I suspect is an import statement with too long a path, possibly related to #1076.

I'm using Ext JS 4.2 with Sencha Cmd 4, which bundles a version of SASS with it.

During the build process it has to import lots of different sass content. The recommended approach with sass is to mimic the classes namespace, so that only sass for classes that are referenced is included in the final css. Hope that makes sense.

Anyway, the statement that is failing is:
@import '../../../../../apps/LongNameThatIveChangedButSameLength/sass/src/LongNameThatIveChangedButSameLength/model/data/Clients/Client';

This is from a temporary build directory deep within a workspace, and none of the names are really changeable, at least not without changing namespace and class names etc.

That import statement fails, where as the following succeeds:
@import '../../../../../apps/LongNameThatIveChangedButSameLength/sass/src/LongNameThatIveChangedButSameLength/view/LoginWindow';

I've tried with empty files even, and it's definitely the import statement itself, and not the file content.

Any chance the path length could be increased to something more robust, since this is currently a deal breaker for me.

Cheers,
Westy

**Comment by nex3** [comment]
Sass itself doesn't have any restrictions on import lengths. Any problems you're seeing here ultimately come from the OS. I'm guessing you use Windows, which unfortunately has quite a low limit.

Issue #1076 was about Sass failing to optimally compress its paths before passing them off to the OS, and it's possible that the bundled version of Sass still suffers from that bug, in which case upgrading to a newer version might solve this.

**Comment by westy** [comment]
Ok, thanks for the response.

Bit confusing, since the Windows path length limit should be 260, and I'm seeing the issue with 126 chars. Have reported back to Sencha to see if they have any insights - http://www.sencha.com/forum/showthread.php?285168-import-does-not-appear-to-support-long-paths&p=1044167#post1044167

Cheers,
Westy

**Comment by nex3** [comment]
Keep in mind that the paths are concatenated with other paths before ultimately being sent to the OS, so that will increase their final length.
