### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1245]
These tests are getting out of hand. Need to refactor these and do so in a way that makes integration with https://github.com/hcatlin/sass-spec much easier.

```
     553 test/sass/plugin_test.rb
     849 test/sass/script_test.rb
     906 test/sass/source_map_test.rb
    1444 test/sass/extend_test.rb
    1884 test/sass/functions_test.rb
    2008 test/sass/conversion_test.rb
    3364 test/sass/engine_test.rb
   13391 total
```

**Comment by nex3** [comment]
Some more test improvements that would be great:
- Moving the tests from `test/sass` to just `test`.
- Making sure that all tests can be run with just `ruby path/to/test.rb`.
- Making sure that no tests write to or read from the working directory's `.sass-cache` directory.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
