### ISSUE TITLE
reading sass maps in ruby

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#1246]
I am looking to load my sass maps from a scss file into ruby, but was unable to find the right classes that handle this.  Maybe someone more familiar with the codebase can help guide me in the right direction?

Something like...

_maps.scss_

``` scss
$map: (key1: value1, key2: value2, key3: value3);
```

``` ruby
map = File.read('_maps.scss')

ruby_map = '...' # do cool sass stuff...

ruby_map[:map][:key]
=> value1
```

**Comment by nex3** [comment]
This is kind of a complicated question. First, you'll need to actually compile the stylesheet unless you just want access to the parse tree of the map. You'll also need to go slightly off the beaten path of the Ruby API, since the `Engine` class doesn't have support for passing in a custom `Environment` object. Here's some sample code to get you started:

``` ruby
engine = Sass::Engine.for_file('_maps.scss', {})
tree = engine.to_tree
environment = Sass::Environment.new(nil, engine.options)
Sass::Tree::Visitors::Perform.visit(tree, environment)
p environment.var('map')
```

Now, the contents of the `$map` variable will be a `Sass::Script::Value::Map` object. You can call `#to_h` on it to get its Ruby value, but the keys and values will still be Sass values. If you want to convert it to a purely Ruby-valued map, you'll need to do that by hand.

**Comment by brewster1134** [comment]
This leaves me with an empty `@vars` hash on the environment instance.

The engine has the correct scss set to the template var, and the tree var returns `(Sass::Tree::RootNode Sass::Tree::CommentNode Sass::Tree::CommentNode Sass::Tree::VariableNode Sass::Tree::CommentNode Sass::Tree::VariableNode)` which i will just have to assume is correct.

**Comment by brewster1134** [comment]
just to rule out my sass maps...

``` ruby
engine = Sass::Engine.new("$map: (key1: value1, key2: value2, key3: value3);", syntax: :scss)
tree = engine.to_tree
environment = Sass::Environment.new(nil, engine.options)
Sass::Tree::Visitors::Perform.visit(tree, environment)
environment.var('map')
=> nil
environment.instance_variable_get('@vars')
=> {}
```

**Comment by nex3** [comment]
Hmm, I forgot that `Perform` sets up a local scope on top of the environment that's passed in.

Here's another approach:

``` ruby
module Sass::Functions
  def export_map(map)
    $exported_map = map
  end
end

str = File.read('_maps.scss') + "$-unused-var: export-map($map)"
Sass::Engine.new(str, syntax: :scss).render
p $exported_map
```

**Comment by brewster1134** [comment]
So now I get an error about how the value of the map is invalid CSS (export map function omitted from example)

``` ruby
str = "$map: (key1: value1, key2: value2, key3: value3);\n$map-object: export-map($map);"
Sass::Engine.new(str, syntax: :scss).render
```

returns

```
(key1: value1, key2: value2, key3: value3) isn't a valid CSS value.
```

which is curious because the same value is valid when set to `$map`

**Comment by brewster1134** [comment]
Looking through the docs, i changed the module to `Sass::Script::Functions` and the export_map function is getting called now, but the results are the same.

**Comment by nex3** [comment]
It works for me if I use `Sass::Script::Functions`:

``` ruby
module Sass::Script::Functions
  def export_map(map)
    $exported_map = map
  end
end

str = "$map: (key1: value1, key2: value2, key3: value3);\n$map-object: export-map($map);"
Sass::Engine.new(str, syntax: :scss).render
p $exported_map # prints "(key1: value1, key2: value2, key3: value3)"
```

**Comment by brewster1134** [comment]
so i later realized that since I would have to be manipulating sass map objects anyway, it was more performant to just do that with the raw scss...

``` ruby
require 'yaml'

map_string = File.read(_maps.scss'))
map = YAML.load(map_string
  .gsub(/^\/\/.*$\n/, '')     # remove comments
  .gsub(/^\s?\$/, '')         # remove sass variable $
  .gsub(/\s?\($/, '')         # opening parens
  .gsub(/^\s*?\)[,|;]?$/, '') # closing parens (with optional semicolon)
  .gsub(/\s?,$/, '')          # commas
)
```

but that was fun playing around with sass....  i always enjoy a good brain exercise!

**Comment by brewster1134** [comment]
i should mention, that i was also working with nested maps and i had multiple sass maps defined in a single file

``` scss
$foo: (key1: ( nested: value2));
$bar: (key1: ( nested: value2));
```

I'm still on the fence with which solution I like more.  The recursive generation of sass seems excessive tho... thoughts?
