### ISSUE TITLE
BUG: Using margin and simple math operation

### ISSUE THREAD

**Issue by cjba7** [sass/sass#1249]
In a SASS file, write:
.hello
    $var: 100px
    margin: 0 0 0 -($var / 2)

In CSS this outputs:
.hello {
  margin: 0 0 -1px; }

It is missing a zero. The same happens if you use different operators or in a different margin location.

This ONLY happens when a negation is done using "-", if done using "-1*" it works as expected.

**Comment by nex3** [comment]
This is an unfortunate but expected consequence of SassScript's grammar. When it sees `0 -($var / 2)`, it needs to decide whether that `-` is a unary or binary operator. At this point it can't "see" the whitespace, so it defaults to thinking of it as a binary operator, producing the result you see.

The best way around this in general is to just wrap the unary minus in another pair of parentheses to make it clear that it's actually unary: `margin: 0 0 0 (-($var / 2))`. In your case in particular, you could also divide by `-2` instead.

**Comment by cjba7** [comment]
Thanks. Understood.
