### ISSUE TITLE
Problem with output "@charset 'utf-8';" to CSS

### ISSUE THREAD

**Issue by barchan** [sass/sass#1253]
Example:

main.scss:

```
@charset 'utf-8';

body {
    color: #333;
}
```

compile to:

```
body {color:#333}
```

where is string "@charset 'utf-8';" ?

My setup: MacOSX 10.9.3 / Ruby 2.1.2 (Rbenv) / SASS 3.3.7.

Thank you!

**Comment by mprins** [comment]
_UTF-8_ must be uppercase, your charset directive is invalid, see eg. https://developer.mozilla.org/en-US/docs/Web/CSS/@charset and https://www.iana.org/assignments/character-sets/character-sets.xhtml

**Comment by barchan** [comment]
Thank you for your answer. But dont work anyway. You can test here http://sassmeister.com/ and make sure that does not work anyway.

**Comment by mprins** [comment]
seems `@CHARSET 'UTF-8'` works but that's not valid since the directive should be lc...

**Comment by barchan** [comment]
yep, work for me too, but this not right way, waiting for fix in new update.

**Comment by lolmaus** [comment]
I don't mean that this should not be fixed, but i doubt that the CSS standard has this directive case-dependent.

**Comment by barchan** [comment]
looks like its not a problem, example: http://sassmeister.com/gist/9537678

if any html-character present in any *.scss file, even like comment, SASS automaticly adding '@charset "UTF-8";' in compiled .css file.

**Comment by mprins** [comment]
@lolmaus the spec http://www.w3.org/TR/CSS2/syndata.html#charset says: 

>  @charset must be written literally, i.e., the 10 characters '@charset "' (lowercase, no backslash escapes), followed by the encoding name, followed by '";'.

**Comment by lolmaus** [comment]
Thank you for correcting me, @mprins. I've looked into a more recent spec:
- http://www.w3.org/TR/css3-syntax/#determine-the-fallback-encoding
- http://www.w3.org/TR/css3-syntax/#charset-rule

and found that the `@charset` rule was regulated by the CSS2 spec to be parsed in binary form. O_o Thus, case sensitivity.

**Comment by apfelbox** [comment]
@lolmaus actually, the spec doesn't exactly say, that it is case insensitive.

The `@charset"` is parsed binary, then encoding `XX*`, then `";`.
The encoding `XX*` is interpreted as ASCII (doesn't say anything about case (in)sensitivity).

> Otherwise, check the byte stream. If the first 1024 bytes of the stream begin with the hex sequence
> 40 63 68 61 72 73 65 74 20 22 XX\* 22 3B
> where each XX byte is a value between 016 and 2116 inclusive or a value between 2316 and 7F16 inclusive, then get an encoding for the sequence of XX bytes, interpreted as ASCII. 

But: the spec itself uses lowercase, so...

> [...]
> If neither of these options are available, authors should begin the stylesheet with a UTF-8 BOM or the exact characters
> 
> @charset "utf-8";

**Comment by nex3** [comment]
Sass will only include a `@charset` declaration in the CSS output if there are any non-ASCII characters. CSS is parsed as ASCII by default, so it's unnecessary if the stylesheet is pure ASCII.

**Comment by apfelbox** [comment]
@nex3 are you sure about that? The first link from @lolmaus mentions

> 4) Otherwise, use utf-8 as the fallback encoding.

**Comment by nex3** [comment]
Okay, to be precise, it's parsed as an _ASCII-compatible_ encoding by default, but the result is the same: `@charset` is unnecessary in a pure-ASCII stylesheet.

**Comment by dasj19** [comment]
I know it's an old thread but may be helful for others in the future...
It turns out you can not have that kind of declaration in a .scss file... It should be in a .sass file otherwise most sass compilers will complain

**Comment by nex3** [comment]
@dasj19 That's not correct, `@charset` declarations can appear in both SCSS and indented-syntax files.

**Comment by IqraMalik496** [comment]
See At-rules ccs2
Assume, for example, that a CSS 2.1 parser encounters this style sheet:


@import "subs.css";
h1 { color: blue }
@import "list.css";
The second '@import' is illegal according to CSS 2.1. The CSS 2.1 parser ignores the whole at-rule, effectively reducing the style sheet to:


@import "subs.css";
h1 { color: blue }
In the following example, the second '@import' rule is invalid, since it occurs inside a '@media' block.


@import "subs.css";
@media print {
  @import "print-main.css";
  body { font-size: 10pt }
}
h1 {color: blue }
Instead, to achieve the effect of only importing a style sheet for 'print' media, use the @import rule with media syntax, e.g.:


@import "subs.css";
@import "print-main.css" print;
@media print {
  body { font-size: 10pt }
}
h1 {color: blue }
https://www.w3.org/TR/CSS2/syndata.html
