### ISSUE TITLE
Unable to make quasi-qualified selectors with BEM SASS

### ISSUE THREAD

**Issue by joemckie** [sass/sass#1255]
Hey - I've been using SASS for a while and recently upgraded to 3.3.7, I've noticed that it seems to be impossible to create quasi-qualified selectors using the BEM syntax. In short, I'm aware this may be intentional as quasi-qualified selectors are to be avoided, however in some cases I personally feel they're needed.

**Example**

```
.block {
    a.&__element {
    }
}
```

I would have expected that to compile as `.block a.block__element`, but instead SASS throws an error. Is there a way around this?

PS. My mouse got a bit click-happy, sorry about the closing/reopening mess!

**Comment by nex3** [comment]
This is expected; `&` may only occur at the beginning of a selector. You'll be able to do the following when #1117 is completed:

``` scss
.block {
  #{selector-append('a', selector-append(&, '__element'))} {
    // ...
  }
}
```
