### ISSUE TITLE
sass-convert from css to scss generating incorrect styles

### ISSUE THREAD

**Issue by othbert** [sass/sass#1257]
```
ul {width: 10px;}
ul div {width: 20px;}
article {width: 10px;}
article p {width: 20px;}
```

sass-convert ./test.css ./test.scss -F css -T scss
becomes

```
ul, article {
  width: 10px;
  div {
    width: 20px;
  }
}
```

on Sass 3.2.19 (Media Mark)
Issue is that the result is missing the declaration for paragraph styles entirely.

Seems to be ok as long as the attributes are not identical, for example;

```
ul {width: 10px;}
ul div {width: 20px;}
article {width: 10px;}
article p {width: 10px;}
```

produces

```
ul {
  width: 10px;
  div {
    width: 20px;
  }
}

article {
  width: 10px;
  p {
    width: 10px;
  }
}
```

as expected.

Apologies if this is a duplicate, I couldn't see it reported before.

**Comment by Anahkiasen** [comment]
Yeah I got that a lot using sass-convert, usually I merge them by hand but I've seen this happening a lot.
