### ISSUE TITLE
Support for inline-image

### ISSUE THREAD

**Issue by foxx** [sass/sass#1258]
I came across a lovely little helper in the compass framework called [inline-image](http://compass-style.org/reference/compass/helpers/inline-data/) which encodes your images via base64 into your SASS. There is also an extension which does something [similar](https://github.com/Integralist/Sass-Base64-Extension), but I'm not convinced by the implementation.

Could a core maintainer please confirm if such functionality, if designed and implemented properly, would stand a chance of being pulled into the core? If so, then I'm happy to spend some time putting together a proper PR.

**Comment by nex3** [comment]
Helpers like this that involve outside assets require a notion of directories in which to look for those assets. Sass core by design omits any such notion, leaving it to more heavily-configured frameworks like Compass.

**Comment by foxx** [comment]
Ah understood, thank you for the clarification.
