### ISSUE TITLE
unable to import nested assets

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#1267]
I recently came across an issue with importing assets from within nested/custom directories.

i have a custom path added to the load_path

`config.sass.load_paths << Rails.root.join('app', 'assets', 'stylesheets', 'foo')`

and when i try to import `foo.css.sass` with `@import foo`, i get an error about `File to import not found or unreadable: foo.`

if i rename it to just `foo.sass` it works...

**Comment by brewster1134** [comment]
i have an app that shows this behavior [here](https://github.com/brewster1134/test/tree/sass_1267) on branch `sass_1267`

**Comment by nex3** [comment]
Sass doesn't support terse imports for files with the `.css.sass` naming convention. Imported libraries are typically not intended to be compiled directly to CSS, so naming them that was is somewhat misleading.

You can solve this either by renaming your file or writing `@import "foo.css.sass"` explicitly.

**Comment by chriseppstein** [comment]
It's trivial to inherit from the `Filesystem` importer and define [different extensions](http://sass-lang.com/documentation/Sass/Importers/Filesystem.html#extensions-instance_method).

**Comment by brewster1134** [comment]
isn't this part of what the sass-rails gem does?  according to their source, the .css.sass extension is mapped to the sass syntax.  does that not apply to import?

**Comment by nex3** [comment]
That's a question for the `sass-rails` maintainers.
