### ISSUE TITLE
Move repo to Sass org

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1269]
@nex3, I'd like to move the Sass repo to the Sass organization.

https://github.com/sass

Any objections?

https://help.github.com/articles/how-to-transfer-a-repository

**Comment by andrew** [comment]
I can help out with any issues you have on the GitHub side, but you should be fine just using the transfer option from the settings.

**Comment by chriseppstein** [comment]
@andrew Thanks!

**Comment by HamptonMakes** [comment]
I just transferred over libsass.

**Comment by KittyGiraudel** [comment]
This is a good idea.

**Comment by hagenburger** [comment]
+1

**Comment by nex3** [comment]
:thumbsup:

**Comment by chriseppstein** [comment]
@nex3 you'll need to be the one who does this. I don't have admin access to the sass repo. Let me know what you need.
