### ISSUE TITLE
incorrect comments handling

### ISSUE THREAD

**Issue by ffuubarbuzz** [sass/sass#1276]
sass fails parsing following:

```
/* Generated with Bounce.js. Edit at http://bouncejs.com/#{s:[{T:"c",e:"b",d:1000,D:0,f:{x:0,y:0},t:{x:1,y:1},s:1,b:5}]} */
```

http://cssdeck.com/labs/nywqmj4z

**Comment by lolmaus** [comment]
You use interpolation there: `#{ }`. What's inside those braces is treated as Sass code.

**Comment by ffuubarbuzz** [comment]
I see. Is it reasanoble to interpolate within comments?

**Comment by lolmaus** [comment]
Yes, you might want to output some variables into CSS comments. E. g. grid configuration, environment type, project version number, etc.

**Comment by ffuubarbuzz** [comment]
Seems reasonable enough:) Thank you, I informed bounce.js author about that issue.

**Comment by lolmaus** [comment]
Actually, you can simply escape that with a backslash `"foo \#{bar} baz"`. This will result in a `foo #{bar} baz` string.

Not sure how to do that in bounce.js though. I've found the "Generated with Bounce.js" string is inside [a CoffeeScript file](https://github.com/tictail/bounce.js/blob/a3c2fbcefba4b57d71879a8418d9444c5db9e595/app/scripts/views/export.coffee#L53) which might be used to generate Sass code or something.
