### ISSUE TITLE
Multiple selector with ampersand in Sass 3.3.8

### ISSUE THREAD

**Issue by hinok** [sass/sass#1277]
Just upgraded from 3.3.0.rc.2 to 3.3.8 and unfortunately some of our styles don't compile anymore.

We have the problem with styles like:

```
.list {
    @at-root {
        #{&}--big#{&}--active {
            color: red;
        }
    }
}
```

I know that since final release 3.3.0 we can write styles without @at-root and just use & instead #{&}. Anyway after changes constructions like below don't compile.

```
.list {
    &--big&--active {
        color: red;
    }
}
```

Codepen demo: http://codepen.io/anon/pen/lJfHw

**Comment by Snugug** [comment]
There was a change in how these selectors work for the full release of Sass 3.3 as the interpolation created some unexpected results. See [Nathan's Post](https://gist.github.com/nex3/8050187) on it

**Comment by Snugug** [comment]
Also see #286

**Comment by hinok** [comment]
@Snugug Thanks for fast response. I read these posts earlier. I'm aware of these changes.
What doesn't change the fact that I can't use multiple selectors now...

In my current project I used a lot of multiple classes selectors like the example above.
It would be great if I could get the string in some way from ampersand (&) and use interpolation like this

```
$el: &; // I know that it doesn't work now, it's only example
#{$el}--big#{$el}--active { ... }
```

Any ideas to solve this problem?

**Comment by nex3** [comment]
You won't be able to do this until script `&` is reintroduced in Sass 3.4.
