### ISSUE TITLE
Sass avatar on GitHub is slightly cropped

### ISSUE THREAD

**Issue by LaurentGoderre** [sass/sass#1278]
@jina I just noticed that the sass logo is slightly cropped at the right and at the bottom on the GitHub avatar

**Comment by jina** [comment]
Ah! It might be because the image scaling gravatar has on uploading. Now that github allows for uploading directly, I'll replace the image because that's something I can access! :-) Thanks for the heads up!

**Comment by LaurentGoderre** [comment]
In case it's actually GitHub that caused it perhaps you could add a few pixels padding around the logo. In any case, I'm closing since you are aware of it now

**Comment by jina** [comment]
Reopening because I like to have my open issues to work against. ;) I won't be able to get to this right this moment (at work). :)

**Comment by LaurentGoderre** [comment]
Aaah lol sorry, different philosophies huh ;)

**Comment by nex3** [comment]
Moved this to sass/sass-site#81.
