### ISSUE TITLE
math error between 3.3.5 and 3.2.19 causes invalid declaration

### ISSUE THREAD

**Issue by nshew13** [sass/sass#1279]
I was using Sass 3.3.5 with `grunt-contrib-sass` to compile my SCSS files without issue. I then tried to add Compass (0.12.2), which installed the Sass 3.2.19 gem as a dependency. Now, when I compile the same SCSS file using `grunt-contrib-compass`, I lose a `border-bottom` property. (There may be other issues, but that one jumped out pretty apparently.)

```
  div.menuCol:hover > div > div.menuItem:first-child {
    margin-left: 0;
    width: $submenu-col-width + $submenu-gutter;

    .arrow-left {
      /* offset menuItem padding */
      position: absolute;
      top: 0;
      left: $submenu-gutter - 10px + 1; /* gutter - border-right-width (negative) + 1 */
      width: 0;
      height: 0;
      border-top:    $nav-height/2 solid transparent;
      border-bottom: $nav-height/2-1 solid transparent;
      border-right: 9px solid $menuItem-hover-bg-color;
    }
  }
```

_compiled with Sass 3.3_

```
div.menuCol:hover > div > div.menuItem:first-child .arrow-left {
  /* offset menuItem padding */
  position: absolute;
  top: 0;
  left: -9px;
  /* gutter - border-right-width (negative) + 1 */
  width: 0;
  height: 0;
  border-top: 25px solid transparent;
  border-bottom: 24px solid transparent;
  border-right: 9px solid #eeeeee;
}
```

_compiled with Compass + Sass 3.2_

```
div.menuCol:hover > div > div.menuItem:first-child .arrow-left {
  /* offset menuItem padding */
  position: absolute;
  top: 0;
  left: -9px;
  /* gutter - border-right-width (negative) + 1 */
  width: 0;
  height: 0;
  border-top: 25px solid transparent;
  border-bottom: 25px -1 solid transparent;
  border-right: 9px solid #eeeeee;
}
```

![arrow_diff](https://cloud.githubusercontent.com/assets/328432/3250371/9aa372ba-f1a4-11e3-972f-3998a614a618.png)
_3.3 on the left, 3.2+Compass on the right_

It looks like a math/order of operations error, in that the `-1` isn't correctly handled, and breaks the declaration. How can I modify the SCSS to compile correctly under the old version?

**Comment by Snugug** [comment]
Update to `border-bottom: $nav-height/2 - 1px solid transparent;` and it'll work in both

**Comment by lolmaus** [comment]
It's not a math error but rather a syntax error.

Just use spaces between variables, numbers and operators and you're fine.

**Comment by nshew13** [comment]
Both

```
border-top:    $nav-height/2       solid transparent;
border-bottom: $nav-height/2 - 1px solid transparent;
```

and

```
border-top:    $nav-height / 2       solid transparent;
border-bottom: $nav-height / 2 - 1px solid transparent;
```

compile to 

```
border-top: 25px solid transparent;
border-bottom: 25px solid transparent;
```

**Comment by lolmaus** [comment]
And your desired output is?..

**Comment by nshew13** [comment]
```
border-top: 25px solid transparent;
border-bottom: 24px solid transparent;
```

There's an issue with border spacing that needed the `-1`.

**Comment by lolmaus** [comment]
I can't reproduce it on Sassmeister: http://sassmeister.com/gist/f832631ea43ce5f55249

Can you?

Also, try purging Sass cache (`compass clean` if you're lucky to use Compass).

**Comment by nshew13** [comment]
I see the correct output now. Maybe it was the cache. Thank you.
