### ISSUE TITLE
I think I broke ruby :/

### ISSUE THREAD

**Issue by jwoertink** [sass/sass#1281]
Not sure if this error belongs here, but I figure I should show someone. I was just trying to style a page in rails with some SASS, and got this.

https://gist.github.com/jwoertink/ef3eed03621d73d92fb2

**Comment by nex3** [comment]
Can you report this on the Ruby issue tracker? https://bugs.ruby-lang.org/

**Comment by jwoertink** [comment]
will do. thanks
