### ISSUE TITLE
A little mistake in documentation

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1283]
From documentation (section @extend):
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend

---

```
.parent {
  @at-root {
    .child1 { ... }
    .child2 { ... }
  }
}
```

These produce, respectively:

```
.child { ... } //maybe here must be .parent class?

.child1 { ... }
.child2 { ... }
```

---

**Comment by apfelbox** [comment]
The correct link is: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#at-root

But you are right, it's an error in the docs.
