### ISSUE TITLE
Add Ability for Sass to remove duplication from source files

### ISSUE THREAD

**Issue by ghost** [sass/sass#1287]
Is it possible for us to get an option on SASS for it to output a condensed version of the input, where duplicate tree nodes are merged as defined?

EG, take the source file reading.

```
.signup {
  form {
    a {
        color:blue;
       }
    }
}
...... more source .... imagine 100's of lines later.....

.signup {
  .img  {
    width:100px;
  }
}
```

This flag would merge the two definitions to produce.

```
.signup {
  form {
    a {
        color:blue;
       }
  .img  {
    width:100px;
  }
}

.... rest of source ....
```

This would really help cleaning up a codebase after translating from CSS

**Comment by lolmaus** [comment]
Duplicate of #116, #309, #615, #685.

**Comment by nex3** [comment]
@lolmaus it looks like this is requesting a source-to-source transformation, not an output optimization.

@savingschampion doing this with intervening source code is unsafe, since the order of rules matters to CSS.

**Comment by chriseppstein** [comment]
I'd like to see a linter address this.

**Comment by savingschampion** [comment]
@nex3 Sass wouldn't decide the order of the source, it would replicate the current order. All it would do is merge duplicate branches, keeping duplicate style attributes in  previously declared order. Unless there is something I'm missing?

**Comment by Anahkiasen** [comment]
Well no, take your example, the image width property was moved before the "...... more source .... imagine 100's of lines later....." so order of the source changed.

**Comment by savingschampion** [comment]
Yes, but the order of the style attributes on that branch retain their order, so if there were any other styles in those hundreds of lines then they would have moved up as well. The structure of the source changes, but not in a way that would change the output.

F.e:

```
.img-container {
    width:100%;
}

.img-container {
   img {
      width:95%;
   }
}

.img-container {
   img {
      width:1000%;
   }
}

```

would move to:

```
.img-container {
    width:100%;
   img {
      width:95%;
      width:1000%;
   }
}
```

The source is still means the same, the output should be the same (maybe removes a duplicate definition of .img-container img {}) , but the source is cleaner.

**Comment by apfelbox** [comment]
@savingschampion the element `img` in your second example could be matched by a multitude of selectors, not just the ones prefixed with `.img-container`.

Which selectors match is not determinable by sass, therefore it should not change the order of selectors - even the ones which seem not to be related.

_edit: some code_ 

``` html
<div class="img-container some-other-selector">
    <span class="img"></span>
</div>
```

``` css
.img-container .img {
    display: inline-block;
    height: 100px;
    width: 100px;
}

.some-other-selector .img {
    background-color: blue;
}

.img-container .img {
    background-color: red;
}
```

Here you can't merge the `.img-container .img` at the bottom with the top one.

**Comment by savingschampion** [comment]
Ah, good point.
