### ISSUE TITLE
Allow + and = in .scss style syntax.

### ISSUE THREAD

**Issue by MarioRicalde** [sass/sass#129]
It would be great if we could allow + and = alias to work within the .scss syntax. This would help reduce the amount of noise created when working heavily with mixins on your stylesheet.

All the syntax would be the same:

```
 +something(100px);
```

Instead of

```
 @include something(100px);
```

Please consider it! I'm currently doing monkey patching to achieve this.. but it's not the best solution.

**Comment by rstacruz** [comment]
+1
I would totally love this. Typing out `@include` everytime is getting tiresome.

(Maybe you can even do `something: 100px` but that's a bit of a stretch :D)

**Comment by barraponto** [comment]
Why don' you use the SASS syntax? It rocks.

**Comment by chriseppstein** [comment]
this is a dup, can't find the other tho.
