### ISSUE TITLE
Switch Sass version easily ?!

### ISSUE THREAD

**Issue by borisdamevin** [sass/sass#1295]
Is it possible to change the version of Sass and Compass without systematically uninstall the most recent versions?

For example: if I have the `3.2.19` version `3.3.8` installed, how to use the `3.2.19` version without deleting the `3.3.8` version?

Thank you.

**Comment by lolmaus** [comment]
[![Bundler Sponge Bob](http://i.memeful.com/memes/MVXeL3d/Imagination-Spongebob.jpg)](http://bundler.io/)

http://bundler.io/

**Comment by chriseppstein** [comment]
Fun fact: any executable installed with rubygems allows you to select the version like this:

```
$ sass _3.2.19_ ...
$ sass _3.3.3_ ...
```

You can get the list of versions:

```
$ gem list sass
```

**Comment by borisdamevin** [comment]
Thank you but this command don't change my version of sass.

I have miss something?

I tape `sass _3.2.19_`
