### ISSUE TITLE
Compress option is a little too good

### ISSUE THREAD

**Issue by kunambi** [sass/sass#1297]
Hello,

With the help of SASS I've been able to create a fontface `@mixin`, that works very well. However, it breaks when I try to embedd fonts with the word `black` in them and using `--style compressed`.

E.g style nested:

```
    @font-face {
      font-family: "Argumentum";
      src: url("/static/css/fonts/argumentum-black.eot");
    }
```

E.g style compressed:

```
    @font-face{font-family:"Argumentum";src:url("/static/css/fonts/argumentum-#000.eot");}
```

I think this should be regarded as a bug, since not all instances of using the word `black` should be automaticly translated into `#000`.

TYIA.

**Comment by lolmaus** [comment]
> a little too good

At least someone is happy with this behaviour. :)

PS Search it up, man. This issue is being raised every other week.

**Comment by kunambi** [comment]
I've look through all the open issues, but haven't found any that resembles this ticket.
There are a few tickets on SO that involves this bug, but unfortunatelly those solutions aren't applicable to me.

Thanks for pointing me in the right direction, but I still consider this a bug with SASS and it should be fixed as such.

**Comment by lolmaus** [comment]
https://github.com/sass/sass/issues/1256
https://github.com/sass/sass/issues/1274
https://github.com/sass/sass/issues/665
https://github.com/sass/sass/issues/1095
https://github.com/sass/sass/issues/874
https://github.com/sass/sass/issues/720
https://github.com/sass/sass/issues/692

TL/DR: quote color names.

Your example has color name already in quotes, so it is not converted to a hex value, at least in current versions of Sass: http://sassmeister.com/gist/1dbc5ad5fe1c747b9427

If you manage to reproduce it on Sassmeister, then it's a legit bug.

**Comment by nex3** [comment]
Yeah, there's no setting that should change the contents of existing strings like that. I can't reproduce it locally, either. What version of Sass are you using?

**Comment by kunambi** [comment]
Hello,

```
C:\>sass --version
Sass 3.3.7 (Maptastic Maple)
```

**Comment by kunambi** [comment]
Hello again,

I was able to reproduce the bug on sassmeister.com, http://sassmeister.com/gist/c93b1bafe121ffa1e3f2, using the mixin I've created for embedding fonts. 

Please note that the bug is only manifests when using "compressed" style, and not while using "compact" or any other style. If this behaviour would show up in all styles, then I'd assume that there's an error in my mixin.

TYIA.

**Comment by apfelbox** [comment]
You need to quote your string values: http://sassmeister.com/gist/c0e183c4f529bc21b5ec

Everything which looks like a color value will be transformed into the most space-efficient representation when using compressed mode. Strings (with quotes) can't be color values, therefore they will be left untouched.

**Comment by kunambi** [comment]
I will follow your practice in the future.

TYVM.
