### ISSUE TITLE
gem update sass doesn't work

### ISSUE THREAD

**Issue by gsambrotta** [sass/sass#1300]
I've two version of sass installed on my machine: 
1. sass-3.2.19 (bundle)
1. sass-3.3.8 

With one of my computer when I do SASS -v I see:
sass-3.3.8
With the other I see:
sass-3.2.19

The one that show me  "sass-3.2.19" cause me several error when I compile projects (using framework like bourbon/neat/susy..) because they use too advanced syntrax.

How can I make also the second machine point to version  sass-3.3.8?

p.s. I can't specify 3.3.8 in the gemfile because i'm using middleman or compass and they need version 3.2

**Comment by chriseppstein** [comment]
Set compass version to "~> 1.0.0.alpha.19"

**Comment by gsambrotta** [comment]
Why the issue is close? Isn't solved. My problem isn't compass since i'm not using compass. 
My problem isn't a incompatible versions, my problem is that when I do sass -v I see the oldest version instead of the newest.

**Comment by apfelbox** [comment]
>  My problem isn't compass since i'm not using compass. 

vs.

> p.s. I can't specify 3.3.8 in the gemfile because i'm using middleman or compass and they need version 3.2

?

**Comment by gsambrotta** [comment]
I'm using middleman that come already with compass inside but I decided to not use it (due to all the version problems) and to install with bower bourbon and neat.
Anyway i don't think this is my real problem since in the other machine everything works fine. I think my problem is about the version of sass that my machine decided to use

**Comment by gsambrotta** [comment]
I tried to uninstall gem sass (again!) and now:
if I do sass -v I get 3.3.8
but inside of this Middleman project, as soon as I do 'bundle' (I get the version 3.2.19 that is the one Middleman use) and I do sass -v I get 3.2.19.

That it doesn't happen in the other machine of' course... any idea?

**Comment by lolmaus** [comment]
1. Set a version you need in the `Gemfile`.
2. Run `bundle install` (or `bundle update` if `bundle install` tells you so).
3. Prepend your commands with `bundle exec`, e. g.:
   
   ```
   bundle exec sass --watch path/sass-directory:path/css-directory   
   ```

**Comment by gsambrotta** [comment]
I can't set the version 3.3.8 in the gem otherwise Middleman complains that it needs 3.2.19

**Comment by lolmaus** [comment]
Is it not telling you specifically which gem locks Sass at 3.2?

It's the Compass gem. Set it to a Sass 3.3-compatible version:

```
gem 'compass', '~> 1.0.0.alpha.19'
```

**Comment by gsambrotta** [comment]
Actually it work.... :/ you have to excuse me @chriseppstein for not believe you at the beginning but I can't understand why now it work... I already tried to update compass gem and it didn't work. 

Also I still don't get why one computer works without the need of this gem compass specification and the other don't.

In addiction I can't understand why it complains just about middleman and never talked about compass(which I don't even use in the project !!!) and now is using sass 3.3.8 and middleman doesn't complain anymore   ...!!

Well, thank you anyway @lolmaus (and everybody replay), you made my day!

**Comment by apfelbox** [comment]
Well, you don't use compass, but it is specified as dependency nevertheless. It is included in the depedency resolution by bundler because of that - and bundler rightfully complains.
