### ISSUE TITLE
Deprecate Multiline Sass Strings

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1302]
On Sass master we have removed support for multiline Sass strings. Unfortunately, these are in use and need to be deprecated before we can introduce this breaking change.

[Multiline Strings In the wild](https://github.com/ericam/true/blob/master/sass/true/_modules.scss#L26-L28)

Furthermore, I was under the impression that `"\n"` would result in a Sass string containing a single newline, but instead it results in string containing an `n`. Strangely enough `"\00000a"` results in "\n" in the output of the interactive mode.

**Comment by nex3** [comment]
> Furthermore, I was under the impression that `"\n"` would result in a Sass string containing a single newline, but instead it results in string containing an `n`.

This is [per spec](http://dev.w3.org/csswg/css-syntax-3/#consume-an-escaped-code-point0). The only meaningful escapes in CSS strings are hex unicode escapes.

> Strangely enough `"\00000a"` results in "\n" in the output of the interactive mode.

This is because we print strings in interactive mode using Ruby's string dumping. I'll fix that.
