### ISSUE TITLE
append() merge two space separated lists problem

### ISSUE THREAD

**Issue by P233** [sass/sass#1304]
Hi

When I use the `append()` function to merge two space separated list with comma, it returns three sub-lists rather than two. But if I merge the two lists via `@for` loop, that works fine. Any idea please?

![screen shot 2014-07-04 at 14 14 00](https://cloud.githubusercontent.com/assets/1818679/3482220/8310c3e2-037d-11e4-85e5-54235b0cfd0b.png)

**Comment by lolmaus** [comment]
> ```
> append($list1, $val, [$separator])
> ```
> 
> Appends a **single** value onto the end of a list.

http://sass-lang.com/documentation/Sass/Script/Functions.html#append-instance_method

**Comment by lolmaus** [comment]
To create a new list out of two lists, use `join()`. It will enforce certain separator type between all items.

To create a list of lists, simply use a comma.

Demo: http://sassmeister.com/gist/ee2b7f15d647d3a97405

**Comment by P233** [comment]
Thanks @lolmaus  this really helps.

**Comment by P233** [comment]
Hi @lolmaus , It seems using comma can only create a list of two space separated lists, but how can I create a list of multiple lists?

Here is my code: http://sassmeister.com/gist/47ef0a768698e0ba1e70

I am expecting to output

```
body {
  list: 1 1, 2 2, 3 3, 4 4, 5 5;
  item: 1 1;
  item: 2 2;
  item: 3 3;
  item: 4 4;
  item: 5 5;
}
```

Is there a way to do that?  thanks

**Comment by lolmaus** [comment]
When you use a comma, you create a new list (of lists). So our code produces a nested list, `$var` becomes equal to `(((((1), 2), 3), 4), 5)`.

To append a single value to a list without nesting, use `append` as i had mentioned above.

Demo: http://sassmeister.com/gist/135a61527a2ee3924cb1

**Comment by P233** [comment]
@lolmaus  Thank you for your reply. unfortunately in my project the sub-list is not  a single value, it has 3-5 values. That would be a pain to create such a list. I'd better find another way. Thanks again!

**Comment by lolmaus** [comment]
@P233, you could recieve more help if you provided a SassMeister demo of what you're actually trying to achieve.

**Comment by P233** [comment]
Thank @lolmaus . I am creating a new Gird System and doing some test. A function will grab data from Sass map and create a comma separated list of multiple space separated lists, and then pass the list to Sass 3.3 `@each` directive to generate grids. That's why I was focusing on creating list. I just did some test that I might use a `@for` loop and the `nth()` function instead of `@each`. I'll keep working on it and let you know :)

@nex3 @chriseppstein It would be handy if Sass could support merge multiple lists into one nested list   :)

**Comment by lolmaus** [comment]
@P233, have a look at this example: http://sassmeister.com/gist/74c2bba1ac3744a236d2

For grids, you should check out [Singularity](https://github.com/Team-Sass/Singularity). It has this all figured out.

For advanced list manipulations, have a look at [SassyLists](https://github.com/Team-Sass/SassyLists/) from @HugoGiraudel.

**Comment by KittyGiraudel** [comment]
> @P233, have a look at this example: http://sassmeister.com/gist/74c2bba1ac3744a236d2

Why don't you use `join`?

**Comment by lolmaus** [comment]
@HugoGiraudel, `join` produces a flattened result of certain list type.

**Comment by P233** [comment]
@lolmaus all my values are generated by function, and the list has to be created by `@for` loop, I am afraid that I can't use your `join-lists` function. 

I should explain the circumstance more clearly:
- A function will generate several space separated list

```
@function sub-list($i) {
  ...
  @return a b c;
}
```
- the amount of sub-list is uncertain but can be known
- I need combine all sub-lists into one comme separated list, so I can pass it to a `@each` directive

```
$list: ();
@for $i from 1 through $sub-list-amount {
  $list: $list, sub-list($i);
}

@each $a, $b, $c in $list {
  #{$a} { width: $b; height: $c }
}
```

But this is not going to work as you explained the `$list` will become a very deeply nested list.

---

Currently, I've found two workarounds:

**Wrokaround 1**

```
$list: ();
@for $i from 1 through $sub-list-amount {
  $list: join($list, sub-list($i), comma);
}
```

Create a flattened list, then

```
@for $i from 1 through $sub-list-amount {
  $a: nth($list, 3*$i - 2);
  $b: nth($list, 3*$i - 1);
  $c: nth($list, 3*$i);

  ...
}
```

**Wrokaround 2**

```
$list: ();
@for $i from 1 through $sub-list-amount {
  $list: append($list, sub-list($i));
}

@each $a, $b, $c in $list {
  #{$a} { width: $b; height: $c }
}
```

Even the `append()` function only accepts _single_ value, but it works. And I also noticed that when using `append()` to combine lists, the very first value _must be empty_.

Here is another example, sorry I can't login sassmeister.com with any browsers today :(

```
@function random-number() {
  @return random(100) random(100) random(100);
}

$list: ();

@for $i from 1 through 5 {
  $list: append($list, random-number(), comma);
}

body {
  list: $list;
  list-length: length($list);
  @each $a, $b, $c in $list {
    sum: $a #{'+'} $b #{'+'} $c #{'='} $a + $b + $c;
  }
}
```

I am much prefer the workaround 2, but I assume this is illgal.

**Comment by lolmaus** [comment]
Look man, it's very hard to understand what you want. You're reinventing the wheel here, and you're doing it in a weird way.

Don't.

Study [Singularity](https://github.com/Team-Sass/Singularity) and [Susy 2](http://susy.oddbird.net/). They are very agile grid systems that can address any situation.

Study [Flexbox](http://css-tricks.com/snippets/css/a-guide-to-flexbox/).

Try to solve your tasks with these.

**Comment by nex3** [comment]
"Workaround 2" seems like the correct way to express this. I'm not sure why you think it's illegal.

**Comment by P233** [comment]
@lolmaus  @HugoGiraudel  I've finished the first version of my grid system. please have a look :)
https://github.com/P233/Rebar-Grid

As you can see in https://github.com/P233/Rebar-Grid/blob/master/rebar-grid/data/_container-list.scss#L37 , I need to combine multiple lists inside a `@for` loop. That why I am looking for a way to combine list.

@nex3 Thank you for your reply, the `append()` only accept singe value, it doesn't combine list unless I append the lists after an empty value. This example may explain my question  http://sassmeister.com/gist/efe05764ee61d0e76c03

**Comment by chriseppstein** [comment]
@P233 Use `join()` to combine two lists and provide a separator value for the result.

**Comment by P233** [comment]
Hi @chriseppstein I have a few space separated lists and I'd like to combine them into one big comma separated list, like this `one two, three four, five six`, this list has three values and each value is a space separated sub list. But if I use `join()` and set comma as separator, I will get a single list with 6 values: `one, two, three, four, five, six`.

**Comment by chriseppstein** [comment]
``` scss
$one: one two;
$two: three four;
$three: five six;

@function something($args...) {
  $rv: ();
  @each $arg in $args {
    $rv: append($rv, $arg, comma);
  }
  @return $rv;
}

.result {
  output: something($one, $two, $three);
}
```

**Comment by P233** [comment]
Thanks @chriseppstein, I am currently using this way in my project. 

In http://sass-lang.com/documentation/Sass/Script/Functions.html#append-instance_method, `appen()` only accept single value, and we cann't directly combine two list with `append()`

``` scss
$one: one two;
$two: three four;

.result {
  output: append($one, $two, comma);
// compiled result: one, two, three four
// there is a comma between 'one' and 'two'
}
```

But if we `append()` a list to `()` first and keep appending other lists, it works as expected. My question is why we have to append list to `()` first, is it legal or is it a feature of Sass?

I am sorry for my poor English, I didn't express my question clearly and make you misunderstood :(

**Comment by chriseppstein** [comment]
@P233 right. because you're saying add the `$two` list as a single element to the `$one` list when you do append like that. Basically, you're not treating $one and $two the same. If you need $one to be a comma delimited list containing a space delimited list  you should declare it with a trailing comma, then it will work like you want it to.

``` scss
$one: (one two,);
```

**Comment by P233** [comment]
@chriseppstein Thank you so much, I understand now.
