### ISSUE TITLE
Use of variables in @import's path

### ISSUE THREAD

**Issue by liamato** [sass/sass#1307]
Should be able to use variables in the `@import` path.
Like this:

``` sass
$template: "basic";
@import "templates/#{$template}/colors";
```

This should be the same as:

``` sass
@imprort "templates/basic/colors";
```

PD: there are any mode to do this in sass 3.3.9

**Comment by Snugug** [comment]
Direct duplicate of #1231 

Master file to track wanted changes to `@import` #1094
