### ISSUE TITLE
Will variable scoping work like this in 3.4?

### ISSUE THREAD

**Issue by alanhogan** [sass/sass#1309]
I ran into something today that I really hope works the way I’d like it to in sass 3.4.

Consider a file like `smacss-support.sass` here:

``` sass
@mixin module($module_class)
  @debug "In module mixin; $module_class is '#{$module_class}'"

  $_module_class: $module_class
  .#{$module_class}
    @content


@mixin submodule($submodule_name)
  @if not variable-exists(_module_class)
    @warn "Submodule mixin ('#{$submodule_name}') used outside of the context of a mixin."

  @debug "Should generate name .#{$_module_class}-#{$submodule_name}"

  $_submodule_class_name: ".#{$_module_class}-#{$submodule_name}"
  // Generate just one class name, with no ancestor selector
  @at-root
    #{$_submodule_class_name}
      @content
```

I would like to use the above code to define 'modules' like so, in `moc.sass`:

``` sass
+module (moc)

    border: 1px solid #888
    padding: 0.6em 1.2em

    +submodule (black)
        border-color: black
```

The intended CSS output would be

``` css
.moc {
  border: 1px solid #888;
  padding: 0.6em 1.2em;
}

.moc-black {
  border-color: black
}
```

However, trying to compile the above code yields an error as `$_module_class` is undefined within our mixin `submodule`. (And `$_module_class` does nothing but alias `$module_class` in the same scope, really.)

My work-around is a global variable `$_module_class` at the top of `smacss-support.sass`:

``` sass
$_module_class: null

@mixin module($module_class)
  // …
```

And that seems to work more or less as intended, except now the checks for usage of the mixin `submodule` outside of a content block passed to the mixin `module` are useless (as the variable is always defined).

Would my use case be supported in 3.4?

**Comment by nex3** [comment]
No. What you're describing is [dynamic scope](https://en.wikipedia.org/wiki/Scope_%28computer_science%29#Dynamic_scoping); Sass is [lexically scoped](https://en.wikipedia.org/wiki/Scope_%28computer_science%29#Lexical_scoping), and 3.4 doesn't change that. All it changes are the [shadowing](https://en.wikipedia.org/wiki/Variable_shadowing) rules: local variables will shadow global ones.

**Comment by alanhogan** [comment]
OK, thanks. 
Is there any way for a mixin to tell if it is being evaluated within the `@content` context of another mixin?

**Comment by nex3** [comment]
Not without the use of global variables.
