### ISSUE TITLE
Strange compilation error of plain old CSS animation

### ISSUE THREAD

**Issue by albell** [sass/sass#1316]
I think I have isolated the problem I'm experiencing. In short, this SCSS (pure CSS actually):

```
.doesnt-compile-by-itself {
      animation: typing 1.2s 9.8s steps(11, end) both,
      blink-caret 1s step-end infinite;
}
```

throws the error:

```
Syntax error: Invalid CSS after "}​": expected "{", was ""
```

This is of course mistaken, because it's perfectly valid CSS. There is no syntax error.

The weird thing is that if I follow it with another declaration it will sail through the compiler with no error at all. So as long as it's not last, it's okay!

```
.throws-a-meaningless-error-by-itself {
     animation:
            typing 1.2s 9.8s steps(11, end) both,
        blink-caret 1s step-end infinite;
}​

.but-add-this-rule-after-and-it-works {
    animation:
        something 1s 12.3s backwards,
        something-else 7s 13.3s backwards,
        and-then 8s 12.3s;
}
```

This kind of bug is extremely frustrating to work around! I'm using Codekit 2.0.6. As a curiosity, this same legit CSS also won't work in Codepen as SCSS:

```
http://codepen.io/anon/pen/HcisB
```

which complains that "Illegal nesting: Only properties may be nested beneath properties."

Any insight into what's happening here would be greatly appreciated. Thanks guys.

**Comment by cimmanon** [comment]
This seems to be an issue of whitespace that isn't whitespace.  When I copy/paste your codepen code into Sassmeister, there's a character that appears after the closing curly brace.  If you delete it, it compiles as expected.

http://sassmeister.com/gist/b44a6fa5a8e95e94b38e

It is worth noting that these types of characters will cause your CSS to fail to validate.
