### ISSUE TITLE
@import as a reference

### ISSUE THREAD

**Issue by julzmon** [sass/sass#1317]
I'm trying to switch to SASS but LESS has a feature which I can't figure out how to accomplish in SASS. LESS you can do `@import (reference) "file";` but there doesn't seem to be a way to do this in SASS.

**Comment by Snugug** [comment]
Duplicate of #1094

**Comment by poorpaddy** [comment]
Is there a way to just reference an import to appease linting and builds? For example, I have a common.scss file that contains mixins and a grid system. I use it in each scss file primarily as a reference but don't need to render the grid in each react components scss.

**Comment by cyrilchapon** [comment]
What is the status of this ?

https://github.com/sass/sass/issues/1094 has been closed several years ago without a single comment

**Comment by poorpaddy** [comment]
@cyrilchapon I think SASS is dead in the water when it comes to this issue. All similiar posts gets tagged as a duplicate to the same place but it is never really addressed.

Honestly I haven't seen any real effort to get that wishlist integrated or major improvements to address SASS shortcomings in a long time.

**Comment by nex3** [comment]
We have a limited amount of time and a lot of important work to do. Improving imports is high priority, but designing and implementing major changes like that takes time.

If you're interested in increasing the velocity that Sass evolves, we welcome contributors and I'm personally always happy to help people learn the codebase.
