### ISSUE TITLE
`--sourcemap=[auto|file|inline|none]` should be `--sourcemap [auto|file|inline|none]`, like `--style` or `--default-encoding`

### ISSUE THREAD

**Issue by hail2u** [sass/sass#1321]
In Sass v.4.0.rc.1, the new `--sourcemap` option needs to specify its value with `=`. But other options such as `--style` or `--default-encoding` specify its value with space. This seems a bit confusing to users and 3rd party tools. I think `--sourcemap` option should specify its value with space like other options.

**Comment by nex3** [comment]
Unfortunately, for backwards compatibility we need to support just `--sourcemap` with no additional arguments, which means that an argument would be ambiguous if `=` weren't required.

Once we release 4.0, though, we can probably support this.

**Comment by sindresorhus** [comment]
How would it be ambiguous? You just check whether `--sourcemap` has a non-flag arg after it.

In node, the [minimist](https://github.com/substack/minimist) arg parser handles this fine.

``` js
var argv = require('minimist')(process.argv.slice(2));
console.log(typeof argv.sourcemap, argv.sourcemap);
```

``` sh
❯ node test.js --sourcemap     
boolean true

~/Downloads  
❯ node test.js --sourcemap 'foo'
string foo
```

**Comment by nex3** [comment]
`sass --sourcemap foo` already has a meaning: compile the file `foo` with sourcemaps enabled. Changing it to mean "compile standard input with `foo`-style sourcemaps" would be a breaking change.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
