### ISSUE TITLE
Erratic behavior using `type-of` & @if/@else  w/ Sass 3.4 

### ISSUE THREAD

**Issue by lozandier** [sass/sass#1325]
## The Problem

For some reason code like the following code snippet breaks in Sass 3.4

``` sass
@mixin abc($a:2)    
  @if type-of($a) == 'color' 
    color: green
  @else 
    color: red

.placeholder_class 
  +abc
```

Regardless of what type is checked (`color`, `number`, `string`, and so on), a value of `33` is outputted instead of outputting `red` with the following error message: 

`Invalid CSS after "": expected selector, was "33"`
## An Example

A Sassmeister pen of the issue can be found [here](http://sassmeister.com/gist/3bdecf8ec53a6abb09e6)

**Comment by lolmaus** [comment]
You've got `33` in the end of your Sass code.

**Comment by lozandier** [comment]
You're right. I'm surprised Sass 3.3x  didn't catch that inside of SassMeister. Thanks for catching that.
