### ISSUE TITLE
Feature detect for SassScript parent-selector

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1327]
~~I'm simply basing this question on the [release notes for 3.4.0.rc1](https://github.com/sass/sass/blob/master/doc-src/SASS_CHANGELOG.md), so I haven't dug into the source to double check. Is there a `feature-exists` argument for detecting the new SassScript parent-selector features, or should I rely on a simple `function-exists(is-superselector)` check?~~

~~I saw that nearly every other feature had the ability to be detected and was curious if it existed and it just wasn't mentioned in the change log. Looking to incorporate a lot of these functions in a newer version of Flint.~~ :thumbsup: 

_Update:_
I've run into this issue: http://sassmeister.com/gist/999e1fe53571b1412555 &mdash; in order to preserve backwards compatibility, in addition to the new `&`, can we get a function called something like `parent-selector()` that basically acts as an alias for the `&` operator? That way we can properly test and use the new parent selector features without breaking newer versions for users still using `3.3.x`.

**Comment by chriseppstein** [comment]
It is trivial to add this, even in Sass 3.3 as the underlying functionality to support it was not removed.

In compass, I have a function to check if `& == null` that works in sass 3.3:
https://github.com/Compass/compass/blob/master/core/lib/compass/core/sass_extensions/functions/env.rb#L67

If we did add this, I think we'd want it to be immediately deprecated in favor of `&`.

**Comment by chriseppstein** [comment]
@ezekg Can you give me a use case where detecting this helps you do a work around?

**Comment by ezekg** [comment]
I was going to do a similar workaround that you mentioned. Flint uses a custom ruby function that acted as a polyfill for the SassScript parent selector to be able to interpolate it. It simply returns a string of the environment selector. https://github.com/ezekg/flint/blob/master/lib/flint.rb#L24-L26

I want to be able to _fall back_ to the polyfill for newer versions of Flint, while using the new `&` operator for users with Sass >= 3.4. I don't want to cease support for 3.3 right away. Right now, any checks within Sass against the `&` throw an error. I have no problem with creating my own custom wrapper function that acts as an alias; I just wanted to suggest that it be a feature.

I'm just a little confused on how this is supposed to be cleanly implemented into existing systems that function on anything less than 3.4. There's no official way to check that the feature exists without throwing an error from using `&` incorrectly. I feel like an alias is needed because of that. It can be deprecated in 3.5 or whatever.

``` scss
@if function-exists(parent-selector) {
    // ... use & alias
} @else {
    // ... use custom ruby function
}
```

For example... how would you implement this into Compass but retain support for < 3.4 in the process? There's no way to utilize any aspect of the SassScript `&` without throwing an error, even if it was in some type of conditional that was dependent on Ruby; it'll still evaluate and throw the error for incorrect usage within the conditional. Right now, it's useless to me until I hit 2.0.

**Comment by chriseppstein** [comment]
@nex3 Thoughts?

**Comment by nex3** [comment]
In general I'm not particularly interested in ensuring that new syntax is usable without errors on older versions of Sass, nor in going out of our way to make new features syntactically compatible with outdated Sass versions. I feel like requiring users who want access to new features to use the new version of Sass is very reasonable.

**Comment by ezekg** [comment]
Fair enough.
