### ISSUE TITLE
Idea: generate CSS3 prefixes automatically

### ISSUE THREAD

**Issue by rfc2822** [sass/sass#133]
Would be cool if you could set an array of compatibilities, for instance with

"border-radius" => [ "-moz-border-radius", "-webkit-border-radius" ],
...

and SASS could add these prefixed properties to every border-radius. So you could write real CSS3 stylesheets without mixins or something like that while getting broadest browser support

**Comment by pointlessone** [comment]
This may be OK for most cases but it's not universal. For example, gradients have different syntax in older webkit and mozilla. You may want to see how compass solves this problem.

**Comment by rfc2822** [comment]
Thank you, compass is exactly what I have been looking for! Was not aware of it...
