### ISSUE TITLE
Feature request: Allow two-digit hex codes to be used as color values

### ISSUE THREAD

**Issue by brtdv** [sass/sass#1332]
Allow the usage of two-digit hex codes as color codes. When using two digit codes, the two-digit hex code should be used for both R, G and B values

For example:
- `#13` has the same color result as `#131313`
- `#f9` has the same color result as `#f9f9f9`
- `#33` has the same color result as `#333` and `#333333`
- `#cc` has the same color result as `#ccc` and `#cccccc`
- etc.

I have the code needed for this ready for review in my sass fork: 
https://github.com/brtdv/sass/commit/6b1e7ce845c2b13d99b0fd5a08aa41e233bf07df

Thanks!

**Comment by 10xLaCroixDrinker** [comment]
:+1:

**Comment by lolmaus** [comment]
My bet is that @nex3 will turn this down because it will make Sass more different from CSS.

Meanwhile, you can use a custom function to do that. `c(13)` isn't much longer to write than `#13`.

**Comment by chriseppstein** [comment]
@tabatkins Is this going to be legal CSS someday?

**Comment by tabatkins** [comment]
No, it's been discussed before, and we rejected it because there's no way to extend it to handle alpha.

It's just a way of specifying a gray, and we added the `gray()` function instead to handle this use-case.  (You have to use percentages, not hex, but whatever.)

**Comment by nex3** [comment]
@lolmaus is right: we aren't going to support a non-CSS-compatible color literal format.

**Comment by nex3** [comment]
@tabatkins is there a spec for that up somewhere?

**Comment by tabatkins** [comment]
http://dev.w3.org/csswg/css-color/, though we're discussing the name of that function right now. (Much of the draft should be considered unstable right now.)

**Comment by nex3** [comment]
Okay, I'll just keep an eye on it for now.
