### ISSUE TITLE
Color.new(hash) may not have both HSL and RGB keys specified for `rgba'

### ISSUE THREAD

**Issue by willemvb** [sass/sass#1333]
```
$green: #161C14;
$link-color: $green;
$link-color-hover: darken($link-color,10%);
$link-color-tap: rgba($green,0.3);
```

I'm trying to derive some colors in Sass with darken and rgba. It seems that in newer versions of Sass (3.4.0.rc.1) my code that used to work is broken. I get following error on the last line:

```
Color.new(hash) may not have both HSL and RGB keys specified for `rgba'
```

**Comment by cimmanon** [comment]
It's worth noting that it only seems to be related to using the same variable:

``` scss
$green: green;
$link-color-hover: darken($green,10%);
$link-color-tap: rgba($green,0.3);
```

If you're not using a variable (or a different variable), you don't get the error at all:

``` scss
$link-color-hover: darken(green,10%);
$link-color-tap: rgba(green,0.3);
// or
$link-color-hover: darken(#00FF00,10%);
$link-color-tap: rgba(#00FF00,0.3);
```

Calling these functions ahead of `rgba()` seems to trigger the error:
- lighten
- darken
- saturate
- desaturate
- adjust-hue

As a workaround, it looks like you can just change the order of the variable assignment:

``` scss
$green: green;
$link-color-tap: rgba($green,0.3);
$link-color-hover: darken($green,10%);
```

**Comment by ezekg** [comment]
+1. This was driving me insane today until I figured out the issue.
