### ISSUE TITLE
Bug in compilation with variables and quotes in background

### ISSUE THREAD

**Issue by romainberger** [sass/sass#1334]
Hi, 

There are some issues with backgrounds, quotes and variables:

`background: url(/img/foo.png) #{$start} 0 no-repeat;` compiles as: `background:url(/img/foo.png)left� no-repeat;`

Using quotes around the url or using the variable without `#{}` (so using `$start`) fixes the issue.

**Comment by nex3** [comment]
What's the contents of the `$start` variable?
