### ISSUE TITLE
Error compiling variables set by custom functions 

### ISSUE THREAD

**Issue by jimmynotjim** [sass/sass#1336]
I'm finding an error with variables that are set with a custom function, like Bourbon's `tint()` for example, in one file and used in another. I'm not sure if this is a Sass issue, a Bourbon issue or a grunt-sass issue, but I figured I'd start here (and created [a repo](https://github.com/jimmynotjim/sass-function-error) as an example)

If I have a [variable](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/src/scss/_settings.scss#L121) set with a custom color function in one file and call that variable in another, it [compiles](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/dev/style.css#L80) the function as text. If I declare the [variable](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/src/scss/_examples.scss#L1) in the same file as where it's used, it [compiles](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/dev/style.css#L92) fine. If I set a [variable](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/src/scss/_settings.scss#L122) with a default sass color function in one file and call that variable in another it [compiles](https://github.com/jimmynotjim/sass-function-error/blob/master/assets/dev/style.css#L86) fine.

Unfortunately I don't know where the breakdown is or how to test for it but would be more than happy to with some guidance.

**Comment by cimmanon** [comment]
What was the error?  I was not able to generate any errors with your code on Sassmeister:  http://sassmeister.com/gist/874bdce807e7e8f81366

**Comment by jimmynotjim** [comment]
There is no error message, check the links I included in my text and you'll see it's simply not compiling correctly. Also, testing on Sassmeister won't show the error because it only happens when the files are separate as I said in my description.

**Comment by nex3** [comment]
It looks like you're importing the settings file before you're importing bourbon. Sass runs everything in the order it sees it; it hasn't loaded the `tint()` function at the point at which you're calling it.

**Comment by jimmynotjim** [comment]
Ah, I feel like such an idiot. Thanks so much for catching that.
