### ISSUE TITLE
Circular Reference Warnings with RSpec

### ISSUE THREAD

**Issue by mhoad** [sass/sass#1337]
I have created a new project with sass 3.2.19 and Rspec 3.0.2 and whenever I attempt to run my RSpec tests I receive a wall of text warning about a circular reference in sass-rails a sample of which I have included below:

/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-3.2.19/lib/sass/version.rb:5: warning: loading in progress, circular require considered harmful - /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-3.2.19/lib/sass.rb
from /usr/local/opt/rbenv/versions/2.1.2/bin/rspec:23:in <main>' from /usr/local/opt/rbenv/versions/2.1.2/bin/rspec:23:inload'
from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/exe/rspec:4:in <top (required)>' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:ininvoke'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in run' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:inrun'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in setup' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:inload_spec_files'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in each' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:inblock in load_spec_files'

Adding this for reference: https://github.com/rspec/rspec-rails/issues/1103

**Comment by nex3** [comment]
That warning output is very difficult to read.

That said, I think this is an issue with rspec. Circular references are valid Ruby code; rspec's developers may consider them harmful, but they're not in fact causing harm in Sass. rspec shouldn't be complaining about the style in a dependency of the package being tested.

**Comment by deivid-rodriguez** [comment]
This is the warning message with a bit of formatting

```
/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-3.2.19/lib/sass/version.rb:5: warning: loading in progress, circular require considered harmful - /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-3.2.19/lib/sass.rb
from /usr/local/opt/rbenv/versions/2.1.2/bin/rspec:23:in ' from /usr/local/opt/rbenv/versions/2.1.2/bin/rspec:23:inload'
from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/exe/rspec:4:in ' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:ininvoke'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in run' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:inrun'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in setup' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:inload_spec_files'
from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in each' from /usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:inblock in load_spec_files'
```

Just to clarify, this is not rspec developers considering circular requires harmful. The warning actually comes from ruby-core: https://github.com/ruby/ruby/blob/trunk/load.c#L739. Rspec just enabled ruby warnings as a default.

**Comment by nex3** [comment]
Ah, I see. In general we don't write Sass to be warning-clean, although if someone wanted to send a pull request for this I'd merge it in as long as it doesn't make the code quality worse.

**Comment by shiba4life** [comment]
I'm running into this error now.  Is there a workaround?  I suppose I could suppress the ruby warning for now.

**Comment by sinstein** [comment]
Remove `--warnings` from your .rspec file to not see the huge number of warnings.
See [here](http://stackoverflow.com/questions/24072876/too-many-warnings-about-circular-require-when-run-rspec)

**Comment by schnittchen** [comment]
I remember vaguely that ruby's code loading mechanism is not thread safe, guessing that this warning has to do with that problem.
