### ISSUE TITLE
Skip value for margin, padding, border CSS shorthand.

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1339]
The idea I had is to add an `x` or `skip` value, which would be in the same vein as `auto` and `inherit`, that could be used to skip a value, instead of re-defining it or resetting it to 0. Then you could continue still use the CSS shorthand syntax instead of reverting to splitting it up like, `margin-top`, `margin-right` etc.

[I wrote this scss partial, that might do a better job of explaining what exactly I mean](https://github.com/dustindowell22/LifeSaver). I've also added more to it that what I've proposed here: multiple properties, multiple units, and the position property.

The main advantage here is speed in changing values when you don't want to revert or re-define a value. It also keeps everything nice and tidy rather than having blocks of properties for margins and paddings.

With the new `@include` and `@extend` selectors coming up just sticking to my scss partial seems completely plausible now, but I think others might find similar features to be useful too.

**Comment by lolmaus** [comment]
Sass follows a policy of staying true to the original CSS syntax. So until the `skip` keyword is part of the CSS spec, Sass is very unlikely to adopt it.

Using a custom mixin is the recommended way of achieving the result you desire. Consider releasing it as a Compass extension and a Bower package.

**Comment by nex3** [comment]
@lolmaus is correct; we don't want to step on CSS's toes here.
