### ISSUE TITLE
Intended comments processed incorrectly

### ISSUE THREAD

**Issue by curvedmark** [sass/sass#134]
This sass code

```
/*
    comment 1
body
    color: black

    /*
        comment 2
    div
        color: gray

    /*
        comment 3
    p
        color: red
```

generates

```
/* comment 1 */
body {
  color: black;
  /* comment 2 */
  /* comment 3 */
}
body div {
  color: gray;
}
body p {
  color: red;
}
```

Notice `comment2` and `comment3` being put together. This happens to all output modes that don't strip comments

**Comment by chriseppstein** [comment]
I can still reproduce this.

**Comment by nex3** [comment]
This is weird, but expected. Sass considers everything nested beneath a selector to be within that selector's rule unless it explicitly "bubbles" out, like other selectors and media queries. So those comments are nested beneath `body` first, and attached to `div` and `p` second. When `div` and `p` bubble out of the `body` selector, Sass doesn't know to take the comments with them.

You can see the same behavior if you interleave nested selectors and property values:

``` scss
.foo {
  a: b;
  .bar {b: c}
  c: d;
}
```

this compiles to

``` css
.foo {
  a: b;
  c: d;
}
.foo .bar {
  b: c;
}
```
