### ISSUE TITLE
Encoding problem in documentation

### ISSUE THREAD

**Issue by kflorence** [sass/sass#1342]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html

It seems like all `'` and `"` are being replaced by `???`

**Comment by kflorence** [comment]
FYI this is as viewed from Chrome Version 36.0.1985.125 in Mac OSX 10.9.4

**Comment by nex3** [comment]
I think this is caused by @chriseppstein's site deployment setup. It doesn't seem to be a problem for me, so it'll be fixed when I re-deploy later tonight.

**Comment by nex3** [comment]
Re-deploying did indeed clear this up.

**Comment by kflorence** [comment]
:thumbsup:
