### ISSUE TITLE
sass generating empty css filled only with commends

### ISSUE THREAD

**Issue by stephanfriedrich** [sass/sass#1347]
As you can see in these Stackoverflow Question, i believe this its a bug.
++ What Happens:
- Sass generate an Empty Css-Selector within only an Comment. 
  .text { color: red; }
  .article { /\* Texts within article */ p {@extend .text;} }

++ to Reproduce the Problem:
http://sassmeister.com/gist/3116020d285be50b8807

++ Source:
http://stackoverflow.com/questions/24262499/empty-css-block-from-scss-when-using-extends-only/

**Comment by cimmanon** [comment]
Why would this be a bug?  C-style comments are considered content and will always present in the compiled CSS _unless_ you're using an output mode that eliminates _all_ comments.  The selector has to be completely free of content in order for Sass to skip over it when generating the CSS.

**Comment by chriseppstein** [comment]
This is a sass feature. We don't output empty rulesets.
