### ISSUE TITLE
Listen polling fallback.

### ISSUE THREAD

**Issue by ghost** [sass/sass#1351]
When run command like `sass -w app.scss:app.css` it fire up message:

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
[Listen warning]:
  Listen will be polling for changes. Learn more at https://github.com/guard/listen#polling-fallback.
```

Gem list.

```
*** LOCAL GEMS ***

bigdecimal (1.2.4)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
sass (3.3.13)
test-unit (2.1.2.0)
```

Ruby version `2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]`
Ruby installed by `rbenv`.
OS system: Ubuntu 14.04 LTS.

**Comment by nex3** [comment]
Install the `rb-inotify` gem and this message will go away.
