### ISSUE TITLE
SASS_REFERENCE: Missing punctuation characters

### ISSUE THREAD

**Issue by escapist** [sass/sass#1355]
Quotes and apostrophes are rendering as "???" throughout the Sass documentation (at least for me) in both Chrome prod and Safari 7.0.5 for Mac.
![screen shot 2014-08-04 at 10 40 04 am](https://cloud.githubusercontent.com/assets/340097/3800936/6b53c8e6-1bfe-11e4-81f3-a11aee9c7426.png)

**Comment by nex3** [comment]
Duplicate of #1342.
