### ISSUE TITLE
Does --sourcemap=inline or --sourcemap=file behave as expected?

### ISSUE THREAD

**Issue by donotknow** [sass/sass#1357]
Does `--sourcemap=inline` or `--sourcemap=file` behave as expected?

I get the same output I would if I have `--sourcemap=auto` for both `inline` and `file`. A `xxx.css.map` file next to my `xxx.css` file. And a relative reference is at the bottom of my css file:

```
/*# sourceMappingURL=xxx.css.map */
```

I was under the impression `inline` would put the source map inside the original css file. And `file` would have an absolute reference to the source map file (so I can move the css file as a later integration step).

This is for Sass 3.4.0.rc.3 (Selective Steve).

**Comment by nex3** [comment]
The `--sourcemap` option controls how the `.map` file links to the `.sass`/`.scss` files. Currently there's no way to control how the `.css` file links to the `.map` file.

**Comment by jamesmoey** [comment]
@nex3 That is not true. The inline option say, include the source text in the sourcemap. Not how .map file link to the source file. As @donotknow say, setting the sourcemap option to inline or file produce the same result. Obviously this is incorrect and broken in sass compiler. I have tested it on version 3.4.6. The result is the same as @donotknow finding.

Please reopen this ticket. This is a valid ticket.

**Comment by nex3** [comment]
>  The inline option say, include the source text in the sourcemap. Not how .map file link to the source file.

I'm not sure what you think the difference between these two is—the source map is the `.map` file, and with `--sourcemap=inline` it does include the contents of the original source file.

**Comment by jamesmoey** [comment]
Now I understand. I was thinking for the ability to include the content of the map file and source file in the resulting css. So no .map file is generated.

**Comment by geryit** [comment]
if using config file:
`sass_options = {:sourcemap => :inline}`
