### ISSUE TITLE
Compressed option doesn't remove all line breaks (worse in 3.3)

### ISSUE THREAD

**Issue by stowball** [sass/sass#1358]
I was working with a colleague and we were using different versions of Sass to compile (me 3.2.14, him 3.3.12).

After he compiled the Sass, there were a lot of differences in the code, all of which were new line breaks.

Upon further inspection, using `compressed` in 3.2.x removes many more line breaks than 3.3.x.

Here are two demos showing the difference of the raw output from the base [Suzi](https://github.com/izilla/Suzi):

3.2 - http://sassmeister.com/gist/aad5acd9f66c46ec9603 - notice that the compiled CSS is all on 1 line. Developing Actual projects can produce 3-5 lines on average.

3.3 - http://sassmeister.com/gist/7aa800992ba8335ab00c - notice that the compiled CSS is already on 4 lines.

In my current project, I used grunt to regex replace all line breaks, and it saved a few hundred bytes, which equated to 97 bytes after gzipping, so it does make a difference

**Comment by stowball** [comment]
OK, it's something to do with media queries. Here's just my media query mixin output, which in 3.2 is on 1 line, & 3.3 & 3.4 on 2 lines: http://sassmeister.com/gist/72d572753b47283ab56b

**Comment by paulomunoz** [comment]
I am having the same problem here, it's weird that in my css some of the media queries are compressed properly but some are not, having a line break right after it's closing element ( } ). I wonder why this happens, I suppose compressed mode should remove all line breaks right?

I've been noticing this for a while but never really tried to find a solution online, and stumbled upon this issue. I could write a task to remove the line breaks manually, I just don't think it's worth it as that would give me only about 80bytes(?) less, so never mind.

But it would be nice to have it fixed.

Cheers

**Comment by nex3** [comment]
I believe this is fixed in the latest release.

**Comment by stowball** [comment]
Fix confirmed in 3.4.12 \o/
