### ISSUE TITLE
Cannot specify variables scope in @function

### ISSUE THREAD

**Issue by charlesdemers** [sass/sass#136]
It would be nice to be able to declare local variables inside @function blocks. Maybe a new keyword like @var could specify that the following variable should be used only within the @function ?

**Comment by chriseppstein** [comment]
I like this idea, but in keeping with the syntax for default values, what do you think about:

```
$foo: value !local;
```

**Comment by charlesdemers** [comment]
I didn't think of it that way but it sounds even better than my proposition. I'd definitely go with that syntax.

**Comment by chriseppstein** [comment]
bump. @nex3 is this a candidate for 3.2?

**Comment by nex3** [comment]
Variables declared in functions are always local. The only case in which they wouldn't be is if there's already a global variable with the same name. Is this feature request for making local variables that shadow globals? I'm not convinced that use case is worth adding syntax.

**Comment by chriseppstein** [comment]
I think we need a !local variable declaration and that it should be best practice to use local vars in functions and mixins. 

In truth, I'd prefer all variables not declared in the global scope to require a !global modifier if they don't shadow, but this is a harder change to coordinate. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by nex3** [comment]
I don't want the best practice to be making variable declarations substantially more verbose than they are now. If this problem needs to be solved, changing the semantics is a better way forward even if it's backwards-incompatible. We could just add `!global`, or we could do a more thorough overhaul of the variable semantics to more closely match the semantics of CSS variables.

Either way, it's way too big of a change to do before 3.2.

**Comment by arcreative** [comment]
Any update on this? This issue, to me, is the single thing wrong with SASS.  I don't think there's a single situation where using solely global scoped variables provides an advantage, especially when your SASS code gets relatively large.  I think that generally the expectation with nested structures (that look strangely like functions) is that the scope will be local, and won't override your global values when nested 3 selectors deep.  I know this would most likely be a breaking change for some, but I don't think anyone would have a problem with it given a little warning.

**Comment by chriseppstein** [comment]
Matching the CSS variable semantics presents a number of complications that I do not know how to solve in a preprocessor because variable resolution depends on the document structure (a better name for css variables would be 'custom css properties' in terms of how they work).

I agree that our variable semantics need work. But if `!local` is off the table (for the very good reasons that @nex3 has given) then this is a fairly big change. Changing the lookup semantics is actually very easy, but in order to not break every sass file, we would have to create an upgrade script that correctly declares variables that are presently global as such in the new version (and this would need to be done in a major version release: 4.0).

In the meantime, a (disgusting) workaround would be to declare all your local variables as an argument with a default value of `null`.

**Comment by arcreative** [comment]
Maybe this is the wrong thread, but I'm looking for variables that are scoped to a particular selector in SCSS.  In the case of nested selectors, the !local syntax would work exactly as "var" would in javascript.  I think this functionality would be indispensable. 

Also, I'm not entirely sure that there would need to be an upgrade script with the way that most people use variables in sass/scss.  Under almost all circumstances, I see people define them in a globals include, unnested or within the selector in which they expect to use them.  I've experienced a few breaking changes in version 3 that required much more work to fix than a change like this, I think this should be relatively safe with a little note in the readme :-)

**Comment by nex3** [comment]
We have a process for introducing breaking changes that takes at least two major releases. In the first release, we detect all code that will be broken by the change, warn about it, and provide an upgrade path; once that's been in the wild for a while, we can release a new version with the change. This change is major enough that we'd want to target it at Sass 4, and likely bundle it with other large-scale changes so we can provide a single upgrade script.

**Comment by zhigang1992** [comment]
I don't think a `!global` is enough,
result is still not as expected when nesting:

``` scss
.parent {
  $color: red;
  .son {
    $color: black;
    color: $color;
  }
  .something {
    color: $color; //This one here is black, but expecting red;
  }
}
```

**Comment by nex3** [comment]
That is the expected behavior. Local variables don't shadow one another. This is pretty standard for languages that don't have a declaration keyword.
