### ISSUE TITLE
Asset-url

### ISSUE THREAD

**Issue by glebm** [sass/sass#1361]
I would like to do something about asset-url helpers in Compass and Sprockets. They make writing and using universally compatible libraries very difficult. Example at hand is bootstrap-sass ([1](https://github.com/twbs/bootstrap-sass/blob/v3.2.0%2B1/assets/stylesheets/bootstrap/_variables.scss#L1-L4), [2](https://github.com/twbs/bootstrap-sass/blob/v3.2.0%2B1/assets/stylesheets/bootstrap/_glyphicons.scss#L17-L21), [3](https://github.com/twbs/bootstrap-sass/blob/v3.2.0%2B1/assets/stylesheets/_bootstrap-sprockets.scss), [4](https://github.com/twbs/bootstrap-sass/blob/v3.2.0%2B1/assets/stylesheets/_bootstrap-compass.scss), [5](https://github.com/twbs/bootstrap-sass/blob/v3.2.0%2B1/assets/stylesheets/_bootstrap-mincer.scss)).

Perhaps we can use `url()` and delegate it to the helper automatically, instead of calling the helpers directly. For example, `url("logo.png")` would be the same as `url(asset-path("logo.png"))` in Sprockets. I've started on a pure Sass library that does this via overriding `@function url($path)` here: https://github.com/glebm/sass-rewrite-url. 

It almost works, but can unquoted strings be processed this way?

**Comment by chriseppstein** [comment]
the url function in CSS has special parsing rules to allow it to treat the argument as a string. Sass has special handling for this, but when it's triggered it's a special string instead of a function call. @nex3 perhaps we should parse the url as a function call with an unquoted string as the argument instead of as a special string?

**Comment by nex3** [comment]
I don't like the idea of overriding the functionality of `url()` at all. Sass goes to great pains to make it clear when users are writing plain versus augmented CSS, and this breaks that entirely. I also don't want to encourage people to monkey-patch external styles in the way this seems to do.

**Comment by glebm** [comment]
Yeah, hidden variable is a bad solution.

If Sass had some kind of native `asset-path` in the core, libraries could include assets compatibly:

``` scss
  background-image: url(asset-path('logo.png'));
```

`logo.png` would be resolved relative to the file and from asset load paths in pure Sass, while environments such as Sprockets could extend the load paths or even override `asset-path` function.

**Comment by nex3** [comment]
Sass very explicitly avoids having any knowledge of project structure, including asset paths. This is the job of layers on top of it like Compass.
