### ISSUE TITLE
High CPU usage on OS X 10.6.8

### ISSUE THREAD

**Issue by 1GR3** [sass/sass#1365]
Hello,
I've recommended sass to my wife but it uses over 90% of CPU when watching a single scss file.
Configuration:
MacBook Pro
Intel Core 2 Duo @ 2.4 GHz
4 GB Ram
OSX 10.6.8
Ruby v2.0
Sass v3.3.14

Any help would be highly appreciated!

**Comment by nex3** [comment]
Do you have the rb-fsevents gem installed? It's necessary to use the native OS X filesystem watching functionality.

Also, for future reference, support requests are more appropriately directed to [the mailing list](https://groups.google.com/forum/#!forum/sass-lang).
