### ISSUE TITLE
importer is nil in staleness_checker.rb

### ISSUE THREAD

**Issue by briangonzalez** [sass/sass#1366]
I am not too familiar with this code, but I am finding that `importer` [here](https://github.com/sass/sass/blob/2045a314e2fcd2a5f32d358a4ba57409089e6372/lib/sass/plugin/staleness_checker.rb#L134) is sometimes nil, which causes sass compilation to error out.

Adding in `return unless importer` above line 134 fixed the issue for me.

**Comment by chriseppstein** [comment]
@briangonzalez The importer is not allowed to be nil. Can I see a stack trace and also a list of rubygems that you are using with your project?

**Comment by briangonzalez** [comment]
I believe the offending gem is `sass-json-vars` (0.3.1), as commenting out the pertinent code mitigates the issue.

**Stack Trace**

```
NoMethodError on line ["134"] of /Users/brian/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.14/lib/sass/plugin/staleness_checker.rb: undefined method `mtime' for nil:NilClass
Run with --trace to see the full backtrace
```

**Comment by briangonzalez** [comment]
Also, here is my project's Gemfile:

``` ruby
# Gemfile
gem 'sass', '3.3.13', :git => 'https://github.com/briangonzalez/sass.git', :ref => 'bfb8d0d'
gem 'compass', '~> 1.0.0.rc.1'
gem 'sass-globbing', '~> 1.1.1'
gem 'sass-json-vars', '~> 0.3.1'
gem 'breakpoint-slicer', '~> 1.2'
gem 'susy', '~> 2.0.0'

gem 'capistrano', '~> 3.2.1'
gem 'capistrano-rvm', '~> 0.1.1'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'hipchat', '~> 1.2.0'
```

**Comment by chriseppstein** [comment]
Please file a bug with `sass-json-vars`.

**Comment by nhunzaker** [comment]
Just following up as a maintainer of the `sass-json-vars` repo. @chriseppstein -- is the recommended route to implement an `mtime` method as you have done in `sass-globbing`? If not, is there a reference you could point me to for the best practice for implementing an `Importer` plugin?

Here is what I am referencing:
https://github.com/chriseppstein/sass-globbing/blob/master/lib/sass/globbing/importer.rb#L54-L71

**Comment by chriseppstein** [comment]
Yep, in their case, they'll want to look at the mtime of the json file.

**Comment by nhunzaker** [comment]
Just to follow up. It looks like we weren't passing options to the `Sass::Engine` that does the final conversion. I believe I have corrected this in `sass-json-vars`

**Comment by chriseppstein** [comment]
@nhunzaker looks great :+1:
