### ISSUE TITLE
integrate clean-css style minifcation

### ISSUE THREAD

**Issue by mattkime** [sass/sass#1371]
https://github.com/GoalSmashers/clean-css

I can generally get about 5% smaller css using the above tool. the problem using it in conjunction with sass is that i can no longer create sourcemaps.

**Comment by nex3** [comment]
This isn't a very useful issue since it doesn't highlight explicit improvements that could be made to the existing minification in Sass. Feel free to file separate, more explicit issues for those improvements.

**Comment by ghost** [comment]
See also: #847
