### ISSUE TITLE
Error while saving to file system cache store

### ISSUE THREAD

**Issue by gettalong** [sass/sass#1372]
After updating from Sass 3.2.19 to Sass 3.3.0 or higher, I get the following warning during `rake test`:

```
Warning. Error encountered while saving cache /tmp/.../_other.scssc: singleton can't be dumped
```

I have read the release notes but didn't find anything related to this in them.

The program in question, webgen, uses the `Sass::CacheStores::Filesystem` to store compiled sass files to a temporary location. As described above this worked without warning until the 3.2.19 release.

The code in use can be seen at the following location: https://github.com/gettalong/webgen/blob/master/lib/webgen/content_processor/sass.rb

Have there been some changes related to this?

**Comment by nex3** [comment]
3.3 added source map support, which involves storing importers in the cache. All importers are [required to be serializable](https://github.com/sass/sass/blob/adc12b9a360f62871d7ec115a3f0d62309da32c5/lib/sass/importers/base.rb#L17); I'd guess Webgen's `NodeTreeImporter` is not.

**Comment by gettalong** [comment]
Thanks for the pointer, I will have a look at this!
