### ISSUE TITLE
Responsive Test page is broken

### ISSUE THREAD

**Issue by vongoh** [sass/sass#1374]
I've been designing responsive using the very useful Responsive Test page on `sass-lang.com` for quite a while now.

[Sass Responsive Test](http://sass-lang.com/styleguide/responsive-test)

However - clicking on the link above demonstrates that the URL box for the test is now covered up by a banner for Sass sticker sales.   Hence we can no longer use this page to help design our sites.

I'm pretty sure Ive seen similar utilities online somewhere (any suggestions welcome) to replace this with .. but .. I'm pretty sure this is not what you guys intended.  Thanks :)

**Comment by nex3** [comment]
Moved this to sass/sass-site#94.
