### ISSUE TITLE
Sourcemaps always output even when not using --sourcemap in Compass 1.0.0

### ISSUE THREAD

**Issue by patw0929** [sass/sass#1378]
I'm using Sass 3.3.14 and Compass 1.0.0.
It's always output sourcemap files even when not using `--sourcemap` option in Compass command line. (without config.rb file in my case.)

I found out that might be the issue in `update_stylesheets` method. When I'm not using `--sourcemap` option, it still sent `sourcemap` to `update_stylesheet`. So I add a ternary operators to fix, and it works as expected.

I'm not sure this fix is right or not, please kindly provide some help. Thanks!

782c4c44d3866d4f8f48ce4b6b87046b3310111e:

``` diff
diff --git a/lib/sass/plugin/compiler.rb b/lib/sass/plugin/compiler.rb
index 9626435..cf710e9 100644
--- a/lib/sass/plugin/compiler.rb
+++ b/lib/sass/plugin/compiler.rb
@@ -211,7 +211,7 @@ module Sass::Plugin
           # XXX For consistency, this should return the sourcemap too, but it would
           # XXX be an API change.
           updated_stylesheets << [file, css]
-          update_stylesheet(file, css, sourcemap)
+          update_stylesheet(file, css, options[:sourcemap] ? sourcemap : nil)
         else
           run_not_updating_stylesheet(file, css, sourcemap)
         end
```

**Comment by nex3** [comment]
This is the intended behavior. Sourcemaps are now on by default. In Sass at least, you can pass `--sourcemap=none` to disable them; I'm not sure whether Compass supports the same option.

**Comment by chriseppstein** [comment]
@nex3 According to @patw0929 the sass version was 3.3

**Comment by nex3** [comment]
Sass 3.3 is no longer supported.
