### ISSUE TITLE
@extend adds extra markup into :not() selector

### ISSUE THREAD

**Issue by blunckr** [sass/sass#1380]
This issue is difficult to describe, it's easiest if you just look at this gist: http://sassmeister.com/gist/654ddb3e40585c408767

You can see that I'm extending 'button' with a class, and in my selector I'm using button within the :not selector. This is causing it to put the extended version of button in the :not selector, which fails because not statements only handle simple selectors. It only happens in 3.4.0.

**Comment by blunckr** [comment]
Note that the selector doesn't have to be 'button' to see this issue

**Comment by lolmaus** [comment]
That's a good catch.

**Comment by chriseppstein** [comment]
That's intended and was a bug fixed in 3.4. You's saying that .another-thing is a button. So now .something's that are not buttons should also not be an .another-thing.

**Comment by blunckr** [comment]
Then the issue is that the selector is being generated incorrectly
Take a look at this updated one with html

http://sassmeister.com/gist/02ea823e832098e797d8

The text should be green since it's not a button or an .another-thing, but you can see that it's not. That's because :not() doesn't allow comma selectors, the rule would have to be .something:not(button):not(.another-thing).

**Comment by chriseppstein** [comment]
I see, yes, it's breaking in chrome. I think we should generate `.something:not(button):not(.another-thing)` instead of `.something:not(button, .another-thing)` to avoid breaking in current browsers.

**Comment by satya164** [comment]
Following the same issue, I have the following code,

```
a:not(.button) {}
```

Sass is expanding it to,

```
a:not(.button, button, input[type="submit"], input[type="button"]) {}
```

I have the following in the .button class, but I think that shouldn't affect my normal CSS syntax. It breaks my code at many places now :(

```
button, input[type="submit"], input[type="button"] {
    @extend .button;        
}
```

My Sass version is Sass 3.4.0 (Selective Steve)
