### ISSUE TITLE
Variables are not replaced when using calc()

### ISSUE THREAD

**Issue by roscopeeco** [sass/sass#1381]
Hello

I have tried using variables within the css calc routine but it doesn't work. The .css output contains a reference to the variable so it hasn't been parsed.
# .scss file

$page-width:948px;
$page-height:622px;

.wrapper {
  min-width: calc($page-width + 280px + 20px);
  min-height: calc($page-height + 126px);
  min-width: -webkit-calc($page-width + 280px + 20px);
  min-height: -webkit-calc($page-height + 126px);
# }
# .css output

.wrapper {
  min-width: calc($page-width + 280px + 20px);
  min-height: calc($page-height + 126px);
  min-width: -webkit-calc($page-width + 280px + 20px);
  min-height: -webkit-calc($page-height + 126px);
# }

thanks

Ross

**Comment by lolmaus** [comment]
Try interpolating the with `#{ }`

**Comment by roscopeeco** [comment]
ok that worked a treat and thanks for the quick reply!

cheers
