### ISSUE TITLE
--watch not working as of 3.4.0

### ISSUE THREAD

**Issue by cshawaus** [sass/sass#1382]
After upgrading to `3.4.0` the --watch function no longer detects file changes and strangely enough doesn't trigger any issues whatsoever, others are having the same issue as well.

Rolling back to `3.3.14` fixes the issue.

**Comment by lolmaus** [comment]
Please report your environment: OS, Ruby version, etc.

Also please post either `Gemfile` and `Gemfile.lock` or `gem list` (post a link to a gist).

**Comment by cshawaus** [comment]
Sorry about the missing info.

Windows 8.1 Pro
**Ruby version:** ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
**Gem version:** 2.0.14

https://gist.github.com/ChrisUpjohn/ef778ae5c89800fa1916

Also I only just installed Ruby and Sass on this PC tonight so there were no previous versions installed before hand.

**Comment by tmugford** [comment]
Same issue here. Updated today and immediately stopped working. No errors.

OS X 10.9.4 (Mavericks)
ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
[gem list](https://gist.github.com/tmugford/4a6fe90ade47671b5a1d)

**Comment by btkarthick** [comment]
I am also facing the same issue. Updated to 3.4, initial watch is working but, its not updating the subsequent .scss updates to css. 

I am using,
Window 2008 server R2,
ruby 1.9.3-p545

Reverting back to 3.3.14 fixes the issue.

**Comment by skristensen** [comment]
Same issue here. Just updated to 3.4.0 today
--watch no longer picks up on the changes I do to the files I've specified it to watch, but apparantly picks up on non sass related changes (like deleting image files, etc).

Windows 7
gem version ?
Ruby 1.9.3-p374

**Comment by chriseppstein** [comment]
It would be super helpful if someone can run a git bisect and let us know which commit broke this.

**Comment by chriseppstein** [comment]
Also, try installing the `listen` gem and let us know if that fixes things for you.

**Comment by cshawaus** [comment]
I've done some deeper debugging and have found that `normalized_load_paths` in `lib/sass/plugin/compiler.rb` is always empty which is resulting in `recompile_required` on `on_file_changed` to always remain false when a status of modified is true.

I manually overrode that variable to stay true and `--watch` began to work as expected, I'm not too familiar with with the `git bisect` command but I did go through the commit logs but to no avail found nothing weird.

**Comment by kalepail** [comment]
Yep, broken for me as well. Tried installing listen gem, no go.

OSX 10.9.4 (Mavericks)
Ruby 2.1.2p95
[Gem List](https://gist.github.com/tyvdh/6e54b1c910303da489b1)

**Comment by eshikerya** [comment]
Same here, had to rollback to 3.3.14
OSX 10.10 (Yosemite public beta 1)
Ruby 2.0.0p481
Gem List

```
bigdecimal (1.2.5, 1.2.0)
CFPropertyList (2.2.8)
chunky_png (1.3.1, 1.3.0)
compass (1.0.1)
compass-core (1.0.1)
compass-import-once (1.0.5)
ffi (1.9.3)
fssm (0.2.10)
io-console (0.4.2)
json (1.8.1, 1.7.7)
libxml-ruby (2.7.0, 2.6.0)
mini_portile (0.6.1, 0.6.0)
minitest (5.4.0, 5.3.4, 4.3.2)
multi_json (1.10.1)
nokogiri (1.6.3.1)
power_assert (0.1.3)
psych (2.0.5, 2.0.0)
rake (10.3.2, 0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.1.1, 4.0.0)
rubygems-update (2.4.1)
sass (3.3.14)
sqlite3 (1.3.9, 1.3.7)
test-unit (3.0.1, 2.5.5, 2.0.0.0)
```

**Comment by andymb** [comment]
Same here:

OSX 10.9.4 (Mavericks) fresh installation
ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]

bigdecimal (1.2.0)
celluloid (0.15.2)
CFPropertyList (2.2.0)
ffi (1.9.3)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
listen (2.4.1)
minitest (4.3.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.0.0)
sass (3.3.14)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
timers (1.1.0)

Uninstalling and replacing with 3.3.14 fixed it.

**Comment by zquintana** [comment]
I'm having the same issue after upgrading to Max OS to Yosemite

**Comment by nex3** [comment]
@zquintana What versions of Sass and Ruby are you using? How about gems?

**Comment by zquintana** [comment]
@nex3 Thanks for responding, it turns out it was a problem on my end. I had 2 directories with same structure and was running the command from the wrong directory. Thanks again, and sorry about that.

**Comment by nex3** [comment]
Glad to hear it wasn't a problem on our end!
