### ISSUE TITLE
Variable shadowed in @if block

### ISSUE THREAD

**Issue by scofalik** [sass/sass#1386]
```
$myVar: 10;
$myBool: true;
@if ($myBool == true) {
  $myVar:7;
}
@debug $myVar;
```

Result: `DEBUG: 10`
Expected: `DEBUG: 7`

Variables should not be shadowed in if blocks. This behavior is not happening in any language I know. I hope this is a bug not a feature.

**Comment by mprins** [comment]
this is a bug in 3.4.x

use the following gist: http://sassmeister.com/gist/839a339544d9db05ef10

| sass | result |
| --- | --- |
| sass 3.4.0 | 10 |
| sass 3.3.x | 7 |
| libsass | 7 |
| sass 3.2.x | 7 |

also http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variables_ says it should be 7

**Comment by FWeinb** [comment]
If you use `!global` it is working:
http://sassmeister.com/gist/1eab32c886ebe63294ee

It looks like `@if` is creating a new scope.

**Comment by lolmaus** [comment]
I agree that variable scoping in `@if` constructs is something completely unexpected.

Meanwhile, you can work it around like this:

``` scss
$myVar: 10;
$myBool: true;
@if ($myBool == true) {
  $myVar: 7 !global;
}
```

http://sassmeister.com/gist/42d201c4132fda1e4586

**Comment by Snugug** [comment]
This is only a problem when you have an `@if` in your global scope. Same example inside a mixin works fine:
http://sassmeister.com/gist/a9ba57e1f143c87451d0

**Comment by scofalik** [comment]
I know this is happening only in 3.4.x because that's when variable shadowing was introduced. I know that `!global` is a workaround but this shouldn't happen in the first place.

I downgraded SASS to 3.3.14 and I am waiting for bugfix. I don't think there is much use in fixing the code right now.

It is interesting to see that the code is working in mixins, though.
