### ISSUE TITLE
The `--sourcemap=none` flag is not working still generating mapping files

### ISSUE THREAD

**Issue by dutchwebworks** [sass/sass#1387]
On Windows 8.1 using Ruby Sass 3.4.0, the option to **disable the automatic creation** of the `*.css.map` can't be disabled using the new `--sourcemap=none` flag. The compiler still generates a `*.css.map` file.

Now every time I do a Sass compile, Sass generates the `*.css.map` file AND writes a comment at the end of the Css referencing the `*.css.map` file. All fine for local dev. and debugging but on a production site, **browser Dev-tools** request this non-existing (on production server) `*.css.map` file and result in a **Error 404** on these file types.

**Comment by lcdsantos** [comment]
Works:
`sass --sourcemap=none style.scss style.css`

Don't work, still generate .map file:
`sass --update --sourcemap=none style.scss:style.css`

![captura de tela 2014-08-22 09 29 45](https://cloud.githubusercontent.com/assets/910974/4010614/28cb3164-29f8-11e4-889c-8d9197a97601.png)

Windows 7 x64
Sass 3.4.0

**Comment by ralokt** [comment]
Why is this issue closed?

If it won't be fixed, at least the documentation should specify that `--sourcemap=none` does not apply with `--update`.

This is currently not clear at all:
```
$ sass --help
(...)
        --sourcemap=TYPE             How to link generated output to the source files.
                                       auto (default): relative paths where possible, file URIs elsewhere
                                       file: always absolute file URIs
                                       inline: include the source text in the sourcemap
                                       none: no sourcemaps
(...)
```

**Comment by nex3** [comment]
It was closed because it was fixed in https://github.com/sass/sass/commit/a1e4fd4bbb9a1a6b403468741007e7d88d258a03. Unfortunately, because this is technically a breaking change and [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811), it won't make it into a stable release.

**Comment by ralokt** [comment]
Thanks for the clarification, that makes a lot of sense.

And also, huge thanks for libsass!
