### ISSUE TITLE
:not() selectors are broken

### ISSUE THREAD

**Issue by satya164** [sass/sass#1388]
I have the following code,

```
a:not(.button) {}
```

Sass is expanding it to,

```
a:not(.button, button, input[type="submit"], input[type="button"]) {}
```

I have the following in the `.button` class, but I think that shouldn't affect my normal CSS syntax. It breaks my code at many places now :(

```
button, input[type="submit"], input[type="button"] {
    @extend .button;        
}
```

My Sass version is `Sass 3.4.0 (Selective Steve)`

**Comment by lolmaus** [comment]
Duplicate of #1380.

**Comment by satya164** [comment]
@lolmaus that bug says attribute selectors. Mine is just a class selector.

**Comment by lolmaus** [comment]
@satya164, sorry, i gave wrong issue number. I've modified my comment, adding the valid issue number.

**Comment by satya164** [comment]
@lolmaus Thanks. Closing this issue.
