### ISSUE TITLE
Using sass-spec for testing

### ISSUE THREAD

**Issue by michaek** [sass/sass#1390]
I know there are already a number of fixtures for testing Sass in the test/ directory, but it seems that the cases in https://github.com/sass/sass-spec are more extensive. Would Sass consider integrating sass-spec into its testing workflow?

This could help ensure that Sass implementations in other languages (such as libsass) are consistent with the reference implementation in Ruby.

**Comment by chriseppstein** [comment]
Yes, this is on my TODO list.

**Comment by michaek** [comment]
That's great news! If you'd like me to help with implementing it, feel free to let me know how you were thinking about moving forward.

**Comment by nex3** [comment]
@chriseppstein Can this be closed out, or is there more you want to do?

**Comment by chriseppstein** [comment]
This is now in place. I will review contribution documentation to make sure that the workflow is clear.

**Comment by chriseppstein** [comment]
Docs in bbc7663c1e24ed7f8e7014f356af1f6c4209aac9
