### ISSUE TITLE
sass --watch failing with 3.4.1 under Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by magnetikonline** [sass/sass#1393]
Having an issue with 3.4.1 (and 3.4.0 as well, 3.3.14 is last good working version) where changes to files are not being picked up with the --watch option, when watching a directory structure.
# Example

``` sh
$ echo ".class {}" > blah.scss 
$ sass --watch /path/to/pwd
# in another terminal
$ touch blah.scss
# result is no change is detected by watching sass process
```

Note, if I change sass to watch a specific file (e.g. `sass --watch /path/to/blah.scss`) the individual file will be watched correctly and updated - but of course this is a single file.
# OS specifics

``` sh
$ uname -a
Linux magnetikxps 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ gem list
*** LOCAL GEMS ***

celluloid (0.15.2)
celluloid-io (0.15.0)
ffi (1.9.3)
listen (2.7.9, 2.7.1)
nio4r (1.0.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.5, 0.9.3)
sass (3.4.1, 3.3.14)
sass-globbing (1.1.1)
timers (1.1.0)
```

**Comment by anthwinter** [comment]
I have been having 'watch' problems with 3.4.1 also. At first it seemed to be only after errors occurred, but I've noticed it happening straight after running the watch command now too.

OS X 10.9.4

**Comment by mboisvertdupras** [comment]
I'm having the same problem. It was working fine in previous versions until I upgraded to 3.4.1 a few days ago. Reverting back to 3.3.14 fixes the issue as others have noted.

Ubuntu 14.04 ( elementary OS Freya )

marc@tinky:/var/www/html/alpha/styles$ uname -a
Linux tinky 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
marc@tinky:/var/www/html/alpha/styles$ gem list

**\* LOCAL GEMS ***

bootstrap-sass (3.2.0.1)
chunky_png (1.3.1, 1.2.8)
compass (0.12.2)
compass-core (1.0.1)
compass-import-once (1.0.5)
ffi (1.9.3)
fssm (0.2.10)
multi_json (1.10.1)
oily_png (1.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.2)
rdoc (3.9.4)
sass (3.4.1, 3.3.8, 3.2.12)

**Comment by corbanCloud** [comment]
I am also having this issue. Running Ubuntu 14.04, and Sass 3.4.1. Reverting to 3.3.14 fixes issue.

**\* LOCAL GEMS ***
bigdecimal (1.1.0)
bundler (1.6.2)
bundler-unload (1.0.2)
celluloid (0.16.0.pre3)
coderay (1.1.0)
executable-hooks (1.3.2)
ffi (1.9.3)
formatador (0.2.5)
gem-wrappers (1.2.5)
guard (2.6.1)
guard-sass (1.4.0)
hitimes (1.2.2)
io-console (0.3)
json (1.5.5)
listen (2.7.9)
lumberjack (1.0.9)
method_source (0.8.2)
minitest (2.5.1)
pry (0.10.1)
rake (0.9.2.2)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (3.9.5)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.3.14)
sass-globbing (1.1.1)
slop (3.6.0)
thor (0.19.1)
timers (4.0.0)

**Comment by nex3** [comment]
I can't seem to reproduce this using any combination of software I've tried and on multiple computers. Clearly it's not just a flake, since so many people are seeing it, and I'm on Ubuntu as well so I _should_ be able to reproduce it.

What versions of Ruby are y'all using? What specific command-line invocations are you doing? Can you post a Gemfile.lock for a project that demonstrates the issue?

**Comment by magnetikonline** [comment]
Hey Nat,

  thanks for looking into this - somewhat relieved :smile: that I'm not the only one.

``` sh
$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

An example that fails for me was added in the opening post.

**EDIT:** Also, assuming you are on Ubuntu 14.04LTS? Not something earlier/later?

Thx

   Pete

**Comment by mboisvertdupras** [comment]
Ruby:

```
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

And here's the command I'm using:
`sass --watch main.scss:main.css`

And also, here's Gemfile.lock although I'm using Bundler right now to work around the problem.

```
GEM
  remote: https://rubygems.org/
  specs:
    sass (3.3.14)

PLATFORMS
  ruby

DEPENDENCIES
  sass (~> 3.3.8)
```

Thanks !

**Comment by magnetikonline** [comment]
@Marc-Boisvert-Dupras now the weird thing is - for a single file it **does** work for me, it's only when watching a full path of files that things don't watch correctly.

I see we are on the same version of Ruby (more than likely the Ubuntu default).

**Comment by mboisvertdupras** [comment]
@magnetikonline Weird indeed. For me, watching for a complete directory works the first time when I make changes but then after that I have to either delete the .sass-cache folder and re-run sass --watch ~/example:~/example2

**Comment by magnetikonline** [comment]
Okay @nex3 - think I'm onto something, --watch is now (I swear it was failing _all the time_ when I raised this!) only when I give an _absolute_ directory watch path.

I run sass via this script to keep the `.sass-cache` directory out of my project(s).

https://gist.github.com/magnetikonline/5735040

So from that - this works:

``` sh
$ sass \
  -r sass-globbing \
  --scss --style expanded --watch css \
  --cache-location /tmp/sasscache/f6f3ddbe95fae8271542e9b5267abe24/
```

this does not:

``` sh
$ sass \
  -r sass-globbing \
  --scss --style expanded --watch /path/to/css \
  --cache-location /tmp/sasscache/f6f3ddbe95fae8271542e9b5267abe24/
```

**Comment by nex3** [comment]
Still can't reproduce this, even using 1.9.3p484 and using identical invocations to the opening example.  I could still use a Gemfile, though.

@magnetikonline I've been running with absolute paths without reproducing the issue, although the fact that it matters for you is certainly interesting information. Can you reproduce this if you run without your script or any additional flags on just a dummy script?

Also, it's possible that the specific path to your CSS matters. Is there any chance it's on a different drive or something than your working directory or cache?

**Comment by magnetikonline** [comment]
@nex3  yeah tested that... I have symlinks to project paths and have even tried with/without the symlinks to the project roots. In every case if I give a relative path it's now working fine - absolutes (which my script does via `pwd`) fails to watch.

**EDIT:** actually, now I'm getting confused :smile:  it's the symlinks that are doing it.

**Comment by nex3** [comment]
And when you say "fails to watch", you mean you don't get any "Change detected" notifications no matter what you change?

**Comment by magnetikonline** [comment]
@nex3 yeah I get an initial build, afterwards `touch` to a file does nothing/no recompile.

Just to confirm I have isolated it to giving a watch path that is part of symlink (soft, not hard symlink). Even with the sass-globbing library enabled/disabled it's consistent behaviour.

This used to be okay with pre 3.4 releases.

**Comment by nex3** [comment]
Ah ha! The symlink thing seems to have been the key. I can reproduce it now.

**Comment by magnetikonline** [comment]
@nex3 yep - at least for me :)

Revised my sass watch script - now getting the resolved path using `pwd -P`, does the trick for me. :smile: .

https://gist.github.com/magnetikonline/5735040/revisions

**EDIT:** thanks heaps Natalie, appreciate your time on this. For me at least, I'm a happy camper now :)

**Comment by imohkay** [comment]
Hey I'm having the same problem on Xubuntu 14.04... upgraded to 3.4.3, still doesn't work... watch only updates the first set of changes... than i need to run it again...

**Comment by nex3** [comment]
Can you provide details about your setup? What version of Ruby and `listen` do you have? What exact  invocation of the command are you using? What does your directory structure look like? Are any of the directories symlinks or on a different volume from one another, or from your Ruby installation?

**Comment by lolmaus** [comment]
Hey @imohkay, try locking your Sass version and its dependencies with Bundler.

Install Bundler with `gem install bundler`.

Create a `Gemfile` in the root of your project with the following content:

``` rb
source 'https://rubygems.org/'
gem 'sass', '~> 3.4.3'
```

If you're using Compass, also add this:

``` rb
gem 'compass', '~> 1.0.1'
```

Then run `bundle install` in that folder.

Then try using Sass/Compass command line prepending it with `bundle exec`. E. g.:

```
bundle exec sass --watch /path/to/pwd
```

or

```
bundle exec compass watch
```

If the issue persists, share your `Gemfile` and `Gemfile.lock` files via https://gist.github.com/ . The  `Gemfile.lock` file will appear also in the project root.

**Comment by imohkay** [comment]
Hi! So just to verify, I reverted to older version of Sass and it watched fine.. Went back to 3.4.3 and I need to keep running the command again and again for it to work... I am not using any libraries like Compass/Bourbon, just vanilla Sass.
Sass version is 3.4.3
Ruby version is: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
I work with devs for Python/Node/PHP projects generally, so I only have Ruby for Sass (hence haven't bothered with RVM)..

I also did sudo gem install listen: kindly see errors below:

```
Building native extensions.  This could take a while...
ERROR:  Error installing listen:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:2:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/hitimes-1.2.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
```

**Comment by magnetikonline** [comment]
@imohkay Might be worthwhile for @nex3 to provide the output for the following.

``` sh
$ uname -a
$ gem list
```

 Pete

**Comment by dikaso** [comment]
Same here:

```
Ubuntu 12.04
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-linux] //also tried newer version of ruby1.9.*
gem 1.8.15
sass 3.4.3
```

```
uname -a
Linux dinko 3.2.0-65-generic-pae #99-Ubuntu SMP Fri Jul 4 21:17:05 UTC 2014 i686 i686 i386 GNU/Linux
```

```
gem list
*** LOCAL GEMS ***

ffi (1.9.3)
hitimes (1.2.2)
rb-inotify (0.9.5)
sass (3.3.14)
timers (4.0.0)

```

I'm not using compass. No symlinks.

My folder structure is 
lib/_aLotOfPartials.scss
style.scss (here I import all of scss files from lib folder)
style.css

Command:

```
sass --watch style.scss:style.css
```

**Comment by nex3** [comment]
@imohkay I'd still like more details about your directory structure.

@DinkoMiletic `--watch` only watches the files and directories you explicitly pass to it. You're telling it to just watch `style.scss`, not anything it imports. You probably want to run `sass --watch .:css` or possibly `sass --watch style.scss:style.css lib:.`.

**Comment by imohkay** [comment]
@nex3 my directory structure is  a main.scss inside /assets/sass and I have a folder at /assets/css where the sass files are to be compiled to css. Inside assets/sass is a partials folder: i.e. /assets/sass/partials. The main.scss contains the import directives, so basically the only compiled file is main.css inside /assets/css. Again, to clarify, no libraries like compass/bourbon and just a static project.. (3.4.2 doesn't watch on 2 static projects I've tested it on...).
The command is:
sass  --watch assets/sass/style.scss:assets/css/style.css

**Comment by soee** [comment]
I have similiar issue (tried on a local and remote servers):

`sass --watch bootstrap.scss:../../public/assets/css/bootstrap.css`

will generate .css file only when first time executed, than nothing if i do some changes in imported partials. This does not work for any 3.4.x version here, just tried 3.3.14 and all works just fine.

**Comment by dikaso** [comment]
So we can conclude that in earlier versions, 3.3.*, watch reacted on changes in partials too? But now we need to explicitly define folders to watch for. Correct?

**Comment by nex3** [comment]
It looks like everyone is seeing the same issue here. When you're using `--watch`, you need to include the directories containing your partials on the command line in order for those partials to be watched.

> So we can conclude that in earlier versions, 3.3.*, watch reacted on changes in partials too? But now we need to explicitly define folders to watch for. Correct?

In practice, yes, but that's not exactly what's happening behind the scenes. In 3.3 and earlier, Sass automatically put the current working directory on the Sass load path. That behavior was removed in 3.4, since it was confusing and contingent on where you were running the `sass` command from. Sass did, and still does, watch everything on the load path; it's just that now that load path doesn't contain the working directory by default, so you don't get automatic watching of everything on the working directory.

At some point, I'd like `--watch` to traverse the `@import` graph to discover which files to watch. Until that's implemented, though, I'll change it to watch the working directory even though it's not on the load path anymore.

**Comment by djonatanb** [comment]
Having the same issue. This is a vagrant machine, maybe that is related to the problem. What happens to me is, says its watching changes, only compiles the first change.

```
Description:    Ubuntu 14.04 LTS
Sass 3.4.13 (Selective Steve)
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
```

Saw somewhere that I should install guard

```
$ guard --version
Guard version 2.12.5
```

```
$ listen -[-]version
ERROR: "listen start" was called with arguments ["-e", "-r", "-s", "-i", "-o", "-n"]
Usage: "listen start"
```

```
$ listen start
Starting listen...
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/tcp.rb:4:in `rescue in <top (required)>': TCP forwarding requires Celluloid::IO to be present. Please install or add as a dependency: gem 'celluloid-io' (RuntimeError)
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/tcp.rb:1:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/listener.rb:290:in `_init_tcp_options'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/listener.rb:57:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen.rb:71:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen.rb:71:in `_add_listener'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen.rb:28:in `to'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/cli.rb:55:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/lib/listen/cli.rb:30:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/listen-2.7.12/bin/listen:12:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/listen:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/listen:23:in `<main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

I installed it with:

```
gem install sass
gem install listen
gem install guard
```

I might have followed some guides pointing to specifying the version of listen.

**Comment by nex3** [comment]
@djonatanb If you're having trouble with the `guard` or `listen` executables, you should report that on those packages' repos, not here.
