### ISSUE TITLE
Normalize / configurable quote character (single / double) in quote function

### ISSUE THREAD

**Issue by mechanicalduck** [sass/sass#1394]
sass version 3.3.0
ruby 2.1.2p95

The sass quote function 
(http://sass-lang.com/documentation/Sass/Script/Functions.html#quote-instance_method) 
which is also used in sass frameworks like compass mixins, uses double quotes, 
also for :compressed output_style.

The quoting style I adhere to are single quotes and more importantly, 
mixing different quote characters reduces gzip compression efficiency.

There can be also other functions / defaults which also use different quoting characters 
and those should be normalized, too.

Note: Not only in attributes, also in selectors.

**Comment by chriseppstein** [comment]
TBH, this sounds like a ton of work and the payoff is _very_ small. I have much bigger fish to fry.
