### ISSUE TITLE
Add a flag to emit ASCII-only output

### ISSUE THREAD

**Issue by dwightjack** [sass/sass#1395]
I'm working with Sass 3.4.

My sass source code is:

```
#test
  content:  "\f000"
```

when parsed it got converted to:

```
#test {
  content: "";
}
```

I'm using expanded style and sass syntax. I've noticed that switching to scss works correctly, anyway my entire codebase is in sass format :( 

Is there any way to preserve original content unicode string?

Thanks in advance

**Comment by quantizor** [comment]
+1, I'm facing this as well and it's causing a lot of issues because now the SCSS file gets flagged as UTF-8, even though I specifically wrote it as ASCII. Then SASS outputs a file with a BOM, which ends up in the middle of my concatenated files and causes other headaches.

**Comment by lolmaus** [comment]
> now the SCSS file gets flagged as UTF-8, even though I specifically wrote it as ASCII.

That's in compliance with the [CSS Syntax Module Level 3](http://www.w3.org/TR/2013/WD-css-syntax-3-20130919/#determine-the-fallback-encoding).

> Then SASS outputs a file with a BOM, which ends up in the middle of my concatenated files and causes other headaches.

I've specifically tried it and Sass 3.4.1 does not produce a BOM for me (though it didn't convert `\f000` into Unicode for some reason, i had to manually type `` into the source Sass).

Anyway, isn't it your concatenation tool's responsibility to produce valid files? BOM aside, the `@charset` directive should only appear in the very beginning of the resulting file. Sass takes care of that for you, but if you postprocess Sass-generated CSS files (which are CSS3-valid) and your postprocessor fails to produce a valid file, there isn't much Sass can do, is it?

**Comment by dwightjack** [comment]
@lolmaus Compliance matters, but sometimes projects didn't comply :p 

> I've specifically tried it and Sass 3.4.1 does not produce a BOM for me (though it didn't convert \f000 into Unicode for some reason, i had to manually type  into the source Sass). 

I've experienced the conversion problem just with .sass extension and sass syntax. switching to .scss works as expected

**Comment by lolmaus** [comment]
@dwightjack, tried with `.sass`, still no BOM.

**Comment by dwightjack** [comment]
@lolmaus yep the BOM issue doesn't come up by changing extension, what's changing is that with .scss `\f000` is preserved, while with .sass it's converted in ``

**Comment by quantizor** [comment]
@lolmaus it's right in the documentation. If you output in compressed style and any utf-8 chars are detected, the file is outputted as UTF-8 with a BOM.

**Comment by quantizor** [comment]
I'm trying to force ASCII in every way I can think of, but 3.4's new behavior to convert the escaped characters into their real entities is defeating that effort.

**Comment by quantizor** [comment]
I'm using the `scss` CLI command to compile instead of `sass`, does that matter?

**Comment by nex3** [comment]
This is the expected behavior. Sass parses strings according to the CSS spec, and the spec says to interpret Unicode escapes as Unicode characters. The only reason the escapes might be preserved is the time-saving optimization wherein certain property values aren't parsed if we can guarantee they don't contain any dynamic code.

What is the actual practical problem with producing UTF-8 output? Is it exclusively other tools that don't handle `@charset` declarations/BOMs correctly?

**Comment by quantizor** [comment]
Well I guess I will never upgrade to 3.4 then. This is a big issue and SASS
shouldn't be fooling around with the input values, especially if we
specifically put a @charset "ASCII" at the top.

**Comment by nex3** [comment]
> SASS shouldn't be fooling around with the input values

This is literally Sass's entire job.

> especially if we specifically put a @charset "ASCII" at the top.

The `@charset` declaration determines what the input character set is, not the output.

You still haven't answered my question: what practical problems does UTF-8 output cause?

**Comment by quantizor** [comment]
No, SASS's job is to rework selector trees, provide utility functions,
variables, etc. With the exception of changing color values to shortened
versions for compressed output, it historically has not tampered with the
values assigned to a property unless you specifically use a function of
some kind.

The issue is not UTF-8, but the fact that 3.4 outputs these files with a
byte order mark in compressed mode. This creates complications when
concatenating files together, because now all of a sudden there is a BOM in
the middle of the file and the browser CSS parser freaks out and drops the
next rule as invalid/malformed.

Could I set up another job to strip out BOM's? I guess, but SASS shouldn't
be including that character or doing this implicit conversion in the first
place.

**Comment by nex3** [comment]
> No, SASS's job is to rework selector trees, provide utility functions, variables, etc. With the exception of changing color values to shortened versions for compressed output, it historically has not tampered with the values assigned to a property unless you specifically use a function of some kind.

Sass has parsed and reformatted property values for a long time. The guarantee it offers is that plain CSS input will produce semantically identical CSS output; Unicode characters are semantically identical to their escape codes, so this guarantee is being upheld.

> The issue is not UTF-8, but the fact that 3.4 outputs these files with a byte order mark in compressed mode. This creates complications when concatenating files together, because now all of a sudden there is a BOM in the middle of the file and the browser CSS parser freaks out and drops the next rule as invalid/malformed.

So it is an issue with the tooling. I suggest you use a concatenation tool (such as Sass itself) that knows how to parse CSS files according to the spec.

**Comment by quantizor** [comment]
If I intended to put a unicode character in my stylesheet, I would have pasted in the actual character. The escaped sequence is in there for a reason and before 3.4, SASS didn't screw with that.

This is very upsetting in general. I'm kind of in disbelief that you would introduce such a change without documenting it more visibly.

**Comment by nex3** [comment]
I'm done arguing with you about this. I think I've stated my point.

This issue is still open because I think it makes sense to add a flag to Sass to tell it to emit ASCII output.

**Comment by chrisdrackett** [comment]
I've run into what (I think) is the same problem. I use icon fonts with my projects and in 3.4 I've run into a problem with the following code:

```
@for $i from 0 through 5
  &.step_#{$i}:before
    content: "\f20" + $i
```

before I would get output in my css file with `\f200`, `\f201`, etc.

Now I get `༠0`, `༠1`, etc, which obviously doesn't display my icon fonts as expected.

**Comment by lolmaus** [comment]
@chrisdrackett, it shouldn't make any difference. Do you have your icon font applied correctly?

**Comment by chrisdrackett** [comment]
yes, when moving to the following code things work as expected:

```
    &.step_0:before
      content: "\f200"
    &.step_1:before
      content: "\f201"
    &.step_2:before
      content: "\f202"
    &.step_3:before
      content: "\f203"
    &.step_4:before
      content: "\f204"
    &.step_5:before
      content: "\f205"
```

**Comment by quantizor** [comment]
Yup. Things get converted whenever Ruby is needed to do an action on the input. If you don't do concatenation or run a function, it stays as expected.

**Comment by chriseppstein** [comment]
@nex3 It seems like there's no good way to construct an escape sequence now. I think we need a fn to construct a character from an escape value. E.g. `char("f205")` would return the equivalent of `"\f205"`.

**Comment by nex3** [comment]
@chriseppstein I agree we should have a function that does that, although that's more the purview of #659.

**Comment by danny-englander** [comment]
I just ran into this after a Sass 3.3.14 > 3.4.4 upgrade and it seems like adding quotes as mentioned above fixes it for me. 

Before I had:
`$fatag: \f02b;`
... which subsequently broke with the upgrade.

Now I use:
`$fatag: "\f02b";`

... and my font-awesome renders as expected.

**Comment by quantizor** [comment]
The conversion happens when passing the character sequence or partial
sequence into any function or concatenation that uses Ruby under the hood.

A bare, quoted sequence should be fine as you mentioned, but it's not fixed
for the rest of us doing something with the codes.

**Comment by quantizor** [comment]
@nex3 Any ETA on when we might see this? Thanks!

**Comment by nex3** [comment]
@danny-englander `$fatag: \f02b;` should still work in 3.4.

@3lux Not particularly. There's a lot to do, and this isn't particularly high on the priority list.

**Comment by jonofthedead** [comment]
@nex3 <code>$fatag: \f02b;</code> does not work in 3.4.x.  it outputs <code>\f02b</code> which throws off any icon webfonts being used.  

Has anyone found a workaround for this?  looks like going back to 3.3.x is the only solution that I can find

**Comment by danny-englander** [comment]
I can confirm, `$fatag: \f02b;` definitely does not work in 3.4.x. `$fatag: "\f02b";` fixes it but it seems hackish.

**Comment by nex3** [comment]
If you're writing `\f02b`, what would you expect it to emit if not what you wrote?

**Comment by jonofthedead** [comment]
I am not sure about \f02b, but in some cases sass converts it.  So "\f001"
turns into "fi" and with icon fonts, this does not work.

jonathan.

**Comment by danny-englander** [comment]
I probably should have clarified. This is happening with Font Awesome. Before the Sass 3.4.x update, I would set the variable with `$fatag: \f02b;` and then use it in my Sass as:

```
.element {
   &:before {
        content: "#{$fatag}";
        @include fontawesome;
      }
}
```

This code would then render the Font Awesome icon as expected. Once I updated to Sass 3.4.x, the icon would no longer render and gibberish was output. Putting quotes around `"\f02b"` in the variable fixes it but I don't know if that's a good way to go. I've tested it across browsers and devices and it seems ok. Maybe I ended up in the wrong spot and should not have posted here for perhaps another issue. Sorry about the confusion.

**Comment by nex3** [comment]
Please explain precisely what output you're expecting in terms of the generated CSS rather than the browser behavior. @jonofthedead, just saying "this does not work" doesn't help me understand what output you expected and in what way the new output doesn't work.

**Comment by jonofthedead** [comment]
So Natalie,

  if I have:

$contentvar: "\f001";

.class:before{
content: $contentvar;

}

I expect the css output to be:

.class:before{
  content: "\f001";
}

But what is getting output is:

.class:before{
  content: "fi";
}

**Comment by lolmaus** [comment]
@jonofthedead, but it still works: http://sassmeister.com/gist/22743e406eeb3744988c

**Comment by nex3** [comment]
@jonofthedead you're not getting the separate characters "f" and "i", you're getting the ligature "". This is the [value of U+F001](http://www.fileformat.info/info/unicode/char/f001/index.htm), and is [entirely equivalent to including the ASCII escape sequence](http://dev.w3.org/csswg/css-syntax-3/#escaping). If a browser is interpreting the two differently, that would be very surprising and would represent a bug in that browser.

**Comment by stephnr** [comment]
I was able to create a backwards solution for generating the proper output for the font content declarations

``` scss
@mixin icon($name, $content) {
  .icon-#{$name}:before {
    content: unquote("\"")+unquote(str-insert($content,"\\", 1))+unquote("\"");
  }
}

// Example
@include icon("Alert","e655");
```

And then the generated CSS:

``` css
.icon-Alert:before { content: "\e655"; }
```

**This works for the current 3.4.x gem of Sass**

**Comment by FlyingDR** [comment]
@Stephn-R Thank you for the tip! I'm really glad that I found it after spending two hours on trying to finding solution for the same problem.

**Comment by tjbenton** [comment]
Thank you @Stephn-R for figuring that out, it was driving me nuts!

Here is a reusable function to use else where if needed.

``` scss
// @source - [@Stephn-R](https://github.com/sass/sass/issues/1395#issuecomment-57483844)
// @description converts 1 or more characters into a unicode 
// @markup {scss}
// unicode("e655"); // "\e655"
@function unicode($str){
 @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"")
}
```

**Comment by bboyle** [comment]
I experienced this after regenerating all our scss recently. We deploy stylesheets that are shared by multiple apps (explicitly, they load the same URL).

One site had issues and was displaying the ligature "". As near as I can tell, the only reason for the difference on that one site is that it serves HTML with ISO-8859-15 encoding specified in the http header. Does the encoding of the HTML page affect the rendering of css generated content? It seems like it does to me. We are not specifying the encoding on the CSS we serve, perhaps specifying UTF-8 there would help.

Appreciate this is a bit of an edge case but will be looking at the methods here for keeping the ASCII encoding on our generated CSS files for this reason.

ps: @tjbenton function works great, thanks!

**Comment by nex3** [comment]
@bboyle What browser(s) are you seeing the incorrect encoding on? Does the issue go away if you replace the unicode character with an explicit escape? Are you using the compressed output format?

**Comment by whaaaley** [comment]
@nex3 This happens to me in Firefox on OS X. It did some research and the last I checked they knew about the bug, but I don't think anyone was working on fixing it.

**Comment by bboyle** [comment]
@nex tested in Chrome. Problem resolved by using "\nnnn" escape format in CSS (I've changed our build to generate in this format using the function provided in this thread).

The character encoding of the HTML page is a total red herring though. I built a test page: UTF-8 encoding in the CSS is fine: http://dev.benboyle.id.au/sass-1395/

Don't know what was causing the problem for us, but it was broken for 2 days straight until we tracked it down (other sites loading the same CSS off the same domain were fine!)

**Comment by bboyle** [comment]
Tracked down the problem we had. We're not getting the `@charset` declaration on the generated css, even when the escapes are converted to unicode characters. I don't know if that's happening in grunt-contrib-compass, compass or sass, or just our particular mix of partials, functions and mixins in scss. We can keep using the ascii solution.

**Comment by nex3** [comment]
@bboyle Are you using compressed mode? Sass uses a BOM rather than a `@charset` there so save space.

Alternately, what happens on your test page if you manually add a BOM to `unicode-no-charset.css`?

**Comment by bboyle** [comment]
@nex using the BOM fixes it, and yes we do use `compressed'. Spot on!

Thanks for following up, I'm going to check our build pipeline for tasks that might remove the BOM.

**Comment by nex3** [comment]
@bboyle Glad to hear that Chrome isn't misbehaving.

@dustindowell22 What exact behavior were you seeing on Firefox? Did the document have a BOM, a `@charset` declaration, or neither? What version of Firefox were you testing?

**Comment by whaaaley** [comment]
@nex3 In Firefox 33 and 33.0.2 (latest) on OS X 10.9.5 and then after I upgraded to 10.10, I'm getting square ligatures. I tried with and without `@charset: "UTF-8";`. No BOM. I'm compiling the latest Font-Awesome. It doesn't matter which output style is selected.

Works everywhere else though. Chrome, Safari, Opera on desktop and Chrome, Opera, Firefox on Android. It's just desktop Firefox for me.

**Comment by nex3** [comment]
@dustindowell22 Not working even with `@charset` is very puzzling. Is it possible that you don't have the font available to view the ligature? Does it work when you handcraft a CSS file that uses the ASCII escape? Can you put up a test page somewhere that demonstrates the issue?

In my local tests, Firefox 33 properly interprets the BOM even when the page's encoding is different.

**Comment by whaaaley** [comment]
@nex3 Finally sat down and found my problem. Total fail on my part. I had an old Font-Awesome font installed locally from a looong time ago. Firefox wasn't pulling them in and my font paths were wrong. I completely forgot I did that. My bad. Everything is good and working. Sorry about that.

**Comment by larsbo** [comment]
I got the  "" issue, too. In my case it only happend in a speciific combination:

I stored the unicode in a sass variable like
`$icon: "\f006";`
and used it (in another file) with
`content: $icon;`
This for this works fine (sass 3.4.5)!

After running critical css (https://github.com/pocketjoso/penthouse) over it, it writes "" inside the critical inline part. And only for the unicode stored inside a sass variable; all the other ones used inside my sass files are correctly copied to the critical css part.

Maybe this can help (or confuse) a little bit? :smile: 
It might be a utf-8/iso-15 issue, too. I can check this, if needed.

Nevertheless @Stephn-R solution works for mee! Thank you.

**Comment by stephnr** [comment]
Your welcome @larsbo! As for a more permanent fix, @nex3, is it possible to include a new function that kinda does the following:

``` scss
.alert-icon {
    content: icon("\f006");
}
```

Is this realistic or should we stick with rough fixes like these?

**Comment by larsbo** [comment]
small update to my issue mentioned above:
First I would like to clarify that the  "" problem is not related to critical css as it might look like in my previous post. The miscoded symbol is already inside my compiled css file.

Second the code  `unquote("\"")+unquote(str-insert($content,"\\", 1))+unquote("\"");` doesn't work as expected. After some testing the following code work in all cases for me:

``` scss
/* modified mixin */
@function unicode($str){
    @return unquote("\"") + $str + unquote("\"");
}

/* icon code stored in sass variable */
$icon: \f00c;

/* using the variable */
.some-class {
    content: unicode($icon);
}
```

And I also vote for a function in sass (maybe a more generic name such as `unicode()`), even if the bug is not completely related to sass. For the average user it doesn't matter which fault it is, it just matter that it works and if you are able to solve it you should :)

**Comment by nex3** [comment]
I don't want to add a function-level workaround for this. Needing to emit ASCII isn't a property of the specific use of Unicode, it's a property of your tool chain, and should be expressed as a global compilation option.

**Comment by sonicdivx** [comment]
Going say SASS compilation needs to have an option for this, like nex3 is implying. Functions work right now as a workaround, but this is really a SASS issue that worked and is "broke" now.

**Comment by mariusc23** [comment]
It seems the issue is as simple as putting the escaped unicode character into a variable (see reduced case below). This is inconsistent behavior and I think should be fixed anyway, but agreed that a flag would be better than a function.

I would like to mention that it does cause some issues in Chrome. This is the only reason I even found out SASS converts the escaped characters. Sometimes instead of showing the icon it shows multiple characters (1-3) instead (ex: ï€‡). Seems like a browser bug, but it did not happen with escaped characters.

``` scss
// SASS
$whatever: "\f004";

.a {
    content: $whatever;
}

.b {
    content: "\f004";
}

// CSS
.a {
    content: "";
}

.b {
    content: "\f004"; // fine
}
```

**Comment by coltpini** [comment]
After a ton of trying to work around this I finally hit this thread, Thanks a ton @larsbo!!

Here is the problem that I saw, below is a link to a gist that documents the solution.

I am trying to create a list that holds the names to all the icons in my icon font. I am working on a very large website in a large company. Our icon font is organized in sections and is located in the PUI in the unicode standard.

I created a loop to go through the list and create a rule for each icon. Using the index (converting to hex) to spit out the proper unicode. resulting in essentially, "\e9" + "00", in different variables. The problem that I was having is that, in the quotes, the "\e" would render as "é" so the compiled css would be content: "é00".
Naturally I thought that I could escaped the \ with \\. But that didn't escape. "\\e9" + "00" would result in - content: "\\e900";

That got really frustrating really quickly. No matter how I tried I could not escape the . I even tried "\005ce" + "00" (\005c is the ascii for '\') to try and get "\e900". That compiled in the css to content: "\\e900". At that point I was pulling out my hair. I used many many number of combinations of quote and unquote, except for the one above, with no avail.

So I see two problems. (I admit I am new to sass, coming from stylus, which didn't have this problem at all)

1) One when compiling it is really frustrating to have '\e900' to compile to ''. That is not the behavior that I would expect. I would expect a value of '\e900' to remain '\e900' when I compile to css.

2)  There doesn't seem to be a way to escape the `\`.

I need to mention all of this is not talking about rendering in the browser, this is all compiling sass to css. These issues are from looking at the resultant css file so this isn't browser behavior.

Here is the code to my working solution.
https://gist.github.com/coltpini/b59b3064d6ecde760c6a

**Comment by nex3** [comment]
@mariusc23 Can you produce a reproduction of the chrome bug? That is, a CSS file + an HTML file (with a correctly-declared encoding) that produces the right glyph for an escape but not for the literal character?

@coltpini Sass strings have the same semantics as CSS strings, which is why you're seeing that behavior. To the eyes of CSS (and thus Sass as well), `\e900` is a single character in a string that happens to be represented in the source by five characters, just like `\n` in other languages.

**Comment by coltpini** [comment]
That isn't what I described in problem above. the problem is that is is encoding before concatenation and the \ will not escape an \. I will show you:
http://codepen.io/coltpini/pen/gbmNrx

if you look at the compiled sass on this pen you can see what is happening when it is translated into css. This isn't about the rendering on html, but the resulting css code after compile.

**Comment by nex3** [comment]
Right, that's because of the semantics of CSS strings, which Sass inherits. You can't combine two halves of an escape sequence in Sass any more than you can in any other language.

**Comment by coltpini** [comment]
The gist I posted does it, and I had no  problems doing this in stylus or JS. It seems odd to me though that you can't escape and escape char.

**Comment by nex3** [comment]
JS absolutely doesn't do this. If you write `"\\" + "n"`, you don't get `"\n"`, you get `"\\n"`.

Stylus might, but if so, that's part and parcel with the decision to have their strings differ in syntax and semantics from CSS strings, which produces net confusion on the whole.

**Comment by coltpini** [comment]
@nex3, Sorry I am not trying to argue or anything here. Our perspectives might be just a little different is all. I updated the codepen to show the js. http://codepen.io/coltpini/pen/gbmNrx 

and maybe where I am wrong is this assumption. JS  "renders" to DOM and Sass renders to CSS. With that mentality.

JS: "\e9" + "00" => e900
JS: "\\e9" + "00" => \e900
JS: "\"\\e9" + "00\"" => "\e900"

Sass: "\e9" + "00" => é00
Sass: "\\e9" + "00" => \\e900
Sass: "\"\\e9" + "00\"" => "é900"

this gist is the only way that I could get "\e900" (the js third result) out of Sass.
https://gist.github.com/coltpini/b59b3064d6ecde760c6a

I hope that helps in understanding the dilemma I am facing.

**Comment by nex3** [comment]
There's a substantial difference between a string containing the characters `\`, `e`, `9`, `0`, and `0` and a string containing the Unicode code sequence U+E900. The second and third JS examples you list are the former; the second Sass sample is semantically identical to those examples, in that it produces a string containing the bytes `\`, `e`, `9`, `0`, and `0`. The CSS string representation of that, like the string representation in Sass, is `\\e900`.

**Comment by coltpini** [comment]
Yes. The problem I am running into is that in my css I need `"\e900"` so that the browser can take that and put it into the unicode char. The only thing I can get, with out the workaround, is `"é00"` or `"\\e900"` both of which won't give me the char in the PUA. 

Your post gave me another thought so I updated http://codepen.io/coltpini/pen/gbmNrx with an icon5 span that tries to break everything out. The problem is that `"\"` won't compile because the `\` is escaping the `"` and `"\\"` compiles to `"\\"` so how can I get my css file to have `"\"`? That is an honest question that I would like to know. I don't know how prevalent of a problem it is but it seems it might be at the root of some of the issues presented here.

I don't know the answer, and maybe the workaround is the answer?

Thanks for your time on this @nex3!

**Comment by nex3** [comment]
First, I want to stress again that, in a CSS document, the bytes `\` `e` `9` `0` `0` are interpreted identically to the code sequence U+E900. So you shouldn't be looking at how to get an unescaped backslash, because on its own the byte `\` doesn't mean anything in CSS and so Sass won't generate it, but how to get a dynamically-defined Unicode code sequence. For that, you want #659.

**Comment by piouPiouM** [comment]
@yaycmyk I encountered your issue [this week](http://pioupioum.fr/outils-astuces/sass-bom-compass.html). If you are using Compass, you can try this code that I use in a Drupal project to remove the BOM of the generated CSS files:

``` ruby
# config.rb
#

# Removes the BOM for UTF-8 stylesheets.
on_stylesheet_saved do |filename|
  css     = File.open(filename, 'r')
  content = css.read
  if "UTF-8" == content.encoding.name
    content.sub!("\xEF\xBB\xBF".force_encoding("UTF-8"), '')
    File.write(filename, content)
  end
end
```

**Comment by jernejcic** [comment]
Adding 

``` html
<meta charset="utf-8" />
```

to my `head` got my Font Awesome characters working again. Hope that saves somebody the hours I've spent on this.

**Comment by yihou** [comment]
I faced the same problem as well, and after that i tried install font-awesome-sass into my ruby folder, it seems to fix the issue already. 
just use the line below
`gem install font-awesome-sass` 

reference https://github.com/FortAwesome/font-awesome-sass

**Comment by MrHakala** [comment]
1 year after first post. Now I'm having the same problem. 
Any consensus on best workaround? Downgrade to 1.3.*?

**Comment by PCateNumbersUSA** [comment]
I'm having this same problem. Has this been fixed or is there an agreed upon solution?

**Comment by richardsison** [comment]
Any updates on this? Having the same issue trying to set up icons as variables which are likely to change in the near future…

Really don't want to have to manually replace all icon-classes in the HTML…

The compiled CSS _seems_ to work, but there is a placeholder symbol where the unicode should be…

`.icon-backtop:before {
  content: ""; }
`

**Comment by yihou** [comment]
Add meta charset to utf-8 and make sure the font files are in place. That should work fine already

**Comment by richardsison** [comment]
Thanks Yihou! But it seems to work already, it's just the CSS file that is compiled from the Sass file that has the symbol… In the HTML the correct webfont symbol renders though.

Is there a way to force the Sass to compile the unicode character (i.e. "\e000") as is?

Here's an example of what I mean: http://share.richardsison.com/10EEL

**Comment by yihou** [comment]
You are welcome. I leave that sass compilation issue because FontAwesome seems to work and I don't have that solution either, sorry. You may look back the comments to sort it out.

**Comment by andykellr** [comment]
This is what we are using:

``` sass
=font-awesome-font
  /* makes sure icons active on rollover in links */
  a
    &
      display: inline-block
  font-family: FontAwesome
  font-weight: normal
  font-style: normal
  text-decoration: inherit
  -webkit-font-smoothing: antialiased
  -moz-osx-font-smoothing: grayscale
  &:before
    display: inline-block
    speak: none

// @source - [@Stephn-R](https://github.com/sass/sass/issues/1395#issuecomment-57483844)
// @description converts 1 or more characters into a unicode 
// unicode("e655"); // "\e655"
@function unicode($str)
  @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"")

=font-awesome-code($code)
  &:before
    content: unicode("f" + $code)

// code is the part after \f e.g. \f000
=font-awesome($code: "000")
  +font-awesome-font
  +font-awesome-code($code)
```

And then in a separate file we have a bunch of mixins:

``` sass
=icon-adjust
  +font-awesome("042")
=icon-adn
  +font-awesome("170")
=icon-align-center
  +font-awesome("037")
...
```

And when we want something to have an icon we do something like this:

``` sass
i.signin
  +icon-signin
```

Our mixins file is generated from font-awesome source so that we can update font-awesome and start using new icons without manually creating all of the mixins. We use mixins because we don't like putting icon classes in our HTML and we don't like having all of the font-awesome CSS rules for icons we will never use.

**Comment by nex3** [comment]
@PCateNumbersUSA @RichardSison We plan to add a flag to always escape non-ASCII characters, as well as a function to take a Unicode code point number and return its corresponding character. This issue is marked "help wanted", though, which indicates that external contributions will be the best way to make that happen.

**Comment by bantya** [comment]
Thank you @Stephn-R your little snippet is very helpful and solved my long lasted problem..
Thanks again from INDIA..

**Comment by stephnr** [comment]
No problem @bantya ! I still use the work around to this day

**Comment by Perkovec** [comment]
Alternatively you can use [gulp-sass-unicode](https://www.npmjs.com/package/gulp-sass-unicode) ( for gulp of course )

**Comment by rickdoesburg** [comment]
After hours of searching I came across your comment @Perkovec. Works like a charm! Thanks.

**Comment by erikflowers** [comment]
I have also encountered this is moving a custom icon font to SASS from Less, and the mixins here seem to work. I am not 100% certain of the implications of seeing the "missing glyph" vs. the \F000, and I know it actually is proper CSS encoding, but it just makes me nervous and I am not sure how to test it, so the mixin seems the way to go for now. All the other icon fonts show the actual ASCII and not the glyph, and I don't know enough to decide if not doing that is smart or not. 

If there was a flag to put the \F000 style text though, I'd use it.

**Comment by Asif-Mahmood** [comment]
@Stephn-R  used his solution above in font-awesome and it worked like a charm. thanks (Y)

**Comment by tspicer** [comment]
Just came across this issue. Basically the issue was observed as a result of Nginx with Google PageSpeed incorrectly representing those values when using CSS page optimizations.  Going to apply some of the hacks mentioned previously.

**Comment by thenetimp** [comment]
@Stephn-R thanks for the mixin totally gives us ( @tspicer ) and I with our problem, but I am frustrated that we have to hack this to get it to work the way we want it too.

**Comment by pinksynth** [comment]
I just came across this issue as well.

Environment (at a glance):
- Integrating some custom icons into Font Awesome 4 scss
- Non-gulp
- Non-Ruby on Rails

Is the consensus that a build of this kind must use one of the above (albeit very helpful) mixins for _every single icon variable to be compiled_? Should I just forget trying to make use of Font Awesome's `_variables.scss` without extensively modifying it?

**Comment by nex3** [comment]
You shouldn't *need* to do anything. Unicode characters have exactly the same semantics in CSS as the corresponding escape codes. It's just a matter of aesthetics, or of another tool failing to be Unicode-safe.

**Comment by thenetimp** [comment]
@nex3  you say it shouldn't be an issue, however this thread proves that it is an issue, and some of us have had to hack mixins to get around it to get it to work.

**Comment by nex3** [comment]
No one here has provided a reproducible case where Unicode output doesn't work in a browser.

**Comment by Fil923** [comment]
W3C Validation fail for this reason

**Comment by nex3** [comment]
@Fil923 Can you provide a repro case?

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.

**Comment by drewwells** [comment]
> I'm moving this issue to the new Ruby Sass repository because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because Ruby Sass is deprecated and no additional features are planned for it.

Please reopen this issue. Sending bugs to a deprecated project and immediately closing it there only frustrates everyone.

**Comment by drewwells** [comment]
A repo case as requested

```
$test: "\f00d";

p {
    a {
        content: $test;
    }

    b {
        content: "\f00c";
    }
}
```

Outputs non-sense
```
@charset "UTF-8";
p a {
  content: ""; }

p b {
  content: "\f00c"; }
```

**Comment by nex3** [comment]
> Please reopen this issue. Sending bugs to a deprecated project and immediately closing it there only frustrates everyone.

I don't know what you're looking for by asking this issue to be re-opened. No one is working on new features planned for Ruby Sass, so whether this issue is open or not this flag is not going to get implemented.

> A repo case as requested
> 
> ```
> $test: "\f00d";
> 
> p {
>     a {
>         content: $test;
>     }
> 
>     b {
>         content: "\f00c";
>     }
> }
> ```
> 
> Outputs non-sense
> ```
> @charset "UTF-8";
> p a {
>   content: ""; }
> 
> p b {
>   content: "\f00c"; }
> ```

I requested a reproduction that shows the a Unicode escape rendering differently than a Unicode character in a browser. Certainly it's the case that the Unicode code point U+F00C is different than the sequence of code points U+5C U+66 U+30 U+30 U+63, but the CSS spec treats those as identical and as far as I'm aware all browsers follow the spec.

**Comment by augustotmw** [comment]
Great day to everyone. 😄 

Im having a almost same and as weird as the cases above, where my:

```
$icon-location: "\e90a";


.icon-location {
  &:before {
    content: $icon-location;
  }
}

```

is being converted into

```
.icon-location:before {
    content: "î¤Š";
}

```

Does anyone know why its happening?

There is a way to pass some argument to sass/Ruby compiler proccess to avoid this "conversion to unicode" and keep the original text value?

The server where it happens is using `node-sass@4.11.0`, if it can help something.

Thanks in advance

PS.: @nex3  @TeresaPartidaS @nschonni  @asottile

**Comment by bardware** [comment]
> content: "î¤Š";

How do you look at the generated css file? Try Notepad++ and "play" with the file encodings available.

**Comment by asottile** [comment]
if it's in html, make sure to have `<meta charset="utf-8">`

**Comment by augustotmw** [comment]
Hi! Thanks by the answers 😃 

> > content: "î¤Š";
> 
> How do you look at the generated css file? Try Notepad++ and "play" with the file encodings available.

I looked at it after run a ng build process and opening the generated css file at my dev env.

Or when I debug at inspector, at hom env.


> if it's in html, make sure to have `<meta charset="utf-8">`

The variable is in a `_variables.scss` file, and its imported and applied in a other file called `_icons.scss`. This last one is imported at a `style.scss` file, and this file generate the css file with the encode problem.

I will try to apply the metatag and see if it solves the case.


Thanks in advance

And best regardings 😄

**Comment by clshortfuse** [comment]
So, I'm trying to get a zero-width unicode character to work with SASS. It won't appear without a hex editor thanks to SASS reinterpreting that. On normal CSS, it's:


````css
div::before {
  content: "\200B";
}
````

But SASS will rewrite it as:
````scss
div::before {
  content: "​";
}
````

It's a little frustrating trying to debug with an invisible character since SASS wants to rewrite it.

**Comment by jathak** [comment]
@clshortfuse: This issue was for ASCII-only support in Ruby Sass, which is no longer developed. You should follow sass/dart-sass#568 for the status of this feature in Dart Sass.

**Comment by cweiske** [comment]
Today I was bitten by this; Drupal 7's CSS concatenator does not remove BOMs and thus the CSS breaks - https://www.drupal.org/project/drupal/issues/1833356

**Comment by nicolaskopp** [comment]
Having the same issue. We recently upgraded to latest dart sass ( https://www.npmjs.com/package/sass v.1.32.13 )

this 
`style.scss`

```scss
 i:before {
                font-family: "metro-mf-icons";
                content: "\F105";
            }
```

gets compiled to  this

`style.css`

```css
header .sub-header-store .store-div .store-selector-toggle i:before {
  font-family: "metro-mf-icons";
  content: "";
}
```

quite annyoing as we have like a Quadrillion scss files which we now have all to go through manually to escape any unicode sequences with some mixins.

While I understand that sass is "just following some nice css3 level specifications", it is effectively breaking working code and I would very much like having a compiler switch which effectively turns this conversion off. It breaks functionality. No update of a software should by default break existing functionality.

**Comment by nex3** [comment]
@nicolaskopp To be clear: **this is not a breaking change.** You do not have to manually escape Unicode sequences. As long as you have a `@charset "UTF-8";` or UTF-8 BOM at the beginning of your stylesheet—which Sass ensures—all browsers will interpret a literal U+F105 character identically to the escape squence `\F105`.



> this
> `style.scss`
> 
> ```css-scss
>  i:before {
>                 font-family: "metro-mf-icons";
>                 content: "\F105";
>             }
> ```
> 
> gets compiled to this
> 
> `style.css`
> 
> ```css
> header .sub-header-store .store-div .store-selector-toggle i:before {
>   font-family: "metro-mf-icons";
>   content: "";
> }
> ```

That's not true. It gets compiled to

```css
@charset "UTF-8";
i:before {
  font-family: "metro-mf-icons";
  content: "";
}
```

*with a `@charset` declaration.*

I'm going to lock this thread since this is not relevant to the Sass language repository. Feel free to follow up on sass/dart-sass#568.
