### ISSUE TITLE
Bug in compilation with variables and quotes in Sass 3.4

### ISSUE THREAD

**Issue by slawaEremin** [sass/sass#1396]
In Sass 3.3 the following code:

```
$fa-css-prefix: 'foo';
$fa-var-music: '\f001'; 
.#{$fa-css-prefix}-music:before { content: $fa-var-music; }
```

compiles into:

```
.foo-music:before {
  content: "\f001";
}
```

But the same code in Sass 3.4 compiles into:

```
.foo-music:before {
  content: "";
}
```

**Comment by lolmaus** [comment]
Did you also notice `@charset "UTF-8";`?

Unicode, baby! :sunglasses:

**Comment by slawaEremin** [comment]
It will not help: http://sassmeister.com/gist/4c326a38bf0457f120db

**Comment by Snugug** [comment]
Are you sure it's not the font you're using to look at the output CSS with? It's [in the private subset](http://www.utf8icons.com/character/61441/UTF-8-character), so probably shouldn't be used as they're [non-standard and aren't available in all fonts](http://en.wikipedia.org/wiki/Private_Use_Areas).

**Comment by cimmanon** [comment]
Going to have to agree with Snugug here.  If you switch to Sass 3.3.x, you'll get the desired CSS output, but it won't change the fact that it doesn't display properly in the browser.

**Comment by lolmaus** [comment]
@Snugug, it's not a font issue: the old CSS output should've produced the same characters as the new one. And the guy is only unhappy with the new output.

@slawaEremin, that's intended and valid CSS. Extract from Sass 3.4.0 [changelog](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html):

> Sass now follows the CSS Syntax Level 3 specification for determining a stylesheet’s encoding. In addition, it now only emits UTF-8 CSS rather than trying to match the source encoding.

I don't know how to revert to the old output, you should wait for @nex3 to comment on that. But why doesn't the new format suit you in the first place?

**Comment by dwightjack** [comment]
Hi this seems to be similar to my issue #1395.

I think the main issue is that unicode code is less error prone, expecially in large multi OS teams in the scenario where someone's IDE doesn't keep UTF8 as default charset (i know, that's sad but actually happens).

**Comment by lolmaus** [comment]
@dwightjack, well, if you have a reason that forces your team into using obsolete IDEs, it might as well justify using an older version of Sass?

**Comment by lolmaus** [comment]
I assume we can close this one. @dwightjack is right that this is a duplicate of #1395 which is older and has a better formulated title.
