### ISSUE TITLE
Sass v3.4 compile of Foundation is not producing the same results as 3.2.19

### ISSUE THREAD

**Issue by danreed121** [sass/sass#1397]
I installed a component that required Sass 3.3+ and when I went back to working on another project that had been compiling just fine for months, the result of the following command was no longer correct:

sass $SOURCE_PATH/src/stylesheets/app.scss $SOURCE_PATH/grails-app/assets/stylesheets/app.css

While the compiler didn't report any files that it could not find, it didn't include all the Foundation components.  Yet, to test this, I added some jibberish comment in some of the Foundation source files, and when I ran this command, the comments were present, in the order of "@import".

I found this post: 
[Zurb Support](http://foundation.zurb.com/forum/posts/18679-problem-using-sass)

When I went back to using 3.2.19 (Which was the last version I had been using), ran the same command, it the compiled result was as expected.

The way I was including Foundation was to create a copy of the "_settings.scss", make any changes there, and at the bottom of that file, import the "foundation.scss", which in turn includes all the components I was using.

**Comment by lolmaus** [comment]
A sidenote. It is a best practice to use [Bundler](http://bundler.io/) to lock versions of your Ruby dependencies. This way, you can have many projects on your computer using different versions of Sass.

**Comment by danreed121** [comment]
@lolmaus understood, I use bundler in my Ruby projects.  In this case I am using sass as a general utility to watch/compile minify my scss files.  I should create a Gemfile for these projects though.

**Comment by nex3** [comment]
This isn't really enough information to act on. See if you can narrow this down to a single reproducible issue and I'll look into it.

**Comment by tvollstaedt** [comment]
It's actually https://github.com/sass/sass/commit/79bad1ff473cc06c66b85086403f4a1905938e37, causing [this](https://github.com/zurb/foundation/issues/5636) issue. That's not a fault from sass, but from poor dependency management of [zurb-foundation](https://github.com/zurb/foundation). I just posted a hint to avoid these issues using a more semantic versioning scheme (#1422).
