### ISSUE TITLE
Check option produces no ouput on Windows

### ISSUE THREAD

**Issue by 4e4c52** [sass/sass#140]
Hello,

I'm on Windows 7 and I try to check my SCSS files with the following command:
```sass -c folder/myfile.css.scss

```

I just get a blank new line on my console.

I've tried with cmd.exe and cygwin, same result.
```

**Comment by nex3** [comment]
Perhaps your SCSS file just doesn't have any errors?

**Comment by chriseppstein** [comment]
@nex3 I think a lot of our users are not used to the UNIX convention of success being indicated by no output.

**Comment by chriseppstein** [comment]
(not suggesting that we should change the behavior, but maybe update the docs?)

**Comment by nex3** [comment]
Updating the `--help` documentation seems reasonable.

**Comment by 4e4c52** [comment]
Yes it have, I've removed a semi-colon after a property and it says nothing.
However, if I add _blabla_ in the middle of the file, I got an error.

I'm using the sass --pre gem.

**Comment by nex3** [comment]
There are cases where a semi-colon is not required after a property (e.g. immediately before a closing brace).

**Comment by 4e4c52** [comment]
@chriseppstein Be sure I know that, I'm just on Windows temporarily ;)

**Comment by 4e4c52** [comment]
@nex3 I had forgotten this case, what a shame...
So consider that I've never opened this issue and that everything is working on Windows 7 ;)
