### ISSUE TITLE
Upgrading to 3.4.1 (from 3.3.14) breaks parsing @- syntax

### ISSUE THREAD

**Issue by okolehao** [sass/sass#1400]
After upgrade, the @- syntax seems to break the SASS parser.  

Sass::SyntaxError: Invalid CSS after "": expected selector, was "0%"
  /app/styles/partials/_animations.sass:89:
    0%
  /app/styles/_app_second.sass:5:
    @import partials/animations
  (sass):41:
  sass/scss/parser.rb:1163:in `expected'
    raise Sass::SyntaxError.new(
  sass/scss/parser.rb:1099:in`expected'
    self.class.expected(@scanner, @expected || name, @line)
...
(95 additional frame(s) were not displayed)

**Comment by lolmaus** [comment]
@okolehao, please remove large pieces of code and share them via https://gist.github.com .

**Comment by okolehao** [comment]
Opps sorry - https://gist.github.com/okolehao/702facfa3c55d6f753b8

**Comment by lolmaus** [comment]
Also please attempt reproducing the problem on http://sassmeister.com/ . It offers both Sass 3.3 and Sass 3.4 compilers, very handy to compare the output.

**Comment by okolehao** [comment]
Thanks @lolmaus  - reproed on SASSmeister

https://gist.github.com/okolehao/98870871ec1d40263e8e

Change config to 3.4.1 and it fails (Invalid CSS after "": expected selector, was "0%") , swap back to 3.3.14 and it compiles

**Comment by nex3** [comment]
It looks like you're writing `@-keyframes`, which isn't a valid keyframes selector and thus doesn't allow the keyframes rule `0%` within it.
