### ISSUE TITLE
Exponential performance regression with maps

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1402]
I briefly talked to @chriseppstein on Twitter and was pointed here. I'm trying to pinpoint why [Flint's](https://github.com/ezekg/flint) compile time seems to exponentially grow as the cache/instance maps get larger. Are you aware of any performance issues for maps within SassScript? My project compile times are averaging ~200s. I've already implemented a pretty robust caching system for Flint, but really didn't see _much_ gain in performance. From what I can pinpoint, it seems that using `map-get` on large maps is the bottleneck.

For example, running this locally and watching the debug output you can see the performance regression as each instance is stored and fetched from the global `$flint__instances` map.

``` scss
@import "flint";

@for $i from 1 through 50 {
  #{unique-id()} {
    @include _(4) {
      @debug "Compiled for #{&}";
    }

    #{unique-id()} {
      @include _(4, auto) { // Self corrects itself by fetching the width of the parent
        @debug "Compiled for #{&}";
      }
    }
  }
}
```

The above code will output 200 instances, one instance for each breakpoint (4) per mixin call. Here is an example of a single instance map. My projects range from about 100-200 of these, all stored in the global `$flint__instances` map.

``` scss
$flint__instance: (
    "#{$selector-cleaned}::#{$key}": (
        "instance-count": $flint__instance-count,
        "parent-selector": if(flint-has-family-instance($key) != false, flint-has-family-instance($key), none),
        "key": $key,
        "breakpoint": flint-get-value($key, "breakpoint"),
        "columns": flint-get-value($key, "columns"),
        "span": $span,
        "context": if($context == "auto", flint-get-instance-value($key, "span"), $context),
        "gutter": $gutter,
        "shift": $shift,
        "output": (
            "width": $output-width,
            "margin-right": $output-margin-right,
            "margin-left": $output-margin-left
        )
    )
);
```

Like I said, I've been unable to put in the amount of debugging time I need to wholly test if this is a Sass issue, or rather an issue with Flint. I'm really filling the issue to see if maps themselves have any performance issues I can look into.

**Comment by Snugug** [comment]
#1019 is tracking performance regressions in Sass. Susy also has similar issues ericam/susy#325.

As for your specific issue, I've found that maps are slow, and map based caching especially so unless the exact same input/output is used multiple times. [Memoization](https://github.com/team-sass/sassy-maps#memo), the name for the type of caching we're doing with maps, inherently takes a performance hit on cold cache hits (which, unless you've got identical input/output each time for a lot of identical and separate queries). You've also got the problem that Sass 3.3 has a performance regression with functions (I've literally found that using `call` instead of calling a function name directly is faster).

Nested maps have double the issue as you've not only got the overhead of maps, but the overhead of functions to get them as well.

When I was building Singularity 1.2, I initially built in memoization as well, but after running tests with real-world usecases instead of memo-optimized tests, I found that removing memoization sped up compile times. On the Susy issue, I [wrote some recommendations](https://github.com/ericam/susy/issues/325#issuecomment-48035023) on how Eric could speed up Susy, I bet a bunch of those would help you out too.

**Comment by lolmaus** [comment]
Thank you for your research, @Snugug. O_O

**Comment by ezekg** [comment]
@Snugug thanks for the info. I do have a lot of nested maps, so I frequently use `map-fetch`. I did see a notable performance gain from caching, enough to implement it. I think I created around 3-4 different caching maps for specific repeated tasks, such as fetching the same value 4 times for each breakpoint. Went from compile times of around ~300s to ~200s. But, this might also be because I moved all of the heavy string-related functions over to Ruby when possible.

**Comment by Snugug** [comment]
My bet is it's the Ruby stuff. Ruby is fast as hell compared to Sass.

Best way to test performance is using the (please excuse if this sounds weird) [Scientific Method](http://en.wikipedia.org/wiki/Scientific_method). Start with a hypothesis, experiment with only one variable change at a time, analyze, and draw a conclusion. If multiple things are changed each test, it's hard if not impossible to draw a meaningful conclusion.

Using the scientific method is how I found out that in a specific position in Singularity, `call` was faster than a direct function call.

**Comment by nex3** [comment]
@ezekg Can you come up with an example where you're seeing exponential behavior that doesn't involve pulling in all of flint?

@Snugug I have a hard time believing that `call` is actually faster than a literal function call, since all it does is construct a function call node and run it.

**Comment by Snugug** [comment]
@nex3 I can't tell you why or how. I can tell you that [at this place in Singularity](https://github.com/Team-Sass/Singularity/blob/1.x.x/stylesheets/singularitygs/_api.scss#L58), having run tests with a direct function call vs `call`, `call` was faster.

**Comment by nex3** [comment]
Since you're interpolating there, how could it be a direct function call at all?

**Comment by Snugug** [comment]
I tried with a direct call to my `output-isolation` function as I know that's the default function that would be used.

**Comment by Snugug** [comment]
@nex3 for what it's worth, I just revisited `call` vs direct function call and it being faster only appears to still hold true for Sass 3.3. In Sass 3.4 the two methods appear to be identically fast.

**Comment by ezekg** [comment]
@nex3 @Snugug just an update on this, I reversed the order that I am merging maps with `map-merge`; I'm now placing the newest item at the beginning as opposed to the end. My performance benchmarks (from Flint's test suite) show an increase of 23%. Gained another 15% by writing a `map-fetch` function in Ruby to use, when available, in place of the one written in pure Sass.

``` scss
$old-map: ();
$new-map: ();

// I'm doing this,
$old-map: map-merge($new-map, $old-map);

// Instead of doing this,
$old-map: map-merge($old-map, $new-map);
```

Still haven't had time to attempt to replicate it outside of Flint, sorry.

**Comment by ezekg** [comment]
Disabling Flint's instance maps (the map-heavy part) cuts the compile time down from ~200s to a mere 20s. Either I suck at coding (very likely lol) or wez gots ta look into maps actually being the cause of performance issues (since I'm not the only one reporting issues). I'm going to try and attempt to run some isolated tests outside of Flint sometime this week.

**Comment by nex3** [comment]
Closing since we never got a clear reproducible use-case.
