### ISSUE TITLE
Commented out code (%) is not skipped

### ISSUE THREAD

**Issue by mechanicalduck** [sass/sass#1403]
Sass 3.4.1 (Selective Steve)

With stars (/\* [...] */) commented out code (%) is not skipped.

This Is not skipped::

```
/* %font-size-#{$name}{} */
```

As an example, $name was not defined as this commented out code block 
shouldn't currently be used at all, and so this still evaluated code would fail:

```
error [...] (Line (Number where the comment opens): Undefined variable: "$name".
```

Adding a single-line comment to the inside still doesn't skip:

```
/* //%font-size-#{$name}{} */
```

Single-line comment skips properly:

```
// %font-size-#{$name}{}
```

[ok]

**Comment by lolmaus** [comment]
This issue is a duplicate.

This is intentional. Interpolation (`#{...}`, not `%`) does work in block comments because you might want to emit comments with variables, for various purposes.
