### ISSUE TITLE
Watch outside folder

### ISSUE THREAD

**Issue by artemhp** [sass/sass#1404]
Hello, if I have a structure in project

```
- project
-- scss
-- - file.scss (this file has @import ../../lib/different/file.scss)
--- config.rb
-- css
- lib
-- different
--- different.scss
```

config.rb

```
project_path = "../"
sass_dir = "scss"
css_dir = "css"
```

How should I adjust config or watcher in command for monitoring modification in lib/different/different.scss file? So, if I make changes in different.scss than file.scss will be recompiled.

**Comment by nex3** [comment]
`config.rb` is Compass, not Sass, so I don't know if it has facilities for doing this. If you're using the Sass command line, you can run `sass --watch scss:css ../lib:css`. As long as a parent directory of the files you want to watch is on the path, those files will be compiled.

Alternately, you could run `sass --watch --load-path ../lib scss:css` and rewrite your import to `@import "different/file.scss"`. Sass knows to watch all load paths for changes.

**Comment by chriseppstein** [comment]
in compass you can use `add_import_path(File.expand_path("../lib", File.dirname(__FILE__))`
