### ISSUE TITLE
PUA codes are converted to blank Unicode strings if looped through @each

### ISSUE THREAD

**Issue by csi-lk** [sass/sass#1405]
Just noticed a bug with the SASS compiler.

It's super specific (almost edge case) but I thought i'd report it anyway...

Pretty much I was looping out a key value pair array for icon font PUA codes using @each mapping  and the compiler seems to 'convert' them to blank unicodes on the way through.

**Version:** 3.4.1
**Input:**

```
$icons: (
search: "\f002",
heart: "\f004"
);

@each $icon-name, $icon-code in $icons{
[data-icon="#{$icon-name}"]{
content: $icon-code;
}
}
```

**Expected Output:**

```
[data-icon="search"] {
  content: "\f002";
}

[data-icon="heart"] {
  content: "\f004";
}
```

**Actual Output:**

```
@charset "UTF-8";
[data-icon="search"] {
  content: "";
}

[data-icon="heart"] {
  content: "";
}
```

The funny thing is this compiles as expected in 3.3.14

**Comment by lolmaus** [comment]
Do you even look through the issue queue before reporting?

**Comment by Snugug** [comment]
What @lolmaus is trying to say is that before posting issues you should look through at least the currently open issues to see if someone else has the same problem, even if the title isn't the same.

This issues is more or less an exact duplicate of the currently open (and still at the top of the issue queue) #1395

As an aside, @lolmaus, I'd encourage you to read the [Sass Community Guidelines](http://sass-lang.com/community-guidelines)
