### ISSUE TITLE
Having more than 4 direct children selectors ( > ) causes issues

### ISSUE THREAD

**Issue by kaytcampbell** [sass/sass#1407]
It appears that while compiling, if I have a CSS selector with more than 4 direct children selectors (i.e. something like: #content-full > div.grid.col-12 > div.col-8.left.widget > div > div.col-4.widget.left > div.circle-wrapper > img{} ) everything stops compiling.

I wasn't sure if it was the compiler that had the issue so I tried using Scout and CodeKit. CodeKit gets stuck compiling it, and it ramps up the memory usage (via Ruby) slowly over time. Quitting CodeKit doesn’t fix the memory usage issue, the only way I found was to kill Ruby in the memory processes (or restart). Scout just stop compiling.

I played around with the amount of direct children selectors and it seems to break when there is more than 4.

**Comment by lolmaus** [comment]
GUI apps use the same compiler as the `sass` command line tool.

Can you reproduce the issue on http://sassmeister.com/ ?

**Comment by willsoto** [comment]
I think the issue is that you don't have a property within img (e.g., `background`) and so there is no output. Sassmeister outputs CSS if I have at least 1 property within the selector, but nothing if it is blank.

As to the other issues, I am not sure what is going on.

**Comment by kaytcampbell** [comment]
Sorry I should have put that in my original issue, I was applying margin to the image. 

I tried to reproduce the issue on Sassmeister and it seemed to work fine on there, so not too sure why it would work there and not on my local machine.

I also tried just running the compiler from the command line to see if there would be any difference, and got the same issue I had with CodeKit.

**Comment by lolmaus** [comment]
If you're using Bundler share your `Gemfile` and `Gemfile.lock` via https://gist.github.com/ .
If not, share the output of `gem list | grep sass`.

**Comment by kaytcampbell** [comment]
sass (3.2.19)
sass-rails (4.0.3)

**Comment by lolmaus** [comment]
You're two versions behind, but it works for that version too: http://sassmeister.com/gist/1a1783cf2fcf3cc7c068 .

You're not likely to receive help until you manage to come up with a reproduction scenario. Ideally, you could create a minimal project that demonstrates the issue and share it via GitHub.

**Comment by nonewcode** [comment]
I know this may not help, but if you need to go down 4 levels in your selector; i would first look at optimising your HTML structure....There would surely be a better way to do things rather than targeting something that specifically.

**Comment by lolmaus** [comment]
@joshuakelly, i encountered situations where you have no other options.

Imagine that:
1. you have a page component with a complex HTML structure, 
2. you have to nest its instances into one another,
3. the looks of an instance should vary depending on its context (e. g. how deep it's nested, what's its state, etc).

In this case, it becomes impossible to target elements by single class because their looks depends on context, and it's impossible to use the descendent combinator (space) because it would affect all nested elements.

I had to target all elements by abusing the immediate child (`>`) combinator. I didn't end up with more than four selectors combined, but still.

**Comment by kaytcampbell** [comment]
I realize there are better ways to target elements. However, I was using the Chrome inspector and that's the CSS path it gave me to the specific element (I was being lazy).

I cannot seem to replicate the issue on other projects though, so I'll just close this ticket for now.

**Comment by nex3** [comment]
This looks like some sort of RegExp optimization issue. If you ever manage to reproduce it, let me know which Sass and Ruby version you did it with and I'll look into it.
