### ISSUE TITLE
--watch for symlinked files and directories doesn't work on OS X

### ISSUE THREAD

**Issue by ghost** [sass/sass#1411]
Hello,
I'm watching my SASS folder that contains another folder which is symlinked. It doesn't compile my code when I make modifications and save into files of this symlinked folders

**Comment by nex3** [comment]
What version of Sass are you using? This should have been fixed in version 3.4.2.

**Comment by ghost** [comment]
I use the last version : 3.4.2

**Comment by nex3** [comment]
Can you provide more information about your setup? What version of the `listen` gem do you have installed, if any? What's your OS and version? What exact command-line invocation are you using when running `sass --watch`?

**Comment by ghost** [comment]
I have not installed listen gem and my OS version is : macOS 10.9.4
The command I use is : sass --watch sass:css

**Comment by tbremer** [comment]
I have a developer who is seeing the same issue, it appears that Listen isn't coming through as a required gem when installing SASS 3.4.2.. Our watch is..

``` shell
$ sass --watch --no-cache --style nested --trace --sourcemap=none source:destination
```

Their system is:
Macbook Pro mid 2012
OSX 10.8.5
Ruby version: `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]`

@cssyren what version of Ruby are you running? `ruby -v` to check

When she installed `Listen` the SASS Watch executed perfectly.

Edit: I am not super familiar with Ruby, but it appears that the Listen gem is required per your Gemfile spec (sass/Gemfile):

``` ruby
if RUBY_VERSION =~ /^1\.8/
  gem 'listen', '~> 1.1.0'
elsif RUBY_VERSION =~ /^1\.9\.[012]$/
  gem 'listen', '>= 1.1.0', '< 2.0.0'
else
  gem 'listen', '>= 1.1.0', '< 3.0.0'
end
```

**Comment by nex3** [comment]
@cssyren @tbremer what are the full paths of the directories being watched? are any of the parent directories symlinks, on network drives, anything like that?

Also, @cssyren, if you run `gem install listen` does it start working?

**Comment by tbremer** [comment]
My full path is: `/var/www/html/answers.com/answ_sass/red-carpet`

answ_sass/red-carpet is not symlinked anywhere (neither are any of it's parents and they aren't network drives), but we do reference symlinked directories in our sass files (our sass library with things like Bourbon, FontStacks and homebrewed mixins & functions).

It (maybe?) should be noted that Gems are installed normally, so we are running the executable from a different partition on the same drive.

**Comment by nex3** [comment]
Since I can't reproduce this locally, is anyone able to reproduce it on a machine that I could SSH into? Failing that, is anyone willing to work closely with me for an hour or so to see if we can glean more information about what's going on?

**Comment by ghost** [comment]
Hello, it's the same form me if I install the listen gem. It doesn't work.
my full path is : /Users/meudah/Sites/Workspace/ccm/ccmadmin/public/2014

**Comment by tbremer** [comment]
@nex3 unfortunately I can't let you SSH into my machine where I can replicate the issue, but I can do a screen share with you sometime this week to try and help find a diagnosis.

**Comment by Paxa** [comment]
Same issue. I figured out that it works only for updates of main file, but when I change included files (via @import) it not updates.

```
sass --watch ./style.sass:style.css
```

Adding `--poll` option or `gem listen` don't make difference

**Comment by Paxa** [comment]
I think I find some solution. In file Sass::Plugin::Compiler https://github.com/sass/sass/blob/stable/lib/sass/plugin/compiler.rb#L338

I add this code:

``` ruby
      directories.each do |dir|
        Dir.glob("#{dir}/**/*.sass").each do |file|
          @watched_files << Sass::Util.realpath(file).to_s
        end
      end
```

I track what happen, when I update file in sub-directory it trigger event `on_file_changed` in object `Sass::Plugin::Compiler`, but `watched_file?(f)` always return false because:

``` ruby
      individual_files.each do |(source, _, _)|
        source = File.expand_path(source)
        @watched_files << Sass::Util.realpath(source).to_s
        directories << File.dirname(source)
      end
```

and `individual_files` is only files in that directory, not sub-directories

in my case it's:

```
["./style.sass", "style.css", "style.css.map"]
```

**Comment by canaandavis** [comment]
I'm having the same issue as @Paxa, where did you include the line of code in complier.rb ?

**Comment by nex3** [comment]
@Paxa that's expected. `sass --watch` only watches files/directories that are actually passed on the command line (as well as those on your load path). Either watch the entire directory or add the path to the files you import to your load path.

@tbremer Assuming you're not seeing the same issue as @Paxa, can we do a screenshare sometime next week? I'm free pretty much any afternoon other than Monday; just send me an email with a time at nex342@gmail.com.

**Comment by tbremer** [comment]
@nex3 I'll send you an email on Monday when I know my meeting schedule a little better and we'll set a time up!

**Comment by tbremer** [comment]
I am digging through the source code a bit, @nex3 are you purposefully using a hash from April 11 as the vendor/listen version??

```
commit 59a5cf42c02ce9731f33b01658bdf148c1b568ef
Merge: 3a51540 80a8627
Author: Thibaud Guillaume-Gentil <thibaud@thibaud.gg>
Date:   Fri Apr 11 13:27:16 2014 +0200

    Merge pull request #205 from nex3/v1.3

    Don't load an adapter if it can't be required.
```

**Comment by Paxa** [comment]
That's how I test and it not working
https://gist.github.com/Paxa/f739ca0e77f1f70f60c8

structure is:

```
folder/
  style.sass
  elements/_button.sass
```

**Comment by tbremer** [comment]
You need to watch the whole directory not just s single file.

**Comment by Paxa** [comment]
How to make it? (if there more then one sass file but I want to compile only one)
In previous versions it always worked like this

**Comment by tbremer** [comment]
You can do a series of import statements in your `style.sass` file.

**Comment by Paxa** [comment]
Can you give some example?

**Comment by tbremer** [comment]
@Paxa, feel free to email if this doesn't help you out.. Your issue is not what this open ticket is about...

**Assume this DIR structure**

``` bash
CSS/
SASS/
    partials/
        - _buttons.sass
        - _inputs.
        - _anchortags.sass
    stylesheets/
        - _homepage.sass
        - _aboutus.sass
        - _portfolio.sass
    style.sass
```

**Within your`style.sass` file you would have...**

```
// Elements
@import 'partials/buttons'
@import 'partials/inputs'
@import 'partials/anchortags'

// Pages
@import 'stylesheets/homepage'
@import 'stylesheets/aboutus'
@import 'stylesheets/portfolio'

// Your styles
#content
  :overflow hidden
  .tabContent
    :height 100%
```

**So, your sass watch would then be:** `sass --watch sass/:css/`

**Comment by nex3** [comment]
> I am digging through the source code a bit, @nex3 are you purposefully using a hash from April 11 as the vendor/listen version??

Yes. More recent versions of listen don't support Ruby 1.8.7, but Sass does, so we vendor in an old version to maintain compatibility.

**Comment by tbremer** [comment]
I am probably wrong, but doesn't sass/Gemfile also take care of that?

``` ruby
if RUBY_VERSION =~ /^1\.8/
  gem 'listen', '~> 1.1.0'
elsif RUBY_VERSION =~ /^1\.9\.[012]$/
  gem 'listen', '>= 1.1.0', '< 2.0.0'
else
  gem 'listen', '>= 1.1.0', '< 3.0.0'
```

The only reason I ask is that newer version of Listen seem to work fine.

**Comment by nex3** [comment]
The Gemfile isn't used by RubyGems for version resolution. We tried unbundling in the runup to 3.4, and it didn't work well.

**Comment by tbremer** [comment]
@nex3 your fix works great! thank you for addressing this issue. I'm sorry I got caught up in a big project at work work and wasn't able to help / do the screen share.

:relieved: :beers:

**Comment by Paxa** [comment]
Awesome! :+1:
