### ISSUE TITLE
Proposal: alias method name in sass

### ISSUE THREAD

**Issue by ghost** [sass/sass#1413]
It would be great that we can have the alias method in sass, it will help a lot in building concise API. And furthermore, I see that there is a pattern in alias is that : 
One method can have an alias or a "negative-alias" ( I haven't found a good name yet for this kind of method ), that the "negative-alias" just returns opposite result of a method.

``` ruby
@function is_true() {
  @return true
}
alias not_false, is_true;
negative_alias is_true, is_false; 
# is_false is internally defined
# @function is_false() {
#   @return not is_true();
# }
```

This kind of operation is suitable for function either return true or false. But still, we can return array of values or empty array, hash of values or empty hash.

**Comment by nex3** [comment]
There's no need to add extra syntax for something that's trivial to do by manually defining a function.

**Comment by lolmaus** [comment]
Though i do think that an alias directive would be handy, latest Sass does provide an almost effortless way to define an alias:

``` sass
@function bar($args...)
  @return foo($args...)
```

You don't even have to care about the number of arguments.

Demo: http://sassmeister.com/gist/60617e4949b6de85d87a

**Comment by ghost** [comment]
thanks @lolmaus. That is handy :)
