### ISSUE TITLE
Regression: Sass::Tree::RuleNode#rule includes trailing comments

### ISSUE THREAD

**Issue by sds** [sass/sass#1416]
The following program returns different output between Sass 3.3.14 and 3.4.2 (i.e. something changed in the minor version bump from 3.3 to 3.4).

``` ruby
require 'sass'

engine = Sass::Engine.new(<<-SCSS, cache: false, syntax: :scss)
p, // Hello
q {
}
SCSS

puts engine.to_tree.children.first.rule.inspect
```

For 3.3.14 it correctly outputs:

``` ruby
["p, \nq"]
```

For 3.4.2, it **incorrectly** outputs:

``` ruby
["p, // Hello\nq"]
```

**Comment by Arcovion** [comment]
Possible duplicate of #326

**Comment by sds** [comment]
Unless I'm misunderstanding that issue, that seems to deal entirely with the Sass syntax, not SCSS. I'm only interested in the SCSS case, which the parser handled correctly until 3.4.x.

**Comment by nex3** [comment]
Sass neither follows semantic versioning nor makes strong guarantees about the compatibility of its internal AST representation across versions. As long as the compilation still works, we're happy.

When handling selectors, it's probably a good idea to fully parse them using `Sass::SCSS::StaticParser`.

**Comment by chriseppstein** [comment]
@nex3 I think we should put a statement to this effect in our API documentation. Do you concur?

**Comment by nex3** [comment]
Sure.
