### ISSUE TITLE
Errno::ENOENT: No such file or directory in Sass.load_paths with bootstrap-sass 2.x

### ISSUE THREAD

**Issue by ianwdunlop** [sass/sass#1418]
With sass gem 3.4.2 I get a Errno::ENOENT: No such file or directory ... /vendor when running a Rails 3.2.19 (or 3.2.18) app. It seems that one of the Sass.load_paths entries is missing the application root directory so it ends up like /Users/Ian/vendor rather than /Users/Ian/app_name/vendor. I downgraded to 3.4.1 in the Gemfile and it works ok.
I think it is a clash with something in the boostrap-sass 2.x gem. I have replicated the problem with v2.3.2.1 & 2.3.2.2. With 3.2.0.2 it works ok. However, I have struggled to figure out if it is the bootstrap-sass gem doing something wrong or the sass gem.

**Comment by nex3** [comment]
Duplicate of #1406.
