### ISSUE TITLE
Should selectors with leading combinators be valid Sass?

### ISSUE THREAD

**Issue by michaek** [sass/sass#1419]
Per http://dev.w3.org/csswg/selectors4/#combinators, combinators are intended to separate two compound selectors. Currently, at least in Sass 3.2.x-3.4.1, the following

```
.a { x: y; }
> .b { @extend .a; }
```

compiles happily to invalid CSS, but this

```
.a { x: y; }
.b > { @extend .a; }
```

errors with the message `.b > can't extend: invalid selector`. It seems like both `.b >` and `> .b` should be invalid and result in the same error.

Thanks!

**Comment by nex3** [comment]
This is actually intended. Leading combinators are sometimes used as a hack to cause a rule to be invisible to some but not all browsers, so we support them even in `@extend`.

**Comment by michaek** [comment]
I figured it was from one of the comments, but I couldn't find any current CSS hacks that fit that pattern. Am I missing something?

**Comment by michaek** [comment]
Would it be possible for someone to clarify which hacks we're talking about? I've searched and asked around a bit, and I haven't yet been able to dig up a CSS hack that starts a selector with a combinator.

**Comment by nex3** [comment]
Unfortunately, I didn't think to write down the sources for the hacks when I added support for them.
