### ISSUE TITLE
SASS on Mac OSX Lion broken

### ISSUE THREAD

**Issue by ghost** [sass/sass#142]
Just updated our systems to Mac OSX Lion. We typically ask SASS to watch an entire directory for changes, like this:

```
$ sass --watch app/sass:public/stylesheets
```

However, after updating to Mac OSX Lion, when SASS detects a change to one of our sass files, and attempts to rebuild the destination css file, we receive the following error:

```
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/vendor/fssm/lib/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

Abort trap: 6
```

**Comment by nex3** [comment]
@ttilley This seems like an FSSM problem.

**Comment by ttilley** [comment]
The fsevents backend is the one making use of rubycocoa... and that line is the one that enters the runloop. So the extent of information we have to go on is that something went south in the event handler before re-entering ruby-land via the bridge. Enabling debugging:

```
2011-07-24 16:20:38.702 ruby[81286:60b] DATACNV : converted arg #0 of type ^{__FSEventStream=} to Ruby value 0x10ffaecd0
2011-07-24 16:20:38.703 ruby[81286:60b] DATACNV : converted arg #1 of type ^v to Ruby value 0x4
2011-07-24 16:20:38.704 ruby[81286:60b] DATACNV : converted arg #2 of type Q to Ruby value 0x3
/Library/Ruby/Gems/1.8/gems/sass-3.1.4/vendor/fssm/lib/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
```

Uhhh... Hmm. Did something change somewhere with how the rubycocoa bridge converts types? This one sounds potentially painful. -_-

...and, correct, an FSSM bug and not a SASS bug.

**Comment by ttilley** [comment]
One that I forgot I had already fixed on "Mon Mar 21 03:24:04 2011 -0400", and by fixed I mean "turned off completely when using lion". So installing FSSM instead of using the vendored version will also work for you (and suggest that you install rb-fsevents instead of using rubycocoa).

lawl.

**Comment by JakeSchoermer** [comment]
Same problem here on Lion. I'd be pretty interested in finding a resolution to this.

**Comment by nex3** [comment]
@Schermy This should be fixed by now. What version of Sass are you using?

**Comment by JakeSchoermer** [comment]
I'm currently running 3.0.25 using rvm.
