### ISSUE TITLE
Nested @for loops act strange

### ISSUE THREAD

**Issue by metamn** [sass/sass#1420]
I'm expecting in nested loops that the inner loop is finished first then the external loop. As this pen shows the external loop executes first then the internal.

```
article {
  @for $i from 1 through 4 {
    @for $j from 1 through 2 {
      $k: $i + $j - 1;
      &:nth-of-type(#{$k}) {
        &:after {
          content: "#{$k}: #{$i} - #{$j}";
        }
      }
    }
  }
}
```

The output is:

```
1: 1 - 1
2: 2 - 1
3: 3 - 1
4: 4 - 1
5: 4 - 2
```

The pen: http://codepen.io/anon/pen/EdukJ

**Comment by metamn** [comment]
With further investigation using the Web Inspector on Codepen I see the loop works well.
Only the nth-of-type() is not working.

The first article has 1 nth-of-type(1), the second article has two nth-of-types(2).

The output is:

```
article:nth-of-type(1):after {
    content: "1: 1 - 1";
}

article:nth-of-type(2):after {
    content: "2: 2 - 1";
}
article:nth-of-type(2):after {
    content: "2: 1 - 2";
}
```

**Comment by nex3** [comment]
That's because of how you're computing `$k`:
- `$i = 1, $j = 1, $k = 1 + 1 - 1 = 1`
- `$i = 1, $j = 2, $k = 1 + 2 - 1 = 2`
- `$i = 2, $j = 1, $k = 2 + 1 - 1 = 2`

etc.
