### ISSUE TITLE
Running sass -v errors

### ISSUE THREAD

**Issue by mattfelten** [sass/sass#1421]
I just ran `sudo gem install sass` and then tried `sass -v` to make sure it worked

```
$ sass -v
/usr/lib/ruby/gems/1.8/bin/sass:19:in `load': no such file to load -- sass (LoadError)
    from /usr/lib/ruby/gems/1.8/bin/sass:19
```

`ruby -v` gives me 

```
ruby 1.8.7 (2008-08-11 patchlevel 72) [x86_64-linux]
```

which looks like it should be fine.

What am I missing?

**Comment by mattfelten** [comment]
`sudo sass -v` totally works though and shows the right one... This is so weird.

```
$ which sass
/usr/lib/ruby/gems/1.8/bin//sass
$ sudo which sass
/usr/bin/sass
```

There's a double slash in that first path. Where'd that come from?

**Comment by nex3** [comment]
This sounds like an issue with your Ruby installation. Try uninstalling and reinstalling ruby.
