### ISSUE TITLE
:custom option

### ISSUE THREAD

**Issue by vuhrmeister** [sass/sass#1423]
As documented [here](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options) there is an option `:custom` which is "available for individual applications to set to make data available to custom Sass functions."

I didn't get it working. On console it tells me 

> stderr: OptionParser::InvalidOption: invalid option: --custom`

I also couldn't find any further information. Is this option still valid or was it removed at some point? If so, please update the docu. Otherwise it would be great if you could explain how to deal with it and extend the docu.

**Comment by nex3** [comment]
That documentation refers to Ruby options. The command-line options are separate, although there is some overlap.
