### ISSUE TITLE
Math Behavior in 3.4.3

### ISSUE THREAD

**Issue by bdkjones** [sass/sass#1427]
Since updating to Sass 3.4.3, I'm getting lots of reports from folks using grid systems (Bourbon Neat, Jeet, Foundation, etc) that the Sass compiler is no longer producing the correct (or expected, at least) output from math operations. 

Here's a representative example: https://github.com/mojotech/jeet/issues/344

I'm not sure what to tell these folks. Is this an issue with the changes in Sass 3.4 or are there changes that need to be made to the Sass in these grid systems in order to be 3.4+ compliant?

**Comment by lolmaus** [comment]
Might be related to #1122.

**Comment by bdkjones** [comment]
#1122 was a good discussion and I'll bump up my default precision. 

In the meantime, it looks like this is not an issue. Several of the folks involved have gotten back to me and said they resolved it. One guy was using a version of Bourbon Neat from a year ago, etc. So, sorry for the fuss.
