### ISSUE TITLE
Comment inconsistencies when converting syntax

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1432]
Sass 3.4.3.

In `sample.sass`:

``` scss
/**
 * This is a docblock comment
 */
```

... when converted to SCSS:

``` scss
/*
 * This is a docblock comment
 */
```

Unfortunately, the missing star means the comment is not a docblock anymore for a documentation parser. :(

**Comment by KittyGiraudel** [comment]
> In general we don't guarantee formatting equivalence when doing conversions, especially for round-trips through other syntaxes.

In this case, I am not sure we can talk about "formatting equivalence". Comment style provides meaning. 

The same way inline comments are stripped and star-bang comments are permanent, double-stars comments are a sign of "official" documentation while single-star comments are for "casual" commenting. 

Not sure I'm being clear though.

**Comment by lolmaus** [comment]
Also, the double asterisks can serve as an indication to CSS compressors not to remove that comment. It is used for keeping license info which is illegal to be removed.

**Comment by KittyGiraudel** [comment]
As far as I know it's the star-bang that is meant to do this `/*! ... */`.

**Comment by lolmaus** [comment]
Ah, okay. Still that's a demonstration of the importance of not crippling the comment.

**Comment by nex3** [comment]
I'm fine with preserving the double-star, since it's a well-known convention (although honestly I think using CSS comments rather than single-line comments for documentation is a misuse). I'm just saying that in general comment formatting isn't something we guarantee will be preserved through conversions.

**Comment by KittyGiraudel** [comment]
> I'm fine with preserving the double-star

Thank you. 

> although honestly I think using CSS comments rather than single-line comments for documentation is a misuse

Agreed. Although for now our parser doesn't handle inline comments. We stick with the convention: double-star.

> I'm just saying that in general comment formatting isn't something we guarantee will be preserved through conversions.

Understood.
