### ISSUE TITLE
Partial dependency requirements

### ISSUE THREAD

**Issue by webbower** [sass/sass#1433]
It would be awesome to have a syntax in SASS where you can define at the top of a partial file (one whose filename starts with and underscore) what other SASS partials it depends on. For example, lets say I have a _buttons.scss and I make a partial that defines a layout module that requires the _buttons.scss partial, at the top, I could write something like:

```
@depends "partials/modules/buttons";

// ... SASS code
```

where the argument for `@depends` would match the argument for `@import`. Then, when the SASS compiles, if the dependency isn't loaded before this partial, it throws a compilation error.

This would help enforce source order, especially in projects with many contributors, as well as provide a sense of inline documentation (what this partial depends on).

**Comment by lolmaus** [comment]
With [compass-import-once](https://github.com/Compass/compass/tree/master/import-once) you can safely import dependencies every time you need them.

It's included by default into Compass projects.

**Comment by nex3** [comment]
Ideally you should just be able to `@import` it and have that work. Because that re-runs the code in the dependency, it's problematic right now, but we're working on a new import directive that will make it much smoother.

**Comment by webbower** [comment]
Hey now. Don't close this yet.

It doesn't sound like you guys are understanding what I'm getting at. This directive (which would be at the SASS level, not the Compass level @lolmaus) would enforce partial import order without having to import files multiple times at the top of a partial module.

**Comment by webbower** [comment]
This would be good for at least a couple reasons:
- With multiple contributors, it conveys which partials depend on each other and throws compile-time errors if a partial gets included out of order.
- If you have a large project with multiple CSS entry points, if you want to use a module defined in a partial in a new entry point, it would tell you if you're missing dependencies.

**Comment by nex3** [comment]
`@import` handles everything you're describing already.
