### ISSUE TITLE
Invoking functions with a @do directive, and then adding a !bang flag

### ISSUE THREAD

**Issue by ezekg** [sass/sass#1434]
With the introduction of maps, I've seen a huge rise in patterns like this,

``` scss
$variable: ();

// ...

$variable: map-merge($variable, ("key": "value"));
```

Essentially, we're just replacing the `$variable` map with a new, updated version of itself, while not actually modifying `$variable` directly. I'm not sure if this is how it is really handled, but from the looks of it, we're creating an unnecessary duplicate of what _could be_ a rather large map. Seems wasteful. And although the pattern works, I don't really like the repetitive nature of using it all the time, over and over again.

What if we created a new `!bang` flag that can be combined with a `@do` directive. Allowing you to first, invoke a function directly while blocking its return value, sort of like what was discussed [here](https://github.com/sass/sass/issues/1348), but less about omitting `@return` entirely. Secondly, the `!bang` flag modifies the original variable passed into `map-merge` similar to Ruby's `!` bang methods, getting rid of the need to create unneeded duplication and memory waste.

This would also allow us to create streamlined setter functions without the need of a `@mixin` wrapper just to be able to call the function. We can just `@do` the function.

``` scss
@do map-merge($result, ("key": "value")) !bang;
```

Just a thought.

**Comment by nex3** [comment]
The distinction between mixins and functions exists explicitly because mixins have side effects in a way that functions don't (or rather, usually shouldn't). If you want to a shortcut for doing something with a side effect, a mixin is a great way to do that.

`!bang` is extremely unclear, and we're not interested in making Sass's data structures mutable.
