### ISSUE TITLE
Please provide different exit codes for errors vs. aborted

### ISSUE THREAD

**Issue by blueyed** [sass/sass#1439]
As reported / raised in https://github.com/scrooloose/syntastic/issues/1186#issuecomment-55692814, it would be nice if `sass --check` would have better exit codes to make it easier to distinguish between "aborted" and "failed", e.g.

0 - no error
1 - parsing aborted (invalid options, file not found, or OS-level problems, such as permission denied)
2 - parsing completed, but errors or warnings were issued

**Comment by chriseppstein** [comment]
I don't understand the purpose of this distinction.

**Comment by blueyed** [comment]
It is meant for Syntastic and others to detect if the invocation failed, e.g. because the compass installation is broken etc, vs. if there were errors in the scss/sass instead.
