### ISSUE TITLE
(nope, it's about colour interpolation) Can't @extend using nested @each only when using output-style 'compressed' 

### ISSUE THREAD

**Issue by mkstix6** [sass/sass#1440]
I'm creating some classes (near the beginning of my scss) for some icons using nested each loops like:

```
@each $iconcolor in
white,
black,
blue
{
  @each $iconname in
  addcircle,
  article,
  calendar{
    .icon-#{#{$iconname}-#{$iconcolor}}{
// i have these icons as separate SVG files at this point, i intend to sprite them later
       background-image:url('style-images/icons/#{$iconcolor}/#{$iconname}.svg');
}
}
}
```

So that i can extend to them later to use those classes about the site like:

```
.calendartitle{
@extend .icon-calendar-white;
}
```

It works fine _unless_ i set CodeKit's output style to compressed. When using compressed i get an error:

```
Error: ".calendartitle" failed to @extend ".icon-calendar-white".
       The selector ".icon-pluscircle-white" was not found.
       Use "@extend .icon-pluscircle-white !optional" if the extend should be able to fail.
        on line 428 of /Users/mk/Sites/Nuviunv2/scss/_dashboard-main.scss
  Use --trace for backtrace.
```

Anyone else experiencing something similar? From simply switching output style between compressed, compact, etc. It's like sass's compressed algorithm is messing something up.

Compiling with CodeKit 2.1.5 using SASS 3.4.3 (Selective Steve)

Real backtrace if it's useful:

```
/*
Sass::SyntaxError: ".fe-addimage img" failed to @extend ".icon-pluscircle-white".
The selector ".icon-pluscircle-white" was not found.
Use "@extend .icon-pluscircle-white !optional" if the extend should be able to fail.


Backtrace:
/Users/mk/Sites/Nuviunv2/scss/_dashboard-main.scss:428
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/extend.rb:61:in `block in check_extends_fired!'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util/subset_map.rb:106:in `block in each_value'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util/subset_map.rb:106:in `each'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/util/subset_map.rb:106:in `each_value'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/extend.rb:50:in `check_extends_fired!'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/visitors/extend.rb:16:in `visit'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/root_node.rb:39:in `css_tree'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/tree/root_node.rb:20:in `render'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/engine.rb:268:in `render'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/exec/sass_scss.rb:383:in `run'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/exec/sass_scss.rb:62:in `process_result'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/exec/base.rb:40:in `parse'
/Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/exec/base.rb:19:in `parse!'
/Applications/CodeKit.app/Contents/Resources/engines/scss/bin/scss:13:in `<main>'
*/
```

**Comment by lolmaus** [comment]
This has nothing to do with nested lists.

Your problem is well known: you're interpolating color names and in compressed mode color names are converted into hex codes, thus producing different selectors.

The solution is simple: quote color names, then they will be treated as strings and will not be converted.

Demo: http://sassmeister.com/gist/fdc6abe9c9893f6eab44

Since https://github.com/sass/sass/issues/1256 , you should receive a warning when interpolating colors. Did you pay attention to the console output?

**Comment by mkstix6** [comment]
Ahh thanks i will try this.

Weird that it only just started breaking it. I haven't changed this code recently must be with the sass update when CodeKit updated.

I haven't see a warning ever about colour interpolation. Is this something that is a SASS problem or a CodeKit issue? I guess i never compile with the terminal directly. The only error i ever see is the 'failed to extend' one.

Thanks again for your help

**Comment by lolmaus** [comment]
This has nothing to do with CodeKit. This is a bugofeature of Sass, known for years.

If you're not seing the warning then you're probably using an version of Sass older than the warning was introduced in.

**Comment by mkstix6** [comment]
Codekit reports it is using Sass 3.4.3. Is that new enough (i see it's 3.4.4 now)?

Thoughts?

**Comment by whaaaley** [comment]
I'm also using Codekit which currently uses Sass 3.4.3. I got the warning about interpolating colors once, but since then I couldn't' seem to reproduce it. It throws the error instead. Maybe it's completely fixed in 3.4.4, not 3.4.3?

Looks like we'll just have to wait on Codekit for the update. In the meantime quoted colors would do.

**Comment by lolmaus** [comment]
@dustindowell22, i doubt that it has anything to do with CodeKit.

For the availability of the warning, let's wait for @nex3's comment.

**Comment by whaaaley** [comment]
@lolmaus I didn't mean that it did have anything to do with Codekit. Only that it was running an older version of Sass. I agree with you.

**Comment by mkstix6** [comment]
Ahh cool, glad i haven't done something too wrong.
Thanks for the input both. Patience will win out here I think.

**Comment by nex3** [comment]
It should warn every time you use a color in interpolation. If anyone can find a case on the command line where it fails to do so, file an issue for it.
