### ISSUE TITLE
Adding the detection of relative color luminance

### ISSUE THREAD

**Issue by brettalton** [sass/sass#1441]
As per this post: http://thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass, Sass currently contains a method for detecting lightness but not luminance. Via  http://lea.verou.me/chroma-zone/#slide44, you can detect a color's luminance using,

```
get luminance () { // Formula from WCAG 2.0
    var rgb = this.rgb.map(function(c){
        c /= 255; // to 0-1 range
        return c < .03928 ? 
                 c / 12.92 : 
                 Math.pow((c+.055)/1.055, 2.4);
    });

    return 21.26 * rgb[0] + // red
           71.52 * rgb[1] + // green
            7.22 * rgb[2];  // blue
}
```

For developing applications on mobile phone to large screens, I would be more interested in the luminance than the lightness. Thoughts?

**Comment by nex3** [comment]
Generally we try to stick with the properties of the color specified in CSS. That said, luminosity is something pretty dissimilar to the existing measurements, and something that's particularly useful for manipulating colors, so I would be open to adding support for it.

Before doing so, though, I'd like to see it get some use in user-space. Make a library with it, let people play around with that library, iterate on the API. If it's popular and works well, then we can talk about merging it into the core.

**Comment by cimmanon** [comment]
Have you looked through Compass?  There are additional color related mixins and functions for brightness and contrast:
- http://compass-style.org/reference/compass/utilities/color/brightness/
- http://compass-style.org/reference/compass/utilities/color/contrast/
