### ISSUE TITLE
Make @extend available for nested selectors

### ISSUE THREAD

**Issue by julkue** [sass/sass#1442]
Hi,

currently if you try to extend a class, for example `#content input` it will throw a error like: "Syntax error: Can't extend #content input: can't extend nested selectors".

It would be great if that would be available!

**Comment by whaaaley** [comment]
I think the best way to fix the problem your having is by using a placeholder like this:

```
%blue {
    color: blue;
    font-weight: bold;
}

#content {
    input {
        @extend %blue;
    }
}

.content-other {
    .content-nested {
        @extend %blue;
    }
}
```

I think extending nested selectors would get confusing easily. By using a placeholder it also makes it available if you ever want to use it again without having to remember that the styles you want to use are in `#content input`

See these issues for explanations: #609 and #251.

**Comment by lolmaus** [comment]
I second @dustindowell22.

Extends are already very confusing. My rule of thumb is to never extend normal selectors, only placeholders, otherwise bloated selectors may be produced, sometimes even causing side effects.

**Comment by lolmaus** [comment]
On the other hand, if this feature were introduced, it wouldn't hurt me in any way: don't extend nested selectors if you don't want to.

**Comment by whaaaley** [comment]
I agree. It makes sense why some people would expect it to work, but it also makes sense why this could be considered a sort of bad practice because placeholders exist.

Nested extends are supported in Stylus and Less, so it might be good for people migrating to Sass.

I don't think it would useful a feature for people already using Sass who are used to placeholders.

**Comment by julkue** [comment]
@lolmaus I can only agree. But I think it would be great to add this feature and you can however still 
decide against!

**Comment by chriseppstein** [comment]
@dustindowell22 nailed this. The rationale is that if you need to extend a modified thing, that thing is worth naming and extracting to it's own concept.
