### ISSUE TITLE
Deprecation Warning when including `sourcemap` option

### ISSUE THREAD

**Issue by jsgv** [sass/sass#1445]
I don't want sass to create Sourcemaps.

I am including the `sourcemap` option:

``` javascript
sass: {
    dist: {
        options: {
          sourcemap: 'none',
          style: 'compressed'                    
        },
        files: [{
            expand: true,
            cwd: 'assets/src/sass',
            src: ['*.scss'],
            dest: 'assets/css/',
            ext: '.css'
        }]
    }
}
```

And the error output:

```
DEPRECATION WARNING: Passing --sourcemap without a value is deprecated.
Sourcemaps are now generated by default, so this flag has no effect.
```

**Comment by Snugug** [comment]
If you don't want sourcemaps it should be `false` not `none`

**Comment by jsgv** [comment]
`false` does not stop sourcemaps from being generated.

**Comment by patrickbjohnson** [comment]
Looks like the grunt-contrib-sass docs [still reference `'none'` ](https://github.com/gruntjs/grunt-contrib-sass)

**Comment by nex3** [comment]
This looks like a Grunt configuration issue, not a Sass one.

**Comment by ghost** [comment]
This is an additional information.

(refs. https://github.com/gruntjs/grunt-contrib-sass/issues/161#issuecomment-56569772 )

I have the same problem. And solved this.
I'm using "grunt-contrib-sass" in our grunt project.
"grunt-contrib-sass" supported sourcemap option of Sass 3.4. (It is different with Sass 3.3)
https://github.com/gruntjs/grunt-contrib-sass/releases/tag/v0.8.0

Our project were using Sass 3.4 and "grunt-contrib-sass" v0.7.x. The problem will occur in this case.

Solution: (If you are using grunt-contrib-sass)
Use Sass &lt;3.4 and grunt-contrib-sass &lt;v0.8
or Sass &gt;=3.4 and grunt-contrib-sass &gt;=v0.8

I hope this will help you :)

**Comment by MarsWilliams** [comment]
@mtakai I was having this problem too, and when I followed your advice (by upgrading to a newer version of Sass), the problem was remedied. Thanks so much for your great advice!

Best,
Mars

**Comment by imruxin** [comment]
I have the problem too, but now is also an insoluble problem for me.
`false`/`none`/`auto` does not stop sourcemaps from being generated.

![image](https://cloud.githubusercontent.com/assets/5736012/5795812/c0f38346-9fd3-11e4-9385-14d5c5b07667.png)

Sass 3.4.9 (Selective Steve)
"gulp-ruby-sass": "^0.7.1"

Thanks.

**Comment by nex3** [comment]
@imruxin Can you reproduce the issue with the command-line executable? If not, I suspect it's an issue with the gulp binding.

**Comment by imruxin** [comment]
@nex3 

```
gulp.task('styles', function() {
    var cssSrc = './scss/**/*.scss',
        cssDest = './css';
    return gulp.src(cssSrc)
        .pipe(sass({
            style: 'compact',
            // sourcemap: 'auto' // none false is also the problem
        }))
        .pipe(gulp.dest(cssDest))
        .pipe(rename({
            suffix: '.min'
        }))
        //.pipe(autoprefixer('last 2 version', 'ie 8', 'ie 9'))
        .pipe(minifycss({
            //keepSpecialComments: 1,
            //keepBreaks: true
        }))
        .pipe(gulp.dest(cssDest));
});
```

Following result:
![image](https://cloud.githubusercontent.com/assets/5736012/5995796/caa3645c-aad6-11e4-83ec-ec800cda11a7.png)

But now when I use the sourcemap option：

```
.pipe(sass({
            style: 'compact',
            sourcemap: 'auto' // none/false is also the problem
        }))
```

Following result:
![image](https://cloud.githubusercontent.com/assets/5736012/5995831/907448a4-aad7-11e4-9114-628d16855818.png)

At last, Thank you

**Comment by ghost** [comment]
@imruxin

In conclusion, it seems that string format of sourcemap option in gulp-ruby-sass is not yet supported.

There are versions of 1.0.0-alpha.\* and v0.7.x in gulp-ruby-sass.
https://github.com/sindresorhus/gulp-ruby-sass/tags

v0.7.x version is not compatible with the Sass 3.4.
(gulp-ruby-sass v0.7.1 was released on 28 Jul 2014. And Sass 3.4 was released on 18 Aug 2014.)
http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#340_18_august_2014

Meanwhile, 1.0.0-alpha.\* version is compatible with the Sass 3.4. However, the format is not string but boolean.
https://github.com/sindresorhus/gulp-ruby-sass/tree/1.0.0-alpha.3#sourcemap

This document (master version) looks like misrepresentation.
https://github.com/sindresorhus/gulp-ruby-sass#gulp-ruby-sass-
(In fact, the description of sourcemap option was rewritten by the following commit.)
https://github.com/sindresorhus/gulp-ruby-sass/commit/a0711276bb7c1e83170edf5e28bb3199fff89f79

You can configure sourcemap option for Sass 3.4 in gulp-ruby-sass 1.0.0-alpha.*. But the valid value is boolean (default: false).

Notes:
gulp-ruby-sass syntax changes in version 1.0.0. See the following page and related issue.
http://stackoverflow.com/questions/28140012/gulp-typeerror-arguments-to-path-join-must-be-strings#answer-28221509
