### ISSUE TITLE
The --cache-location commandline argument does not work

### ISSUE THREAD

**Issue by sandermarechal** [sass/sass#145]
It appears that the --cache-location commandline option doesn't work in Sass 3.1.4. My exact command:

`sass --style compressed --cache-location build/sass-cache --update /home/sander/projects/fmjewelry/www/app/assets/css:/home/sander/projects/fmjewelry/www/app/webroot/css`

I have also tried it with an absolute path to `--cache-location`. The `build` directory already exists, but `build/sass-cache` does not yet. I have also tried passing just `build` as the cache location to see if it needed a path that already exists, but that didn't work.

I am running Debian Lenny with Ruby 1.8.7

**Comment by sandermarechal** [comment]
I just updated to sass 3.1.7. I'm still seeing this issue.

**Comment by jklaiho** [comment]
Seconded. Just ran into this. Sass 3.1.7 as well. Running OS X 10.7.

**Comment by nex3** [comment]
I believe this has been fixed. In any case, I can't reproduce it.
