### ISSUE TITLE
Comment breaks @if/@else via Compass#1837

### ISSUE THREAD

**Issue by scottdavis** [sass/sass#1451]
Compass/compass#1837

**Comment by pixelpuppe** [comment]
Using a comment one line before "@each" with the same indentation, I get the error message "@else must come after @if."

_This compiles without errors:_

``` sass
div
  @if true
    /* use red color */
    color: red
  @else
    /* use blue color */
    color: blue
```

_This throws an error:_

``` sass
div
  /* use red color */
  @if true
    color: red
  /* use blue color */
  @else
    color: blue
```

Also tried it with single-line comments.
Shouldn't comments be ignored?

**Comment by nex3** [comment]
This is intended. Since `/*`-style comments produce CSS output, they can't be used between `@if` and `@else` nodes for the same reason that you couldn't write

``` sass
div
  @if true
    color: red
  color: green
  @else
    color: blue
```

**Comment by lolmaus** [comment]
@nex3, the problem happens with line comments as well.

**Comment by nex3** [comment]
> @nex3, the problem happens with line comments as well.

Hmm, that's probably undesirable behavior. Unfortunately, it's also the sort of thing that can only really be fixed with a complete overhaul of the indented syntax parser, which is unlikely to happen any time soon.

**Comment by ghost** [comment]
+1
