### ISSUE TITLE
a subtle inconsistency with Sass math when multiplying/dividing compatible units

### ISSUE THREAD

**Issue by pdaoust** [sass/sass#1452]
I discovered something in my production code today:

``` scss
(180deg*2rad)/180deg
```

evaluates to `2rad`, like it would've in Sass 3.3, but

``` scss
180deg*(2rad/180deg)
```

evaluates to `114.59156deg`. Since the two equations are mathematically equivalent, does anyone know what's causing this behaviour?

**Comment by lolmaus** [comment]
`(2rad/180deg)` results in a unitless value.

`(180deg*2rad)` results in a `360deg*rad` which is CSS-invalid until you divide it by `deg` or `rad`.

**Comment by pdaoust** [comment]
Okay, I can sorta understand the reasoning; Sass can reduce `deg/rad` to a unitless number because it knows the ratio of degrees to radians. But it still feels inconsistent to me, because the multiplication operation doesn't do the same thing; I'd expect it to convert units there as well. E.g., `180deg*2rad` ought to be `20626.48062deg*deg` (or maybe `360rad*rad`; not sure which), which then, when divided by `180deg`, would give you a non-squared value.

Informal corroboration: I chatted with my wife, who knows a lot more math than I do (having actually done math and physics in college) and she told me when I'm multiplying two values with compatible units, I could conceivably use `deg·rad` or `cm·in` or whatever as the unit, but it's more useful to just choose a common denominator unit (e.g., `deg²` or `cm²`).

I see now that this isn't actually a regression; Sass has been doing this with compatible units all along. So I'm changing the title of this issue accordingly.

**Comment by lolmaus** [comment]
@pdaoust, Sass has no reasoning behind this behavior. It simply mechanically executes arithmetic operations in the specified order.

**Comment by pdaoust** [comment]
Well there does seem to be some sort of reasoning going on: with addition, subtraction, and division, there's unit conversion, but with multiplication, there isn't. It was just a surprising effect, and I thought I'd open up a conversation about whether consistency is a good idea or not here. (Following the principle of least surprise and all.)

**Comment by lolmaus** [comment]
@pdaoust how would you convert degrees multiplied by radians?

**Comment by pdaoust** [comment]
@lolmaus detailed previously -- they would be converted to a common unit, as with addition/subtraction (probably the unit of the first value, for consistency with addition/subtraction) and then have their units squared, e.g., `deg²` or in Sass terms `deg*deg`. That's essentially what's happening already whenever you multiply compatible units; it just doesn't do the step of converting.

**Comment by nex3** [comment]
This is caused by the parentheses defining the order of operations. When you write `(180deg*2rad)/180deg`, the parenthesized statement takes precedence, so you get 360 degree-radians divided by 180 degrees. Then the degrees cancel out and you end up with 2 radians.

When you write `180deg*(2rad/180deg)`, though, the first operation Sass does is the division. To do so, it first converts to compatible units, dividing 114.59156 degrees by 180 degrees. The units cancel and you get the unitless number 0.63662. Then this number is multiplied by `180deg`, adopting its units, to produce 114.59156 degrees.
