### ISSUE TITLE
Static local variables for @mixins

### ISSUE THREAD

**Issue by ghost** [sass/sass#1453]
I would like to propose static local variables for mixins.

By declaring a mixin-local variable as static with the `!static` modifier, the variable would retain its state between mixin invocations but would, as with any mixin-local variable, not be accessible from the global scope.

``` scss
@mixin foo {
    $bar: 0 !static; /* only set when mixin first invoked */
    $bar: $bar + 1;
    @debug $bar;
}

@include foo; /* 1 */
@include foo; /* 2 */
@include foo; /* 3 */

@debug $bar; /* Undefined variable: "$bar" */
```

This would entirely remove the possibility of globally scoped variable name clashes, and further (perhaps more importantly) promote encapsulation.

**Comment by stephnr** [comment]
:+1:

**Comment by pdaoust** [comment]
:+1: A compelling idea — it would eliminate the need for 'secret' variables in the global scope like `$_private-counter-for-my-mixin`, and I like how the semantics are identical to `!default` (instantiate once, assign only when not already instantiated). Coming from a C# background, it makes me nervous to declare secret globals.

I also know that the Sass scoping stuff would require a bit of rework to make this happen -- right now scoping is handled with a stack-like construction which doesn't yet have the ability to keep things around statically. So if this were deemed useful enough to implement, I'm happy to wait around for a while.

**Comment by ghost** [comment]
@pdaoust Yes, I've found far too often the need to do `$_my-private-foo` which... feels unclean.

I think it goes without saying too, that this behavior should be extended to functions if it is accepted/implemented.

**Comment by nex3** [comment]
I think this will fall naturally out of the new `@import` work we're planning.

**Comment by ghost** [comment]
@nex3 Any particular thread in which these plans are being discussed?

**Comment by nex3** [comment]
I guess #1094 is the closest.
