### ISSUE TITLE
3.4.5 seems to ignore mixin arguments

### ISSUE THREAD

**Issue by pavellishin** [sass/sass#1454]
example.scss

```
// Keyframe animations
@mixin keyframes($animation-name) {
  @-webkit-keyframes $animation-name {
    @content;
  }
  @-moz-keyframes $animation-name {
    @content;
  }
  @keyframes $animation-name {
    @content;
  }
}

@include keyframes(move-up) {
  0% {
    top: 25px;
    opacity: 1;
  }

  100% {
    top: -50px;
    opacity: 0;
  }
}
```

Expected result: 

```
@-webkit-keyframes move-up {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
@-moz-keyframes move-up {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
@keyframes move-up {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
```

Actual result:

```
@-webkit-keyframes $animation-name {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
@-moz-keyframes $animation-name {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
@keyframes $animation-name {
  0% {
    top: 25px;
    opacity: 1; }
  100% {
    top: -50px;
    opacity: 0; } }
```

**Comment by lolmaus** [comment]
You can fix this with interpolation:

```
@-webkit-keyframes #{$animation-name} {
```

But the issue is legit: the behavior has changed and is breaking.

**Comment by pavellishin** [comment]
Thanks for confirming this for me, I don't know very much about sass - it's a dependency of another project I'm working on - so I was just sort of surprised. Luckily, a user notified me that things were breaking, and git helped me find the break in the resulting .css file :/

**Comment by lolmaus** [comment]
By the way, your issue title is misleading. Those are not mixins, but rather CSS directives that are treated by Sass almost literally (not parsed/executed).

**Comment by pavellishin** [comment]
Ah, sorry - again, not super familiar with sass. I wasn't aware that @include was a css directive, I thought it was a mixin...

**Comment by lolmaus** [comment]
@pavellishin, `@include` is a Sass directive. But the problem occurs not in `@include`, but rather in `@keyframes`, which is a CSS directive.

**Comment by pavellishin** [comment]
Oh, I see - you're saying that when sass sees

`@-webkit-keyframes $animation-name {`

It notices the @...keyframes directive, and doesn't bother scanning the rest of the line to check whether there are any variables that need to be evaluated, right?

**Comment by lolmaus** [comment]
@pavellishin, yes, as you noticed, this behavior was introduced in the recent version. Let's wait for @nex3 to tell whether it is a feature or a regression.

I consider this a regression because it breaks existing code and i can't think of any reasoning behind it.

**Comment by pavellishin** [comment]
I agree.

**Comment by nex3** [comment]
`@keyframes` were never supposed to take raw variables. We considered that a bug, so we didn't introduce a deprecation period for it. There's been some confusion, but not too much.
