### ISSUE TITLE
Placeholder extend incorrectly works in pseudo selectors.

### ISSUE THREAD

**Issue by extempl** [sass/sass#1455]
Source: 

```
.block {
  color: black;

  %test {
    color: white;
  }

  &::before {
    @extend %test;
    color: green;
  }

  .some-block {
    @extend %test;
  }
}
```

Result: 

```
.block {
  color: black; }

  .block .block::before, .block .some-block {
    color: white; }

  .block::before {
    color: green; }
```

`.block .block::before` should be `.block::before`

**Comment by extempl** [comment]
Seems like this happens only if placeholder was defined inside of `.block`

**Comment by whaaaley** [comment]
The problem is you're nesting your placeholder, so everywhere you extend `%test` you're actually extending `.block %test` and because `%test` is a placeholder, it never gets output, so I see how that could get kind of confusing. It's not just limited to pseudo elements either. I, and I think others, would recommend to never nest placeholders.

So something like this instead:

Input

```
%test {
    color: white;
}

.block {
    color: black;

    &::before {
        @extend %test;
        color: green;
    }

    .some-block {
        @extend %test;
    }
}
```

Output

```
.block::before, .block .some-block { color: white; }

.block { color: black; }
.block::before { color: green; }
```

**Comment by extempl** [comment]
Well, I defined placeholder inside of a block simply because I need to limit its scope. And it's correctly works for any block where it was extended. But it incorrectly works for pseudo-elements. 

Yes, you always can rename placholders to separate scopes. But sometimes it's not the true way.

**Comment by whaaaley** [comment]
Okay. I see the problem you're having. It is a little weird the way that works. I see how that could be expected. You need to use `@at-root` so it doesn't copy the parent again.

```
@at-root {
    %test {
        color: white;
    }
}
```

Though, I still think not nesting would be a better bet.

**Comment by nex3** [comment]
@dustindowell22 is right. Sass resolves nesting before it does any `@extend` stuff, so what it sees is this:

``` scss
.block {
  color: black;
}

.block %test {
  color: white;
}

.block::before {
  @extend %test;
  color: green;
}

.block .some-block {
  @extend %test;
}
```

I agree with @dustindowell22 that you shouldn't use nesting for this sort of namespacing.
