### ISSUE TITLE
@import style of a selector from a specific style

### ISSUE THREAD

**Issue by julkue** [sass/sass#1456]
Hello

I have the problem that in my base-app.scss I have defined a list-style inside `#content`. Now in another file I want to use this style, but because it has of course also other styles that would overwrite the styles inside the other file I can not use `@import`. I am searching a solution to import only the styles of a nested selector inside a file. I can not merge those two files together, so that would not be a solution for me.

**Comment by lolmaus** [comment]
Etract the styles into a separate file, making them available either as an extend or a mixin. Then import the file into both original files and use the extend/mixin in them.

This is a graceful approach that solves your task. What you specifically ask for is very hackish and is not possible.

**Comment by julkue** [comment]
Well, thank you. That is a solution that will work, yes. But I think if nested selectors for `@extend` will be available, this would be no big feature. The usage could be like:
`@extend ['selectors': '#content ul', 'file': url]`.

A simple regex.

**Comment by lolmaus** [comment]
> But I think if nested selectors for @extend will be available...

Well, they're [not going to be](https://github.com/sass/sass/issues/1442).

**Comment by julkue** [comment]
As you can see there are more and more useful cases for this feature.
