### ISSUE TITLE
Are there any "starter" issues?

### ISSUE THREAD

**Issue by KatieK2** [sass/sass#1457]
Are there any "starter bugs" which would work well to introduce someone to how Sass works under the chassis? Or any quick fixes which just need a bit of attention? Highlighting these open issues can be a great way to get people involved with developing Sass.

**Comment by HamptonMakes** [comment]
Probably the best way to get started is to make SassSpec tests to demonstrate bugs that are reported. Just helping to get verification of the bugs and stuff and make sure that we can figure out affected versions. It’s a good way to get commits in. ;)

**Comment by nex3** [comment]
The [planned features](https://github.com/sass/sass/issues?q=is%3Aopen+is%3Aissue+label%3APlanned) might be a good place to look. Language features require a fair amount of cross-cutting work, which can be a pain but is certainly a good way to get a feel for the shape of the code.
