### ISSUE TITLE
Make it easy to investigate why a certain rule is created

### ISSUE THREAD

**Issue by BlackHC** [sass/sass#1458]
At the moment, it is not easily possible to determine why a certain CSS rule is output. You only see where the original in the SASS file is, but you don't know which @extend or @include call was responsible for it. 
For more complex hierarchies of %placeholders and @extends (and when using libraries or frameworks), it is really hard to figure this out manually. You essentially have to resort to commenting out parts of the code in turns to trace the instantiation flow.

Would it be possible to dump a stack trace for certain rules? Or maybe add a @probe statement that adds a watch to a SASS rule and prints information everytime it is instantiated?

Thanks,
 Andreas

**Comment by lolmaus** [comment]
The struggle is real!

Source map points to a mixin definition, giving no clue from where the mixin was invoked. Thus, debugging large codebases of old/foreign projects is a pain.

**Comment by nex3** [comment]
The sourcemap data actually does contain information about where each individual complex selector comes from, but unfortunately I don't think any browsers surface that information. Luckily, your `@probe` directive pretty much exists, in the form of `@warn`, which will print the full stack trace whenever it's run.

**Comment by BlackHC** [comment]
No, it does not!?
@warn just emits a line number and no full stack trace, even in Sass 3.4.5
(Selective Steve) with --trace and --debug-info. So what are you referring
to? This certainly does not solve my issue.

Thanks,
 Andreas

On Thu, Oct 2, 2014 at 12:17 AM, Natalie Weizenbaum <
notifications@github.com> wrote:

> The sourcemap data actually does contain information about where each
> individual complex selector comes from, but unfortunately I don't think any
> browsers surface that information. Luckily, your @probe directive pretty
> much exists, in the form of @warn, which will print the full stack trace
> whenever it's run.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/issues/1458#issuecomment-57550093.

## 

Why is this e-mail so short? Answer: five.sentenc.es.

**Comment by nex3** [comment]
Works for me:

```
$ ./bin/sass --version
Sass 3.4.2.46bb5d4 (Selective Steve)
$ cat test.scss
@mixin foo {
    @warn "warning";
}

@include foo;
$ ./bin/sass test.scss test.css
WARNING: warning
         on line 2 of test.scss, in `foo'
         from line 5 of test.scss
```

**Comment by BlackHC** [comment]
Sorry for not being more explicit! Your example is a very narrow case and does not cover @extends for example:

```
%a {
  @warn "hello";
  color: red;
}

nested {
    a {
      @warn "hello2";
      @extend %a;
    }
}
```

only prints:

```
blackhc$ scss --trace test.scss 
WARNING: hello
         on line 2 of test.scss

WARNING: hello2
         on line 8 of test.scss

nested a {
  color: red; }
```

which does not provide any information on how "nested a" came to be instantiated.
I would need to know that it originates from line 9 and line 1, for example.

Thanks,
 Andreas

**Comment by lolmaus** [comment]
@nex3, `@warn` only outputs a result of an evaluation. To use it, you have to know in advance where this evaluation is done in the code.

What we're asking for is the opposite: we see a line of resulting CSS and want to determine from what line of Sass source it originates from.

I had a situation where i needed that badly last week, with my own code. :sweat: I had overcomplicated things and had hard time debugging it without a way to trace CSS rules to Sass `@include` calls.

**Comment by nex3** [comment]
> What we're asking for is the opposite: we see a line of resulting CSS and want to determine from what line of Sass source it originates from.

This is what source maps or line comments are for.

**Comment by BlackHC** [comment]
So, what about my example? If this is too cumbersome for you, maybe we can
just have a short VC next week as you're also at Google if I see this
correctly :-)
Thanks,
Andreas
