### ISSUE TITLE
states using the parent selector (eg. [data-state="value"]& )

### ISSUE THREAD

**Issue by ianstormtaylor** [sass/sass#146]
I run into a lot of cases where I am deep in a nested selector, and I need to add a case for a state on the parent. Ideally that would be done like this:

`[data-state="value"]&`

(by placing the state on the other side of the parent selector), but that throws an error, and so I have to break out of the nesting and renest to the same level with the new state on the parent.

I think this would be a really nice addition to the language. (There might need to be some logic involved to put attribute selectors after class selectors after id selectors, as I thought I remember the ordering being important, but I might be wrong.)

What do you guys think?

**Comment by Dykam** [comment]
I encountered the same. It is already possible to prepend like `.parentClass &`, but a way to be more flexible with the provided selector would be nice. It would make sass mixins a lot more powerful than they are now.

**Comment by NoNoNo** [comment]
I propose some kind of `CONCAT` operator:

``` SCSS
A {
  .flag1 & {
    color: red;

    .flag2 CONCAT & {
      color: blue;
    }
  }
}
```

would be compiled to:

``` CSS
.flag1 A {
  color: red;
}
.flag2.flag1 A {
  color: blue;
}
```

I needed this so badly that I wrote a SASS post-processor routine in PHP:

``` php
<?php

  $sCSS = preg_replace_callback('/([^\\s}]+)\\s+CONCAT\\s+([^\\s{]+)/', function ($asMatches) {
    if (in_array($asMatches[2][0], array('.', '#', ':'))) {
      return $asMatches[1].$asMatches[2];
    }
    if (in_array($asMatches[1][0], array('.', '#', ':'))) {
      return $asMatches[2].$asMatches[1];
    }
    throw new Exception('Fatal SASS-Error! Illegal CONCAT: '.$asMatches[0]);
  }, $sCSS);
```

Thanks & greetings!

**Comment by jasonbouffard** [comment]
This is something that I too could use. For instance: when using the html5 boilerplate's html conditional tag for lt-ie8, lt-ie7, etc and modernizr's classes on the html tag.

**Comment by jasonbouffard** [comment]
While searching around for this have you guys seen this thread? http://groups.google.com/group/sass-lang/tree/browse_frm/month/2011-10/7bb5c901112bf961?rnum=11&_done=%2Fgroup%2Fsass-lang%2Fbrowse_frm%2Fmonth%2F2011-10%3F#doc_0ce775bae679b536

**Comment by chriseppstein** [comment]
#286 will address this use case.
