### ISSUE TITLE
Fail to pass 8symbols HEX colour value for IE lt 9 transparency

### ISSUE THREAD

**Issue by viksok** [sass/sass#1461]
FilterError: sass: subprocess had error: stderr=Syntax error: Colors must have either three or six digits: '#FF32363b'

filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#$hex-start', endColorstr='#$hex-stop',GradientType=1 ) 

Passed values: #00000000, #FF272a2e
Where 00 means transparent, and FF means opaque

**Comment by cimmanon** [comment]
Sass has a function specifically for this purpose [`ie-hex-str($color)`](http://sass-lang.com/documentation/Sass/Script/Functions.html#ie_hex_str-instance_method) (meaning you'll need to pass in a valid color, not an 8 character hex color value).
