### ISSUE TITLE
@at-root documentation error

### ISSUE THREAD

**Issue by jemandy** [sass/sass#1462]
According to http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html , the scss fragnent

```
.parent {
    @at-root .child { ... }
}
```

complies to 

```
.parent { ... }
```

However Sass actually complies it to

```
.child { ... }
```

If I understand @at-root correctly, Sass behavior is correct and the documentation is wrong.

**Comment by HamptonMakes** [comment]
Reading the documentation, I believe it's assuming there are attributes on the .parent { }, since the indicated output is:

```
.parent { ... }

.child1 { ... }
.child2 { ... }
```

A way to clarify that would be to put "..." in the .parent Sass block so that it shows that _with_ attributes this happens.

**Comment by HamptonMakes** [comment]
Oh wait, I was misreading. It says "These produce, respectively:"... this is just confusingly written. Let me take a crack at it.
