### ISSUE TITLE
@each variables in multiline comments are parsed

### ISSUE THREAD

**Issue by malrase** [sass/sass#1465]
We're trying to track down the source of this issue in libsass: 
https://github.com/sass/libsass/issues/424

We found that Ruby Sass 3.4 gives a "no variable" error if an @each variable is used within a multiline comment. 

```
/*@each $header, $size in (h1: 2em, h2: 1.5em, h3: 1.2em) {
    #{$header} {
        font-size: $size;
    }
}*/
```

See gist here:
http://sassmeister.com/gist/0277dd12d32a99cd97fd

If you define $header above the comment, there is no error.

**Comment by HamptonMakes** [comment]
The `/*@` isn't required. You can add lots of spacing or newlines before the `@each` and it still happens.

**Comment by lolmaus** [comment]
This issue is raised every month or so.

This behavior is intentional. Interpolation `#{...}` does work in block comments because you might want to emit comments with variables, for various purposes: debugging, documenting, etc.

**Comment by HamptonMakes** [comment]
Goddamnit. I didn't see the interpolation inside the block. Ugh. #fail

**Comment by HamptonMakes** [comment]
And, btw, it's not properly explained in Sass' documentation. We should probably mention it more clearly there!

**Comment by am11** [comment]
@lolmaus, as discussed at https://github.com/sass/libsass/issues/424; if there is an issue in multi-line comment, wouldn't it be nice to raise a warning instead of syntax error? Something like:

```
Warning: Unbound variable in multi-line comment at line X, column Y in <file>.scss. 
         Did you mean to use single-line comment?
```

(if this is something pursuable, should it be reported at separate issue or reopening this issue be a good idea).

Thanks @hcatlin! :)

**Comment by lolmaus** [comment]
Sass might be resolving interpolation before it knows whether it's a block comment. We should wait for @nex3 to comment on this.

**Comment by chriseppstein** [comment]
Interpolation is evaluated in all CSS comments now. This was addressed as a "bug fix" and it seems like the reference documentation needs updating.
