### ISSUE TITLE
Sass Cache error message

### ISSUE THREAD

**Issue by whoshallsucceed** [sass/sass#147]
The issue revealed in SASS-Rails repository seems still alive. As said in this issue (https://github.com/rails/sass-rails/issues/5), it seems related to SASS, so I re-report the issue here.

I just get the warning:

```
Warning. Error encountered while saving a Sass::Tree::RootNode to cache /Users/adrien/Sites/playboy/tmp/sass-cache/dd88a41ae6a72174d9ee01082a8943cbb11b7ec3/menu.css.sassc: can't dump anonymous class #<Class:0x00000103b6d1c8>
```

I checked if this warning was _real_:

```
$ ls -la tmp/sass-cache/dd88a41ae6a72174d9ee01082a8943cbb11b7ec3/
drwxrwxr-x  3 adrien  staff   102 Aug  1 16:52 .
drwxrwxr-x  5 adrien  staff   170 Aug  1 16:52 ..
-rw-rw-r--  1 adrien  staff  1262 Aug  1 16:52 notifications.css.sassc
```

So, I guess **yes**. Any solution?

FYI :

```
* sass (3.1.5)
* sass-rails (3.1.0.rc.5)
* sprockets (2.0.0.beta.10)
* rails (3.1.0.rc4)
* railties (3.1.0.rc4)
```

**Comment by wakiki** [comment]
+1 - we are getting the same error with

rails 3.1.0.rc5
sass', '3.1.5'
sass-rails', "~> 3.1.0.rc"

Warning. Error encountered while saving a Sass::Tree::RootNode to cache \* can't dump anonymous class *

**Comment by amay** [comment]
+1 - same error

Warning. Error encountered while saving a Sass::Tree::RootNode to cache .../_base.css.sassc: can't dump anonymous class #Class:0x00000100caecb0

rails (3.1.0.rc5)
sass (= 3.1.5)
sass-rails (3.1.0.rc5)

**Comment by amay** [comment]
Some more info from digging into the commit history:

The original issue (https://github.com/rails/sass-rails/issues/5) was closed because of this commit: https://github.com/nex3/sass/commit/e813a76afbf383cec40f6ebb9fda2e6d91b2956f, which was contributed as part of sass 3.1.4. Then in sass 3.1.6, that commit was reverted. No additional comment is provided, so not sure why the revert occurred.  I rolled back to version 3.1.4 to see if that would fix the issue, but it did not.

**Comment by amay** [comment]
Some more information. This only appears to occur when I'm declaring my own compass mixins. Strangely, no error occurs if the mixin has no arguments, but once there are arguments, I get the dump error.

**Comment by amay** [comment]
And when I debug in lib/sass/cache_stores/base.rb, and try to print out obj, I get this error: "can't convert String into Array"

**Comment by whoshallsucceed** [comment]
Yeah. I just got the warning when using variables without any mixins. So it seems the problem just comes from variables.

**Comment by olivierlacan** [comment]
Facing the same issue, any news?

**Comment by digitalplaywright** [comment]
This problem is also happening for me, but only in production on heroku.

**Comment by chriseppstein** [comment]
@nex3 can you comment?

**Comment by nex3** [comment]
At a guess, it looks like the problem here is that some non-serializable object is getting put into the options hash. As of 947e8cfc6bc31a7f39933a5d4035f6da75dcb5d1, the cache store is no longer storing the full options hash, so this should be fixed now.
