### ISSUE TITLE
Sass darken should accept null argument

### ISSUE THREAD

**Issue by stubbornella** [sass/sass#1470]
My team and I are interested in making darken accept a null argument. We'd like to see it return nothing if null is passed, and like Sass does for null variables, remove the property value pair from the selector. We use bootstrap for our front end and this would allow us to return less code for values we don't want to set.

We currently get this error:

```
error src/pivotal-ui/pivotal-ui.scss (Line 17 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_buttons.scss: $color: null is not a color for `darken')
```

Would you be open to a PR?

Thanks,

@stubbornella & @gpleiss

**Comment by nex3** [comment]
I'm pretty reticent to add this; it's dissimilar to how other functions work both in Sass and in other languages, and I think it would be surprising for most users who saw it. It would also make it much harder for users who didn't intend to pass null to track down what's going on.

This behavior also isn't too hard to get without modifying the existing behavior: the way `and` works in Sass, you could write `$color and darken($color)` and get the same effect.
