### ISSUE TITLE
Improve @import with namespace-like functionality

### ISSUE THREAD

**Issue by fnky** [sass/sass#1472]
I'd love to have a way to import multiple files from a folder without repeating myself and also be able to move my imports around fast and efficient.

Currently you've to specify a relative path for each import

``` scss
@import 'base/scaffolding',
        'base/typography',
        ...
```

This becomes very repetitive when you have a large folder structure. The [`sass-globbing`](https://github.com/chriseppstein/sass-globbing) gem can help with this, but doesn't allow for control for which Sass files to include or in which order.

I've come up with a rough idea how `@import` could look like to import from folders – adding functionality for easy globbing aswell – this should also support the current `@import` syntax.

``` scss
@import (
  'scaffolding',
  'typography'
) from 'base';

@import (
  'header',
  'footer',
  'list',
  'media',
  'box',
  'button'
) from 'components';

@import (
  'mixins/*',
  ('button', 'font-icon') from 'extends',
  'functions/*',
  'variables'
) from 'generic';

@import '*' from 'states';
```

The `from` keyword determines which directory to import the list of files from.

**Comment by stephnr** [comment]
:+1: Definitely a feature worth building

**Comment by Snugug** [comment]
Duplicate of https://github.com/sass/sass/issues/1094

**Comment by fnky** [comment]
@Snugug Could you explain as why this is a duplicate? As I see it #1094 is a compilation of `@import` related issues but it doesn't contain any ideas as explained above.

**Comment by Snugug** [comment]
3rd item down **Import Directory**, 4th item down, **Namespaces and Aliases**.

**Comment by fnky** [comment]
As I understand it, that will import all files (just like globbing would) with no control of order and which files to be imported. As I describe above, I would like to get more control over which files I import and which order, as that can be important.

**Comment by Snugug** [comment]
> If "foo" is a folder than it tries to import "foo/_module.scss"

You'd specify which files you'd like to import (and in what order) in `_module.scss` (or something similar) and then just do `@import "foo";`

**Comment by fnky** [comment]
I see. However, what if I would like to keep all my imports single file (e.g. styles.scss)?

**Comment by Snugug** [comment]
That proposal won't help you if you only ever import from a single file; however #1094 also includes **Import Once** which removes the issue of duplicating a file's contents when importing (as each file will only be imported once) which is usually why someone would do that. Most would consider it a best practice for partials to be able to specify exactly what they rely upon and not rely exclusively upon the import cascade for anything non-trivial, and **Import Once** will allow us to do just that. Especially with the usecase you've provided, creating a `base` folder, a `components` folder, those seem like logical groupings that should define their dependencies and be provided as chunks.

If at that point you still only want to import from a single file, it becomes a purely stylistic choice.

**Comment by nex3** [comment]
I'm not interested in adding extra syntax to save a few characters of typing.
