### ISSUE TITLE
SASS 3.4.5 --watch not working on Windows

### ISSUE THREAD

**Issue by eliorivero** [sass/sass#1475]
Similar to #1469 when loading sass the first time, it writes the corresponding css and css.map but any changes done afterwards to the scss file are not reflected.

Tested on Windows 7, Ruby 1.9.3p545 no other gems installed.

**Comment by RanjithRana** [comment]
install compass gems and then use this command ----> compass --watch

**Comment by eliorivero** [comment]
Just uninstalled 3.4.5 and installed 3.4.4 and it works correctly. Version 3.4.3 (the one I was using before updating) also works.

**Comment by RanjithRana** [comment]
ok..

**Comment by nex3** [comment]
What are the contents of the SCSS file you're watching? What are the paths to the files in question? Is there anything weird like different drives or network shares going on? What is the specific command line invocation you're using?

**Comment by eliorivero** [comment]
I can't provide you the content of the file I'm working on, but is a simple one where all I'm using is nesting and & in multiple classes concatenated, nothing odd.

Different drives, yes, all in same computer.

Command line is just watch, with style expanded and precision 10.

**Comment by nex3** [comment]
Does you file use any `@import`s? Can you post the exact command-line invocation you're using to start the watch?
