### ISSUE TITLE
Add percentage to color function invert 

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#1477]
It would be nice to have native support for invert percentage 
(like filters: http://dev.w3.org/fxtf/filters/#funcdef-invert)

As demonstrated by Ana Tudor it is possible to create this by hand: 
Example 1: http://codepen.io/thebabydino/details/gJuaL/
Example 2: http://codepen.io/jakob-e/pen/JlFfr

``` SCSS
    invert($color, $percentage:100%)

```

**Comment by KittyGiraudel** [comment]
Adding a default value of `100%` would prevent any API break.

**Comment by whaaaley** [comment]
I like it, but I was just thinking it wouldn't need to be as complex like in the examples. You could just use `invert()` in combination with `mix()` with the original non-inverted color and it would have the same result.

```
@function invert-pct( $color, $percent: 100% ) {
    $percent: 100% - $percent;
    @return mix( $color, invert( $color ), $percent );
}
```

I forked your example and replaced it with my function: http://codepen.io/dustindowell22/pen/dstwp

**Comment by jakob-e** [comment]
@dustindowell22 Quite clever :+1: 
@HugoGiraudel My thought too

**Comment by jshawl** [comment]
@dustindowell22 @HugoGiraudel @jakob-e 

I've implemented the optional percentage in the above pull request, but am noticing only slightly different values from @dustindowell22's implementation. 

https://github.com/jshawl/sass-invert-tests

**Comment by whaaaley** [comment]
@jshawl Looking over your code and doing some quick math, wouldn't 255 need to be 256 instead? If we're inverting colors we'd go from 0-255 to 1-256, and then subtract from that.

**Comment by jshawl** [comment]
@dustindowell22 nvm! I implemented your solution, in ruby! Just calls the mix method with a percentage (defaults to 100% if none given)
