### ISSUE TITLE
Incorrectly optimized @extend

### ISSUE THREAD

**Issue by beliarh** [sass/sass#1479]
A similar problem: https://github.com/sass/sass/issues/1414

> It's optimized out because it's a subselector of .something:hover. That is, everything that matches .something-else .something:hover matches .something:hover as well.

But I have to use child selector in my project

``` scss
%lvl1_button {
    /* lvl1 button styles ... */

    &:hover { /* :hover styles ... */ }
    &.disabled { /* .disabled styles ... */ }
}

.menu {
    > .button,
    > .submenu > .button { // .submenu just a wrapper
        @extend %lvl1_button;
    }
}
```

And it compiles to

``` css
.menu > .button,
.menu > .submenu > .button {
  /* lvl1 button styles ... */
}
.menu > .button:hover {
  /* :hover styles ... */
}
.menu > .disabled.button {
  /* .disabled styles ... */
}
```

As we can see this code is optimized incorrectly.
**.menu > .button !== .menu > .submenu > .button**
Expected output in this case

``` css
.menu > .button,
.menu > .submenu > .button {
  /* lvl1 button styles ... */
}
.menu > .button:hover,
.menu > .submenu > .button:hover {
  /* :hover styles ... */
}
.menu > .disabled.button,
.menu > .submenu > .disabled.button {
  /* .disabled styles ... */
}
```

**Comment by whaaaley** [comment]
I'm pretty sure Sass is working correctly. `.menu > .disabled.button` and `.menu > .submenu > .disabled.button` are targeting the same element and applying the same styles so they get optimized and the more specific selector gets removed. Both of your compiles should behave the same.

**Comment by beliarh** [comment]
More complex example:
http://jsfiddle.net/72800sj5/ (works; `@mixin` instead of `@extend`)
http://jsfiddle.net/1g10z6b4/ (does not work; styles compiled localy using latest version of sass, just replaced `@mixin` with `%` and `@include` with `@extend %`; probably there are an older sass version on jsfiddle, that cannot compile styles correctly)

From http://www.w3.org/TR/CSS2/cascade.html#cascading-order

> To find the value for an element/property combination, user agents must apply the following sorting order:
> 1. Find all declarations that apply to the element and property in question, for the target media type. **Declarations apply if the associated selector matches the element in question** and the target medium matches the media list on all `@media` rules containing the declaration and on all links on the path through which the style sheet was reached.
> 2. Sort according to importance (normal or important) and origin (author, user, or user agent). In ascending order of precedence:
>    1. user agent declarations
>    2. user normal declarations
>    3. author normal declarations
>    4. author important declarations
>    5. user important declarations
> 3. Sort rules with the same importance and origin by specificity of selector: more specific selectors will override more general ones. Pseudo-elements and pseudo-classes are counted as normal elements and classes, respectively.
> 4. Finally, sort by order specified: if two declarations have the same weight, origin and specificity, the latter specified wins. Declarations in imported style sheets are considered to be before any declarations in the style sheet itself.

In case of simple nested selectors
**.menu .button ==  .menu .submenu .button**: `.button` is subselector of `.menu` in both selectors, so we can remove the second. That optimization is correct.

But in case of child selectors
**.menu > .button !==  .menu > .submenu > .button**: selectors are different and they matches different elements (but .menu > .button == .menu > .submenu > .button <=> (iff) .submenu has .menu class). Sass mustn't optimize that code.

**Comment by whaaaley** [comment]
I see now, sorry about that. Yup. You're definitely right.
