### ISSUE TITLE
Add inline sourcemap support

### ISSUE THREAD

**Issue by enyo** [sass/sass#1484]
Some users want to use sourcemaps in development without creating any additional files, or even entirely over stdin/stdout. We should add an additional sourcemap type (`in-css`? `base64`? `super-inline`?) that does this.

**Edited by @nex3 to retarget the issue. Previous report below:**

I can't find any possibility to get the sourcemap without having to write both, the compiled `.css` and the sourcemap file to disk.

I am looking for something like:

``` bash
$ sass --sourcemap-only style.scss
```

which would output the sourcemap instead of the compiled `.css`.

This is relevant when writing transformers in certain frameworks since they only work in memory.

**Comment by nex3** [comment]
Just delete the sourcemap after it's written.

**Comment by enyo** [comment]
As I said, I'm not writing the files to disk, but just pipe the output through, since it's used in a chain of transformers. 
Temporarily writing the output somewhere, reading the source map file and deleting the two generated files on the disk is a very ugly and hackish workaround.

**Comment by nex3** [comment]
`sass` is a command-line application; it works with the filesystem. It's not unreasonable to interact with it using the filesystem.

**Comment by enyo** [comment]
Precisely. `sass` is a command-line application, and as such it should be able to work with `stdin` and `stdout` as nearly any other command-line application does. Even programs that output binary files (like `zip`) do output the result in `stdout`. Actually... I can't think of many scripts (apart from `sass`) that aren't able to do that.

**EDIT**: Sorry. That may have come off a bit presumptuous. If you don't want to implement my request, it's obviously your choice and I'll find a workaround. It being a command-line application is the reason I'd love that feature though. It will allow me to use it as I'd love using it, instead of having to implement a hack for it.

**Comment by nex3** [comment]
`sass` works on standard IO by default: if you just run `sass` with no other arguments, it will read Sass code from standard input and emit it on standard output. But that doesn't work with sourcemaps, because sourcemaps need to know the location of files on disk.

**Comment by enyo** [comment]
Ok. That's a good point that sourcemaps map to files on disk, which is why they require interaction with a filesystem. My use case was fairly simple, but I can see how that could become quite complex to implement, and require a few additional parameters to work properly.
I will work around it then.
Thanks for your work on Sass.

**Comment by robwierzbowski** [comment]
Part of the sourcemap spec describes inline sourcemaps, where the sourcemap includes the source and is then base 64'd into the sourcemap comment in the result file. See gulp-sourcemaps default for an example. stdin/out sass compilation could include sourcemaps using that pattern.

**Comment by nex3** [comment]
@robwierzbowski That presents size issues for the resulting CSS document. I don't think most users would want a gigantic base64 comments in the stylesheet that everyone downloads.

**Comment by robwierzbowski** [comment]
Well you wouldn't want to create sourcemaps for production assets. I think
that's a case of knowing how to use your tools.

On Friday, October 31, 2014, Natalie Weizenbaum notifications@github.com
wrote:

> @robwierzbowski https://github.com/robwierzbowski That presents size
> issues for the resulting CSS document. I don't think most users would want
> a gigantic base64 comments in the stylesheet that everyone downloads.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/issues/1484#issuecomment-61329855.

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by Arcovion** [comment]
Inline sourcemaps would be great, Middleman & Jekyll lack support for sourcemaps on their preview servers currently and Sprockets sourcemap support was pushed back to v4.0 which is ages away.
Adding this feature could streamline things as there'd be nothing to link or support, it's all embedded in a single file.
As mentioned this should just be for development - it's the build tools' responsibility to enable sourcemaps.

**Comment by nex3** [comment]
Okay, I'll reopen this and retarget it to adding an option for in-CSS sourcemaps.

**Comment by Arcovion** [comment]
Less appears to support this too via [`lessc --source-map-map-inline`](http://lesscss.org/usage/#command-line-usage-options)

**Comment by enyo** [comment]
Great. That would solve my problem.

**Comment by sassanh** [comment]
+1

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
