### ISSUE TITLE
Sourcemap sources are different between default, auto, and inline

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#1485]
The docs say there are three valid sourcemap values:
- `auto`: relative paths to the source, or absolute file protocol paths if relative isn't available
- `inline`: source is inline, says nothing about file paths
- `file`: always absolute file protocol paths

I would assume `auto` is the default, but running with no sourcemap argument gives me paths relative to the running sass process. `inline` does the same. Example:

`auto`: 

```
// these paths are crazy but correct — I'm compiling to a tmp directory.

sources: 
   [ '../../../../../../Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/_partial-1.scss',
     '../../../../../../Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/fixture-a.scss',
     '../../../../../../Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/_obj-1.scss',
     '../../../../../../Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/component/_obj-2.scss' ],
```

`file`:

```
sources: 
   [ 'file:///Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/_partial-1.scss',
     'file:///Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/fixture-a.scss',
     'file:///Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/_obj-1.scss',
     'file:///Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source/component/_obj-2.scss' ],
```

`inline` or default:

```
sources: 
   [ 'fixture/source/_partial-1.scss',
     'fixture/source/fixture-a.scss',
     'fixture/source/_obj-1.scss',
     'fixture/source/component/_obj-2.scss' ],
```

Two takeaways:
1. I think default should behave like auto, or if there's a purpose for relative-to-the-process source paths it should be documented and its own option. 
2. I'm not sure what the spec says, but should `inline` have sources at all?

**Comment by nex3** [comment]
> I think default should behave like auto, or if there's a purpose for relative-to-the-process source paths it should be documented and its own option.

The default should definitely be `auto`. I can't reproduce a case where specifying `--sourcemap=auto` has different results than not specifying `--sourcemap` at all; can you give me more details about your compilation locations and the locations of your libraries when this happened?

> I'm not sure what the spec says, but should `inline` have sources at all?

Yes; the browser (or other sourcemap viewer) still needs to have some sort of name to show for the files, even though it has the content of those files inline. Since these names don't need to be used to find files on disk, Sass formats them in the most user-friendly way possible.

**Comment by robwierzbowski** [comment]
Thanks for the quick response and explanation.

Ah, while I was writing down reproduce info I found where I was setting a default of `inline` in my code. All works perfectly, sorry for the static, thanks Natalie!
