### ISSUE TITLE
Is there an equivalent to `append` for maps?

### ISSUE THREAD

**Issue by LandonSchropp** [sass/sass#1488]
I'd like to add a key-value pair to a map dynamically. With a list, I can add a value like this:

```
$list: ("one", "two", "three")
$list: append($list, "four")
```

It'd be nice if it worked the same way for a map. I noticed there's a `map-get` function, but there doesn't seem to be `map-set` or `map-append` functions. Ideally, I'd be able to do this:

```
$map: (one: 1, two: 2, three: 3)
$map: map-set($map, four, 4)
```

When I tried to use `append` for the map, it returned a list of lists, which doesn't work with the other map functions.

**Comment by Snugug** [comment]
The function you're looking for is map merge

http://sass-lang.com/documentation/Sass/Script/Functions.html#map_merge-instance_method

**Comment by LandonSchropp** [comment]
Ahh, I get it now. Thanks!
