### ISSUE TITLE
Compiling Ionic SCSS fails with SASS version 3.4.6, doesn't with 3.3.7

### ISSUE THREAD

**Issue by harsaharsa** [sass/sass#1494]
Trying to compile [Ionic v1.0.0-beta.13](https://github.com/driftyco/ionic/releases/tag/v1.0.0-beta.13) SCSS via the grunt-contrib-sass task fails with SASS version 3.4.6. Doesn't fail with 3.4.5 or any previous version, so it's a bug with 3.4.6.

The error I get is:

```
File dist/components/ionic/scss/ionicons/ionicons.css created.
NoMethodError: undefined method `specificity' for [:not(.pulling-rotation-disabled)]:Array
```

Haven't looked deeper into what's happening, but what could be the reason here?

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1476
