### ISSUE TITLE
Warn on mixin redefinition

### ISSUE THREAD

**Issue by aaronpanch** [sass/sass#1497]
Currently, when there are multiple mixins with the same name, the mixin defined later wins. This is fine, but it would be nice to get a warning when this happens so as to avoid accidental redefinitions. This is especially a problem when including multiple mixin libraries. Perhaps this could be an option, because I'm sure plenty of people are doing this intentionally as well.

**Comment by nex3** [comment]
It's too likely that people are doing this intentionally to warn about it, and I don't like adding options. When `@use` comes along, that'll make this a lot harder to do accidentally.
