### ISSUE TITLE
Duplicate keys in maps

### ISSUE THREAD

**Issue by azinasili** [sass/sass#1498]
It seems that SASS throws an error when there are duplicate keys in a map. I usually put styles into a map and then use a function to print those styles for me. However I ran into this problem when using transitions in maps. I can't comma separate the styles since the map thinks it is a new property and I can't add a new property with a different value since SASS fails with duplicate keys.

**This fails on build**

``` css
$map: (
  transition: background 1s ease, color 1s ease
);
```

**This also fails**

``` css
$map: (
  transition: background 1s ease,
  transition: color 1s ease
);
```

Is there a work around this without redoing my workflow?

**Comment by Snugug** [comment]
Wrap your comma-separated properties in parenthesis `()` to tell Sass it's a list, not a new key.

``` scss
$map: (
  transition: (background 1s ease, color 1s ease)
);
```

http://sassmeister.com/gist/e38e93d85b4ea0ab9eb7

**Comment by azinasili** [comment]
Aha! Didn't even think about this. Thanks!
