### ISSUE TITLE
feature: allow attributes to be written using escaped variables

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#150]
Allowing attributes to be written within mixins can help clean a few things up when writing code. Currently vendor prefixes need to be written out for every vendor-prefixed attribute.

``` sass
=prefix($attribute, $value)
  -webkit-#{$attribute}: $value
  -moz-#{$attribute}: $value
  -ms-#{$attribute}: $value
  -o-#{$attribute}: $value
  #{$attribute}: $value

+prefix(box-shadow, 2px 0 5px #000)
```

Or some more complex math that can apply to a verity of attributes:

``` sass
$golden: 1.618
$thirds: 3 / 2
$fourths: 4 / 3

=modular-scale($attribute, $value, $ratio, $multiple)
  $modular-scale: $value
  @for $i from 1 through $multiple
    $modular-scale: $modular-scale * $ratio
  #{$attribute}: $modular-scale

.foo
  +modular-scale(width, 12px, $golden, 6)
```

**Comment by nex3** [comment]
I'm not sure what you're suggesting... can you give an example?

**Comment by scottkellum** [comment]
I gave examples of the feature in use. I want to write CSS attributes with variables. Currently the following code will result in an error:
'''sass
-webkit-#{$foo}: $bar
'''

**Comment by nex3** [comment]
This already works, and has worked for quite a while.
