### ISSUE TITLE
--cache-location and --no-cache still create .sass-cache in pwd

### ISSUE THREAD

**Issue by Profpatsch** [sass/sass#1500]
I’m running a command like this:

```
GEM_HOME=tmp tmp/bin/sass  --cache-location=tmp    -Itmp/bower/bootstrap-sass-official/assets/stylesheets/  --watch app/sass:app/static 2>&1
```

and sass creates its cache folders in `pwd` as well as `tmp` (they are duplicated (!)).

Furthermore, `--no-cache` still creates `.sass-cache` in `pwd`. These two seem broken in that `.sass-cache` is created in any case.

**Comment by nex3** [comment]
I can't reproduce this. What versions of Sass and Ruby are you using?

**Comment by Profpatsch** [comment]
Hm, it seems to have stopped now. Gonna reopen if it happens again.
