### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by maraisr** [sass/sass#1507]
Ever since the 3.4.7 update I'm getting this error each time I run a sass build. Via Grunt and or directly. If I downgrade to 3.4.6 it works just fine.

**Comment by nex3** [comment]
Please provide more details. What command-line invocation are you passing Sass? What do your Sass files look like? What version of Ruby are you using? What's your OS? What's the output when you run Sass with `--trace`?

**Comment by maraisr** [comment]
It now looks to only be via Grunt... The command is

sass assets/scss/website.scss tmp/css/website.pre.css --style compressed --unix-newlines --require susy --require breakpoint

If i run that, then it works, but that exact same command through Grunt fails... 

Ruby: ruby 1.9.3p545
Sass: Sass 3.4.7
OS: Windows 7 64bit

**Comment by nex3** [comment]
Without a way to reproduce this or at least a stack trace, there's not much I can do about it. If you find a way to reproduce this consistently, post here and I'll re-open the issue.
