### ISSUE TITLE
Remove the % symbol when the value is zero

### ISSUE THREAD

**Issue by alexpacklink** [sass/sass#1508]
Using the percentage() mixin, if it is passed a zero value, the function returns 0%. This launches errors in linter libraries like CSSLint to check code quality.

It is easy to find a workaround when you are treating with your own code but not if you use, for example, the Official Bootstrap SASS port. Only with the grid, you will receive 4 errors due to the 0% value.

It would be a great help to maintain the code as good as possible.

Thx

**Comment by nex3** [comment]
Removing a unit where one is expected will screw with unit arithmetic in very bad ways.

**Comment by cimmanon** [comment]
In the context of Flexbox, the unit matters.  While it is unlikely for someone to want to write this, the following code:

``` css
.foo {
    flex: 1 0;
}
```

is very different from this:

``` css
.foo {
    flex: 1 0%;
}
```
