### ISSUE TITLE
Documentation suggestion: Recommend using bundler for version and dependency mgmt

### ISSUE THREAD

**Issue by Josh68** [sass/sass#1513]
Not sure this is the place to make such a suggestion, but here goes. I pretty much only have a Ruby environment on my Windows machine for using SASS with Compass. I've done one project with Middleman, which had a skeleton that included bundler, and am now working with Grunt.

Only just today did I realize just how important bundler is in managing multiple projects with SASS and Compass, to keep different versions of the those gems and various plugins in sync. And I didn't realize I could use bundler to provide a base for my Grunt tasks (e.g., "bundle exec grunt server" or "bundleExec: true" in my Gruntfile Compass config).

I find it odd that the use of bundler isn't mentioned in basic SASS or Compass documentation, since it seems fundamental for any developer using them (I have not tried using an environment without Ruby and relying on libsass, but that would leave me without Compass, for now). I'd be happy to try to contribute to the documentation, but am not sure I know enough to do that responsibly.

Thanks for all of your work. Love SASS.

**Comment by nex3** [comment]
I think this is out of scope for the core Sass docs, but you could suggest it on the [Sass site repo](/sass/sass-site/issues).

**Comment by Josh68** [comment]
Thanks for the suggestion.
