### ISSUE TITLE
SASS doesn't watch changes in VMware shared folder

### ISSUE THREAD

**Issue by kargapoltsev** [sass/sass#1516]
I installed Ubuntu Server as a guest on VMware (Windows host). And I setting up a shared folder. And now I want to use SASS on Ubuntu, but it doesn't watch the changes in the shared folder on the host made. 
If I load files through SFTP, compass work brilliantly.

There is way to force SASS to watch changes?

**Comment by nex3** [comment]
If you pass `--poll`, it won't try to use the native filesystem watching at all, which should work here.
