### ISSUE TITLE
Glob importing native feature?

### ISSUE THREAD

**Issue by gespinha** [sass/sass#1517]
Hi there,

Is glob importing planned for the near future? I don't want to rely on gems to do this.

Thanks in advance!

**Comment by nex3** [comment]
No. Sass, like CSS, is an order-sensitive language, and glob-based imports make the ordering of imports unclear and fragile. This is a recipe for accidentally introducing subtle bugs that are hard to track down or even notice.

**Comment by dbox** [comment]
It's utility would greatly outweigh those who don't understand how it should be used. 

Very much in favor of having this feature.

**Comment by arxpoetica** [comment]
FYI: https://github.com/rails/sass-rails#glob-imports

**Comment by ghost** [comment]
@nex3 We can figure out the order!
Stylus manages globbing internally and does it well. And it can throws error like a pinpoint. This is the most empty feature blocking reason. 
Reading couple of your issues and seems like this is your regular routine. 
You have a new nickname, "feature blocker without any valid reason". 
Now i understand why sass sucks. I will remove it from my project and never use it again. F... Imbec...
