### ISSUE TITLE
Emit a warning or error if there is a @import url() after sass imports

### ISSUE THREAD

**Issue by brauliobo** [sass/sass#1524]
If I do

``` scss
@import 'partial';
@import url('../style');
```

Then sass will put the `@import url` will appear before the imported partial's styles, **changing the precedence order**.

So the developers must be warning or even an error must be raise, because the precedence order is very important.

**Comment by nex3** [comment]
CSS requires that `@import` statements appear before anything else in a stylesheet (other than `@charset` declarations, I guess). We can't really throw an error for that case, because that breaks the ability for partials to declare CSS imports that they use (e.g. for loading font stylesheets).

**Comment by brauliobo** [comment]
What about a warning??

**Comment by cimmanon** [comment]
A warning would be rather annoying for anyone who is happily taking advantage of Sass doing the right thing here.
