### ISSUE TITLE
Properly handle alpha units

### ISSUE THREAD

**Issue by nex3** [sass/sass#1525]
- [x] [Specs](https://github.com/sass/sass-spec/pull/1291)
- [x] Dart Sass
- [x] [Documentation](https://github.com/sass/sass-site/commit/fc34fe4b)
- [ ] [LibSass](https://github.com/sass/libsass/issues/2719)
- [x] [Ruby Sass](https://github.com/sass/ruby-sass/issues/80)

---

Currently `rgba()` and `hsla()` completely ignore units on the `$alpha` argument. They should interpret percentages [per spec](http://dev.w3.org/csswg/css-color/#typedef-alpha-value) and fail for any other unit.

**Comment by nex3** [comment]
This is handled correctly by Dart Sass, but it looks like [it's still marked as TODO](https://github.com/sass/sass-spec/blob/master/spec/libsass-todo-tests/color-functions/opacity/opacity/input.scss) for LibSass.

@xzyfer Is there an issue tracking this on the LibSass side yet?

**Comment by prakhar-pal** [comment]
The spec at [http://dev.w3.org/csswg/css-color/#typedef-alpha-value](http://dev.w3.org/csswg/css-color/#typedef-alpha-value) says that percentages(0-100%) and number(0-1) are allowed for alpha argument.
My understanding from issue description is that it should fail when anything other than % are given as argument. So,
`.card{
      color: rgba(255,255,255,0.5);
}`
should fail, but
`.card{
     color: rgba(255,255,255,50%);
}`
should pass? Kindly clarify.

**Comment by nex3** [comment]
@lawki These functions are intended to allow unitless numbers between 0 and 1 as well.

**Comment by prakhar-pal** [comment]
Got it, thanks.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
