### ISSUE TITLE
Single file compile not creating directories (expected?)

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#1528]
When I run 

```
sass fixture/my-file.scss result/my-file.css
```

if the directory `result` doesn't exist I get the error:

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:182:in `initialize': No such file or directory - result/my-file.css (Errno::ENOENT)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:182:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:182:in `open_file'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:171:in `write_output'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/sass_scss.rb:397:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/sass_scss.rb:62:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:52:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/lib/sass/exec/base.rb:19:in `parse!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.7/bin/sass:13:in `<top (required)>'
    from /usr/bin/sass:23:in `load'
    from /usr/bin/sass:23:in `<main>'
```

Is this expected? Sass creates directories with `--update` and compiles fine if the directory exists. I think I would have noticed this earlier, so I may be doing something wrong. Using Sass 3.4.7 (Selective Steve).

**Comment by robwierzbowski** [comment]
Checked with 3.3, same error.

**Comment by nex3** [comment]
Yes, this is expected. Sass follows other UNIX commands in this regard; you'll see the same behavior with `cp`, for example.

`--update` works differently because it's often responsible for recreating an entire directory tree.

**Comment by robwierzbowski** [comment]
Ok, thanks! Just wanted to make sure I wasn't doing something wrong.

On Tuesday, November 18, 2014, Natalie Weizenbaum notifications@github.com
wrote:

> Yes, this is expected. Sass follows other UNIX commands in this regard;
> you'll see the same behavior with cp, for example.
> 
> --update works differently because it's often responsible for recreating
> an entire directory tree.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/issues/1528#issuecomment-63543984.

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by nex3** [comment]
@robwierzbowski I think you posted that in the wrong thread

**Comment by robwierzbowski** [comment]
True true. Thanks.
