### ISSUE TITLE
add option to simplify generated css of nested #id

### ISSUE THREAD

**Issue by pgherveou** [sass/sass#153]
Hello there
as #id are supposed to be unique inside a page what do you think about 
transforming this scss 
# id-1 {

```
 font-size: 14px;
 #id-2 {font-size: 12px; }
```

}

to this css
# id-1 { font-size: 14px;}
# id-2 {font-size: 12px; }

instead of the current
# id-1 { font-size: 14px;}
# id -1 #id-2 {font-size: 12px; }

Currently I remove the nesting to simplify generated css
but it would be interesting to be able to keep elements nested just to keep the scss organised

**Comment by chriseppstein** [comment]
Stylesheets can be shared across pages, so this optimization cannot be safely performed.

It's best to use partials to organize your code. Nesting is a way of simplifying the authoring of selectors -- it's not intended for organization.
