### ISSUE TITLE
Add Gitter.im Chatroom for support

### ISSUE THREAD

**Issue by ankurp** [sass/sass#1534]

**Comment by ankurp** [comment]
@nex3 What is the reason for not having a support chatroom?

**Comment by nex3** [comment]
Well, first of all you filed an issue without any text, so there's not really anything there to discuss. You're asking us as maintainers to devote our time and attention to an additional channel without any particular justification about why that channel is important. There's already the [@SassCSS](http://twitter.com/SassCSS) twitter account, the [mailing list](https://groups.google.com/forum/#!forum/sass-lang), the [StackOverflow tag](http://stackoverflow.com/questions/tagged/sass), and the IRC channel at `irc.freenode.net#sass`. Why does this thing you're proposing provide more value than any of these?
