### ISSUE TITLE
Unifying :root selectors doesn't work as expected

### ISSUE THREAD

**Issue by gsnedders** [sass/sass#1545]
SASS 3.4.7 does the following:

`selector-unify(":root.sml *", ":root.article h2")` returns `:root.sml :root.article h2, :root.article :root.sml h2`. This obviously matches, well, nothing (because the root element is never a descendant of the root element!). I'd expect this to return `:root.sml.article h2`.

**Comment by gsnedders** [comment]
It'd be nice to have some way of doing this with a specified root element (say, `html`) and operate under the assumption that there will be a single one per document. But that's probably stretching it, really.

**Comment by stephnr** [comment]
Can you expand on the feature you are requesting? How would this differ than from using the @at-root directive?

**Comment by gsnedders** [comment]
I have something roughly along the lines of:

```
@mixin foo($selector) {
    #{$selector} {
        /* a bunch of rules */
    }
    #{$selector}:before {
        /* a bunch more rules */
    }
    $sml = selector-unify(":root.sml *", $selector);
    #{$sml} {
       color: blue;
       background: black;
    }
 }
```

`@at-root` doesn't help in my case because in some cases I'm including the mixin within a media query (and at other times not).

**Comment by gsnedders** [comment]
Oh, I'd misunderstood what `@at-root` does. I'd read as far as "the @at-root directive causes one or more rules to be emitted at the root of the document" and then looked elsewhere. Still, doesn't really do what I need.

What I need, ideally, to do is to take two selectors, `html.sml *` and `html.article article > h2`, and somehow merge them to come out with `html.sml.article article > h2`. Of course, doing that with an `html` element selector requires knowledge that the tree only contains a single `html` element, which is impractical. However, the `:root` selector by definition only matches a single element, hence it should be possible to merge them.

I can't just do `html.sml #{$selector}` because some of the other selectors need to match classes on the root element (and everything is a mess so changing the HTML will probably lead to other breakage, le sigh…) and hence somehow have to merge the two…

**Comment by stephnr** [comment]
Personally, I would suggest one of two options:
1. Use the & parent selector. Something like that would look like this:

``` sass
html.sml {
    & * { ... }
    &.article article > h2 { .. }
    @at-root html.article article > h2 { ... }
}
```
1. Redo your css declarations. If you have to be declaring things this way, it seems to me that you are using your CSS selectors in a very odd format. Try using some form of Object Oriented CSS in order to resolve these kinds of issues in the future.
