### ISSUE TITLE
Apply the same value to multiple properties.

### ISSUE THREAD

**Issue by Robovirtuoso** [sass/sass#1547]
In my Sass I often find myself applying the same value to multiple properties. Usually to properties such as margin, padding, width and height. I've solved the problem for myself by making a mixin:

``` scss
@mixin property($value, $properties) {
  @each $property in $properties {
    #{$property}: $value
  }
}

.box {
  @include property(30px, padding-left padding-right);
  @include property(50%, width height);
}
```

Is this something that others would find helpful? Obviously not having the `@include` would be a nicer syntax, but is this the type of feature that would be better fit in the language itself? I would be more than happy to make a patch if this would be beneficial to others.

**Comment by Snugug** [comment]
IMO, this is not something appropriate for a language level feature, but best suited libraries built on top of the language.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/109

**Comment by whaaaley** [comment]
Me too. I wrote a mixin with a similar idea: https://github.com/dustindowell22/lifesaver
I agree this kind of stuff shouldn't be Sass's responsibility.

**Comment by Robovirtuoso** [comment]
Didn't realize this was already an issue, my bad!

It doesn't look like anyone's talked about it in a while, though there seems to be quite a bit of support around it. Am I better off making a PR or finding a Sass library to contribute something like this to? And if the latter, do you have any recommendations for what library to contribute to? As far as my knowledge goes there isn't a community agreed upon "standard library" for Sass.

**Comment by Snugug** [comment]
There isn't one, although I'd accept a pull request into toolkit https://github.com/at-import/toolkit

**Comment by stephnr** [comment]
:-1: agreed. This is not a level language feature. It should just be included separately and used as needed.

**Comment by KittyGiraudel** [comment]
Agreed. Should not be part of Sass in my opinion.

**Comment by lolmaus** [comment]
I disagree.
1. Applying a value to multiple properties is a very-very common task.
2. A helper mixin syntax is very bulky and does not make the code much cleaner.

In other words, this:

``` scss
@include property(foo bar, 'baz');
```

is way worse than either of these:

```
foo, bar: 'baz';
foo: bar: 'baz';
```

**Comment by stephnr** [comment]
Correct me if I am wrong @HugoGiraudel but I believe that this is not an issue about whether an "applicator" is needed or not, the issue is with how the `@include` directive was designed.

It was not originally designed for those types of operations. Plus, there would be a serious concern with scope. For example, if you did the following:

``` scss
@include property(foo bar, 'baz');

// Generates:
// foo, bar: 'baz';
// foo: bar: 'baz';
```

These variables would exist outside the scope of the initial Sass compilation sequence and be rendered useless. 

HOWEVER, I would consider just using something like a **_variables.scss** file to import. This is what I use and have found it very helpful.

Reference: http://thesassway.com/beginner/how-to-structure-a-sass-project

**Comment by KittyGiraudel** [comment]
I am having a hard time figuring out what you are talking about I must admit. Did I miss something?

**Comment by lolmaus** [comment]
@Stephn-R, this has nothing to do with variables, and your suggested output it invalid CSS.

**Comment by stephnr** [comment]
@lolmaus, that is the exact example you provided

Perhaps you meant something like this?

SCSS:

``` scss
@include property(30px, padding-left padding-right);
```

CSS:

``` css
padding-left: 30px;
padding-right: 30px;
```

**Comment by whaaaley** [comment]
@lolmaus I agree that this way is still bulky. I think a better solution would be what's been mentioned in #366 which would make includes less bulky and more CSS looking. Then these small helper mixins wouldn't be almost equally as painful to use and look at as it would be to just write it out by hand.

Then the proposed:

```
foo, bar: baz;
```

Could possibly be turned into a mixin with this syntax:

```
++qux: foo bar, baz;
```

Which isn't much worse, but still much better than:

```
@include qux(foo bar, baz);
```
