### ISSUE TITLE
random($limit) return values inclusive of limit

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1548]
The docs for `random($limit)` state it will 

> Return an integer between 1 and `$limit`, inclusive of 1 but not `$limit`.

However it appears to return limit. http://sassmeister.com/gist/9e90b4b76610de0d9a55

**Comment by xzyfer** [comment]
Can you please confirm whether is a bug so I can adjust the libsass implementation accordingly?

**Comment by mgreter** [comment]
This spec seems pretty counterintuitive as all `rand` functions I normally use include the upper boundary. IMO this makes perfectly sense or what would you expect from `random(1)`?. I wonder if it would be less painfull to just change the spec than "breaking" an existing feature. But that's up to you guys, just wanted to give my opinion. But some clarification would be helpfull! Thanks!

**Comment by nex3** [comment]
This is unexpected behavior, but I agree with @mgreter that breaking backwards-compatibility here would be bad. If we were to change the behavior, it would be very difficult to do a deprecation period. I'll just change the docs.

> This spec seems pretty counterintuitive as all `rand` functions I normally use include the upper boundary.

@mgreter I find this surprising. Ruby, C#, and Java all exclude the upper bound.

**Comment by mgreter** [comment]
@nex3: just checked the C, Perl and PHP implementation and they include the upper bound for `rand`:
http://www.w3schools.com/php/func_math_rand.asp
`If you want a random integer between 10 and 100 (inclusive), use rand (10,100).`
http://man7.org/linux/man-pages/man3/rand.3.html
`returns a pseudo-random integer in the range 0 to RAND_MAX inclusive`
But I also checked c++ `uniform_real_distribution` which seems to exclude the upper bound!
`rand(x | a, b) -> 1/(b-a) -> a <= x < b`

**Comment by chriseppstein** [comment]
The docs are changed to match the behavior. Closing.
