### ISSUE TITLE
Error with charset directive

### ISSUE THREAD

**Issue by jminer** [sass/sass#1550]
I am trying to run Sass 3.4.7 on a server with a command like `~/.gem/ruby/1.9.1/bin/sass input.css output.css` but I get an error about an "Invalid US-ASCII character" referencing a line with a smart quote. Although a smart quote is not ASCII, from reading the documentation, I would assume that Sass would treat the file as UTF-8, but it does not seem to be doing so.

After some searching, I find that I should add a `@charset` directive and that it has to come at the very beginning of the file:

```
@charset "UTF-8";
...
```

I added it, but now I just get a different error: `Invalid charset directive '@charset': expected string.`

I added a line to see what `value` is in `parse_charset_directive()`, and it is `"UTF-8";` (it includes the semicolon). Adding a semicolon to the regex in `parse_charset_directive` seems to fix the error, but I don't know the code enough to know if that fix is correct:

```
      name = value && value[/\A(["'])(.*)\1;\Z/, 2] # "
```

**Comment by nex3** [comment]
If you're using the `.sass` indented syntax, you should leave off all semicolons from directives (and any other line). They're only necessary when using SCSS.

**Comment by jminer** [comment]
Yes, changing the extension of the input file to `.scss` did make it work. I thought I read that the indented syntax was deprecated, so I wrongly assumed that SCSS was the default. I guess it makes sense, since `.sass` came first. Thanks.
