### ISSUE TITLE
Error running sass 3.4.7 on Windows 7 (64bit) and jruby 1.7.16.1

### ISSUE THREAD

**Issue by jsmreese** [sass/sass#1551]
Trying to build Foundation for Apps with jruby 1.7.16.1 installed, and I see this error from gulp-ruby-sass:

```
gulp-ruby-sass: stderr: Errno::ESRCH: No such process - No such process
mtime at org/jruby/RubyFile.java:924
stylesheet_needs_update? at C:/jruby-1.7..16.1/lib/ruby/gems/shared/gems/sass-3.4.7/lib/sass/plugin/staleness_checker.rb:65
...
```

Downgrading to jruby 1.7.15 fixes the issue.
For more info see https://github.com/zurb/foundation-apps/issues/203#issuecomment-65805631 and https://github.com/sindresorhus/gulp-ruby-sass/issues/168

Sass 3.4.9 might fix this issue?
Not sure because gulp-ruby-sass (or foundation-apps?) requires sass 3.4.7.

**Comment by nex3** [comment]
This looks like a bug in JRuby. Sass is just calling the standard `File.mtime` function here.

If someone comes up with a workaround for this, I'll look into adding it, but I have a hard time imagining what it would be, since this is pretty much the API for getting the modification time of a file.

**Comment by sebcramer** [comment]
@nex3 Just to chime in (since im am also experiencing the same problem): The problem still persists even if using the current version of jruby (9.1.6.0). Our plugin definition in maven looks like this:
``` xml
<plugin>
  <groupId>nl.geodienstencentrum.maven</groupId>
  <artifactId>sass-maven-plugin</artifactId>
  <version>2.22</version>
  <dependencies>
    <dependency>
      <groupId>org.jruby</groupId>
      <artifactId>jruby-complete</artifactId>
      <version>9.1.6.0</version>
    </dependency>
  </dependencies>
  <executions>
    <execution>
      <id>package</id>
      <goals>
        <goal>update-stylesheets</goal>
      </goals>
      <configuration>
        <resources>
          <resource>
            <source>
              <directory>${basedir}/src/main/stylesheets</directory>
            </source>
            <relativeOutputDirectory>..</relativeOutputDirectory>
            <destination>${sass.outputDir}</destination>
          </resource>
        </resources>
        <useBourbon>true</useBourbon>
        <sassOptions>
          <style>${css.output.style}</style>
          <unix_newlines>true</unix_newlines>
          <sourcemap>:none</sourcemap>
        </sassOptions>
      </configuration>
    </execution>
  </executions>
</plugin>
```

I agree that this is a jruby bug - buuut: Some digging around showed that (at least with the current version) it might be related to the fact that the output path is not existing. The error reads as follows:
```
Errno::ESRCH: No such process - D:/workspaces/appl/appl-parent/appl-web/target/generated-resources/sass/resources/default/css/main.css
                        mtime at org/jruby/RubyFile.java:1032
     stylesheet_needs_update? at uri:classloader:/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:65
  block in update_stylesheets at uri:classloader:/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:211
                         each at org/jruby/RubyArray.java:1734
           update_stylesheets at uri:classloader:/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:209
           update_stylesheets at uri:classloader:/gems/sass-3.4.22/lib/sass/plugin.rb:82
                       <main> at <script>:22
```
If I now go ahead an manually create ``target\generated-resources\saas\resources\default\css`` the problem goes away. Perhaps that might be a feasible workaround?

**Comment by latuszek** [comment]
This issue still persist. The fix should be as simple as creating the output directory (if not already exists) before calling mtime.

**Comment by latuszek** [comment]
Here's a workaround for sass-maven-plugin.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.0.2</version>
    <executions>
        <execution>
            <id>create-css-directory</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <outputDirectory>path/to/missing/directory</outputDirectory>
                <resources>
                    <resource>
                        <directory>${project.build.directory}</directory>
                        <excludes>
                            <exclude>**/*</exclude>
                        </excludes>
                    </resource>
                </resources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by sebcramer** [comment]
I build a groovy script I include in the maven build to generate all required artefacts. I noticed problems under certain conditions when the output css files are not present. The groovy script will create the output files and back date them. I will post it on Monday when I am back at my desk.

**Comment by sebcramer** [comment]
The script looks like this:
``` Groovy
import groovy.io.FileType

def list = []

def dir = new File(inputDirStruct)
dir.eachFileRecurse(FileType.DIRECTORIES) { file ->
   if (!file.name.startsWith('_')) {
      list << dir.toURI().relativize(file.toURI()).toString() 
   } 
} 

list.each {
   def outDir = new File(sassOutputDir, it)
   outDir.mkdirs()
   if ('css'.equals(outDir.getName())) {
      def mainCss = new File(outDir,'output.css')
      if (!mainCss.exists()) {
         new FileOutputStream(mainCss).close()
         mainCss.setLastModified(0)
      }
   }
}
```
It is called from maven like so:

``` XML
<plugin>
   <groupId>org.codehaus.gmavenplus</groupId>
   <artifactId>gmavenplus-plugin</artifactId>
   <executions>
      <execution>
         <id>sass-fix</id>
         <phase>generate-sources</phase>
         <goals>
            <goal>execute</goal>
         </goals>
         <configuration>
            <properties>
                <property>
                   <name>inputDirStruct</name>
                   <value>${basedir}/src/main/stylesheets</value>
                </property>
                <property>
                   <name>sassOutputDir</name>
                   <value>${sass.outputDir}</value>
                </property>
             </properties>
             <scripts>
                <script>file:///${project.basedir}/src/build/groovyScripts/sass-fix.groovy</script>
             </scripts>
          </configuration>
       </execution>
    </executions>
</plugin>
```

Hope it helps.

**Comment by latuszek** [comment]
@sebcramer Try it my way. You should not need groovy plugin and writing scripts. Just the ordinary maven-resources-plugin which is used by default in maven. The script creates needed directory and should be run before sass plugin. That's is.

@nex3 It would be nice if sass creates those dirs by itself.

**Comment by sebcramer** [comment]
@seiyapl I startet out with just the directories. The problem was: some version of ruby started to act up regarding the output files (not only the directories).

**Comment by latuszek** [comment]
@sebcramer OK, then Your case is other than main :)

**Comment by sebcramer** [comment]
I think we are all in agreement that this is a terrible JRuby Windows bug. But I also tend to agree with @seiyapl : Perhaps it would be worth while to create the output artifacts (and back date them) to prevent the JRuby problems from striking.
