### ISSUE TITLE
Could Handling of Pseudo Classes When Combined With &- Be Improved?

### ISSUE THREAD

**Issue by Undistraction** [sass/sass#1552]
Just encountered the following, and wondering if Sass's handling of this situation could be improved:

Scss:

```
.Example {

  &-subtitle {
   color: blue;
  }

  &:first-child {

    &-subtitle {
      color: red;
    }

  }
}
```

Result:

```
.Example-subtitle {
  color: blue;
}
.Example:first-child-subtitle {
  color: red;
}

```

Given that the current handing effectively breaks the pseudo selector, in this situation, could Sass treat this as shorthand? Rendering:

```
.Example-subtitle {
  color: blue;
}
.Example:first-child .Example-subtitle {
  color: red;
}
```

**Comment by whaaaley** [comment]
`&` is a parent selector. It could be a good idea to allow `&&`, `&&&` etc, to reach higher up the tree, but I don't think it would be a good idea to give pseudo elements special treatment. If you want that output, just don't nest it. Put all your selectors on the same line.

```
.example {
  &-subtitle {
   color: blue;
  }

  &:first-child &-subtitle {
    color: red;
  }
}
```

Outputs:

```
.example-subtitle {
  color: blue;
}
.example:first-child .example-subtitle {
  color: red;
}
```

Edit:

I just discovered we can store the `&` selector in a variable, which is cool. I've never had a need to do this in SCSS. Then we can do this:

```
.example {
  &-subtitle {
   color: blue;
  }

  $this: &;

  &:first-child {
    #{$this}-subtitle {
      color: red;
    }
    #{$this}-paragraph {
      color: green;
    }
  }
}
```

Outputs:

```
.example-subtitle {
  color: blue;
}
.example:first-child .example-subtitle {
  color: red;
}
.example:first-child .example-paragraph {
  color: green;
}
```

**Comment by Undistraction** [comment]
@dustindowell22 Very interesting. Thanks.

**Comment by nex3** [comment]
I don't think it makes sense to add special cases to the behavior of `&` here. In general, most really complex parent-selector behavior ends up being a lot clearer when just written out explicitly.

**Comment by issam-seghir** [comment]
> `&` is a parent selector. It could be a good idea to allow `&&`, `&&&` etc, to reach higher up the tree, but I don't think it would be a good idea to give pseudo elements special treatment. If you want that output, just don't nest it. Put all your selectors on the same line.
> 
> ```
> .example {
>   &-subtitle {
>    color: blue;
>   }
> 
>   &:first-child &-subtitle {
>     color: red;
>   }
> }
> ```
> 
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/copy.png)
> Copy
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> Outputs:
> 
> ```
> .example-subtitle {
>   color: blue;
> }
> .example:first-child .example-subtitle {
>   color: red;
> }
> ```
> 
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/copy.png)
> Copy
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> Edit:
> 
> I just discovered we can store the `&` selector in a variable, which is cool. I've never had a need to do this in SCSS. Then we can do this:
> 
> ```
> .example {
>   &-subtitle {
>    color: blue;
>   }
> 
>   $this: &;
> 
>   &:first-child {
>     #{$this}-subtitle {
>       color: red;
>     }
>     #{$this}-paragraph {
>       color: green;
>     }
>   }
> }
> ```
> 
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/copy.png)
> Copy
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> Outputs:
> 
> ```
> .example-subtitle {
>   color: blue;
> }
> .example:first-child .example-subtitle {
>   color: red;
> }
> .example:first-child .example-paragraph {
>   color: green;
> }
> ```

I experienced the same problem and your comment was incredibly helpful, even after 9 years. Thank you. ♥

**Comment by issam-seghir** [comment]
> `&` is a parent selector. It could be a good idea to allow `&&`, `&&&` etc, to reach higher up the tree, but I don't think it would be a good idea to give pseudo elements special treatment. If you want that output, just don't nest it. Put all your selectors on the same line.
> 
> ```
> .example {
>   &-subtitle {
>    color: blue;
>   }
> 
>   &:first-child &-subtitle {
>     color: red;
>   }
> }
> ```
> 
> Outputs:
> 
> ```
> .example-subtitle {
>   color: blue;
> }
> .example:first-child .example-subtitle {
>   color: red;
> }
> ```
> 
> Edit:
> 
> I just discovered we can store the `&` selector in a variable, which is cool. I've never had a need to do this in SCSS. Then we can do this:
> 
> ```
> .example {
>   &-subtitle {
>    color: blue;
>   }
> 
>   $this: &;
> 
>   &:first-child {
>     #{$this}-subtitle {
>       color: red;
>     }
>     #{$this}-paragraph {
>       color: green;
>     }
>   }
> }
> ```
> 
> Outputs:
> 
> ```
> .example-subtitle {
>   color: blue;
> }
> .example:first-child .example-subtitle {
>   color: red;
> }
> .example:first-child .example-paragraph {
>   color: green;
> }
> ```

**I experienced the same problem and your comment was incredibly helpful, even after 9 years. Thank you. ♥**
