### ISSUE TITLE
Better way to scope lots and lots of variables inside mixins.

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1553]
I just ran into a situation today where I needed to scope a bunch of variables inside a mixin. I _could_ prepend something to all the modified variables, but there are a lot of variables in lots of places and the names are already pretty long, **or** I could throw all the code I need into a mixin. I just need to copy all the variables in a bunch of different places like this:

``` scss
@mixin bar( [[[ receiving 15 arguments here ]]] ) {
  // code with scoped variables
}

@mixin foo( [[[ original 15 arguments here ]]] ) {
  // code
  @include bar( [[[ relaying 15 arguments here ]]] );
  // more code using original variables
  &:hover {
    // code
    @include bar( [[[ relaying 15 arguments here ]]] );
    // more code using original variables
  }
}
```

This would be painful, especially if I needed to add more mixins or change/add more variables. I saw this issue #871, but it's kind of the exact opposite of what I need in a way, but maybe it could be made to work? I need a better way to scope variables inside a mixin. I have a few rough ideas how to solve this, but the only super simple one that doesn't really mess with a lot of things is this.

`@scope` It lets variables in, but nothing out:

``` scss
@mixin bar( [[[ original 15 arguments here ]]] ) {
  // code
  @scope {
    // scoped code using and modifying 15 arguments
  }
  // more code using original variables
  &:hover {
    // code
    @scope {
      // scoped code using and modifying 15 arguments
    }
    // more code using original variables
  }
}
```

I understand this is a rare use case. In most cases, you could probably utilize maps somehow if you didn't need to modify the variables often, but in this case I need to use the `bar` mixin in many different places and modify a few variables with different values each time getting very similar, but also very custom result each time.

Edit: This is basically a dup of all of these  #616, #440, #599, #462 and #353. I guess I searched the wrong things before posting. What's the situation with this idea though? Is it still a thing that you guys are open to implementing one day? Or maybe it doesn't fit in anymore as things have progressed?

**Comment by nex3** [comment]
This seems like a much narrower use case than is worth adding a new directive for.

> Edit: This is basically a dup of all of the mentions here #1026. I guess I searched the wrong thing before posting. What's the situation with this idea though? Is it still a thing that you guys are open to implementing one day? Or maybe it doesn't fit in anymore as things have progressed?

I'm not sure you referenced the right issue number there...
