### ISSUE TITLE
@extend inside of media queries

### ISSUE THREAD

**Issue by SimpleIX** [sass/sass#1557]
I have a class for rows and columns, the column layouts turn into rows on mobile - I have designed it in such a way that if I could use the code:

> .column { @extend .row }

The columns would transition to rows based on the media query; however with the nature of the @extend it seems to ignore media queries and @extend outside of the given range for the media query. All my other styles inside of the media queries work fine so it is this extend issue I believe..

**Comment by whaaaley** [comment]
See #1050
