### ISSUE TITLE
Feature request for multiple properties

### ISSUE THREAD

**Issue by tjbenton** [sass/sass#1558]
I had a thought on how sass could make it easer to work with properties that have the same value.

Here is a simple use case where I would use it when positioning icons. 
###### Input: SCSS

``` scss
.foo{
  top, left: 50%;
  margin: {
   top, left: -.5em;
  }; 
}
```
###### Input: SASS

``` sass
.foo
  top, left: 50%
  margin: 
   top, left: -.5em
```
###### Output: CSS

``` css
.foo{
 top: 50%;
 left: 50%;
 margin-top: -.5em;
 margin-bottom: -.5em;
}
```

I think it would be a simple feature to add, and it makes perfect SASS sense and helps reduce redundant code. This is a very simple example and only reduces the code a little bit but think about how much code you could potentially save when you are using maps or variables for your values.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/109
