### ISSUE TITLE
@mixin support for variables

### ISSUE THREAD

**Issue by bitbrain** [sass/sass#1559]
Add support for variables to store mixins. It could look something like this:

``` scss
$my-mixin: @custom-mixin !default;
```

Afterwards we could override it:

``` scss
$my-mixin: @another-mixin;
```

To include the mixin we can call:

``` scss
@include $my-mixin;
```

This feature is very useful when dealing with complex themes, when different sass definitions are required.

**Comment by Snugug** [comment]
Duplicate in desire to #626
