### ISSUE TITLE
Variable Documentation

### ISSUE THREAD

**Issue by allejo** [sass/sass#1561]
This may seem like a silly question, but is there a convention as to documentation what variables are for? For example, if you define a variable as a color, it would be handy to know what that color is for. This would be handy for larger projects like Bootstrap or Compass so IDEs can better support code completion and hints.

```
// $Color-Grey_Font To be used when text is desired to be grey
$Color-Grey_Font: #656565
```

**Comment by stephnr** [comment]
What you are asking about is a "Best-Practice" for variable declaration in Sass. Honestly, imo, this is handled on a case by case basis and should be handled in a way similar to CSS Class naming conventions.

There are a couple of ways to do this, but most people lean to either **Semantic** or **Non Semantic** naming conventions

**Comment by KittyGiraudel** [comment]
Isn't it what comments are for?

**Comment by allejo** [comment]
@KittyGiraudel, yea that is what comments are for.

I guess I was asking a mix of semantic naming conventions and if there would be room or a need for something like JavaDoc but for Sass.

**Comment by lolmaus** [comment]
@allejo, i asked @KittyGiraudel to comment on this because they are building JavaDoc for Sass: https://github.com/SassDoc/sassdoc

Currently SassDoc aims at documenting functions API. I hoped they would come up with a suggestion for documenting variables.

**Comment by KittyGiraudel** [comment]
Actually SassDoc is perfectly able to document variables, and for a while
now. Functions, mixins and placeholders as well. And version 2 is coming in
early January for much more coolness.

**Comment by allejo** [comment]
Oh that's perfect! That was exactly what I was looking for! I didn't know it already existed. Well that's embarrassing, I should have looked a bit harder... Thanks everyone
