### ISSUE TITLE
null variables in a mixin are not correctly evaluated by variable-exists

### ISSUE THREAD

**Issue by B-Prod** [sass/sass#1567]
With the folowwing code, we would expect to see "not exixt" as debug ouput, but it is not the case.

```
@mixin test-variable($my-variable: null) {
  @if variable-exists(my-variable) {
    @debug 'exist';
  }
  @else {
    @debug 'not exist';
  }
}
```

Tested with Sass 3.4.9

**Comment by cimmanon** [comment]
There's a big difference between a variable that is not set vs a variable that is set to null.  If you want to check nullness, check for null:

``` scss
@mixin test-variable($my-variable: null) {
  @if variable-exists(my-variable) and $my-variable != null {
    @debug 'exist';
  }
  @else {
    @debug 'not exist';
  }
}
```

**Comment by B-Prod** [comment]
OK, I will use the check against "null". But the documentatin is not clear
at all about that, I looked for that for a white before posting the issue...

Thanks for the lights.

2014-12-21 15:31 GMT+01:00 cimmanon notifications@github.com:

**Comment by KittyGiraudel** [comment]
As far as I can tell, the variable `my-variable` always exists in this example since it's been defined by the mixin.

**Comment by chriseppstein** [comment]
Comments here are correct. The variable is defined and set to `null`, so this check returns `true`.
