### ISSUE TITLE
@each and index() works with value only, not with key,value

### ISSUE THREAD

**Issue by maxgalbu** [sass/sass#1570]
If I use index() when using `@each key,value`, index() returns `""`, but if I use `@each value` index() works fine.

This works (`@each value`):

http://sassmeister.com/gist/9cd0c0618a38048a46c4

This doesn't (`@each key,value`):

http://sassmeister.com/gist/bd7cff5749ef3e8e4e5f

**Comment by lolmaus** [comment]
Did you notice that your working example produces invalid CSS?

The `index()` function is designed to work with lists. Internally, Sass maps are build on top of lists, so the `index()` function happens not to crash when it's applied to maps.

**Comment by Snugug** [comment]
In the first example, the value of `$color` is the `key: value` pair, which does have a position in the map. In the second, the value of `$color` is only the `value`, which does not have a position in the map (and is allowed to be duplicated, whereas keys are not).

If you would like to get the index of the `$colorname` in the `$colors` map, use `map-keys` to get an ordered list of the map keys along with `$colorname`

http://sassmeister.com/gist/02e1ec8bf36d20b4eba7

**Comment by maxgalbu** [comment]
@lolmaus @Snugug I didn't notice that, now i see what sass is doing. The behaviour was not straightforward for me so I didn't check the invalid css. Thanks!
