### ISSUE TITLE
variable scope in funciton

### ISSUE THREAD

**Issue by IEfucker** [sass/sass#1577]
Hi,guys.I did some test in variable scope issue, and get confused when I get different result from jsBin, sassmeister and grunt.
jsBin:http://jsbin.com/veqipu/1/edit?html,css,output
sassmeister:http://sassmeister.com/gist/b5eb34e268000534f444

jsBin is what I want, body:22px, .test:24px, sassmeister with body:21px,  .test:21px, same with my grunt.
And my grunt-contrib-sass is 0.8.1. Is that a problem of sass version .

**Comment by cimmanon** [comment]
jsBin must be using an older version of Sass, because that's not how variables work anymore.

See: https://github.com/sass/sass/issues/1183

**Comment by IEfucker** [comment]
Got it. More like Less now in my opinion.And it's better, for scope is more clear now.
