### ISSUE TITLE
mixin shorthand syntax

### ISSUE THREAD

**Issue by geddski** [sass/sass#1579]
When using a lot of mixins your code becomes cluttered with `@include`s. It would be really awesome to be able to have a shorthand syntax for mixins:

``` scss
@component(menu) {
  ...
}
```

as a shorthand for the full syntax: 

``` scss
@include component(menu) {
  ...
}
```

This would make using something like csstyle that relies on mixins a lot cleaner.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/366
