### ISSUE TITLE
@extend inside @media

### ISSUE THREAD

**Issue by prajith-ta** [sass/sass#1580]
//  Input (SCSS)
//  ---------------------------------------------------------------------------
@mixin highlight($count) {
    > \* {
        @extend %notification;
        width: 45px;
    }
}
@media only screen and (min-width: 1025px) {
    %notification {
        width: auto;
        float: none;
    }
    .help {
        @include highlight(2);
    }
    .push {
        @include highlight(2);
    }
    .pull {
        @include highlight(2);
    }
}

//  Output (CSS)
//  ---------------------------------------------------------------------------
@media only screen and (min-width: 1025px) {
    .help > *,
    .push > *,
    .pull > \* {
        width: auto;
        float: none;
    }
    .help > \* {
        width: 45px;
    }
    .push > \* {
        width: 45px;
    }
    .pull > \* {
        width: 45px;
    }
}

The above sample code works fine & compiled expected result. 
But the following code shows "You may not @extend an outer selector from within @media." error.

//  Input (SCSS)
//  ---------------------------------------------------------------------------
@mixin highlight($count) {
    > \* {
        @extend %notification;
        width: 45px;
    }
}
@media only screen and (min-width: 1025px) {
    %notification {
        width: auto;
        float: none;
    }
    .help {
        @include highlight(2);
    }
    .push {
        @include highlight(2);
    }
    .pull {
        @include highlight(2);
    }
}

@media only screen and (min-width: 769px) {
    %notification {
        width: auto;
        float: none;
    }
    .help {
        @include highlight(2);
    }
    .push {
        @include highlight(2);
    }
    .pull {
        @include highlight(2);
    }
}

//  Expected Output(CSS)
//  ---------------------------------------------------------------------------
@media only screen and (min-width: 1025px) {
    .help > *,
    .push > *,
    .pull > \* {
        width: auto;
        float: none;
    }
    .help > \* {
        width: 45px;
    }
    .push > \* {
        width: 45px;
    }
    .pull > \* {
        width: 45px;
    }
}

@media only screen and (min-width: 769px) {
    .help > *,
    .push > *,
    .pull > \* {
        width: auto;
        float: none;
    }
    .help > \* {
        width: 45px;
    }
    .push > \* {
        width: 45px;
    }
    .pull > \* {
        width: 45px;
    }
}

Need a simple solution. Please Help me......... Urgent

**Comment by chriseppstein** [comment]
Please seek support on a support forum not the issue tracker. If you google for this error you will find quite a bit of details about it.
