### ISSUE TITLE
unquote should raise an error for non-strings

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1583]
currently unquote silently passes through values that are not strings. This is inconsistent with the quote function.

The current behavior should be deprecated in the next major release and then changed to an error following that.

This was the outcome of #1574.

**Comment by KittyGiraudel** [comment]
Out of curiosity, how do you plan on tackling quoting multi-words strings through the `quote` function as they are actually lists?

``` scss
$wannabe-quoted: hello world; // list
$quoted-string: quote($wannabe-quoted); // error?
```

**Comment by nex3** [comment]
@HugoGiraudel there isn't a plan to change that behavior. `hello world` is a list, not a string, so it's not a valid value for `quote()`.

**Comment by KittyGiraudel** [comment]
That is what I expected. Thanks Natalie.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
