### ISSUE TITLE
superclass mismatch for class Literal (TypeError)

### ISSUE THREAD

**Issue by mkrishtopa** [sass/sass#1584]
sass --compass --scss ./project/static/newdesign/styles/fonts.scss --trace
/usr/lib/ruby/vendor_ruby/sass/script/literal.rb:7:in `module:Script': superclass mismatch for class Literal (TypeError)

Ubuntu 14.04 (64)
sass -v
  Sass 3.4.0.rc.3 (Selective Steve) (also tried latest stable)
compass -v
  Compass 1.1.0.alpha.3 (Polaris) (also tried 1.0.1)
ruby 1.0 (also updated to 2.0, builded from sources)

Any idea how to fix?

**Comment by chriseppstein** [comment]
Upgrade to compass 1.0.

**Comment by chriseppstein** [comment]
And uninstall all versions of Sass and compass and re-install.
