### ISSUE TITLE
SASS 3.4.9 @at-root @keyframes causes error

### ISSUE THREAD

**Issue by PeterBaltruschat** [sass/sass#1592]
The following snippet:

```
@at-root @keyframes my-key-frame
{
    color:#000;
}
```

causes this error:

```
Error: Invalid CSS after "": expected selector, was "@keyframes my-k..."
```

If you remove @at-root, it compiles successfully.

**Comment by PeterBaltruschat** [comment]
Note that if curly brackets are added like:

```
@at-root {
    @keyframes my-key-frame
    {
        color:#000;
    } 
}
```

the compilation succeeds.

**Comment by lolmaus** [comment]
What is the expected CSS output?

**Comment by PeterBaltruschat** [comment]
Expected output would be the keyframes definition at the document root, e.g.

```
.my-class
{
    @at-root @keyframes my-key-frame
    {
        color:#000;
    }
}
```

would be equivalent to

```
.my-class { }

@keyframes my-key-frame
{
    color:#000;
}
```

**Comment by lolmaus** [comment]
`@at-root` is part of a selector, while `@keyframes` isn't. That's why you need an extra pair of curly braces.

**Comment by KittyGiraudel** [comment]
Seconded, this is an intended behaviour.

**Comment by chriseppstein** [comment]
Confirmed. @at-root accepts a selector on the same line as a shorthand for the common use case. All other css blocks must be enclosed with the curly braces.
