### ISSUE TITLE
Concatenating @media queries

### ISSUE THREAD

**Issue by lachlanjc** [sass/sass#1593]
One feature I'd love for Sass to handle is concatenating @media queries. I like to keep my media queries next to the component itself, but unfortunately that translates to way more bytes than necessary in the final stylesheet, repeatedly declaring `@media (max-width: 480px`) and so on. It would be awesome if Sass could move all the code for mobile styling into one media query at the end of the final document.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/316

**Comment by lachlanjc** [comment]
Sorry @cimmanon. I did a search of issues and didn’t see anything, so I went ahead and created this.
