### ISSUE TITLE
SASS Maps with multiline layouts?

### ISSUE THREAD

**Issue by gespinha** [sass/sass#1594]
Hi there,

SASS allows us to create amazing maps with values, that help us manage our layouts easily, but the way maps should be displayed in order to work doesn't make any sense, we should be able to have something like this work:

```
$map: (
  first: (
    background: white,
    color: red
  ),
  second: (
    background: black,
    color: blue
  ),
  third: (
    background: grey,
    color: yellow
  )
)
```

instead of this:

```
$map: (first: (background: white, color: red), second: (background: black, color: blue), third: (background: grey, color: yellow))
```

This would enhance readability and the use of this kind of organisation to manage values across SASS

Thanks

**Comment by lolmaus** [comment]
This is a planned feature: #216. Unfortunately for us, indented syntax lovers, its priority is the lowest. :(

**Comment by ghost** [comment]
+1

**Comment by iErik** [comment]
Why do people hate the indented syntax? It's the best syntax invented

**Comment by gespinha** [comment]
@iErik I agree! But for SASS maps in particular in indented syntax, I think its quite damaging to the readability of the code. Its good that you can still use them in separate files with SCSS syntax, but maintaining two different syntaxes just doesn't feel right.
