### ISSUE TITLE
Exclude folder for sass watch?

### ISSUE THREAD

**Issue by bcherny** [sass/sass#1595]
I have the following structure:

``` text
app/
|_ bower_components/
|_ modules/
|_ models/
|_ ...
```

I want to watch app/, but ignore bower_components/. Is this possible?

**Comment by stephnr** [comment]
Have you tried using something like [Gulp](http://gulpjs.com/) or [Grunt](http://gruntjs.com/)? These can help with specific exclusions like this.

**Comment by bcherny** [comment]
I have, but with either one it's not trivial to get partial builds working correctly. Especially when it comes to SASS, where rebuilding a _partial should trigger a rebuild of anything that imports it too.

The best answer I have so far is a specific whitelisted watcher (rather than a blacklisted one) -

``` bash
sass --watch app/modules:app/modules app/models:app/models
```

**Comment by stephnr** [comment]
Can you send me what you have used in a gulp task? I can try to update it for your situation.

**Comment by bcherny** [comment]
The task looks something like this:

``` coffee
gulp.task 'compile-sass', ->

  gulp.src [
    'styles/foo.sass'
    'styles/bar.sass'
    ...
  ].map (uri) ->
    path.resolve "#{ CONFIG.APP_DIR }/#{ uri }"
  .pipe cache 'sass'
  .pipe do sourcemaps.init
  .pipe do sass
  .pipe remember 'sass' # enable partial rebuilds
  .pipe concat 'styles.css'
  .pipe do sourcemaps.write
  .pipe gulp.dest "./#{ CONFIG.DIST_DIR }/"

gulp.task 'watch', ->
  gulp.watch "#{ CONFIG.APP_DIR }/**/*.sass"
```

Again, the problem with this approach is that we can only rebuild the file that was modified, and not anything else that imports that file. To do that, we would need to parse all files and generate a dependency graph, and re-build any ancestors of a rebuilt node as well, in order.

**Comment by stephnr** [comment]
I would recommend rethinking how you organize your sass project. I can understand the concern of not being able to compile sass templates that inherit the modified file, however, it is all a matter of structure.

For example, I organize my projects like follows:

```
---scss
|
|---base
     |--- _colors.scss
     |--- _mixins.scss
     |--- _variables.scss
|---includes
     |--- _nav.scss
|---helpers
     |--- _font-helper.scss
| styles.scss
| nav.scss
```

What I do is watch all Sass files within the `scss` folder. Whenever anything changes, set the task runner to compile the files located at the root. In this fashion, you will **_always**_ be able to compile your sass whenever **_any**_ file has been modified.

Here is an example gulpfile for reference:
[Sample Gulpfile => see 'compile-sass' function](https://gist.github.com/Stephn-R/8864d2840b2675057c26#file-gulpfile-js)

**Comment by bcherny** [comment]
I've worked with a good number of sass projects in the past, but have inherited a fairly large one and would like to rework the build process without messing with the file structure. I'm not so much looking for an alternative fs structure, but a way to exclude files from the SASS watcher, or an alternative, efficient partial rebuilder.

The problem with your watch is that you're compiling extra files. Say you have the following structure:

``` text
styles
|_ foo.sass
|_ includes/
  |_ _bam.sass
  |_ _bar.sass
  |_ _baz.sass
```

Say foo requires _bam, which requires _bar. When you modify _bam, your build would recompile all SASS files. But what you really want is to recompile just _bam, then _bar, then foo. The more files, partials, and imports you have in your project, the more extraneous compiling you have to do (which slows down your watcher).

**Comment by nex3** [comment]
There's no way to do this using the standard command-line interface, although you could probably whip something up with the Ruby API.

**Comment by alexbab** [comment]
sass will ignore folders or files with a trailing underscore. Just add an underscore at the begining of bower components
