### ISSUE TITLE
Cache error when processing 

### ISSUE THREAD

**Issue by JAW-Dev** [sass/sass#1597]
I updated all my gems the other day and switch from compass to grunt using autoprefixer. Then I started occasionally receiving errors like this.

```
Errno::ENOENT: No such file or directory - ./.sass-cache/f4441f6dc52b9bd4f93d2265c6e7ed2bc5e7a78c/_footer.scssc
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.
```

It looks like something is causing that extra "c" at the end of the file. It seems like that's the issue

It's not a completely breaking. I just run the process again and it runs fine.

**Comment by stephnr** [comment]
Can you attach your gruntfile.js as well?

**Comment by nex3** [comment]
`scssc` is the file extension of the cache files that Sass creates so it doesn't have to re-parse your files over and over.

Unfortunately, there's not much I can do here without a consistent reproduction or a stack trace. If you find a way to reproduce this, ideally without grunt in the mix, let me know. Even just a stack trace might be enough to go on.

**Comment by JAW-Dev** [comment]
@Stephn-R Here's the Gruntfile
https://gist.github.com/jawittdesigns/da37c9335808234a3291

@nex3 How do you get a stack trace

**Comment by stephnr** [comment]
the stack trace is usually pre-pended to the compiled CSS file at the head.

**Comment by JAW-Dev** [comment]
Oh, that. Yeah, I don't get that since I'm using grunt to process Sass. Grunt just stops the process without writing to any files if there's an error. Maybe it's just a grunt-sass issue.

**Comment by stephnr** [comment]
perhaps. It is possible, try running a sass compile via the terminal

**Comment by nex3** [comment]
Closing due to unresponsiveness.
