### ISSUE TITLE
RubyInline incompatibility

### ISSUE THREAD

**Issue by jdelStrother** [sass/sass#16]
Heya,
In the process of upgrading my app to Rails 3, I've updated to Sass 3.1.0.alpha.19, and can no longer get it to boot.  I get : 
lib/sass/plugin/rails.rb:19: undefined method `reverse_merge!' for nil:NilClass
- instead.

Turns out that RubyInline defines "attr_reader :options" on the Module object.  This then prevents Sass::Plugin's method_missing magic from forwarding Sass::Plugin.options to the compiler, and it just returns nil instead.

Any thoughts on a workaround?

**Comment by nex3** [comment]
This is a bug in RubyInline. They shouldn't go around monkeypatching core classes.

**Comment by jdelStrother** [comment]
For what its worth, I've had a couple of people stumble across this problem.  Here's my "fix", in application.rb : 

require 'inline'
class ::Module; undef :options; end;

If you rely on RubyInline's 'options' behaviour, you'll have to find some other way around.  See also - http://rubyforge.org/tracker/index.php?func=detail&aid=28657&group_id=440&atid=1774
