### ISSUE TITLE
The sass executable shouldn't implicitly switch to --update

### ISSUE THREAD

**Issue by danfinnie** [sass/sass#1602]
Currently, the `sass` and `scss` executables silently switch to `--update` mode if multiple colon-separated paths are passed on the command line. This leads to confusing differences between `sass foo:bar` and `sass foo:bar baz:bang`, especially if `foo` and `bar` are directories.

We should change the behavior to never enable `--update` mode without the flag itself being explicitly passed. This means we'll need to deprecate handling directories without `--update`.

This issue has been retargeted by @nex3. Original issue follows:

---

I've been working on a [pull request for grunt-contrib-sass](https://github.com/gruntjs/grunt-contrib-sass/issues/178) and noticed that when passed only one file, the sass executable automatically acts as if `--force` was passed.  I believe this is caused by the `@args.size` clause in an [if statement in sass_scss.rb](https://github.com/sass/sass/blob/af77545b39e042a42b1e3200c6dfa4679d2c0221/lib/sass/exec/sass_scss.rb#L40-L47).

I wrote a shell script to demonstrate this behavior:

``` bash
#!/usr/bin/env bash

set -e
set -x

sass -v
ruby -v

SASS_OPTS="--sourcemap=none"

rm -f *.css *.map
sass $SASS_OPTS foo.scss:foo.css bar.scss:bar.css

echo "junk" > foo.css
echo "junk" > bar.css
sass $SASS_OPTS foo.scss:foo.css bar.scss:bar.css

echo
echo "Tried to recompile both files, but both are junk:"
cat foo.css
cat bar.css

sass $SASS_OPTS foo.scss:foo.css

echo
echo "Only recompiled foo.css, and that file is updated:"
cat foo.css
cat bar.css

sass $SASS_OPTS bar.scss:bar.css

echo
echo "Only recompiled bar.css, and that file is updated:"
cat foo.css
cat bar.css
```

This is the output on my system:

```
+ sass -v
Sass 3.4.9 (Selective Steve)
+ ruby -v
ruby 2.0.0p576 (2014-09-19 revision 47628) [x86_64-linux]
+ SASS_OPTS=--sourcemap=none
+ rm -f bar.css foo.css '*.map'
+ sass --sourcemap=none foo.scss:foo.css bar.scss:bar.css
      write foo.css
      write bar.css
+ echo junk
+ echo junk
+ sass --sourcemap=none foo.scss:foo.css bar.scss:bar.css
+ echo

+ echo 'Tried to recompile both files, but both are junk:'
Tried to recompile both files, but both are junk:
+ cat foo.css
junk
+ cat bar.css
junk
+ sass --sourcemap=none foo.scss:foo.css
+ echo

+ echo 'Only recompiled foo.css, and that file is updated:'
Only recompiled foo.css, and that file is updated:
+ cat foo.css
.foo {
  content: 'foo'; }
+ cat bar.css
junk
+ sass --sourcemap=none bar.scss:bar.css
+ echo

+ echo 'Only recompiled bar.css, and that file is updated:'
Only recompiled bar.css, and that file is updated:
+ cat foo.css
.foo {
  content: 'foo'; }
+ cat bar.css
.bar {
  content: 'bar'; }
```

I haven't been able to find any documentation that references this feature.  Is it an intended feature?  If so, would you accept a PR to add this to the documentation?

**Comment by nex3** [comment]
The default behavior of the `sass` executable is, Unix-style, to process a file as input and emit is as output, completely disregarding anything that may have been where the output is going. Usually is uses the Unix-y `executable input output` pattern, but for consistency it also allows `executable input:output`.

What I'm getting at is that it's not so much that it always enables `--force` as that it's not doing an update at all. It's just doing a batch-mode compilation.

It is pretty strange that it implicitly switches to update semantics when multiple colon-separated filenames are used, though. I think my preferred behavior would be to never use update semantics unless `--update` is explicitly passed, and to just allow multiple colon-separated files to be compiled in sequence in batch mode, but making that change would require a deprecation period.

**Comment by danfinnie** [comment]
@nex3 Sorry for the slow reply.  I agree that I would prefer consistent behavior with 1 or multiple files, but I did not mean to suggest that this behavior should be changed.  I merely wanted to document this behavior.  If you'd rather update the behavior, that's of course fine by me (not that it's my call).

Is there anything I can do to help push thing along?  I could submit a PR for the actual code change, but that looks like a small component of deprecating the feature... Thoughts?

**Comment by nex3** [comment]
The commit above adds the deprecation. If you'd like, you could go ahead and change the behavior on the master branch, although I'll get around to it eventually.

**Comment by danfinnie** [comment]
@nex3 I took a stab at this today.  I noticed that your deprecation noticed mentioned directories.  My interpretation of this was anytime you passed multiple files on the command line, whether because you specified a directory or because you listed 2 files explicitly.  Is this how you're seeing it?

**Comment by nex3** [comment]
The reason the error mentions directories is because that's the only backwards-incompatible change that would happen here. Because the executable only processes directories with `--update`, changing it to no longer have `--update` semantics when multiple arguments are passed has the side effect that directories will cease to be processed. Hence the error.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
