### ISSUE TITLE
DEPRECATION WARNING: Passing null, a non-string value, to unquote

### ISSUE THREAD

**Issue by Spheerys** [sass/sass#1607]
Hi,

I have just updated my Sass version on one project and I have now several warning :

```
DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
```

But I don't know what's wrong (and deprecated) in my code.
I don't use unquote, calc, element, expression, and url as user-function...
How can I have more explaination (number of line...) about these warnings ?

**Comment by KittyGiraudel** [comment]
I believe you are passing a color keyword to the `unquote` function. Color names are not strings but colors. The `unquote` function should only accept strings.

``` scss
// Nope
unquote(red);

// Yep
unquote('red');
```

**Comment by cimmanon** [comment]
If you're not using the unquote function, check any 3rd party libraries you're using.  I don't know if it still does, but Compass used to use the unquote function quite extensively in its css3 mixins.

**Comment by Spheerys** [comment]
I will look about this. Thx :)
But it could be more easy if the error indicate a line number IMO

**Comment by omgmog** [comment]
Would really appreciate the line number each time this warning occurs. When using a framework that depends on `unquote()` the terminal is just spammed with these `DEPRECATION WARNING` messages, with little indication as to where the bad code is. 

In the "Gridle" framework (referenced above), `null` is passed to `unquote()` in a few places, so it would be nice to narrow it down.
