### ISSUE TITLE
Standard Extension Language

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1608]
Sass extensions are currently ruby based. This was all well and good while we only had one implementation but with libsass in the mix, there is no way to introduce sass extensions that can work everywhere. The ruby extensions syntax is highly dependent on the specifics of the ruby implementation. I see a couple options:
1. Define a way to create extensions that support implementation specific code. For libsass this would be a shared object file and some way to initialize it. For ruby this would be much like what we have right now.
2. Choose a highly interoperable language for writing sass extensions and a common API in that language that all implementations would need to support. The most likely candidate for this is probably Lua. It is lightweight, fast, and fairly easy to write code in.

In addition to the extension support, I think it would be good for code that depends on extensions to make that dependency explicit using some special directive in the sass file itself. This could be as simple as letting `@import` (or some sass 4.0 equivalent) refer to sass "extensions" (since conceptually they define functions not unlike a sass file could). Or we could introduce some new directive for this.

/cc @akhleung @hcatlin @xzyfer

This is a major hurdle for making compass cross-implementation compatible.

**Comment by akhleung** [comment]
As a Lua fan I'm not unbiased, but Lua would provide a portable, performant, high-level solution. For implementation-specific extensions ... would it be sufficient to decide on some sort of data interchange format that all extensions would use?

**Comment by Snugug** [comment]
I think #1155 is probably related to this as well

**Comment by chriseppstein** [comment]
@Snugug It is similar in that we need to standardize the configuration format. But it's orthogonal to this issue.

**Comment by Snugug** [comment]
Yup. Agreed. That being said, I kind of view the two issues combined as "Let's standardize the non-mixin part of Compass".

**Comment by xzyfer** [comment]
Lua gets a :+1: from me.

I'm also a fan of explicitly declaring extension dependencies in source. However if overloading `@import` I believe there is a benefit in being able to clearly distinguish extensions and sass sources.

Two cases come to mind
- being able to parse the sass dependency tree i.e. for sass cli style smart watching
- passing configuration options to plugins like in the compass `config.rb` e.g. `@import "my-extension" with { foo: true }` _(I'm not proposing a syntax)_

**Comment by chriseppstein** [comment]
@scottdavis mentioned using ruby embedded into all implementations via mruby in another issue: https://github.com/Compass/compass/issues/1916#issuecomment-70733255 so I'm adding that as a possible (more backwards compatible) option here that we can discuss.

**Comment by nex3** [comment]
First of all, I don't think changing the extension language is something we should plan on doing in the near future. A lot of the factors that go into figuring out whether it's a good idea and what language is the best choice are unknown; in particular, the ultimate speed improvement from the work I'm doing and its effect on the community is unknown.

That said, there are certainly possible outcomes where increasing the portability of extension functions becomes desirable. If Ruby continues to be the language of the reference implementation, which I consider pretty likely, I'd be strongly in favor of using mruby. If it works well enough, it would also be worth looking into using it to distribute a stand-alone version of the Ruby implementation.

If we don't want to use Ruby for one reason or another, I'd prefer JavaScript to Lua. I believe it's not much more difficult to embed, the Node community is vibrant, and it's known by vastly more Sass authors.

**Comment by chriseppstein** [comment]
@nex3 Sass extensions are currently a major impediment to making Sass projects portable across implementations. We _need_ to provide a way for people to have a sass file that can run reliably across several implementations even if that sass file using host-language extensions. Without mitigation, we still have the schism we're trying to avoid in the community. You only addressed option #2 here and I agree that Lua or something else is probably premature. Instead, my preference right now is to have a standard way of making several host implementations of a sass extension work together.

**Comment by chriseppstein** [comment]
For instance, I think `@load "<extension-name>";` could be sufficient. Each implementation could define a standard about how that would work. And in theory, a Sass file that only provides sass functions could be used a fall back implementation in some cases.

**Comment by nex3** [comment]
I'd be okay with expanding the `Importer` API to allow an importer to provide Ruby functions for a given importer, thus allowing `@use "<extension-name>"` to work. What mechanism are you thinking for looking up extensions?

**Comment by chriseppstein** [comment]
> What mechanism are you thinking for looking up extensions?

I'm not sure exactly what you're asking here. Are you asking what this API would look like?

**Comment by nex3** [comment]
What's the algorithm for taking a string in a `@use` declaration and finding, loading, and making available Ruby functions for the document containing that `@use`?

**Comment by chriseppstein** [comment]
@nex3 I suppose it would just be a ruby file that defines functions. those would be class_eval'd into a module and that would get included into the evaluation context based on finding it with `@use`. in terms of lookup, I guess we'd need an extension load path or to just piggy back the sass load path for this.

**Comment by nex3** [comment]
I think at this point the closest we're going to come to this is the standard JS API for writing an extension that can be used by anyone in a way that's theoretically implementation-dependent, as well as the embedded host for writing an extension that works well in whichever native language people use. This doesn't solve the issue of writing an extension that can be used in any Sass installation, but that's not something we've seen people clamoring for recently.
