### ISSUE TITLE
Combining media query with selector

### ISSUE THREAD

**Issue by mahemoff** [sass/sass#1609]
Is there any reason why this couldn't work?

```
@media (max-width: 480px) .message
  color: red
```

I get `"Invalid CSS after \"...-width: 480px) \" expected media query list`

**Comment by Snugug** [comment]
That's not valid CSS. Selectors need to be nested under media queries.

**Comment by mahemoff** [comment]
Sass isn't valid CSS either :). It would make responsive stylesheets more concise in some cases.

**Comment by Snugug** [comment]
I don't see how that's a win over nesting; it makes identifying the selector less clear. It would also require special parsing rules for for `@media` to allow for a specific invalid syntax, but not others (note: there's a difference between extending CSS and outright writing invalid CSS).

**Comment by mahemoff** [comment]
Fair enough. I'd find it useful in some situations (small tweaks) but the cons outweigh it.

**Comment by lolmaus** [comment]
This could be a nice feature request for the (hopefully) upcoming indented syntax revamp.

For example, Jade allows putting multiple expressions on one line: 

``` jade
html: body: p Hello.

html
  body
    p Hello
```

Sass could use the same approach:

``` sass
@media (max-width: 480px); .message
  color: red; background-color: white


@media (max-width: 480px)
  .message
    color: red
    background-color: white
```

I personally don't use in Jade, but it's obvious that it could make Sass more concise in certain cases.
