### ISSUE TITLE
Global variables and mixins

### ISSUE THREAD

**Issue by pyrsmk** [sass/sass#1610]
Hi!

I'm the creator of [vertical-rhythmic](https://github.com/pyrsmk/vertical-rhythmic) and got stuck on a weird bug. I'm defining the `$vr-ratio` variable globally to define the good value in `vr-baseline()` and get it in `vr()`. It worked well but, as of Sass 3.4.5 (I don't know for the other versions), the variable isn't accessible anymore from the `vr-baseline()` scope. Instead of defining the global `$vr-ratio` variable, it defines a local one with the same name. Then, `$vr-ratio` equals to `null` in `vr()` mixin and the compilation fails. For now, I fixed that by adding the `!global` parameter to the definition in `vr-baseline()` (as you may see in the source).

Is that a wanted behavior?

**Comment by KittyGiraudel** [comment]
Yes, and your fix is the correct way of doing. Here is an extra explanation on variable shadowing from Sass 3.4: http://sass-guidelin.es/#scoping.

**Comment by KittyGiraudel** [comment]
This should probably be closed. There is no bug whatsoever.

**Comment by pyrsmk** [comment]
I think so, thanks for the response ;)
