### ISSUE TITLE
Support using the & operator directly after another selector

### ISSUE THREAD

**Issue by ericandrewlewis** [sass/sass#1612]
I'd like to write the following sass

```
.wrapper {
    .class-on-wrapper& {
        // styles
    }
}
```

However the sass compiler doesn't like this, saying `"&" may only be used at the beginning of a compound selector`.

You can probably accomplish this with sass functions, but this syntax seems intuitive, and something sass should support natively.

**Comment by stephnr** [comment]
There is no difference between:
`.wrapper.class-on-wrapper` and `.class-on-wrapper.wrapper`

Example: http://codepen.io/Stephn_R/pen/QwgONO

**Comment by ericandrewlewis** [comment]
Sorry to over-simplify, but there is a difference when you're nested more than one level deep. e.g.

```
.a {
    .b {
        .c& {
            // styles
        }
    }
}
```

**Comment by stephnr** [comment]
Forgive me but I am not seeing a difference here either:

http://codepen.io/Stephn_R/pen/QwgONO

**Comment by ericandrewlewis** [comment]
```
.a {
    .b {
        .c& {
            // styles
        }
    }
}
```

would presumably translate to

```
.c.a .b {
    // styles
} 
```

**Comment by stephnr** [comment]
In this case, it looks like you are trying to use something like the `@at-root` directive but by appending the & selector, it would include the parent selectors. I understand now. This feature does not currently exist, however, if we are considering **_"Best Practices"**_, this is not a good practice.

It's not worth it to add a feature to help people write _bad code_

**Comment by chriseppstein** [comment]
you can use the [selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions) and Sass script to manipulate your current context (`&` in SassScript is your current selectors) and accomplish this.
