### ISSUE TITLE
calc  with variables doesn't work

### ISSUE THREAD

**Issue by nathraQ** [sass/sass#1615]
Following code is ignored by the sass compiler.

```
@keyframes rightToLeft { 
  0%   {right:0px; top:0px;}
  100% {right:calc(100% - $indent);  top:0px}
}
```

It does not throw errors while compiling it is just ignored and exactly the same in the output file.

`100% {right: $indent;  top:0px}` however does compile correctly.

~~I'm not quite sure if this is part of the interpolation bug with keyframes.~~

**update**: sorry just realized now it's a general calc and $variables problem.
so `calc(100% - $indent)` does not work

**Comment by nathraQ** [comment]
it's not a bug, it's a feature #1147  please close as duplicate

**Comment by KittyGiraudel** [comment]
Works as intended. 

You have to interpolate the variable.

**Comment by nathraQ** [comment]
Yes I've seen that, thanks. Just wasn't intuitive to me though
