### ISSUE TITLE
lighten(transparent, ...) doesn't work

### ISSUE THREAD

**Issue by krnlde** [sass/sass#1622]
Hey guys,
I'm from the less.js folks and used Sass for quite a time now. I experienced this painful bug recently. Here is my setup:

``` sass
$color: #aaa

body
  background-color: lighten($color, 10%)
```

So far so good. If I now change the variable to `$color: transparent`, the Compiler will crash with the info: `Syntax Error: $color: "transparent" is not a color for "lighten"`. Now, as mentioned, I come from Less and I really find it convenient that less interprets `transparent` as a color and just returns `transparent` after applying any kind of function (lighten, darken, fade-in, fade-out, etc..) so you can use variables to customize for example bootstrap components without having to override a single selector.

Since I couldn't find any reference to this topic I'm starting with this issue.

We are using `gem 'sass-rails', '~> 4.0.2'` which resolves to `'sass', '~> 3.2.0'`

Thoughts on this?

**Comment by no-dashes** [comment]
+1

**Comment by krnlde** [comment]
For everyone else having headaches with this, I found something here #754. Since version 3.4.11 of Sass (or to be exact: commit 0b86e2b2f67b6fa53c1476c0100908c5428b872f) this problem should be solved. A pitty we can't upgrade to this version due to other dependencies :(
