### ISSUE TITLE
Umask not honoured

### ISSUE THREAD

**Issue by christophlehmann** [sass/sass#1623]
In a multi-user environment others can't delete the .sass-cache folder since files created with 0600.

Please remove ', 0600' in lib/sass/cache_stores/filesystem.rb on line 39.

Thanks!

**Comment by chriseppstein** [comment]
The [umask is honored](https://github.com/sass/sass/blob/master/lib/sass/util.rb#L1257) in that the permissions will not be _more_ permissive than the umask.

Reading the comments for [my commit](https://github.com/sass/sass/commit/5007bdf2b1cf9d43e5ed69690efb339660a3564c) that fixed this it does seem that `0600` was not the desired behavior. Please submit a pull request that fixes this and we'll merge it in.
