### ISSUE TITLE
Make requiring Sass from an npm repo easier

### ISSUE THREAD

**Issue by callumacrae** [sass/sass#1626]
Feature request! I _think_ it's pretty trivial, but I don't know how sass works internally so I'm not really sure.

Currently it's not very nice to import Sass from an npm package. Initially we had this:

``` scss
@import "../node_modules/lmn.jester.theme.default/src/styles";
```

Then I wrote [this little library](https://github.com/callumacrae/find-node-modules) which we now pass to the `import_path` option in our gulpfile. Now we have this:

``` scss
@import "lmn.jester.theme.default/src/styles";
```

What would be ideal—and what we do with JS stuff we get out of npm—is if there were an equivalent of the [main](https://docs.npmjs.com/files/package.json#main) field for Sass. Then, I could just write the following:

``` scss
@import "lmn.jester.theme.default";
```

If the "sass" field (or whatever it were called) in "lmn.jester.theme.default" had a value of "src/styles", it would behave the same as the above.

This involves making some pretty big assumptions, but none that I think will break anything or cause confusion. If the import statement points to a directory, you would see if there is a package.json, and then if there is, it would read the json and see if there is a "sass" field. It would then append that the import path, and import that file.

Currently writing this behaviour in a mixin is impossible—I can read the json using a plugin, but I can't import a dynamic filename.

**Comment by nex3** [comment]
I don't think this is something that should be built into Sass directly, but it's a great use-case for writing a [custom importer](http://sass-lang.com/documentation/Sass/Importers/Base.html) as a plugin.
