### ISSUE TITLE
".*.scss" and "../" problems for @import

### ISSUE THREAD

**Issue by krainboltgreene** [sass/sass#163]
Been wanting to put a ticket for these problems for a while now, so here it goes.

These two things result in problems (specifically in Rails):
## Setup

``` files
app/assets/stylesheets/
- photographs/
-- photographs.scss
-- index.scss
- extra/
-- _mixins.scss
-- _variables.sass.scss
```
## "Back Directory" problem

Doesn't like looking for stuff in another directory that isn't in the current one. It's been since Rails 3.1.0rc3 since I've done this, so I don't know if this is still there.

``` scss
# file: app/assets/stylesheets/photographs/index.scss
@import "photographs"
@import "../extra/mixins"
```
## "Rails File Format Extention" problem

I just recently did this and it doesn't work.

``` scss
# file: app/assets/stylesheets/extra/_mixins.sass.scss

@import "variables"
```

It only looks for _filename_.scss, not _actual-filename-ending-in_.scss.

**Comment by nex3** [comment]
I'm assigning this to @chriseppstein, since he knows more about Rails integration than I do at this point.

**Comment by chriseppstein** [comment]
@krainboltgreene the second issue should be filed against sass-rails, but I don't really understand the issue so can you please explain it differently there? The file resolution and lookup is actually done by sprockets -- I just call their method to find it. See:
- https://github.com/rails/sass-rails/blob/master/lib/sass/rails/importer.rb#L33-41
- https://github.com/rails/sass-rails/blob/master/lib/sass/rails/template_handlers.rb#L17

So it might be better to file the bug against sprockets.

**Comment by krainboltgreene** [comment]
This is neither sass-rails nor sprocket's problem specifically.

The @import feature in SASS specifically looks for files named "filename.scss", but should instead look for "filename*.scss". See: https://github.com/nex3/sass/blob/master/lib/sass/importers/filesystem.rb#L92

**Comment by chriseppstein** [comment]
In vanilla sass, only filename.s[ac]ss is valid. Sass allows for other importing rules to apply by letting an "importer" object be placed on the load path. sass-rails does this to tap into the rails/sprockets file resolution system.

**Comment by krainboltgreene** [comment]
I realize that, but should vanilla sass only accept filename.s[ac]ss, or filename*.s[ac]ss?

There are already other web application frameworks, and even static frameworks, that are using the "rails way" of multi-part extensions.

**Comment by chriseppstein** [comment]
@krainboltgreene That is why we implemented the importer framework. We don't know what is the semantics of those other extensions. The other web frameworks can implement their own importer that provides the appropriate semantics.
