### ISSUE TITLE
MAC OSX Yosemite 10.10.2 - Neither normal watch nor polling watch seems to be firing

### ISSUE THREAD

**Issue by crispen-smith** [sass/sass#1631]
I'm not sure the best way to explain, or provide context around this item, and I suspect it's a dupe of something someone else has run in to, but I'm about ready to just reimage my whole box at this point, and I'm hoping that someone can help me avoid that.

For several months, through various updates, my workflow has been running a shell script that simply calls:  sass --watch Offsite/SASS/:Site/Resources/stylesheets/ 

ie. on the CLI I type: Sudo sh watch.sh  and forget about it.

It almost always needs to fallback to polling but other than that, I can live with it.

I've been trying to update my overall workflow this past week and at one point last weekend I had guard, guard-livereload, and sass running together beautifully.  I'd make a chance in my sass code, it would recompile my css, and livereload would reload the browser.

At last, I thought, seamless integration.  Once I had nodemon packaged in there to restart my node app for server side code changes, it was exactly what I'd been wanting.

Now, it's all broken.  I'll acknowledge I've probably done something stupid, but I've tried several clean builds and I'm just not seeing ruby and my file system talk to each other. 

gem list gives me this:

bigdecimal (1.2.6)
bundler (1.7.12)
celluloid (0.16.0)
coderay (1.1.0)
em-websocket (0.5.1)
eventmachine (1.0.6)
ffi (1.9.6)
formatador (0.2.5)
guard (2.11.1)
guard-compat (1.2.1)
guard-livereload (2.4.0)
guard-shell (0.7.1)
guardfile (0.0.2)
hitimes (1.2.2)
http_parser.rb (0.6.0)
io-console (0.4.3)
json (1.8.1)
listen (2.7.11)
lumberjack (1.0.9)
method_source (0.8.2)
minitest (5.4.3)
multi_json (1.10.1)
nenv (0.2.0)
notiffany (0.0.3)
power_assert (0.2.2)
pry (0.10.1)
psych (2.0.8)
rake (10.4.2)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.2.0)
sass (3.4.0)
shellany (0.0.1)
slop (3.6.0)
test-unit (3.0.8)
thor (0.19.1)
timers (4.0.1)

My root /offsite/sass/style.scss should be seeing a /modules/forms/skins/_account.scss file with recent changes in it (uncompiled) and I'm getting this from my command line:

```
Crispens-MacBook-Pro:cinchedstore crispensmith$ pwd
/Users/crispensmith/documents/cinchedstore
Crispens-MacBook-Pro:cinchedstore crispensmith$ sudo sh watch.sh
Password:
>>> Sass is watching for changes. Press Ctrl-C to stop.
--end
```

I'd normally expect to see at least a compile of recent changes.

Hoping someone can help.

**Comment by nex3** [comment]
Can you reproduce this without using `sudo` on directories in your home directory, or is it specific to this particular mode of calling `sass --watch`? Or could this be the same underlying issue as in guard/guard-livereload#130?

**Comment by crispen-smith** [comment]
@nex3, apologies i should have updated this.  It is entirely driven by an underlying issue with the RB-FSevent gem.   I don't have enough knowledge to provide anything definitive on this, but it seems that RB-FSevent sometimes cannot handle camelCasedDirNames.   Once I moved the contents to another directory, without caps in the name, I had no issues.
