### ISSUE TITLE
@at-root causes unused placeholders to output CSS

### ISSUE THREAD

**Issue by ghost** [sass/sass#1634]
I would like to keep my placeholders completely silent until they are extended, but it seems that using the `@at-root` directive within a placeholder interferes with their ability to remain silent.
For example,

``` sass
%myPlaceholder {
  .myClass {
    background-color: black; 
  }
}
```

does not output any CSS until `@extend %myPlaceholder;` is called. This is the desired behavior. But if I construct my placeholder like this:

``` sass
%myPlaceholder {
  @at-root .myClass {
    background-color: black; 
  }
}
```

I get the following output:

``` sass
.myClass {
  background-color: black;
}
```

regardless of whether my placeholder ever actually gets extended.

There could be a logical purpose for this behavior but I haven't been able to find it. Thanks for all your hard work!

**Comment by lolmaus** [comment]
That's just what `@at-root` means in Sass.

Why do you want `@at-root` within a placeholder anyway?

**Comment by ghost** [comment]
I've been working for a few months on a reusable toolkit that can be included in all my pages. Some of my (widget) placeholders call mixins that require the @at-root trick to prevent double-selectors from being outputting. Sort of like this:

``` sass
@at-root #{$element} {
  //code to remain silent here
}
```

To put it another way, I just do.

I was under the impression that @at-root is simply supposed to exit the current scope and insert code at the root of the CSS document, rather than outputting CSS when I clearly do not want it to.

**Comment by lolmaus** [comment]
Doing

``` css
%myPlaceholder {
  @at-root .myClass {
    background-color: black; 
  }
}
```

is the same as doing

``` css
.myPlaceholder {
  @at-root .myClass {
    background-color: black; 
  }
}
```

Both just declare selectors, that's it.

I think you want a mixin instead of an extend.

**Comment by ghost** [comment]
This problem occurs when I call a mixin that uses @at-root from any placeholder. I may be able to come up with a case-by-case workaround but I thought someone else might wind up with this same issue. The example was just to isolate the issue.

**Comment by Snugug** [comment]
@dustin-domco What `@at-root` does is it breaks out of the current scope entirely to go to the root of your CSS. This means that when you declare `@at-root` inside of a placeholder selector, it's no longer inside that placeholder selector (thus not scoped by it or its rules). What you're doing is equivalent to the following: 

``` scss
%myPlaceholder {
}
.myClass {
  background-color: black; 
}
```

If you're building a reusable toolkit, might I suggest you looking at the [DRY-ing Out your Sass Mixins](http://alistapart.com/article/dry-ing-out-your-sass-mixins) A List Apart article. It's a pattern that truly shines when building reusable toolkits.

**Comment by ghost** [comment]
Thanks, I've read that and most of the other related articles more than once. While that approach works for many cases, I find this approach to be a little more refined and appropriate for my projects. I have a series of mixins that take an optional selector argument, similar to a javascript function, to be used out of context (again, a simplified example):

``` sass
@mixin percentageCircle( $element: null ) {
  @if ( $element == null ) {
    $element: &;
  }

    @at-root #{ $element } {
        //styles apply here
    }
}
```

This allows me to use either of the following syntaxes, depending on their use-case:

``` sass
@include percentageCircle(".percentageCircleContainer");
```

or

``` sass
.percentageCircleContainer {
   @include percentageCircle;
}
```

Both of those syntaxes produce the desired code, but I've just recently learned that they output CSS into files that do not use any of this functionality, as long as they are included in the toolbox (which they always will be) and referenced by a placeholder.

This type of mixin does not output any code outright, but if I create a placeholder like this:

``` sass
%percentage-circle-widget {
    @include percentageCircle(".percentageCircleContainer");
}
```

I get the undesired result of having the code within the mixin applied to every single page that uses the toolbox, whether or not the placeholder or mixin is called. In this context, it certainly seems like a bug, but I'm aware that I'm pushing the limits of what Sass is capable of.

**Comment by ghost** [comment]
On the same note, I cannot contain @keyframes directives within a placeholder either. They get outputted as though they were @at-root by default. I'm assuming this is a feature and not a bug, but it certainly hinders my approach.
If I could interpolate mixins it would completely solve this issue, since I wouldn't need to use placeholders for widgets anymore. Thanks for hearing me out!

**Comment by ghost** [comment]
I was ultimately able to accomplish what I wanted by using a self-aware mixin that I believe was covered in the link you provided. I had used them elsewhere before, but hadn't thought to apply them to my widget library. It took a little more logic but it's working smoothly now. Sorry to bug you guys!
