### ISSUE TITLE
Error using a class with ++

### ISSUE THREAD

**Issue by jjalonso** [sass/sass#1637]
Hello, im using a framework that use a class like .mr+, .mr++ and .mr+++

When i try to extend this class i get a error.

```
  button {
    @extend .mr++;
    @extend .btn;
    @extend .btn--l;
  }
```

The error doesnt happen when i extend .mr, .mr+ but using two ++ like .mr++ drop a error:
13 Feb 00:11:30 - error: Compiling of 'app/styles/app.scss' failed. app/styles/_dash.scss:14: nested selectors may not be extended

Any help?
Thanks.

**Comment by cimmanon** [comment]
If the `+` is part of your selector name, then you need to be escaping it with a backslash.  In CSS, the following selectors are identical:

``` css
.foo+.bar { ... }
.foo + .bar { ... }
```

For anyone who doesn't remember the good old IE6 days, omitting the spaces around the adjacent/descendant selector operators was a common selector hack for hiding styles from that browser (it also failed miserably at parsing the selector in its spaced format, treating it the same as `.foo .bar`, if I'm not mistaken).

In fact, attempting to validate the following CSS will raise an error:

``` css
.mr++ {
    color: red;
}
```

> Parse Error  [++]

The following is valid CSS and Sass:

``` scss
.mr\+\+ {
  color: red;
}

button {
  @extend .mr\+\+;
}
```

**Comment by nex3** [comment]
@cimmanon is correct. `.mr++` is not a valid selector.
