### ISSUE TITLE
Can't use variables inside CSS nth- selectors

### ISSUE THREAD

**Issue by neagle** [sass/sass#164]
It looks like variables don't work inside CSS nth-selector in. Example:

```
$num: 2;

b:nth-child( $num ) {
}
```

This will produce the following error:

**Syntax error: Invalid CSS after "b:nth-child( ": expected expression (e.g. fr, 2n+1), was "$num ) {"**

I made the above example simple to the point of uselessness. If you'd like to know why I'd want to use a variable in an nth- selector, here's a second example:

```
@for $i from 1 to $circles {
    #circles b:nth-of-type( $i ) {
          /* Some styling */
    }
}
```

Please let me know if I can provide any more detail!

**Comment by neagle** [comment]
Bah, finally found the documentation on [interpolation](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#interpolation_). Nothing to see here!

**Comment by chriseppstein** [comment]
You have to use #{$num}

**Comment by saratchandr** [comment]
I am also facing the same problem. 

I have a list where it shows like .class:nth-of-type(int);
I would like to declare this as variable initially and pass the "int" value at run time.

Please let me know how do it ?

**Comment by chriseppstein** [comment]
``` scss
$type: int;
.class:nth-of-type(#{$type}) {
  color: red;
}
```

**Comment by touhid-rahman** [comment]
&:nth-last-child(-n + #{$column_number})
=> Not working :(

But &:nth-last-child(-n + 3)
Working....

**Comment by nex3** [comment]
@touhid-rahman That [works for me](https://www.sassmeister.com/gist/6ef7404d3b4a28dc9093fe42781b1607) on Ruby Sass. What version/implementation are you using? What error are you getting?
