### ISSUE TITLE
how remove copyright in minimified CSS (with SASS and Rails)?

### ISSUE THREAD

**Issue by MatrixFr** [sass/sass#1646]
I want remove all comment automaticly added in my minimified CSS assets, using rails and SASS. Exemple:

```
/*!
 * jQuery UI CSS Framework 1.10.4
 * http://jqueryui.com
 *
 * Copyright 2014 jQuery Foundation and other contributors
 * Released under the MIT license.
 * http://jquery.org/license
```

I tried :

```
config.sass.line_comments = false # in production config
rake assets:clobber assets:precompile #force recompilation
```

for JS we can do :

```
config.assets.js_compressor = Uglifier.new(copyright: false)
```

there is an equivalant like :

```
config.assets.css_compressor = Sass.new(copyright: false)
```

?

**Comment by nex3** [comment]
The entire point of the `!` after the `/*` is to indicate that the comment should always be preserved. If you want it removed, get rid of the `!` before sending it to Sass.

**Comment by HamptonMakes** [comment]
It's probably best to also note that those copyright notices are technically required... as per the MIT license.

**Comment by NicosKaralis** [comment]
I'm a little late for this issue.

I have in my rails app some vendor `js` and `css` files. They are downloaded and compiled during every deploy. And currently I'm facing this problem:

This css code:

```
@media (min-width: 64em) {
  .drawer--sidebar .drawer-hamburger {
    display: none;
    visibility: hidden;
  }

  /*! Left */
  .drawer--sidebar.drawer--left .drawer-nav {
    left: 0;
    border-right: 1px solid #ddd;
  }
}
```

Generates this css:

```
@media (min-width: 64em) {.drawer--sidebar .drawer-hamburger {display:none;visibility: hidden}/*! Left */;.drawer--sidebar.drawer--left .drawer-nav {left: 0;border-right: 1px solid #ddd}}
```

```
@media (min-width: 64em) {
  .drawer--sidebar .drawer-hamburger {
    display:none;
    visibility: hidden
  }

  /*! Left */
  ;.drawer--sidebar.drawer--left .drawer-nav {
    left: 0;
    border-right: 1px solid #ddd
  }
}
```

Funny thing is that `.drawer--sidebar .drawer-hamburger` behave as expected but `.drawer--sidebar.drawer--left .drawer-nav` is not detected.

I want to remove that comment incorrectly flagged as copyright. How can I do it?
