### ISSUE TITLE
Conditional stylesheet generation

### ISSUE THREAD

**Issue by bcoughlan** [sass/sass#165]
I'm slowly building up a library of mixins for creating cross-browser layouts and minimising the amount of hacks needed to get a site to function in old browsers, but I'm beginning to hit the limits of SASS.

What would be really useful for this kind of stuff would be being able to include browser-specific CSS within mixins. So for example a selector with the code:

```
    display: inline-block;

    !ie6,ie7
    display: inline;
    vertical-align: middle;
    zoom: 1;
```

would generate the files style.css, style-ie6.css, style-ie7.css. I'm digging through the ruby code and will have a go at implementing it but I'm honestly quite unfamiliar with the language.

**Comment by chriseppstein** [comment]
Feature queries with modernizr are te way to go here -- not browser detection. 

Then you can do:

```
#sidebar {
  ...;
  .no-box-shadow & {
    ...;
  }
}
```

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by bcoughlan** [comment]
While modernizr fine for box shadows and gradients, it doesn't help with things like lack of support for inline-block, or lack of support for child selectors. There's also the need for javascript and the overhead that comes with it, whereas sass is compiled and we just end up with the css.

My goal is to implement mixins for all of the hacks required for modern browsers, and also mixins for quick layout generation (without the overhead of Blueprint). I'm making mixins for two-column/three-column fluid/fixed layouts, just that IE6 (of course) needs some conditional statements.

**Comment by chriseppstein** [comment]
There are libraries that do what modernizr does but for browser detection. The same strategy can be used. No new features are needed in sass. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by nex3** [comment]
It's also worth noting that the correct way to do conditional blocks in Sass is to use an `@if` directive with a variable. For example:

```
display: inline-block;

@if ($ie6 or $ie7) {
  display: inline;
  vertical-align: middle;
  zoom: 1;
}
```

Then in `style-ie6.scss` you define `$ie6: true`, for example.

**Comment by chriseppstein** [comment]
I used to think this was a good idea, but the consistency and predictability of one input file to one output file is a really nice feature. Closing.
