### ISSUE TITLE
HSLA doesn't accept two arguments

### ISSUE THREAD

**Issue by futekov** [sass/sass#1658]
Sass works perfectly fine if I write `rgba(#4382a0, 0.5)` by converting it to `rgba(67, 130, 160, 0.5)`. 
However, `hsla(#4382a0, 0.5)` fails with "wrong number of arguments (2 for 4) for `hsla'".

[SassMeister demo](http://sassmeister.com/gist/57c411964fc0ff2a90b6)

**Comment by nex3** [comment]
This is a special convenience feature of `rgba`; it doesn't match the CSS definitions and really it's mostly around for historical reasons. I'd suggest using `change-color(..., $alpha: ...)` instead.
