### ISSUE TITLE
Include datauri functionality?

### ISSUE THREAD

**Issue by barkan** [sass/sass#166]
It would be great to be able to do this (using pseudo-syntax since I'm still researching SASS):

$theImage = '/img/the-image.png';
$theImageDataUri = @data-uri('/img/the-image.png');

.old-and-busted .doodad {
background: url($theImage);
}

.new-hotness .doodad {
background: url($theImageDataUri);
}

Semantics and philosophy aside as to detecting and handling browsers which don't support datauris, this could be a great way to cut down on http requests and simplify an advanced feature of css.

Extra credit for adding a test for image size so you can do a fallback in IE8 when the data uri would exceed 32kb. :)

**Comment by nex3** [comment]
This is the sort of thing that belongs in an extension to Sass, such as Compass. In fact, Compass may already support it; @chriseppstein?

**Comment by chriseppstein** [comment]
Yep. It's in compass and it's called inline-image(). 

http://compass-style.org/reference/compass/helpers/inline-data/

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by maranomynet** [comment]
I've resorted to using a post-processor like https://github.com/Wenqer/gulp-base64
