### ISSUE TITLE
Wrong documentation on the website

### ISSUE THREAD

**Issue by appsandkids** [sass/sass#1662]
A little unsure if it is the right place to write. However could not find any contact form on the http://sass-lang.com/.

Anyhow, on the http://sass-lang.com/install there is a section for Linux that says: If you're using a distribution of Linux, you'll need to install Ruby first. You can install Ruby through the apt package manager, rbenv, or rvm.
sudo su -c "gem install sass"

However it is likely that the above call will fail if the person does not have Ruby already installed. It installs sass, isn't?

That command line should be changed with something that installs Ruby, e.g. 
sudo apt-get install ruby-full

**Comment by nex3** [comment]
Try [sass-site](https://github.com/sass/sass-site) instead.
