### ISSUE TITLE
Slightly incorrect error message on multiplication between number with units and color

### ISSUE THREAD

**Issue by ahmadsalim** [sass/sass#1666]
I am running Sass version `3.4.13 (Selective Steve)` and when I try to multiply a number with units with a color I experience the following error:

```
>> 10em * #fff
SyntaxError: Cannot add a number with units (10em) to a color (#fff).
```

The error is slightly incorrect since I am not performing any addition.

**Comment by ahmadsalim** [comment]
Also, please notice that the error is actually a semantic one and not a syntactic one.
In ruby, one would usually expect to get something starting with `TypeError` in this case.

**Comment by lydell** [comment]
Well, in a way you _are_ performing addition, since multiplication is just repeated addition ;)
