### ISSUE TITLE
placeholders wrapping empty style block cannot be extended

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#1667]
This looks like a bug to me

``` sass
%place {
    // uncomment the following line and it compiles
    // color: red;
}

.place {
  @extend %place;
}
```

http://sassmeister.com/gist/569689a78d4d36635b23

**Comment by davidkpiano** [comment]
Pretty sure that the error thrown is by design. A `%place` placeholder with no declarations is treated as nonexistent.

You probably want this:

``` scss
.place {
  @extend %place !optional;
}
```

**Comment by wheresrhys** [comment]
`!optional` would prevent errors but isn't exactly what I need. In my use case I'm forking a module that defines styles for icons using placeholders. Many other modules which I want to consume too will extend these placeholders and, correctly, expect those placeholders to be defined, so `!optional` isn't appropriate here. 

My fork deliberately suppresses the styles defined by some of these placeholders but this throws an error so I have to leave in some dummy style, such as `zoom:1`. 

My use case is very niche, I know, but the behaviour seems completely wrong to me anyway. Do any other languages convert things that carry out null operations into `undefined`? In javascript (for example) an empty object is still an object, an empty variable is still a variable etc.... In sass I would expect an empty placeholder, mixin etc... to, once declared, continue to exist unless explicitly deleted. And tidying up empty style blocks is more a task for a css minifier than a css preprocessor IMHO.

Do you have any idea where I might find the original rationale behind the design decision to throw the error?

**Comment by chriseppstein** [comment]
The error is right. You're "forking" a thing and changing it such that a placeholder that is being extended is not really there anymore. The users who are calling extend without the `!optional` notifier deserve to be told that the thing they are building on top of has been removed. You can hack it by putting nonsense css properties in there like you've done, it doesn't even have to be legal css, per se, but I feel that Sass is doing the right thing here. This gives an error to prevent the silent failure of an extend, we can never give that error and support this edge case, even if I agreed that this was a valid use case, I would still err on the side of assuming there's a coding error happening here.

**Comment by wheresrhys** [comment]
> The error is right. You're "forking" a thing and changing it such that a placeholder that is being extended is not really there anymore. The users who are calling extend without the !optional notifier deserve to be told that the thing they are building on top of has been removed. 

I don't think sass should be making a call as to whether a placeholder is really there/has been removed based on the contents of a style block. e.g. styles within a placeholder can come from mixins, functions and extending other placeholders. If these styles amount to nothing in some cases I don't think sass should declare that placeholder not to be there. A more predicatable output would be to have an empty style block, which optimising can remove later. And if I really want to remove a placeholder _I will just remove the placeholder_.

My use case I think can be ignored in this discussion (there's a good reason for it, namely it's a temporary hack to suppress a load of buggy styles until they get fixed properly, but I appreciate that it's not a pattern with broad applications). And I would agree with your reasoning about throwing the error,  namely that an empty placeholder is _probably_ a mistake, if it wasn't for the fact that empty placeholders can occur quite legitimately when writing sass as configurable modules. I think empty style blocks for placeholders should, at most, show a warning.

**Comment by chriseppstein** [comment]
> I don't think sass should be making a call as to whether a placeholder is really there/has been removed based on the contents of a style block.

It's partially a side-effect of our implementation. Sass removes empty selectors as an optimization as it transforms Sass selectors into CSS selectors. Extend, being a CSS concept is applied after this optimization has been performed. Certainly, we _could_ distinguish between these two cases, but so far a compelling use case has not been found to justify this.

You need to explain why an empty selector is more "extend worthy" than a missing selector. In both cases, it seems like a coding error has occurred. What is the point of extending an empty selector? In both cases, the `!optional` flag tells sass that the user accepts they may be building on top of a thing that may not exist in their CSS output.

> if it wasn't for the fact that empty placeholders can occur quite legitimately when writing sass as configurable modules.

Maybe this is the use case. Please tell us more about this, I remain skeptical.

**Comment by wheresrhys** [comment]
Say we have two modules, both of which can be configured to have some parts turned off. Another module uses their mixins to define styles for a placeholder.

``` sass
// configured in the product
$module1-styles-text: false; // but true by default
$module2-styles-color: false; // but true by default

// @import module1/main
@mixin module1TextStyle () {
  @if $module1-styles-text {
    font-family: myfont
  }
}

// @import module2/main
@mixin module2Coloring
  @if $module2-styles-color {
    color: red
  }
}

// @import module3/main
%module3FancyText {
  @include module1TextStyle();
  @include module2Coloring();
}

// product styles
.thing {
   @extend %module3FancyText;
}
```

Whether this use case is convincing or not I think the empty placeholder being coerced to undefined needs documenting anyway as the behaviour is a bit unusual.
