### ISSUE TITLE
SCSS 3.4.12: Length doesn't return the proper value for variable arguments

### ISSUE THREAD

**Issue by scarletcs** [sass/sass#1671]
Define a mixin, give it a [variable argument](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_arguments) (i.e. of the form `$var...`), and test its `length()`.

The expected behaviour would be that it counts the number of elements in that variable. _However,_ the length function appears to _instead_ count the number of individual arguments that have been passed.

An example is available [in this SassMeister gist](http://sassmeister.com/gist/ee4a5475fe527b474bf0). Here's the code:

```
@mixin length-test($v...) {
  content: length($v);
}

.foo {
  @include length-test(a, b); // length: 2

  $list: a, b;
  @include length-test($list); // length: 1
}
```

This has a very undesirable effect. If I define a `@mixin gradient-background($stops...)`, I cannot tell the difference between _one stop_ being defined, or an arbitrary number of stops passed as a variable.

**Comment by scarletcs** [comment]
Apparently `nth($v, 1)` will return the entire variable `$v` if it was passed in as a variable.

I think I understand now, and that this may not be a bug but something I have to work around: a list passed in as a variable argument is one argument that is a list; it is not interpreted as multiple arguments.

**Comment by cimmanon** [comment]
This is the result I would expect:  you're passing a single value (a list) to your mixin, giving you a list containing a single element (the list you just passed in).

If you want to take your list and use it as an argument like that, you need to expand it:

``` scss
.foo {
  $list: a, b;
  @include length-test($list...); // length: 2
}
```

**Comment by scarletcs** [comment]
Hooray! Thank you for teaching me how to work with that. :)
