### ISSUE TITLE
Allow nesting of multiple values, similar to font property

### ISSUE THREAD

**Issue by ghost** [sass/sass#1675]
As it's possible to nest `font` properties, like

``` scss
font: {
  family: sans-serif;
  weight: 700;
}
```

to output

``` css
font-family: sans-serif;
font-weight: 700;
```

would it be possible to nest other multiple values, like

``` scss
src: {
  url("font.woff") format("woff");
  url("font.otf") format("opentype");
}
```

to output something like

``` css
src: url("font.woff") format("woff"),
     url("font.otf") format("opentype");
```

?

This would allow for easier processing and generating of the nested properties.

**Comment by KittyGiraudel** [comment]
Why don't you use a list? This type is made exactly for such use cases.

**Comment by indrekpaas** [comment]
Thanks Hugo!
