### ISSUE TITLE
Split lists into parts

### ISSUE THREAD

**Issue by danieldiekmeier** [sass/sass#1676]
In Python, you can get a part of a list with [n:m] after a list. Like this:

```
list = [1, 2, 3, 4, 5]

list[2:]
>>> [3, 4, 5]

list[:2]
>>> [1:2]

list[-2:]
>>> [4, 5]
```

Can we get something like this in Sass, too? I recently started using nth() to get parts of `&`, but if I could get the last few elements, it would make everything a little easier.

**Comment by davidkpiano** [comment]
@danieldiekmeier There are external libraries you can use to accomplish this, such as [Sassy Lists](http://sassylists.com/documentation/#function-sl-slice) or [the `_slice()` function in Sassdash](https://github.com/davidkpiano/sassdash) (which accepts negative start values for retrieving items from the end of a list).

**Comment by danieldiekmeier** [comment]
@davidkpiano Sassdash looks amazing, I'll definitely have a look. Thank you for your work there!
