### ISSUE TITLE
Comunity Speed Test

### ISSUE THREAD

**Issue by Sinius15** [sass/sass#1677]
Dear Sass Community,

I am a computer-science student in Holland and i am doing research on css-preprocessors. One of the aspects i am interested in is the community support. This is a test to discover the reaction speed of the community to issues. I will measure the time it takes to close this issue. 
Would the first person who reads this please close this issue?

Thanks in advance!

**Comment by HamptonMakes** [comment]
The whole core team for this is PST-based, so this is morning email checking.
