### ISSUE TITLE
The ability to reference itself (property lookup)

### ISSUE THREAD

**Issue by dan-gamble** [sass/sass#1678]
Does SASS have the ability or would it be possible in the future to implement some kind of property look up like Stylus' property lookup? http://learnboost.github.io/stylus/docs/variables.html#property-lookup

**Comment by Snugug** [comment]
Direct duplicate of #521

Soft duplicate of #727, #1582, #1603, #999, and probably others, I only looked back 2 pages in the issue search results.

**Comment by dan-gamble** [comment]
Sorry, i tried searching for `self`, `this` and `property lookup` but nothing surfaced.

**Comment by Snugug** [comment]
No worries, I tried `property value` and got a few. I'd recommend looking at one of the open issues to see if that would help.
