### ISSUE TITLE
Watch just stopped working 

### ISSUE THREAD

**Issue by IGRACH** [sass/sass#1679]
I have `ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]`, `gem 2.2.2`, `Sass 3.4.13 (Selective Steve)`. On Win7/64, and option -w (watching files) just stopped working. I can compile manually and sass appears to work, just  can't --watch files.

**Comment by nex3** [comment]
@IGRACH what ended up being the issue here?
