### ISSUE TITLE
sass compilation to css is slow

### ISSUE THREAD

**Issue by Zakay** [sass/sass#168]
Compiling sass is really slow, tried both with cache option enabled and disabled. What I noticed is that it only caches library files. The ones starting with underscore. I am using sass but not with the watch options. If at least it cached all files, it would speed up alot when recompiling. Even though I think it should be much faster without the caching, but fixing the caching would suffice.

**Comment by nex3** [comment]
Can you elaborate on this slowness? How slow are we talking? How many files/lines of Sass are you compiling? Normally Sass is pretty fast, but there are sometimes bugs that cause it to be very slow when parsing certain structures. It may be that you've run into one such bug, in which case we'll need to track it down and fix it.

Sass caches all files, whether or not they're partials. The only time it re-parses a file is if it changed since the last time the cache was written.

**Comment by chriseppstein** [comment]
The cache of the primary files is the generated css files. I don't see the
point in caching them. But if you want to make a patch and show a measurable
speed up we'll merge it in.

**Comment by Zakay** [comment]
About it being slow: @nex3
I am currently working on a new project, so style wise its very small, but even so.
Currently the project have about 30 sass files which together are about 2000 rows of very simple sass.
For every file it takes about 100-200 ms to compile, 3-4 seconds for all of them. If I concatenate them together before I do the sass compilation it takes 1 second which is more ok. The just this experiments shows me that the tear-up/tear-down takes most of the time, but even the compilation takes time.

This might feel ridiculous complaining about seconds, but when you work with a project and you compile all the time these seconds are getting annoying. And this get a lot worse when working with a project that has hundreds of sass files. I have another project where I need to wait almost 30 seconds.

About cached sass files: @chriseppstein
All our sass files are compiled and concatenated in a specific order into "all.css", so I don't have the css file anywhere.
That way if sass cached them separately the speed of compiling the all.css would go much faster, if you only changed some of the files. But this issue isn't that important anyway, if you manage to speed the compiler.

**Comment by chriseppstein** [comment]
@Zakay given what you said about your structure, all of the imported files should be cached. How are you compiling your stylesheets? Are you running the sass compiler once for each file? Please show us how you get your measurements.

**Comment by Zakay** [comment]
@chriseppstein Yes, I am running it once per file, but I just found out that is running using stdin, so the reason why there is no cached file is because the compiler doesn't know the filename. This is because the sass files goes through another filter before passing sass compiler. And of course coming from stdin the compiler doesn't know if the file has any changes.

So I am in the process to re-do this step so that I can call the compiler with a filename instead.

Would be nice anyway to profile the compiler, and optimize it :)

**Comment by Zakay** [comment]
@chriseppstein I now changed our environment to use the filename instead, so the compile cache files now exist, BUT next time i execute the compilation I get the same results, no speed improvments at all, which is very weird.

**Comment by chriseppstein** [comment]
@Zakay You're still running it once per file? Most of the time is spent loading ruby and the sass program. You should let sass compile all your files with one call using the `--update` option.

**Comment by Zakay** [comment]
@chriseppstein the problem is that if you have a project that combines other style sheets that SASS, then you really can't use the update nor the watch command.

So, even if you have the compiled cache files it still takes the same amount of time compiling each file, which tells me that the compilation itself isn't slow but the tear-up or tear-down, but I'am guessing it the first setting up process which is slow in the SASS compile script. Is there a way to profile ruby? I haven't coded any ruby at all.
I would recommend profiling it and check where/what it spends most of the time, this process can probably be optimized a lot.

**Comment by chriseppstein** [comment]
We have done a lot of profiling on this project. But you have not provided us with a clear explanation of your problem yet. Please post how it is you are determining the speeds and the exact styles and steps you are using when you compile. So far I am not convinced this is a bug.

**Comment by Zakay** [comment]
Well, I don't think its a bug either, its just that I think ~249ms for compiling one file is very slow, especially when you have a project hundreds of files. In a project where you have mixed css/sass and you can't run the update/watch command.
And I wanted to report this as an issue. 

Example of one of these files, which takes 133-249ms on a Intel i7, 1.8 GHz, 4GB Ram, SSD:

```
/* Reseters */
body
    margin: 0
    padding: 0
    font: 12px/1.2 "Gill Sans", sans-serif

h1, h2, h3, h4, h5, h6
    margin: 10px 0 5px
    font: bold 24px/1.2 "Gill Sans", sans-serif

h2
    font-size: 20px

h3
    font-size: 18px

h4
    font-size: 16px

h5
    font-size: 14px

h6
    font-size: 12px

p
    margin: 0 0 10px

ul, ol
    margin: 0 0 10px 30px
    padding: 0

dl
    margin: 0

form
    margin: 0
    padding: 0

label, select
    cursor: pointer

input, select
    vertical-align: middle

input[type="checkbox"], input[type="radio"]
    cursor: pointer

table
    empty-cells: show

td, th
    vertical-align: middle

/* Default link behaviour */
a
    text-decoration: none
    &:hover
        text-decoration: underline

    &:focus
        outline: 0 none
        -moz-outline: 0 none
    &:active
        outline: 0 none
        -moz-outline: 0 none

    img
        border: 0

/* General */
.hidden
    display: none

.inline
    display: inline

.inline_block
    display: inline-block

.error
    color: #F00
    text-shadow: #FEE 1px 1px 0px
    font-weight: bold
    font-style: italic
    font-size: 12px
    padding: 0 0 8px 0

.message
    text-align: center
    padding: 10px
    border: 1px solid #ccc
    font-size: 14px
    margin-bottom: 5px
    background: #ffffee
    background: -moz-linear-gradient(top, #ffffee 0%, #fffcd1 100%)
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffee), color-stop(100%,#fffcd1))
    background: -webkit-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
    background: -o-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
    background: -ms-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffee', endColorstr='#fffcd1',GradientType=0 )
    background: linear-gradient(top, #ffffee 0%,#fffcd1 100%)
```

**Comment by chriseppstein** [comment]
I agree that is slow. And it may be a bug. Or it may be that you are doing something wrong.  I will ask you one more time: please show us how you are compiling your project so that we can diagnose your issue.

**Comment by Zakay** [comment]
For that file, I just run the command "time sass general.sass" in the terminal.
Using (Sass 3.1.2 (Brainy Betty))

**Comment by ttilley** [comment]
133-249ms for one file is perfectly reasonable if you're calling sass on each file individually. most of that time has nothing to do with compiling the sass file, but with loading ruby itself, parsing the ruby code, interpreting or running on the VM, and so forth. Using your file as an example, named test.sass by itself with no cache:

```
[11:15:54][168]$ ls -a
.         ..        test.sass
[11:15:56][168]$ time sass test.sass test.css

real    0m0.207s
user    0m0.184s
sys 0m0.021s
[11:15:59][168]$ ls -a
.           ..          .sass-cache test.css    test.sass
```

Using just that number, one would assume that compiling 200 versions of that file would take 41.4 seconds (0.207 \* 200 = 41.4). However, using 200 versions of that file each with a different name in a "sass" subdirectory and output to a "css" subdirectory:

```
[11:24:48][168]$ ls -a
.    ..   css  sass
[11:24:52][168]$ ls css | wc -l
       0
[11:24:55][168]$ ls sass | wc -l
     200
[11:24:57][168]$ time sass --quiet --update sass:css

real    0m5.258s
user    0m5.109s
sys 0m0.146s
```

And on a subsequent cache-warm run:

```
[11:25:11][168]$ time sass --quiet --update sass:css

real    0m0.711s
user    0m0.647s
sys 0m0.053s
```

This is why @nex3 and @chriseppstein have suggested a workflow where you can use --watch or --update. The bulk of the time cost you're seeing can be avoided entirely.

**Comment by Zakay** [comment]
@ttilley The issue is if you have an styles not only from sass, then you really can't use the watch/update command. When you really need to re-write the entire "all.css".

But if most of the time is ruby, then you really can't do anything about it. I also reached to the conclusions that its not the compiling that is slow, but setting up the script. But what I don't know if its the setting up of the ruby environment or setting up the compiler which takes most of the time. Or maybe 3rdparty ruby libs. But as a guess I wouldn't first blame ruby itself.

**Comment by ttilley** [comment]
I'm not sure why having non-sass styles would be a problem. Can you explain the issues you're having in more detail? sass should be perfectly well equipped for dealing with mixed sass/scss/css environments. This is especially true when you consider that scss is a superset of css, and any parsable css file can be renamed to scss and just work :tm:. There is also a sass-convert utility that can convert from css, scss, and even less (mostly) to sass... Though you will need to take care where your css is commented, as the parse tree is optimized in such a way that your comments may no longer be in the right place.

**Comment by ttilley** [comment]
Just for giggles, here's a compile from sass to css and a conversion from css back to sass with diff to show you how ZOMG awesome sass is at parsing/converting. Note that most of the differences are whitespace and subtle changes in syntax where multiple forms mean the exact same thing (#ccc and #cccccc for example). In a few places the parse tree optimization even removes some redundancy from your original sass file and makes it more readable. =]

```
[11:56:04][168]$ sass test.sass test.css
[11:56:12][168]$ sass-convert --from css --to sass test.css test2.sass
[11:56:24][168]$ diff -u test.sass test2.sass
```

``` diff
--- test.sass   2011-09-13 11:55:13.000000000 -0400
+++ test2.sass  2011-09-13 11:56:24.000000000 -0400
@@ -1,12 +1,13 @@
-/* Reseters */
+/* Reseters
+
 body
   margin: 0
   padding: 0
-  font: 12px/1.2 "Gill Sans", sans-serif
+  font: 12px / 1.2 "Gill Sans", sans-serif

 h1, h2, h3, h4, h5, h6
   margin: 10px 0 5px
-  font: bold 24px/1.2 "Gill Sans", sans-serif
+  font: bold 24px / 1.2 "Gill Sans", sans-serif

 h2
   font-size: 20px
@@ -43,8 +44,9 @@
 input, select
   vertical-align: middle

-input[type="checkbox"], input[type="radio"]
-  cursor: pointer
+input
+  &[type="checkbox"], &[type="radio"]
+    cursor: pointer

 table
   empty-cells: show
@@ -52,23 +54,20 @@
 td, th
   vertical-align: middle

-/* Default link behaviour */
+/* Default link behaviour
+
 a
   text-decoration: none
   &:hover
     text-decoration: underline
-
-  &:focus
+  &:focus, &:active
     outline: 0 none
     -moz-outline: 0 none
-  &:active
-    outline: 0 none
-    -moz-outline: 0 none
-
   img
     border: 0

-/* General */
+/* General
+
 .hidden
   display: none

@@ -79,8 +78,8 @@
   display: inline-block

 .error
-  color: #F00
-  text-shadow: #FEE 1px 1px 0px
+  color: red
+  text-shadow: #ffeeee 1px 1px 0px
   font-weight: bold
   font-style: italic
   font-size: 12px
@@ -89,14 +88,14 @@
 .message
   text-align: center
   padding: 10px
-  border: 1px solid #ccc
+  border: 1px solid #cccccc
   font-size: 14px
   margin-bottom: 5px
   background: #ffffee
   background: -moz-linear-gradient(top, #ffffee 0%, #fffcd1 100%)
-  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffee), color-stop(100%,#fffcd1))
-  background: -webkit-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
-  background: -o-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
-  background: -ms-linear-gradient(top, #ffffee 0%,#fffcd1 100%)
-  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffee', endColorstr='#fffcd1',GradientType=0 )
-  background: linear-gradient(top, #ffffee 0%,#fffcd1 100%)
+  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffffee), color-stop(100%, #fffcd1))
+  background: -webkit-linear-gradient(top, #ffffee 0%, #fffcd1 100%)
+  background: -o-linear-gradient(top, #ffffee 0%, #fffcd1 100%)
+  background: -ms-linear-gradient(top, #ffffee 0%, #fffcd1 100%)
+  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffee', endColorstr='#fffcd1',GradientType=0 )
+  background: linear-gradient(top, #ffffee 0%, #fffcd1 100%)
```

**Comment by Zakay** [comment]
ok here goes:

I have multiple files, let say:
1.sass
2.sass
3.css
4.sass

And I want them to be compiled into all.css in the order 1.sass + 2.sass + 3.css + 4.sass.
When I change 3.css or any other file, I must rewrite all.css and thus need to run the compile script on each file to all.css
And that is the problem, I have to loop through the files in that order and either execute sass on the sass files or just cat to the clean css files.

**Comment by Zakay** [comment]
And yeah, sass compiles beautifly!

**Comment by ttilley** [comment]
in that scenario you have a few options. you can go the hacky route and make _three.scss a symlink to three.css if you absolutely cannot convert it to sass. then in all.sass you would have:

``` sass
@import "one"
@import "two"
@import "three"
@import "four"
```

that should just work, but it's hacky and ugly. also, your css file needs to be correct and parsable css. there are css hacks for targeting specific browsers that might parse, but not to what you had intended (comment hacks, for example).

another option would be to move the concat/compress phase out of sass and into another tool entirely. an excellent choice for handling multiple rulesets based on file change events is `guard`: https://github.com/guard/guard

using guard, guard-sass, and guard-shell, you would simply run "guard" in a directory with a guardfile like so:

``` ruby
guard 'sass', :input => 'sass', :output => 'styles'

guard 'shell' do
  watch(/\.css$/) {`some_shell_command_that_concats_or_even_compresses_your_css`}
end
```

A recently popular (thanks to rails 3.1) options is to use the sprockets asset pipeline, but that would be significantly more complex: https://github.com/sstephenson/sprockets

...I'd say the simplest option is to let sass do what it's good at, switch to using --watch or a guardfile, and have something else be responsible for concatenating or compressing your css together. If you're ok with using guard, it does make it simpler to have multiple simultaneous rulesets for multiple tools (including running your unit tests when source files change, checking the syntax of your javascript using jslint, using livereload to refresh the css in your running browser the second you save your sass/css file, etc). At the least, it'd have a process that stays resident and your speed problem goes away.

@nex3, @chriseppstein - if you have better suggestions, i'd love to hear them as well. Either way, I'd say that it's safe to close this bug. Perhaps someone with more motivation than me should make a blog post or write a wiki article. ;)

**Comment by chriseppstein** [comment]
Try this instead:

Rename your CSS files to scss.

Rename all.css to all.scss

Run sass only on all.css

The output will produce a concatenated stylesheet -- no http round trips to get all the others.

**Comment by ttilley** [comment]
I only included the complexity because he mentioned third party css earlier, which I can understand not wanting to modify. A symlink rather than rename would still allow `@import` to include the content rather than compile to a css import statement... Unless I'm talking out of my ass and it checks for the css file first.

**Comment by Zakay** [comment]
Thanx for the pointers, I am testing a couple of the tips now, if none works as I hope, then I will integrate file caching in our environment instead. It would probably speed things up on other stuff too.
