### ISSUE TITLE
:host selector

### ISSUE THREAD

**Issue by matantsu** [sass/sass#1682]
im working with polymer and to refrence the custom element from within the style you need to use the `:host` selector. 

eg:

```
:host{
   display: block;
}
```

sass won't recognize this selector and therefore this wouldn't work:

```
:host
   display: block
```

raises:

```
Properties are only allowed within rules, directives, mixin includes, or other properties.
If ":host" should be a selector, use "\:host" instead.
```

**Comment by cimmanon** [comment]
I don't understand why this is an issue.  The error tells you exactly what you need to do to resolve this.

```
If ":host" should be a selector, use "\:host" instead.
```

**Comment by matantsu** [comment]
it is an issue because `:host` should be supported. otherwise it is impossible to use `sass` with `polymer`

**Comment by cimmanon** [comment]
Sass is treating the `:host` selector the same way it treats _all_ pseudo elements/selectors.  If you don't like having to escape the colon, then I suggest you switch to scss syntax.
