### ISSUE TITLE
@extend within the same directive?

### ISSUE THREAD

**Issue by uxai** [sass/sass#1685]
I am getting this error:

```
ember_1 | File: /app/tmp/tree_merger-tmp_dest_dir-u7e8wD3d.tmp/app/styles/_mobile.scss (39)
ember_1 | You may not @extend an outer selector from within @media.
ember_1 | You may only @extend selectors within the same directive.
```

When I comment out the line mentioned it works fine...however I have a class directly below that extending the same class? I also do not have any media queries from the class being extended or the class extending it..

What does this error even mean? All the files are in the same directory that they are being extended from, and why am I just now getting this error.

**Comment by nex3** [comment]
Without showing us code that's producing an error you don't understand, there's not really any way for us to explain what's going on to you.
