### ISSUE TITLE
Error using an alias for map-get

### ISSUE THREAD

**Issue by ghost** [sass/sass#1686]
Hi,
I've wrote this function to access to the map-get function (it may seem a bit strange, but I personally find the shorthand useful) :

``` sass
@function mg($map, $key) {
  @return map-get($map, $key);
}
```

If I call it on a simple map, everything works well, for example:

``` sass
$foo: ( name: "foo", value: "bar", number: 13 );
@debug mg($foo, number);
// ==> 13
```

But when things become more complicated I get an unexpected error.
Here's an example:

``` sass
$breakpoints: (
  ( name: "small", up_to: 0 ),
  ( name: "medium", up_to: 676px ),
  ( name: "large", up_to: 1024px )
);

@debug map-get(nth($breakpoints, 1), name);
// ==> small

@debug mg(nth($breakpoints, 1), name);
// ==> Error: (name: "small", up_to: 0) isn't a valid CSS value.
//        on line 379 of core/utilities/_utilities.scss
//        from line 8 of core/_core.scss
//        from line 31 of heartbrick.scss
//  Use --trace for backtrace.
```

What can I do? Is it a sass bug? Where am I wrong?
_(Sorry for my english, I'm trying to write as best as I can)_
I'm using sass 3.4.13 (Selective Steve).

**Comment by davidkpiano** [comment]
Can't reproduce issue. This usually occurs when a function (in this case `mg()`) is not defined. In your last example, it looks like you haven't defined `@function mg(...)` yet.

**Comment by ghost** [comment]
The example I cited was some example I've made to test thing before posting this issue. My situation is the following:

I have a file ( `project direcotry/core/utilities/_utilities.scss` ) whit the definition of `@function mg() ...` (like in the first post). That file is included within another file (`_core.scss`) that is included by another file (`heartbrick.scss`). I've included heartbrick.scss in another file (`main.scss`), and then I've use a function (`get-breakpoint`) that use `mg`.

The strange thing is that if I use `get-breakpoint` with `mg` I get the error, if I replace all the call to `mg` with `map-get` I haven't any errors.

Folder tree (partial):

```
project directory/
├── core/
│   ├── _core.scss
│   └── utilities/
│       └── _utilities.scss
├── heartbrick.scss
├── main.scss
└── _variables.scss
```

main.scss:

``` sass
@import 'heartbrick';
//...
$my_variable: my_function( get-breakpoint(medium), $my_parameter );
// ...
```

heartbrick.scss:

``` sass
// ...
@import 'variables';
@import 'core/core';
```

_variables.scss:

``` sass
// ...
$breakpoints: (
  ( name: "small", up_to: 0 ),
  ( name: "medium", up_to: 676px ),
  ( name: "large", up_to: 1024px )
);
```

_core.scss:

``` sass
@import 'utilities/utilities';
// ...
```

_utilities.scss:

``` sass
// ...
@function get-breakpoint($breakpoint) {
  @each $breakpoint in $breakpoints {
    @if $breakpoint == mg($breakpoint, name) {     // These two lines trigger the error
      @return mg($breakpoint, up_to);         // now, I've changed `mg` to `map-get`
    }
  }
  @return false;
}
// ...
@function mg($map, $key) {
  @return map-get($map, $key);
}
```

I'm sure that when I get the error, the function `mg` was defined. In the last example, for brevity, I haven't wrote it.

I'm working on a project with a great number of functions and mixin', and most of them use `mg`, so when I call `get-breakpoint` I'm sure that `mg` is defined.

However, if `mg` wasn't defined, the error message would be different, right?

Now I've change some call to `mg` to `map-get` and everything works fine. 0 errors.
I've spent a couple of hour today on this issue, but now I successfully manage to get all the thing works properly :)

_(Sorry for my english, I'm trying to write as best as I can)_

**Comment by ghost** [comment]
Now I've tried to create a new file, and put in all the example from my first post. I cannot reproduce the error, but when I tried to compile before the project I've got the error.
I even manage to correct the error, so for now I close this issue.

If I ever get another error related with this issue, I'll manage to test more, and then posting here.
