### ISSUE TITLE
Passing variables from the command line or programmatically

### ISSUE THREAD

**Issue by milesj** [sass/sass#1692]
I maintain a project that compiles two types of Sass outputs, a LTR (default) and a RTL version. Currently the process is rather lengthy, as I have to compile the LTR first, then edit the Sass files and modify specific variables to enable RTL, then compile RTL, and then reverse all the Sass modifications.

It would be really awesome if we could pass Sass variables from the command line and make them globally available, something like:

```
sass --variable="rtl=1" toolkit.scss toolkit.css
```

Or if that's too... janky, perhaps support for it programmatically? (Ignore my Ruby as I don't know it).

``` ruby
render = Sass::Engine.new(File.read(original_file_name), {
  cache: true,
  syntax: :sass,
  style: :compressed,
  variables: {
    rtl: true
  }
}).render
File.write(output_file_name, render)
```

**Comment by nex3** [comment]
This isn't something we intend to add to the command-line API, but it is possible to do programmatically by manually running `Sass::Tree::Visitors::Perform` with a `Sass::Environment`.

**Comment by milesj** [comment]
Thanks for the response. Do you have an example of this in action?

**Comment by nex3** [comment]
I don't know of one off the top of my head.

**Comment by cirosantilli** [comment]
Related: https://stackoverflow.com/questions/15153613/provide-sass-variables-definitions-on-command-line
