### ISSUE TITLE
#{&} operaotr

### ISSUE THREAD

**Issue by yonatanmn** [sass/sass#1698]
I had an [issue](https://github.com/sass/sass/issues/1695), and got [this ref](https://github.com/sass/sass/issues/1369) as an answer.
but then I realized this:

```
.grand-grand{
  .grand-parent{
    .parent {
      color: green;

      @at-root h2#{&} { color: red; }

      h2#{&} { color: blue; }

      &.someClass{ color:orange; }
    }
  }
}
```

will give this output: (sassmeister, sass@3.4.12)

```
.grand-grand .grand-parent .parent {
  color: green;
}
h2.grand-grand .grand-parent .parent {
  color: red;
}
.grand-grand .grand-parent .parent h2.grand-grand .grand-parent .parent {
  color: blue;
}
.grand-grand .grand-parent .parent.someClass {
  color: orange;
}
```

Though the desired output should be the same for `orange` and `blue`: 

```
.grand-grand .grand-parent h2.parent{
  color: blue;
}
```

**Comment by cimmanon** [comment]
Why did you open a new issue for this?

**Comment by yonatanmn** [comment]
beacuse the other one is duplicated, and had a good anwser

**Comment by nex3** [comment]
This is exactly what `@at-root` is for.

**Comment by yonatanmn** [comment]
That I understand, giving the `at-root` example was just to demonstrate that it's not a solution here. the problem I'm talking about is with the parent operator (`#{&}`), which doesn't give the desired output, like it would give without the curly brackets, but instead copies the entire heritage, like I showed.

**Comment by nex3** [comment]
`#{}` does literal string interpolation. If you want more advanced selector manipulation, use the [selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions).
