### ISSUE TITLE
make --watch work with symlinks 

### ISSUE THREAD

**Issue by timkelty** [sass/sass#17]
It appears that if I symlink a folder with sass files in it into that folder that I'm watching, changes aren't detected. It would be great if they could be!

**Comment by nex3** [comment]
What operating system are you using? What messages (if any) does sass print out when you start `--watch`?

**Comment by timkelty** [comment]
Mac OSX

When I start watching I get:

`>>> Sass is watching for changes. Press Ctrl-C to stop.
Warning: Unable to load CarbonCore. FSEvents will be unavailable.`

After that it gives me the regualar 'change detected to...' messages, but not with symlinked stuff.

**Comment by timkelty** [comment]
and runny ruby via RVM, btw.

**Comment by timkelty** [comment]
I was able to get rid of the carboncore warning by following Brandon's instructions here:
 http://groups.google.com/group/compass-users/browse_thread/thread/df7d9d0da9ec1eb1

However, symlinked things still don't seem to work with --watch

**Comment by medwards** [comment]
Hitting this as well. If I had to guess ::Sass::Plugin.watch doesn't confirm that a file in its list of files is a symlink vs a normal file.
UPDATE: I'm pretty sure this is a bug in FSSM.

**Comment by nex3** [comment]
I'm closing this since we've moved off of FSSM.

**Comment by svivian** [comment]
I am still experiencing this bug, changes in files that are inside symbolic link folders are not being detected. No errors or anything (I was getting the "Listen has fallen back to polling" message but fixed it by installing `listen`).

I'm on Ubuntu 12.04.

**Comment by nex3** [comment]
@svivian I can't reproduce this. It works for me on Ubuntu 12.04 using both the polling and the rb-inotify backend.

**Comment by mgol** [comment]
It doesn't work for me, too. My config is that I have the `styles` folder within which I have a symlink named `other` to a directory containing another `main.scss`. In my `styles/main.scss` file I have `@import other/main.scss`. It doesn't matter if I invoke watch using:

```
$ compass watch --trace .
```

or:

```
$ compass watch --trace styles/main.scss styles/other/main.scss
```

changes in the second file are not detected.

**Comment by mgol** [comment]
BTW, I'm on OS X 10.8.3.

**Comment by mgol** [comment]
I reported it to compass: https://github.com/chriseppstein/compass/issues/1110

**Comment by nex3** [comment]
Okay, I can reproduce this as long as the symlink is pointing outside of the directory being watched. For example:

```
/
  /style
    /other -> ../other
    main.scss
  /other
    main.scss
```

I think this is a listen issue. I've reported it as guard/listen#71.

**Comment by nex3** [comment]
This is now being tracked on guard/listen#25. I'm going to close it here, but feel free to re-open it if the listen folks decide that they won't implement it there.
