### ISSUE TITLE
@content blocks in imported files

### ISSUE THREAD

**Issue by anthonyshort** [sass/sass#170]
Thought I'd play around with the alpha tonight and noticed that when I try to import files with mixins that have @content I get an error about the mixin not supporting @content. Here's a simple example made with 2 files

Our media.scss file

```
@mixin mobile {
    @media only screen and (min-width : 320px) and (max-width : 480px) {
        @content;
    }
}
```

Then the other file that imports it.

```
@import 'media';

@mixin tablet {
    @media only screen and (min-width : 320px) and (max-width : 480px) {
        @content
    }
}

// This will work as it's using a local one
#id {
  @include tablet {
    .class {
      color:red;
    }
  }
}

// This will fail :(
#id {
  @include mobile {
    .class {
      color:red;
    }
  }
}
```

Interestingly, that mobile mixin there will throw an error with or without a content block added to it, but it will work if there are no styles within the content block.

Tested using 3.2.0.alpha.21.

**Comment by nex3** [comment]
This is fixed by ec1346f41691e329c04558e37ccccb4254f2365f.
