### ISSUE TITLE
mac osx watch has above average cpu usage

### ISSUE THREAD

**Issue by nathraQ** [sass/sass#1710]
**The data**
**sass version:** 3.4.13
**osx:** 10.10.3
**ruby version:** 2.2.2p95

**The problem**

The cpu usage goes up to 90% and above.
I stumbled up on that problem when I wrote a script to watch multiple folders. My cmd looked something like that  `sass --watch path1/to/scss/:path1/to/css/ path2/to/scss/:path2/to/css/`with about 20 folders. The command works and on a ubuntu it doesn't take any relevant cpu usage. on my mac it used about 90% of the cpu. First thought was that it's because of the amount of watched folders. But if I compare   `sass --watch 6level/deep/path/to/scss/:6level/deep/path/to/css/` to `cd 6level/deep/path/to/; sass --watch scss/:css/` the first on also uses 90% of the cpu the second one "only" 10%.

To me that is a perfomance bug

**Comment by nathraQ** [comment]
Is anything missing to reproduce this behaviour?

**Comment by c9s** [comment]
same here

**Comment by nathraQ** [comment]
happy to see this it not only my problem. As additional observation, this problem does not appear with ubuntu 14.04. Can it be that de overly old guard version is the problem, as I don't get that message when I start sass on ubuntu

**Comment by nex3** [comment]
This is a good thing to report to the [guard/listen](/guard/listen) folks. They maintain the library we use to watch for changes on the filesystem; there's not much Sass can do if the filesystem watcher is spinning a lot. That said, this sounds like it may just be an issue of watching too much stuff; you may need to work around it by `cd`ing into the directory manually for now.

**Comment by actuallymentor** [comment]
Getting 40-60% CPU usage on an i7 (ruby process specifically) as a result of sass --watch.

EDIT: Debugging complete. Run 'gem install listen'. For whatever reason the listen gem is not a dependency anymore which makes sass's ruby process go haywire.

**Comment by chriseppstein** [comment]
@actuallymentor Recent versions of listen have a _lot_ of ruby dependencies. We ship a version of listen that is older and did not have as many dependencies. Ideally, we'd use a lighter weight library, and extract the CLI to it's own gem so people who are just using the core compiler can do so without all the CLI dependencies.

**Comment by actuallymentor** [comment]
@chriseppstein lighter dependencies is great, but not if it makes my i7 spin half of it's power to the ruby process :)

I'd gladly trade a sucky dependency structure for battery life and a silent computer. I literally only noticed something was up because it was blowing like an airplane while just working in sublime.

**Comment by chriseppstein** [comment]
@actuallymentor I hear you. Fortunately, there's a work around (installing a newer version of listen that we will use instead), while you wait for us to refactor.

**Comment by nex3** [comment]
Specifically, the dependencies in the newer version of listen are incompatible with Ruby 1.8.7, which Sass still supports because it was installed by default on OS X until relatively recently.
