### ISSUE TITLE
Inconsistent behaviour across versions/releases

### ISSUE THREAD

**Issue by hypeJunction** [sass/sass#1711]
This is more of an observation than a bug report, but I think you ought to consider the well being and the mental health of all the teams working with sass gems. The more recent releases cause a lot of headache, the behaviour we rely on keeps changing from one release to another. As a result we all have to coordinate which version of the gem to use across multiple work stations. If one of us is working on multiple sass projects that use different gem version, we have to switch back and forth.

Gem upgrades result in a lot of diff noise. Introduction of the @charset declaration now breaks view systems that use aggregators. And so on. Perhaps for every new feature you introduce, you should provide an option to switch it of via config.

**Comment by nex3** [comment]
This is a good thing to bring up on the mailing list, but not the issue tracker.

**Comment by hypeJunction** [comment]
Sure.
In case anyone is having similar problems, one possible solution is to use Gemfile to lock your project gem versions and to use bundle gem.
