### ISSUE TITLE
Sass::SyntaxError: Invalid CSS after "@charset "UTF-8"": expected "{", was ";"

### ISSUE THREAD

**Issue by alexwhitman** [sass/sass#1719]
Using sass 3.4.13 in a rails app I'm hitting an error when running `rake assets:precompile`.

The error is `Sass::SyntaxError: Invalid CSS after "@charset "UTF-8"": expected "{", was ";"`.  I've gone through all of the app assets and all of the assets in gems and removed any instance of `@charset "UTF-8";` and the error still occurs.

Can anyone point me towards where I should be looking next or what I should be looking for?

**Comment by nex3** [comment]
Can you reproduce this without Rails in the loops? If not, I'm pretty confident this is an issue with the Rails infrastructure and not with Sass.

**Comment by timbodeit** [comment]
Seeing the same issue with jekyll when prefixing document with '---\n---' front matter.

**Comment by chriseppstein** [comment]
@timbodeit jekyll should strip the front matter before passing the file to Sass. Please file a bug with that project.
