### ISSUE TITLE
map_values not working for maps created with braces

### ISSUE THREAD

**Issue by thany** [sass/sass#1727]
Please consider this piece of Sass:

```
$spacings:
  (top:    0.5rem)
  (right:  0.5rem)
  (bottom: 0.5rem)
  (left:   2.7rem)
;

@debug map_values($spacings);
```

Spews out this error on the console:

```
$map: ((top: 0.5rem) (right: 0.5rem) (bottom: 0.5rem) (left: 2.7rem)) is not a map for `map_values'
```

This might be _technically_ correct and all, but I'd still expect this to work, because `$spacings` is a map without anything special or weird, as far as I can tell.

Now without braces:

```
$spacings: (
  top:    0.5rem,
  right:  0.5rem,
  bottom: 0.5rem,
  left:   2.7rem
);
```

Works fine. But I prefer the first notation. Doesn't require the error prone comma-at-the-end-of-each-line-except-for-the-last-one notation.

This is on Sass 3.4.13, Gem system 2.4.7, Ruby 2.1.3p242, Windows 7 x64.

**Comment by cimmanon** [comment]
So you're asking to break the syntax of lists because you prefer to not have to worry about commas?  Because what you're creating is a list of mappings.

**Comment by thany** [comment]
I didn't ask for that, that's your interpretation.
It looked pretty map-ish to me... I've even used maps like this before.

My reason for not wanting to "worry about commas" is just version control. You probably know what happens to version control when adding one to the map.

You could also make commas optional in maps, just like they are in lists. Just an idea. So something like this:

```
$spacings: (
  top:    0.5rem
  right:  0.5rem
  bottom: 0.5rem
  left:   2.7rem
);
```

Makes version control cleaner.

**Comment by nex3** [comment]
This isn't the syntax for maps. Maps already have a syntax, and it's not that. That syntax already means something, and it's not a map. We're not planning on changing it.

**Comment by chriseppstein** [comment]
You created a list of maps. I think the syntax you used to use was a list of lists:

``` scss
$spacings:
  (top    0.5rem)
  (right  0.5rem)
  (bottom 0.5rem)
  (left   2.7rem)
;

@each $k, $v in $spacings {
  @debug $k;
  @debug $v;
}
```

Note that without the colons, a list of lists acts a lot like a map in an `@each` directive.

**Comment by chriseppstein** [comment]
Another point: Sass allows trailing commas in maps and lists for the source control issue you mentioned.

``` scss
$spacings: (
  top:    0.5rem,
  right:  0.5rem,
  bottom: 0.5rem,
  left:   2.7rem,
);

@each $k, $v in $spacings {
  @debug $k;
  @debug $v;
}


$l: (
  1,
  2,
  3,
);

@each $e in $l {
  @debug $e;
}
```
