### ISSUE TITLE
@extend issue combining :last-child with :after

### ISSUE THREAD

**Issue by gxclarke** [sass/sass#173]
The following:

```
.block:after { content: "abc"; }
    .test:last-child {
   @extend .block;
}
```

Generates:

```
.block:after, .test:after:last-child { content: "abc"; }
```

The `:last-child` pseudo-class and the `:after` pseudo-selector need to be reversed for this to be valid.

**Comment by hagenburger** [comment]
**+1**

This also makes it impossible to use Compass’ `pie-clearfix` as a global extendable class:

```
.pie-clearfix { @inlcude pie-clearfix; }
.something:last-child { @extend .pie-clearfix; }
```

**Comment by nex3** [comment]
I believe this is fixed now.
