### ISSUE TITLE
Feature Suggestion: Exposing Current CSS Properties to Mixins/Functions via `$this` Map

### ISSUE THREAD

**Issue by jdsteinbach** [sass/sass#1737]
## Feature

Give Sass mixins / functions the ability to find & use CSS properties in the selector block they're used in: with `$this`\* & Sass map syntax.

\* _This map name works & seems transparent, but if there's a better option, I'm not tied to this name._
## Code Examples

The following code blocks present sample syntax for `$this` and a simple (simplistic, probably :smile:) use case.
### Syntax

What I'm suggesting could be handled in a reasonably simple way: `$this` is a Sass map with its first key-value pair as `selector: '.current-selector .string'` and the other key-value pairs being CSS property-value pairs. This exposes `$this` data through familiar API: Sass map functions.

I could see adding a `parent: ()` map to `$this` (with subsequent "grandparents" as nested parent maps). These maps would be created by explicit Sass nesting, not by any heavy CSS scanning work.

```
.box {
    padding: 1em;
    margin: 1em auto;
    font-size: 1.2rem;

    &-title {
         color: red;
         font-weight: bold;

          a {
              text-decoration: none;
              color: inherit;

              // $this -- see below:
          }
    }
}
```

```
$this: (
    selector: '.box-title a',
    text-decoration: none,
    color: inherit,

    parent: (
        selector: '.box-title',
        color: red,
        font-weight: bold,

        parent: (
            selector: '.box',
            padding: 1em,
            margin: 1em auto,
            font-size: 1.2rem
        )
    )
);
```

This would expose parents via `map-get($this, parent)`. The other option I'd find useful is $map[dot]key. This would be (IMO) a big win for all Sass map handling, but that's a separate issue, I suppose. 😀
### Use Case

```
@mixin em-padding($this) {
    $fs: map-get($this, 'font-size');
    @if unit($fs) == "px" {
         padding: 20px/$fs*1em 10px/$fs*1em;
    }
}

.box {
    font-size: 40px;
    @include em-padding($this);
}

/* Expected output */

.box {
    padding: .5em .25em;
}
```
## Potential Issues

I can see some potential issues related to supporting a feature like this:
### Handling inherited properties

This is a follow-up feature request I could see devs asking for: "This element inherited its font-size from its parent: how can I access & use that value?" I'm all about saying no to that request. Unless it's in a Sass nesting context. As described above, I'd like to add that as a nested `parent: ()` map inside of the `$this` map.
### Error reporting

I think most of the existing Sass errors will make this manageable: can't math a string, etc. As with maps, validation could be left up to the user: `@if map-has-key($this, 'font-size')` etc.
### Properties written after the `@include`

Ideally, the entire selector block would be `$this`; writing a property after calling a `$this`-dependent mixin/function would produce the same code as writing that property before the mixin/function. Having the property written after a `$this`-dependent mixin would override any attempt to output that same property with the mixin.

That brings up the issue of devs attempting to write "recursive" mixins with `$this`:

```
@mixin increase-padding-top($this) {
    @if map-has-key($this, 'padding-top') {
        padding-top: 1.5 * map-get($this, 'padding-top');
    }
}
```

The issue here is that properties defined after the mixin is called would affect its output, but also override it. One answer to this is "refactor your mixins so you don't need to override their output like that." Another answer would be to throw an error: "You can't write recursive property mixins" but that would require a LOT more contextual awareness than just exposing an object & letting devs do what they need to. I'm leaning toward calling this order/override issue a "user error" and teaching people to use the tool correctly.
### Handling `!important` properties

One obvious thing: `!important` should not be given a `$this`-specific function (one that would encourage devs to use this CSS flag for a Sass-y purpose). `!important` will need to be stripped out in order to treat the CSS values as the values/strings/lists they are. If we're going to treat `$this` as an object and make devs use it thoughtfully, there's no reason to "re-insert" `!important` - they're writing their mixins/functions & can include it there if they've got good reason to do so. 
### Properties set by other mixins in the selector block

If I set the current `padding-top` with a mixin that calculates a number based on a vertical rhythm measurement and `$this->font-size`, then try to use a `margin` mixin that relies on `$this->padding-*` values, will generated values be available in `$this`? Or worse, two competing `$this`-dependent mixins attempting to set & use matching properties. I'm thinking, "no, `$this` only gets explicitly written values." 

\* _Yep, I know `$map->key` isn't Sass syntax; just using it as shorthand in this issue._

I've been working through some use cases (mostly type-scale & vertical rhythm related) where this feature would be really useful. I'm a front-end dev and have no idea how to actually write this for the compiler, but I wanted to make a recommendation here, now that we're almost entirely at Ruby/LibSass feature parity & getting ready for new features. Thanks!

**Comment by nex3** [comment]
Since Sass operates at compile-time, the only way we could possibly do this is to define "current property" as you do, as "a property in the lexically-enclosing block". However, this is _very different_ than the CSS definition of "a property on the underlying HTML element". Directly exposing that difference is a recipe for serious confusion, as well as a violation of our general philosophy to try to define Sass semantics more in terms of the styling of a page than the manipulation of a syntax tree.
