### ISSUE TITLE
Error with map-merge

### ISSUE THREAD

**Issue by mwean** [sass/sass#1738]
I'm trying to use the `map-merge` function, and I'm getting an error: 

``` scss
map-merge((foo: 1), (bar: 2));
```

``` sh
$ sass --version
Sass 3.4.14 (Selective Steve)

$ sass my_file.scss
Error: Invalid CSS after "...: 1), (bar: 2))": expected "{", was ";"
```

However, if I try the same thing in the interactive shell, it works, but only if I omit the semicolon.

Here's a Sassmeister example: http://sassmeister.com/gist/a3a3c81b75412d8275a4

**Comment by cimmanon** [comment]
What you're doing is generating invalid CSS, and Sass won't let you.  Not sure what you're trying to accomplish here, but if you want to debug it, use the `@debug` directive.

``` scss
@debug map-merge((foo: 1, bar: 2), (baz: 3));
@debug map-merge(("foo": 1), ("bar": 2));
```

**Comment by mwean** [comment]
Ah! I thought it merged in-place! All I needed to do was assign it to a variable. Maybe we should update the documentation because the examples didn't make it clear to me that I had to do that.
