### ISSUE TITLE
Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by burlesona** [sass/sass#174]
Using Sass 3.1.7 and 3.2.0.alpha.21:

Any file I create with an @ symbol in it throws this error. This is in Mac OS 10.7.1, using a completely empty gemset with nothing in it except haml and sass.

Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8

For example:

```
#test.scss
@import "partial";

#partial.scss
div { color: #000; }

#shell
sass test.scss
=> Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8
Use --trace for backtrace.
```

I checked a dozen times, the files I've tested this against are all UTF-8, there is no reason any conversion should be required in the first place. No idea how to fix this problem.

**Comment by burlesona** [comment]
Nevermind, fixed.

**Comment by thornbird** [comment]
would you mind to write how do you fix that?
