### ISSUE TITLE
Extending placeholder in placeholder

### ISSUE THREAD

**Issue by franciscop** [sass/sass#1740]
I am trying to extend one placeholder within another. Right now [I have this](https://github.com/picnicss/picnic/blob/dev/plugins/checkbox/_plugin.scss):

```
// Define it for the element checkbox
[type=checkbox] {
  @extend %checkbox;
  }
```

Then, [the definition of %checkbox is](https://github.com/picnicss/picnic/blob/dev/plugins/checkbox/_class.scss):

```
%checkbox {
  @extend %radio;
  // more rules
  }
```

Finally, [`%radio` is defined as](https://github.com/picnicss/picnic/blob/dev/plugins/radio/_plugin.scss):

```
%radio {
  // ...
  + * {
    // ...
    &:before,
    &:after {
      // ...
      }
    }
 }

[type=radio] {
  @extend %radio;
  }
```

The expected behaviour is that `[type=checkbox] + *` is among the output css. However it cannot be found anywhere there. On the other hand, if I write this in the first statement:

```
// Define it for the element checkbox
[type=checkbox] {
  @extend %radio;
  @extend %checkbox;
  }
```

It works as expected. This is a really strange behaviour, any idea why?

**Comment by franciscop** [comment]
Unfortunately I wasn't able to reproduce it [**in jsfiddle**](http://jsfiddle.net/franciscop/n0qfcf87/) so it might have to do with my code. However, it compiles perfectly.

**Comment by nex3** [comment]
[Works for me](http://sassmeister.com/gist/8fe83e4c6760d75e3452).
