### ISSUE TITLE
Is there a possibility to reset Sass for a particular folder?

### ISSUE THREAD

**Issue by lukaskoeller** [sass/sass#1741]
Normally, when I'm working with Sass, my projects are placed in my Dropbox folder (win 7, 64bit). Because of the amount of storage I switched to Google Drive.
First time I tried that (sass --watch sass:css) the cmd just compile the files onces but didn't log any changes after that (didn't log and didn't compile).

At any time I use --trace inside Google Drive but interrupted it with 'ctrl + c' before I updated sass. I'm not an expert but I can't imagine, that this could be the origin of the problem.

Windows 7 64bit
Sass 3.4.14
Ruby 2.2.2

Now I tried the same with my Macbook (Yosemite 10.10.3) and everything works fine...
Is there any possibility to set sass to the basic settings or something like this?

Just reinstalled Ruby and Sass on Windows but nothing changed.

I deleted the version of the folder from Google Drive and copied the old version from Dropbox to Google Drive again. Everything worked fine. But I didn't know what changed that --watch didn't worked any longer.

**Comment by lukaskoeller** [comment]
Now i tried the same with my Macbook (Yosemite 10.10.3) and everything works finde...
Is there any possibility to set sass to the basic settings or something like this?

**Comment by nex3** [comment]
This sounds like something to bring up with [guard/listen](/guard/listen), the library that Sass uses to watch for filesystem changes. There are certain sorts of filesystems that just don't work well with watching, though, so you may have to pass `--poll` to get watching to work.

**Comment by lukaskoeller** [comment]
Look's like `--poll` doesn't work :( It return an error and logs I should use `--trace` but I guess this was the reason why I run into this problem.

**Comment by nex3** [comment]
Please include the error and stack trace you get when you use `--poll`.

**Comment by lukaskoeller** [comment]
`>sass --poll`

The error is as followed: `OptionParser::InvalidOption: invalid option: --poll`
`Use --trace for backtrace.`

**Comment by nex3** [comment]
Are you sure you're actually using Sass 3.4.14? That version _definitely_ supports the `--poll` option. Try running `sass --version` to see what version Sass thinks it is.

**Comment by lukaskoeller** [comment]
`Sass 3.4.14 <Selective Steve>`

![sass](https://cloud.githubusercontent.com/assets/10390627/8762031/713dbbc8-2d6d-11e5-8239-f3a7ae2ac31d.PNG)

**Comment by lukaskoeller** [comment]
Sorry that I have to asked for help another time but it would be very important to me to get this problem fixed. I've just tried to work on another project with sass and ran into some problems.
I've tried `gem uninstall listen` and `gem install listen` but this just brought me to another error log:
`NoMethodError: undefined 'start' for #<Thread:0x3031a58>
Use --trace for backtrace`

I would be very pleased if anyone could help me out!

**Comment by lukaskoeller** [comment]
This may helps out. Looks like two versions of sass are installed. How can I uninstall the older version? Maybe that solve the problem.
And btw: How to downgrade listen, I've already read about a bug with guard listen 3.x?
![sass](https://cloud.githubusercontent.com/assets/10390627/9276707/e50df5ac-42a5-11e5-9788-94de3f51eb8d.PNG)

**Comment by lukaskoeller** [comment]
Now, I've deleted the older sass version and downgraded listen but it still not work:
![sass](https://cloud.githubusercontent.com/assets/10390627/9277338/afa07f9e-42a9-11e5-8409-382843d455b8.PNG)

**Comment by nex3** [comment]
Try uninstalling `listen` entirely.

**Comment by lukaskoeller** [comment]
That really helped out! Thank you soo much for your support!

**Comment by lukaskoeller** [comment]
Mhh...Now sass doesn't listen any longer for changes (Although that worked the days before very well (after uninstall `listen`)). Any idea? Reinstall `listen` doesn't helped
