### ISSUE TITLE
Windows only bug?

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [sass/sass#1743]
Can anyone double check to see if this is a bug? On Windows: 

<pre><code>$varA: 18px;
$varB: 13px;
$varC: $varA / $varB;
 
a {
        min-height: $varC + 0em;
}</code></pre>

I get "Incompatible units: 'em' and 'px/px'". Changing the 0em to 0px, simply gives "Incompatible units: 'px' and 'px/px'". This does not show up on OS X running the same Sass version. I've tried 0.9.6 and 3.1.2.

**Comment by KittyGiraudel** [comment]
What do you mean with:

> I've tried 0.9.6 and 3.1.2.

**Comment by scottdraves** [comment]
i believe those are libsass versions.

**Comment by KittyGiraudel** [comment]
LibSass is inversion 3.2.5 and Node-Sass is in version 3.2.0. I'm not sure...

**Comment by DiegoAlbertoTorres** [comment]
Just tried most recent node-sass (3.2.0) with libsass 3.2.5.  Seems that the error output is gone, but Sass is still hanging. Will try to find out where it is hanging...

**Comment by mprins** [comment]
@DiegoAlbertoTorres if you're not using (ruby) Sass but (node) libsass this is in the wrong tracker. Please close this and report in [sass/node-sass](https://github.com/sass/node-sass/issues)

**Comment by DiegoAlbertoTorres** [comment]
Woops. Sorry about that.
