### ISSUE TITLE
Code in comment is parsed

### ISSUE THREAD

**Issue by lpijet** [sass/sass#1746]
Following code produces error: "Error: Undefined variable: $i"

```
/* @for $i from 2 through 40 {

  &:nth-child(#{$i}) {

    transition-delay: .8s * ($i * 0.13);
  }
} */
```

SASS version 3.4.14

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1123

**Comment by KittyGiraudel** [comment]
This is expected. Use `//` to have unparsed comments. :)

**Comment by lpijet** [comment]
Newbie fault. Sorry ;)
Thanks for answer
