### ISSUE TITLE
Uniformize functions using amount/percentages

### ISSUE THREAD

**Issue by zessx** [sass/sass#1749]
`darken`, `lighten`, `saturate` and `desaturate` all use a percentage for their `$amount` parameter:

```
$dark_blue: darken($blue, 50%);
```

On the opposite side, `opacify` and `transparentize` use a [0,1] value:

```
$light_blue: transparentize($blue, 0.5);
```

As I perfectly understand the use of a [0,1] value for opacity, I think these 6 functions should accept both kind of values. In clear, allow us to use indifferently:

```
$dark_blue: darken($blue, 50%);
$dark_blue: darken($blue, 0.5);

$light_blue: transparentize($blue, 50%);
$light_blue: transparentize($blue, 0.5);
```

**Comment by whaaaley** [comment]
I agree. This still trips me up when doing colors because it's different from RGBA/HSLA.

**Comment by nex3** [comment]
The units for these functions are consistent with the units CSS uses for the corresponding values in `hsla()` and related functions. It would have been great if those units had been consistent when the functions were created, but that ship sailed long ago and Sass isn't the right place to change it.

Besides, this would be a backwards-incompatible and ambiguous change. `darken($blue, 0.5)` is already valid Sass—functions accept unitless values, so it's the same as `$darken($blue, 0.5%)`.
