### ISSUE TITLE
Add Sass gem's metadata on rubygems.org

### ISSUE THREAD

**Issue by JuanitoFatas** [sass/sass#1750]
Hello Sass,

Could you please fill metadata information in sass's page on rubygems.org

https://rubygems.org/gems/sass/edit

Here are my suggestions:

| URL | VALUE |
| --- | --- |
| **Source Code URL** | https://github.com/sass/sass |
| **Documentation URL** | http://sass-lang.com/documentation/file.SASS_REFERENCE.html |
| **Wiki URL** |  |
| **Mailing List URL** | http://sass-lang.com/community |
| **Bug Tracker URL** | https://github.com/sass/sass/issues |

Thank you!

**Comment by nex3** [comment]
Done.

**Comment by JuanitoFatas** [comment]
Thank you! :heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart:
