### ISSUE TITLE
Wrong output order of rules with lone `&` as selector breaks cascading

### ISSUE THREAD

**Issue by Marat-Tanalin** [sass/sass#1751]
Order of rules in output CSS is wrong when using a lone `&` as selector. Since CSS is a cascading thing, exact rule order is _critical_. Minimal testcase is below.

Source SCSS code:

```
UL {
    & {
        margin: 0;
    }

    margin-left: 35px;
}
```

Actual result:

```
UL {
    margin-left: 35px;
}
UL {
    margin: 0;
}
/* Effective `margin` value is `0`. */
```

Expected result:

```
UL {
    margin: 0;
}
UL {
    margin-left: 35px;
}
/* Effective `margin` value is `0 0 0 35px`. */
```

The testcase is _minimal_. In reality, `&` is a part of a selector _enumeration_ allowing to apply the same styles to the element and its nested elements at once, and then override it partially for the element itself:

```
UL {
    &, LI {
        margin: 0;
    }

    margin-left: 35px;
}
```

P. S. This issue has originally been reported as a [bug](https://github.com/leafo/scssphp/issues/271) of scssphp implementation, but according to one of its implementors ("The current behavior matches ruby sass and libsass"), this is a bug of original SASS compiler as well as libsass (I'm not able to test it myself for now).

**Comment by cimmanon** [comment]
This has nothing to do with &.  Nested selectors are simply moved to the outside, following the selector it was nested inside of with all other ordering preserved.

``` scss
ul {
  color: red;
  li {
    color: blue;
  }
  color: green;
}
```

Output:

``` css
ul {
  color: red;
  color: green;
}
ul li {
  color: blue;
}
```

Directly related to https://github.com/sass/sass/issues/735

**Comment by nex3** [comment]
This is intended. All nested properties are emitted before any nested rules at all times. This helps ensure that when nested rules and properties are intermixed (as in @cimmanon's example) there isn't unnecessary duplication of the top-level rule.

**Comment by anEffingChamp** [comment]
Why would the margin-left declaration come after the margin: 0 if it is housed 
in a block declared before the margin zero? As far as I can tell, the parent 
block is declared first, so it gets printed first. Nested blocks are declared 
afterward / within the parent and get printed afterward. That behavior seems 
totally reasonable to me.

**Comment by Marat-Tanalin** [comment]
> This has nothing to do with &.

Exactly. It's quite the contrary. The implementation is just not aware of the lone `&` use and its usefulness if implemented properly.

```
UL {
    & {
        margin: 0;
    }
}
```

is effectively equivalent to:

```
UL {
    margin: 0;
}
```

And:

```
UL {
    & {
        margin: 0;
    }

    margin-left: 35px;
}
```

is naturally expected to be equivalent to:

```
UL {
    margin: 0;
    margin-left: 35px;
}
```

The fact that nested rules are rendered after the containing rule is just a specifics of the current implementation, not something by design as for the nested lone `&` itself.

As a web developer since 2002, I believe lone `&` should be special-cased not to break cascading. Thanks.

FWIW, I understand the mechanism in general, and it works fine for all cases _except_ for the lone `&`. That's exactly what my report is about.

**Comment by Marat-Tanalin** [comment]
In CSS, I write this:

```
UL, UL LI {
    margin: 0;
}

UL {
    margin-left: 35px;
}
```

In a preprocessor, I write the equivalent (more DRY thanks to preprocessor) code:

```
UL {
    &, LI {
        margin: 0;
    }

    margin-left: 35px;
}
```

With the current behavior of SCSS, we are forced to be less DRY by creating another rule and repeating containing-rule selector (`UL` in this case):

```
UL {
    &, LI {
        margin: 0;
    }
}

UL {
    margin-left: 35px;
}
```

or by surrounding entire rest part of the containing rule in a redundant `&` rule:

```
UL {
    &, LI {
        margin: 0;
    }

    & {
        margin-left: 35px;
    }
}
```

Isn't such fight with the preprocessor not what preprocessors exist for — to make things _easier_, not harder to use? ;-)

**Comment by cimmanon** [comment]
You do understand that you are not obligated to use nesting, right?  All of your nested examples look more noisy than your plain CSS example.  On top of that, unless you're also using unordered lists, the most DRY way to write that is to not nest at all:

``` css
UL {
    margin: 0;
}

LI {
    margin: 0 0 0 35px;
}
```

**Comment by Marat-Tanalin** [comment]
@cimmanon Of course, if I'm using nesting, I _certainly_ know what and why I'm doing.

Don't take minimal testcases too seriously. Exact elements have nothing to do with the issue itself.

If `UL`/`LI` pair (fwiw, `UL LI` does not affect `LI` elements inside `OL` lists) looks somewhat misleading for you, consider `.foo`/`.bar` instead.

**Comment by Marat-Tanalin** [comment]
It's still unclear why it's necessary to move contents of nested pseudorule with **exactly** (not just any nested rule without thinking) lone `&` selector to a position after its containing rule.

The behavior is absolutely clear and reasonable (and needless to explain) for a nested rule based on a **real** selector **altering** its parent-rule selector since CSS just does not support nesting rules and this is actually the **only** way to go.

But that's not truth for the lone `&` selector since **lone `&` is not actually a selector at all**, it's just a way to **reference** its parent selector.

So there is absolutely nothing wrong or impossible in rendering contents of such nested **pseudo**rule exactly in place of the pseudorule itself.

For example, there is nothing that prevents this SCSS:

```
.example {
    background: white;
    & {
        color: blue;
    }
    display: block;
}
```

from being rendered as this CSS:

```
.example {
    background: white;
    color: blue;
    display: block;
}
```

and not this:

```
.example {
    background: white;
    display: block;
}
.example {
    color: blue;
}
```

Thanks.

**Comment by Marat-Tanalin** [comment]
Still awaiting for an official comment given what I said in my previous [comment](https://github.com/sass/sass/issues/1751#issuecomment-115399084). Thanks.

**Comment by Marat-Tanalin** [comment]
Should I file a new, even more specific bug to get a substantive answer about exactly **lone** `&` pseudoselector (as opposed to real nested selectors and selectors **containing** the simple `&` pseudoselector, but not **equal** to it). Or how to reopen this bug?

There is nothing reasonable, required or inevitable in breaking cascading when using lone `&` pseudoselector.

Thanks.
