### ISSUE TITLE
Error when passing only a number to nth-child

### ISSUE THREAD

**Issue by thany** [sass/sass#1765]
Sass considers this piece of code to be wrong:

```
$index: 3;
div:nth-child($index) { }
```

The expected output is:

```
div:nth-child(3) { }
```

Which is perfectly valid and selects the third div in its parent. Instead, Sass manages to produce an error in the console:

```
error test.scss (Line 2 of test.scss: Invalid CSS after "div:nth-child(": expected An+B expression, was "$index)")
```

Current workaround:

```
$index: 3;
div:nth-child(#{$index}) { }
```

This is on Sass 3.4.15 on Ruby 2.2.2.

**Comment by cimmanon** [comment]
This isn't a bug, Sass does not allow you to use variables for any part of a selector without interpolation.

**Comment by thany** [comment]
I see, so that makes this a feature request ;)

**Comment by nex3** [comment]
I don't think it's worth breaking consistency with the way all other selector interpolation works to make a relatively uncommon construction slightly easier.
