### ISSUE TITLE
Installing sass on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by aronstrandberg** [sass/sass#1768]
My sass gem "disappeared" after installing the OS X 10.11 beta, and re-installing it doesn't seem to work.

Running without sudo, I get this:

```
Ignoring json-1.8.2 because its extensions are not built.  Try: gem pristine json --version 1.8.2
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/.yardopts
```

With sudo:

```
Ignoring json-1.8.2 because its extensions are not built.  Try: gem pristine json --version 1.8.2
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/sass
```

Thoughts?

**Comment by nex3** [comment]
This looks like an OS problem rather than a Sass problem. We don't do anything to change the default installation process.

**Comment by nex3** [comment]
It looks like this is popping up for at least several users of El Capitan. I haven't the slightest idea why it would be happening, though, and it still looks like an OS issue. If someone who's running into it wants to dig in and see if they can find the root cause so we can maybe find a workaround, that would be appreciated.

**Comment by aronstrandberg** [comment]
I had trouble installing Jekyll too, and according to [issue 3807](https://github.com/jekyll/jekyll/issues/3807) there, it seems the issue is Apple not bundling the Ruby development headers. I seem to have (kind of) solved it by running `rvm install ruby-2.2-head --disable-binary`. 

Now, Sass works, but only after running `rvm list` every time I want to use it.

**Comment by chriseppstein** [comment]
>  I had to do the rootless thing to make sass and compass work. sudo nvram boot-args="rootless=0"; sudo reboot

https://twitter.com/cochinet/status/620624513919684609

**Comment by unclenorton** [comment]
Upgrading the Ruby version to 2.2.2 as per [this instruction](https://gorails.com/setup/osx/10.11-el-capitan) did the trick for me. You will also need to add the local .rbenv binary path (/Users/username/.rbenv/versions/2.2.2/bin) to your bash profile for convenience.

**Comment by ousenko** [comment]
Using home-brew or custom $GEM_HOME can help resolving the issue.
I made an installation of ruby via brew:

```
brew install ruby
```

Now the `gem` stuff seem to happen relative to my `/usr/local/bin*`

**Comment by miklb** [comment]
In case anyone else runs across this, latest public beta (5) resolves the Ruby issues, at least for me after updating my gems.

**Comment by Alan-Billi** [comment]
I'm on El Capitan Beta 6 and still having the same trouble.
Made a fresh install of all Homebrew/Ruby/Rails and still have it :(

**Comment by endoplasmic** [comment]
This should get you up and running: `sudo gem install -n /usr/local/bin GEM_NAME_HERE`

**Comment by ghelton** [comment]
@endoplasmic that worked for me thanks! :+1:

**Comment by jacobmiller** [comment]
@unclenorton 's link to Gorails ruby upgrade instructions worked for me

**Comment by stgeorgiev** [comment]
@endoplasmic, thanks it worked.

**Comment by miklb** [comment]
I'm a Ruby n00b, but from what I've read, and being a perpetual beta user in all things dev, slowing down and re-reading everything works.

I did a clean install of Homebrew, used rbenv and triple checked all of the _paths in my shell_ (that last part was key).

Also, take said n00b at face value, but using `sudo` with Ruby on a Mac sounds like a disaster long term from what I've extensively researched.

**Comment by gary-Shen** [comment]
@endoplasmic Thank you. it worked.

**Comment by TalD** [comment]
@endoplasmic, thank you for the right solution.

**Comment by yanwsh** [comment]
@endoplasmic Thank you so much, it's working.

**Comment by marcuswd** [comment]
Tks, @endoplasmic!

**Comment by DannySu09** [comment]
Work like a charm! Thx! @endoplasmic

**Comment by wKoza** [comment]
THx @endoplasmic !

**Comment by ghamaide** [comment]
Works perfectly with @endoplasmic command line ! Thx !

**Comment by pepelsbey** [comment]
@endoplasmic, this `-n /usr/local/bin` works for `sass` and `stringex`, but doesn’t for `jekyll`

```
$ sudo gem install -n /usr/local/bin jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
    ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150930-3326-qv7utq.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/fast-stemmer-1.0.2/gem_make.out
```

**Comment by amberfeinerman** [comment]
Thank you so much @endoplasmic! You saved the day.

**Comment by jcastelli** [comment]
@pepelsbey Just dropping a line to report that installing Jekyll to `/usr/local/bin` DID work for me. I'm no Rubyist, so I'm not sure I can offer much beyond that, but wanted to throw it out there!

**Comment by jcastelli** [comment]
Oh, and I must also thank @endoplasmic – I didn't even know you could specify a directory to drop the binaries. Awesome!

**Comment by ijmorgado** [comment]
Thank you so much @endoplasmic ...you rock!

**Comment by r1seUp** [comment]
thank you guys it worked for me using @unclenorton's suggestion to reinstall Ruby and @endoplasmic's way for installing gems

**Comment by afmklk** [comment]
Thank you @endoplasmic, this saved me some headaches!

**Comment by bferioli** [comment]
@endoplasmic ❤ /thanks

**Comment by ravenjam** [comment]
@endoplasmic This is the solution, thanks

**Comment by eneserdogan** [comment]
Thanks @endoplasmic :+1:

**Comment by atakangktepe** [comment]
@endoplasmic :+1: thanks

**Comment by L1lle** [comment]
@endoplasmic thanks worked for me as well

**Comment by guygunaratne** [comment]
Thank @endoplasmic that worked for me. Cheers :+1: :+1:

**Comment by soberman** [comment]
@endoplasmic you're the man!

**Comment by ilkeryilmaz** [comment]
@endoplasmic :+1: thanks

**Comment by mehanig** [comment]
@endoplasmic much kudos!

**Comment by webfacer** [comment]
@endoplasmic it worked! very helpful! thx!

**Comment by Trullus** [comment]
@endoplasmic Worked like a charm, thank you!

**Comment by snide** [comment]
Just a note that if you run bundle and have your gulp or grunt tasks set to bundle_exec: true, you'll also need to make sure to update your bundle as well. Simply reinstalling bundle (similar to reinstalling  sass / compass above) and then running a new bundle install should get you running properly again.

**Comment by KevinSleegers** [comment]
@endoplasmic you saved the day! Thank you so much!

**Comment by ampersanddigital** [comment]
@endoplasmic === legend.

**Comment by shrekuu** [comment]
@ousenko  Thanks. I believe installing this more recent ruby is better :smile:

**Comment by jpieterse84** [comment]
@endoplasmic - Lifesaver!!

**Comment by windmaomao** [comment]
thank you @endoplasmic , it works with `sudo gem install -n /usr/local/bin compass`.

**Comment by Web3nt** [comment]
Good lookin @ousenko and @endoplasmic, worked like a charm!

**Comment by jimmyko** [comment]
Thanks @endoplasmic. It rocks.

**Comment by jasewarner** [comment]
Thanks @endoplasmic!

**Comment by vineshhpatel** [comment]
Thanks @endoplasmic

**Comment by Coolkevs** [comment]
Thank you @endoplasmic. it works!

**Comment by rafaelign** [comment]
Thanks @endoplasmic ! ;)

**Comment by lukehollis** [comment]
That did it--thanks @endoplasmic

**Comment by richardsison** [comment]
@endoplasmic Thanks mate!! That did the trick.

**Comment by devilmark84** [comment]
Due to Apple System Integrity Protection (http://apple.stackexchange.com/questions/208764/cant-write-to-usr-lib) it's impossible to write in the default folder /usr/local/bin.
    sudo gem install sass --install-dir /usr/local
Not the _/usr/local/bin_ because the installer creates the _bin_ folder.

**Comment by d-wren** [comment]
@endoplasmic  Thank you so much! It worked for me.

**Comment by ajuliano** [comment]
The solution presented by @endoplasmic worked for me as well. Thank you!

**Comment by LesleyMerks** [comment]
Thanks @endoplasmic  !

**Comment by Macstyg** [comment]
@endoplasmic Thanks a lot!

**Comment by jamigibbs** [comment]
@endoplasmic Cheers!! 💪

**Comment by JamesVanWaza** [comment]
If that doesn't work also this will work
`brew install ruby`
 `sudo gem install -n /usr/local/bin compass`

**Comment by ghost** [comment]
@endoplasmic Muchas graciasssssssssss

**Comment by niuserre** [comment]
Thanks @endoplasmic!

**Comment by olferuk** [comment]
@endoplasmic thanks man :)

**Comment by AnderUstarroz** [comment]
+1 @endoplasmic,  you are definitely the hero of this thread. Cheers

**Comment by Kofaka** [comment]
Thanks @endoplasmic and @jgacuca567 :) You just saved a ton of my time!

**Comment by uiuco** [comment]
+1 @endoplasmic and @jgacuca567

**Comment by matthewhirsch** [comment]
@endoplasmic much appreciated!

**Comment by PokimLee** [comment]
@endoplasmic you saved my day! thx!

**Comment by fatisar** [comment]
Just throwing in my @endoplasmic thanks for the day

**Comment by GThatchapit** [comment]
@endoplasmic  It Work!

**Comment by shiraji** [comment]
@endoplasmic :+1:

**Comment by xiaoshier** [comment]
thank you very very very much!

**Comment by xiaoshier** [comment]
@endoplasmic thank you very very very much!

**Comment by xturgorex** [comment]
you probably haven't been told this enough yet, but thank you very much @endoplasmic.

**Comment by lukemoderwell** [comment]
@endoplasmic very thanks. so gratitude.
