### ISSUE TITLE
Sass won't install on El Capitan

### ISSUE THREAD

**Issue by matiasvad** [sass/sass#1769]
I just installed the public beta of El Capitan - 10.11 Beta (15A215h), and found Sass to have been removed. Installing it again proves to be quite an issue.

```
➜  ~  gem install sass
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
➜  ~  sudo gem install sass
ERROR:  While executing gem ... (Errno::EPERM)
Operation not permitted - /usr/bin/sass
➜  ~  sass -v
zsh: command not found: sass
```

**Comment by nex3** [comment]
Duplicate of #1768.

**Comment by jaredwerba** [comment]
I am running into the same problem. Running Beta 15A278b

**Comment by slunt32** [comment]
Dunno if this applicable here but @endoplasmic provided a solution in #1768:

<code>This should get you up and running: sudo gem install -n /usr/local/bin GEM_NAME_HERE</code>

**Comment by ecseley** [comment]
Thanks @slunt32, that worked perfectly!  Cheers!

**Comment by ksundmyhr** [comment]
Perfect, @slunt32 :)

**Comment by Msimoneau** [comment]
@slunt32 you saved my day !!!

**Comment by Devnco** [comment]
@slunt32 Thanks for the trick, it helped ! ;-)

**Comment by marxwiggin** [comment]
Thanks!

**Comment by FreDeRoover** [comment]
@slunt32 Thanks for the trick!

**Comment by jers73** [comment]
Thanks. Worked for me

**Comment by stafast** [comment]
@slunt32 Thank you

**Comment by ghost** [comment]
thanks @slunt32 @endoplasmic saved me a headache!

**Comment by scott-wyatt** [comment]
Life saver

**Comment by jjalonso** [comment]
Good! We can continue with our paylisp.... Thanks @slunt32

**Comment by zoephilipps** [comment]
:+1: saved my life as well. Can continue using SassBeautify for Sublime. :)

**Comment by frank-castro** [comment]
thanks @slunt32 @endoplasmic

**Comment by swordling** [comment]
@slunt32 You are my favourite person right now.

**Comment by joe-bell** [comment]
Thanks @slunt32!

**Comment by maxigor** [comment]
thanks @slunt32 <3

**Comment by olivertappin** [comment]
Cheers @slunt32!

**Comment by thebeard** [comment]
Thanks!

**Comment by walterspieler** [comment]
@slunt32 Worked perfectly for me, Thank you !

**Comment by slunt32** [comment]
No problem guys, except don't thank me, all the credit goes to @endoplasmic

**Comment by voidstate** [comment]
Another Thank you from me.

What exactly is this command doing?

**Comment by endoplasmic** [comment]
@slunt32 appreciate, and the way I found the solution was someone was having issues with cocopods a few years back. I tried the command with the sass gem and it magically worked :D

**Comment by codezyc** [comment]
@slunt32,THX.

**Comment by zeshanshani** [comment]
Wow! Worked great @slunt32! Thank you!

**Comment by toptalo** [comment]
@slunt32 Thank you!

**Comment by ghost** [comment]
@slunt32 Thank you!

**Comment by lricoy** [comment]
@slunt32 thanks!

**Comment by scottyg** [comment]
@slunt32 Live saver

**Comment by yourpleasure** [comment]
@slunt32 Thank you very much

**Comment by ssjssh** [comment]
@slunt32 thanks+1

**Comment by clintonpaquin** [comment]
thank you @slunt32

**Comment by samkohli** [comment]
Thanks!

**Comment by jihchi** [comment]
@slunt32 thanks!

**Comment by vicdantas** [comment]
@slunt32 Thanks!

**Comment by paleite** [comment]
Thank you!

**Comment by jetlej** [comment]
Thank you!!!!

**Comment by allmotorking** [comment]
I had to install updated xcode once i installed El Capitan before i could install sass

**Comment by JamesIves** [comment]
@slunt32 saved the day, thanks!

**Comment by asaadmahmood** [comment]
+1 Thanks.

**Comment by cristifilip** [comment]
@slunt32 You're the man!

**Comment by unwiredtech** [comment]
@slunt32 Thanks! Worked fine here too!

**Comment by lukerobertson1** [comment]
+1

**Comment by stevejvv** [comment]
thanks!
