### ISSUE TITLE
Variable followed by "%" fails to compile

### ISSUE THREAD

**Issue by billzhong** [sass/sass#1774]
Hi,

The following code fails to compile by Ruby compiler.

``` scss
@each $size in (10, 20, 30, 33, 40, 50, 60, 70, 80, 90) {
    &.col#{$size}>div {
        flex: 0 1 #{$size}%;
    }
}
```

But it works on libsass compiler.

Any advice? Thanks.

Bill

**Comment by cimmanon** [comment]
It probably shouldn't work on libsass.  The percent sign, on its own without quotes, is not a valid string.

The correct way to add a unit to a number is via arithmetic, not interpolation.

``` scss
flex: 0 1 $size * 1%;
```

**Comment by joemckie** [comment]
Have you checked out the [`percentage()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#percentage-instance_method) function? It seems like that may help you.

E.g.

``` sass
@each $size in (10, 20, 30, 33, 40, 50, 60, 70, 80, 90) {
    &.col#{$size}>div {
        flex: 0 1 percentage($size / 100);
    }
}
```

**Comment by nex3** [comment]
This brings up some interesting questions about what the general rule for Sass interpolation should be, which I've talked about in #1778. Any way that lands, though, this will be invalid.
