### ISSUE TITLE
Create an @inject directive, like @extend, that would strip off the extending selectors.

### ISSUE THREAD

**Issue by EigenTheory** [sass/sass#1780]
I currently use something similar to this feature in my projects, basically by replacing class definitions with `@mixin classname {}` **vs** `.classname {}`. I find on large projects, when using Bootstrap or Foundation, that being able to inject the class contents into semantic classes reduces the overhead of excessive extending selectors.

**_Example:**_

``` html
<nav class="main-nav"</nav>
```

Recommended Extending Method:

``` css
.main-nav {
  @extend .navbar;
  @extend .navbar-default;
  @extend .navbar-fixed-top;
}
```

Generated Selectors:

``` css
@media (xyz) .navbar, .main-nav {}
.navbar, .main-nav {}
.navbar-default, .main-nav {}
.navbar-fixed-top, .main-nav {}
@media (xzy) .navbar-fixed-top, .main-nav, .navbar-fixed-bottom {}
.navbar-fixed-top, .main-nav, .navbar-fixed-bottom {}
.navbar:after, .main-nav:after {}
.navbar:before, .main-nav:before, .navbar:after, .main-nav:after {}
```

**_Injecting:**_

Using existing classes as @mixin:

``` css
.main-nav {
  @include navbar;
  @include navbar-default;
  @include navbar-fixed-top;
}
```

Generated Selectors:

``` css
  @media (xyz) .main-nav {}
  .main-nav {}
  .main-nav:before, .main-nav:after {}
```

Something like this would be nice...

``` css
.main-nav {
  @inject .navbar;
  @inject .navbar-default;
  @inject .navbar-fixed-top;
}
```

**Comment by KittyGiraudel** [comment]
Still not sure what `@inject` would do in your example.

**Comment by apfelbox** [comment]
@joseorihuela what you want is basically an `@extend` that removes the class itself from the source. I am not sure whether this is feasible, as you can't know whether the class is used anywhere (in your HTML). The problem is that as soon as your `@inject .navbar` would find `.navbar` it needs to exist in your code and therefore will be included in the compiled CSS.

But I think there might be a solution, that should also solve your use case:

`@import`ing files with direct output of any SCSS. You would basically just include the whole selectors without producing output.

### How that would look like:

File `_import-me.scss`

``` scss
.a {
    color: red;
}
```

File `app.scss`

``` scss
@import-names "import_me.scss";

// the *name* `.a` is visible, as we only import the names
.b {
    @extend .a;
}
```

What this would produce:

``` css
.b {
     color: red;
}
```

### Usage with Bootstrap

``` scss
@import-names "bootstrap.css";

.main-nav {
  @extend .navbar;
  @extend .navbar-default;
  @extend .navbar-fixed-top;
}
```

Output:

``` css
@media (xyz) .main-nav {}
.main-nav {}
.main-nav:before, .main-nav:after {}
```

**Comment by davidkpiano** [comment]
@joseorihuela @apfelbox This is essentially the same thing as `@extend`ing a `%placeholder` selector. :)

**Comment by apfelbox** [comment]
@davidkpiano that is correct, **except** when you have no control of your vendor code (like when using any (S)CSS framework out there – like bootstrap).

**Comment by EigenTheory** [comment]
@davidkpiano what @apfelbox said. I was thinking more along the lines of being able to utilize vendor frameworks in a more semantic way without all of the extending selectors muddying things up.

**Comment by nex3** [comment]
This is along the lines of one of the features we're looking at for `@import` v2. We want to allow users to write something like a "placeholder import", where any imported styles work like placeholder selectors—they're extendable, but they aren't compiled to CSS on their own.
