### ISSUE TITLE
Data Attributes in Selectors causes compiler error.

### ISSUE THREAD

**Issue by neurofuzzy** [sass/sass#1783]
Example:

.slider[data-value='70'] {

}

Sass error: { status: 1,
  file: '~/main.scss',
  line: 1172,
  column: 30,
  message: 'invalid property name',
  code: 1 }

**Comment by cimmanon** [comment]
Cannot reproduce: http://sassmeister.com/gist/7884ec056fc6843c84e4

**Comment by KittyGiraudel** [comment]
Cannot reproduce either.
