### ISSUE TITLE
Can't overwrite variable in mixin

### ISSUE THREAD

**Issue by KupuJIJI** [sass/sass#1791]
Hi, all. I need help.

Before I update sass gem to 5.0.2 + 

It works:

``` sass
$block: 'undefined'

@mixin b($name)
  $block: $name  // IN this point variable changed

  .#{$block}
    @content

@mixin e($name)
  .#{$block}__#{$name}  // and here was name of block
    @content

```

But now it doesn't work. And I have in output

``` css
.undefined__element-name{}  without .block-name__element-name
```

Please help.

**Comment by KittyGiraudel** [comment]
Use `!global` flag to override a global variable from an inner scope.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1511

**Comment by KupuJIJI** [comment]
@HugoGiraudel Great thanks!
