### ISSUE TITLE
Sass Truck Factor

### ISSUE THREAD

**Issue by gavelino** [sass/sass#1792]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Sass** and obtained a value of **1**.

The developer responsible for this TF is:

Natalie Weizenbaum - author of 82% of the files 

To validate our results, we would like to ask **Sass** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Sass**?

(b) Do you agree that **Sass** will be in trouble if the listed developer leave the project (e.g., if she wins in the lottery, to be less morbid)?

(c) Does **Sass** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by davidkpiano** [comment]
@gavelino I believe her name is **Natalie** Weizenbaum.

**Comment by gavelino** [comment]
@davidkpiano 

"Nathan Weizenbaum" is the name that happens in some commits (https://api.github.com/repos/sass/sass/commits/92e3b022669a6131500a048cd6c2e6f6504cc2d3). But, I noted that the same e-mail was used for Natalie Weizenbaum too. So, I think you are right.

**Comment by nex3** [comment]
(a) Yes.

(b) Somewhat. @chriseppstein would be able to continue the language design, and [LibSass](https://github.com/sass/libsass) is in a good position to carry forward development efforts.

(c) There is quite a lot of API documentation, although in practice it doesn't seem to contribute to a lot of external contributions.
