### ISSUE TITLE
SASS @import variable interpolation

### ISSUE THREAD

**Issue by gespinha** [sass/sass#1794]
Hi there,

I am trying to simplify my management upon importing a set of parcials and I am trying the following but its not working:

```
$folder: 'folder/'
@import $folder + 'my_file_path'
```

Doesn't variable interpolation inside @import work in SASS yet?

Thanks in advance

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/279

**Comment by gespinha** [comment]
Thanks ;)
