### ISSUE TITLE
Suggestion for unescaping overqualified selectors

### ISSUE THREAD

**Issue by b44rd** [sass/sass#1795]
Here is how I love to write sass. 

The following code allow me to define a scope that contains an element (.whatever) and some element within (.something)

```
.scope {
    .whatever {
        .something {
            property: value;
        }
    }
}
```

My output will be

```
.scope .whatever .something { property: value; }
```

However, this is to me overspecifying in most cases. What I would love to be able to do, is simply

```
.scope {
    .whatever {
        \.something {
            property: value;
        }
    }
}
```

which produces 

```
.scope .something { property: value; }
```

This way, I can still have a visual representation of my DOM within my scss file, but my css file doesn't compile into a huge monster that I would have to postprocess afterwards. 

Could something like this be an idea for nested elements to break out of its respective parent? I would really love to see something like this in the future, and I think it would be really useful for a lot of people.

**Comment by cimmanon** [comment]
You do understand that the following is perfectly valid CSS, right?

``` css
\.something {
    color: red;
}
```

Your suggestion would break the ability to write such a selector.  If you want to "visually represent the DOM", try using comments instead.

**Comment by nex3** [comment]
You could theoretically write a mixin for this if you want, but it's not something that's worth supporting in the core language.

**Comment by b44rd** [comment]
"It's not something worth supporting in the core language" -> Issue closed. 

Seriously? Well, thanks a ton, @nex3 ... O_o

**Comment by b44rd** [comment]
Perhaps some other character might be more ideal, @cimmanon. :) But I would really like to be able to writhe styles under a scope without overspecifying stuff (which by the way is the only thing I hate about scss at the moment). :)

**Comment by cimmanon** [comment]
@b44rd I have no real influence over the direction of the Sass project.  It is my opinion that over-qualification is a problem you're making for yourself, not one that Sass should be solving.  Using comments is your best option in this case.

**Comment by b44rd** [comment]
@cimmanon I understand. Comments wouldn´t be ideal imho, but perhaps a mixin might work well. 

Just out of curiousity: How would I write a mixin like that? Thanks.
