### ISSUE TITLE
Should rgb() and rgba() functions be updated to accept strings?

### ISSUE THREAD

**Issue by cimmanon** [sass/sass#1796]
I had an odd question pop up on SO the other day where the asker was attempting to use `calc()` in combination with `rgb()`.  This fails, of course, because `rgb()` only accepts either 3 integers or a color.  But is this behavior correct?
# Bugzilla for Mozilla

There is an open [bug report on Bugzilla regarding Mozilla's lack of support for calc() in rgb()/rgba()](https://bugzilla.mozilla.org/show_bug.cgi?id=984021).  If you read the related bug reports that are linked to it, one commenter points out that Chrome _does_ support it.
# CSS validator

``` css
body {
    background-color: black;
    color: rgb(calc(255 - 0) , 0, 0);
}
```

This throws a validation error, but then again so do feature queries (which Sass _does_ support along with just about every browser other than Internet Explorer).
# Specification

> The format of an RGB value in the functional notation is ‘rgb(’ followed by a comma-separated list of three numerical values (either three integer values or three percentage values) followed by ‘)’. The integer value 255 corresponds to 100%, and to F or FF in the hexadecimal notation: rgb(255,255,255) = rgb(100%,100%,100%) = #FFF. White space characters are allowed around the numerical values.

Source: http://www.w3.org/TR/css3-color/#rgb-color

> The calc() function allows mathematical expressions with addition (‘+’), subtraction (‘-’), multiplication (‘*’), and division (‘/’) to be used as component values. The ‘calc()’ expression represents the result of the mathematical calculation it contains, using standard operator precedence rules. It can be used wherever <length>, <frequency>, <angle>, <time>, <number>, or <integer> values are allowed. Components of a ‘calc()’ expression can be literal values, ‘attr()’ or ‘calc()’ expressions, or <percentage> values that resolve to one of the preceding types.

Source: http://www.w3.org/TR/css3-values/#calc

Does not specify either way, but from the description for calc(), it sounds like it _should_ work.

**Comment by nex3** [comment]
I agree that this should work.
