### ISSUE TITLE
Caching of Sass::Importers::Filesystem breaks on multiple template_locations

### ISSUE THREAD

**Issue by datenimperator** [sass/sass#180]
My rails app A contains an railtie engine E which uses Compass (and thus, Sass). Both engine and rails app contain sass templates in folders named _app/stylesheets_. The folder belonging to the engine is not below the Rails.root directory of the rails app.

So we'll find:

some/directory/A ( <= this is Rails.root )
- app/stylesheets

some/directory/E
- app/stylesheets

Sass (and Compass) project_dir is Rails.root. During setup, my engine uses `Sass::Plugin.add_template_location` to add the extra directories containing templates to the list of compilable templates. The code can be seen at https://gist.github.com/1247187 It works as expected, as far as resolvability of templates is concerned.

Unfortunately, `Sass::Importers::Filesystem#mtime(name, options)` fails for all names that are outside of Rails.root. I've tracked it down to `find_real_file(@root, name)` which fails because
- dir is not "." but a full path pointing to Rails.root
- name contains a full path, too
- remove_root fails because name doesn't start with Rails.root
- concatenation of dir/name isn't a valid path
- Dir[path] is empty

All this makes Sass believe that there's no valid cache. In the end, all templates outside of Rails.root will be recompiled upon every request.

**Comment by datenimperator** [comment]
This is the same as discussed on compass-users:

http://groups.google.com/group/compass-users/browse_thread/thread/db8c15e987bcb332

(I'm the original author)

**Comment by nex3** [comment]
Closed by fc056d77c961cd9429f53702ddeb655c96d911d9

**Comment by datenimperator** [comment]
Thanks for getting this fixed.
