### ISSUE TITLE
Trouble with `&` not following spec?

### ISSUE THREAD

**Issue by aaronmgdr** [sass/sass#1801]
when i copy and paste the [following from the sass reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector) 

```
#main {
  color: black;
  &-sidebar {
    border: 1px solid;
  }
}
```

i get this `Sass::SyntaxError` 

```
Invalid CSS after "  &": expected "{", was "-sidebar {"

"-sidebar" may only be used at the beginning of a compound selector.
```

in gemfile.lock 
`sass (3.2.19)`

**Comment by aaronmgdr** [comment]
it compiles when there is a space between `&` and `-sidebar` but that outputs `#main -sidebar`  rather than `#main-sidebar`

**Comment by KittyGiraudel** [comment]
It is supported starting Sass 3.3.

**Comment by aaronmgdr** [comment]
thanks. figured it was probably me being on an old version
