### ISSUE TITLE
Sass cache has absolute file paths

### ISSUE THREAD

**Issue by schneems** [sass/sass#1802]
If you're using a cache between building assets and you move the directory of your project, then the cache data becomes invalid. This happens on Heroku since every build happens in what is essentially a tmp dir. It also happens fairly frequently in Capistrano deploys where people will symlink a common cache directory on the deploy rather than having to copy it over. This problem was originally identified in rails/sprockets#59. I've been working on removing absolute paths from the sprockets cache you can follow along in https://github.com/rails/sprockets/issues/96 if you want. We've gotten to a point where all the absolute paths we generate are properly compressed before they go into the cache and expanded after they come out, however Sass still generates absolute paths that we cannot easily sanitize at the sprockets level. 

I've identified at least one place where sass directly uses absolute paths and puts it in a cache, and another place where sass generates an absolute path in a comment that sprockets will end up caching https://github.com/rails/sprockets/issues/96#issuecomment-133436122. I'm interested in removing these absolute paths so that the cache can be re-used even if you move or copy your project.

I'm opening this issue to start a dialog. I'm interested in working on this, I would appreciate any help anyone can give me.  I'm new to the sass repo. Has anyone tried removing absolute paths from the sass cache before? Are there any known blockers? Any tips or techniques that might make a patch removing absolute paths from sass cache easier?

**Comment by chriseppstein** [comment]
What specific issues are the absolute paths in our cache causing?

**Comment by bughit** [comment]
The specific issues with absolute paths in a shared cache that have already been encountered and addressed are cache misses and Sprockets::FileOutsidePaths errors.  An additional theoretical possibility is some code trying to open an absolute path that no longer exists.

Absolute paths for in project files have no benefits and only problems.

**Comment by nex3** [comment]
I'm fine with removing absolute paths where possible. I'd like to see a list of places where they're being generated, though.

**Comment by chriseppstein** [comment]
> Absolute paths for in project files have no benefits and only problems.

Sass has no concept of what is a project file and what is a library file. Sass just has a load path. Some of those paths would be broken if they are not absolute (E.g. the stuff that's coming from inside a ruby gem). So we'd need the cache implementation to have an option that let's us decide what paths should be relative and what are "outside" the project so that relocating the project and the cache directory to a different depth in the filesystem doesn't break path references. Probably something like `:relativize_paths_within => directory_name` that way the project wrappers around sass (e.g. sass-rails and compass) can create a FileSystemCache instance that behaves the way they expect it to.

**Comment by bughit** [comment]
@schneems it makes sense that sprockets needs to assist with the decision of which paths need to be transformed and maybe even the work of transforming them

Do you plan on adding something like that?

**Comment by schneems** [comment]
Sorry for not responding. I was trying to come up with a sprockets + sass example that broke due to cache sharing and I couldn't. I'm not saying a case like this doesn't exist but rather I couldn't contrive one into existence.

I like that proposal, we could easily supply the root of the project where assets are being compiled as an argument. I'm happy to do lots of leg work here.  Right now i'm playing major catchup on sprockets. If we can get a failing case, I can prioritize this higher. Sorry for opening the ticket and going into radio silence. For now we should either close this pending a failing example, or keep it open to keep the conversation going (wherever your personal issue preferences stand).

**Comment by bughit** [comment]
Under what circumstances are the paths stored by SASS opened?  Producing those conditions, and moving/deleting the out of project folder where they point, should create a problem.

**Comment by chriseppstein** [comment]
Closing this issue for now. If a concrete use case exists, we will consider how to fix that.
