### ISSUE TITLE
Multiple included placeholders will create new selector

### ISSUE THREAD

**Issue by FranDias** [sass/sass#1811]
Similar/same place holders will not combine in the compiled output:

``` sass
%m-all-0
  margin: 0

%m-all-0
  margin: 0

.m-all-0
  @extend %m-all-0
```

Compiles to (two of the same selectors/rule sets)

``` css
.m-all-0 {
  margin: 0;
}

.m-all-0 {
  margin: 0;
}
```

http://sassmeister.com/gist/94e6780aaeab0a4e2fcd

I'd expect SASS to realize that those selectors are the same and reduce compiled output.

In this simplified example the obvious answer is to just to fix the selectors but in larger projects this can become a pain. Mainly if there are `mixins` or `placeholders` which are being included into other files.

**Comment by chriseppstein** [comment]
> I'd expect SASS to realize that those selectors are the same and reduce compiled output.

We don't do this with classes or any other selector. Placeholder selectors are the same as those.

**Comment by FranDias** [comment]
@chriseppstein Thanks for your time and consideration of this issue, makes sense to be consistent.

For anyone else wondering this behavior is also consistent with media queries.
http://sassmeister.com/gist/09545a51a563e77a1a35
