### ISSUE TITLE
Not able to use '--poll' with Sass -v 3.4.18. Sass doesn't listen for changes any longer.

### ISSUE THREAD

**Issue by lukaskoeller** [sass/sass#1820]
IMPORTANT: This problem just occurs on files which already have been created during the problem came up. All new `.scss` files working perfect with sass and it listen for changes as normal.

I'm now deal with some Sass issues for a while and the latest issue posted here is no longer current.
The main problem is that Sass just compiles the files once but doesn't listen for changes after that. When I try using `--poll` Sass gives me an uncommon error:
`>sass --poll
OptionParser::InvalidOption: invalid option: --poll
  Use --trace for backtrace.`

Windows 10 64bit
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]

gem list:
**\* LOCAL GEMS ***

bigdecimal (1.2.4)
ffi (1.9.10 x64-mingw32)
io-console (0.4.3)
json (1.8.1)
listen (3.0.3)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rdoc (4.1.0)
sass (3.4.18)
test-unit (2.1.6.0)

---- Not the current setup ---
When I downgrade listen to `2.9.0` the follwoing error occurs when initializing `sass --watch`:
`C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:21: warning: already initialized constant Celluloid::LINKING_TIMEOUT`
`C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:21: warning: previous definition of LINKING_TIMEOUT was here`
`C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:24: warning: already initialized constant Celluloid::BARE_OBJECT_WARNING_MESSAGE`
`C:/Ruby22/lib/ruby/gems/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:24: warning: previous definition of BARE_OBJECT_WARNING_MESSAGE was here`
`LoadError: cannot load such file -- hitimes/hitimes`
`Use --trace for backtrace.`

And with that (-v 2.9.0) the gem installs also some other gems.
Gem list which comes with listen -v 2.9.0:
**\* LOCAL GEMS ***

bigdecimal (1.2.6)
bundler (1.10.6)
celluloid (0.17.1.2)
celluloid-essentials (0.20.2.1)
celluloid-extras (0.20.1)
celluloid-fsm (0.20.1)
celluloid-pool (0.20.1)
celluloid-supervision (0.20.1.1)
dotenv (2.0.2)
ffi (1.9.10 x86-mingw32)
hitimes (1.2.2 x86-mingw32)
io-console (0.4.3)
json (1.8.1)
listen (2.9.0)
minitest (5.4.3)
nenv (0.2.0)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rdoc (4.2.0)
rspec-logsplit (0.1.3)
sass (3.4.18)
test-unit (3.0.8)
timers (4.1.1)

Any idea how to fix that? I would be very pleased!

**Comment by chriseppstein** [comment]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/SassCSS">@SassCSS</a> I was able to reproduce this issue on Windows 10.</p>&mdash; Barry Tormey (@barry_tormey) <a href="https://twitter.com/barry_tormey/status/638448818980306944">August 31, 2015</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by lukaskoeller** [comment]
May that also could help: I had to deal with the same problem on Windows 7 64bit.

**Comment by lukaskoeller** [comment]
Update:

When I copy the .scss files in sublime and create a new file in a new directory everything works!
For every help anyway I would be very happy!

**Comment by nex3** [comment]
Haven't heard any reports of this in a long time, so I'm closing it out.
