### ISSUE TITLE
adjacent & to tag name has a space i don't want there

### ISSUE THREAD

**Issue by alexbowers** [sass/sass#1826]
When i try something like this:

```
.ff {
  &.ff-checkbox {
    label & {
      color: red;
    }
  }
}
```

this generates:

```
label .ff.ff-checkbox {
  color: red;
}
```

However, what i want is:

```
label.ff.ff-checkbox {
  color: red;
}
```

Is there a way to strip out this space?

If i remove the space from before the ampersand, then it causes an error:

```
/*
Error: Invalid CSS after "label": expected "{", was "&"

       "&" may only be used at the beginning of a compound selector.
        on line 3 of src/styles/main.scss

1: .ff {
2:   &.ff-checkbox {
3:     label& {
4:       color: red;
5:     }
6:   }
7: }
```

This, to me, should be possible. But i'm not sure on the best way to do it.

Maybe allowing the space be removed with the ampersand, or to allow another character, perhaps a tilde to concat immediately before? so ~tag would create a prefix of tag.

**Comment by davidkpiano** [comment]
See this issue: https://github.com/sass/sass/issues/1520

**Comment by alexbowers** [comment]
Thanks.

For anyone else, relevant line is this:

```
@at-root #{selector-append("label", &)} { }
```
