### ISSUE TITLE
NoMethodError: undefined method `read' for "css/path/to/file.css":String

### ISSUE THREAD

**Issue by rafalkrawiec** [sass/sass#1827]
Hi, I'm getting an error (like I wrote in title) while trying to use `sass-convert` on a directory containing css files.

Backtrace:

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:244:in `block in process_file': undefined method `read' for "css/path/to/file.css":String (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/util.rb:503:in `silence_sass_warnings'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:241:in `process_file'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:210:in `block in process_directory'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/util.rb:647:in `block in glob'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/util.rb:647:in `glob'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/util.rb:647:in `glob'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:187:in `process_directory'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:40:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/base.rb:52:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/exec/base.rb:19:in `parse!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/bin/sass-convert:12:in `<top (required)>'
    from /usr/bin/sass-convert:23:in `load'
    from /usr/bin/sass-convert:23:in `<main>'
```

**Comment by dnesting** [comment]
(Moving my comment to a new issue #1835 since I no longer think it's the same problem.)

**Comment by chriseppstein** [comment]
Thank you for reporting this issue, but it's hard to know how to reproduce it based on your description. Please include steps to reproduce this.

**Comment by lowenthal-jason** [comment]
@chriseppstein There's really not many steps to reproduce this. My environment is Mac OSX.

Once SASS is installed:

![image](https://cloud.githubusercontent.com/assets/7915144/13373213/b4317e42-dd26-11e5-8c4b-fccd5f69140b.png)

If I include the backtrace, it looks just like what @wildpine posted

**Comment by patrickhayescom** [comment]
How do I get/run the fixed version?  I just got the latest versions of Sass and Compass for Windows, and the bug fix isn't there:
_gem uninstall compass
gem uninstall sass
gem install sass -v 4.0.0.alpha.1
gem install compass -v 1.1.0.alpha.3
gem clean
sass-convert -R C:\Users\phayes\css_to_scss --from css --to scss --trace_
**sass_convert.rb:246:in `block in process_file': undefined method`read' for "C:/Users/phayes/css_to_scss/style-legacy.css":String (NoMethodError)**
