### ISSUE TITLE
Add increment and decrement operators

### ISSUE THREAD

**Issue by Petah** [sass/sass#183]
It would be nice to have ++ and -- included.

Here is my use case:

```
.ui-toolbar > .editor-ui-button {
    $i = 1;

    &-save,
    &-cancel {
        @include box-ordinal-group($i++);
    }

    &-undo,
    &-redo {
        @include box-ordinal-group($i++);
    }

    &-bold,
    &-italic,
    &-underline {
        @include box-ordinal-group($i++);
    }

    &-text-size-inc,
    &-text-size-dec {
        @include box-ordinal-group($i++);
    }

    &-horizontal-rule {
        @include box-ordinal-group($i++);
    }

    &-float-left,
    &-float-none,
    &-float-right {
        @include box-ordinal-group($i++);
    }

}
```

**Comment by nex3** [comment]
This is not something I'm keen to support. For one thing, it's only clear what's going on to someone who's familiar with C-style programming languages. Also, we may change the semantics of variables in the future to be more declarative, which would be at odds with this operator.

**Comment by Petah** [comment]
so what would be the alternative to this?

**Comment by nex3** [comment]
You could write `$i += 1`, I suppose.

**Comment by Petah** [comment]
Is that not C-style?, and does that work, or will it be implemented?

**Comment by nex3** [comment]
Oh, sorry, it's actually `$i = $i + 1`; `+=` isn't implemented either, and I don't anticipate it will be.

**Comment by Petah** [comment]
Why is it not considered to be implemented?

Given the above use case, do you think it is acceptable to do the following:

```
.ui-toolbar > .editor-ui-button {
    $i = 1;

    &-save,
    &-cancel {
        @include box-ordinal-group($i);
    }
    $i = $i + 1;

    &-undo,
    &-redo {
        @include box-ordinal-group($i);
    }
    $i = $i + 1;

    &-bold,
    &-italic,
    &-underline {
        @include box-ordinal-group($i);
    }
    $i = $i + 1;

    &-text-size-inc,
    &-text-size-dec {
        @include box-ordinal-group($i);
    }
    $i = $i + 1;

    &-horizontal-rule {
        @include box-ordinal-group($i);
    }
    $i = $i + 1;

    &-float-left,
    &-float-none,
    &-float-right {
        @include box-ordinal-group($i);
    }

}
```

To quote the home page I don't think it is "Syntactically Awesome"

This could be implemented in a variety of ways including:

```
$i++ / $i--
$i += 1 / $i -= 1
@inc $i 1 / @dec $i 1
```

I am only requesting this as I have already implemented this in the PHamlP version of Sass, and I do not want to diverge from the main Sass

**Comment by nex3** [comment]
As I said, this is a feature that really only appeals to programmers who are used to it from other languages, and provides no benefit to people coming to Sass from a design standpoint (and is in fact more difficult for them to understand). In addition to this, it conflicts with the proposed semantics of CSS variables, which we may want or need to support in the future.

**Comment by Petah** [comment]
I'm sure a non programmer would understand the semantics of an increment/decrement operator.

How does it conflict with the proposed semantics of CSS variables.

**Comment by nex3** [comment]
The proposed CSS variables have a consistent value throughout the stylesheet; once the variable is set, it takes on that value everywhere in the stylesheet, before or after.

**Comment by davevasquez** [comment]
As a designer this would be a really useful thing to have.  I came here by way of google searching for how to do this.  I have a variable I want to maintain throughout our site (a z-index value), but want a particular element to always be +1 greater than the variable (which may change over time).  Being able to link them via a simple increment operator would be extremely helpful so I don't inadvertently break things by changing the variable and forgetting to change this other value that should always be 1 greater.  I was hoping it would be as simple as $variable++ but I guess we aren't quite there yet?

**Comment by whaaaley** [comment]
@davevasquez z-index is a great example.

I'd say most designers who work with CSS also, at the very least, dabble in JavaScript, and creating a for loop with i++ is one of the first things you learn. To me, this is no more complicated than using a any kind of loop.

**Comment by Snugug** [comment]
Duplicate of #502

**Comment by nex3** [comment]
@davevasquez for use-specific examples like that, it's very easy to write a function that does it more semantically:

``` scss
$z-index: 0;
@function next-z-index() {
  $z-index: $z-index + 1;
  @return $z-index;
}
```

**Comment by davevasquez** [comment]
@nex3 Thanks for the helpful function!

**Comment by CathyMacars** [comment]
@dustindowell22 agreed

**Comment by lukewatts** [comment]
I don't think those who understand how to program should have their hands tied for fear of confusing people who don't want to use the programming constructs anyways. Surely if $I++ is too confusing then loops through nested lists and maps are all too confusing and should never have made it into Sass either. I'm not trying to be flippant but surely Sass is already too complicated for someone not willing to learn the basics of C-Style programming, so why not just add in incrementors and decrementors for the 2% of situations where they would be necessary?

**Comment by ghost** [comment]
Recently, I've been abusing a lot of Sass and `$i++` looks like a pretty addition. SassScript is already very strong and this is not a far throw for iterators.

**Comment by seahindeniz** [comment]
Well, whenever I try to wrote Scss, I get more familiarity with C-Style syntax than any other non-C-Style langs

I mean comparing these simple examples, its just enough to confirm 🙂 
```scss
@function foo($bar: 1){
  $bar: $bar + 1;

  @return $bar;
}

// Call it as
foo();
```

```js
function foo($bar = 1){
  $bar= $bar + 1;

  return $bar;
}

// Call it as
foo();
```
