### ISSUE TITLE
how to negate a selector not(first-child)

### ISSUE THREAD

**Issue by kiga01** [sass/sass#1833]
guys i'm trying to get a rule that only a apply to all the selectors of a class without the first element

for example .column:not(first-child)

how can i do something like this with sass? 

thank u

**Comment by alexandradeas** [comment]
You would simply use the css pseudo-selectors and write `.column:not(:first-child)` - note that you missed the semi-colon on :first-child - however, I'd personally advise against chaining pseudo-selectors as legacy browsers have trouble supporting them in my experience.

A better alternative would be to simply create `.column` and apply your styles then simply overwrite `.column:first-child`  to apply your styles to the first child. This will give you a faster rendering time and greater cross-browser consistency.

**Comment by chriseppstein** [comment]
Sorry, our issue tracker is not for general support of how to write CSS. Please seek support in a more appropriate forum.
