### ISSUE TITLE
Spaces around slash separators could be removed for more compression

### ISSUE THREAD

**Issue by carols10cents** [sass/sass#1834]
I noticed in [this sass-spec test case](https://github.com/sass/sass-spec/blob/master/spec/basic/15_arithmetic_and_lists/input.scss) that spaces around slash separators are preserved (note the difference in the output between [property h](https://github.com/sass/sass-spec/blob/master/spec/basic/15_arithmetic_and_lists/expected_output.css#L12) and [property m](https://github.com/sass/sass-spec/blob/master/spec/basic/15_arithmetic_and_lists/expected_output.css#L20)).

I would have expected the spaces to be removed, especially in compressed output.

Small test case [on sassmeister](http://sassmeister.com/gist/4ba47e8111f706d5c395) with  libsass (v3.2.5), current behavior seems to be the same with the different versions I tried (so this would be a feature request):

Input:

```
div {
  margin: 0/0/0/0;
  padding: 0 / 0 / 0 / 0;
}
```

Current compressed output:

```
div{margin:0/0/0/0;padding:0 / 0 / 0 / 0}
```

Expected compressed output:

```
div{margin:0/0/0/0;padding:0/0/0/0}
```

Please let me know if there's any other information that would be helpful! :heart:

**Comment by chriseppstein** [comment]
I assume you're using slashes for border-radius and not margin or padding since that's not legal css.

And yes, this would be a very minor improvement to our compression mode. `/` is not very common in CSS values. We'll happily accept a patch for this.

**Comment by HamptonMakes** [comment]
A case where sass-spec is born to model Ruby Sass parser, even when it's a "bug" (or semi-unintentional behavior). Eagle eyes badge for you on this one.

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/387
