### ISSUE TITLE
Fatal error running sass under setuid

### ISSUE THREAD

**Issue by VictorNicollet** [sass/sass#184]
On a fresh install of sass 3.1.8 on a Debian system, I have the following problem:

```
cat *.scss | sass --trace --scss -t compressed > ../public/full.css
/usr/lib/ruby/vendor_ruby/1.8/rubygems/defaults.rb:40:in `exist?': Insecure operation - exist? (SecurityError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/defaults.rb:40:in `default_path'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:752:in `path'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/source_index.rb:59:in `installed_spec_directories'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1051:in `source_index'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:243:in `activate_dep'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:236:in `activate'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1307:in `gem'
    from /usr/local/bin/sass:18
```

The problem only happens when the command is run as part of a process that is setuid www-data (the "web server" user on the box) from one of the non-root users. When a non-root user runs that command, it works. When root runs the process that does the setuid www-data, it also works. 

I suspect some kind of file permission issue when running sass, but don't really know how to explore this further. 

Thank you for your help.

**Comment by nex3** [comment]
This looks like a Rubygems issue, not a Sass issue.

**Comment by bregenspan** [comment]
closed by pigeon
