### ISSUE TITLE
A render issue in documentation

### ISSUE THREAD

**Issue by biokillos** [sass/sass#1840]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_

??? instead of '

![2015-09-23 23-13-41 file sass_reference sass documentation - google chrome](https://cloud.githubusercontent.com/assets/7377940/10059020/cf7d1598-6248-11e5-8113-e5d9248ad852.png)

**Comment by chriseppstein** [comment]
Hmm. I redeployed and it's fixed. I think one of the other devs may have some system issue mucking with unicode support >_<
