### ISSUE TITLE
Set random_seed?

### ISSUE THREAD

**Issue by blixt** [sass/sass#1845]
Is there a way to set the `random_seed` class variable to ensure that my generated CSS doesn't change behavior over time?

Some random patterns are simply much more beautiful than others, and being able to set the seed before generating CSS would avoid having to test and regenerate in case the random pattern is undesirable.

**Comment by chriseppstein** [comment]
There's not a super convenient way to do this, but yes, it's possible:

```
Sass::Script::Functions.random_seed = 0
```

If you are using Compass, you can drop this into your config.rb. If you are using the sass cli you need to put this into a ruby file and use the `-r ./sass_random_seed.rb` cli option to run it.

**Comment by chriseppstein** [comment]
Note: Sass does this in it's own tests to make sure they are predictable: https://github.com/sass/sass/blob/144e581b32bee04fb58e3dcdb10a9c2b87bec00c/test/sass/functions_test.rb#L1636

**Comment by blixt** [comment]
Yup I did see that option, but it requires a lot of hacking on the consumer end when SASS is just a step in a build pipeline. Is there any way I could convince you to reopen this task as a request to enable the seed to be set from within SASS syntax?

To give you an idea, here's part of a gulpfile for my website:

``` javascript
gulp.task('sass', () => {
  return gulp.src('./sass/main.scss')
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.rename('roger.css'))
    .pipe(plugins.sourcemaps.write({includeContent: false}))
    .pipe(plugins.sourcemaps.init({loadMaps: true}))
    .pipe(plugins.autoprefixer({
      browsers: ['last 2 versions']
    }))
    .on('error', plugins.util.log)
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('./s/'))
    .on('error', plugins.util.log);
});
```

I'm not sure how to use your suggestion with the upstream package `node-sass` which is used by `gulp-sass`, and even if I can pass in a custom Ruby file, it would spread out configuration in many places, when all I really want to do is indicate that the random seed is fixed, right next to the actual SASS that depends on `random()` is written.
