### ISSUE TITLE
Dynamically passing lists as arglists?

### ISSUE THREAD

**Issue by mil** [sass/sass#1849]
Using Sass's call() function, it seems you can only pass arguments to functions individually. E.g. so writing something like:

``` sass
@function test($args...) {
  @return length($args);
}

$some-list: a, b, c;
$result: call(test, $some-list);
```

will yield `$result` as `1`.. However, writing:

``` sass
$result(test, a, b, c)
```

would yield `$result` as `3`.

So I am wondering is if there is a way to dynamically create and modify arglists to pass to `call()` or other functions (e.g. how could I make the first example yield `$result` as 3 while still keeping `$some-list` as a variable)?

I've tried examples where I modify the callee's arglist but it seems passing that list to `call()` still passes the arglist as a single list.

**Comment by cimmanon** [comment]
You need to use the ellipsis syntax to expand the list to individual arguments:

``` scss
$result: call(test, $some-list...);
```

**Comment by mil** [comment]
ah doh - didn't realize that was valid syntax. thanks @cimmanon
