### ISSUE TITLE
issue for rgba function

### ISSUE THREAD

**Issue by long800110** [sass/sass#1853]
when I use the function `rgba(#ffffff, 1);` , the result show as  `white`, but `#ffffff` is my expect. How can I convert the result of named color to Hex?
Any solution for it?

**Comment by cimmanon** [comment]
Related: https://github.com/sass/sass/issues/343

**Comment by chriseppstein** [comment]
The color sass outputs is the same color. There's no x-browser compat issues. This is just an aesthetic that you disagree with, and that's ok.
