### ISSUE TITLE
Invalid parent selector when nesting Sass ampersand (&) in Child selector (>)

### ISSUE THREAD

**Issue by pat270** [sass/sass#1857]
Not sure if this is a bug or working as intended.

```
.code.ruby > {
    &.ruby {
        color: green;
    }
}
```

Throws `Invalid parent selector for "&.ruby": ".code.ruby >"` in Ruby 3.4.14. I expect it to output:

```
.code.ruby > .ruby {
    color: green;
}
```

Strangely, some invalid css passes:

```
.code.ruby > {
    &+.ruby {
        color: green;
    }
}
```

Outputs:

```
.code.ruby > + .ruby {
  color: green;
}
```

**Comment by chriseppstein** [comment]
Your parent selector ends in a combinator instead of a simple selector. I don't know why you would expect that output from that input. To get the output you want you need to add a space between `&` and `.ruby`. Or you can simply remove the `&` as `&` is implicit in the start of every selector that does not contain it.

**Comment by chriseppstein** [comment]
See #1836 for a discussion on illegal selectors.

**Comment by pat270** [comment]
Hey @chriseppstein, thanks for responding so quickly and for the discussion above. I only filed this as an issue because there was a discrepancy between LibSass 3.2.5 and Ruby 3.4.14 parsers. The code above compiles with LibSass but errors in Ruby. See http://sassmeister.com/gist/36486158ba84062cd13f.

I admit I don't know anything about the sass engine, all I have to go on is http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector. It states "& must appear at the beginning of a compound selector, but it can be followed by a suffix that will be added to the parent selector." With this definition, the behavior of the work around you suggested, and the response from nex3 in the issue above I think it supports my expectation.

**Comment by cimmanon** [comment]
@pat270 When there is a discrepancy between LibSass and the official Ruby Sass, the bug report should be filed against LibSass.

**Comment by pat270** [comment]
Thanks @cimmanon, I filed an issue at https://github.com/sass/libsass/issues/1601.
