### ISSUE TITLE
The option of not getting rid of empty selectors

### ISSUE THREAD

**Issue by joseluis** [sass/sass#1858]
I'm wondering if there is a way to avoid the filtering out of the empty selectors on compilation? Didn't find anything about this in the docs, or anywhere really.

I have the use case of having to generate CSS stylesheets intended to be edited later and maintaing all the original selectors in them. I'd like to use Sass as a preprocessor since it fits perfectly for the rest of the needs.

thank you

**Comment by KittyGiraudel** [comment]
As far as I can tell, there is no such option.

**Comment by chriseppstein** [comment]
> I have the use case of having to generate CSS stylesheets intended to be edited later and maintaing all the original selectors in them. I'd like to use Sass as a preprocessor since it fits perfectly for the rest of the needs.

Put a `/* ... */` comment in them.

**Comment by joseluis** [comment]
> Put a /\* ... */ comment in them.

I agree that would be the most sensible option given the circumstances. Thanks!
