### ISSUE TITLE
Some spaces missing, resulting in invalid CSS

### ISSUE THREAD

**Issue by NoNoNo** [sass/sass#186]
Minimal test case:

```
#bar {
  content: '';
  $colorTop: green;
  $stop1: 25%;
  $colorBottom: red;
  $stop2: 75%;
  background: -moz-linear-gradient(top, #{$colorTop} 0%, #{$colorTop} #{$stop1}, #{$colorBottom} #{$stop2}, #{$colorBottom} 100%);
}
```

Expected result:

```
@charset "UTF-8";
#bar {
  content: '';
  background: -moz-linear-gradient(top, green 0%, green 25%, red 75%, red 100%); }
```

Actual result: 

```
@charset "UTF-8";
#bar {
  content: '';
  background: -moz-linear-gradient(top, green0%, green25%, red75%, red100%); }
```

If I comment out the `content:` line using `//` the result it still wrong; if I delete the line, the result is correct.

If I say `content: 'o';` the result is correct.
If I say `content: 'ä';` the result has two correct spaces and two missing spaces: 
`background: -moz-linear-gradient(top, green 0%, green25%, red75%, red 100%); }`
If I put  `content:` after the `background:` the result is correct in any case.

`Sass 3.1.8 (Brainy Betty)`

Thanks & greetings!

**Comment by NoNoNo** [comment]
This bug is still in Sass 3.1.10 (Brainy Betty).

**Comment by nex3** [comment]
I can't reproduce this. Can you put a file that reproduces this in a gist? It looks like it's some sort of encoding issue, so I need to get at it in a way that preserves encodings.

**Comment by NoNoNo** [comment]
https://gist.github.com/1422468

**Comment by nex3** [comment]
I'm afraid I'm still unable to reproduce this, even from the gist. I'm going to close the issue as unreproducable; if you can figure out more information that might lead to a reproduction, I'll certainly re-open it.
