### ISSUE TITLE
pass an argilst into an arglist

### ISSUE THREAD

**Issue by mkstix6** [sass/sass#1860]
It's possible i just have a lack of syntax knowledge here, apologies if so.

I have a function that calls a function.
Both functions accept arglists.

When passing the first argilst into the second function as an argument the process breaks. Through testing it's as if the second function is sent a string with quotes and commas in.

I'm not sure if there's:
1) just a work around for this
2) whether there's a bug in my code
3) whether there's a limitation in SASS

I did try to look for a function to split a string by a delimiter but I don't think that exists.

Below: Reduced functions and the data they're intended to work within.

The first `$A: col('brands','facebook', 'active','small');` fails as it tries to call `map-deep-get` within itself. In the debug you can see the `keyloop` hasn't been delivered separate keys.

The second `$B: map-deep-get($colors,'brands','facebook', 'active','alternative');` works.

Would like to understand why this doesn't quite work and if there's a work around.

```
$colors: (
    'primary': (
      'active': #111111,
      'base': #222222,
      'highlight': #333333,
    ),
    'secondary': (
        'base': #444444,
    ),
    'brands': (
        'twitter': #55acee,
        'facebook': (
          'base': #3b5998,
          'hover': #5b79b8,
          'active':(
                'base':#1b3978,
                'alt':#666666
            ),
        ),
        'pinterest': #cc2127,
        'instagram': #3f729b,
        'google_plus': #dd4b39,
        'whatsapp': #4dc247,
        'wordpress': #21759b,
        'base':#123456,
    )
);

@function map-deep-get($map, $keys...) {
    $value: $map;
    @each $key in $keys {
        @debug 'keyloop: #{$key}';
        $value: map-get($value, $key);
    }
    @return $value;
}

@function col($color-name, $tone...) {
  @if length($tone) == 0 {
    $tone: base;
  }
  @return map-deep-get($colors, $color-name, $tone);
}

@debug "THIS DOES NOT WORK | col('brands','facebook', 'active','alternative')";
$A: col('brands','facebook', 'active','small');
@debug 'RESULT-A: #{$A}';

@debug "THIS WORKS | map-deep-get($colors,'brands','facebook', 'active','alternative')";
$B: map-deep-get($colors,'brands','facebook', 'active','small');
@debug 'RESULT-B: #{$B}';
```

**Comment by cimmanon** [comment]
Your example is pretty convoluted, but I'm pretty sure this is a duplicate of https://github.com/sass/sass/issues/1849

**Comment by mkstix6** [comment]
Yes, looking at #1849 i can see that my problem (aside from the convolution) is from trying to pass:
2 variables and an arglist
into map-deep-get that's expecting
a variable and an argilst

arglists are just a little less flexible than i assumed.

Thank you @cimmanon

**Comment by mkstix6** [comment]
@cimmanon If you had time could you expand a little on the convolution you're seeing. It might help me in the long run.

**Comment by mkstix6** [comment]
I replaced the col() function with this in the end:

````
@function col($color-name...) {
  @if length($color-name) == 0{
    @error 'missing arguments in col()';
  }
  @if length($color-name) == 1 {
    @if map-deep-get($colors, $color-name...) != color{
    	$color-name: append($color-name,'base');
    }
  }
  @return map-deep-get($colors, $color-name...);
}
````

**Comment by mkstix6** [comment]
I changed the col() function, this works better:

```
@function col($color-name...) {
  @if length($color-name) == 0{
    @error 'col() must have at least 1 argument';
  }
  @if length($color-name) == 1 {
    @if type_of(map-deep-get($colors, $color-name...)) != color{
        $color-name: append($color-name,'base');
    }
  }
  @if type_of(map-deep-get($colors, $color-name...)) != color{
    @error 'colour not found using col()';
  }
  @return map-deep-get($colors, $color-name...);
}
```
