### ISSUE TITLE
Small thing: Add map and list to type-of() example in documentation

### ISSUE THREAD

**Issue by mkstix6** [sass/sass#1861]
On a search through the docs I made the mistake of thinking the type_of() example was exhaustive of the types it detected.
I worked out after that it does detect map and list.
Looking round the net I think other people have made that mistake too.

Current example makes the function seem less capable than it is. Below:

```
type-of(100px)  => number
type-of(asdf)   => string
type-of("asdf") => string
type-of(true)   => bool
type-of(#fff)   => color
type-of(blue)   => color
```

This is something that will affect only a few people but I think even one line mentioning something about list and map (and any other types) would improve the docs.

**Comment by chriseppstein** [comment]
It also detects `null` and returns `"null"`

**Comment by nex3** [comment]
This was done as part of 5d44df5aa.
