### ISSUE TITLE
Engine's :filename option is not required, can cause erroneous "@import loop"

### ISSUE THREAD

**Issue by nanodeath** [sass/sass#1865]
If you have a custom importer that doesn't specify a filename parameter in the returned `Sass::Engine` object, and that importer shows up twice in the import stack (or another, similarly-behaving importer), you'll erroneously get an `An @import loop has been found` error.

This is because the `visit_import` method [checks](https://github.com/sass/sass/blob/b409aad5fb34f363cec426f2102dd7005e1a45a6/lib/sass/tree/visitors/perform.rb#L318) the stack to see if any element has the same filename as the current importer...which, if both filenames are `nil`, will return true and cause a loop error to occur, even if there is no loop.

In `Sass::Engine`'s [`normalize_options`](https://github.com/sass/sass/blob/4e3e1d5684cc29073a507578fc977434ff488c93/lib/sass/engine.rb#L174) method, it's even recognized that `:filename` [might not](https://github.com/sass/sass/blob/4e3e1d5684cc29073a507578fc977434ff488c93/lib/sass/engine.rb#L179) be passed, but is not considered an error condition.

I'm not sure what the best fix is. The simplest would probably be to exclude nils from the import-loop check, but this may open the door for infinite loops if not done carefully (e.g. in case a no-filename importer was a part of a loop). Or in the next minor version bump, perhaps `:filename` could be made required.

**Comment by chriseppstein** [comment]
> In Sass::Engine's normalize_options method, it's even recognized that :filename might not be passed, but is not considered an error condition.

The `:filename` option is `nil` when working with standard input. Your custom importer is non-conforming per [the documentation](http://sass-lang.com/documentation/Sass/Importers/Base.html#find-instance_method) which states that the `:filename` option for a custom importer should be set to the URI.

**Comment by nanodeath** [comment]
Even though this is technically user error, it would be nice if Sass did anything to validate that the custom importer is actually conformant. It sounds like the STDIN case is the only case in which `:filename` isn't required.

**Comment by chriseppstein** [comment]
Agree that would be better for developers of new importers. This is a relatively rare thing though. Not a big fan of adding code that slows down every user's imports even if by a few clock cycles to detect a problem that an add-on developer can easily detect and fix in development. we documented the behavior and I don't think it's too much to ask developers to read the base class contract when implementing it.

**Comment by chriseppstein** [comment]
Though, one possibility is to have a TestUnit test case that lints an implementation of Importer::Base to ensure conformity. This wouldn't require us to do anything at runtime.

Not super high on my todo list but would be a thing we'd accept as a patch.
