### ISSUE TITLE
Comment interpolations have wrong source_range

### ISSUE THREAD

**Issue by srawlins** [sass/sass#1868]
When visiting a Sass tree with a visitor (and expanding to visit things like comments, script interpolations and script funcalls), Sass::Script::Tree::Interpolation nodes (and nodes within) have wrong `#source_range`. It appears to not understand when comments are on their own lines, maybe? Here's a recreate script:

``` ruby
require 'sass'

class InterpolationVisitor < Sass::Tree::Visitors::Base
  def visit_comment(node)
    puts "Comment at:       #{node.source_range.inspect}"
    yield
  end

  def visit_script_funcall(node)
    puts "Funcall at:       #{node.source_range.inspect}"
    yield
  end

  def visit_script_interpolation(node)
    puts "Interpolation at: #{node.source_range.inspect}"
    yield
  end
end

module Sass::Tree
  class CommentNode
    def children
      super + value.select { |item| item.is_a?(::Sass::Script::Tree::Node) }
    end
  end
end

module Sass::Script
  class Tree::Funcall
    def self.visit_method; :visit_script_funcall; end
  end

  class Tree::Interpolation
    def self.visit_method; :visit_script_interpolation; end
  end

  class Tree::Variable
    def self.visit_method; :visit_script_variable; end
  end
end

sass = <<SASS
$color: purple;
/* \#{hue($color)} */

$color: purple;
/* \#{hue($color)} */
SASS

puts sass
tree = Sass::Engine.new(sass, {syntax: :scss}).to_tree
InterpolationVisitor.new().send(:visit, tree)
```

This produces:

```
Comment at:       nil
Interpolation at: (2:15 to 2:29)
Funcall at:       (2:17 to 2:28)
Comment at:       nil
Interpolation at: (5:53 to 5:67)
Funcall at:       (5:55 to 5:66)
```

which is definitely way wrong.

**Comment by srawlins** [comment]
It's probably not high priority to fix internal, undocumented API bugs (this is for brigade/scss-lint#568), so I'd be happy to contribute a fix. I'll probably need a hint though.

**Comment by chriseppstein** [comment]
@srawlins This appears to be an oversight. We just didn't think that comment nodes were important from a source-mapping perspective or we missed it.

We just don't pass a source range when we make a `Sass::Tree::CommentNode`:
- .scss syntax: https://github.com/sass/sass/blob/stable/lib/sass/scss/parser.rb#L176
- .sass syntax: https://github.com/sass/sass/blob/stable/lib/sass/engine.rb#L779

Hopefully that's enough to get you going on a patch.
