### ISSUE TITLE
Invalid CSS after "  &+"

### ISSUE THREAD

**Issue by tlobinger** [sass/sass#187]
I get the following error with the new sass gem 3.1.8 - it works with 3.1.4

Syntax error: Invalid CSS after "  &+": expected number or function, was "section#content {

the code looks like that

```
aside {
  width: $column * 2 + $gutter * 1;
  background: url("/assets/img/aside_background.png") top left no-repeat;
  margin-top: 32px;
  min-height: 800px;
  &+section#content {
    margin-left: 24px;
  }

...
```

**Comment by nex3** [comment]
Duplicate of #182.
