### ISSUE TITLE
Support for @nest

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1870]
https://tabatkins.github.io/specs/css-nesting/#at-nest

We should parse `@nest` directives as nested selectors and just drop the `@nest` directive in our output. Later if `@nest` becomes well supported we can output all nested selectors as `@nest` directives instead of permuting/expanding them.

@tabatkins @nex3 thoughts?

**Comment by tabatkins** [comment]
Sounds fine to me, but note that Nesting hasn't been accepted by the CSSWG yet.

**Comment by nex3** [comment]
Usually we wait until there's at least one browser that supports a new CSS feature before we add explicit support for it.

**Comment by nex3** [comment]
There doesn't seem to be a lot of movement towards accepting this within the CSSWG, so I'm going to close this out until there's an official working group draft.
