### ISSUE TITLE
How to import a string from a file using SASS?

### ISSUE THREAD

**Issue by gajus** [sass/sass#1876]
I want to import SVG from a file (to hard-code it in the CSS), e.g.

``` scss
$svg-icon: @import('./icon.svg');
```

Is this possible at all using SASS?

**Comment by chriseppstein** [comment]
Sass, the language, does not provide any such facility. But Sass lets extensions do things like this. For instance, the eyeglass framework for node-sass has the ability to [read arbitrary files about to land](https://github.com/sass-eyeglass/eyeglass/pull/67). In ruby land, the compass framework has the ability to inline SVG files. I'm sure there are other solutions out there.

**Comment by strarsis** [comment]
[eyeglass-file-text](https://github.com/strarsis/eyeglass-file-text) for plain text + binary files (as base64 string)
[eyeglass-inline-svg](https://github.com/strarsis/eyeglass-inline-svg) (uses eyeglass-file-text above + [eyeglass-inline-urlescape](https://github.com/strarsis/eyeglass-inline-urlescape)) 
for plain text in data uris, notably SVG files.

With best regards

**Comment by gajus** [comment]
@strarsis Thank you for sharing this.
