### ISSUE TITLE
Breaking change in 3.1.8: unexpected illegal nesting error

### ISSUE THREAD

**Issue by ChristianPeters** [sass/sass#188]
The @each directive in the following statement leads to an SyntaxError: `Illegal nesting: Only properties may be nested beneath properties.`:

``` Sass
  ul
    margin:
      @each $side in top right left
        #{$side}: $std-whitespace / 2
```

This worked in 3.1.7 and breaks in 3.1.8.

As a workaround, you can write:

``` Sass
  ul
    @each $side in top right left
      margin-#{$side}: $std-whitespace / 2
```

Well, it is not a big issue. I clearly prefer the former notation though. Nesting the directive under the margin property tells stylesheet readers that they do not have to "evaluate" this non-trivial statement if they are not interested in margins right now.

**Comment by nex3** [comment]
Closed by 424e847cc4490d751e1ae7c53f2193ddb3c2807a
