### ISSUE TITLE
Inconsistencies in messages

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1880]
These were discovered by LibSass and Sass Spec. As the LibSass team closes in on parity Sass' small inconsistencies make Sass Spec angry at us. Below are some of the one currently hurting us. I'd PR a fix myself but there it's not clear which is right way to go.

---

~~Too many arguments.~~

This was mistake on my behalf.

---

Deprecations warnings

```
WARNING: Function bar takes 4 arguments but 5 were passed.
        on line 23 of test.scss
This will be an error in future versions of Sass.
```

```
DEPRECATION WARNING on line 15 of test.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.
```

```
DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 15 of test.scss
```

---

Inconsistencies with file path. Sometimes the file path displayed in console messages is relative, other times it's absolute. I've been update to reverse engineer a reliable algorithm for when to use which. I suspect it's non-standard.

```
$ sass /sass/sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss
DEPRECATION WARNING on line 1 of /sass/sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.
```

```
$ sass sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss
DEPRECATION WARNING on line 1 of sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.
```

```
$ sass ../sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss
DEPRECATION WARNING on line 1 of ../sass-spec/spec/libsass-closed-issues/issue_1681/url/input.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.
```

```
$ sass foo/test.scss
DEPRECATION WARNING on line 6 of foo/test.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.
```

**Comment by xzyfer** [comment]
**update** I've patch sass-spec to be more forgiving about file paths. This issue is merely food for thought now.

**Comment by chriseppstein** [comment]
Our deprecation warnings are ad hoc, it would be good if they were handled more consistently.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
