### ISSUE TITLE
:not producing incorrect css

### ISSUE THREAD

**Issue by lisatassone** [sass/sass#1882]
Hi there,

I believe I have discovered an anomaly with the :not selector.  I am using Sass 3.4.19.

I have something like this:

``` sass
[class^="icon-"]
  font-family: 'icons'

.icon-down-arrow:before
  content: "\e00e"

#cNav li
    &.levelOne
      display: inline
      float: left
      position: relative
      a
        display: block
        height: 19px
        padding: 11px 11px 7px
        color: #666
        [class*="icon"]:not(.icon-down-arrow)
          font-size: 16px
          width: 20px
          vertical-align: -10%
        .icon-down-arrow
          font-size: 7px
```

and further down this:

``` sass
.ui-icon-triangle-2-n-s
    @extend .icon-down-arrow

a.mceOpen
  @extend .icon-down-arrow
  font-family: 'icons'
  font-size: 7px
  display: table-cell !important
  vertical-align: middle !important
```

The resulting css is muddled. Where it should produce:
# cNav li.levelOne a [class*="icon"]:not(.icon-down-arrow)

its producing:
# cNav li.levelOne a [class*="icon"]:not(.icon-down-arrow):not(.ui-icon-triangle-2-n-s):not(a.mceOpen)

Seems to be chaining the :not's together without regard to the defining parent selectors.

**Comment by chriseppstein** [comment]
This is working as expected. You extended the `.icon-down-arrow` class. That means you've created an equivalence between that class and the extending classes (E.g. `a.mceOpen` is an `.icon-down-arrow`), so if you exclude the base class in a `::not()` pseudoselector, the relationship you've defined with extend means that sass also has to exclude the classes that inherit from it.

**Comment by lisatassone** [comment]
Thanks for the explanation @chriseppstein. My understanding was that just the properties of the class were inherited (or copied) not that they would be tied together in other declarations using the base class.  Would placeholders behave the same way here?
