### ISSUE TITLE
unquote does not appear to work within #darken

### ISSUE THREAD

**Issue by rosskevin** [sass/sass#1884]
```
sass -i
>> darken(unquote("#f44336"), 4%)
SyntaxError: $color: "#f44336" is not a color for `darken'
```

This is mixin buried within a framework. While I can try to hunt down the source, I also think this _should_ work, shouldn't it?

**Comment by cimmanon** [comment]
All of the color manipulation functions, like [darken](http://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method), require a Color.  The [unquote](http://sass-lang.com/documentation/Sass/Script/Functions.html#unquote-instance_method) function returns a string with the quotes removed.

There is no reason to expect this code to compile at all.  Removing quotes around a string still makes it a string.

**Comment by rosskevin** [comment]
can this string be converted to a color?

**Comment by cimmanon** [comment]
No, it has to be a Color from the start.  That means don't quote it, and don't try to use the unquote function on it.
