### ISSUE TITLE
Parent selector clarification

### ISSUE THREAD

**Issue by robocoder** [sass/sass#1886]
Getting different output between sass and libsass. Wondering which behaviour is correct given this input?

```
ul, ol {
    & & {
      display: block;
    }
  }
```

**Comment by HamptonMakes** [comment]
So, Ruby Sass 3.4.14

```
ul ul, ol ul, ul ol, ol ol {
  display: block;
}
```

Libsass gives me: 

```
ul ul, ol ol {
  display: block;
}
```

I'm not 100% sure which is more correct, but libsass is closer to what I'd expect... but seems like Ruby sass is being a lot more clever with it's attempts to make it logical.

**Comment by chriseppstein** [comment]
`&` represents the entire parent selector. So `& &` in SassScript would be written as `selector-nest('ul, ol', 'ul, ol')` which returns `ul ul, ol ul, ul ol, ol ol`.

It sounds like libSass is just iterating over each comma-delimited portion of the parent selector and evaluating the child selector in that context which works for many cases, but definitely not this one.

**Comment by saper** [comment]
This works now properly as of libsass 3.3.2.
