### ISSUE TITLE
&:pseudoclass expanding doesn't work in v3.4.19

### ISSUE THREAD

**Issue by malcheg** [sass/sass#1887]
I have a piece of scss with pseudo class extending, that worked in v3.4.18, but after update to v3.4.19 it doesn't work anymore:

``` scss
.site-nav_link {
  ...
  ...
  &:hover {
    color: #cccccc;

   &:before {
      opacity: 1;
    }
    .site-nav_label {
      padding-left: 5px;
    }
  }

 &[data-active="true"] {
    @extend &:hover;    //<<<<<<------- it doesn't work in v2.1.0

    &.site-nav_link--exp:after {
      content: $icon-arrow-top;
    }
  }
}
```

Message from compiler:

``` scss
Message:
    ..\src\main\assets\scss\components\_filename_.scss
Error: Can't extend &:hover: can't extend parent selectors

       Backtrace:
        ../src/main/assets/scss/components/_filename_.scss:144
        on line 144 of ../src/main/assets/scss/components/_filename_.scss
>>     @extend &:hover;
   ------------^
```

**Comment by cimmanon** [comment]
Sassmeister reports as running 3.4.14 and it gives the same error.  I have a hard time believing the error message would be removed for a specific version between 3.4.14 and 3.4.19.  Are you sure this worked in 3.4.18?

Even if this didn't throw the above error, I don't see how this could possibly have compiled without error.  The selector you would be extending if this did work would be `.site-nav_link[data-active="true"]:hover`, which doesn't exist here.

**Comment by davidkpiano** [comment]
You would want to `@extend .site-nav_link:hover` here.

**Comment by malcheg** [comment]
Thx for fast response, i'm sure it was v3.4.18, but you're right my solution isn't logical.
