### ISSUE TITLE
Filesystem Listing

### ISSUE THREAD

**Issue by HamptonMakes** [sass/sass#1888]
I know this issue has been discussed before, wrt to dynamically being able to `@import` with globs, but I feel like it's time to revisit with Sass 4.0, and Sass now being a much more integral part of a lot of major, complex web build systems.

I propose that we allow for a standard library `fs-ls($dir)`  `file-ls($dir)` or  `$fs.ls($dir)` (modules!) function, that lists out the contents of the directory, using naive UTF-8 byte-value sorting, and optionally takes a second argument, that is either a string representing an allowed file extension, or a list of allowed extensions.

An example usage:

```
@use fs as $fs;

$dir: "icons"
@each $file in $fs.ls($dir, "png") {
  $icon: str-slice($file, str-length($dir) + 2, -5);
  .#{$icon} {
    width: 50px;
  }
}
```

Would be equivalent to:

```
$dir: "icons";
@each $file in ($dir + "/hello.png", $dir + "/myfile.png") {
  $icon: str-slice($file, str-length($dir) + 2, -5);
  .#{$icon} {
    width: 50px;
  }
}
```

Note: Obviously, the string manipulation part isn't great here, but that's also something we can work on elsewhere...

Note: This proposal would _not_ allow use with `@import` out of the box. I'd later perhaps propose that it's a special case we could handle if all of the arguments were static, but again... not included here.

**Comment by chriseppstein** [comment]
I've just built a filesystem API for eyeglass. There's a few things I don't like about it due to libsass limitations that should be fixed in the coming months (native functions don't know what file they are in... only importers can know their file context), but the functions provided there and the security system in place are worth considering for Sass core, IMO. 

https://github.com/sass-eyeglass/eyeglass/blob/fs/docs/filesystem/index.md

this hasn't landed in eyeglass yet -- I want to land it soon, but it's not too late to incorporate feedback.

**Comment by HamptonMakes** [comment]
The function names and stubs look good, and seem to be pretty similar.

Obviously, you are using the `@import "fs(dir)";` because that's the only real hook you have in the current Sass syntax, but I think we can agree that wouldn't be the form we'd want this to take.

Also, I really, really want to start thinking about how to form these utilities into standard-library modules that can be optionally included (or, in the case of fs, disallow it in many instances).

Hence, translate these into `$fs.exists($dir)` from `fs-exists($dir)`... I think this is something we could do easily across the board as equivalent functions.

@nex3 are you willing to consider revisiting our relationship to the file system?

**Comment by nex3** [comment]
I really don't like the idea of adding any filesystem stuff to Sass core. Once the core language refers to the OS in any way, it brings in a huge amount of complexity—path manipulation, error handling, and security all start being things we need to think seriously about. It also creates a tension where some core functions are incompatible with some contexts, like SassMeister.

This is still something I want to keep in the world of external packages. Ultimately we will need to be able to support packages defining native functions that work across Ruby and libsass—this is a great driving use-case for that.
