### ISSUE TITLE
Precision Functions

### ISSUE THREAD

**Issue by HamptonMakes** [sass/sass#1891]
I'm starting a new thread for this request, because while it's a solution to #1122, it's not the same as the title of that issue.

I propose that we treat precision like we do units. Set Sass::Script::Value to have precision not just defined as a class variable, but instead an instance variable. By default, we set it to whatever the default is. If you want to use a higher precision (or control it in your library/module), you can modify it with a function call. The left-hand value in any operation is the one that determines the output precision.

Adding two functions:

1) `value-precision($number)` which returns the current precision of the number
2) `value-set-precision($number)` returns a new copy of `$number` with a new precision set

We could also drop the `value-` prefix or use something else, if it seems more elegant. To work with future modules, I'd suggest whatever is on the left hand side would be the standard library name for these kinds of functions. Maybe `numeric` or `format`?

Here's some example usage.

```
@debug value-precision(2); // 5 (default!)
@debug value-precision(2.00); // still 5
@debug 2.00; // 2
@debug 2 / 3; // 0.66667;
@debug value-set-precision(2, 10) / 3; // 0.6666666667
@debug 3 / value-set-precision(2, 10); // still default, left hand wins // 0.66667
```

I think this is much better way to deal with the problem... each library can make it's own call about aesthetics. The function names are longer than normal people would want to write all the time (a concern @nex3 brought up in #1122) and I think would cover those cases where we _know_ precision isn't set.

This shouldn't break any existing code. It has almost no side effects. It would solve the issues these users are highlighting.

**Comment by chriseppstein** [comment]
I don't understand why we are revisiting this without any new ideas being proposed except a different name for a function that @nex3 rejected for grounds that would still apply here as well.

**Comment by HamptonMakes** [comment]
The original proposal I saw only had a "setter" function and was rejected because the information would then be totally hidden. I'm proposing a set of value modifiers for both set and get that matches the style (at least, an attempt to match) of string functions that we've introduced.

And, I don't think that just because an issue from March 2014 was a no, means that no reconsideration can ever be done. Seeing the hacks that users are having to do to get around this fairly obvious limitation (that's only getting worse with larger screen sizes), it's not just acceptable to say "well, we'll never fix this!" in my opinion.

I do agree that "hidden" attributes aren't the absolute sexiest idea ever, but I'm not sure we have a better idea. That issue, to me, is still an issue.

Why a new issue? Because I'd rather have a clear proposal to discuss, then a thread from a year and a half ago discussing a different possible solution.

**Comment by nex3** [comment]
I still don't like this idea. We should just straight-up increase the precision. Adding a new function for this doesn't provide nearly enough value.

**Comment by timostsauber** [comment]
I realise this is more than 5 years old now, but has this been 'straight-up increased? yet?

It's 2021 and this page appears in the Google results when I search for the 5 digit SASS precision limitation / bug, and I'm kind of scratching my head as to why?
