### ISSUE TITLE
Guard Support?

### ISSUE THREAD

**Issue by HamptonMakes** [sass/sass#1897]
Guard is a simple Ruby library that can run tests when the test is saved. Would this be something that you'd be open for having in the development configuration? (not required!)

**Comment by chriseppstein** [comment]
I have a Guardfile that I haven't checked in.

``` rb
# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard :test do
  watch(%r{^lib/(.+)\.rb$})     { |m| "test/#{m[1]}_test.rb" }
  watch(%r{^test/.+_test\.rb$})
  watch('test/test_helper.rb')  { "test" }
end
```
