### ISSUE TITLE
including an image path in a mixin?

### ISSUE THREAD

**Issue by jannisg** [sass/sass#19]
I'm trying to write a simple mixin that I can use to place an dropshadow image into, the mixin that isn't working is this:

```
@mixin dropshadow($img,$padding:30) {
    padding-bottom: $padding+px;
    background:{
        image: url(../images/+$img);
        position: center bottom;
        repeat: no-repeat;
    }
}
```

This doesn't work and I get this error

> error scss/style.scss (Line 309: Invalid CSS after "  image: url(": expected ")", was "../images/+$img);")

Any ideas on how I can do this?

**Comment by nex3** [comment]
According to the CSS spec, `url()` is another form of string quotes, so Sass treats it the same way (usually). In order to include a variable along with some other text, you need to use `#{}`, as in `url(../images/#{$img})`.

**Comment by jannisg** [comment]
works great, thanks!
