### ISSUE TITLE
control directives break nested properties

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#190]
Putting a control directive inside a nested property doesn't work. So, for example, the following doesn't do anything: 

```
.class {
    font {
        @if true == true {
            style: italic;
        }
    }
}
```

**Comment by NoNoNo** [comment]
Works for me:

```
.class {
    font {
        @if true == true {
            font-style: italic;
        }
    }
}
```

results in:

```
.class font {
  font-style: italic;
}
```

**Comment by wheresrhys** [comment]
now I realise my mistake - missed a  colon after "font"

**Comment by NoNoNo** [comment]
Ah, didn’t even know this feature "nested properties"…
