### ISSUE TITLE
Named colors become quote sensitive when used as keys in maps

### ISSUE THREAD

**Issue by Arnique** [sass/sass#1902]
Consider the following map variable:

```
$colors:(
  "black": #000,
  "blackish": #000
);
```

Normally map-get() would still be able to retrieve the key **"blackish"** with or without the quotes. Oddly, this is not the same case for **"black"** as it happens to be a named color, and map-get() suddenly becomes quote sensitive and treats **black** and **"black"** as 2 different keys. 

```
// Returns #000 with quotes
$test-1: map-get($colors, "blackish");

// Still returns #000 without quotes
$test-2: map-get($colors, blackish); 

// Returns #000 with quotes
$test-3: map-get($colors, "black");

// Returns null without quotes ???
$test-4: map-get($colors, black);
```

I'm finding this inconsistency quite annoying.

**Comment by cimmanon** [comment]
There's nothing inconsistent here.  Duplicate of https://github.com/sass/sass/issues/1256

**Comment by Arnique** [comment]
Pretty long thread. Let me go through it first.

**Comment by Arnique** [comment]
Okay, so basically

```
map-get($colors, black)
```

Is interpreted internally as

```
map-get($colors, #000)
```

and this is why it returns a null value?

**Comment by Arnique** [comment]
I guess I can live with the whole "named colors are objects" setup in Sass.
