### ISSUE TITLE
@import with placeholder paths

### ISSUE THREAD

**Issue by sthag** [sass/sass#1905]
Hi,

is it possible to use @import with a path like this `@import modules/*/*`?
The file/directory structure would be

```
modules/
    example/
        _example_module.sass
    exmaple/
        _exmaple_module.sass
main.sass
```

I tried it and the result is: `error ./main.sass (Line 1): File to import not found or unreadable: modules/*/*.`

Is there a way to accomplish this? I can not find it documented and need a hint.
My goal is to have a folder (modules) and to put reusable sass snippets (example, exmaple) in there. With the placeholder in the @import method the placed modules would then automatically be loaded.

**Comment by cimmanon** [comment]
You're looking for [Sass globbing](https://github.com/chriseppstein/sass-globbing).

**Comment by sthag** [comment]
Thanks. That's it.
