### ISSUE TITLE
SASS/Compass missing ; off last line for every element

### ISSUE THREAD

**Issue by DanCanetti** [sass/sass#1906]
When compiling it appears as though the CSS is missing the ; off each line of the css. I think this is causing issues with loading the site (www.danielcanetti.com) in safari.

I recently had issues using scss in compass so swtiched to sass syntax and this is when I started noticing the issues.

**Comment by chriseppstein** [comment]
It is legal to omit the semi-colon on the last property declaration in a ruleset. I don't think that is what is causing your problem. If it is, please submit a very small reproducible test case (ideally on a site like codepen) instead of just linking to your website.

**Comment by DanCanetti** [comment]
Hi Chris,

Thanks for getting back to me. I have fixed this by using the SCSS syntax instead.
