### ISSUE TITLE
@extend and & interracting in an unexpected way 

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#191]
```
.sel1 {
    .sel2 & { 
        height:775px; 
    }
}

.sel3 {
    .sel4 {
          @extend .sel1;
    }
}
```

results in e.g.

```
.sel2 .sel1,
.sel2 .sel3 .sel4,
.sel3 .sel2 .sel4  {
    height: 775px;
}
```

I would not expect ".sel3 .sel2 .sel4" to be included in the generated selector as I intend to extend ".sel3 .sel4". Furthermore, it seems to go against the text in the documentation "@extend works by inserting the extending selector (e.g. .seriousError) anywhere in the stylesheet that the extended selector (.e.g .error) appears.", i.e. without the extend rule the stylesheet woudl be

```
.sel2 .sel1 { 
        height:775px; 
}

.sel3 .sel4 {

}
```

So with the extend rule it should be

```
.sel2 .sel1,
.sel2 .sel3 .sel4 { 
        height:775px; 
}
```

**Comment by chriseppstein** [comment]
The use of descendent selectors is ambiguous. There's no guarantee of which ancestor will come first in the document, so sass permutes the ancestors to cover all possible document structures. You might consider whether you can extract a common base class and then extend it from both locations.

**Comment by chriseppstein** [comment]
also note: you get this same behavior without the use of the `&` operator.
