### ISSUE TITLE
Testing: assert_ranges_equal file assertion unhelpful

### ISSUE THREAD

**Issue by srawlins** [sass/sass#1910]
While working on @nex3's comments on #1875, switching to `assert_parses_with_mapping`, it was super hard to diagnose the following error:

```
  1) Failure:
SourcemapTest#test_selectors_properties_sourcemap_sass [/Users/srawlins/code/sass/test/sass/source_map_test.rb:397]:
Input.
--- expected
+++ actual
@@ -1 +1 @@
-"test_selectors_properties_sourcemap_sass_inline.sass"
+nil
```

This comes from [`assert_ranges_equal`](https://github.com/sass/sass/blob/stable/test/sass/source_map_test.rb#L922..L926).

**Comment by nex3** [comment]
Closing this out after talking it over on the pull request.
