### ISSUE TITLE
Allow min() and max() to accept lists

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#1913]
Currently `min()` and `max()` only accept arguments. However this can be confusing as arguments are formatted the same way as a list.

As a result I expected `min()` and `max()` to take lists in variable form like `min($list)` but this throws an error. While `min($list...)` works in Ruby Sass (LibSass has a bug with passing arguments in as `...`) it would be more clear to have these functions parse lists instead of arguments.

**Comment by chriseppstein** [comment]
@scottkellum what behavior would you expect if two lists of numbers were passed? Max over all of them? Error? A list of maximums?

**Comment by scottkellum** [comment]
@chriseppstein I expect this:

``` sass
$list: 5, 3, 6, 2;
@debug max($list);
```

To return `6`.

**Comment by davidkpiano** [comment]
This probably doesn't help, but you can do this [in Sassdash](http://davidkpiano.github.io/sassdash/sassdoc/index.html#function-_min): `_min($list);` (returns 6)

Just for comparison:
- JS: `Math.min(1, 2, 3)` accepts multiple arguments, not an array/list
- Ruby: `[1,2,3].min` not a function but accepts a list
- Python: `min(1, 2, 3)` also accepts multiple args but not an array/list

I think it's pretty standard to do this by multiple arguments, and not by passing in an array. Though I could see a `list-min($list)` function being useful.

**Comment by cimmanon** [comment]
@scottkellum Chris is asking about this case:

```
$list1: 1 2 3 4 5;
$list2: 6 7 8 9 10;
@debug min($list1, $list2); // what do?
```

For what it's worth, Haskell only allows 2 arguments to be passed to the `min` function (eg. `min 1 2`). Lists must be passed through the `minimum` function (eg. `minimum [1, 2, 3, 4 ,5]`), and lists of lists are allowed:

```
Prelude Data.List> minimum [[1, 2, 3], [4, 5, 6]]
[1,2,3]
```

I don't see the benefit to expanding min/max to accept lists when Sass already offers a construct to expand a list to fill in a function's arguments, and getting the minimum from 2 different lists seems like an unlikely task.  However, the documentation for the min/max functions _could_ use an example of how to pass in a list, since that is a fairly common operation that a user might want to perform.

**Comment by chriseppstein** [comment]
@cimmanon I agree that a documentation change is a minimally sufficient response to this issue for the current release.

But I also want Sass to be intuitive -- having to read docs for **common operations** means that we have failed to "Just Work" and the principle of least surprise is what we endeavor to adhere to for all our APIs.

**Comment by scottkellum** [comment]
@cimmanon Oh, that can throw an error for sure. Multi dimensional lists certainly seem like invalid inputs for this, as do strings and other things that aren’t comparable values.

I created this issue because I assumed lists of numbers would work. Apparently it is currently implemented the way many other languages are implemented and because I don’t have much of a programming background I was not aware of this pattern.

**Comment by KittyGiraudel** [comment]
>  Multi dimensional lists certainly seem like invalid inputs for this, as do strings and other things that aren’t comparable values.

The problem is that a multi-dimensional list is still a list, and that would make the function fail on some lists, but not all of them. I find it even more confusing.

**Comment by chriseppstein** [comment]
@HugoGiraudel I think `min($list...)` and `min($list)` are the same amount of confusing if the list is not comprised solely of numbers.

**Comment by nex3** [comment]
I think I'd rather just encourage users to write `min($list...)` here.
