### ISSUE TITLE
Division by zero sometimes produces strange errors

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1914]
The following sample:

```
foo {
  bar: (red / 0.0);
  bar: (red / #F0f);
}
```

Produces this error message:

```
ArgumentError: comparison of Fixnum with Float failed
```

Which is not very helpfull. IMO it should produce the same as `1 % 0`:

```
ZeroDivisionError: divided by 0
```

Although the message is kind of redundant ;)

Might be related to http://pjkh.com/articles/ruby-argumenterror-comparision-of-fixnum-with-float-failed/
Since it seems to be a native ruby error, there is no position indication, which would help even more!

**Comment by chriseppstein** [comment]
I intend to deprecate math operations with colors, so polishing the error messages isn't really worth the effort.
