### ISSUE TITLE
-(50px/2)

### ISSUE THREAD

**Issue by perfey** [sass/sass#1915]
sass
background: url(../img/xxx.png) no-repeat -(50px/2) 0;
to css
background: url(../img/xxx.png) no-repeat-25px 0;

error, loss of space. The following is correct:
background: url(../img/xxx.png) no-repeat -25px 0;

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1912

**Comment by chriseppstein** [comment]
Please see my comment on #1912
