### ISSUE TITLE
When using extend "html" can appear anywhere in the selector

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#192]
In the documentation SASS specifies it avoids creating useless selectors (e.g. #main#footer) when using extend. But I've been coming across things like

div html {

}

Should some rules for placing of special tags such as html and body be added to the @extend feature?

**Comment by nex3** [comment]
Sass avoids building in HTML-specific knowledge, in part because CSS can in theory be used with other sorts of XML documents. I don't think we can be confident enough that these sorts of selectors are useless to get rid of them.

**Comment by wheresrhys** [comment]
In that case, maybe this should be a feature request: for SASS to be configurable to treat html as a special selector if the user wants it (and maybe this should be the default setting). 

Putting classes on the html tag is so common these days, and those classes are often to apply generic styles to be inherited by other elements, so being able to use @extend on the html selector without risking lots of useless selectors being added to the stylesheet would be of great benefit I think.
