### ISSUE TITLE
[question] SCSS only displays one error in a page

### ISSUE THREAD

**Issue by abose** [sass/sass#1921]
Hi,
 We were creating an SCSS extension for https://github.com/adobe/brackets . The main aim is that we would be able to display `all` scss errors in the page in the lint panel.
  However, when i compile a file with many SCSS errors using `SASS test.sass -c` ; the check stops as soon as the first error is seen. Is it by design or is there a way to list all the errors in the sass file?

**Comment by daniilmatafonov** [comment]
Maybe this will help you 
http://webdesign.tutsplus.com/tutorials/an-introduction-to-error-handling-in-sass--cms-19996
Or you may use compass compiler. It is great, but you'll need ruby environment.

**Comment by chriseppstein** [comment]
Our parser stops at the first error -- it has no error recovery built in order to continue giving further errors.

**Comment by abose** [comment]
Thanks all for the answer .
