### ISSUE TITLE
Not polling for change on bsd platform

### ISSUE THREAD

**Issue by gkrnours** [sass/sass#1927]
Running sass 3.4.19 on openBSD with the --watch flag result in the following message from the listen gem:

> Please add the following to your Gemfile to avoid polling for changes:
> 
> ``` rb
>     require 'rbconfig'
>     if RbConfig::CONFIG['target_os'] =~ /(?i-mx:bsd|dragonfly)/
>       gem 'rb-kqueue', '>= 0.2'
>     end
> ```

The same message is available at [the listen repo](https://github.com/guard/listen#on-bsd).

**Comment by chriseppstein** [comment]
We use the listen gem, so yeah, if they print out a warning, you'll see it. I think if you pass `--poll` with with the `--watch` option it should avoid printing the warning message.

**Comment by gkrnours** [comment]
Oh.
I was hoping someone more familiar than I am with sass and Gemfile would be able to write a patch.
Thanks for pointing to `--poll` :)
