### ISSUE TITLE
Add type forcing function(s)?

### ISSUE THREAD

**Issue by whmii** [sass/sass#1928]
**problem**
I have been recently working on a grid system that uses a significant amount of `calc()` operations. While developing this framework, I've noticed that it is very difficult to force sass to not do calculations when it thinks that it can.

**example**
As an example, I would like to be able to assign a variable like `$foo: string(1px + 1em);`. currently, if I wanted to declare such a variable, I would have to write `$foo: unquote("1px + 1em');` which is perfectly functional, but is difficult to understand and does not show the intent of the developer. Also, if Calc is being used a lot within the application these `unquote` functions end up everywhere. 

Note: sass does some awesome string/integer/unit calculation and i do NOT want to mess with that but it would be nice to explicitly set "hey sass, please don't work your math magic over here"
;)

use case (in development so plz don't throw shade) https://github.com/thoughtbot/cask/pull/2

**Comment by chriseppstein** [comment]
Note that if you set `$foo: calc(1px + 1em)` this would work fine. `calc(...)` is a kind of quotation for Sass.

I assume that you're not setting it this way for some reason? But that's not really clear in this description, I'd like to understand your use case better.

We have a plan to make variables work better with calc in #818. With that you'd simply set your variable to values involving the calc function and Sass would magically take care of the rest. Please read through that issue and let us know if you think it will help clean up your use case(s) and if not, please explain why.

**Comment by whmii** [comment]
The project I am working on uses some relatively complex calc's that have some consistent parts. Because of this it is useful to have 'standard segments' of the calc operation defined ahead of time and wait to add the `calc()` wrapper until the last possible second so that the internal values are easier to add to / manipulate. 

In my example I am trying to define a consistent value that is the width of a single column → `100% / $column-count - $gutter * $foobar` and then later use that to determine things like how large a left margin should be to push a column X number of columns over + that column's own gutter. As stated I can likely make do with `unquote("")` but they end up everywhere and make it difficult for an outsider to understand what is being done.

Hope this clears things up :S

This is for a potential [Neat](neat.bourbon.io) 3.0 release that I'm workshopping in another repo so I can make sure it's viable.
a _very_ WIP pr example that I will be filling out today. https://github.com/thoughtbot/cask/pull/3/files

**Comment by nex3** [comment]
I tihnk using `calc()` plus interpolation is sufficient here.
