### ISSUE TITLE
Commenting @each loops breaks compiler

### ISSUE THREAD

**Issue by entozoon** [sass/sass#1929]
Say you have something like:

```
/*
$colors: (
    "blue": #050708
);
@each $key, $value in $colors {
    .background--#{$key} {
        background: $value;
    }
}
*/
```

Commented out as such, it breaks with Error: Undefined variable: "$key".
Which is presumably because it tries to echo a $key variable into the comment itself, which is mad.

**Comment by entozoon** [comment]
Using a // style comment on each line works fine however. But that's not ideal

**Comment by chriseppstein** [comment]
Sass allows interpolation in css comments. It's not "mad", it's a useful feature for generating comments into the css output. E.g. debugging output, copyright notices, inline documentation that includes user settings.

If you want to comment out Sass code from actually being part of the output, only the `//` style comment will do that.
