### ISSUE TITLE
In sass, dash is same as underline?

### ISSUE THREAD

**Issue by aboutjquery** [sass/sass#1930]
Hello,

@mixin test($map: $_map_test) {
 // content
}

Did `$_map_test` is same as `$-map-test`?

If yes, i should not use underline?

Thank you so much.

**Comment by chriseppstein** [comment]
Yes, in variables, mixins and function names, underscores and dashes are semantically equivalent. This allows projects that have a dash convention to consume libraries that have an underscore convention (and vice-versa)

**Comment by chriseppstein** [comment]
This is mentioned at the end of the "variables" section in the Sass reference: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variables_
