### ISSUE TITLE
Map doesn't like direct access to map entries with certain keys

### ISSUE THREAD

**Issue by barneycarroll** [sass/sass#1936]
Sass seems not to like accessing certain keys directly. I have the following map:

``` scss
$palette : (
  peach  : (
    base  : #f59658,
    light : #fecb90
  ),

  amber  : (
    base  : #ffc050,
    light : #feedba
  ),

  slate  : (
    base  : #42748c,
    light : #91bac8
  ),

  teal   : (
    base  : #4ab8a1,
    light : #b3e0d7
  ),

  wine   : (
    base  : #9e5995,
    light : #d6b9d2
  ),

  grey  : (
    1: #f8f8f8,
    2: #e6e6e6,
    3: #c0c0c0,
    4: #989898,
    5: #717171
  ),

  red    : #b8292f,
  orange : #ff8c00,
  green  : #a8cc3f,
  blue   : #2c6077,
  marine : #0ac3df
);
```

Iterating through the values shows everything to be in order:

``` scss
@each $value in $palette {
  @debug $value;
};
```

Similarly, iterating through the keys and interpolating them indicates the same thing:

``` scss
@each $key in map-keys( $palette ) {
  @debug map-get( $palette, $key );
};
```

However, imperative access to the values via arbitrary keys fed to returns null values for the keys 'teal', 'grey', 'red', 'orange', 'green' & 'blue':

``` scss
@each $key in 'peach' 'amber' 'slate' 'teal' 'wine' 'grey' 'red' 'orange' 'green' 'blue' 'marine' {
  @debug map-get( $palette, $key )';
}
```

This appears to be unrelated to definition order, spacing, or other structural aspects of the map and entirely to do with the strings used as keys. Changing the string 'blue' to 'bleu', for instance, leads to a fully functional map.

What's the best way for me to provide a test case for this bug?

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1256

**Comment by barneycarroll** [comment]
Thanks @cimmanon! It was only on reading the post I realised some of those keys were highlighted differently… :0
