### ISSUE TITLE
Source maps aren't generated when the --update flag is used.

### ISSUE THREAD

**Issue by rdebeasi** [sass/sass#1948]
When I use `sass --watch`, a source map is generated. When I run the same command with `--update` instead of `--watch`, however, no source map is generated.

Here's what I'm trying to do:

```
mls-mba-debeasi:stat debeasi$ svn stat
!       css/style.css.map
mls-mba-debeasi:stat debeasi$ sass --update ./scss/:./css/
mls-mba-debeasi:stat debeasi$ svn stat
!       css/style.css.map
mls-mba-debeasi:stat debeasi$ sass --update ./scss/:./css/ --sourcemap=auto
mls-mba-debeasi:stat debeasi$ svn stat
!       css/style.css.map
mls-mba-debeasi:stat debeasi$ sass --watch ./scss/:./css/
>>> Sass is watching for changes. Press Ctrl-C to stop.
>>> Change detected to: scss/style.scss
      write ./css/style.css
      write ./css/style.css.map
^Cmls-mba-debeasi:stat debeasi$ svn stat
M       css/style.css.map
```

Am I doing something wrong here, or is sass misbehaving? Thank you in advance for your help!! 😃

**Comment by chriseppstein** [comment]
When I use `--update` it makes a sourcemap by default. What version of Sass are you using?

**Comment by rdebeasi** [comment]
I'm on Sass 3.4.20. I'm no longer able to reproduce the issue. I'm not sure what the root cause was, but whatever it was appears to have been on my end. Sorry for the hassle!
