### ISSUE TITLE
@at-root not working smoothly with dynamic selectors?

### ISSUE THREAD

**Issue by kmcaloon** [sass/sass#1949]
I'm sure I am missing something here. The current situation I am having problems with is a bit more involved than this, but to simplify it here is an example of what's going on...

Here is part of my "element" mixin code that is working as it's supposed to

```
$elSeparator: '__'; 
@mixin element($element) {
  &#{$elSeparator+$element} {
    @content;
  }
}
```

It's working fine. For example, here is a portion of the code in question:

```
.snippet {
  @include element(date-flag) {
    // Some code
  }
}
```

Which is being processed into:

```
.snippet__date-flag {
  // Some code
}
```

So far so good. However, when I try to escape out of the nesting from the "date-flag" element and target a dynamic selector as a parent, this start to get messy.

So for example, here I am trying to target ".snippet--showdate .snippet__date-flag".  Keep in mind that all of this code will actually be within a mixin, but I am manually including it here for troubleshooting:

```
.snippet {

  @include element(date-flag) {

    $parent: snippet--showdate;
    $current: &;
    @at-root .#{$parent} #{$current} {
      $selector: &;
      @debug $selector;
    }
  }
}
```

Returns this in the terminal:

```
DEBUG: .snippet__date-flag .snippet--showdate .snippet__date-flag
```

Any idea what might be going on here? Again, there is more going on in the actual code that makes this sort of functionality necessary, however after troubleshooting this is seems to be the current problem.

**Comment by chriseppstein** [comment]
@kmcaloon what version of Sass are you using? In Sass `3.4.20` I get `.snippet--showdate .snippet__date-flag`.

**Comment by chriseppstein** [comment]
In node-sass I also get  `.snippet--showdate .snippet__date-flag`.

**Comment by kmcaloon** [comment]
@chriseppstein  thanks for the quick response. You were on the right track. Although my sass gem was up to date, the gulp-sass node provided with the sage/roots WP theme I was using needed to be updated. Sorry for the false alarm.

**Comment by chriseppstein** [comment]
@kmcaloon No worries, glad we got it sorted out.
