### ISSUE TITLE
wrong variable interpolation in @each loop

### ISSUE THREAD

**Issue by simne7** [sass/sass#195]
I came across this problem when trying to create comments in an @each-loop. 

scss:
$list: 1,2,3,4,5;

@each $cnt in $list {

```
/*! comment °#{$cnt}*/
.name {
    width: #{$cnt}px;
}
```

}

css:
/\* comment °1*/
.name {
  width: 1px; }

/\* comment °1*/
.name {
  width: 2px; }

/\* comment °1*/
.name {
  width: 3px; }

/\* comment °1*/
.name {
  width: 4px; }

/\* comment °1*/
.name {
  width: 5px; }

SASS version : 3.1.8 (Brainy Betty)
RAILS version: 1.2.6

**Comment by nex3** [comment]
I'm pretty sure this is fixed as of 3.1.10.
