### ISSUE TITLE
Rubocop TODOs

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1953]
After landing Pull Request #1805 to stable, there are 32 new rubocop checks remaining that we need to consider either enabling with associated clean up or disabling permanently on the project.

This issue is to track that work so we don't forget about it.

**Comment by chriseppstein** [comment]
The basic strategy here is:
1. move a check in `.rubocop_todo.yml` to `.rubocop.yml` and enable it.
2. run `rake rubocop`
3. If there are warnings or failures that seem reasonable to address, fix them. If there are exceptions use a rubocop comment to disable the new check for that offense.
4. If there are a lot of failures (10+) then maybe we just disagree with that check or need to tune the arguments to it.
5. Commit the changes for each new check separately so we can revert that check if we disagree with it.
6. Make sure to merge to master and verify that the changes pass there as well (there is work on master that hasn't been checked yet)

**Comment by chriseppstein** [comment]
10 down, 21 to go. pushed directly to stable and master.

**Comment by nex3** [comment]
Thanks for doing this, Chris!
