### ISSUE TITLE
Substraction inconsistent with negative fractions missing leading zero

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1954]
``` scss
div {
  sub-1: 1em-.75; // 1em- 0.75
  sub-5: 1em-0.75; // 0.25em
  sub-2: 1em -.75; // 1em -.75
  sub-6: 1em -0.75; // 1em -0.75
  sub-3: 1em- .75; // 1em- .75
  sub-7: 1em- 0.75; // 1em- 0.75
  sub-4: 1em - .75; // 0.25em
  sub-8: 1em - 0.75; // 0.25em
}
```

The differences between `sub-1` and `sub-5` seem wrong. IMO `sub-1` should be evaluated too.

**Comment by chriseppstein** [comment]
> IMO `sub-1` should be evaluated too.

See #1912.

> The differences between sub-1 and sub-5 seem wrong.

Agree. I don't know why `sub-5` isn't the same output as `sub-1`. Perhaps @nex3 does.

**Comment by nex3** [comment]
That's just an oversight. We have a special-case check for the next character being a digit, but we should also have one for a dot followed by a digit.

**Comment by mgreter** [comment]
:+1: thanks
