### ISSUE TITLE
Add @import_directory and @import_tree 

### ISSUE THREAD

**Issue by aziz** [sass/sass#196]
if I had @import_directory and @import_tree I could get rid of ugly sprocket comments at the top of my stylesheets and be 100% sass. 
Why should I explicitly name all the files with @import? is there any way around it at the moment?

**Comment by chriseppstein** [comment]
Sass provides a framework for customizing the behavior of the @import directive. This framework is used by [sass-rails](https://github.com/rails/sass-rails) and [sprockets-sass](https://github.com/petebrowne/sprockets-sass) to make the sprockets directives unnecessary in Sass files.
