### ISSUE TITLE
compile_file does not allow to pass a specific encoding

### ISSUE THREAD

**Issue by mgreter** [sass/sass#1965]
To be clear, I'm talking about input encoding, output is always utf-8.

Maybe I'm missing something, but I couldn't figure out how to define a specific encoding for input files if they lack any bom or charset declaration. Therefore ruby sass will probably apply the default encoding, which would be `CP850` in my case. But I know that the file in question is utf-8, so I would expect:

``` ruby
Sass.compile_file(filename, :encoding => "UTF-8")
```

Btw. I find it quite puzzeling that it also seems impossible in ruby to open a file in utf-8 encoding with the newline conversion disabled. We have some spec tests results that contain single `\r` chars, which get converted to `\n` by ruby io if newline conversion is on. But I'm using 1.9.3, so that may already be solved (saw a `writebin` function in the docs). I can work around those issues, but I figured I still post this here.

**Comment by mgreter** [comment]
OK, found out how to do it, since cli had an option for exactly this:

``` ruby
Encoding.default_external = "UTF-8"
Sass.compile_file(filename)
```

Not sure if it would be worth adding a `default_encoding` option for the file compiler though.

**Comment by chriseppstein** [comment]
That's an oversight. The encoding should be specifiable as an option. Ruby's file API allows a per-file-read specification of the encoding. Setting `default_external` globally is a workaround that works ok for things like the Sass executable, but should not be forced onto other processes.

**Comment by MareoRaft** [comment]
How can I find the most easy "Help Wanted" issues?  I'm new but would like to contribute.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
