### ISSUE TITLE
Sass watch on large project very slow to detect file changes.

### ISSUE THREAD

**Issue by abose** [sass/sass#1966]
Hi,
 I am part of the brackets open source project(brackets.io), and we were experimenting ruby SASS compilation support for brackets. 
We have a project with 9000+ files being watched and around 20 SASS files in it. However, if we make a change only to one sass file among the 20, sass watcher takes around 20 seconds to detect that the file has changed and then trigger a recompile. However if i narrow the watch to just the folder with the 20 sass files, the change detection is instant. 
Why is the compilation slowed down in the first case even though there are only 20 SASS files? Is there any way / flags that i should set to speed it up? [Our use case(live preview) reqires a fast change detection and recompile of the changed sass file.] 

Platform: windows 8.1 64bit processor:corei7; ram:24GB; SSD

Thanks in advance,
Arun,
Brackets.io

**Comment by chriseppstein** [comment]
Hi Arun, do you have the `wdm` ruby gem installed?

**Comment by chriseppstein** [comment]
It would be great if you could do some profiling on your project and let us know where you're seeing the bottlenecks.

**Comment by chriseppstein** [comment]
I found the bug and fixed it.

**Comment by abose** [comment]
Thanks!
