### ISSUE TITLE
supports() clause doesn't support declaration-syntax

### ISSUE THREAD

**Issue by zolotov** [sass/sass#1967]
`supports()` clause support, that was introduced in 3.4.20 is not fully compatible with W3C CSS spec.

According to [CSS Cascading and Inheritance Level 4](https://www.w3.org/TR/2015/WD-css-cascade-4-20150908/#typedef-supports-condition) it's allowed to place `supports_conditions` **OR** `declaration` inside `supports()` clause.

```
@import [ <url> | <string> ]
        [ supports( [ <supports-condition> | <declaration> ] ) ]?
        <media-query-list>? ;
```

So the following imports are both valid and  equivalent:

``` css
@import "mystyle.css" supports(display: flex);
@import "mystyle.css" supports((display: flex));
```

However Sass compiler doesn't work for the following code:

``` scss
@import "mystyle.css" supports(display: flex);
```

And produces the following error:

```
Error: Invalid CSS after "....css" supports(": expected ")", was "display: flex);"
        on line 1 of test.scss
```

**Comment by chriseppstein** [comment]
Thanks, we'll get that fixed in the next patch release.
