### ISSUE TITLE
is_map function

### ISSUE THREAD

**Issue by harvey-woo** [sass/sass#1968]
Really need a function to return if param is a map or others. The `type_of` function return `list` if i pass it a map as param.

**Comment by KittyGiraudel** [comment]
The `type-of` function returns `map` for maps.

**Comment by chriseppstein** [comment]
@Alphmega What @HugoGiraudel says is true: 

```
$ sass -i
>> type-of((a: 1))
"map"
```

If you're getting a different result, I'm very confused as to how. I guess you can tell us what version and implementation you are using -- maybe you just need to upgrade -- I dunno.

**Comment by harvey-woo** [comment]
@chriseppstein @HugoGiraudel After upgrading sass, it returns correct return. Thanks for answering
