### ISSUE TITLE
Support multiple properties assignment in one directive

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#197]
Idea is to support this type of syntax:

.class {
    border-top, border-bottom: 1px solid black;
    background-color, color: white;
}

compiled to:
.class {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
    background-color: white;
    color: white;
}

As discussed in an email with Nathan Weizenbaum:
"This is something we've considered, but never found to be compelling enough to implement. [...] That said, we don't have a strong reason to oppose the feature, so if you can demonstrate a strong community desire for it, that may well bring it to the point where we're willing to add it in.

**Comment by chriseppstein** [comment]
I think it is a good feature. I need it occasionally and I don't see any downsides. However, as I've stated before, I think comma delimited left hand values are the right syntax.

**Comment by jleclanche** [comment]
> However, as I've stated before, I think comma delimited left hand values are the right syntax.

I'm not sure I understand what you mean. What would it look like?
Edit: bloody comment&close.

**Comment by chriseppstein** [comment]
sorry, I was confused. I thought this was an addendum to #109. I'm closing this as a dupe. Feel free to xfer any additional information that you think is needed to #109.

**Comment by jleclanche** [comment]
I didn't see that issue; I was pretty sure I searched them all. Sorry about that :)
