### ISSUE TITLE
undefined method `to_tree' for nil:NilClass

### ISSUE THREAD

**Issue by nooperpudd** [sass/sass#1978]
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
Sass 3.4.21 (Selective Steve)
Compass 1.0.3 (Polaris)

[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Backtrace:
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:184:in`tree'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:149:in`dependencies'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:166:in`block in dependency_updated?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `each'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in`any?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:166:in`block in dependency_updated?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:81:in `call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:81:in`stylesheet_modified_since?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:211:in`block in update_stylesheets'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in `each'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in`update_stylesheets'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:471:in `on_file_changed'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:328:in`block in watch'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:252:in `call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:252:in`on_change'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:254:in`call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:323:in`poll_changed_directories'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'

**Comment by chriseppstein** [comment]
I set up a fresh project using compass 1.0.3 and sass 3.4.21 using ruby 2.0.0p481 and ran the watcher, made several edits and everything worked fine. I will need better steps to reproduce this issue.

```
➜  sass_issue_1978  bundle
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing chunky_png 1.3.5
Installing multi_json 1.11.2
Installing sass 3.4.21
Installing rb-fsevent 0.9.7
Installing ffi 1.9.10 with native extensions
Using bundler 1.11.2
Installing compass-core 1.0.3
Installing compass-import-once 1.0.5
Installing rb-inotify 0.9.5
Installing compass 1.0.3
Bundle complete! 1 Gemfile dependency, 10 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from compass:
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
➜  sass_issue_1978  bundle exec
➜  sass_issue_1978
➜  sass_issue_1978  mvim .
➜  sass_issue_1978  bundle exec compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write stylesheets/screen.css
 modified sass/screen.scss
    write stylesheets/screen.css
 modified sass/screen.scss
    write stylesheets/screen.css
 modified sass/screen.scss
    write stylesheets/screen.css
^C
★★★ Happy Styling! ★★★
➜  sass_issue_1978  ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin14.5.0]
```
