### ISSUE TITLE
Top most parent selector

### ISSUE THREAD

**Issue by ngryman** [sass/sass#1980]
Hi guys,

I know this has been already discussed (i.e. #1804, #218).
But I think `sass` is still missing some sugar in its syntax :)

When we speak about nesting, we inevitably speak about states / modifiers of parents. This is components era!

Currently, it is very frustrating to style a child whose parent is mutating and the only choices are:

``` sass
.component {
  .element {
    color: #bada55;

    // possibility 1
    @at-root .component.active .element {
      color: #55adab;
    }
  }

  // possibility 2
  &.active .element {
    color: #55adab;
  }
}
```

Either it is unnecessary verbose or we lose context.

If you use composited class name conventions like `bem`:

``` sass
.component {
  &__element {
    color: #bada55;

    .component--active & {
      color: #55adab;
    }
  }
}
```

Thanks to the _trailing ampersand_, it is better. But we still have to explicitly write our component class name. Trailing ampersands are awesome because we keep context of the currently styled element. But currently, it is too limited. Prepended selectors must be out of the root element scope.

There is no _clean_ way to change the state of a root element and styling its children while keeping context.

We should be able to do something like this:

``` sass
.component {
  .element {
    color: #bada55;

    &&.active & {
      color: #55adab;
    }
  }
}

// or

.component {
  &__element {
    color: #bada55;

    &&--active & {
      color: #55adab;
    }
  }
}
```

`&&` would reference the top most selector.

When used in combination with `&`, `sass` should strip the top most selector from every `&` occurrence. So in our example, `&&.active &` would naively output `&& -> (.component.active) & -> (.component .element)`. It should be simplified to `&& -> (.component.active) & -> (.element)`.

I know this has already been proposed in some way, but I really think I won't be the only one that would be super uber happy if some sugar was available out of the box ;)

**Comment by jeremydelacasa** [comment]
+1

**Comment by Jean-Xu** [comment]
+1

**Comment by chriseppstein** [comment]
The ability for `&` to be used in SassScript means that the language doesn't need to define sugar for every possible type of selector manipulation (many such types of manipulation has been suggested over the years). Here's some Sass code you can use _right now_ that does this for you:

https://gist.github.com/chriseppstein/476836b0488e293b258e

**Comment by ngryman** [comment]
Thanks for the gist. I expected this, but it's worth trying.

Still, I keep thinking that usage/best practices are constantly evolving. `sass` is now old and my use case is the use case of more and more people. `sass`, and other tools should follow usage, not principles.

Defining components and styling children is something **very** usual, it's a common pattern. That's why `&` was introduced. It is a powerful feature that everybody now use. This pattern is now strongly enforced by new generation frameworks like `react`, `angular2`, `polymer` and off course web components.

We are defining black boxes more and more, with only the root element being accessible by other elements and the only way to change a component visual state. This pattern already exists and is going to become a "standard".

So, being able to reference this root element from its children is not like selecting grand parents or anything else, it becomes vital. `sass` is focused on `DRY`, and without this selector, it's a pain.
`CSS` itself introduced the [:root](https://developer.mozilla.org/fr/docs/Web/CSS/:root) selector for this specific reason, so why `sass` wouldn't do it?
