### ISSUE TITLE
SCSS parser fails with CRLFs under JRuby 1.9

### ISSUE THREAD

**Issue by lencioni** [sass/sass#1985]
In fixing [a bug related to CRLFs in SCSS-Lint](https://github.com/brigade/scss-lint/pull/701), I found that our test suite fails under JRuby 1.9 with errors like the following:

```
Failure/Error: @tree = @engine.to_tree

     Sass::SyntaxError:
       Invalid CSS after "p {   margin: 0;}": expected selector or at-rule, was "}"
     # (sass):1
     # ./vendor/bundle/jruby/1.9/gems/sass-3.4.21/lib/sass/scss/parser.rb:1180:in `expected'
     # ./vendor/bundle/jruby/1.9/gems/sass-3.4.21/lib/sass/scss/parser.rb:1115:in `expected'
     # ./vendor/bundle/jruby/1.9/gems/sass-3.4.21/lib/sass/scss/parser.rb:40:in `parse'
     # ./vendor/bundle/jruby/1.9/gems/sass-3.4.21/lib/sass/engine.rb:403:in `_to_tree'
     # ./vendor/bundle/jruby/1.9/gems/sass-3.4.21/lib/sass/engine.rb:309:in `to_tree'
     # ./lib/scss_lint/engine.rb:33:in `initialize'
     # ./spec/spec_helper.rb:40:in `(root)'
```

The input being parsed here is

```
p {^M   margin: 0;^M}
```

where the `^M`s are CRLFs typed in Vim by pressing `<Ctrl>+v<Ctrl>+m`.

**Comment by chriseppstein** [comment]
I [added a test case to make sure CRLF parses correctly](https://github.com/sass/sass/commit/ffa19a651be1cf9973cd18527744f554621c4dbd). I couldn't reproduce this issue. [Even on JRuby](https://travis-ci.org/sass/sass/jobs/107838138). Maybe there's some very specific set of configuration, platform, and environment. If so, someone needs to break this down into something I reproduce and fix.

**Comment by lencioni** [comment]
@chriseppstein Thanks so much for looking into this! I'll report back here if I am able to find out any more info.
