### ISSUE TITLE
How to handle Ampersand in mixins

### ISSUE THREAD

**Issue by thepian** [sass/sass#1987]
If you use & in a mixin the mixin is limited to being nested in a selector. 

In older LibSass `&` would be replaced by blank if used globally, which supports some very useful solutions.

In the Sass tool I get an error;

```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 2 of ./input.scss, in `breaker'
        from line 15 of ./input.scss
  Use --trace for backtrace.
```

Why could this not be a warning rather than an error. Or alternately, how would an if construct be made to test for the mixin being inside/outside a rule.

The sort of mixin I refer to can be seen here:

https://gist.github.com/thepian/70ed200bfd611bdaa82b

**Comment by chriseppstein** [comment]
The way to write this mixin to handle root-level inclusion is like this:

``` scss
@mixin breaker($compact-selector) {
  @if & {
    #{$compact-selector} & {
      @content
    }
  } @else {
    #{$compact-selector} {
      @content
    }
  }
}
```
