### ISSUE TITLE
any way to test if @content has content?

### ISSUE THREAD

**Issue by smiLLe** [sass/sass#1988]
Hey guys,

is there any way to test @content for any content? like length(@content) ?

**Comment by chriseppstein** [comment]
No, but it would be easy enough to add a function that can check this.

**Comment by chriseppstein** [comment]
Maybe `content-exists()`. @nex3 thoughts?

**Comment by nex3** [comment]
Sounds reasonable to me.

**Comment by glebm** [comment]
How about `content-given()`?

**Comment by KittyGiraudel** [comment]
`content-exists(..)` would be better in order to stay consistent with `feature-exists(..)` and the like.

**Comment by chriseppstein** [comment]
I think this function should return the arity of the content block or nil if none given. Right now this would always be zero, but after #871 it could be a positive value. All of which is "truthy" so `@if content-given()` can be used without testing for zero.

**Comment by nex3** [comment]
@chriseppstein I'm not a fan of overloading functions like that—it makes it difficult for people unfamiliar with the function to read code that uses it. It should do exactly what the name says. I'd prefer to have a separate `content-arity()` function for that.

**Comment by chriseppstein** [comment]
@nex3 Agreed. I actually had come to the same realization before I read your comment 👍

**Comment by nex3** [comment]
This has been implemented.
