### ISSUE TITLE
Why i can't call function inside map-item?

### ISSUE THREAD

**Issue by medzhidov** [sass/sass#1991]
I use in my scss:

```
$body: (
    sm: calc(100% - #{70px / $font_size} )
);
```

But if i use `map-get($body, sm)`, i get:

`
calc(100% - #{70px / $font_size} )
`

What i do wrong?

**Comment by chriseppstein** [comment]
I can't reproduce this with either ruby sass or libsass. Probably you just need to upgrade or something.
