### ISSUE TITLE
Why scope success?

### ISSUE THREAD

**Issue by bra-kodairakenya** [sass/sass#1995]
Sorry!!!
I have poor English.

Look so described the problem under.

```
%btnBase {
  display: none;
}

// Scope error
@media only screen and (min-width:300px) {
  a {
    @extend %btnBase;
  }
}

@mixin mobile {
  @media only screen and (min-width:300px) {
    @content;
  }
}

// Why Success??
@include mobile {
  a {
    @extend %btnBase;
  }
}

```

**Comment by cimmanon** [comment]
I cannot reproduce this.  If you are using LibSass, you will need to file a bug report with that repo.

**Comment by bra-kodairakenya** [comment]
Thanks. I use LibSass. Write a report from now.

https://github.com/sass/libsass/issues/1923

**Comment by kenyakodaira** [comment]
https://github.com/sass/libsass/issues/1923
