### ISSUE TITLE
separate sass engine and cli into separate gems.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1996]
The code for for the CLI is unnecessary when using just the core engine and this has made installing dependencies etc more complex than needed.

I think it's better to extract the sass engine to it's own gem (sass-core) than to move the CLI out (sass-cli). This way `gem install sass` still just works as it always has for people who are following install guides etc.

**Comment by chriseppstein** [comment]
@nex3 :+1: on this idea?

**Comment by chriseppstein** [comment]
## Proposal

### Gems:
- sass-core will be the Sass Engine and supporting ruby code.
- sass will be cli and depend on sass-core.

### Git:
- sass-core will be fork of sass git repo.
- sass will have the core code removed and remain the main git repo.

### Existing Issues:
- Leave them in sass/sass

### New issues:
- either repo is fine. we won't police users about it.

### Versioning:
- a release to `sass-core` will force a release of `sass` and vice versa keeping version numbers in sync.

**Comment by nex3** [comment]
:+1:

**Comment by nex3** [comment]
Another possibility would be to rename this repo to `sass-core`, so that it preserves all its existing issues, then create a new repo called `sass-cli` that's a fork of this one. We'd still release the code in the `sass-cli` repo as a gem named `sass`.

**Comment by KittyGiraudel** [comment]
> either repo is fine. we won't police users about it.

I believe it would be nice to centralise issues so that searching through existing issues returns more relevant results?

**Comment by chriseppstein** [comment]
@HugoGiraudel That's a good point. maybe we'll just turn issues off on the new repo.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
