### ISSUE TITLE
Upgrade to latest listen

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1997]
Make listen a proper dependency now that it no longer depends on celluloid.

This requires deprecating our support of old versions of ruby (at least < 1.9.3).

We might want to do this once #1996 happens if we agree that's the right direction.

**Comment by nex3** [comment]
Chris and I discussed this and agreed to drop support for Ruby 1.8.7 and 1.9.3 as of Sass 3.5. The details will be in a blog post to be posted Monday.
