### ISSUE TITLE
pseudo elements

### ISSUE THREAD

**Issue by paravozz** [sass/sass#2001]
When SCSS generates CSS, there whitespace between selector and him pseudo classes. 

Example:

<pre><code> **SCSS:**
a {
    some css;
    :hover {
        morecss;
    }
}
</pre></code>

It compiles to

<pre><code> **CSS:**
a {
    some css;
}
a :hover { /\* whitespace after 'a' and some browsers can't correct read it */
    morecss;
}
</pre></code>

**Comment by davidkpiano** [comment]
Try this: 

``` scss
a {
    // some css;
    &:hover {
        // morecss;
    }
}
```

Add the ampersand: `&` to "attach" the parent selector.

**Comment by paravozz** [comment]
Thank You!

Closed.
