### ISSUE TITLE
Sass source maps with Google Chrome

### ISSUE THREAD

**Issue by DeoThemes** [sass/sass#2004]
Hello.

I'm trying to make source maps working with Google Chrome so instead of compiled style.css it will show me .scss style. I'd tried to add sass folder in dev tools workspaces and than go to sources tab and right click on style.css then map it to style.scss. But after this I still see style.css line in a dev tools.

What am I doing wrong?

Hope you can help with that.
Best Regards.

**Comment by ubergeekzone** [comment]
@DeoThemes See if this will help you out any at all https://robots.thoughtbot.com/sass-source-maps-chrome-magic

**Comment by chriseppstein** [comment]
It'd be good to have a HOWTO on our website for this.

**Comment by ubergeekzone** [comment]
@chriseppstein i am working on a HOWTO for this tonight for you guys, found out about this where it asked if someone wanted to do it on twitter.

**Comment by DeoThemes** [comment]
@chriseppstein  Hi, thanks for advice, but I've already checked this article and tried to follow all steps. But on a step **Map to network resource** when I right click on style.scss there are no options to choose file. Here is screenshot  - http://clip2net.com/s/3uZ2fab

Maybe the problem can be cuz I'm running file on a local machine and a format is file:/// instead of localhost?

It might be very helpful for a new users to read detailed HOWTO with all explanations. I spent about 2-3 days serfing forums and still can't find working solution.

Thanks for your help.
Best Regards.

**Comment by ubergeekzone** [comment]
What OS are you on? I think the issue is because you are trying to access
it via file://

On Monday, February 29, 2016, DeoThemes notifications@github.com wrote:

> @bergeekzone Hi, thanks for advice, but I've already checked this article
> and tried to follow all steps. But on a step _Map to network resource_
> when I right click on style.scss there are no options to choose file. Here
> is screenshot - http://clip2net.com/s/3uZ2fab
> 
> Maybe the problem can be cuz I'm running file on a local machine and a
> format is file:/// instead of localhost?
> 
> It might be very helpful for a new users to read detailed HOWTO with all
> explanations. I spent about 2-3 days serfing forums and still can't find
> working solution.
> 
> Thanks for your help.
> Best Regards.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/issues/2004#issuecomment-190483385.

## 

Amy Bridges
Owner
P: (404) 487-6003 ext 700
E: amy.bridges@invoate.com
LinkedIn https://www.linkedin.com/in/amy-bridges-ab33b336 | Invoate
http://www.invoate.com | Behance https://www.behance.net/ubergeekzone

**Comment by DeoThemes** [comment]
> What OS are you on? I think the issue is because you are trying to access
> it via file://

I'm on Windows 10. If it's important to use local server, what soft would you recommend?

Thanks.

**Comment by ubergeekzone** [comment]
Download XAMPP https://www.apachefriends.org/index.html

On Monday, February 29, 2016, DeoThemes notifications@github.com wrote:

> What OS are you on? I think the issue is because you are trying to access
> it via file://
> 
> I'm on Windows 10. If it's important to use local server, what soft would
> you recommend?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sass/sass/issues/2004#issuecomment-190535792.

## 

Amy Bridges
Owner
P: (404) 487-6003 ext 700
E: amy.bridges@invoate.com
LinkedIn https://www.linkedin.com/in/amy-bridges-ab33b336 | Invoate
http://www.invoate.com | Behance https://www.behance.net/ubergeekzone

**Comment by DeoThemes** [comment]
Hi.

Finally it's working, now I can see sass files in Google Chrome. But now I'm having another problem. If I make some changes to sass file, it doesn't change file in browser. Here is screenshot - http://clip2net.com/s/3v5wvXU

Thanks. 

UPD: found the problem, it's because my compiler still was working with an old files located not on the localhost.

Thanks a lot for your help. Someone definitelly should write an article with step by step instructions.

**Comment by ubergeekzone** [comment]
Hello,

 My account was hijacked earlier today, if you have something form me about
a proposal agreement do not open it. I have took the appropriate measures
to ensure this will not happen again.

Thanks

## 

Amy Bridges
Owner
P: (404) 487-6003 ext 700
E: amy.bridges@invoate.com
LinkedIn
https://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/afeb9aa266b28974e84e4d1ad30e3c37/www.linkedin.com/in/amy-bridges-ab33b336
| Invoate
http://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/7afd6d954dbb7c577d195f10610bebf1/www.invoate.com
| Behance
https://t.yesware.com/tt/24554823f0769e3928dc2ff821448567077d1807/cc7947eb285eaae542a5318d220bf049/f1e0e013a0c812229189b26c95d207f1/www.behance.net/ubergeekzone
