### ISSUE TITLE
sass --watch directory also watches other directories causing high CPU usage

### ISSUE THREAD

**Issue by tigrr** [sass/sass#2006]
Suppose we have a directory structure like the following: sass, css, other files and folders.
`sass --watch sass:css`
watches not only "sass" directory, as you would expect, but the entire current working directory. Sass doesn't process them though. This causes high CPU usage, especially if you have many files in your active directory.

Perusing into other issues I've found out that this behavior is intended as a workaround to a few other Linux issues.

I am opening this issue:
1. Once again, to invite developers' attention to it. (Please don't tell me it is all right this way, it is not.)
2. To let users know about it, since this may consume their computer resources without their knowledge, and to propose a possible workaround, which is:

**Workaround**
Change to "sass" directory and from within run this instead of the command above:
`sass --watch .:../css`
Now files in the parent directory won't be watched.

**Comment by chriseppstein** [comment]
This was how it was always supposed to work, but there was a hard-to-find bug that watching the current directory papered over for most users. I found the hard-to-find bug and removed the hack we had added to watch the current working directory.

**Comment by tigrr** [comment]
@chriseppstein , sorry, I am not sure what you're talking about. The reason I complained was very high CPU usage and messages from sass in the terminal about changes made (new files detected) in sass files in other directories. 
Also, I'm using version 3.4.21
