### ISSUE TITLE
Improve backtrace terminal usability

### ISSUE THREAD

**Issue by kaelig** [sass/sass#2008]
In iTerm2 (and maybe in other terminals), any pattern like such:

```
filename.ext:linenumber
```

e.g.

```
index.scss:50
```

…becomes clickable (CMD+click) and links to said file, pointing at said line.

Currently, Sass's backtraces look like this:

```
WARNING: Assuming 640 to be in pixels, attempting to convert it into pixels.
         on line 90 of /Users/me/workspace/sass-mq/_mq.scss, in `mq'
         from line 17 of test/_after-import.scss, in `styles'
         from line 96 of test/_after-import.scss
         from line 6 of test/test.scss
```
1. Is this something that could be modified so that developers can easily navigate to the right line in a file?
2. Would it make sense, or am I the only one to care about these terminal usability tweaks?

**Comment by chriseppstein** [comment]
for historical reasons, Sass matches ruby's stack trace format. I suggest iTerm add support for other kinds of stack trace formats (maybe there's a regex config or something?)
