### ISSUE TITLE
Output indentation levels

### ISSUE THREAD

**Issue by Jujucristine** [sass/sass#2010]
In non-compressed output modes, the indenting seems to get all messed up if you're using nesting in the sass file. You might get something like this in your result:

```
.modal.caption-edit {
        max-width: 450px; }

.modal.caption-edit textarea {
            max-width: 360px; }
```

When it should all be outputted like so:

```
.modal.caption-edit {
    max-width: 450px; }

.modal.caption-edit textarea {
    max-width: 360px; }
```

There's also another indenting/spacing problem with these output modes in which any nested sass returns without a new line between each selector. This is a problem with the "trailer" \n in the to_css.rb file. I have it fixed on my local files but it should probably be fixed in the official build.

**Comment by Jujucristine** [comment]
The source of the problems seems to be in the following lines on /visitors/to_css.rb:

Line 248:

```
    tab_str = '  ' * (@tabs + node.tabs)
```

Trailer on line 332 seems to not be getting to line 347:

`trailer = "\n" if node.group_end`
`output("}" + trailer)`

**Comment by chriseppstein** [comment]
What is the source sass file that causes this output issue? We'd like to reproduce this first.

**Comment by paul-codes-1** [comment]
I was able to reproduce this issue. Taking a crack at it.

**Comment by paul-codes-1** [comment]
![selection_012](https://cloud.githubusercontent.com/assets/14105031/15696288/8a6fa33e-275b-11e6-882c-56670c3a2ea7.png)
![selection_011](https://cloud.githubusercontent.com/assets/14105031/15696286/8808c756-275b-11e6-95bf-717c6d34ca4f.png)

Here are images of the input scss file and its output to css with improper indentation.

**Comment by paul-codes-1** [comment]
@Jujucristine do you remember how you fixed this locally?

**Comment by Jujucristine** [comment]
I edited the lines I mentioned above. The only problem is that the fix I made makes all indents fixed to one level, so if you nest something like @media queries they will not double indent. Because of this it's more of a palliative, as it works for the majority of the code you'd be writing, but not all.

For the indenting I edited the above line as such:

to_css line 248:
`tab_str = '    ' * (@tabs + node.tabs)`

changed to:
`tab_str = '    '`

I imagine a proper fix would involve making the  (@tabs + node.tabs) work on css levels, and not scss levels.

**Comment by paul-codes-1** [comment]
Ok, so what condition could I test for to see if double indents should be possible? I'm thinking I could set it up like:

```
(some_condition) ? allow_multi_indent? = true : allow_multi_indent? = false
allow_multi_indent? ? tab_amt = (@tabs + node.tabs) : tab_amt = 1
tab_str = '  ' * tab_amt
```

**Comment by maciej-ka** [comment]
@paulmoliva you may wish to run with "expanded" theme, `sass -t expanded`. Your output looks like correct "nested" output theme which is the default.

test.scss

```
.modal {
  .caption-edit {
    max-width: 450px;

    textarea {
      max-width: 360px;
    }
  }
}
```

then `./sass -t expanded /tmp/test.scs`

and result is

```
.modal .caption-edit {
  max-width: 450px;
}
.modal .caption-edit textarea {
  max-width: 360px;
}
```

@Jujucristine could you post example with wrong behavior?

**Comment by chriseppstein** [comment]
I'm not sure why this is being called "improper indentation" `nested` is the default output style and this is working as inteded.  You may prefer `expanded` or `compact` instead.

**Comment by Jujucristine** [comment]
Examples are already above, and no, I'm not looking for expanded nor compact.

**Comment by chriseppstein** [comment]
@Jujucristine I typed out the screenshot from above:

``` scss
.modal {
  .caption-edit {
    max-width: 450px;
    textarea {
      max-width: 360px;
    }
  }
}
```

And it compiles to this:

``` css
.modal .caption-edit {
  max-width: 450px; }
  .modal .caption-edit textarea {
    max-width: 360px; }
```

Which is what is expected and is not what you initially reported. I don't have an actual source file to use to attempt to reproduce this issue, so it's closed. Please provide a reproducible test case.
