### ISSUE TITLE
Sass Multiline Comment: Docs Need Clarification?

### ISSUE THREAD

**Issue by bdkjones** [sass/sass#2013]
I have a user who sent me this Sass file, using `*.sass` syntax:

```
/*
  ~1)Imports
  ----------------------------------------------------------------------------------------------------
@import '1-imports'
/*
  ~2)HTML5 Reset
  ----------------------------------------------------------------------------------------------------
@import '2-reset'
/*
  ~3)Defaults
  ----------------------------------------------------------------------------------------------------
@import '3a-defaults-typography'
@import '3b-defaults-objects-forms-tables'
```

I was very surprised that this file did anything because the multiline comment-start-delimiter `/*` is not paired with a comment-end-delimiter `*/` The example in the Sass docs shows the comment properly closed:

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments

Is it the case that in the indented syntax, any line that is indented _more_ than the comment-start-delimiter is considered part of the multiline comment? Can I get the exact rules for multiline comments in the `*.sass` syntax? I have an algorithm that scans for @import statements in these files and ignores those excluded by comments, so I need to know how Sass parses them for the indented syntax. Thanks!

**Comment by chriseppstein** [comment]
> Is it the case that in the indented syntax, any line that is indented more than the comment-start-delimiter is considered part of the multiline comment?

Yes.

> Can I get the exact rules for multiline comments in the *.sass syntax?

The indented syntax for comments is documented here:

http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#comments

Basically, the outdent terminates all comments (`/*` and `//`) in the indented syntax. The closing comment delimiter (`*/`)is actually removed from any multi-line css comment to avoid it being output twice.

**Comment by bdkjones** [comment]
Thanks; that's exactly what I needed but could not find.
