### ISSUE TITLE
@each converts numbers to string

### ISSUE THREAD

**Issue by mkimont** [sass/sass#2014]
Example 

```
 $reasonColors: (1:$beta-color, 2:$gamma-color,3:$zeta-color);
 $reasonSkew: (1:2deg, 2:-12deg, 3:4deg);
 @each $profile, $bgcolor in $reasonColors {
            $number: #{$profile};
            $skew: map-get($reasonSkew, $number);
```

$skew with throw nothing as map-get is type sensitive ( $number is passed as string)

Right now I change all profile to be strings ( $reasonColors: ('1':$beta-color, '2':$gamma-color ... )  ) and it's work. I know that in future somebody somewhere will need here a numbers for calculations.

I will be grateful for any help. Did I miss something here ?

**Comment by davidkpiano** [comment]
The `#{$profile}` interpolation always converts to a string. Try `$number: $profile`

**Comment by chriseppstein** [comment]
@davidkpiano has got it right. no need for interpolation there.
