### ISSUE TITLE
how to use/define variable names with variable name 

### ISSUE THREAD

**Issue by anujaykumar1** [sass/sass#2017]
like in less i can use @@var to [get value of a value](http://lesscss.org/features/#variables-feature-variable-names), how may i use this in sass ?

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/132

**Comment by chriseppstein** [comment]
As noted in the issue linked by @cimmanon, the correct solution here is to use Sass maps which we added a couple versions ago to handle this use case.
