### ISSUE TITLE
Allow for several @extend classes in one line

### ISSUE THREAD

**Issue by mikker** [sass/sass#202]
**Feature request:**

The ability to `@extend` several classes by chaining them ala `@extend .two.columns;`.

Thanks!

**Comment by chriseppstein** [comment]
That syntax will extend all the places where `.two.columns` appear together. If you mean for it to be functionally equivalent to `@extend .two; @extend .columns;` then I think the syntax would be `@extend .two, .columns;`.

Seems pretty easy to add. @nex3 do you have any objection?

**Comment by mikker** [comment]
Yes, that's probably what I meant. Another option could be without the comma `@extend .two .columns;`. Space-separated like in HTML - `class="two columns"`. Any one would be great :)

**Comment by nex3** [comment]
`@extend .two .columns` would mean extending the descendant selector, not extending multiple simple selectors. `@extend .two, .columns` would work, but I'm not sure it's worth the terseness. I think it's clearer to have a couple of `@extend`s when it's just two or three selectors being extended, and as far as I know it's very rare to extend more than that.

**Comment by mikker** [comment]
Of course!

Still - I think I know now what my original concern was: Some css only applies to elements that have BOTH classes.

<pre>
.one { ... }
.two { ... }
.one.two { ... }
</pre>


`@extend .one; @extend .two;` would give you the first two - but will it also apply the third?

**Comment by chriseppstein** [comment]
yes it will. give it a try :)

**Comment by mikker** [comment]
Great! Thanks a lot.

**Comment by sayedbs** [comment]
#Might be you try it.

for extend multiple class overwrite or extend

    .element {
       @xtend .class-1; 
       @extend .class-2;
    }

it's better than prev 

    .element {
        @extend #{'.class-1', '.class-2', '.class-3',....'.class-n'};
    }
**it's simple but work fine** 

###===Thank you===
