### ISSUE TITLE
Error: @charset may only be used at the root of a document.

### ISSUE THREAD

**Issue by yajo** [sass/sass#2023]
Take this document `one.sass`:

```
@charset "UTF-8"
/*  © Yajo
.other
    @import "other"
```

Then this another `_other.sass`:

```
@charset "UTF-8"
/*  © Yajo
.someclass
    display: none
```

Then:

```
sass \
        --cache-location /var/cache/sass\
        --compass\
        --require bootstrap-sass\
        --update /app:/app\
```

Says:

```
      error /app/...../static/src/css/_other.sass (Line 1: @charset may only be used at the root of a document.)
```

... but I need UTF8 for ©! And [docs say that `@charset` only goes into CSS when there's any non-ASCII character](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#encodings), so it should even be automatic.

**Comment by chriseppstein** [comment]
@nex3 thoughts?

**Comment by nex3** [comment]
There are plenty of non-`@charset` ways to load files as UTF-8. Most OSes these days are configured to use UTF-8 by default, and Sass will pick up on that. You can also pass the `-E` parameter to control the default encoding. If you really need to put something in the file itself, you can use a BOM. But `@charset` is explicitly a CSS directive, and we can't emit it as a CSS directive if it's in the middle of the output file, so don't use that.

**Comment by yajo** [comment]
But docs say it's automatic. Shouldn't it be ignored unless it is at the top?

**Comment by nex3** [comment]
We do automatically choose to add or remove a `@charset` declaration at the beginning of the output file depending on whether it's necessary to preserve the semantics of that file. But if you're writing a `@charset` in the middle of your stylesheet—which is effectively what it means for it to be in a partial that you import—there's no way we can compile that while preserving the CSS semantics, because the CSS semantics are that it's an error.

**Comment by yajo** [comment]
I know, I understand the bug. But it seems it's not a bug in the implementation but in the design.

If you really need to declare the partial as UTF8 as is my case, then you cannot compile at all unless removing all `@charset` declarations and passing the `-E` flag. But that's not good. What happens if I want to use 2 libraries and both have the `@charset` at the top? What if both are different? I'd have to recode and modify at least one of them.

So IMHO if the compiler is smart enough to provide the `@charset` for the CSS output automatically when needed, it should be smart enough to _not_ output them _when it's the first declaration of a partial_, and to convert that partial to the main `.sass` file's encoding when they differ.

So after all, any `@charset` declaration should raise an exception only when not in the first line of any file, partial or not. Otherwise it should be used internally by the compiler, but not for the output.

**Comment by cimmanon** [comment]
Why can't it just bubble up to the top the same way CSS `@import` statements are handled?  There are people that are surprised when the location of the import changes because they don't realize that what they've written is isn't valid.  Why can't `@charset` be handled the same way?

``` scss
.foo {
  color: red; 
}
@import url("http://example.com/styles.css");
```

Output:

``` css
@import url("http://example.com/styles.css");
.foo {
  color: red;
}
```

**Comment by chriseppstein** [comment]
@nex3 this seems like a bug to me. The `@charset` is needed in partials to declare the charset but then it cannot be imported except at the top level. This seems like an oversight in the implementation.

**Comment by chriseppstein** [comment]
I discussed this with @nex3 and we decided that it should be considered a bug.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
