### ISSUE TITLE
Feature Request: "@import as" 

### ISSUE THREAD

**Issue by adampoczatek** [sass/sass#2024]
I was thinking about difficulties with implementing third-party extensions in your CSS, mainly due to class name collisions and then I thought it would be nice to have something like `@import as` syntax, similar to [import](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import) and [export](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/export) in JavaScript.  

Here's a simple example of how this could work.  

**_button.scss**

```
@export .buttonComponent {
    padding: 10px;

    &--primary {
        background: blue;
    }
}
```

**app.scss**

```
@import "button" as .btn;

.btn {
    border: 1px solid #ccc;

    &--primary {
        border-color: darkblue;
    }
}
```

Compiled CSS in **app.css**

```
.btn {
    border: 1px solid #ccc;
    padding: 10px;
}

.btn--primary {
    border-color: darkblue;
    background: blue;
}
```

This is a very simple example to illustrate my point. Now, imagine if you could push it even further by exporting mixins.

**components/_buttonComponent.scss**

```
@export @mixin buttonComponent ($selector: '.buttonComponent', $padding: 10px) {
    #{$selector} {
        border: 1px solid #ccc;
        padding: $padding;

        &--primary {
            border-color: darkblue;
        }
    }
}
```

**app.scss**

```
@import "components/buttonComponent" as btnComponent;

@include btnComponent('.btn', 20px);

.btn {
    background: blue;
}

.btn--primary {
    color: white;
}
```

Compiled CSS in **app.css**

```
.btn {
    background: blue;
    border: 1px solid #ccc;
    padding: 20px;
}

.btn--primary {
    color: white;
    border-color: darkblue;
}
```

You could go with JavaScript syntax and do multiple import/export:

**_buttonComponent.scss**

```
@export .buttonComponent {}
@export .buttonComponentPrimary {}
```

**app.scss**

```
@import {.buttonComponent as .btn, .buttonComponentPrimary as .btn--primary} from "buttonComponent";
```

---

Long term vision - we have all popular components hosted on Bower, we can import them with ease and adjust settings so that they work nicely with our codebase.

What do you guys think?

**Comment by chriseppstein** [comment]
We are currently re-designing `@import` for Sass 4.0. See #353 and https://github.com/sass/proposal.module-system

That said, there is not currently any selector re-writing capability in this new module system. I opened an issue against that spec for discussion.
