### ISSUE TITLE
License clarifications

### ISSUE THREAD

**Issue by georgestavos** [sass/sass#2026]
Hi,
I'm part of a team developing and maintaining websites for several big players in the adult entertainment industry. We would like to adopt SASS into our projects as it looks very promising.
However I just wanted to make sure it is fine, license wise, to use SASS in commercial projects. We will NOT be releasing any of our code. We will certainly report issues as we encounter them though.

Long story short:
Is SASS usable in commercial projects without forced source code disclosure?

**Comment by mprins** [comment]
> Is SASS usable in commercial projects without forced source code disclosure?

Yes, see: https://github.com/sass/sass/blob/stable/MIT-LICENSE

**Comment by chriseppstein** [comment]
Sass releases its code under an unmodified MIT license.
