### ISSUE TITLE
Import CSS inline

### ISSUE THREAD

**Issue by evanhuang8** [sass/sass#2027]
This is a duplicate of #556, but since that issue is locked I just feel like bringing it up here again.

Is there a reason an inline option is still not available? It's ridiculous to have to set up a whole compass toolchain just to be able to import an CSS file inline in a SCSS file

**Comment by whaaaley** [comment]
They're revamping the import system entirely. There's a thread about stuff here #1094

**Comment by chriseppstein** [comment]
It's locked because we've heard enough feedback at this point. The feature is being included in Sass 4.0.

Despite the name, you don't have to use compass to use compass-import-once. See the readme here: https://github.com/Compass/compass/tree/stable/import-once
