### ISSUE TITLE
Documentation for scale-color incorrectly lists $hue as argument

### ISSUE THREAD

**Issue by imathis** [sass/sass#203]
On http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html in the "Other Color Functions" section, scale color incorrectly lists $hue as an acceptable argument.

scale-color($color, [$red], [$green], [$blue], [$hue], [$saturation], [$lightness], [$alpha]

**Comment by nex3** [comment]
Closed by d532b300585851b5e8fd89fe6cfdc21541251205
