### ISSUE TITLE
question about the scope of using @extend with selectors

### ISSUE THREAD

**Issue by erichummel** [sass/sass#2035]
I'm in the process of trying to upgrade Sass from 3.2.19 to 3.4.22 (my main goal is updating sprockets, but since the 3.2.19 version of sass is locking sprockets to an older version, I need to update sass).

Basically, I'm getting numerous errors running our test suite like 

```
".some-selector .some-other-selector" failed to @extend ".ico-star".
The selector ".ico-star" was not found.
```

For many of these, it makes sense, as the selector in question was removed by our front end guy some time ago and the older version of sass never complained about the fact that it was missing. 

The ones I'm having issues with, however, are situations where the selector exists and is `@import`ed before the css file that uses it, e.g.:

```
@import "common/icons" [contains the .ico-star style definition], "desktop/modals" [tries to @extend .ico-star];
```

The extend still fails with the error mentioned above. 

What am I doing wrong here? 

Do I need to explicitly `@import` the stylesheet that contains the styles I want in the stylesheet that is doing the `@extending`? 

Or should I convert these shared classes to `@mixins` and use them that way?

My apologies if github issues is not the place for this type of question, but I poured over all the relevant documentation (and googled the shit out of it) and couldn't really find anything that explains how `@extend` scopes the selectors that it uses.

**Comment by cimmanon** [comment]
Sounds like your imports are not partials.

**Comment by erichummel** [comment]
@cimmanon the only difference between a partial and a regular css file is the leading underscore, right?

`@import "common/icons"` is referring to the file common/_icons.scss, likewise, `@import "desktop/modals"` is referring to desktop/_modals.scss

[EDIT] and both of them are imported in a manifest file that `@imports` loads of partials

**Comment by chriseppstein** [comment]
@erichummel I cannot reproduce this issue according to your description unless I try to compile `desktop/modals` directly (since you say it doesn't import `common/icons` itself (which I think was what @cimmanon was trying to say. if you run `sass --update` or `sass --watch` and desktop/modals is not a partial then sass will try to compile it.

**Comment by erichummel** [comment]
thanks for looking into it, @chriseppstein - I'm trying to create a super simple test case on a fresh rails app to reproduce the issue. 

I'll either reproduce it, in which case I'll push the test case to github and share it here, or I won't be able to reproduce it and I'll have to dissect what the difference between my app and the test app is, in which case I will post my findings here and close this issue.

**Comment by erichummel** [comment]
welp, try as I might, I couldn't reproduce the issue in a new rails app, and in the process of noting the difference between my app and the test case I tracked down a few more erroneous `@extends` and voila, the problem has disappeared. 

I guess I must have been so bleary eyed while stuck in the weeds with this yesterday that I misread the error or something.

At any rate, if anyone else runs into a problem like this while upgrading sass to 3.4.x, check all your `@extends` and make sure that their dependencies are actually being `@imported` before they're extended. Also, make sure you're not calling `@extend` from within media query blocks to extend with selectors defined outside of those blocks.

thanks @chriseppstein and @cimmanon
