### ISSUE TITLE
old bug appears again,like https://github.com/sass/sass/issues/1260#issuecomment-213566682

### ISSUE THREAD

**Issue by aaronwng** [sass/sass#2039]
modified sass/pages/css/global/global.sass
[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Backtrace:
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:184:in`tree'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:149:in`dependencies'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:166:in`block in dependency_updated?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:125:in `each'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:125:in`any?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:166:in`block in dependency_updated?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:81:in `call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:81:in`stylesheet_modified_since?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:211:in`block in update_stylesheets'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:209:in `each'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:209:in`update_stylesheets'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:470:in `on_file_changed'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:328:in`block in watch'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/listener.rb:252:in `call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/listener.rb:252:in`on_change'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/adapter.rb:254:in`call'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/adapter.rb:323:in`poll_changed_directories'
        /Library/Ruby/Gems/2.0.0/gems/sass-3.4.18/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'

[#1260](https://github.com/sass/sass/issues/1260#issuecomment-213566682) also appear this bug

**Comment by chriseppstein** [comment]
Please upgrade to `3.4.22` and let us know if you're still seeing it.

**Comment by chriseppstein** [comment]
Also, if you're still seeing it please show us how you're running sass and provide steps to reproduce.
