### ISSUE TITLE
Name spacing for mixins

### ISSUE THREAD

**Issue by bvsatyaram** [sass/sass#2054]
In JavaScript, I would namespace functions as follows:

```
var MyAwesomeApp = {
  func_one: function() {
    ...
  },
  func_two: function() {
    ...
  }
}
```

I would like to do the same with Sass mixins too, to make sure that the mixins I define won't have any conflict with mixins defined by other third party sass files. I tried searching for the same, but couldn't find a good solution. Is there a way in which I can namespace mixins in Sass? If yes, please help me with a pointer. Else, is it in the pipeline?

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/sass/issues/353

**Comment by chriseppstein** [comment]
This is planned for 4.0
