### ISSUE TITLE
Semicolon appearing after a comment and breaking rules

### ISSUE THREAD

**Issue by NicosKaralis** [sass/sass#2055]
I've reported this issue [in this closed issue comment](https://github.com/sass/sass/issues/1646#issuecomment-218261257) but after some digging I found that my problem is something else.

Just to explain my issue again:

I have in my rails application many vendor assets, `js` and `css`, that are downloaded and compiled on each deploy.

After the last deploy some css rules stopped working. After a lot of experimenting I found this rule:

```
@media (min-width: 64em) {
  .drawer--sidebar .drawer-hamburger {
    display: none;
    visibility: hidden;
  }

  /*! Left */
  .drawer--sidebar.drawer--left .drawer-nav {
    left: 0;
    border-right: 1px solid #ddd;
  }
}
```

The comment is incorrectly flagged as copyright. But the real problem here is that this will render into the following:

Compressed:

```
@media (min-width: 64em) {.drawer--sidebar .drawer-hamburger {display:none;visibility: hidden}/*! Left */;.drawer--sidebar.drawer--left .drawer-nav {left: 0;border-right: 1px solid #ddd}}
```

Expanded

```
@media (min-width: 64em) {
  .drawer--sidebar .drawer-hamburger {
    display:none;
    visibility: hidden
  }

  /*! Left */
  ;.drawer--sidebar.drawer--left .drawer-nav {
    left: 0;
    border-right: 1px solid #ddd
  }
}
```

The rule `.drawer--sidebar .drawer-hamburger` after the compression works, but the rule `.drawer--sidebar.drawer--left .drawer-nav` is not being detected.

If I use chrome web inspector and replace `*/;` with `*/` on the css file everything is back to normal.

What can I do to solve this?

**Comment by NicosKaralis** [comment]
After more digging I found a possible cause for this problem.

Inside `@media` declaration each comment, `\* *\` or `\*! *\`, will have a semicolon after it. They shouldn't.

This is the only place where I found this happens

**Comment by chriseppstein** [comment]
I'm pretty sure this isn't a sass bug. I can't reproduce it using the Sass CLI and it's unlikely that such a bug could go unnoticed in Sass for so long since I can't imagine any recent change to our stable branch that could have affected this.

If you can provide a failing test case, outside of your rails asset pipeline, we will be happy to dig into it further.
