### ISSUE TITLE
Variables referencing

### ISSUE THREAD

**Issue by ArmorDarks** [sass/sass#2066]
To be honest, I'm not sure how exactly that issue should be named, since I can't tell for sure is it more related to referencing itself, or mutability.

Instead of long explanations, let's go straight to examples:

``` sass
$global-map: ();

@function test-get($key, $map: $global-map) {

  @return map-get($map, $key)

}
```

This seem fine. Now, imagine that somewhere you need to _write_ to that global map. You could imagine something like this:

``` sass
@mixin test-set($key, $value, $map: $global-map) {

  // ... do something with value...

  $newMap: ($key: $value);

  $map: map-merge($map, $newMap) !global;

}
```

But it won't work for obvious reasons. Sass variables don't write/mutate by reference. You will need to hardcode global variable instead:

``` sass
@mixin test-set($key, $value) {

  // ... do something with value...

  $newMap: ($key: $value);

  $global-map: map-merge($global-map, $newMap) !global;

}
```

This doesn't seem like a serious problem, unless you realize that you can't make this code portable. If Sass variable could uphold references to other variables and write by them, it would allow to reuse code with any global variable you'd want to:

``` sass
$other-global-map: ();
$and-another-global: ();

@include test-set(test, value, $other-global-map);
@include test-set(test, value, $and-another-global);
```

But for now you have to write same mixin but with different hardcoded global variables each time you'd want to apply procedural changes of that mixin to another global variable.

Please, correct me if I'm missing anything.

Thanks.

**Comment by chriseppstein** [comment]
All Sass values are immutable. Code will need to be structured around return values instead of being based on side-effects. That is, the code that is calling `test-set` should look like `$global-map: test-set($test, $value, $global-map) !global`

**Comment by ArmorDarks** [comment]
Hi @chriseppstein 

Thanks for your reply!

Ah, I see, as I've supposed they're indeed immutable. That's fine, of course.

Though, I'm trying really hard to apply you code and understand how does it solve described issue, without any luck. Am I missing something?

**Comment by ArmorDarks** [comment]
@chriseppstein any chances for this to be reviewed?

Judging from your newer issues you're now less opposed to side-effects in functions.

Personally, I'm not fan of side effects too, but in some scenarios Sass just forces you to use them, because there are no easy way to pass certain values (for example, between mixins https://github.com/sass/sass/issues/871).

I do not think that your solution is good example, because it breaks the point of those functions. They supposed to encapsulate logic of assigning and retrieving to those global variables in the way, that user even may not need to know about those temporary global functions. But instead you're suggesting to expose this global variable for assignment. This way app just can't expose to user normal methods for set\get.

I propose at least to re-open this issue.

Thanks.

**Comment by ArmorDarks** [comment]
@chriseppstein? @nex3? Anyone?

If reply on this issue can't be provided right away, please, at least __re-open this issue__. I think it is very impolite to close issue right away without any meaningful solution.

**Comment by chriseppstein** [comment]
@ArmorDarks The solution is to write your code differently so that the calling code performs the mutation in place instead of relying on side-effects.


```scss
@function test-set($map, $key, $value) {
  // ... do something with value...
  @if ...some condition... {
    $newMap: ($key: $value);
    @return map-merge($map, $newMap);
  } @else {
    @return $map;
  }
}
```

Then use this function mutate an existing map in the scope where it is defined:

```scss
$my-map: test-set($my-map, key, value);
```

**Comment by chriseppstein** [comment]
@ArmorDarks FWIW, I never suggested that you create global variables per se. just that if you have a global variable you are mutating in a local scope to make sure to use the `!global` modifier when you update the variable reference. I think a best practice is to avoid globals as much as possible.
