### ISSUE TITLE
Stop remove empty selectors

### ISSUE THREAD

**Issue by camsong** [sass/sass#2069]
Sass will remove empty selectors by default, Is there an options to disable this?

Such as

``` sass
.empty {
}
```

will compile to nothing, but I want it compile to `.empty{}`, otherwise I got error when using css-modules.

ref: https://github.com/sass/node-sass/issues/1569
https://github.com/css-modules/css-modules/issues/140

**Comment by andypinet** [comment]
i have a idea
like this

```
.empty {
    @empty
}
```

**Comment by mgreter** [comment]
[Can be done with important comments](http://libsass.ocbnet.ch/srcmap/#LmVtcHR5IHsKICAgIC8qISBrZWVwICovCn0=)

```
.empty {
    /*! keep */
}
```

**Comment by chriseppstein** [comment]
What @mgreter said. Although, a random weird comment isn't very self documenting so maybe wrap it up in a mixin:

``` scss
@mixin empty-module($module-name) {
  .#{$module-name} { /*!*/ }
}
@include empty-module("empty");
```

**Comment by camsong** [comment]
It works, thanks @mgreter. Could you tell more about why sass remove empty selectors?

**Comment by chriseppstein** [comment]
> Could you tell more about why sass remove empty selectors?

@camsong 
1. A selector with no properties has no meaning to a browser.
2. It is the selector analog of pruning out properties that are set to `null`.
3. It cleans up the use case of including a mixin into a selector that conditionally produces no output based on configuration settings, global state, etc. In those cases, a selector is undesired as is an additional conditional at the call site.

**Comment by toolbox1972** [comment]
From a pre-processing perspective there are scenarios you would want to create selectors with blank declarations, e.g. bulk creation. I planned below structure, but realize I cannot create the blank selectors.
I do not really understand why (at _partial building) you are not allowed to create blank selectors. The process of (_partial) is not the end-result, which unqualifies the motivation of that a browser would not make use of blank selectors. (the browser does not communicate with the (_partial).

    @import '_1-partial_variables.sass'
    @import '_2-partial_divs_only.sass'
    @import '_3-partial_wrapper.sass'
    @import '_4-partial_divs_layout.sass'

**Comment by chriseppstein** [comment]
@toolbox1972 a partial is just a fragment of a sass file and plenty of users split up their css into partials, so no, it doesn't invalidate the reasons I gave above for why blank selectors are removed. We've also provided a simple means by which an empty selector can be kept (adding a `/*!*/` comment).

**Comment by toolbox1972** [comment]
@chriseppstein Fair enough, thanks for your quick answer.
