### ISSUE TITLE
Undefined variable error but variable is indeed defined

### ISSUE THREAD

**Issue by guoyunhe** [sass/sass#2070]
``` sass
//_variable.scss
$blue-base: #66ccff;
$blue-dark: darken($blue-base, 10%);
$blue: $blue-base;
$blue-light: lighten($blue-base, 10%);
$blue-lighter: lighten($blue-base, 20%);
$blue-lightest: lighten($blue-base, 25%);

$link-color: $blue-dark;
$link-some-active-color: $blue;
```

``` sass
// _global.scss
a {
    color: $link-color;
    text-decoration: none;

    &:hover, &:active, &:focus {
        color: $link-some-active-color;
    }
}
```

Error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: src/sass/_global.scss
Error: Undefined variable: "$link-some-active-color".
        on line 20 of src/sass/_global.scss
>>         color: $link-some-active-color;
   ---------------^
```

I am using Gulp.

**Comment by guoyunhe** [comment]
Found the reason, I import in a wrong way.

**Comment by manix** [comment]
@guoyunhe can you elaborate?

**Comment by majidzeno** [comment]
@manix I faced the same issue with Sass, in my case the error was because I included the variables file after the other file where I used them, you could try doing this, reorder files import, make the variables file at the top.

**Comment by superknife0512** [comment]
@majidzeno wow, thank you so much. I also stuck at that error

**Comment by ahsin59** [comment]
how to import file

**Comment by nex3** [comment]
@ahsin59 Check out [the Sass tutorial](http://sass-lang.com/guide) for information on how to use `@import`.

**Comment by ghost** [comment]
@manix  thanks a lot .it worked

**Comment by Mohit349** [comment]
> @manix I faced the same issue with Sass, in my case the error was because I included the variables file after the other file where I used them, you could try doing this, reorder files import, make the variables file at the top.

**Comment by Mohit349** [comment]
thanks @manix  it works for me

**Comment by catamphetamine** [comment]
I my case, it was weird: there was no `@import` of the mixins file but somehow it highlighted a random variable inside a mixin inside that file as being undefined (while in reality being defined in the same file). `@import`ing the mixins file fixed the issue.

**Comment by SankThomas** [comment]
I made the mistake of declaring variables inside :root. As in;
:root {
  $primary-color: #fff;
}
So when I referenced this variable, it gave me that error. FIxing it is as easy as removing :root and the curly braces...

**Comment by Thomas-lbt** [comment]
OMG i searched for at least 45min and it ends up that it is just an order of imports :(((( i didn't even know imports had orders i'm so mad

**Comment by LisaWillG** [comment]
@majidzeno that worked great thank you

**Comment by syedzeeshanahmed** [comment]
> @manix I faced the same issue with Sass, in my case the error was because I included the variables file after the other file where I used them, you could try doing this, reorder files import, make the variables file at the top.

Awesome!

**Comment by bennycode** [comment]
You can also name all your files with an underscore upfront (e.g. `_color.scss`, `_font.scss`, `_button.scss`, etc.) and import them in one single `style.scss`:

```scss
@import 'color';
@import 'font';
@import 'button';
```

This technique is called [partials](https://sass-lang.com/guide#topic-4) and will merge all your styles in one single CSS output so ordering gets sorted out by SCSS. Note that the filenames start with an underscore but the imports don't.

**Comment by GonzaloDieguez** [comment]
> @manix I faced the same issue with Sass, in my case the error was because I included the variables file after the other file where I used them, you could try doing this, reorder files import, make the variables file at the top.

Thanks! Lifesaving!

**Comment by Akshaykashyap** [comment]
@manix thanks a lot .it worked

**Comment by Ng1n3** [comment]
Reordering the import fix this for me thanks @manix. Learnt a new thing in scss

**Comment by LudovicDM** [comment]
> @manix really thank you so much
