### ISSUE TITLE
Unexpected output when using negative value and division operator in margin shorthand

### ISSUE THREAD

**Issue by Wolfr** [sass/sass#2072]
Reduced test case: http://www.sassmeister.com/gist/5720b6f7aac53433123f71395a6708f8

Is this intended? I would expect "margin: 0 -15px" as output.

**Comment by douglasdeodato** [comment]
try this:

.modal-body {
  .row {
    margin: 0 -#{$grid-gutter-width/2};
  }
}

http://www.sassmeister.com/gist/4474904b97d170f48a5ffd1d0642282f

Check  the documentation about: **Interpolation: #{}, Operators and Numbers** . You will understand better :) http://sass-lang.com/documentation/file.SASS_REFERENCE.html

I hope it helped you,

**Comment by Wolfr** [comment]
Yes. Thank you!
