### ISSUE TITLE
@extend across files failure

### ISSUE THREAD

**Issue by alexcracea** [sass/sass#2073]
Hello,

So as I believe there was some updates recently that I found out only by reinstalling my whole OS. Now with a fresh reinstall of nodejs & gulp - sass won't get me to render extends across files:

Here's the file structure
├── styles.scss - imports _style-main
├── _styles-main.scss - imports _extends and _icons
├── _extends.scss
├── _icons.scss

in _icons.scss I declare an extend:

```
%icons {
  font-family: 'my_font';
  speak: none;
  font-style: normal;
  font-weight: normal;
}

```

in _extends I call the %icons extend upon another extend:

```
%more {
  &:after {
    @extend %icons;
  }
}
```

Error message:
Error! _extends.scss
Error: "%more:after" failed to @extend "%icons".
       The selector "%icons" was not found.
       Use "@extend %icons !optional" if the extend should be able to fail.
        on line 39 of _extends.scss
     @extend %icons;

The weirdest thing here is that if I import _icons.scss directly at the top of _extends.scss file - it works and it was acting absolutely normal last week when I had an older version of npm. Please help me at least understand what changed and how to fix it - this problem occurs on a already finished project

**Comment by chriseppstein** [comment]
It looks like you're trying to compile a partial by itself.

**Comment by alexcracea** [comment]
@chriseppstein not really, I include an extend from _icons.scss inside _extends.scss that are both imported in _styles-main in a correct order, plus, there are more .scss files in the project.

There is something wrong with the package version after the sass update on this project.

I tried downgrading gulp and npm and it didnt help, couldn't downgrade node-sass though.

Curious is that if i make a dummy project somewhere else on my PC with just these 3 files - it works.

**Comment by alexcracea** [comment]
Found the issue source, it was all because the import partials was wrong.

The only thing mattered was the fact that by the time of developing we used an older version of sass and were getting no errors.
