### ISSUE TITLE
Allow @extending selectors defined with empty body

### ISSUE THREAD

**Issue by hon2a** [sass/sass#2074]
At the moment `@extend`ing a selector that is defined just with empty body

``` scss
%pattern {}
.instance {
  @extend %abstract;
}
.context {
  %abstract {
    // ... context-based modifications
  }
}
```

throws the following error

```
Error: ".instance" failed to @extend "%pattern".
       The selector "%pattern" was not found.
       ...
```

suggesting that the `%pattern` definition, being empty, is discarded right away. The code above should be self-explanatory as to why this might be undesirable. Seeing as making the body not empty, e.g. adding a compiled `/* css comment */` makes it work just fine, wouldn't it make more sense to keep the definition for possible extensions even though it doesn't produce CSS at the moment it is parsed?

This doesn't apply only to abstract (placeholder) selectors. It works the same with other types of selectors as well.

**Comment by andypinet** [comment]
this can work

```
%abstract {
/*!*/
}
.instance {
  @extend %abstract;
}
```

**Comment by hon2a** [comment]
@andypinet Yeah, I said that near the end of the description. Still, it'd be nicer if it worked without the work-around.

**Comment by chriseppstein** [comment]
What is the use case here? Extending a selector that will be pruned from output is just as confusing as extending a selector that didn't exist and silently ignoring. You can add `!optional` to your extend directive to make it succeed if the base selector isn't output.

**Comment by hon2a** [comment]
@chriseppstein Thanks for that, you prompted me to try the full use-case I put in the description on [SassMeister](http://www.sassmeister.com/) and it actually works as long as there is a non-empty use of `%abstract` later in the code. That means your `!optional` suggestion is also applicable to flag `.instance` as `%abstract` without being sure that `%abstract` will be used anywhere.

Originally I tried only this code on SassMeister

``` scss
%pattern {}
.instance {
  @extend %abstract;
}
```

and got the warning. I then expected that the `@extend` will not properly work with later uses of `%abstract`. Since this isn't true, I'm closing the issue. Thanks for the help.
