### ISSUE TITLE
Are operations inside interpolation allowed?

### ISSUE THREAD

**Issue by franciscop** [sass/sass#2075]
Is this allowed at all officially?

``` scss
.five  > * {
  width: calc(100% / 5 - #{$gutter * 4 / 5});
}
```

It compiles without problem and as expected:

``` css
.five  > * {
  width: calc(100% / 5 - 4px);
}
```

However I cannot find any reference. The [SASS Reference for Interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_) only talks about interpolating simple variables and nothing remotely similar to an operation inside the interpolation itself.

> Note, this does _not_ work however:

``` scss
.five  > * {
  width: calc(#{100% / 5} - #{$gutter * 4 / 5});
}
```

It prints the same output as before. So apparently it only interprets the inside of the interpolation if there's a variable.

**Comment by chriseppstein** [comment]
Interpolation allows any script expression to be inside.
