### ISSUE TITLE
Is really fast - my simply first test show that shoudl be better.

### ISSUE THREAD

**Issue by aktywnitu** [sass/sass#2083]
Hi,

compilation must be fast like visual graphic programs. Yes?
Why I use less:

```
time lessc less/bootstrap.less > test.css
real    0m1.552s
user    0m1.836s
sys     0m0.096s
```

```
time sass stylesheets/_bootstrap.scss >test.css
real    0m2.294s
user    0m2.220s
sys     0m0.064s
```

**Comment by chriseppstein** [comment]
We agree. Ruby is slow, that's why we built libsass.

```
time lessc bootstrap.less > /dev/null
1.86s user 0.10s system 123% cpu 1.594 total
```

```
$  time ~/Projects/libsass/sassc/bin/sassc _bootstrap.scss > /dev/null
0.13s user 0.03s system 93% cpu 0.165 total
```

Which, as you can see here is **14 times** faster than less on equivalent stylesheets. For details on how to install a version of libsass that is best for your particular development environment, please see http://sass-lang.com/libsass.
