### ISSUE TITLE
Add option to remove double spacing and new lines from sass-convert output

### ISSUE THREAD

**Issue by ezrafree** [sass/sass#2084]
Hello,

This is an enhancement request, specifically it's an enhancement/feature request for `sass-convert`.

Is there any chance we could get an option added to `sass-convert` to allow for the result to not be formatted to contain new lines between statements?

For example, currently it formats the code as such:

```
.foo {
    display: none;

    .bar {
        display: none;

        .baz {
            display: none;
        }
    }

    @include bp($max: 667px) {
        padding: 0 !important;
    }


    @include bp($max: 375px) {
        padding: 0 !important;
    }
}
```

Note the blank lines between statements. If there were an option to also remove these new lines, that would actually be my preference. Yes, I realize that some people find this above format to be more readable, and I also realize that that's how the code is formatted in the documentation on the Sass website. However, my preference would be a format such as:

```
.foo {
    display: none;
    .bar {
        display: none;

        .baz {
            display: none;
        }
    }
    @include bp($max: 667px) {
        padding: 0 !important;
    }
    @include bp($max: 375px) {
        padding: 0 !important;
    }
}
```

I realize this was intentional on the part of the developers, as I can see in the changelog from 3.4.16 (10 July 2015) it says:

```
When converting from Sass to SCSS or vice versa, double-space around nested rules the same as around top-level rules.
```

However, every "beautify" plugin for Sublime Text and Grunt seem to just use `sass-convert` under the hood, so this decision is greatly affecting the entire realm of our ability to automatically beautify Sass code. Any chance of making this behavior optional somehow?

**Comment by chriseppstein** [comment]
The sass-convert tool aims to create a sass output file that is well formatted, but it is not designed to be a generic code formatting tool for Sass. This option is one of a class of potential formatting options that would take sass-convert down a code path of increasing complexity and away from its core purpose (converting one syntax to another). Lots of editors do use sass-convert as a code beautifier, but that is really a hack. We would really like to see the community develop a proper code beautifier that would be written in a way to allow for personal code formatting preferences. We're available to help consult on the best way to structure such a tool and how to use the Sass abstract syntax tree for just this sort of task.
