### ISSUE TITLE
有这样一个需求.....

### ISSUE THREAD

**Issue by chinajoy** [sass/sass#2085]
先有这样一个scss
.a{
    xxxx: xxxx;

```
.b{
      xxxx: xxxx;
      xxxx: xxxx;
      xxxx: xxxx;
  }
```

}

.c{
    这里面我需要.b里面的样式;
  }

我不希望在.b前面加@at-root
有解决方法嘛？

**Comment by douglasdeodato** [comment]
well if you at least translate this to English I will be able to help you.

**Comment by chinajoy** [comment]
First there is such a SCSS
.a{
       XXXX xxxx;
     .b{
          XXXX xxxx;
         XXXX xxxx;
         XXXX xxxx;
     }
}
.c{
     I need the style inside of.B;
}

I don't want to add @at-root to the front of the.B.
Is there a way to solve it?

@douglasdeodato

**Comment by xzyfer** [comment]
The easiest way is to make the styles inside of B a mixin. Then include
that mixin in both B and C.
