### ISSUE TITLE
Feature request: @if variable-exists import else error message

### ISSUE THREAD

**Issue by douglasdeodato** [sass/sass#2086]
I wanna know if it is possible to me get a message or alert in my terminal saying the font was not loaded, is that possible? right now I can't get any error message.

**font variable:**
`$font-url: 'http://fonts.googleapis.com/css?family=Open+Sans:100,300,400,700,900';
`
**if conditional**

**// Import if Google Fonts URL is defined**

```
@if variable-exists(font-url) {
      @import url($font-url);
}
```

I know It's possible to get the message using JavaScript, but will be nice if could get this in sass on terminal.

**so maybe we could get this:**

```
@if variable-exists(font-url) {
      @import url($font-url);
      **@else "error message";**
}
```

Thanks for your Time.

**Comment by chriseppstein** [comment]
This works for me:

``` scss
$font-url: unquote("somefile.css");
@if variable-exists(font-url) {
  @import url($font-url);
} @else {
  @error "sorry no dice";
}
```

**Comment by douglasdeodato** [comment]
This only checks whether there is a variable with name $font-url. It doesn't check whether the path provided exists or not. In your case, always the if condition will trigger.
