### ISSUE TITLE
Referencing Parent Selectors by using & is not compiled correctly

### ISSUE THREAD

**Issue by menocomp** [sass/sass#2088]
As per specs here:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector
consider this example:
`
.btn-default {
  color: red;
}
.btn:hover {
    &.btn-default{
        @extend .btn-default;
    }
}
`
it is now compile to 
`
.btn-default, .btn.btn-default:hover {
  color: red;
}
`
while it should respect the classes order and should be compiled as follow:
`
.btn-default,
.btn:hover.btn-default {
  color: red;
}
`

BTW, this issues is not reproducible in LESS. I am not comparing though. I just moved from LESS to SASS recently and my styles are not working due to this issue.

**Comment by chriseppstein** [comment]
The order difference here is irrelevant to the meaning of the selector, so I'm not sure where the "should" comes from. Also note: our reference documentation is not a specification. It exists to provide a high level understanding of our features. People coming from less usually expect `@extend` and `&` to act like search and replace features, but our implementations of those features are much more nuanced than that.

**Comment by menocomp** [comment]
Thanks for pointing that the documentation is not considered as s specification.
I did not understand what you mean hear by irrelevant! 
I tried to add space between & and the other selector as follows:
`
.btn:hover {
    & .btn-default{ //space added in this line just after &
        @extend .btn-default;
    }
}
`
and this time it is compiled correctly to
`
.btn-default, .btn:hover .btn-default { // & order here is respected
  color: red;
}
`
I still can say that & is not respected when there is no space after it as in my first example.

**Comment by chriseppstein** [comment]
> I still can say that & is not respected when there is no space after it as in my first example.

@menocomp The space is semantically important because a space is the difference between an descendant combinator and adding classes (etc) to the parent selector.
