### ISSUE TITLE
Return proper complement of colors

### ISSUE THREAD

**Issue by scottkellum** [sass/sass#209]
Currently the color functions invert() and complement() both invert the color, but complement isn’t an inverted color in color theory.

The correct inverse of #ff0000 is #00ffff

The complement of #ff0000 should be #00cc00

**Comment by nex3** [comment]
I'm not sure what definition of "complement" you're using; according to [Wikipedia](http://en.wikipedia.org/wiki/Complementary_color), in perceptual color spaces like RGB and HSL, the complement of red (`#f00`) is in fact cyan (`#0ff`), since red mixed with cyan produces gray.

**Comment by scottkellum** [comment]
I am thinking of more traditional notions of color: http://en.wikipedia.org/wiki/Complementary_color#Art_and_design

Would be nice to have baked in to Sass, but I can attempt a function to make the conversion.

**Comment by nex3** [comment]
It would be neat to have a plug-in for traditional-style complementary colors, but I don't think that's something that warrants baking into Sass.
