### ISSUE TITLE
Ignoring warnings about empty selector

### ISSUE THREAD

**Issue by jerzygangi** [sass/sass#2090]
I have a few empty selectors in my code, intentionally.

When I compile with SASS, I get warnings like this one:

`WARNING on line 24:`
`This selector doesn't have any properties and will not be rendered.`

Is there a way to ignore these warnings? To avoid the output from the SASS compiler from printing to TTY?

**Comment by chriseppstein** [comment]
The `-q` command line option (or the `:quiet` engine option) will silence all warnings. There's no way to selectively silence warnings in general.

You can silence these warnings by adding a CSS comment E.g. `/* This selector intentionally has no properties */` and when compiling in compressed mode the comment and selector will be removed.

What is your use case for leaving these in?

**Comment by jerzygangi** [comment]
@chriseppstein Sorry for the delay in replying to you.

I am using SASS via Jekyll, which is why I did not know how to provide the `-q` command line option.  (I don't know how to provide any command line options to SASS in the context of Jekyll, since Jekyll kicks of SASS as part of its own build process.) Do you know how to control the SASS output with options like `-q` when Jekyll is running SASS?

In the meantime, I used a comment as per your advice which worked great.

My use case for leaving in the empty selectors was readability. I like seeing the full nested structure of my tags in the CSS, because it helps me think through and reason about the HTML structure when I'm writing CSS styling. It is probably more concise to omit it, but one of my favorite things about SASS is that I can "see" the HTML hierarchy in CSS.

Thanks again for your help on this -- much appreciated.

**Comment by chriseppstein** [comment]
@jerzygangi Sounds good. I'm going to leave this closed then. I think our current behavior is sufficient.
