### ISSUE TITLE
syntax reference 

### ISSUE THREAD

**Issue by dbzlatan** [sass/sass#2091]
Are there any resources for Sass syntax reference, and not just SCSS?
I was trying to use Sass maps but tutorial that I was looking at was in SCSS.
Rewrote it in plain Sass but it wouldn't work. There was an error code but I don't remember it now.
I tried contacting creator of a tutorial but he isn't responding. So my two questions are…
- Are there any resources for Sass syntax reference, and not just SCSS?
- Could you help me write this SCSS in plain Sass?

```
$variable: (
  key1: value1,
  key2: value2,
  key3: value3
);

.class {
  attribute: map-get($variable, key1);
}
```

I thank you for any info you may provide.

**Comment by chriseppstein** [comment]
In the indented syntax all expressions must be on a single line. A map's value is an expression.

``` sass
$variable: (key1: value1, key2: value2, key3: value3)

.class
  attribute: map-get($variable, key1)
```
