### ISSUE TITLE
libsass python

### ISSUE THREAD

**Issue by sideffect0** [sass/sass#2095]
whats about adding libsass python implementation ?

**Comment by xzyfer** [comment]
That already exists - https://github.com/dahlia/libsass-python

**Comment by sideffect0** [comment]
@xzyfer why not add these implementation on the official repo then ?

**Comment by xzyfer** [comment]
No particular reason. I did know about them until I google for `libsass python` in response to this issue, and they've never asked.

We try to document LibSass wrapper we're aware of at http://sass-lang.com/libsass but there so many it's hard to keep track.
