### ISSUE TITLE
font-family rule with CSS4 variables is ignored

### ISSUE THREAD

**Issue by oscarsolas** [sass/sass#2098]
Hi, when i use a CSS4 variable inside font-family rule, Sass ignores the rule and doesn't print it in the CSS compiled file.

Example:
h2 {
    font-family: var(--variable);
}

**Comment by douglasdeodato** [comment]
maybe this can clarify for you? https://codepen.io/jakealbaugh/post/css4-variables-and-sass

**Comment by oscarsolas** [comment]
I have tried, but the issue persists.
The issue only occurs with the font-family rule, It works well with any other rule.

**Comment by chriseppstein** [comment]
I can't reproduce this with ruby sass or libsass. Are you sure it's not caused by some other tool in your asset pipeline?
