### ISSUE TITLE
Change the default location for Sass stylesheets in the Sass::Plugin

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#21]
The current default is bad for two reasons:
1. The sass stylesheets are source code and shouldn't be directly served by the webserver.
2. The sass generates to a folder that contains the source files, making it overly difficult to force a recompile by removing the output.

Compass has changed this default to "app/stylesheets" since its inception. I think this should be the default for Sass in a Rails app and maybe just the "sass" directory at the project root otherwise.

For backwards compatibility, the public/stylesheets/sass directory should be still be supported with a deprecation warning if it is found.

**Comment by nex3** [comment]
Closing, since Sass in Rails is now supported by `sass-rails`.
