### ISSUE TITLE
how organize same media query style in unit block

### ISSUE THREAD

**Issue by hamedmoody** [sass/sass#2100]
Hi
i write this code :
![1](https://cloud.githubusercontent.com/assets/9475089/16900836/1c8693b8-4c46-11e6-8c0f-9462e73c9be2.PNG)
but seprate media queries sass code rendered in seprated media queries css code such this:
![2](https://cloud.githubusercontent.com/assets/9475089/16900849/38163e58-4c46-11e6-9caa-4d6d8092d39b.PNG)
is not better organize media queries Css in unit block for prevent repeating media queries?
Thanks

**Comment by chriseppstein** [comment]
There are other tools that you can add to your pipeline for optimizing your css files. For example: https://github.com/rstacruz/css-condense

Compressing CSS especially if you re-order selectors, can change the cascade and result in real styling differences. It's not a feature that we've decided to prioritize so far.

**Comment by hamedmoody** [comment]
Thanks its work
