### ISSUE TITLE
Object in sass ?

### ISSUE THREAD

**Issue by LoicGoyet** [sass/sass#2103]
While I'm currently developing sass with a large scale of algorithm, I found out that my code was pretty messy as a cascading list of `@functions` and `@mixins`. I was looking for a better way to structure my code, I thought objects as it is in javascript or php could be a great feature.

When I write "objects" I don't mean JSON like variable, cause obviously `maps` exists, but I mean a class with its own properties and methods that could instantiated into a variable.

Meanwhile I setup in my code bunch of conventions that would make the trick and reproduce as much as I needed objects, but I thought it could be a great feature anyway in the future, or at least a great debate :).

**Comment by xzyfer** [comment]
Sounds like Sass maps. Any reason they don't work for your usecase?

On 7/25/16, Loïc Goyet notifications@github.com wrote:

> While I'm currently developing sass with a large scale of algorithm, I found
> out that my code was pretty messy as a cascading list of `@functions` and
> `@mixins`.
> 
> I was looking for a better way to structure my code, I thought objects as it
> is in javascript or php could be
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/sass/issues/2103

## 

Regards,
Michael

**Comment by LoicGoyet** [comment]
Sorry I accidentally post the issue while writing ><. I'm currently finishing it, I do not talk of maps :).

**Comment by LoicGoyet** [comment]
That's it, my full issue is on :)

**Comment by chriseppstein** [comment]
This is not on our roadmap at this time. But in Sass 3.5 we've introduced first class functions and in 4.0 there's a module system that provides namespacing and encapsulation, so it's possible for users to create a quasi-object system on top of those primitives. If we see a user-space implementation become more widely adopted we may decide to introduce syntactic sugar for it.

**Comment by LoicGoyet** [comment]
@chriseppstein thanks for the answer !

I expected it is off the roadmap for now, but I just wanted to be sure I am not missing something or working on a object-like system it will be released soon.
For know with first class functions and bunch of methodology I was able to make a similar pattern, so no rush 👍
