### ISSUE TITLE
Sass function to call more than one Palette

### ISSUE THREAD

**Issue by douglasdeodato** [sass/sass#2104]
I am using sass palettes and I would like know how can I make this function works for more than 1 palettes.

right now I can just use 1 palette with this function, how can make this function works for more than 1 palette?

the reason I want that is because I have different components in that project and each one should have their own palette. (because will be exported for a library for a easy use in the next projects)

I am getting this error when I run my code:

`error scss/functions/_functions.scss (Line 18: $map: null is not a map for`map-get')
`

that error happen when I create 2 palettes in the same project  if I have just 1 works well.

structure:
components/component1 (1 palette created here)

(main palette)
main
base/config (1 palette created here too)

```
@function palette($palette, $shade: 'base') {
  @return map-get(map-get($main-palette, $palette), $shade);
}


//my primary palette for whole project
$main-palette: (
    grey: (
        xx-light : lighten($grey, 43%),
        x-light  : lighten($grey, 35%),
        light    : lighten($grey, 6%),
        base     : $grey,
        dark     : darken($grey, 8%),
        x-dark   : darken($grey, 16%)
    ),  
);
```

secondary palette just for a specific component

```
@function palette($palette, $shade: 'base') {
  @return map-get(map-get($component1-palette, $palette), $shade);
}


  $component1-palette: (
            black: (
                light    : lighten($black, 6%),
                base     : $black,
                dark     : darken($black, 8%),
                x-dark   : darken($black, 16%)
            ),  
        );

```

I know I could just use:

```

  $main-palette: (
            black: (
                light    : lighten($grey, 6%),
                base     : $grey,
                dark     : darken($grey, 8%),
                x-dark   : darken($grey, 16%)
            ),  
            component1: (
                light    : lighten($black, 6%),
                base     : $black,
                dark     : darken($black, 8%),
                x-dark   : darken($black, 16%)
            ),  
        );

```

but my point is not apply the palette I want inside the main one, but create a own palette for the component.

understand my point?

thanks

**Comment by GabeJonson** [comment]
try to transmit three parametrs. First map varibel as default, key and value...
that was like a
```
@function material($color: $material, $key, $val) {
	@return map-get(map-get($color, $key), $val);
}
```

**Comment by chriseppstein** [comment]
It seems to me that you need to take the palette storage map as an argument.

``` scss
@function palette($palette-name, $shade: 'base', $palette: $main-palette) {
  @return map-get(map-get($palette, $palette-name), $shade);
}
```

And then you would use the main palette by default, but you could specify another palette when you invoke it like so: `palette(black, $palette: $component1-palette)`
