### ISSUE TITLE
The method `invalid_content_parent` is never called

### ISSUE THREAD

**Issue by marianposaceanu** [sass/sass#2106]
So I was investigation why using libsassc I was getting:

```
SassC::SyntaxError: Error: Mixin "something" does not accept a content block.
```

which is completely valid since `something` doesn't use `@content`.

https://github.com/sass/libsass/blob/master/src/expand.cpp#L666

---

Yet on the Ruby side nothing is reported and whilst reading a bit the code:

This method should set `has_content` to true:

https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/check_nesting.rb#L82

but it doesn't seem to be called anywhere.

Hence this logic won't raise an exception if the mixin has no `@content`:

https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/perform.rb#L354

**Comment by chriseppstein** [comment]
I need to see a Sass source code example for this.

**Comment by marianposaceanu** [comment]
Ok the _bug_ is quite an edge case it seems libsassc is much more strict:

``` sass
@mixin breakpoint($args: null) {
  //  CASE IF NO DATA IS PASSED WE SHALL OUTPUT MEDIA QUERY ONLY FOR SCREEN THIS MEANS STYLES WILL BE GLOBALLY AND INHERITABLE BY UPPER BREAKPOINTS
  @if $args == null {
    @media screen {
      @content;
    }
  }
  //  CASE IF DATA IS PASSED WE GENERATE BREAKPOINT FOR PASSED BREAKPOINT
  @else {
    @media screen and (min-width: $args) {
      @content;
    }
  }
}

@mixin clearfix() {
  a::after {
    content: '';
    display: table;
    clear: both;
  }
}

@include breakpoint() {
  padding: 30px 0;

  @include clearfix() {}
}
```

## libsassc

```
Error: Mixin "clearfix" does not accept a content block.

       Backtrace:
        app/assets/stylesheets/home.scss:59, in mixin `@content`
        app/assets/stylesheets/home.scss:37, in mixin `breakpoint`
        app/assets/stylesheets/home.scss:56
        on line 59 of app/assets/stylesheets/home.scss
>>   @include clearfix() {}
   -----------^
```

## Ruby sass

it renders without issue

In any case this is something minor - I just found it bc. the front-end guy made that small mistake and thus the assets would not compile anymore was curios why that happened.

**Comment by chriseppstein** [comment]
Huh. Yeah, I would consider this a bug in ruby sass. A content block is not allowed to that mixin. @nex3 can you confirm?

**Comment by nex3** [comment]
Yep, looks like a bug to me. Here's a much simpler repro:

``` scss
@mixin foo() {}
@include foo() {}
```

It looks like we aren't recognizing the empty content block as something that could trigger the error.

**Comment by maciej-ka** [comment]
@chriseppstein, @xzyfer https://github.com/sass/sass-spec/pull/897

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
