### ISSUE TITLE
@import $myVariable as $variableAlias from 'some-module'

### ISSUE THREAD

**Issue by xprt64** [sass/sass#2107]
It would be nice if one could import specific variables from other files (similar to EcmaScript 6). It could be done like this:

`@import $myVariable as $variableAlias from 'some-module'`

or like this:

`@import {$myVariable as $variableAlias} from 'some-module'`

**Comment by chriseppstein** [comment]
Duplicate of #353 ([among others](https://github.com/sass/sass/labels/%40use)). We're addressing this in Sass 4.0.
