### ISSUE TITLE
String interpolation of Lists: uniform output

### ISSUE THREAD

**Issue by gcmznt** [sass/sass#2108]
Trying the following:
`@debug #{('a', 'b', 'c')};`

I get two different output:
- in compressed mode: `DEBUG: a,b,c`
- in other modes: `DEBUG: a, b, c`

I think that using string interpolation of structured data types must generate the same output always. In my use case I was using interpolation to generate `content` for an `::after` element, and i was not expecting to find two different output.

If this behaviour is correct for other use cases, a possible solution is to create a function like JS `Array.join` method and give more flexibility to the developer.

What do you think about this topic?
Thank you

**Comment by chriseppstein** [comment]
Interpolation assumes the output is headed to the CSS file so it compresses.

You don't need to use string interpolation with `@debug`. The debug function passes it's argument through the `inspect()` function which has the property of producing consistent output that you seek.
