### ISSUE TITLE
Sass - Invalid CSS after "}": expected "}", was ""

### ISSUE THREAD

**Issue by nitaki** [sass/sass#2109]
Hi everybody.

This i smy first time here on GH trying to find an answer but I'm at my wit's end with this. I keep getting the above error when trying o compile with Compass. I also tried Sassmeister and get the same problem so there's probably an error in the code but I am not getting it!

If someone could help me out I would be very grateful!

**Comment by veganista** [comment]
This probably isn't the best place for this sort of question. This is for for reporting bugs with sass it's self.

However, you had a couple of missing `}`'s in the `.section` block.

See here: http://www.sassmeister.com/gist/a602d747ad063e4cd1d74a8777e33bdb
