### ISSUE TITLE
Error encountered while saving cache ... can't dump hash with default proc

### ISSUE THREAD

**Issue by midwire** [sass/sass#2110]
This is a cross-posted issue here: https://github.com/rails/sass-rails/issues/331#issuecomment-236230570.

When hitting production for the first time after a deploy, or in development after deleting `tmp/cache` and restarting Apache/Passenger, we see in the log:

`Warning. Error encountered while saving cache 7664b4b0d7f5e2ecfb6f548f93c2953c94877abd/typography.sassc: can't dump hash with default proc`

We just upgraded to Rails 5 to start seeing this problem.

It is directly related to importing google fonts through their dynamic `css`:

`@import url(https://fonts.googleapis.com/css?family=Montserrat:400,600,700|Open+Sans:400,600,700)`

... though my hunch is that any `@import url` call that results in a `CssImportNode` is having this problem.

Further investigation reveals a similar issue to [this](https://github.com/rails/sass-rails/issues/36#issuecomment-2189392):
- A Sass::CacheStores::Base instance attempts (and fails) to call Marshal.dump on :
- A Sass::Tree::RootNode instance which amongst its @children nodes has :
- A Sass::Tree::CssImportNode instance which amongst its attributes has :
- A `:uri` which is an instance of `Sass::Script::Tree::Funcall` which fails when trying to call `Marshall.dump` on it
- The `Sass::Script::Tree::Funcall` instance has two attributes (`args`, `options`) both of which fail when trying to call `Marshall.dump` on them.
- Further... the `args` attribute is an `Array` of `Sass::Script::Tree::Literal` instances which has a `value` attribute which is : 
- An instance of `Sass::Script::Value::String` which has an attribute `options` which is an instance of Hash, which fails when trying to call `Marshal.dump` on it.
- That `options` hash does not have a `default_proc` so there must be another embedded hash which does.

I'm currently trying to figure out where those Hash instances get set and by whom. Any insights will be appreciated.

```
sass (3.4.22)
sass-rails (5.0.6)
  railties (>= 4.0.0, < 6)
  sass (~> 3.1)
  sprockets (>= 2.8, < 4.0)
  sprockets-rails (>= 2.0, < 4.0)
  tilt (>= 1.1, < 3)
```

**Comment by midwire** [comment]
**Update:** 

```
badnode = root.children[0] #=> Sass::Tree::CssImportNode
spr_cached_environment = badnode.uri.args[0].value.options[:sprockets][:context].environment
```

`Sprockets::CachedEnvironment` sets several instance variables as Hashes with `default_proc`s, which fail when trying to call `Marshal.dump` on them.

Stepping back a bit, I'm wondering...

`CssImportNode` is derived from `DirectiveNode` which says:

```
  # A static node representing an unprocessed Sass `@`-directive.
  # Directives known to Sass, like `@for` and `@debug`,
  # are handled by their own nodes;
  # only CSS directives like `@media` and `@font-face` become {DirectiveNode}s.
  #
  # `@import` and `@charset` are special cases;
  # they become {ImportNode}s and {CharsetNode}s, respectively.
  #
  # @see Sass::Tree
```

So I'm wondering why are we trying to cache an `A static node representing an unprocessed Sass`@`-directive`? Since it is unprocessed what is the point of caching it at all? Should it not process the directive, download the `css` and then cache that?

Asking in earnest.

**Comment by chriseppstein** [comment]
For performance we cache parsed Sass files as an AST. that way we can re-use the AST without re-parsing the sass file. One of the important aspects of the AST is the class (Importer) that is used to find the file on disk (or elsewhere) so that we can also find files relative to that file. Sass-rails uses such a class and one of the contracts of that class is that it's instances must be serializable.

Maybe there's a fix for Sass or via Sass rails. Or maybe it's better to fix it in sprockets. No one on this project uses rails anymore so if someone can debug this and send a patch, we'll review it.

**Comment by midwire** [comment]
Thanks @chriseppstein. We've moved the CSS import directive for the google font outside of Sass which works well for us. I don't know if I'll get the OK to fix the underlying issue, but I appreciate the info about AST. Feel free to close. Thanks for the awesome work on Sass!
