### ISSUE TITLE
Wrong selector and extend

### ISSUE THREAD

**Issue by iddekingej** [sass/sass#2114]
Code:

```
a b{
    c:d;
}

d{
    @extend a,b;
}
```

Output is:

```
a b, d b, a d, d d {
  c: d; }

```

what I expect:

```

a b, d b, a d{
  c: d; }

```

Version: 
Sass 3.4.22.7716e67

**Comment by chriseppstein** [comment]
It's working as intended, `d d` is absolutely a result of that extend directive because both `a` and `b` are "replaced" by `d` in the selector `a b`.
