### ISSUE TITLE
Use @import for satisfying dependencies only

### ISSUE THREAD

**Issue by CROSP** [sass/sass#2117]
Hi, I have problem, I need to include/extend few classes from `Bootstrap Framework` in some of my `.scss` files. 
The easiest way is to `@import "../external-dependencies/bootstrap/assets/stylesheets/bootstrap";` 
This works, but  the problem that I get all compiled bootstrap classes in my output `CSS` file, that is undesirable behavior, I need only satisfy dependencies like that    

```
.l-software-features {
  @extend .row;
} 
```

And I don't want to have `bootstrap` classes in my main css.  
I want to get for example something like following output    

```
.row,
.l-software-features {
  // Row properties
} 
.l-software-features {
  color : #fff;
} 
```

Is there any solution for this problem ?

**Comment by chriseppstein** [comment]
There is. Bootstrap should provide their sass imports in such a way as to allow you to selectively import only the parts you want.

In Sass 4.0 we will have a new import system that does allow you more control over whether anything is output. No ETA on that right now.
