### ISSUE TITLE
Background shorthand

### ISSUE THREAD

**Issue by artemgurzhii** [sass/sass#2118]
Having this sass code

``` javascript
background: url('background.png') -10px -10px/110% no-repeat
```

Getting this error
public/css/2-modules/platform/platform-heading.sass
Error: -0.09709px/% isn't a valid CSS value.
        on line 2 of platform-heading.sass

> > url('background.png') -10px -10px/110% no-repeat

**Comment by chriseppstein** [comment]
This compiles fine in ruby sass. However libSass seems to choke on it. Is that what you're using?

**Comment by artemgurzhii** [comment]
I'm using gulp-sass, but this is not fixing this issue. Is there any way to fix/avoid this?
