### ISSUE TITLE
Parse pseudo selector arguments as declaration values

### ISSUE THREAD

**Issue by nex3** [sass/sass#2120]
Right now we have a bunch of custom logic to parse pseudo selector arguments. Although I think this covers all the syntaxes those selectors use in practice today, it's not very future-proof; CSS will probably add more different pseudo selector argument syntaxes in the future that may not fall under our current parsing. To be maximally future-proof, we should parse those arguments using the [`<declaration-value>`](https://drafts.csswg.org/css-syntax-3/#ref-for-typedef-declaration-value-1) production that was added to support custom properties. This will parse any sequence of reasonable characters while still respecting tokenization rules.

**Comment by xzyfer** [comment]
LibSass is also interested in the implementation of this. I've trying to clean up our selector handling. Our pseudo selector handling is need to some love. I'd take this change as an opportunity to bring our implementation closer to Ruby Sass'.
