### ISSUE TITLE
Bracket lists shouldn't be == to parenthesized lists

### ISSUE THREAD

**Issue by nex3** [sass/sass#2121]
Currently bracketed lists in 3.5 are `==`-equivalent to parenthesized lists with the same contents. This doesn't match the behavior of lists with different separators, or the general principle that `==`-equivalence should roughly track CSS equivalence.

**Comment by xzyfer** [comment]
Does this extend to when lists are keys to map-get also?

**Comment by nex3** [comment]
@xzyfer Definitely. `==` and hash equality are always the same.

**Comment by mirisuzanne** [comment]
@nex3 is there a `list-separator()` equivalent for checking if a list uses brackets vs parenthesis? Also, is an un-specified list like `one two three` forced into one of the two categories by default? 

In True test output, we have to help users understand that lists can output the same `inspect` value, and still be unequal.

**Comment by xzyfer** [comment]
Sorry for the short reply I'm on my phone. I think you'll find most of the
answers in sass-graph

https://github.com/sass/sass-spec/tree/master/spec/sass_3_5/functions

Check out the join and is-bracketed folders.

**Comment by nex3** [comment]
To add some more detail: in Sass's internals, lists *never* have parentheses. When you write `(1 2 3)`, the parentheses mean the same thing that they do in `(1 + 1)`—they just group the expression. So the only question is whether a list has brackets or has no brackets, which is answered by `is-bracketed()`.
