### ISSUE TITLE
$grey and  $gray palettes

### ISSUE THREAD

**Issue by douglasdeodato** [sass/sass#2123]
I just curious about this, I know grey and gray are the same thing one used in american English and another in British .

I just tried create 2 palettes with the names grey and gray and I got this:

`Duplicate key #808080 in map (grey: (xx-light: lighten($grey, 43%), x-light: rgba(240, 240, 240, 1), light: rgba(221, 221, 221, 1), base: $grey, dark: rgba(133, 133, 133, 0.24), x-dark: darken($grey, 16%)), gray: (base: $gray)).`

http://www.sassmeister.com/gist/ce8796a25459423576e8bd50218892ae

that is a intentional error?  I just curious about that, where I can find more about this?

thank you.

**Comment by xzyfer** [comment]
This is because colour identifiers are replaced with their hex values. i.e. `color: red` -> `colour: #ff0000`.

So in your case but `grey` and `gray` are being turned into `#808080` which is why you're getting a duplicate key error.

**Comment by douglasdeodato** [comment]
@xzyfer  thanks but I am still not understanding.

**Comment by chriseppstein** [comment]
@douglasdeodato You should quote color names if you want them to be identifiers instead of color values.
