### ISSUE TITLE
Unbreakable space between rule and opening brace results in the browser ignoring the rule

### ISSUE THREAD

**Issue by Aquaj** [sass/sass#2125]
I'm surprised this bug hasn't been reported before but after some search in the issues I couldn't find it.

We had the rule :

```
.manure-sub-results-group {     // results-group[&nbsp;]{
  width: 100%;
}
```

Which created the appropriate rule inside the CSS, with a selector that would match the elements concerned, but that the browser would simply consider malformed and not apply to said elements.

Shouldn't Sass either forbid or replace unbreakable whitespaces at compilation? Is there a use to them in CSS that I don't know of?

We're using Rails with the `sass-rails` gem, if it turns out that issue actually depends from the sass-rails project, I apologize for the inconvenience and will just scoot over to their repository.

**Comment by chriseppstein** [comment]
Sorry, I don't see what the error is. I compiled your code example and get:

``` css
.manure-sub-results-group {
  width: 100%; }
```

Please provide a simple code example that in its entirety reproduces this issue and show us what output/error you're getting and what you expected to get.
