### ISSUE TITLE
En spaces (U+2002) are parsed as ListLiterals instead of VariableNodes

### ISSUE THREAD

**Issue by etjossem** [sass/sass#2126]
If you include a non-standard space character such as en space (U+2002) in a line of Sass code, that entire line is parsed as a Sass::Script::Tree::ListLiteral instead of a Sass::Tree::VariableNode.

This behavior can cause cascading problems for scss-lint, etc.

Original bug report: https://github.com/brigade/scss-lint/issues/775

**Comment by chriseppstein** [comment]
We parse according to the CSS grammar which specifically defines what characters are considered whitespace and calls out "space-like" characters as not being considered whitespace.

![css3 module syntax 2016-08-31 13-58-10](https://cloud.githubusercontent.com/assets/1839/18146153/0dea73f0-6f83-11e6-88bb-f63825e105b0.png)
