### ISSUE TITLE
Ability to pass additional variables to Sass.compile

### ISSUE THREAD

**Issue by bogdan** [sass/sass#2127]
Can I pass some extra variables to `Sass.compile`?

ex:

``` ruby
Sass.compile("#{$element} { width: 100% }", variables: {element: "#my_element"})
```

I know I can concat the definition to the SASS manually, but in my case:

``` ruby
builtin_variables = "$element: 'my_element'\n"
Sass.compile(builtin_variables + user_defined_sass)
```

Results in wrong line number when syntax invalid because I want the line numbers to match the `user_defined_sass`.

**Comment by chriseppstein** [comment]
No. The way to do this would be to expose a sass function that can return a value from your external environment via a function call instead of as a magically globally available variable.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#defining_custom_sass_functions
