### ISSUE TITLE
@include group (Idea)

### ISSUE THREAD

**Issue by eliezerpujols** [sass/sass#2130]
You would be cool to be able to do this:

`mixins.scss` :
![image](https://cloud.githubusercontent.com/assets/12506535/18113473/8899333e-6f06-11e6-8f23-76b9bc704b63.png)

Other file, `@include` group:
![image](https://cloud.githubusercontent.com/assets/12506535/18113569/5b14f258-6f07-11e6-8ed2-a0caa389551d.png)

Or

![image](https://cloud.githubusercontent.com/assets/12506535/18113672/01609126-6f08-11e6-9366-9185e7d036cf.png)

A rule `@include` which contain others`@include`.

**Comment by chriseppstein** [comment]
I understand that repeatedly typing `@include` is annoying. But to address that I'd rather do #366 than this. Any syntax that we introduced for at-rules I'd want to be generally applicable to all at-rules.
