### ISSUE TITLE
Cannot use hyphens between interpolated variables in a class name

### ISSUE THREAD

**Issue by matthewmorek** [sass/sass#2131]
At present it is impossible to include a hyphen character (`-`) between two interpolated variables inside a class name.

**What I'm trying to do:**

``` sass
.h#{$i}-#{$mq} { ... }
```

**Expected result:**

``` css
.h1-md { ... }
```

**Actual result:**

``` bash
Please check validity of the block starting from line #80  Fatal
```

The only way out of this situation is to use `unquote` function and declare a hyphen as a variable:

``` sass
$hyphen: unquote("-");
.h#{$i}#{$hyphen}#{$mq} { @include h($i); }
```

**Comment by chriseppstein** [comment]
I cannot reproduce this with any recent version of ruby sass. Is this a libsass issue? If so, please report it to them at: https://github.com/sass/libsass/issues
