### ISSUE TITLE
Use platform independent exit codes rather than 65 for data errors

### ISSUE THREAD

**Issue by nschonni** [sass/sass#2132]
[I raised the issue that libsass doesn't match the Ruby Sass exit code](https://github.com/sass/libsass/issues/2162), which is causing issues when trying to port the sass-spec for node-sass. @mgreter helpfully pointed out that [65 has a different meaning on window](https://github.com/sass/libsass/pull/2163#issuecomment-244283645)

Not sure, but it seems like `EINVAL` might work http://blog.honeybadger.io/understanding-rubys-strange-errno-exceptions/

/cc @mgreter @xzyfer

**Comment by chriseppstein** [comment]
I can't think of any way to deprecate an exit code and we're not going to risk breaking any scripts calling `sass` already and checking the return code.

![sysexits 2016-09-08 11-05-42](https://cloud.githubusercontent.com/assets/1839/18360804/58941cf8-75b4-11e6-9d4d-ad881b7be1f8.png)

That said, we might consider changing the exit code to something platform specific on just windows, but, tbh, I'm not sure what value that brings that is worth breaking any windows scripts.

**Comment by mgreter** [comment]
FWIW:

Ruby (test.rb)

``` ruby
exit(65)
```

Batch (test.cmd):

``` cmd
@echo off
ruby test.rb
if ('%ERRORLEVEL%' == '0') (
  echo Ran command successfull!
) else (
  echo An error was detected!
  NET HELPMSG %ERRORLEVEL%
)
```

Results in

```
An error was detected!
Network access is denied.
```

Ruby is simply following POSIX conventions, which do not fully apply on windows!
