### ISSUE TITLE
Import CSS Files

### ISSUE THREAD

**Issue by ghost** [sass/sass#2137]
https://github.com/sass/sass/issues/556

Why is this issue still open? What is the current method to do this without too much hassle?

**Comment by chriseppstein** [comment]
The linked issue has solutions to this, they are still valid.

**Comment by ghost** [comment]
so it's being stalled right now and people will have to do with a fix?

**Comment by chriseppstein** [comment]
@Cratyz No it's being worked on as a feature in Sass 4.0. As it says in the original issue. There are a number of work-arounds, the simplest being to simply rename the files to have a different extension.
