### ISSUE TITLE
@extend should stop on pseudo elements

### ISSUE THREAD

**Issue by zuzusik** [sass/sass#2139]
Pseudo element should always be on the last place in selector, otherwise selector is considered to be invalid.

Look at this example: https://gist.github.com/zuzusik/c80e3953ca50e89fb07cd7452db5cd63, it produces the invalid CSS (`.article .header::before .highlighted` is invalid selector and so all the rule is considered to be invalid)

**Comment by nex3** [comment]
I think this has to be something we leave up to the user to sort out. [According to the spec](https://drafts.csswg.org/selectors-4/#pseudo-element-structure), some pseudo-elements do allow combinators and some do not. Sass tries hard to avoid encoding information about the specific semantics of different CSS identifiers, which means we can't distinguish between these two cases and must assume that any pseudo-element may have combinators.
