### ISSUE TITLE
@extend prints styles in the order that the extended are originally declared

### ISSUE THREAD

**Issue by bdimcheff** [sass/sass#214]
This might be the expected behavior for @extend, but it seems odd to me.  I'd be willing to take a shot at fixing it if it would be welcome.  Check it out:

```
.class-one
  color: red
  font-size: 8px

.class-two
  color: lime

.merged
  @extend .class-two
  @extend .class-one
```

Turns into:

```
.class-one, .merged {
  color: red;
  font-size: 8px; }

.class-two, .merged {
  color: lime; }
```

That means that, even though I extend `.class-one` _after_ `.class-two`, the style for `.class-one` gets written out before `.class-two`, so the cascade order is not what I expect.  I'd expect something with `.merged` to be red, but it's green instead.  Am I crazy?

**Comment by nex3** [comment]
This is expected. If A `@extend`s B, A is added to B's selector. This doesn't and shouldn't change the location of B.

When you say that `.merged` `@extend`s `.class-two` and `.class-one`, you're saying that all `.merged` elements should be styled as though they also match `.class-two` and `.class-one`. The precedence of these styles is still determined by the location of `.class-two` and `.class-one` in the source.

**Comment by bdimcheff** [comment]
Ah, I see.  That makes sense... I'll try to figure out some other way of doing what I'm trying to do.  Thanks.
