### ISSUE TITLE
Strange result  when ";" mssing in nested css

### ISSUE THREAD

**Issue by iddekingej** [sass/sass#2142]
When I compile the following statement ( the ";"  is omitted after b:3):

```
a{
    b:3
    c{
        d:2;
    }
}
```

I get the follow strange result

```
a {
  b: 3 c;
    b-d: 2; }

```

What I expected : Error (Invalid css)

Version:Sass 4.0.0.alpha.1.7c08935 (Bleeding Edge)

**Comment by nex3** [comment]
Sorry it took so long to reply!

This is expected. Sass allows nested declarations, so you can write something like:

```scss
div {
  font: 15px sans-serif {
    weight: bold;
  }
}
```

`3 c` is a valid declaration value, so that's how Sass is parsing your CSS.
