### ISSUE TITLE
can we generate multiple mixins (mixin lib) with loop in sass

### ISSUE THREAD

**Issue by seeliang** [sass/sass#2146]
instead of

``` sass
@mixin tg($font-size,$line-height) {
  something related to font-size and line-height
}

@mixin h1 {
  @include tg 
}

@mixin h2 {
  @include tg 
}

....
```

can i do 

``` sass

$typography-list: h1, h2......
@mixin tg($font-size,$line-height) {
  something related to font-size and line-height
}


@each $typography in $typography-list {
  create @mixin {
    @include tg()
  }
}
```

I am trying to create mixin lib, so that it can be shared cross different projects without creating any css. 

The css render parts would be different sass files in different projects

**Comment by KittyGiraudel** [comment]
You can’t create mixins or functions dynamically in Sass at the moment.

**Comment by sihuiDomain** [comment]
Thanks, I am a big fan of your sass articles. Those articles have helped me in multiple projects and have saved hundreds of hours in maintaining and continuous integration. I can't thank you enough.

From your experience, do you think this feature is useful for sass in the long run ?

**Comment by KittyGiraudel** [comment]
I like how conservative Sass is in regard to adding features, so I’m going to go with a no. Even in programming language, it would be quite uncommon to dynamically generate functions. A possible way would be lambdas, but again that would likely be overkill for Sass.

**Comment by seeliang** [comment]
Thanks @KittyGiraudel
