### ISSUE TITLE
Invoking Functions outside of Properties

### ISSUE THREAD

**Issue by deckdom** [sass/sass#2148]
I noticed that functions can't be called/invoked from anywhere except from the properties. Example:

```
html {
    color: my-function();
}
```

Why isn't it possible to call methods from the global scope or basically from anywhere? Currently having issues with that since I'm working on a more programmatic approach rather than the usual way.

**Comment by KittyGiraudel** [comment]
Duplicate of https://github.com/sass/sass/issues/1854.

Why don’t you use a mixin for that?
