### ISSUE TITLE
@import + http request?

### ISSUE THREAD

**Issue by MCTaylor17** [sass/sass#2152]
I'm just wondering if there's a good way to import files from an external source.  For example:

``` .scss
@import "http://fake.com/resource.scss";
```

**Comment by douglasdeodato** [comment]
@MCTaylor17  check out: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

**Comment by MCTaylor17** [comment]
@douglasdeodato, I guess I didn't elaborate very well.  I'd like Sass to make an HTTP request to retrieve the asset so that I can work with it (eg extending classes, using variables from it, etc).

**Comment by KittyGiraudel** [comment]
As far as I can tell, this is not possible at the moment.

**Comment by nex3** [comment]
You can define [a custom importer](http://sass-lang.com/documentation/Sass/Importers.html) to do this yourself.
