### ISSUE TITLE
Nested ampersand "prefix" in class does not get expanded with parent @extend

### ISSUE THREAD

**Issue by JawsomeJason** [sass/sass#2154]
Take the following Sass example using BEM-style syntax:

``` sass
.foo {
  color: green;

  &__bar {
    color: red;
  }

  .free {
    color: blue;
  }
}

.foo-to-extend {
  @extend .foo;
}
```

My expected output:

``` sass
.foo, .foo-to-extend {
  color: green;
}
.foo__bar, .foo-to-extend__bar {
  color: red;
}
.foo .free, .foo-to-extend .free {
  color: blue;
}
```

Actual output (v3.4.21):

``` sass
.foo, .foo-to-extend {
  color: green;
}
.foo__bar {  // where is `, .foo-to-extend__bar`
  color: red;
}
.foo .free, .foo-to-extend .free {
  color: blue;
}
```

This seems unintended, especially since the only difference is a space.  Can someone confirm if this is a known bug so I can track it?  Or is there a workaround for my needs?

**Comment by nex3** [comment]
This is the intended behavior. `@extend` is handled after *all* SassScript has been processed, so it only sees selectors with `&` resolved.
