### ISSUE TITLE
Improve & suffixing

### ISSUE THREAD

**Issue by AyubM** [sass/sass#2158]
It would be beneficial if the language allowed suffixing & as easily as prefixing it.

```
.foo {
&.bar {
    // works
}

.bar & {
    // works
}

.bar& {
    // doesn't work
}
}
```

Reason this would be useful is because you could easily make "variations" for modules. see http://stackoverflow.com/questions/39812375/bubble-up-rules-in-sass-for-variation-theme-classes

**Comment by KittyGiraudel** [comment]
Duplicate of https://github.com/sass/sass/issues/1856.
Duplicate of https://github.com/sass/sass/issues/1760.
Duplicate of https://github.com/sass/sass/issues/1695.
Duplicate of https://github.com/sass/sass/issues/1826.
