### ISSUE TITLE
Using Sass's parsers & visitors to modify CSS

### ISSUE THREAD

**Issue by rmosolgo** [sass/sass#2169]
Hi there, 

Here's a question that might just end in "nope nope nope", but here goes anyway 😆 

I'm looking for a way to turn this: 

``` css
:module(stuff) .thing { color: red; }
```

into this: 

``` css
/* development: */
.{opaque hash}_stuff_thing { color: red; }
/* production: */
.{opaque hash}st { color: red; }
```

I had a working version with the `CssParser` gem, but I couldn't figure out how to use it in a way that didn't throw out media queries. I see that Sass has VERY robust language manipulation tools, so I'm trying to take them for a spin. Here's what I've got so far: 

``` ruby
    def rewrite_css(css_module_code)
      # Parse incoming CSS into an AST
      css_root = Sass::SCSS::CssParser.new(css_module_code, "(CSSModules)", nil).parse
      # modify the AST 
      Visitor.visit(css_root) 
      # print out new valid CSS 
      css_root.css
    end 

    class Visitor < Sass::Tree::Visitors::Base
      def visit_rule(node)
        rewritten_rules = node.rule.map { |r| hash_selector(r) }
        selector_seq = Sass::Selector::Sequence.new(rewritten_rules)
        node.resolved_rules = Sass::Selector::CommaSequence.new([selector_seq])
      end

      private 

      def hash_selector(selector)
        # my hashing here 
      end 
    end 
```

However, I'm running into some problems where `RootNode#css` requires some values to have been assigned by various visitors, but I'm not exactly sure which ones. 

All that to say, I'm looking for advice and I have a few questions: 
- Is this a really terrible idea, to use Sass's stuff this way? Should I just stahp?
- Can you point me to relevant Sass code that might shed some light on this? 
- Do you have any alternative suggestion to accomplish my goal? 

I looked for an "extension point" in Sass where I could attach my visitor, but I couldn't quite find one! 

Thanks!

**Comment by KittyGiraudel** [comment]
I would probably write a simple PostCSS plugin to do that if I were you. Basically iterate through rules and modify the selector on the fly with a custom function (based on env, and file name and what else). PostCSS is very convenient to post-treat CSS (as the name suggests).

**Comment by rmosolgo** [comment]
Is that a JavaScript project? I'd like to stick to Ruby if possible 😬 

Here's what I ended up with, seems to work out ok: https://github.com/rmosolgo/css_modules/blob/master/lib/css_modules/rewrite.rb#L35
