### ISSUE TITLE
Euro-sign in `content` outputs garbage

### ISSUE THREAD

**Issue by thany** [sass/sass#2170]
Consider this snippet of scss:

```
a::before { content: '€'; }
```

This will output in the compiled css:

```
a::before { content: 'Ôé¼'; }
```

The file in question is saved as utf-8 - in fact ALL files in the project are. I tried adding `@charset 'utf-8';` at the top of the file, but this should be unneccesary as well as it just doesn't help. I've also tried putting this directive in my main.scss (the entry point - not an include), but no juice.

Please keep in mind that when I feed the above snippet as straight css straight to the browser, it'll parse it perfectly fine as utf-8. So from that I have to assume the file is saved as utf-8 and correctly intepreted as such.

So my editor is Brackets, which supports _only_ utf-8. So I can't possibly have saved the file in a different encoding by accident. I'm also on Windows 10, perhaps the €-character is a different one there, as compared to other platforms. Regardless, any non-ansi character will output garbage.

Now, I _could_ escape all those characters where I use them. I could, but I want my code to be as expressive as possible. so having some weird escape sequence in code where it shouldn't be neccesary, doesn't work with the concept of meaningful code that I try to live by.

So can we please get this problem fixed? I mean, once and for all? Because I recall this exact problem has existed for quite a while.

**Comment by thany** [comment]
Workaround:

Since I'm using [gulp-compass](https://www.npmjs.com/package/gulp-compass), I have created a file called `force-utf8.rb` which contains:

```
Encoding.default_external = 'utf-8'
```

And then in my Gulpfile.js, I added:

```
.pipe(compass({
  require: [
    path.join(__dirname, 'force-utf8.rb')
  ],
  css: 'source/assets/css',
  sass: 'source/sass',
  //...
```

This is no fix by any stretch of the imagination.

**Comment by douglasdeodato** [comment]
@thany  what version sass you are using? I don't get this problem using even the 3.4

**Comment by thany** [comment]
I'm on 3.4.22.

Can you think of a reason this might be happening, even if it's working fine on your machine?

**Comment by nex3** [comment]
I'm not sure why your system is reading the input as the wrong encoding, but if you add `@charset "UTF-8";` to the top of the file, it will ensure that Sass will *always* read it as UTF-8 regardless of what the system says.

**Comment by thany** [comment]
Last time I checked, that didn't help.
Do I need to include it in a specific file (like the entry point) or only to the file where non-ASCII is used, or to all files?

Is there any documentation that describes Sass' behaviour regarding how to interpret encoding as UTF-8 or otherwise?

**Comment by nex3** [comment]
> Last time I checked, that didn't help.
> Do I need to include it in a specific file (like the entry point) or only to the file where non-ASCII is used, or to all files?

Only the file where non-ASCII characters are used.

> Is there any documentation that describes Sass' behaviour regarding how to interpret encoding as UTF-8 or otherwise?

There's [a section in the reference](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#encodings).
