### ISSUE TITLE
Compressed CSS in <style> tag breaks webfonts

### ISSUE THREAD

**Issue by danielbenjamins** [sass/sass#2172]
I'm using CodeKit and Sass to compile a .css file. That file I include in between "<style></style>" tags in the header. When I use "Compress" to compile my CSS it breaks my webfont, although the link to the webfont is valid. It breaks because spaces are being removed in the compiling process. When I compile using "Compact" everything is fine. Any suggestions?

**Comment by danielbenjamins** [comment]
My code:

**Compact, works:**

`@font-face { font-family: 'Schluber'; src: url("www.mywebsite.com/fonts/Schluber.eot"); src: url("www.mywebsite.com/fonts/Schluber.eot") format("embedded-opentype"), url("www.mywebsite.com/fonts/Schluber.woff2") format("woff2"), url("www.mywebsite.com/fonts/Schluber.woff") format("woff"), url("www.mywebsite.com/fonts/Schluber.ttf") format("truetype"), url("www.mywebsite.com/fonts/Schluber.svg#Schluber") format("svg"); }`

**Compressed, doesn't work:**

`@font-face{font-family:'Schluber';src:url("www.mywebsite.com/fonts/Schluber.eot");src:url("www.mywebsite.com/fonts/Schluber.eot") format("embedded-opentype"),url("www.mywebsite.com/fonts/Schluber.woff2") format("woff2"),url("www.mywebsite.com/fonts/Schluber.woff") format("woff"),url("www.mywebsite.com/fonts/Schluber.ttf") format("truetype"),url("www.mywebsite.com/fonts/Schluber.svg#Schluber") format("svg")}`

**Comment by KittyGiraudel** [comment]
I had a look at your code. I don’t see anything that could cause an issue on Sass’ side. The compression seems fine.

**Comment by danielbenjamins** [comment]
Well apparently it's not fine ;-)

Because of the compression spaces are being removed and that breaks the webfonts. I contacted CodeKit and they point at Sass for causing this problem.

What to do...?

**Comment by KittyGiraudel** [comment]
I don’t see where a space has been removed that should have not. Also, I have been using Sass for compressing CSS for years without never seeing an issue. Could you show us the exact links to your fonts maybe?

**Comment by danielbenjamins** [comment]
Spaces are being removed after "@font-face", after "{", etc. If you take a close look at the code you'll see the differences. I copied the links from my website that is not live yet, I only replaced the real domain name with "www.mywebsite.com".

**Comment by douglasdeodato** [comment]
instead compile a css file into a sass file why dont u try just like that? i really sure will works.

```
$font-path: "../fonts/" !default;


@font-face {
  font-family: 'CalligraffitiRegular';
  src: url('#{$font-path}calligraffiti/Calligraffiti-webfont.eot');
  src: url('#{$font-path}calligraffiti/Calligraffiti-webfont.eot?#iefix') format('embedded-opentype'),
    url('#{$font-path}calligraffiti/Calligraffiti-webfont.woff') format('woff'),
    url('#{$font-path}calligraffiti/Calligraffiti-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by danielbenjamins** [comment]
I guess that's what I'm doing:

```
@font-face {
    font-family: 'Schluber';
    src: url('#{$themepath}/fonts/Schluber.eot');
    src: url('#{$themepath}/fonts/Schluber.eot') format('embedded-opentype'),
         url('#{$themepath}/fonts/Schluber.woff2') format('woff2'),
         url('#{$themepath}/fonts/Schluber.woff') format('woff'),
         url('#{$themepath}/fonts/Schluber.ttf') format('truetype'),
         url('#{$themepath}/fonts/Schluber.svg#Schluber') format('svg');
        }
```

**Comment by douglasdeodato** [comment]
ok @eaglejohn  so the problem is when you compile right? are u using command line for compile?  have you tried use command line of sass or grunt sass task?

**Comment by danielbenjamins** [comment]
Yes, only after compiling using "Compression" it's going wrong. Compiling using "Compacted" is working great. I'm using CodeKit (with the Sass compiler build in) to compile, I'm not familiar with the command line or other methods.

**Comment by douglasdeodato** [comment]
I am using command line and never got any problem it is very easy to use. these tools are easy but sometimes do a mess.

do you have the project anywhere on github? o can setup to u this task  if you want. 

or just follow this link: http://sass-lang.com/documentation/file.SASS_REFERENCE.html

**Comment by KittyGiraudel** [comment]
> Spaces are being removed after "@font-face", after "{", etc. If you take a close look at the code you'll see the differences.

That is the point. Useless spaces are being removed. That’s what compression does.

**Comment by danielbenjamins** [comment]
@HugoGiraudel Are the spaces still useless when they break functionality?

**Comment by douglasdeodato** [comment]
@eaglejohn  sometimes the spaces make broke the compiling.

if you are using sublime text, I suggest u install this: http://blog.revathskumar.com/2012/08/sublimetext-remove-tailing-spaces-on-file-save.html

that will remove all your spaces and tailing spaces of your code.

I sugest to you install as well: https://packagecontrol.io/packages/CSS%20Format

I hope helped you somehow.

**Comment by KittyGiraudel** [comment]
> Are the spaces still useless when they break functionality?

The removal of spaces is not what broke your code.

**Comment by danielbenjamins** [comment]
@HugoGiraudel What's breaking my code then? Since changing the compiling method fixes the issue. On Google I find more issues with webfonts and missing spaces.

@douglasdeodato Thanks, I'll look into it!

**Comment by KittyGiraudel** [comment]
> What's breaking my code then? Since changing the compiling method fixes the issue. On Google I find more issues with webfonts and missing spaces.

Do you have a link please?

**Comment by danielbenjamins** [comment]
@HugoGiraudel http://www.tamarakingtattoos.com/ the font "Schluber" is not loading, although the paths are correct. Path example: http://www.tamarakingtattoos.com/wp/wp-content/themes/tamaraking/fonts/Schluber.eot

**Comment by danielbenjamins** [comment]
@HugoGiraudel Did you find some time to take a look? The website is live and I can't have it live with the font not loading for much longer...

**Comment by KittyGiraudel** [comment]
I did have a look and I didn’t see anything wrong. Indeed the font files are not loading. That is super odd.

**Comment by danielbenjamins** [comment]
@HugoGiraudel Can we track this down to the way the file is compiled? Or is it something else? I recompiled the file again because it's a live website. So from now on the font is loading again. Still would like to use the compressed method since it's saving a lot of loading time.

When I load the css (using the compressed method) with the <link> tag everything is fine. As I said in my first post, I'm including the css in <style> tags.

**Comment by danielbenjamins** [comment]
I "fixed" it by splitting the fonts up from the css file and using this workaround:

```
<style>
@font-face{font-family:'Schluber';src:url("<?php echo $template_dir ?>/fonts/Schluber.eot");src:url("<?php echo $template_dir ?>/fonts/Schluber.eot")format("embedded-opentype"),url("<?php echo $template_dir ?>/fonts/Schluber.woff2")format("woff2"),url("<?php echo $template_dir ?>/fonts/Schluber.woff")format("woff"),url("<?php echo $template_dir ?>/fonts/Schluber.ttf")format("truetype"),url("<?php echo $template_dir ?>/fonts/Schluber.svg#Schluber")format("svg")}
<?php include (TEMPLATEPATH . '/style.css'); ?>
</style>
```

**Comment by mgreter** [comment]
@eaglejohn you have a UTF-8 BOM in your styles. Guess that is causing your problems. Your tools don't seem to handle UTF-8 files correctly (not sure how you concat/embedd them into your html).

![sass-merge-error](https://cloud.githubusercontent.com/assets/282293/19627016/5131c444-993e-11e6-8d7c-a4c2ef88566b.png)

**Comment by danielbenjamins** [comment]
I couldn't get rid of the UTF-8 BOM so far but I've found something else. When my css starts with something different than the font-face declaration, the issue is gone and all fonts are displaying perfectly...

<img width="755" alt="screen shot 2016-10-27 at 15 31 59" src="https://cloud.githubusercontent.com/assets/985981/19782183/bad994de-9c5a-11e6-8ad2-5be2b8f68d85.png">
