### ISSUE TITLE
Add ability to ignore specific directories or files

### ISSUE THREAD

**Issue by neolefty** [sass/sass#2173]
Useful for a large project with multiple targets. For example, we have multiple "brands" which all get built from the same codebase. It takes about 5 seconds to build each one. But during development, I typically only care about one of them, so I'd like to ignore the rest.

I can do that with --update:

`$ sass --update brands/my_brand`

My current solution is to prepend `_` to the other brands' main `.scss` files: rename `brands/foo/foo_branding.scss` to `brands/foo/_foo_branding.scss`.

I would rather do something like:

`$ sass --watch . --ignore brands/foo --ignore brands/bar`

The directory structure is something like this:
- app
  - a/_style.scss
  - b/_style.scss
  - c/_style.scss
- brands
  - foo/foo_branding.scss (imports a/_style.scss, etc)
  - bar/bar_branding.scss
  - my_brand/my_brand_branding.scss

**Comment by nex3** [comment]
This isn't a planned feature. You can always specify files individually if you want finer-grained control.
