### ISSUE TITLE
undefined method `visit_method' for Sass::Script::Tree::Operation:Class

### ISSUE THREAD

**Issue by ncino-cpezza** [sass/sass#2184]
Getting this error all of the sudden in my application no clue where to start or how to fix any help greatly appretiated!

running 3.4.22 gem version

**Comment by dovestyle** [comment]
+1... Happens when I `@import 'bootstrap';` I'm guessing it's an alpha bootstrap 4 issue and not just a sass issue.

**Comment by nex3** [comment]
Can someone provide a simple standalone reproduction case for this?

**Comment by webzorg** [comment]
I have it suddenly appear too. No clue where it comes from.

**Comment by chiefpansancolt** [comment]
NOt sure what more information i can provide as there is not much in an error message all i can say is it just happend again when i do a @import in the application.scss file similar to the @import 'bootstrap' command but for materialize and nothing changed in repo to make this happen, it just did...

**Comment by mirkode** [comment]
Hey guys,

I am also getting a 
```ruby
undefined method `visit_method' for Sass::Script::Tree::Operation:Class
```
when doing an `@import "bootstrap";` in my `application.scss` using the new `gem 'bootstrap', '~> 4.0.0.alpha6'`.
I was using `pronto-scss` before which threw me a similar error. Something like:
```ruby
undefined method `bubbles?' for Sass::Script::Tree::Operation:Class
```
Anyone knows something about that?
Any help is greatly appreciated!

Thanks!

**Comment by stefanverdonschot** [comment]
I'm also getting this error while importing bootstrap 4 alpha. Are there any updates about htis issue?

**Comment by chriseppstein** [comment]
I downloaded the latest bootstrap (branch `v4-dev`) and I compiled a sass file that consisted of `@import "bootstrap";` after placing the bootstrap `scss` directory on the import path. There was no error.

I also downloaded the exact version in the bootstrap gem for `4.0.0.alpha6` and compiled it like so:

`./bin/scss -I /Users/ceppstei/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bootstrap-4.0.0.alpha6/assets/stylesheets foo.scss foo.css`

So I need someone to create more detailed steps to reproduce this issue.

as things stand, I'm inclined to think this bug isn't a Sass bug and is probably related to a monkey patch by some other ruby gem. So please explain exactly how you are compiling your stylesheets (With compass? With rails? Some other framework?)

**Comment by Br3nda** [comment]
Found. Something in haml-rails is monkey patching us into this error
