### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by mabar** [sass/sass#2185]
It should be good to have possibility to say which data type is required on input and what is returned by sass mixins and functions.

@mixin example(color $foo, int $bar, list $baz): list{}
//requires color, int and list on input and returns list

**Comment by nex3** [comment]
Sass is a dynamically-typed language and we have no plans to add static type annotations. However, you can make assertions about types using the `type-of()` function:

```scss
@mixin example($color) {
  @if (type-of($color) != "color")
    @error "$color: #{$color} must be a color.";
  }

  // ...
}
```
