### ISSUE TITLE
Pass pwd as an argument to sass with the watch option

### ISSUE THREAD

**Issue by aadithpm** [sass/sass#2187]
Returns:
`error No such file or directory @ rb_sysopen - pwd`

Also:

`error pwd (Line 35: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 8 spaces.)`

However, it seems to be listening and trying to compile the file, returning  the same error.
The file compiles if I compile it manually. I'm not very good at this so I'm unable to pinpoint the issue. 
Would it be possible to add a feature to take pwd as an argument?

**Comment by nex3** [comment]
I'm sorry, how exactly are you invoking Sass?
