### ISSUE TITLE
Info message uniqid

### ISSUE THREAD

**Issue by tjapro** [sass/sass#2190]
Hello!
When I compile the scss files I have got this information:
`Info: No mac address - uniqid() falls back to uniqid.process(). no interfaces found`

I know that is only an information, but what does it means?

**Comment by nex3** [comment]
Can you provide more detail? Are you using Ruby Sass or LibSass? What version? How are you invoking it?

**Comment by tjapro** [comment]
In the past I had this message, but I tested today and I don't get any message...
If in future I have got the same message I will say.

I am using the last version of gulp-sass (gulp-sass@2.3.2) in a gulp script in fedora 25.
This is the piece of code:
```
gulp.task("sass", function() {
  return gulp.src(Object.values(paths.sources.sass))
    .pipe(g.plumber({
      errorHandler: alert
    }))
    .pipe(g.sourcemaps.init({
      debug: stage < 0
    }))
    .pipe(g.sass({
      outputStyle: stage < 0 ? 'nested' : 'compressed',
      sourceComments: stage < 0,
      includePaths: ["./node_modules/normalize.css"]
    }))
    .pipe(g.postcss([p.cssnext({
      browsers: ['last 2 versions']
    })]))
    .pipe(g.if(stage >= 0, g.cssnano()))
    .pipe(g.sourcemaps.write())
    .pipe(g.rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest(getPath() + "css"));
});
```

**Comment by nex3** [comment]
This is the repository for Ruby Sass. You want libsass, at https://github.com/sass/libsass.
