### ISSUE TITLE
Support HSV\HSB color model

### ISSUE THREAD

**Issue by ArmorDarks** [sass/sass#2192]
Hello

It would be great to have Sass `adjust-color` function support HSV color model.

This can be done by providing additional `$hsv: true` option.

The reason for this is that Photoshop, one of the most popular softwares among designer those days, still doesn't have option to switch HSV color model to HSL (which Sass uses by default).

Because of fundamental [differences](https://en.wikipedia.org/wiki/HSL_and_HSV) between HSL and HSV models, it causes a lot of frustrations for designers when it comes to adjusting colors based on already prepared Photoshop data.

Few years ago there were an issue about it: https://github.com/sass/sass/issues/1014, and it was proposed to do such thing as an extension. Sounds right, but in same time maybe because of extensive popularity of Photoshop and little hope that it will switch to HSL model, it would be not bad idea to revisit this issue and consider adding optional HSV color model mode to Sass functions.

I also must admit, that because HSV is linear and, for instance, changing brightness doesn't affect saturation, it is easier and more predictive system when it comes to getting of color variants based on color adjusting.

**Comment by nex3** [comment]
The response is the same as last time.

**Comment by ArmorDarks** [comment]
@nex3 Thanks for reply

It's slightly unclear why HSL has been chosen at first place despite wide popularity of HSV?

It seems to be quite odd pick, since in most cases with Sass works people which, well, having to deal quite a lot with colors, and in most cases they will stumble exactly upon HSV. So, it's unclear why it has been chosen to enforce less popular those days implementation on them.

The extension approach in Sass doesn't work quite well those days, because of environmental differences. Some projects running on Ruby, some on node-sass, and this means that extensions can't be made universally portable that easily.

**Comment by nex3** [comment]
> It's slightly unclear why HSL has been chosen at first place despite wide popularity of HSV?

HSL wasn't *chosen* so much as *inherited*. CSS supports it, and we want to be compatible with CSS, so we support it as well.

> The extension approach in Sass doesn't work quite well those days, because of environmental differences. Some projects running on Ruby, some on node-sass, and this means that extensions can't be made universally portable that easily.

An extension that's written in pure Sass should be plenty portable.

**Comment by ArmorDarks** [comment]
@nex3 Thanks for reply once again

> HSL wasn't chosen so much as inherited. CSS supports it, and we want to be compatible with CSS, so we support it as well.

Ah, I see. Well, then it's quite logical. Too bad that HSL is surprisingly unintuitive and very hard to work with due to lightness shifting other parameters.

> An extension that's written in pure Sass should be plenty portable.

Extensions of such kind written in pure Sass are quite slow due to calculations, even on libsass. I guess it's because a lot of underhood magic happens with types casting and so on. In the end, even `node-sass` function ends to be much cleaner and faster, but less portable.

Considering that some people have very large codebase, trading portability for such resources waste isn't an option too, unfortunately.

Well, I guess it doesn't change anything anyway. Thank you for finding time to take a look at this issue, though, and for Sass, of course :)
