### ISSUE TITLE
Navigating backwards within CSS selectors nestings

### ISSUE THREAD

**Issue by sorcamarian** [sass/sass#2193]
SCSS nesting is great and it gives me an idea about the HTML structure.

But for large nestings, it would be a great optimization measure to be able to go backwards. Basically, avoid certain nesting levels(leave them just for better organization purpose).

I thought at something like this:
```
<div id="wrapper" class="container-fluid">
  <div class="row">

    <div class="col-md-6 text-side">
      <h2>Entry title</h2>
      <div class="text-description">
        <p>Description</p>
        <p>Description</p>
        <p><Description<></p>
      </div>

    </div> <!-- .text-side -->
    <div class="col-md-6 image-side">
      <div class="image-wrapper">
        <div class="image-block">
          <img src="" alt="">
        </div>
      </div>
    </div> <!-- .image-side -->

  </div>
</div>
```
SCSS(with the feature I am trying to find) 
^ - back one selector
^(x) - back x selectors
(sign: "^" is inspired from: http://docs.emmet.io/ )

```
#wrapper {
  .row {

   .text-side {
      h2{
        color : #000;
        }// h2
      .text-description{
          p{
            color : #333;
            mark{
              background-color: green;
              } // mark
            } // p
        } // .text-description  
    }

    ^ .image-side {
   // avoid 1 selectors: .row
      .image-block {
        ^(2) img{
        // avoid 2 selectors: .image-block .image-side
          width: 100%;
          } // img
        } // .image-block
      } // .image-side

  }// . row
} // #wrapper
```

**Comment by nex3** [comment]
This strikes me as very difficult to read and understand what CSS will be produced, and I'm not a fan of having real Sass code that doesn't have any effect on the resulting CSS. I suggest using comments for pure documentation of the HTML structure.
