### ISSUE TITLE
SASS - npm WARN excluding symbolic link 

### ISSUE THREAD

**Issue by ghost** [sass/sass#2194]
I am using windows 10.

The sass installation has the following response:

C:\Dev>npm install sass
**npm WARN excluding symbolic link index.js -> lib/sass.js
npm WARN excluding symbolic link lib\index.js -> sass.js**
sassEssentials@0.0.1 C:\Dev
`-- sass@0.5.0

npm WARN sassEssentials@0.0.1 No license field.

C:\Dev>npm install -g sass
**npm WARN excluding symbolic link index.js -> lib/sass.js
npm WARN excluding symbolic link lib\index.js -> sass.js**
C:\Users\Zoltán\AppData\Roaming\npm
`-- sass@0.5.0

After the installation I tried to check the version:

C:\Dev>sass -v
'sass' is not recognized as an internal or external command,
operable program or batch file.

Could you please advise?

**Comment by mprins** [comment]
You need to talk to the npm package maintainer and/or follow the install instructions on: http://sass-lang.com/install

**Comment by Kyterneser** [comment]
I followed the manual and I got the following:

![gem-sass](https://cloud.githubusercontent.com/assets/22621999/20576863/ffe97bdc-b1bf-11e6-9a2e-59636a40c8f5.PNG)

I used this one also:

https://gist.github.com/luislavena/f064211759ee0f806c88

Any ideas?

**Comment by ghost** [comment]
Thanks for the comment. 

After trying to follow the standard manual again. I got the certificate error message: 

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

There is an up to date fix on the following webpage:

http://guides.rubygems.org/ssl-certificate-update/

Now it works fine.
