### ISSUE TITLE
Sass-lang.com - invalid certificate

### ISSUE THREAD

**Issue by drawcard** [sass/sass#2199]
Hi,

I'm not sure where else to report this but browsers are reporting that http://www.sass-lang.com/ has an expired HTTPS certificate. Chrome is currently persuading visitors not to view the site.

![image](https://cloud.githubusercontent.com/assets/1435638/20998797/5962b966-bd60-11e6-8770-49c0c7c024c0.png)

![image](https://cloud.githubusercontent.com/assets/1435638/20998863/a872ed3c-bd60-11e6-8def-115a214bfb5a.png)

**Comment by Laassari** [comment]
I think sass-lang.com has no SSL
![capture](https://cloud.githubusercontent.com/assets/22548931/21000108/d6851ce0-bd10-11e6-98d7-d0d240f16530.JPG)

**Comment by nex3** [comment]
The repository for the Sass website is https://github.com/sass/sass-site.

**Comment by drawcard** [comment]
Looks like the issue has gone away now. Thanks :)
