### ISSUE TITLE
how to write @import absolute path

### ISSUE THREAD

**Issue by dajavu** [sass/sass#2206]

**Comment by nex3** [comment]
Please provide more detail about what you're trying to do, what you've tried, and why the results you've seen don't match what you expect.

**Comment by dajavu** [comment]
![image](https://cloud.githubusercontent.com/assets/16098072/21092968/3fde9500-c08a-11e6-90cb-8cc73152fdd6.png)

Why can't @import "/test/A/A.scss";

**Comment by nex3** [comment]
Is `test` at the root of your file system?

**Comment by dajavu** [comment]
yes，I want sass @import is absolute path

**Comment by nex3** [comment]
Absolute imports work for me. I suspect that you don't actually have the `test` directory in your filesystem root.
