### ISSUE TITLE
one- and two-digit RGB notation

### ISSUE THREAD

**Issue by while0pass** [sass/sass#221]
Maybe it would be usefull that sass could interpret not only standard for CSS 3-digit color RGB notation, but also cope with 1- and 2-digit in the following way:
# F --> #FFFFFF
# FC --> #FCFCFC

**Comment by nex3** [comment]
I don't like diverging from the standard CSS grammar without good reason. I don't think this is clear enough or useful enough to warrant that.

**Comment by while0pass** [comment]
In general, I agree. Nevertheless, sometimes I feel bothered or even a bit frustrated with the fact that there are no shorthand equivalent for some recurring values like #ababab while there is for others like #aabbcc. Of course it is not crutial, espetially due to whole sass :)
