### ISSUE TITLE
Compass sprite_load_path

### ISSUE THREAD

**Issue by DantaliaN00** [sass/sass#2210]
I want set my sprite_load_path as relative to my project subdir (without full path). But I don't see any ways to do that

I compile compass by command-line
`compile --config PATH_TO_CONFIG`

If I set folder structure like this, it's works fine
-- img
--- sprites
---- icon1.png

But I want something like this for my sprites
-- sprites
--- icon1.png

I can't use sprite-img("/../sprites/*.png"), b/c ".." not supported

I need something like
sprite_load_dir

Any possible ways?

**Comment by nex3** [comment]
The repository for Compass is https://github.com/compass/compass. Note however that it's no longer actively maintained, so you may not receive an answer quickly.
