### ISSUE TITLE
Local scope with @content?

### ISSUE THREAD

**Issue by ghost** [sass/sass#2216]
I can use `@content` to work with almost anything in a local scope. For example, I can declare a namespace, `$_`, for my classes (and placeholders):
```scss
@mixin scope { @content; }

@include scope {
  // Namespace
  $_: 'checkbox';

  // Variables
  @import './variables/default';
  @import './variables/user';

  // Partials
  @import './partials/block';
  @import './partials/elements/checkmark';
  @import './partials/elements/input';
  @import './partials/elements/label';
  @import './partials/elements/overlay';
}
```

Any variable, mixin, and placeholder put inside `scope` is inaccessible by the global scope:

Example:
```scss
@mixin scope { @content; }

@include scope {
  $_: 'checkbox';
}

.#{$_}__test {} // Error: undefined variable: "$_". on line 7 at column 1
```

Another example:
```scss
@mixin scope { @content; }

@include scope {
  @mixin scope2 { @content; }
}

@include scope2; // Error: no mixin names scope2
```

Regarding local variables, as long as `$_` is declared within `scope` include, I can re-use `$_` as a namespace for other modules. With "local" imports, I can write exactly what code went into developing any particular module. 

However, this seems to only work when compiling with LibSass and not Ruby Sass. Both CodePen and SassMeister report the following error when using Ruby Sass:
```
Import directives may not be used within control directives or mixins.
```

If I put the same code in SassMeister using LibSass, it will report the following error:
```
File to import not found or unreadable: ./variables/default
Parent style sheet: stdin on line 8 at column 3
```

The code directly above implies that it's acceptable to use the import directive within the included mixin. With LibSass I can declare `@import` and/or `@mixin` using `@content`. I have a [working project](https://github.com/lithiumiron/checkbox) that uses the `scope` mixin.

Is this a bug? Is it something to consider? Let me know your thoughts on this case. Apologies for any confusion....

**Comment by nex3** [comment]
If LibSass is allowing imports in `@include`s, that's a bug. It should match the behavior of Ruby Sass here.

/cc @xzyfer @mgreter
