### ISSUE TITLE
shift_output_offsets shifting the wrong end_pos?

### ISSUE THREAD

**Issue by matthewd** [sass/sass#2221]
Hi!

I was just reading through the source map handling, and noticed [this line](https://github.com/sass/sass/blob/3bde119f7976c64dd93b51feea110f7cacaf2d16/lib/sass/source/map.rb#L59).

I'm probably just confused, but shouldn't that be `if m.output.end_pos.line == 1`?

Sorry if I just wasted your time. 😅 

:heart::heart::heart:

**Comment by nex3** [comment]
Yeah, you're probably right. Want to submit a PR to fix it?

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
