### ISSUE TITLE
Fixnum and Bignum deprecated in Ruby 2.4.0 (released Dec 25, 2016)

### ISSUE THREAD

**Issue by richiethomas** [sass/sass#2222]
In responding to [issue # 2218](https://github.com/sass/sass/issues/2218), I discovered that the [Fixnum and Bignum classes are being deprecated](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/) in this latest release (Dec 25, 2016).

Currently, references to Fixnum generate a warning to the console (see issue #2218).  After grepping for "Fixnum" and "Bignum", I count 72 references to Fixnum and 0 references to Bignum in the Sass codebase.  Should we replace the references to Fixnum with references to Integer, or at least reference both where possible in order to be backwards-compatible?

If so, I'd like take responsibility for fixing this issue.

**Comment by nex3** [comment]
Isn't this already being tracked in #2218?

**Comment by richiethomas** [comment]
#2218 addresses the warning that's issued when the "json_value_of" method is called.  I created a new issue since there are many other references to Fixnum in the codebase, possibly generating warnings elsewhere as well.

**Comment by richiethomas** [comment]
That said, if the fix for #2218 should also address the other references, then yeah there'd be no need for issue #2222 (this issue).
