### ISSUE TITLE
selector inheritance bug in sass

### ISSUE THREAD

**Issue by shiranabbasi** [sass/sass#2225]
**There is a problem in sass compilation. It's the code i wrote:**

.error {
  border: 1px #f00;
  background: #fdd;
}

.error.intrusion {
  background-color: orangered;
}

.badError {
  @extend .error;
  border-width: 3px;
}

      **It should be compiled down to:**

.error, .badError {
  border: 1px #f00;
  background: #fdd; }

.error.intrusion, .badError.intrusion {
  background-color: orangered; }

.badError {
  border-width: 3px; }

       **but what it does is:**

.error, .badError {
  border: 1px #f00;
  background: #fdd; }

.error.intrusion, .intrusion.badError {
  background-color: orangered; }

.badError {
  border-width: 3px; }

Please can anyone help me ?.

**Comment by yo7** [comment]
It looks the difference is what you expect is `.badError.intrusion`, but the result is `.intrusion.badError`, right?

I think these two mean the same. The former means "elements with `.badError` also have `.intrusion`", the latter is "elements with `.intrusion` also have `.badError`. Both result in the same style.

You can refer to [the W3C documentation](https://www.w3.org/TR/css3-selectors/#class-html).

**Comment by nex3** [comment]
@yoostk is right: the actual output and your expected output are semantically identical.

**Comment by shiranabbasi** [comment]
Thanks a lot it really helped me.
