### ISSUE TITLE
Bug with non superselectors being unified

### ISSUE THREAD

**Issue by mgreter** [sass/sass#2229]
I struggle to get some internal libsass compare functions right and stumbled accross the following oddity. To me this looks like a bug, as I expected that only superselectors can be unified.

```scss
test {
  test-01: is-superselector("a", "|a"); // false
  test-02: is-superselector("|a", "a"); // false
  test-03: selector-unify("a", "|a"); // unified
  test-06: is-superselector("|*", "tag"); // false
  test-06: is-superselector("tag", "|*"); // false
  test-06: selector-unify("tag", "|*"); // unified
}
```

```css
test {
  test-01: false;
  test-02: false;
  test-03: |a;
  test-06: false;
  test-06: false;
  test-06: |tag; }
```

Currently libsass uses to_string and a simple string compare at some point. When I change this to use the internal deep compare functions, it breaks either one or another spec test. My current implementation refuses to unify the above examples, since it thinks they are not superselectors of each other (resulting in `tag |tag, |tag tag`). Maybe this is just an oversight, since namespaces are probably very seldomly used this way. But would be great if somebody could clarify to bring some more speed to libsass? Thanks!

**Comment by nex3** [comment]
I believe `is-superselector()` is correct here and `selector-unify()` is wrong. We don't have the context to know whether `a` is the same selector as `|a`, so we should be treating them as different everywhere.
