### ISSUE TITLE
Feature proposal: @delete

### ISSUE THREAD

**Issue by vendramini2017** [sass/sass#2230]
Hey Sass community! How about implement a feature to delete some class before define in another file? In my case, I use Sass of UIkit(CSS/JS framework)and sometimes I want to implement my own version of some class of uk. So I thought to do sometimes like:
----------------
uikit.scss

.uk-hidden{
display:block;
}
-----------------
myfile.scss
@import 'uikit';
@delete .uk-hidden;
.uk-hidden{
visibility: hidden;
}

----------------------
output.css

.uk-hidden{
visibility: hidden;
}

**Comment by vendramini2017** [comment]
sorry for typos, I was typing in cellphone

**Comment by nex3** [comment]
This is something I've considered as part of the upcoming module system. I'm closing this issue out since the module system is being tracked in #1094.
