### ISSUE TITLE
Sass::Logger::Delayed incompatible with non-SASS loggers

### ISSUE THREAD

**Issue by gshutler** [sass/sass#2231]
[`Sass::Logger::Delayed`](https://github.com/sass/sass/blob/0154f6589cd438c0389963416e25340bc55b4358/lib/sass/logger/delayed.rb) has become dependent on the `logger` implementing the [`LogLevel`](https://github.com/sass/sass/blob/0154f6589cd438c0389963416e25340bc55b4358/lib/sass/logger/log_level.rb) protocol.

This dependency was introduced in 3.4.23 by 7866dbcd and doesn't seem avoidable.

**Comment by nex3** [comment]
Sass's logger API was never intended to be compatible with other logger APIs.
