### ISSUE TITLE
Variables with value null !default doesn't win over other variables with the !default flag

### ISSUE THREAD

**Issue by pat270** [sass/sass#2234]
The code below:
```
$color1: null !default;
$color1: red !default;

$color2: null;
$color2: green !default;

.my-element {
    background-color: $color1;
    border-left-color: $color2;
}
```
outputs:
```
.my-element {
    background-color: red;
    border-left-color: green;
}
```

I would expect it to output nothing. See http://www.sassmeister.com/gist/f02c5a9403e7348d20da0b52d3b86c81 for live example.

**Comment by nex3** [comment]
This is intentional. As [the reference](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_) says:

> Variables with `null` values are treated as unassigned by !default

**Comment by pat270** [comment]
@nex3 Thanks for the reference, I didn't realize it was explained there. I was wondering why you decided to treat null variables as unassigned when using the !default flag? Following that definition shouldn't something like:
```
$color: red !default;
$color: null;
.element { color: $color; }
```
output:
```
.element { color: red; }
```
As of now it doesn't output anything since $color is now null. Is the behavior in the first comment something you would consider adding as a feature? I think it fits better with the way !default behaves. The syntax $someVar: null !default; is written like you are assigning a value to a variable. If you wanted to declare a variable without an assignment, perhaps another type of syntax should be used.

**Comment by nex3** [comment]
> I was wondering why you decided to treat null variables as unassigned when using the !default flag?

It matches the behavior of similar operators in other languages (like `||=` in Ruby), and it gives users an explicit way to say "use the default value".

> Following that definition shouldn't something like:
> ```
> $color: red !default;
> $color: null;
> .element { color: $color; }
> ```
> output:
> ```
> .element { color: red; }
> ```

No. `!default` is basically just a shortcut for `if(defined($variable) && $variable != null, $variable, expression)`—the defaultness doesn't stick to the variable going forward.

**Comment by pat270** [comment]
That's too bad. This would be a very nice feature to have. Thanks for clarifying it.
