### ISSUE TITLE
Sass incorrectly interprets native CSS mixins as nested rules

### ISSUE THREAD

**Issue by tony19** [sass/sass#2235]
Sass is [converting](http://www.sassmeister.com/gist/a25f5615b0201e89a048dd8987262cfe) this [native CSS mixin](https://blog.hospodarets.com/css_apply_rule) (`--view1-card`):

    // my-view1.scss
    $color: #f00;
    my-view1 {
      --view1-card: {
        border: solid 1px #{$color};
        opacity: 0.5;
      };
    }

into:

    // my-view1.css
    my-view1 {
      --view1-card-border: solid 1px #f00;
      --view1-card-opacity: 0.5;
    }

...which is incorrect. The native mixin declaration should've been passed through like this:

    // my-view1.css
    my-view1 {
      --view1-card: {
        border: solid 1px #f00;
        opacity: 0.5;
      };
    }

According to the blog notes for Sass 3.5, Sass *should* support native CSS mixins as shown above, but that is not the case. The same behavior occurs in Sass 4.0.0-alpha1.
![screen shot 2017-02-01 at 1 32 33 am](https://cloud.githubusercontent.com/assets/26580/22498491/5d98d766-e81e-11e6-969d-0098c29c0226.png)

### Environment

 * node 7.4.0
 * [`gulp-sass`](https://www.npmjs.com/package/gulp-sass) 3.1.0 (uses `node-sass` 4.5.0)
 * macOS Sierra 10.12

**Comment by tony19** [comment]
**Workaround:** To prevent the unwanted conversion, I'm using Sass string interpolation `#{'...'}`:

    // my-view1.scss
    my-view1 {
      --view1-card: #{'{
        border: solid 1px blue;
        opacity: 0.5;
      }'};
    }

But this defeats the IDE's IntelliSense and syntax highlighting. What are my alternatives that wouldn't require stuffing the CSS mixin in a string?

**Comment by tony19** [comment]
Interestingly, `dart-sass` 1.0.0-alpha.8 works properly.

**Comment by nex3** [comment]
This is the repository for Ruby Sass. You're using Node Sass, based on LibSass, which lives at https://github.com/sass/libsass.

**Comment by xzyfer** [comment]
@tony19 can you confirm the output is broken in the Ruby Sass 3.5. RC and Sass 4.0.0-alpha1?

**Comment by tony19** [comment]
@xzyfer <del>Only</del> Sass 3.5 RC <ins>and 4.0.0-alpha.1.edec1af</ins> (and `dart-sass`) produce the correct output.

 * `3.4.23` ❌ 
```css
my-view1 {
  --view1-card-border: solid 1px #f00;
  --view1-card-opacity: 0.5; }
```

 * `3.5.0-rc.1.3983be8`  ✅ 
```css
my-view1 {
  --view1-card: {
    border: solid 1px #f00;
    opacity: 0.5;
  }; }
```

 * `4.0.0.alpha.1.af6c039` ❌ 
```css
my-view1 {
  --view1-card-border: solid 1px #f00;
  --view1-card-opacity: 0.5; }
```

 * <ins>`4.0.0-alpha.1.edec1af` ✅ 
```css
my-view1 {
  --view1-card: {
    border: solid 1px #f00;
    opacity: 0.5;
  }; }
```
</ins>

**Comment by xzyfer** [comment]
Thanks @tony19. My guess the 4.0 failure is just because the latest updates haven't been merged into that branch.

As for node-sass we have an issue for this in https://github.com/sass/libsass/issues/2076

**Comment by nex3** [comment]
4.0.0.alpha.1 is outdated; you'll need to use the master branch for the latest 4.0 features.

**Comment by tony19** [comment]
Ok, indeed. The master branch also works properly. Updated comment above.
