### ISSUE TITLE
@info as new logging option

### ISSUE THREAD

**Issue by DaSchTour** [sass/sass#2236]
I somehow have the feeling that there is something missing between `@warn` and `@debug`. For example for the case that is used in foundation-sites framework, that developers are notified of bad contrast values. I would like to add this as an information and not as a warning. Warnings often irritate inexperienced developers. Such errors on the one hand lead to confusion and make some developers fell uncomfortable and on the other hand it may lead to overlook more important warning. So this additional log level would help to create a better differentiation between such "warnings".

**Comment by nex3** [comment]
How would `@info` behave differently than `@warn`?

**Comment by DaSchTour** [comment]
It would be displayed at other log levels.

**Comment by nex3** [comment]
The Sass language has no conception of a "log level".

**Comment by DaSchTour** [comment]
@nex3 well than it should have. There are a lot of issues caused by missing concept for log levels. Because there is some kind of "log level" with `@error` `@warn` and `@debug` but there is not concept for it.

**Comment by nex3** [comment]
Adding a concept of log levels would add a large amount of complexity that's only useful for a small number of users. It's also easy to handle yourself with a mixin:

```scss
$print-info: false;

@mixin info($message) {
  @if $print-info {@warn $message}
}
```

**Comment by DaSchTour** [comment]
@nex3 well, looks like a nice idea. How do I manage to control this on a CI level? How can I change the variable depending on if the build is done locally or on CI server?

**Comment by nex3** [comment]
One way would be to define a custom function in your host language that reports the surrounding environment.

**Comment by DaSchTour** [comment]
Okay, and than I'll have to add the same function to all framework I use? The point Iwanted to make is, that sass isn't very supportiv for creating liberaries. If I do all my sass on my own, this would perfectly work. But if I want to create css frameworks and libraries and every library implements it's own way of giving users the possibiliy to handle errors and logging or maybe doesn't implement it it's going to be a total mess. I thought that sass could be or grow to more than just a pimped CSS. I would love to use sass for creating libraries that supports developers in their development. But without a proper log leveling I don't see any chance to support developers with fine grained information while not bothering them with to much overhead if not needed. You really don't get what's so complex about log levels. There is already so kind of messaging with debug, warn and error. Just creat function for logging, add the level and pass it to the output. Logging and log levels is the most simple and most basic function of every programming language. Every developer knows it and is used to it. And the worst about scss is, that it gives the impression, that there is something like log levels, by adding debug, warn and error, but in fact it's just some strange undeterminable output that is generated from this functions which is handle or not handle in other ways by every sass implementation.
