### ISSUE TITLE
Concatenation results in unrecognised character

### ISSUE THREAD

**Issue by nickdunn** [sass/sass#2238]
When concatenating two characters together, *some* combinations result in unrecognised characters being output.

The following test case is a real-world case where I want to append a non-breaking space (\feff) to another character that is used in an icon font.

    $char-f: '\66';
    $char-g: '\67';

    .test-1 {
      content: '#{$char-f}\feff';
    }

    .test-2 {
      content: '#{$char-g}\feff';
    }

    // this is broken
    .test-3 {
      content: '\feff#{$char-f}';
    }

    .test-4 {
      content: '\feff#{$char-g}';
    }

Output:

    @charset "UTF-8";
    .test-1 {
      content: "f﻿";
    }

    .test-2 {
      content: "g﻿";
    }

    .test-3 {
      content: "󾿿";
    }

    .test-4 {
      content: "﻿g";
    }

(Note that \feff is present in 3 of the 4 examples, but it's invisible).

When \feff is concatenated with \66 a single unrecognised character is returned rather than two.

I've been able to replicate this with the https://github.com/sass/node-sass wrapper, as well as pasting the above into http://sass.js.org.

**Comment by nex3** [comment]
This is the repo for the Ruby implementation of Sass. You're using LibSass, the C impementation. Please re-file this issue on [the LibSass issue tracker](https://github.com/sass/libsass/issues/new).
