### ISSUE TITLE
pass variables or constants to imported files

### ISSUE THREAD

**Issue by radiovisual** [sass/sass#2240]
If I have a file `styles.scss` that looks like this:

```
$red: #fd0002;
@import 'Foo';
```

and in `Foo.scss`:

```
Foo {
  color: $red;
}
```

it would naturally result in the following error:

<pre>
Error in plugin 'sass'
Message:
    sass/Foo.scss
Error: Undefined variable: "$red".
        on line 123 of sass/Foo.scss
>>   color: $red;
   ---------^
</pre>

I understand the reason for the error, but because SASS simply combines all of your imported files into one file (to reduce HTTP requests), it would be awesome if your imported files had access to constant values that you want to make "globally accessible" to your CSS modules. 

I just want to write some constants that I know will not change anywhere in my project, and let all of my SASS modules have access to these same constants. **Perhaps there is already an established best practice for this?** Or a way to pass specific variables to an imported module?

I can imagine something like you would do when passing variables to imported templates in templating engines:

```scss
// Import Foo (and let Foo.scss use the $red and $blue variables) 
@import 'Foo' ($red, $blue);
``` 

Or something like:

```scss
@import 'Constants' as $constants;
@import 'Foo' ($constants);
```

Or:

```scss
@import 'Constants' as global;
@import 'Foo'; // Foo now has access to global constants
```

Any ideas?

**Comment by mprins** [comment]
Put constants in a partial and import that.

I do it like this: https://github.com/GeoDienstenCentrum/sass-maven-plugin/tree/sass-maven-plugin-2.22/src/test/projects/maven-bourbon-test/src/main/sass

**Comment by radiovisual** [comment]
Thanks @mprins.

I have solved the problem in the following way:

I define a `Constants.scss` file with all of my Constants, and at the top of each module that uses the constants, a simple `@import` does the trick:

In `Constants.scss`:
```scss
$red: #fd0002;
```

In `Foo.scss`:
```scss
@import 'Constants';

Foo {
  color: $red;
}
```

I think I was overthinking the problem. So I will close this issue. If someone feels I am really onto something here, then feel free to reopen. 😄
