### ISSUE TITLE
(Sass <4) "Invalid CSS" error when using more than 3 interpolated exprs in statement

### ISSUE THREAD

**Issue by traviskaufman** [sass/sass#2241]
**Repro**: http://www.sassmeister.com/gist/088ea8e72c8ce5cf0d1e737bba98f420

When using the expression:

```scss
#{$mdc-elevation-property}:
    #{map-get($mdc-elevation-umbra-map, $z-value)} $mdc-elevation-umbra-color,
    #{map-get($mdc-elevation-penumbra-map, $z-value)} $mdc-elevation-penumbra-color,
    #{map-get($mdc-elevation-ambient-map, $z-value)} $mdc-elevation-ambient-color;
```

Ruby-Sass v3.4.21 fails to compile, printing the following error:

```
Invalid CSS after "...-penumbra-color": expected ";", was ","
```

The same error occurs in Ruby-Sass v3.3.x - http://www.sassmeister.com/gist/41aa6afa0e1d70187d9630e594028656

---

When the last line of that above statement is removed, e.g.

```scss
#{$mdc-elevation-property}:
    #{map-get($mdc-elevation-umbra-map, $z-value)} $mdc-elevation-umbra-color,
    #{map-get($mdc-elevation-penumbra-map, $z-value)} $mdc-elevation-penumbra-color;
```

It compiles correctly for both 3.3.x and 3.4.x

---

When using Sass v4 alpha or LibSass, it compiles correctly as-is:

- http://www.sassmeister.com/gist/1bcd1ed795806f5a4c3d4f8c8e1c2edc
- http://www.sassmeister.com/gist/58078f6fec315da378886c31956d6748

I'm not sure why exactly this would be happening, but any insight would be appreciated. Please let me know if you need anything else to help diagnose. Thanks!

p.s. Apologies for the strange issue title, but I'm not exactly sure _why_ this is happening; it's just that after I remove a certain number of interpolated exprs, it seems to compile. 🤷‍♂️

**Comment by nex3** [comment]
This is presumably caused by the old and strange interpolation semantics (see [this blog post](http://blog.sass-lang.com/posts/308328-cleaning-up-interpolation) for details). I don't think there's much we can change about it without risking backwards-incompatibility.

Fortunately, for your code in particular, the interpolation is totally unnecessary. You can just include function calls directly in lists:

```scss
#{$mdc-elevation-property}:
    map-get($mdc-elevation-umbra-map, $z-value) $mdc-elevation-umbra-color,
    map-get($mdc-elevation-penumbra-map, $z-value) $mdc-elevation-penumbra-color,
    map-get($mdc-elevation-ambient-map, $z-value) $mdc-elevation-ambient-color;
```
