### ISSUE TITLE
Deprecate old-style property syntax

### ISSUE THREAD

**Issue by nex3** [sass/sass#2245]
The old property syntax looks janky and we don't intend to support it in Dart Sass, so we should deprecate it here.

Tasks:

- [x] Deprecate existing behavior in `stable`.
- [x] Remove behavior from `master`.

**Comment by ArmorDarks** [comment]
Do you mean [those](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties)?

**Comment by nex3** [comment]
No, I mean

```sass
.foo
  :color blue
```
