### ISSUE TITLE
Math operator as a variable value

### ISSUE THREAD

**Issue by NicolasGraph** [sass/sass#2248]
Hi,
Is there a way to store a math operator in a variable and use this variable for calculation?
Thanks!

**Comment by nex3** [comment]
It's fairly verbose, but you can do this by defining a custom function:

```scss
@function plus($number1, $number2) {
  @return $number1 + $number2;
}

$operation: get-function("plus");
@debug call($operation, 1, 2); // prints 3
``` 

(Note that `get-function` only works in Sass 3.5, which is currently a release candidate rather than a full release).

**Comment by NicolasGraph** [comment]
Thanks @nex3, I can use something less flexible for now but your tip is good to know!
