### ISSUE TITLE
Using native CSS variables in color functions doesn't work

### ISSUE THREAD

**Issue by pgrantmartello** [sass/sass#2249]
:root { --color: red; }

    body { background-color: mix(var(--color), white, 50%) }

I feel like the above code snippet should compile, but it doesn't.

**Comment by davidkpiano** [comment]
That's because there's no way to statically determine the value of `var(--color)` before runtime.

That is, if I do this:
```js
document.documentElement.style.setProperty('--color', 'blue');
```

then the body's background-color would be different.

**Comment by pgrantmartello** [comment]
Yeah, that makes sense. It's unfortunate. I still feel like maybe there should be some caveated ways in which this might work (like the above example), but I hear what you're saying. Valid point! thanks.
