### ISSUE TITLE
issue with @import and nested rules together

### ISSUE THREAD

**Issue by b3rimbau** [sass/sass#225]
```
>sass --ver
Sass 3.1.11 (Brainy Betty)
```

Here's my test case:

My variable is imported from test-import.scss, whose only contents is:

```
$column-spacing: 12px;
```

My SASS file is test.scss, whose contents are:

```
@import "test-import.scss";

.outer {
    margin-left: $column-spacing;

    .inner {
        color: red;
  }
}
```

This compiles ot test.css, whose contents are:

```
.outer {
  margin-left: 12px; }
```

If I change test.scss by changing margin-left to margin, then I get the expected result:

```
.outer {
  margin: 12px; }
  .outer .inner {
    color: red; }
```

If I've made a stupid mistake, sorry.

**Comment by nex3** [comment]
I can't reproduce this. Can you create a repo with files that reproduce and link it here?

**Comment by nex3** [comment]
Closing.
