### ISSUE TITLE
CSS fragments and other data

### ISSUE THREAD

**Issue by ArmorDarks** [sass/sass#2252]
I drew some ideas from Clojure and how everything in it reassembled by simple data structures. So I tried to apply those knowledges to Sass, and, if possible, simplify already existing in Sass concept — maps, tighten up already existing Sass syntax closer to its origins, CSS, and by the way make work with CSS fragments not only reality, but intuitive and simple thing.

This issue takes a long jump, makes big claims and tries to solve few issues at once, so, first of all, calm down and buckle up tight.

In short, __this issue is about defining CSS fragments and other structural data in a better (or alternative) way__.

Disclaimer: some things might be broken or incomplete overlooked or oversighted. Some might hurt your feelings.

To be honest, I hesitated a lot to publish this or no... But here it goes.

## Goals

1. Unify existing in Sass data structures with already existing ones in CSS. In some sense, to redefine boundaries between those two.
2. Make basement for solving https://github.com/sass/sass/issues/1582 and similar issues.
3. Make work with CSS fragments easy and intuitive.
4. Make work with CSS fragments powerful.
5. Define format, which should expressively describe CSS fragments.
6. Define format, which should be easy to write and easy to understand for end-user.
7. Define format, which should be easily accessible.
8. Define format, which should be easy to manipulate.
9. Define format, which should provide easy introspection.
10. Define format, which should not introduce radically new syntax to CSS.

## The road

For this part, I will need your imagination. Stay tuned; do not think about unimportant parts rights now. (Yeap, literally just ignore all my mistakes and take it as granted *makes Jedi movement with his hand*).

Let us imagine that we could build whatever we want and any way we want.

And, as first part of this ugly plan, let's imagine new Object, which we can use as an alternative to maps:

``` sass
$myVar: {
  prop1: some value;
  prop2: #fff;
  nested: {
    prop3: 123;
  };
};
```

Note curly brackets `{}` and `;` instead of usual for maps `()` and `,`. This syntactically makes Objects very similar to CSS, but from other side seems to do same thing as usual Sass map. As a side benefit, `;` seems to be more logical for last element in Object then trailing comma in Sass maps.

Object properties can be easily accessible. I will use for now and in future JavaScript syntax, since it have necessary means to make what we want to do here, but for now just imagine like you are reading warm and cozy Sass with some extensions:

```js
$myVar.prop1 \\ -> contains `some value`
$myVar.nested.prop3 \\ -> contains 123
```

It is possible, because on contrary to maps, Object are simpler data structures and they can't contain as Object keys _any_ value, but only strings or numbers literals. Let's leave maps to more complex scenarios.

For now, all of this seems to be completely irrelevant. You can tell, that this just a representation of data, another version of Sass map, and this doesn't do anything with CSS fragments. Indeed, you are right. We can use those exactly as typical data structures. But there is a catch.

Let's say, we want to add in this Object a bit of CSS:

``` sass
$myVar: {
  prop1: some value;
  prop2: #fff;
  nested: {
    prop3: 123;
  };

  .article h1,
  .article h2 {
    border-width: 1px;
    border-color: red;
  }
};
```

Yes, it just that easy for end-user to write it. We just made a colossal thing, for which many Sass framework developers would kill, since before they were forced to find most odd ways to describe CSS in their data structures as Sass map.

But here we're doing exactly the thing — giving them ability to write CSS just as a part of their data structure with clear and familiar syntax.

This opens a hatch for a lot of creativity, since from now CSS parts can be stored in variables, in Sass maps, passed from one variable to another, manipulated an so on.

Selectors are harder to access directly, but it seems to me reasonable. Think of jQuery — you need to write full selector if you want to access properties directly.

Same thing we have here:

```js
$myVar[.article h1, .article h2] \\ will return its data
```

I think additional external tools can eliminate this issue. Like a jQuery for Sass, which will provide even better ways to access Object properties based on queries. We just need to provide basement for such tools.

Of course, things not that easy under the hood. In fact, while `props` are normal part of data structure, usual Object properties, `.article h1, .article h2` is a _syntax sugar_. Same as we have for [methods declaration of Classes in ES2016](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes). Under the hood, it transforms into more usual and introspective data structure, which I will describe later.

So, let's take a look at structure which we have in result:

``` sass
$myVar: {
  prop1: some value;
  prop2: #fff;
  nested: {
    prop3: 123;
  };

  .article h1,
  .article h2 {
    border-width: 1px;
    border-color: red;
  }

  aside {
    .tagline {
      color: grey;
    }
  }
};
```

Some might say — wait, but this is nothing new! We already have this thing, and it’s called CSS. That's the whole point. My proposal is about embracing and extending already known to CSS concept. CSS already have data structure, which CSS represents itself, and I do not see reasons why we should not embrace it.

It is very powerful abstraction, which will eliminate a lot of issues Sass frameworks developers facing those days, especially when they end up mapping properties of CSS to Sass maps, and then generate something based on them (let's say, themes). With current Sass capabilities we are encouraging strange practice to mimic one data structure (CSS) with another (Sass map), while we could just use first one directly, thus eliminating undesired additional layer of complication.

In the end of the day, we can use those objects for many things:

1. To compose new selectors based on Object or other data structures.

   Generating new selectors is easy, because you can just iterate upon Object and output all selectors as... selectors.

2. To compose new data based on different Objects

   ```sass
   $myObj1: { color: red; }
   $myObj2: { h1 { background: blue; } }

   // some pseudo-code
   $result: merge($myObj1. $myObj2)
   ```

   `$result` will contain

   ```sass
   {
    color: red;

    h1 { background: blue; }
   }
   ```

3. Since it is a data structure, it can be "mutated" by accessing and changing it's properties and values:

   ```sass
   $myObj: {
    color: red;

    &.is-active { color: black; }
   }

   $myObj.border-width: 1px;
   $myObj[&.is-active].background: dark-as-my-soul;
   ```

   This will reshape fragment into

   ```
   {
    color: red;
    border-width: 1px;

    &.is-active {
      background: dark-as-my-soul;
      color: black;
    }
   }
   ```

4. To use it as a form of mixin:

   ```sass
   $myObj: {
    color: red;

    &.is-active { color: black; }
   }

   .myClass {
    border: 1px solid green;
    $myObj
   }

   .anotherClass $myObj
   ```

   will yield

   ```sass
   .myClass {
    border: 1px solid green;
    color: red;

    &.is-active { color: black; }
   }

   .anotherClass {
     color: red;

     &.is-active { color: black; }
   }
   ```

   Syntax is debatable, but I can see it demonstrates the point.

5. To use it as a closer to CSS alternative to maps.

   Objects provide a way to store usual, not related to CSS fragments, data with more accessible way. Since it isn't that broad as maps, it's easier to access with dot notation and make any manipulations based on it.

   ```sass
   $myObj: {
    selector: .test
    value: red
   };
   
   article #{#myObj.selector} {
    color: $myObj.value
   }
   ```

6. Since it is usual CSS (or more to say — Sass), you can use any expected Sass features inside Objects, like other mixins, functions, concatenation with `#{}`, etc.

   ```sass
   $myObj = {
    body {
      @include mysterious-mixin();
    }
   }
   ```

7. Think about your ways. It will be your homeworks. My fantasy is quite limited.

Some might raise few questions here:

1. What if Object contains unknown to CSS properties and we will try to mix it into real selector, like

   ```sass
   $myObj: {
     invalidProp: red
   }

   aside { $myObj }
   ```

   Answer: it will output all properties, which you're passing it, resulting in

   ``` sass
   aside { invalidProp: red }
   ```

   Sass is not validator of CSS properties, so what you are passing in you are getting out. We should understand that in this proposal Object is broader than CSS fragment. __It is extension of CSS data structure__, which allows you to store any data you want, not only CSS values, and it is up to you where you will use it — as part of CSS, or as a storage in you framework. Yes, literally it blurs edges between regular CSS and data, and it is good thing.

   If we think about it, whole CSS file can represent large Object, in which you can easily access any selector and it's values without need to define additional variables.

2. To some people syntax of declaring selectors might look like odd thing.

   Indeed, we are using `:` for keywords (typically for Object/dict structures in many languages), but selectors suddenly do not use any colons.

   First, we should think about it as granted: CSS _already has this syntax_. And secondly, it might be unexpected syntax unless Lisp or [Clojure](https://kimh.github.io/clojure-by-example/#let) languages will run somewhere nearby — they have very similar syntax, and it is quite effective, in fact.

Well, it might be slightly unobvious, but described above approaches solves (I hope so) most of estimated goals: it is easy to write, it is easy to read, it is a simple data structure, easy to manipulate, and it does not introduce new syntax to CSS.

However, we are still not done. In https://github.com/sass/sass/issues/1582 was mentioned important thing — those data structures should be __introspectable__. And because of this, CSS fragments can't be represented as a primitive data structure — it will be very uneasy to distinguish selectors or at-rules from typical properties. Thus, any CSS fragment should under hood turn into real data. That's why I said at first that any selectors or at rules in Object are just a syntax sugar, which in reality turning out to understandable and mutable data structures under the hood.

## Internal structure

Here https://github.com/sass/sass/issues/1582#issuecomment-72259831 @chriseppstein and @eoneill proposes their own vision.

Obvious benefit of that structure is that it's very descriptive. It seems to get everything right.

However, there are few issues:

1. It has very uneasy cognitive model. It's really hard to read.
2. It seems to be mostly inaccessible with normal tools. This means, that you should write funky Sass, or introduce new to Sass functions, like mentioned `ruleset()` or `at-rule()`, to help with this complexions. Usually this is a bad sign.
3. Because of previous issue, it is easy to declare manually or mutate.

I took some inspiration from [JSON Schema draft](http://json-schema.org/examples.html) and [tcomb](https://github.com/gcanti/tcomb) internals.

I will use for this example JavaScript Object, because, sorry, but `()` and `()` (you see the difference? I don't too) for arrays and maps makes any example magnificently and incredibly unreadable.

So let's take example in mentioned comment, and put it in our lands first:

```sass
$myObj: {
  .foo, .bar {
    color: red;
    color: rgba(255, 0, 0, 0.5);
  }
  /* This is a comment about the media block that follows. */
  @media (max-device-width: 400px) {
    /* A comment inside the media block. */
    aside#sidebar { width: 100%; }
  }
};
```

And imagine we log out our object to console (don't ask me how, I don't know, I don't want to hear anything about Sass is a compiled language it doesn't log anything to console STOP! Calm down! Let's continue):

```js
log($myObj)
```

We will see following data structure:

``` js
{
  '.foo, .bar' {
    meta: {
      type: 'selector',
      selectors: ['.foo', '.bar']
    }

    'color': 'red',
    'color': 'rgba(255, 0, 0, 0.5)'
  },

  '/* This is a comment about the media block that follows. */': {
    meta: {
      type: 'comment'
    }
  }

  '@media (max-device-width: 400px)': {
    meta: {
      type: 'at-rule'
      at-rule: 'media'
      value: 'max-device-width: 400px'
    },

    '/* A comment inside the media block. */': {
      meta: {
        type: 'comment'
      },

      'aside#sidebar' {
        meta: {
          type: 'selector',
          selectors: ['aside', '#sidebar']
        }

        'width': 100%
      }
    }
  }
}
```

This structure is:

1. Much easier to read — it is same cascade as we already have in CSS.
2. It is easy to access properties, since no tricky routing needed — all values available in plain form, with straightforward paths.
3. Types and other meta information of keywords is easy to introspect — everything available under `meta` property. Note, that current proposed meta might be not full, it's just an proposal of format, not features.
4. Since it is easy to access internals, it is also easy to change. You can access and redefine any value with dot notation or already existing Sass tools without funky paths.
5. This construction is easy to write or generate — for cases when we want to declare it manually, in form of pure data structure.
6. Since it has easy structure, we do not need additional Sass function to decrease pain during defining or manipulation. We just do not have this pain at first place.
7. Think about some other benefits. Those seems to be unimpressive, and I'm afraid that maintainers will instantly close this issue (but don't tell them about this one!).

Unfortunately, not everything perfect, and my proposal have few obvious fatal flaws too:

1. Properties or selectors, at rules, comments can occur few times. You can see it with `color` property. Indeed, in most cases, data structures does not allow anything with duplication of keywoards (which is `color` in our case).

   At least, this will demonstrate to some folks why @chriseppstein and @eoneill opted to use so hard-to-read-list-based notation in their [example](https://github.com/sass/sass/issues/1582#issuecomment-72259831).

   To be honest, so far I don't see clear solution to this issue. However, from other point of view, CSS object structure allows having multiple properties with same keywoard. So, maybe we should allow it too. But, while I'm typing it, I'm feeling how other language pointing a gun to my head and sign with cardinal sin starts to flash on my screen. Nevertheless, maybe it is just a signature of unique CSS nature?

3. Anyway, EVEN if we do allow duplication of properties in Object, there still will be serious issue — how to access that second or first property? Introduce some weird syntax? Like `$myObj[.foo, .bar].color[0]` for first occurrence and `$myObj[.foo, .bar].color[1]`?

Probably they solvable, probably not. Maybe we can put all duplicated properties into another array:

```js
{
  '.foo, .bar' {
    meta: {
      type: 'selector',
      selectors: ['.foo', '.bar']
      discardedDuplicatedProperties: [
        { 'color': 'red' }
      ]
    }

    'color': 'rgba(255, 0, 0, 0.5)'
  }
}
```

Which might be not worst idea, since in most cases we would want to filter them out anyway, but still it looks like a complication.

Anyway, my point here is that this structure should be as easy as possible, and described above model is what I, and I believe, many other Sass developers would like to see. I mean, the direction, to this. So it be like an object. You know, without lists, easy to read. With a nesting, and some nice metas. Ah, whatever, I think you have understood what I mean!

## Outro

I feel that there will be especially a lot of criticism about my attempt to unify CSS with data structures, which to some people might look like so different. The thing is, for me CSS selectors always felt like a typical language object or dict, but with slightly different syntax. I think that by embracing and extending them we will make Sass ~~great again~~ easier (since there will be less concepts to learn) and will introduce a lot of new possibilities (because of impossible before data manipulations and combinations).

Even if this whole concept will fail with loudest sounds of falling down on a peaceful tourist tree, I still hope that it will serve as a basement for some new, even better features.

I also sincerely hope that I was able to deliver at least piece of my vision. If I didn't — don't blame me, just read issue few times again!

Just kidding... Thanks for reading!

**Comment by chriseppstein** [comment]
So I didn't read all of this because I'm hung up at something pretty fundamental in CSS that seems to be missing at the beginning that I feel much of the design here hangs on: css has multi-valued keys.

The classic case for this is progressive enhancement:

```css
.foo {
  color: #fff; // fallback to white on old browsers, new browsers are overridden by the next line.
  color: some-new-fangled-color-fn(arg1); // fails to be parsed on old browsers, is discarded.
}
```

As such, access to the value of `color` in this data-structure is inherently more complicated than a map and not just because of the non-string key aspect.

I am very interested in increasing the homoiconicity of Sass data structures so this concept is interesting to me but I'd like to see you revisit the design and have it take multi-valued keys into account before giving the rest of it my full attention.

**Comment by nex3** [comment]
Duplicate of #1582

**Comment by ArmorDarks** [comment]
It wasn't exactly a duplicate, but anyway I wasn't happy with solutions I've come up with for described above obstacles and limitation.
