### ISSUE TITLE
Nested mixin issue

### ISSUE THREAD

**Issue by anaelbe** [sass/sass#2253]
Hello,

When i tried to compile a nested mixin one step too far, i got a segmentation error

```
&__logo
    width: 10.4rem
    border: 1px solid $color-border-grey
    border-radius: .6rem
    text-align: center

      +media-query('<',large)
        margin-left: auto
        margin-right: auto
```

and here is the mixin 

```
=media-query($type, $size)
  $media-types: ( '<' : 'max-width', '>' : 'min-width' )
  $type: map-get($media-types, $type)
  $size: map-get($breakpoints, $size)

  @if $type and $size
    @media only screen and ($type: $size)
      @content
  @else
    @content
```

It is not supposed to work, but maybe catchin the error would be useful

**Comment by chriseppstein** [comment]
Two things:

1. There are undefined variables in this code. please boil this down to a simple 1 file example that fails on ruby sass without any external dependencies.

2. Ruby sass doesn't generally get segmentation faults... that's probably a node-sass or libsass issue. After boiling this issue down, it's probably best to file it against the appropriate repo.

I'm closing for now.
