### ISSUE TITLE
@import file without parsing

### ISSUE THREAD

**Issue by khoan** [sass/sass#2256]
currently, I'd like to achieve:

```
$ cat style.scss
.dynamic-stuff {
  @import 'bam';
}
$ cat bam.scss
  color: brown;
```

Naturally, Sass is spewing `Sass::SyntaxError: Invalid CSS after color: brown expected {, was ;`

**Comment by chriseppstein** [comment]
The imported file must be valid syntax in stand-alone format. properties are not supported at the top level of a stylesheet.

The solution here is two write `bam.scss` so that it starts with a selector:

```scss
& {
  color: brown;
}
```
