### ISSUE TITLE
Sass complie css file in same dir of .scss, even with custom ouput path

### ISSUE THREAD

**Issue by dehghani-mehdi** [sass/sass#2257]
Hello,

I'm using Windows 10 x64 latest version, also just installed `Ruby 22 x64` & `Sass`.
After adding `Sass` to `PATH`, tired to compile `scss` file using `sass` as follow:

`sass --watch sass static/css/ --style compressed` (notice that I have sass folder in root of my project, contains main.scss, also have static folder, contains css folder & I want to sass generate .css file inside this folder), but .css file generate twice, one in sass folder, another to css folder (as expected), how to prevent generate css file in sass folder?

Thank you!

**Comment by chriseppstein** [comment]
The output directory is specified by separating by a colon when using `--update` or `--watch`.

`$sass --watch sass:static/css/ --style compressed`

**Comment by dehghani-mehdi** [comment]
@chriseppstein I tired that before reporting this issue, do you closing other issues like this?
