### ISSUE TITLE
Sass complie css file in same dir of .scss, even with custom ouput path

### ISSUE THREAD

**Issue by dehghani-mehdi** [sass/sass#2258]
As other issue closed even before fixing, I reported this issue again!

I'm using `Windows 10 x64 latest version`, also just installed `Ruby 22 x64` & `Sass`.
After adding Sass to PATH, tired to compile scss file using sass as follow:

`sass --watch sass static/css/ --style compressed` also `sass --watch sass:static/css/ --style compressed` (notice that I have sass folder in root of my project, contains main.scss, also have static folder, contains css folder & I want to sass generate .css file inside this folder), but .css file generate twice, one in sass folder, another to css folder (as expected), how to prevent generate css file in sass folder?

**Comment by chriseppstein** [comment]
You're missing the colon between the input and output directories.

**Comment by dehghani-mehdi** [comment]
@chriseppstein Are you kidding me? I already answered this in prev reported issue, I tired that with colon too. also I mentioned here!
