### ISSUE TITLE
gulp-sass not working on windows 7

### ISSUE THREAD

**Issue by JohnSmithers23** [sass/sass#2260]
Struggling to find an answer to this.

I am also very new to the whole gulp/sass/node thing. The answers in here for other relatively similar issues are at the edge of my capacity to be honest. Would really like to get off this base though. Any help appreciated very much.

First up all my versions; followed by my install sequence and messages; third a test to see if sass is there.

Thanks (see below)

$ node -v
v7.7.2

$ gulp -v
[22:53:11] CLI version 3.9.1
[22:53:11] Local version 3.9.1

$ npm -v
4.3.0

When I try to install gulp-sass:
$ npm install gulp-sass
wpinitiation@1.0.0 C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev
`-- gulp-sass@3.1.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\deprecated\package.json'
npm WARN wpinitiation@1.0.0 No repository field.

and when I test to see if its there:
$ sass -v
bash: sass: command not found

**Comment by chriseppstein** [comment]
The issue you posted at https://github.com/dlmanning/gulp-sass/issues/596 is sufficient. If there's a bug in Sass that they discover, we'll need steps to reproduce independent of other tooling.
