### ISSUE TITLE
Sass use transition: transform

### ISSUE THREAD

**Issue by huzedong2015** [sass/sass#2263]
# Sass
// prefix list
$prefix: -webkit- "";

// transition
@mixin transition($value) {
    @each $val in $prefix {
        #{$val}transition: if($value == transform, $val + $value, $value);
    }
}

# Use
body {
  @include transition(transform .4s);
}

# Result
body {
  -webkit-transition: transform 0.4s;
  transition: transform 0.4s;
}

# Want result
body {
  -webkit-transition: **-webkit-transform** 0.4s;
  transition: transform 0.4s;
}

_This is also true if using “compass/css3”;_

@nex3      sos

**Comment by chriseppstein** [comment]
`$value` is a list consisting of two values `transform` and `.4s` so `$value == transform` always evaluates to false. You'll need to check whether `nth($value, 1) == transform`

**Comment by huzedong2015** [comment]
@chriseppstein  Initially no sass found "nth", "indexOf" function, but later used the "autoPrefixer"
