### ISSUE TITLE
Selectors are not supported in ::slotted()

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#2266]
This is a valid CSS used with Web Components v1:
```scss
::slotted(input:active) {
}
::slotted(input[disabled]) {
}
```

It should compile to the same:
```css
::slotted(input:active) {
}
::slotted(input[disabled]) {
}
```

Instead, I'm getting:
```
$ scss --style compressed --no-cache --trace --sourcemap=none style.scss:style.css
style.scss:1: Invalid CSS after "::slotted(input": expected ")", was ":active)" (Sass::SyntaxError)
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1207:in `expected'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1137:in `expected'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1132:in `tok!'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/static_parser.rb:288:in `pseudo'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/static_parser.rb:153:in `simple_selector_sequence'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/static_parser.rb:111:in `selector'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/static_parser.rb:86:in `selector_comma_sequence'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1115:in `expr!'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/scss/static_parser.rb:20:in `parse_selector'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:427:in `visit_rule'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:160:in `block in visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/stack.rb:79:in `block in with_base'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/stack.rb:115:in `with_frame'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/stack.rb:79:in `with_base'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:160:in `visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:52:in `map'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:169:in `block in visit_children'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:181:in `with_environment'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:168:in `visit_children'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:188:in `visit_root'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:159:in `visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/visitors/perform.rb:8:in `visit'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/tree/root_node.rb:20:in `render'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/engine.rb:281:in `render'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/exec/sass_scss.rb:400:in `run'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/exec/sass_scss.rb:63:in `process_result'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/exec/base.rb:52:in `parse'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/lib/sass/exec/base.rb:19:in `parse!'
	from /var/lib/gems/2.3.0/gems/sass-3.4.23/bin/scss:13:in `<top (required)>'
	from /usr/local/bin/scss:22:in `load'
	from /usr/local/bin/scss:22:in `<main>'
```

**Comment by chriseppstein** [comment]
Found the spec:

https://drafts.csswg.org/css-scoping-1/#slotted-pseudo

**Comment by nazar-pc** [comment]
I've tried to implement this, but without real knowledge of Ruby and SASS implementation I didn't succeed.
Is this a difficult feature to implement? I feels like necessary bits are already there, but some configuration is needed.

**Comment by xzyfer** [comment]
The `::slotted` only exists in an editor draft spec. Support isn't likely to be added until the spec is more stable, or browsers start to implement the spec.

**Comment by xzyfer** [comment]
[caniuse](https://caniuse.com/#feat=shadowdomv1) suggests this may have landed in stable blinked based browsers and Safari's via the Shadow Dom v1 implementation.

**Comment by nazar-pc** [comment]
Browsers such as Chrome and Safari already implemented it more than half a year ago https://caniuse.com/#feat=shadowdomv1
Firefox already started implementation https://platform-status.mozilla.org/#shadow-dom, https://bugzilla.mozilla.org/show_bug.cgi?id=1205323
Edge... well, Edge is slow, but also going to implement it in near future https://developer.microsoft.com/en-us/microsoft-edge/platform/status/shadowdom/
> Roadmap Priority: High — We intend to begin development soon

**Comment by xzyfer** [comment]
@tabatkins can you please comment on the stability of, latest spec for, `::slotted`?

**Comment by tabatkins** [comment]
To the best of my knowledge, it's stable; it tracks what Shadow DOM is wanting to do, and that's been stable for a while.  The WD is quite old, so I just requested to publish an updated one.

**Comment by xzyfer** [comment]
Tracking LibSass support in https://github.com/sass/libsass/issues/2383

**Comment by nex3** [comment]
This was implicitly fixed by #2304. However, we can't extend into `::slotted()` yet. Since it doesn't support selector lists, we'll have to generate multiple instances of `::slotted()`, each in its own complex selector. We don't do this for any other selectors in Ruby Sass, and adding the infrastructure will be hard work.

Extending into `::slotted()` is a very narrow feature, though, and I don't think we should let it block 3.5. I've filed #2325 to track extensions so we can address it later on.

**Comment by tabatkins** [comment]
Oh, hm, limiting ::slotted() to a single compound selector is an accidental limitation. The point is just to prevent combinators; a compound-selector list should be allowed.  I'll fix the spec. ^_^

**Comment by nex3** [comment]
Oh, nice, that makes this *much* easier to implement 😊. In that case I'll target #2325 to 3.5 as well.
