### ISSUE TITLE
compare list literals

### ISSUE THREAD

**Issue by yoannisj** [sass/sass#2267]
Checking if two list literals are equal always returns `true`. This is the case when using the `if()` function for ternary-like comparison, and also using the `@if` construct:

`````sass
$equals: if(0 10 true 'hello' == false 'bar' 4, 'yes', 'no'); // 'yes'
$equals: if(10 null 5 == 5 10 null, 'yes', 'no'); // 'yes'

@if 0 10 true 'hello' == false 'bar' 4, 'yes', 'no' {
  $equals: 'yes';
}

@if 10 null 5 == 5 10 null {
  $equals: 'yes';
}
`````

I have managed to work around this issue by either storing the list values in variables before comparing them, or by wrapping each inside parenthesis.

**Comment by chriseppstein** [comment]
For better or worse, `==` has a higher order of precedence than ` ` so, yes, you need parens here to disambiguate.
