### ISSUE TITLE
Web site  NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by jemandy** [sass/sass#2271]
This is a problem with the https://sass-lang.com/ website, not with Sass itself.

When going to https://sass-lang.com/, my browsers give my a NET::ERR_CERT_COMMON_NAME_INVALID security exception.  Browsing to http://sass-lang.com/ is fine.

**Comment by ArmorDarks** [comment]
Sass website seems to not have SSL certificate, that's why you're getting mentioned warning.

As you can see, because of that default route is `http://sass-lang.com/`, not `https://sass-lang.com/`
