### ISSUE TITLE
@at-root scoping

### ISSUE THREAD

**Issue by meefox** [sass/sass#2273]
When you define functions in mixin.scss and wrapped it by @at-root rule.
Like: 
```
@at-root {
  	@import 'mixin.scss';
}

// functions from mixin.scss will not be available here
```
Is it right behavior?

**Comment by nex3** [comment]
Being able to write an `@import` within an `@at-root` is pretty weird, but otherwise this is intended. Mixins and functions are lexically scoped: they're only visible within the enclosing brackets. This is as true for `@at-root` as it is for any other construct.
