### ISSUE TITLE
nest selector with parent issue

### ISSUE THREAD

**Issue by bluelovers** [sass/sass#2275]
in SCSS we can do nest seletor like htis

```
div
    {
        &[id*='gemini-ad-']
        {
            @content;
        }
    }
```

will return `div[id*='gemini-ad-']`

but any way can make something like this?

```
[id*='gemini-ad-']
{
    div&
    {
        @content;
    }
}
```

return `div[id*='gemini-ad-']` too?

**Comment by nex3** [comment]
`div[id*='gemini-ad-']` and `div[id*='gemini-ad-']` are semantically identical—why do you care which is produced?

**Comment by AlexWayfer** [comment]
Hello!

Our situation: Items has list-view and table-view (toggle).

```scss
.items {
  ul& {
    /* styles for list-view */
  }

  table& {
    /* styles for table-view */
  }
}

/* in another file */

.some-container {
  @import 'items';
}
```

**Comment by nex3** [comment]
@AlexWayfer In that situation I'd recommend manually writing `ul.items` and `table.items`.

**Comment by AlexWayfer** [comment]
@nex3, thanks, we have done so. But is this case there is a code repetition, against which, as far as I understand, Sass is developing.

**Comment by nex3** [comment]
Sometimes reducing repetition has to be balanced against making language features behave clearly and consistently.

**Comment by AlexWayfer** [comment]
> Sometimes reducing repetition has to be balanced against making language features behave clearly and consistently.

```sass
.items {
  /*
     `&` here is `.items`
     `&:hover` will be `.items:hover`
     so `table&` should be `table.items`
  */
}
```

It's simple and intuitive in understanding.

**Comment by nex3** [comment]
`&` is context-dependent. It's only `.items` there if there are no additional parent selectors.

**Comment by AlexWayfer** [comment]
> & is context-dependent. It's only .items there if there are no additional parent selectors.

OK, makes sense. Thank you.

**Comment by bluelovers** [comment]
https://stackoverflow.com/questions/43485109/sass-scss-nest-selector-with-parent?answertab=active#tab-top

**Comment by AlexWayfer** [comment]
Hm :thinking: 

Thank you, @bluelovers.
