### ISSUE TITLE
Interpolation doesn't work as expected.

### ISSUE THREAD

**Issue by akoidan** [sass/sass#2277]
Greeting, I'm using `Sass 3.5.0-rc.1 (Bleeding Edge)` installed with gem. I have a few examples for interpolation that doesn't work in following situations. I separate them within comments. For compiling I'm using `sass --no-cache --update "in.sass":"out.css" --style compressed`. Is there a intentional reason I can't use those?

**Comment by akoidan** [comment]
```
@mixin keyframes($name)
    $foo: #{'@-moz-keyframes'}
    #{$foo} #{$name} // this is line 82
        @content
```

```
@include keyframes(progressMove)
    0%
        background-position: 0 0
    100%
        background-position: 50px 50px
```

expected output

```
@-moz-keyframes progressMove {
    0% { background-position: 0 0 }
    100% { background-position: 50px 50px }
}
```
> Invalid CSS after "": expected selector, was "@-moz-keyframes...")

**Comment by Deathangel908** [comment]
```
@include image("R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=")

@mixin image($base64)
    background: url(data:image/gif;base64,#{$base64}) //this is line N
    //background: url("data:image/gif;base64,#{$base64}") // or this one - doesn't matter
```
> (Line N: Properties are only allowed within rules, directives, mixin includes, or other properties.)

**Comment by akoidan** [comment]
```
$safari-only: '(min-color-index:0) and(-webkit-min-device-pixel-ratio:0)'

@media screen and #{$safari-only}
    body
        background-image: linear-gradient(green 0%, red 100%) !important
```
Which compiles into:

```
@media screen and (min-color-index: 0) and (-webkit-min-device-pixel-ratio: 0) {
  body {
    background-image: linear-gradient(green 0%, red 100%) !important;
  }
}
```
Note, there IS a space after 2nd and. But I want use a css trick to include only safari browser which doesn't work with a space.

**Comment by nex3** [comment]
The keyframes issue occurs because Sass tries to parse plain interpolation as a selector, regardless of what it contains. If instead you write

```sass
@mixin keyframes($name)
    @-moz-keyframes #{$name} // this is line 82
        @content
```

It will work as expected, since Sass knows at parse-time that it's a `@keyframes` rule.

----

For the `@media` issue, if the CSS spec says that two outputs mean the same thing, Sass will freely choose between them. This may mean that we don't support certain CSS hacks, but supporting hacks is not a major goal for us.
