### ISSUE TITLE
@extend additive selection instead of replacing the original selector component

### ISSUE THREAD

**Issue by luxaritas** [sass/sass#2280]
I would like to have a way for `@extend` to treat the selector as a "scope" for the extended properties to apply in as opposed to a replacement for the `@extend`ed selector. Let me provide an example: https://www.sassmeister.com/gist/3c45c601de754da2757dacb092dc70ab

Instead of creating a new rule where `div > div > div` replaces `.c`, I want `div > div > div` to describe an element which .c styling should be applied to, including the styling of `.a .b .c` if the element described by `div > div > div` indeed has parent elements with `.a` and `.b`.

I'm relatively new to sass, so if there is a way to do this, I'd love to hear it. I've dug through the docs though and haven't found anything.

**Comment by nex3** [comment]
I don't think I follow. What output do you expect/want from your example?

**Comment by luxaritas** [comment]
I was thinking about that earlier, and I realized that I'm not sure if there is any existing method in CSS to do this. Here's an example of what originally prompted me to look for this from when I was working in Bootstrap: https://gist.github.com/luxaritas/b9e5fdcddf1b490423ca2e74919b8bc2

I don't see any good way to figure out the correct hierarchy automatically (accounting for both instances where a portion of the child selector could refer to the same element as a portion of the parent as well as where it might be a parent/child of the element referred to) unless you go through EVERY single combination, which wouldn't necessarily be desirable. I suppose I could manually build out an `@extend` for the hierarchy, but that requires me knowing that the hierarchy exists ahead of time.

Perhaps there could be a way to be notified of hierarchies for an extended selector so that you could manually create selectors if needed?

**Comment by luxaritas** [comment]
Ok, just realized this is possible with the CSS4 `:matches()`. The result would be `:matches(.a .b div):matches(div > div > div)` for my initial example, which I tested successfully on Safari iOS. For the boostrap example, it would be `:matches(.navbar-light .navbar-nav a):matches(nav.auto-link li a)`

**Comment by luxaritas** [comment]
After going back and testing a little bit, it seems that `.a .b div:matches(div > div > div)` also works, so I could simply do `div:matches(div > div > div) {@extend .c;}`, then find/create a polyfill for `:matches` so that it works on more than just Safari. I would like to see `@extend` include this selector by default though.

**Comment by nex3** [comment]
It would be nice to generate `:matches()` selectors with `@extend`—it would definitely allow us to clean up our output. Unfortunately, we can't realistically do so until all widely-used versions of major browsers support it.
