### ISSUE TITLE
Namespacing modules

### ISSUE THREAD

**Issue by josephrexme** [sass/sass#2285]
Right now the only way to namespace a module is by nesting in a BEM format which gets messy real quick. I propose that a `@namespace` syntax be introduced. With this we could have:
```scss
// _mod-module.scss
@namespace 'mod-module';
.foo{}
.bar{}
```
that interprets as this in CSS:
```css
/* app.css */
.mod-module__foo{}
.mod-module__bar{}
```
Another option would be to leave the name spacing to when the module is being imported. This way we can specify modules we want to be namespaced from the manifest/index Sass file
```scss
// _mod-module.scss
.foo{}
.bar{}
```
```scss
@import 'mod-module', 'modModule';
```
this way the `@namespace` syntax is not required so it produces:
```css
/* app.css */
.modModule__foo{}
.modModule__bar{}
```
taking the name of the namespace as second argument to `@import`

**Comment by nex3** [comment]
Rewriting selectors *en masse* like this seems like a can of worms to me. It seems clear for a simple rule with a single class selector, but once selectors get more complex it becomes much less straightforward. It would also be likely to amplify confusing around `@extend` and selector modification.

**Comment by josephrexme** [comment]
No matter how complex they get it'd play the role of `&` and that could work for classes and skip ids. Attribute selectors and pseudo selectors would be directly attached to the namespace i.e:
```scss
// scss
@namespace 'mod-module';
:focus{}
::after{}
[data-name^=Chuck]{}
#future{}
```
to
```css
.mod-module:focus{}
.mod-module::after{}
#future{}
.mod-module[data-name^=Chuck]{}
```

**Comment by josephrexme** [comment]
It is also very easy to address the case of `@extend` checking if the current module has a namespace it prepends the necessary namespace

**Comment by josephrexme** [comment]
It could be named something else since it appears the syntax is already [in the specs](https://drafts.csswg.org/css-namespaces-3/). Perhaps `@module`

**Comment by ArmorDarks** [comment]
You can use `mixin` coupled with `&` to achieve pretty much similar behavior.

**Comment by josephrexme** [comment]
@ArmorDarks I believe what you mean by using a mixin would be something like:
```scss
@mixin namespace($module-child){
  &__#{$module-child}{
    @content;
  }
}
```
used as
```scss
.mod-module{
  @include namespace('foo'){
    property: value;
  }
  @include namespace('bar'){
    property: value;
  }
}
```
Agreed this is totally possible but that's even more characters than just using:
```scss
.mod-module{
  &__foo{}
  &__bar{}
}
```
and it wouldn't solve the problem of clarity with name spacing. Consider CSS modules and how it handles namespacing you would be reducing likeliness for errors and messy code with this.

Benefits are:

- DRY code (avoids repetition of `&__` or `@include namespace()`)
- Easy readability and maintenance
- You can easily convert any CSS or scss file to a module by using the `@import('filename', 'module-prefix')`

**Comment by ArmorDarks** [comment]
To be honest, when working with BEM, I do not recommend any form of concatenation, even `&__foo {}`, since it makes search-n-finding of such selectors much harder, especially in large projects. So, whole idea with namespacing as part of Sass feature sounds very vague for me.

At least for now I don't see how Sass could handle this well, It should be part of CSS and closely coupled with imports (module system), then we won't have obscurity and A LOT of potential edge cases introduced by Sass-only directive.

**Comment by josephrexme** [comment]
I agree but there's a solution to everything. Using [ack](https://beyondgrep.com), this would find every selectors you need for the nested syntax:
```bash
ack --scss -l -Q .mod-module | ack -x '&__foo'
```
and for the new proposed syntax which is:
```scss
@module '.mod-module';

.foo{}
.bar{}
```
this should do the search:
```scss
ack --scss -l -Q .mod-module | ack -x 'foo'
```
As you've said it should be coupled with the module system but we have that better in Sass right now and not CSS. Hopefully we get houdini soon and all these can just be added extensions for CSS but Sass is the biggest hope for such a feature now. I hope this can be looked into more closely and reconsidered
