### ISSUE TITLE
Sass compiler ignoring @charset

### ISSUE THREAD

**Issue by tberne** [sass/sass#2287]
The attached ZIP ([SCSSS.zip](https://github.com/sass/sass/files/990829/SCSSS.zip)) has a SCSS file named `inow.scss`.
The file `inow.css` has a `@charset 'UTF-8';` directive. There's an import named `_grid.scss`. Later, I also included `@charset` in imports too.
In an environment with default US-ASCII charset, SASS compiler won't compile it.
It generates the following error:

    Error: Invalid US-ASCII character "\xC3"
            on line 106 of includes/_grids.scss
            from line 26 of inow.scss
      Use --trace for backtrace.

The problem is on `line 106 of includes/_grids.scss`. It has a letter with an accent (in a comment).
I could reproduce it locally in a Windows machine by using `-E US-ASCII` option.
The command-line used to reproduce was: `sass --scss -t expanded -E US-ASCII inow.scss inow.css`.

I believe the compiler should respect the `@charset`.

**Comment by nex3** [comment]
Can you provide a simpler reproduction for this—ideally only one or two files?

**Comment by tberne** [comment]
New version:
[SCSSS.zip](https://github.com/sass/sass/files/1012809/SCSSS.zip)

**UPDATE**: I found that if I had a UTF-8 character in main SCSS file (named `inow.scss`), there's no problem. The problem is when the UTF-8 character is in an included file (in this case, `includes/_grids.scss`).

**Comment by nex3** [comment]
Ah, I see what's going on. The `@charset` declaration [requires double quotes](https://drafts.csswg.org/css-syntax-3/#determine-the-fallback-encoding), but your files use single quotes.

**Comment by tberne** [comment]
Oh, I see...I though single quotes were ok. 
Thanks for your time.

**Comment by notrealdev** [comment]
same issue, still not works with sass 3.5
```Sass compiler ignoring @charset 'utf-8';```
````Sass compiler ignoring @charset "utf-8";````

**Comment by nex3** [comment]
@xttn Can you provide a file that reproduces the error?

**Comment by notrealdev** [comment]
Yes, my simple code here:
```sass
@charset 'utf-8';
body{background: red}
```
CSS output:
```css
body{background: red}
```
`Sass compiler ignoring @charset 'utf-8'`

**Comment by meowsus** [comment]
@xttn https://github.com/sass/sass/issues/2287#issuecomment-302838188

It seems that you need double quotes.

**Comment by notrealdev** [comment]
I tried and not other difference between `"` and `'`

**Comment by nex3** [comment]
Sass uses `@charset` rules in the input files to determine the character set of those files. However, it doesn't *output* a `@charset` rule unless the output file actually has non-ASCII characters, since it doesn't do anything otherwise.

**Comment by ethernidee** [comment]
That's not true.
@charset "utf-8";
// Force sass to output charset directive: 
Does not help.

content: "“" does not help either.

Previosly everything worked without this buggy optimization.

**Comment by nex3** [comment]
What version of Sass are you using?

**Comment by ethernidee** [comment]
Sorry, seems like I was mistaken. It's Ruby Sass 3.7.4 issue,
