### ISSUE TITLE
Option to disable @charset include

### ISSUE THREAD

**Issue by mikestreety** [sass/sass#2288]
Is there a way to disable the auto-adding of the `@charset`? It can't be present in [AMP CSS](https://www.ampproject.org/docs/reference/validation_errors) - we currently use sass to compile our amp css.

We also concatenate on the server (in some rare circumstances) and if the files generated each have a charset, the resulting concatenation has several `charsets` inside.

I am currently using `gulp-sass` which wraps `node-sass` which uses `LibSass`. Is there anyway we can expose an option to disable the `charset`?

**Comment by mikestreety** [comment]
Is it true it will only add it when it finds non-ascii characters? Or does it just add it regardless?

**Comment by nex3** [comment]
> Is there a way to disable the auto-adding of the `@charset`?

There is not, other than manually trimming it yourself after the fact.

>  It can't be present in AMP CSS - we currently use sass to compile our amp css.

We target the official CSS spec when we generate. If a downstream tool doesn't correctly handle valid CSS, that's an issue for that tool.

> We also concatenate on the server (in some rare circumstances) and if the files generated each have a charset, the resulting concatenation has several `charsets` inside.

In this case, the concatenation script falls under the definition of a "downstream tool". In order to correctly concatenate CSS, you must be resilient to the existence of `@charset` declarations.

> Is it true it will only add it when it finds non-ascii characters? Or does it just add it regardless?

It's only added when non-ASCII characters exist.

**Comment by scoobster17** [comment]
I have been playing around with this (what can I say, curiousity) and can confirm the `charset` **is** only added when there are non-ASCII characters (in my case, two dashes in [toast grid](https://github.com/daneden/toast), which I might submit a PR for). I confirmed using this script on mac from [https://superuser.com/a/417379/885222](superuser):

```perl -ne 'print "$. $_" if m/[\x80-\xFF]/' ./path/to/file.css```

(grep didn't work for me).

According to [this article](https://www.theverge.com/2018/3/8/17095078/google-amp-accelerated-mobile-page-announcement-standard-web-packaging-urls) which I read recently, Google seem to have jumped ahead of standardisation and published AMP anyway, and they are looking forward to standards catching up.

So perhaps when this comes to pass, this will filter into `sass` as the option proposed by this issue (unless you want to get ahead of the game on this, looks like it is coming in some form or another).

**Comment by n18l** [comment]
For those seeking to trim off the `@charset` rule post-compilation as nex3 suggested, consider adding a task to your build pipeline for that express purpose. A task for Gulp 4 (utilizing the [gulp-replace plugin](https://www.npmjs.com/package/gulp-replace)) might look as follows:

```js
const gulp = require('gulp');
const replace = require('gulp-replace');

function styles(cb) {
    // Your normal style tasks

    cb();
}

function trimCharset(cb) {
    const compiledCssFile = path.to.file;

    return gulp.src(compiledCssFile)
        .pipe(replace(/@charset.*?;/, ''))
        .pipe(gulp.dest(compiledCssFile));

    cb();
}

exports.build = series(
    // Your other build tasks
    gulp.series(styles, trimCharset)
);
```

I don't really think it's in the best interest of SASS for it to offer an option to willingly defy CSS standards—we're better off addressing unique project concerns like this one on a per-project basis and filing issues with the downstream tools that enforce non-standard requirements (thanks, Google AMP).

**Comment by lkraav** [comment]
https://sass-lang.com/documentation/cli/dart-sass#no-charset seems to say there's a `--no-charset` option available.
