### ISSUE TITLE
Custom selector tokens

### ISSUE THREAD

**Issue by LiamGoodacre** [sass/sass#229]
Currently only ids, classes, and pseudo selectors have particular tokens to use:
id - #
class - .
pseudo - :

To select by a custom attribute, you usually have to write some form of:
[attr=value]

I feel that it would be useful to define custom attributes:
Example definition:
@attr !($value) [data-foo*=" $value "]

Example use:
# id_selector!bar!baz {...}

Output:
# id_selector[data-foo*=" bar "][data-foo*=" baz "] {...}

**Comment by chriseppstein** [comment]
I'm not a fan of this. A lot of mental overhead for very little benefit.

**Comment by nex3** [comment]
I agree with Chris. For cases where the output would be extremely verbose, use #{} and a function.
