### ISSUE TITLE
No way to use -ms-grid-columns and -ms-grid-rows ?

### ISSUE THREAD

**Issue by pelcasandra** [sass/sass#2290]
According to [MSDN documentation](https://msdn.microsoft.com/en-us/library/hh772246(v=vs.85).aspx), grid and rows repetitions should be specified using brackets instead of `repeat` like this.

        -ms-grid-columns: (33.3vw)[3]
        -ms-grid-rows: (14.285vh)[3]

But this is giving me error:

```
Sass::SyntaxError: Invalid CSS after "...columns: (33.3vw)": expected ";", was "[3];"
```

Even If I use the `unquote` function I also get the same error. 

        -ms-grid-columns: unquote("(33.3vw)[3]")
        -ms-grid-rows: unquote("(14.285vh)[3]")

Is there any way to overcome this currently?

**Comment by nex3** [comment]
The Microsoft syntax isn't valid according to the CSS spec, and we don't support it. I don't know why `unquote()` isn't working for you, though—it [works for me](https://www.sassmeister.com/gist/24c4e9d152173ff551f023ced8c5190b).

**Comment by pelcasandra** [comment]
@nex3 You dont support it but that how it works for Edge. So I guess there no way to use CSS grids on Microsoft Edge with SASS? Why not implementing a support for this case? 

By the way, the link you posted seemed to be empty.

**Comment by nex3** [comment]
> You dont support it but that how it works for Edge. So I guess there no way to use CSS grids on Microsoft Edge with SASS?

`unqoute()` works.

> Why not implementing a support for this case?

We have finite implementation time, and chasing every intermediate syntax iteration the spec goes through isn't an efficient use of that time. Also, this syntax is highly ambiguous with existing Sass syntax, so supporting it would likely cause pain and backwards incompatibility.

> By the way, the link you posted seemed to be empty.

Oops, [fixed](https://www.sassmeister.com/gist/24c4e9d152173ff551f023ced8c5190b).

**Comment by aronmoshe-m** [comment]
+1 for `unquote()` as a workaround. Works just fine when live compiling SASS on WordPress.
