### ISSUE TITLE
Considering Travis Speed Up

### ISSUE THREAD

**Issue by junaruga** [sass/sass#2293]
To simplify this topic, I want to talk about `next` branch.
But other branches `stable` and `master` are also same.

Right now `sass`'s Travis tests takes long time until finishing.
The one of the reason is running many Virtual Machines(VMs).

Right now 15 VMs are running on latest next branch.
https://travis-ci.org/sass/sass
https://travis-ci.org/sass/sass/builds/233836704

By this PR: https://github.com/sass/sass/pull/2269 , the number of VM is little bit reduced.
But maybe we still can reduce the number of VMs.

I have 2 ideas to improve this.

### Unify VMs by different UNIX environment variable to 1 VM

Look at below `.travis.yml` of `test_declarative`.

- Before: https://github.com/svenfuchs/test_declarative/blob/d839c374d72f4c9c84d3e0babc03174255debacc/.travis.yml

- After: https://github.com/svenfuchs/test_declarative/blob/master/.travis.yml , https://github.com/svenfuchs/test_declarative/blob/master/test/run.rb

The idea is that I reduced the number of VM by unifying 4 VMs to 1 VM, running `./test/run.rb`.
4 Gemfile cases are running on 1 process `./test/run.rb`.
As the result, `test_declarative`'s Travis speed was much faster than before.

For example, we have below cases for `sass` in `.travis.yml`. And we can unify these cases to 1 VM.

```
- env: MATHN=true RUBOCOP=false
- env: MATHN=false RUBOCOP=false
- env: MATHN=true RUBOCOP=true
```

### A specified version Ruby for 3 VMs?

Ruby 2.2.3, 2.1.7, 2.0.0 are running using 3 VMs for each other.

We really need these 3 cases?

```
- env: MATHN=true RUBOCOP=false
- env: MATHN=false RUBOCOP=false
- env: MATHN=true RUBOCOP=true
```

For example, below 2 cases isn't good enough?

```
- env: MATHN=true RUBOCOP=true
- env: MATHN=false RUBOCOP=true
```

How do you think?

Thanks.

**Comment by nex3** [comment]
I'm definitely on board with consolidating the environment variable matrix. We only need to test Rubocop once, so

```yaml
- env: MATHN=true RUBOCOP=true
- env: MATHN=false RUBOCOP=false
```

should be fine.

As for doing multiple test runs in a single VM, it's at least worth experimenting to see if it produces a net speed gain.

**Comment by junaruga** [comment]
@nex3 Okay. I am happy that you are interested in this topic. Next week, I will work for that. measure the running time of below patterns in my repository. And report here.

- Current next branch
- Only 2nd Idea
- 2nd + 1st idea

**Comment by junaruga** [comment]
@nex3 I have a question.

Seeing `Rakefile`, 

* `rake test:ruby`: `MATHN=true or false`
* `rake test:spec`: It does not depend on MATHN, right? That means we do not have to run the `test:spec` in 2 cases: `MATHN=true or false`.

**Comment by junaruga** [comment]
@nex3 I will report you.

# Report

## Check Speed (Ran for)

The time is the value of "Ran for" for each Build.
Test environment is here: https://travis-ci.org/junaruga/sass/branches
You can see all the results that I showed there.

| Case | Branch | Modification | Try 1 | Try 2 | Try 3 | Average | Comment |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 1 |  feature/next-travis-speedup-1, next | next branch (original) | 07:23 | 09:17 | 13:03 | 09:54 | |
| 2 |  feature/next-travis-speedup-2 | 2nd idea (reduce 3VMs) | 05:36 | 05:09 | 07:05 | 05:57 | |
| 3 |  feature/next-travis-speedup-3 | 2nd idea + 1st idea (unify 2 VMs to 1) | 03:31 | 03:33 | 06:58 | 04:41 |  *Try 3 (06:58) includes a long time job. |
| 4 | feature/next-travis-speedup-4 | 2nd idea + 1st idea + Trusty | 05:46 | 05:44 | 05:15 | 05:35 | |
| 5 | feature/next-travis-speedup-5 | 2nd idea + 1st idea + test:spec: 2 to 1 | 03:40 | 02:41 | 05:04 | 03:48 | *Try 3 (05:04) includes a long time job. |

## Conclusion

* Case 2 is faster than Case 1.
* Case 3 is faster than Case 2.
* Case 3 is faster than Case 4.
* Case 5 is faster than Case 3.

So, "Case 5" is best. I will recommend Case 5.
How do you think? If it is no problem, I want to send PR for Case 5.

## Ref: Modification

Only latest commit is target for each branches.

https://github.com/junaruga/sass/commits/feature/next-travis-speedup-1
https://github.com/junaruga/sass/commits/feature/next-travis-speedup-2
https://github.com/junaruga/sass/commits/feature/next-travis-speedup-3
https://github.com/junaruga/sass/commits/feature/next-travis-speedup-4
https://github.com/junaruga/sass/commits/feature/next-travis-speedup-5

**Comment by nex3** [comment]
Thanks for running those tests! A PR for case 5 sounds great.

**Comment by junaruga** [comment]
Close this ticket, as #2302 was merged.
