### ISSUE TITLE
Help generating docs

### ISSUE THREAD

**Issue by lostapathy** [sass/sass#2295]
I'd like to submit a PR fixing some broken links in the docs, but I'm having a hard time building them to match what's getting published on sass-lang.com

I've done the usual
```
git clone
bundle install
rake doc
```
But I seem to get a different output than is currently on the website.

For example, http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options takes you to the correction section, but hitting doc/file.SASS_REFERENCE.html#options in my working copy does not.

My local copy is generally formatted differently as well, for example I don't have the nice right-hand navigation that shows up on the sass-lang.com link above.

I've tried building with both a current version of yard and the 0.8.7.6 that the docs on sass-lang.com indicate they were built with and get the same results.

I've got a few corrections already identified, and if I can get setup to build them correctly I'll take a shot at fixing some of the doc warnings as well.

**Comment by nex3** [comment]
You may be using the wrong version of Yard... I just compiled with 0.8.7.6 (the version in the lockfile) and I got the sidebar and working inner links. Note that to get it to look exactly like the website, you'll need to compile from within the [sass-site](https://github.com/sass/sass-site) repo, since it adds some custom CSS.

**Comment by lostapathy** [comment]
Thanks @nex3 - pointing me to the sass-site project seems to fill in a lot of pieces.  FWIW, it doesn't quite build out of the box in an otherwise fresh environment, but I'll submit a PR over there for that.

When I build that, it builds with yard 0.9.9 which I believe is a result of [this line of the gemspec](https://github.com/sass/sass/blob/stable/sass.gemspec#L22) - can you point me at the lockfile that's locked to 0.8.7.6?

**Comment by lostapathy** [comment]
I found the root of this. [This commit](https://github.com/sass/sass/commit/2980ac65ae6adfee04243b9f16469277f6e2bc6d) changed from maruku to redcarpet, which explains what I'm seeing.  Mainly, that anchors in the generated html with redcarpet are different than in the older docs (that I assume were generated with maruku).

For example, maruku generates lowercase anchors, such as:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options

But redcarpet generates them uppercase, it would generate:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Options

Is it safe to assume that the correct path forward is to update any broken links to use the redcarpet-style anchors?

FWIW, what let me down this path is a broken link on [this doc](http://sass-lang.com/documentation/Sass/Engine.html#constructor_details) for "the Sass options documentation" - which matches neither case.  I'm working to submit a PR to fix a few things like that, but ran into this issue first.

**Comment by nex3** [comment]
> Is it safe to assume that the correct path forward is to update any broken links to use the redcarpet-style anchors?

Yes, thanks!

**Comment by lostapathy** [comment]
Thanks - I submitted a PR on sass-site to address the build issues and will follow up with a PR for doc updates.  I think I'm all set here and am closing this.
