### ISSUE TITLE
SASS fails to import when extension is not provided and there is a directory in the same location with the same name

### ISSUE THREAD

**Issue by AnmSaiful** [sass/sass#2296]
Say, I have a directory named `home` and a file named `home.scss`, where they both are in the same location. Now importing `home` does not automatically detect and include `home.scss`.

For example, if I use `@import "home";` it does not include `home.scss`. But if I use `@import "home.scss";` it does.

I am using the version `3.4.22`

**Comment by daveschwerstein** [comment]
@import "home"; would work if your scss file is _home.scss

**Comment by AnmSaiful** [comment]
Thank you. But I need to generate `home.css` file. :-)

**Comment by daveschwerstein** [comment]
if home.scss is the main file, what are you trying to import? Are you importing the directory "home/"?

**Comment by AnmSaiful** [comment]
Well, I am just trying to include `home.scss` using the code `@import "home";`, where it fails because there is a directory named `home` in the same location.

Maybe the compiler is getting confused because it is possible to have the same name of a file and directory. And the real file has a `.scss` extension where the declaration does not have.

I know the underscore workaround, but I think this should be solved, as it is an unexpected issue. It took some of my valuable times to precisely detect the actual issue. Would not be happy to hear someone else is also going through the same experience, as because the scenario is not rare. :-)

**Comment by daveschwerstein** [comment]
> Well, I am just trying to include home.scss using the code @import "home";.

Which file is the import statement in?

**Comment by AnmSaiful** [comment]
Any valid SASS files.

Well, let me be more specific. Consider the following directory structure.

```
/css
    home.css
    style.css
/scss
    /home
    home.scss
    style.scss
```

The style.scss file contains:
@import "home";

And this does not importing `home.scss`;

Make sense? :-)

**Comment by daveschwerstein** [comment]
the syntax `@import "home";` references a partial (`_home.scss`). If you want to render two files (home.css and style.css) where style.css includes code from home.css, the option would be to do as you are with `@import "home.scss";` because it is not a partial. This isn't a problem with the compiler nor is it getting confused with a home/ directory existing. The issue is a desire for the compiler to know if you are referring to home.scss or _home.scss with the same import statement. Does that make sense?

for more: http://sass-lang.com/guide

**Comment by AnmSaiful** [comment]
Oh yeah. I forgot that excluding extension works only for partials. Thanks for reminding me.

And yeah, it completely make sense. :-)

Many thanks for your kind co-operation. And sorry for the inconvenience.

I am closing the issue. :-)

**Comment by daveschwerstein** [comment]
No worries, I'm glad you sorted it out.
