### ISSUE TITLE
Custom placeholder format?

### ISSUE THREAD

**Issue by JayAdra** [sass/sass#2299]
Hey there!

I am trying to get a dynamic colour from a PHP backend into a stylesheet. I had this working using normal CSS by using the following:

```css
.example {
	color: rgb(%%settings.bg_main_color%%);
}
```

Although this is invalid CSS, I had a route which would get the contents of the CSS file, replace the placeholders with the value from DB, and output the new content as a CSS file, so it worked great.

Now that we've moved to using SASS, and moved this colour into a variable, we can't get it to work dynamically.

I've tried everything I could find to get the compiler to ignore this "error" or otherwise print the raw string as I passed it, but nothing works. Something like this would be ideal:

```css
$main: rgb(%%settings.bg_main_color%%);
```

As throughout my code I use:

```css
.example {
	color: $main;
}
```

So my question is, is there a way (even if it's a hack) to get SASS to ignore this specific "error"? If not, is there another way to achieve what I want? Keep in mind I can't physically write the DB value to the file, as it's dynamic for each account/user and can be changed dynamically.

If it helps, I'm using Compass.app on Windows 10.

Any suggestions at all would be greatly appreciated.

Thanks!

**Comment by nex3** [comment]
Sass doesn't (and won't) support invalid CSS. I can imagine a few ways around this.

* You could dynamically create a stylesheet that defines Sass variables from the database before you invoke Sass.

* You could define a custom function in Ruby that loads colors from the database.

* You could use a plain-CSS custom function like `color-from-db("settings.bg_main_color")` that Sass would pass through unmodified and you could later search and replace much like you're doing now.

**Comment by JayAdra** [comment]
Thanks for the suggestions. Number 3 sounds the most suitable, but I'm unsure how to do this? How can I define and use a custom CSS function (not Sass)? Is this similar to custom CSS properties?

I couldn't find anything on it while searching, but a link or small code snippet would be greatly appreciated!

Thanks!

**Comment by nex3** [comment]
If you're using Ruby Sass, [these docs](http://sass-lang.com/documentation/Sass/Script/Functions.html#adding_custom_functions) describe how to add custom functions.

**Comment by nex3** [comment]
In option 3, you wouldn't define a `color-from-db()` function, you'd just do a search-and-replace after the fact.

**Comment by JayAdra** [comment]
Great, thank you! Got it working, though it just means I can't do:

```css
.example {
	color: rgba($main, 0.5);
}
```

As it tries to validate $main as a colour when doing that. No matter, I think this solution will work for my needs.

Thanks again!
