### ISSUE TITLE
Feature Request: add an option to the sass command to print out a mixin reference

### ISSUE THREAD

**Issue by timkelty** [sass/sass#23]
I think it would be killer if you could do something like `sass --reference styles/screen.scss` and have it spit out a big reference list of all your available mixins and their parameters.

I imagine I would just keep that up in a terminal window at all times when I'm in my stylesheets. It think it would be awesome!

**Comment by nex3** [comment]
I don't think this is something which belongs in Sass proper. It would make more sense as a separate application that uses Sass's parsing code, like [SassDoc](http://github.com/chriseppstein/sassdoc).

**Comment by timkelty** [comment]
oh! i didn't know about SassDoc, thanks, thats pretty much what I'm looking for!
