### ISSUE TITLE
Fixing IE gradient

### ISSUE THREAD

**Issue by bbenezech** [sass/sass#231]
Shorthands for colors not allowed in IE gradients.

Bootstrap use them a lot. 

Result is painfully 80ish. 

Compass already implements a hack, thinking about doing the same for bootstrap-sass: 

https://github.com/thomas-mcdonald/bootstrap-sass/issues/14
http://pinds.com/2011/11/30/fixing-ie-gradients-with-rails-3-1-and-scss/

cc @thomas-mcdonald @rjackson

**Comment by chriseppstein** [comment]
I think it's ok if sass pulls this in. Its life is limited tho, IE is getting on the CSS3 bandwagon.

**Comment by chriseppstein** [comment]
link to code: https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/colors.rb#L35-42

**Comment by iwasrobbed** [comment]
+1 Life may be limited, but this is an easy and helpful fix in the mean time.

**Comment by tmiller** [comment]
+1 bootstrap-sass doesn't seem to be able to precompile assets with the hack they implemented, because rake isn't loading it

**Comment by evantravers** [comment]
+1 This would be a boon…

**Comment by leesmith** [comment]
+1

**Comment by nex3** [comment]
Closed by 374d8c94b2c794d5b73ad7218f1fd5367755dd7b.
