### ISSUE TITLE
:hover and parent-of-parent-selector

### ISSUE THREAD

**Issue by dhffdh** [sass/sass#2313]
How can this rightly be done without this bicycle ( @at-root #{$parent} ) ?
```
.item{  
	$parent: &;
	&-title{
		@at-root #{$parent} {
			&:hover &-title {
				color: #e1b900;
				text-decoration: underline;
			}
		}
	}
}
```
It generate this:
```
.item:hover .item-title {
  color: #e1b900;
  text-decoration: underline;
}

```

**Comment by nex3** [comment]
It's not entirely clear to me what you're trying to express, but generally if you're using the parent selector expression, you need to use `@at-root` along with it because there's no way for Sass to know if the string you're passing in to `#{}` includes the parent selector or not.
