### ISSUE TITLE
Support extending into ::slotted()

### ISSUE THREAD

**Issue by nex3** [sass/sass#2325]
As of 3.5, we support the `::slotted()` pseudo-element. However, we don't parse its argument as a selector, which means it's not possible to `@extend` into it. This should be fixed.

**Comment by nex3** [comment]
Note that at time of writing the spec says `::slotted()` only allows compound selectors, but [it will be extended to allow selector lists](https://github.com/sass/sass/issues/2266#issuecomment-309530185).

**Comment by tabatkins** [comment]
The change is pushed now.
