### ISSUE TITLE
Selector imports, selector renaming, glob importing

### ISSUE THREAD

**Issue by maoberlehner** [sass/sass#2330]
I've seen that most of this features were already requested in https://github.com/sass/sass/issues/1094 but I might add to the conversation that I've implemented a custom importer (thanks for the awesome custom importer API) which is a playing ground to checkout possible solutions to those problems: https://github.com/maoberlehner/node-sass-magic-importer

[node-sass-magic-importer](https://github.com/maoberlehner/node-sass-magic-importer) enables renaming classes / selectors, once importing and silent importing (similar to LESS reference imports).

**Comment by maoberlehner** [comment]
Hmm.. closing without pointing out any further actions or even a reason, seems not like a nice thing to do..

But, I guess maintaining this repo must be a lot of work (and I'm very thankful for that) – so I'll just assume _"we don't want you to plug your own project here"_ is the reason. Although I really think adding an information to https://github.com/sass/sass/issues/1094 would've been helpful to some people.

**Comment by nex3** [comment]
You didn't really have a bug report or a question... you were just linking to an alternate solution. It didn't seem like there was any additional action to take.
