### ISSUE TITLE
Function return value not used in variable declaration

### ISSUE THREAD

**Issue by davewallace** [sass/sass#2332]
Hi there,

Related to #909 possibly, though that's pretty old now, but I pretty much lifted the CSS Tricks material design for box-shadow helper example and then tried to set the value of that helper function as the value of a variable. I then referenced the variable within a selector block - it rendered incorrectly.

Here's my codepen for the issue: https://codepen.io/davewallace/pen/pwpxEB

The CSS output of the pen is:
```
div {
    margin: 50px;
    background: white;
    box-shadow: card(1);
}
```

Edit: interestingly, if I reference only one function, such as bottom-shadow(), the return value from that function does work (https://codepen.io/davewallace/pen/mwpzLL)

Any help much appreciated!

**Comment by nex3** [comment]
Sass has a distinction between "functions" and "mixins". A function, declared with `@function`, returns a value can be used in a property value, variable value, and similar contexts (collectively called "SassScript"). A mixin, declared with `@mixin`, is called (using `@include`) at the statement level and creates *new* selectors and/or properties at the point where it's called.

You're declaring `card()` as a mixin, but you're trying to call it like a function. Sass doesn't see a function named `card`, so it decides that you must be referring to a plain-CSS function and compiles it accordingly. If you write a function instead, [your example works](https://www.sassmeister.com/gist/633e603ebe7a467141357db4010c6200).

**Comment by davewallace** [comment]
/me sighs.

I looked at the problem for too long. Of course you're right - this ticket's contents belongs on stackoverflow now! And thank you :)
