### ISSUE TITLE
Selector factorization

### ISSUE THREAD

**Issue by BuonOmo** [sass/sass#2333]
This is a feature request for a selector optimization that would work like this:

```scss
.ctn (.foo, .bar) { ... }
// would be like
.ctn .foo,
.ctn .bar { ... }
```

For this example you also could nest it, but this would be very usefull if the names are long or a little bit complicated. Or if the factorisation is made for the parent:

```scss
(.foo, .bar) .btn { ... }
// would be like
.foo .btn,
.bar .btn { ... }
```

Any thought on this ?

**Comment by nex3** [comment]
We try hard to avoid adding new syntax on top of CSS—it makes it less clear to an unfamiliar reader what's Sass and what's CSS, and it adds to the risk of collisions with future CSS additions.

In this case, what you're describing is essentially the `:matches()` selector, which *is* part of CSS. This isn't especially widely-supported yet, but it probably will be on approximately the same timeline it would take to add this feature to Sass.
