### ISSUE TITLE
HSL returns inaccurate color values

### ISSUE THREAD

**Issue by benbennybenben** [sass/sass#2335]
###I've created a color scheme in Sketch and wanted to recreate in SASS for some templates using the HSL module. When I take the original HEX base color, all I want to do is get the H value, then set the Saturation and the Lightness to set amounts. But when I do this, the results don't reflect what I've made using the same process in Sketch or Photoshop.

These are the color values that I get

**In Sketch:**
HEX: #FCDC41   |   HSL: 50deg,  74%,  99%

**In Photoshop:**
HEX: #FCDC41   |   HSL: 50deg,  74%,  99%

**Using SASS**
HEX: #FCDC41   |   HSL: 49.7deg,  96.8%,  62.1%  (Actual HEX: #9E8405)

So I'm trying to figure out why this is happening. I've double check it and it doesn't look like I've made any mistakes.

I made a codepen with what I started to make, the first set of color values in the white box are the sass colors, and the second set are what the color should be. The swatch is the entered HEX and the background color is the generated color.
https://codepen.io/benbennybenben/pen/MoXMzN

**Comment by ArmorDarks** [comment]
Photoshop uses HSV (HSB) color model, it isn't same as HSL. See https://github.com/sass/sass/issues/2192

**Comment by benbennybenben** [comment]
Thanks, @ArmorDarks , I've just started to understand that whilst working on the problem, silly mistake. Thanks for the link. I'll read up

**Comment by viktor992** [comment]
Recently, I had to deal with HSB colors in a project that used SASS. I implemented a module to transform and manipulate HSB colors and published it as a Node package to facilitate its reuse in the future. Here is the package in case it is useful to anyone else: [sass-hsb-functions](https://github.com/viktor992/sass-hsb-functions).
