### ISSUE TITLE
background doesn't allow color + image

### ISSUE THREAD

**Issue by yuriabrito** [sass/sass#234]
background: #000000 url("image.png) no-repeat;

only shows the image, no colour to fill the blank space.

**Comment by chriseppstein** [comment]
I assume you don't have the missing double quote in your actual code.

Sass is a preprocessor, it generates normal css. As such, sass bugs take the form of "This Sass input produced invalid CSS output". Where both the sass input and the css output are provided as well as a the expected output. This input/output looks like standard css so I can only assume there is a problem in your stylesheets.
