### ISSUE TITLE
Please split out listen support to a separate gem

### ISSUE THREAD

**Issue by henderea** [sass/sass#2347]
When I updated my sass installation today, I found that it was trying to install a gem called `sass-listen`, which conflicted with the `listen` gem I already had installed.  I only use the `sass` gem with rails, so I have no need for listen support in it.

Is there anyway we could make listen support a separate gem?  I don't feel that I should have to have `sass-listen` installed just so I can use the latest version of `sass` with rails.

Also, if the listen support is split out, that means less bloat for people like me who don't need listen support for sass.

**Comment by cwonrails** [comment]
I noticed the same today when updating my global gems. Screenshot: 
![image](https://user-images.githubusercontent.com/4729979/28176196-8406f650-67c4-11e7-8811-cea5f58379c1.png)

**Comment by nex3** [comment]
Duplicate of #2345. There's no way to keep the existing CLI without depending on some version of listen, but I plan to release a version of sass-listen that doesn't conflict with the real listen.

**Comment by fmluizao** [comment]
Sorry to comment on a closed issue, but I think this one is not a duplicate of https://github.com/sass/sass/issues/2345

This issue is about leave the decision to use or not file watching up to the user.

I think that _sass-listen_ should depend on _sass_, not the inverse. 

This way, people who need/want file watching will use _sass-listen_.

**Comment by bquorning** [comment]
> Also, if the listen support is split out, that means less bloat for people like me who don't need listen support for sass.

I agree. I have no need for the “watch” support, and I would rather not add 3 extra gems (sass-listen, rb-fsevent and rb-inotify) to my application.

**Comment by joevandyk** [comment]
rb-ionotify also brings in the ffi gem.

**Comment by joevandyk** [comment]
@nex3 Any chance sass-listen could depend on sass? It can be a pain to install the dependencies for sass-listen, fb-fsevent, rb-ionotify, and ffi.
