### ISSUE TITLE
Finding word in string that has single quotes.

### ISSUE THREAD

**Issue by wotta** [sass/sass#2349]
Hello everyone,

Not sure if there is a way to do this.
But I am creating something ( which is not that useful ) that needs to find a specific word from a complete string.
That word always has quotes around it.

Note sure if this is possible but I better ask here.

Best regards,
Wouter.

**Comment by nex3** [comment]
You can use the [`str-index()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#str_index-instance_method) function to find a substring within a string.
