### ISSUE TITLE
`:root` error message does not display properly

### ISSUE THREAD

**Issue by jhpratt** [sass/sass#2351]
It took me reading through the generated source to realize that it had to be escaped with a backslash (why is this?). The `::before` message doesn't properly show the backslash.

**Comment by nex3** [comment]
I'm not sure what issue you're running into, exactly. Can you include a minimal Sass file that reproduces the error, as well as the behavior you'd expect from that file?

**Comment by jhpratt** [comment]
After updating to the latest version, it appears to have been fixed.
