### ISSUE TITLE
Sass 3.5 isn't compatible with JRuby 1.7

### ISSUE THREAD

**Issue by jslegers** [sass/sass#2358]
I'm trying to install Sass 3.5.1 on my laptop, but it doesn't seem to be compatible with JRuby 1.7.

Here's the log I got when running `gem install sass` :
````
Fetching: ffi-1.9.18-java.gem (100%)
Successfully installed ffi-1.9.18-java
Fetching: rb-inotify-0.9.10.gem (100%)
Successfully installed rb-inotify-0.9.10
Fetching: rb-fsevent-0.10.2.gem (100%)
Successfully installed rb-fsevent-0.10.2
Fetching: sass-listen-4.0.0.gem (100%)
Successfully installed sass-listen-4.0.0
Fetching: sass-3.5.1.gem (100%)
ERROR:  Error installing sass:
        sass requires Ruby version >= 2.0.0.
````

My environment : 

* OS : Windows 10
* JRuby version : 1.7.27 (1.9.3p551)
* Java version : 1.8.0_131

Is there a way around this without having to install a different version of Ruby on my machine?

What is the latest version of Sass compatible with JRuby 1.7?

**Comment by nex3** [comment]
We don't test against JRuby so I can't say for sure, but the last Sass version that was compatible with Ruby 1.9.3 was Sass 3.4.25.

**Comment by jslegers** [comment]
Thanks. I haven't tried running sass yet, but the installation seems fine :

````
Fetching: sass-3.4.25.gem (100%)
Successfully installed sass-3.4.25
1 gem installed
````
