### ISSUE TITLE
syntax error, unexpected modifier_if

### ISSUE THREAD

**Issue by BMannell** [sass/sass#2359]
### Error
Getting error `/gems/sass-3.5.1/lib/sass/script/functions.rb:2050: syntax error, unexpected modifier_if (SyntaxError)` when trying to start a rails server. 

### Release Version 
3.5.1

### Code
https://github.com/sass/sass/blob/530f80fe78c0d9287d20c5622f7583779133fb6b/lib/sass/script/functions.rb#L2048-L2060

https://github.com/sass/sass/blob/530f80fe78c0d9287d20c5622f7583779133fb6b/lib/sass/script/functions.rb#L2093-L2099

**Comment by BMannell** [comment]
Both spots are throwing `unexpected modifier_if ` errors.

**Comment by BMannell** [comment]
Reverting to release version 3.4.21 resolved the errors.

**Comment by tparkin** [comment]
I'm seeing the same error. Thanks for sharing your fix, @BMannell!

**Comment by nex3** [comment]
What version of Ruby are you using?

**Comment by katlandreth** [comment]
Possibly related to this ruby bug: https://bugs.ruby-lang.org/issues/10279 ?

**Comment by BMannell** [comment]
I am using version `ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]`

**Comment by nex3** [comment]
This looks like a bug in Ruby, not in Sass.
