### ISSUE TITLE
Website Sass Basics: Clarify usage of watch command

### ISSUE THREAD

**Issue by colinfoster** [sass/sass#2362]
I'm just getting started with Sass and got stuck at "Preprocessing" on the "Basics" page (for much longer than I'd like to admit).
   http://sass-lang.com/guide

It wasn't clear to me at all that the colon represented a delimiter between "input:output." (e.g., hmm... maybe app/sass is a mime type... for some reason?) I consulted the documentation but the usage wasn't any clearer.

Perhaps the example could be replaced with:

> To watch an entire directory for changes to your Sass files, and output CSS to the same directory, you would use:
> `sass --watch path/to/public-sass-and-css-files/`
> 
> To output CSS to a different directory, separate paths with a colon:
> `sass --watch path/to/private-sass-files/:path/to/public-css-files/`

Hopefully a report from someone with noob eyes is useful.

Thanks,
Colin

**Comment by nex3** [comment]
This is the repository for Sass's code; please file website issues against the [sass-site repo](https://github.com/sass/sass-site).
