### ISSUE TITLE
Installation sass  error on mac seira 

### ISSUE THREAD

**Issue by khaitawng** [sass/sass#2366]
ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.18/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20170821-21856-ns4gm.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.18 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/ffi-1.9.18/gem_make.out

Please help me.

Thanks much & Have a nice day

**Comment by nex3** [comment]
Duplicate of #2357.

**Comment by Pertsevoy** [comment]
lomismo ((

**Comment by Pertsevoy** [comment]
I have the same problem how to solve?

**Comment by nuelschoch** [comment]
same here :(

**Comment by SuperManWG** [comment]
h1 bro! This is "pertsevoy" You need php storm and u must comlip sass or less

**Comment by MtKuile** [comment]
I have the same problem.

**Comment by nuelschoch** [comment]
i made it work:

- updated ruby (ruby was still installed, sass was gone after the high sierra update)
- xcode-select --install (i read that somewhere)
- i also installed/updated some xcode related stuff via app store (read that too somewhere, don't know if that was helping in any way)
- sudo gem install sass -n /usr/local/bin

worked for me. hope that helps.

btw, sass installed or not, try [CodeKit](https://codekitapp.com) if you guys don't know it

**Comment by supermodo** [comment]
Thanks @nuelschoch, that fixed my problem too...and the CodeKit testimonials make my day

**Comment by esr360** [comment]
Still receiving this error `ERROR: Failed to build gem native extension` oh High Sierra even after running `xcode-select --install`.

**Comment by mangglez** [comment]
It works!! 
First you have to install the command tools line, so go to the Terminal and type: 
xcode-select --install 
When it finishes type: sudo gem install sass
After that check if it's installed: sass -v

**Comment by francosalcedo** [comment]
For users mac: do not forget to accept the T&C of x-code, run this
sudo xcodebuild -license

**Comment by Aviisek** [comment]
getting same issue in mac os catalina. this `xcode-select --install` does not help, it prints `xcode-select: error: command line tools are already installed, use "Software Update" to install updates` .
