### ISSUE TITLE
@media syntax error

### ISSUE THREAD

**Issue by ismell** [sass/sass#237]
If you download the YAML base.css (http://www.yaml.de/fileadmin/yaml/core/base.css)
and try to parse it via sass

```
$ sass base.css

me@devbox:/var/www/rangelwed.com/Symfony/web$ sass base.css
WARNING on line 329 of base.css:
This selector doesn't have any properties and will not be rendered.
WARNING on line 449 of base.css:
This selector doesn't have any properties and will not be rendered.
WARNING on line 499 of base.css:
This selector doesn't have any properties and will not be rendered.
Syntax error: Invalid CSS after "": expected selector, was "{"
        on line 41 of base.css
  Use --trace for backtrace.


me@devbox:/var/www/rangelwed.com/Symfony/web$ sass -v
Sass 3.1.12 (Brainy Betty)
```

It seems to be the @media tags.

**Comment by chriseppstein** [comment]
If you compile scss you need to pass --scss to the sass command line.

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by ismell** [comment]
Oh, that was a dumb on my part. Guess I should sleep more huh ?

Thanks

**Comment by chriseppstein** [comment]
You can also use the `scss` command line tool which is the same except it
defaults to `--scss`

On Tue, Jan 3, 2012 at 7:25 AM, Raul E Rangel <
reply@reply.github.com
