### ISSUE TITLE
please untie sass-listen from listen, and tag the release

### ISSUE THREAD

**Issue by jonassmedegaard** [sass/sass#2373]
Hi,

sass-listen is declared a fork of listen, yet is tied to listen so that I cannot file bugreports (the button is for requesting a PR instead).

The bug I wanted to file (now abusing this issue tracker for it, hope you don't mind) is possibly related:

Please tag the 4.0.0 release, to ease tracking by redistributors (like Debian for which I maintain packages).

Kind regards,

 - Jonas

**Comment by nex3** [comment]
I've enabled issues for sass/listen and created a v4.0.0 tag.
