### ISSUE TITLE
Wrong compilation result

### ISSUE THREAD

**Issue by meefox** [sass/sass#2374]
Following snippet:
```
@mixin mixin_1 {
    @at-root {
        .mod#{&} {
	    @content;
	}
    }
}
.container {
    .class-1,
    .class-2 {
        @include mixin_1;
    }
}
```

And result is 
```
.mod.container .class-1, 
.container .class-2 {
  color: #20AD6B; }
```
Problem is that:
.mod class is missing from second selector with class-2

**Comment by vladislav251990** [comment]
It's because & is list of your selectors. Try following code, it should work as expected.
```
@mixin mixin_1 {
    @each $sel in &{
        @at-root {
            .mod#{$sel} {
                margin: 0;
            }
        }
    }
}
.container {
    .class-1,
    .class-2 {
        @include mixin_1;
    }
}
```

**Comment by nex3** [comment]
@vladislav251990 is right. When you write `#{&}`, it does a simple string interpolation, without the full selector expansion that happens when you use `&` as a selector component.
