### ISSUE TITLE
Unknown Property - `speak: none;`

### ISSUE THREAD

**Issue by stevenventimiglia** [sass/sass#2377]
When applying `speak: none;`,  I receive "Unknown property." errors.

![speak-none](https://user-images.githubusercontent.com/10396421/30780265-1363d23e-a0d5-11e7-9869-fc0b0e2d70ff.png)

**Comment by stevenventimiglia** [comment]
**References:**
1. http://www.cssportal.com/css-properties/speak.php
2. https://css-tricks.com/almanac/properties/s/speak/

**Comment by nex3** [comment]
This error is generated by your IDE or your linter; Sass doesn't track which properties exist and which don't.
