### ISSUE TITLE
CSS min() and max() re-introduced

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#2378]
*(edited by @nex3)*

- [x] [Proposal](https://github.com/sass/language/blob/master/accepted/min-max.md)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1274)
- [x] [Documentation](https://github.com/sass/sass-site/commit/efc113ec)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/426)
- [ ] [LibSass](https://github.com/sass/libsass/issues/2701)
- [x] [Ruby Sass](https://github.com/sass/ruby-sass/issues/77)

---

https://drafts.csswg.org/css-values/#calc-notation
A (maybe) quick solution could be to add a `@` prefix – and while at it extend the math methods to cover pow, sqrt, cos, etc...

````SCSS
 @min($numbers...)
 @max($numbers...)
 @abs($number)
 @percentage($number)
 @round($number)
 @ceil($number)
 @floor($number)
 @random($limit)
 //  Sadly missing from Sass at this point 
 @pow($base, $exponent)
 @sqrt($number)
 @cos($number)
 ...

**Comment by nex3** [comment]
Ugh, this is pretty bad news. Long-term, we'll be moving these functions into importable libraries with namespaces... hopefully that'll happen before browsers start implementing them.

**Comment by diligiant** [comment]
@nex3 I wouldn't hold my breath for too long as it's likely to appear in Safari when the iPhone X is released if I infer from grorg answered here -> https://github.com/w3c/csswg-drafts/issues/1693#issuecomment-329920580

I agree with @jakob-e that a quick fix would be enough to be ready for early November.

**Comment by nex3** [comment]
"Quick fixes" that break existing Sass code aren't acceptable. At the very least, we need a minor-version deprecation period for this. Until then, you can use `calc(max(...))` or `m#{a}x(...)` as a workaround.

**Comment by diligiant** [comment]
Quick didn’t imply dirty! I didn’t know about m#{a}… trick. That will do (max alone is needed for @supports). Thank you.

**Comment by jrjacobs24** [comment]
I ran into this issue today as well when converting my src from Less to Scss. I found that using Sass Function [unquote](http://sass-lang.com/documentation/Sass/Script/Functions.html#unquote-instance_method) rendered the correct output I was looking for.

In my Scss:
```scss
.example {
  right: unquote('max(#{$global-margin}, env(safe-area-inset-right))');
}
```

In my CSS:
```css
.example {
  right: max(15px, env(safe-area-inset-right));
}
```

I went this method instead of using `calc(max(...))` or `m#{a}x(...)` routes because the first one made the resulting code look messy, and the second one just felt too hacky. Anyways, hope this helps someone.

**Comment by nex3** [comment]
I've written up [a proposal](https://github.com/sass/language/blob/master/proposal/min-max.md) for solving this. @xzyfer, please take a look.

**Comment by xzyfer** [comment]
@nex3 are you able to add the production for CalcArithmetic in this
proposal?

**Comment by nex3** [comment]
Sorry, that's a typo, it should just say `CalcValue`. I'll fix it.

**Comment by nex3** [comment]
A week has passed since the proposal was released, so I've marked it as accepted in https://github.com/sass/language/commit/cf3283d5c3633757c57e32e7b05bee5f1ecc1f93. I'll write up specs soon.

**Comment by BenjaminHoegh** [comment]
> I ran into this issue today as well when converting my src from Less to Scss. I found that using Sass Function [unquote](http://sass-lang.com/documentation/Sass/Script/Functions.html#unquote-instance_method) rendered the correct output I was looking for.
> 
> In my Scss:
> 
> ```scss
> .example {
>   right: unquote('max(#{$global-margin}, env(safe-area-inset-right))');
> }
> ```
> 
> In my CSS:
> 
> ```css
> .example {
>   right: max(15px, env(safe-area-inset-right));
> }
> ```
> 
> I went this method instead of using `calc(max(...))` or `m#{a}x(...)` routes because the first one made the resulting code look messy, and the second one just felt too hacky. Anyways, hope this helps someone.

how do you then use `@support` to check for support for the `max()` function?

**Comment by jrjacobs24** [comment]
@BenjaminHoegh I'd assume you would just do the same thing. I tested this quickly on sassmeister.com and it converted correctly:

```scss
@supports (right: unquote('max(#{$global-margin}, env(safe-area-inset-right))')) {
  .example-class {
    right: unquote('max(#{$global-margin}, env(safe-area-inset-right))');
  }
}
```

Converted successfully to:
```css
@supports (right: max(15px, env(safe-area-inset-right))) {
  .example-class {
    right: max(15px, env(safe-area-inset-right));
  }
}
```

I didn't check to see if this instance of `@supports` works correctly in browser, however.

**Comment by swordray** [comment]
Define CSS `max()` and `min()` functions.

```sass
@function max($numbers...)
  @return m#{a}x(#{$numbers})

@function min($numbers...)
  @return m#{i}n(#{$numbers})
```

These will keep your own code clean.

```sass
.example
  right: max(15px, env(safe-area-inset-right))
```

**Comment by mrleblanc101** [comment]
It's been 3 years, will this be fixed ?

**Comment by nex3** [comment]
This has been supported for almost two years in Dart Sass. If it's a substantial issue for you, I suggest using that implementation.

**Comment by mrleblanc101** [comment]
We use gulp with gulp-sass, but the compiler seem customizable and does not default to dart-sass. I'll look into switching then.

**Comment by goyaltushar92** [comment]
any update on it?

**Comment by Awjin** [comment]
Any updates would have been posted here.

**Comment by edmundo096** [comment]
This is one of the first result for me when googling related issues.

As Natalie [mentioned above](https://github.com/sass/sass/issues/2378#issuecomment-618568291), it's already supported on the newer Dart-based Sass implementation, with the details about it and how it works on its documentation here: https://sass-lang.com/documentation/syntax/special-functions#min-and-max

If that doesn't works then most probably one must be using other implementation such as the Libsass (which as moment of writing it still doesn't supports it, as pointed on the previous link) or the Ruby based one (no longer supported).
If this is the case, the previously mentioned workarounds must be sufficient, like the `unquote()` function use and such.

Hope this doesn't makes more noise over the issue and helps anyone arriving here.

**Comment by swordray** [comment]
`alpha()` and `saturation()` is not supported in dart-sass.

**Comment by jakob-e** [comment]
### General Workaround

To deal with CSS-Sass naming conflicts you can **_use uppercasing to bypass Sass functions_**.

```
.class {
  padding-right: Max(15px, env(safe-area-inset-right));
}
```
The example above will be ignored by Sass as there is no uppercased **M**ax function (only **m**ax). CSS is not case-sensitive why Max will work just as well as max.

**Comment by nex3** [comment]
> `alpha()` and `saturation()` is not supported in dart-sass.

This isn't true. Dart Sass supports both the plain-CSS and Sass definitions of `alpha()` and `saturation()`.

**Comment by swordray** [comment]
> > `alpha()` and `saturation()` is not supported in dart-sass.
> 
> This isn't true. Dart Sass supports both the plain-CSS and Sass definitions of `alpha()` and `saturation()`.

I get this error at `sass@1.26.10`.

```
    SassError: $color: 0.9 is not a color.
        ╷
    158 │             background-color: color(var(--tertiary-system-background) alpha(0.9))
        │                                                                       ^^^^^^^^^^
```

**Comment by nex3** [comment]
I think you meant to use [`opacity()`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/opacity) in that example.

**Comment by swordray** [comment]
> I think you meant to use [`opacity()`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/opacity) in that example.

It is used by [postcss-color-function](https://github.com/postcss/postcss-color-function).

**Comment by nex3** [comment]
That's not standard CSS, and thus not supported by Sass.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
