### ISSUE TITLE
Passing and modifying arglist across mixins (Sass v3.5.0, Libsass v3.5.0 bug?)

### ISSUE THREAD

**Issue by bencergazda** [sass/sass#2382]
Reduced test case: https://www.sassmeister.com/gist/44340f52a27ad3e4fe61c9772de66d4f

Simplified: I have three mixins:
- a `main` with a few arguments
- a `router`, which calls the appropriate `main` mixin, depending on the situation
- a `helper`, which calls the original mixin (through the `router` mixin) with predefined arguments.

It works when I do not use named argument in the `helper` mixin, but if so, fails on **Sass v3.5.0.pre.rc.1 and LibSass v3.5.0.beta.2**.

Works ok in every cases with other Sass versions: **Sass v3.3.14, Sass v3.4.21, Sass 4.0.0.alpha.1**

Should I do something otherwise?

**Comment by nex3** [comment]
I'm not sure what the deal is with SassMeister, but when I test this locally I get the same output in 3.4.25, 3.5.0-rc.1, 3.5.1, 4.0.0.alpha.1, and bleeding edge 4.0.0:

```css
/* param1-value should be 'param___1' and param2-value should be param__2 in both cases, but if I use named arguam*/
.ordinal-arguments {
  /* OK - gets $param2 value from @mixin helper and has the correct $param1 value */
  param1-value: param___1;
  param2-value: param__2;
  param3-value: param3; }

.named-arguments {
  /* OK on Sass v3.3.14, Sass v3.4.21, Sass 4.0.0.alpha.1,
  but fails on Sass v3.5.0.pre.rc.1 and LibSass v3.5.0.beta.2,
  (gets $param2 value from @mixin helper, but $param1 has only its default value.)
  
  (Note: It works on Sass v3.5.0.pre.rc.1 and LibSass v3.5.0.beta.2, when: 
    - in @mixin helper I call "main" instead of "router" (line 23)
    - or if I do not edit the value of $param 2 (line 23) ) */
  param1-value: param___1;
  param2-value: param__2;
  param3-value: param3; }
```

If you can reproduce this with LibSass, I suggest filing an issue against [the libsass repo](https://github.com/sass/libsass/issues/new).
