### ISSUE TITLE
margin / padding compilation gives incorrect result when using variables prefixed with "-"

### ISSUE THREAD

**Issue by pzaj2** [sass/sass#2385]
I'm using node-sass 4.5.3 that use libsass (3.5.0.beta.2). I think it's best to use an example here:

SASS:
```sass
$var: 5em;

.class {
    margin: 0 0 -$var 0;
}
```

Expected:
```css
.class {
    margin: 0 0 -5em 0;
}
```

Actual:
```css
.class {
    margin: 0 -5em 0;
}
```

I found a workaround for that I use currently - enclosing whole expression with brackets:
```sass
$var: 5em;

.class {
    margin: 0 0 (-$var) 0;
}
```

**Comment by nex3** [comment]
This is intentional. SCSS isn't whitespace-sensitive, so writing `0 -$var` is equivalent to `0 - $var`, which is parsed as subtraction. Enclosing it in parentheses is the correct way to express this.

**Comment by pzaj2** [comment]
@nex3 I see, should it be consistent when dealing with variables then? Look at this example:

```sass
$minusVar: 0 -5em;

.class {
    margin: 0 0 $minusVar 0;
}
```

It produces "incorrect" result, $minusVar is "0 -5em", not as one would expect - an expression that was evaluated:

```css
.class {
  margin: 0 0 0 -5em 0;
}
```

So in case of variables it is whitespace-sensitive, because using `0 - 5em` will result in variable set to `-5em`. This is what made me create this issue at first place. I suppose that, if my first example **is** intentional, then this one is not?

**Comment by nex3** [comment]
The difference is that, for numbers, the minus sign is parsed as part of the number itself rather than an operator that applies to the number, as per [the CSS syntax spec](https://drafts.csswg.org/css-syntax-3/#consume-a-number).
