### ISSUE TITLE
Getting error after upgrading to MacOS High Sierra

### ISSUE THREAD

**Issue by Mttylzq** [sass/sass#2389]
MacOS 10.13
Whenever a sass command is run on the command line, I get this error:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by Mttylzq** [comment]
When install sudo gem install sass
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

**Comment by Mttylzq** [comment]
reinstall compass fix it
sudo gem install -n /usr/local/bin sass

**Comment by Alan-W** [comment]
Maybe it's your compass has hung up, you can execute: sudo gem install compass to fix it.

**Comment by mdmasumbillah** [comment]
Thanks @Mttylzq 

Solved this problem:
sudo gem install -n /usr/local/bin sass

**Comment by TheDeterminator** [comment]
I have read that using sudo to install gems is dangerous in that it can overwrite your hard drive or publish sensitive information to the internet: 
https://github.com/calabash/calabash-ios/wiki/Best-Practice%3A--Never-install-gems-with-sudo

Does anyone know if this is still true ?

**Comment by FlorianHeigl** [comment]
Installing it elsewhere is not "solving"??

**Comment by sean256** [comment]
> Installing it elsewhere is not "solving"??

With the way MacOS is now, this is as solved as it's gonna get

**Comment by dylan-k** [comment]
> With the way MacOS is now, this is as solved as it's gonna get

@sean256 What is it about the MacOS that makes you have to install in a different directory?
