### ISSUE TITLE
[question] issue with Sass absolute paths

### ISSUE THREAD

**Issue by trsh** [sass/sass#2392]
I have a node project 'app'. And inside it, there is folder /styles and inside this folder styles.scss.

styles.scss imports sass from node library with `@import '~xxx/src/core.scss'`

This core.scss has an non relative import like `@import 'src/_mixins.scss'`

This gives an error, because it tries to find src/_mixins.scss inside my 'app' project. At least I suspect this.

Can I some-have fix this, without touching the Node library or coping stuff to my app?

**Comment by nex3** [comment]
Are you using Ruby Sass or node-sass?

**Comment by trsh** [comment]
@nex3 node-sass. And is solved this with includePaths option. So now when importing it looks up also there and it works fine.
