### ISSUE TITLE
sass 监视其它盘路径问题文件出现的问题

### ISSUE THREAD

**Issue by ZongDuCha** [sass/sass#2393]
ruby和sass都安装成功（C盘）
![image](https://pic1.zhimg.com/50/v2-355bca387e222e5a6302230209b0011c_hd.jpg)

如果在F盘建文件夹并且监视就会一直卡在这里：
![image](https://pic1.zhimg.com/50/v2-c5cba6ca39b156f19758853764c906b0_hd.jpg)

但是只要在C盘建文件夹并且监视就没什么问题：

![image](https://pic3.zhimg.com/50/v2-15b84a71d6f60c6e4ea7e3e6b804e89a_hd.jpg)

请问这是什么原因？

知乎同题：https://www.zhihu.com/question/67224713

**Comment by nex3** [comment]
We use the [`listen`](https://github.com/guard/listen) package to listen for changes on the filesystem. I suggest filing an issue against them if you aren't seeing changes reported on the F drive. Note that on Windows, we set `poll: true`, so we shouldn't be interacting with the native listen code at all.
