### ISSUE TITLE
Use of sass logo in website

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [sass/sass#2395]
I am giving the finishing touches of my website, designed by sass of course, and I want to put the sasa logo in the footer of the page, among others. What are the terms of use for the logo? Also, is an svg version available? If not, can I create an svg out of the raster image and use the same?

**Comment by nex3** [comment]
@jina Can you comment on this?

**Comment by jina** [comment]
Here are the terms and downloads! http://sass-lang.com/styleguide/brand
