### ISSUE TITLE
sass error

### ISSUE THREAD

**Issue by ghost** [sass/sass#2396]
I got this error

WARNING on line 1 of C:\Users\TECH:
This selector doesn't have any properties and will not be rendered.
WARNING on line 2 of C:\Users\TECH:
This selector doesn't have any properties and will not be rendered.
Errno::ENOENT: No such file or directory @ rb_sysopen - VALLEY\Desktop\MyProject\NewWebsite\home.scss
  Use --trace for backtrace.

when I write 
C:\Ruby23-x64> sass C:\Users\TECH VALLEY\Desktop\MyProject\NewWebsite\home.scss C:\Users\TECH VALLEY\Desktop\MyProject\CSS\style.css

 how I can fix it please ??

**Comment by nschonni** [comment]
You've got a space in your path, so it's treating it as separate parameters. Put double quotes around the file and output path values

**Comment by ghost** [comment]
yes , It treated .
Thank you very much.
