### ISSUE TITLE
Haml::Util::ruby1_8? workaround for Unicode in IronRuby

### ISSUE THREAD

**Issue by CrazyPyro** [sass/sass#24]
EDIT: This seems to be a more overarching issue with Haml/Sass making incorrect assumptions about Unicode capabilities based on IronRuby 1.1.1 claiming to be Ruby 1.9.  Hence the rename.

I ran across this error while upgrading a project on an older Haml/Sass, Rails, and IronRuby stack to the latest versions of each (3.0.23, 3.0.1, 1.1.1).

**Comment by nex3** [comment]
I think this is a bug in IronRuby. All of the unicode classes in that regexp go in the right direction.

I'll leave this open to remind myself to add a workaround.

**Comment by CrazyPyro** [comment]
Thanks for looking into this.
I also posted this on IronRuby's issue tracker: http://ironruby.codeplex.com/workitem/5396

**Comment by CrazyPyro** [comment]
> to remind myself to add a workaround.

This is what I used on lib/sass/scss/rx.rb:52 

> s = if Sass::Util.ruby1_8? or ::RUBY_ENGINE=="ironruby"

**Comment by CrazyPyro** [comment]
After patching the above, I ran into more related errors.  All Haml pages returned by Rails had this error:
    undefined method `encode' for "@charset \"":String

So it looks like the workaround needs to be more general than my initial suggestion.
Revised: 

/lib/haml/util.rb
      def ruby1_8?
    -      Haml::Util::RUBY_VERSION[0] == 1 && Haml::Util::RUBY_VERSION[1] < 9
    +      ::RUBY_ENGINE=="ironruby" || # IronRuby claims to be 1.9, but is not compatible
    +      (Haml::Util::RUBY_VERSION[0] == 1 && Haml::Util::RUBY_VERSION[1] < 9)
      end

**Comment by nex3** [comment]
Merge remote branch 'refs/remotes/haml/stable' into stable

Closed by 422b6333e15ad9cfdabc559ba600bb02c0e676bf
Closed by 422b6333e15ad9cfdabc559ba600bb02c0e676bf
