### ISSUE TITLE
Re-declare mixins _after_ they are used

### ISSUE THREAD

**Issue by powerbuoy** [sass/sass#240]
I know we can already re-declare @mixins like this:

``` scss
@mixin foo {color: red}
@mixin foo {color: blue}
p {@include foo}
```

Becomes:

``` scss
p {color: blue}
```

_However_, something I noticed today is that if the @include comes
before the re-declaration it won't take:

``` scss
@mixin foo {color: red}
p {@include foo}
@mixin foo {color: blue}
```

Becomes:

``` scss
p {color: red}
```

I would like it, too, to become:

``` scss
p {color: blue}
```

**Comment by chriseppstein** [comment]
I think this warrants some thought, but it's a big deal to change this behavior. you're going to have to work around this limitation for now.

**Comment by chriseppstein** [comment]
Can you provide some more details on your use case. why can't you simply restructure your code?

**Comment by powerbuoy** [comment]
Sure, here's what I wrote to Nathan before:

It may seem like my problem could be solved quite easily by moving
code around, the problem is that I work in a framework that supports
extending sites and styles and when you do that _your_ site's CSS code
will come _last_ in the generated CSS-file (which is obviously
necessary for specificity reasons). So if I extend one site that
declares and uses a lot of mixins, but then from my own site want to
override one of those mixins the overridden mixin will only be used in
my own code - _not_ the code in the extended site.

Edit: A simple example would be the style I extend declares a blue `@button` and uses it in several places but in my new style I'd like the button to be green so it would be awesome to just go `@mixin button {background: green}` and change my own buttons _as well_ as the other style's buttons.

**Comment by nex3** [comment]
This is analogous to the change we've been considering for a while to the variable semantics to bring them in line with the proposals being made to CSS proper. If we change one, we'll certainly have to change the other.

**Comment by judowalker** [comment]
Hi, do you guys have any plans on implementing this? I'm using Bootstrap 4 and would like to override some of their mixins.

**Comment by olsonpm** [comment]
I got here looking for the same thing as judowalker.  I would like to override one of bootstrap3's mixins with the one in bootstrap4's.  That way I don't have to worry about updating all of bootstrap for our sizable application.

**Comment by gzzz** [comment]
Almost 5 years and still nothing?..
That's sad.

**Comment by martpie** [comment]
Bump-ip-up. Typically the usecase is to override Bootstrap mixins when your design forces you to remove some of the default framework's CSS properties.

**Comment by AndyOGo** [comment]
For this feature use `less`, since it is going the declarative approach, you get it out of the box.
`Sass`'s approach is fundamentally different, it's imperative.

**Comment by DaleMckeown** [comment]
+1 for this. I only just realised that SASS doesn't work the same way that LESS does in this respect.

**Comment by nex3** [comment]
I'm surprised to see that this is still open. It's not the sort of thing that's at all feasible—mixins can have side effects like setting variables, and those variables can be used in arbitrary places, including in control flow directives like `@if` and `@for`. In the general case, behavior like this would require that we re-run the entire stylesheet up to the current point if you re-define a mixin. It would also mean we'd never be able to add the ability to dynamically define mixins or likely to dynamically include Sass files.

**Comment by ArmorDarks** [comment]
Continuing on necroing this thread, my few cents...

> So if I extend one site that
> declares and uses a lot of mixins, but then from my own site want to
> override one of those mixins the overridden mixin will only be used in
> my own code - not the code in the extended site.

I think that issue arises because Sass so far does not have any means for code encapsulation, thus any mixins changes affects everything globally. To compare with JS, your sites would be module (which is a closure), and you'd be able to freely override anything within closure and be sure that it will never affect global scope. Well, almost.

But, anyway, I'd advise not to alter mixins. It just like overriding functions — in most times it isn't ok thing to do.

**Comment by martpie** [comment]
> But, anyway, I'd advise not to alter mixins. It just like overriding functions — in most times it isn't ok thing to do.

Here is one usecase (a bit different from what the issue is about though). I do custom builds of Bootstrap 4, and I need to override default mixins and write my own to meet our guidelines. A bit like `!default` is for variables. 

Just my two cents. Not really related with the issue.

**Comment by ArmorDarks** [comment]
> Here is one usecase (a bit different from what the issue is about though). I do custom builds of Bootstrap 4, and I need to override default mixins and write my own to meet our guidelines. A bit like !default is for variables.

It's understandable that for any action there should a justified situation.

Though, maybe in that situation it would be better to create new mixin. instead of overriding the existing one? Or you wanted Bootstrap to use your own overridden mixin instead?

**Comment by martpie** [comment]
> Or you wanted Bootstrap to use your own overridden mixin instead?

Yes exactly. I want to override the default one, so the rest of the custom Bootstrap will compile nicely. Again, there are workarounds, but redeclaring mixins would save us some time and would be "cleaner".

**Comment by ArmorDarks** [comment]
Ah, I see. Seems like there is no way that can be done in Sass — Bootstrap mixins will always takes precedence, since they are declared afterwards, and declaring overrides after Bootstrap is too late.

As far as I know, in Less it will work, because Less lazily computes mixins in the end, and it really quite weird thing. Anyway, because mentioned by @nex3 issues I think this isn't a proper solution.

The only thing I could think now, is if all mixins in Sass would hoist to the top, like functions do in JavaScript. However, this will mean simply that last declared mixin will be always used for the whole stylesheet. And it isn't ideal too.

**Comment by AndyOGo** [comment]
I would vote for the `!default` to support `@mixin` and maybe others too, not just `$variables`

**Comment by ghost** [comment]
Everyone keeps talking about overriding mixins but what about if your mixins are overriding your main code. Becuase of this i cant make my site mobile responsive what could be the issue. So lets say i have 

```scss
&__main-tittle{
      max-width:100%;

    @mixin atSmall{
       max-width:50%; this code here will override my code max-width:100%; 
    }
}
```

which is messing up my  site and making it hard for me to style my site for mobile. 
I been searching over over and am lost,
And confused please someone help me Im going crazy.
