### ISSUE TITLE
After compilation, styles are the same

### ISSUE THREAD

**Issue by SilencerWeb** [sass/sass#2400]
I have a problem with styles' compilation. Example:

```
.link
    text-decoration: none
    color: #fff
```

Output:
```
.link {
  text-decoration: none;
  color: #fff;
}
```

If I change the name of the property or add new styles, it will compile and everything will be okay:

```
.link
    font-size: 14px
    text-decoration: none
    background-color: #fff
```

Output:
```
.link {
    font-size: 14px;
    text-decoration: none;
    background-color: #fff;
}
```

BUT! If I change VALUE of the property, it will compile, but styles will be same! For example:

```
.link
    font-size: 14px
    text-decoration: none
    background-color: red
```

Output:
```
.link {
    font-size: 14px;
    text-decoration: none;
    background-color: #fff;
}
```

How is it? I don't know what can be the reason for it. System? Console? Gulp? Now I'm working on the MacBook, but before I worked on the computer with Windows and hadn't ever had such problems. If you need more information - just ask.

System: macOS Sierra 10.12.6
Console: iTerm2 3.1.5 with zsh 5.2
Project: https://github.com/SilencerWeb/spark17

**Comment by nex3** [comment]
What version of Sass are you using? How are you invoking it?

**Comment by SilencerWeb** [comment]
@nex3 gulp-sass version 3.1.0. Invoke with gulp when files are changed.

**Comment by nex3** [comment]
This is the repository for Ruby Sass. I suggest filing an issue against [gulp-sass](https://github.com/dlmanning/gulp-sass/issues/new).
