### ISSUE TITLE
Markdown to HTML documentation build seems to be broken

### ISSUE THREAD

**Issue by gpakosz** [sass/sass#2403]
Hello,

While studying options I noticed the documentation is hard to read.
It seems to me the source Markdown content tries to add anchors but ends up messing the output:

```
{#load_paths-option} `:load_paths`
: An array of filesystem paths or importers which should be searched
  for Sass templates imported with the [`@import`](#import) directive.
  These may be strings, `Pathname` objects, or subclasses of {Sass::Importers::Base}.
  This defaults to the working directory and, in Rack, Rails, or Merb,
  whatever `:template_location` is.
  The load path is also informed by {Sass.load_paths}
  and the `SASS_PATH` environment variable.
```
is rendered as
![image](https://user-images.githubusercontent.com/553208/32885230-306b242e-cabd-11e7-9bd0-f65353960dcf.png)

and as you can see `#load_paths-option` inserted as content instead of an `id` on the `<p>` element:
![image](https://user-images.githubusercontent.com/553208/32885277-5089d78c-cabd-11e7-9fc5-aca27c280c36.png)

**Comment by gpakosz** [comment]
Thank you

**Comment by gpakosz** [comment]
Hey @nex3 👋 It seems http://sass-lang.com/documentation wasn't updated with the fix.

![image](https://user-images.githubusercontent.com/553208/34540334-74b1f8aa-f0d4-11e7-83ad-8ec212144144.png)

**Comment by nex3** [comment]
Looks like I forgot to deploy the update. Done!

**Comment by SKalt** [comment]
I'm getting this error again.
```html
<p>## List Functions #list-functions</p>
```
Within the sass repo, how do you build the docs, so that I can test the error (and future fix) out?

**Comment by nex3** [comment]
We're working on [totally rewriting and revamping the docs](https://github.com/sass/sass-site/projects/1), so rendering bugs with the old docs aren't a high priority right now.
