### ISSUE TITLE
:importer option is not documented along with :load_paths and :filesystem_importer options

### ISSUE THREAD

**Issue by gpakosz** [sass/sass#2404]
Hello,

While studying SASS, I was having difficulties reconciling the observed behavior with the documentation for `:load_paths` and `:filesystem_importer` options.

So I decided to look at the source code and stumbled upon [`Engine#normalize_options()`](https://github.com/sass/sass/blob/a4b3e8c0c7073573cfd8df111eb25c8295851ebe/lib/sass/engine.rb#L186-L188)

```
# If the `:filename` option is passed in without an importer,
# assume it's using the default filesystem importer.
options[:importer] ||= options[:filesystem_importer].new(".") if options[:filename]
```

as well as [`ImportNode#import()`](https://github.com/sass/sass/blob/a4b3e8c0c7073573cfd8df111eb25c8295851ebe/lib/sass/tree/import_node.rb#L45-L56)
```
paths = @options[:load_paths]

if @options[:importer]
  f = @options[:importer].find_relative(
    @imported_filename, @options[:filename], options_for_importer)
  return f if f
end

paths.each do |p|
  f = p.find(@imported_filename, options_for_importer)
  return f if f
end
```

And it was totally not obvious to me that `load_paths` won't even have a chance to run if there's an `@options[:importer]`.

**Comment by nex3** [comment]
The `:importer` option is intentionally private; it's used internally to track which importer imported the current stylesheet.

When an `@import` appears in a stylesheet, the importer that imported that stylesheet has a chance to resolve it as a *relative import*. It's important that relative imports take precedence over absolute ones: this is what allows Sass libraries to confidently import other stylesheets within the same library without worrying about name conflicts elsewhere on the user's system.
