### ISSUE TITLE
Case-insensitive attribute selectors support

### ISSUE THREAD

**Issue by ffoodd** [sass/sass#2405]
Hi there,

I'm trying to use case-insensitive attribute selector (e.g. `[charset="utf-8" i]`) and am currently unable to compile because of this. I got:

`Error: unterminated attribute selector for charset` when trying to compile with node-sass. I searched Sass changelogs and didn't find any mention of support for this feature.

May Sass support this kind of selector? As it's part of CSS spec and is already supported by many browsers, it would be great.

**Comment by ffoodd** [comment]
It seems that Sass-only does support it (tested in [this codePen](https://codepen.io/enguerranws/pen/GOQjpZ) so it might be an issue with node-sass.

Could someone confirm this?

**Comment by nex3** [comment]
I can confirm that this works with Ruby Sass. Please file an issue against [LibSass](https://github.com/sass/libsass).
