### ISSUE TITLE
Sass Installation error for OSX Sierra

### ISSUE THREAD

**Issue by jordan-miguel** [sass/sass#2406]
I'm trying to install SASS, but failing miserably.

I already have Ruby & Homebrow installed.
After running `sudo gem install sass` I get the following errors -

1. `ERROR:  Error installing sass:
        ERROR: Failed to build gem native extension.`
2. `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h`

Have done a fair bit of research on stackoverflow and can't seem to find a solution.

**Comment by nex3** [comment]
Duplicate of #2357. I believe [this comment](https://github.com/sass/sass/issues/2357#issuecomment-337168358) describes a solution.

**Comment by jordan-miguel** [comment]
Sorry, I found a solution elsewhere, should've deleted the question!

**Comment by nex3** [comment]
Was your solution the same as described above?

**Comment by jordan-miguel** [comment]
Yes it was. :)
