### ISSUE TITLE
Merge/join folders for @import

### ISSUE THREAD

**Issue by OvalMedia** [sass/sass#2412]
Hello,

I have a base folder with all my sass partials. Now I want to have another folder ("project") that is initially empty and inherits from that base folder. So when I want to make changes I copy a partial from the base folder and modify it there.

Now I would like that sass imports all partials from base and mege them with with the partials from project.

Example:

```
base
-- _partial1.scss
-- _partial2.scss
-- _partial3.scss

project
-- _partial2.scss

```
So in the end sass compiles partials 1 and 3 from base and partial 2 from project. 
Is this possible somehow?

Thank you.

**Comment by nex3** [comment]
You can write [custom importer](http://sass-lang.com/documentation/Sass/Importers/Base.html) that has this behavior.
