### ISSUE TITLE
[Feature request] Decimal to hexadecimal helper function

### ISSUE THREAD

**Issue by Fleuv** [sass/sass#2419]
This feature request was created regarding [this question on stackoverflow](https://stackoverflow.com/questions/15961089/how-to-convert-integer-to-hex-in-sass). Where you will find two possible implementations for converting a decimal to a hexadecimal. 

Please consider implementing this new helper function.

> Submitted by [JPGringo](https://stackoverflow.com/users/1588426/jpgringo)
> ```
> @function dec-to-hex($d) {
>     $hexVals: "A" "B" "C" "D" "E" "F";
>     $base: 16;
>     $quotient: $d;
>     $result: "";
>     @if $d == 0 {
>         $result: "00";
>     }
>     @while $quotient != 0 {
>         $mod: $quotient % $base;
>         $quotient: floor($quotient / $base);
>         @if $mod > 9 {
>             $mod: nth($hexVals, $mod - 9);
>         }
>         @if $d < $base {
>             $result: "0" + $mod;
>         } @else {
>             $result: $mod + $result;
>         }
>     }
>     @return $result;
> }
> ```

> Submitted by [Pierpaolo Cira](https://stackoverflow.com/users/2459308/pierpaolo-cira)
> ```
> @function decToHex($dec) {
>     $hex: "0123456789ABCDEF";
>     $first: (($dec - $dec % 16)/16)+1;
>     $second: ($dec % 16)+1;
>     @return str-slice($hex, $first, $first) + str-slice($hex, $second, $second)
> }
> ```

Unfortunately I hardly know anything more then the basics of sass, please let an expert/the community review and optimize this function. I will advocate for the implementation of this feature into the core and I will try to help to make that possible, starting with submitting this request.

**Comment by nex3** [comment]
We try to keep the set of functions that are shipped with Sass pretty lean—we only add new ones when there's important functionality that's impossible or extremely difficult to to achieve with a pure-Sass function, or when it's likely to be useful to many many Sass authors. I don't think this fits either criterion.
