### ISSUE TITLE
Bogus color warning?

### ISSUE THREAD

**Issue by glebm** [sass/sass#2424]
Users have been reporting the following warning from Sass v3.5.2 and Sass v3.5.3

```
WARNING on line 4, column 7 of gems/bootstrap-4.0.0.beta2/assets/stylesheets/bootstrap/_root.scss:
You probably don't mean to use the color value `blue' in interpolation here.
It may end up represented as #0000ff, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "blue").
If you really want to use the color value here, use `"" + $color'.
full log output for each `$color`
```

This is with regards to the following code:

https://github.com/twbs/bootstrap/blob/8b8999b07aecd0213ef0c984c6f8e104aef2c7f5/scss/_root.scss#L1-L5

However, these variable *are* quoted here: 

https://github.com/twbs/bootstrap/blob/8b8999b07aecd0213ef0c984c6f8e104aef2c7f5/scss/_variables.scss#L49-L51

@nex3 Is this a buggy warning or are we doing something wrong? Thanks

**Comment by glebm** [comment]
Nevermind, user error.

**Comment by jdavidbakr** [comment]
@glebm - I just started getting this warning (updated to Laravel Mix version 4) and it looks to me like it's a problem with bootstrap's sass - which is what you are linking to.  What did you end up figuring out what the issue was?

**Comment by jdavidbakr** [comment]
Found it - my issue was from this thread: https://github.com/twbs/bootstrap-rubygem/issues/130 - apparently the older version of Laravel Mix was using a different sass processor that didn't fire this warning.
