### ISSUE TITLE
undefined method `unshift' for ">":String

### ISSUE THREAD

**Issue by guigs** [sass/sass#2426]
I'm having this error when running a test after upgrade to sass 3.5.4 (from 3.4.25)

     Failure/Error: = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
     
     ActionView::Template::Error:
       undefined method `unshift' for ">":String
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/sequence.rb:74:in `block in resolve_parent_refs'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/sequence.rb:68:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/sequence.rb:68:in `resolve_parent_refs'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/comma_sequence.rb:38:in `block in resolve_parent_refs'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/comma_sequence.rb:37:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/comma_sequence.rb:37:in `resolve_parent_refs'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:439:in `visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `block (2 levels) in visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `block in visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:442:in `visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `block (2 levels) in visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:444:in `block in visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:442:in `visit_rule'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `block in with_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `with_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `block in with_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:88:in `with_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `block in with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:135:in `with_frame'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/stack.rb:79:in `with_base'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:162:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `map'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/base.rb:36:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:161:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/root_node.rb:36:in `css_tree'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/tree/root_node.rb:20:in `render'
     # .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/engine.rb:290:in `render'
     # .../ruby/gems/2.3.0/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
     # .../ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
     # .../ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:92:in `[]'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355:in `find_asset'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:336:in `digest_path'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:325:in `asset_path'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `each'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `detect'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/helpers/asset_url_helper.rb:198:in `asset_path'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/helpers/asset_url_helper.rb:343:in `stylesheet_path'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/helpers/asset_tag_helper.rb:118:in `block in stylesheet_link_tag'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/helpers/asset_tag_helper.rb:114:in `map'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/helpers/asset_tag_helper.rb:114:in `stylesheet_link_tag'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:185:in `block in stylesheet_link_tag'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `map'
     # .../ruby/gems/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:183:in `stylesheet_link_tag'
     # ./app/views/layouts/application.html.slim:6:in `_app_views_layouts_application_html_slim__1414468857276379518_47163020169160'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/template.rb:157:in `block in render'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:168:in `instrument'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/template.rb:352:in `instrument_render_template'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/template.rb:155:in `render'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/renderer/renderer.rb:23:in `render'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/rendering.rb:103:in `_render_template'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/rendering.rb:83:in `render_to_body'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/rendering.rb:24:in `render'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/rendering.rb:36:in `render'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # .../ruby/2.3.0/benchmark.rb:308:in `realtime'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # .../ruby/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/implicit_render.rb:33:in `default_render'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/base.rb:186:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/rescue.rb:20:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `block in instrument'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `instrument'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
     # .../ruby/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/base.rb:124:in `process'
     # .../ruby/gems/2.3.0/gems/actionview-5.1.3/lib/action_view/rendering.rb:30:in `process'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal.rb:189:in `dispatch'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal.rb:253:in `dispatch'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/routing/route_set.rb:31:in `serve'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/journey/router.rb:46:in `block in serve'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/journey/router.rb:33:in `each'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/journey/router.rb:33:in `serve'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
     # .../ruby/gems/2.3.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:415:in `call_app!'
     # .../ruby/gems/2.3.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:271:in `mock_call!'
     # .../ruby/gems/2.3.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:185:in `call!'
     # .../ruby/gems/2.3.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
     # .../ruby/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # .../ruby/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # .../ruby/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/cookies.rb:613:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:97:in `run_callbacks'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
     # .../ruby/gems/2.3.0/gems/bugsnag-5.3.3/lib/bugsnag/rack.rb:34:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # .../ruby/gems/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:36:in `call_app'
     # .../ruby/gems/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `block in call'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
     # .../ruby/gems/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/request_id.rb:25:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
     # .../ruby/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # .../ruby/gems/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/static.rb:125:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
     # .../ruby/gems/2.3.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
     # .../ruby/gems/2.3.0/gems/capybara-2.15.1/lib/capybara/server.rb:44:in `call'
     # .../ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
     # .../ruby/2.3.0/webrick/httpserver.rb:140:in `service'
     # .../ruby/2.3.0/webrick/httpserver.rb:96:in `run'
     # .../ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `unshift' for ">":String
     #   .../ruby/gems/2.3.0/gems/sass-3.5.4/lib/sass/selector/sequence.rb:74:in `block in resolve_parent_refs'

The scss it is trying to analyze is:

```scss
  .form-group {
    margin-left: $padding-small-horizontal;

    &:first-child {
      margin-left: 0;
    }

    > & {
      margin-left: 0;
    }
  }
````

**Comment by nex3** [comment]
I believe this was fixed by f35120e513382973bcafab6b2a559e33a3c8a502.

**Comment by guigs** [comment]
@nex3 I just removed the rule from my css and moved on. But I remember having tried with sass master and I was still able to reproduce it, so I don't believe f35120e513382973bcafab6b2a559e33a3c8a502 fixes it.

**Comment by nex3** [comment]
It works for me on master:

```
$ echo 'a {> & {b: c}}' | ./bin/sass --scss
> a {
  b: c; }
```
