### ISSUE TITLE
SASS treats "@if true && false" as "true" instead as a syntax error

### ISSUE THREAD

**Issue by agabrys** [sass/sass#2429]
Hi,
SASS does not support usage of the `&&` and `||` operators in conditions (e.g. `@if $variable1 && $variable2`). Compilers fail compilation if any conditions contain `||`, but unfortunately `&&` is always treated as `true`.

The following code:

    .example1 {
        content: 'if true && false';
        content: 'is';
        @if true && false {
            content: 'true';
        } @else {
            content: 'false';
        }
    }

    .example2 {
        content: 'if false && true';
        content: 'is';
        @if false && true {
            content: 'true';
        } @else {
            content: 'false';
        }
    }

    .example3 {
        content: 'if false && false';
        content: 'is';
        @if false && false {
            content: 'true';
        } @else {
            content: 'false';
        }
    }

after the compilation is equal to:

    .example1 {
      content: 'if true && false';
      content: 'is';
      content: 'true';
    }

    .example2 {
      content: 'if false && true';
      content: 'is';
      content: 'true';
    }

    .example3 {
      content: 'if false && false';
      content: 'is';
      content: 'true';
    }

(verified on [Sass.js](http://sass.js.org/))

It would be great if SASS compilers can fail compilation.

**Comment by nex3** [comment]
This is valid syntax—`true && false` is parsed as a space-separated list containing `true`, `&`, `&`, and `false`. It may be worth adding a warning for `&&`, though, since it certainly looks confusing.
