### ISSUE TITLE
inclusion in Gemfile impacts application boot-up time

### ISSUE THREAD

**Issue by aspiers** [sass/sass#243]
I've just upgraded to Rails 3.1, and even though I don't have any .sass or .scss files yet, I notice that when I add `gem 'sass'` to my `Gemfile`, application boot-up time immediately takes about 1 second longer (timed via `time rake route`).  In comparison, most other well-behaving gems seem to only add around 0.1s.  Happy to provide further debug on request.

**Comment by chriseppstein** [comment]
On my machine running:

```
time echo "div { color: red;}" | scss
```

Causes ruby to start, scss to load, and a compilation to occur in about 0.5s.

When I use IRB to time the sass boot with:

``` ruby
def time
  s = Time.now
  yield 
  puts "#{Time.now - s}"
end

time { require 'sass'}
```

It takes 0.35s on my machine.

Maybe your machine is much slower than mine? So ya, some more debugging is required.

**Comment by chriseppstein** [comment]
Without doing any profiling, my spidey sense says that is that Regex compilation at boot time is non-trivial and could be eliminated until the first RX constant is looked up.

**Comment by nex3** [comment]
Lazy-loading `RX`, if that is indeed the problem, wouldn't be the easiest thing to do. It's referenced at load time in a number of places.

Without further debugging information, though, I don't think there's anything we can act on here.

**Comment by chriseppstein** [comment]
Would love to see some profiling data. Anyone interested? @cheba?

**Comment by nex3** [comment]
Closing due to lack of response.
