### ISSUE TITLE
sass-lang website not working

### ISSUE THREAD

**Issue by chandanch** [sass/sass#2430]
The website is showing an error: 'Application Error'
Url: http://sass-lang.com/

**Comment by nex3** [comment]
This has been fixed.

**Comment by hinok** [comment]
Hey @nex3,
It seems that website is down again :(

![image](https://user-images.githubusercontent.com/1313605/34762839-875ed968-f5e9-11e7-9e75-6f6f05b88cbe.png)

**Comment by chandanch** [comment]
@hinok The website is back again check it out.
