### ISSUE TITLE
Improve interoperability with postcss

### ISSUE THREAD

**Issue by aleclarson** [sass/sass#2433]
Using **sass** in tandem with **postcss** is a dream come true. Sometimes, **postcss** plugins provide new syntax that throws **sass** for a loop ([example](https://github.com/jonathantneal/postcss-short/issues/6)). Luckily, **sass** doesn't complain when custom attribute _names_ are used, but the same cannot be said for custom attribute _values_.

I'm proposing a `strict: false` option that tells **sass** to ignore errors within attribute _values_, and instead pass the value through. To avoid breakage, `strict` would default to true.

Here's an example that uses [`postcss-short`](https://github.com/jonathantneal/postcss-short) for shorthand syntax where `position` is also used to specify `top` but `right/bottom/left` are skipped.

```css
// the original snippet
div {
  position: absolute 0 * *;
}

// sass considers this an error, pass it through unaltered
div {
  position: absolute 0 * *;
}

// postcss transforms into valid css
div {
  position: absolute;
  top: 0;
}
```

Without `strict: false` specified, **sass** throws an error:
*Invalid CSS after "... absolute 0 0 \*": expected expression (e.g. 1px, bold), was "\*;"*

To validate the CSS output like **sass** currently does, users of **postcss** would need a plugin that fills that role to be at the end of the pipeline.

Is this something the **sass** team would consider adding?

Thanks! 👍

**Comment by nex3** [comment]
This isn't something we can add. Sass has its own syntax and semantics, and we can't just fall back to passing through anything we don't understand—that would hide syntax errors, make it much harder to safely add features, and generally make the language behave in a confusing way.

As a side-note, this sort of thing is why I recommend that CSS extensions like `postcss-short` try to stick to syntactically-valid CSS, so it can be interoperable with other tools. For example, instead of using `*` it could use `_`, which is a valid CSS identifier with no other meaning attached to it.

**Comment by aleclarson** [comment]
> that would hide syntax errors, make it much harder to safely add features, and generally make the language behave in a confusing way

When using `strict: false`, the user takes responsibility to ensure their styles compile without error when upgrading Sass to a new major/minor version. Although that's riskier in theory, how often does Sass really add new syntax?

Shouldn't a preprocessor like Sass make the effort to be interoperable with postprocessors, rather than the other way around? People should be able to benefit from Sass without sacrificing enticing new syntax provided by PostCSS plugins. Since PostCSS plugins are inherently community driven, there is more room for experimental syntax there than in Sass.

I agree that `postcss-short` could change its default syntax, but why should Sass punish users that want to use a syntax plugin that Sass may or may not ever use in the future. Like I said above, leave that decision to the end user.

Thanks for hearing me out! 💯

**Comment by nex3** [comment]
Adding flags that fundamentally affect how stylesheets are parsed isn't something we're ever going to do. It fragments the language and makes it much more difficult for users to have confidence that they can re-use stylesheets, even if they aren't setting the flag themselves.

Let me give you an example of why the `postcss-short` syntax in particular would be a problem. Suppose you have:

```scss
div {
  position: absolute 0 * *;
}
```

and you want to add a left position. You might try to change this to:

```scss
div {
  position: absolute 0 * 10px;
}
```

But this *is* valid Sass syntax: the `*` is interpreted as multiplication and you get `position: 0` which is definitely not what you intended. This is what I mean when I say allowing arbitrary unparseable text adds confusion.
