### ISSUE TITLE
SASS --style compressed does not minify CSS

### ISSUE THREAD

**Issue by mgpdattila** [sass/sass#2438]
The --style compressed command stopped minifying CSS and produces compact output only. There are no commands in SASS that will produce minified output.

This problem appeared in mid 2017 and has not been corrected after several re-installations and upgrades on two different machines.

**Comment by nex3** [comment]
What implementation and version of Sass are you using? I can't reproduce this with Ruby Sass 3.5.5.

**Comment by mgpdattila** [comment]
dans-mbp:Tenants dan$ sass -v
Sass 3.5.5 (Bleeding Edge)
dans-mbp:Tenants dan$

**Comment by mgpdattila** [comment]
I just updated Ruby and SASS both.

**Comment by nex3** [comment]
```
$ gem install sass --version 3.5.5
Fetching: sass-3.5.5.gem (100%)
Successfully installed sass-3.5.5
Parsing documentation for sass-3.5.5
Installing ri documentation for sass-3.5.5
1 gem installed
$ sass --version
Sass 3.5.5 (Bleeding Edge)
$ echo 'a {b: c}' | sass --scss -t compressed
a{b:c}
```

How are you running Sass in your app? Is it possible your framework is failing to pass options through correctly?

**Comment by mgpdattila** [comment]
I run this command: sass --watch Tenants --style compressed

**Comment by mgpdattila** [comment]
Tenants being the directory in which the CSS and SCSS files are located.

**Comment by nex3** [comment]
```
$ mkdir dir
$ echo 'a {b: c}' > dir/test.scss
$ sass --watch dir --style compressed &                                                
>>> Sass is watching for changes. Press Ctrl-C to stop.
      write dir/test.css
      write dir/test.css.map
$ cat dir/test.css
a{b:c}
/*# sourceMappingURL=test.css.map */
```

I'm pretty baffled why this wouldn't be working for you. Have you tried deleting the output files and the `.sass-cache` directory?

**Comment by mgpdattila** [comment]
I have no idea where the output files or the .sass-cache directory are.

dans-mbp:Tenants dan$ cat dir/test.css
cat: dir/test.css: No such file or directory

**Comment by mgpdattila** [comment]
I used Finder search on my mac to locate: .sass-cache. Nothing was found.

**Comment by nex3** [comment]
Unless you're passing an output directory to `sass --watch`, the output files are next to the input files. The `.sass-cache` directory would be in the directory from which you're running the `sass` command. It may not show up in Finder because it's a hidden directory.

**Comment by mgpdattila** [comment]
Here are my files:

```
dans-mbp:Tenants dan$ ls -a
.		acnots		bigcompany	madisonryp	sfdemo01	summit		ti
..		acnra		juniper		mtm		sfdemo02	synopsys	trueblue
.DS_Store	amgen		madisondemo	sandn		sfdemo03	takeda
```

**Comment by nex3** [comment]
You said earlier you were running `sass --watch Tenants`. That suggests that the `.sass-cache` directory would be above the `Tenants` directory.

**Comment by mgpdattila** [comment]
It is not in Tenants based on running command ls -a. The output files are the .css files. I am removing those now.

**Comment by mgpdattila** [comment]
I deleted and replaced the .css files, but the output is still not minified. I am leaving work now but will be back on Monday. The problem is the same on two different machines and remains after several full deletions and installs.

**Comment by mgpdattila** [comment]
The problem continues. The exported CSS files are not minified.

**Comment by nex3** [comment]
I'm really sorry, but if I can't reproduce this there's nothing I can do to fix it.
