### ISSUE TITLE
Can't update from sass 3.5.4 to 3.5.5

### ISSUE THREAD

**Issue by aried3r** [sass/sass#2443]
I'm running a Rails app and when updating the sass gem from 3.5.4 to 3.5.5 I get the following errors:

```
ExecJS::RuntimeError - SyntaxError: Unexpected token , in JSON at position 3:
  app/helpers/svg_helper.rb:6:in `svg'
```

Sadly the stack trace isn't very useful or telling.

This is the `svg_helper.rb`
```Ruby
# frozen_string_literal: true

module SvgHelper
  def svg(id)
    "<svg role=\"img\" class=\"svg__#{id}\"><use class=\"#{id}\"" \
    "xlink:href=\"#{image_path('sprite.svg')}##{id}\"></use></svg>".html_safe # Line 6
  end
end
```

This is not limited to the SVG helper, once I remove all calls to that file, other occurrences of `image_path('example.svg')` throw errors. I also found one error where a `favicon.ico` was failing.

There's no `,` in the SVGs at position 3.

Ruby 2.5.0
Rails 5.1.4
sass 3.5.5

I also use sassc-rails and bootstrap-sass (although I think the latter that's not used except on one old page).

**Comment by nex3** [comment]
If you're using sassc-rails, you're not using Ruby Sass. That said, I have a hard time imagining why either of them would cause a JSON parsing error.

**Comment by aried3r** [comment]
Thanks for the reply! Indeed I have no idea why it's throwing a JSON error in ExecJS. Going back in our codebase I can still replicated. I can `bundle update` all N-1 dependencies expect `sass`, then it works. Once I update `sass`, it doesn't.

Looking at the changes from 3.5.4 to 3.5.5 and using sassc-rails (which has a dependency on sass, just like bootstrap-sass) I cannot see how any kind of error, much less the JSON error should appear.

Maybe it's a problem elsewhere, already tried different Ruby versions. Maybe it's in our assets, maybe it's bundler, but it's still weird we can reproduce it with this gem.

I'll dig deeper, I guess it's really not related to this gem, probably opened the issue too soon. :)
