### ISSUE TITLE
`font-display` cannot get compiled

### ISSUE THREAD

**Issue by tom10271** [sass/sass#2446]
ERROR in ./node_modules/css-loader?{"minimize":true}!./node_modules/sass-loader/lib/loader.js!./web/styles/embed/myCss.scss
    Module build failed: 
        font-display: swap;
       ^
          Invalid CSS after "    font-display": expected "}", was ": swap;"

Webpack 3, Node 6.10.0 macOS v10.12.6 (16G1036)

**Comment by nex3** [comment]
This is the repository for Ruby Sass; Node Sass uses LibSass, which lives at https://github.com/sass/libsass.

When you post this there, I suggest including your full Sass file so that they can figure out why the parsing failed.
