### ISSUE TITLE
Encoding incorrectly detected forces to declare charset in every Sass include

### ISSUE THREAD

**Issue by Paulmicha** [sass/sass#2451]
Error dump :
```
/*
Error: Invalid US-ASCII character "\xC3"
        on line 10 of /src/scss/component/_navbar.scss
        from line 10 of /src/scss/_overrides.scss
        from line 18 of /src/scss/style.scss

5: $tablet:          "screen and (min-width: #{$screen-sm-min})";
6: $normal:          "screen and (min-width: #{$screen-md-min})";
7: $wide:            "screen and (min-width: #{$screen-lg-min})";
8: $grid-breakpoint: "screen and (min-width: #{$grid-float-breakpoint})";
9: 
10: // Update : en rajoutant le logo dans la navbar fixed, on doit décaler
11: // davatange le contenu de la page.
12: // TODO : le repliage après scroll de la moitié supérieure devra être géré en JS.
13: $navbar-height: 100px;
14: 
15: body {

Backtrace:
/src/scss/component/_navbar.scss:10
/src/scss/_overrides.scss:10
/src/scss/style.scss:18
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:1043:in `rescue in block in find_encoding_error'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:1040:in `block in find_encoding_error'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:1039:in `each'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:1039:in `each_with_index'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:1039:in `find_encoding_error'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/util.rb:767:in `check_sass_encoding'
/usr/local/bundle/gems/sass-3.5.5/lib/sass/engine.rb:444:in `check_encoding!'
```

Steps to reproduce :

- Use the `Dockerfile` detailed below
- Make sure every single Sass file has UTF-8 encoding (+ LF line endings)
- In any Sass file, use non-ascii character inside a comment, e.g. `// Test accent : éàèçã.`

Workaround :

The error disappears when starting EVERY Sass file with the explicit `@charset "UTF-8";` declaration - *even includes*...

Here's the `Dockerfile` used :

```
FROM ruby:2.5

RUN gem install sass

WORKDIR /tmp
ENTRYPOINT ["sass", "--watch", "/src/scss:/dist", "--style", "compressed", "--sourcemap"]
```

**Comment by nex3** [comment]
One way or another, Sass needs to know what encoding your source files are. There's no guarantee that all of them are the same--it's entirely valid for a UTF-8 file to import a Latin-1 file, for example--so the most robust solution is indeed to add `@charset` declarations for each file (Unicode byte-order marks will also work, although they may be more difficult to author).

However, if you don't want to explicitly add `@charset`s and all your files use the same encoding, Sass will fall back to Ruby's default external encoding. You can set this by passing the `--default-encoding` option to Sass, as in `sass --default-encoding utf-8 --watch /src/sass:/dist --style --compressed --sourcemap`.
