### ISSUE TITLE
Beginner | Help needed | @mixin non compiling

### ISSUE THREAD

**Issue by bostiq** [sass/sass#2452]
Hi, sorry for possibly wasting your time, couldn't find a forum for it... **noob alert...** 

I'm learning sass, have mac, installed following steps from [sass-lang.com](url).

I use Sublime and installed sass package and used it to test it.

I copied this snippets straight from [sass-lang.com](url) and testing the compiler through sublime and mac osx terminal to make sure they don't output differently.. they don't.

I tested the compiler with this snippet:

```@mixin large-text {
    font: {
        family: Arial;
        size: 20px;
        weight: bold;
        }
    color: #ff0000;
}

.page-title {
  @include large-text;
  padding: 4px;
  margin-top: 10px;
}
```

I made sure all indentation are consistent in the whole document and this returns
`Error: Invalid CSS after "": expected expression (e.g. 1px, bold), was "{" on line 38`

Now I took away graphs `{` put tabulations before instead than space.. put only one set and then tried the other... no matter what I do this doesn't compile.

What am I doing wrong???

**Comment by marvinschopf** [comment]
Could you paste the **complete** content of the file? It seems that you are having **more** than 38 lines...

**Comment by nex3** [comment]
Yes, please post the full source file.

**Comment by bostiq** [comment]
sure.. here it is: (this is just a test file)
```
$c1: #345
$c2: #ed9
$c3: #2ac

$sans: Helvetica, Arial, sans-serif
$serif: 'Times New Roman', Garamond, serif

=border-radius($radius)
	-webkit-border-radius: $radius
	-moz-border-radius: $radius
	-ms-border-radius: $radius
	border-radius: $radius


body
	background-color: $c1

a
	color: $c3

p
	color: $c2

nav
	+border-radius(10px)

	ul
		display: inline-block
	li
		font-family: $sans

	a
		font-family: $serif


@mixin largetext {
	font: {
		family: Arial;
		size: 20px;
		weight: bold;
	}
	color: #ff0000;
}

.page-title {
	@include large-text;
	padding: 4px;
	margin-top: 10px;
}
```
And TIA

**Comment by nex3** [comment]
It looks like you're mixing the SCSS syntax and the indented syntax. You need to choose one or the other for each file, and use the `.scss` extension for  SCSS and the `.sass` extension for the indented syntax.
