### ISSUE TITLE
Возможно ли в sass подобное?

### ISSUE THREAD

**Issue by ghost** [sass/sass#2455]
https://prntscr.com/i4bx56

Just started to learn
Thank you in advance

**Comment by ArmorDarks** [comment]
Partially.

Sass doesn't have `@export` directive. Hopefully someday it will receive one.

Conditional imports (within `@if` or `@for` directives) aren't possible. See https://github.com/sass/sass/issues/739 and https://github.com/sass/sass/issues/451. I recommend to wrap files content into mixins instead and invoke conditionally mixins, but import them in the beginning of the file.

Globing isn't available in Sass by default and would likely not appear in future. However, you can use `node-sass` [`importer`](https://github.com/sass/node-sass#importer--v200---experimental) option to override Sass imports and add globbing to it.

Here is a small function I've experimented with for [Kotsu](https://github.com/LotusTM/Kotsu):

```js
const { dirname } = require('path')

module.exports = function () {

  /*
  Sass
  https://github.com/sindresorhus/grunt-sass
  Compiles Sass with node-sass
  */

  this.config('sass', {
    build: {
      options: {
        importer: (url, prev, done) => {
          if (url.includes('/*')) {
            const cwd = dirname(prev)
            const files = this.file.expand({ cwd, filter: src => /(css|scss|sass)$/.test(src) }, url)

            if (!files.length) throw new Error(`no files provided for ${cwd}`)

            const imports = files.reduce(
              (imports, file) => `${imports}@import '${file}'\n`,
              ''
            )

            return done({ file: `${cwd}/`, contents: imports })
          }

          return done({ file: url })
        },
      },

      files: [{
        expand: true,
        cwd: 'source/styles',
        src: '{,**/}*.{scss,sass}',
        dest: 'build/styles',
        ext: '.compiled.css'
      }
      ]
    }
  })
}
```

It relies on Grunt, but I hope you can get the idea.

With this, such imports will work too:

```scss
@import 'components/*';
```

However, beware that importing order of globbed files will be unpredictable. So, it will work only for systems, which do not rely on importing order.

**Comment by ghost** [comment]
Thanks, will try.
Have a nice day =)
