### ISSUE TITLE
Import like Less reference (@import (reference))

### ISSUE THREAD

**Issue by marceloadsj** [sass/sass#2463]
When is this feature will be added?

**Comment by nex3** [comment]
Duplicate of #1094.

**Comment by marceloadsj** [comment]
The issue #1094 is locked since 2016 with no updates.

@nex3 do you have some news to say to community?

**Comment by nex3** [comment]
When there's news, I'll post it on the original thread. Right now, my limited development time is going into getting Dart Sass up and running rather than working on the new module system.
