### ISSUE TITLE
Not working extend nestling

### ISSUE THREAD

**Issue by macfiss** [sass/sass#2468]
Hi, noticed a bug in @extend directive, for example, there are elementary classes:

```
.is-visible {
  display: block !important;
}

.form-error {
    //...

    &.is-visible {
      display: block;
    }
}
```

Trying to @extend <is-visible> class <form-errors>:
```
._is-visible {
    @extend .is-visible !optional;
}
```

Bad result: 
```
.is-visible, 
._is-visible {
  display: block !important; 
}

.form-error.is-visible, 
.form-error._is-visible { //<-- ???
    display: block; 
}
```

The result should be (expected for less, for example):
```
.form-error.is-visible {
    display: block; 
}
```

Because I want to extend only one class and don't care about complex selectors containing this class. Otherwise it prevent me from using <is-visible> class in other components like <form-error>.

**Comment by ArmorDarks** [comment]
Because, good it or not, Sass extending works another way.

See #1599 for some insights.

**Comment by macfiss** [comment]
@ArmorDarks, so there is no way to extend some selector and not extend all other selectors that contains this selector?

**Comment by ArmorDarks** [comment]
That's right.

**Comment by nex3** [comment]
This is an important aspect of how `@extend` works. When you write `._is-visible {@extend .is-visible}`, you're saying "Style every element that matches `._is-visible` as though it matched `.is-visible` as well." *Every* style rule whose selector includes `.is-visible` can affect the styles of elements that match it, so we adjust all of them with `@extend`.
