### ISSUE TITLE
at-rule or selector expected in keyframes - vs code

### ISSUE THREAD

**Issue by GranaT3** [sass/sass#2475]
visual studio code detects some errors, which have no meaning and did not appear before. How can I solve that?
https://gist.github.com/GranaT3/c9a30c1f95815a8ab44800118640bb8f

![image](https://user-images.githubusercontent.com/17104324/36542793-41d74d4e-17b8-11e8-9d95-33bb65dede34.png)

**Comment by ghost** [comment]
Did you find a solution for this?

**Comment by Arelav** [comment]
I'm pretty sure it is a linting error. The solution depends on linter your use in the project. Most popular are "stylelint" and "scss-lint".
