### ISSUE TITLE
Depreciation warning for colors

### ISSUE THREAD

**Issue by akvadrako** [sass/sass#2478]
Hi, I actually just have a usage question, but I can't find anywhere to ask it. I couldn't find a link to any forum, mailing list or chat from your repo, homepage or docs.

I would like to know how to get rid this depreciation warning:

```
DEPRECATION WARNING on line 145, column 67 of /.../layout.scss:
The value "#AAAAAA00" is currently parsed as a string, but it will be parsed as a color in
future versions of Sass. Use "unquote('#AAAAAA00')" to continue parsing it as a string.
```

What should I do? I DON'T want it parsed as a string - it's a color.

**Comment by nex3** [comment]
If you want a color value, you can use `rgba()` syntax: `rgba(#AAAAAA, 0)`.

**Comment by RISCfuture** [comment]
So your recommendation is that for now we change all our color variables from `#AAAAAA` to `rgba(#AAAAAA, 0)`, but only temporarily, until the new version of Sass comes out, when we change them back to `#AAAAAA` because the `rgb()` call is redundant?

**Comment by nex3** [comment]
The value `#AAAAAA` will work just fine. It's only the syntax `#AAAAAA00`, which represents opacity as hex digits, which isn't supported yet and requires the use of the `rgba()` function right now.

**Comment by nicolasxu-bg** [comment]
> The value "#526c9687" is currently parsed as a string, but it will be parsed as a color in
> future versions of Sass. Use "unquote('#526c9687')" to continue parsing it as a string.

It is what I got. What is going on?

**Comment by nex3** [comment]
@nicolasxu-bg That syntax isn't supported yet in some Sass implementations. Use the `rgba()` function instead.
