### ISSUE TITLE
Update repository structure for a post-Ruby-Sass world

### ISSUE THREAD

**Issue by nex3** [sass/sass#2480]
Eventually, as Ruby Sass marches towards end-of-life, it won't really make sense for it to live in the sass/sass repository any more, as it will no longer be the primary implementation of Sass and will eventually get frozen and archived. That means we need to figure out a new repository structure, as well as figure out what to do with all the outstanding issues here with minimal breakage for people who have hard-coded references to this Git URL.

@chriseppstein and I propose the following migration, but feedback is encouraged:

* [x] Fork a copy of this repository to sass/ruby-sass.
  * New development will happen in sass/ruby-sass, and that's where new gems will be cut from.
* [x] Add big scary messages to sass/sass that say "Update your URLs to point to sass/ruby-sass!"
  * Definitely one of these at the top of the README.
  * Probably also one that prints every time you run `bin/sass` or `require "sass"`.
* [x] Migrate all Ruby implementation issues from sass/sass to sass/ruby-sass.
  * Unless GitHub adds native support for moving issues, this will probably mean closing the issues in sass/sass and creating new issues in sass/ruby-sass which summarize and link to the old issues.
* [x] Create a new sass/language repo as a central location for feature specifications which are currently spread out across issues.
  * Disable issues for this repository; language design discussions should remain in sass/sass.
* [x] Once Ruby Sass reaches end-of-life, wipe the commit history for sass/sass, replace it with sass/language's commit history, and delete sass/language.

**Comment by asottile** [comment]
Github allows you to rename a repository while keeping a redirect around (this is the default behaviour) -- for example https://github.com/docker/docker redirects to `moby/moby`.

This also works for cloning etc.

In theory, you should be able to (harmlessly) get the ball rolling just by renaming the repository to `ruby-sass`.  If (in the future) there's a desire to promote a new implementation to the "default", one could create a new `sass/sass` (or rename a repo to `sass/sass`) repository which would break the redirects.

**Comment by nex3** [comment]
We considered doing that, but it would end up with all the stars and watchers on this repo moving to sass/ruby-sass. We expect that most people are interested in this repository because they care about Sass the language, rather than Ruby Sass the implementation, so we didn't want to clobber those subscriptions.

Also, since we know we eventually want to have sass/sass be something other than the Ruby implementation, we want to have *something* there that tells people to update their URLs. If we just left a redirect until we promoted sass/language, that promotion would be more likely to surprise users.

**Comment by saper** [comment]
Shall we move the releases? I hope it is a relatively simple API operation

**Comment by nex3** [comment]
Good call. Done.
