### ISSUE TITLE
Archive Ruby Sass

### ISSUE THREAD

**Issue by nex3** [sass/sass#2481]
**Note:** This should only happen once Ruby Sass reaches its end-of-life, a year after Dart Sass's first stable release.

Once Ruby Sass hits end-of-life and is no longer being maintained, we should [archive it](https://help.github.com/articles/archiving-a-github-repository/) to make it clear that it's unsupported and no issues should be filed against it.

**Comment by stof** [comment]
@nex3 this issue should be closed as the repository is now archived

**Comment by nex3** [comment]
Good catch, thanks!
