### ISSUE TITLE
Blog about deprecation

### ISSUE THREAD

**Issue by nex3** [sass/sass#2483]
*Tracking this here for want of a better place.*

About a week after Dart Sass 1.0.0 stable releases, we should post a blog announcing and explaining Dart Sass's official deprecation. Major points to hit include:

* The timeline—deprecation begins immediately, end-of-life is in one year.
* Bugs will continue to be fixed, but only features necessary for CSS compatibility will be added.
* Warning-free stylesheets should run as-is on Dart Sass and hopefully LibSass too.
* Encourage users to migrate to [`sassc`](rubygems.org/gems/sassc), and we're planning sass/dart-sass#249.
* The repository will be moving (#2480).
* If someone wants to take on maintenance of Ruby Sass, we're happy to assist.

**Comment by chdiza** [comment]
I knew this was coming, so I played around with dart-sass and sassc.  I found them both to have far fewer cmdline flags and features than ruby-sass does, and for this reason, stuck with ruby.

Are either sassc or dart-sass going to adopt more of ruby-sass's flags?  Last I checked, the following are in ruby-sass but not the other two:
```
  --poll
  --scss
  --stop-on-error
  --unix-newlines
  --update
  --watch
  --no-cache
  --default-encoding
  --check
  --force
  --debug-info
  --interactive
  --quiet
  --require
```
I use `--update` and `--no-cache` all the time, e.g.

**Comment by nex3** [comment]
I can't speak for `sassc`, but for Dart Sass:

* `--update`, `--watch`, `--poll`, `--force`, and `--stop-on-error` [are planned](https://github.com/sass/dart-sass/issues/264).
* `--scss` doesn't make sense since the default syntax is already SCSS. However, it does support an `--indented` flag that tells it to use the indented syntax when reading from standard input.
* `--unix-newlines` isn't necessary because Dart Sass always emits files with Unix-style newlines.
* `--no-cache` isn't necessary because Dart Sass is fast enough that it doesn't need to cache parse trees.
* `--default-encoding` is something we could support eventually, but at present Dart Sass only supports UTF-8 anyway so it wouldn't do much for now.
* `--check` basically just compiled the stylesheet and threw out the output. I don't think it was ever widely-used, and it's easily replaceable by running `sass input.scss /dev/null` so we don't intend to support it.
* `--debug-info` was a hacky work-around from the era before source maps existed, so we don't intend to use it.
* `--interactive` [would be nice to add](https://github.com/sass/dart-sass/issues/265).
* `--quiet` is supported as of [1.0.0-rc.1](https://github.com/sass/dart-sass/releases/tag/1.0.0-rc.1).
* `--require`, or something like it, [is intended](https://github.com/sass/dart-sass/issues/148) for the Node.js CLI. It's more complicated for pure Dart, which doesn't currently support a good way of [dynamically loading code](https://github.com/dart-lang/sdk/issues/10530).

**Comment by nex3** [comment]
[This blog has been blogged](http://sass.logdown.com/posts/7081811).

**Comment by eric-hemasystems** [comment]
Got the gem warning today which lead me to the blog post.

The blog recommended was switching to `sassc`. I'm assuming if using Rails then we want `sassc-rails` for a drop-in replacement of `sass-rails`. But looks like `sassc-rails` [still depends on the `sass` gem](https://github.com/sass/sassc-rails/blob/master/sassc-rails.gemspec#L26-L28)...

So I switched but am still dependent on the deprecated gem. Is there a plan to disconnect `sassc-rails` from the `sass` gem or I am misunderstanding what I was supposed to do?

**Comment by nex3** [comment]
I'm not a maintainer for `sassc-rails`, so I don't know their plan. I suggest filing an issue on their repo.
