### ISSUE TITLE
Blog about end-of-life

### ISSUE THREAD

**Issue by nex3** [sass/sass#2484]
*Tracking this here for want of a better place.*

**Note:** This should only happen once Ruby Sass reaches its end-of-life, a year after Dart Sass's first stable release.

Once Ruby Sass has hit end-of-life, we should post a blog telling users of this and reiterating the recommended migration path.

**Comment by mokolabs** [comment]
Sorry... what is the recommended migration path for Ruby (and Ruby on Rails)? I read the blog a few times, but it's not very clear on this point.

Should we use libsass via https://github.com/sass/sassc-ruby or https://github.com/sass/sassc-rails?

Thanks!

**Comment by nex3** [comment]
> Sorry... what is the recommended migration path for Ruby (and Ruby on Rails)? I read the blog a few times, but it's not very clear on this point.

That's because this blog post hasn't been written yet :wink:.

For the short term, the `sassc-rails` gem is probably the best way to go.

**Comment by mokolabs** [comment]
Ha! Alrighty. Sounds good. 👍

**Comment by nex3** [comment]
This was done a while ago: https://sass-lang.com/blog/posts/7828841-ruby-sass-is-unsupported
