### ISSUE TITLE
Parse SCSS file, importer ?

### ISSUE THREAD

**Issue by JulienItard** [sass/sass#2485]
Hello,

I'd like to parse scss file with this method `Sass::SCSS::Parser.new(str, filename, importer).parse` from here http://sass-lang.com/documentation/Sass/SCSS/Parser.html#initialize-instance_method

But i'm not sure what i should use as `importer`. Thanks for help

**Comment by nex3** [comment]
That's an internal class. If you want the parse tree for a file, you're better off creating a [`Sass::Engine`](http://sass-lang.com/documentation/Sass/Engine.html) and calling [`#to_tree`](http://sass-lang.com/documentation/Sass/Engine.html#to_tree-instance_method).
