### ISSUE TITLE
Certain CSS level 4 selectors are incorrectly compressed

### ISSUE THREAD

**Issue by madrobby** [sass/sass#2497]
I have a CSS level 4 selector in SCSS:

```scss
.someclass:nth-child(1 of .due-today) { 
/* ... */
}
```

When compressing the CSS via Sass, the result is something like…

```css
.someclass:nth-child(1of.due - today) {
/* ... */
}
```

…which obviously isn't working.

**Comment by madrobby** [comment]
Fwiw, I tried compressing with the latest CSSO and it works there.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
