### ISSUE TITLE
Could not find an option named "watch" error

### ISSUE THREAD

**Issue by iamalp** [sass/sass#2498]
I installed sass from npm globally
`npm install -g sass`

Then from official documentation [Doc link](https://sass-lang.com/guide#topic-1), I entered --watch command from my terminal. I am in the same directory where are the css and scss files are located. 
`sass --watch main.scss main.css`

Ang it gave me an error.
`Could not find an option named "watch".`

Despite I have installed sass via npm globally 'watch' command is not recognizable by sass.

**Comment by mprins** [comment]
you probably want to talk to (file your issue with)  the people that make/distribute npm sass which uses dart sass and not to the (original) ruby sass that is hosted in this repository

**Comment by acagastya** [comment]
@Alpsenel I got a similar issue for watching sass files. This is what I recommend:
1. check version of sass using `sass --version` (optional)
2. Uninstall sass using `gem uninstall sass`
3. Install version 3.4.0 using `gem install sass -v 3.4.0` (note; latest stable version is 3.5.6)

**Comment by nex3** [comment]
The Sass website documentation was referring to [Ruby Sass](https://sass-lang.com/ruby-sass), which [has been deprecated](http://sass.logdown.com/posts/7081811). Dart Sass, which you installed via npm, doesn't yet support `--watch` (https://github.com/sass/dart-sass/issues/264).

I've updated the website to stop mentioning `--watch` until we have it implemented in Dart Sass.

**Comment by ve3** [comment]
map also not supported?

**Comment by nex3** [comment]
@ve3 That's correct, Dart Sass doesn't currently support source maps (https://github.com/sass/dart-sass/issues/2).

**Comment by Mugane** [comment]
So what is actually supported?

**Comment by nex3** [comment]
You can run `sass path/to/file.scss path/to/output.css`.

**Comment by Mibeon** [comment]
What the f**** is that? How can I listen for changes in my files? Should I every time run it manually?????? What's going on with dev tools. Homebrew running crazy, sass, what's next?

**Comment by josuevalrob** [comment]
I have this: 1.2.1 compiled with dart2js 2.0.0-dev.49.0
Is this the good one or the wrong one?

**Comment by nex3** [comment]
@josuevalrob That is the latest version of Dart Sass, yes.

**Comment by tassiogoncalves** [comment]
Any prediction of when the watch command will be implemented?

**Comment by anthondevg** [comment]
I have the same problem, It's really annoying to have to compile the sass code manually every moment that we do changes on the sass

**Comment by Mugane** [comment]
You guys may want to install gulp and gulp-sass, then set up a gulpfile.js and then "gulp watch" will work.
> npm install gulp
> npm install gulp-sass
see https://codehangar.io/gulp-sass/ for more details

**Comment by cvwebb** [comment]
Here's the official documentation on the implementation of Dart Sass. This took me a minute to realize too
https://sass-lang.com/dart-sass

**Comment by chriseppstein** [comment]
There are literally dozens of projects that will generically watch for changes and then execute code or shell commands. That wasn't true when Ruby Sass was first released. But now, it's not an especially important feature. Use a build tool on top of Sass.

**Comment by nex3** [comment]
I wouldn't say that this isn't an especially important feature--it's certainly something I consider high-priority--but please do be patient as implementing these things takes time and there's only one of me.
