### ISSUE TITLE
Child selectors

### ISSUE THREAD

**Issue by ebednarz** [sass/sass#250]
I just started playing with SASS this week and didn't find anything about child selectors in the documentation.

Something like the following appears to work fine:

```
.copy {
    > {
        p {
            margin: 0;
            text-indent: 1.5em;
        }
    }
}
```

Are there any reasons (e.g. complex use cases) not to use this? Otherwise it would be nice if it was
a) documented and
b) if the compressed style would strip whitespaces surrounding '>'

**Comment by nex3** [comment]
Child selectors are a feature of CSS. The documentation says that Sass supports everything in CSS3; I don't think it's necessary to specifically call out all the individual features.

I'll leave this issue open for the compressed-mode request.

**Comment by ebednarz** [comment]
I'm not referring to CSS syntax but SASS 'CSS extensions'. The latter simply mentions 'nested rules' as a feature, but my SCSS example does not start with a nested rule( set).

BTW, if it is possible to break up selectors within rule sets by combinator and nest the parts, I would expect this

```
foo {
    /* I'm surrounded by a decendant combinator */ {
        bar {
            /* declarations */
        }
    }
}
```

to work, too, but the compiler disagrees ;-)

Well, YMMD. Thanks for the confirmation and the compressed-mode commit.

(Speaking about the documentation, all the (compiled) 'font' shorthand examples are invalid.)
