### ISSUE TITLE
Color operator docs does not specify that subtraction is deprecated

### ISSUE THREAD

**Issue by binki** [sass/sass#2500]
See https://github.com/sass/sass/blob/ed6036d2bf3b0b5331aca27764fe3128709626ae/doc-src/SASS_REFERENCE.md#color-operations which states that all arithmetic operators apply to colors on a componentwise basis. However, when I try to use subtraction, I get an error in dart-sass and ruby-sass outputs this warning:

```
DEPRECATION WARNING on line 2 of /sass/spec/colors/arithmetic/input.scss:
The operation `#fff minus #fad` is deprecated and will be an error in future versions.
```

I have legacy SCSS which uses this operator. The documentation should not suggest that this is an option and should contain instructions for porting legacy code to future SCSS with examples of before/after.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to the reference documentation, which lives in the Ruby Sass repository.
