### ISSUE TITLE
Cannot open file  -- os-x 10.13.3

### ISSUE THREAD

**Issue by ralphfrost** [sass/sass#2503]
In trying to learn/use sass for 1st time, I used Homebrew to install dart-sass on recently updated High Sierra 10.13.3 . That worked and sass --version shows 1.1.1    After some initial failures,  in VS Code I created a simple main.scss file containing:

```
$color: #d9534f;

body {
    color: $color;
}
```
and while in the same directory as the file in terminal, then issued:

`sass main.scss main.css  --trace`

in console which returned:

```
Error reading main: Cannot open file.

dart:io                               _File.readAsBytesSync
package:sass/src/io/vm.dart 27        readFile
package:sass/src/compile.dart 33      compile
package:sass/sass.dart 63             compile
package:sass/src/executable.dart 110  main
```

Sudo doesn't make a difference.   After much searching, I don't see what do I need to change, learn or do to get this working.  Please advise.  Thank you.

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by ralphfrost** [comment]
Thanks. Sorry to bother you. I did submit to SO, and then persisted and did
brew update several times, then brew uninstall sass, then brew install
sass/sass/sass  -- which fixed my 'problem'...

Again, pardon my interruption.

Thank you for your effort and creativity on providing Sass!!

Ralph Frost
