### ISSUE TITLE
--watch no longer recognized? (osx high sierra 10.13.4)

### ISSUE THREAD

**Issue by Paul-Morris** [sass/sass#2506]
It lists the help file everytime I try to use --watch. (sass --watch sass:style.css) 
But it seems to work fine without it (sass sass/style.scss style.css)

After upgrading to 1.2.1, uninstalling and reinstalling with homebrew I can't get --watch to work at all. It's like it isn't even a valid command anymore.

**Comment by nex3** [comment]
`--watch` is not yet supported in Dart Sass, but it's high priority. See https://github.com/sass/dart-sass/issues/264.
