### ISSUE TITLE
Regarding issue #132

### ISSUE THREAD

**Issue by nukkamoto** [sass/sass#2507]
Regarding issue #132

Every language has string interpolation. 

Add the feature, stop being stubborn.

Also in my opinion those who work for 30 years plus get stuck in their own (old) ways and don't like change. @chriseppstein .

By expressing string interpolation is a bad idea, is just saying all other languages who have implemented it are wrong to do so. 

Also, closing/disabling comments is a bad form of censorship which goes agains Open-Source ideals.

Please reconsider! and change old habits, they are toxic.

**Comment by nex3** [comment]
Name-calling is not acceptable behavior, nor is attempting to re-open a locked issue. Don't do it again or you will be blocked from the Sass organization.
