### ISSUE TITLE
@import is non-standard behaviour

### ISSUE THREAD

**Issue by kaspar-allenbach** [sass/sass#2518]
Lately this Message pops up in my build tool:

> Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass. Use a custom importer to maintain this behaviour.

I wonder what kind of problem this is going to solve. 

What is the proposed sollution when I want to inline a css file from a npm package?

**Comment by chriseppstein** [comment]
See: https://github.com/sass/node-sass/issues/2362
