### ISSUE TITLE
add clinging selector to imported file

### ISSUE THREAD

**Issue by ebrahimiaval** [sass/sass#2522]
how to add .hdr class to .topHeader clinging in below structure (.hdr.topheader) just by edit  header.scss file. (like: `&@import "topHeader"` )
 in this structure get .topHeade nested of  .hdr (.hdr .topHeader).

in file style.scss :
`.hdr {
    @import "header";
}`

in header.scss :
`&{ 
     @import "topHeader";
}`

in topHeader.scss  :
`.topHeader{
    ...
}`

**Comment by chriseppstein** [comment]
You need to make `topHeader` into a mixin.

```scss
// topHeader.scss
// This assumes that sometimes top header is sometimes included at the root level.
@mixin topHeader {
  @at-root #{if(&, selector-append(&, ".topHeader"), ".topHeader")} {
    // contents of the topHeader class go here
  }
}

If topHeader is always included in another selector it can be simplified to:

```scss
// topHeader.scss
@mixin topHeader {
  &.topHeader {
    // contents of the hdr class go here
  }
}
```

```scss
// header.scss is not really necessary in this example.
```

```scss
// style.scss
@import "topHeader.scss";
.hdr {
  @include topHeader;
}
```
