### ISSUE TITLE
variable color in RGB or HSL format are output as HEX

### ISSUE THREAD

**Issue by jimblue** [sass/sass#2525]
Hi,

I'm using a variable to define a color in RGB values.
Then I use this variable $color to setup the stroke of a SVG.

```sass
$color: rgb(0, 129, 198);

@mixin divider($stroke: $color) {
  background: transparent url('data:image/svg+xml;utf8, <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMax meet" viewBox="0 0 20 4" stroke="#{$stroke}" stroke-width="1"><path fill="none" d="M0, 3.5 c 5, 0, 5, -3, 10, -3 s 5, 3, 10, 3 c 5, 0, 5, -3, 10, -3 s 5, 3, 10, 3"/></svg>');
}
```

The fact that the variable $color is in RGB format is important because of a chrome deprecation:

_**[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.**_

The problem is that SASS always output the color in hex value even if I've choose initially a RGB or HSL value.

Thanks for your help!

Cheers

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
