### ISSUE TITLE
"Error compiling CSS asset", ArgumentError with Rails 3.2

### ISSUE THREAD

**Issue by alexeymuranov** [sass/sass#253]
I have just upgraded to Rails 3.2, and my controller tests are passing, but in the browser i see a page that says:

```
Error compiling CSS asset
ArgumentError: wrong number of arguments (19 for 1)
  (in .../app/assets/stylesheets/custom.css.scss)

/Volumes/Data/Users/alexey/.rvm/gems/ruby-1.9.3-p0/gems/sass-3.1.12/lib/sass/script/variable.rb:16:in `initialize`
```

If i disable styles in my browser, i can see my page.

Here is what i see in terminal:

```
Started GET "/assets/application.css" for 127.0.0.1 at 2012-01-22 20:18:39 +0100
Error compiling asset application.css:
ArgumentError: wrong number of arguments (19 for 1)
  (in /Volumes/Data/Users/alexey/Development/rails_projects/raclette/app/assets/stylesheets/custom.css.scss)
Served asset /application.css - 500 Internal Server Error
```

If i replace the .scss file with the generated .css file, then everything works.

**Comment by alexeymuranov** [comment]
I have reported the issue to sass-rails [\#85](https://github.com/rails/sass-rails/issues/85), i think it is more appropriate there, sorry for the noise.

**Comment by alexeymuranov** [comment]
I resolved my problem, it was my own fault.

**Comment by MattEhrlich** [comment]
@alexeymuranov How did you solve this problem?

**Comment by alexeymuranov** [comment]
@MattEhrlich, i do not remember, i used some hacks that caused the problem.
