### ISSUE TITLE
Add placeholder-exists() function

### ISSUE THREAD

**Issue by FlyingDR** [sass/sass#2533]
Currently Sass have a number of functions for introspection like `variable-exists`, `function-exists`, `mixin-exists` and so on. But there is currently no `placeholder-exists` which would allow to check if placeholder is actually available.

In the same time attempt to `@extend` with unavailable placeholder results into fatal error, hence lack of this function makes use of dynamically created placeholders very unreliable.

**Comment by nex3** [comment]
There's no way to implement this in a way where it will behave how you expect. Functions are evaluated at the point in the stylesheet where they're written, so if you write `placeholder-exists("foo")` there's no way for Sass to know if you're going to write `%foo` later on in the stylesheet or not.

I suggest using the [`!optional`](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#the_optional_flag) flag to write an `@extend` that doesn't produce an error if the extended selector doesn't exist.

**Comment by FlyingDR** [comment]
@nex3 thanks for explanations, but I don't see how it blocks existence of such function. Same logic applies to other introspection functions, but they're available:
```scss
@debug function-exists(my-func);
@debug mixin-exists(my-mixin);
@debug global-variable-exists(my-var);

@mixin my-mixin() {

}

@function my-func() {
    @return null;
}

$my-var: true;

@debug function-exists(my-func);
@debug mixin-exists(my-mixin);
@debug global-variable-exists(my-var);
```
This code gives `false`, `false`, `false`, `true`,  `true`, `true`, so it is also no way for Sass to know if I will going to declare mixin or variable later in stylesheet or not. Also attempt to use not yet defined global variable or mixin results into same error as for placeholder. 

From a point of view of a person who doesn't know Sass internals - behavior is the same but Sass have introspection functions for one type of information and from your words it can't have for another.

**Comment by nex3** [comment]
The difference is that `placeholder-exists()` doesn't have a use-case. For `function-exists()`, `mixin-exists()`, and `variable-exists()`, and `global-variable-exists()`, you can call them before referring to a function/mixin/variable and they'll tell you whether that reference will succeed or throw an error. But that's wouldn't be true for `placeholder-exists()`; it would have false negatives, where it would tell you a placeholder doesn't exist but the `@extend` would still work.

At the same time, we do already have a feature for writing an `@extend` that only does something if the placeholder you're extending actually exists: the `!optional` flag. `placeholder-exists()` wouldn't satisfy the use-case, and we have another feature that would, so it doesn't make sense to add `placeholder-exists()`.

**Comment by FlyingDR** [comment]
Ok, thank you for explanations!
