### ISSUE TITLE
Support full media query conditions

### ISSUE THREAD

**Issue by nex3** [sass/sass#2538]
* [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/media-logic.md)

**Deprecation**

* [x] [Tests](https://github.com/sass/sass-spec/issues/1798) (https://github.com/sass/sass-spec/pull/1807)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1728) (https://github.com/sass/dart-sass/pull/1749)
* [x] [Documentation](https://github.com/sass/sass-site/issues/655) (https://github.com/sass/sass-site/pull/656)
* [x] Update canonical spec (https://github.com/sass/sass/pull/3365)

**Final**

* [x] [Tests](https://github.com/sass/sass-spec/issues/1798) (https://github.com/sass/sass-spec/pull/1833)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1728) (https://github.com/sass/dart-sass/pull/1822)
* [x] [Documentation](https://github.com/sass/sass-site/issues/655) (https://github.com/sass/sass-site/pull/685)

---

The [Media Queries Level 4](https://www.w3.org/TR/mediaqueries-4/#media-conditions) spec defines syntax for full boolean algebra among media features. At time of writing, I believe no browsers support this syntax, but once one does Sass should add support as well.

In addition to parsing additional forms, this will affect Sass's media query merging logic. For example, merging `not print` and `(min-width: 600px)` should produce `not print and not (min-width: 600px)` rather than failing entirely.

**Comment by stof** [comment]
For reference, this is supported in Firefox 63+.
And looking at the Chromium issue tracker, they have some in-progress work done (probably related to their implementation of container queries, as they rely on that range syntax too)

**Comment by stof** [comment]
Those are announced to be shipping in Chrome 104, which should make the awaited browser support being there as Firefox already shipped them.
https://caniuse.com/mdn-css_at-rules_media_range_syntax

**Comment by nex3** [comment]
I have a PR out for a proposal: https://github.com/sass/sass/pull/3344

**Comment by nex3** [comment]
The proposal has landed. Since it's relatively straightforward and unlikely to change, I'll give it two weeks for public comment.

**Comment by nex3** [comment]
The initial deprecation phase has landed. We'll wait at least three months to give users a chance to migrate away from the deprecated syntax, then land full support.
