### ISSUE TITLE
！Failed to compile.

### ISSUE THREAD

**Issue by ArthurYung** [sass/sass#2539]
my code:
```
@for $p from 1 through 3{
  .el-#{$p}{
    color:#fff
  }
}
```

tell me why？？？
```
Failed to compile.

./src/components/page/home/home.scss
Module build failed: Syntax Error

(206:9) Unknown word

  204 |
  205 | @for $p from 1 through 3{
> 206 |   .el-#{$p}{
      |         ^
  207 |     color:#fff
  208 |   }
```

**Comment by ChuckOu** [comment]
a

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
