### ISSUE TITLE
Ability to import specific variables

### ISSUE THREAD

**Issue by sbernheim4** [sass/sass#2540]
It would be really cool to allow users to import not the whole stylesheet but specific variables. 

Lets say you have two scss files. `navbar.scss` and `landing-page.scss`. You set the height of the navbar in `navbar.scss` using some variable like `$navbar-height: 65px;` but then in `landing-page.scss` you want to use that value so you can do something like

```
.landing-page {
    position: absolute;
    top: $navbar-height
}
```

Currently you would have to import the whole stylesheet to just get that value. It would be really cool if instead you could do something like `import-var(navbar-height) from '../navbar/navbar.scss'`

I know the example is trivial but there are many other scenarios where being able to access individual variables would be very helpful without having to store all your variables in one stylesheet and import that `variables.scss` file in every file that may only need access to a single variable.

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/1094, specifically "Disabling CSS Ouptut".
