### ISSUE TITLE
Support for base level parent selectors (&) in partials

### ISSUE THREAD

**Issue by elia** [sass/sass#2541]
_originally reported in https://github.com/sass/libsass/issues/2704_

We use base level parent selectors a lot in partials (see below for the "how"), but found it's no longer supported upgrading from 

```
gem 'sass', '~> 3.4.24'
gem 'sassc', '~> 1.11.2'
```

to the latest version, I didn't find any explicit mention of this in the changelog, is this intentional?

In https://github.com/sass/sass/issues/1873 is specified that `&` selectors cannot be used as root selectors, but nothing is said about partials imported inside a selector. 

---

### application.sass

```sass
#header
  @import header
```

### _header.sass

```sass
&
  position: relative

h1
  color: green
```

resulting in something like:

```css
#header { position: relative; }
#header h1 { color: green; }
```

This technique allows to reuse partials and move them around very easily, e.g. let's say I need an additional wrapper between `#header` and its content I can just add a `<div class="wrapper">` to the HTML and change `application.sass` to be

```sass
#header .wrapper
  @import header
```

**Comment by nex3** [comment]
I strongly recommend wrapping your header logic in a mixin and including that rather than just importing the file wholesale. It's much more flexible and re-usable, and it ensures that your partial is a valid Sass file when used in isolation.

**Comment by elia** [comment]
I see your point, yet I have a few things I'd like to point out that I think should be considered:

- the header is just an example, we have hundreds of partials for multiple sites using this technique which was legitimate in previous versions (52kLOC in partials out of 55kLOC sass total)
- those partials are not used in isolation, instead are specifically designed to be imported inside existing selectors, in fact I'm happy it gives an error when used outside a selector
- using mixins doesn't add anything in terms of flexibility or re-usability, they would need to be gigantic or to resort once again to partials

All these points are meant to show how this is a legitimate case, and tightly linked to the ability to import partials inside selectors.

---

here's an excerpt from one of our projects:

#### application.sass

```sass
#messages
  @import messages

#spinner
  @import spinner

#content
  @import content

#slide-cart
  @import cart

#footer
  @import footer
````

#### _content.sass
```sass
  html body.boutiques &
    @import content/static

  html body.boutiques &
    @import content/boutiques

  html body.controller_newsletter_subscriptions &
    @import content/newsletter

  html body.controller_users &
    @import content/users

  html body.controller_orders.action_show &
    @import content/users
    @import content/order_show

  html body.controller_orders:not(.action_show) &
    @import content/cart

  html body.controller_checkout.action_edit &,
  html body.controller_checkout.action_update &,
    @import content/checkout
```

**Comment by nex3** [comment]
Sorry, I've checked and I was mistaken--this is supported behavior in Ruby Sass and Dart Sass (although I still think it's quite bad practice). If it's not working when you're using LibSass, please file an issue against [the LibSass repo](/sass/libsass/issues/new).

**Comment by elia** [comment]
An update: apparently SassC has no problem with this technique. To my understanding it senses that `&` isn't empty and so it's fine (I just replicated it with a number of versions from 1.11 up to 2). 

The problem arises instead with sassc-rails, probably because of the custom importers. I'll be happy to open an issue there, or if you prefer [transfer this one](https://blog.github.com/changelog/2018-10-30-issue-transfer/) to that repo.

Should this behavior also be added to the sass-spec?

**Comment by nex3** [comment]
> The problem arises instead with sassc-rails, probably because of the custom importers. I'll be happy to open an issue there, or if you prefer [transfer this one](https://blog.github.com/changelog/2018-10-30-issue-transfer/) to that repo.

Can you open a new issue there?

> Should this behavior also be added to the sass-spec?

Yeah, probably.
