### ISSUE TITLE
Undefined operation with adding 2 colors 

### ISSUE THREAD

**Issue by kays-chetoui** [sass/sass#2543]
![capture](https://user-images.githubusercontent.com/21172977/43318127-e794cb38-919f-11e8-8bcf-a8be734c487d.PNG)

**Comment by nex3** [comment]
This is intended. Color arithmetic is no longer supported--see #2144 for details. If you want to mix two colors together, we recommend using [the `mix()` function](http://sass-lang.com/documentation/Sass/Script/Functions.html#mix-instance_method).

**Comment by geocolumbus** [comment]
The documentation still indicates you can add RGB colors with +. In Section 6, for example.

https://sass-lang.com/documentation/file.SASS_REFERENCE.html#sassscript

**Comment by nex3** [comment]
@geocolumbus That's fixed in the new documentation being added in sass/sass-site#205.
