### ISSUE TITLE
sass permamently delete css file due to undefined mixin

### ISSUE THREAD

**Issue by timEIrm** [sass/sass#2552]
```
Error: Undefined mixin.
@include media-breakpoint-between(xs,sm){

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  example.scss 38:1  root stylesheet
```

What happen is that sass creates a .css.map file and permamently deletes the .css file used to overwrite bootstrap 4 scss file. I can't find the .css file, even when looking at system trash bin. It's just "poof", gone!

This is really a groundbreaking bug! Luckily it is easy to create a new file and then comment out the failing @include media-breakpoint, and after doing these steps, type "sass example1.scss example.css" to recreate the file. However what is going on here?

Seems undefined mixin of the type @include creates this bug. (This is bootstrap 4 mixin!)

Thanks for all help adressing this issue!

**Comment by nex3** [comment]
This is the intended behavior. When you tell Sass to write to a CSS file, you're giving Sass ownership over that file. When your input is invalid, Sass deletes the file so that if you refresh your browser page you don't see stale styles.
