### ISSUE TITLE
[Documentation] Add a nice search experience in the website

### ISSUE THREAD

**Issue by s-pace** [sass/sass#2554]
👋  Sass team,

As web developers, we've already used Sass and it is a great tool. But with so many content along the years, we noticed that using **your documentation without a search** might be painful.

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://docsearch-sass.netlify.com/) of what DocSearch on the Sass website could look like here. Feel free to try it and let us know what you think.

[![demo of DocSearch + Sass](https://cl.ly/4f1e3af3c74c/Screen%20Recording%202018-08-29%20at%2011.36%20AM.gif)](https://docsearch-sass.netlify.com/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'a409ff5d6a2476083c1a8dd1f8c04ec5',
  indexName: 'sass-lang',
  inputSelector: 'ADD ME AND FIX ME',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Please add one and update it accordingly.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/sass-lang.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to analytics on the most searched terms or those with no results. All of this is of course entirely free.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by nex3** [comment]
This is the repo for Sass language design; can you file this on [sass/sass-site](https://github.com/sass/sass-site) instead?

**Comment by s-pace** [comment]
Sure thing, thanks @nex3
