### ISSUE TITLE
use if to determine 100%

### ISSUE THREAD

**Issue by five00miles** [sass/sass#2555]
index.scss
```sass
@function p2r($size) {
  @return ($size/100)*1rem;
}

@mixin size($width, $height) {
  @if $width == 100% {
    width:100%
  }@else{
    width: p2r($width);
  }
  // width: p2r($width);
  height: p2r($height);
}
a{
  @include size(100,100);
}
```

---------------------------------------------
indec.css
```css
a { width: 100%; height: 1rem; }
```

why the result is  `a { width: 100%; height: 1rem; }`  not `a { width: 1rem; height: 1rem; }`

thanks

**Comment by nex3** [comment]
What version and implementation of Sass are you using?

**Comment by five00miles** [comment]
ruby 3.4.23

I read the #1496. 
Now i know how to resolve it.

thanks
