### ISSUE TITLE
Can we include mixins fast way?

### ISSUE THREAD

**Issue by ozergul** [sass/sass#2558]
Hello
I wonder that using mixins with way like less.
For example I create a mixin:

`@mixin test() { ... }`
And using like this:
`@include test();`

But in Less:
`.test();`

If there is better way to do is I would like to learn it.

**Comment by nex3** [comment]
In the indented syntax, you can define mixins using `=test` and include them using `+test`. In SCSS, you must use `@mixin` and `@include`, because we want to minimize the risk of syntactic ambiguity with plain CSS.
