### ISSUE TITLE
Missing vendor prefixes for tab-size

### ISSUE THREAD

**Issue by Serranya** [sass/sass#2560]
I have an scss file like this:
```
@charset "UTF-8";

pre {
   tab-size: 3;
}
```
**output:**
```
pre {
  tab-size: 3; }
```
**expected:**
```
pre {
  tab-size: 3; 
  -o-tab-size: 3; 
  -moz-tab-size: 3; }
```
Tab size needs the `-moz` or the `-o` prefix to work in FireFox/Opera. But the property is emitted as is.

```
sass -v
Ruby Sass 3.5.6
```

**Comment by nex3** [comment]
Sass doesn't do automatic vendor prefixing. I suggest using a tool like [Autoprefixer](https://autoprefixer.github.io/) to post-process your CSS.
