### ISSUE TITLE
Already defined variables in lists

### ISSUE THREAD

**Issue by justingolden21** [sass/sass#2571]
Hi, a suggestion.  If I have some variables, let's say colors, already defined, and I'd like to make a list to loop through them, I have to copy paste each color into my list, then when I want to change a color, I have to change both occurrences of it. This seems kinda of "anti-sass" so to speak. Here's my example:

*I have these colors already defined for other usage in my project:*
```
$bright-red: hsl(0, 80%, 60%);
$red: hsl(0, 80%, 50%);
$dark-red: hsl(0, 80%, 40%);
$bright-green: hsl(120, 80%, 60%);
$green: hsl(120, 80%, 50%);
$dark-green: hsl(120, 80%, 40%);
```
*Then I have my list variables:*
```
$colorNames: red green blue;
$brightColors: hsl(0, 80%, 60%) hsl(120, 80%, 60%) hsl(240, 80%, 60%);
$darkColors: hsl(0, 80%, 40%) hsl(120, 80%, 40%) hsl(240, 80%, 40%);
```
*Then I loop through my list variables, assigning any .btn.btn-red a background color of $bright-red for example:*
```
@for $i from 1 through length($colorNames) {
	.btn.btn-#{nth($colorNames, $i)} {
		background-color: nth($brightColors, $i);
		border: 2px solid nth($darkColors, $i);
		color: #fff;
	}
	.btn.btn-#{nth($colorNames, $i)}:hover {
		background-color: nth($darkColors, $i);
	}
}
```

However, if I'd like to update my bright red, I have to change **both variables**, which seems against the spirit of sass (simplifying css by making variables you can easily change without find and replace)

Let me know if I was unaware and there already is a way to do this, but since I don't believe there is a way to do it, and I think it would be helpful for many developers to be able to write code like this:
```
$brightColors: $bright-red $bright-green $bright-blue;
```
Instead of typing out the colors themselves again and having to update both.

Thank you for listening to my input 👍

**Comment by nex3** [comment]
The syntax you're suggesting is already valid Sass: https://www.sassmeister.com/gist/361871d61bcc85ff8058bbde22bfca73.
