### ISSUE TITLE
@extend containing classes with 'Referencing Parent Selector (&)' produce wrong output order

### ISSUE THREAD

**Issue by bskibinski** [sass/sass#2573]
I've tested through my own projects and used https://www.sassmeister.com/ to compare some versions.

**Bug:**
When creating an @extend containing a class prefixed with the "&" (the Referencing Parent Selector), the class gets printed first, following the extending class.

_Shortest example Using any up to date sass libray (dart/lib/ruby)_
**Input**
```
%extend {
  background: red;
  &.class {
    text-decoration: none;
  }
}

.wrapper {
  @extend %extend;
}
```
**Output:**
```
.wrapper {
  background: red;
}
.class.wrapper {
  text-decoration: none;
}
```
**Expected output:**
```
.wrapper {
  background: red;
}
.wrapper.class {
  text-decoration: none;
}
```
I'm not sure in which version this broke (in my projects i just noticed this bug now). But this could break a lot of sites if you would ever update older sass tools.

In my humble opinion this is a pretty major bug because it could break existing sites if you ever update your sass library.

**Comment by nex3** [comment]
I don't understand the problem here. The order of class selectors within a compound selector shouldn't affect anything about how that selector's style rule works. Why do you consider this a bug? How could it break sites?

**Comment by bskibinski** [comment]
@nex3 Sorry you're absolutely right!
I was looking at a very similar bug for libsass:
https://github.com/sass/libsass/issues/2681

**input:**
```
%extend {
  background: red;
  &:hover {
    text-decoration: none;
  }
}
input {
  &[type=button] {
    @extend %extend;
  }
}
```
**output in libsass:**
```
input[type=button] {
  background: red;
}
input:hover[type=button] {
  text-decoration: none;
}
```
And in that bug report the order does matter. Then i noticed this order difference and wasn't thinking straight...

It was a long day...

**Comment by nex3** [comment]
That bug seems specific to libsass, so I'm closing this out.
