### ISSUE TITLE
Scoped variable declarations override global variable definitions.

### ISSUE THREAD

**Issue by twoolie** [sass/sass#258]
Test SASS file: 

```
$color: white
.scoped
    $color: black
    color: $color
html
    color: $color
```

Expected Output:

```
.scoped { color: black; }
html { color: white; }
```

Actual Output:

```
.scoped { color: black; }
html { color: black; }
```

it seems like the scoped variable assignment overrides the superscoped variable. I do not know if this is by design or not but i could not find mention of it in the issues list, or the language reference.

**Comment by chriseppstein** [comment]
it is by design.

**Comment by twoolie** [comment]
@chriseppstein Could you please explain why this is part of the design?

**Comment by chriseppstein** [comment]
It was a decision that was made before I worked on the project. Maybe @nex3 can shed some light.

**Comment by nex3** [comment]
The variable is declared in the global scope. Once it's been declared here, any reference to it refers to the globally-declared variable. This includes setting it.

This may change if we ever move to a less imperative semantics for the variables, but I'm going to close this issue because it certainly won't change on its own.

**Comment by twoolie** [comment]
> I'm going to close this issue because it certainly won't change on its own.

@nex3 does this mean it won't change without someone pushing the change, or it won't change until the language changes as well?
- If you need someone to make the changes and give you a pull request, I volunteer.
- If no change is to be made, can someone please add this to the documentation on variable scoping?

**Comment by nex3** [comment]
This change would only go along with other, wider-reaching, changes in the semantics of variables.

I'll see what I can do about clarifying the documentation.

**Comment by bertBruynooghe** [comment]
You can work around this problem by not using global variables, but using functions instead.
A bit more work, but it offers more safety.
  @function testValue(){@return 1px;}
  .test3{
    top: testValue()
  }

**Comment by 166MMX** [comment]
:( ugly variable names - here we come
