### ISSUE TITLE
Implement ability to increase a selector specificity by some syntax sugar

### ISSUE THREAD

**Issue by hardrese7** [sass/sass#2582]
Hey, everyone knows that using of `important` in CSS is the biggest evil. But there is one good hack for it — selector repeat, for example:
```
.link {
color: red;
font-size: 24px;
line-height: 24px;
}

.link { // without hack
color: green !important;
font-size: 26px !important;
line-height: 26px !important;
}

.link.link { // with hack
color: green;
font-size: 26px;
line-height: 26px;
}
```

it's really helpful, I have tried to do it with SCSS:
```
.class1__el {
padding: 10px;
}
@media only screen and (max-width : 700px) {
    .class1 {
      &__el#{&}__el {
        padding: 27px 31px 27px;
    }
}
```

it works but it looks strange, also what will be if I need to increase specificity again and again?

I suggest adding some syntax sugar here, something like:
```
    .class1 {
      &__el:set-specificity(4) {
        padding: 27px 31px 27px;
      }
   }
``` 
that will be compiled to
```
.class1__el.class1__el.class1__el.class1__el {
    padding: 27px 31px 27px;
}
```

**Comment by tinyRepository** [comment]
Very good idea

**Comment by esr360** [comment]
I have never had to use this hack and I've been around the block multiple times with CSS. As useful as it may be (or seem), I'm inclined to think if you need it, it's because you've done something wrong elsewhere. Frankly this is more abusive than using `!important` imo.

**Comment by hardrese7** [comment]
@esr360 so you just suggest using of `!important` for such cases, right?

https://j11y.io/css/dont-use-important/
according to that article, `!important` is bad because we can't override it without another `!important`. But with the hack we can avoid described trouble.

Could you describe why it is ` more abusive than using !important`?

**Comment by hardrese7** [comment]
as a cherry pick, let's make some search on importants in scss-lang.ru code? Seems someone from their team did `something wrong elsewhere`. And I'm not alone)
![image](https://user-images.githubusercontent.com/10993151/47782068-e92d5b80-dd31-11e8-897a-a7cce5117a28.png)

**Comment by esr360** [comment]
@hardrese7  I guess if anything I'm suggesting that if you find yourself having to do this it probably means you have some inefficiencies elsewhere in your codebase.

**Comment by nex3** [comment]
This isn't something we intend to add, for a number of reasons:

* Sass-only pseudo-selectors violate the design principle of making it clear what's Sass and what's CSS, and risks overlapping with future CSS additions.
* This pseudo-selector wouldn't behave like a normal CSS selector; it doesn't select a set of elements, it modifies the behavior of other selectors in its compound selector.
* The pseudo-selector would only work in certain circumstances (when its compound selector contained a repeatable selector with specificity 1).
* It's not clear that this is even a good practice in the first place.

If you really want, I'm pretty sure you could make a selector function that did this, too.

**Comment by maxcooper** [comment]
If anyone else finds this issue looking for a good way to increase specificity, here's a mixin that adds `:nth-child(n)` to the parent selector, which increases the specificity while selecting the same elements:
```
@mixin increase-specificity($amount: 1) {
  $suffix: '';
  @for $i from 0 to $amount {
    $suffix: $suffix + ':nth-child(n)';
  }
  &#{$suffix} {
    @content;
  }
}
```
To use:
```
.myClass {
  @include increase-specificity(4) {
    content: 'I am specific!';
  }
}
```
Which emits:
```
.myClass:nth-child(n):nth-child(n):nth-child(n):nth-child(n) {
  content: 'I am specific!';
}
```
