### ISSUE TITLE
Unable to find .sass-cache in windows

### ISSUE THREAD

**Issue by 0xcrypto** [sass/sass#2583]
I am trying to clean the cache but there is no .sass-cache in the project directory. I deleted the whole project and cloned the remote repo again. Still after recompiling, there is no sign of .sass-cache in the project directory. Does it reside somewhere else in the Windows?

I am using version 1.14.3 dart implementation.

**Comment by nex3** [comment]
Dart Sass doesn't create a cache directory, since its parser is fast enough that caching is unnecessary.
