### ISSUE TITLE
#sass IRC channel

### ISSUE THREAD

**Issue by fkm** [sass/sass#2588]
Hi there

I wanted to ask, if the #sass IRC channel on freenode is owned by this project.

The channel is set to moderated for no apparent reason.

**Comment by nex3** [comment]
I vaguely recall setting something up on IRC ages ago, but I don't remember the details. I may still be a moderator or something, though. How would I go about disabling it?

**Comment by fkm** [comment]
Let's hope so :-)

First you'd need to authenticate with NickServ:
`/msg NickServ identify <nick> <password>`

Then ChanServ should give you channel operator status after which you can remove the moderated (m) channel mode:
`/mode #sass -m`

**Comment by nex3** [comment]
Unfortunately, it seems I'm not an operator. If you can get an admin to mark the channel as un-moderated, consider this post official maintainer endorsement of that.

**Comment by Sur3** [comment]
The IRC is still moderated.. :-/
