### ISSUE TITLE
Caching compass sprites fails on windows

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#259]
See this issue in compass: https://github.com/chriseppstein/compass/issues/625

**Comment by nex3** [comment]
This is just a filename escaping issue, correct?

**Comment by chriseppstein** [comment]
Pretty sure. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by nex3** [comment]
Do we have a way to test a fix for this? I don't personally have easy access to any Windows machines.

**Comment by chriseppstein** [comment]
Another bug in compass for this: https://github.com/chriseppstein/compass/issues/695 I think @StanAngeloff can help us with testing.

**Comment by StanAngeloff** [comment]
Yup, I'd be happy to. I'm on the move for the next 2-3 hours, but if it helps, I can set up Teamviewer for an overnight connection if you need direct access to the VM (it is going to be somewhat slow). I'd also be happy to assist with testing patches, etc.

**Comment by StanAngeloff** [comment]
It may actually turn out to be a rather simple issue. On _nix systems, the `_` is a valid character for file names:

```
$ touch \*\*HELLO\*\*
$ ls -hal
-rw-r--r-- 1 stan stan    0 2012-02-02 20:22 **HELLO**
```

When an `@-import` contains special characters like `*` those are not escaped properly and on Windows cause issues. Simply substituting the invalid character works for me:

``` ruby
# lib/sass/cache_stores/filesystem.rb

def path_to(key)
  File.join(cache_location, key).gsub('*', '-')
end
```

I haven't looked through the entire source code and there may as well already exist a sanitising function to do just this.

**Comment by mihaibirsan** [comment]
If you came to this page still experiencing this issue, run `gem install sass` to update your sass gem.

This issue has been fixed is sass. The compass team should update the dependency requirement so that the sass gem also gets updated. (Currently running sass-3.1.15 and it works.)

**Comment by Nilegfx** [comment]
@mihaibirsan thank you .. i faced this and after i (gem install compass) it worked just fine. thank you all.
