### ISSUE TITLE
Force Sass not to compile css variable (when wished)

### ISSUE THREAD

**Issue by pmochine** [sass/sass#2594]
I tried with [Stackoverflow](https://stackoverflow.com/posts/53836822), but had no luck.

I have this line:

    min-height: calc(100vh - var(--vh-offset, 0px));

but it is compiled to:

    min-height: calc(100vh - 0px);

However, my goal is that it stays like this:

    min-height: calc(100vh - var(--vh-offset, 0px));

so that I can update --vh-offset with javascript. 

How can I say sass to let the line be as it is?

**Comment by nex3** [comment]
The behavior you're describing is not standard Sass behavior. My best guess is that, somewhere in your stylesheet codebase, you've defined a Sass function named `var()` that's shadowing the built-in CSS `var()` function.

**Comment by pmochine** [comment]
@nex3 hmm you are right! super weird. I installed a fresh laravel project and tried to compile it and it is like you said. 

Now it's time to debug it...

**Comment by pmochine** [comment]
So thank you again @nex3, I found the bug in my webpack mix file.

I'm using:

    mix.js('resources/assets/js/app.js', 'public/js')
	.sass('resources/assets/sass/app.scss', 'public/css')
	// .options({ 
	// 	postCss: [
	// 	require('precss')() <--- this gave me the problem
	// 	]
	// })
