### ISSUE TITLE
Breaks some PostCSS Plugins

### ISSUE THREAD

**Issue by octoxan** [sass/sass#2595]
Trying to use this via Laravel Mix, and am getting the following error when trying to use the https://github.com/jonathantneal/postcss-at-else plugin

```shell
Module build failed: ModuleBuildError: Module build failed:
} @else {
Invalid CSS: @else must come after @if
```

**Comment by nex3** [comment]
There's not much we can do about this. `@else` is meaningful Sass syntax, and was for years before that plugin was released. I think your best bet is to try to get that plugin to choose a syntax that doesn't conflict with Sass.
