### ISSUE TITLE
@try/@catch operator.

### ISSUE THREAD

**Issue by damienwebdev** [sass/sass#2596]
# Proposal: 
Add a try/catch operator to sass to handle `@error` directives more cleanly without hard compiler crashes.

## Use Case
As a developer, I'd like to be able to write test code to cover my sass functions. I'm unable to test all branches of my code as my `node-sass` compiler crashes if it reaches an `@error` directive. While I am glad that the `@error` worked as intended and crashed while I was using the function, I'd like to be able to catch the exception during "test" mode and make an assertion about the message that was thrown.

See: https://github.com/oddbird/true/issues/92 for an example.

### Side comments
With `sass` as popular as it is, and new sass code being written every day, I find that the number of projects that I've worked on without tests for functional code to be high. Testing is necessary for maintenance and confidence in code. As sass is becoming a de-facto "language" for writing stylesheets, it seems that the `@error` operator necessitates a partnering try/catch directive. Even if `@error` is a weakly typed error, and try/catch doesn't have exception types, having the ability to catch an exception and handle it (if only for testing purposes) allows me to be confident that the code that I write is working the way I intend.

**Comment by damienwebdev** [comment]
After a brief review @nex3 should I move this into `sass/language`?

**Comment by nex3** [comment]
This looks like it would be valuable! If you want to start [the process of speccing it out](https://github.com/sass/language/blob/master/CONTRIBUTING.md), please go ahead.

**Comment by kaelig** [comment]
I’m not against try/catch from a programmer's standpoint, but I wonder if this construct would go against the foundations upon which CSS is built: in CSS, when something doesn’t work or can’t be parsed, then it’s ignored by the user-agent. Try/catch leads Sass towards an entirely new direction.

As a library author I’d be _pro_-try/catch, but I thought useful to bring this up in case this spec happened to want to be mindful of said point.

Edit: considering Sass already has `@error` and `@warn`, I think try/catch blocks would be a pretty good addition to the language.

**Comment by damienwebdev** [comment]
Closing in favor of https://github.com/sass/language/issues/56

**Comment by johncrim** [comment]
@damienwebdev - how is #56 a better issue report than this one? It seems unrelated.

I strongly agree with the original issue, eg @catch is needed particularly for sass unit tests.

**Comment by damienwebdev** [comment]
@johncrim this was moved to #2619 and #2850 which originally existed across a variety of repos that have now been merged together. I suspect my original comment must have been migrated in a strange way leaving the odd ref.

**Comment by mirisuzanne** [comment]
I started on the proposal there, and then got pulled to other things. Happy for feedback or contributions as people have time.

**Comment by juanRabaa** [comment]
Is this being considered? I run into a problem creating font faces dynamically when the font file isn't found. I would like to only create the font face is the file exists, or in the worst case, prevent the error if it doesn't.

Saw this related issue https://github.com/sass/sass/issues/779

**Comment by mirisuzanne** [comment]
This is still planned, and is my next priority once we ship the new color spaces.
