### ISSUE TITLE
scss parse error

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#26]
Consider the following SCSS file:

```
$var: true and
      false;
@debug "Should be false: #{$var}";
```

You'd expect the output to be:

```
Line 3 DEBUG: Should be false: false
```

But instead you get:

```
Line 3 DEBUG: Should be false: true and false
```

Removing the newline from the assignment expression yields the correct behavior.

**Comment by nex3** [comment]
Merge branch &#39;stable&#39;

Closed by da1b39fa47bc60aed191e649acc321203adf20e5
