### ISSUE TITLE
A bug when compiling `@include boxShadow(inset 0 -$depth 0 0 rgba(0, 0, 0, 0.15));`

### ISSUE THREAD

**Issue by tanin47** [sass/sass#2601]
It seems Sass drops the first zero. Here's the minimal reproducible example:

```
$ sass --scss src.scss  test.css

$ cat src.scss
@mixin boxShadow($statement){
  -webkit-box-shadow: $statement;
  -moz-box-shadow: $statement;
  box-shadow: $statement;
}
@mixin buttonSize($depth){
  @include boxShadow(inset 0 -$depth 0 0 rgba(0, 0, 0, 0.15));
}
.test {
  @include buttonSize(3px);
}

$ cat test.css
.test {
  -webkit-box-shadow: inset -3px 0 0 rgba(0, 0, 0, 0.15);
  -moz-box-shadow: inset -3px 0 0 rgba(0, 0, 0, 0.15);
  box-shadow: inset -3px 0 0 rgba(0, 0, 0, 0.15); }

/*# sourceMappingURL=test.css.map */
```

Please notice that: `@include boxShadow(inset 0 -$depth 0 0 rgba(0, 0, 0, 0.15));` in `src.scss` is compiled to `inset -3px 0 0 rgba(0, 0, 0, 0.15);` in `test.css`.

The root cause is definitely the `-` in `-$depth`. Once I remove that minus sign and use `@include buttonSize(-3px)` instead, it works properly.

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/1912.
