### ISSUE TITLE
Bug of the global flag

### ISSUE THREAD

**Issue by max-hk** [sass/sass#2609]
According to the documentation, the !global flag assign values to a global variable.

> You may now explicitly assign to global variables using the !global flag

However, the code below
```
$aVar: 100px;

@mixin abc {
    @media (min-width: 700px) {
        $aVar: 200px !global;
        @content;
    }
}

.a {
    @debug $aVar; // Should this line ouptput 200px?
    @include abc {
        @debug $aVar; // 200px
    }
}
```
Give output like this
```
test.scss:11 Debug: 100px
test.scss:13 Debug: 200px
```

Shouldn't both line 11 and 13 give a output of 200px, as aVar is overwritten to be 200px?

**Comment by nex3** [comment]
In your example, you haven't executed the mixin that contains `$aVar: 200px !global` at the point at which you execute the first `@debug`. As such, the variable hasn't yet been reassigned.
