### ISSUE TITLE
#{$i} this is not supported

### ISSUE THREAD

**Issue by Hideer** [sass/sass#2611]
lock title 

![image](https://user-images.githubusercontent.com/31301552/53938110-1e83f480-40ea-11e9-8726-7065d191280e.png)

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
