### ISSUE TITLE
What should the syntax for module mixins be?

### ISSUE THREAD

**Issue by nex3** [sass/sass#2624]
Draft 2 of the proposal allows a [module mixin](https://github.com/sass/language/tree/proposal.module-system.draft-2/#module-mixins) to be defined using the syntax `@use "susy" mixin`. This defines a mixin with the same name as the module's prefix that, when included, injects the module's CSS at that point in the document. This is intended to satisfy the use-case currently handled using [nested imports](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_import), where a user wants to scope a chunk of upstream CSS within a specific selector or media query.

I'm not sure this is the best syntax to use, though. Creating an implicit mixin feels weird, especially because it means `namespace` and `namespace.member` will both be meaningful identifiers, but the latter won't actually be referring to a member of the former. It would also be the only instance under the new module system where a `@use` without `no-prefix` would create an identifier that's not part of a unique namespace.

**Note:** I'm considering this discussion largely orthogonal to https://github.com/sass/language/issues/8. In any of these proposals, the module mixin may or may not allow configuration parameters to be passed.

## Possible Options

1. ### Keep the existing syntax

   ```scss
   @use "susy" mixin;

   .susy {
     @include susy;
   }
   ```

2. ### Add a meta mixin and a `silent` modifier

   This mixin would take the namespace or URL of the module and include its CSS. This way we don't pollute the top-level namespace. It would also require adding a modifier to `@use` to tell it not to generate any CSS on its own, but that may be useful anyway.

   ```scss
   @use "susy" silent;
   @use "sass:meta";

   .susy {
     @include meta.module-css("susy");
   }
   ```

3. ### Add a meta mixin that can dynamically load files

   If the meta mixin can take a module URL, it raises a new question: why not just allow it to take *any* URL, not just one that has a `@use` declaration in the same file? This dovetails with the planned [`load()`](https://github.com/sass/sass/issues/739#issuecomment-279093113) function nicely; it would effectively be a shorthand for `@include meta.include(map.get(meta.load($url), "css"))`.

   It also dodges most of the downsides of dynamic includes, because it explicitly *does not* introduce any new names to the file that includes it. Static analysis therefore remains tractable (although, as with `load()`, it does become impossible to statically determine the set of files a stylesheet depends on).

   ```scss
   @use "sass:meta";

   .susy {
     @include meta.load-css("susy");
   }
   ```

**Comment by nshahan** [comment]
It sounds like option 3 might be a problem for build systems with strict dependency management.
