### ISSUE TITLE
What should the syntax for @use without a namespace be?

### ISSUE THREAD

**Issue by nex3** [sass/sass#2625]
Although we want to encourage users to use namespaces for most of their modules, there are valid use-cases for avoiding namespaces, such as importing a legacy library that already uses manual namespace. Draft 2 defines the syntax for doing this as `@use "susy" no-prefix`, but I'm not thrilled with this. The term "prefix" is a holdover from when namespaces just added to the identifier rather than using a `.` to separate names (`susy-foo` versus `susy.foo`), and if possible I'd like the syntax to more closely mirror that of choosing a prefix (`@use "susy" as grid`).

## Possible Options

1. ### Keep the existing syntax

   ```scss
   @use "susy" no-prefix;
   ```

2. ### Use another keyword

   ```scss
   @use "susy" no-namespace; // Kind of wordy
   @use "susy" global; // "global" isn't really accurate; it's scoped to this module
   ```

3. ### Mirror the explicit namespace syntax

   ```scss
   @use "susy" as *;
   ```

**Comment by TedSander** [comment]
I would vote for option 3. I like that it is similar to regular syntax while also keeping it just awkward enough that hopefully people don't use it as the default.
