### ISSUE TITLE
env() and max() issue

### ISSUE THREAD

**Issue by BenjaminHoegh** [sass/sass#2639]
When developing for smartphones like iPhone X(S/R) or P20 you use `env(safe-area-inset-[left|right|top|bottom])` but for some reason you can't use it inside `max()` when coding in SASS
`padding-right: max(12px, env(safe-area-inset-right));`

https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/2378. Dart Sass has supported plain CSS `min()` and `max()` since 1.11.0, but LibSass and Ruby Sass don't yet. If it's an important feature for you, I suggest switching to Dart Sass.

**Comment by nex3** [comment]
That depends what implementation you're using. Ruby Sass added support in https://github.com/sass/ruby-sass/pull/85, which will be released as part of 3.7, probably in the next week or two. However, Ruby Sass is deprecated, so if you're using it you should look into migrating to another implementation anyway. I don't know what the timeline for LibSass is, but you can follow https://github.com/sass/libsass/issues/2701 for updates.
