### ISSUE TITLE
NameError in lib/sass/tree/visitors/deep_copy.rb: undefined 'query'

### ISSUE THREAD

**Issue by StanAngeloff** [sass/sass#265]
```
$ sass --version
Sass 3.2.0.alpha.62 (Bleeding Edge)
```

I believe [line 94 of lib/sass/tree/visitors/deep_copy.rb](https://github.com/nex3/sass/blob/master/lib/sass/tree/visitors/deep_copy.rb#L94) should read:

``` ruby
node.query = node.query.deep_copy
```

I am not familiar with the code, but prefixing `query` with `node.` seems to work well in local development.

**Comment by gxclarke** [comment]
I am experiencing the same issue with 3.2.0.alpha.64.

**Comment by dfross** [comment]
Ditto - same as gxclarke.
