### ISSUE TITLE
Upcoming -webkit-filter:grayscale(); throws synax error

### ISSUE THREAD

**Issue by potench** [sass/sass#267]
The upcoming `grayscale()` filter implemented in Chrome Canary throws a parse error when compiled in SASS

```
0 is not a color for `grayscale'
```

because there is an existing function in SASS called grayscale

```HSL Colors:
The {Sass::Script::Functions#grayscale grayscale} function converts a color to grayscale.

```
```

**Comment by nex3** [comment]
Duplicate of #239.
