### ISSUE TITLE
Loading existing source maps

### ISSUE THREAD

**Issue by niksy** [sass/sass#2673]
Is Sass capable of loading existing source maps of source file before processing those files?

Currently, I’m working on a codebase where we need to first process Sass files with external tool, changing it’s contents and then pass that file to Sass for further processing. That external tool can generate source maps, but it seems like Sass ignores those source maps when it compiles to CSS, producing inconsistent result.

Is this something that is defined in spec or should I ask question on technical implementation repository like `libsass`?

**Comment by nex3** [comment]
This is something that's better handled by a tool that's dedicated to the purpose. I believe [the `source-map` package on npm](https://www.npmjs.com/package/source-map) is generally considered the best in class for manipulating and merging source maps.
