### ISSUE TITLE
Index in @each return wrong number when same value passed more than once

### ISSUE THREAD

**Issue by skrzepij** [sass/sass#2674]
Hi, 
I've create a small mixing to set elements width it looks like this: 

```
=setSectionsWidth($args...)
  @if length($args) < 1
    flex-direction: column
    .trf-section
      width: 100%
  @else
    flex-direction: row
    @each $elWidth in $args
      $i: index($args, $elWidth)
      .section:nth-child(#{$i})
        width: $elWidth
  ```

And then I'm using it in the wrapper:
```
.sectionsWrapper
  +setSectionsWidth(40%, 60%)
```

This works pretty good, but I've encounter with a problem, when I'm passing two, the same values: 
```
setSectionsWidth(50%, 50%)
```
In this case, `index()` will return two times same value (`1`). 
As we can presume - styles will be duplicated for the first element (`.section:nth-child(1)`), and second element will remain without styling.

**Comment by nex3** [comment]
The `index()` function doesn't know anything about your `@each` context; it just returns the index of the first instance of the value in the list. If you want to have the iteration index, you can use `@for` instead:

```sass
=setSectionsWidth($args...)
  @if length($args) < 1
    flex-direction: column
    .trf-section
      width: 100%
  @else
    flex-direction: row
    @for $i from 1 through length($args)
      $elWidth: nth($args, $i)
      .section:nth-child(#{$i})
        width: $elWidth
```
