### ISSUE TITLE
Which sass compiler is faster

### ISSUE THREAD

**Issue by AtlasianOnline** [sass/sass#2685]
Hi

Which sass compiler is faster, has better performance?

Dart-sass, node-sass, lib sass, Ruby sass?

**Comment by sarsamurmu** [comment]
LibSass isn't standalone. Mostly Dart Sass and Node Sass is Faster. Forget about Ruby Sass.

**Comment by AtlasianOnline** [comment]
when Ruby Sass encounters an error, by default it produces a CSS file that includes the error message and stack trace in a comment as well as in the content property of a body::before style rule in order to make it immediately visible during users' edit/refresh cycle. Dart Sass and Node Sass don‘t do this currently. How can I anable this method on Node Sass?

**Comment by sarsamurmu** [comment]
Node Sass Shows all error message and stack traces in Command Line.

**Comment by nex3** [comment]
> Hi
> 
> Which sass compiler is faster, has better performance?
> 
> Dart-sass, node-sass, lib sass, Ruby sass?

Node Sass is just a JavaScript wrapper for LibSass. You can see some benchmarks between implementations [here](https://github.com/sass/dart-sass/blob/master/perf.md), although they're a bit out-of-date at this point.



> when Ruby Sass encounters an error, by default it produces a CSS file that includes the error message and stack trace in a comment as well as in the content property of a body::before style rule in order to make it immediately visible during users' edit/refresh cycle. Dart Sass and Node Sass don‘t do this currently. How can I anable this method on Node Sass?

Dart Sass just added support for this in [version 1.20](https://github.com/sass/dart-sass/releases/tag/1.20.0).
