### ISSUE TITLE
Is there any return value from @mixin?

### ISSUE THREAD

**Issue by nh0627** [sass/sass#2686]
Hi! as a Javascript developer, I am all of sudden wondering if there is any return value from @mixin.

In Javascript, even though a method does not have a return statement, but still it returns "undefined".

Is there something like this in @mixin of Sass? 

Is there any returned value out of @mixin (void or undefined, or something like these)?

(I know when I want to return some variable or value, I can use @function & @return.)

Thank you!

**Comment by nex3** [comment]
No, there is not. Mixins can't be used in an expression context, so it doesn't make sense for them to return anything.
