### ISSUE TITLE
Order of compilation for nesting and parent selector

### ISSUE THREAD

**Issue by alanyinjs** [sass/sass#2687]
It seems that Sass is compiling nesting before parent selector. Not sure if this is the intended behaviour or it's actually a bug (couldn't find much info in documentation). I understand that this type of nesting is rare if you follow good practice. However I was simply wondering out of curiosity.

e.g. What Sass will do is that it will handle the nesting first, so the following code:

```
.class-a {
  .class-b {
     & > &-item {
      color: red;
      background-color: red;
      font-size: 36px;
    }
  }
}
```
will actually be equivalent to
```
.class-a. class-b {
  & > &-item {
    color: red;
    background-color: red;
    font-size: 36px;
  }
}
```
which gets compiled to 
```
.class-a .class-b > .class-a .class-b-item {
  color: red;
  background-color: red;
  font-size: 36px;
}
```
instead of
```
.class-a  .class-b > .class-b-item {
  color: red;
  background-color: red;
  font-size: 36px;
}
```
which seems to be the more 'desired' behaviour.
<img width="1646" alt="Screen Shot 2019-05-10 at 1 28 27 pm" src="https://user-images.githubusercontent.com/25688258/57500758-fa31d780-7327-11e9-8157-0a8cad7a5dc0.png">

**Comment by nex3** [comment]
This is intended. Every `&` you include in a selector is replaced as-is with the fully resolved parent selector, in this case `.class-a .class-b`.
