### ISSUE TITLE
When I want to splicing with $i:1 and % in lists, how should I write it?

### ISSUE THREAD

**Issue by luqiudi** [sass/sass#2689]
En：
When I want to splicing with $i:1 and % in lists, how should I write it?
This will give you an error, what should I do?
Like:
```
$arrlinear:(135deg);
        @for $i from 0 to 100 {
            // $e:appen(red $i%);
            
            $arrlinear:append($arrlinear,red #{$i}%,comma);
            // $arrlinear:append($arrlinear,$e,comma);
        }
```

CN：
当我想在lists里面用 $i:1 和 %进行拼接的时候，应该怎么写呢;
这样写会报错的啊，我该怎么做
就像：
```
$arrlinear:(135deg);
        @for $i from 0 to 100 {
            // $e:appen(red $i%);
            
            $arrlinear:append($arrlinear,red #{$i}%,comma);
            // $arrlinear:append($arrlinear,$e,comma);
        }
```

please tell me，thanks very much= =；

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
