### ISSUE TITLE
&(n): nth Parent Selector Proposal

### ISSUE THREAD

**Issue by n8yeung** [sass/sass#2690]
&(n): nth Parent Selector would accept a parameter n. If n is equal to 1 then it would be the immediate parent or the parent of the level that is directly above the current section. If n is equal to 2 then it will go two levels up and so forth.

**Comment by n8yeung** [comment]
This is similar to https://github.com/sass/sass/issues/2264#issue-216577214 but focuses only on distance from the current section.

**Comment by nex3** [comment]
I suggest doing this using [selector functions](https://sass-lang.com/documentation/functions/selector) and [the parent selector expression](https://sass-lang.com/documentation/style-rules/parent-selector#in-sassscript).
