### ISSUE TITLE
Partial referencing itself with @import

### ISSUE THREAD

**Issue by dancombs** [sass/sass#270]
Mixin file referencing itself within @import will cause the server to spin off to oblivion.

Example..

File with the name "_mixin.sass" which has the following...

``` scss
@import "_mixin.sass"
```

Watch the process monitor sky rocket...

**Comment by chriseppstein** [comment]
At the least we should error out here, but I think we should just not perform the second import of the same file.

**Comment by nex3** [comment]
I've updated the title of this, since it's actually about partials, not mixins.

I'm up for forbidding a file to import itself. The more general multi-import case is more likely to break stuff, so that warrants more thought.
