### ISSUE TITLE
@export + @include => @exclude

### ISSUE THREAD

**Issue by Media-Evil** [sass/sass#2700]
The idea is to resolve the mixin  in respect to the specified location, exclude it from the document and export somewhere else and then download it on-demand.

@export + @include => @exclude mixinName ( settings );

**Comment by Media-Evil** [comment]
Though this seems quite odd. To give a precise example: imagine u have a partial that contains a mixin. Then u import that partial to the main file, include (and extend the mixin) then resolve the result into a separate file that is loaded on-demand.

Odd because I see no way to make it intuitive.

**Comment by nex3** [comment]
I'm sorry, there's no way to do this. If you want to serve separate CSS files, we recommend having separate Sass entrypoints (non-partial files) that share mixins with one another.
