### ISSUE TITLE
Conversion issue RGBA to HSLA

### ISSUE THREAD

**Issue by harikrishna159** [sass/sass#2725]
Hi, Team. 
I am facing the issue of converting RGBA to HSLA. I don't want to convert RGBA to HSLA. how can I stop that?  At this time I have created a variable like this.

$fma-rich-white-with-transparency: rgba(255, 255, 255, 0.6);
assigned this to  background-color: $fma-rich-white-with-transparency;.  

In final result it's converting like this  Actual result : background-color: hsla(0,0,100%,.6);
Expected result is : background-color: hsla(0,0%,100%,.6);
Can you please hlp me how can I unistall RGBA to HSLA converter.Becuse ) 0% coversion is not happening.

Thanks,
Hari

**Comment by nex3** [comment]
We need more information in order to help you with your problem. Which Sass implementation are you using, and version of Sass? What's the Sass source that's not behaving how you expect, what output are you expecting, and what output or error are you getting instead? Please make sure your example is as tightly-focused on the problem as possible, so that it's easy for us to understand what's going on.

**Comment by zhaolc90** [comment]
I have the same problem:
when I defined color : rgba(254, 238, 233, 0.5)
which will convert to ~~hsla(14,91%,95%,.5)~~

what I want is hsla(14,91.3%,95.5%,.5), there losing precision somehow.

**Comment by nex3** [comment]
@zhaolc90 Same questions as above.

**Comment by musaffar-patel** [comment]
Hi

I am also experiencing this issue,

In scss file I have the property:

color: rgba(255, 255, 255, 0.5);

But after it's compile to css, it converts it to:

color: hsla(0,0%,100%,.5);

How can this conversion be prevented so that the output css remains:
color: rgba(255, 255, 255, 0.5);

Kind Regards
Musaffar

**Comment by Awjin** [comment]
@musaffar-patel We need more information to help with your problem. Which Sass implementation are you using, and version of Sass?

**Comment by msaktor** [comment]
I have the same issue 
```
    "node-sass": "4.14.1",
    "sass-loader": "^6.0.6",
```

**Comment by volalex** [comment]
Hi,
Same issue here
`color: rgba(255, 255, 255, 0.7);`

Converts to
`color: hsla(0,0%,100%,.7);`

Also I see this only in release css, in webpack dev mode all is fine

I am using sass loader from vue.js vue.config.js

Versions from package-lock.json (omitted some lines for brevity):
`
"node-sass": {
      "version": "4.13.1"
}`
`"sass-loader": {
      "version": "8.0.2"
}
`
Would appreciate any help
Kind regards,
Alexey

**Comment by Awjin** [comment]
This an issue with [`node-sass`](https://github.com/sass/node-sass); please open a bug there. I will encourage you to use the reference implementation of Sass, which is Dart Sass, and is available for installation in Vue.js.

**Comment by rener172846** [comment]
Hi,
It's still existing issue even I switched from `node-sass` to `sass`.

```
color: rgba(24, 24, 24, 0.8);
```

Is converted to
```
color: hsla(0,0%,9%,.8);
```

The correct color in hsla should be
```
color: hsla(0,0%,9.4%,.8);
```

I'm ok even rgb color converted to hsl, but the converted color has the tangible difference and it should be fixed.
Additionally everything works well in dev mode, this issue occurs only in prod mode.

**Comment by nex3** [comment]
@rener172846 I can't reproduce this. With Dart Sass 1.57.1 in compressed mode, I get `color::rgba(24,24,24,.8)`.

**Comment by rener172846** [comment]
@nex3 I don't know what's the Dart Sass, I've used `node-sass` so far, but just tried to install sass by `npm install sass` command and it shows version 1.57.1 in the package.json.
And have you checked after build? `rgba` works correctly on the develop mode.

**Comment by nex3** [comment]
```shellsession
$ mkdir /tmp/test
$ cd /tmp/test
$ npm init -y
$ npm i sass
$ npx sass --version
1.57.1 compiled with dart2js 2.18.6
$ echo 'a {color: rgba(24, 24, 24, 0.8);}' | npx sass -
a {
  color: rgba(24, 24, 24, 0.8);
}
```

I think your configuration is causing you to compile with a different version of Sass than you expect.

**Comment by rener172846** [comment]
Hi @nex3 , I tried with your command lines, and get same result as you.
Please note that I just switched to Sass, so it should be the latest version, and the problem is that I got that issue only on the production build, on the development mode everything works well.

**Comment by nex3** [comment]
It sounds like your production build is still using Node Sass.
