### ISSUE TITLE
The universal selector should be a superselector of everything

### ISSUE THREAD

**Issue by nex3** [sass/sass#2728]
- [x] Specs (https://github.com/sass/sass-spec/pull/1808)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/789) (https://github.com/sass/dart-sass/pull/1753)
- [x] ~~[LibSass](https://github.com/sass/libsass/issues/2962)~~

---

Currently, `is-superselector("*", "a")` returns `false` in all Sass implementations. However, semantically, the selector `*` does match all elements matched by `a`. More broadly, `*` should be considered a superselector of *all* selectors (except those with other explicit namespaces).

**Comment by nex3** [comment]
Similarly, `*|T` should match all `T` whether they're explicitly namespaced or not, and `*|*` should match *all* selectors.

**Comment by GustvandeWal** [comment]
Just found out this doesn't work the hard way. I've been trying to create a sort of `selection.is-child-of(selection)` function by nesting the parent with an asterisk, like so:
`is-superselector(selector-nest($parentSelector, '*'), $childSelector)`. This doesn't work, so for now, I am using this (very verbose and ugly) alternative:
`is-superselector(selector-nest($parentSelector, '[selection="definitely very unique"]'), selector-append(&, '[selection="definitely very unique"]'))`, which breaks with pseudo-element selectors.
