### ISSUE TITLE
I've developed a tool for near instant SASS compilation at scale. Can I promote is somewhere?

### ISSUE THREAD

**Issue by sebastianwebb** [sass/sass#2729]
Hi guys, 

Sorry if this is the wrong place to post. My WordPress plugin compiles SASS in the browser using the SASS.js library by medialize. I've developed a system for [selectively compiling SASS code](https://themeover.com/ultra-fast-sass-compilation-with-microthemer-for-wordpress/) so that compilation time doesn't increase as the project size grows. Instead, it remains at around 50ms.

I would like to get the word out to the SASS community through whatever channel seems appropriate and non-spammy. If someone could point me in the right direction I would be very grateful.

Many thanks,
Sebastian

**Comment by nex3** [comment]
Maybe ping [Sass News](https://twitter.com/sassnews)?

**Comment by sebastianwebb** [comment]
Thanks @nex3, will do!
