### ISSUE TITLE
Generate browser-specific code

### ISSUE THREAD

**Issue by Fodoj** [sass/sass#273]
You know what could be really productive? Browser-specific css generator. I will give you an example:

Write in .scss file:
.box {
     border-radius: 2px;
}

and get in .css file:

.box {
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
   border-radius: 2px; 
}

I think this is awesome idea. May be no very useful when we talk about border-radius, but for gradients, shadows and others this will be very handy feature.

**Comment by markiz** [comment]
You might be thinking about mixins.
Look at http://compass-style.org/, e.g. [border-radius](http://compass-style.org/reference/compass/css3/border_radius/).

**Comment by aackerman** [comment]
This is already possible, and you don't need Compass to do this.

Simple border-radius mixin.
@mixin border-radius($dist) {
  -webkit-border-radius: $dist;
  -moz-border-radius: $dist;
  -o-border-radius: $dist;
  border-radius: $dist;
}

.box {
  @include border-radius(2px);
}

**Comment by Fodoj** [comment]
Yeah, ok. I just was thinking that it would be cool to avoid writing this mixins and rely on sass implementation of them.

**Comment by barraponto** [comment]
Problem is browser are released every few weeks, and they are eventually dropping vendor prefixes and adopting regular CSS3 syntax. Keeping SCSS/SASS mixins up to date is something easy for frameworks, but keeping the language compiler up to date is just more work than it is worth.

Also, it is a SASS/SCSS choice to make mixins explicit. We don't just call mixins without + or @include.

**Comment by nex3** [comment]
@barraponto is correct. Not only is it a bad idea to try to keep up with every single vendor-prefixed property out there, but it's also a bad idea to have some styles that look identical to plain CSS be manipulated by Sass. It makes it extremely difficult to figure out what's going on in the source without a deep knowledge of the internals of Sass.
