### ISSUE TITLE
can I take the value of a variable as a variable with the same name as the value?

### ISSUE THREAD

**Issue by yz-xlame** [sass/sass#2732]
example:
```
.dev {
    $success:  #0f0;
    $name: success;
    background-color: (I want to use $name instead of $success)
}
```

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
