### ISSUE TITLE
sass --watch multiple destinations?

### ISSUE THREAD

**Issue by abuyoyo** [sass/sass#2735]
is it possible to have sass --watch listen on the same file but produce different outputs?
ie. a minified and a non-minified version:

`sass --watch filename.scss:filename.css --style nested filename.scss:filename.min.css --style compressed`

**Comment by nex3** [comment]
I'm sorry, there's no way to do this from the command line. For complex invocations like this, you'll need to either use multiple invocations or the Dart or JS APIs.

**Comment by zaydek** [comment]
I found this to be a helpful solution that doesn’t require Sass introducing new APIs: https://flaviocopes.com/package-json-watch.

Personal usage looks like this: `yarn watch --interval 0.1 'yarn -s sass src/index.scss dist/index.css' src`
