### ISSUE TITLE
Allow custom property identifiers to begin with digits

### ISSUE THREAD

**Issue by robin-dongbin** [sass/sass#2738]
- [x] ~Proposal~ *(The spec is already correct)*
- [x] ~Documentation~ *(Too much of an edge case)*
- [x] [Specs](https://github.com/sass/sass-spec/pull/1460)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/815)
- [x] [LibSass](https://github.com/sass/libsass/issues/2987)

---

Reproduction:
```
:root{
  --10: #333
}

p{
  color: var(--10)
}
```

**Comment by nex3** [comment]
CSS custom property names, like all property names, must be valid CSS identifiers. `--10` is not, because it doesn't begin with a letter after the `-`s.

**Comment by robin-dongbin** [comment]
@nex3 it works well in css but not in scss.

**Comment by nex3** [comment]
I'm sorry, you're right, I just checked [the spec](https://drafts.csswg.org/css-syntax-3/#ident-token-diagram) and it looks like `--` can be followed by a digit and still be an identifier. I believe this is a bug in all existing implementations.

**Comment by nex3** [comment]
It looks like both Dart Sass and LibSass also fail to parse `--`, `---`, and so on as identifiers.

**Comment by nex3** [comment]
Closing out since LibSass is deprecated.
