### ISSUE TITLE
SASS imported file importing another file keeps parent's path

### ISSUE THREAD

**Issue by Loxoz** [sass/sass#2741]
* System: Windows 10
* Node : v10.15.0
* NPM : 6.11.2
* webpack : 4.39.3
* sass-loader : 8.0.0
* sass : 1.23.0-module.beta.1

So i got a problem and misunderstand with sass and webpack (``sass-loader``):
(Hope it's not related to sass-loader)

This is my files tree:
```bash
| src/
   | page/
      | app.scss
   | globall.scss
   | default.css
```

> page/app.scss
```scss
@import '../global.scss';
```

> global.scss
```scss
@import './default.css';
```

And the problem is that ``global.scss`` is trying to search for ``default.css`` in the ``src/page/`` forlder instead of the ``src/`` where it is.
**Here is the error:**
```log
    ERROR in ./src/page/app.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/page/app.scss)
    Module not found: Error: Can't resolve './default.css' in '\src\page'
     @ ./src/page/app.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/page/app.scss) 3:10-88
```
Edit: btw i forgot to mention but using ``/src/default.css`` works well in ``global.scss`` but that's not what i'm wanting

**Comment by nex3** [comment]
The "Module not found" error is coming from webpack's module resolver. I suggest you file an issue against them.
