### ISSUE TITLE
Accept keyword (map) arglists in @use?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#2742]
```scss
// ccs.scss
$hue: 0 !default;
$saturation: 50% !default;

// module that needs to use and forward, with new but configurable defaults…
$config: (
  hue: 330,
  saturation: 80%,
) !default;

@use 'ccs' with ($config...);
@forward 'ccs';
```

This wouldn't really work with positional arguments, but it would provide a great way to pass-along configuration settings from one module to another - similar to the way function/mixin arglists [work well for aliasing](http://modules.sass-lang.com/documentation/at-rules/function#passing-arbitrary-arguments):

```scss
@function fg($args...) {
  @warn "The fg() function is deprecated. Call foreground() instead.";
  @return foreground($args...);
}
```

On the other hand, this is relativly simple to do already, by using a single map for configuration in the original module… 

```scss
// ccs.scss
$config: (
  hue: 0,
  saturation: 50%,
) !default;

// module that needs to use and forward…
$config: (
  hue: 330,
  saturation: 80%,
) !default;

@use 'ccs' with ($config: $config);
@forward 'ccs';
```

**Comment by mirisuzanne** [comment]
Actually, I think you would need to provide a new name at each level in the workaround, or you get naming conflicts…

```scss
// ccs.scss
$config: (
  hue: 0,
  saturation: 50%,
) !default;

// module that needs to use and forward…
$new-config: (
  hue: 330,
  saturation: 80%,
) !default;

@use 'ccs' with ($config: $new-config);
@forward 'ccs';
```

**Comment by nex3** [comment]
Can you go into more detail about the use-case you're envisioning? You mention "passing along" configuration settings, but this already happens automatically with `@forward`. What benefit would a different way of doing it provide?

**Comment by mirisuzanne** [comment]
This was partly trying to work around #2744 without fully understanding it, and partly merging two use-cases that might be better split out: 

First: wrapping packages with new, intermediate default settings. My tools often provide a core module with very un-opinionated defaults, and then wrappers/plugins that provide a more opinionated configuration and additional helpers. That sort of wrapper package needs to:

1. set some origin-package configuration
2. allow the user to set some origin-package config, possibly even overriding the new defaults
3. use the configured origin-package to build helpers

I think if the other bug is fixed, most of that is already supported - but not a clear way to provide intermediate `!default` configurations, because that would cause conflicting config / duplicate use-width. That could be solved with an entirely different syntax, and should maybe have a new issue filed, but I was conflating it with:

Second: syntax sugar, much like the `$map...` keyword syntax in calling functions/mixins. That's not useful in the simple case, where configuration is being set directly - but would be useful if you are dynamically generating config options to be passed into a module. I can't claim that's a super common use-case - but it is the sort of thing I might do. :)

**Comment by nex3** [comment]
> I think if the other bug is fixed, most of that is already supported - but not a clear way to provide intermediate `!default` configurations, because that would cause conflicting config / duplicate use-width. That could be solved with an entirely different syntax, and should maybe have a new issue filed, but I was conflating it with:

You could do:

```scss
// _opinionated.scss
$hue: 0 !default;
$saturation: 50% !default;

@use "unopinionated" with ($hue: $hue, $saturation: $saturation);
```

...but you'd have to manually copy *all* config, any post-facto modifications of `opinionated`'s variables wouldn't affect `unopinionated`'s, and you'd have no way of forwarding anything defined in `unopinionated`. Which is definitely no good.

I think this is something we are not going to solve before October 1, but I consider it high priority for a post-launch feature addition. I'll add it to the agenda of the next Google Sass design meeting, and I'm happy to hear any suggestions. As a straw idea, we could provide a very explicit way to forward a package with overridden configuration, maybe something like:

```scss
@forward "unopinionated" with (
  $hue: 0 !default, // Can be overridden by upstream users.
  $saturation: 50% // Cannot be overridden by upstream users.
);
```

**Comment by mirisuzanne** [comment]
I like that straw idea a lot. thanks!

**Comment by mirisuzanne** [comment]
I can't get your example of chained configuration to work:

> ```css-scss
> // _opinionated.scss
> $hue: 0 !default;
> $saturation: 50% !default;
> 
> @use "unopinionated" with ($hue: $hue, $saturation: $saturation);
> ```

When using `opinionated`, I run into two scenarios:

- As written, I have no access to any members of `unopinionated` - because they have not been forwarded
- If I also `@forward 'unopinionated'`, I get the error: `This module was already loaded, so it can't be configured using "with".`

That seems to also suggest the [chained configuration](https://github.com/sass/migrator/blob/partial-migration/test/migrators/module/chained_configuration.hrx) migrations will cause this  same issue?

**Comment by nex3** [comment]
Yeah, it's not a great workaround. There really isn't a good way to express this right now.

**Comment by nex3** [comment]
Merging this with https://github.com/sass/sass/issues/2744.
