### ISSUE TITLE
Make selectors imported from .css files extendable

### ISSUE THREAD

**Issue by hab25** [sass/sass#2743]
The problem is well explained by the question, and pentzzsolt's answer, here: https://stackoverflow.com/questions/48624359/how-to-extend-a-class-from-a-css-file-in-sass

**Comment by nex3** [comment]
This does currently work, according to my tests, in both Dart Sass and LibSass. There's not currently a spec for it, which is an oversight; I've just put out https://github.com/sass/sass-spec/pull/1463 to fix that.

**Comment by hab25** [comment]
@nex3 Dart sass doesn't work for me. Here's a MRE: https://github.com/vinayluzrao/sass-issue-2743

**Comment by nex3** [comment]
When you write `@import "css-importee.css"`, you aren't actually importing that CSS; you're writing a [plain CSS import](https://sass-lang.com/documentation/at-rules/import#plain-css-imports). To import a CSS stylesheet, you need to leave off the extension and write `@import "css-importee"`.

**Comment by hab25** [comment]
Ah I see, thanks a lot for clearing it up
