### ISSUE TITLE
What Sass version has @use?

### ISSUE THREAD

**Issue by dtvn** [sass/sass#2752]
The reason I ask it because the all the sass lint in vscode store doesn't seem to support `@use` and `@forward`. Does anyone can suggest me a good linter that doesn't put a red mark on my correct code?

**Comment by jathak** [comment]
Dart Sass supports `@use` and `@forward` starting in `1.23.0`.

It looks like VS Code uses its own parser for CSS, so it would be up to them to update it. You should consider +1ing the issue for it: microsoft/vscode#81943
