### ISSUE TITLE
Are `module-variables` to be declared in every file with a different name

### ISSUE THREAD

**Issue by mbellary-chwy** [sass/sass#2756]
I have started using new Sass module system. It is looking great. Thanks for introducing Sass modules. I am playing around with it a lot and trying to find out some best practices.

URL for a Sample project: https://github.com/MansoorBashaBellary/dart-sass-module-test

In the above GitHub project, i have these different files:

1. `_default.scss` -> All class based styles go here
2. `_index.scss` -> Forwarding all tooling related stuff here(mixins, placeholders, variables)
3. `_mixins.scss` -> All mixins go here
4. `_placeholders.scss` -> All placeholders go here
5. `_settings.scss` -> All defaulted variables go here
6. `button.scss` -> This is the file that i used to generate my build file

In the Sass modules, i am liking `module-variables` feature a lot, it almost kills namespacing on each variable declared.

In my `_index.scss` file: i am creating `$btn-settings` as below and using it on `_default.scss`.

```
@use './settings';
$btn-settings: module-variables(settings);
```

If i need to access same button settings on `_mixins.scss` and `_placeholders.scss`, should i be creating new `module-variables` in those files. ?

Please let me know if i am doing some things incorrectly and guide me in following best practices

**Comment by nex3** [comment]
> In my `_index.scss` file: i am creating `$btn-settings` as below and using it on `_default.scss`.

What do you mean by "using it on `_default.scss`"? Why not just directly access variables using e.g. `settings.$btn-radius`?

**Comment by mbellary-chwy** [comment]
Got it. Thanks. Closing this
