### ISSUE TITLE
Nesting in Sass properties: could you update it?

### ISSUE THREAD

**Issue by MustafaWael** [sass/sass#2758]
**### scss:**
`.info-page {
  margin: auto {
    bottom: 10px;
    top: 2px;
  }
}`

_____________________________________________________________

**### CSS:**
`.info-page {
  margin: auto;
  margin-bottom: 10px;
  margin-top: 2px;
}`

_____________________________________________________________

### **but you can output this as a shorthand code like:**
`.info-page {
  margin: 2px auto 10px;
}`

**Comment by nex3** [comment]
Sass intentionally avoids baking in knowledge of the specifics of how each CSS property works. This makes it much easier for the language to stay up-to-date with the CSS spec and for CSS authors to ensure that they get exactly the output they expect. If you want to generate the smallest possible CSS output, I recommend a post-processing minifier like [cssnano](https://github.com/cssnano/cssnano).

**Comment by MustafaWael** [comment]
@nex3 Thanks for the explanation and your help about recommendation :heart:
