### ISSUE TITLE
Make possible to group the selectors

### ISSUE THREAD

**Issue by ghost** [sass/sass#2760]
It will be a good feature to group parent selector. 

**Use case:**

I have this code:

```
.sibling-class {
    .some-class1 {...}
    .some-class2 {...}
    .some-class3 {...}
    ....
    .some-class1000 {...}
}
```
And I need:

```
.sibling-class {
    &.some-class1 {...}
    &.some-class2 {...}
    &.some-class3 {...}
    ....
    &.some-class1000 {...}
}
```
How can I do it without putting `&` one thousand times if every class is unique?

Question on [stackoverflow](https://stackoverflow.com/questions/58485158/sass-group-parent-selector)

**Comment by nex3** [comment]
I don't think we're going to make this syntax any terser than one character per selector.
