### ISSUE TITLE
Automatice locating of `_index.scss` file is not working for devDependencies

### ISSUE THREAD

**Issue by mbellary-chwy** [sass/sass#2761]
I am able to automatically locate the `_index.scss` file in the same repository.
On trying to automatically locate an `_index.scss` file of `devDependencies`, it throws me an error of:

```
Can't find stylesheet to import.
```

For example, my styles folder has `_index.scss` file, which is not able to locate automatically:

```
@use '~@<dependency-name>/src/styles' as *;
```

Can someone please help me on this

**Comment by nex3** [comment]
Imports beginning with `~` go through Webpack's custom importer. Please file an issue against that.
