### ISSUE TITLE
Syntax to import font urls in sass modules

### ISSUE THREAD

**Issue by mbellary-chwy** [sass/sass#2762]
Before using Sass modules, i was importing font urls like:

```
@import 'https://fonts.googleapis.com/css?family=Roboto+Mono:400|Roboto:300,300i,400,400i,500,500i,700,700i';
```

Could someone please help me in finding new syntax to load a font url in new sass modules. It doesn't seem to work with @use

**Comment by mirisuzanne** [comment]
In that case, the browser handles the font import – and Sass isn't doing anything. That form of `@import` is native to CSS, and is not affected by the module syntax. `@use` is only required when importing other Sass modules. 

No changes needed - keep using `@import` the same way you have.
