### ISSUE TITLE
Can't get variables form modules imported with @forward and @use

### ISSUE THREAD

**Issue by MustafaWael** [sass/sass#2764]
# Get Variables: @forward without prefix.
> ### **./src/_header.scss**
`$wheat: wheat;`
____________________________________________________

> ### **./src/_index.scss**
`@forward 'header';`
____________________________________________________

> ### **style.scss**
`@use 'src' as b;
header {
  background: b.$wheat;
}`
___________________________________________________

> ### **style.css**
`header {
  background: wheat;
}`

# Get Variables: @forward with prefix.
> ### **./src/_header.scss**
`$wheat: wheat;`
____________________________________________________

> ### **./src/_index.scss**
`@forward 'header' as a-*;`
____________________________________________________

> ### **style.scss**
`@use 'src' as b;
header {
  background: b.a-$wheat;
}`
___________________________________________________

> ### **style.css**
/* Error: expected "(".
 *   ,
 * 4 |   background: b.a-$wheat;
 *   |                   ^
 *   '
 *   style.scss 4:19  root stylesheet */

############################################################################

# But works with mixins without prefix and with prefix

**Comment by mirisuzanne** [comment]
Forwarding prefixes are applied after the `$` - so you want `b.$a-wheat` in the example above. See [the documentation for forwarding prefixes](https://sass-lang.com/documentation/at-rules/forward#adding-a-prefix).

**Comment by MustafaWael** [comment]
Thank you for your attention to this matter, thanks a lot :heart: :heartbeat:
