### ISSUE TITLE
Allow rules to be renamed or removed

### ISSUE THREAD

**Issue by estani** [sass/sass#2766]
draft Proposal to allow rules to be removed, renamed, or just marked as "not exportable" whichever is simpler (if possible at all)

## background
Sass is a magnificent tool for writing adapters to ease migrations of css framework versions. 
Creating aliases is possible thanks to `@extend` but renaming/removing previous rules is it not.

## summary
For Bootstrap v3 -> v4 all `col-xs-*` where renamed to `col-*` to allow a V3 app use the V4 version the following rule can be used:
```scss
@for $i from 1 through 12 {
  .col-xs-#{$i} {
    @extend .col-#{$i}
  }
}
```
Now `col-md-*` in V3 behave like `col-lg-*` in V4 since "every tier has been bumped up one level". The proposed function to solve this might work as follows:
```scss
@for $i from 1 through 12 {
  @rename col-lg-#{$i} v4-col-lg-#{$i} //renaming col-lg-#{$i} into v4-col-lg-#{$i}
  @rename col-xl-#{$i} v4-col-xl-#{$i}
  .col-md-#{$i} {
    @extend .v4-col-lg-#{$i}
  }
  .col-lg-#{$i} {
    @extend .v4-col-xl-#{$i}
  }
}
```
Renaming or deleting be used interchangeably since renaming a rule would indeed set it obsolete, although it will clutter the resulting css.

## Syntax

The syntax is simple and would suffice for the first iteration.

<x><pre>
RenameExpression ::= '@rename' ExistingCssRule NonExistingCssRule
</pre></x>

The `ExistingCssRule` must exist previous to the call, and similarly `NonExistingCssRule` is not allowed to exist.

Is this even possible in the current data structures of sass?

**Comment by nex3** [comment]
As a general principle, in Sass language design we try to avoid features that are mostly focused on using upstream stylesheets in a way their author didn't intend them to be used. Those patterns tend to produce brittle dependencies that are likely to break when the upstream stylesheets change in unexpected ways. It's almost always better to use GitHub to submit upstream changes or to use PostCSS to process your compiled stylesheets to produce the sort of output you want.

**Comment by estani** [comment]
ok, makes sense although I find is a pitty, since Sass power makes it great to be used for this purpose. But coherence is much more appreciated, thanks.
