### ISSUE TITLE
Reference a module's member within @use of said module

### ISSUE THREAD

**Issue by illepic** [sass/sass#2771]
Variable definitions often refer to other variables within the same file/module. For example, in Bootstrap 4:

```scss
// ~bootstrap/scss/_variables.scss

$spacer: 1rem !default;
$spacers: () !default;
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * .25),
    2: ($spacer * .5),
    3: $spacer,
    4: ($spacer * 1.5),
    5: ($spacer * 3)
  ),
  $spacers
);
```

In this case, say we want to modify both the `$spacer` and `$spacers` values within a single implementation:

```scss
// ./my-project/_libraries.scss

@use '~bootstrap/scss/bootstrap' with (
  $spacer: 1.5rem,
  $spacers: (
    6: ($spacer * 4), // Is there a way to reference this member $spacer?
  ),
);
@forward '~bootstrap/scss/bootstrap';
```

In the example above, we need to both override `$spacer`, then reference the overridden value immediately. Does there exist syntax within the new modules system that lets us do this (such as something like `$this.$spacer`)?

**Comment by nex3** [comment]
This is why you're allowed to write variables before `@use` rules, so you can write this like:

```scss
$spacer: 1.5rem;
@use '~bootstrap/scss/bootstrap' with (
  $spacer: $spacer,
  $spacers: (
    6: ($spacer * 4),
  ),
);
@forward '~bootstrap/scss/bootstrap';
```

**Comment by illepic** [comment]
Thank you so much! Apologies for one last clarification (thank you for bearing with me here).

The simpler, but more awkward case is when we **don't** want to modify `$spacer`, but must reference it to augment an existing `map-merge`. Given the existing Bootstrap variables again like so:

```scss
// ~bootstrap/scss/_variables.scss

$spacer: 1rem !default;
$spacers: () !default;
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * .25),
    2: ($spacer * .5),
    3: $spacer,
    4: ($spacer * 1.5),
    5: ($spacer * 3)
  ),
  $spacers
);
```

If we just want to add another `$spacers` entry, we must reference `$spacer`.  But we aren't modifying `$spacer`:

```scss
// ./my-project/_libraries.scss

@use '~bootstrap/scss/bootstrap' with (
  $spacers: (
    6: ($spacer * 4), // Is there a way to reference this member $spacer?
  ),
);
@forward '~bootstrap/scss/bootstrap';
```
This is that scenario where don't necessarily want to redeclare `$spacer`, but need to at least refer to it. Of course we can use your suggestion of redeclaring it first (with its original value), but I wanted to verify there is no syntax for referring to the imported module at the time of `@use`ing it (like `$this.$spacer`, or something similar).

Thank you again so much!

**Comment by nex3** [comment]
I'm sorry, there's no way to do that. As far as Sass is concerned, the `$spacer` variable from within the `bootstrap` library doesn't exist until you've started evaluating `bootstrap`.

There is one exception: you can update the `$spacers` map *after* you've loaded the module. This won't affect any side-effects (including generated CSS) that referred to `$spacers` while the module was loading, but it will affect mixins or functions you invoke afterwards:

```scss
@use '~bootstrap/scss/bootstrap';
@forward '~bootstrap/scss/bootstrap';

bootstrap.$spacers: map-merge(bootstrap.$spacers, (6: $spacer * 4));
```

**Comment by illepic** [comment]
Thank you!
