### ISSUE TITLE
Support <general-enclosed> in @supports

### ISSUE THREAD

**Issue by tomhodgins** [sass/sass#2780]
*Added by @nex3*

- [x] [Proposal](https://github.com/sass/sass/pull/2825)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1592)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/894)
- [ ] [LibSass](https://github.com/sass/libsass/issues/3042)

---

Hi @nex3 and friends! I've noticed that there are a few gaps between CSS's specified syntax and what dart-sass will parse, one area in particular is parsing `@supports` conditions. The following examples should all be valid in CSS syntax but each generate parsing errors in dart-sass:

```css
@supports (a b) {}
@supports c(d) {}
@supports (e(f)) {}
```

The syntax for `@supports` conditions in CSS is defined here: https://drafts.csswg.org/css-conditional-3/#typedef-supports-condition

```perl
<supports-condition> = not <supports-in-parens>
                     | <supports-in-parens> [ and <supports-in-parens> ]*
                     | <supports-in-parens> [ or <supports-in-parens> ]*
<supports-in-parens> = ( <supports-condition> ) | <supports-feature> | <general-enclosed>
<supports-feature> = <supports-decl>
<supports-decl> = ( <declaration> )
```

One thing that seems missing is that the CSS syntax allows [`<general-enclosed>`](https://drafts.csswg.org/mediaqueries-4/#typedef-general-enclosed) productions, which are very open-ended in what they can contain.

```perl
<general-enclosed> = [ <function-token> <any-value> ) ] | ( <ident> <any-value> )
```

It looks like [this might be the section](https://github.com/sass/dart-sass/blob/master/lib/src/parse/stylesheet.dart#L3269-L3356) of the dart-sass parser where these conditions are read, but I'm not sure right now how to fix this or improve the code that's there.

When tokenized as CSS, `@supports c(d) {}` should look like this:

```json
{
  "type": "AT-RULE",
  "value": {
    "type": "BLOCK",
    "value": [],
    "name": "{"
  },
  "name": "supports",
  "prelude": [
    {
      "token": "WHITESPACE"
    },
    {
      "type": "FUNCTION",
      "value": [
        {
          "token": "IDENT",
          "value": "d"
        }
      ],
      "name": "c"
    },
    {
      "token": "WHITESPACE"
    }
  ]
}
```

You can use [this tool](https://tomhodgins.com/demo/cssom/) to check what different browsers will parse out of a string of CSS input. Or run this code to parse and re-stringify a string of CSS in any browser to see the same kind of result:

```js
import('https://unpkg.com/cssomtools').then(({parse, stringify}) =>
  console.log(
    stringify(
      parse`
         @supports c(d) {}
      `
    )
  )
)
```

It looks like Safari struggles with `@supports` conditions that aren't inside `()` parens, but Chrome and Firefox both seem to follow the spec a little more closely:

**Safari**

<img width="616" alt="safari-mostly-works" src="https://user-images.githubusercontent.com/955601/69577417-47ac2400-0f9c-11ea-9939-ddc14e172bdc.png">

**Firefox**

<img width="447" alt="firerox-all-work" src="https://user-images.githubusercontent.com/955601/69577428-4c70d800-0f9c-11ea-9a57-3bea29721f7b.png">

It would be great if dart-sass could parse CSS more accurately in this area, please let me know if there's any way I can be of further help in identifying or testing this.

Thanks <3

**Comment by nex3** [comment]
We have a policy of not adding support for a new spec in Sass until at least one browser supports it in the wild. It sounds like you've verified that Chrome and Safari can *tokenize* unparenthesized `@supports` queries, but do such queries actually have a semantic effect on those browsers yet?

**Comment by tomhodgins** [comment]
> We have a policy of not adding support for a new spec in Sass until at least one browser supports it in the wild.

The `@supports` at-rule already enjoys [widespread browser support](https://caniuse.com/#feat=mdn-css_at-rules_supports) and is relied on by CSS authors for helping with progressive enhancement on [30% of websites](https://almanac.httparchive.org/en/2019/css#supports-and-import) as of 2019.

> It sounds like you've verified that Chrome and Safari can tokenize unparenthesized @supports queries

All of the examples I gave are valid CSS, and there are plenty more valid examples that won't parse in dart-sass. This issue is that the parsing of the `@supports` condition doesn't seem to follow the specified grammar in CSS.

> do such queries actually have a semantic effect on those browsers yet?

Using `@supports` rules with custom values is a technique used for encoding style information in CSS syntax for use with any kind of CSS-aware tool, and browsers will parse and retain them in CSSOM even if they don't have built-in support for the feature. You can put a lot of stuff in a `<general-enclosed>` production, so this makes it a valuable way to store custom instructions for handling of the CSS held inside even if you're bringing your own support! You can look through the rules in a stylesheet, find these `@supports` rules with custom style information, and make decisions about what to do to support it. And it's not just useful in browsers, this is a technique that's useful for preprocessing CSS as well.

Here's an example, let's say you want to style a `<textarea>` and also write an element query for styling applying a different style when it's taller than a certain height. Even though this feature will require a JS runtime in the browser to be supported, all our style information can be expressed inside our CSS stylesheet:

```css
textarea {
  border: 2px solid red;
}
@supports (--element("textarea", {"minHeight": 150})) {
  [--self] {
    border-color: lime;
  }
}
```

Here we have a regular CSS rule for `<textarea>` elements, and below that an `@supports` rule that could be supported by (any number of…) element query plugin running in the browser. It's expressed here using the general enclosed production and a custom function name starting with `--` so it will never accidentally collide with the name of any future feature.

You could parse this sort of thing server-side and output the plain CSS minus these custom rules and also output all the required JavaScript needed to support the other styles, or since browsers will keep these around in CSSOM you can also being your own support client-side. Here's a demo of supporting the styles inside an `@supports` at-rule that runs client-side:

```html
<style>
  textarea {
    border: 2px solid red;
  }
  @supports (--element("textarea", {"minHeight": 150})) {
    [--self] {
      border-color: lime;
    }
  }
</style>

<script type=module>
  import deqaf from 'https://unpkg.com/deqaf'
  import element from 'https://unpkg.com/jsincss-element-query/index.vanilla.js'

  deqaf({stylesheet: {element}})
</script>

<textarea>Make me taller than 150px</textarea>
```

Hopefully that helps explain some of why `@supports` is so useful for developers. It's the built-in way for CSS authors to declare progressive enhancement that provides the best experience to their users, conditionally based on what features can be supported.

I think it would be a big benefit to everybody using Sass to be able to use `@supports` and work with stylesheets that make use of it :D Thanks

**Comment by nex3** [comment]
> > We have a policy of not adding support for a new spec in Sass until at least one browser supports it in the wild.
> 
> The `@supports` at-rule already enjoys [widespread browser support](https://caniuse.com/#feat=mdn-css_at-rules_supports) and is relied on by CSS authors for helping with progressive enhancement on [30% of websites](https://almanac.httparchive.org/en/2019/css#supports-and-import) as of 2019.
> 
> > It sounds like you've verified that Chrome and Safari can tokenize unparenthesized @supports queries
> 
> All of the examples I gave are valid CSS, and there are plenty more valid examples that won't parse in dart-sass. This issue is that the parsing of the `@supports` condition doesn't seem to follow the specified grammar in CSS.

What is and is not "valid CSS" is not as cut-and-dried as you're making it out to be. CSS is a constantly-evolving language composed of many different specs that each have multiple different levels, each of which *also* changes over time, sometimes in backwards-incompatible ways. On top of that, each browser supports each of these levels differently at different points in time.

We've run into issues in Sass before where we implemented a new spec before any browsers supported it, and the spec ended up making an incompatible change. This caused us and our users a lot of pain as we had to back out the features we added and that people were already using in Sass. So we have a strong policy now of only adding support for CSS specs that are implemented in at least one browser.

In the case of `@supports`, Sass added support for the [CSS Conditional Rules 3](https://www.w3.org/TR/2013/CR-css3-conditional-20130404/#at-supports) candidate recommendation version. We did not include support for the `general_enclosed` rule because the spec specifically says:

> style sheets **must not** write ‘`@supports`’ rules that match this grammar production. (In other words, this production exists only for future extensibility, and is not part of the description of a valid style sheet in this level of the specification.)

A similar note appears in [the current editor's draft](https://drafts.csswg.org/css-conditional-3/#at-supports):

> Authors must not use `<general-enclosed>` in their stylesheets. It exists only for future-compatibility, so that new syntax additions do not invalidate too much of a `<supports-condition>` in older user agents.

So, according to a strict reading of Conditional Rules 3, your `--elements` function is *not* valid CSS.

---

*All that said*, the current draft of [Conditional Rules 4](https://drafts.csswg.org/css-conditional-4/#at-supports-ext) expands the `@supports` rule to include a `selector()` function, which [Firefox appears to support](https://caniuse.com/#search=supports%20selector). Sass policy also says to decouple the Sass language from the details of CSS where possible, so the best way to support this function without tightly coupling ourselves to exactly which function names CSS supports is probably to support `general_enclosed` in its entirety. So I'm marking this as planned.

**Comment by tomhodgins** [comment]
> What is and is not "valid CSS" is not as cut-and-dried as you're making it out to be.
> according to a strict reading of Conditional Rules 3, your --elements function is not valid CSS.

These two forms (the parenthesized version and non-parenthesized function variations) are what the CSS Working Group has given for the purpose explained above:

```css
@supports --my-custom-function-name() {}

@supports (--my-custom-function-name()) {}
```

If you have questions about what's valid in CSS it might be worth asking the CSSWG directly—I've been able to get answers about questions like this in the #css channel on the W3C IRC server.

**Comment by nex3** [comment]
Be that as it may, the text of the spec explicitly indicates that it's forbidden. If it's important to you that the spec allow this for client-side sniffing purposes, I suggest petitioning the working group to change that spec text—it sounds like they're likely to be open to it.

**Comment by tomhodgins** [comment]
From the #css channel on the W3C IRC, August 8 2018:

<img width="310" alt="question" src="https://user-images.githubusercontent.com/955601/69685060-0fceda80-1089-11ea-95bd-ae4400d3102e.png">

<img width="309" alt="answer" src="https://user-images.githubusercontent.com/955601/69685064-12313480-1089-11ea-9731-3f419ef48790.png">

<img width="308" alt="update" src="https://user-images.githubusercontent.com/955601/69685071-13faf800-1089-11ea-8e1a-385b46fa4be0.png">

> **innovati:** Does this `@supports` rule look like it will be valid when `@supports` gets updated from css2 grammar? https://github.com/tomhodgins/qaffeine-demo/blob/28a80c3dac558df865764d83e9c6db670894b4d0/src/stylesheet.css#L109&L115

```css
/* Min-width */
@supports (--js-element('.minwidth', {minWidth: 300})) {
  [--self] {
    background: greenyellow;
    border-color: limegreen;
  }
}
```

> **TabAtkins:** Yes.

> **innovati:** oh wonderful! Thank you
> Is this flexibility built into CSS intended for browser makers to use, or developers like me (or both?)

> **TabAtkins:** Intended for browsers, so we can add new types of support conditions that'll report as false in old browsers (rather than being invalid and throwing out the whole rule).
> But as long as you stay in `--` space, you'll be sure to avoid any browser additions.

If you look through the [commit changes](https://github.com/w3c/csswg-drafts/commit/206498e6bd16ad8dc00967a26607c72bdcd12dfa) from that day you can see the comment you referred to earlier was added after Tab had suggested this syntax be used for this purpose, and the wording and syntax definitions were updated in the draft version of the spec to clarify the syntax according to the [CSS Syntax Module](https://www.w3.org/TR/css-syntax-3/).

If you have questions about the spec, Tab is the perfect person to ask about this (or any CSS syntax-related question!) I think the two of you might even work for the same company ;)

**Comment by nex3** [comment]
I'm not making any claims about authorial intent, just the text of the specification, which is unambiguous. Regardless, this is all irrelevant to Sass since we plan on adding support for `<general-enclosed>` whether or not your use case is valid CSS, so I would like to stop discussing it.

**Comment by tomhodgins** [comment]
Thanks, that will be a wonderful day! <3

**Comment by nex3** [comment]
The proposal is out. I'll leave it open for comment for two weeks before we mark it accepted.

**Comment by nex3** [comment]
Marking this as accepted now.

**Comment by tomhodgins** [comment]
Thanks @nex3!

**Comment by nex3** [comment]
Closing this out since LibSass is deprecated.
