### ISSUE TITLE
Variables in @import

### ISSUE THREAD

**Issue by Snugug** [sass/sass#279]
Currently when using @import, you need to hardcode in uri. I'd like the ability to pass in a variable/function call to get the uri and use that for the @import call, something like the following:

```
@function drupal-theme($project, $append: '') {
  @return /sites/all/themes/#{$project}/#{$append};
}
…
@import #{drupal-theme('my-theme', 'sass/style)};
```

Which would be the same as:

```
@import '/sites/all/themes/my-theme/sass/style';
```

This would also make it easier for a master import for sub-partials a la Compass framework stuff:

```
$compass-css3: 'border-radius' 'inline-block' 'opacity' 'box-shadow' 'text-shadow'…;
@each $css3 in $compass-css3 {
  @import 'css3/#{$css3};
}
```

**Comment by nex3** [comment]
Allowing dynamic imports would completely break Sass's ability to quickly determine which files import which other files, and thus what needs re-compiling when.

**Comment by julkue** [comment]
This is not unnecessary because the output file of the compiled .css file could be everywhere. I think a dynamic import would be great!

**Comment by jslegers** [comment]
I agree with @Snugug. IMO, dynamic imports are essential for flexible theming.

I'm thinking especially of the following feature :

![File structure](http://i59.tinypic.com/5nodph.png)

``` scss
$basetheme : 'default';
$subtheme : 'blueoyster';

//----------------------------------------------------
// DO A LOT OF OTHER STUFF HERE
//----------------------------------------------------

@import 'themes/' + $basetheme + '/__styles';
@import 'themes/' + $subtheme + '/__styles';
```

Another obvious use case would be polyfilling (https://github.com/sass/sass/issues/739).

**Comment by johanroug** [comment]
agree.. just tried, but then I stumpled on this post

**Comment by nod** [comment]
From a deployment standpoint, being able to dynamically set different import paths during compile is pretty huge.

**Comment by uxtx** [comment]
+1

**Comment by spoeken** [comment]
+1

**Comment by joaomilho** [comment]
:+1:

**Comment by jlukic** [comment]
Currently this missing feature is blocking the SCSS port of Semantic UI

In LESS we use this simple [theme bootstrapper](https://github.com/Semantic-Org/Semantic-UI/blob/next/src/theme.less) to process theme inheritance, but it requires the ability to use variables inside `import` statements.

**Comment by smichaelsen** [comment]
+1

**Comment by mdix** [comment]
+1

**Comment by niklas-r** [comment]
This would be great to have. My use case right now looks like this:

``` scss
@import '#{$bowerPath}/normalize.scss/_normalize.scss';
```

Which of course doesn't work :(

**Comment by davidkpiano** [comment]
@niklas-r change that to `/normalize.css` and it'll work ;-)

**Comment by niklas-r** [comment]
@davidkpiano I tried that at first but it doesn't work as you might think.

First of all, the variable interpolation still doesn't work even though you try to `@import` a CSS-file.

Secondly, when you `@import` a CSS-file, Sass will output an `@import`-statement in the compiled CSS. You can read more about it here: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

This behavior is supposedly a feature but I much prefer the way Less handles it. By directly importing the CSS-file in the compiled CSS. But that's a matter for another ticket.

**Comment by lolmaus** [comment]
@niklas-r, if you're trying to import an `.scss` file from Bower, you should store `bower_components` outside of your Sass subfolder and add path to `bower_components` to Sass `import_path`.

Then you can simply do `@import 'normalize.scss/_normalize.scss';`.

**Comment by niklas-r** [comment]
@lolmaus thank you, didn't think of that!

**Comment by thom-nic** [comment]
FWIW, in my case I'm using bootstrap via bower and the path to imports is very long:

``` sass
//custom _boostrap.sass to override included components:

@import bootstrap-sass-official/assets/stylesheets/bootstrap-sprockets

// Core variables and mixins
@import bootstrap-sass-official/assets/stylesheets/bootstrap/variables
@import bootstrap-sass-official/assets/stylesheets/bootstrap/mixins

// Reset and dependencies
@import bootstrap-sass-official/assets/stylesheets/bootstrap/normalize
@import bootstrap-sass-official/assets/stylesheets/bootstrap/print
//@import bootstrap-sass-official/assets/stylesheets/bootstrap/glyphicons

// Core CSS
@import bootstrap-sass-official/assets/stylesheets/bootstrap/scaffolding
@import bootstrap-sass-official/assets/stylesheets/bootstrap/type
// ... etc
```

So it would be nice if I could have a `$bs-root: bootstrap-sass-official/assets/stylesheets/bootstrap/` at the top of the page and not have to repeat it for every import.

**Comment by lolmaus** [comment]
@thom-nic, have `bower_components/bootstrap-sass-official/assets/stylesheets` in Sass load path, then you can do `@import bootstrap-sprockets`.

**Comment by thom-nic** [comment]
Ah, ok thanks @lolmaus!

**Comment by Jakobud** [comment]
A really good use case for this is when you have a system that uses theming that overrides base classes. For example:

```
$theme = "mytheme";

@import "#{$theme}/variables";
@import "#{$theme}/grid";
@import "#{$theme}/type";
@import "#{$theme}/layout";
etc
```

You could optionally change `$theme` at any time to point to another theme without having to change dozens of `@import` directives.

An excellent example of a theming system like this is http://semantic-ui.com. Unfortunately the author had to use LESS to accomplish his framework with multiple optional themes since SASS doesn't support this.

**Comment by paustria** [comment]
Agree with @Jakobud 

+1 to add variable to @import functionallity

**Comment by asadpakistani** [comment]
+1

@include #{$variable} . Does not work also +23232322 for this one as well please.

**Comment by josephdburdick** [comment]
+1 this would be fawesome

**Comment by opyate** [comment]
> Allowing dynamic imports would completely break Sass's ability to quickly determine which files import which other files, and thus what needs re-compiling when.

Sure, I'm happy to search/replace when I want to change a theme.

**Comment by jslegers** [comment]
> Allowing dynamic imports would completely break Sass's ability to quickly determine which files import > which other files, and thus what needs re-compiling when.

I'd be happy to see compilation time quadrupled if that's the trade-off for adding variable support to "import" functionality.

IMO, it's one of the most essential language features still lacking in SCSS.

**Comment by cimmanon** [comment]
If your reason for needing variables for imports is because "I need to change my theme without having to modify all of my import declarations", why aren't you using the `-I` option (`--load-path`)?

``` scss
@import "colors";

.foo {
    background: $secondary;
    color: $primary;
}

h1 {
    border: 1px solid $primary;
}
```

Hotdog:

```
$ sass --watch sass:css -I "sass/themes/hotdog"
```

Output:

``` css
.foo {
  background: yellow;
  color: red; }

h1 {
  border: 1px solid red; }
```

Greyscale:

```
$ sass --watch sass:css -I "sass/themes/greyscale"
```

Output:

``` css
.foo {
  background: #CCC;
  color: #333; }

h1 {
  border: 1px solid #333; }
```

**Comment by opyate** [comment]
@cimmanon thanks for the tip. I'm a mostly -backend developer with these things hidden behind wrappers like https://github.com/Kronuz/pyScss

**Comment by joaoreynolds** [comment]
+1

**Comment by Jakobud** [comment]
@cimmanon 

> why aren't you using the -I option (--load-path)?

Why are you still using command line SASS?

**Comment by cimmanon** [comment]
@Jakobud What I use is none of your concern (I happen to use Compass rather than vanilla Sass, and I don't have a use for variables in imports anyway).  If you're using a build tool that does not grant you access to the `-I` option, that seems to be a problem with your build tool.

**Comment by davelab** [comment]
+1

**Comment by ParHaggstrom** [comment]
+1

**Comment by antenando** [comment]
+1 ...

**Comment by kerihenare** [comment]
+1

(I'm not usually a "+1" kind of guy, but this would be really helpful)

**Comment by daveschwerstein** [comment]
Our use is for a platform arrangement which would allow different sites on the platform to switch the version of a feature locally.

**Example:**
- Shared Theme Layer:
  - @import "variables"; // Shared variables _$slider-version: 'slider-a' !default;_
  - @import "sliders/#{$slider-version}-base";
- Local Theme:
  - @import "variables"; // local variables file _$slider-version: 'slider-b';_
  - @import "../shared-theme-layer/base";

Our purpose for this is that on creation of a new feature, say blogs, the import link would be added to the shared theme layer base import file and rolled out instead of developers having to go to each of the individual sites and adding that file to the local theme base import file.

**Comment by MikeMitterer** [comment]
+1 - please!!!!

**Comment by jaketodaro** [comment]
+1

**Comment by talbs** [comment]
+1 this would help immensely with package and third party lib paths!

**Comment by jessedvrs** [comment]
+1 - Not for dynamic variables, but for constants. Specific alternative for people using a build system like Gulp: you could use a template system (like Swig) to replace the variables before it reaches the Sass compiler.

**Comment by marcobarbosa** [comment]
+1 come on :)

**Comment by starise** [comment]
:+1: it would be nice

**Comment by TiBianMod** [comment]
+1 please, nice future.

**Comment by theofidry** [comment]
+1

**Comment by mentos1386** [comment]
+1 this would be very useful

**Comment by topisani** [comment]
+1

**Comment by phinz** [comment]
+1

**Comment by kevin-smets** [comment]
+1

**Comment by hurgleburgler** [comment]
+1

**Comment by thomaslund** [comment]
+1

**Comment by henke443** [comment]
+1

**Comment by nahuelsotelo** [comment]
+1

**Comment by mikeifomin** [comment]
+1

**Comment by tommiepommieporretje** [comment]
+1

**Comment by felgeekpe** [comment]
+1

**Comment by nielsdendekker** [comment]
+1

**Comment by yoannisj** [comment]
Another way to deal with this, which I also suggested for [node-sass-import-once](https://github.com/at-import/node-sass-import-once/issues/15) is to add a `:load_aliases` option for the sass-compiler. 

This would be similar to how the [`:load_paths` option](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#load_paths-option) works, but more flexible as it would take an object where the keys can be used in `@import` to point to a specific load path. This extra flexibility covers a lot of different use cases:
- import stylesheets directly from bower-components (see note below)
- allow for a more complex directory structure, where stylesheets are not all in the same folder
- swap source directories based on a config file (e.g. for theming)

**options**

``` ruby
load_aliases:
   vendorcomp: './bower_components/vendor-component/path/to/stylesheets/sass/'
   foo: './src/path/to/bundles/foo-bundle/stylesheets/',
   theme:  './src/path/to/themes/blue-orchid/stylesheets/'
```

**sass file**

``` scss
@import "vendorcomp/pagination";
@import "foo/modules/navbar";
@import "theme/colors";
```

**note**: Working with bower_components is already possible with the `:load_paths` option if the component stores its stylesheets directly in a directory having the same name. For example [bootstrap-sass](https://github.com/twbs/bootstrap-sass) which stores sass files in _bootstrap-sass/assets/stylesheets/bootrstrap_ which allows us to do `@import bootstrap/dropdown` provided we add the load_path `./bower_components/bootstrap-sass/assets/stylesheets`. But aliases would make it more flexible and also work with bower component' which don't.

**Comment by esr360** [comment]
Just look how many people in recent days are requesting this! A true testament to how popular Sass has become in the 3 years that this issue was opened. This is a completely legitimate feature, I honestly thought my syntax was wrong when this wasn't working for me.

+1

**Comment by shanecav** [comment]
+1

**Comment by yoannisj** [comment]
I have moved aliasing suggestion to [issue #1094 ] which compiles wishes and suggestions for future  `@import` behaviour.

**Comment by trendfischer** [comment]
+1

**Comment by stvnspchr** [comment]
+1

**Comment by praveenaj** [comment]
+1

**Comment by JuhG** [comment]
+1

**Comment by kallisti5** [comment]
+1

**Comment by katzgrau** [comment]
+1

**Comment by brajt** [comment]
+1

**Comment by extonec** [comment]
+1

**Comment by mishanon** [comment]
+1

**Comment by dlimars** [comment]
+1

**Comment by gluecksmensch** [comment]
+1

**Comment by sgraham785** [comment]
+1

**Comment by mreis1** [comment]
+1

**Comment by Daggett** [comment]
+1

**Comment by dww510** [comment]
+1

**Comment by ashraffayad** [comment]
+1

**Comment by dajnz** [comment]
+1

**Comment by aliaksandrb** [comment]
+1

**Comment by AddoSolutions** [comment]
+1

**Comment by willdavidow** [comment]
+1

**Comment by lukedanielson** [comment]
+1

**Comment by pajtai** [comment]
+1 - currently using templating to create sass files

**Comment by msdn11** [comment]
+1

**Comment by dangelion** [comment]
+1!!!

**Comment by cwebb123** [comment]
+10

**Comment by Idyllei** [comment]
+1 Though CSS is (supposedly) "static," having an option of dynamic compilation of Sass could turn out to be quite useful.

**Comment by afischer** [comment]
+1

**Comment by iWader** [comment]
+1 because nearly 4 years on we still don't have this feature.

**Comment by gwashbrook** [comment]
+1

**Comment by mrhorrocks** [comment]
+1

**Comment by GesJeremie** [comment]
+1

**Comment by sabriskay** [comment]
hi!
I have an error in _setting.scss "File to import not found."

`@import "foundation/functions";`

Anybody know about that? Thanks!

**Comment by GesJeremie** [comment]
@sabriskay I guess your path isn't correct.

**Comment by bbashy** [comment]
How isn't this a thing yet...

"sass is awesome!!! Let's do a variable for this path! :)... oh wait what... syntax? Google. Nope, not a feature.".

**Comment by jslegers** [comment]
@bbashy :+1:

**Comment by sabriskay** [comment]
Thanks, I will do ;)

**Comment by chriseppstein** [comment]
This feature will be provided by #739 if we ever implement that.
