### ISSUE TITLE
[Math Functions] Mark built-in module variables as unmodifiable

### ISSUE THREAD

**Issue by nex3** [sass/sass#2799]
The [math function proposal](https://github.com/sass/sass/blob/master/proposal/more-math-functions.md) adds two variables to the built-in `sass:math` module, which are actually the first variables ever exposed by a built-in module (cool!). We probably don't want users setting `$e` and `$pi` to different values, though, so they should be unmodifiable.

Rather than special-casing those two variables in particular, I think the proposal should update the variable-assignment logic to fail if the variable comes from *any* built-in module, effectively making all built-in modules' variables unmodifiable.

**Comment by Awjin** [comment]
Agreed. I added a section in Draft 2 to address this: https://github.com/sass/sass/commit/4b551c143b1cb7cc1e41c32f99c86d659d1964e2
