### ISSUE TITLE
Color compression and IE filters

### ISSUE THREAD

**Issue by alexdixon** [sass/sass#280]
It looks like if I uses sass variables in IE filters, the sass color compression breaks the filter.  I wrote up this gist to demonstrate:

https://gist.github.com/gists/1838545

You can see the "Color Values" section of the YUI docs for a bit more info:
http://developer.yahoo.com/yui/compressor/css.html

**Comment by nex3** [comment]
You can use the new ie-hex-str function added for #269 to get IE-compatible colors.

Sass is not context-aware in the way that would be necessary for it to know not to do compression within IE's filter syntax.

**Comment by alexdixon** [comment]
Perfect -- thanks!
