### ISSUE TITLE
@extend css tag from module (@use)

### ISSUE THREAD

**Issue by JGH153** [sass/sass#2806]
I'm currently upgrading a scss project from @import to the new module system with @use. Everything is going great except for the @extend at-rule. I'm unable to find anything in the documentation on how to tell sass that the tag being extended comes from another module.

This does not work:

```
@use "./colors.scss" as colors;

body {
  @extend .element; // not working
  @extend colors, .element; // not working
}
```

Example: https://stackblitz.com/edit/angular-tufq7f?file=src%2Fstyles.scss

Is this an intentional breaking change? Is the solution missing from the official docs? Any suggestions are appreciated.

**Comment by jathak** [comment]
This code works when run directly with the latest version of Dart Sass.

It looks like you're using a version of Sass that doesn't support the module system. Please make sure you're using Dart Sass 1.23.0 or later (libsass/Node Sass don't support the module system)

**Comment by JGH153** [comment]
I can't find an online sass playground supporting modules and multiple files, but here is a direct link to the repo with the issue, using "sass": "1.24.3"

https://github.com/hafslundnett/hdd-style/blob/sass-modules/components/tooltip.scss#L29

I’m getting the same type of error there as well:
```
The target selector was not found.
Use "@extend typographyU !optional" to avoid this error.
29 │     @extend typographyU, .is-p;`
```

Removing all @extend at-rules referencing classes from other files makes the project compile successfully with sass modules.

You can easily run the project locally with ```yarn``` and ```yarn start```

What am I missing? I can try to make a minimal reproduction of the issue if that helps.

**Comment by jathak** [comment]
Omit the `typographyU`. Selectors are not namespaced (only variables, functions, and mixins). It should just be `@extend .is-p`.

**Comment by JGH153** [comment]
That solves one problem, thanks for the help. Does this mean there is no way to say which module I want to extend from, using the module system?

**Comment by jathak** [comment]
No. Please see the [documentation on extension scope](https://sass-lang.com/documentation/at-rules/extend#extension-scope)
