### ISSUE TITLE
Issue with @extend, placeholder classes and interpolation.

### ISSUE THREAD

**Issue by filip-jk** [sass/sass#2807]
Hello there!

I'm having a little issue with SASS @extend, placeholder class, and interpolation. 

I'm trying to keep the HTML as clean as possible and that's I decided to go for the @extend function in pair with placeholder classes. However, I'm mainly extending layout-related classes like grid, list etc - that's why I'm mixing a placeholder with a regular class in the declaration, i.e:

```
%drawer,
.drawer {
 ...
}
```

Everything was going just fine except for a moment when I noticed the interpolation with the variable being the ampersand in the main class causes some issues. Sample code (with most of the CSS rules removed):

```
%drawer,
.drawer {
  $this: &;

  position: fixed;
  z-index: 10;

  &__content {
    right: 0;
    transform: translate(100%, 0);
  }

  &__optional-element {
    background: red;
  }

  &--left { // I want this modifier to be applied to the parent element as it may affect more than one children element
    #{$this}__content {
      left: 0;
      transform: translate(-100%, 0);
    }
  }
}
```

And the extension code:

```
.product-drawer {
  @extend %drawer;

  &__content {
    @extend %drawer__content;
  }
}
```

However, the compiled CSS output comes with a problematic bit:

```
.drawer--left .product-drawer,
.drawer--left .drawer__content {
  left: 0;
  transform: translate(-100%, 0);
}
```

You may notice the first line is redundant and actually wrong. In addition, the "&__optional-element" bit is not outputted for the "product-drawer" extension which makes it really strange. It happens only to rules with the $this interpolation.

As soon as I remove the regular ".drawer" class from the original declaration (and just leave %drawer there), the problem is gone but in these layout-related classes (%grid, %list), we want to keep the regular class name as well so in some various, simple cases it can be used without a need to write new CSS and extending the placeholder class (.grid, .list).

I know that this could be resolved by separating the placeholder class (%drawer) from the regular one (.drawer) completely and then extend the placeholder class inside the regular ".drawer" declaration but that would simply duplicate the code... Or maybe my approach is wrong by design? 

Thank you!

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
