### ISSUE TITLE
Uninstall JS Sass So I Can Go Back To Ruby Sass

### ISSUE THREAD

**Issue by pauljohnknight** [sass/sass#2817]
Hi,

I installed SASS on my Mac, but wish uninstall it so I can install the old Ruby version which I had on my previous Mac. There seems to be continuing issues where it effectively crashes / stops working out of the blue, which I never experienced on the Ruby version. 

I can't see anywhere in the Docs how to uninstall it?

I used `npm install -g sass` to install it on my current machine - but I don't know whether this is a Dart or JS version of SASS ?

Thanks in advance for any help.

Paul.

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

Speaking of things that need the core team's attention: if you can consistently reproduce a crash or any other behavioral problem, we'd love to work with you to get it fixed. Please feel free to open a separate issue about that.

**Comment by pauljohnknight** [comment]
Also I've found out what seems to be causing the issue with Dart / JS SASS version crashing. It happens when certain errors occur, particularly when you cut and paste code in that that may have a typo in when you have auto-save turned on (in VS Code). This seems to be the running issue with mine and i appreciate other people have had a problem with it stalling but people couldn't seem to work out why it was happening.

**Comment by nex3** [comment]
Since it sounds like you're able to reliably reproduce the crash, are you willing to do some work to help us debug it?

**Comment by pauljohnknight** [comment]
Yes sure. I've never done anything like that but happy to help.

**Comment by nex3** [comment]
Thanks! First steps:

* [Install Dart](https://dart.dev/get-dart).
* [Install Git](https://git-scm.com/downloads) if you haven't already.

Once you have these, run:

```shellsession
$ git clone git://github.com/sass/dart-sass
$ cd dart-sass
$ pub get
$ pub run grinder pkg-npm-dev
```

This will create a Sass npm package in the `build/npm` directory. Try running Sass directly from that using `node build/npm/sass.js`. If you can still reproduce the errors there, please include the text of the crash report and I'll see if I can figure out how to best debug it.

**Comment by pauljohnknight** [comment]
Hi Natalie

I don't know if I'm going to have time to do that - I don't really use git
/ github so would need to learn it. I've re-installed the Ruby version
which works like a dream.

If you wish to recreate the problem, from what I can gather from myself and
other users who experience it: we all use VS Code, with autosave turned on.
All the people I know who encounter the problem also use SASS partials.

After no more than about 20 changes to the .scss files it will stop
working. To speed up the crashing, you will need to make mistakes in your
code and then correct them. It doesn't happen on every mistake but by the
time you get to no more than 20 changes and make a mistake it will defo
stop working. All of the users I know who encounter this are also using a
Mac.

Paul.

**Comment by nex3** [comment]
I'll try that, but I'll warn you ahead of time that problems like this are notoriously flaky and difficult to reproduce on unrelated computers. There's probably no way we can continue to improve the underlying systems if we don't get some help from users like you to reproduce these issues.

Also, I strongly discourage you from continuing to use Ruby Sass. It is completely undeveloped at this point, which means that not only will it not get new Sass features, it won't ever be updated to support new CSS features, and if there are ever security bugs in it or any of its dependencies, they won't ever be fixed. In the long term, it'll be much better for you and all other users to make sure that Dart Sass is robust rather than using Ruby Sass because it works okay right now.

**Comment by pauljohnknight** [comment]
OK I appreciate what you're saying, but I just can't work with the Dart
version: it really affects productivity / work rates. Like other people who
are having this problem, the real killer is when you have some CSS that
isn't working that may be a specificity issue, or because the CSS is
incorrect (but doesn't throw an error), you have to reboot SASS each time
incase it is an instance where SASS has crashed, even in cases where it is
user error. On top of the actual crashing it makes the whole process very
unpleasant when you're on a deadline.

I only really use SASS for the partials (and use the built in compress CSS
file functionality), so for now it should be OK.

Paul

**Comment by pauljohnknight** [comment]
Oh, and one other thing, I do use `sass --watch scss:./ --style compressed` to
compress the outputted CSS, for when you are recreating the environment.

Paul

**Comment by nex3** [comment]
FYI, https://github.com/sass/dart-sass/pull/962 should have fixed the underlying issue with `--watch`.

**Comment by pauljohnknight** [comment]
Hi Natalie,

That does seemed to have solved the problem. A thousand thank yous for
getting to the bottom of it, it really is appreciated.

Kind regards,

Paul
