### ISSUE TITLE
hyphen issue - using in variables

### ISSUE THREAD

**Issue by udaypathak** [sass/sass#2822]
/* Error: expected ":".

,
1 | $primary - font:Roboto, sans - serif;
| ^
'
scss\style.scss 1:10 root stylesheet */
body::before {
font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
"Droid Sans Mono", monospace, monospace;
white-space: pre;
display: block;
padding: 1em;
margin-bottom: 1em;
border-bottom: 2px solid black;
content: 'Error: expected ":".\a \2577 \a 1 \2502 $primary - font:Roboto, sans - serif; \d\a \2502 ^\a \2575 \a scss\style.scss 1:10 root stylesheet';
}

why getting compile error in SASS when using hypen in variable $primary-font?

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
