### ISSUE TITLE
Import  once

### ISSUE THREAD

**Issue by BonBonSlick** [sass/sass#2824]
https://github.com/sass/sass/issues/156

Is there still no out of the box salvations?

**Comment by mirisuzanne** [comment]
This is a core feature of the module system, which was released in October:

https://sass-lang.com/blog/the-module-system-is-launched

> @use only executes a stylesheet and includes its CSS once, no matter how many times that stylesheet is used

**Comment by BonBonSlick** [comment]
thanks, missed that!
