### ISSUE TITLE
Allow @else to be compiled to CSS

### ISSUE THREAD

**Issue by nex3** [sass/sass#2826]
Currently, Sass considers an `@else` rule that's separate from an `@if` invalid. However, this is useful syntactic space for plain CSS as well. For example, the CSS team at Google is working on a PostCSS plugin that defines serve-time conditionals for which `@else` would be a useful construct. I've also heard informally that the CSSWG is considering allowing `@else` after `@media` and `@supports` rules.

Given this, I think it may make sense to start allowing `@else` to be treated as an unknown at-rule and compiled to plain CSS if it doesn't appear after an `@if` rule. One open question, if we decide to do this, is whether to allow it *anywhere* or only after another unknown at-rule. The former is more broadly forwards-compatible, but the latter is more likely to catch unintended user errors.

**Comment by Ariane-B** [comment]
It might be simpler to simply add something like `@css-if` / `@css-else` (or rather `@css-anyatrule`) that simply compiles the exact same at-rule to CSS.

**Comment by nex3** [comment]
I'm closing this out since no one expressed any interest, and we decided not to use `@else` for our PostCSS plugin anyway.
