### ISSUE TITLE
:is() should behave like :matches() with @extend

### ISSUE THREAD

**Issue by nex3** [sass/sass#2829]
Currently, if a `:matches()` selector is extended into `:not()`, it's replaced with additional `:not()` rules. For example, `selector-extend(":not(.c)", ".c", ":matches(.d, .e)")` returns `:not(.c):not(.d):not(.e)`. However, despite `:matches()` being an alias for `:is()`, the same is not true for the `:is()` selector. It should be.

**Comment by nex3** [comment]
Actually, it looks like the problem is broader—we have a fair amount of `:matches()`-specific logic, and *none* of it is currently applied to `:is()`.

**Comment by nex3** [comment]
Note that `:is()` is not yet supported by that name [in any browsers](https://caniuse.com/#search=%3Ais).

**Comment by stof** [comment]
`:is()` is now supported in Firefox and Safari (and Chromium has it behind a flag)
