### ISSUE TITLE
CSS "box-sizing" alternative?

### ISSUE THREAD

**Issue by klj613** [sass/sass#283]
I just came across "box-sizing: border-box" to fix the width of a box when you add padding to it (cross-browser issues). Then I thought about CSS pre-processors. That they could remove the padding value from the width value?

Not sure if anyone already mentioned this. And of course it can be done with variables I guess. Discussion?

**Comment by nex3** [comment]
This isn't really doable in general, since Sass doesn't know the computed value of the necessary properties. For example, if you had the following CSS:

``` css
.foo {padding: 5px}
.bar {width: 100px}
```

It's very difficult for the preprocessor to tell what the width should be for an element with class `foo` and class `bar`.
