### ISSUE TITLE
Add hwb() support in the sass:color module

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#2834]
*Edited by @nex3*

* [x] [Proposal](https://github.com/sass/sass/pull/2835)
* [x] [Specs](https://github.com/sass/sass-spec/issues/1570)
* [x] [Documentation](https://github.com/sass/sass-site/issues/477)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1089)
* [ ] [LibSass](https://github.com/sass/libsass/issues/3128)

---

- based on [CSS Color level 4](https://www.w3.org/TR/css-color-4/#the-hwb-notation)
- Adds Sassified functions for `hwb()` color definitions, inspection, & adjustments in the `sass:color` module
- Split out from #2831

**Comment by nex3** [comment]
Oops, forgot to mention here: this has been [open for public review](https://sass-lang.com/blog/request-for-comments-hwb-functions) since 7 October, and on 21 October if no new issues have come up we'll mark it as accepted and start the release process.

**Comment by nex3** [comment]
Marking this as accepted now.
