### ISSUE TITLE
Function interpolation in @media

### ISSUE THREAD

**Issue by emilbayes** [sass/sass#284]
This issue has been up before, but was only fixed for variables.

The following code does not work, as the function is never executed but merely printed:

```
$inter: 800px 1000px
@media (max-width: nth($inter,1))
    width: 1000px

//Output:
@media (max-width: nth(800px 1000px,1)) {
    width: 1000px;
}
```

Workaround:

```
$inter: 800px 1000px
$cur: nth($inter, 1)
@media (max-width: $cur)
    width: 1000px

//Output:
@media (max-width: 800px) {
    width: 1000px;
}
```

Even though there is a workaround the prefered method would be for SASS to execute the function.

**Comment by chriseppstein** [comment]
Please don't abandon inline SassScript for #{} except as a short-term hack -- I think we can make it work here but it will require us to parse the media query.
