### ISSUE TITLE
Feature request: @use as reference

### ISSUE THREAD

**Issue by RickMeijer** [sass/sass#2841]
# Intro
I'm not very good in explaining things. It's kind of like having dyslexia of the mind or something. Can't even rubber duck properly. 
I tried to be as clear and succint as possible (dropping succintness in favor of clarity), but I feel like I failed miserably regardless. If I'm unclear on something, please give some feedback so I can improve myself. I'm not even sure if I'm in the right git, to be honest. Thanks.

# The problem in a nutshell
There are two ways of looking at this.
One: @use without config acts as a @use with config, making the loading order more important than it needs to be(?). 
Two: function and mixins are evaluated on inclusion instead of execution.

This introduces issues with a certain type of setup common for projects that use webpack to compile the sass per component (like Vue and React).

functions that use a configurable variable to set a default argument and are invoked after that variable is set shouldn't cause a problem with @use ... with, but it seems like it does. 

This causes problems when you're trying to have global variables, functions and mixins in a project that is split over several different components.

This used to be possible:
```
// variables.scss
$variable: 'foobar';

// function.scss
@import "variables";
@function debug($var: $variable) {
  @debug #{$var};
}

@import "function.scss";
debug(); // 'foobar'
$variable: 'foo';
debug(); // 'foo'
```
And now it isn't (for good reason, IMHO). But there is a situation where this kind of behaviour is neccesary:

# A 'ridiculous' example
Let's say we have a global settings or variable file like so:
```
//ridiculous-settings.scss

$map: (
  foo: red
) !default;
```
And we have a function definition somewhere in our framework as well, like so:
```
// ridiculous-function.scss

@use 'sass:map';
@use './ridiculous-settings';

@function ridiculous-function($arg1, $arg2: ridiculous-settings.$map) {
   @return map.get($arg2, $arg1);
}
```
Finally we have an index file that is loaded in our main ridiculous-wrapper component, and functions as a mounting point for the sass.
```
// ridiculous-wrapper.vue

<style lang="scss">
@use "ridiculous-framework" as * with (
  $map: (
    foo: yellow
  )
)
.ridiculous-wrapper {
  background: ridiculous-function("foo"); // background is yellow
}
</style>

<template>
  <div class="ridiculous-wrapper">
    <slot />
  </div>
</template>
```
This works swimmingly. The css is compiled and applied for the wrapper, and everything works as expected. Components further down the tree are using the variables configured here. Unfortunately, the mixins, functions and variables are only scoped to this wrapper. It has been that way since forever, and makes sense because every component has its own scope.

The current official solution (as I'm aware) is to import the functions you need in components down the tree like so:
```
// ridiculous-component.vue
<style lang='scss">
@use 'ridiculous-ramework/ridiculous-function' as *;

.ridiculous-component {
  background-color: ridiculous-function('foo'); // background is still yellow, as configured
}
</style>

<template>
  <div class="ridiculous-component" />
</template>
```
This works, but is very verbose for a project with hundreds of components. Javascript has the same issue, but the tooling for that is better suited in case of refactoring.
Besides that; there is every possibility a user can @use the function with a `with` clause, breaking the components further down.

## Desire is the root of unhappiness
There is a strong desire to **not** have to define the same imports for every component, and be able to have variables, functions and mixins available as soon as you import a framework.

Not only that; but you want to set them only once, 

To that end, some clever people used the `prependData` option the `sasss-loader` provides, or something like [sass-resources-loader](https://github.com/shakacode/sass-resources-loader).

It works by prepending the to-be-compiled styles with the data provided, like so:
```
// vue/webpack config
{
  loader: 'sass-loader',
  options: {
    prependData: `
      @use "ridiculous-framework/ridiculous-function.scss"; //prepended
    `
  },
}

// ridiculous-component.vue
<style lang='scss">
@use "ridiculous-framework/ridiculous-function.scss"; //prepended

.ridiculous-component {
  background-color: ridiculous-function('foo'); // background is still yellow, as configured
}
</style>

<template>
  <div class="ridiculous-component" />
</template>
```

This creates a problem for the main framework, since it is compiled to this:
```
// ridiculous-wrapper.vue

<style lang="scss">
@use "ridiculous-framework/ridiculous-function.scss"; //prepended
@use "ridiculous-framework" as * with (
  $map: (
    foo: yellow
  )
)
.ridiculous-wrapper {
  background: ridiculous-function("foo"); // background is yellow
}
</style>

<template>
  <div class="ridiculous-wrapper">
    <slot />
  </div>
</template>
```
The prepending of the function causes the variables to be set with their framework defaults, because the function needs a reference to the variables. This causes an error to occur on the actual instantiation of the framework.
So even though the variables won't be used until the function is run, it blocks the instantiation of said variables. Do I make sense?

Currently there is no way for me to reference files without instantiation.

I hope I made myself clear. I've been working on this for a bit now, and I the longer I work on it the more convoluted it becomes. Ah well. Thanks for making it this far  🎉

**Comment by jathak** [comment]
This sounds similar to #2791. Does that meet your request here, or is there something else you mean by "`@use` as reference"? If so, can you briefly summarize what that is?

**Comment by lunelson** [comment]
I've been thinking about this problem too—if I understand the OP correctly: how to orchestrate `@use` and `with` in a module-bundling (i.e. webpack) scenarios (in my case, React).

AFAICT the problem is that in each place where one might `import` a `.scss` file in JS, those evaluations may or may not be independent (isolated) from the others, and we can't predict in which order they will be evaluated.

`sass-loader` offers the option to `prependData`, as mentioned, but merely adding a `@use` rule is not enough if you intend to configure the `@use`d module, so I believe you'd want to do something like the following:

1. Assuming a setup like this...

    ```scss
    // _config.scss
    $foo: 'foo';
    $bar: 'bar';
    ```
    ```scss
    //_framework.scss
    $foo: 'whatever' !default;
    $bar: 'whatever' !default;

    @function foo() { @return $foo; }
    @function bar() { @return $bar; }
    ```

2. ...you'd want to apply the full `@use ... with ( ... )` syntax inside the `prependData` option in `sass-loader`:

    ```js
    // webpack.config.js
    const CONFIG_PATH = require.resolve('.relative/path/to/_config.scss');
    const FRAMEWORK_PATH = require.resolve('.relative/path/to/_framework.scss');

    /* ...in loader configs:... */
    {
      loader: 'sass-loader',
      options: {
        prependData: `
    @use '${CONFIG_PATH}' as *;
    @use '${FRAMEWORK_PATH}' with (
      $foo: $foo,
      $bar: $bar,
    );
        `
      },
    }
    ```

**Comment by lunelson** [comment]
As an aside, it would be cool if we could pass just variable names to `with`, like `... with ( $foo, $bar )`

**Comment by RickMeijer** [comment]
Ooh boy it's been a while for me, so it's all a bit foggy. I think I eventually worked around the problem. I have to keep junior developers in mind as well, and any solution I came up with at the time was way to difficult to maintain/automate. I need to take another stab at it sometime. Looks like the above solution should work, which is pretty exciting.
