### ISSUE TITLE
using "with" in @use & @forward for lists and maps

### ISSUE THREAD

**Issue by taurean** [sass/sass#2842]
The documentation is pretty clear on the syntax for overriding a variable in a file when using `@use` or `@forward` but what is it possible to override more than just variables? Eg. How could I go about overriding a list (such as a list of typefaces), replace a map (or join it with another existing one), etc? Right now I'm mainly concerned with replacing a list but it would be great to be able to append to a map as well.

**Comment by naiyerasif** [comment]
This is a problem I'm facing while trying to merge maps. Permitting the use of the namespace of the imported module would be useful, e.g.,

```scss
@use 'variables' with (
  $font-families: map.merge(variables.$font-families, other.$font-families)
);
```

or

```scss
@use 'variables' as base with (
  $font-families: map.merge(base.$font-families, other.$font-families)
);
```

At the moment, this is not possible. Any workaround would be appreciated.

**Comment by Awjin** [comment]
@taurean 

> The documentation is pretty clear on the syntax for overriding a variable in a file when using `@use` or `@forward` but what is it possible to override more than just variables? Eg. How could I go about overriding a list (such as a list of typefaces), replace a map (or join it with another existing one), etc? Right now I'm mainly concerned with replacing a list but it would be great to be able to append to a map as well.

Overriding maps/lists is already implemented:

```scss
<===> style.scss
@use 'module' with (
  $a: (b: 2, c: 2)
);

<===> _module.scss
$a: (b: 1, c: 1) !default;
@debug($a); //=> (b: 2, c: 2)
```

@Microflash 

You could achieve this behavior by extracting the variables into their own module.

```scss
<===> _variables.scss
$a: (b: 1, c: 1);

<===> style.scss
@use 'sass:map';
@use 'variables';
@use 'module' with (
  $a: map.merge(variables.$a, (d: 2))
);

<===> _module.scss
@use 'variables';
$a: variables.$a !default;
@debug($a); //=> (b: 1, c: 1, d: 2)
```

These are both great questions for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass). We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
