### ISSUE TITLE
Sass --watch does not detect @use file changes

### ISSUE THREAD

**Issue by crystalfp** [sass/sass#2843]
My `main.scss` file contains: `@use "../widgets/widget.scss";`
and is compiled with `sass --style=compressed --watch --color main.scss main.min.css`

If I modify `main.scss` the compiler compiles it.

But if I modify `../widgets/widget.scss` nothing happens.

Same problem if I change `@use` to `@import`. What am I missing? 

sass 1.26.3 on Windows 10 64 bits.

Small example (change extension to .zip) [bug-sass.txt](https://github.com/sass/sass/files/4496052/bug-sass.txt)

**Comment by cpoftea** [comment]
It's not an issue

You didn't tell 'watcher' to watch you `widget.scss`. 'Watcher' don't watch imports or modules if you don't tell him.

First, you should rename you `widget.scss` to `_widget.scss` to prevent compilation (read [here](https://sass-lang.com/documentation/at-rules/use#partials) about partials)

Second, you should pass the file to command
`sass --style=compressed --watch --color main.scss:main.min.css ../widgets/_widget.scss`

**Comment by crystalfp** [comment]
Thanks! I will implement your suggestion.
Simply I was convinced that sass compiler could extract the composition tree by following the `@use` and `@include` chain.
