### ISSUE TITLE
Compilation remove quotes inside attribute selector

### ISSUE THREAD

**Issue by philippebeck** [sass/sass#2845]
sass --version => 1.26.3 compiled with dart2js 2.7.1

**With this input code** (same as the expected output) :
`[class^="grid"],
[class*=" grid"],
[class^="fluid"],
[class*=" fluid"] {
  display: grid;
}`

**The actual output code is** :
`[class^=grid],
[class*=" grid"],
[class^=fluid],
[class*=" fluid"] {
  display: grid;
}`

So the quotes around "grid" & "fluid" missing for each first occurrence !

So I tried many options without any change to the output (or with twice quote like : `[class^='"grid"']) :
- adding single quotes around
- creating a variable $grid
- using meta.inspect()
- using string.quote()
- mixing those different options

The solutions I found to keep the quotes & only one pair of quotes are all bad because I need to add a dot or a space before or after the term "grid" like ".grid" | " grid" | "grid." | "grid "...

I have the same problem with many other part of code, here is another example :

**Input** (same as the expected output) :
`[class*="card"]`

**Output** :
`[class*=card]`

Same wrong result !

Thanks for your help !

**Comment by jathak** [comment]
This behavior is intended, as `[class*="card"]` and `[class*=card]` are equivalent in CSS.

Sass only includes quotes when serializing selectors if they are necessary, so they're omitted here even if the Sass string used to construct the selector was quoted.

**Comment by markfullmer** [comment]
> This behavior is intended, as [class*="card"] and [class*=card] are equivalent in CSS.

> Sass only includes quotes when serializing selectors if they are necessary, so they're omitted here even if the Sass string used to construct the selector was quoted.

This is not the case for all selectors. For example, `ol[type="i"]` will be interpreted differently from `ol[type=i]`. For example, the following CSS will always choose to apply the latter declaration, whether or not `<ol type="i">` or `<ol type="I">` is present in markup.

```
ol[type=I] {
  list-style-type: upper-roman;
}
ol[type=i] {
  list-style-type: lower-roman;
}
```
In contrast, the following **will** respect the casing difference:


```
ol[type="I"] {
  list-style-type: upper-roman;
}
ol[type="i"] {
  list-style-type: lower-roman;
}
```

**Comment by nex3** [comment]
[That's not accurate](https://codepen.io/nex3/pen/ZEZJowL). The behavior of both of your CSS snippets is identical (tested in Firefox and Chrome), which is [the specified behavior](https://www.w3.org/TR/selectors-4/#attribute-case).

**Comment by markfullmer** [comment]
> The behavior of both of your CSS snippets is identical 

~Thanks for responding! The problem arises **when both are used in conjunction**. As can be seen in the screenshot below, when both are defined in CSS, the latter CSS declaration always takes precedence. In the example, I defined the CSS for `type=I` (upper-roman) second, and as can be seen when the markup is `type="i"` (lower-roman), the upper-roman CSS wins out:~

**Update: my mistake! The same thing happens if the `type` attribute is quoted. This is a CSS issue, not a SASS compiler issue. Reference: https://github.com/w3c/csswg-drafts/issues/2101#issuecomment-438751096**
