### ISSUE TITLE
Ability to use @use with a variable map

### ISSUE THREAD

**Issue by vasilyevd** [sass/sass#2846]
I just started making my Design System and got such a problem.
System Design provides a default configuration.
In an application that uses the Design System, you must configure ...
```scss
// re-configure ds-config by custom variables value
@use "design-system/ds-config" as config with (
  $core-namespace: 'myapp',
);
// use api (variables, mixins, functions) with re-configured values
@use "design-system/ds-api" as ds;
```
But, if I need to redefine so many values?
For example, set a palette of primary colors? Identify a typography map? Set indentation settings, etc.
The list will be very long.

When using "@use 'module-name' with", we would like to describe a list of variables not only individually, but also ...
a) by variables map (like meta:load-css used $with as map)
like
```scss
$config-map: (
  core-namespace: 'myapp'
);
@use "design-system/ds-config" with $config-map;
```
or refer to the file/module in which these variables are defined
```scss
/** _my-config-file-or-module.scss */
$config-map: (
  core-namespace: 'myapp'
);

/** app-styles.scss */
@use "design-system/my-config-file-or-module" as app-config;
@use "design-system/ds-config" with app-config.config-map;

// or
@use "design-system/ds-config" with "my-config-file-or-module";
```

**Comment by mirisuzanne** [comment]
Since a module only needs to be configured once, and that configuration is used throughout, it's already possible to handle that in a distinct file - keeping the long configuration out-of-sight:

```scss
// _my-config-file-or-module.scss
@use "design-system" with (
  $long: list,
  $of: configuration,
  $settings: true,
);

// app-styles.scss
@use "_my-config-file-or-module.scss"; // handles design-system config internally
@use "design-system"; // loads the module, already configured
```

That seems very similar to me. The config file uses a `with` block rather than a map, but they have the same basic shape. The app-styles doc is even more compact, since it doesn't need to do any configuration.

This will work as long as ` _my-config-file-or-module` is loaded before the app-styles `@use` of the design system.

Am I missing something in your request?

**Comment by cpoftea** [comment]
@mirisuzanne And what if you want to use those config variables in other files?

**Comment by mirisuzanne** [comment]
```scss
@use "design-system" as ds; // loads the module, already configured

body {
 color: ds.$configured-variable;
}
```

The variables defined in the design system now have the configured values. When you `@use "design-system"` (or maybe `design-system/ds-config` depending how you set it up), you have access to those variables, and their already-configured values.

**Comment by cpoftea** [comment]
Another question to this topic is
@mirisuzanne  Can we do something like this now?
```scss
// ds-config
$var1: val1;
$var2: val2;
```
and then
```scss
// configured module
@use 'ds-config' as config;
@use 'module' with config;
```
instead of
```scss
// configured module
@use 'ds-config' as config;
@use 'module' with (
  $var1: config.$var1,
  $var2: config.$var2
);
```

**Comment by nex3** [comment]
@cpof-tea You can't.

Generally speaking, if you're trying to do really fancy things with `@use ... with`, you're probably going to be better off just using explicit configuration maps. The `with` syntax is intended as a way to continue to use the sort of default-overriding that was common with `@import`, but any time you're tying yourself to overriding configuration before you load a module you're going to lose some flexibility. Loading the module first and adjusting the configuration later, ideally through mixins that expose a well-designed API for doing so, is a better way to go.

**Comment by cpoftea** [comment]
Hmm, I'll keep it in mind, thx

**Comment by vasilyevd** [comment]
> ```css-scss
> $long: list,
>   $of: configuration,
>   $settings: true,
> ```
I just would like to be able to set the configuration not only with a "manual" list but also with a map.
```css-scss
$my-config-map: (
  $long: list,
  $of: configuration,
  $settings: true
);
@use ... with $my-config-map
```
Now meta.load-css() works like this.

Since `$my-config-map` can be pre-configured using a script. 
Now if we pass to `use .. with` a variable with `null`, the `!default` value will be overridden by this `null` value. Those. if I need to exclude some value from the configuration list, I will need to do it by hand.
But with my script/logic, I could just remove it from the map (or not add it).
