### ISSUE TITLE
min() throws erros in React css modules

### ISSUE THREAD

**Issue by davidc360** [sass/sass#2847]
font-size: min(1em, 20px)
results in error: SassError: Internal Error: Incompatible units: 'px' and 'em'. I think Sass is calling its own min function instead of the CSS built in one?

**Comment by cpoftea** [comment]
It's a LibSass implementation behavior. All sass built-in modules and their functions (such as `max()`, `min()`, `darken()`, `lighten()` etc) are accessible at global scope.
Try to wrap it `#{min(...)}`. Should help

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/libsass/issues/2701. If you use Dart Sass, `min()` and `max()` will behave as expected when used in a plain-CSS-compatible way.
