### ISSUE TITLE
Styles produced by the `use`d modules appear out of order related to the comments

### ISSUE THREAD

**Issue by emirotin** [sass/sass#2848]
- [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/ordered-comments.md) (https://github.com/sass/sass/pull/3548)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1939) (https://github.com/sass/dart-sass/pull/1989)
- [x] [Tests](https://github.com/sass/sass-spec/issues/1901) (https://github.com/sass/sass-spec/pull/1919)

---

# Intro

I've encountered a problem when `use`ing a library, specifically MDC.

Before going into details I should mention that:
- I understand that `use` is intended for "no side effects" modules — to only get the exported variables, mixins, etc., not the yielded styles,
- I understand that `use` statements must go first and are meant to resemble the programming language static imports.

Given that I have a valid use-case which I describe in the end of this description.

---

# The issue

The CSS yielded by the `use`d module is output at the beginning of the file even before any multiline comments which may precede the `use` line.

Repro: https://github.com/emirotin/sass-comments-issue (run `npm install && npm run build`).

---

# My use-case

I'm using MDC following the recommended way to use its styles:

```
@use "@material/theme" with (
  $primary: #9c27b0,
  $secondary: #76ff03,
  $background: #fff,
);
@use "material-components-web";
```

From https://material.io/develop/web/docs/theming/

`material-components-web` package does produce lots of styles with of course lots of CSS to handle edge cases in various browsers.

I have stylelint enabled and it has a lot of warnings for these styles. I only care about the linting for my own styles, as well as I cannot influence the MDC styles so I want it wrapped in stylelint-disabled/enabled comments.

Apparently it's not possible. I think I can workaround it with `@import` (it causes a different, unrelated issue at the moment) but I think keeping the preceding comments can be desired in other cases as well.

**Comment by Awjin** [comment]
I assume you're seeing the following input—
```
/* stylelint-disable */
@use "foo";
/* stylelint-enable */
```
emit the following output—
```
foo { ... }
/* stylelint-disable */
/* stylelint-enable */
```
This is intended behavior, since the CSS from a dependency must be emitted first. It would be really complicated to add an exception for comments that come before an `@use` rule.

> I have stylelint enabled and it has a lot of warnings for these styles. I only care about the linting for my own styles, as well as I cannot influence the MDC styles so I want it wrapped in stylelint-disabled/enabled comments.

One possible workaround is to lint only the `scss` files and not the emitted `css`, so that the linter runs only on the code you've authored.

**Comment by emirotin** [comment]
Yeah I've ended up reconfiguring my project to lint my own files only, thanks.

Imo, use would be more useful (pun intended) if it had no side effects and not emit any CSS at all (and warn or err on the imported module's side effects).

**Comment by orionrush** [comment]
I've just run into this myself - Im converting a framework to Sass, and some of the supplied code, when converted to mixins,  brakes rules like max depth etc. Im able to mute the rules with 

    /* stylelint-disable max-nesting-depth */
    ...
    /* stylelint-enable max-nesting-depth */ 

But as there are going to be _a lot_ of mixins, im seeing these comments appear everywhere in the output, and I'd love to tidy it up. I know I can [ignore files](https://stylelint.io/user-guide/configure#ignorefiles), but I do still want linting in general...

**Comment by nex3** [comment]
I've been looking into this again and I think I've found a way to handle it efficiently without _too_ much nastiness in the compiler.

**Comment by nex3** [comment]
Proposal is out for review, it's likely to be uncontroversial so I'll just give it two weeks.

**Comment by bnjmnrsh** [comment]
How exciting @nex3 - thank you for circling back to this issue, much appreciated.
