### ISSUE TITLE
Feature request: Simplified nth-* statements

### ISSUE THREAD

**Issue by Ariane-B** [sass/sass#2851]
In CSS, when you want to target several `:nth-of-child` or `:nth-child` pseudo-classes at once, you have to repeat the whole thing:

```css
.my-parent .my-class:nth-of-type(6n+1), .my-parent .my-class:nth-of-type(6n+4), .my-parent .my-class:nth-of-type(6n+5) {
  /* Some styles */
}
```

Sass allows us to shorten it a bit, but it's still wordy:

```scss
.my-parent {
  .my-class {
    &:nth-of-type(6n+1), &:nth-of-type(6n+4), &:nth-of-type(6n+5) {
       // Some styles
    }
  }
}
```

I wish it were possible to shorten the statement to something like this:

```scss
.my-parent {
  .my-class {
    &:nth-of-type( 6n+1, 6n+4, 6n+5 ) {
       // Some styles
    }
  }
}
```

Which would compile to:

```css
.my-parent .my-class:nth-of-type(6n+1), .my-parent .my-class:nth-of-type(6n+4), .my-parent .my-class:nth-of-type(6n+5) {
  /* Some styles */
}
```

Would that be doable? I realize it wouldn't be such a hard function to write, but it would be nice if it were built-in. It would blend in better with the other selectors. You could use the almost-native syntax and it'd behave as expected. After all, there isn't really a possibility for confusion. If there are commas, someone necessarily wants those pseudo-classes together.

**Comment by Awjin** [comment]
From a design standpoint, and from experience, Sass avoids overloading built-in CSS functions. We've learned from cases like `min()`, where parsing it as a CSS vs. Sass function depending on the context can lead to confusing behavior. Backwards compatibility will also be an issue as the CSS and Sass specs evolve. The exact same concerns apply here with `:nth-of-type`.

To avoid these problems, it would be best to implement this as a function.

**Comment by Ariane-B** [comment]
Thank you for you answer. What do you think would be the most concise/practical to write? Usually, dynamically generated selectors require `#{}` concatenation to work. Is there a way to sidestep this?

**Comment by mirisuzanne** [comment]
@Ariane-B You can sidestep repeating that interpolation by using a mixin rather than a function:

```scss
@mixin nth-of-type($args...) {
  // loop over $args to generate a list of &:nth-of-type(<arg>) $selectors, and then…
  #{$selectors}  {
    @content;
  }
}

.my-parent {
  .my-class {
    // You'll also need to quote the nth-logic so it doesn't get compiled to e.g. 7n, 10n, 11n
    @include nth-of-type( '6n+1', '6n+4', '6n+5' ) {
       // Some styles
    }
  }
}
```

**Comment by Ariane-B** [comment]
Hmm, so it's either a function with interpolation or a mixin with the `@include` keyword. Thank you!
