### ISSUE TITLE
Semi-global scopes for loops cause optimization problem

### ISSUE THREAD

**Issue by mgreter** [sass/sass#2852]
I believe the topic of "Semi-global scopes" has come up before (e.g. https://github.com/sass/sass/issues/1863) under different context. I somewhat understand the reasoning for having it this way, although as an experienced programmer it sure seemed very counter intuitive to me as well. I came across this lately when I optimized LibSass runtime. I use a stack based approach like C compiler do for variables, functions and mixins. E.g. I know how many variables are in a scope after parsing, so I can actually resolve them to an array position access. Same for all inner occurrences of variable accesses; I always know which variable on the stack to use. On runtime when a scope is executed I only initialize the stack array for the additional variables and store the offset for the new runtime frame. When a variable is accessed on runtime, it only needs to add the current frame offset and its local offset to fetch itself from a sequential global array (same as functions stacks works in most compiled languages). This gave quite a bit of performance improvement, and I think dart-sass might well try to do this optimization, as all runtime variable map lookups are eliminated. If it wasn't for those semi-global scopes ...

So the questions are quite simple:

1) Is it okay to drop this behavior in LibSass 4.0 if I advertise it properly?
2) I would like Sass to reconsider and to follow other languages here!?

Note: it was not too hard to still have the optimizations for 99% of the variable accesses and still supporting "semi-global scopes". But needing to support this special case adds quite some complexity and runtime overhead, as I need to keep around maps for all variables just for this case. Otherwise I could completely drop them for runtime evaluation.

Here are some samples to illustrate what is meant:
```scss
$a : 2;
@for $a from 1 through $a {
 $a: $a + 1;
 @debug($a); 
}
@debug($a); 
```
```scss
$b : 5;
@for $count from 1 through 2 {
 $b: $b + $count;
 @debug($b); 
}
@debug($b); 
```
I believe the following was the one that gave me the most headache, since in the first iteration, the `$i != 5` seems to reference the outer scope, but on subsequent runs `$i` will reference the scope of `.foo`, as if it was magically created there. AFAICR it's where I came to the conclusion that any fully static optimization is impossible.

```scss
$i: 1;
.foo {
  @while $i != 5 {
    $i: $i + 1;
    @debug($i);
  }
  @debug($i);
}
@debug($i);

$n: 1;
@while $n != 5 {
  $n: $n + 1;
  @debug($n);
}
@debug($n);
```
Feel free to guess what its output should be :)

**Comment by Awjin** [comment]
Getting rid of semi-global scopes would be a massive breaking change. I'm not sure that would be an appropriate trade-off for a small optimization.

**Comment by mgreter** [comment]
I may should have been a bit more detailed. I'm not talking about how control structures can assign to global scope if they are in the global scope. My question is why the `$i` used in e.g. the while statement doesn't bleed out in the example above where the while is inside the .foo scope.

**Comment by nex3** [comment]
> I may should have been a bit more detailed. I'm not talking about how control structures can assign to global scope if they are in the global scope. My question is why the `$i` used in e.g. the while statement doesn't bleed out in the example above where the while is inside the .foo scope.

That's part of what it means for a scope to be "semi-global". Control directives like `@while` define their own fully local scopes if they're used within another local scope (in this case, the local scope within the style rule). It's only when they're used within a global or semi-global scope that they can assign to global variables without explicitly writing `!global`.

**Comment by mgreter** [comment]
Sorry all, I think I confused myself a bit yesterday, will going to close this and open another issue.
