### ISSUE TITLE
Plain css clamp()

### ISSUE THREAD

**Issue by Awjin** [sass/sass#2860]
- [x] [Proposal](https://github.com/sass/sass/pull/2942)
- [x] [Specs](https://github.com/sass/sass-spec/issues/1599)
- [x] [Documentation](https://github.com/sass/sass-site/issues/505)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1146)

---

The plain CSS function [`clamp()`](https://www.w3.org/TR/css-values-4/#funcdef-clamp) has shipped in Chrome, Edge, and Firefox. This function introduces a `calc()`-style context where plain CSS math is supported—e.g. `clamp(1%, 1% + 1vw, 10%)`.

To support `clamp()`, Sass must parse it specially as a `calc()`-syntax function. Fortunately, because the Sass `clamp()` function is scoped to the `sass:math` module, it does not conflict with the CSS `clamp()`. Differentiating the two is straightforward.

Although this may be a breaking change, since this function is relatively new and has no namespace conflicts, I propose we fast-track this.

**Comment by nex3** [comment]
I think because this technically does introduce a backwards incompatibility (a user could be writing `clamp($foo)`, which will need to be changed to `clamp(#{$foo})`, we'll unfortunately have to avoid the fast-track process.

**Comment by nex3** [comment]
The proposal has landed. Since it's relatively small, I think we'll only need to wait two weeks for feedback (unless a debate needs to happen).
