### ISSUE TITLE
I just want to change the lightness, but the values ​​of hue and saturation are also changed

### ISSUE THREAD

**Issue by renlindong** [sass/sass#2862]
code：
![image](https://user-images.githubusercontent.com/20882991/82325389-c1820f00-9a0d-11ea-8d58-4535cff2605b.png)

$color-test: 
![image](https://user-images.githubusercontent.com/20882991/82325515-f2624400-9a0d-11ea-93dc-9c012dc43350.png)

$color-test-light:
![image](https://user-images.githubusercontent.com/20882991/82325555-0443e700-9a0e-11ea-96be-66b7017f8570.png)

$color-test-light--dep:
![image](https://user-images.githubusercontent.com/20882991/82325622-1aea3e00-9a0e-11ea-8927-738e73385e00.png)

**Comment by jathak** [comment]
Sass always represents colors in RGB, so I'm not sure why you're seeing HSL being output at all.

Can you provide more information?
- which Sass compiler and version you're using
- a minimal reproduction of the input and output you're seeing in textual form (not screenshots)
- are you using any workaround to force Sass to output colors in HSL form? If so, that's the likely culprit, not Sass itself

**Comment by mirisuzanne** [comment]
Browser inspectors will show you any format you want. That's an internal browser dev-tools setting. It's likely not the actual output. 

That's likely causing the issue here: Sass converts to rgb, and the browser converts back to hsl in dev-tools – so there may be slight rounding differences.

**Comment by renlindong** [comment]
> Browser inspectors will show you any format you want. That's an internal browser dev-tools setting. It's likely not the actual output. 
> 
> 
> 
> That's likely causing the issue here: Sass converts to rgb, and the browser converts back to hsl in dev-tools – so there may be slight rounding differences.


Your answer resolved my question. Thank you😊
