### ISSUE TITLE
Need advice on easiest way to migrate from @import to @use

### ISSUE THREAD

**Issue by kerryj89** [sass/sass#2865]
Hi,

I have 426 SCSS files in one of my projects.  The files are structured in a modular/scoped-ish way as seen below, where styles in `section/login/components/_some-components.scss` are encapsulated by my own CSS `.section-login {}` along the way to change the component background to pink when inside the login view in this contrived example:

```
base/
components/
└─ _some-component.scss
layout/
section/
├─login/
|  └─components/
|    └─ _some-component.scss (.some-component { background: pink })
├─events/
|  └─components/
|    └─ _some-component.scss (.some-component { background: green })
utilities
vendors
```

A lot of my components rely on generic spacing variables that they implicitly have access to after `@importing '_variables'` once in the top-most import kickstart file.  If I understand correctly, SCSS is going all in with the modular approach and things will be less implicit in the future.  That is, if you want to use a generic variable, you must say so in the file you're wanting to access it via `@use`.

Please let me know if my understanding is correct, and advise if there is a quick way to migrate to this setup other than constantly trying to build and rectify missing `@use` file by file.

Thanks!

**Comment by jathak** [comment]
You can use the [Sass migrator](https://sass-lang.com/documentation/cli/migrator)!

Once installed, you should be able to run `sass-migrator module --migrate-deps <glob of all your SCSS entrypoints>`. It also supports incremental migration, so you can migrate upstream dependencies first and then anything depending on this files.

If you run into any issues, you can file bugs [here](https://github.com/sass/migrator/issues).
