### ISSUE TITLE
nested @use? what can replace import?

### ISSUE THREAD

**Issue by saltnpixels** [sass/sass#2867]
I am starting to use @use, although I use webpack and so I import all files via javascript....

Anyways if I want to nest an import how cna I do that when @use is meant to be used at the top of a file??

.something{
@use ... will not work
}

I would normally use import, but you say your phasing that out...

**Comment by jathak** [comment]
You can use `@include meta.load-css(...)` to dynamically load the CSS from another file. If you want to access variables, functions, or mixins, you'll need to `@use` it from the top of the file. This ensures that the source of all Sass member references can be statically determined.

**Comment by saltnpixels** [comment]
Cool thanks. and can I ask one more question?

Normally I have one file and I import all my sass into the one file....like so:


base.scss
 //the resources one holds actual scss variables I have set up. The files below use these...
 - @import resources.scss.
 - @import  reset.scss
 -  @import layout.scss
...etc


What is the correct model going forward for stringing files together? 
I used to follow something like this:
http://thesassway.com/beginner/how-to-structure-a-sass-project

**Comment by nabeerdar** [comment]
> You can use `@include meta.load-css(...)` to dynamically load the CSS from another file. If you want to access variables, functions, or mixins, you'll need to `@use` it from the top of the file. This ensures that the source of all Sass member references can be statically determined.

Thanks, very helpful
