### ISSUE TITLE
Issue with factoring out coefficient from calc

### ISSUE THREAD

**Issue by hosseinzoda** [sass/sass#2868]
I'm going to drop this here. The css of this is not right.

# scss
```
.b4x {
  width: calc(var(--block-width) * 4 + var(--block-margin) * 4);
}
```

# css
```
.b4x {
  width: calc(var(--block-width) + var(--block-margin));
}
```

# Workaround

Factor out the coefficient manually.
```
.b4x {
  width: calc(4 * (var(--block-width) + var(--block-margin)));
}
```

**Comment by jathak** [comment]
I'm unable to reproduce this with both Dart Sass and libsass.

Which Sass compiler and version are you using?

**Comment by hosseinzoda** [comment]
Hi Jennifer

Maybe it is already solved. I'm using `node-sass@4.13.1` via  `sass-loader@8.0.2`. 

I don't know what is the compiler version. It looks like it is solved on the version you are running.

**Comment by jathak** [comment]
I can't replicate it even with `node-sass@4.13.1`.

Can you try passing a test file directly into the `node-sass` executable? It's possible the issue is with `sass-loader`.

**Comment by hosseinzoda** [comment]
Well, Yes. It is working right when I tried to with `node-sass`executable. So should I submit this issue to `sass-loader`?

**Comment by jathak** [comment]
Yeah. The issue doesn't seem to be Sass itself.
