### ISSUE TITLE
Option for alternative method to specify partials (without underscore)

### ISSUE THREAD

**Issue by rowdyrotifer** [sass/sass#2870]
I gave myself a little laugh the other day calling Sass _The Opinionated File Sorter_ because, lead by underscores, scss partials are ungrouped from related files when files are listed in alphabetical order.

But then I thought, maybe it'd be a reasonable proposal to add add a second option to specifying partials: an option to treat `.pscss` (or something similar) as partial scss files as well.

What do y'all think? 😁

**Comment by voltaek** [comment]
I like the idea of not having to use the underscore to differentiate partials, but I think something like `some-component.partial.scss` or `some-component.part.scss` would be better for maintaining current compatibilities, such as default program by file extension, syntax highlighting by file extension, scripts that look for `*.scss` files, etc. Basically, not changing the final extension would save everyone a lot of headache and still accomplish the same goal.

**Comment by jathak** [comment]
While using an alternate file extension *instead of* underscores to indicate partials might have made sense if Sass was being designed today, the costs of adding support for yet another file extension to Sass's already complex URL resolution logic (which would have to be implemented in both Dart Sass and libsass, as well as in tools like Webpack that reimplement this logic) unfortunately outweigh the benefits.

**Comment by voltaek** [comment]
@jathak Do you think keeping the file extension, but adding an infix to the filename - as I suggested above - would still add too much complexity to the resolution logic? Even if integration into the various SASS libraries as an alternative option for naming partials took some time, I think people would still appreciate being able to use a more obvious naming convention.

**Comment by rowdyrotifer** [comment]
Well I think the real problem is that if the SASS specification said that this needed to be supported in version X then dart sass and libsass basically _have_ to implement it for version X. I would have naïvely assumed @voltaek 's suggestion would have been simple but @jathak mentioned "complex URL resolution logic" and I'm sure she already has an idea of whether it'd be a few-lines fix or actually require a rewrite or something otherwise headache-inducing!

So since it sounds like this is a case where the specification is dependent on the implementations here, I'd assume that the only way for this to gain traction would be if someone, on behalf of this issue, would reference these implementations or perhaps try to implement the change first themselves to confirm/deny whether it would be difficult/simple.
