### ISSUE TITLE
Limitations of @use for chunking

### ISSUE THREAD

**Issue by clshortfuse** [sass/sass#2875]
To keep this short. I essentially have a number of files that import a number of modules that have overlap.

External modules: `theme`, `layout`, `button`, `menu`, `dialog.

* `/splash/firstpaint.scss` imports `theme`
* `/splash/index.scss` imports `splash/firstpaint.scss` and `button`.

* `/firstpaint.scss` imports `splash/firstpaint.scss` and `layout`

* `/styles.scss` imports a set of files that eventually import `/splash/index.scss`, `layout`, `button`, `dialog`, `menu` modules

Client-side, there's only `firstpaint.scss` and `styles.scss`.

`firstpaint.scss` imports via `@use` the bare minimum of UI components to achieve a first paint. `styles.scss` has a differed loading strategy. The goal is to get `styles.scss` to NOT import rules that overlap with `firstpaint.scss`.

I can manually achieve what I want by commenting out external modules that overlap, but that heavily negates the benefit of modules loading if I need to manually track what's loaded and where. It also gets cumbersome when working with a large project (This example is a simplification of one with 72 `@use` operations).

I figured, perhaps I could a blank reference instead, so I don't have to comment out all the overlapping modules. So in `styles.scss`, before processing the file tree, I can manually add:

```scss
@use "_blank.scss" as theme;
@use "_blank.scss" as layout;
````

In theory, it will be blank for `styles.scss` since it'll be already included with `firstpaint.scss`. But SCSS seems to handhold a bit aggressively here and throw: `SassError: There's already a module with namespace "layout".` Yes, I know the module exists, and that's the intended effect. Perhaps, we can relax this error to a warning either permanently or via an argument. Maybe some syntax similar to `!default` where if the module is already imported, then it can be optionally overridden.

Another option would be a rule that force unloads a module: (eg: `@exclude`, `@disuse` `@unload`, or `@unuse`). Basically we tell sass NOT to include the imports.

The last is obviously create some integrated chunking system. Then I can have three files, `firstpaint.scss`, `styles.scss` and `chunk_firstpaint_styles.scss`. I would think that would require the most amount of work, since it goes outside of working with one file at a time.

----

I apologize this already exists in sass, or maybe there's something in `webpack` that will do this for me.

**Comment by clshortfuse** [comment]
Another thought. Perhaps if there was a line in `styles.scss` that says it expects all the modules inside `firstpaint.scss` to included and won't include it itself.

Something like `@expects './firstpaint.scss';`.

**Comment by clshortfuse** [comment]
Apparently `LESS` has something like called [import references](http://lesscss.org/features/#import-atrules-feature-reference). I don't see a way to make it work with SASS. The workarounds to use `@extend` don't really apply here.

**Comment by clshortfuse** [comment]
Well, I figured out a way to do it. I can apparently do this with the `importer` option. First by collecting all the imports of `firstpaint.scss`:

````js
/**
 * @param {sass.Options} sassOptions
 * @return {Set<string>}
 */
function getImportedURLs(sassOptions) {
  /** @type {Set<string>} */
  const importedUrls = new Set();
  sass.renderSync({
    ...sassOptions,
    importer(url) {
      const fileName = path.parse(url).name;
      if (fileName[0] !== '_') {
        importedUrls.add(url);
      }
      return null;
    },
  });
  return importedUrls;
}
````

Then by telling `sass-loader` to snip out those imports.

````js
{
  loader: 'sass-loader',
  options: {
    sassOptions(loaderContext) {
      const fileName = path.parse(loaderContext.resourcePath).name;
      if (fileName === 'firstpaint') return {};
      return {
        importer(url) {
          if (firstPaintImports.has(url)) {
            return { contents: '/* REMOVED BY CHUNKER */' };
          }
          return null;
        },
      };
    },
  },
},
````

It would still be nice for a `@depends` syntax, similar to `LESS`. Also, `importer` doesn't really show what the context of the import is. This assumes `with` isn't being used with `@use`.

**Comment by nex3** [comment]
It sounds like you're trying to do [code splitting](https://reactjs.org/docs/code-splitting.html#code-splitting)—splitting up your CSS into multiple different chunks that are served at different times. This was an [explicit non-goal](https://github.com/sass/sass/blob/master/accepted/module-system.md#non-goals) of the module system:

> The ability to split monolithic CSS into separate chunks that can be served lazily is important for maintaining quick load times for very large applications. However, it's orthogonal to the problems that this module system is trying to solve. This system is primarily concerned with scoping Sass APIs (mixins, functions, and placeholders) rather than declaring dependencies between chunks of generated CSS.
>
> We believe that this module system can work in concert with external code-splitting systems. For example, the module system can be used to load libraries that are used to style individual components, each of which is compiled to its own CSS file. These CSS files could then declare dependencies on one another using special comments or custom at-rules and be stitched together by a code-splitting post-processor.

While an out-of-the-box code splitter for CSS would be useful, I don't think Sass is the right tool for it.

**Comment by clshortfuse** [comment]
@nex3 I'm aware of that and I've read that prior to comment. I know my initial comment is long, but I suggest you try to understand the point I'm making

I'm not asking for SCSS to do the code-splitting. I'm saying to facilitate code-splitting. The problem is that is users of SCSS have to manually compile a list of modules are imported then `@use` become just as limited as `@import`. The point of `@use` is that you don't have to worry about a subnode (in the import tree) reusing an `@import`. But in the context of code-splitting, it doesn't allow it.

>We believe that this module system can work in concert with external code-splitting systems. 

That's what I'm suggesting. And as I stated, `LESS` has a `@import (reference)` syntax. That's not code splitting. That just facilitates code-splitting. It's not the same thing.

**Comment by nex3** [comment]
If the libraries you're using are bundling top-level CSS along with mixins and variables that you want to refer to *without* that top-level CSS, that sounds like a design issue with those libraries. We generally recommend that libraries and partials only expose mixins, so that the entrypoint file has full control over which CSS it generates.

Generally speaking, it's not Sass's policy to support use-cases related to using an upstream stylesheet in a way it wasn't intended to be used. Those sorts of dependencies are almost always brittle, because the upstream stylesheet may unknowingly change in a way that will break your downstream behavior.

**Comment by clshortfuse** [comment]
>If the libraries you're using are bundling top-level CSS along with mixins and variables that you want to refer to without that top-level CSS, that sounds like a design issue with those libraries. We generally recommend that libraries and partials only expose mixins, so that the entrypoint file has full control over which CSS it generates.

It's still a common way for libraries. Top-level CSS has it's benefits, of course. It's the first piece of CSS Google's Material Components asks you to do in their first tutorial: https://codelabs.developers.google.com/codelabs/mdc-101-web/#2

>@import "@material/textfield/mdc-text-field";

I get the concept of requiring mixins and understand all you're saying. But, even IF the library does use mixins instead of top-level CSS, a developer who wants to code-split has to maintain their own, internal dependency tree, despite that tree already being compiled by SASS, to ensure that different split trees don't input the same file. Then it defeats the point of using `@use` liberally in multiple files. So, you're actually better off sticking with `@import` and using a single file that imports all the dependencies. I'm not sure if that point came across clearly, but the point is, the decision to move from `@import` from `@use` isn't without consequences, and it makes code-splitting harder if you do move. And if you do decide to code-split later after having `@use` calls in multiple files, you might have to end up removing them and reverting to `@import` style loading.

I've, personally, solved my issue. I've migrated my framework to use `@use` and I like it. It's great, especially the variable changes. But when it came to refactoring applications to use the framework with `@use`, this is the problem I realized because I do code-split and refactoring means `@use` ends up being as limited as `@import`. Yeah, I ended up writing tiny webpack plugin, but it's limited to knowing exactly what files need to be cross-checked for what SASS file, while needing to completely rendering in full the cross-checked files, with no support for `with`. (Though I would admit that last part can be addressed by changes to `dart-sass`'s `importer` function.) So, if I wanted to make a universal, public plugin that would do it for people, the language doesn't support it.

I'm not really asking to do the team to "do my homework for me". But it's something that I see as a deficiency the `@use` system. Of course, if the team thinks it's fine as it is, and if you want to code-split, then you'll have to manually track all your file dependencies, then that's fine too. I just want to the limitations to be clear in case there's any change in the future to the spec that might help reduce them.

Thanks for your time and patience.

**Comment by AndreasJilvero** [comment]
It's crazy that this is not supported. I'm using dynamic imports for the JS and CSS of my components, but a lot of the content in the CSS is just duplicated CSS rules. A way to implicitely import (or `@expects` like the author mentioned) would be super useful.
