### ISSUE TITLE
@use for scss _variables file no longer makes variables global

### ISSUE THREAD

**Issue by WesMC** [sass/sass#2876]
I came across this when I was trying to compile my scss for a theme I bought.

I noticed the @import and replaced it with @use, and got the following error
`Error: $color: theme-color("primary") is not a color.`

You can see this when you unzip [bootstraps](https://github.com/twbs/bootstrap/archive/v4.0.0.zip) own scss and try to compile bootstrap.scss after replacing all `@import` occurrences with `@use`

I now need to go into each .scss file and include a `@use` in order to reference the variables.

This may have been done intentionally, but that global scope, in my opinion, needs to remain...

EDIT:
This is also true for mixin and function files

**Comment by Awjin** [comment]
Removing global scope and introducing locality/encapsulation were [explicit goals for the module system](https://github.com/sass/sass/blob/master/accepted/module-system.md#goals). The new module system brings Sass in-line with best practices demonstrated by other modern languages. I agree, though, that manually adding an `@use` to each file is tedious. For that, I would recommend using the [Sass migrator](https://sass-lang.com/documentation/cli/migrator), which converts `@import`s to `@use`s and fixes up variable references automatically.

**Comment by WesMC** [comment]
Sounds good. Thank you for the clarification.
