### ISSUE TITLE
Use $variables in scss @import path

### ISSUE THREAD

**Issue by Starlette** [sass/sass#2878]
I see people have been asking for this feature since 2011: https://github.com/sass/sass/issues/115 
Is it not possible for you to add this feature? If not, can you make an alternative suggestion? 

I tried using Gulp's _includePaths_ but it doesn't work with what I need. Example:
```javascript
.pipe(sass({ 
    outputStyle: 'compressed',
    precision: 10,
    includePaths: [
        '../..',
         '../../modules/materialize'
    ]
 })
```
This works with 
```sass
@import "modules/materialize/sass/components/global";
``` 
but not with 
```sass
@import "sass/components/variables";
``` 

Feel free to call me out if I'm using it wrong :) either way, myself and many others would love to do something like this rather:
 ```sass
$materialize-path: "../../modules/materialize/sass/components/";
@import "#{$materialize-path}variables";
```

**Comment by jathak** [comment]
Assuming you are using Dart Sass, you can use the [`meta.load-css` mixin](https://sass-lang.com/documentation/modules/meta#load-css) to dynamically load CSS from a path specified via SassScript (this is part of the module system, which Node Sass has not yet implemented).

However, dynamically loading variables, functions, or mixins from another file is not something we want to allow, as it would make static analysis impossible.
