### ISSUE TITLE
Feature request: Compile entire directory using JavaScript API and not CLI

### ISSUE THREAD

**Issue by 76784** [sass/sass#2879]
Consider the following directory, called `styles`:
```
_partial1.scss
_partial2.scss
_partiala.scss
_partialb.scss
_partialx.scss
_partialy.scss
stylesheet1.scss
stylesheet2.scss
stylesheet3.scss

```
Using the command line, it is incredibly easy to compile these three parent .scss files to css by doing this:

`dart-sass styles:dist/css`

This results in a directory called `dist/css` which contains:
```
stylesheet1.css
stylesheet2.css
stylesheet3.css
```
I have a need, however, to *also* include .scss and .css from `node_modules`. The following *will* work:

```
"dart-sass --load-path=node_modules/some-location-one/css --load-path=node_modules/some-location-two/css --load-path=node_modules/some-location-three/css styles:dist/styles"
``` 

But, I have a need to make the css from `node_modules` configurable. For this reason, I am trying to use the sass JavaScript API (instead of the CLI above):

package.json:
```
scripts": {
    "sass": "node sassConfig.js"
  },
```

sassConfig.js:
```
const sass = require('sass');
const fs = require('fs');
const DEST_DIR = 'dist';
const DEST_AND_SUB_DIR = "dist/styles";

// check if destination directory exists. if not, create it.
if (!fs.existsSync(DEST_DIR)){
    fs.mkdirSync(DEST_DIR);
}
// check if destination/sub-directory exists. if not, create it.
if (!fs.existsSync(DEST_AND_SUB_DIR)){
    fs.mkdirSync(DEST_AND_SUB_DIR);
}

const result = sass.renderSync({
  file: "styles/one-of-many.scss", // need to do all parent .scss in this directory, not just one file
  includePaths: [
        "node_modules/some-location-one/css", // works fine
        "node_modules/some-location-two/css",
        "node_modules/some-location-three/css"		
      ],
  sourceMap: true
});

fs.writeFile( DEST_AND_SUB_DIR + "/styles.css", result.css, function (err) {
  if (err) return console.log(err);
});
```
I've looked through the [sass JavaScript API][1] sass documentation, but there doesn't seem to be the ability to do this "compile entire directory" option like there is in the CLI. It would be nice for this feature to be present. Thanks.

  [1]: https://sass-lang.com/documentation/js-api

**Comment by stof** [comment]
> I've looked through the [sass JavaScript API](https://sass-lang.com/documentation/js-api) sass documentation, but there doesn't seem to be the ability to do this "compile entire directory" option like there is in the CLI. It would be nice for this feature to be present. Thanks.

There is no such API. The compiler itself does not know about directories as input (nor about multiple files as input). The `render` API is about doing a single compilation.
However, node.js has already the tool you need for that: loops (and the `fs` module to read the list of files in the directory).
