### ISSUE TITLE
Bugs with referencing parent selectors

### ISSUE THREAD

**Issue by kizu** [sass/sass#289]
There are some cases that work ok in other pre-processors and it would be cool to support them in Sass too:
# Concatenating with elements

When I write 'p&' I expect the & to expand to the parent selector, so I could narrow the class to the element and from

```
.class {
  color: lime;
  p& {
    color: red;
  }
}
```

I would get the 

```
.class {
  color: lime;
}
p.class {
  color: red;
}
```

Right now I get the error “"&" may only be used at the beginning of a selector.” — I think that such limitation is unneeded.
# Concatenating the parent selector with the postfix

When I write `&_disabled` I expect it to expand to concatenate with the selector, so I could write

```
.class {
  color: lime;
  &_disabled {
    color: red;
  }
}
```

and get this:

```
.class {
  color: lime;
}
.class_disabled {
  color: red;
}
```

But right now I get this (the space occurs between the postfix and selector):

```
.class {
  color: lime;
}
.class _disabled {
  color: red;
}
```

**Comment by nex3** [comment]
Duplicate of #282

**Comment by kizu** [comment]
@nex3 ok, I've understood the arguments against `prefix&` case, but don't the `&postfix` is different? There are a lot of techs that are heavy class-based due to rendering speed optimizations, so having such feature would be great.

Also, why other preprocessors do this and you can't :)

**Comment by nex3** [comment]
The answer to both of your questions is that Sass has a very thorough understanding of selectors. It doesn't treat them just as strings that can be sliced and diced; it fully parses them and understands their structure. A side effect of this is that `&`, Sass's addition to the selector syntax, needs to fit into the standard parsing model of selectors. The examples you're citing involve having `&` mean "replace this text with the text of the parent selector", but Sass instead thinks of it as "replace this simple selector with the parent selector". It's a subtle distinction, but it's important for features like `@extend` that use the full selector parse tree, as well as for SCSS being a true superset of CSS3. These are things that other preprocessors don't really worry about.

Chris and I are talking about ways to address these use cases (see #286). If we end up allowing the use of `&` in SassScript, you'll be able to do your examples as so:

``` scss
.class {
  color: lime;
  p#{&} {
    color: red;
  }
}
```

``` scss
.class {
  color: lime;
  #{&}_disabled {
    color: red;
  }
}
```

**Comment by kizu** [comment]
`#{&}` would be better than nothing, so I'll look forward to it, thank you!

**Comment by svitaliyv** [comment]
I'm using plain sass

```
#{&}_disabled {
```

not work
Syntax error: Invalid CSS after "  #{"

**Comment by chriseppstein** [comment]
@svitaliyv using `&` inside of `#{}` is a proposed feature that we are working on in a branch. it's not completed yet.

**Comment by brewster1134** [comment]
with 3.3, i can no longer do

``` sass
@at-root .mobile#{&}
```

how do i interpolate `&` into a class name now?

**Comment by lolmaus** [comment]
@brewster1134, try `@at-root &.mobile`.

**Comment by brewster1134** [comment]
@lolmaus this is not what i need to do.  I need to prepend to the root parent.  I used to be able to do this...

``` sass
=prepend($prefix)
  @at-root .#{$prefix}#{&}   // note there is no dot (.) separating it
    @content

.foo
  .bar
    +prepend(baz)
      background: red    
```

should output

``` css
.baz.foo .bar {
  background: red;
}
```

i know its sort of hacky, but it was the only way i knew to programmatically modify the parent selector.

**Comment by brewster1134** [comment]
Oddly... i had to roll back to `3.3.0.rc.2` explicitly to get this functionality back.  various versions before and after it throw an exception.

**Comment by chriseppstein** [comment]
@brewster1134 see https://gist.github.com/nex3/8050187 for details.

**Comment by brewster1134** [comment]
ah! very helpful thanks! so it looks like i am sticking with rc.2 until the suite of functions around `&` in SassScript is supported.  Is rc.2 the last version to support it?
