### ISSUE TITLE
Add a  `meta.module-exists` function

### ISSUE THREAD

**Issue by yaquawa** [sass/sass#2891]
Seems like there is no way to test if a module exists ?
Should we have a `meta.module-exists` function as well as the other existing test functions such as `meta.global-variable-exists($name, $module: null)`, `meta.content-exists()`,`meta.variable-exists`...?

**Comment by nex3** [comment]
Can you give an example of a use-case for such a function?

**Comment by yaquawa** [comment]
Hi @nex3 
For my case, this is for error handling the `meta.load-css`.

For example, if you have a css framework like bootstrap that allows users to load different modules like buttons or girds etc. 

```scss
@use "neolithic-css" as nc with
(
    $breakpoints: (
        xs: 320px,
        sm: 550px,
        md: 768px,
    ),
    $modules: [
        [ 'background/background-color',( property-name-alias: bg ) ],
        'typography',
        'spacing',
        'layout',
        'grid',
    ],
    $colors: ['black','white','gray','blue', 'deep-orange'],
    $extra-colors: (
        primary: #0667B7
    )
);
```
Then you could `use` the given modules on behalf of users by utilizing the `meta.load-css`
```scss
@include meta.load-css($module-name, $with: $config)
```

But if the user have got some typo, this `meta.load-css` will throw an error, but the error message isn't that helpful to describe what happened. So I want to check if the module exists first, if it's not then tell the user the module name is incorrect. If sass has a try catch syntax I'd like to dealing it with that, but it does not have such a syntax.

Sure the users could use the `@use` rule directly, but I think the way I shown above is more "self described" and easier to understand and way more shorter than `@use`.

**Comment by nex3** [comment]
It sounds like you're not looking for whether a module exists in the same sense as the other `meta.*-exists()` functions, but whether a given URL would end up loading a module.

I wouldn't recommend doing complex dynamic module loading like you're doing, for a number of reasons. It's substantially less efficient, it means that any static analysis tools like the Sass migrator won't be able to tell which dependencies exist between your files, and—as you've noticed—it makes it difficult for Sass to generate useful error messages when things go wrong.
