### ISSUE TITLE
Can't apply color function on string hex after unquote

### ISSUE THREAD

**Issue by sandeeppatidar30** [sass/sass#2895]
$color: unquote('#F00');

.foo {
    color:  rgba($color, 0.5);
}

It throw an error saying $color: #F00 is not a color.
$color: #F00 is not a color.

Please let me know the alternative fix for this problem.

**Comment by Awjin** [comment]
[`unquote()`](https://sass-lang.com/documentation/modules/string#unquote) takes a string and returns a string with the quotes removed. You need to provide `rgba()` with a color input.
