### ISSUE TITLE
@forward show not working

### ISSUE THREAD

**Issue by TkinterinShanghai** [sass/sass#2897]
Hey fellow developers!

So I was getting started with your @forward ... show ... and ran into an issue that might be a bug. My code looks something like:

styles/_button.scss

```
.base-button {
    color: red;
}

@mixin my-button {
    @extend .base-button;
    content: "some cool string or something";
}
```

styles/_forwardbutton.scss:
```
@forward './button' show my-button ; // please dont forward base-button, i only want my-button

// ... additional, optional magic
```
main.scss:
```
@use 'styles/forwardbutton';

.coolest-button {
  @include forwardbutton.my-button;
}

```

My compiled output is:
```
.base-button, .coolest-button {   // oh, hi base-button, didnt expect you to be here
  color: red;
}

.coolest-button {
  content: "some cool string or something";
}
```

**Comment by jathak** [comment]
`show` and `hide` only apply to Sass members (variables, functions, and mixins).

The entire CSS tree is always included when a module is depended on with `@use` or `@forward`.

We generally think it's good style to avoid having CSS directly in partials and instead wrap styles within mixins that you call from within the entrypoint.

That being said, #2791 is a proposal under consideration to support `@use` rules that don't include CSS, so you should +1 that issue if you're interested in a feature like this.
