### ISSUE TITLE
No easy way to get the last element of a list

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#29]
Please consider adding one of the following:

```
last($list)
nth($list, last)
```

so that the last element of a list can be easily accessed.

**Comment by nex3** [comment]
For stuff like this that can be straightforwardly (if verbosely) done using the existing primitives, I'd like to try saying that it should be done using Sass-defined functions. Of course, those functions have to exist first, but I intend to implement them in time for 3.1.

**Comment by nex3** [comment]
This can now be done via

```
@function last($list) {
  @return nth($list, length($list));
}
```

I'm closing this issue. Once Sass 3.1 has been out for a while and we've got a better sense of what the most useful Compass-defined functions are, we can think about moving them into core Sass.
