### ISSUE TITLE
obscure @-moz-document selector

### ISSUE THREAD

**Issue by emilbayes** [sass/sass#290]
This selector:

```
@-moz-document url-prefix(http://) {
```

Throws this error:

```
(Line 455: Invalid CSS after "      input": expected ")", was "[type=submit].b...")
```

The line comes from Zurb Foundation, foundation.css, line 454.

It is fixed easily by quoting the http:// part:

```
@-moz-document url-prefix("http://") {
```

However I don't know if this breaks something in some version of Gecko, therefore I thought it might need to be fixed.

**Comment by chriseppstein** [comment]
@tixz what version of Sass are you using?

From the [spec](http://www.w3.org/TR/css3-conditional/#at-document), using double-quotes are safe in this context. @nex3 I think it's strange that we're parsing the `@-moz-document` directive. But if we are going to, it seems like we'll need to make `url-prefix` and quote like we do for `url`.

**Comment by emilbayes** [comment]
I'm using Sass 3.2.0.alpha.76 (Bleeding Edge)

**Comment by nex3** [comment]
@chriseppstein We aren't currently parsing `@-moz-document`; this is hitting the directive fallback code.

I think we should actually support the `@-moz-document` syntax, as we do for `::-moz-any` and other vendor-specific syntaxes.

**Comment by chriseppstein** [comment]
@nex3 I thought we didn't parse unknown directives and just consumed everything to the first `;` or `{` as a string.

**Comment by nex3** [comment]
@chriseppstein That heuristic would fail when encountering quoted strings or other grammar edge cases. The fallback behavior for an unknown directive is to try to parse the tokens after it as a selector or, failing that, as an expression.

**Comment by nex3** [comment]
For the record, Mozilla's parsing of this is non-standard... it's [supposed to](http://www.w3.org/TR/css3-conditional/#url-prefix) require quotes within `url-prefix`. I'll still support it, of course.
