### ISSUE TITLE
Drop support for trailing combinators in weird places

### ISSUE THREAD

**Issue by nex3** [sass/sass#2901]
Currently, Sass is *very* liberal when it comes to allowing trailing combinators (such as the `>` in `a >`). These combinators are useful in some situations, particularly when resolving nesting, but they can also lead to invalid CSS and semantic nonsense with `@extend`. I think we should simplify this by deprecating, and then eventually throwing errors for, the following situations:

* Trailing combinators in selector pseudo classes. This means that `:has(a >)`, for example, would be an error.

* Trailing combinators in extenders (but not necessarily extendees). This means that `a > {@extend b}` and `selector.extend("a >", "b", "b")` would be errors.

* Trailing combinators in *post-nesting* style rules. This means that `a > {x: y}` would be an error, but `a > {b {x: y}}` would still be valid.

All of these have no clear use-case and generally produce invalid CSS, so hopefully deprecating them won't cause much trouble for users, and should eventually simplify the logic for `@extend` and reduce the possibility for users to accidentally generate invalid CSS.

See https://github.com/sass/dart-sass/issues/1053 for an example of how the complexity of the existing behavior has caused bugs even in Dart Sass.

**Comment by nex3** [comment]
Another example to add: the parser should forbid multiple combinators in a row, as in `a > > b`.

**Comment by stof** [comment]
I recently looked in detail at the implementation of the selector parsing and selector unification in dart-sass (to port it to scssphp to have a spec compliant logic), and I was quite surprised to discover the support for multiple combinators and trailing combinators, and the code complexity related to (partially) handle them.
So I think this deprecation makes sense (and I don't see any reason why existing projects would rely on them given they don't produce valid CSS anyway)

**Comment by nex3** [comment]
Feel free to write up a proposal!

**Comment by nex3** [comment]
Closing this out in favor of https://github.com/sass/sass/issues/3340, which covers doubled combinators as well.
