### ISSUE TITLE
Improve error message when using webkit `~` package imports with ~ in path-namespace

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#2906]
Using a package import with only one URL fragment, Sass will try to create a namespace of the same name – but `~` is not valid in a namespace identifier. The result is an error:

```scss
@use '~cascading-color-systems';
```
```
Error: Invalid Sass identifier
```

This can be solved by adding a URL fragment, or providing an explicit namespace:

```scss
@use '~cascading-color-systems/index';
```
```scss
@use '~cascading-color-systems' as ccs;
```

The error message should be improved to provide more help in resolving the issue.

**Comment by Mereo4** [comment]
Omg, yes, I completely agree on this request. I ran into the same issue with "~normalize.css" and thought it was because of some limitation of "@use" with css files. I wasted a lot of time to find an actual clue about the real problem.
