### ISSUE TITLE
Using ampersand (&) to select only the provided parent string and not the whole concatenated parent

### ISSUE THREAD

**Issue by aleksander351** [sass/sass#2909]
My SCSS:
```
.block {
    margin: 2px;

    & &__element {
        margin: 3px;
              
        &-nested {
            margin: 4px;
        }
    }
}
```

The desired output:
```
.block {
  margin: 2px;
}

.block .block__element {
  margin: 3px;
}

.block .block__element .block__element-nested {
  margin: 4px;
}
```

Obviously, the & selector copies the whole parent when applying to a child. But could there be a way to combine the child name with only the provided direct parent?

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
