### ISSUE TITLE
What kind of final CSS output - simple or complex selectors?

### ISSUE THREAD

**Issue by pindiespace** [sass/sass#291]
Hi, I'm researching issues of efficiency and performance optimization on the web, and was struct by the compiler-like nature of SASS. In turn, it made me think of the code output for an Intel desktop by a C++ compiler, versus RISC output destined for low-power mobile devices. If I understand RISC correctly, the instuction set is simpler, so the code output is simpler. This leads to big energy savings on RISC processors (which is why they're 95% of the mobile market).

My question is: Does SASS and equivalent CSS 'compilers' aim for a level of final code complexity. In other words, do they try to burn everything down to the simplest possible CSS selectors, or generated more complex ones? Thanks in advance

**Comment by nex3** [comment]
The compilation of Sass to CSS is very different than the compilation of C++ to machine code. C++ is at a much higher level of abstraction than machine code; there are many ways that a given snippet of C++ could be compiled that would all run correctly, and a C++ programmer doesn't have to think about the underlying machine code at all.

Sass, on the other hand, is relatively close to CSS. It adds a number of abstractions on top, but the user ultimately needs to understand CSS, and much of writing Sass is just writing CSS. This gives Sass much less flexibility in the CSS it emits. The selectors it creates are exactly those which have been specified by the user.

**Comment by pindiespace** [comment]
Thanks for the comment! The reason I'm interested is that optimization guidelines like the Yahoo! Exceptional Performance group recommend making CSS selectors short. So, I was wondering if there was a way to take a complex selector and pseudo-compile it to a set of simpler ones.

**Comment by nex3** [comment]
I don't believe there's a way to do so without affecting the semantics of the CSS, unless the compiler has a very thorough knowledge of the structure of the document being styled.

**Comment by pindiespace** [comment]
I was thinking of something like

div .someclass

If the compiler scanned the markup, and found that .someclass ALWAYS appeared in the div, then the div isn't needed, and in fact slows things down. This does assume that someone doesn't put .someclass where it doesn't belong later. But the logic is that div .someclass is inefficient - the coding should have been just .someclass

**Comment by nex3** [comment]
The part you're missing is that the compiler _can't_ scan the markup. Sass operates completely independently of the HTML rendering.

**Comment by pindiespace** [comment]
got it now, thanks
