### ISSUE TITLE
Namespaces with dots only instead of dots and dashes?

### ISSUE THREAD

**Issue by mangelozzi** [sass/sass#2911]
When one `@use`'s a module, it gets placed in a namespace, thanks one honking great idea, well done team!!

However in the situation where `c` imports `b`, and `b` imports `a`, in `c` one would think you could write something like `a.b.$useful-variable`. I.e. nested namespaces separated by dots.

After [research](http://www.sass-lang.com/documentation/at-rules/forward#adding-a-prefix) I see there are prefixes, so we could have:
`a.$b-useful variable`.
I tried using the above techniques but instead of importing as `-b`, to import as `.b`:
```scss
@forward "b" as b.*;
```
 but it gives an error: `Error: expected "*".`

Is there a way to namespace all the way down with dots, as opposed to 1 layer deep with a dot, and the rest with dashes?

**Comment by Awjin** [comment]
We can't allow dots in namespaces, because the module resolution logic hinges on the semantics of `.`. Arbitrary `.`s would defeat this system.

**Comment by mangelozzi** [comment]
> We can't allow dots in namespaces, because the module resolution logic hinges on the semantics of `.`. Arbitrary `.`s would defeat this system.

I was just showing a work around to try get namespaces to work with dots, the point is not to make namespaced allow dots in their names. The point is how does one support nested namespaces with dots? Is it possible without resorting prefixes then a dash?

**Comment by jathak** [comment]
Nested namespaces are not something that really makes sense within the Sass module system. The module system is explicitly designed to better encapsulate Sass members, so loading a file with `@use` only makes its members available in the current file, not to any files that later depend on the current file.

`@forward` does allow exposing the members of one module via another, but it doesn't create any nesting; it instead just includes the members of the module being forwarded as part of the API of the forwarding module.

**Comment by mangelozzi** [comment]
> Nested namespaces are not something that really makes sense within the Sass module system. The module system is explicitly designed to better encapsulate Sass members, so loading a file with `@use` only makes its members available in the current file, not to any files that later depend on the current file.
> 
> `@forward` does allow exposing the members of one module via another, but it doesn't create any nesting; it instead just includes the members of the module being forwarded as part of the API of the forwarding module.

I can see a scenario where it makes sense, and hence I asked the qestion. Say you have a `settings` module. And the settings module forwards `color` and `sizes`. Then one could `@use "settings"` and could do `settings.color.$myblue`, or `settings.sizes.$content-x`. Thats what names spaces are about.
At the moment one has to keep loading lot of small files in each file, e.g.:
```
@use "settings/color";
@use "settings/sizes";
@use "settings/config";
@use "settings/debug";
@use "scheme/color" as something other than `color`;
```
Im summary one has the choice to either:
1. Include many smaller modules, or
2. Pile them into one huge module, or
3. Use the half dash and half dots namespacing.
