### ISSUE TITLE
Nested namespaces with dots

### ISSUE THREAD

**Issue by mangelozzi** [sass/sass#2912]
When one `@use`'s a module, it gets placed in a namespace, thanks one honking great idea, well done team!!

However in the situation where `c` imports `b`, and `b` imports `a`, in `c` one would think you could write something like `a.b.$my-variable`. I.e. nested namespaces separated by dots.

After [research](http://www.sass-lang.com/documentation/at-rules/forward#adding-a-prefix) I see there are prefixes, so we could have: `a.$b-my-variable`, which is not ideal to be to have a broken pattern in the namespaces.

Is there a way to namespace all the way down with dots?

**Comment by jathak** [comment]
Duplicate of #2911.
