### ISSUE TITLE
Can't @use a namedspaced %placeholder

### ISSUE THREAD

**Issue by mangelozzi** [sass/sass#2913]
For example:
```
@use "placeholders";

.foo {
        @extend placeholders.%input;
}
```
Gives `Error: Expected identifier.`

I searched around a bit and found #1094. Is this feature not supported yet? As recommended by the documentation I am changin from libsass to dart-sass and to using @use, but this seems to be a blocker.

**Comment by mirisuzanne** [comment]
Placeholder selectors are not considered "members" of a module, and are not namespaced during import. Your code should work without the prefix:

```scss
@use "placeholders";

.foo {
        @extend %input;
}
```

**Comment by ChazUK** [comment]
I feel like this is a bit counter intuitive to not have it as a member of a module. With sass-loader I'm getting an error when trying to use @use and @extend %placeholder

```
@use 'font-faces';

%heading-XL {
  @extend %bold;
}
```

```
SassError: The target selector was not found.
Use "@extend %bold !optional" to avoid this error.
```
