### ISSUE TITLE
Enhancement Request: Why SASS syntax doesn't accept block in @use...with()?

### ISSUE THREAD

**Issue by ngdangtu-vn** [sass/sass#2919]
In SCSS syntax, we can do this:
```SCSS
@use 'library' with (
  $black: #222,
  $border-radius: 0.1rem
);
```

But we cannot do that in SASS. It has to be like this:
```SASS
@use 'library' with ($black: #222, $border-radius: 0.1rem)
```

I don't get it why `with` in SASS cannot be used as a block? In simple case where only a few short-name variables, this is acceptable. But if we have long-name variables, no matter how we look at it, it is a pain. SASS syntax is really clean, but the `@use ... with()` kills its pride. I believe it's necessary to find away to make this happens.

**Comment by Awjin** [comment]
Since the indented syntax uses whitespace semantically, this is not currently possible. Support for multi-line expressions is being tracked here: https://github.com/sass/sass/issues/216.
