### ISSUE TITLE
Namespaced selectors

### ISSUE THREAD

**Issue by fxdave** [sass/sass#2923]
When I @use "something". I don't want anything from that module in the final CSS. That's my job to reexport everything that I need. That's why I don't @import it. 

Let's see an example of what I want:

```scss
// header.scss
@use 'bootstrap';

.header {
   &__button {
         @extend bootsrap.btn, bootsrap.btn-primary;
   }
}
```
```jsx
// Header.js
import React from 'react'
import './header.scss'

export default () => <div className="header">
    <a className="header__button" href="/">Home</a>
</div>
```

Instead of one global CSS file, I would break it down into components.
Should every single component on the site that is possible lazy-loaded contain the whole bootstrap CSS framework? - I don't think so. I just want a tiny portion for a tiny component.

How to solve it?

**Comment by fxdave** [comment]
To represent its importance:
It's just 6 components that uses bootstrap:
![image](https://user-images.githubusercontent.com/12275699/95925130-4f91d400-0db9-11eb-823d-f1c933b21a7f.png)

**Comment by cpoftea** [comment]
First of all, Bootstrap isn't adopted to Sass modules for now. Just for notice.

`@use` is meant to compile a whole module. Also, as you may know, most bundlers handles non-js assets as standalone files. So every time you import sass files, which uses Bootstrap as `@use` module or simple `@import` in it, it will result to, as you can see, whole Bootstrap being compiled in every your asset.

And maybe here cannot be a good solution for your use case (Bootstrap + separated component styles extending some Bootstrap selectors + lazy loading). Need to think 🤔

**Comment by cpoftea** [comment]
Dirty solution, but still.
For performance purposes, create single entry scss style.
Then import Bootstrap and every your component in it.
Compile.
Then extract every component classes via postcss plugin to their component directory.
And only then import them as assets in your js.
One of a hell 💩

And you can do this only for production builds. For development you can import that root scss style, again, for performance purposes.

You will end up with something like this in your js
```js
const style = require(dev ? '{project root}/scss/style.scss' : './component.css')
```

**Comment by jathak** [comment]
Namespaced selectors aren't really something that we can support given how broad the syntax for selectors already is. Selectors like `bootstrap.btn` are already valid CSS, so we can't use the same namespace-dot syntax we use for Sass members.

If a library wants to enable its users to depend on only certain parts of their styles, they should use mixins and/or have multiple entrypoints that expose different styles. We try to avoid features that allow upstream stylesheets to be used in a way their author didn't intend them to be used. Those patterns tend to produce brittle dependencies that are likely to break when the upstream stylesheets change in unexpected ways.
