### ISSUE TITLE
Missing Awesome Future (Modifying a Map or List)

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2929]
Hi
I need a way to modify **Maps**/**Lists** without losing their data.
**It's an awesome idea and I really need this.
I'm waiting for your feedback.**
```scss

// map created
$map1: (
  key-1: value-1
);

// map modified
$map1: modify (
  key-2: value-2
);

// map1 result
// (
//   key-1: value-1,
//   key-2: value-2
// );


// map created
$map2: (
  hello-key: (
    key-1: value-1
  )
);

// map modified
$map2: modify (
  hello-key: (
    key-2: value-2
    key-3: value-3
  )
);

// map2 result
// (
//   hello-key: (
//     key-1: value-1,
//     key-2: value-2
//     key-3: value-3
//   )
// );


// Lists

// created
$list: 1 2;

// modified
$list: modify 3 4 5;

// result
// 1 2 3 4 5

```

**Comment by cpoftea** [comment]
It is already here.
[map.merge](https://sass-lang.com/documentation/modules/map#merge)
```scss
@use "sass:map";

$map1: (
  key-1: value-1
);

$map1: map.merge($map1, (
  key-2: value-2
));

@debug $map1;
// (
//   key-1: value-1,
//   key-2: value-2
// )
```
[map.deep-merge](https://sass-lang.com/documentation/modules/map#deep-merge)
```scss
@use "sass:map";

$map2: (
  hello-key: (
    key-1: value-1
  )
);

$map2: map.deep-merge($map2, (
  hello-key: (
    key-2: value-2
    key-3: value-3
  )
));

@debug $map2;
// (
//   hello-key: (
//     key-1: value-1,
//     key-2: value-2,
//     key-3: value-3
//   )
// )
```
[list.join](https://sass-lang.com/documentation/modules/list#join)
```scss
@use "sass:list";

$list: 1 2;
$list: list.join($list, 3 4 5);

@debug $list; // 1 2 3 4 5
```
You can find more at [list](https://sass-lang.com/documentation/modules/list) and [map](https://sass-lang.com/documentation/modules/map) modules docs

**Comment by babakfp** [comment]
Hi.
Error: two arguments allowed but three are passed. (for simple map)
Error: undefined function. (for deep map)
It does not even work with Prepros. Yes, I send an email to Prepros support to figure it out that what is the problem.

In short, we need a programming language for CSS. What if there was a programming lang similar to Javascript with SASS powers? This is what we need.

Do you know about Tailwind? Tailwind is not good enuff because it's not with sass. sass is not good enuff because it's not with Javascript, (it's not a programming language). CSS is horrible and You can't beat a demon with a water gun.

What I'm trying to build is something like Tailwind. unfortunately, it's not possible because I don't have a powerful gun...

Did I explain it well?

**Comment by babakfp** [comment]
> It is already here.
> [map.merge](https://sass-lang.com/documentation/modules/map#merge)
> 
> ```css-scss
> @use "sass:map";
> 
> $map1: (
>   key-1: value-1
> );
> 
> $map1: map.merge($map1, (
>   key-2: value-2
> ));
> 
> @debug $map1;
> // (
> //   key-1: value-1,
> //   key-2: value-2
> // )
> ```
> 
> [map.deep-merge](https://sass-lang.com/documentation/modules/map#deep-merge)
> 
> ```css-scss
> @use "sass:map";
> 
> $map2: (
>   hello-key: (
>     key-1: value-1
>   )
> );
> 
> $map2: map.deep-merge($map2, (
>   hello-key: (
>     key-2: value-2
>     key-3: value-3
>   )
> ));
> 
> @debug $map2;
> // (
> //   hello-key: (
> //     key-1: value-1,
> //     key-2: value-2,
> //     key-3: value-3
> //   )
> // )
> ```
> 
> [list.join](https://sass-lang.com/documentation/modules/list#join)
> 
> ```css-scss
> @use "sass:list";
> 
> $list: 1 2;
> $list: list.join($list, 3 4 5);
> 
> @debug $list; // 1 2 3 4 5
> ```
> 
> You can find more at [list](https://sass-lang.com/documentation/modules/list) and [map](https://sass-lang.com/documentation/modules/map) modules docs

Hi.
Error: two arguments allowed but three are passed. (for simple map)
Error: undefined function. (for deep map)
It does not even work with Prepros. Yes, I send an email to Prepros support to figure it out that what is the problem.

In short, we need a programming language for CSS. What if there was a programming lang similar to Javascript with SASS powers? This is what we need.

Do you know about Tailwind? Tailwind is not good enuff because it's not with sass. sass is not good enuff because it's not with Javascript, (it's not a programming language). CSS is horrible and You can't beat a demon with a water gun.

What I'm trying to build is something like Tailwind. unfortunately, it's not possible because I don't have a powerful gun...

Did I explain it well?

**Comment by Awjin** [comment]
@cpof-tea is correct—the built-in map functions are the best way to achieve this behavior. To use them, you must have the latest version of Dart Sass ([1.27.0](https://github.com/sass/dart-sass/releases/tag/1.27.0)).
