### ISSUE TITLE
Invalid css calc() ouptut for zero variables inside calc arguments

### ISSUE THREAD

**Issue by anton-marchenko** [sass/sass#2934]
Version:
sass npm package 1.28.0 compiled with dart2js 2.10.3

Steps to reproduce:
1. create test.scss with next styles:

```
$v1: 12em;
$v2: 5px;
$v3: 0;

.test {
    height: calc( #{$v1} + #{$v2} + #{$v3} );
}
```
2. run `sass test.scss`
3. see output:
```
.test {
  height: calc( 12em + 5px + 0 );
}
```

It is invalid height property value that we can see in Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/45929621/97676284-77fc1c80-1aa1-11eb-9e25-b35a9812d32e.png)

*Expected output* (that we can see in node-sass library, for example):

```
.k-grid-content tr {
  height: calc( 12em + 10px );
}
```

**Comment by jathak** [comment]
Dart Sass's behavior here is correct. Sass doesn't do any sort of simplification on `calc` functions, so the invalid parameter gets passed through.

We do eventually plan to support a first-class `calc` function in Sass (see #2186), which might allow this kind of simplification, but for now Sass avoids making assumptions about what inputs `calc` accepts.
