### ISSUE TITLE
Clarification around SASS_PATH: spec vs implementation details

### ISSUE THREAD

**Issue by stof** [sass/sass#2939]
The [documentation about finding files for imports](https://sass-lang.com/documentation/at-rules/import#finding-the-file) describes the concept of load paths. Running specs from sass-spec requires that load paths are supported as it relies on a `-I` argument to specify the root of the `spec/` folder as load path which is used.
Official implementations also support `SASS_PATH` as a way to configure additional load paths (libsass does not actually support it. But the sassc wrapper does). But there is nothing in sass-spec enforcing that `SASS_PATH` is supported.

Is `SASS_PATH` considered an implementation detail or is it expected to be supported by all implementations ?

I'm asking that as one of the maintainers of scssphp (a PHP implementation of the scss syntax which is used in several PHP CMS plugins to be able to compile admin-provided scss files even on shared hosting where running a sass binary is not an option). The new maintenance team is working on modernizing the codebase and increasing spec compliance. And I found out that we currently don't implement support for `SASS_PATH` (listed as https://github.com/scssphp/scssphp/issues/249).

**Comment by nex3** [comment]
I'd say that the way load paths are configured is an aspect of the CLI and API, and as such outside of the scope of the language spec. If you want to have a high degree of compatibility with the way other Sass languages run, then feel free to support load paths specified in `SASS_PATHS` with a lower precedence than explicit load paths, but don't feel bound by that.
