### ISSUE TITLE
Interpolation fails when using margin shorthand

### ISSUE THREAD

**Issue by jenshedqvist** [sass/sass#294]
This SCSS:

`margin: -#{$module_padding + 1} -#{$module_padding + 1} 0 -#{$module_padding + 1};`

Outputs to:

`margin: -15px-15px 0-15px;`

It does the same thing with positive margins.

I'm using Win 7 64 bit and Sublime Text as editor. Compass as compiler (adding an issue there as well).

**Comment by mikefowler** [comment]
I can't speak to the stable release, but this appears to be fixed on the alpha version I'm on (alpha.76) when compiling with either Sass or Compass.

**Comment by jenshedqvist** [comment]
Man, I was sure I was running the latest Compass and SASS. Updated it and now it works. I'll give you a holler if it turns on me but for now this issue is closed.
