### ISSUE TITLE
Clarification on partializing partial imports

### ISSUE THREAD

**Issue by stof** [sass/sass#2940]
```scss
@import "_partial";
```

In dart-sass, this will try to import `__partial.scss` and then `_partial.scss`, i.e. the `_` prefix is always tried even if it is already there. I haven't checked the behavior of the older libsass and ruby-sass implementations to know whether they were also doing it.

This behavior is not covered in sass-spec, probably because the best practice is to omit the `_` when importing partials. I'd like to know whether that's the expected behavior (which is indeed simple to implement) or whether `_` should be added only if not already there.

**Comment by stof** [comment]
This came up when reworking the implementation of imports in scssphp. My new implementation matches the one from dart-sass, but our old implementation was adding `_` only if not there.

**Comment by nex3** [comment]
Dart Sass's behavior matches Ruby Sass's, so it's probably best to consider it the spec behavior. If I had the choice to make over again I'd probably avoid looking for `__partial.scss`, but I don't think changing it now is worth the potential backwards-compatibility headaches.

**Comment by stof** [comment]
OK, then we'll merge our new implementation in scssphp which also follows that behavior.
