### ISSUE TITLE
Enabled breakpoint only if map field has specific value?

### ISSUE THREAD

**Issue by devhoussam** [sass/sass#2945]
I want to know how can I Enabled media breakpoint only if map $tests in key example in state has a specific value called responsive.

Note : state field it contain other values but the media breakpoints shows only if responsive is exist inside state.

```
$breakpoints: (
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1400px
) !default;

$tests: () !default;
$tests: map-merge(
  (
    "example": (
        state: (responsive, a, b, c),
    ),
  ),
  $tests
);

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    @each $key, $test in $tests {
      @if type-of($test) == "map" and (map-get($test, state)) {
        @include testing($test);
      }
    }
  }
}
```

**Comment by Awjin** [comment]
I'm having trouble understanding your question. What is the behavior that you want here? Could you provide an explanation of your problem?

If you need to check if an item exists in a list, you can use [`list.index()`](https://sass-lang.com/documentation/modules/list#index).

**Comment by devhoussam** [comment]
Here is my [Question in stackoverflow](https://stackoverflow.com/questions/64772672/merge-two-maps-summing-values-for-same-keys-in-sass)

**Comment by Awjin** [comment]
Sorry, I still don't understand your question. Please make your code example as **small** as possible, so that it only shows the behavior you are asking about.

**Comment by devhoussam** [comment]
I solve the problem thank you
