### ISSUE TITLE
Add degenerate numeric constants to math module

### ISSUE THREAD

**Issue by Awjin** [sass/sass#2954]
The CSS Values and Units Level 4 Working Draft has landed math functions, in which they added constants for [`infinity`, `-infinity`, and `NaN`](https://www.w3.org/TR/css-values-4/#calc-error-constants).

We should add these variables to `sass:math`. This will allow Sass to have a valid plain-CSS representation of them if they come out of Sass functions. (e.g. `calc(infinity)`).

**Comment by stof** [comment]
Sass already supports those in SassScript. What would be needed would be to allow serializing them to CSS instead of making it an error.

**Comment by roydukkey** [comment]
Additionally, I could see use cases for this purely in Sass. An example is for my [sass-module-list](https://github.com/roydukkey/sass-module-list), which has implemented many functions similar to the JavaScript array functions.

For [`Array.prototype.flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) the `depth` parameter accepts a number. A depth of `Infinity` makes sense when you don't know the depth.

```js
const arr = [0, 1, 2, [[[3, 4]]]];

console.log(arr.flat(Infinity));
// expected output: [0, 1, 2, 3, 4]
```

I have implemented this is Sass, and would like to accept `infinity` once available.

**[src/list/_flat.sass](https://github.com/roydukkey/sass-module-list/blob/6025a1bf499c50115537509f7017fa755b8cd2b1/src/list/_flat.sass)**
```sass
@use 'sass:list'
@use 'sass:meta'
@use '../internal'

@function flat($list, $depth: 1, $separator: list.separator($list))
	internal.$exception-function: 'flat'

	@if meta.type-of($depth) != 'number'
		@error internal.exception-type('depth', $depth, 'number')

	@if $depth < 1
		@error internal.exception-param('The depth may not be less than 1', 'depth')

	@if internal.param-separator-is-invalid($separator)
		@error internal.exception-separator()

	@return _flat($list, $depth, $separator, 1)

@function _flat($list, $depth, $separator, $at-depth)
	$result: internal.init($list)

	@each $item in $list

		@if list.length($item) > 1 and $at-depth <= $depth
			$sub-list: _flat($item, $depth, $separator, $at-depth + 1)

			@each $sub-item in $sub-list
				$result: list.append($result, $sub-item, $separator)

		@else
			$result: list.append($result, $item, $separator)

	@return $result
```

**Comment by stof** [comment]
Note that the CSS spec seems to support the `infinity` and `nan` constants only in calculations, thanks to the new `<calc-constant>` production (which also supports `e` and `pi` btw)
