### ISSUE TITLE
SASS/SCSS enabled comma (,) between list items?

### ISSUE THREAD

**Issue by devhoussam** [sass/sass#2955]
I want to know How can I enabled comma (,) between list items in SASS/SCSS?

I made this simple mixin but in testing I got an error message :

_"only 2 arguments allowed, but 4 were passed"???_

**Here is my code :**

```
@mixin names($values: ()) {
    @each $var in $values {
	   content: "#{$var}";
	}
}

.test {
    @include names('jhon', 'oliver', 'max');
}
```

I know I can't remove the comma (,) between list items and it will work but 
the concept I want to know How can get the same result with comma (,).

**Comment by Awjin** [comment]
Sass allows passing arbitrary arguments. Here is the documentation: https://sass-lang.com/documentation/at-rules/mixin#taking-arbitrary-keyword-arguments.

```scss
@mixin names($values...) {}

.test {
  @include names('jhon', 'oliver', 'max');
}
```
