### ISSUE TITLE
use Hex and RGB Color in same $color map?

### ISSUE THREAD

**Issue by devhoussam** [sass/sass#2957]
I have an Idea to create something different using SCSS What I want to achieve is very simple.

use two different color types HEX and RGB in same map key.

and Using it If I want to create a css color class with proprety contain RGB value it will be possible and same thing for Hex Color.

**My Full Code :** 

```
@function hexToRGB($hex) {
  @return red($hex), green($hex), blue($hex);
}

$red-50:  #FEF6F5         !default;

$red: () !default;
$red: map-merge(
    (
        "red-50": hexToRGB($red-50),
    ),
    $red
);

$colors: () !default;
$colors: map-merge(
    (
        "red":       $red,
    ),
    $colors
);

@each $name, $value in $colors {
    @each $shade, $color in $value {
        .color-#{$shade} {
            /** RGB Color **/
            --color-example1: rgba(#{$color}, 1);
            /** Hex Color **/
            --color-example2: #{$color};
        }
    }
}
```

**The Result that I want to get after compiling to CSS :**

```
.color-red-50 {
  /** RGB Color **/
  --color-example1: rgba(254, 246, 245, 1);
  /** Hex Color **/
  --color-example2: #FEF6F5;
}
```

What I want from these examples is to use different color types (Hex and RGB) and use them on the same map $colors key.

**Comment by Awjin** [comment]
Could you provide a minimal example, using only code that is relevant to your issue?

**Comment by zaydek** [comment]
@devhoussam Take a look at this, I think you will find what you need: https://github.com/zaydek/duomo/blob/7bc0e6c978e2d67d8725dbb417c992d303e24782/src/duomo/helpers/generators.scss#L45.

Basically use can use `color.red($v)`, etc. to extract a color component and then write `color` twice; one as hex and one as `rgba`.

**Comment by devhoussam** [comment]
> @devhoussam Take a look at this, I think you will find what you need: https://github.com/zaydek/duomo/blob/7bc0e6c978e2d67d8725dbb417c992d303e24782/src/duomo/helpers/generators.scss#L45.
> 
> Basically use can use `color.red($v)`, etc. to extract a color component and then write `color` twice; one as hex and one as `rgba`.

thank you so mush for your help
