### ISSUE TITLE
Add min, max, and avg functions

### ISSUE THREAD

**Issue by richthegeek** [sass/sass#296]
I occasionally come across cases where i need to get the maximum of two variables. Whilst it can be solved by defining an in-Sass function like so:

``` scss
@function max($a, $b) {
  @return if($a > $b, $a, $b);
}
```

This solution works, but it's a bit of a pain to define it when I need to use it for each project. It could be included in Compass, ofcourse, but it seems sort-of the wrong place for it.

If max is included, then it would be odd for min not to be included, and it's implementation is similarly trivial.

I can't think of a usecase for avg at the moment, however I think in the broader scope of increasing math-support for SASS it'd be an obvious inclusion.

**Comment by richthegeek** [comment]
These functions could also handle lists

``` scss
$list: 12, 30, 4;
min($list) => 4
```

**Comment by nex3** [comment]
I didn't add support for `min($list)` because presumably it will fall out naturally from #138.

I also didn't add `avg()` since I doubt it'd be widely useful.

**Comment by richthegeek** [comment]
Wonderful, so min and max are sorted, and they care for unit conversion where possible.

I agree with the choice on avg() - I can't see a use for it at the moment.

Anyway, thanks!
