### ISSUE TITLE
How to fix an Undefined Variable Error in SCSS? @use (error) | @import (works)

### ISSUE THREAD

**Issue by AToal** [sass/sass#2960]
I've run into an Undefined Variable Error writing SCSS. My file structure is sound, because it compiles the rest of the files as it should into main.scss, and I've made sure that variables are at the top of my files being compiled.

I started out using @use, and I get "Error: Undefined variable." I then switched all @use to @import, and it worked.

I'd like to be able to @use instead of @import, so please help me get @use working right.

**Comment by babakfp** [comment]
[SASS Documentation](https://sass-lang.com/documentation/at-rules/use)
This is not the right place to ask these kinda questions.
My advice is, don't touch your current project. Try to use the `@use` rule in your new projects.

**Comment by Awjin** [comment]
@atoal It's hard to diagnose your problem without an example of the code that is breaking. Are you referencing the variable with a proper namespace?
