### ISSUE TITLE
Override

### ISSUE THREAD

**Issue by artola** [sass/sass#2962]
Is supported some kind of rule override?
In some trivial cases using the `shame` file is enough, for example: `.foo {color: red}` later on `.foo {color: green}`.
But I have code imported from a package that contains `.foo {left: auto !important}` and I could just override using `!important` again, but in my case it is not possible because we need to remove totally the rule, to get the value from some inline style. I could just hack around with:

https://gist.github.com/artola/589f408a7a49343c2abdd850102efca5

Later on when the code in minified, the hack remains but it is invalid css, therefore like never defined.

**Comment by jathak** [comment]
This doesn't seem to have anything to do with Sass specifically, but is instead a result of the [CSS cascade](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#Cascading_order). `!important` generally isn't something that can be overridden in CSS.

**Comment by artola** [comment]
@jathak is it possible with some helper to override the whole rule?

**Comment by jathak** [comment]
Not within Sass itself. We don't like to add features that allow you to change third-party Sass libraries in ways that aren't explicitly allowed by the library authors (e.g. via mixins or configurable variables), as it makes it difficult for them to make changes without unintentionally breaking downstream users.

You could try writing a PostCSS plugin to remove the undesired `!important` though.
