### ISSUE TITLE
How to set different output folders for different projects using SAAS at a time in code editor

### ISSUE THREAD

**Issue by ashehzadgec** [sass/sass#2965]
Hi there

Is it possible to have different output folders for different projects at the same time.
For instance, I am working on 2 projects with SAAS at a time. But right now, I am able to set output directory for one project. How I can set the output directory for 2nd project without effecting the output folder for 1st project. So that whenever I switch between projects, I do not have to change the output for folder for CSS output for each project again and again. I hope I made it easy to understand. BTW I am using VS code editor.

Regards,
Shehzad Asif

**Comment by jathak** [comment]
This seems like a feature request for your editor's Sass extension, not Sass itself.

**Comment by ashehzadgec** [comment]
Hi Jennfier

Yes, you are right, Thanks for correcting it. I should have posted the
question to their forum.
