### ISSUE TITLE
Is it possible to set variable with media queries in SAAS

### ISSUE THREAD

**Issue by ashehzadgec** [sass/sass#2968]
Hi there

I am just thinking about is there any way to set variables within media queries in SAAS.
Currently I am doing in the following way:

$h1
$h1-tab
$h1-mob

Desired way

@media 980px{
$h1-tab
}

Regards,
Shehzad Asif

**Comment by Awjin** [comment]
You can achieve this by using [global scope](https://sass-lang.com/documentation/variables#scope).

```scss
$h1: 1px;

@media (980px) {
  $h1: 2px !global;
}

@debug $h1; //=> 2px
```

**Comment by ashehzadgec** [comment]
Hi Awjin

Thanks for the solution. But can you explain why you used the following
code and is it necessary?

@debug $h1; //=> 2px

**Comment by Awjin** [comment]
The `@debug` is just there to print the value of `$h1`, so you can verify that it's the correct value. You don't need to put it in your final code.
