### ISSUE TITLE
Please remove black lives matter banner

### ISSUE THREAD

**Issue by barsan-md** [sass/sass#2971]
Before starting I am aware that this has been answered already here: https://github.com/sass/sass-site/issues/461

However, I am not satisfied with the answer. Beyond being somhow a generic declaration of support for human rights, it doesn't justify at all why there should be such a strong claim on a technical website. There is no descrimination in internet communities like this, most of people are just nicknames, we don't always know nor does it matter who the person is, there's no need to take political positions. Also me and the other op. are technically NOT engaging in any political action, just asking YOU to not do so. It is annoying to access sass website and being asked with a huge banner to join in streets when I was interested only to check some syntax rules. This is not to say that I am insensitive to point at issue, I'm saying that we have to separate the concerns.

Also there is a second, more important reason. The person who answered, from USA, has (like most of the USA citizen out there) a self centered vision of the world. Maybe you didn't know but there are other countries in the world. Me, in particular, I'm writing from Italy. We don't have all the issues with the police that you have. You (intended as USA citizen) should not project you problems on the rest of the world. Issues like those of police violence in the USA should be discussed and solved in contexts where the USA citizend are involved. A website that should offer technical documentation is not that place.

**Comment by nex3** [comment]
Black lives matter, and that's all there is left to say on the matter.
