### ISSUE TITLE
Defaulting to a variable with !default

### ISSUE THREAD

**Issue by idofilus** [sass/sass#2972]
I have a library project with variables:

```
$background-color: white !default;
$dialog-background-color: $background-color !default;
```

And in the project using it I can override e.g. the background color:
```
$background-color: tomato;
```

But, the `$dialog-background-color` stays white, is there any way for SASS to dynamically "re-assign" the default value to be the new `$background-color` ?

**Comment by babakfp** [comment]
```SCSS
$background-color: black;

$background-color: white !default;
$dialog-background-color: $background-color !default;

// [1]

@debug "$background-color"$background-color; // black | [1]: gray
@debug "$dialog-background-color"$dialog-background-color; // black | [1]: black

// what if you add the code in [1]:
$background-color: gray;

```

- Maybe you are using an old version of dart-sass (or other...).
- Maybe you are using it in the wrong order.

Test my code in a blank separate file, to see if the problem is because of your project or because of the version

```
sass --version // 1.27.0 compiled with dart2js 2.10.1
```

**Comment by jathak** [comment]
Sass variables are imperative, so they won't update in that way. Provided you don't need your variables at Sass compile time, you may be able to use [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), which are declarative and resolved at CSS run time.
