### ISSUE TITLE
Comment before @else if in .sass

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2978]
Hello.
This code gives an error:
```SASS
$num: 1
@if $num == 1
// comment
@else if $num == 0

// Error: This at-rule is not allowed here.
// 4:1 | @else if $num == 0
```
I need to remove the comment to solve the error:
```SASS
@if $num == 1
@else if $num == 0
```
It will be nice if it solved. I remember the time that I want to switch to sass (from scss). In the end, I got some weird errors like this and after that, I hated the sass. Now I'm working with sass and I loved it. If this kinda stuff solved, I guess more people switch to sass because it's cleaner and fast. Also, I this because sass isn't popular as mush as scss, there is no fully highlighting support available (for vscode), so it's not 100% satisfying.
I'm not able to help with coding, so this is all I can do.

**Comment by Awjin** [comment]
Since the comment is part of the `if` statement, it needs to be indented.

```sass
$num: 1
@if $num == 1
  // comment
@else if $num == 0
```
