### ISSUE TITLE
Define a JS API for handling debug messages and warnings

### ISSUE THREAD

**Issue by nex3** [sass/sass#2979]
* [x] [Proposal](https://github.com/sass/sass/blob/main/proposal/js-logger.d.ts)
* [x] [Tests](https://github.com/sass/sass-spec/pull/1726)
* [x] [Documentation](https://github.com/sass/sass-site/pull/584)
* [x] [Dart Sass](https://github.com/sass/dart-sass/pull/1515)
* [ ] Node Host

---

The JS API is currently missing a means of handling messages generated by the `@debug` and `@warn` directives, as well as deprecation warnings generated by the implementation itself. Node Sass has the ability to provide a custom function named `@warn` that handles warnings, but this is neither documented nor supported by Dart Sass. Dart Sass has the ability to pass in subclasses of [`Logger`](https://pub.dev/documentation/sass/latest/sass/Logger-class.html) to handle these callbacks. We should come up with a similar `Logger`-style API for JS.

See https://github.com/sass/dart-sass/issues/585

**Comment by glenn2223** [comment]
Firstly, sorry if the below isn't what you expected. However, if you can point me in the right direction, I'm more than happy to help where I can (always looking to expand the skillsets).

---

I was thinking that, as these "at rules" don't actually stop compilation, any warning and debug messages should be returned with the `Result` of `render()` and `renderSync()`. However, I can redirect my thoughts to a Dart Sass Logger API if you wish 😄 

Further to my initial thought, the adjustments I was thinking were: (also included some quick defs examples)
- New interface that takes all functionality from `SassException`
- `SassException` will then extend `Error` and `SassProblem`
- `Result` has two new properties `warningMessages` and `debugMessages`

**New interface** - SassFlag or SassProblem (sorry, not important)
````ts
export interface SassFlag {
    message: string;
    formatted: string;
    line: number;
    column: number;
    status: number;
    file: string;
}
````

**SassException**
````ts
export interface SassException extends Error, SassFlag { }
````

**Result**
````ts
export interface Result {
    css: Buffer;
    map?: Buffer;
    stats: {
        entry: string;
        start: number;
        end: number;
        duration: number;
        includedFiles: string[];
    };
    warningMessages: SassFlag[];
    debugMessages: SassFlag[];
}
````

**Comment by glenn2223** [comment]
Alternate suggestion for a logger (as originally requested). Again, to prevent duplication of code I'd strip most of `SassException` and make it extend the new `SassFlag`

````ts
/*
 * MODS
 */
export interface Options {
// … Other properties removed for brevity

    logger?: Logger;
}

export interface SassException extends Error, SassFlag {
    status: number;
 }

/*
 * NEW
 */
export interface Logger {
    warning: (warning: SassFlag) => void;
    debug?: (debug: SassFlag) => void;
}

export interface SassFlag {
    message: string;
    formatted: string;
    line: number;
    column: number;
    file: string;
}
````
---
I'd then call it myself as such:
````ts
data.logger = {
    warning: (warning: SassFlag) => {
        // Output the message => OutputWindow.Show("Warning:", warning.formatted.split("\n"), showOutputWindow);
        // Show a popup => WindowPopout.Warn("Live Sass Compiler\n *Warning:* \n" + warning.formatted);
    },
    debug: (debug: SassFlag) => {
        // Output the message => OutputWindow.Show("Debug info:", debug.formatted.split("\n"), showOutputWindow);
    },
};
````

**Comment by nex3** [comment]
I think we need this to be a callback-based interface, because Sass compilation can take a fair amount of time and we want people to see diagnostics as they occur rather than only once the compilation is finished (which it may not if it ends up in an infinite loop or something like that). Also, providing callbacks serves as a signal to the compiler that it should stop printing messages to stderr, which may be important to the user.

If I understand correctly, your idea of a `SassFlag` interface is kind of a way of representing the source location of the messages the way [`SourceSpan`](https://pub.dev/documentation/source_span/latest/source_span/SourceSpan-class.html) does in Dart. It's unfortunate that there's not an existing standard interface for this in JS... the closest that exists in the CSS world is PostCSS's [`Source`](https://postcss.org/api/#source) type, although that's tightly coupled to PostCSS's `Input` type in a way that makes it difficult to use as a general interchange format.

You're right that we should have some sort of shared representation there, but I don't know that the current `SassException` interface is one we want to enshrine forever. It has a number of drawbacks, like not including the character offset of the error in the file and not including its end position so a consumer can't fully highlight it (in an editor for example). I'm not sure what the best solution for that is, though.

**Comment by glenn2223** [comment]
>I think we need this to be a callback-based interface, because Sass compilation can take a fair amount of time and we want people to see diagnostics as they occur rather than only once the compilation is finished (which it may not if it ends up in an infinite loop or something like that).

Good shout, logger with callback it is

>If I understand correctly, your idea of a SassFlag interface is kind of a way of representing the source location of the messages the way SourceSpan does in Dart. It's unfortunate that there's not an existing standard interface for this in JS... the closest that exists in the CSS world is PostCSS's Source type, although that's tightly coupled to PostCSS's Input type in a way that makes it difficult to use as a general interchange format.

Sorry, I always use Typescript. Forgot for a second that there's no interfaces in JS

>You're right that we should have some sort of shared representation there, but I don't know that the current SassException interface is one we want to enshrine forever. It has a number of drawbacks, like not including the character offset of the error in the file and not including its end position so a consumer can't fully highlight it (in an editor for example). I'm not sure what the best solution for that is, though.

So `column` should be a string formatted as `30-40` or, when applicable, just `30`. Which, when shown in the `formatted` property, can be `line:column` (e.g. `20:30-40`).
You could always possibly apply this to `SassException` in a major release.
What are the other drawbacks so we can make sure this new feature is the most versatile it can be 😄

**Comment by nex3** [comment]
Formatting the column as a string obligates users to parse it by hand. Dart Sass has information about the specific line, column, and character offset that the messages both begin and end on, and I'd like to make that available to the user. Essentially, I'd like to provide all the information that's available in the [`SourceSpan` type](https://github.com/sass/embedded-protocol/blob/00d84d6ae9cef32fd3a30f336e771cc981e3bcbf/embedded_sass.proto#L508-L552) from the embedded protocol.

**Comment by glenn2223** [comment]
Wow, `SourceSpan` is a solid nut. After seeing that I can really see the limitations of the current SassException.

So are we happy with a new optional property in `options` which has a callback for warning and debug (as below)?

````TS
interface Options {
  // Other properties removed for brevity
  logger?: Logger;
}

import { WriteStream } from "tty";
import { stderr, stdout } from "process";

export interface Logger {
    warn: (message: string, source: SourceSpan) => void;
    debug?: (message: string, source: SourceSpan) => void;
}

export interface SourceSpan {
    text: string;
    start: SourceLocation;
    end: SourceLocation;
    url: string;
    context: string;
}

export interface SourceLocation {
    offset: number;
    line: number;
    column: number;
}

export class StandardLogger implements Logger {
    warn(message: string, source: SourceSpan): void {
        stderr.write(
            [
                "Compilation Warning", 
                `Warning: ${message}`,
                "  ╷"
            ].join("\n")
        );

        this.process(stderr, source);
    }

    debug(message: string, source: SourceSpan): void {
        stdout.write(
            [
                "Compilation Debugger",
                `Debug: ${message}`,
                "  ╷"
            ].join("\n")
        );

        this.process(stdout, source);
    }

    private process(stream: WriteStream, source: SourceSpan): void {
        const writeArray: string[] = [];

        // NOTE: I take it `source.text` will have the required lines, however built below for modding (and just in case)
        // Left out file fetch for some brevity
        const exampleFile = ".abcdefg {\n    x: 1px;\n}";

        const file = exampleFile.split("\n", source.end.line);
        file.splice(0, source.start.line - 1).splice(source.end.line - source.start.line + 1);

        // get file and iterate over the lines
        for (var line = 0; line <= source.end.line - source.start.line; line++) {
            if (line > 0) {
                writeArray.push("\n");
            }

            writeArray.push(`${line + 1} | `);

            if (source.start.line === source.end.line) {
                writeArray.push(file[line].substring(0, source.start.column - 1));
                writeArray.push(`\x1b[4m${file[line].substring(source.start.column - 1, source.end.column - 1)}`);
                writeArray.push(`\x1b[0m${file[line].substring(source.end.column - 1)}`);
            } else if (line === 0) {
                writeArray.push(file[line].substring(0, source.start.column - 1));
                writeArray.push(`\x1b[4m${file[line].substring(source.start.column - 1)}`);
            } else if (line === source.end.line - source.start.line) {
                writeArray.push(file[line].substring(source.start.column - 1, source.end.column - 1));
                writeArray.push(`\x1b[0m${file[line].substring(source.end.column - 1)}`);
            } else {
                writeArray.push(file[line]);
            }
        }

        stream.write(writeArray.join(""));
        stream.write("  ╵");
        stream.write(
            `  ${source.url}:${source.start.line}:${source.start.column}-${source.end.line}:${source.end.column}`
        );
    }
}
````

### Example:
**Input**
````js
new StandardLogger().warn(
  "This is an example warning",
  {
    text: "....",
    start: {
      offset: 1,
      line: 1,
      column: 4,
    },
    end: {
      offset: 1,
      line: 2,
      column: 8,
    },
    url: "C:\\My Folder\\My File.scss",
    context: "...."
  }
);
````

**Output** (had to use [UNDERLINE] as it won't show in here)
````console
Compilation Warning
Warning: This is an example warning
  ╷
1 | .ab[UNDERLINE]cdefg {
2 |     x: [/UNDERLINE]1px;
  ╵
  C:\My Folder\My File.scss:1:4-2:8
````

Sorry, I feel like I might be more of a hindrance than a help. Is there anything I can do to actually help to keep this ball rolling?

**Comment by nex3** [comment]
That setup looks good! I think you can also reasonably avoid the complexity in `StandardLogger` by just having it be an opaque object that tells Sass to use its own internal (written in Dart) logic for highlighting the span.

**Comment by glenn2223** [comment]
> I think you can also reasonably avoid the complexity in `StandardLogger` by just having it be an opaque object that tells Sass to use its own internal (written in Dart) logic for highlighting the span.

I assumed that was already available in `SourceSpan.text`. However one should never assume, so I added some example logic above (just in case).

___

Would it be worth also giving an option like the below. This way a standard output is given to one or more `WriteStream`s. (Excuse the TS again)

````TS
export class StandardLogger implements Logger {
    private _warnStream: WriteStream;
    private _debugStream?: WriteStream;

    constructor(warnStream: WriteStream, debugStream?: WriteStream | true) {
        this._warnStream = warnStream;
        if (debugStream === true) {
            this._debugStream = warnStream;
        } else {
            this._debugStream = debugStream;
        }
    }

    warn(message: string, source: SourceSpan): void {
        this._warnStream.write(
            [
                "Compilation Warning", 
                `Warning: ${message}`,
                source.text
            ].join("\n")
        );
    }

    debug(message: string, source: SourceSpan): void {
        this._debugStream?.write(
            [
                "Compilation Debugger",
                `Debug: ${message}`,
                source.text
            ].join("\n")
        );
    }
}
````

**Comment by nex3** [comment]
At least in the Dart API, `SourceSpan.text` just refers to the substring of the source text covered by the span, not the human-friendly rendering of that span within a given context.

I agree that it would be nice to be able to pass in one or more streams to write to, but that would require the embedded host implementing source span serialization in JS somehow which is likely to be more pain than it's worth. At least for now, I think it makes more sense to just say that the API defaults to printing messages to stderr.

**Comment by glenn2223** [comment]
Sorry for the delay (work, uni study, opensource commitments and family time can really leave you with zero time *[not that I'm complaining about the last one 😄]*).

Was [this](https://github.com/glenn2223/sass/blob/758a6e704eb2317b9a7493ef5c277e4d4a5b0ea8/Javascript%20API.md) what you were after?

Before I add examples and the `SassType`'s, I thought I should check I was on the right track?

**Comment by nex3** [comment]
Yeah, that looks good! cc @Awjin who's working on a similar source span representation for exposing exceptions—we should make sure these align.

Are the logger function arguments provided by position, or as an object with named keys? I suggest you do the latter, so that it's easy to add arbitrary additional information later on. For example, we probably want the `warn` function to take a `deprecation` parameter that indicates whether or not it's a deprecation warning.

**Comment by Awjin** [comment]
The `SourceSpan` and `SourceLocation` designs are looking solid, thanks for putting this together @glenn2223. I'd recommend labeling which parameters are optional, like `SourceSpan.end?`, as they're laid out in the [embedded protocol](https://github.com/sass/embedded-protocol/blob/00d84d6ae9cef32fd3a30f336e771cc981e3bcbf/embedded_sass.proto#L508-L552). Even though this is a JS API, I think it makes sense to use TypeScript syntax to clearly specify the interfaces.

**Comment by glenn2223** [comment]
Thanks for the input

How's the updated version, still on track? Almost done the mark-up (well, markdown 😄 sorry bad joke). Anything wrong? Anything I can do to help elsewhere (coding or otherwise)?

**Comment by nex3** [comment]
@glenn2223 Thanks for your patience and sorry for the long wait, it's been a pretty hectic February on the Sass team. I think for the built-in `StandardLogger`, it probably makes sense to make it minimally configurable until we get actual user requests to expand its API. Generally speaking, I'd rather have users write their own custom loggers rather than try to anticipate everyone's needs in the built-in API.

**Comment by glenn2223** [comment]
No worries about the delay (after a massive delay on my part 😁). Sorry for mine too, finished my first uni module though 👍

So I've just commented out the reference to the stdlogger and finished [the markdown](https://github.com/glenn2223/sass/blob/758a6e704eb2317b9a7493ef5c277e4d4a5b0ea8/Javascript%20API.md)

**Comment by nex3** [comment]
Are you waiting on another review? If so, I'm going on vacation for a couple weeks, but I can check it out when I return.

**Comment by henrycatalinismith** [comment]
I just found my way to this issue thread after a little search for how to get `@debug` and `@warn` messages via the JS API. Looks like some really good progress was made here! I wanted to say "Hey, I'm also really interested in using this functionality!" but without it being a "please prioritise this free work for me" comment so I spent a couple hours trying to build what you've come up with here as best as I can.

https://github.com/sass/dart-sass/compare/master...hendotcat:node-logger?expand=1

It's very incomplete and my lack of expertise with Dart is on full display here. If this is a helpful thing for me to put more effort into then I'd be happy to revisit it: I'm starting a new job soon where I'll be working with Dart full time so hopefully that'll enable me to make one or two more meaningful contributions than an unfinished branch (haven't even managed to fully build and test this yet). If this isn't a helpful thing for me to spend more time on then that's also cool because I've really enjoyed digging into this tonight and I hope it's at least a nicer-than-usual way of saying ":+1: any update on this?"!

---

Quick update: I threw another couple of hours at this tonight and got it working. Very satisfying! Well-aware the code in that branch is a long long way from mergeable but it's fun seeing the idea come to life!

<table><thead><tr><th><code>test.js</code></th><th>Output</th></tr></thead>
<tbody><tr><td><pre><code>const sass = require("./dart-sass/build/sass.dart.js")
sass.renderSync({
  data: [
    '@warn "WATCH OUT!";',
    '@debug 0.0001%;',
  ].join("\n"),
  logger: {
    warn: m => console.log(`warning: ${m}`),
    debug: m => console.log(`debug: ${m}`),
  },
})
</code></pre></td><td><pre><code>warning: WATCH OUT!
debug: 0.0001%</code></pre></td></tbody></table>

**Comment by glenn2223** [comment]
Hey @nex3, I see I didn't actually reply to your last comment 🤦‍♂️. I hope that the release of 1.33/1.34 had made this less of a priority rather than it dropping off the radar 😁

Yes please a review would be nice. I assume I need to add a `deprecated` property [here](https://github.com/glenn2223/sass/blob/758a6e704eb2317b9a7493ef5c277e4d4a5b0ea8/Javascript%20API.md#logdata)

---

Thanks for bringing this to life @hendotcat 😍. I agree it's brilliant to see something working

**Comment by glenn2223** [comment]
Side bar @hendotcat, I think the spec of the JS API is to be, in a way, independent of the logger you seem to be copying from [here](https://pub.dev/documentation/sass/latest/sass/Logger-class.html) - though they aren't much different.

Basically, both the error and warning will have the message and `SourceSpan` properties passed to the call. Both would need to have a `deprecated` `bool` as well - well I think so anyway, especially with the divide `/` deprecation - but that's not in my spec yet (waiting on confirmation from @nex3 )

**Comment by nex3** [comment]
> Yes please a review would be nice. I assume I need to add a `deprecated` property [here](https://github.com/glenn2223/sass/blob/master/Javascript%20API.md#logdata)

A few thoughts:

* I think the clearest way to define JS APIs is by writing them out as TypeScript `.d.ts` interfaces. It's terser than having to spell out the types in prose and has thoroughly-specified semantics. If you're not comfortable with that syntax, though, I can do it as a separate pass.
* As you say, `LogData` should have a boolean `deprecation` field.
* It's not clear to me why `Logger.debug` is optional but `Logger.warn` is not. It seems like they should either both be mandatory or both be optional.

**Comment by glenn2223** [comment]
>I think the clearest way to define JS APIs is by writing them out as TypeScript `.d.ts` interfaces. It's terser than having to spell out the types in prose and has thoroughly-specified semantics. If you're not comfortable with that syntax, though, I can do it as a separate pass.

That's fine; [here you go](https://github.com/glenn2223/sass/blob/master/index.d.ts)

>As you say, `LogData` should have a boolean `deprecation` field.

👍, all done on the `.d.ts` file

>It's not clear to me why `Logger.debug` is optional but `Logger.warn` is not. It seems like they should either both be mandatory or both be optional.

My initial thoughts were: the `Logger` is optional so if you specify it then, surely, you want to `warn`. However, writing it down, it's clear now that one could want to only debug. I will mark them both as optional, though this can be changed - if requested

**Comment by glenn2223** [comment]
Quick side-bar: can the `.d.ts` file be added to the outputted package? This way I can stop using [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sass/index.d.ts) (which currently uses *`"Type definitions for sass 1.16"`*)

**Comment by nex3** [comment]
@glenn2223 Can you make that `.d.ts` file into a PR? I have more comments, but at this point it would be easier to write them as code review comments attached to specific lines.



> Quick side-bar: can the `.d.ts` file be added to the outputted package? This way I can stop using [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sass/index.d.ts) (which currently uses _`"Type definitions for sass 1.16"`_)

https://github.com/sass/dart-sass/issues/13

**Comment by glenn2223** [comment]
Done, see #3067 - or did you want it over on `sass/dart-sass`

**Comment by nex3** [comment]
No, this is the right repo. All the JS API stuff is part of the language spec, since it's shared across multiple implementations.

**Comment by nex3** [comment]
The proposal has landed. I'm going to wait until the in-progress proposals for the new JS API have landed to officially request comments, though, so we can request for all of these at once.

**Comment by nex3** [comment]
This proposal is now officially out for review. It will remain that way for at least a month (potentially longer depending on discussion), at which point we'll move on to implementation.

**Comment by nex3** [comment]
It's been a month and there have been no objections, so I'm going to mark the proposal as accepted and start merging it into the main spec directory.
