### ISSUE TITLE
Document --pre

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#298]
The --pre flag is undocumented: there is no manual entry for sass/scss, and --help doesn't show it.

Edited for clarity

**Comment by jleclanche** [comment]
I'm on an old version, oops.

**Comment by jleclanche** [comment]
It's an issue with --pre as well.

**Comment by nex3** [comment]
I'm not sure what you mean by the `--pre` flag. Sass doesn't have a `--pre` flag. It has `--precision`, but that does show up in `--help`.

**Comment by jleclanche** [comment]
They're one and the same, apparently ruby's optparse doesn't care if the flag is unfinished. Never used it as --precision so didn't know.

Closing this.
