### ISSUE TITLE
Syntax Error: SyntaxError

### ISSUE THREAD

**Issue by 17858274056** [sass/sass#2984]
<img width="512" alt="WechatIMG15485" src="https://user-images.githubusercontent.com/39400164/103401243-0ca6f780-4b83-11eb-9f09-786adc8dccf7.png">

**Comment by 17858274056** [comment]
no

**Comment by 17858274056** [comment]
<img width="512" alt="WechatIMG15485" src="https://user-images.githubusercontent.com/39400164/103401364-77f0c980-4b83-11eb-9860-08e051905cb9.png">

**Comment by Awjin** [comment]
This is valid Sass and should compile. What version of Sass are you using? What else are you using to compile your Sass?
