### ISSUE TITLE
how can I return Colour in "hsl" form

### ISSUE THREAD

**Issue by PavanTank4631** [sass/sass#2988]
// next.config.js

```
const env = require('./site.config').env;
const Colour = require('sass').types.Color;
const { r, g, b } = require('./site.config').customProperties;

const withBundleAnalyzer = require('@next/bundle-analyzer')({ enabled: !!process.env.ANALYZE });

const config = {
  env: {
    ...env,
  },
  sassOptions: {
    functions: {
      'primaryOpacityColour()': function () {
        return new Colour(r, g, b)
      },
    },
  },
};

module.exports = withBundleAnalyzer(config);
```

**Comment by stof** [comment]
I don't understand what your question is

**Comment by PavanTank4631** [comment]
I want to return hsl(r, g%, b%) value from the primaryOpacityColour() function, but When I tried it, It's not working

**Comment by stof** [comment]
hmm, it looks like the node API does not have the equivalent of `SassColor.hsl()` in the dart API for values.

**Comment by PavanTank4631** [comment]
Is there any other way to archive something like this?

**Comment by stof** [comment]
I don't think there is a way to achieve this until some improvement is done in the JS API. Currently this JS API for types is implemented to copy the API of node-sass (to make it a drop-in replacement) rather than to expose all the features of the underlying dart API.

**Comment by Awjin** [comment]
@stof is right—there's currently no way to do this. We are working on designing a new API to resolve these issues (see https://github.com/sass/sass/issues/2510).

**Comment by jayenashar** [comment]
is it possible to use a string somehow?  like ```return new sass.types.String(`hsl(${h}, ${s}%, ${l}%)`);```
