### ISSUE TITLE
Typescript :)

### ISSUE THREAD

**Issue by babakfp** [sass/sass#2989]
Hi.
Is it possible to have something like Typescript (built-in) in SASS? I'm currently working on a big project (a SASS library) and it seems to be impossible to protect from unneeded types!.
some examples:
```scss
$text type string;
$text: "Hello World";

$num type number;
$num: 22;

$text-and-num type string or number;
$text-and-num: "Hello World";
$text-and-num: 22;

$list type list;
$list: 1 2;

$map type map(
  string or number,
  list or map
);
$map: ("Hi", 1 2);
$map: (1, (1: 2));
```

I didn't find an open issue on this repo (and dart-sass), so I decided to create one. 
Thanks.

**Comment by Awjin** [comment]
While this is a really interesting thought, Sass was not designed as a statically typed language. It would require a tremendous amount of effort to completely redesign and overhaul the language to support something like this. Beyond that, we'd have to weigh the cost of sharply increasing the learning curve of Sass for folks who use the language daily but are not developers. With all that said, it would be interesting to see a preprocessor that converts "typed Sass" into Sass, but that's an experiment outside of the scope here.

**Comment by babakfp** [comment]
Hi.
The feature can be optional. If I don't want to use it, then I don't need to use it.
We are developers, right? I mean we spend a lot of time on a stupid thing so it may just hard to start, like going to the gym. for example work out isn't hard, it's just hard to start.
Can't we (we as a community) create something like an event and share the work with other developers to do their own part of the project or something like that. I don't know, I'm just trying to help.

Is there is a plan to overwrite the documentation? I'm planing it so?

**Comment by babakfp** [comment]
Hi
What about a simple built in function like:
```sass
@use "sass:list"

@function type-validation($data, $types...)
  @each $type in $types
    @if type-of($data) != $type
      @error "ERROR UNEXPECTED TYPE ||| expected-type: #{$types} ||| received-type: #{type-of($data)}"
  @return null

$my-name: 'babak'
// $type-validation: type-validation($my-name, string)
$type-validation: type-validation($my-name, number, map)
```

@Awjin

**Comment by babakfp** [comment]
Do we need to check the second argument item/items type?

**Comment by Awjin** [comment]
This looks like a good approach to me.
