### ISSUE TITLE
sass-convert has serious issues with operators

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#299]
```
adys@azura ~ % echo "e + .c{color: red}" | sass-convert --to scss 
e .c {
  color: red;
}
adys@azura ~ % echo "e > .c{color: red}" | sass-convert --to scss 
e .c {
  color: red;
}
adys@azura ~ % echo "e > .c2 > .c{color: red}" | sass-convert --to scss 
e .c {
  color: red;
}
```

**Comment by chriseppstein** [comment]
what version of sass is this?

**Comment by jleclanche** [comment]
Current master HEAD.

**Comment by jleclanche** [comment]
Sass 3.2.0.alpha.0 (Bleeding Edge)

**Comment by chriseppstein** [comment]
yikes. I think I borked it. :'(

I'll add a regression test and get it fixed soon. You can probably work around this by downgrading temporarily.

```
$ gem install sass --version 3.1.15
$ sass-convert _3.1.15_ --to scss
```

**Comment by jleclanche** [comment]
It's more serious than I thought. 

echo ".a .b .c{color: red}" | sass-convert --to scss  
.a .c {
  color: red;
}

**Comment by chriseppstein** [comment]
Ok. We'll write a bunch of tests and get this sorted out. does the older version work for you?

**Comment by jleclanche** [comment]
I have not tested, but I'm not that bothered with it; it's for a one-time conversion so I fixed it manually. Do you need me to test it?

**Comment by chriseppstein** [comment]
If you don't mind, it would help us know whether we have to patch stable too. but I can test it when I get there.

**Comment by jleclanche** [comment]
Just tried and having problem with rubygems. It's probably better if you test it; sorry.

**Comment by chriseppstein** [comment]
No worries. thank you for bringing this to our attention.

**Comment by nex3** [comment]
This is caused by 1cbf18c8e1017180682268f599132bbabf51fd79. I'm baffled as to how this escaped the test coverage. I'll fix it tomorrow.
