### ISSUE TITLE
How to get and load window width in px into SCSS variable?

### ISSUE THREAD

**Issue by bencuri** [sass/sass#2990]
I would like to set the variable below to have the value of the Window width in "px". How can you do that? Is it possible at all? Adding 100vw is not a good solution in my case because I further want to process the variable value, and in case the unit is "vw", I won't be able to do that, only if it is "px". Before processing, the value of the variable has to be in "px" no matter what. 

```
div {
        $screensize: """window width in px"""
        .................
        .................
         width:$screensize;
    }
```

**Comment by babakfp** [comment]
It's not related to css, so it's not related to sass too. You should use Javascript.
