### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by stof** [sass/sass#2993]
Running `npm run link-check` reports all external links as dead links (or at least links going to github.com).
This seems to be caused by https://github.com/tcort/markdown-link-check/issues/142 which has been fixed upstream in markdown-link-check but not in the fork used in this repo.

**Comment by stof** [comment]
it could also be caused by https://github.com/tcort/markdown-link-check/issues/114 (which is also fixed upstream but not in the fork)

**Comment by nex3** [comment]
I've merged upstream into my branch, so this should be fixed now.
