### ISSUE TITLE
Extend in stylesheets with unknown directives broken on sass/master

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#30]
The following stylesheet results in an infinite loop in `do_extend`:

```
.foo { color: red; }
h1 { @extend .foo; }
@font-face {
  font-family: "something";
  src: url('/fonts/something.eot');
}
```

**Comment by nex3** [comment]
Fix an infinite loop bug caused by poorly translated visitor code.

Closed by 9649af33677777ee2214f341617a51861eabd415
