### ISSUE TITLE
Client-side compilation like less.js?

### ISSUE THREAD

**Issue by AshleyAitken** [sass/sass#300]
How about a sass.js to do same as less.js (mostly for use during development)?

Just a suggestion - integrating sass compilation into editors, IDEs, and other tools or watching directories makes thing just that little bit more complex (IMHO). 

Thanks for considering.

Cheers,
Ashley.

**Comment by chriseppstein** [comment]
Months of work. #justsaying

**Comment by nex3** [comment]
The longer answer is that we would like to have a JS implementation of Sass for ease of development, but currently it's not worth the development energy that would have to go into it. Chris and I are kept very busy designing and implementing Sass and Compass, and design issues take precedence over a port.

**Comment by AshleyAitken** [comment]
Thanks for the comments. 

I understand and I am grateful for all the work you do on Sass and Compass.  

Cheers,
Ashley.

**Comment by Anahkiasen** [comment]
For the note you can use [node-sass](https://github.com/andrew/node-sass)

**Comment by lolmaus** [comment]
@AshleyAitken Client-side? How?

**Comment by AshleyAitken** [comment]
On 30 Apr 2014, at 4:56 pm, lolmaus notifications@github.com wrote:

> @AshleyAitken Client-side? How?

I’m no expert but by implementing what is currently done in Ruby in Javascript, e.g. how Less does it.  This would only be for development, not production.  The developers of Sass and Compass have suggested (previous response) that they have higher priority design tasks, which is up to them and I have no problem with that (I’m already very grateful for all they have done).

Cheers,
Ashley.

## 

Dr Ashley Aitken - Principal
Running Code Productions
ashley@runningcode.com.au
http://www.runningcode.com.au
LinkedIn/Twitter/Skype: AshleyAitken
Perth, Western Australia (GMT + 8)
Mb (04) 1226-8159 (Preferred)
Ph (08)  9368-5505
Fx (08) 9271-3160

**Comment by lolmaus** [comment]
@AshleyAitken I'm sorry, i pinged you accidentally.

I meant to reply to @Anahkiasen' comment:

> For the note you can use node-sass

AFAIK, node-sass is written in C and i'm not aware of any way to execute it in a browser.

**Comment by Anahkiasen** [comment]
Ah yes exact, don't mind me, thought node-sass was written in pure JS

**Comment by Snugug** [comment]
node-sass is JS bindings for Libsass, a C compiler for Sass.

**Comment by FWeinb** [comment]
There is a emscripten port of [libsass](https://github.com/hcatlin/libsass) called [libsass.js](https://github.com/rodneyrehm/libsass#readme)

**Comment by ghost** [comment]
maybe [in-browser-sass](https://neos21.github.io/in-browser-sass/) ??

**Comment by kopax-polyconseil** [comment]
Hello, is there now a lib that can process sass to css client side?

**Comment by nex3** [comment]
This is being tracked on https://github.com/sass/dart-sass/issues/25.
