### ISSUE TITLE
The github organization refers to a suspended twitter account

### ISSUE THREAD

**Issue by stof** [sass/sass#3000]
![image](https://user-images.githubusercontent.com/439401/104328289-f76b8a80-54eb-11eb-9ab8-e2af530eed61.png)

![image](https://user-images.githubusercontent.com/439401/104328325-00f4f280-54ec-11eb-8b67-1af9cfdf2dfc.png)

If the twitter account is not relevant anymore, I suggest removing it from the github organization profile.

**Comment by nex3** [comment]
I think I just misremembered our Twitter handle when I added that field. Updated to the correct `@SassCSS`.
