### ISSUE TITLE
str_split() within @while loop produces error

### ISSUE THREAD

**Issue by Simplicissi** [sass/sass#3001]
In my work on a `str_split()` function, I stumbled upon something, I can only explain to be an error.

The `$in: str-index();` function within the `@while` loop does return the expected integer of `2`, however trying to reuse it or perform any mathematical action on it will return errors similar to:
```
Error: $end-at: 1-1-1 is not a number.
```

```
Error: Undefined operation "null * 1".
```
https://codepen.io/LudwigGeorgImmanuel/pen/BaLqvVB
```
//...

@function str_split($str, $substr) {
  $in: str-index("#{$str}", "#{$substr}");
  
  @if ($in != null) {
    $i: 1;
    
    @while $i <= math_fit(str-length("#{$substr}"), str-length("#{$str}")) {
      $in: str-index("#{$str}", "#{$substr}");
     
      
      @for $j from 1 through str-length("#{$substr}") {
        $str: str_replace("#{$str}", ($in + $j) - 1, ($in + $j) - 1, "x");
      }
      
      $i: $i + 1;
    }
  }
  
  @return $str;
}

//...
```

**Comment by jathak** [comment]
`str-index` returns `null` when the substring is not contained within the given string. That null then gets passed around added to with the expression `(null + 1) - 1 - 1`. The `+` and `-` do string concatenation with either operand is not a number, so you end up with the string `1-1-1`.
