### ISSUE TITLE
Website -> Selected Language(SCSS / SASS) is Grey and non-Selected Language is a Bright Colour(Pink). Should be reversed

### ISSUE THREAD

**Issue by russelgauthier** [sass/sass#3009]
Website -> Selected Language(SCSS / SASS) is Grey and non-Selected Language is a Bright Colour(Pink). Should be reversed.

E.g. https://sass-lang.com/documentation/at-rules/use

Selected items are generally the brighter colour(a pink colour in this case), and non-selected items are greyed out. This is also contradicted on the same page by => CSS being pink(selected).

I can't determine if this is where I would submit the suggestion. If not the right place, inform me where to submit it and I'll do so. I've heard this independently pointed out by 2 designers and noticed it myself within the last week as we were scouring documentation. It really stuck out. Otherwise, great. Thanks.

**Comment by mirisuzanne** [comment]
This seems like it would belong on the [sass site](https://github.com/sass/sass-site), since it is not related to the language itself.

**Comment by russelgauthier** [comment]
Thanks. I didn't know if this was the right repo :)
