### ISSUE TITLE
sass --watch multiple files ?

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#301]
Hi,
Is it possible to do something like that ?

```
sass --watch sass:css sass_alt:css_alt
```

To watch multiple folders at the same time and make them compile in different places ?

**Comment by nex3** [comment]
This works already.

**Comment by jmcbee** [comment]
hi, how? I wanted to watch both a file and a directory:
- app/styles/main.scss
- app/styles/components/*.scss

Bootstrap scss files resides on `app/styles` as well so I try to prevent watching the whole `app/styles` folder to compile them faster.

**Comment by nex3** [comment]
`sass --watch app/styles/main.scss:out/main.css app/styles/components:out/components`

**Comment by jmcbee** [comment]
Actually, it looks like it automatically watches everything that's been imported by `main.scss`.

**Comment by ghost** [comment]
If you have everything in the same folder then do like so:

<code> sass --watch style.sass:style.scss style.sass:style.css </code>

**Comment by dgtlmoon** [comment]
Remember kids, `node-sass` is not `sass` :) if you got here through google being vague..
