### ISSUE TITLE
mix() function inside a CSS Var definition

### ISSUE THREAD

**Issue by G4bbix** [sass/sass#3012]
Hey there

Recently I have encountered a Problem with the mix() function when using it inside a CSS Var Deifnition. The function is not being processed when inside a CSS function. 
I have created a small demo of the Problem: https://jsfiddle.net/0y9jgxeo/

**Comment by Awjin** [comment]
Since CSS variables allow almost any text at all in their declaration values, you need to explicitly interpolate any Sass code that's assigned to a CSS variable ([see the docs](https://sass-lang.com/documentation/style-rules/declarations#custom-properties)).

```scss
:root {
  --mixedRed: #{mix(#ffffff, #ff0000, 50)};
}
```
