### ISSUE TITLE
How to transfer the variable to the file?

### ISSUE THREAD

**Issue by maxsite** [sass/sass#3015]
```
style.sccs
----------
// my variables — Different files are connected
@use 'my-variables1' as *; // $a: red;
// @use 'my-variables2' as *; // $a: green;
// @use 'my-variables3' as *; // $a: blue;

// core — Not edited!!!
@use 'default' as *;  // $a: black !default;
@use 'generation' as *;


my-variables1.scss
------------------
$a: red;


default.scss
------------
$a: black !default;


generation.scss
---------------
@use 'default' as *;
p {color: $a}
```
output:
`p {color: black}`

**How to make the file «generation.scss» used «$a» from file «my-variables1.scss»?**

**Comment by Lakro** [comment]
Indeed the upcomming project structure is very confusing to a lot off people. I try doing the same at the moment ... 

As I think the intended solution for the project structure is:
Import the vars with `@use` to every partial file if needed ... not to the main file.
(See example below)

But now there is the problem to a pass the individual settings for the project WRITTEN IN A SEPARATED FILE to the config file so it overwrites the defaults there. Nowhere is a decription how to do it ... :-/ 

(1) That's what I have:

```
//file ###> _config.scss

$columnWidth: 50% !default;
$projectColors: (
   primary: red,
   secondary: blue,
) !default;


//file ###> _functions.scss 

@use 'config' as * // --> to use config vars (here: without namespace)

@function getColor( $name ){
   $color: map-get($projectColors, $name);  
   @return $color;
}


//file ###> _partial.scss

@use 'config' as *     // --> use config vars (here: without namespace)
@use 'functions' as *  // --> use functions (here: without namespace)

.class {
   width: $width;
   color: getColor( primary );
}


//file ###> myStylesheet.scss
// no need to @use 'config' or 'functions' 
// as they are not direct needed in this file

@use 'partial'  //--> write the css

---

```

(2) HOW CAN I DO NOW:

```
//file ###> _myOwnSettings.scss

$columnWidth: 25%;
$projectColors: (
   primary: orange,
   secondary: yellow,
);


//file ###> _config.scss
// how to use _myOwnSettings.scss HERE
//
// tried: @use 'myOwnSettings' [as *|m]
// general not working: as *
// partial working: as m
// but than I need additional:
// 
// columnWidth: m.columnWidth;
// projectColors: m.projectColors
//
// THIS CANNOT BE INTENDED
// what's the intended way?
// is there a function or automated way to advice vars?


$columnWidth: 50% !default;
$projectColors: (
   primary: red,
   secondary: blue,
) !default;

...
...
...

```

THX for advise and clearing confusion.

br Lakro

**Comment by maxsite** [comment]
Theoretically can be done like this:

```
my-variables1.scss (And other files)
------------------
@use 'default' with (
    $a: red,
);
```

output:
`p {color: red}`

But it does not work when you need to rewrite the value to change the value:

```
style.sccs
----------
@use 'my-variables1'; // $a: red;
@use 'my-variables2'; // $a: green; - error!!!

// core — Not edited
@use 'default';  // $a: black !default;
@use 'generation';
```

**Comment by Lakro** [comment]
There is an additional question concerning this point.

In your official statement you described a technique to organize a project/module so you can pass variables-settings from outsite just calling the main file. Your example:

```
@use "bootstrap" with (
  $paragraph-margin-bottom: 1.2rem
);
```
(see: https://sass-lang.com/blog/the-module-system-is-launched#configuring-libraries)

That shows, that there must be an intended way to...

1. call a main-file with passing indivual-settings-variables to the project
2. just to forward the individual-settings-variables internal in the project to the config-file
3. so that the individual-setting-variables can overwrite the default-variables

Beyond the fact that the project Bootstrap in real decided to change to DartSass but not to use `@use` (so this technique cannot been studied there) ...  

Please can you give advise or a link to an demo project how the intended project-stucture and way is to pass the vars. 

Sorry for that question. But here indeed is a lot confusion... and slso I have (wider) experience with Sass for years I am confused and seem not to be able to figure it out ... really after testing it nearly one week I do have no sheen of imagination how that could work with the new technique :-(

br Lakro

**Comment by Lakro** [comment]
@maxsite 

> my-variables1.scss (And other files)
> ------------------
> @use 'default' with (
>   $a: red,
> );

Well. That concerns the additional question I added to that thread. 

Thinking a step forward ... indeed there must be a way to call a module with individual settings (maybe or exactly!) that way ... but than you have to pass them to the defaults and/or partials to overwrite the dafaults without changing the code of the module ...

Really confusing ... ... ... really hope for example and/or advice I have been looking for for ... time.

**Comment by maxsite** [comment]
In general, I want to repeat this code:

```
style.scss
----------
@import 'my1'; // $a: red;                        |
@import 'my2'; // $a: green;                      |  Optional
$a: blue;                                         |

@import 'def'; // $a: black !default;
@import 'gen'; // $a = blue;


my1.scss
--------
$a: red;


my2.scss
--------
$a: green;


def.scss
--------
$a: black !default;

gen.scss
--------
p {color: $a}
```

Is there a way to do it through USE/FORWARD ?

**Comment by jathak** [comment]
Avoiding these sorts of implicit overrides was a specific goal of the module system, as it makes it difficult to figure out what declaration a variable reference actually refers to.

If you want to refer to a variable from another module, you need to explicitly `@use` it in the file where it's referenced. You can override `!default` variables with a `with` clause, but that still needs to be done explicitly the first time that module is used.

For example:
```scss
// style.scss
@use 'def' with ($a: blue);
@use 'gen';

// def.scss
$a: black !default;

// gen.scss
@use "def";

p { color: def.$a; }
```
would result in the color of `p` being blue.

`as *` makes members from a dependency available in the current module without a namespace, but it doesn't mean that the two modules now share a scope, so you can't just override variables like with `@import` when everything shared a global scope.

**Comment by maxsite** [comment]
I need the user to have the ability to override the variable in other files many times.

```
// style.scss
@use 'my1'; // @use 'def' with ($a: red); 
@use 'my2'; // @use 'def' with ($a: green);

@use 'gen';

// Error: This module was already loaded
```

**Comment by mirisuzanne** [comment]
The `with` clause & `default` are for initial configuration, but you can still override variables whenever you want. I do this all the time:

```scss
// config.scss
$a: black !default;

// style.scss
@use 'config' with ($a: blue);
@use 'my1';
@use 'my2';

// my1.scss
@use 'config'; // can't use with more than once
config.$a: red; // override the value of $a inside config.scss

// my2.scss
@use 'config'; // now $a == red
config.$a: green !default; // I can also use default here
```

**Comment by maxsite** [comment]
Thank you! But it works not just as necessary.

```
// config.scss
$a: black !default;

// my1.scss
@use 'config';
config.$a: red;

// my2.scss
@use 'config';
config.$a: green !default;

// gen.scss
@use "config";
p { color: config.$a; }

// style.scss 
@use 'config' with ($a: blue); // config.scss -> $a: black !default;
@use 'my1'; // @use 'config'; config.$a: red;
@use 'my2'; // @use 'config'; config.$a: green !default;
@use 'gen'; // @use "config"; p { color: config.$a; }

// output 
// p {color: red;} — incorrect, correctly green
```

It is necessary that the user has the ability to override the variable several times.

**Comment by maxsite** [comment]
I seem to understand. Need to be removed `!default` in my2.scss.

```
// config.scss
$a: black !default;

// my1.scss
@use 'config';
config.$a: red;

// my2.scss
@use 'config';
config.$a: green;

// gen.scss
@use "config";
p { color: config.$a; }

// style.scss 
@use 'config' with ($a: blue); // config.scss -> $a: black !default;
@use 'my1'; // @use 'config'; config.$a: red;
@use 'my2'; // @use 'config'; config.$a: green !default;
@use 'gen'; // @use "config"; p { color: config.$a; }

// output 
// p {color: red;} — green

```

Samples

```
// style.scss 
@use 'config' with ($a: blue); 
@use 'gen'; // p {color: blue;}

// style.scss 
@use 'my1'; // red 
@use 'gen'; // p {color: red;}

// style.scss 
@use 'my2'; // green 
@use 'gen'; // p {color: green;}

// style.scss 
@use 'my1'; // red 
@use 'my2'; // green 
@use 'gen'; // p {color: green;}

// style.scss 
@use 'gen'; // p {color: black;}

```
