### ISSUE TITLE
Transparent as a color for non-prefixed gradients

### ISSUE THREAD

**Issue by ghost** [sass/sass#302]
Sass isn't accepting transparent as a color value for non-prefixed gradients, when compiling. 

Example: 

```
/* This Works */
background: -webkit-linear-gradient( left, transparent 0%, rgba(0,0,0,.01) 10%, rgba(0,0,0,.01) 90%, transparent 100% );

/* This Triggers the Error:
   Expected a color. Got: transparent  */
background: linear-gradient( left, transparent 0%, rgba(0,0,0,.01) 10%, rgba(0,0,0,.01) 90%, transparent 100% ) ;
```

Transparent works fine in every other test I could think of. 

Version: Sass 3.2.0.alpha.63 (Bleeding Edge)

**Comment by chriseppstein** [comment]
This is a compass error and it's fixed on master and stable. I will be releasing it in the next day or two.

**Comment by nex3** [comment]
I'm closing this because it's a Compass issue, not a Sass one.
