### ISSUE TITLE
npm not found after installing sass globally

### ISSUE THREAD

**Issue by singjyuwong** [sass/sass#3020]
After running `npm install -g sass` in the terminal, I tried to run `npm install sass --save-dev` again in my current project (no intermediate actions were done), I got the following error
```
zsh: command not found: npm
```

1. Operating system: macOS Big Sur Version 11.2.1 (Intel chip)
2. Previously installed global modules can still be found in `/usr/local/lib/node_modules`
3. `which node` returns `/usr/loca/bin/node`
4. `which npm` returns `npm not found`

**Comment by Awjin** [comment]
Installing Sass doesn't have to ability to break npm. It's most likely an issue with your npm installation or zsh configuration; I'd encourage you to explore those further.
