### ISSUE TITLE
Can't set a global variable inside a function

### ISSUE THREAD

**Issue by SorinGFS** [sass/sass#3022]
We can't set a global variable inside a function, except if nested in a condition... twice!
I created this example to reproduce the issue:

```scss
    /* fist try! */
    $fakevar: () !default;
    $isItSassWonderful: true;

    @function setFakeVar() {
        @if $isItSassWonderful {
            $fakevar: append($fakevar, 'yeeees sass is wonderful', comma);
        }
        @return null;
    }

    @debug setFakeVar();
    @debug $fakevar;

    /* but... */
    $fakevar: () !default;
    $isItSassWonderful: true;

    @function setFakeVar() {
        @if $isItSassWonderful {
            @if $isItSassWonderful {
                $fakevar: append($fakevar, 'if you insist...', comma);
            }
        }
        @return null;
    }

    @debug setFakeVar();
    @debug $fakevar;
```

**Comment by jathak** [comment]
When you wish to update a global variable from within a local scope, you should use the `!global` flag. See the documentation [here](https://sass-lang.com/documentation/variables#shadowing).

**Comment by SorinGFS** [comment]
> 
> 
> When you wish to update a global variable from within a local scope, you should use the `!global` flag. See the documentation [here](https://sass-lang.com/documentation/variables#shadowing).

As you can see... I don't need the "global" flag...

**Comment by jathak** [comment]
Ah, I see. The behavior here for a single if rule is correct (a new variable is declared within the function's local scope), but the latter case does seem to be a bug in Dart Sass. I opened sass/dart-sass#1250 to track the fix there (since this doesn't seem to be an issue with the language itself, just a bug in the implementation).

**Comment by SorinGFS** [comment]
> 
> 
> Ah, I see. The behavior here for a single if rule is correct (a new variable is declared within the function's local scope), but the latter case does seem to be a bug in Dart Sass. I opened [sass/dart-sass#1250](https://github.com/sass/dart-sass/issues/1250) to track the fix there (since this doesn't seem to be an issue with the language itself, just a bug in the implementation).

I think you shouldn't fix this as it can break a lot of code since it was available in functions inside deep nested conditions for years without even knowing it.
