### ISSUE TITLE
can sass support `@from 'bootstrap' import .btn` Grammar

### ISSUE THREAD

**Issue by LY1806620741** [sass/sass#3023]
我在开发的时候用到了第三方库,有几个痛点

1. 如何局部使用第三方样式，并最小化加载，因为完全引入实在是不优美
2. 是否可以支持url编译,以精简git仓库，例如@import xxx.com/thirdparty/sass/demo.sass（我可以用shell和.gitignore实现，但是实际上我是个懒汉）
---
I used a third-party library when I was developing, and there were several pain points.

1. How to use third-party styles locally and minimize loading, because full introduction is really not beautiful.
two。
2. Can url compilation be supported to simplify the git repository, such as @ import xxx.com/thirdparty/sass/demo.sass (I can do it in shell and .gitignore, but I'm actually a slacker)

**Comment by babakfp** [comment]
1. Just import the libraries .sass/.scss file. If you are using bootstrap, you need to import the other files (variables, mixins...) before the component files.
2. Just download the files?

**Comment by jathak** [comment]
For (1), we generally don't want to allow downstream users to depend on a library in ways that aren't specifically allowed by it. If a library wants to allow you to depend on only certain parts of its CSS, it should use mixins or separate the relevant CSS into multiple files.

For (2), we don't plan to add any mechanism for having Sass download external dependencies. It's not worth the complexity when existing tools already handle this more robustly. You should use some sort of package manager and/or build system for that (e.g. install your dependencies with NPM and then use Webpack to refer to stylesheets in those deps). We do plan to add a built-in package importer in the future (see #2739), but the actual downloading of dependencies would still be handled by NPM (or some other package manager).
