### ISSUE TITLE
Suggestion: New @extend Syntax

### ISSUE THREAD

**Issue by babakfp** [sass/sass#3025]
Hi
### Current Syntax
```scss
.myclass {
  @extend .class-one;
  @extend .class-one, .class-two;
}
```
### Desired Syntax
```scss
.myclass {
  @extend class-one;
  @extend class-one class-two;
}
```
With the current syntax, using multiple classes doesn't feel to be right. It's good for better UX and clean code. It's easy to write and makes people involved, like filling the max power or something...

**Comment by jathak** [comment]
I'm not sure what exactly you're asking for here. Omitting the dot in front of a class would be confusing (as classes are always written as `.name` within CSS) and separating multiple classes passed to `@extend` with a space could lead to confusion with the descendent combinator (in a selector `.a .b` selects an element with class `a` that's a descendent of an element with class `b`, so separating classes with a space in an `@extend` would be confusing).

**Comment by babakfp** [comment]
### Using  `,` in list type value
```sass
$list-1: item-1 item-2
$list-2: (item-1 item-2)
$list-3: [item-1 item-2]
$list-4: item-1, item-2
$list-5: (item-1, item-2)
$list-6: [item-1, item-2]

@debug type-of($list-1) // list
@debug type-of($list-2) // list
@debug type-of($list-3) // list
@debug type-of($list-4) // list
@debug type-of($list-5) // list
@debug type-of($list-6) // list
```
We can write a list in 6 different syntaxes and does this confuse some people or not?

### Writing `.` before the class name
We can `@extend` anything right? Even this:
```sass
.my-component
  @extend [hover~="bg-gray-50"]
```
Output:
```css
[hover~=bg-gray-50]:hover, .my-component:hover {
  --bg-opacity: 1;
  background-color: rgba(248, 250, 252, var(--bg-opacity));
}
```
Being able to extend a class without writing a `.` and a `,` just makes it more friendly and readable:
```sass
// Current Syntax
.my-component
  @extend .flex, .ai-center, .jc-between

// Desired Syntax
.my-component
  @extend flex ai-center jc-between
```
It is not a big deal but it's a nice thing to have. We can have both syntaxes and the user can be able to choose the desired one.
