### ISSUE TITLE
Deep-merge function different output

### ISSUE THREAD

**Issue by Lukjuh** [sass/sass#3029]
Hello 👋

Does anyone know why the output of my deep-merge function is different from the example from sass-lang.com?

In my example, the key / values ​​are placed at the end.

**SASS-lang example:**
![image 1 (1)](https://user-images.githubusercontent.com/8874796/111742656-da0ac200-8888-11eb-8a2c-939623868223.jpg)

**My own example**
![Group 4](https://user-images.githubusercontent.com/8874796/111742654-d8d99500-8888-11eb-859d-ef1f177c11de.jpg)

**Comment by Awjin** [comment]
This is expected, since Sass doesn't guarantee a specific ordering of key/values when deep-merging maps.
