### ISSUE TITLE
can't render the @material/icon-button

### ISSUE THREAD

**Issue by HomyeeKing** [sass/sass#3032]
```scss
@use @material/icon-button
```

```js
sass.render({...})
```
![image](https://user-images.githubusercontent.com/49113249/112297499-eea7e980-8cd0-11eb-9dd5-465bc366bee5.png)

**Comment by jathak** [comment]
You need to provide a [load path](https://sass-lang.com/documentation/js-api#includepaths) to the compiler to tell it where to look for non-relative imports. Assuming you've installed the material libraries via NPM, the relevant load path will probably be `node_modules`.
