### ISSUE TITLE
Library Singletons: Pre-configured utilities/functions with @use with * or DI

### ISSUE THREAD

**Issue by coenmooij** [sass/sass#3033]
Hi,

I'm building an open-source scss framework. One of the main concepts is configuration. For example:

```scss
use 'library' with ($darkMode: true);
```
For now I've put just one setting, but imagine an extensive theme configuration object. (e.g. `$configuration: ( etc... )` )

In my `library` I have some `utilities` which use this setting. I have some `components` that use these utilities.

With `@import` this works fine. I can just use the `$darkMode` in my utility like this:
```scss
$darkMode: false !default;

@function background-color() {
  @if $darkMode {
    @return black;
  } @else {
  @return white;
}
```

Now in my `components` I can just use this function like:
```scss
.component {
  background-color: background-color();
}
etc...
```

Now `@import` is going away, so I want to build my library with `@use` & `@forward`.

To make this work I need to:
```scss
// library.scss
$darkMode: false !default;
@use 'utilities' with ($darkMode: $darkMode);
@use 'components' with ($utilities: utilities);
```
```scss
// components.scss
$utilities: () !default;
@use 'button' with ($utilities: $utilities);
```
I have to specify my dependencies and the deeper I go, I keep having to send my `props` around. Mind you, this is just an example with 1 setting, imagine a situation with complete theme settings.

In front-end frameworks, we solve this with Dependency Injection where we have the framework manage a singleton that we can inject and configure. So Ideally in scss this would look like:

```scss
// library.scss
$darkMode: false !default;
@use 'utilities' with ($darkMode: $darkMode);
@forward 'components';
```
```scss
// button.scss
@use 'utilities';
```

Maybe it is not 'good practice' and I see some comments that boil down to: `You shouldn't do it like that` but honestly it is very verbose and a little frustrating too. I believe there is value in `@import` (or something similar like `@use with *` so we can keep our files separated easily without losing configuration and sharing variables. The current situation with `@use` & `@forward` is progress but I think it is not mature enough yet for deprecating `@import` unless there are ways to make things straightforward for us developers. Would love to hear some opinions, as well as suggestions to solve otherwise or how we can implement something in sass.

The `@use with *` (which is basically an `@import`) or have some way to cascade scope into child `@use` statements. Or `@forward with ()`

**Comment by coenmooij** [comment]
I wanted to add the example of what I'm dealing with now:
```scss
$base: null !default;
$modifiers: null !default;
$colors: null !default;
$color-options: null !default;
$fill-types: null !default;
$fill-options: null !default;
$elevations: null !default;
$elevation-options: null !default;
$margins: null !default;
$margin-options: null !default;
$paddings: null !default;
$padding-options: null !default;
$sizes: null !default;
$size-options: null !default;
$widths: null !default;
$width-options: null !default;
$corners: null !default;
$corner-options: null !default;
$borders: null !default;
$border-options: null !default;
$focus-types: null !default;
$focus-options: null !default;
$disabled-types: null !default;
$disabled-options: null !default;
$breakpoints: null !default;
$breakpoint-options: null !default;
$case-options: null !default;
$hover-options: null !default;
$active-options: null !default;
$alignment-options: null !default;
$position-options: null !default;
$highlight-options: null !default;
$options: null !default;
$components: null !default;
$types: null !default;
$configuration: null !default;
$themes: null !default;
);

@use 'configuration/normalize' with (
$base: $base,
$modifiers: $modifiers,
$colors: $colors,
$color-options: $color-options,
$fill-types: $fill-types,
$fill-options: $fill-options,
$elevations: $elevations,
$elevation-options: $elevation-options,
$margins: $margins,
$margin-options: $margin-options,
$paddings: $paddings,
$padding-options: $padding-options,
$sizes: $sizes,
$size-options: $size-options,
$widths: $widths,
$width-options: $width-options,
$corners: $corners,
$corner-options: $corner-options,
$borders: $borders,
$border-options: $border-options,
$focus-types: $focus-types,
$focus-options: $focus-options,
$disabled-types: $disabled-types,
$disabled-options: $disabled-options,
$breakpoints: $breakpoints,
$breakpoint-options: $breakpoint-options,
$case-options: $case-options,
$hover-options: $hover-options,
$active-options: $active-options,
$alignment-options: $alignment-options,
$position-options: $position-options,
$highlight-options: $highlight-options,
$options: $options,
$components: $components,
$types: $types,
$configuration: $configuration,
$themes: $themes
);
```

**Comment by mirisuzanne** [comment]
The `with` clause is designed for the much narrower use-case of setting `!default` values on first-load. If you find yourself using it simply to access variables from another file, you probably want to switch the direction of that dependency. In this case, `normalize` wants to `use` the configuration variables, and not the other way around:

```scss
// # configuration/variables.scss
$base: null !default;
$modifiers: null !default;
$colors: null !default;
$color-options: null !default; 
// etc…

// # configuration/_normalize.scss
@use 'configuration/variables' as *;
```

Now you have access to all of the configuration settings inside `normalize`, without any duplication or explicit `with` statements.

Similarly, `@use 'components' with ($utilities: utilities);` can be simplified by having the `components` partial `@use 'utilities';`

**Comment by coenmooij** [comment]
Hi @mirisuzanne ,
Thanks for your reply. Unfortunately the 'variables' part is something outside of the library. So the user of this library will define all these variables. But I can make my example clearer:

```scss
// style.scss (outside the library)

$colors: (primary: blue, secondary: red);
$margins: (small: 1rem, big:2rem);

// npm package
@use '~@organisation/package/library' with ($colors: $colors, $margins: $margins);
```

Then inside the library:
```scss
// _index.scss (entry point of library)

$colors: null !default;
$margins: null !default;

@use 'normalize' with ($colors: $colors, $margins: $margins);

// Some actual instructions
@include theme(normalize.$theme);
```

So I could reverse it.. but then it becomes really weird as to how the $theme is getting inside the function? And I would have to put a @use statement both ways to make sure it is included?

Hope this makes my situation clearer. The library is configurable from the outside. This is the core idea to have it configurable and easy to use for the library user.

Monday my current refactor will be done so I can pass a link to the project as well.

(btw @mirisuzanne I'm using 'sass-true' and its awesome :) )

**Comment by mirisuzanne** [comment]
Hi @coenmooij (glad you like True!)

I would organize the library something more like this:

```scss
// # _config.scss
$colors: null !default;
$margins: null !default;

// # _normalize.scss
@use 'config'; // now normalize has access to the variables from config …

// # _index.scss (entry point)
@forward 'config'; // allow the user to configure first
@use 'normalize'; // … already configured by the user, because it relies on config
@include theme(normalize.$theme);
```

In the old system that would be weird to `@import` the config file multiple places, almost in a loop. But this is the purpose of the new module system. Each file can reference all the files it relies on. The entry point doesn't need to handle relationships between other files (importing one, exporting it to the other) – it's only focused on what needs to be passed along to the user or output.

---

Aside, personal preference, I'd also encourage users not to duplicate all the variables - defining them and then passing them as two steps. Ideally they just configure the variables in the library and then use those variables if they need. So: 

```scss
// style.scss (outside the library)
// npm package
@use '~@organisation/package/library' with (
  $colors: (primary: blue, secondary: red),
  $margins: (small: 1rem, big:2rem),
);
```
