### ISSUE TITLE
Media query results in broken logic

### ISSUE THREAD

**Issue by jpduckwo** [sass/sass#3035]
Hi, I'm trying to put in a browser hack to target only chrome (don't ask!) using a media query as follows (scss)

```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
  .something {
    // rules
  }
}
```

However I can't seem to stop if from breaking the two 'and's into separate media queries which breaks the logic completely

It compiles to:
```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (-webkit-min-device-pixel-ratio: 0), screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm)
.something {
    // rules
}
```

As far as I can see there is no way to stop this behaviour, is this a bug? Or can I structure my scss to output how I want it?

**Comment by jathak** [comment]
I can't seem to replicate this with the latest version of Dart Sass. What compiler and version are you using? Does it work if you replace `// rules` with a simple example like `color: blue;`?

**Comment by jpduckwo** [comment]
Hey @jathak, this is inside an Angular project which is using npm package sass@1.32.6. However I think it's not Sass and possibly PostCSS that is breaking it. I'll investigate more closing for now! Thanks!
