### ISSUE TITLE
Sass not working

### ISSUE THREAD

**Issue by xItzDiamondx** [sass/sass#3042]
I'm developing on VS Code with SCSS installed. For some reason, it isn't working

Please help.

Link: [Dark Mode](https://github.com/xItzDiamondx/dark-mode)

**Comment by xItzDiamondx** [comment]
Site: http://bit.ly/SiteDarkMode

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large. To get a helpful answer from StackOverflow, I'd encourage you to add more details to your question, like what problem you are trying to solve, and which sections of your Sass code are actively breaking.
