### ISSUE TITLE
Sass: Where are you sailing?

### ISSUE THREAD

**Issue by KoenigAlfonz** [sass/sass#3045]
**First of all**, I want to mention, that sass has been and still is an incredible good tool, with what we can build very sophisticated and exciting stuff. Bravo!!

There have been some little issues though, that were causing me head-scratches from time to time.
For example, we get missleading informations about features like **variable interpolation** or **mixin/function interpolation** as seen in these topics:

<https://stackoverflow.com/questions/15748937/how-to-define-a-dynamic-mixin-or-function-name-in-sass>

<https://github.com/sass/sass/issues/857> <https://github.com/sass/sass/issues/626> <https://github.com/sass/sass/pull/2057>

So as of now I am pretty confused on what exactly is possible now and I am yet to find a Sass-version that supports any of those features.
Some clarification here would be very welcome!

Another thing I noticed is, that the current Sass version does no longer seem to support **interpolation when extending placeholder-selectors**, which is especially unfortunate since my **css-framework** is heavily relying on that feature.
(With it, we can pretty much mimic all of the functionality of e.g. **tailwind-css**, without it, everything falls apart)

    @extend %#{$some-variable};
    // now throws an error saying: compound selectors can no longer be extended

These **interpolation features** are things that **we (advanced sass users) actually need**.
I think that the focus is on the wrong things here. Let's take the new **Sass modules** for example: While this is a cool feature, (don't get me wrong) it is only solving one little problem, that can be easily worked around, unlike the other features mentioned above.

So be it as it is, I am forced to use the old sass-version for the time-being.
**I would love** to see the current Sass-version catching up though.

Feel free to correct me and/or join the discussion.

Cheers!

**Comment by jathak** [comment]
Interoplation within `@extend` is allowed. The issue is that, in your case, `$some-variable` contains a compound selector, which is not allowed to be extended.

**Comment by KoenigAlfonz** [comment]
@jathak Well, obviously **NOT**! That variable is just containing a string like 'padding-4' or 'color-primary'. So the resulting placeholder would look like this: '%color-primary'.

As far as  I am concerned compound selectors are looking like that:: '.something .something-else'.
In fact, I've never tried to extend a compound-selector since that is an extremely rare usecase.

And **No**, no matter how often I try, interoplation within @extend seems not to be working. At least not in dart-sass.

**Also, I don't understand, why this issue has been closed, when it is containing feature requests that have been asked for multiple times. Plus that was no answer to my question of what Sass is actually supporting now.**

**Comment by jathak** [comment]
If `$some-variable` is something like `color-primary`, then `@extend %#{$some-variable}` works fine (just tested in the latest Dart Sass).

Can you provide a minimal reproduction where you're getting an error for this case?

**Comment by KoenigAlfonz** [comment]
Ok, so after researching, I've found out that there is a problem with **pseudo-classes** (because they have a **colon**). I'm not exactly sure, if selectors with a pseudo-class are considered compound selectors. If yes, then a colon in the variable string is causing the problem.

Here is the thing:
I want to update my tailwind-css-like sass environment to be able to run with dart-sass.

I've got the following mixin
`// extend properties
@mixin properties($properties...) {  
    @each $propertyString in $properties {
        $split: stringSplit($propertyString, ' ');
        @each $property in $split {
            $test: escapeColon($property);
            @extend %#{$test};
        }
    }
}`

(Sorry for the bad formatting, but I don't know how to make line breaks here)

and the following usage of the mixin
`.container {
    @include properties('max-container-x mx-auto px-2 m:px-3 l:px-4');
}`

Creating the placeholder-selectors is done somewhere else without problems, but the compiling stops at `m:px-3` saying `compound selectors can no longer be extended`.

I can work around that by escaping the colons, but I don't want to write double backslashes all over the place (and certainly not go over old projects looking out for every colon), so I came up with a simple string-replace function `escapeColon()`, but it seems like Sass is running the line  `@extend %#{$test};` before `$test: escapeColon($property);` (in reverse order) which is very confusing to me.

**Error**: `expected selector @extend %str-replace("m:px-3", ":", "\\:") not found`

After all, it's very unfortunate that everything fails only because of one character.

Thanks.


**I'm still interested in knowing something about variable interpolation or mixin/function interpolation. Sorry for the reopening but I'm not sure, why this issue was closed in the first place.**

**Comment by thiagomajesk** [comment]
Hi @KoenigAlfonz! I think there's a lot of valid points on questioning the direction Sass is going, and given that there are some substantial issues opened/ closed regarding extending/ expanding the language I think it's completely valid. 

I can't answer about the technical limitations you are facing, but I'm seeing you're trying to port some of the Tailwind utilities to Sass. This is something that I've attempted before and fell into the same traps - which feels frustrating. One of the problems I faced is with the state modifiers because each colon has to be escaped. I don't know if it helps, but you can take a look at this repo that uses Bootstrap API to generate Tailwind utilities: https://github.com/thiagomajesk/bootilities.

**Comment by KoenigAlfonz** [comment]
@thiagomajesk Thanks a lot! I'll definitely have a look into it.
The thing is, that I could actually accomplish most of the Tailwind features with LibSass. I'm just having trouble to get it to work with dart-sass and as LibSass may not be supported at some point in the future, I'm afraid to get decoupled then.

@thiagomajesk  If you're interested in my Sass environment, you can contact me at `m.krzywinski@gmx.de`

I did not want to only blame Sass and as these features regarding interpolation have been talked about a lot, the devs might be tired of hearing it. I'm just not getting why, at some points, it was mentioned, that features like that have been added, when I can't find that anywhere and nobody can explain to me, where it got added in.
I mean, I'd understand if someone would only say, that core sass was not designed with that in mind and it would be a ton of work to change it.

That's why I was asking for clarification.

**Comment by jathak** [comment]
Variable and mixin interpolation isn't something we're going to support. These sorts of dynamic references make code difficult to read and maintain, and supporting them in the compiler would be detrimental to performance. If you need to dynamically reference values, we recommend using a [map](https://sass-lang.com/documentation/values/maps) instead.

**Comment by KoenigAlfonz** [comment]
Ok, thank you!

So reflecting on what you just said:

1. Mixin interpolation was never, and still is not planned because it would be difficult to read and maintain (that's debatable :)) and be bad for performance.
2. Dynamic mixin invocation in the way described here #2057 was added, but dropped again, due to performance issues.
3. Dynamic mixin invocation just like the `call($function-name)` is still planned and will be added at some point in the future!?
