### ISSUE TITLE
Error: is not a color; storing and reading color values from .json

### ISSUE THREAD

**Issue by nachtfunke** [sass/sass#3046]
I am running into a rather serious issue since updating to dart-sass. I am working with a project that stores all of its color information in `.json` files that get converted into sass-maps via [rootbeer](https://github.com/gkatsev/rootbeer). Functions then use `map-get` to retrieve these values and then return their value unquoted to be used as color in CSS and for all other types of color thingies. Since updating though, working with functions like `transparenize()`, or `lightness()` causes the compiling to crash, because they can only be used on colors.

I understand why this is happening, but it basically breaks my entire process of having single source of truth for the project's colors. JSON does not understand color values. I cannot put any color format there any longer, because of this. Even if I were to split the color strings into seperate values for rgb or hsl, I cannot call `color.lightness()` or `color.red()` on them to maybe combine them into a valid color, because I cannot call these functions on non-color typed values.

What is the way to go forward here? Ideally I could just somehow _tell_ sass that whatever is being passed is actually a color, not a string. But that is not possible at the moment. So I a truly don't know what to do here.

**Comment by jathak** [comment]
This sounds like a bug in rootbeer, where it's not correctly converting colors in your json into Sass color literals. You should file an issue with it.

**Comment by nachtfunke** [comment]
> This sounds like a bug in rootbeer, where it's not correctly converting colors in your json into Sass color literals. You should file an issue with it.

I have, thank you.
