### ISSUE TITLE
Error thrown when assigning url() to a custom property

### ISSUE THREAD

**Issue by OliverBrotchie** [sass/sass#3047]
Example:
`--n: url('Some Url')`

This is valid CSS however it throws this error during compilation:
> Error: Invalid CSS after " ": expected "}", was "url('Some Url')"

**Comment by jathak** [comment]
What Sass compiler and version are you using? I'm not able to replicate this error on the latest version of Dart Sass

**Comment by milahu** [comment]
same error with `Ruby Sass 3.7.4`
works with `dart-sass 1.77.0`

**Comment by nex3** [comment]
Ruby Sass has reached [end of life](https://sass-lang.com/blog/ruby-sass-is-unsupported/), and is no longer supported. Please switch to another implementation as soon as possible to ensure that you'll remain up-to-date with the latest features and CSS support.
