### ISSUE TITLE
@supports/@document/@keyframes bubbling

### ISSUE THREAD

**Issue by nex3** [sass/sass#305]
`@supports` and `@document` should support `@media`-style bubbling. For `@document` merging multiple rules isn't possible, but for `@supports` it is.

**Comment by nex3** [comment]
According to [the spec](http://dev.w3.org/csswg/css3-conditional/), `@support` and `@document` support nesting in native CSS, so merging the rules is unnecessary.

**Comment by chriseppstein** [comment]
@keyframes too ^_^

**Comment by brewster1134** [comment]
created new issue https://github.com/nex3/sass/issues/621

**Comment by nex3** [comment]
Bubbling has been supported by default for at-rules for a while.
