### ISSUE TITLE
Stray double quote in variable output

### ISSUE THREAD

**Issue by b9chris** [sass/sass#3053]
This file:

```
@import '../../../../../core/static/core/ui/css/contrib/bootstrap/_variables.scss';
@import '../../../../../core/static/core/ui/css/bootstrap_variable_overrides.scss';


#gap-sm {
	height: 100px;
}



#signupForm {
	div.explain {
		color: #006499;
		font-size: 12px;
		margin-bottom: 30px;
	}
}

#features {
	details {
		background: url("/static/profile/ui/img/asideicons.png") no-repeat;
	}
}


@media(min-width: $screen-sm-min) {
	#bodyContent {
		margin-top: 300px;
	}

	#title {
		margin-top: -230px;
		color: #fff;
	}

	#signupForm {
		margin-top: -150px;
		background: #fff;
		padding: 15px;
		border-radius: 10px;

	}
}
```

Results in this, erroneous output:

```
#gap-sm {
    height: 100px
}

#signupForm div.explain {
    color: #006499;
    font-size: 12px;
    margin-bottom: 30px
}

#features details {
    background: url("/static/profile/ui/img/asideicons.png") no-repeat
}

@media(min-width: 768px"){#bodyContent{margin-top:300px}#title{margin-top:-230px;color:#fff}#signupForm{margin-top:-150px;background:#fff;padding:15px;border-radius:10px}}/*# sourceMappingURL=signup.css.map */
```

The above output is prettified to make the stray double quote jump out at you (in the @media line at the bottom, before everything else remains minified), but here's the original, exact output it produces:

`#gap-sm{height:100px}#signupForm div.explain{color:#006499;font-size:12px;margin-bottom:30px}#features details{background:url("/static/profile/ui/img/asideicons.png") no-repeat}@media(min-width: 768px"){#bodyContent{margin-top:300px}#title{margin-top:-230px;color:#fff}#signupForm{margin-top:-150px;background:#fff;padding:15px;border-radius:10px}}/*# sourceMappingURL=signup.css.map */`

**Comment by b9chris** [comment]
Actually, ignore this - this appears to be further up the chain in a Python package calling this npm package.

**Comment by mirisuzanne** [comment]
It's hard to debug this without seeing the definition of `$screen-sm-min` -- which I assume is happening inside `bootstrap_variable_overrides.scss`? Most likely, that's where the extra quote is coming from.
