### ISSUE TITLE
global module isn't shadowed as expected

### ISSUE THREAD

**Issue by fivegreenapples** [sass/sass#3058]
Scenario:
```
// lib.scss
$color: green;


// one.scss
@use "lib.scss" as *;
$color: red;
.red {
    color: $color;
}

// two.scss
@use "lib.scss" as *;
.green {
    color: $color;
}

// main.scss
@use "one.scss";
@use "two.scss";
```

After compiling main.scss, my expectation was:
```
.red {
  color: red;
}

.green {
  color: green;
}
```

Actual output is:
```
.red {
  color: red;
}

.green {
  color: red;
}
```

The point here is that the `$color` variable in `one.scss` does not appear to be a shadow, but actually affects the variable defined in `lib.scss` such that when used in `two.scss` it has a new value.

Is this expected or a bug? I couldn't find a definitive source of info on this particular scenario.

**Comment by jathak** [comment]
This is expected. See https://github.com/sass/dart-sass/issues/1308
