### ISSUE TITLE
Sass: Where are you sailing?

### ISSUE THREAD

**Issue by KoenigAlfonz** [sass/sass#3059]
**First of all**, I want to mention, that sass has been and still is an incredible good tool, with what we can build very sophisticated and exciting stuff. Bravo!!

There have been some little issues though, that were causing me head-scratches from time to time.
For example, we get missleading informations about features like **variable interpolation** or **mixin/function interpolation** as seen in these topics:

<https://stackoverflow.com/questions/15748937/how-to-define-a-dynamic-mixin-or-function-name-in-sass>

<https://github.com/sass/sass/issues/857> <https://github.com/sass/sass/issues/626> <https://github.com/sass/sass/pull/2057>

So as of now I am pretty confused on what exactly is possible now and I am yet to find a Sass-version that supports any of those features.
Some clarification here would be very welcome!

Another thing I noticed is, that the current Sass version does no longer seem to support **interpolation when extending placeholder-selectors**, which is especially unfortunate since my **css-framework** is heavily relying on that feature.
(With it, we can pretty much mimic all of the functionality of e.g. **tailwind-css**, without it, everything falls apart)

    @extend %#{$some-variable};
    // now throws an error saying: compound selectors can no longer be extended

These **interpolation features** are things that **we (advanced sass users) actually need**.
I think that the focus is on the wrong things here. Let's take the new **Sass modules** for example: While this is a cool feature, (don't get me wrong) it is only solving one little problem, that can be easily worked around, unlike the other features mentioned above.

So be it as it is, I am forced to use the old sass-version for the time-being.
**I would love** to see the current Sass-version catching up though.

Feel free to correct me and/or join the discussion.

Cheers!

Here we go again, as this one was probably closed by accident. (#3045)
A simple answer to my questions would be welcome
**NOTE: I did not use a compound selector and I am able to read and understand error messages BY MYSELF**

**Comment by jathak** [comment]
Please do not open duplicate issues.
