### ISSUE TITLE
Clarification about the proposed `meta.module-mixins()` function

### ISSUE THREAD

**Issue by binyamin** [sass/sass#3063]
> :information_source: I opened this issue to find a concise, central point of clarification for state of the `meta.module-mixins()` function. The idea was that other users could refer to this issue for understanding.

I see from [accepted/module-system.changes.md#draft-3](https://github.com/sass/sass/blob/master/accepted/module-system.changes.md#draft-3) that the `meta.module-mixins()` function is on hold "until Sass supports first-class mixins".
1. What are "first-class mixins"?
2. (related) Where can I find references, a proposal, an issue, or even a definition for "first-class mixins"? (I searched the repository on GitHub)
3. Where can I track its status, to know when work can begin on the `meta.module-mixins()` function?
4. Shouldn't the accepted proposal make a note of this blocked feature, so it won't be forgotten?

Also, this feature's siblings `module-functions()` and `module-variables()` are already out. The documentation site should probably say _something_ about `module-mixins()`, even if just "coming ~~soon~~".

**Comment by nex3** [comment]
> 1. What are "first-class mixins"?

This refers to the ability to store mixins as SassScript values, which can be assigned to variables, passed to functions, and so on, the same way you can do with functions today using `meta.get-function()`.

> 2. (related) Where can I find references, a proposal, an issue, or even a definition for "first-class mixins"? (I searched the repository on GitHub)
> 3. Where can I track its status, to know when work can begin on the `meta.module-mixins()` function?

https://github.com/sass/sass/issues/626

> 4. Shouldn't the accepted proposal make a note of this blocked feature, so it won't be forgotten?
> 
> Also, this feature's siblings `module-functions()` and `module-variables()` are already out. The documentation site should probably say _something_ about `module-mixins()`, even if just "coming ~soon~".

We usually avoid describing features that don't exist yet. I think it would be more confusing than it would be valuable to say "eventually this function will exist and it will return a type of object that we don't have any documentation for yet".

**Comment by binyamin** [comment]
> #626

I saw that issue. I meant actual progress updates, without the "hey, you gotta add this" chit-chat. :wink:

**Comment by nex3** [comment]
We'll update that issue when work begins. For now, we're focusing on other work.
