### ISSUE TITLE
Bug with functions not getting evaluated

### ISSUE THREAD

**Issue by KoenigAlfonz** [sass/sass#3064]
So, I've got the following mixin:
```
// extend properties
@mixin properties($properties...) {  
    @each $property in $properties {
        $test: str-replace($property, ":", "\\:");
        // at this point in time, i expect $test to contain 'm\\:px-3' and that getting passed into the extend
        @extend %#{$test};
    }
}
```

and the following usage of the mixin:

```
.container {
    @include properties('m:px-3'); 
}
```

Unfortunately, the str-replace functions is never getting evaluated. Instead the function call is getting passed as String leading to the error below.

**Error**: expected selector @extend %str-replace("m:px-3", ":", "\\:") not found

**Comment by Awjin** [comment]
How is your `str-replace()` function defined?

**Comment by KoenigAlfonz** [comment]
Just like that:
```
@function str-replace($string, $search, $replace: '') {
    $index: str-index($string, $search);
    @if $index {
        @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
    }
    @return $string;
}
```

Does that mean, that it is actually supposed to work? That would be great, because I thought of another problem with extending.
