### ISSUE TITLE
Color-stop as list

### ISSUE THREAD

**Issue by emilbayes** [sass/sass#307]
I was trying to write a linear-gradient mixin that will take the first color stop and set it as the background color. However SASS recognizes my list as a set of color-stops so I can't access the first element with the `nth` function:

```
$colorStopsList: (#fff 20%, #f6f6f6 50%, #eee 50%, #f4f4f4 100%);
$colorStop: nth($colorStops, 1): //Type-of: compass::sassextensions::functions::gradientsupport::colorstop
//$colorStop: #fff 20%
background-color: type-of(nth($colorStop, 1)); //Returns #fff 20%, where #fff was expected
```

I don't know if this is a Compass issue or a Sass issue...

**Comment by chriseppstein** [comment]
I'm pretty confused here. did you close this because you moved it to compass? Or was there some other resolution?

**Comment by emilbayes** [comment]
Well this was my mistake, but I couldn't find any way to remove the issue.

**Comment by chriseppstein** [comment]
Just wanted to make sure it didn't fall through the cracks.
