### ISSUE TITLE
add allowed/legal characters for variable naming to sass docs

### ISSUE THREAD

**Issue by glgoose** [sass/sass#3072]
It seems like the `.` character can't be used in variable names.
![image](https://user-images.githubusercontent.com/48956933/120108022-9d4e2780-c163-11eb-9f32-7af6e0cddad8.png)

I couldn't find anything in the docs about what the allowed characters are for naming variables.

I found [this stackoverflow answer from 2013](https://stackoverflow.com/questions/17191265/legal-characters-for-sass-and-scss-variable-names) for ruby sass referencing a 'lexer' in the source code with regexes for tokenizing, which is outdated now.

**Comment by babakfp** [comment]
You can use:
`$name`
`$name_some`
`$name-some`
`$nameSome`

It's wrong to use `.` character in the variable name.

**Comment by nex3** [comment]
Sass's notion of a valid identifier is the same as [CSS's](https://www.w3.org/TR/css-syntax-3/#identifier). This is described in the [Sass specification](https://github.com/sass/sass/blob/master/spec/variables.md#syntax).

**Comment by glgoose** [comment]
> Sass's notion of a valid identifier is the same as [CSS's](https://www.w3.org/TR/css-syntax-3/#identifier). This is described in the [Sass specification](https://github.com/sass/sass/blob/master/spec/variables.md#syntax).

Thanks for referencing those 2 links.

In the sass specs `<ident-token>` seems to be defined by the following:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/48956933/120537392-861e6c80-c3e5-11eb-8339-3ecef991085b.png">

I wasn't aware of the existence of the [Sass specification](https://github.com/sass/sass/blob/master/spec/variables.md#syntax) here, read through it a couple of times but couldn't find any reference to a valid identifier being the same as in the CSS specification or what characters would be allowed.

I imagine it might be clear for others because they would intuitively apply the same syntax rules as writing a css variable and wouldn't try to write anything that wouldn't also be valid in css.

**Comment by Rafer45** [comment]
Done adding links to the CSS spec in the Sass spec 👍
