### ISSUE TITLE
Nested & turfs to front instead of before selector

### ISSUE THREAD

**Issue by Snugug** [sass/sass#308]
This was unexpected for me, don't know if it's a bug or if I've been thinking this would work and have just never tried it before. If I have the following selectors:

``` scss
.foo {
  .bar {
    .baz & {
  }
}
```

The outcome I expect should be:

```
.foo .baz .bar{}
```

But instead what we get is:

```
.baz .foo .bar()
```

Is this simply a misunderstanding of nested & or is my assumption correct and it's a bug? Either way, thoughts on implementing it? If it's a misunderstanding, this becomes an API change, dunno if we wanna do that (it's just as easy for me to rewrite the selectors, just came across and thought I'd ask).

**Comment by chriseppstein** [comment]
This is working as designed. `&` is the full selector context. We are planning new enhancements to `&` in bug #286.

**Comment by Snugug** [comment]
Cool, thank you.
