### ISSUE TITLE
Encoding content property wrong generation icon code

### ISSUE THREAD

**Issue by ferranmoron** [sass/sass#3084]
I have a problem with this:

.ico-create:before {
    content: "\e933";
}

this generate:

.ico-create:before {
  content: "";
}

My file has encoding UTF-8

I'm using:

const result = sass.renderSync({
                        file: path,
                        outputStyle: 'compressed',
                        sourceMap: false
                    });

Thank you,
Ferran

**Comment by galvarez421** [comment]
https://github.com/sass/sass/issues/659#issuecomment-71759457 may help you if you are able/willing to change the source 🙂.

**Comment by ferranmoron** [comment]
Thank you very much @galvarez421 , this is exactly what I needed
