### ISSUE TITLE
Avoid Duplicate Css When Import Scss File Into Another Scss file

### ISSUE THREAD

**Issue by khoas9** [sass/sass#3086]
I use Web Compiler to compile scss file to css file and i have some problems with it.
I have a common.scss file located in wwwroot and i also define some variables, mixin, class in here
// common.scss
@mixin buttons($bg-color, $color) {
    border: none !important;
    box-shadow: $box-shadow !important;
    border-radius: $border-radius !important;
    background-color: $bg-color !important;
    color: $color !important;
}
.primary-btn {
    @include buttons($primary-blue, $white);

    &:focus {
        outline: $outline !important;
    }

    &:active {
        outline: $outline !important;
    }
}
And in another  component.scss i use @import "../../wwwroot/scss/common.scss" to reuse these variable but all class i define in common.scss is also import to my component.scss too. So how can i ignore these class, i just want to use only variables in common.scss.

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
