### ISSUE TITLE
Proposal: mixin enhancements 

### ISSUE THREAD

**Issue by Atulin** [sass/sass#3087]
## 1. Short syntax

One of the things I love about the indented SASS syntax is short syntax mixins with `=` and `+`. Would it be possible to bring them to brace-syntax SCSS?

## 2. Multiple mixins

Far as I know, to use multiple mixins i need to use

```scss
.foo {
  @include mixin_one;
  @include mixin_two;
} 
```

I believe it would be a good idea to allow single-line syntax for multiple mixins at once, like so:

```scss
.foo {
  @include mixin_one mixin_two;
} 
```

With or without a comma separating mixins.

This in particular would allow for an easy way to create a large library of tiny mixins, Tailwind style, and for using them in a painless way.

**Comment by jathak** [comment]
For the shorthand mixin syntax, this isn't something we ever plan to support in the SCSS syntax. It's not immediately clear to users what `=` and `+` mean, and if we were designing the indented syntax today, we wouldn't include more than one way to declare/include a mixin.

The multiple mixin syntax is something worth considering, but there are some issues we'd need to address / mitigate before adding new syntax to the language:

1. Code `@include mixin_one mixin_two mixin_three` makes some sense when none of the mixins have arguments, but how would this feature interact with mixins with arguments or (especially) content blocks?
2. Having multiple ways of doing the same thing is a design smell that we generally try to avoid. We'd probably need a stronger argument for adding this syntax than just "it's shorter than the alternative".

**Comment by Atulin** [comment]
The motivation behind this issue was an attempt to introduce something akin to Tailwind's `@apply`, except one that allows users to build their own collection of building blocks they can later apply to their classes. I admit, I did not consider mixins with arguments and content blocks.

Now, I see two ways of achieving the initial intent behind this issue:
1. Don't allow mixins with content blocks to be used, mixins with params still fit the syntax: `@include mixin1 mixin2(3px) mixin3`
2. Instead of single-line mixins, perhaps single-line `@extend` would be a better idea: `@extend .pad-1 .mg-3 .text-red` style

**Comment by nex3** [comment]
You can already write a single-line `@extend` as `@extend .pad-1, .mg-3, .text-red`. That said, using extend for non-semantic classes is generally not recommended.
