### ISSUE TITLE
Intelligent removal of duplicate properties when compiling

### ISSUE THREAD

**Issue by necolas** [sass/sass#309]
Would be great to not have duplicate properties output in the compiled CSS, as they currently are:

![](http://f.cl.ly/items/2e2B1P3G1v0q0z0v1H3E/Screen%20Shot%202012-03-05%20at%204.52.46%20PM.png)

This would be good for including defaults in mixin that you can override later. Simple example:

```
@mixin btn-template {
    position: relative;
    display: inline-block;
    padding: 5px;
    border: 1px solid #ccc;
    margin: 0;
    text-align: center;
    text-decoration: none;
    white-space: nowrap;
    cursor: pointer;
}

.btn {
    @include btn-template;
    padding: 5px 10px;
    border: 2px solid #555;
}
```

...the CSS produced from this would include 2 `padding` and 2 `border` declarations, where you'd prefer to only have one of each.

**Comment by nex3** [comment]
Subset of #116.

**Comment by necolas** [comment]
None of those examples are of duplicate properties within the same declaration block. This is an example that, IMO, is distinct (if related) from trying to optimise separate selector blocks by merging them or combine different properties into a single property - both of which can be quite dangerous optimisations and probably require more work to achieve. I hope you will consider this smaller problem as something that would be beneficial and without drawbacks.

**Comment by chriseppstein** [comment]
One must be very careful, duplicated properties are basically the only approach to x-browser support. How can we know this isn't because `blue` isn't supported and `red` is the fallback value?

I think @nex3's idea is to use mixin boundaries to decide whether to keep or not, but this would break if the "duplication" was actually building on the concept of the previous mixin call, not overwriting it.

**Comment by chriseppstein** [comment]
Maybe if it was explicit: `padding: 5px 10px !replace;`

**Comment by necolas** [comment]
> duplicated properties are basically the only approach to x-browser support

Good point!

**Comment by nex3** [comment]
@necolas Your mixin example is very close to the "ignore overridden declarations" example in #116.

@chriseppstein I think using `!replace` removes some substantial benefits of this approach. Part of the goal is that it can work together with other optimizations to remove unnecessary properties that the user may not realize are redundant. `!replace` relies on the user to effectively do that work themselves.

I think a better way to avoid the issue would be to make cross-context fallbacks explicit. I think they're a much less frequent use case. A solution to #249 might provide an answer here.

**Comment by necolas** [comment]
> I think a better way to avoid the issue would be to make cross-context fallbacks explicit

A problem with that approach is that it's the opposite of how CSS behaves (i.e., you break user expectations from their experiences working with CSS), and these fallbacks are used relatively frequently when working with `background` and CSS gradients. It's a harder problem than I initially realised when working with a simple mixin. Thanks for exploring the options.

**Comment by nex3** [comment]
I'm not sure what you mean by "the opposite of how CSS behaves." CSS always uses "last property wins," with unknown values being ignored to support cross-browser stuff.

**Comment by necolas** [comment]
Yes, so if you have multiple property declarations, then some of them can act as fallbacks for browsers that do not understand subsequent property values. Therefore, you shouldn't drop earlier appearances of a property because you cannot know which ones may be intentional fallbacks. Forcing people to explicitly label them as fallbacks is not something CSS authors would expect to do.

**Comment by nex3** [comment]
I think the heuristic of only eliminating redefined properties across mixins will mean that explicit fallbacks will be few and far between. Have you ever used a fallback across mixins in practice?
