### ISSUE TITLE
Convert Sass variables to CSS variables

### ISSUE THREAD

**Issue by ghost** [sass/sass#3091]
We all know how are variables important. They are everywhere. JavaScript, C#, Java, Python... Should I continue?
CSS has them too! Introduced in 2012. There are however enormous differences between Sass and CSS variables.

## Syntax
```css
:root {
  --color-primary: hsl(44, 80%, 100%);
}
a {
  color: var(--color-primary);
}
```
C'mon, that's ugly! I don't want to write this every time I use a variable. That's why I use Sass right? Well, sort of. Here's the catch.

## Dynamics
All variables defined in CSS can be changed in runtime through JavaScript.
```javascript
document.querySelector(':root').style.setProperty('--color-primary', 'hsl(280, 60%, 40%)')
```
But Sass variables are **not** dynamic. What a shame!
This could bring you opportunities like super-easy Dark mode.

It turns out that there is a possibility to have dynamic Sass variables. The implementation shouldn't be that hard. Just compile `$primary` to `var(--primary)` and CSS will do the work for us!
Honestly, it seems that I wasn't the first to have this idea. [Sass-to-css-variables](https://github.com/samuelthomps0n/sass-to-css-variables#readme "GitHub") have already implemented that; however, I'm not sure about this project as it has been updated 4 years ago. A Sass function mentioned in [this article](https://codepen.io/jakealbaugh/post/css4-variables-and-sass#working-together-3 "CodePen") could also solve the problem, but I would be much happier if this feature was simply integrated. It would help so many people.

See how many articles lacking this feature have been written. Google is [full](https://google.com/search?q=dark+mode+in+sass "Google") of them.

- [**How to create a dark mode in sass**](https://medium.com/@katiemctigue/how-to-create-a-dark-mode-in-sass-609f131a3995 "Medium") *by Katie McTigue*

  > I don’t know if this speaks to my inability to understand Sass, or to Sass’s inability to anticipate developer needs, but the fact is Sass compiles to good ole css — it’s a preprocessor and not a full-fledged language. Therefore it can’t just swap all your variables on the fly after it is already compiled.

  Well, **it turns out it can!** And I'm full of hope.

- [**Dark Mode with Sass and CSS variables**](https://dev.to/zetareticoli/dark-mode-with-sass-and-css-variables-4f9b "DEV Community") *by Francesco Improta*

  > Implementing dark mode with Sass is hard because it is a preprocessor language. Any changes implies a new generating process and a page refresh. Therefore it is impossible to switch from light to dark - or the way around - in real time

  **Not true** from now on. Hopefully...

- [**Add dark mode support on your website with SASS**](https://www.fabrizioduroni.it/2020/05/20/dark-mode-css-sass-scss/ "Fabrizio Duroni") *by Fabrizio Duroni*

  He did it too, but the **longest** way possible.

**Comment by mirisuzanne** [comment]
Sadly, there is not any way to "make Sass variables dynamic", because Sass itself is pre-compiled, while CSS is interpreted by the browser (dynamically) at runtime. That's not an oversight, or a mistake – only the browser engine _can_ handle the dynamic interactions required.

CSS Custom Properties are dynamic _because they are computed at runtime by the browser_, just like any other CSS property, with full knowledge of the DOM, Cascading, & Inheritance. Sass has no access to the DOM, and no way to manage that cascade or inheritance. CSS Custom properties & Sass variables are fundamentally different, in a way that can't be merged… 

But it's true that _converting_ Sass variables into CSS custom properties can be very useful, and there are a lot of great approaches for doing it. If you want them set on the root (`html`), I recommend using loops on all the variables in a module, so you don't have to write it out one variable at a time. Here's some code to output both dark and light-mode variables:

```scss
@use 'path/to/my/darkmode';
@use 'path/to/my/lightmode';
@use 'sass:meta';

html {
  @each $name, $value in meta.module-variables("lightmode") {
    --#{$name}: #{$value};
  }

  @media (prefers-color-scheme: dark) {
    @each $name, $value in meta.module-variables("darkmode") {
      --#{$name}: #{$value};
    }
  }
}
```

**Comment by ghost** [comment]
I'm very thankful for the `meta.module-variables` function, but I see I was a bit unclear.
This is more a **feature request** rather than an issue. You've made a great workaround as many others did but compiling Sass variables to CSS variables makes much more sense to me  than just parsing the variable value. Wouldn't it be better to have dynamic variables?

**Comment by mirisuzanne** [comment]
@LukoFoks I understand, and yes, that would be great. But it's sadly not possible, and there is no way for us to make it possible. The only way to have variables react dynamically in the browser, is to use variables in a native browser language – and that means CSS. You can think of it like the difference between server-side JavaScript and client-side JavaScript. Sass is a server-side version of CSS. While Sass acts as a proving-ground for many new CSS features (including variables!), Sass itself does not run in the browser, and therefor cannot be dynamic. That's not something that we can change.

**Comment by ghost** [comment]
@mirisuzanne thank you for your patience. I understand that Sass is just a preprocessor and that it can't be dynamic.

> The only way to have variables react dynamically in the browser, is to use variables in a native browser language – and that means CSS.

Yes and that's exactly what I mean!
> But it's sadly not possible

So you mean that it is not possible to compile Sass into CSS this way:
**Input**
```sass
:root
  $variable: #fff

a
  color: $variable
```
**Output**
```css
:root {
  --variable: #fff;
}

a {
  color: var(--variable);
}
```
I can't see much difficulty.

**Comment by mirisuzanne** [comment]
Sure, it would be possible to create CSS variables out of Sass variables, but it is not reasonable to assume that _all Sass variables belong in CSS_. The two types of variable work in fundamentally different ways, so it's important that authors maintain control of both:

- What Sass variables are added to CSS, and when
- When they want the Sass (lexical scope) value, and when they want the CSS value (cascade scope)

That's already possible for authors to do, as we've discussed above. But any magical automation of that process would take away author control, and add a lot of confusion between the two variable types. What is the following output?

```scss
:root {
  $variable: #fff;
}

$variable: red;

a {
  color: $variable;
}
```

It's much more clear if you use a distinct syntax for the two types of variable, and it allows you to determine as an author how the two types should interact:

```scss
:root {
  --variable: #fff;
}

$variable: red;

a {
  color: var(--variable, ${$variable});
}
```

**Comment by ghost** [comment]
> Sure, it would be possible to create CSS variables out of Sass variables.

Great, that's what I thought!

> But it would add a lot of confusion between the two variable types.

As you said, there are currently two options:

### CSS variable
- [x] Dynamic
- [ ] Amazing syntax

### Sass variable
- [x] Amazing syntax
- [ ] Dynamic

But for what reason would you need both variable types with disadvantages instead of **one without** any **disadvantage**?
### Sass to CSS variable
- [x] Amazing syntax
- [x] Dynamic

This would be an upgrade as well as a unification. After Sass variables compile to CSS variables they achieve dynamics with a beautiful syntax. CSS variables aren't needed anymore as Sass variables actually are CSS variables.
<br/>
> The two types of variable work in fundamentally different ways.

No doubt. Let's take a look how their scope differes.

### Sass
- Global variables
  - Declared at top level
  - Acessible everywhere
- Local variables
  - Declared inside blocks
  - Acessible inside block
  - Override global variables
### CSS
- Parent variables
  - Declared inside blocks
  - Acessible inside block and its childs
- Child variables
  - Declared inside blocks
  - Acessible inside block and its childs
  -  Override parent variables
 
Yes, they are different.

```sass
:root
  $variable: #fff

$variable: red

a
  color: $variable
```

The `$variable` output would not be `red` as CSS variables need to be declared within a block. But that doesn't mean we must only use CSS variable types. The power of preprocessor could think of a global variable too. A solution would be to look for top level variables and compile them to `:root`. Which means no `:root` would be ever again needed in our code.

```sass
$variable: #fff

a
  $variable: red
  color: $variable
```
Compiles to:
```css
:root {
  --variable: #fff;
}

a {
  --variable: red;
  color: var(--variable);
}
```
Here `$variable` successfully outputs to `red`. As you can see CSS variables don't have a bad scope system.
*Btw:* Compiling top level variables to `:root` was only an idea. It can always be written to `html` for example.

**Comment by jasonteunissen** [comment]
I'm running into the same issue.
you can put css-variables into sass variables.
the issue I am having is automating this process.

```
$var: (
'hulk':     green,
'spider':   red,
'bat':      black
);

:root{
    @each $name, $color in $var {
        --#{$name}: #{$color};
    }
}

@each $name, $color in $var {
    #{'$'}#{$name}: --#{$name};
}

.card{
    color: $hulk;
}
```

**Comment by ghost** [comment]
It's great that you're trying to achieve it @jasonteunissen but I got bad news for you.
You **cannot** achieve it.

What you are doing here
```scss
#{'$'}#{$name}: --#{$name};
```
is called _Dynamically created variable_. That is not possible in Sass according to #1450. Therefore an automatically defined 
 CSS variable in the code by @mirisuzanne 
```scss
@each $name, $value in meta.module-variables("lightmode") {
    --#{$name}: #{$value};
}
```
can only be used dynamically with the ugly CSS variable syntax `var(--name)`.

The reality that Sass variable are not dynamic makes them much **less powerful** and I'm still keeping fingers crossed 🤞 to make them also a [syntactic sugar][1] for CSS variables.

[1]: https://en.wikipedia.org/wiki/Syntactic_sugar#:~:text=In%20computer%20science%2C%20syntactic%20sugar,to%20read%20or%20to%20express. "Wikipedia"

**Comment by jackgreentemp** [comment]
> It's great that you're trying to achieve it @jasonteunissen but I got bad news for you. You **cannot** achieve it.
> 
> What you are doing here
> 
> ```css-scss
> #{'$'}#{$name}: --#{$name};
> ```
> 
> is called _Dynamically created variable_. That is not possible in Sass according to #1450. Therefore an automatically defined CSS variable in the code by @mirisuzanne
> 
> ```css-scss
> @each $name, $value in meta.module-variables("lightmode") {
>     --#{$name}: #{$value};
> }
> ```
> 
> can only be used dynamically with the ugly CSS variable syntax `var(--name)`.
> 
> The reality that Sass variable are not dynamic makes them much **less powerful** and I'm still keeping fingers crossed 🤞 to make them also a [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar#:~:text=In%20computer%20science%2C%20syntactic%20sugar,to%20read%20or%20to%20express.) for CSS variables.

I found something weird. Variable name is "$eed_color_base_black_1" in other scss file， the variable name would become "eed-color-base-black-1"  when using `@each $name, $value in meta.module-variables`. How to fix this?

demo link: https://codesandbox.io/s/bitter-water-iqfox5?file=/src/styles.scss

**Comment by sebasasa** [comment]
Who closed this, the feature was never added, neither were reasons given as to why this very very useful feature was decided to not be implemented

**Comment by jathak** [comment]
> I found something weird. Variable name is "$eed_color_base_black_1" in other scss file， the variable name would become "eed-color-base-black-1" when using `@each $name, $value in meta.module-variables`. How to fix this?

This is working as intended. For historical reasons, Sass treats underscores and hyphens interchangeably, and normalizes all member names to only use hyphens.

**Comment by DungGramer** [comment]
I create a mixin for this solution. Check it out!

```scss
@mixin add-css-variables($module) {
    :root {
     @each $name, $value in $module {
       --#{$name}: #{$value};
     }
    }
 }
 
 @use "sass:meta";
 @use "colors.scss" as colors;
 $colors: meta.module-variables('colors');

// Usages
 @include add-css-variables($colors);
 ```

**Comment by vrbajaroslav** [comment]
> 

Thanks, how your "colors.scss" file looks like?

**Comment by vrbajaroslav** [comment]
> I create a mixin for this solution. Check it out!
> 
> ```css-scss
> @mixin add-css-variables($module) {
>     :root {
>      @each $name, $value in $module {
>        --#{$name}: #{$value};
>      }
>     }
>  }
>  
>  @use "sass:meta";
>  @use "colors.scss" as colors;
>  $colors: meta.module-variables('colors');
> 
> // Usages
>  @include add-css-variables($colors);
> ```

Thanks, i am trying this out. How your "colors.scss" file looks like?

**Comment by DungGramer** [comment]
> > I create a mixin for this solution. Check it out!
> > ```
> > @mixin add-css-variables($module) {
> >     :root {
> >      @each $name, $value in $module {
> >        --#{$name}: #{$value};
> >      }
> >     }
> >  }
> >  
> >  @use "sass:meta";
> >  @use "colors.scss" as colors;
> >  $colors: meta.module-variables('colors');
> > 
> > // Usages
> >  @include add-css-variables($colors);
> > ```
> 
> Thanks, i am trying this out. How your "colors.scss" file looks like?

It's normal scss variable file. Like this:
```scss
$primary: hsl(210deg 100% 56%);
$secondary: hsl(220deg 97% 53%);

$success-color: hsl(146deg 75% 38%);
$warning-color: hsl(39deg 100% 61%);
$error-color: hsl(347deg 82% 48%);
$info-color: hsl(188deg 78% 41%);
```

After using `add-css-variables($colors)`, You can using 1 of 2 ways below for using variable.
1. Using SCSS variable
```scss
@use "colors.scss";
.btn-primary {
    background: $primary;
}
```
2. Using CSS variable
```scss
.btn-primary {
    background: var(--primary);
}
```

**Comment by AlexSkrypnyk** [comment]
The solution to _create_ CSS variables using meta module is working - great! We can now create a list of all or filtered CSS variables to be automatically exposed.

The next problem to solve is how to _use_ SASS variables to assign to properties without duplication.

I want this output (with CSS variable fallback):

```
.btn-primary {
    background: var(--primary, #123456);
}
```

The first thing comes in mind to achieve this is to implement a helper function and call it like this:

```
.btn-primary {
    background: my-css-var-func($primary);
}

@function my-css-var-func($primary) {
  @return var('--' + get-name-of-arg-var(arg[0]), $primary);
}
```

Obviously, there is no `get-name-of-arg-var()` or `arg[0]` in SASS :(

The best next thing is:

```
.btn-primary {
    background: my-css-var-func('primary', $primary);
}
```
but this approach is prone to errors (imagine duplicating 1000s  of variables this way).

Maybe there is another way to achieve what `my-css-var-func($primary)` would do?

**Comment by nickgeorgiou** [comment]
Can’t you just pass the name of the variable as a plain string? my-css-var-func('primary') and then it checks to see if the --var exists and then fallback to the $variable with the name?

```
@function my-css-var-func($var) {
  @return var('--' + $var, #{$var});
}
```

And then use `background: my-css-var-func('primary')`

**Comment by mirisuzanne** [comment]
If you are looping over variables in a map to generate the custom properties, you can use that same map to access them by name: 

```scss
@use 'sass:map';
@use 'sass:meta';
@use 'my/vars';

$vars: meta.module-variables('vars');

html {
  /* use the map to generate custom props */
  @each $name, $value in $vars {
    --#{$name}: #{$value};
  }
}

@function css-var($name) {
  /* use the same map to access variables dynamically */
  $fallback: map.get($vars, $name);
  @return var(--#{$name}, $fallback);
}

.example {
  color: css-var('primary');
}
```

**Comment by AlexSkrypnyk** [comment]
@mirisuzanne 
Thank you for replying. I looked into this approach first thing :)

In your example
```
.example {
  color: css-var('primary');
}
```
`primary` is not a variable but a string. Strings are not working with static analysis (IDE won't be able to find all the usages of a variable or offer an autocomplete) and  prone to human error when typing. That is why I want to use a variable itself to get that value.

Oh, and in other languages, like PHP, what I'm asking for (getting a variable name when passed to the function) is considered to be a bad practice. And I agree with that. Just really want a solution for my problem :)

**Comment by vincentts** [comment]
I recently came across the same issue.
I separated the CSS vars into a separate file so that I can reuse the SASS variables in other files by referencing the CSS vars.

SASS vars:
There are duplications on the naming for the sass vars and css vars, but I reckon because they are often the same and they are contained in one file, they can be easily changed using editor's multiple cursors.
```
// _vars.scss
$theme-vars: false !default;

@function css-var( $name, $value ) {
    @if ( $theme-vars ) {
        @return $value;
    }
    @return var(--#{$name});
}

$primary: css-var( 'primary', #123456);
$secondary: css-var(  'secondary', #234567);
```
CSS vars:
```
// root.scss
@use 'my/vars' with ( $theme-vars: true );
@use 'sass:meta';

:root {
    @each $name, $value in meta.module-variables('vars') {
        --#{$name}: #{$value};
    }
}
```
Usage in other files to reference CSS vars:
```
@use 'my/vars' as *;

h1 { color: $primary }
p { color: $seconday }
```
