### ISSUE TITLE
`deep-merge()` ordering should match `merge()`

### ISSUE THREAD

**Issue by Awjin** [sass/sass#3092]
Currently, the result of `deep-merge()`ing two maps does not guarantee the order of items.

We should spec the behavior to instead match that of `merge()`, in which the order of `$map1` is preserved and any unique entries in `$map2` are added to the end.

See https://github.com/sass/dart-sass/issues/1385

**Comment by nex3** [comment]
[The proposal](https://github.com/sass/sass/blob/bf28c1339c4970c67413294b5c818641ff85de92/proposal/deep-merge-order.md#deep-merge-order-draft-1) has landed. Since it's relatively small but also a breaking change, let's give it two weeks for public comment before we declare it accepted.
