### ISSUE TITLE
How to migrate cases that make use of @content and @import with @content and @forward

### ISSUE THREAD

**Issue by csalmeida** [sass/sass#3095]
I'm migrating a codebase from using `@import` to `@use` and `@forward`. Most of it is okay but I'm unsure what to do in a case where `@import` is used with `@content`.

Considering the following mixing that the only goal is to wrap styles in a class:

```scss
@mixin alternative-styles {
  .parent-class {
    @content;
  }
}
```

The mixin is then used with `@import` to wrap all those styles in a `.parent-class`:

```scss
@include alternative-styles {
  @import 'components';
}
```

I assumed replacing it with a `@forward` wouldn't work but have it a try anyway in this way:

```scss
@include alternative-styles {
  @forward 'components';
}
```

This threw the following error:

```bash
Error: This at-rule is not allowed here.
   ╷
22 │   @forward 'components';
     │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
```

Is there any way to achieve wrapping a bunch of styles in a class that supports the `@use` and `@forward` rules?

Thanks a lot in advance!

**Comment by csalmeida** [comment]
I have found that the `sass-migration` tool solves the issue this way:

```sass
@use 'sass:meta';
@use 'mixins';

@include mixins.alternative-styles {
  @include meta.load-css('components');
}
```

The `components.scss` files has multiple `@forward` statements to keep all component references in one place like this:

```scss
// components.scss
@forward 'components/buttons';
@forward 'components/text';
```

After the sass compiler runs it results in an empty block:

```css
.parent-class {
}
```

**Comment by jathak** [comment]
`@use` and `@forward` rules must be written at the root of the stylesheet, before any other rules.

`meta.load-css` is the replacement for nested `@import` rules when using the module system. In many cases, it should provide equivalent behavior, but since it only loads the CSS, and not any Sass members, there are some cases where it will not. I believe it should work fine for your use case though.

**Comment by csalmeida** [comment]
Thank you so much for the explanation @jathak. 🙏

I see, so in this case to get the `.parent-class` block populated with all the styles that are forwarded to `components.scss` I would need to compile `components.scss` first and pass the styles that result from it into `meta.load-css`. Is that correct?

I understand that in theory, passing `components.scss` should work since only styles are held in each file but could it be that passing a file to `meta.load-css` with `@forward` statements is not supported? As in, the styles would need to be added directly to `components.scss` rather than through `@forward` rules in order to be loaded correctly?

At the moment (explained in the example above) [passing `components.scss` into `meta.load-css` results in an empty block](https://github.com/sass/sass/issues/3095#issuecomment-875431581) when the styles are compiled to CSS.

**Comment by jathak** [comment]
You shouldn't need to do a separate compilation.

Do `components/buttons` and `components/text` actually emit any CSS? If they do, it should be included by `meta.load-css`.

**Comment by csalmeida** [comment]
Perfect, have put a few files together to test this in isolation it does work just fine.
Really grateful for your help @jathak!
