### ISSUE TITLE
Feature request: called-from history of @mixin and @function

### ISSUE THREAD

**Issue by Fnxxxxo** [sass/sass#3098]
## Feature description:
I hope Sass to have a built-in function `called-from`, which can be used to get the caller stack for current mixin or function.
I am coming from stylus and I use a `called-from` syntax to implement a BEM mixin for development. The details is:
``` stylus
block($name) {
  / .{$name} {
    {block}
  }
}

element($name) {
  $continue = true
  $name = '__' + $name

  for $caller in called-from {
    if $continue {
      if ($caller in ('element' 'modifier')) {
        $continue = false
        // Use the latest caller as prefix
        & ^[0]{$name} {
          {block}
        }
      } else {
        &{$name} {
          {block}
        }
      }
    }
  }
}

modifier($name, $val = null) {
  $val = $val && '-' + $val
  $name = '_' + $name
  $name = $val ? $name + $val:$name
  &{$name} {
    {block}
  }
}
```
This supports me to write general element style and override them under specific modifier like:
```
+block(main) {
  width: 100%;
  +element(panel) {
    background: green;
  }
  +modifier(active) {
    +element(panel) {
      background: red;
    }
  }
}
// Which built to 
// .main { width: 100%; }
// .main__panel { background: #008000; }
// .main_active .main__panel { background: #f00; }
```
## How this feature looks like
``` scss
@mixin someMixin() {
  .someMixin {
    @content
  }
}

@mixin otherMixin() {
  .otherMixin {
    @content
  }
}

@include someMixin() {
  @include otherMixin() {
    called-from() // This return an array ['otherMixin', 'someMixin']
  }
}
```
## Abount workaround
Currently, I store the name of current mixin to global variable with `!global` and read them from children. But this solution is vulnerable. Other suggestions are welcome.

**Comment by jathak** [comment]
This is not something we'd ever plan to support in the language, since varying behavior based on the call stack would make it very difficult to understand others' code. If you require this sort of behavior within your own code, a global variable is probably the way to go.
