### ISSUE TITLE
Allow parenthesis `show`/`hide` clause, as `with` does

### ISSUE THREAD

**Issue by xnuk** [sass/sass#3101]
Currently, `show ...` / `hide ...` does not wraps member list with parenthesis `()`:
https://github.com/sass/sass/blob/2121f939b411c1650005b82c53557dd6248bff74/spec/at-rules/forward.md#L21-L23

While `with ( ... )` requires it:
https://github.com/sass/sass/blob/2121f939b411c1650005b82c53557dd6248bff74/spec/at-rules/use.md#L33-L35

So I want Sass also allows it in `show` / `hide`:
```scss
// from
@forward '@some/library' show some-function-name, $some-var-name with (
  $some-config-name: 1px,
  $magenta: #ff00ff,
);

// to
@forward '@some/library' show (
  some-function-name,
  $some-var-name,
) with (
  $some-config-name: 1px,
  $magenta: #ff00ff,
);
```

Maybe the spec could be written like this?:
```ebnf
ShowClause     ::= 'show' MemberNameList
HideClause     ::= 'hide' MemberNameList

MemberNameList ::=     MemberName (',' MemberName)*
                 | '(' MemberName (',' MemberName)* ','? ')'

MemberName     ::= '$'? <ident-token>
```

**Comment by jathak** [comment]
Having two different supported syntaxes for `show` and `hide` clauses is not something we want to add.

**Comment by xnuk** [comment]
(Sorry for late reply check.) If two different syntax (with/without parens) is avoided, how do you think about migrating `show a, $b` to `show (a, $b)`? I understand it would be breaking change though, but I feel there is inconsistency between `show a, $b` and `with ($a: 1, $b: 2)`.

**Comment by jathak** [comment]
The breaking change here wouldn't be worth it
