### ISSUE TITLE
I don't know if you're aware but Black Lives Matter is founded by Marxists...

### ISSUE THREAD

**Issue by Steve-Dusty** [sass/sass#3102]
Saying "Black Lives Matter" does not literally mean "Black lives matter". Saying this is promoting the Black Lives Matter organization/movement. When you were telling those other issue submitters how Black Lives Matter means a lot for the Black community, you seem not to pay much attention to their message. Black Lives Matter is more of an organization than what they claim to be. It declares statements about a certain President that are up for moot - for a LOT of people, spread blatant anti-capitalist messages, and finally creating a controversy. If you are to keep supporting this Marxist organization, you've now chosen a clear side. I'm submitting this issue not because I believe either the political right or the left is more superior to one another (we need both to maintain a balance) but because the community of SCSS/Sass should not be involved in this. Keep up your work and you'll be known as a supporter of the far-left. If my message should somehow convince you, change the banner to "Black lives matter" (with no capitalizations) and write your own statement instead of linking it to the official Black Lives Matter website.

**Comment by justinwilaby** [comment]
I think this is the incorrect repo. The sass team can correct me if I'm wrong but I believe this falls under "UX improvement" and such requests should be submitted to the [sass/sass-site](https://github.com/sass/sass-site/) repo.

**Comment by Steve-Dusty** [comment]
Thank you for the update.
