### ISSUE TITLE
Tabulator on output

### ISSUE THREAD

**Issue by laaneoks** [sass/sass#3104]
Would you please add the flag ("--tab" for example) to get output indention with tabulators, not with spaces?

**Comment by jathak** [comment]
Sass is not designed to generate a deeply customizable output; just a readable one. If you want more advanced control over your CSS output, we'd recommend using a postprocessor like PostCSS after you compile your Sass.

**Comment by laaneoks** [comment]
Tabs or spaces are not "deeply customizable output". It is a very standard case and very simple to implement.
Please consider more time this option.
