### ISSUE TITLE
Conditional documentation doesn't include "and"/"or"

### ISSUE THREAD

**Issue by samgermain** [sass/sass#3109]
Here's the page https://sass-lang.com/documentation/at-rules/control/if

There's no explanation of how conditionals use `and`/`&&` or `or`/`||`

**Comment by samgermain** [comment]
I realized its under operators https://sass-lang.com/documentation/operators/boolean

**Comment by kerryj89** [comment]
I think it still wouldn't hurt to include some examples for and/or considering how common it is for those of us using the docs as a quick reference.

**Comment by Awjin** [comment]
I think it's reasonable to mention the operators in the conditional docs. Created https://github.com/sass/sass-site/pull/613 to address this.
