### ISSUE TITLE
New unit conversions

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#311]
http://www.w3.org/TR/2012/WD-css3-values-20120308/#other-units

CSS now supports `s` and `ms` as time values. Sass should be able to convert between them at `1s` == `1000m`.

CSS also support `Hz` an `kHz` and Sass should convert between them at `1000Hz` == `1kHz`

CSS also now supports angle measurements `deg`, `rad`, `grad` and `turn` which can be converted using good old `π` and whatnot.

Lastly it seems like `dpi` and `dpcm` can be converted but it seems like any conversion would not be 100% accurate due to rounding issues implied by quantization.

**Comment by scottkellum** [comment]
Getting there...
https://gist.github.com/2004835

**Comment by chriseppstein** [comment]
@scottkellum Sorry I really should have put some more details about this into the issue. We have conversions built into sass as it is a core syntax concern and part of our arithmetic system: https://github.com/nex3/sass/blob/master/lib/sass/script/number.rb#L424-430
