### ISSUE TITLE
slash as divider

### ISSUE THREAD

**Issue by adriennemcd** [sass/sass#3115]
hi, hoping for some clarification. I'm the maintainer of a design system and as a transition period, we're currently supporting the old `@import` syntax and the new module syntax (meaning that we have duplicates of files until the deprecation period is over). When I ran the migrator for division, it changed the '/' to the `divide()` function in the old syntax files and didn't update the new module files at all.

I'm not looking to troubleshoot the migrator here, but I just want to clarify when I should be using `divide()` vs `math.div()`. It seems like `math.div` is only available for stylesheets that are compiled with dart sass. Is `divide()` available in LibSass? I couldn't find it in the docs

**Comment by nex3** [comment]
> I'm not looking to troubleshoot the migrator here, but I just want to clarify when I should be using `divide()` vs `math.div()`.

There's no top-level `divide()` function. We had planned to add this function, and initially implemented a migrator for it, but our plans ended up changing to only target `math.div()`. I'm guessing you're using an outdated version of the migrator; if you upgrade, it should migrate everything to `math.div()` (and fix a number of other minor bugs).

> It seems like `math.div` is only available for stylesheets that are compiled with dart sass. Is `divide()` available in LibSass? I couldn't find it in the docs

Unfortunately, one of the reasons that [LibSass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) is that it hasn't added any new features in a long time, including any support for division other than the `/` operator. As such, we recommend moving towards dropping support for LibSass; the set of features that aren't compatible with it will only continue grow over time.

There is a way to maintain compatibility with both implementations in the meantime, though. You can take advantage of the fact that LibSass doesn't respect import-only files to have the same `@import` point to a different stylesheet for LibSass than it does for Dart Sass:

```scss
// _divide.import.scss
// `@import "divide"` will load this file in Dart Sass, but not LibSass.
@use "sass:math";

@function divide($numerator, $denominator) {
  @return math.div($numerator, $denominator);
}
```

```scss
// _divide.scss
// `@import "divide"` will load this file in LibSass, but not Dart Sass.

@function divide($numerator, $denominator) {
  @return $numerator / $denominator;
}
```
