### ISSUE TITLE
Support merging multiple arbitrary arg maps

### ISSUE THREAD

**Issue by asyncliz** [sass/sass#3116]
When merging several map variables, it can be a frustrating devx to chain them in a single call (especially with a formatter like Prettier).

```scss
$finalmap: map.merge(
  $map1,
  map.merge(
    $map2,
    map.merge(
      $map3,
      map.merge($map4, $map5)
    )
  )
);
```

An alternate syntax to `map.merge()` and `map.deep-merge()` could support multiple arbitrary map arguments to improve this.

```scss
$finalmap: map.merge($map1, $map2, $map3, $map4, $map5);
```

`map.deep-merge()` can easily be changed to support the following syntax:

```
map.deep-merge($map1, $maps...);
```

`map.merge()` will be a bit trickier since it supports keys. Instead of always checking if the last argument is a map, the arg list will need to be iterated and a separate key list and map list built. The "described" syntax could look something like this:

```
map.merge($map1, $map2);
map.merge($map1, $keys..., $maps...);
```

**Comment by jathak** [comment]
Maps can technically be keys, so the syntax you propose wouldn't work, since you wouldn't always be able to distinguish between what's a key and what's a map.

You should be able to implement this as a user-defined function though.

**Comment by asyncliz** [comment]
I believe there is value in avoiding defining utility bag functions for this use case, since they increase the burden of maintenance for library authors.

For one, `map.deep-merge()` can still support this use case since its syntax does not accept keys as an argument.

```scss
$finalmap: map.deep-merge(
  $map1,
  map.deep-merge(
    $map2,
    map.deep-merge(
      $map3,
      map.deep-merge($map4, $map5)
    )
  )
);

// vs
$finalmap: map.deep-merge($map1, $map2, $map3, $map4, $map5);
```

This proposal can be split into two improvements: one towards `deep-merge()`, which will satisfy an immediate use case, and another to further discuss `merge()`, which can still be solved, albeit more creatively and with more opinions.

For example, the syntax of `map.merge()` can be adjusted to support this use case by using keyword arguments.

```
map.merge($map1, $map2);
map.merge($map1, $keys..., $map2);
map.merge($map1, $maps..., $keys...); // $keys must be a keyword argument
```

```scss
// By default, treat multiple args as one map, followed by keys, then a final map
$regularmerge: map.merge($map1, 'foo', $mapkey, $map2);

// Keyword arguments can explicitly call out what keys to merge for one or more maps
$finalmap: map.merge($map1, $map2, $map3, $map4, $map5, $keys: ('foo', $mapkey));

// An optional breaking change that improves DevX would be to evaluate all arguments.
// If they're all Maps, a decision could be made to assume the user desires to merge
// multiple Maps. This could generate a warning before a breaking change is introduced.
$prechange: map.merge($map1, $mapkey1, $mapkey2, $map2); 
/* @warn: the next version of Sass will merge all Maps together. Use the $keys keyword argument to specify Map keys. */

$postchange: map.merge($map1, $map2, $map3, $map4);
```

**Comment by nex3** [comment]
It's likely to be very confusing to novice users if `map.merge()` and `map.deep-merge()` both support rest arguments, but with entirely different semantics.

> For example, the syntax of `map.merge()` can be adjusted to support this use case by using keyword arguments.
> 
> ```
> map.merge($map1, $map2);
> map.merge($map1, $keys..., $map2);
> map.merge($map1, $maps..., $keys...); // $keys must be a keyword argument
> ```

Unless we choose to do a breaking change (the bar for which is extremely high), this suggests that people who just want to merge maps without specifying keys would still have to write `map.merge($map1, $map2, $map3, $keys: ())` which is definitely less clear than `map.merge($map1, map.merge($map2, $map3))`.

If we were going to do this, I'd strongly prefer to make it explicit by adding new `map.merge-all()` and `map.deep-merge-all()` functions.

**Comment by asyncliz** [comment]
> If we were going to do this, I'd strongly prefer to make it explicit by adding new `map.merge-all()` and `map.deep-merge-all()` functions.

This would be a great alternative!
