### ISSUE TITLE
Why not?

### ISSUE THREAD

**Issue by babakfp** [sass/sass#3119]
```SASS
$sm: 640px
$md: 768px
$lg: 1024px
$xl: 1280px
$2xl: 1536px // ERROR: Expected identifier
```
It's not possible to create a var that its name starts with a number.

**Comment by jathak** [comment]
This is intentional, as CSS does not allow identifiers to start with a number (see https://www.w3.org/TR/css-syntax-3/#ident-token-diagram).

**Comment by babakfp** [comment]
but it's a SASS variable, not something related to CSS.

**Comment by robsonsobral** [comment]
But SASS is intentionally as close as possible to CSS to avoid future conflicts.
