### ISSUE TITLE
!important Mixins

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#312]
Is there a way in SASS to do something like in LESS where you can mark a whole mixin as important ?
Like this per example :

```
@include opacity(1) !important;
```

Which would result in :

```
filter: progid :DXImageTransform.Microsoft.Alpha(Opacity=100) !important;
opacity: 1 !important;
```

If not it's really a feature that I think should be in there. Sometimes you have to overwrite box-shadow, text-shadow, opacity etc. you can't really control, and !important really comes in handy in these cases.

**Comment by nex3** [comment]
No there is not.

@chriseppstein thoughts on adding this?

**Comment by chriseppstein** [comment]
I do not like this as a general facility for mixins. In this case, `@include opacity(1 !important);` will probably work, but it will not work generally unless compass adds support for `!important` as an argument to the mixins. I think it is the job of the mixin api to support importance where it makes sense.

**Comment by chriseppstein** [comment]
@Anahkiasen feel free to open an issue on compass to discuss changes to the compass css3 mixins.

**Comment by Petah** [comment]
This would be useful for overriding the inline styles jQuery UI puts on.

For example a jQuery UI dialog puts `display: block` inline on the `ui-dialog-content`

Where as I want to override it with `display: -xxx-box` using `@include display-box()`

**Comment by polikin** [comment]
+1

**Comment by dark-panda** [comment]
+1

**Comment by BenMorel** [comment]
+1

**Comment by aluminiumgeek** [comment]
+1

**Comment by jpdevries** [comment]
I've proposed an idea for something similar, but with Silent Classes
http://www.sassmeister.com/gist/e50c05fa188cbfeb3ac6

``` scss
%greedy {
  width:100%;
}

div {
  // we can do this
  @extend %greedy;
  // but i wish we could do this
  //@extend %greedy !important; 
}
```

I know the point of silent classes is to group all the properties together (and you could have a group for regular, and a group for `!important`) so it might be a bit odd, but I've found myself wishing we could do it several times. Same with mixins.

**Comment by chriseppstein** [comment]
@jpdevries That is just not technically possible. `!important` is a property modifier. Extend works by rewriting selectors. If we did this it would have consequences for selectors that were not intended to be important.

**Comment by bitcoin-coder-bob** [comment]
@chriseppstein 

So is it not possible to do what I am demonstrating here? I want its `table-layout`  to have a value of `auto` in a class called `itemList home-items`. However if the class is only called `itemList` that I would want it to be `table-layout: fixed !important`.  In the first case of `table-layout` in `itemList` it must contain the `!important`. Is there anyway to then override its value in a nested class like I am trying to do here? Currently as far as I can tell from experimenting this is not supported.


``` 
.itemList {
  width: 100%;
  font-weight: 500;
  table-layout: fixed !important;

  &.home-items{
    overflow-x: hidden !important;
    width: 100% !important;
    min-width: 100% !important;
    table-layout: auto !important;
  }
}
```

**Comment by ArmorDarks** [comment]
@stefanpenner what you're trying to do related to CSS specificity only and has little to do with this issue.

Sass mixin just generating CSS code and can't affect specificity. You need to construct your classes in such way so that your selector with the desired rule would win.

Just read about [how CSS specificity works](https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/) to figure out what you need.
