### ISSUE TITLE
catch undefined mixin

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#3120]
is it possible to catch a call to an undefined mixin?

i would like a catch-all mixin to allow supporting adding values to any css property. something like this...

```sass
@mixin get-prop-color($prop, $color) {
  #{$prop}: $color;
}

@mixin catch-undefined-mixin($mixin-name, $color) {
  @include get-prop-color($mixin-name, $color)
}

body {
  @include background-color(red);
}
```

similar to how ruby's [method_missing](https://ruby-doc.org/core-2.6.3/BasicObject.html#method-i-method_missing) works

**Comment by jathak** [comment]
This isn't something we plan to support, as it's better to be explicit about what you wish to support. Allowing something like Ruby's method_missing makes for less readable code and makes static analysis harder.
