### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by babakfp** [sass/sass#3124]
Hi

![Screenshot 2021-08-19 085436-min](https://user-images.githubusercontent.com/44144724/130101717-4a58d8e4-9672-497c-bae4-526a9692f608.png)

when I remove `+space-y(.5rem)`, that weird output won't generate.

[source code in this repo](https://github.com/babakfp/SASS-Weird-output)

```terminal
sass --version
1.27.0 compiled with dart2js 2.10.1
```

**Comment by stof** [comment]
your repository is not a working reproducer. There is nothing that can be compiled with Sass to reproduce the issue in a working way.

**Comment by babakfp** [comment]
Hi
Please check again, I fixed [the repo for reproducing](https://github.com/babakfp/sass-weird-output)😄🌻
@stof

**Comment by stof** [comment]
Well, you have the variable `$_s` defined in both files (`_mixin.sass` and `_first-selector.sass`), so they override each other.

Variables in Sass are isolated between *modules*. But your reproducer uses a single module (`@import` does not create a module boundary).

**Comment by babakfp** [comment]
What about `_` in var name? It doesn't work with `@import`? It should only be available inside the file that it is defined.
@stof

**Comment by stof** [comment]
@babakfp the `_` prefix in a variable name makes it private to its *module*, not to its *file*. When you use `@import`, the various files belong to the same module

**Comment by babakfp** [comment]
Cool, thanks❤
