### ISSUE TITLE
@use / @forward scope and variable renaming doesn't scale well

### ISSUE THREAD

**Issue by rhassingerr** [sass/sass#3128]
Consider a large, mature system build with Angular 12 which uses `@import`s and would like to switch to `@use`s.
Currently all the 100+ .scss files have the same import:

```
@import "../../../../styles/corp.scss";
```

...with varying quantities of `../` depending on how deep it is in the path hierarchy. Inside `corp.scss` contains 10+ imports that point to all the scss files which contain the non-style information (variables, mixins, etc.):

```
@import "colors.scss";
@import "fonts.scss";
@import "dimensions.scss";
@import "mixins.scss";
@import "behaviors.scss";
... etc.
```

So now the devs want to properly swtich to @use, so they change the @import in every file to:
```
@use "../../../../styles/_colors.scss";
@use "../../../../styles/_fonts.scss";
@use "../../../../styles/_dimensions.scss";
@use "../../../../styles/_mixins.scss";
@use "../../../../styles/_behaviors.scss";
... etc.
```

This is interesting, because now you can "scope" the variables:
```
.title { color: colors.$title-text; }
```

but all those @use lines in every file is messy and varies depending on the depth of the scss files. So the devs put them all into one file, _corp.scss (like they were before) and @forward them:
```
@forward "_colors.scss";
@forward "_fonts.scss";
@forward "_dimensions.scss";
@forward "_mixins.scss";
@forward "_behaviors.scss";
... etc.
```

So now each file has a single-line `@use`. However, now scope is lost, because every value has the scope `corp`:
```
.title { color: corp.$title-text; }
```

Back to the `@forward` docs, it turns out you can prefix the variables:
```
@forward "_colors.scss" as color-*;
@forward "_fonts.scss" as font-*;
@forward "_dimensions.scss" as dimension-*;
@forward "_mixins.scss" as mixin-*;
@forward "_behaviors.scss" as behavior-*;
... etc.
```

And use it as:
```
.title { color: corp.$color-title-text; }
```

Unfortunately, this makes a number of things confusing and hard to maintain. The variables get renamed instead of scoped. `color` scope is lost, and instead becomes part of the name. It's harder to search for the use of values because `$color-title-text` will not find the source, and `$title-text` will not find the usages. You can forward more than once, but the prefixes just build up.
Ideally, the devs would like to be able to organize scss like so:
```
// _corp.scss
@forward "signup/_signup.scss" as signup; 
// _signup.scss
@forward "payment/_payment.scss" as payment; 
// _payment.scss
@forward "_colors.scss" as colors;
```
Currently, this would be referenced in this kludgy manner:
```
.title { color: corp.$signup-payment-colors-title-text; }
```

But if bottom-up hierarchical scoping were used, it could be referenced like:
```
.title { color: corp.signup.payment.colors.$title-text; }
```
The latter is much easier to maintain, and apps like VS Code would have a much easier time refactoring or jumping to source.

**Comment by stof** [comment]
to me, the solution to avoid the huge (and varying) list of `../` to reach the `styles` folder is to rely on the existing Sass feature: load paths: https://sass-lang.com/documentation/at-rules/use#load-paths

**Comment by jathak** [comment]
@stof's solution is the correct one here. This sort of namespace forwarding would add significant complexity to the syntax and semantics of `@forward`, and it's better to directly depend on the Sass members you need with `@use` rules in the file you need them in when possible.

**Comment by MassMessage** [comment]
> to me, the solution to avoid the huge (and varying) list of `../` to reach the `styles` folder is to rely on the existing Sass feature: load paths: https://sass-lang.com/documentation/at-rules/use#load-paths

How do I set this load paths? Currently I'm facing similar issue

**Comment by nex3** [comment]
You can use the [`--load-path` option](https://sass-lang.com/documentation/cli/dart-sass#load-path) for the command-line executable, or the [`loadPaths` option](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) for the JS API.
