### ISSUE TITLE
Support variables in @media queries

### ISSUE THREAD

**Issue by borismus** [sass/sass#313]
I want to do this, but SCSS throws errors:

$small: 540px;
$big: 1000px;

@media screen and (max-width: $small) {
  // Styles for the smallest version.
}

@media screen and (min-width: $small and max-width: $big) {
  // Styles for the mid version.
}

@media screen and (min-width: $big) {
  // Styles for large version
}

**Comment by chriseppstein** [comment]
This works on the sass prerelease. I assume you're running 3.1. Please install 3.2 to get this feature:

```
gem install sass --pre
```
