### ISSUE TITLE
:where() not working

### ISSUE THREAD

**Issue by nstringham** [sass/sass#3130]
the `:where()` sudo-class ([MDN reference](https://developer.mozilla.org/en-US/docs/Web/CSS/:where)) is alot like the `:is()` sudo-class but `:is()` works in sass and `:where()` doesn't

this
```sass
.my-class
  :is(&)
    color: red
```
compiles to this
```css
:is(.my-class) {
  color: red;
}
```

and this
```sass
.my-class
  :where(&)
    color: red
```
should compile to this (expected behavior)
```css
:where(.my-class) {
  color: red;
}
```
but actually compiles to this (actual behavior)
```css
.my-class :where(&) {
  color: red;
}
```

I am using sass 1.38.1 installed with npm

**Comment by jakob-e** [comment]
I think this falls into the [special functions](https://sass-lang.com/documentation/syntax/special-functions) category – why you need to use [interpolation](https://sass-lang.com/documentation/interpolation) to turn the [parent selector ](https://sass-lang.com/documentation/style-rules/parent-selector)into a chunk of CSS.


```
.my-class
  :where(#{&}) 
    color: red
```

**Comment by nstringham** [comment]
> I think this falls into the [special functions](https://sass-lang.com/documentation/syntax/special-functions) category – why you need to use [interpolation](https://sass-lang.com/documentation/interpolation) to turn the [parent selector ](https://sass-lang.com/documentation/style-rules/parent-selector)into a chunk of CSS.
> 
> ```
> .my-class
>   :where(#{&}) 
>     color: red
> ```

I'm not 100% sure I understand what you're saying but thanks for pointing out the workaround

**Comment by nstringham** [comment]
> I think this falls into the [special functions](https://sass-lang.com/documentation/syntax/special-functions) category – why you need to use [interpolation](https://sass-lang.com/documentation/interpolation) to turn the [parent selector ](https://sass-lang.com/documentation/style-rules/parent-selector)into a chunk of CSS.
> 
> ```
> .my-class
>   :where(#{&}) 
>     color: red
> ```

this actually results in
```css
.my-class :where(.my-class) {
  color: red;
}
```
so it does not work as a workaround

**Comment by Awjin** [comment]
You're right. `:where` should generally behave like `:is`, but with added special handling of the specifity (e.g. when trimming selectors for `@extend`).

Since this is a language change and will need to go through the formal language feature process, I'm moving this to the Sass language repo.

**Comment by jakob-e** [comment]
The .my-class :where(.my-class) is the expected result - to break out of the class wrapper you can use @at-root
````
.my-class 
  @at-root
    :where(#{&}) 
      color: red

````
Output 
````
:where(.my-class) {
  color: red;
}

**Comment by stof** [comment]
@nex3 `:where` is also not parsed as a pseudo-class using an inner selector in dart-sass: https://github.com/sass/dart-sass/blob/52ef3c6ef17aec7cc1f9602671de666d35d0b0b3/lib/src/parse/selector.dart#L13-L23
