### ISSUE TITLE
Migrating to @use from using @import with bootstrap node_modules and multiple themeing

### ISSUE THREAD

**Issue by mmestas** [sass/sass#3132]
I have an angular project that builds multiple themes (ex. dark-mode, light-mode) using the @import rule for the bootstrap node_modules.

Each stylesheet is nested under a different class name (i.e. .dark-theme { @import bootstrap theme that has been built using dark theme variables }  .light-theme {@import bootstrap theme...etc} 

I'm having a rather difficult time converting this to @use, especially since modules can only be loaded once with @use and I need to essentially build multiple stylesheets and import them nested under a class name to have multiple themes. 

I made a demo working model of what I mean here: https://codesandbox.io/s/angular-bootstrap5-theming-tkw8j

If @use will become deprecated, what can I use to migrate this and still have theming?

EDIT: 

I also wanted to ask, I saw in the SASS docs, something to the effect of: 

`@use './node_modules/bootstrap/scss/bootstrap' as bs with (
  $white:    #fff,
  $gray-100: #f8f9fa,
  $gray-200: #e9ecef,
  $gray-300: #dee2e6,
  $gray-400: #ced4da,
  $gray-500: #adb5bd,
  $gray-600: #6c757d,
  $gray-700: #495057,
  $gray-800: #343a40,
  $gray-900: #212529,
  $black:    #000,
  $blue:    #0562ec,
  $indigo:  #6610f2,
  $purple:  #6f42c1,
  $pink:    #e02673,
  $red:     #dc3545,
  $orange:  #fd7e14,
  $yellow:  #FAAF40,
  $green:   #8BC53F,
  $teal:    #20c997,
  $cyan:    #086964
);`

Which simplifies things a lot, but again, it would not let me nest this under a class name, nor use more than one reference to the bootstrap node_module

**Comment by jathak** [comment]
`@use` and `@forward` rules may not be nested, but you can load CSS with [`meta.load-css`](https://sass-lang.com/documentation/modules/meta#load-css).

**Comment by mmestas** [comment]
Yes, I realize they can't be nested, hence the issue. meta.load-css also has the problem of only allowing you to load a module once.  If I try loading the module again under another class name using $with, I get an error.  In other words, you cannot create multiple themes built under separate classes like you could with @import.  meta.load-css does not allow for this because of the $with error, so what's the alternative?

**Comment by jathak** [comment]
If you need to load the same CSS multiple times, but with different configuration, you should use wrap the relevant CSS in a mixin instead. You can then call that mixin as many times as you want, with whatever parameters you want.
