### ISSUE TITLE
How to Scope Existing CSS with @use

### ISSUE THREAD

**Issue by Hecatron** [sass/sass#3140]
Hi,
I'm a bit new to scss so please forgive me if the answer to the below is obvious.
But what I'm trying to do is use scss to scope some existing css.
I'm currently trying to take an existing css file (from a source I don't have any direct control over)
then add an additional css selector to each of the selectors within the css.

This is possible with the import statement, but I'm wondering how it's done with "@use"

So for example

**test1.scss**
```
.scopedselector {
    @import './test2';
}
```

test2.css
```
.example1 {
    color: white;
    background-color: black;
}

.example2 {
    color: red;
    background-color: black;
}
```

End Result:
```
.scopedselector .example1 {
    color: white;
    background-color: black;
}

.scopedselector .example2 {
    color: red;
    background-color: black;
}
```

Now it does mention in the docs that imports are going to be depreciated eventually.
But @use only seems to work at the top of the file.
If thats the case then what would be the equivalent of the above but using a @use statement instead of @import?

**Comment by cpoftea** [comment]
You can use `sass:meta` module and his mixin [`load-css`](https://sass-lang.com/documentation/modules/meta#load-css).
```
@use "sass:meta";

.scopedselector {
  @include meta.load-css("test2");
}
```

**Comment by Hecatron** [comment]
Ah thanks that's just what I was looking for
