### ISSUE TITLE
@debug doesn't print nested empty lists

### ISSUE THREAD

**Issue by kinseywk** [sass/sass#3160]
Was super confused trying to debug a function that was working correctly the whole time because @debug really doesn't like empty lists for some reason:

```
$a: [];
$b: [[]];
$c: [[], []];
$d: [[[]]];
$e: [1, [], [2, 3]];
$f: [1, [2, [], 3]];

@debug "#{$a}"; //Correctly prints []
@debug "#{$b}"; //Incorrectly prints []
@debug "#{$c}"; // "                 "
@debug "#{$d}"; // "                 "
@debug "#{$e}"; //Incorrectly prints [1, [2, 3]]
@debug "#{$f}"; // "                          "
```

**Comment by Awjin** [comment]
This would be correct behavior if the lists did not have brackets. However, in this case the empty lists do have brackets, so it doesn't make sense to remove them from serialization.

**Comment by stof** [comment]
dart-sass does the right thing:

```
debug.scss:8 DEBUG: []
debug.scss:9 DEBUG: []
debug.scss:10 DEBUG: []
debug.scss:11 DEBUG: []
debug.scss:12 DEBUG: [1, [2, 3]]
debug.scss:13 DEBUG: [1, [2, 3]]
```

libsass gives a buggy output:

```
debug.scss:8 DEBUG: 
debug.scss:9 DEBUG: 
debug.scss:10 DEBUG: , 
debug.scss:11 DEBUG: 
debug.scss:12 DEBUG: 1, , 2, 3
debug.scss:13 DEBUG: 1, 2, , 3
```

**Comment by stof** [comment]
hmm, no. dart-sass is not right. It is *less* weird than libsass.

**Comment by stof** [comment]
However, the CSS rendering of list filters out blank items. And dart-sass implementation of `SassList` considers empty list to be blank even when they have brackets (as an empty list does not contain any non-blank element): https://github.com/sass/dart-sass/blob/8d5d586e7c4492379ff40b564118e7dc64091bb5/lib/src/value/list.dart#L29

**Comment by kinseywk** [comment]
> The issue is that you are not debugging an empty list. You are debugging a string in which you interpolate those lists. So `@debug` is not seeing any list. It sees a string. And the interpolation does not uses the `inspect()` output but the CSS output.

Ah, that makes sense. I didn't know to use meta.inspect(). My apologies. Still, it strikes me as inconsistent that cases $a through $d produce the same strings.
