### ISSUE TITLE
Import mixins not work.

### ISSUE THREAD

**Issue by muaytau** [sass/sass#3162]
Hi everyone. I just started my career as a junior full stack developer. 
I ran into this issue. But I have no idea how to fix this. :(
![image](https://user-images.githubusercontent.com/86136164/134445745-08284e1d-0ca7-45cf-ba91-c1c77851adb3.png)

Can anybody help me please? :)

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
