### ISSUE TITLE
--embed-source-map flag doesn't work with many-to-many mode

### ISSUE THREAD

**Issue by ngdangtu-vn** [sass/sass#3165]
I want to embed source map files to source files but I keep getting this error:

```bash
$ sass -–embed-source-map dir-1s:dest dir-2:dest
Positional and ":" arguments may not both be used.

# ... sass help note
```

I tried to move the flag to behind of the inputs but the result didn't change. This is a bug right?

Here is my computer spec:

- Windows 10
- Sass-dart 1.42.1 (installed via choco)

**Comment by nex3** [comment]
It looks like your second dash in `-–embed-source-map` is actually a U+2013 EN DASH character, which is causing Sass to interpret the entire argument as a filename rather than a flag. If you write `--embed-source-map` instead, it should work.

**Comment by ngdangtu-vn** [comment]
> It looks like your second dash in `-–embed-source-map` is actually a U+2013 EN DASH character, which is causing Sass to interpret the entire argument as a filename rather than a flag. If you write `--embed-source-map` instead, it should work.

My bad, I'm sorry about this. Btw, can we have a better error message for this case? The current message kept making me thought that I'd added input/output incorrectly. Maybe we can display a message like:

```
The command has homoglyph character(s). Please double check your inputs.
```

(I think I copied the whole `-–embed-source-map` from the doc site to my editor so I miss it. Sb'll probably make the same mistakes as well)

**Comment by stof** [comment]
@ngdangtu-vn the issue is that the U+2013 EN DASH character is valid in filenames. If dart-sass rejects such filenames due to maybe being confused for a dash character denoting the option, it would force you to rename the file for it to be usable.

**Comment by stof** [comment]
> (I think I copied the whole `-–embed-source-map` from the doc site to my editor so I miss it. Sb'll probably make the same mistakes as well)

this looks weird (unless you editor changed the dash when pasting it), as the doc site does not seem to use U+2013 EN DASH

**Comment by ngdangtu-vn** [comment]
> this looks weird (unless you editor changed the dash when pasting it), as the doc site does not seem to use U+2013 EN DASH

I've checked and it is my bad. Not exactly sure what source causes this but indeed that the document doesn't use the character.


> U+2013 EN DASH character is valid in filenames

About this. I understand that Sass is very generous in using name (support Unicode right?), but I don't see why sb would use such a similar character in filenames. Do we have any special reason for it?

And I wonder how does the app parse the command input? Since we have a limited flags, is it possible to do typo checking for flags?

**Comment by stof** [comment]
@ngdangtu-vn it uses https://pub.dev/packages/args

**Comment by ngdangtu-vn** [comment]
Maybe this is the scope of args package :?

**Comment by stof** [comment]
well, for your case where you use an EN DASH in place of the *second* dash, this might be solved in the `args` package if it expects that everything starting with a DASH must be an option (if not placed after a `--` separator of course, as that one disables parsing options). It would then report EN DASH as an invalid option shortcut (as there is no such shortcut defined in dart-sass).
