### ISSUE TITLE
Suggestion: Improve error message for command flags case

### ISSUE THREAD

**Issue by ngdangtu-vn** [sass/sass#3166]
This issue is inherit from this #3165 

My case was I accidently use a similar character that looks like dash and it cause an error message (which origin of it is, I believe, from Dart language). As the result, I got confused with input/output. Usually, in other cli app, I should receive some messages that tells me I got a weird characters, but it isn't the case in Sass. So I suggest we should add new error message for this case. Something like this:

```
The command has homoglyph character(s). Please double check your inputs.
```

How do you guys think?

**Comment by stof** [comment]
see my comment on https://github.com/sass/sass/issues/3165#issuecomment-929072441

This can only be achieved by forbidding some file names

**Comment by jathak** [comment]
There are a lot of Unicode characters that look similar to dashes, and special casing them isn't something that's worth the effort for this edge case.
