### ISSUE TITLE
Allow operations in @media()

### ISSUE THREAD

**Issue by MoOx** [sass/sass#318]
I can do that

``` scss
@mixin media-xl {
  @media (min-width: $media-query-width-xl) and (max-width: $media-query-width-xxl - 1px) {
    @content
  }
}
```

The  - 1px is not allow. It will be great if we can use thing like that.

**Comment by MoOx** [comment]
Btw, a workaround si to make the same behavior like this
`@mixin media-xl         { $max: $media-query-width-xxl  - 1px; @media (min-width: $media-query-width-xl)     and (max-width: $max)  { @content } }`

**Comment by nex3** [comment]
This works on the latest master branch.

**Comment by MoOx** [comment]
Sorry I feel stupid.
