### ISSUE TITLE
Question about deprecation warnings

### ISSUE THREAD

**Issue by zaydek** [sass/sass#3182]
Is my understanding correct that previous to ~v1.32 Sass wasn't logging deprecation warnings to stderr? I'm finding that the JS API is not programmatic enough for my needs because from what I can tell, there's not programmatic way to silence deprecation warnings using the JS API. I'm aware I can use `--quiet` as a flag for the CLI, but I need programmatic control over stdout / stderr, which is why I'm using the JS API in the first place.

Assuming my understanding is correct, that forced deprecation warnings are recent and a side-effect of using the JS API, would you recommend I revert my version to ~v1.32 or is there some reasonable way I can suppress the deprecation warnings without resorting to creating child processes and invoking the CLI API instead.

Thank you.

**Comment by jathak** [comment]
As of 1.43.0, you can now [pass a logger](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1430) to the JS API. `Logger.silent` should silence all messages; you can also pass a custom `Logger` to more precisely control the output.

**Comment by zaydek** [comment]
Thanks @jathak. I thought I tried that but maybe I did something wrong. Will follow-up only if there's an issue. Thanks!

**Comment by black7375** [comment]
@jathak Can I disable only certain alerts at CLI?

---

In project [Firefox lepton theme](https://github.com/black7375/Firefox-UI-Fix), we use [`@-moz-document`](https://sass-lang.com/documentation/breaking-changes/moz-document).

It is not affected because it is a UA sheet level.
https://bugzilla.mozilla.org/show_bug.cgi?id=1035091

**Comment by jathak** [comment]
No, but for the `@-moz-document` deprecation, you can avoid the warning by just interpolating the name.

**Comment by black7375** [comment]
Thanks, there is no warning in the next code:

```scss
@#{-moz-document} url-prefix("about:downloads") {
}
```

It seems to be suitable as a temporary solution.
