### ISSUE TITLE
Question about math.div

### ISSUE THREAD

**Issue by miguelesquirol** [sass/sass#3184]
I'm migrating manually my code with a new way to do divisions. But every time I use a variable inside a division it gives me the alert:

"math.div() will only support number arguments in a future release. Use list.slash() instead for a slash separator."

a![image](https://user-images.githubusercontent.com/594913/136574251-e05957c7-545a-4764-b742-1b135b4eee74.png)

**Comment by Awjin** [comment]
It looks like `$track-height` is not a number.
