### ISSUE TITLE
Feature request: Add possibility to use math inside `#{}`

### ISSUE THREAD

**Issue by toptalo** [sass/sass#3194]
With new `math.div()` syntax simple mathematical expressions become looks too hard to read.
For example, can you easily understand what is going on here: 
```margin-top: math.div(math.div($height, $CANVAS_HEIGHT) * $margin-top, 100) * 100%```
I think not really =)

I suggest to use interpolation in such places:
```margin-top: #{$height / $CANVAS_HEIGHT * $margin-top / 100 * 100%};```

Looks better, right?

What do you think?

**Comment by cpoftea** [comment]
Since Sass [`v1.40.0`](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1400) you can use first-class `calc()` function
```scss
margin-top: calc($height / $CANVAS_HEIGHT * $margin-top / 100 * 100%);
```
