### ISSUE TITLE
[JS API] Add an sourceMapEmbedSources option in the sourcemap API

### ISSUE THREAD

**Issue by stof** [sass/sass#3197]
The CLI has a `embed-sources` option for the source-map to control whether the sources are embedded. The dart API allows to access this feature because it exposes the SingleMapping object directly which has the feature. the legacy JS API also has an option for that
However, the new JS API does not seem to expose such feature. and the issue on the embedded protocol has been closed without feedback: https://github.com/sass/embedded-protocol/issues/46

**Comment by Awjin** [comment]
It would be useful to support this behavior. @stof do you want to drive the design process for this?
