### ISSUE TITLE
`Invalid parent selector` when parent selector has pseudo selectors and appending

### ISSUE THREAD

**Issue by emattias** [sass/sass#3198]
This crashes sass with `Invalid parent selector ":not(.no-global-styles)"`

```scss
.parent-selector:not(.no-global-styles) {
	...
	&--active {
		...
	}
}
```

This is a workaround I did:
```scss
.parent-selector:not(.no-global-styles) {
	...
}

.parent-selector--active:not(.no-global-styles) {
	...
}
```

Which changes the order of the selectors which can change what selector takes precedent. This can cause unintended consequences.

Is there another way to handle this case where you need to append to a selector that has pseudo selectors? Could sass change it so that it appends pseudo selectors to the end of the appended selector instead of appending it after the pseudo selectors like it does now (which results in an invalid selector).

**Comment by jathak** [comment]
This is working as intended. Appending to the parent selector always just adds the suffix to the end of the parent. When that's invalid (`.parent-selector:not(.no-global-styles)--active` in this case), it results in an error.

If you need more complex handling here, you should just write it by hand. If this sort of logic is repeated in multiple places, consider writing a mixin.

**Comment by stof** [comment]
btw, this sort of things is exactly why the upcoming CSS nesting spec won't allow such selector suffixes in the CSS nesting feature...
