### ISSUE TITLE
Support "empty" namespace attribute selector [|attr] (pipe symbol)

### ISSUE THREAD

**Issue by pjeweb** [sass/sass#3199]
While migrating from LibSass we encountered a small difference that breaks our - admittedly uncommen - but css spec compliant use of "empty" xml namespace attribute selectors [1].

Input:
`[|att] { color: green }`

Expected output (no changes):
`[|att] { color: green }`

Actual error message:
```
    Error: Expected identifier.
      ╷
    1 │ [|attr]{ color: green }
      │  ^
```

1) https://www.w3.org/TR/selectors-3/#attrnmsp

**Comment by pjeweb** [comment]
Current workaround for us is patching the JS blob. This is for DartSass (`npm install sass@1.43.4`):
```
diff --git a/node_modules/sass/sass.dart.js b/node_modules/sass/sass.dart.js
index 374b92f..8b225c7 100644
--- a/node_modules/sass/sass.dart.js
+++ b/node_modules/sass/sass.dart.js
@@ -85356,7 +85356,7 @@ self.readline = _cli_pkg_requires.readline;
       else if (normalize && first === 95) {
         t1.readChar$0();
         text._contents = t2 + H.Primitives_stringFromCharCode(45);
-      } else if (first === 95 || T.isAlphabetic1(first) || first >= 128)
+      } else if (first === 95 || first === 124 || T.isAlphabetic1(first) || first >= 128)
         text._contents = t2 + H.Primitives_stringFromCharCode(t1.readChar$0());
       else if (first === 92)
         text._contents = t2 + H.S(_this.escape$1$identifierStart(true));
```

Where `124` is the Code for the Pipe symbol (vertical line).

This should relate to the source at https://github.com/sass/dart-sass/blob/55cb4fd5097975dc8fe11fa423ac9c1520c4f950/lib/src/parse/parser.dart#L170. I am not sure if this should be a change to `isNameStart` or an addition in this if-expression.

**Comment by stof** [comment]
Well, your proposed fix is the wrong one. `|` is not a name start character at all (your change would allow `|` in all identifiers, which is clearly wrong). The right fix would have to happen in the selector parser.

**Comment by pjeweb** [comment]
> Well, your proposed fix is the wrong one. `|` is not a name start character at all (your change would allow `|` in all identifiers, which is clearly wrong). The right fix would have to happen in the selector parser.

Thanks for the feedback. That was my first look at the (dart) sass source, so I was missing the bigger picture. I hope I found the right place now (see pull requests).
