### ISSUE TITLE
Sass master incorrectly identifies its VERSION

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#32]
it claims it is 3.1.0.alpha.0 when it's actually 3.1.0.alpha.50. This makes it impossible for users to bundle compass with sass master.

**Comment by chriseppstein** [comment]
You should check out what compass does for dev builds I think it's pretty clever and works really well.

**Comment by nex3** [comment]
Do you have a link?

**Comment by chriseppstein** [comment]
https://github.com/chriseppstein/compass/blob/master/lib/compass/version.rb#L31-33

**Comment by nex3** [comment]
This is fixed by the new versioning scheme I just pushed (see ec89f4f5831b98572f2d1ffd23203ea58d1ecbd8).
