### ISSUE TITLE
[Request] Allow default mixins, functions, variables refrenced by namespace only.

### ISSUE THREAD

**Issue by slynagh** [sass/sass#3202]
I'm working on a project where all mixins are defined within their own file, grouped in a mixins folder and `@forward`ed via `_index.scss`. This works fine in the following example:
```
// classes/_some-class.scss
@use "../mixins";
.some-class {
  @include mixins.make-stuff;
}
```

When a mixin needs to `@use` other mixins, this system becomes problematic,
since it @using a @forwarded version of itself, and leads to errors.
```
// mixins/_make-stuff.scss
@use "../mixins"; 

@mixin make-stuff {
  @include mixins.reset-stuff;
  @include mixins.icon;
}
```

So instead I need to use those mixin files explicitly.
```
// mixins/_make-stuff.scss
@use "reset-stuff";
@use "icon";

@mixin make-stuff { 
  @include reset-stuff.reset-stuff;
  @include icon.icon;
}
```
This doesn't read very well.
Since those files only contain the one mixin, I find myself wishing I could do the equivalent of a JS `export default` and have the mixin itself accessible through just the namespace:

```
// mixins/reset-stuff
default @mixin reset-stuff() { ... }

// mixins/icon
default @mixin icon() { ... }

// mixins/make-stuff
@use "reset-stuff";
@use "icon";
@mixin make-stuff {
  @include reset-stuff();
  @include icon()
}
```
I'm aware I can @use as * but that leads to conflicts. The same principle could also be applied to functions and variables (especially maps).

Or else should is there another approach I could use?

**Comment by jathak** [comment]
This is something we're unlikely to add, as it's not clear if I see something like `@include icon()` whether that's supposed to refer to the default mixin in namespace `icon` or a mixin called `icon` declared in the current file.

I'm not seeing why forwarding all your mixins through an `_index.scss` file isn't working. There shouldn't be a difference between getting the mixin directly from the declaring file or via a `@forward`.

**Comment by slynagh** [comment]
Then perhaps this is a bug report.
![image](https://user-images.githubusercontent.com/7286688/144991230-ccbe6115-7161-452f-91e5-46e6b782afd9.png)

What is expected behaviour if a module loads its parent index file? In effect it is loading itself.

The above example, `mixins/_card.scss` uses other mixins.

**Comment by jathak** [comment]
That is working as intended. You're not allowed to create a dependency loop. If you have multiple files that need to depend on each other and you want to expose them as a single module, you can still forward them all through one entrypoint for downstream users, but they should `@use` each other directly when necessary.

If the members of the two files are so intermingled that you truly need them to share the same global namespace, it probably makes more sense to just make them a single source file.
