### ISSUE TITLE
@import deprecation without LibSass support of its alternative?

### ISSUE THREAD

**Issue by ygoe** [sass/sass#3203]
I've just read about [the deprecation of `@import`](https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline) and its replacement `@use`. While I haven't fully understood the reasons behind this yet (and not making variables available globally completely destroys my use of a settings file with all these variables), I'm worried about the future of the language if LibSass doesn't support the alternative yet. You want to remove it (also from LibSass) before implementing the alternative. This takes away an essential feature of SASS from the only compiler that I have (`sassc`). Is that your plan? In that case I'd need to think about moving away from this language and finding (or forking) an alternative. Or simply stick with the latest functional version of the language for an indeterminate time.

**Comment by jathak** [comment]
`@import` is not yet deprecated. It will be eventually, and our original plan had been to do so two years after the module system release, but we've pushed that back to give more time for the ecosystem to migrate.

[LibSass, however, _**is**_ deprecated](https://sass-lang.com/blog/libsass-is-deprecated), so future language changes are not blocked on LibSass support, just as has been the case with Ruby Sass for some time.

All Sass users should migrate away from LibSass and to Dart Sass, which is available as a native executable on all major platforms, and in compiled-to-JS form via the npm `sass` module.

**Comment by nex3** [comment]
For some historical context, we did originally work with the LibSass maintainers to come up with a timeline that would have seen the module system launched simultaneously in both Dart Sass and LibSass. However, they didn't end up having enough bandwidth to implement it then or at any point since then, which was a major factor in our decision to deprecate that implementation in the first place.
