### ISSUE TITLE
variables are now out of scope when declared above import statements?

### ISSUE THREAD

**Issue by patrick99e99** [sass/sass#3204]
My stylesheets do something like:

```
# application.scss
$color: golden-brown;
@import 'waffles';
```
```
# waffles.scss
.yummy { color: $color }
```

I am using webpack with sass-loader, and previously this would work just fine-- but since upgrading to webpack 5, I am now getting `SassError: Undefined variable` in regard to `$color`.

Sass' documentation says:
Variables declared at the top level of a stylesheet are global

Why am I getting undefined variable errors?

I opened this issue on sass-loader and they told me to re-open it here........

**Comment by jathak** [comment]
I'm unable to reproduce this in Sass on it's own, which makes me think this is indeed a sass-loader bug (and should be reopened there).

What version of Sass is sass-loader using?

**Comment by patrick99e99** [comment]
```
"sass-loader": "^12.3.0",
"sass": "^1.28.0",
```

**Comment by jathak** [comment]
Can you try bumping the Sass version up to the latest (1.43.4)?

**Comment by patrick99e99** [comment]
Just updated to latest, no change...  Still get: `SassError: SassError: Undefined variable.`

**Comment by jathak** [comment]
My guess is that Webpack is attempting to compile `waffles.scss` as a standalone file, in which case it doesn't have access to the `$color` variable from `application.scss`. That sounds like either a bug in Webpack/sass-loader or a misconfiguration, so I'm going to close out this issue.

In general, we recommend avoiding this pattern by explicitly `@import`-ing or `@use`-ing each file that you need variables from in the file that uses them.

**Comment by patrick99e99** [comment]
Ok...  I reopened the issue on sass-loader.

If this is in-fact an anti-pattern, can you give me a suggestion on how to properly override variables?

For example, bootstrap-sass says to do:
```
$icon-font-path: "bootstrap-sass/assets/fonts/bootstrap/";
@import "bootstrap-sass/assets/stylesheets/bootstrap";
```

How am I supposed to alternatively set this $icon-font-path?

Also, my app, based off of user preferences knows to use `application.scss` vs `application_dark.scss` (for dark colors).

This has been implemented with:
```
# application.scss
@import 'colors'
@import base'
```


```
# application_dark.scss
@import 'dark_colors'
@import base'
```

...  Without this sort of global variable functionality, I can't see how to accomplish something like this with `@use` ?  There'd be no way for each stylesheet to know whether to `@use 'colors'` or `@use 'dark_colors'` ...  How does one accomplish this if not with global variables?
