### ISSUE TITLE
No replacement for to-be-deprecated @import available

### ISSUE THREAD

**Issue by ygoe** [sass/sass#3208]
I've now switched my toolset from libsass/sassc to dart-sass to use the latest language features. I also tried to remove the `@import` that should be deprecated at some time. But I wasn't able to get things to work as before.

First off, I'm writing a single library. No external code, no external users, no external contributors outside of my source files. So there is zero name conflict potential. This makes all the reasons to deprecate `@import` pointless in the first place. Yet I'll have to give it up sometime so I want to be prepared. And if language changes are required for that, we'll have enough time to implement them.

My library uses these files, as a simplified example:

* root.scss → root.css
    * normalize.css (Some general bootstrap stuff)
    * _settings.scss (Variables for everything in my library)
    * _functions.scss (A few helper functions like for colours)
    * plugins/_plugin1.scss (Library feature 1)
    * plugins/_plugin2.scss (...)

root imports normalize, settings, functions and all plugins. The content of normalize, then root's own content and then all plugins is the resulting CSS output.

Each plugin imports settings and functions and uses them as global names. Most of them are variables, some of which I'll replace with CSS variables later.

Today `@import` works perfectly here. But when I replace that with `@use "file" as *`, then nothing works anymore. First the imports of root after its own content are impossible with `@use` because that must come at the top of the file which is the wrong place. Second, I get errors about duplicate variable definitions that I don't understand and that were never a problem. These must be from the same file parsed multiple times. Wasn't that exactly the problem that should be solved? Instead, it was now *introduced*!

So, what exactly is the functionally equivalent replacement syntax of `@import`? If there is none, I guess the language will be less powerful than before and I might need another solution.

**Comment by ygoe** [comment]
After fiddling with this for some time, I changed my code structure so that the root file does not contain any content but only imports other files. All CSS rules are now moved to separate files, nothing is in the entry file anymore. In this case I can use `@use "file" as *` for the settings and `@use "plugin"` for all plugins in the root file. This seems to work now. But I'm wondering if Sass is trying to advocate that the entry file must only contain import/use directives and no actual content. That's a strange limitation that I don't understand. Maybe it's a bug, too. Or a common scheme of web developers these days that tend to prefer hundreds of tiny files over a handful of more complete files.

PS: Most of my Sass variables have been converted to CSS variables anyway, I'm not using Sass variables much anymore. Only for places where CSS doesn't support variables, like media query conditions or selector strings.

**Comment by ygoe** [comment]
I found another bug with `@use` replacing `@import`. My main entry file has a license banner comment in the first line, then follow some includes of the module files. With `@import` this comment comes first, then follows all the included content. With `@use`, the included files come first, then follows the comment from the top of the file. My license banner comment is now placed at the very end of the generated file! Nobody can find it there. The first of the included files has its own license comment which now ends up at the beginning of my bundled file. Now it looks like my file it something else because that's the comment at the top. Looks like I'll have to continue using `@import` in new projects as well. You simply can't remove it from the language, it's required!

**Comment by jathak** [comment]
The module system specifically wants to eliminate all stylesheets within a compilation sharing the same global namespace. Making it explicit where Sass members are coming from is one of the main goals of the module system.

The limitations of `@use` are by design, as they prevent patterns that make your code less readable and maintainable. Some things that were possible with `@import` will not be with the module system.

**Comment by ygoe** [comment]
Okay, so it's official that `@use` takes away important features of the language. Let's hope that `@import` will never be removed because that will be a very sad day.
