### ISSUE TITLE
Mix of class and input

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#321]
I know this is again gonna sound like I'm trying to LESSify SASS but I think it would be really useful to have some sort of function to act as a mix between a class declaration and a mixin declaration.

In LESS any class can be a mixin and any mixin can be a class. Although that sounds too messy for my taste, I like the idea of being able to use predefined properties both in my SASS file as a mixin and in the HTML code as a simple class. Is there a current way to do so or a planned function that would go in that direction ?
It's particularely useful in frameworks like Bootstrap where a lot of classes need to be used.

**Comment by chriseppstein** [comment]
Sass provides the @extend directive for working with classes.
