### ISSUE TITLE
Document syntax of placeholder selectors

### ISSUE THREAD

**Issue by dabrahams** [sass/sass#3212]
A small thing, but I couldn't find it in the docs.  Information on which tokens are allowed in a placeholder selector, and how `\`-escaping can be used to include anything, might be useful.  Thanks!

**Comment by jathak** [comment]
Placeholder selectors use the same syntax as any [CSS identifier](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram), just with a `%` in front.

**Comment by dabrahams** [comment]
Nice.  Please put that in the documentation.

**Comment by nex3** [comment]
The sass-lang.com documentation isn't meant to be a comprehensive language spec; we have [a separate language spec](https://github.com/sass/sass/tree/main/spec#readme) for that. The documentation says that placeholder selectors "look and act" like class selectors, which I think is sufficient to informally indicate that they have the same syntax other than the starting character.

**Comment by dabrahams** [comment]
I understand, thanks. I'm impressed that you're writing a formal spec; so many projects don't.   As a language weenie myself, I certainly would have gone to look at the formal spec had I been able to find it.  Shouldn't there be a (more prominent?) link from the informal to the formal docs?

I don't see a mention of `%` in the [syntax](https://github.com/sass/sass/blob/main/spec/syntax.md), and given the lazy policy (“as needed for new proposals“), I don't see how this would ever get clarified in the formal doc either.  Just sayin'.
