### ISSUE TITLE
Problem with file names in dart-sass

### ISSUE THREAD

**Issue by KoenigAlfonz** [sass/sass#3217]
So, I just realized that apparently all sass files now have to start with an alphabetic character.

The problems occuring here are the following:

![sass-filenames](https://user-images.githubusercontent.com/51205241/146428199-25f58935-55c2-46a5-8fa8-f4a9ad5db2fb.png)

1.  files can no longer be ordered to create a sensible structure
2.  index files are getting lost in between all other files within the same directory

Off goes all clean structuring of larger sass projects. The more files added in a directory, the more confusing and time consuming it gets, which when dealing with a framework on a daily basis (at work) is really costing a lot of time and money in the long term.

I don't know why changes like that have to be made to occur out of nowhere, so that the transition from lib-sass to dart-sass turns out to be more and more frustrating.

Any alternatives for better structuring are welcome!

Maybe, this decision could be overthought, since this one is such a little thing with such a big effect.

**Comment by stof** [comment]
Well, only if you want to use the default namespace. If you use an explicit namespace for the `@use`, the file name can be anything (btw, the latest version of dart-sass has a better error message for that case)

**Comment by stof** [comment]
note that this is not related to libsass vs dart-sass, but to `@import` vs `@use`. The `@import` directive does not generate any namespace that needs to be an identifier. And if libsass implements Sass modules one day, it will have the same restriction for `@use`

**Comment by KoenigAlfonz** [comment]
> Well, only if you want to use the default namespace. If you use an explicit namespace for the `@use`, the file name can be anything (btw, the latest version of dart-sass has a better error message for that case)

Uhh, thank god. This is a life-saver. Didn't expect there to be a difference, but kind of silly, that I didn't check that either.

> note that this is not related to libsass vs dart-sass, but to `@import` vs `@use`. The `@import` directive does not generate any namespace that needs to be an identifier. And if libsass implements Sass modules one day, it will have the same restriction for `@use`

Yup, I noticed that too some time later


Thanks a lot for your help! It seems like I have some catching up to do on the module-thing
