### ISSUE TITLE
Need help, when migrating from LibSass to DartSass

### ISSUE THREAD

**Issue by KoenigAlfonz** [sass/sass#3218]
Hello,

it seems like, I'm currently unable to accomplish a migration to the recommended Sass version and I am further more not sure, if a migration is technically at all possible.
Imagine the following scenario:

Let's say, we have two folders,
- one containing a sass framework creating general styles and css variables plus a bunch of utility-classes and placeholder selectors to be made available in the theme files (other folder).
- the other containing multiple themes, each consisting of a global config file and a collection of components.

Since the framework is using all the config variables in the theme's config files, these had to be imported first, then the framework, so that each theme could share the same framework folder, feed it with different config variable values to create different and unique final css files, each time.

If I understand sass-modules correctly, there is no longer a way to use variables from another file, without @use importing that file first. But here is the thing: If I want to keep this extremely efficient and neat concept, I would have to @use all the theme config files inside the framework folder, which is obviously not possible because these theme config files all have the same variables and I can not assign multiple variables at once.

After all, I am afraid that DartSass has stripped support for this concept entirely.

Any help would be well appreciated.

Let me know, if I have to further explain exactly what I mean or provide an example zip.

**Comment by stof** [comment]
To me, the way to go would be to have one file in the framework that defines all the themable variables as configurable variables. All other framework files would then use that file.

On the theme side, each theme entrypoint (or maybe the config file, depending on the exact architecture) would start with the configuration of the framework theme (before import other parts that use that theme layer)

```scss
@use 'framework/theme' with ($themeVar1: ..., $themeVar2: ...);
@use 'button'; // or whatever else you need to import
```

The idea is to distinguish the theme *API* defined by the framework from the *values* passed to this API (which are different for each theme).

**Comment by KoenigAlfonz** [comment]
Wow, that sounds interesting. I will dive into it soon and let you know the results.

Thank you!!

**Comment by KoenigAlfonz** [comment]
Ok, so unfortunately this is not gonna work like that. It says, using "with" is not allowed after using it somewhere else (in the framework)

![use-with](https://user-images.githubusercontent.com/51205241/147020467-94d32c6b-cf01-4137-8750-49026d4de5b3.png)

Good thought though. Did I understand you correctly?

**Comment by stof** [comment]
@KoenigAlfonz can you share a full reproducer ?

**Comment by stof** [comment]
In my previous comment, I also said that the theme file should configure the framework theme module (`framework/theme` in my example, but it could be anything else) **before** importing other framework files (so that the configured usage is the first usage)

**Comment by KoenigAlfonz** [comment]
> In my previous comment, I also said that the theme file should configure the framework theme module (`framework/theme` in my example, but it could be anything else) **before** importing other framework files (so that the configured usage is the first usage)

Yeah, I did that. I know, I previously said it would be only one config file (because I thought, it wouldn't make much difference) but in this case, I actually got a whole bunch of them (each to configure a set of placeholder-selectors and utility classes) plus one global theme-config.

Ok, then I created configurable variables for all of them but since they need to use some functions, they have to @use the functions file as well, which itself is @using variables from said configurable variables and then at some point, I am always ending up with that error message.

It is kind of a spiral of death, where everyone has to import this and this, here and there and in the end, it's always cracking, not to mention the extra layers of complexity it brings for no reason.

> @KoenigAlfonz can you share a full reproducer ?

I can send you the whole thing using @import and my attempts of using the module-system at some point, if you are interested. For now, I probably stick with @import.
I don't want to offend anyone but to be honest, I never really understood, why the module-system was introduced. I can see, that it makes sense in JavaScript with NodeJS, but I personally don't think, that Sass is a good use case for it, because it's definitively creating more problems than it solves. I mean, namespacing variables? Common, just write the namespace into the variable name.

I appreciate your help a lot though. I will continue to try it, for a bit. Let's see...

**Comment by nex3** [comment]
@KoenigAlfonz I don't personally recommend the use of configurable variables in a case that's this complex. I agree that it's a good idea to define a `framework/_theme.scss` file as @stof suggested, but instead of changing the variables using `@use ... with`, I recommend directly writing to them in the individual theme files:

```scss
@use "framework/theme";

theme.$highlight: #abc;
// ...
```

Or, if you want more control over when each individual theme is activated, you could even wrap that in a mixin:

```scss
@use "framework/theme";

@mixin dark {
  theme.$highlight: #abc;
  // ...
}
```

**Comment by stof** [comment]
Regarding the issue of circular dependencies between modules, this will still be an issue both with my suggestion and @nex3's one. However, the solution using `@import` also suffers from that, except that it is a lot less explicit about it (and will probably do weird things instead of failing).
The solution for that is to organize the functions and variables in modules corresponding to features (or other logical domains) rather than by type of member (all variables in one file and all functions in another one). When organizing by feature, I never found a situation needing to rely on circular dependencies (while it was indeed common when organizing by type).

**Comment by stof** [comment]
Regarding the issue of circular dependencies between modules, this will still be an issue both with my suggestion and @nex3's one. However, the solution using `@import` also suffers from that, except that it is a lot less explicit about it (and will probably do weird things instead of failing).
The solution for that is to organize the functions and variables in modules corresponding to features (or other logical domains) rather than by type of member (all variables in one file and all functions in another one). When organizing by feature, I never found a situation needing to rely on circular dependencies (while it was indeed common when organizing by type).

**Comment by KoenigAlfonz** [comment]
@nex3 thanks for your support. It sure looks interesting and also allows for assigning variables to variables, but as @stof said, it's still not solving the issue.

**Comment by KoenigAlfonz** [comment]
@stof I see what you mean. Unfortunately, I can't really change the whole structure though, so I may end up creating standalone theme-versions using the module-system as an alternative.

**Comment by stof** [comment]
> but instead of changing the variables using `@use ... with`, I recommend directly writing to them in the individual theme files:

@nex3 can you explain why you recommend that ? The effect is that the theme file would then be forbidden to use some of the variables to compute other variables (or the default values of other variables), as those computations would run before changing the variables.

**Comment by nex3** [comment]
@stof I'm having trouble following. Can you provide an example?

**Comment by stof** [comment]
```scss
// framework/_theme.scss

$linkColor: rebeccapurple !default;
// By default, buttons are using the same color than links, but themes are allowed to change that
// by configuring a specific button color
$buttonColor: $linkColor !default;
```

Using `@use "framework/theme" with ($linkColor: green)`, the `$buttonColor` will also be green, respecting the intent documented in the comment. With your proposal doing `theme.$linkColor: green`, `theme.$buttonColor` will be `rebeccapurple`

**Comment by nex3** [comment]
Then make the theme itself a mixin as well:

```scss
// framework/_theme.scss

$link-color: null;
$button-color: null;

@mixin override($link-color: null, $button-color: null) {
  $link-color: $link-color or rebeccapurple !global;
  $button-color: $button-color or $link-color !global;
}

// Set up the default values.
@include override();
```

```scss
// framework/_dark.scss

@use "framework/theme";

@mixin dark {
  @include theme.override($button-color: #abc);
}
```

Generally speaking, you can always model the behavior of an `@import`-style graph with side effects by wrapping each module in a mixin whose parameters are the configurable variables.
