### ISSUE TITLE
extended compatibility rules (feaure)

### ISSUE THREAD

**Issue by andresbott** [sass/sass#322]
Feature Request:
when aplying rules like box-shadow, for browser compatibility you also apply -moz-box-shadow and -webkit-box-shadow. 
It woud be great that sass checks for this rules, and if not present adds them to the css.

there are some rules comonly used widh hacks.

**Comment by chriseppstein** [comment]
Sass enables frameworks which provide this capability. See: http://compass-style.org/reference/compass/css3/
