### ISSUE TITLE
Theming/Customizing of React Component Library

### ISSUE THREAD

**Issue by newlukai** [sass/sass#3222]
## Scenario

Imagine we have
- a simple (TypeScript) React app "ExampleApp", built using `create-react-app`
- and a node module "@example/components" which
  - incudes React Functional Components written with TypeScript
  - styled with *.module.scss files
  - is transpiled to JS using babel
  - and thus exposes JS modules which `require` the unmodified *.module.scss files.

## Requirement

We now want to have a new React app "DemoApp" which, of course, should make use of the "@example/components". Since both apps have different designs we want to apply different styles to the "@example/components".

To me it seems important that
- the "@example/components" define some default/fallback styles
- it is possible for the "@example/components" to make use of properties one usually sees in the context of themes, like a primary and a secondary color
- an App is able to set theme properties like a primary color and the "@example/components" make use of that where it makes sense (defined by the component author)
- a page of an app overrides theme properties or component styles to apply an individual style.

## Problem

First of all: I'm new to SASS.

As we use SASS for styling both, the "@example/components" as well as the apps, I instantly tried to make use of variables.

1. In "Button.module.scss" define a variable `$button-background` and set a default value:
   ```scss
   // "@example/components"/src/components/Button/Button.module.scss
   $button-background: fuchsia !default;

   .button {
     background: $button-background;
   }
   ```
   As the SCSS file is just copied to the "dist" directory, the variable still is available in the "node_modules/@example/components/dist/components/Button" directory of the app project.
1. Use that Button component in a page:
   ```tsx
   import {Button} from "@example/components";
   import style from "./Page.module.scss";

   export const Page = () => (<div className={style.Page}><Button /></div>);
   ```
1. Override the `$button-background` in the "Page.module.scss" file:
   ```scss
   .Page {
     $button-background: blue;
   }
   ```

As you might guess, this does not work. To me it seems that SASS compiles the Button.module.scss file isolated. Thus, it would be necessary for SASS to have an `@import` or `@use` rule in the Button.module.scss file to get the desired value for `$button-background`.

## Solution?

Is there a possible solution for this or an approach to customization/theming of externalized components with SASS? Or to add a corresponding feature? The most similar issue I found is #2745 I guess.

## Other Approaches

There would be other options:
- CSS Custom Properties: absolutely matches the requirements, but I guess we would put too much load on the browser to track all the properties and styles.
- CSS-in-JS (JSS, Emotion, …) with a `ThemeProvider`
  - would force us to migrate away from SASS to another solution
  - would put the styles in the component, I like to have separate files
- custom props or using a `ThemeProvider` and `useTheme`: seems to only make sense with CSS-in-JS to weave the props into styles.

Would be great to read of your experiences. It's quite hard to find good resources regarding this topic. Maybe also be the case I'm totally lost in the wrong direction. Thanks in advance.

**Comment by stof** [comment]
When you import Sass files from a JS file in webpack, each import of a Sass file indeed triggers a compilation of that Sass file. The Sass compiler is not aware of anything happening in the JS code built by webpack.

**Comment by nex3** [comment]
e solution here would typically be to compile all of your components' CSS into a single stylesheet, and use mixins to allow customization of the components' default CSS like this:

```scss
// _button.scss
@mixin button($background: fuchsia) {
  .button {
    background: $background;
  }
}
```

```scss
// page.scss
@use 'button';

.Page {
  @include button.button($background: blue);
}
```

However, if React expects each component to have its own stylesheet that's directly imported by the component's TS/JS, then that approach won't work. As @stof points out, each stylesheet is its own separate Sass compilation, so they can't meaningfully override one another's Sass variables. In that case, you could either use CSS custom properties, or provide a mixin library *as well as* the base stylesheet in your component that users could use to override its styles using the cascade much as in my example above.

**Comment by newlukai** [comment]
Thank you very much for your input. :bow: 

Currently the plan is to make theming possible using MUIs ThemeProvider as well as CSS-in-JS using Emotion.
