### ISSUE TITLE
I have sass and sass-loader installed but my application is throwing me error to install node-sass to work with sass-loader 

### ISSUE THREAD

**Issue by daniyalmujtaba** [sass/sass#3224]
./src/index.scss (./node_modules/react-scripts/node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-scripts/node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/index.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.

this is the error 

Versions I am using 

"sass": "^1.45.1",
"sass-loader": "^12.4.0",
"react-app-rewired": "^2.1.8",
"react-scripts": "^2.1.3",
"webpack": "^5.65.0"

**Comment by stof** [comment]
This should be reported to the sass-loader issue tracker (but first, make sure that you use the latest version of the loader). This is not an error triggered by sass itself.
