### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by dchirag005** [sass/sass#3244]
Recommendation: math.div(1, $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │     ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                ^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 49:32  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
48 │     $rfs-base-font-size: $rfs-base-font-size /
   │ ┌────────────────────────^
49 │ │     ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │ └──────────────────────────────────────────────────^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 48:24  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 57:20  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
397 │ $headings-margin-bottom: ($spacer / 2);
    │                           ^^^^^^^^^^^
    ╵
    src/assets/scss/custom/_variables.scss 397:27  @import
    src/assets/scss/argon.scss 24:9                root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($r * 299 + $g * 587 + $b * 114, 1000)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
62 │   $yiq: (($r * 299) + ($g * 587) + ($b * 114)) / 1000;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/_functions.scss 62:9  color-yiq()
    src/assets/scss/custom/_variables.scss 716:31   @import
    src/assets/scss/argon.scss 24:9                 root stylesheet

DEPRECATION WARNING: $null: Passing a unit other than deg (25%) is deprecated.

To preserve current behavior: $null / 1%

See https://sass-lang.com/d/color-units

   ╷
19 │       adjust-hue($color, 25%) 100%
   │       ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/core/mixins/_background-variant.scss 19:7  bg-gradient-variant()
    src/assets/scss/core/utilities/_backgrounds.scss 10:3      @import
    src/assets/scss/custom/_utilities.scss 5:9                 @import
    src/assets/scss/argon.scss 66:9                            root stylesheet

WARNING: 68 repetitive deprecation warnings omitted.

**Comment by Awjin** [comment]
Using `/` as division is indeed deprecated. If you need Bootstrap to support the new syntax, feel free to file an issue with Bootstrap.
