### ISSUE TITLE
[Help Request] Understand why compiled SCSS is broken

### ISSUE THREAD

**Issue by boonware** [sass/sass#3248]
# Background
I am building a React project. In this project I am using Carbon for UI components. I do not have any custom webpack config, only the default from Create React App. My dependencies are as follows:

```
  "dependencies": {
    "@carbon/icons-react": "^10.44.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "carbon-components": "^10.50.0",
    "carbon-components-react": "^7.50.0",
    "carbon-icons": "^7.0.7",
    "history": "^5.1.0",
    "loglevel": "^1.7.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "redux": "^4.1.2",
    "web-vitals": "^1.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/eslint-parser": "^7.15.4",
    "@babel/preset-react": "^7.16.0",
    "babel-jest": "^27.4.2",
    "eslint": "^8.4.1",
    "eslint-config-airbnb": "^19.0.2",
    "eslint-plugin-flowtype": "^8.0.2",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jest": "^25.3.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.27.1",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-testing-library": "^5.0.1",
    "redux-mock-store": "^1.5.4",
    "sass": "^1.48.0",
  },
```

# Problem
The SCSS in the production build of the project is broken. When I open the production build in my browser I see errors in the console for a number of SCSS files: `Ruleset ignored due to bad selector`. I have confirmed this is broken on Firefox, Safari and Chrome. The SCSS files that are referenced are coming from the Carbon library. This is one of the files: [_side-nav.scss](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/ui-shell/_side-nav.scss). When I inspect the file in my browser I see invalid SCSS, for example:

```
@mixin expanded($opacity: false, $visibility: false) {
  @if $opacity == {
    opacity: 0;
  }
```

Note the missing boolean value. When I check this file in the Carbon repo (see link above) the code is correct on line 41:
```
@mixin expanded($opacity: false, $visibility: false) {
  @if $opacity == true {
    opacity: 0;
  }
```

I am at a loss to understand why the SCSS from the Carbon library, when compiled in my app, ends up broken. Note the app works fine when run from `npm start`, i.e without a production build.

Any idea what's going on here, or how I may even begin to track down the root cause?

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
