### ISSUE TITLE
API: Deprecation warnings should appear in results object, not logged to console.

### ISSUE THREAD

**Issue by broofa** [sass/sass#3251]
The current `sass` behavior of logging deprecation warnings to the console when invoked from the API is problematic for us (CodePen)

We use `sass` to process user-provided SCSS on our servers.  Any deprecations warnings that result from this need to be surfaced to our users, as part of our editor UI.   To do that, we need access to these warnings such that we can route them from the backend back to our users (in the browser).  The current practice of logging these warnings to the console makes this problematic.

First of all there's the matter of having user-content related warnings in our production logs.  This is just noise to us, as they're not something we can / should be acting upon.  Not a huge deal, as we can figure out how to ignore these warnings, but it's annoying.

Of more concern is the fact that these warnings are completely invisible to the code that's calling `sass` and passing the results back to the browser clients (where the warnings should actually be displayed).  There's no exceptions being thrown, and no hint of problems in the data structure returned by `compile()` or `compileString()`.

[Edit to add: This also makes a mess of our unit test logs.  Strictly a cosmetic issue, but still... annoying.]

To fix this, we'd like to see deprecation warnings included in the results structure rather than in the console.   I.e.  For this script...

```javascript
const sass = require('sass');
console.log('RESULT', sass.compileString(`$width: 20% / 100%`));
```

Instead of the current behavior, which is to output this:
```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20%, 100%)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
1 │ $width: 20% / 100%
  │         ^^^^^^^^^^
  ╵
    - 1:9  root stylesheet

RESULT { css: '', loadedUrls: [] }
```

... it would be preferable to see something more like this (console output suppressed, `deprecations` array added to result structure):
```
RESULT {
  css: '',
  loadedUrls: [],
  deprecations: [
    {
      message: 'Using / for division is deprecated and will be removed in Dart Sass 2.0.0.',
      location: '1:9-18' // i.e. full location of error, as highlighted in current log output.  So, "line 1, chars 9-18"
    },
    etc...
  ] 
}
```

**Comment by jathak** [comment]
You can use the [Logger API](https://sass-lang.com/documentation/js-api/modules/Logger) for this.

**Comment by broofa** [comment]
Oh, cool!  Thanks.  'Didn't see that API in the docs. 😛
