### ISSUE TITLE
Import relative-path assets from a Sass module from another Sass module

### ISSUE THREAD

**Issue by ghost** [sass/sass#3253]
I'm unable to import fonts from relative-path when the source is imported via `@use` from another source. For example:

`src/a.scss`

```sass
@use './somewhere/else/b.scss' with (
    $foo: #fff,
);
```

`src/somewhere/else/b.scss`

```sass
@font-face {
    font-family: "Roboto";
    font-weight: normal;
    src: url("./roboto-regular.ttf") format("ttf");
}

$foo: #fff !default;
```

Sass thinks `roboto-regular.scss` is located at `src/roboto-regular.scss`, but it should be `src/somewhere/else/roboto-regular.scss`. I'm using Parcel for the build process.

Actual code: [www.github.com](https://github.com/recoyx/appcreator-sample)

Minimum reproducible project: `npm install && npm run compile` [www.github.com](https://github.com/Klaider/parcel-sass-sample)

**Comment by Awjin** [comment]
Sass does not resolve `url()`, so the URL you pass it must be relative to the root.

```
src: url("somewhere/else/roboto-regular.ttf")
```

Support for custom URL loaders is being proposed in https://github.com/sass/sass/issues/2535.
