### ISSUE TITLE
Autocomplete for dynamic scss generated code

### ISSUE THREAD

**Issue by SvenBudak** [sass/sass#3255]
Hi! Maybe I just missed the docs describing this.... but I was not able to find a way to make autocompletions available in my IDE for dynamically generated code:

```scss
// Headline Styles
@if $headline-styles {
  @each $variant, $variantObject in $headline-variants {
    .typo-#{$variant} {
      font-size: var(--#{$variant}-font-size-rfs) !important;
      font-weight: var(--#{$variant}-font-weight) !important;
      line-height: var(--#{$variant}-line-height) !important;
    }
  }
}
```

When I type `.typo` in my .html files, I don`t get autocomplete. My idea now was to write autocomplete files that can be generated with a separate scss build script before I start developing the site.... but that feels a bit dirty.

**Comment by Awjin** [comment]
You will have to file a bug with the IDE that you use. Sass itself has no knowledge about IDE autocompletion.
