### ISSUE TITLE
Support constants in calc()

### ISSUE THREAD

**Issue by nex3** [sass/sass#3258]
- [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/calc-constants.md)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1900) (https://github.com/sass/dart-sass/pull/1922)
- [x] [Tests](https://github.com/sass/sass-spec/issues/1885) (https://github.com/sass/sass-spec/pull/1890)
- [x] [Documentation](https://github.com/sass/sass-site/issues/700) (https://github.com/sass/sass-site/pull/707)
- [x] Update canonical spec (https://github.com/sass/sass/pull/3519)

---

Values and Units 4 defines `pi`, `e`, `infinity`, `-infinity`, and `NaN` [constants for use in `calc()` expressions](https://drafts.csswg.org/css-values-4/#calc-constants). We should support these as they land in browsers. The current status (as of 8 February 2022) is:

* [x] `infinity`: [landing in Chrome 99](https://blog.chromium.org/2022/02/chrome-99-css-cascade-layers-new-picker.html?m=1)
* [x] `-infinity`: [landing in Chrome 99](https://blog.chromium.org/2022/02/chrome-99-css-cascade-layers-new-picker.html?m=1)
* [x] `NaN`: [landing in Chrome 99](https://blog.chromium.org/2022/02/chrome-99-css-cascade-layers-new-picker.html?m=1)
* [x] `pi`: unsupported anywhere as far as I can tell
* [x] `e`: unsupported anywhere as far as I can tell

For the degenerate constants (`infinity`, `-infinity`, and `NaN`) we should not only support parsing them in `calc()` expressions but also serializing Sass numbers with those values *to* `calc()` expressions.

**Comment by luiscla27** [comment]
I think this enhancement is _a kind of_ dup of  #2954 

(I was looking for [general purpose constants](https://github.com/sass/sass/issues/3398) but found yours and the suggested dup instead)

**Comment by nex3** [comment]
They're different—https://github.com/sass/sass/issues/2954 would add support for `math.$infinity`, `math.$negative-infinity`, and `math.$nan` (`math.$pi` and `math.$e` already exist). This would add support for `calc(infinity)`, `calc(-infinity)`, `calc(NaN)`, `calc(pi)`, and `calc(e)`.

**Comment by nex3** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/calc-constant#browser_compatibility, all of these constants are now supported by Firefox (although interestingly it seems _none_ are supported in Chrome).

**Comment by nex3** [comment]
The proposal has landed. Since it's relatively unlikely to be controversial, I'll give it two weeks for public comment before declaring it implementable.
