### ISSUE TITLE
Error: undefined variable when using meta.load-css with $with

### ISSUE THREAD

**Issue by paceaux** [sass/sass#3260]
I am writing the following code:

```
$fa-css-prefix: 'fa' !default;
$fa-var-glass: "\f000" !default;



@include meta.load-css('objects/icons', 
    $with: (
        $fa-css-prefix: fa,
        $fa-var-glass: "\f000",
    )
)
```

My file, objects/icons.scss, contains the following:

```
.#{$fa-css-prefix}-glass:before { content: $fa-var-glass; }
```

When I do this, I get the error 

```
Error: Undefined variable.
  ╷
4 │ .#{$fa-css-prefix}-glass:before { content: $fa-var-glass; }
  │    ^^^^^^^^^^^^^^
  ╵
```

You can replicate this problem with [this repo and branch](https://github.com/paceaux/sass-use-problems/tree/non-module-meta-load-css-and-with). I run `npm run build:styles` to get this error. 

I don't think variables from the `$with` argument are getting passed into the module.

**Comment by jathak** [comment]
The with clause (in `@use` and `meta.load-css`) can only override variables that are already declared with `!default` in the stylesheet you're loading. See the documentation [here](https://sass-lang.com/documentation/at-rules/use#configuration).
