### ISSUE TITLE
Official support for SCSS Intellisense.

### ISSUE THREAD

**Issue by slynagh** [sass/sass#3262]
The current best choice for [SCSS Intellisense in VSCode](https://github.com/mrmlnc/vscode-scss) has limited support for the new module system and hasn't been updated in nine months. If the Sass team could find capacity to contribute to this plugin it would really make developing SCSS even more of a joy than it already is.

**Comment by Awjin** [comment]
Unfortunately, the Sass team has no extra capacity. We would certainly welcome community contributions here!
