### ISSUE TITLE
"@use" with dynamic path (load all breakpoints files with an "@each" loop)

### ISSUE THREAD

**Issue by spacecodeur** [sass/sass#3264]
I update an old personnal project (symfony v4 to v6). Inside it, I loaded all my breakpoints files like this : 

```dart
$grid-breakpoints: (
        xxxs: 0,
        xxs: 320px,
        xs: 568px,
        sm: 667px,
        md: 768px,
        lg: 992px,
        xl: 1200px,
        xxl: 1400px,
        xxxl: 1700px
);

@each $name, $value in $grid-breakpoints{
    @media (min-width: #{$value}) {
        @import url('custom/#{$name}/global');
    }
}
```

But this approach does not work with new version of sass ! after some searches, I understand I must use the "@use" sass instruction instead "@import"

I tried this

```dart
$grid-breakpoints: (
        xxxs: 0,
        xxs: 320px,
        xs: 568px,
        sm: 667px,
        md: 768px,
        lg: 992px,
        xl: 1200px,
        xxl: 1400px,
        xxxl: 1700px
);

@each $name, $value in $grid-breakpoints{
    @media (min-width: #{$value}) {
        @use url('custom/#{$name}/global');
    }
}
```

but I get an error : 

```bash
SassError: This at-rule is not allowed here.
   ╷
25 │         @use url('custom/#{$value}/global');
```

Then I tried this : 

```dart
$grid-breakpoints: (
        xxxs: 0,
        xxs: 320px,
        xs: 568px,
        sm: 667px,
        md: 768px,
        lg: 992px,
        xl: 1200px,
        xxl: 1400px,
        xxxl: 1700px
);

@each $name, $value in $grid-breakpoints{
    @media (min-width: #{$value}) {
        @use 'custom/#{$name}/global';
    }
}
```

And I get the same error... ("This at-rule is not allowed here.")

Is it possible to use the @use instruction with a dynamic path ? if yes, how :?

my version of sass and sass-loader : 

- sass-loader@12.6.0
- sass@1.49.9

Thanks for any help :)

**Comment by slynagh** [comment]
Hi @kegilko check out `meta.load-css()` mixin.
https://sass-lang.com/documentation/modules/meta#load-css.
```scss
@use "sass:meta";

$grid-breakpoints: (
        ... 
);

@each $name, $value in $grid-breakpoints{
    @media (min-width: #{$value}) {
        @include meta.load-css('custom/#{$name}/global');
    }
}
```

**Comment by jathak** [comment]
Because you're using the `url()` function, Sass treats the `@import`s in your original code as plain CSS imports, which are just emitted as-is in your output CSS. Plain CSS `@import`s aren't going away, so you should leave them as-is.

If you do want to compile CSS from a dynamic path into your final code, then @slynagh's answer to use `meta.load-css()` is correct.
