### ISSUE TITLE
@use "@import" style instead of ":import"ing it

### ISSUE THREAD

**Issue by deadalnix** [sass/sass#3266]
It seems to me like the current behavior of @use when it comes to style in the imported sheet is erroneous, as all the styles get duplicated in the imported module - just like `@import` would do rather that refers to it in the used modules, like you'd expect from a module system.

Let me expand:

mymodule.scss
```scss
.someClass {
    width: 100%;
}
```
a.scss
```scss
@use "mymodule";

.someOtherClass {
    height: 100%;
}
```

Then using it:
```js
import styles from "a.scss";

console.log(a.someClass); // Outputs a_someClass_HASH
console.log(a.someOtherClass); // Outputs a_someOtherClass_HASH
```

The styles from module `mymodule` has been copied over to `a` instead of referring to the class of `mymodule`. This is wrong for a couple of reasons:

1. This causes code bloat, which in turn makes it hard to provide resuable scss components (unless they are pure scss and contain no CSS whatsoever, which is hard to enfore in practice, plus legacy codebase are not built with that assumption in mind).

See for instance:
a.scss and b.scss
```scss
@use "mymodule";
```

```js
import astyles from "a.scss";
import bstyles from "b.scss";
```

This will cause all the styles in mymodule to be generated twice with different mangling.

2. It is breaking CSS module abstractions by leaking copies of symbols across modules, making them interfere in unexpected ways. In many way, the argument is the same as for moving from `@import` to `@use` , you want the symbols defined upstream to stay there unless you import them. If we want that for variables, mixins and whatnot, why wouldn't we want that for CSS classes?

For instance:
a.scss
```scss
// What if someone adds this later?
.someClass {
    background-color: pink;
}
```
b.scss
```scss
@use "a";

.someClass {
    width: 100%;
}
```

Any change upstream can mess up downstream semantic, as if `as *` or `@import` was used. It is unfortunate that the behavior is sound for scss features, but not for the underlying CSS ones.

Fortunately, the [:import](https://github.com/css-modules/icss#import) mechanism from ICSS does exactly what `@use`ought to do here: providing a way to refers to CSS coming from another module, without generating copies. Considering sass relies on ICSS, it seems like it should leverage this for it lowering instead of doing a copy paste like it does now. We'd get the benefit of @use for CSS as well as scss specific features.

Related issues: #2791 and #3265 I think this strikes at the core of the issue here, rather than symptoms like in these two issues.

**Comment by jathak** [comment]
I think you're confusing Sass modules with some other module system provided by ICSS (which Sass has nothing to do with).

**Comment by deadalnix** [comment]
I'm not confusing. Both work at their level and provide benefits - in fact, many of the same benefit, but at their level of abstraction.

I could literally copy paste the whole rationale page about moving from @import to @use to justify moving from CSS to CSS modules (or ICSS).

Right now, both are actively working against each other. there is no sensible way to use CSS modules with sass, without effectively growing the generated CSS quadratically with the number of SCSS modules. There is really no reason for it to be the case.

There is no reason for it to be the case, and I don't really understand the reaction. This is a real problem experienced by real users at the moment and i don't see it decreasing as CSS module use is becoming more and more prevalent (and for good reason, just like @use is bound to replace @import over time).

What are user supposed to do with existing codebase here? Ship 20 versions of bootstrap or any other mainstream SCSS framework with different mangling with their website? Rewrite bootstrap entirely? None of these things seems reasonable.

Alternatively, if no dependency on ICSS is desired, then having sass being able to do it own mangling is also an option, in which case, sass can pick consistent names and post process could get rid of the redundancies. That would sidestep CSS modules entirely and provide the same benefit.

But I don't really see how the current situation where all classname are defacto application wide globals is a sensible path forward.

**Comment by jathak** [comment]
The Sass module system doesn't prevent you from using ICSS or some other system for scoping CSS, but they are two different tools which solve two different problems.

**Comment by deadalnix** [comment]
I think this is where there is something you are missing, it kinda does. Not strictly, one can use both, but the end result is a quadratic growth in the size of the generated CSS at the end of the pipeline.

**Comment by deadalnix** [comment]
To make sure I'm being clear, quadratic growth is generally pretty bad, but in the case of CSS specifically, where size matters, it is really bad.
