### ISSUE TITLE
Incorrect url module `require`d in FileImporter documentation

### ISSUE THREAD

**Issue by codemacabre** [sass/sass#3267]
A very small change, and only to documentation.

I spotted a mistake in the example code for [FileImporter](https://sass-lang.com/documentation/js-api/interfaces/FileImporter), where the first line imports [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl) from Node's `url` module. The implementation actually uses [`pathToFileURL`](), so the first line should change from:

https://github.com/sass/sass/blob/f355f602fc15f55b0a0a795ebe6eb819963e08a5/js-api-doc/importer.d.ts#L26

to:

```js
const {pathToFileURL} = require('url');
```

I initially thought this required a change on `sass/sass-site`, and followed the contribution guidelines there, but after finding the change is needed here and on reading the contributing guidelines for this repo that things are different, I haven't submitted my PR, but can do if it's easier. I have the change in a [fork](https://github.com/codemacabre/sass/tree/file-importer-docs-require-fix).

**Comment by jathak** [comment]
Go ahead and send the PR. The contributing guidelines are for actual changes to the language / JS API, but the API itself is correct here; it's just a documentation fix.
