### ISSUE TITLE
Error: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by DasGestirn** [sass/sass#3269]
**Folder structure:**
https://imgur.com/a/TcVv9eY

**Error:**
https://imgur.com/a/0Mu5FrS

Sass version is 1.49.9 compiled with dart2js 2.16.1.

ParcelJS solved my problem by being able to compile my Sass/Scss code into plain CSS but i don't want to use it in such a small project like this one.

OS:MX Linux.

**Comment by stof** [comment]
Well, Sass does not support importing files based on a fake absolute path (where the root of the absolute path is not the root of the filesystem but the root of your project, which is not known by Sass as it does not have such concept).

There are 2 solutions here:
- use the proper relative import (i.e. `@import "abstracts/reset"`)
- define a load path from which imports can be resolved (which might be what ParcelJS is doing). In the command-line, this is done using the `-I`/`--load-path` option. There, you would pass the root of your project (containing the `src` folder in your example) as a load path.

Note however that the `--quiet-deps` flag treats any import resolved using a load path as being a dependency (and so will silence warnings there). So in your case, the recommended approach is to use relative imports IMO.

**Comment by DasGestirn** [comment]
Thanks! It worked

**Comment by Aquaengraved** [comment]
Hi, 

Seems I got a similar issue, but i'm not sure what to do as my screen.scss already has the @import paths as above (in SCSS style rather than SASS). 

**Error:**
![image](https://user-images.githubusercontent.com/36793493/174191280-fd3f1fca-16c9-4b7b-a878-e826f3de70d5.png)

**Folder structure:**
![image](https://user-images.githubusercontent.com/36793493/174191396-d332e46b-cd0a-4867-b493-33665a464886.png)

**screen.scss:**
![image](https://user-images.githubusercontent.com/36793493/174191471-b12f5ab5-4605-4696-9469-25f75bdb22ba.png)

**style.css:**
![image](https://user-images.githubusercontent.com/36793493/174191494-abebc2e7-0655-4625-95e2-26a8a9b98b12.png)

Read your SASS basics. But can't seem to find something for this. 
Any advice would be appreciated.
Also if you need any extra information, let me know.

**Comment by nex3** [comment]
@Aquaengraved Because your `screen.scss` file is in `src/scss/modules`, the relative URL `modules/custom_variables` resolves to `src/scss/modules/module/custom_variables`. You should just write `@import "custom_variables"` instead.

**Comment by Aquaengraved** [comment]
Got it working. Thanks for helping out.

**Comment by Aquaengraved** [comment]
Hi,

Back here unfortunately. Not sure how/why, but for some reason today my compiler worked. Until at some point I moved the src folder over to another project. Now both projects the compiler no longer works?

I tried changing the import paths. I tried changing the path from where I was calling the sass command in the powershell. I can't seem to get it right. Am I missing something? See below updated screenshots.

Installed items: 
Nodejs 8.11.0
sass 1.53.0 with dart2 2.17.3

Goes for both projects.

![image](https://user-images.githubusercontent.com/36793493/175748819-8254b3ae-7758-4cb8-b315-13eece72034d.png)
![image](https://user-images.githubusercontent.com/36793493/175748833-dde7967c-5ff9-45b2-82a0-b97ff2d07a2a.png)
![image](https://user-images.githubusercontent.com/36793493/175748846-f7f7e1fe-3409-4452-8a3f-0d789965275f.png)

If you need any more info let me know. P.s. folder structure has not changed (you can compare current to last time) 
The only thing changed was that I put screen.scss in the same folder as style.css (for ease in the command).

**Comment by stof** [comment]
Well, if you move `screen.scss`, you need to adjust the relative path to other files. In your new location, `screen.scss` needs to use `@import "modules/custom_variables";` to find the file.

And `modules/_fonts.scss` needs to import `@import "custom_variables";` and not `@import "modules/custom_variables";` (the first error in your screenshot)

**Comment by interlinc-jpeichoto** [comment]
I am seeing the same issue. Not sure that I understand the above though. What do you need from me to be able to assist? Many thanks

**Comment by jathak** [comment]
@interlinc-jpeichoto This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large. To get a helpful answer from StackOverflow, I'd encourage you to add more details to your question, like what problem you are trying to solve, and which sections of your Sass code are actively breaking.

**Comment by netsanetamanuel** [comment]
what worked out for me is , you just have to specify the right director just type . . or dot dot to specify the directory and vscode automaticaly take you through . thank you

**Comment by vzakharov-rxnt** [comment]
I'm getting the same error when using Web Test Runner instead of karma. Not sure what to do.

```
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @use 'src/app/common/variables' as v;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\app\ad-free-button\ad-free-button-popup\ad-free-button-popup.component.scss 1:1  root stylesheet [plugin angular-sass]
```

And many other errors like this.
