### ISSUE TITLE
Variables inside Calc are not being replaced

### ISSUE THREAD

**Issue by Rybadour** [sass/sass#3275]
When writing a calc statement in Sass 1.49.9 it fails to replace any variables with their resulting values in the generated CSS.

Example:
```
$var: 20px;
.foo {
  width: calc(100% - $var * 2);
  margin: 40px;
  background: black;
  height: 40px;
}
```

Results in this CSS where the calc statement is now invalid because of the "$var":
```
.foo {
  width: calc(100% - $var * 2);
  margin: 40px;
  background: black;
  height: 40px;
}
```

JsFiddle seems to reproduce the issue as well: http://jsfiddle.net/2fLkwu0m/1/

**Comment by jathak** [comment]
I'm not able to reproduce this with Dart Sass 1.49.9. Are you sure that's what you're using?

JsFiddle is likely using a pre-1.40.0 version of Sass, before first-class calc was supported.

**Comment by Rybadour** [comment]
Ah, nevermind. Not sure where we made the mistake but we weren't using dart-sass we were using node-sass. Updating to use the "sass" npm package fixed the issue!
