### ISSUE TITLE
 Roadmap for deprecation and removal of @import [stub]

### ISSUE THREAD

**Issue by querkmachine** [sass/sass#3276]
Sorry for the stub but we seemingly can't agree on which repo this issue should be placed in: sass/sass-site#614

Thanks!

**Comment by jathak** [comment]
Because the module system is only available in Dart Sass, we want to wait until a substantial portion (roughly 70-80%) of our users are using it before we deprecate `@import`.

**Comment by querkmachine** [comment]
@jathak Thanks. Are metrics on usage available anywhere?

**Comment by jathak** [comment]
We generally look at the download stats on NPM as an approximation for the ecosystem as a whole, basically taking `sass / (sass + node-sass)` to see the percentage of users on Dart Sass (currently ~66%)

**Comment by joneff** [comment]
Looking at the npm stats, going one year back, installations of dart-sass has more than doubled; whereas installations of node-sass has shrunk about 20%. The ratio between node : dart sass shifted from "55:45" a year ago to "32:68" for the week before, with the last 2 percent being added in the previous 3 weeks.

In other words the trends are near the lower bound of the "70%-80%" and looking at the trends, we'll cross the lower threshold in about 3 or 4 more weeks (say end of May) and then it will not be long until we are at the upper boundary.

So, can we get a more concrete day?
