### ISSUE TITLE
Problem installing sass on windows with npm

### ISSUE THREAD

**Issue by rodrigoq** [sass/sass#3279]
Hello when i do:
`npm install sass --save-dev`

I get this error:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

Versions:
node: v14.19.1
npm: 8.6.0
Windows 10 (21H1)

If I do:
`npm install sass -g`
the installation works fine.

Also I think I already have `fsevents` installed:
`npm ls fsevents`
```
+-- babel-jest@27.0.6
| `-- @jest/transform@27.0.6
|   `-- jest-haste-map@27.0.6
|     `-- fsevents@2.3.2
`-- webpack@4.46.0
  `-- watchpack@1.7.5
    +-- chokidar@3.5.2
    | `-- fsevents@2.3.2 deduped
    `-- watchpack-chokidar2@2.0.1
      `-- chokidar@2.1.8
        `-- fsevents@1.2.13
```

Any Idea why is trying to install something for mac?

**Comment by nex3** [comment]
This isn't a fatal error, it's just a weird quirk of npm that if you specify an optional dependency for one specific OS (like the `chokidar` filesystem-watcher package does for `fsevents`), npm will raise a big fuss about it on other OSes. You should still be able to use Sass just fine despite that message.
