### ISSUE TITLE
Named arguments misbehavior

### ISSUE THREAD

**Issue by pointlessone** [sass/sass#328]
As I've noted in #327, one can only specify last args as named. I'd like to discuss problems with that and a possible solutions.

Example function

``` sass
@function f($a, $b, $c)
  @return $a, $b, $c
```
### Example 1

``` sass
a
  a: f(1, 2, 3, $b: 4)
```

This compiles to:

``` css
a {
  a: 1, 2, 3; }
```

I think, named arguments are more specific than unnamed. When I explicitly specify a name for value I want it to be that value. Also as we have here one spare unnamed argument it, probably, should raise an error on args number mismatch.
### Example 2

``` sass
b
  b: f($a: 1, 2, $c: 3)
```

Currently it raises an exception: Function f is missing parameter $b. Again, if named arguments would be treated as higher priority and unnamed distributed between all the other arguments we'd have it perfectly good.

In current implementation arguments are consequently assigned with unnamed arguments being higher priority that named. That means that named arguments will be taken into account only after poll of unnamed arguments have been used up. That makes it only possible to use named arguments for tail args and never for the first ones, or one have to name all arguments instead.
### Proposed algorithm
1. Check total number of passed arguments and raise an exception if there's more than function can take
2. Check if there's any unknown named arguments and raise an exception if there is 
3. Iterate over function definition parameters list
   1. Check if there's a named argument for current parameter and take its value if there's one
   2. Check if there's a value in unnamed arguments list
   3. Take first one and remove it from the list if there's one
   4. If there's no unnamed argument left, check if there's a default value for current parameter
   5. Take default value if there''s one
   6. Raise an exception if there's no default value

**Comment by nex3** [comment]
I think both of your examples should raise exceptions. I think it makes reading function calls much clearer to have all the positional arguments together at the beginning; otherwise, it's very hard to track which name a positional argument corresponds to.

I think the correct behavior is basically what exists now, with the addition of throwing an error if an argument is specified both positionally and as a named argument.

**Comment by pointlessone** [comment]
@nex3 Are you a Python guy? ;) Just kidding.

Anyway, what you describe is pretty much what Python has implemented.

``` python
def foo(a, b = 2, c = 2):
  print a, b, c

foo(b = 2, 1, 3)
# raises: SyntaxError: non-keyword arg after keyword arg

foo(2, c = 3, a = 1)
# raises: TypeError: foo() got multiple values for keyword argument 'a'
```

But at least, they have it codified. If you like that behavior we shell go with that but still, we have to raise a few more exceptions and be more explicit about how arguments can be passed in.

I'm raising this issue now because I'm about to work on #138 and it involves changes to arguments handling.

Still I'm in favor of of my proposition because it's more flexible. It may be harder to read but let's see where functions are used (called). It's either inside frameworks, or in user stylesheets. Either way those calls are maintained (mostly) by the same people who wrote them. If they've managed to write it and get result they wanted, they probably will be able to read it too. Also everyone can decide for himself if he wants to use it or not.

Either way this is non-breaking change. Sure, only for code that didn't abuse syntax quirk for no gain.

PS: you can ping me on IRC if you think that can be better place for discussion.

**Comment by nex3** [comment]
I haven't used Python's keyword arguments in any depth, but I'm not surprised to see that they use the same rules I'm proposing.

I'm extremely skeptical of allowing flexibility at the cost of difficulty of reading, especially when the flexibility doesn't buy any additional expressive power.

**Comment by pointlessone** [comment]
So, Python it is.
