### ISSUE TITLE
Is it possible to remove nested styles from an imported file?

### ISSUE THREAD

**Issue by FunctionDJ** [sass/sass#3280]
I'm using a CSS framework using SASS which generates a lot of variants like
```sass
.button
  // ...
  &.is-small
    // ...
  &.is-big
    // ...
```
I don't need these small and big variants. I know that other frameworks allow this to be configurable using variables / lists.. Is there any way for me to remove them without changing the source SASS files i'm importing?

**Comment by nex3** [comment]
No, it's not. Sass's philosophy is generally to avoid features that are targeted at using upstream dependencies in ways they weren't intended to be used.

**Comment by FunctionDJ** [comment]
@nex3 Got it, thanks for the response
