### ISSUE TITLE
Monorepo map files incorrect for relative node_modules --load-path

### ISSUE THREAD

**Issue by lee-chase** [sass/sass#3281]
We have a project which builds upon a separate projects SCSS. In our monorepo this results in SASS files being found both at the top-level node_modules and within the package. As a convenience to our users we roll up both package and node_modules SASS into one CSS file.

Currently given the following command
```
sass --style=compressed --load-path node_modules --load-path ../../node_modules scss/index.scss:css/index.min.css
```

a map file is generated with relative references to `../../node_modules/dep_package`. However, when our package is installed from npm the dependency tree is flattened meaning that `../../node_modules/dep_package` results in an attempted path look up of `../../node_modules/node_modules/dep_package` which does not exist. 

![image](https://user-images.githubusercontent.com/15086604/161759264-1e2b9fe0-fbe1-4323-8b8e-3ec3e058bbe2.png)

A mechanism to resolve this would be really handy.

**Comment by jathak** [comment]
This isn't something that's worth adding complexity to the CLI for. If you need to customize source maps, you can edit them yourself in a post-processing step.
