### ISSUE TITLE
support accessing module members dynamically

### ISSUE THREAD

**Issue by yinonov** [sass/sass#3282]
JS support [accessing an object's properties by using the dot notation or the bracket notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors).
bracket notation enables us to dynamically fetches property values.

is it possible for scss to support referencing module members dynamically?

the following code leans on hardcoded magic string of custom properties.
```scss
@mixin get-elevation($type) {
  background-color: var(#{--color-surface-#{$type}dp});
  filter: var(#{--shadow-surface-#{$type}dp});
}
```

I'd prefer avoiding  hardcoded variables and reference to scss variables that are mapped to tokens directly

```scss
@use 'my-tokens';

@mixin get-elevation($type) {
  $background-color: my-tokens[$color-surface-dp-#{$type}];
  $box-shadow: my-tokens[$shadow-surface-dp-#{$type}];

  background-color: var(#{$background-color});
  $box-shadow: var(#{ $box-shadow});
}
```

**Comment by jathak** [comment]
For use cases like this, we'd recommend using a map. Adding dynamic lookup for members would make static analysis more difficult (or impossible in many cases), so it's not something we plan to add to the language.

**Comment by yinonov** [comment]
ok so maps allow accessing props dynamically, that's a fair alternative :)
