### ISSUE TITLE
@support() is adding extra checks

### ISSUE THREAD

**Issue by ashleyww93** [sass/sass#3287]
I have the following code:

```
.AnimatedImageCard__container {
    @supports (not(backface-visibility: hidden)) {
      -moz-backface-visibility: hidden;
      -webkit-backface-visibility: hidden;
    }
 }
```

But after I build and serve my site, the minified css is output as:

```
@supports not ((-webkit-backface-visibility: hidden) or(backface-visibility: hidden)) {
    .AnimatedImageCard__container {
        -moz-backface-visibility: hidden;
        -webkit-backface-visibility:hidden
    }
}
```

On safari, `backface-visibility` is not supported, but `-webkit-backface-visibility` is, however, I need to ONLY add this css for safari as my card flip animation is broken without it (and if I include it for all browsers, its broken on chrome)

**Comment by stof** [comment]
Are you processing the output of Sass with autoprefixer ?
There is nothing in Sass that would automatically inject this prefix (I confirmed this by running your code snippet in Sass and it does not produce the `(-webkit-backface-visibility: hidden)` condition).

**Comment by nex3** [comment]
@stof is correct; Sass doesn't automatically add browser prefixes under any circumstances. This must be another tool in your toolchain.
