### ISSUE TITLE
Is there any way to compare $var and var()?

### ISSUE THREAD

**Issue by Meihina** [sass/sass#3288]
I code like this.

```
@function shadowSet($currentX, $x1, $y1, $x2, $y2, $cx, $cy) {
    $shadow : 0 0 0 0 #000;
    $pointsNum: 100;
    @for $i from 0 through $pointsNum {
        $t: ($i + 1) / $pointsNum;
        $point: twoBezier($t ,$x1, $y1, $x2, $y2, $cx, $cy);

        $color: rgb(255, 255, 255);
        @if (nth($point, 1) < var(--currentX)) {
            $color: rgb(255, 145, 0);
        }

        $shadow: $shadow, #{nth($point, 1)} #{nth($point, 2)} 0 0 #{$color};
    }
    @return $shadow;
}
```

but it throws error.

![1650012257285](https://user-images.githubusercontent.com/50244072/163548463-90d10132-f2cb-4077-927b-96b75d049344.png)

**Comment by stof** [comment]
`var(--currentX)` is an unquoted string as far as Sass is concerned. So it cannot be compared with a Sass number. CSS variables cannot be resolved in Sass, as they depend on resolving custom properties based on the DOM. They cannot be known at compile time when generating the CSS.
