### ISSUE TITLE
@use with !default and multiple variable files

### ISSUE THREAD

**Issue by kerryj89** [sass/sass#3291]
I am trying to convert my project to the Sass module system.  I am struggling to apply the idea to a multi variable import setup as clean/implicit as the non-modular example and thought who better to ask than the ones that wrote it (or anyone else that overcame this problem).

My non-modular project example:

```
// styles.scss

@import 'variables-project';   // $color-3: 'yellow'; ...and 20 more variables
@import 'variables-company';   // $color-2: 'pink' !default; $color-3: 'blue' !default; ...and 10 more variables
@import 'variables-global';    // $color-1: 'red' !default; $color-2: 'green' !default; $color-3: 'blue' !default; ...and 150 variables

.foo {
    color: $color-1;  // red
    background-color: $color-2; // pink
    border-color: $color-3; // yellow
}
```

My first instinct was to not define a namespace thinking that the variables will collide and resolve like the example above, but was met with `Error: This variable is available from multiple global modules.`:

```
@use 'variables-project' as *;
@use 'variables-company' as *;
@use 'variables-global' as *;
```

What is the cleanest way to override variables like in the first example, but using the module system?  I don't want to explicitly copy and paste the variables from each file and paste it into `with`'s map since `variables-company.scss` and `variables-global.scss` can be updated, added or deleted upstream.

Thanks for any suggestions.

**Comment by nex3** [comment]
If you're trying to override a variable in the new module system, you should always explicitly refer to the definition of that variable that you want to override. One of the problems with the old `@import` system is that if someone looked at `_variables-project.scss` in isolation, they'd have no way of knowing that the variables it defined were actually intended to override the variables in `_variables-company.scss`. In the module system, you can fix this by writing:

```scss
// _variables-global.scss
$color-1: red !default;
$color-2: green !default;
$color-3: blue !default;
```

```scss
// _variables-company.scss
@forward 'variables-global' with (
  $color-2: pink !default,
  $color-3: blue !default
);
```

```scss
// _variables-project.scss
@forward 'variables-company' with (
  $color-3: yellow !default
);
```

```scss
// styles.scss
@use 'variables-project';

.foo {
  color: variables-project.$color-1; // red
  background-color: variables-project.$color-2; // pink
  border-color: variables-project.$color-3; // yellow
}
```
