### ISSUE TITLE
with deprecating @import how to inject a portion of the css inside a bundle

### ISSUE THREAD

**Issue by mhamri** [sass/sass#3295]
for long time i was enjoying such syntax in the angular 

```
:host{
    @import "~/some-third-party-lib/dist/lib"
}
```
in this way I could localize usage of a css or even scss lib in the host. but now that you are going to deprecate the `@import` what other option are you providing to replace it? I can't use `@use` and `@forward` because it's expected that it's being used as the first item in the file. 

or I could create a mixin of animation lib like this 

```
@mixin someAnimation(){
    @import "somet-animation-lib/dist/animation-type/file.scss"
}
```

but all that good stuff is going to go away and I wonder what else I could use?

**Comment by nex3** [comment]
The ideal way to handle this use-case would be to update the library to provide its styles as a mixin rather than directly as CSS. If that's totally infeasible, you can mimic the behavior of nested imports using [`meta.load-css()`](https://sass-lang.com/documentation/modules/meta#load-css).
