### ISSUE TITLE
Reference variables from module before "with"

### ISSUE THREAD

**Issue by daniil4udo** [sass/sass#3297]
Hi SASSers 😄 

For few weeks trying to achieve relatively simple task, which seems impossible with `@use`

In brief is to use some module before customization it with `@use "..." with ()"

Here is an example.

Lets say we have a CSS framework. Main `framework.sass` forwards all needed files.

```
/// framework.sass

@forward "variables"
@forward "functions"
@forward "components"
```

Where `variables.sass` looks like this:
```
/// variables.sass

$invert-dark: #000 !default
$invert-light: #fff !default
```

We have `functions.sass` that uses some variables from `variables.sass`
```
/// functions.sass

@use "variables"

@function usefullFnOne()
    @return variables.$invert-dark


@function usefullFnTwo()
    @return SOME-USEFULL-VALUE
```

Now interesting part.

In `functions.sass` we have `usefullFnTwo` that we want to use before framework customization.

It is impossible to do smth like that:

```
/// main.sass in the project

@use "functions.sass"

$usefullVar: functions.usefullFnTwo()

@use "framework.sass" with ($invert-dark: $usefullVar)
```

Someone would say just to separate functions that use variables and dont, but I wonder if there is a workaround to achieve it in example shared above

**Comment by nex3** [comment]
`@use ... with` isn't a silver bullet, and it's not appropriate for all use-cases. You can always fall back on setting variables directly:

```scss
/// main.sass
@use "functions"
@use "framework"

$usefulVar: functions.usefulFnTwo()
framework.$invert-dark: $usefulVar
```

(If your framework emits styles directly, we recommend switching it to providing a mixin that users can invoke where and when they choose.)
