### ISSUE TITLE
Sass generates invalid sourceMaps when custom importer is used

### ISSUE THREAD

**Issue by p-karbownik** [sass/sass#3300]
Hi,

I think that I found a bug. The problem occurs when a custom importer is used and the function url() is located inside .scss files. In my project I use sass with resolve-url-loader, which requires proper sourceMap delivered by sass.

The issue occurs only when a custom importer is used and doesn't when the default one is used. Therefore I assume, that there could be a problem with the generation of sourceMap. This is an error, which is thrown by resolve-url-loader:

`Error: resolve-url-loader: error processing CSS
  expected "base" to be absolute path to a valid directory, got "data:;charset=utf-8,.custom%20%7B%0A%20%20%20%20color:%20var(--override);%0A%20%20%20%20content:%20url('.."
  at ./sass-customization-webpack/src/base/main.scss:3:3
    at ./sass-customization-webpack/node_modules/resolve-url-loader/index.js:287:12)
    at onFailure (./sass-customization-webpack/node_modules/resolve-url-loader/index.js:228:14)`

Here is .zip with repository which should allow to reproduce the issue:
[sass-customization-webpack-2.zip](https://github.com/sass/sass/files/8580844/sass-customization-webpack-2.zip)

**Comment by p-karbownik** [comment]
I've already founded a solution. In function `load(canonicalUrl)` of the importer I added returning of the property `sourceMapUrl`and that helped.

**Comment by JiangWeixian** [comment]
@p-karbownik hi, I meet same problem... when use sass-loader(with sass-embedded) and resolve-url-loader. I just want to know how to get correct `sourceMapUrl`

**Comment by nex3** [comment]
@JiangWeixian it's up to each `Importer` implementation to set up its source map URLs correctly. For `sass-loader`, make sure it's using the modern Sass compiler API—the legacy API has very limited support for source maps.
