### ISSUE TITLE
Custom functions sum example is incorrect

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#3304]
https://sass-lang.com/documentation/js-api/modules#CustomFunction

`arg1` doesn't exist and should be `arg[1]`

```js
const result = sass.compile('style.scss', {
  functions: {
    "sum($arg1, $arg2)": (args) => {
      const value1 = args[0].assertNumber('arg1').value;
      const value2 = args[1].assertNumber('arg2')
          .convertValueToMatch(arg1, 'arg2', 'arg1');
      return new sass.SassNumber(value1 + value2).coerceToMatch(arg1);
    }
  }
});
```
 
I'd make the PR myself but it seems the js-api page is gitignored.
It's also worth noting I've ran into a lot of issues trying to run the Custom Fucntion examples in the docs.

**Comment by nex3** [comment]
Feel free to open issues or send PRs for any other issues you run into—the JS API docs live in the `js-api-doc` directory of this repository, and you can see #3305 as an example of fixing them.
