### ISSUE TITLE
Variable name changed when use meta.module-variables

### ISSUE THREAD

**Issue by jackgreentemp** [sass/sass#3306]
> It's great that you're trying to achieve it @jasonteunissen but I got bad news for you. You **cannot** achieve it.
> 
> What you are doing here
> 
> ```css-scss
> #{'$'}#{$name}: --#{$name};
> ```
> 
> is called _Dynamically created variable_. That is not possible in Sass according to #1450. Therefore an automatically defined CSS variable in the code by @mirisuzanne
> 
> ```css-scss
> @each $name, $value in meta.module-variables("lightmode") {
>     --#{$name}: #{$value};
> }
> ```
> 
> can only be used dynamically with the ugly CSS variable syntax `var(--name)`.
> 
> The reality that Sass variable are not dynamic makes them much **less powerful** and I'm still keeping fingers crossed 🤞 to make them also a [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar#:~:text=In%20computer%20science%2C%20syntactic%20sugar,to%20read%20or%20to%20express.) for CSS variables.

I found something weird. Variable name is "$eed_color_base_black_1" in other scss file， the variable name would become "eed-color-base-black-1"  when using `@each $name, $value in meta.module-variables`. How to fix this?

demo link: https://codesandbox.io/s/bitter-water-iqfox5?file=/src/styles.scss

_Originally posted by @jackgreentemp in https://github.com/sass/sass/issues/3091#issuecomment-1118439675_

**Comment by jackgreentemp** [comment]
Could someone help me about this  issue?

**Comment by jathak** [comment]
This is working-as-intended. Underscores and hyphens are treated as identical in Sass identifiers, so `$eed_color_base_black_1` and `$eed-color-base-black-1` refer to the same variable.
