### ISSUE TITLE
[Feature Request] introduce a config file like ".sassrc" or something else

### ISSUE THREAD

**Issue by KunalTanwar11** [sass/sass#3307]
Sass could have a `config` file (which you save in the base dir) in which users can set options at once for compilation instead of using `javascript`.

### For Example
`.sassrc`
```js
module.exports = {
  sourceMaps: false,
  outputStyle: 'compressed' | 'expanded',
  // etc...
}
```

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/2669
