### ISSUE TITLE
How do I set the include path for meta.load-css()?

### ISSUE THREAD

**Issue by MassMessage** [sass/sass#3313]
I'm getting this error:

```
Electron Forge was terminated:
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'button-up.svg' in 'C:\Users\jckj\Desktop\merge\Newton\src'
```

from the code:

```
.myContainer {
    @include meta.load-css("7.css/dist/7");
}

```
this because it's searching for the resource files, such as button-up.svg in `src` dir but those files are in the `7.css/dist/7` folder itslf. How can I make `meta.load-css()` search in the 7 dir folder instead of?

**EDIT:** I've tried using postcss-import like this: 

```
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'postcss-import': require('postcss-import') ({
      path: ['7.css/dist']
    })
  },
}
```

but it didn't make any difference.

**EDIT 2:**

I just found out about https://sass-lang.com/documentation/at-rules/use#load-paths but not how to use this yet...

**Comment by greven** [comment]
Is this issue related to SASS at all? Think it has to do with whatever stack you are using because to use load paths you pass the flag in the sass cli as -I PATH, if you can't do this directly you will have to refer to the documentation of the framework you are using.

**Comment by MassMessage** [comment]
> Is this issue related to SASS at all? Think it has to due with whatever stack you are using because to use load paths you pass the flag in the sass cli as -I PATH, if you can't do this directly you will have to refer to the documentation of the framework you are using.

no it it's not really. I just found reading the docs more carefully that the imports are passed down to webpack's so settign the path in `resolve.modules` did solve.
