### ISSUE TITLE
Multiple @mixin with single @include.

### ISSUE THREAD

**Issue by ghost** [sass/sass#3318]
### This is a feature request that I feel should have in the SCSS to improve productivity.

**Current code**
```scss
.button{
   @include flex(column);      //display:flex & flex-direction:column
   @include box(40px, 80px);   //width:40px & height:80px
   @include border(2px, #fff); //border: 2px #fff solid
}
```
And I really hate needing to call `@include` every time I use mixins. So
<br/>

**Expected code**

```scss
.button{
     @include flex(column) box(40px,80px) border(2px, #fff);
}
```

Notes
- I can't create a single mixin with all the arguments because for some classes I don't wanna use `flex` and for others, I don't wanna use `border` at all. Even though I can pass name argument like `hey($width:4px)` needing to call `$width` makes me think why I should use mixins at all.

Advantages
- Help to main the code growing vertically. We can manage horizontal and vertical code sizes.
- Visual clearance
- No need to call same word `@include` multiple times, Hence improve productivity time.

**Comment by stof** [comment]
This has already been requested in the past, and the main issue is that this does not play well with content blocks

**Comment by jathak** [comment]
Duplicate of https://github.com/sass/sass/issues/3087
