### ISSUE TITLE
darken(color, amount) but desaturate(amount, color) have inconsistent argument order

### ISSUE THREAD

**Issue by felixniemeyer** [sass/sass#3319]
It would be nice if the argument order for all color functions was (color, amount)

**Comment by nex3** [comment]
Good news: they are!

![darken](https://user-images.githubusercontent.com/188/169910757-98806a12-867d-4848-9f6c-7150c8fe40fd.png)
![desaturate](https://user-images.githubusercontent.com/188/169910755-6b5daafe-b4b5-4a10-ad70-89db2eec7def.png)

That said, we recommend that users avoid these functions for reasons described [in the documentation](https://sass-lang.com/documentation/modules/color#desaturate), and use [`color.scale()`](https://sass-lang.com/documentation/modules/color#scale) or [`color.adjust()`](https://sass-lang.com/documentation/modules/color#adjust) instead.

**Comment by felixniemeyer** [comment]
I'm so sorry for this false alarm. I must have been tired or so on that day :/
Thanks for pointing towards `color.scale()` and `color.adjust()`
