### ISSUE TITLE
How to create global mixins and variables without any scoping restrictions

### ISSUE THREAD

**Issue by sonikasharma1403** [sass/sass#3323]
we are importing a few third-party libraries in our scss file. instead of `@import` if we use `@use`, compilation throws an error that it cannot find variables and mixins. Since we cannot change their code, I wondered if there's any way to make variables and mixins available to the third-party library without changing their code.

**Comment by nex3** [comment]
Your best option is to create a single intermediate file that `@import`s everything you need from the library, and then `@use` that file.

**Comment by kerryj89** [comment]
@nex3 That option will ultimately fail when `@import` gets dropped (Oct. 2022?), correct?

When migrating, I hoped for something like `@use 'old-3rd-party-component' provide 'variables'` which would behave as if `@use 'variables' as *` was at the top of the `@use'd` `old-3rd-party-component` file.  I'm guessing this form would go against modularity (the whole "what came from where" would be hidden at the file level and only revealed at the @use/@forward point) and would only shine when used with older libs and might have people overusing it elsewhere, but it would've been really handy to have for these situations.

**Comment by nex3** [comment]
> @nex3 That option will ultimately fail when @import gets dropped

That's correct, although the same is true for the entire third-party library.

> Oct. 2022

That date is no longer accurate. We haven't even deprecated `@import` yet, and we aren't planning to remove it until at least a year after its deprecation (and probably longer).
