### ISSUE TITLE
Module loop: this module is already being loaded.

### ISSUE THREAD

**Issue by sonikasharma1403** [sass/sass#3327]
Error messages should be more descriptive.

`Module loop: this module is already being loaded.`

If the module is already loaded then we should be able to use the variables. Is my understanding correct? 
But, if we remove `@use` then it throws, undefined variables and mixins error

**Comment by jathak** [comment]
This means that there's a loop of `@use` rules in your code.

For example, if you have files A, B, and C, where A uses B, B uses C, and C uses A, the `@use` rule in C would cause this error because we haven't finished loading A yet (since C is indirectly loaded as part of it).
