### ISSUE TITLE
Improve @each rule without need to use if else

### ISSUE THREAD

**Issue by NIK0LADZE** [sass/sass#3328]
Let's say i have declared mixins for mobile, tablet and desktop(maybe some other mixins for other media breakpoints, doesn't really matter) and i want to set similar styles for 3 mixins, this is how it would work currently:
```
@mixin media ($keys...) {
    @each $key in $keys {
        @if ($key == mobile) {
            @include mobile {
                @content
            }
        } @else if ($key == tablet) {
            @include tablet {
                @content
            }
        } @else if ($key == desktop) {
            @include ipad-landscape {
                @content
            }
        }
    }
}
```
I thought it would be better if the following code would actually work the same: 
```
@mixin media($keys...) {
   @each $key in $keys {
      @include $key {
         @content
      }
   }
}
```
also pro of this version is that you won't have to pre-describe which mixins would actually work in @mixin media with if else checks, just passing as an argument for media mixin would be enough, i.e following scss code:
```
@mixin mobile {
    @media (max-width: 767px) {
        @content
    }
}

@mixin tablet {
    @media (max-width: 1024px) {
        @content
    }
}

@mixin media($keys...) {
   @each $key in $keys {
      @include $key {
         @content
      }
   }
}


@include media(mobile, tablet) {
    color: red;
}
```
would compile to this: 
```
@media (max-width: 767px) {
  color: red;
}

@media (max-width: 1024px) {
  color: red;
}
```

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/626
