### ISSUE TITLE
request features 

### ISSUE THREAD

**Issue by abdo-spices** [sass/sass#3331]
Hi i want some new features like documentation (you can use docusarus)
new features like conditional import, autoprefixer , JIT complier , official Vscode extensions with full intellisense
and a variable will called compress takes a Boolean and at compile every class has the same property take it like extend at rule it's very useful for components
@apply directive like in tailwind

**Comment by nex3** [comment]
> documentation (you can use docusarus)

[We have documentation!](https://sass-lang.com/documentation)

> conditional import

See [`meta.load-css()`](https://sass-lang.com/documentation/modules/meta#load-css).

> autoprefixer

There's a dedicated [Autoprefixer](https://github.com/postcss/autoprefixer) that already exists. We have no desire to do a bunch of extra work only to duplicate its functionality.

> JIT complier

JIT-compiling Sass would be a tremendous amount of work for relatively thin performance gains.

> official Vscode extensions with full intellisense

This is a great thing for the community to provide.

> and a variable will called compress takes a Boolean and at compile every class has the same property take it like extend at rule

I recommend looking into [cssnano](https://cssnano.co/).
