### ISSUE TITLE
Are CSS color names reserved words? At least in maps?

### ISSUE THREAD

**Issue by U-4-E-A** [sass/sass#3333]
In my map: -

```
$colors: (
blue: #00adef
)
```

This is not found here: -

`background-color: map.get($colors, 'blue');`

Same goes if it is any obvious color name ("red", "green", "yellow", "lightgreen"). If I suffix it with something so it becomes random, such as "yellowy", it works.

So... are CSS color names reserved words in sass?

**Comment by nex3** [comment]
From [the documentation](https://sass-lang.com/documentation/values/maps):

> ### ⚠️ Heads up!
>
> Most of the time, it’s a good idea to use [quoted strings](https://sass-lang.com/documentation/values/strings#quoted) rather than [unquoted strings](https://sass-lang.com/documentation/values/strings#unquoted) for map keys. This is because some values, such as color names, may _look_ like unquoted strings but actually be other types. To avoid confusing problems down the line, just use quotes!

Color names in Sass always resolve to plain color values, which are not equal to color name strings. If you write your map as `("blue": #00adef)` it will work.
