### ISSUE TITLE
Strict unary operator impact on unary divide

### ISSUE THREAD

**Issue by stof** [sass/sass#3337]
The dart-sass implementation currently has 4 unary operators: `+`, `-`, `/` and `not`. `not` being an identifier already requires spaces around it to disambiguate it and is not a binary operator, so it is a special case. However, `+`, `-` and `/` are kind of similar.

Is `/` expected to be updated by the strict unary operator proposal ?

**Comment by nex3** [comment]
I think it's unlikely that many people intentionally use unary `/`, and the move to `/` as a separator means that something like `$a /$b` can actually be valid CSS where `$a -$b` can't, so I don't think it's a good idea to forbid `$a /$b`. Thanks for checking, though!
