### ISSUE TITLE
Support for directory processing in JS API

### ISSUE THREAD

**Issue by sonikasharma1403** [sass/sass#3339]
Hi, I am trying to use the sass JS API instead of command line. For scss to css compilation using command line, we can pass the directory and everything else is taken care of. But, while converting the command line usage to JS API using the `render` method, I found that there is no way to pass a directory to it. Let me know if there is any other function that has this support? if not, then can we have a support for this?

**Comment by nex3** [comment]
Since the CLI is intended for manually compiling Sass while the JS API is more intended for automation, I don't think it makes sense to add non-Sass-specific complexity to it that could easily be implemented using standard JS APIs.

**Comment by sonikasharma1403** [comment]
@nex3, 
so, if we want all the files in a directory to be compiled from SCSS to CSS, then we will have to pass one file at a time to the JS API? Is my understanding correct?

**Comment by nex3** [comment]
Yes, that's correct. That's how the CLI does it internally as well.

**Comment by sonikasharma1403** [comment]
@nex3 :  thank you for your help
