### ISSUE TITLE
hyphens and underscores are treated the same in variable names

### ISSUE THREAD

**Issue by philipwalton** [sass/sass#334]
If I go to http://sass-lang.com/try.html and enter the following code:

```
$font-size: 20px;
$font_size: 10px;

p {
  font-size: $font-size;
}
```

The result is:

```
p {
  font-size: 10px; }
```

It seems that the second variable (with the underscore) is overriding the first one (with the hyphen). I'd assume this isn't intentional, but if it is could you please provide the rationale.

Thanks!

**Comment by chriseppstein** [comment]
It is intentional. The rationale is that the separator is a stylistic preference, not a meaningful one.

**Comment by philipwalton** [comment]
@chriseppstein thanks for the quick reply. I understand your rationale, and I can't say I disagree with you. Having `$font-size` and `$font_size` in the same file isn't exactly a best practice.

However, in my case, I was converting someone else's code and using the hyphens as a way to separate my variables from his, and since I wasn't expecting them to cause naming collisions, it took me forever to finally figure out that this was the root of the issue.

Perhaps explicitly stating this somewhere [in the docs](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#variables_) would prevent this from happening to others.

**Comment by chriseppstein** [comment]
Seems reasonable :) Sorry for the lost time to debugging this.

**Comment by philipwalton** [comment]
Thanks. Don't worry, sass has saved me more time than it's lost me :)

**Comment by xzyfer** [comment]
We've recently run into this in Libsass (https://github.com/sass/libsass/issues/877). It appears this feature is still largely undocumented aside from this mention

> Since the named arguments are variable names, underscores and dashes can be used interchangeably.
> http://sass-lang.com/documentation/file.SASS_REFERENCE.html#keyword_arguments

As @philipwalton points out it would be great to have a definitive reference for what this behaviour is applied to as it's currently unclear /cc https://github.com/sass/libsass/issues/877#issuecomment-74405004

**Comment by traviswimer** [comment]
Does anyone else think it would make more sense to display a compile error instead, when two variables only differ on "_" vs "-"? It can be rather confusing if you don't happen to be aware of this obscure functionality.

**Comment by ArmorDarks** [comment]
Wow. That whole idea with `-` and `_` meaning same thing is kinda strange solution.

**Comment by esr360** [comment]
It seems odd that this behaviour is intentional. At least there should be a compile error, right? The current behaviour as it stands according to this thread surely can't be the goal?

**Comment by Asday** [comment]
The behaviour is odd, coming from programming languages, but I honestly can't say I disagree with the rationale.  Personally I'd enforce consistency within projects I oversee, but hey, VB is case insensitive, what can you do.

I don't think it should be a compile error to redefine a variable.  A quick search on google and the issues here show no results for "const" either, so I don't think many other people in the world think so either.
