### ISSUE TITLE
Calculation through calc() falsely simplified

### ISSUE THREAD

**Issue by totkeks** [sass/sass#3348]
I got the following calculation `calc(320px / 100vw)` as part of a bigger clamp function.
And this gets simplified by sass into `3.2px/vw` resulting in this error message:
```
Number 3.2px/vw isn't compatible with CSS calculations
```

I think the expected result should be `3.2px/1vw` or no simplification at all if that is possible too.

I'm running vitejs with `sass: 1.52.3`

I also found this issue https://github.com/sass/sass/issues/2565, but I don't fully understand, if the removal of `/` would solve the problem or is rather the cause of it or has nothing to do with it at all.

**Comment by nex3** [comment]
Neither `3.2px/1vw` nor `calc(3.2px / 1vw)` are valid CSS values. Sass generates an error rather than producing a CSS value that it knows is invalid so that you can tell what's going wrong rather than simply having your CSS render incorrectly for opaque reasons.

**Comment by Kered13** [comment]
These calculations are now supported in CSS [on most browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/calc#browser_compatibility). However Sass still does not allow them.

**Comment by nex3** [comment]
I've filed https://github.com/sass/sass/issues/4156 to track adding support for emitting numbers with complex units. As a workaround, complex numbers can currently be emitted [using meta.inspect()](https://sass-lang.com/playground/#eJwzNHQoLU5VUC9OLC62yk0tSVS35kpUqE6yUgBx9DLzigtSk0s0khNzkjUMDQwKKhT0FQzLyjU1awEn/BJ5).
