### ISSUE TITLE
Sass won't recognize @font-face tag?

### ISSUE THREAD

**Issue by blaasvaer** [sass/sass#3380]
Whenever I try to use @font-face in sass it doesn't get added to the compiled output ... the tag is simply ignored.

If I use . instead (just to test that this is not a path issue) it gets compiled just fine.

What am I missing here?

Wrapping in @at-root doesn't make any difference either.

**Comment by nex3** [comment]
We need more information in order to help you with your problem. Which Sass implementation are you using, and version of Sass? What's the Sass source that's not behaving how you expect, what output are you expecting, and what output or error are you getting instead? Please make sure your example is as tightly-focused on the problem as possible, so that it's easy for us to understand what's going on.

**Comment by blaasvaer** [comment]
`package.json`: "sass": "^1.35.1"

I'm expecting it to output this:

```
@font-face {
	font-family: 'DBScreenHeadLight';
	src: url('../fonts/dbscreen/dbscreen-head/dbscreen-head-light.woff2') format('woff2'),
	     url('../fonts/dbscreen/dbscreen-head/dbscreen-head-light.woff') format('woff');
	font-weight: 100;
	font-style: normal;
}
```

from this:

```
@font-face {
	font-family: 'DBScreenHeadLight';
	src: url('../fonts/dbscreen/dbscreen-head/dbscreen-head-light.woff2') format('woff2'),
	     url('../fonts/dbscreen/dbscreen-head/dbscreen-head-light.woff') format('woff');
	font-weight: 100;
	font-style: normal;
}
```
Yes, you're seeing double, 'cause I would expect it to output EXACTLY what I put in – that is, to describe the problem again: it simply won't add the @font-face to the 'compiled' version. But if I replace the @ with a . (period) it outputs just fine ... so, SOMEHOW Sass ignores this specific @ tag.

I've got another project based on the exact same setup (this one is actually an exact copy of it) that runs just fine ... that's why I've spent the better part of a day trying to figure out why Sass suddenly chooses to act weird.

**Comment by blaasvaer** [comment]
And just for the 'fun' of it, adding a backslash (to escape the @ – \\@font-face) WILL add it to the compilation ... so, in my opinion Sass has a bug that – for whatever reason – wont include @font-face when compiling.

Now, Sass itself uses al sorts of @-tags ... and I'm pretty sure, that somewhere here lies the bug. It somehow simply has issues handling @font-face tags in some cases ... trouble is to figure out WHICH cases.

**Comment by blaasvaer** [comment]
And it will ALSO ADD @fontface (when leaving out the dash) ... so, Sass DOES have issues with @font-face tags.

**Comment by blaasvaer** [comment]
When adding the escaping backslash it will ONLY import the first one (that is, with the slash of course). It won't include the rest ... so, at this point Sass simply suck!

**Comment by blaasvaer** [comment]
Looking for an alternative solution, thanks.

**Comment by blaasvaer** [comment]
After some more digging and implementing alternate solutions ... it turned out to be 'gulp-cssnano' being the bugger. Changed it for gulp-postcss and cssnano ... fixed the issue.

This ran after sass and obviously screwed things up ... just weird it is working on the other project. Same version, same everything ... well, there's development for you.
