### ISSUE TITLE
Feature-Request: function HEX to filter for svg

### ISSUE THREAD

**Issue by Daijobou** [sass/sass#3382]
To color a background-image svg-file, its not working with **fill**, **stroke** or **color**, but you can use **filter**:

> background-image: url(file.svg);
> filter: invert(17%) sepia(97%) saturate(6345%) hue-rotate(359deg) brightness(100%) contrast(116%);

I would like in sass a function that convert hex-code to filter.

Sass:

> $my_color: #FF0000;
> filter: hex_to_filter($my_color);

CSS:

> filter: invert(17%) sepia(97%) saturate(6345%) hue-rotate(359deg) brightness(100%) contrast(116%);

Source: https://codepen.io/sosuke/pen/Pjoqqp

Currently the only way I found is to embed svg in css, what makes the css-file big.
> background-image: url('data:image/svg+xml;utf8,<svg ... fill="**#{$my_color}**">...</svg>');

**Comment by nex3** [comment]
We try to keep the core libraries narrowly focused on things that most Sass users need, but this sounds like a great thing to write as a custom function in a Sass library!

**Comment by pddec** [comment]
Does anyone know any Sass library that can generate CSS filters?
