### ISSUE TITLE
Refactor semi-colons away

### ISSUE THREAD

**Issue by kwolk** [sass/sass#3383]
Newer languages like Swift have done away with semi-colons at the end of a line, isn't it time to refactor that away ?

**Comment by nex3** [comment]
If you'd like to write CSS without semicolons, Sass supports a [whitespace-sensitive indented syntax](https://sass-lang.com/documentation/syntax#the-indented-syntax) that doesn't use them. For the SCSS syntax, we're strictly beholden to compatibility with CSS.

**Comment by kwolk** [comment]
Thanks for the info, I just came across this.

My understanding is that it spits out the CSS at the other end, so I would expect it to be added then.

It was just for the SASS environment.
