### ISSUE TITLE
Clarification about math variables

### ISSUE THREAD

**Issue by stof** [sass/sass#3386]
Regarding https://github.com/sass/sass/blob/main/proposal/floating-point.md#variables, should the compiler provide `$pi` and `$e` as `3.141592653589793` and `2.718281828459045` or should it provide the higher-precision value available in the implementation language, to avoid rounding errors in computation ?
For instance, in JS, `Math.PI` provides a higher precision. The same is true in PHP with the builtin `M_PI`.

**Comment by nex3** [comment]
The examples there are in blockquotes, indicating that they're not normative—the specified requirement is "the closest possible double value approximation". However, I think those are the closest approximations—running `Math.PI == 3.141592653589793` in JS returns `true`, for example.
