### ISSUE TITLE
Placeholders and interpolation

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#339]
Is there currently a way to combine the two following situations :

```
#{$icon-font-base-class}
%.placeholder-class
```

I tried `%#{$icon-font-base-class}` but it throws an error ?

**Comment by nex3** [comment]
`%#{$icon-font-base-class}` should work. This is a bug.

**Comment by chriseppstein** [comment]
What is `%.placeholder-class` The dot (indicating a class?) seems like the syntax error here.

**Comment by chriseppstein** [comment]
please show the source code and error you are getting.

**Comment by nex3** [comment]
I assumed the dot was a typo.

**Comment by Anahkiasen** [comment]
I didn't know %. was supposed to be %, didn't find the placeholders in the sass doc. I was trying to update a bit of compass-recipe that was still using @silent. I see the problem now, I'll check, should work now.

**Comment by Anahkiasen** [comment]
Yup, it was a dot at the beginning of the variable. Removing it fixed it. Closing.

**Comment by MoOx** [comment]
Mey compass-recipes still use `@silent` ? Who is maintaining this shitty library ? :)
