### ISSUE TITLE
How to override a SASS/SCSS function with new module structure?

### ISSUE THREAD

**Issue by ravianand1988** [sass/sass#3399]
I have added a question on [StackOverflow](https://stackoverflow.com/questions/73855793/how-to-override-a-sass-scss-function-with-new-module-structure). However, I am a little desperate for the answers/responses. Therefore raising it here too. :pray:

**Comment by nex3** [comment]
One of Sass's broad design pillars is that it's not a priority for us to allow libraries to be used in a way their authors didn't expect or intend. This includes forcibly overriding functions—how those functions get called within a library is an implementation detail, and not something users should be relying on in the first place.

If a library *wants* to expose customizability though user-defined functions, it's still possible by passing in [first-class functions](https://sass-lang.com/documentation/values/functions) to APIs that are designed to expect them. But that requires the library to explicitly design support for this sort of customization.
