### ISSUE TITLE
FSSM patched to work on Rubinius

### ISSUE THREAD

**Issue by Twisol** [sass/sass#34]
The version of 'fssm' included with Sass doesn't on Rubinius because it causes a StackError. Version 0.2.2 of fssm, which was just released, does work. However, Sass has fssm vendored at a specific commit, rather than including the gem in the gemspec, so I still can't use Sass easily. Can you update your vendored version of fssm, or include it in the gemspec instead?

**Comment by chriseppstein** [comment]
This is a dupe of #31. Sass is supposed to allow you to use your own version of FSSM if it can find it and only fall back to the vendored version if it's missing.

**Comment by Twisol** [comment]
Unfortunately that doesn't seem to be the case. I can confirm that I have the latest FSSM gem (0.2.2) installed, as well as the latest Haml gem (3.0.24). When I run 'sass --watch' it fails with a StackError, and the trace reveals that it's still using the vendored copy of fssm.

Even if it were working, it's nice to know that I have to manually install a dependency to use Sass fully... Can you comment, by any chance, on the reason why fssm is vendored instead of listed in the gemspec?

**Comment by chriseppstein** [comment]
Issue #31 is still open. When it is fixed, it will work.

**Comment by Twisol** [comment]
Ah, I'm sorry. I see. It was merged but a new gem hasn't been released yet. Thank you.

**Comment by nex3** [comment]
I wouldn't say this is a duplicate of #31... we ought to update the default FSSM version regardless of how overridable it is.

However, we can't update until ttilley/fssm#16 is fixed. So for now I'll just re-open this.

**Comment by electrum** [comment]
Can you update now that ttilley/fssm#16 is fixed?
