### ISSUE TITLE
[feature] Variables that change inside media queries affect all instances they're used

### ISSUE THREAD

**Issue by ricardogo** [sass/sass#340]
Example: I have a page where the grid size changes depending on the screen size. Almost all elements are dependent on the grid size, which are specified as variables (and one function that calculates the width of an element, depending on the columns it occupies).

It would be interesting if those variables change inside a media query, all the places they were referenced would be updated with the new value. This way, things just work in different resolutions without having to rewrite a big part of the styles.

Mind that I've only been using this for a couple of days and that this "featured" could actually harm others.

**Comment by nex3** [comment]
Can you give an example of the Sass you're envisioning and the CSS it would output?

**Comment by Anahkiasen** [comment]
I think what he meant is this :

```
$width: 200px
$padding: ($width / 10)

body
    width: $width
    padding: $padding

@media (min-width: 480px)
    $width: 100px
```

And when you'd resize under 480px, both the width and padding properties of body would recompute.
Although I was thinking the same thing just yesterday and how much I needed it, I don't exactly see how that would work. The only way maybe would be making SASS check what variables change in each @media ruleset, and automatically append the concerned properties with their modified values.

So the output would be something like this :

```
body
{
    width: 200px;
    padding: 20px;
}

@media (min-width: 480px)
{
    body
    {
        width: 100px;
        padding: 10px;
    }
}
```

Now that would be a hugh step forward, but maybe too big of a change.

**Comment by ricardogo** [comment]
a possible input would be:

``` css

$width: 200px;

body {
  width: $width;
}

@media(min-width: 480px) {
  $width: 100px;
}
```

and the output would be:

``` css
body {
  width: 200px;
}

@media(min-width: 480px) {
  body {
    width: 100px;
  }
}
```

right now, I have to re-write exactly the same css inside the media query, for the values to update. in the way I'm proposing, all the css that had references to that variable would be automatically generated to reflect the new values.

basically, what @Anahkiasen said.

**Comment by chriseppstein** [comment]
This would be a nice feature when browsers support variables natively, but this is far too magical for a compiler. I suggest you use mixins to create a DRY abstraction and use it to replicate the necessary styles in each media query.

**Comment by tdshap** [comment]
So reassigning sass variables in media queries is still not supported?

**Comment by scazzy** [comment]
Still want this feature in 2017!

**Comment by Bram-Zijp** [comment]
Hi,

A possible solution to the described problem would be the following:


```

@mixin height {
    height: 460px;
    @media (max-width: 900px) {
        height: 400px;
    }
}

.one {
    @include height;
}

.two {
    @include height;
}


```

**Comment by sgruetter** [comment]
An other workaround would be something like this:

// Styling
```
.spacing--horizontal {
  margin-left: 16px;
  margin-right: 16px;
}

@media (max-width: 550px) {
  .spacing--horizontal {
    margin-left: 12px;
    margin-right: 12px;
  }
}
```

// HTML
`<header class="spacing--horizontal">Hello World</header>`
