### ISSUE TITLE
Color spaces proposal is inconsistent about quotes on color name inputs

### ISSUE THREAD

**Issue by nex3** [sass/sass#3400]
As written, the color spaces proposal (https://github.com/sass/sass/issues/2831) has some inconsistencies about whether it allows quotes in space names passed in by the user. For example, `color.to-space()` first checks if `color.space($color) == $space`, which is a quote-insensitive comparison, but [Looking Up a Known Color Space](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#looking-up-a-known-color-space) explicitly throws an error if the string isn't unquoted.

One way or another, this should be consistent. I can see arguments for going in either direction, though:

* Other Sass APIs that take specific named flags, like the `$separator` argument to various list functions, are quote-insensitive.
* The `color()` function defined by the CSS spec does not allow quoted color space names and we probably don't want to make it do so.

Either way, we have to be inconsistent with one thing or another. What do you think, @mirisuzanne?

**Comment by mirisuzanne** [comment]
I think we should start by requiring unquoted strings, to match CSS. Since quotes will throw an error, we can revisit if there seems to be a good reason later.

**Comment by nex3** [comment]
That sounds good to me.
