### ISSUE TITLE
Unknown color spaces should always be compared case-insensitively

### ISSUE THREAD

**Issue by nex3** [sass/sass#3401]
In the color spaces proposal (https://github.com/sass/sass/issues/2831), the definition of `color.to-space()` currently compares the input space with `color.space($color)` using `==`. This isn't a case-insensitive comparison, which means that `color.to-space(color(unknown 1 2 3), UNKNOWN)` will fail. [CSS serialization](https://www.w3.org/TR/css-color-4/#serializing-color-function-values) indicates that unknown space names are case-insensitive, so this comparison should be as well (as should any elsewhere in the proposal).

**Comment by mirisuzanne** [comment]
After looking into it more, I don't think this is true. As far as I can tell, [CSS Color 4](https://drafts.csswg.org/css-color-4/#color-function) only allows known color spaces (which are case-insensitive), but unknown color spaces are entirely _invalid_.

[CSS Color 5](https://drafts.csswg.org/css-color-5/#color-function) adds support for custom spaces, but only as [dashed idents](https://drafts.csswg.org/css-values-4/#typedef-dashed-ident), which require the `--` prefix, and are case-sensitive.

I think the solution we actually need here might be:

- known color space compare as case-insensitive (or are normalized to lower-case before comparison)
- dashed-ident color spaces retain their case, and are case sensitive in comparisons
- unknown, un-dashed color spaces are treated like special strings - we don't want to throw an error (in case new spaces get added to CSS), but we also can't parse them as valid colors.

**Comment by nex3** [comment]
Sounds good. We might also want to add a Design Decisions note explaining that we're intentionally allowing unknown, non-dashed color spaces for forwards-compatibility.

**Comment by mirisuzanne** [comment]
We removed support for unknown color spaces in draft 1.2
