### ISSUE TITLE
Color Spaces: forbid some known spaces from color() syntax

### ISSUE THREAD

**Issue by nex3** [sass/sass#3405]
Currently, the spec allows the `color()` syntax to be used for _any_ known color space. However, the CSS spec only defines support for spaces that don't have their own syntax; for example, `color(rgb 50 100 150)` is invalid CSS, as is `color(lab 0.5 0.5 0.5)`. In the interest of not muddying the waters or getting ourselves into a forwards-incompatible position, we should probably throw an error if the user tries to construct a color this way.

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2 #3426
