### ISSUE TITLE
Merge equal selectors on output

### ISSUE THREAD

**Issue by ieris19** [sass/sass#3407]
So, I am fully aware that in the past, features to optimize compiled Sass have been rejected in favor of more specialized tools as mentioned in issue #2464, however, as a new user of Sass I am baffled that the feature I am about to propose is not yet implemented.

I believe Sass should merge identical selectors. This means that the compiler should behave as follows:

`input.scss`
```
span {
  color: red;
}
span {
  color: blue
}
```

`output.css`
```
span {
  color: red;
  color: blue;
}
```

This means that Sass should merge all selectors that are equal, but perform no further optimizations. This would make the resulting css incredibly more readable and help developers spot issues like two different partials overwriting each other. 

I also think this is not beyond the scope of a preprocessor, or to be honest, any tool that puts multiple files together in any way. 

And the order would be determined just by order of importing/writing, just like it is now, so output would only become cleaner and no functionality would change.

**Comment by nex3** [comment]
Please don't open a new issue that you know is requesting the same thing as an issue that's already been closed.

**Comment by ieris19** [comment]
> Please don't open a new issue that you know is requesting the same thing as an issue that's already been closed.

The reason I opened a new issue is because I'm asking for something slightly different.

I might have not explained myself properly.

Current SASS compiler behavior concatenates one import after another. 
While in the past, it has been suggested to optimize the output css (the mentioned issue suggested SASS decide based on priority and specificity which selector would take effect and thus, only compile that one. This I agree is on the scope of an optimizing tool and not a preprocessor)

However, I do believe that SASS should, for lack of a better work, "concatenate" equal selectors. This means, when two selectors are the same, take the above span example, and reside in different files, the output will create a single span section, and fill it with ALL properties from all files in order of import.

The current behavior would print: 

```
<CSS from file one>
span {
  color: red;
}
<Rest of File one>

<CSS from file two>
span {
  color: blue
}
<Rest of File one>
```

And what I am suggesting is not what was previously suggested, but simply merge the selectors so that the output becomes:

```
<Unique CSS selectors from file one>
span {
  color: red;
  color: blue;
}
<Rest of unique CSS selectors from file one>

<Rest of selectors unique to file 2>
```

**Comment by nex3** [comment]
The answer is still the same: this is a job for a dedicated CSS optimizer like `cssnano`, and is out of scope for Sass.
