### ISSUE TITLE
Color Spaces: Be explicit about how to handle out-of-gamut HSL/HWB colors

### ISSUE THREAD

**Issue by nex3** [sass/sass#3409]
The color spaces proposal (#2831) currently contains no logic to ensure that out-of-gamut HSL and HWB colors aren't produced. The summary says that these color spaces aren't able to represent out-of-gamut colors, but neither the [Validating a Color Channel](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#validating-a-color-channel) nor the [Converting a Color](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#converting-a-color) procedure defines what to do when they end up with values that are out-of-bounds.

For Validating a Color Channel, I think the behavior is clear: for backwards-compatibility, we should match Sass's current behavior and clamp the saturation, lightness, whiteness, and blackness channels between 0 and 100. For Converting a Color, though, I'm not sure if the behavior should be to avoid errors by clamping or gamut-mapping out-of-gamut colors, or to just accept that `color.to-space(..., hsl)` is an inherently risky operation and throw an error if it doesn't work. I'm leaning towards the latter, partly because it's the easiest to change if we decide it's not optimal in the future, but I'd like your thoughts @mirisuzanne.

**Comment by nex3** [comment]
We'll have to be careful if we do decide to make this an error. For example, `color.same(color(display-p31 0 0), hsl(0deg 100%, 50%)))` should return `false` rather than simply failing.

**Comment by nex3** [comment]
Another wrinkle to consider here: the definition for `color.adjust()` uses the "Validating a Color Channel" procedure, but it _should_ allow negative values for lightness *et al*.

**Comment by mirisuzanne** [comment]
Both the `hsl()` and `hwb()` functions handle clamping/scaling of these channels. I think it might make sense to move that into _normalization_ (but not _validation_, since out-of-gamut-values are valid, but then get clamped).

> For Converting a Color, though, I'm not sure if the behavior should be to avoid errors by clamping or gamut-mapping out-of-gamut colors, or to just accept that color.to-space(..., hsl) is an inherently risky operation and throw an error if it doesn't work. 

The [colors-4 conversion algorithm](https://www.w3.org/TR/css-color-4/#color-conversion) does have a step for gamut-mapping hsl/hwb colors in step 8. We don't currently link to that algorithm - I wonder if it's new? I can add a link from our color-conversion, or port it in if that's better. I think it would be best to follow the CSS spec, rather than throwing an error.

> Another wrinkle to consider here: the definition for `color.adjust()` uses the "Validating a Color Channel" procedure, but it _should_ allow negative values for lightness _et al_.

I think this already addressed by our other changes to `color.adjust()` in #3426

**Comment by nex3** [comment]
> Both the `hsl()` and `hwb()` functions handle clamping/scaling of these channels. I think it might make sense to move that into _normalization_ (but not _validation_, since out-of-gamut-values are valid, but then get clamped).

Sounds good to me.

> > For Converting a Color, though, I'm not sure if the behavior should be to avoid errors by clamping or gamut-mapping out-of-gamut colors, or to just accept that color.to-space(..., hsl) is an inherently risky operation and throw an error if it doesn't work.
> 
> The [colors-4 conversion algorithm](https://www.w3.org/TR/css-color-4/#color-conversion) does have a step for gamut-mapping hsl/hwb colors in step 8. We don't currently link to that algorithm - I wonder if it's new? I can add a link from our color-conversion, or port it in if that's better. I think it would be best to follow the CSS spec, rather than throwing an error.

I think just linking to this is fine.

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2 #3426
