### ISSUE TITLE
Color Spaces: Channel indexes should respect reverse-indexing

### ISSUE THREAD

**Issue by nex3** [sass/sass#3410]
Since the color spaces proposal (https://github.com/sass/sass/issues/2831) uses 1-based channel indexes for new color space functions, it should probably follow the other Sass indexing convention: that negative numbers index from the back of the list. You probably don't need to explicitly describe this; just say they're "Sass-style indexes" and we'll act like that's a well-defined term elsewhere in the spec. (Or you can define it yourself explicitly if you'd prefer.)

**Comment by mirisuzanne** [comment]
We removed channel indexing along with custom color spaces in draft 1.2
