### ISSUE TITLE
Color Spaces: Should color interpolation method require "in"?

### ISSUE THREAD

**Issue by nex3** [sass/sass#3411]
The color spaces proposal (https://github.com/sass/sass/issues/2831) currently defines the syntax for a [Color Interpolation Method](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#color-interpolation-method) to always begin with "in ". This makes sense in the CSS mix syntax, where you need a separator to indicate the separation between the colors themselves and the interpolation method, but Sass's function syntax is already explicit about which parameter is where.

More concretely, I think `color.mix($color1, $color2, $method: oklch shorter hue)` may read a bit better than `color.mix($color1, $color2, $method: in oklch shorter hue)`. We would still use the `in` when we eventually add support for the CSS syntax, of course.

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
