### ISSUE TITLE
Color Spaces: hue interpolation should respect weight

### ISSUE THREAD

**Issue by nex3** [sass/sass#3413]
The method that the color spaces proposal (https://github.com/sass/sass/issues/2831) currently specifies for [hue interpolation](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#hue-interpolation) doesn't take a "weight" parameter and doesn't explicitly indicate how to linearly interpolate between the two angles supplied by the various hue interpolation algorithms.

**Comment by mirisuzanne** [comment]
I'm not sure I see this issue. The linked procedure for hue interpolation accepts two hue values, and adjusts them according to the methods defined in CSS - where they are represented as `θ₁` and `θ₂` (this could be clearer, maybe?). Those two values are returned, and assigned to `channel1` and `channel2` respectively. The very next step defines how those channels are interpolated, with weight. It's the same as all other channels:

> Set `channel` to the result of calculating `(channel1 * weight) + (channel2 * (1 - weight))`.

I don't think we need any special-casing here?

**Comment by nex3** [comment]
Oh, I see, you're right.
