### ISSUE TITLE
`color.mix()` shouldn't clamp weight

### ISSUE THREAD

**Issue by nex3** [sass/sass#3414]
The color spaces proposal (https://github.com/sass/sass/issues/2831) currently specifies that the `$weight` parameter for `color.mix()`, in both legacy and new mode, is clamped between 0 and 1 after being percent-converted. This actually makes the logic more lax than the current implementation, which throws an error if `$weight` is outside the 0-100 range. Given that the CSS draft spec for `color-mix()` _also_ [forbids out-of-bound percentages](https://drafts.csswg.org/css-color/#color-mix-percent-norm), I think we should make this strict again and throw an error if the weight is outside this range (using fuzzy matching).

**Comment by mirisuzanne** [comment]
Addressed in 2a8b9ce

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2

**Comment by vadimkantorov** [comment]
As an outsider to SASS, am I correct to assume that `mix(...)` produces the same outputs as `color-mix(...)`? Thanks!

**Comment by nex3** [comment]
@vadimkantorov It depends. The released version of `color.mix($color1, $color2, $weight)` is equivalent to `color-mix(in rgb, $color1 $weight, $color2)`, with the caveat that Sass currently has no notion of "missing channels" as defined by CSS Color 4 so this assumes that the colors have no missing channels. `color-mix()` has many interpolation methods that are different (and better) than `in rgb`, though, which `color.mix()` doesn't support.

The forthcoming Sass support for CSS Color 4, which this issue is part of, will expand `color.mix()` to have an additional `$method` parameter that matches the first argument to `color-mix()`. If a method is passed (as in `color.mix($color1, $color2, $method: in lch)`), then it _will_ behave exactly like `color-mix()`. But this hasn't yet been released.
