### ISSUE TITLE
Color Spaces: color.invert() handles $weight in reverse

### ISSUE THREAD

**Issue by nex3** [sass/sass#3415]
The color spaces proposal (https://github.com/sass/sass/issues/2831) defines [`color.invert()`](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#colorinvert) with a definition that ends with a call to `color.mix(invert, color, $weight, mix-space)`. But since `$weight` defaults to `100%`, this means that by default it will return _the original color_ rather than the inverted color. I think it should instead say `color.mix(invert, color, 100% - $weight, mix-space)`.

Also worth noting that the signature doesn't include `$weight`.

**Comment by nex3** [comment]
Another issue with the same function: currently, it's invalid to run `color.invert($color, $space: display-p3)` even though this has a well-defined output, because `display-p3` isn't a supported interpolation space. I think the definition should have explicit early-exit clauses if `$weight == 0%` or `$weight == 100%` so that you can pass in those color spaces when mixing isn't necessary.

**Comment by mirisuzanne** [comment]
According to [the current documentation for `color.mix`](https://sass-lang.com/documentation/modules/color#mix)

> A larger weight indicates that more of `$color1` should be used, and a smaller weight indicates that more of `$color2` should be used.

Since `invert` is `$color1` in this case, a default weight of `100%` returns the inverted color. 

Fixing the other issues here, but I don't think the weight is actually reversed.

**Comment by mirisuzanne** [comment]
(I do think our handling of weight is confusing, and not what I expect)

**Comment by nex3** [comment]
> Fixing the other issues here, but I don't think the weight is actually reversed.

Ah, you're right, my mistake.

**Comment by mirisuzanne** [comment]
> because `display-p3` isn't a supported interpolation space.

There are a few ways we could address this:

- Make the limitation explicit (probably overkill)
- Use either `srgb` or `linear-srgb` as the 'closest' option (still rgb)
- Use `oklab`, which is defined by CSS as the 'best default' option when none is specified
- Skip the call to `mix`, and just do a weighted averaging of input/output channels?

**Comment by nex3** [comment]
Another option would be to simply expand on the CSS spec and support `mix()` with all known color spaces, but I'm reticent to do that when I don't have a clear understanding of why CSS only supports a subset of them in the first place.

I think for now, my preference is to say that if you pass an unmixable color space like `display-p3`, `$weight` must be 100% or 0% and so we never call `mix()`.

**Comment by mirisuzanne** [comment]
Making this change with reference to the interpolation method construct, which may also need to be updated based on the resolution of https://github.com/w3c/csswg-drafts/issues/7907 in CSS.

**Comment by mirisuzanne** [comment]
e796596

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
