### ISSUE TITLE
Color Spaces: Support legacy behavior for color.change/adjust/scale

### ISSUE THREAD

**Issue by nex3** [sass/sass#3417]
Like all color functions, `color.change()`, `.adjust()`, and `.scale()` historically treated RGB, HSL, and HWB colors as interchangeable. As currently specified in the color spaces proposal (https://github.com/sass/sass/issues/2831), though, any color channels that aren't in a color's space throw errors. To preserve backwards-compatibility, this should allow the any RGB, HSL, and HWB channels to be modified for any legacy colors (at least when `$space` isn't set).

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
