### ISSUE TITLE
Color Spaces: Should a and b be scalable?

### ISSUE THREAD

**Issue by nex3** [sass/sass#3418]
The color spaces proposal (https://github.com/sass/sass/issues/2831) currently explicitly marks the a and b channels of the lab and oklab color spaces as not scalable, since their minimum values are negative mirrors of their positive values instead of being zero. However, we _could_ meaningfully define scaling here as a linear scale between min and max instead of between zero and max.

In mathematical terms, we'd say `scale(original, factor) = original + (max - original) * factor` if `factor > 0` and `scale(original, factor) = original + (original - min) * factor` if `factor < 0`. This preserves the behavior that scaling a number by positive X% brings it X% closer to the maximum and scaling it by negative X% brings it X% closer to the minimum.

**Comment by mirisuzanne** [comment]
What I found strange with these is that they map `%` from `-100%` to `100%` - so it's not clear to me if an adjustment of `100%` should move it the entire distance, or half the distance between the min and max. Is it confusing if a change of `100%` moves the value `200%`?

**Comment by nex3** [comment]
The `%` in `color.scale()` refers to a different thing than the `%` in a color's channel. The former refers to the distance between the current value and the minimum/maximum, while the latter refers to the distance between 0 and the minimum/maximum. So I think it's fine to say that 100% (scale factor) can increase the channel by 200% (channel value).

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
