### ISSUE TITLE
Use compileString issues

### ISSUE THREAD

**Issue by GDGHD-123** [sass/sass#3422]
I want to try
![image](https://user-images.githubusercontent.com/53597925/195068180-53cdbcc5-6521-4e56-bd83-be1b9f7b8b5d.png)
but
![image](https://user-images.githubusercontent.com/53597925/195068075-85efcc3d-789e-4b72-a77f-71a7d907f52c.png)

Try it in a vue 3.0 project

**Comment by nex3** [comment]
Sass doesn't currently support running in a browser. See https://github.com/sass/dart-sass/issues/25.
