### ISSUE TITLE
Color Spaces: color.adjust() should handle out-of-range values for HSL/HWB channels

### ISSUE THREAD

**Issue by nex3** [sass/sass#3424]
The color spaces proposal (https://github.com/sass/sass/issues/2831) currently doesn't check the range of any arguments for the `color.adjust()` function. Normally, this is fine—most color spaces fully preserve even out-of-gamut values. However, HSL and HWB _don't_ do so, so we should handle that somehow.

Currently, `color.adjust()` forbids arguments outside of `[-100%, 100%]` for these arguments, but if the resulting channel value would be out-of-range it's simply clamped to `100%` or `0%`. We could preserve this behavior, or we could match other color functions in allowing _any_ argument while using the clamping behavior to preserve the guarantee that HSL and HWB never represent out-of-gamut colors.

**Comment by nex3** [comment]
Just to make sure I'm understanding correctly, this is now handled in two ways, right?

1. Normalizing Color Channels now explicitly _clamps_ channels for HSL and HWB. This means that `hsl()`, `hwb()`, `color.change()`, and `color.adjust()` clamp out-of-bounds channels.

2. Converting colors into `hsl()` and `hwb()` now automatically gamut-maps the RGB equivalent before doing the final conversion.

**Comment by mirisuzanne** [comment]
That's right, yes.

**Comment by mirisuzanne** [comment]
(I can make that more clear in the changelog)

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
