### ISSUE TITLE
How to dynamically replace variable value for generic stylesheet?

### ISSUE THREAD

**Issue by miedrl** [sass/sass#3429]
I've got three files defining the same SCSS variables but with different values for light, dim and dark mode.

```
_vars_light.scss

$bgColor: white;
$textColor: black;
```

```
_vars_dim.scss

$bgColor: darkblue;
$textColor: white;
```

```
_vars_dark.scss

$bgColor: black;
$textColor: white;
```

In addition, I've got a file with styles that should work for all modes.
_styles.scss

```
body {
   background-color: $bgColor;
   color: $textColor;
}
```

I used to @import _styles.scss into the three variable files and it worked fine. As @imported is marked as deprecated I want to use @use instead but i can't just replace @import _styles,scss with @use _styles.scss as the variables would not be known within _styles.scss.

**Question**: How can I keep my file structure without using @import at all and without using @use within _styles.scss? Or what is the best practice for this problem?

**Comment by jathak** [comment]
This sort of dynamic configuration is explicitly discouraged by the design of the module system. While it may be possible to migrate your previous setup to use a `with` clause (see [here](https://sass-lang.com/documentation/at-rules/use#configuration)), the better solution would be to have a mixin that takes in your configuration and emits the relevant CSS.

Also, `@import` has not been deprecated _yet_ (though it will be in the future).
