### ISSUE TITLE
Stop converting hex colors to names (i.e. #FFFFFF to white)

### ISSUE THREAD

**Issue by joevandyk** [sass/sass#343]
We generate stylesheets with sass that are used with html emails. 

Unfortunately, sass converts #FFFFFF to "white".  This will screw up html email formatting.  http://litmus.com/blog/background-colors-html-email has more details. 

There doesn't seem to be a way to disable this.  To fix our html emails, I had to fork sass and make the following change: https://github.com/joevandyk/sass/commit/e48a18e247819b70f4524a56629c3ca5397b0733

Thoughts on this?

**Comment by nex3** [comment]
I'm willing to make some compromises for browser compatibility, but in general Sass compiles towards the CSS spec. Failing to parse color names (or apparently even three-character hex colors, according to that blog post) is a huge violation of the spec; if something that simple isn't supported, I'd be extremely surprised if the rest of the CSS features that Sass depends on are. It doesn't really make sense to add configuration options for targeting such a broken implementation, so I think you're best off monkey-patching or forking Sass to get the behavior you want.

**Comment by chriseppstein** [comment]
I wasn't even aware that you can use stylesheets with great success in emails. that blog post seems to be talking about inline style attributes.

Can you provide a demonstrable test case for this?

**Comment by joevandyk** [comment]
We use premailer and premailer-rails3 to automatically inline content from stylesheets into the html email body.

i.e. 

```
table
  td
   background-color: #efefef
```

And haml in the email view like:

```
%table
  %td
```

Makes the email look like:

```
<table><td bgcolor="#efefef" /> </table>
```

This allows us to have reasonable markup in html emails (most of the styling can be kept in sass).

**Comment by chriseppstein** [comment]
Can you please point me to a litmus test showing the magnitude of this issue in email clients? http://litmus.com/

**Comment by chriseppstein** [comment]
Note: as a work around you can do this: `unquote("#ffffff")` to emit a color as a string -- this will cause sass to output the text exactly as you type it.

**Comment by joevandyk** [comment]
Yeah, we figured we could unquote, but there's a lot of colors that could accidentally be converted to names. We'd prefer the colors to be exactly as we indicate them in the stylesheet.

https://joevandyk.litmus.com/pub/ddace69 (email with 'white' embedded in the email)

https://joevandyk.litmus.com/pub/350f5cf (exact same email, except with '#ffffff' in place of 'white')

**Comment by nex3** [comment]
It seems like it's the job of your CSS -> inline style converter to convert the colors to the expected format.

**Comment by joevandyk** [comment]
Sass is converting '#ffffff' to 'white', and premailer is supposed to convert 'white' to '#ffffff'?

I guess that's one approach.  

As an aside, what's the purpose of converting hex colors to their color names?  There any benefit, other than it might be more readable?

**Comment by nex3** [comment]
> Sass is converting '#ffffff' to 'white', and premailer is supposed to convert 'white' to '#ffffff'?

Yes. Sass compiles Sass/SCSS to CSS; its output is going to be based on the CSS spec. Premailer compiles CSS to inline styles, so it's premailer's job to convert standard CSS into a format that's understood in its target language.

> As an aside, what's the purpose of converting hex colors to their color names? There any benefit, other than it might be more readable?

It's more readable, and in compressed mode it can produce smaller CSS. Sass has no idea what the original syntax used to create colors was; it doesn't keep that information around, and even if it did the information just wouldn't exist for generated colors. We have to make a decision about what color format to use, and the decision we made was to use human-readable names where possible.

**Comment by chriseppstein** [comment]
if you have a inliner, that would be a good place to do this transformation. After all, a dev could just as easily write `white` and you'd have a bug.

**Comment by joevandyk** [comment]
Sounds good, thanks guys.  I'll see if I can get this done in premailer.

**Comment by TheDutchCoder** [comment]
I think "forcing" hex to names should be optional at least. Sometimes #ff0 is preferred over "orange" (esp. when size matters) and it's also a matter of personal preference. Would you be willing to make it optional, so it can be turned off globally?

**Comment by chriseppstein** [comment]
Sass emits the smallest color value it can when in compressed output mode, so when size matters it does the right thing. Regarding the personal preference aspect, I do not like the idea of introducing new configuration options for this -- that makes sass's code more complex and it's yet another thing that people learning sass need to read and understand.

The one thing I would consider would be to change sass's default behavior to using the same format on the output as was used on the input for un-transformed colors. unless in the compressed mode, where we would select the smallest representation. I think there is significant debugging value in preserving the authored format in as much as is possible. For transformed values we could even have the format be contagious to values derived from it.

**Comment by TheDutchCoder** [comment]
Okay I agree Chris, it makes sense to keep the original input, unless in compressed mode.
My workflow is normally to compile into readable (expanded) css for dev and then to compressed for production, so a 1-on-1 format for colors is preferred for dev (at least in my case). Oh and thanks for all the hard work, SASS is amazing!

**Comment by chriseppstein** [comment]
I have filed issue #363 to track this further.
