### ISSUE TITLE
"orange" is not a color for lighten

### ISSUE THREAD

**Issue by adie** [sass/sass#344]
I want to use standard string colors in `lighten` function, but it accepts only a few number of string colors like "red", "green" and "blue". No "orange" or "darkgreen".

**Comment by nex3** [comment]
This works on the master branch.

**Comment by micolous** [comment]
I notice the last release was two days ago (after this bug was closed), but I'm still having this problem with 3.1.16.  Was the change not merged into the stable version?

**Comment by micolous** [comment]
Just to clarify: lighten with `red`, `green`, `blue` and arbitrary hex-colours work for me, just not other named colours.

**Comment by nex3** [comment]
The stable release is cut from the stable branch, not the master branch. You'll have to wait for 3.2.0 for this.
