### ISSUE TITLE
add parameterized classes

### ISSUE THREAD

**Issue by Pieter-1337** [sass/sass#3440]
Apparently it is possible with Tailwind already would be nice to see a custom implementation in sass though :)
------------------------- 

Perhaps it already is possible but I could not find an example of it.

I was thinking it would be really handy if we could parameterize css classes.

for instance a class in a stylesheet
```
.margin-left-(value){
    margin-left: value;
}

```
Then when setting the class on the class attribute on an HTML file be able to do the following

`<div class="margin-left-(15px)">whatever</div>`

Obviously some special syntax would be needed to let it be known that from here on in the class declaration a parameter (or multiple?) is expected. Perhaps it is not possible to do so with css. But it would greatly reduce duplicate statements such as:

```
.margin-left-15{
  margin-left: 15px;
}
.margin-left-20{
  margin-left: 20px;
}
```

So yeah doing this straight from an HTML template would be awesome, and very handy. If this is already possible a link in the right direction would be appreciated 2! :)

**Comment by Goodwine** [comment]
Hi, there, Sass doesn't modify HTML files, for HTML you may want to use another templating solution.

For Sass however you could use interpolation and loops or mixins 🤔 (in a Sass file)
```scss
@each $i in [10, 15, 30] {
    .margin-something-something-#{$i} {
        a: b;
    }
}
```
