### ISSUE TITLE
Color Spaces: Missing channels in legacy colors

### ISSUE THREAD

**Issue by nex3** [sass/sass#3443]
In the [current color spaces proposal PR](https://github.com/sass/sass/pull/3426), serialization is only explicitly defined for non-legacy colors. This implies that legacy colors are serialized the same way as ever, which means they have no special handling for missing channels and thus treat them as `0`.

This produces a CSS compatibility issue: if a user writes `hsl(none 0% 50%)`, that should be serialized as `hsl(none 0% 50%)` and not `hsl(0deg, 0%, 50%)` as we would otherwise do. *However*, because `hsl(none 0% 50%)` has substantially lower browser compatibility than `hsl(0deg, 0%, 50%)` I think we *don't* want to serialize something like `color.to-space(gray, hsl)` as `hsl(none, 0%, 50.1960784314%)` despite the conversion logic recognizing that hue is powerless in this case.

I think the best solution here is probably to say that legacy colors with missing channels get serialized using the new syntax, _but also_ to add a clause to `color.to-space()` that explicitly replaces missing channels with 0 for legacy colors. That way users will only get the new, less-compatible color format if they explicitly opt into it.

**Comment by mirisuzanne** [comment]
Seems like there might be some complexity to that last bit of logic. Are we just looking at the output color, and converting all missing channels to 0 if the target space is legacy? Or only if the missing channel is also powerless, and therefor specific to the conversion? Do we care if the input color had missing channels?

**Comment by nex3** [comment]
Good question. For simplicity's sake, I think it's better to just look at whether the output color has any missing channels, regardless if they were put there because of powerless checks or original `none`s.
