### ISSUE TITLE
compiler does not remove source map reference comments

### ISSUE THREAD

**Issue by ryaa** [sass/sass#3448]
To reproduce:
1) clone the repository https://github.com/ryaa/scss-use-issue-demo
2) change to the cloned repo directory
3) issue `npm install`
4) issue `npx sass src/global.scss --load-path=node_modules | grep sourceMappingURL`
Note that the output contains the source map comments as below
```
/*# sourceMappingURL=core.css.map */
/*# sourceMappingURL=normalize.css.map */
/*# sourceMappingURL=structure.css.map */
/*# sourceMappingURL=typography.css.map */
/*# sourceMappingURL=display.css.map */
/*# sourceMappingURL=padding.css.map */
/*# sourceMappingURL=float-elements.css.map */
/*# sourceMappingURL=text-alignment.css.map */
/*# sourceMappingURL=text-transformation.css.map */
/*# sourceMappingURL=flex-utils.css.map */
```

Please see the comments in the original issues https://github.com/angular/angular-cli/issues/24230#issuecomment-1314942552 and https://github.com/ionic-team/ionic-framework/issues/26277#issuecomment-1314458815

**Comment by Goodwine** [comment]
I should get to this this week
