### ISSUE TITLE
Could not find an option named "scss".

### ISSUE THREAD

**Issue by bsastregx** [sass/sass#3453]
Strange thing happening here.
As the title says, I am getting "Could not find an option named "scss".

```
"scripts": {
    "start": "concurrently \"npm run serve\" \"npm run build:watch\" \"npm run compile:sass\"",
    "compile:sass": "sass ./src/styles:./src/styles -w",
},
```

**Comment by jathak** [comment]
Can you reproduce this error by running `sass` directly on the command line? If not, this is likely an issue with some other part of your build process, rather than Sass itself.

**Comment by ecloseraves** [comment]
Is this problem solved? [geometry dash online](https://geometrydashonline.io)
