### ISSUE TITLE
Component may not be empty error on replacing ``:host` selector

### ISSUE THREAD

**Issue by Passeriform** [sass/sass#3456]
I've been facing `SassError: components may not be empty.` after upgrading sass from `1.36.0` to `1.56.1`.

Minimum sass:
```sass
:host {
	& > ul.page-nav-container > .page-nav-traveller {
		width: 1em;

		@at-root #{selector-replace(&, ":host", ":host.continuous")} {
			background-color: red;
		}

		@at-root #{selector-replace(&, ":host", ":host.discrete")} {
			background-color: green;
		}
	}
}
```

The error log:

```sass
./src/app/shared/scrollable/page-nav/page-nav.component.scss?ngResource - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: components may not be empty.
  ╷
5 │         @at-root #{selector-replace(&, ":host", ":host.continuous")} {
  │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/shared/scrollable/page-nav/page-nav.component.scss 5:8  root stylesheet
```

I'm using selector-replace in other places just fine. It just doesn't like having `:host` in the mix.
I don't mind refactoring for this particular use-case but seems like this is unexpected.

**Comment by Goodwine** [comment]
The example code actually works for me ([example](https://stackblitz.com/edit/node-i8fbqc?file=index.js,package.json), run `npm run test`) on the latest Sass version.

Something else may be going on with your setup since it looks like your app is Angular, so I wonder if maybe your setup is misconfigured.

Since this works with Sass standalone I'll close this bug.

**Comment by Passeriform** [comment]
Thanks @Goodwine. I found the issue was with Angular version update indeed.

For anyone stumbling on this, I resorted to use `str-replace`  for replacing host instead:

```typescript
:host {
	& > ul.page-nav-container > .page-nav-traveller {
		width: 1em;

		@at-root #{str-replace("#{&}", ":host", ":host.continuous")} {
			background-color: red;
		}

		@at-root #{str-replace("#{&}", ":host", ":host.discrete")} {
			background-color: green;
		}
	}
}
```
