### ISSUE TITLE
Incorrect warning message for division with minus sign before `calc`

### ISSUE THREAD

**Issue by perenstrom** [sass/sass#3458]
We're using `sass` `1.55.0` in our Vue project. And when we migrated to Vue 3 we updated sass as well, fixing all occurrences of division without using `calc()`. However we still get warning for the following snippet, is that intended or is this a valid way of writing?

```
margin-top: -calc($arrow-button-size / 2);
```

`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`

**Comment by jathak** [comment]
This is working as intended, since `-calc(...)` is interpreted as a function called `-calc` (which has no special handling), rather than negating the result of the `calc(...)` function.

**Comment by perenstrom** [comment]
Okay, so what would the proper way of doing this calculation be? `calc(-1 * $arrow-button-size / 2);`?

**Comment by nex3** [comment]
That would work, as would `calc(-$arrow-button-size / 2)` or `calc($arrow-button-size / -2)`
