### ISSUE TITLE
Color Spaces: Unquoted channel names play poorly with RGB

### ISSUE THREAD

**Issue by nex3** [sass/sass#3464]
The [Color Spaces proposal](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md) currently requires channel names to be unquoted strings for functions like `color.channel()` and `color.is-powerless()`. While this matches the requirement that color spaces be unquoted, it raises a serious problem: the channel names `red`, `green`, and `blue` for the various predefined color spaces will be parsed by Sass as color values rather than unquoted strings, making `color.channel($color, red)` throw an error. While this could be worked around with `color.channel($color, unquote("red"))`, that's obviously infeasible in practice.

I see three basic approaches we could take here:

1. Require quoted strings instead. This avoids any ambiguity issues, but it's inconsistent with color space names which require unquoted strings and _aren't_ ambiguous with predefined colors. We could also take this a step further and change color spaces to require quoted strings as well for consistency, but then that's inconsistent with how they're written in plain CSS (particularly the `color()` function and the `<color-interpolation-method>` production, the latter of which we want to accept as-is for the `mix` function).

2. Switch to CSS's  channel terminology. Colors 5 defines [relative color syntax](https://www.w3.org/TR/css-color-5/#relative-colors) which makes explicit reference to channel names, but (other than `alpha`) they're different than the names we use. In particular, they're all single letters: `r`, `g`, `b`; `l`, `c`, `h`; and so on. While this is less obvious to a reader, there's real value in being consistent with CSS in addition to avoiding ambiguity with color names. If we did go this route, though, we'd need to consider whether to deprecate the existing long-form argument names for `color.adjust()`, `.scale()`, and `.change()`.

3. Hack around the issue entirely by defining `#f00`, `#0f0`, and `#00f` as value aliases of the channel names `red`, `green`, and `blue`. This is extremely messy so I'm inclined to dislike it, but it may be the path of least resistance.

**Comment by mirisuzanne** [comment]
I would probably lean towards options 2 here, tho 3 is tempting. 

2. I like matching CSS - and while it's less clear about what each channels represents, it's more directly related to the color name. `rgb()` has `r`, `g`, and `b` channels. I don't love either option when it comes to deprecation: breaking changes suck, and maintaining legacy syntax is a pain. But it would be a change that the migrator can automate pretty well. 

3. I agree it doesn't feel great as an implementer - but kinda clever in hiding the implementation complexity from authors. Dunno if it's worth it, tho.

**Comment by mirisuzanne** [comment]
After meeting to discuss, we settled on option 1 (with heavy hearts).

- This is a Sass function without a direct CSS counterpart, so Sass consistency seems more relevant
- It is not worth the deprecation pain to try and match CSS with all Sass-specific color functions, and doesn't make sense for this single function to behave differently

**Comment by nex3** [comment]
We decided to avoid Option 3 because even allowing unquoted strings wouldn't _really_ make `color.channel()` consistent with plain CSS, since plain CSS uses one-letter channel names, so we decided it wasn't worth the messiness of the semantics.
