### ISSUE TITLE
Sass `calc()` and CSS `calc()` inconvenience  

### ISSUE THREAD

**Issue by AndrewSunshiny** [sass/sass#3466]
There are 2 possible options when using `calc()`
1: it will be computed to some value at compiling time
1: it will be parsed as CSS `calc` function if it can't be computed because of value incompatibility

The problem:  at first there is no such when using some simple expressions, but when it gets complicated, when some variables appear in it, and especially when you are reviewing and debugging someone else code it inevitable leads to time consumption.
Plus, it would be helpful to see if the value wasn't computed but supposed to, so it would lead to a warning or error.

Some function can be added to split Sass and CSS `calc()` interpretation completely or just more convenient variant which “working only the Sass way” (computing on compiling)

**Comment by nex3** [comment]
There is a way to say "only do calculations during compilation": use Sass's arithmetic operations instead of `calc()`. If you're writing `calc()` in your Sass, you should always assume that it might emit `calc()` to your CSS.
