### ISSUE TITLE
SASS, multiline selectors and comments

### ISSUE THREAD

**Issue by marcandre** [sass/sass#348]
Take the following SASS:

```
.foo,
.bar
  display: none
```

It generates:

```
.foo,
.bar {
  display: none; }
```

That's fine.
Add any style of comment at the end of the first line and the first selectors disappears. E.g.

```
.foo, /* Hello */
.bar
  display: none
```

doesn't generate the `.foo,` part. Same thing for `// single line comment`. On the other hand:

```
.foo /* Hello */,
.bar
  display: none
```

works.

**Comment by nex3** [comment]
This is expected. The indented syntax looks for a comma at the end of the line; it's not smart enough to look around comments.

**Comment by marcandre** [comment]
Thanks for replying. So, it's a feature? Or it's a bug but it would be too hard to have the right regex for this?

**Comment by nex3** [comment]
More the latter than the former.
