### ISSUE TITLE
CSS Variables: How to assign css custom properties in a loop

### ISSUE THREAD

**Issue by yaldram** [sass/sass#3480]
Hello community, I have a list of colors and for each color I want to create the following class - 
```css
badge.gray {
   --color-100: #{$color-gray100};
   --color-500: #{$color-gray500};
   --color-800: #{$color-gray800};
 }
```
When I try to achieve this using a loop the sass variables are not evaluated - 
```sass
@each $color in $colors {
  .badge.#{"" + $color} {
    --color-100: #{'$color-' + $color + '100'};
    --color-500: #{'$color-' + $color + '500'};
    --color-800: #{'$color-' + $color + '800'};
  }
}
```
In the browser my output is the following - 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/13429535/213786377-4d0f80d3-08ce-43e9-954f-869ac9749f1c.png">

As opposed to the expected output - 
<img width="168" alt="image" src="https://user-images.githubusercontent.com/13429535/213786491-f19bb2ec-ff1c-44bd-a898-1b2ffdfa591f.png">

Please guide me, thanks in advance.

**Comment by yaldram** [comment]
One way to solve the above problem is to use css custom properties instead of sass variables like so - 
```scss
@each $color in $colors {
  .badge.#{"" + $color} {
    --color-100: #{'var(--color-' + $color + '100)'};
    --color-500: #{'var(--color-' + $color + '500)'};
    --color-800: #{'var(--color-' + $color + '800)'};
  }
}
```

**Comment by yaldram** [comment]
But when we use css custom properties we cannot use saas functions like `transparentize`.

**Comment by jathak** [comment]
This isn't an issue with custom properties; Sass variables can't be referenced dynamically. In cases like these, you should generally use a map of colors instead of Sass variables.
