### ISSUE TITLE
Question: @layer combined with SCSS

### ISSUE THREAD

**Issue by StfBauer** [sass/sass#3483]
When I use the @use directive in sass - it always has to come at the first lines of the file, while with @import they could be anywhere inside the file.

What is the common practice for [@layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) use?

For example, I like to do something like this:

```scss
@layer mylayer{
    @use 'mypartialfile'
}
```

As of now, this does not work yet or do I miss something?

**Comment by jathak** [comment]
You should use [`meta.load-css`](https://sass-lang.com/documentation/modules/meta#load-css) for this.

**Comment by StfBauer** [comment]
Awesome, thanks I will try this!!!
