### ISSUE TITLE
CSS Container Queries: support for variable in arguments

### ISSUE THREAD

**Issue by PanzerKunst** [sass/sass#3486]
First, big thanks for Sass, I've been using that library for years, and it made me like writing styles again.

I've just tested container queries, and it seems that their usage isn't yet 100% integrated with Sass. Let me show with an example.

Original code, with media queries:
```
$vw-xl: 1280px;
$vw-xxl: 1600px;
$min-content-side-margin: 16px;

main {
  @media (min-width: $vw-xl) {
    margin-left: auto;
    margin-right: auto;
    max-width: $vw-xl - $min-content-side-margin;
  }

  @media (min-width: $vw-xxl) {
    max-width: $vw-xxl - $min-content-side-margin;
  }
}
```

Equivalent styling, via container queries:
```
#root {
  container-type: inline-size;

  > main {
    @container (min-width: $vw-xl) {
      margin-left: auto;
      margin-right: auto;
      max-width: $vw-xl - $min-content-side-margin;
    }

    @container (min-width: $vw-xxl) {
      max-width: $vw-xxl - $min-content-side-margin;
    }
  }
}
```

The above code doesn't result in effective styling in the browser.

But if I replace the value of `min-width` with the respective variable value, the styling is applied in the browser:

```
#root {
  container-type: inline-size;

  > main {
    @container (min-width: 1280px) {
      margin-left: auto;
      margin-right: auto;
      max-width: $vw-xl - $min-content-side-margin;
    }

    @container (min-width: 1600px) {
      max-width: $vw-xxl - $min-content-side-margin;
    }
  }
}
```

I'm using Sass version 1.57.1 (https://registry.yarnpkg.com/sass/-/sass-1.57.1.tgz).

**Comment by jathak** [comment]
To use a variable inside most CSS at rules (including `@container`), you need to interpolate it (e.g. `@container (min-width: #{$vw-xl})`).

`@media` is an exception to this. If we were making the decision today, we would probably treat `@media` the same way we do `@container` and most other CSS at rules, but for historical reasons it doesn't require interpolation.
