### ISSUE TITLE
Warning when build the project

### ISSUE THREAD

**Issue by MattTrovao** [sass/sass#3492]
I have created a lot of builds from this project, since it was update by me or colegues, and never got any big SASS error, and the ones I got was easy to resolve, but today I got the following warning:
```
...warnings when minifying css:
▲ [WARNING] Unexpected "$" [css-syntax-error]

    <stdin>:14:0:
      14 │ $red: #d20a11;
         ╵ ^
```

 I never got this warning before, and didn't find anything about how to solve him, anyone know a way to solve this?
 
 Here is the code from the file:
 ```
 /*
* ==============================================
* ARQUIVO DE REGRAS DE CORES.
* UTILIZAR AS CORES EM HEXADECIMAL (#FFF)
* ==============================================
*/

/*
* ===========================================
* CORES PRIMARIAS
* ===========================================
*/

$red: #d20a11;
$redH: #BA0F20;
$redA: #A7272A;
$redS: #dea2a3;
$text: #231F20;
$textH: #333333;
$textA: $textH;
$textD: #0c0a0a;
$graySelect: #4f4e50;
$gray: #3b3b3b;
$gray2: #70716E;
$gray3: #41423F;
$darkBlue: #21222c;
$box: #747474;

```

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large. (It looks like this is an error coming from something other than Sass.)
