### ISSUE TITLE
IE has limit of 4095 selectors in a CSS file -- sass should warn or throw optional exception

### ISSUE THREAD

**Issue by joevandyk** [sass/sass#350]
We recently ran into a bug where IE ignores everything after the 4095th selector in a css file. We were using `@extend` extensively for lots of styles (which can create lots of css selectors) and unwittingly ran into the problem of having more selectors than the IE limit. We didn't know about the 4095 limit, so it took a lot of time tracking down why IE seemed to ignore a small percentage of our styles, and why rearranging the stylesheet fixed some bugs but caused others.

http://marc.baffl.co.uk/browser_bugs/css-selector-limit/ demonstrates the bug.

It might be good for Sass to warn about this limit if there's more than 4095 selectors in a generated file. Or even throw an exception (that could be turned off).

**Comment by averyvery** [comment]
+1

**Comment by eoinkelly** [comment]
+1

**Comment by jordanisip** [comment]
+1

**Comment by paulyoung** [comment]
One of my projects may be of use here. [Website](http://blesscss.com) and [GitHub repo](http://github.com/paulyoung/bless.js).

If there's a demand I'm happy to port it to Sass.

**Comment by eoinkelly** [comment]
@paulyoung Blesscss looks cool but I think for this use-case the check needs to be built into Sass so that you get alerted about the problem _before_ you spend time trying to figure out why some of your CSS is being mysteriously ignored.

**Comment by chriseppstein** [comment]
Would love to see a patch for this. Can someone write it?

**Comment by paulyoung** [comment]
I'm happy to, will see if I can get to it soon.

**Comment by chalofa** [comment]
+1

**Comment by TomasEkeli** [comment]
+1

**Comment by Anahkiasen** [comment]
+1

**Comment by jhilden** [comment]
FYI: We have created a small gem that can handle the splitting of big stylesheets for you in Rails projects using the Asset Pipeline:  https://github.com/zweilove/css_splitter
However, it's still version `0.0.1` and help would be appreciated.

Nevertheless, I think it would be a great idea to integrate a warning about too many selectors into Sass itself.  Because often those too big stylesheets can be avoided with some proper feedback at the right time.  Maybe Sass could even handle all the selector-counting-buisiness and css_splitter would only handle the splitting.

**Comment by alademann** [comment]
+1

**Comment by polarbirke** [comment]
+1

**Comment by ghepting** [comment]
+1 -- but honestly if you have that many styles that have to be in 1 stylesheet #yourdoingitwrong  :)

**Comment by mcberros** [comment]
+1

**Comment by piouPiouM** [comment]
Note: if you use Compass, you have the `compass stats` command to see the number of CSS selectors by stylesheet (you have to install the `css_parser` gem).

**Comment by vinayraghu** [comment]
:+1:

**Comment by DanielApt** [comment]
+1

**Comment by albybarber** [comment]
@joevandyk if you are using grunt as part of your build process then you could just throw - `grunt-scss-lint` https://github.com/ahmednuaman/grunt-scss-lint into one of your tasks.

Also a cool trick i have done in the past (before SCSS and GRUNT) is add banners to your site that say `IE RULE LIMIT REACHED` then add `display:none` styles right at the bottom of your stylesheet. This way if you reach the limit and are testing in IE you will see the banners when there is an issue.

**Comment by nex3** [comment]
Since [Sass no longer supports versions of IE before IE 10](http://sass.logdown.com/posts/1404451), this is no longer planned.
