### ISSUE TITLE
Parent selector with :is() CSS pseudo-class function 

### ISSUE THREAD

**Issue by untainsYD** [sass/sass#3505]
I propose adding some flexibility in using the parent `scss` selector (`&`) with `:is()`.

When I am trying to use smth like:
```scss
:is(.some-class) {
    ...
    &__element {
        ....
    }
} 
```

Sass compiler parses it as `:is(.some-class) __element`. I know, it's right and all is fine, but I want to have some flexibility to control it, and have an output like: `:is(.some-class__element)` or for multiple classes `:is(.some-class__element, .some-class-2__element)`.

I don't have any ideas for implementation, but it might be interesting for SASS developers to look into it, in future milestones.

For more clarification try:
```scss
:is(.test, testSecondary) {
    @debug #{&};
    @debug #{&__element};
}
```

**Comment by jathak** [comment]
This isn't something we plan to support. `&` always applies to the entire parent selector.
