### ISSUE TITLE
Number of decimals

### ISSUE THREAD

**Issue by BenjaminHoegh** [sass/sass#3509]
I find it a bit wasteful that SASS always use the same number of decimals when less can be used without changed the value

example:
`max-width: 83.3333333333%;` could just be `max-width: 83.33%;`

while still keep decimals where needed 
`flex: 0 0 66.6666666667%;`

**Comment by nex3** [comment]
Fewer decimals _does_ change the value. `max-width: 83.33%` will have observably different behavior than `max-width: 83.3333333333%;` on large or high-resolution screens. Even if it didn't, there's no way for Sass to tell what context a given number serialization will be used and adjust it accordingly.
