### ISSUE TITLE
`@use` should be after `@layer`?

### ISSUE THREAD

**Issue by ngdangtu-vn** [sass/sass#3510]
Right now, the only thing I know that can be on top of `@use` is itself or comment. But to define `@layer`, we should keep it on top of other rules. And it doesn't seem possible right now.

**Comment by ngdangtu-vn** [comment]
For now, I use the legacy `@import` to solve this problem.

**Comment by nex3** [comment]
This is one reason we generally recommend `@use`-ing libraries that provide mixins, rather than always emit top-level CSS. If you do that, you can make sure to `@include` your mixins after the `@layer` rule.

**Comment by ngdangtu-vn** [comment]
> rather than always emit top-level CSS. If you do that, you can make sure

Actually, I always keep `@mixin` in a separated file. So my struct right is like this:

```SCSS
@use 'mixins' as m;

@layer reset, base, comp;

@import 'reset';
@import 'comp';

@include m.awesome;
```

However, as the doc warned, the `@import` is deprecated so the code above is not safe to use. I prefer to have a official way to deal with this case. We cannot close this issue this way.

**Comment by nex3** [comment]
I'm saying that the contents of `reset.scss` and `comp.scss` should _also_ be wrapped in mixins.

If you really want to write them as top-level CSS, you can use the `meta.-load-css()` mixin instead of `@use` or `@import`.
