### ISSUE TITLE
Migrating from SASS @import

### ISSUE THREAD

**Issue by chrisfinazzo** [sass/sass#3514]
In a prior version of my project, I:

1. Used `@import` to bring all SCSS files into `app.scss`
2. Converted `app.scss` to `app.css` with `sass`
3. Compressed the resulting file with the `--compressed` flag

After installing and running the migration tool, it tells me I should use `@use` instead, when *I think* to do what I want means `@forward` instead. The command I ran and the directory it is working on are show below.

`sass-migrator --migrate-deps --verbose --dry-run module app.scss `

```
.
├── app.scss
├── base.scss
├── contact.scss
├── grid.scss
├── layout.scss
├── rjp.scss
├── social.scss
├── typography.scss
└── utils.scss

```

I updated my NPM scripts and tried it out, but the resulting file only shows the `@forward` statements and not the compiled result.

```
@forward 'base';
@forward 'contact';
@forward 'layout';
@forward 'rjp';
@forward 'social';
@forward 'typography';
@forward 'utils';
@forward 'dark';
@forward 'grid';

/*# sourceMappingURL=app.css.map */
```

Did I miss a step?

**Comment by stof** [comment]
you need to use the `sass` package to compile your Sass files, not `node-sass`. `node-sass` has not implemented support for Sass modules yet.
Note that node-sass is deprecated and won't receive support for them: https://github.com/sass/node-sass/#node-sass

**Comment by stof** [comment]
> After installing and running the migration tool, it tells me I should use `@use` instead, when _I think_ to do what I want means `@forward` instead.

Actually, if all you want is to produce a CSS file, `@use` will work totally fine. Using `@forward` is useful only if you want to expose the mixins, functions and variables to other Sass imports of your `app.scss` file.

**Comment by chrisfinazzo** [comment]
Apologies, I should have been more specific:

- Migration away from `node-sass` is complete. The original comment has been updated to reflect this fact.
- Styles are transformed into CSS with the following script: `sass --style=compressed ./src/scss/app.scss ./public/css/app.css`
- While this produces an `app.css` in the appropriate directory, this takes the form shown below, as opposed to what I expected to see - the styles written out in compressed form.

```
@forward 'base';@forward 'contact';@forward 'layout';@forward 'rjp';@forward 'social';@forward 'typography';@forward 'utils';@forward 'dark';@forward 'grid'
/*# sourceMappingURL=app.css.map */
```

Is this behavior correct and it's just my understanding which is off? Would seem like a fairly significant change compared to past versions...

**Comment by stof** [comment]
which version of `sass` are you using ?

**Comment by chrisfinazzo** [comment]
> which version of `sass` are you using ?

1.60.0

**Comment by nex3** [comment]
Can you provide a minimal GitHub repo that reproduces this?

**Comment by chrisfinazzo** [comment]
> Can you provide a minimal GitHub repo that reproduces this?

Test repo is [here][].

[here]: https://github.com/chrisfinazzo/sass-test

**Comment by stof** [comment]
Running `npm run sass:release` in your repository produces this output:

```
Error: Can't find stylesheet to import.
  ╷
8 │ @use 'dark';
  │ ^^^^^^^^^^^
  ╵
  src/scss/app.scss 8:1  root stylesheet

```

**Comment by chrisfinazzo** [comment]
Updated now - I was trying out using System Colors as described [here][] and must have forgotten to remove it.

[here]: https://blog.jim-nielsen.com/2021/css-system-colors/

![facepalm](https://media.giphy.com/media/WrNfErHio7ZAc/giphy.gif?cid=ecf05e47fj1iw5hoscwnljit5jzo8vidsynllfe02ypjlrop&rid=giphy.gif&ct=g)

**Comment by stof** [comment]
When I run the command now, `public/css/app.css` contains the expected CSS, not `@use`. So it looks like it works.

**Comment by chrisfinazzo** [comment]
> When I run the command now, `public/css/app.css` contains the expected CSS, not `@use`. So it looks like it works.

What command are you actually running here? Starting to think my script might not actually be doing the correct thing...unless this actually _is_ expected behavior.

![Screen Shot 2023-03-29 at 9 52 01 AM](https://user-images.githubusercontent.com/1534882/228560258-f8f7fa90-de50-4a1c-b3a4-b746035a8207.jpg)

**Comment by stof** [comment]
I'm running `npm run sass:release`

Can you run `sass --help` and paste the full output ? I'm suspecting that the `sass` command being executed on your machine is _not_ dart-sass 1.60.0 contrary to what you answered before.

**Comment by chrisfinazzo** [comment]
Ah, now I see what's going on...

```
Chris in [~/Documents/Sass Test] on (main) % sass -v
Ruby Sass 3.7.4
Chris in [~/Documents/Sass Test] on (main) % brew info sass
==> sass/sass/sass: stable 1.60.0
Stylesheet Preprocessor
https://sass-lang.com
/usr/local/Cellar/sass/1.60.0 (7 files, 8MB) *
  Built from source on 2023-03-23 at 22:35:31
From: https://github.com/sass/homebrew-sass/blob/HEAD/sass.rb
==> Dependencies
Build: dart-lang/dart/dart ✔
```

```
Chris in [~] % sass --help
Compile Sass to CSS.

Usage: sass <input.scss> [output.css]
       sass <input.scss>:<output.css> <input/>:<output/> <dir/>

━━━ Input and Output ━━━━━━━━━━━━━━━━━━━
    --[no-]stdin                   Read the stylesheet from stdin.
    --[no-]indented                Use the indented syntax for input from stdin.
-I, --load-path=<PATH>             A path to use when resolving imports.
                                   May be passed multiple times.
-s, --style=<NAME>                 Output style.
                                   [expanded (default), compressed]
    --[no-]charset                 Emit a @charset or BOM for CSS with non-ASCII characters.
                                   (defaults to on)
    --[no-]error-css               When an error occurs, emit a stylesheet describing it.
                                   Defaults to true when compiling to a file.
    --update                       Only compile out-of-date stylesheets.

━━━ Source Maps ━━━━━━━━━━━━━━━━━━━━━━━━
    --[no-]source-map              Whether to generate source maps.
                                   (defaults to on)
    --source-map-urls              How to link from source maps to source files.
                                   [relative (default), absolute]
    --[no-]embed-sources           Embed source file contents in source maps.
    --[no-]embed-source-map        Embed source map contents in CSS.

━━━ Warnings ━━━━━━━━━━━━━━━━━━━━━━━━━━━
-q, --[no-]quiet                   Don't print warnings.
    --[no-]quiet-deps              Don't print compiler warnings from dependencies.
                                   Stylesheets imported through load paths count as dependencies.
    --[no-]verbose                 Print all deprecation warnings even when they're repetitive.
    --fatal-deprecation            Deprecations to treat as errors. You may also pass a Sass
                                   version to include any behavior deprecated in or before it.
                                   See https://sass-lang.com/documentation/breaking-changes for 
                                   a complete list.

          [bogus-combinators]      Leading, trailing, and repeated combinators.
          [call-string]            Passing a string directly to meta.call().
          [color-module-compat]    Using color module functions in place of plain CSS functions.
          [elseif]                 @elseif.
          [function-units]         Passing invalid units to built-in functions.
          [moz-document]           @-moz-document.
          [new-global]             Declaring new variables with !global.
          [slash-div]              / operator for division.
          [strict-unary]           Ambiguous + and - operators.

    --future-deprecation           Opt in to a deprecation early.

          [import]                 @import rules.

━━━ Other ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-w, --watch                        Watch stylesheets and recompile when they change.
    --[no-]poll                    Manually check for changes rather than using a native watcher.
                                   Only valid with --watch.
    --[no-]stop-on-error           Don't compile more files once an error is encountered.
-i, --interactive                  Run an interactive SassScript shell.
-c, --[no-]color                   Whether to use terminal colors for messages.
    --[no-]unicode                 Whether to use Unicode characters for messages.
    --[no-]trace                   Print full Dart stack traces for exceptions.
-h, --help                         Print this usage information.
    --version                      Print the version of Dart Sass.
```

The Homebrew install gives me the Dart implementation, but I didn't think it required being listed in `package.json`?

Weird.

**Comment by stof** [comment]
Well, looks like your project has ruby-sass installed in a place where the PATH will give it priority over your global install of dart-sass when you are inside your project.
there is 2 things you can do:

- check how the PATH is configured on your system to understand why `sass` refers to rub-sass when you are in `~/Documents/Sass Test` while it refers to dart-sass when you are in `~`. Maybe it is related to the ruby-version file in your test repo that would enable some globally-installed gems when you are in this folder (which would be why I don't reproduce it on my machine)
- remove ruby-sass entirely from your system as this should not be used anymore.

**Comment by chrisfinazzo** [comment]
I think this is fixed now...

It might have been down to the `.ruby-version` still in the directory when I was playing around with generation which was overriding dart-sass. While `sass --version` continues to report Ruby Sass, processing my stylesheets now gives me an `app.css` that looks as I expect it to.

I still need to port these changes over to the actual project they will be used in (and make the equivalent changes to my blog - which uses Jekyll - and is a bit of a different procedure) but this is at least a path forward.

Thanks all.

![awsome](https://media.giphy.com/media/mbhseRYedlG5W/giphy.gif)
