### ISSUE TITLE
Allow out-of-gamut HSL/HWB?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#3515]
The CSSWG just reversed course on this, and resolved to allow out-of-gamut colors in these spaces. The argument is in two parts, only one of which applies to us:

- The gamut mapping was observable by JS, a privacy concern we don't have to worry about
- The gamut mapping makes round-trips lossy

https://github.com/w3c/csswg-drafts/issues/8444

That second argument, along with matching CSS, makes me think we should follow suit.

**Comment by mirisuzanne** [comment]
Remove all clamping again. 😅

**Comment by mirisuzanne** [comment]
This is on the agenda again at the CSSWG meeting tomorrow - so holding off to see how that resolves.

**Comment by mirisuzanne** [comment]
Current state, as I understand it… CSS still performs clamping for:

- all alpha/opacity
- all (ok)lab/(ok)lch lightness
- all channels of the rgb(a) functions

CSS does not clamp hsl/hwb any more. Still, in order to handle round-tripping interpolation (color-mix or relative-color syntax) through legacy spaces, those functions always return `color(srgb …)` non-legacy format.

Currently in the Sass color proposal v1.4, we clamp:

- all alpha/opacity
- all (ok)lab/(ok)lch lightness
- hsl lightness and saturation
- hwb whiteness and blackness (we also scale them so `w+b <= 100`)

Before I make changes, I just want to clarify where we're headed:

- I think we need to keep clamping for alpha and (ok)lab/lch lightness channels?
- remove clamping & scaling in hsl and hwb
- I'm not clear if we need to use `color(srgb …)` for interpolation through non-legacy spaces?

Thoughts @nex3 ?

**Comment by mirisuzanne** [comment]
1. correct
2. correct
3. no change

**Comment by nex3** [comment]
Reading through the resolution of https://github.com/w3c/csswg-drafts/issues/8444, I'm not sure it's actually saying that `hsl()` and `hwb()` aren't clamped. I think instead it's saying that _all_ legacy color spaces are clamped for backwards compatibility, and the round-tripping issue is solved by having `color-mix()` and relative color syntax return sRGB colors when operating in a legacy space. @tabatkins can you confirm?

If that's correct, then I think we need to change the behavior here. We should:

* Always clamp legacy RGB, HSL, and HWB colors (again :sweat_smile:).
* Return unclamped sRGB colors when doing `color.mix()` with an explicit legacy space.
* Plan to return unclamped sRGB colors for relative color syntax once we support that.

**Comment by mirisuzanne** [comment]
I can see that read of the issue. But I don't see anything in the CSS Color 4 specification that mentions clamping on hwb or hsl colors - only rgb. Maybe that's an issue in the spec?

**Comment by tabatkins** [comment]
I've actually lost track of exactly what the state is of these functions. @svgeezus, could you answer this?

**Comment by mirisuzanne** [comment]
I asked Chris on Mastodon, and got an answer: https://mastodon.social/@svgeesus/110832780356396419
 
HSL and HWB should not be clamped. Closing this with no change, for now.
