### ISSUE TITLE
Add JS API for deprecations

### ISSUE THREAD

**Issue by jathak** [sass/sass#3520]
* [x] Proposal (https://github.com/sass/sass/pull/3522) - Open for public comment until 4/19
* [x] Tests
* [x] Documentation
* [x] Dart Sass
* [x] Node Host

---

Tracking issue for adding deprecations support to the JS API, matching the behavior of the `--fatal-deprecation` (https://github.com/sass/dart-sass/issues/633), `--future-deprecation` (https://github.com/sass/dart-sass/issues/1363), and `--silence-deprecation` (https://github.com/sass/dart-sass/issues/1918) CLI flags.

**Comment by stof** [comment]
is there any progress on implementing that accepted proposal or was it forgotten ?

**Comment by nex3** [comment]
It's in @jathak's list of tasks, but that list is very long and this hasn't hit the top of the priority queue yet.
