### ISSUE TITLE
Parse native CSS nesting in plain CSS

### ISSUE THREAD

**Issue by nex3** [sass/sass#3524]
* [x] [Proposal](https://github.com/sass/sass/blob/main/proposal/plain-css-nesting.md)
* [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1927) (https://github.com/sass/dart-sass/pull/2198)
* [x] [Tests](https://github.com/sass/sass-spec/issues/1894) (https://github.com/sass/sass-spec/pull/1963)
* [x] Documentation is probably not necessary, since this is covered by the general expectation that plain CSS parsing supports all plain CSS features
* [x] Update canonical spec (https://github.com/sass/sass/pull/3841)

---

Although we're preserving Sass's current nesting behavior for now (per https://github.com/sass/sass/issues/3030), we can support native CSS nesting when parsing plain CSS. We shouldn't do any resolution here, just pass it through as-is.

**Comment by nex3** [comment]
Proposal is out, since this is a low-risk subset of plain CSS nesting support I'll give this two weeks for public comment.

**Comment by flachware** [comment]
I appreciate the efforts to bring native nesting to Sass. Please clarify, do I understand correctly that this means that all features of Sass are available in `.css` files, except for Sass’ nesting?

**Comment by nex3** [comment]
No, _no_ Sass features are available in `.css` files. They are parsed strictly as plain CSS. See https://sass-lang.com/documentation/at-rules/use#loading-css for details.

**Comment by flachware** [comment]
Pity, so it’s either Sass or native nesting. But thanks for clarifying.

**Comment by ggedde** [comment]
@nex3 I am a little confused as to how this will work. Sorry the documentation is a bit hard to understand. I just tested using @use with a plain .css file, but nesting does not work as it gives an error. Is there no way to currently import an plain .css file and leave it exactly as the way it is and ignore all errors? Is there any error suppression setting, etc? Or are you saying that we will have to wait for that?

I guess I can just run some sort of npm package/command after sass parse to add my plain css to the final bundle, etc.

**Comment by nex3** [comment]
This issue is still open and the checkbox for "Dart Sass" isn't checked, which indicates that this has not yet been implemented.
