### ISSUE TITLE
@ at rules @use isn't working 

### ISSUE THREAD

**Issue by AlAminKh03** [sass/sass#3526]
Let me first share my file structure,
I'm willing to make my own component lib named "Girgiti" by Sass. So, In my project, I have made a folder name Girgiti and below I'm trying to illustrate my folder structure 

- Girgiti
       -   Components 
  ` _cards.scss `
-  _variables.scss
-  _base.scss
-  index.scss
sorry, I couldn't illustrate as desired but let me explain In in `Girgiti ` folder there's 3 files and 1 folder , the 3 files are `_variables.scss`,`_base.scss`,`  index.scss` and the folder is `Components`. Inside the `Components` folder there's another file named `_cards.scs` .  In `_variables.scss` i have declared some variables to use across all the module. As desired i imported all of my files in `indes.scss` file like this 

- @use "variables";
- @use "base";
- @use "Components/cards";
 But when I use like this it shows me a compilation error that it can't access the variables from `_variables.scss`  but when i use **@import** instead of **@use** it compiles with no errors and works just fine. But in documentation, it is recommended to use the @use rule to import modules.

**Comment by jathak** [comment]
While `@import` loads all Sass variables into a shared global namespace, allowing files to reference variables from files they don't actually import directly, `@use` isolates each module's members into its own namespace, so you'll need to update your code to add `@use` rules for each file that depends on variables from another, and then namespace them accordingly. If you're migrating code that was using `@import`, you can run the [Sass migrator](https://sass-lang.com/documentation/cli/migrator) to handle most cases of this automatically.
