### ISSUE TITLE
Configure the forwarded module with nested maps

### ISSUE THREAD

**Issue by untainsYD** [sass/sass#3530]
Can we configure the forwarded module with nested maps to override any value?

I have some maps like that:
```scss
// filename _maps.scss

$variable: (
    'map': (
        'grey': #747474,
    ),
    'map_2': (
        'transparent': transparent,
    ),
    'map_3': (
        'transparent': transparent,
    ),
) !default;
```

Then I forward them to `_index.scss` file:
```scss
@forward 'maps' as maps-* with (...);
```
But it doesn't work for nested maps, only for the flattened ones, like:
```scss
// filename _maps.scss

$variable: (
    'key': value,
    'key_2': value,
    'key_3': value,
) !default;
```

```scss
// filename _index.scss

@forward 'maps' as maps-* with ($variable: ('key': newValue)); // works fine
```

My folder structure in that demo would look like:
```
...
folder/
     _maps.scss
     _index.scss
```

**Comment by stof** [comment]
What do you mean by "it works with flattened maps" ? If you expect it to override only the `key` key in the map, it does not work either with a flattened map. You are still overriding the `$variable` variable with a map containing a single key. Here is the proof:

```scss
@use 'index' as i;

@debug i.$maps-variable;
```

This outputs this:

```
debug.scss:3 Debug: ("key": newValue)
```

Overriding a variable containing a map **never** performs merging automatically.

**Comment by stof** [comment]
If you want to allow overriding any value, a solution is to separate the configurable input from the default value:

```scss
@use 'sass:map';

$variableCustomization: () !default;
$_variableDefaults: (
    'map': (
        'grey': #747474,
    ),
    'map_2': (
        'transparent': transparent,
    ),
    'map_3': (
        'transparent': transparent,
    ),
);
$variable: map.deep-merge($_variableDefault, $variableCustomization);
```

```scss
@forward 'maps' as maps-* with ($variableCustomization: ('map': ( 'grey': #636363,'red': #630000));
```

**Comment by untainsYD** [comment]
@stof Thank you for your answers!

> What do you mean by "it works with flattened maps" ? If you expect it to override only the key key in the map, it does not work either with a flattened map.

Yes, I was mistaken, I meant overriding the variable with a new `map` key/value.

> @forward 'maps' as maps-* with ($variableCustomization: ('map': ( 'grey': #636363,'red': #630000));

Thank you, for your solution, it's great!
