### ISSUE TITLE
Need the best way to download Sass for Visual Studio Code

### ISSUE THREAD

**Issue by bgswan2** [sass/sass#3535]
I need to find out how to download sass to run in Visual Studio Code, if possible.
Can anyone help me?

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
