### ISSUE TITLE
Conversion of hex colors to names (#FFFFFF to white) ruins gradients

### ISSUE THREAD

**Issue by jpg** [sass/sass#354]
IE9 (and below) only accepts full 6-character hex codes for colors used in gradients:

http://msdn.microsoft.com/en-us/library/ms532930%28v=vs.85%29.aspx

Others have tried to solve it, but this didn't work for me (and seems like an ugly hack):

http://pinds.com/2011/11/30/fixing-ie-gradients-with-rails-3-1-and-scss/

The popular sass version of Twitter Bootstrap is quite broken because of this issue.

If there was a way to turn off this compilation feature of sass that would fix it.

**Comment by chriseppstein** [comment]
Sass provides the `ie-hex-str($color)` function in 3.2 which emits color values that are compliant with the non-standard color values that IE filters expect.
