### ISSUE TITLE
Unwanted character is prepended to generated css file

### ISSUE THREAD

**Issue by NavinSK7936** [sass/sass#3545]
An unwanted unicode character is prepended to the css file when the following .scss file is compiled
```
.label {
    width: 100%;
    &::after {
      content: '\2666a';
    }
}
```
the resulting compressed .css file is
`\ufeff.label {
width: 100%;
}
.label::after {
content: '\2666a';
}
}`

IDK why that strange unicode character is added to the output file,
and css processes '\ufeff.label' as a selector and thus ignoring the style for '.label'.

I'm using sass 1.56.1 compiled with dart2js 2.18.4.

**Comment by stof** [comment]
Are you using Sass alone or a part of a bigger pipeline ?
U+FEFF is the BOM character. Adding it at the beginning of the generated CSS as a unicode character is totally expected. However, it should not be added as a CSS escape sequence.

When I try that with the official builds of Sass, I don't receive it as a CSS escape sequence though, so I cannot reproduce the issue.

**Comment by NavinSK7936** [comment]
yep sorry the issue was in part of another pipeline, thanks btw

**Comment by stof** [comment]
If your pipeline combines the generated CSS with other CSS files and does not want this BOM, you can use the `charset` option to disable it: https://sass-lang.com/documentation/js-api/interfaces/Options#charset

**Comment by nex3** [comment]
(Note that naively concatenating CSS files is not safe for a number of reasons, not just the presence of a `charset` or BOM)
