### ISSUE TITLE
Define compile*ToResult methods in TypeScript

### ISSUE THREAD

**Issue by mjomble** [sass/sass#3561]
In [Dart Sass 1.36](https://github.com/sass/dart-sass/releases/tag/1.36.0), the following change was made:

> Added compileToResult(), compileStringToResult(), compileToResultAsync(), and compileStringToResultAsync() methods. These are intended to replace the existing compile*() methods, which are now deprecated.

However, https://github.com/sass/sass/blob/main/js-api-doc/compile.d.ts has not yet been updated to reflect these changes.

**Comment by nex3** [comment]
Those changes were made to the Dart API, not the TypeScript API (note the header in the release notes). The TypeScript API has always returned result objects, so it doesn't need to have the new return type flagged as separate function names.
