### ISSUE TITLE
Make semicolons optional in SCSS

### ISSUE THREAD

**Issue by TheBlckbird** [sass/sass#3567]
What about making semicolons optional in SCSS?
I personally find them really annoying so why not just make them optional?
And you can see that it SCSS would work without them when you look at SASS.

## Why not just use SASS?

I don’t really like code that depends on indentation to define scopes like Python or SASS.
So it’s just a personal preferance but I think that many people would agree on it.

**Comment by jathak** [comment]
The main feature of the SCSS syntax is that it is a superset of plain CSS. Optional semicolons would violate that, so it's not something we can support.
