### ISSUE TITLE
iconv deprecated

### ISSUE THREAD

**Issue by kud** [sass/sass#357]
I've got a bug when SASS. Each time I compile, it tells me "iconv deprecated".

https://github.com/chriseppstein/compass/issues/835

**Comment by nex3** [comment]
Sass doesn't reference iconv, and to the best of my knowledge never has. I'm not sure why you're seeing this issue, but I don't think it's Sass.

**Comment by kud** [comment]
hey,

Did you read what it's written in the link? The author of compass was telling me it seems to be a SASS bug. That why I posted here.

**Comment by nex3** [comment]
Chris thought it was a Sass bug because he knew it wasn't a Compass bug. I know it's neither a Sass bug nor a Compass bug. It must be coming from elsewhere in your app.

**Comment by kud** [comment]
Okay! I'll check deeper to see where's the bug. Thank you! ;)
