### ISSUE TITLE
double slash (//) behavior inside CSS custom property aren't documented

### ISSUE THREAD

**Issue by hibiyasleep** [sass/sass#3573]
### tl;dr

when declarating CSS custom property, `//` seems doesn't handled as comment. semicolon inside comment also affects syntax.
**This behavior could be okay** and is intended behavior, but however, most editor and syntax highlighting and even [official documentation](https://sass-lang.com/documentation/syntax/comments) don't tell this.

### env
dart-sass 1.32.12

### examples
assuming every content is under `:root {` or somewhat:

* In Sass
  ```sass
    --var1: foo // comment
    --var2: bar // this comment contains symbols and semicolon; what would be happen?
  ```
  becomes
  ```css
    --var1: foo // comment;
    /* (--var2 fails with 'Semicolon aren't allowed in the indented syntax' error.) */
  ```
* In SCSS
  ```scss
    --var1: foo; // comment
    --var2: bar // comment;
    --var3: baz // this comment contains symbols and semicolon; what could be happen?
  ```
  becomes
  ```css
    --var1: foo;
    --var2: bar // comment;
    /* (--var3 fails with 'Excepted "{"' error.) */
  ```

**Comment by nex3** [comment]
This is expected behavior. CSS variables have special parsing behavior for CSS compatibility, because in CSS they allow _almost anything_ as their value, and those values are directly accessible to JavaScript so we can't just say that Sass treats them differently. Essentially what this means is that silent comments aren't supported inline within custom property values.

**Comment by hibiyasleep** [comment]
I think this should be documented somewhere at least, as official syntax highlighting even getting confused of this. should this go into another issue?

**Comment by nex3** [comment]
We do call out the fact that custom properties are parsed differently [in the docs](https://sass-lang.com/documentation/style-rules/declarations#custom-properties):

> Because of this, Sass parses custom property declarations differently than other property declarations. All tokens, including those that look like SassScript, are passed through to CSS as-is. The only exception is [interpolation](https://sass-lang.com/documentation/interpolation), which is the only way to inject dynamic values into a custom property.

The _precise_ details of how Sass parsing works belongs in [the spec](https://github.com/sass/sass/blob/main/spec/spec.md). The specification of existing behavior is expanded lazily as needed, so we don't have anything there currently for custom properties.
