### ISSUE TITLE
Silent Extend doesn't extend in place

### ISSUE THREAD

**Issue by Snugug** [sass/sass#358]
I'm using silent extends and I've noticed something unexpected that will effect cascading and therefore is BAD. If I have a silent extend that exists before some styling and then use the silent extend after some that styling, the extended selectors show up above the styling they were called from. this is unexpected as I was under the impression that the point of silent extends was to inherit from the first item that called them. Example:

```
%foo {
  color: red;
}

body {
  color: green;
}

.bar {
  @extend %foo;
}


Output:


.bar {
  color: red;
}

body {
  color: green;
}


Expected Output:


body {
  color: green;
}

.bar {
  color: red;
}
```

**Comment by nex3** [comment]
This is expected. Placeholder selectors work just like normal selectors in all respects except that they themselves are not printed. This includes where the generated rules for `@extend` exist in your stylesheets.

Conceptually, `@extend` makes additional rules apply to a given selector. Those rules apply with all the cascade information of the originally declaration. Ideally even the original specificity would be preserved, but unfortunately this isn't possible in a preprocessor.

**Comment by chriseppstein** [comment]
closing.
