### ISSUE TITLE
[FR] `rgb(#fff / 0.5)` and `rgba(#fff / 0.5)` support

### ISSUE THREAD

**Issue by wenfangdu** [sass/sass#3586]
Now that Sass supports the following formats:

```scss
rgb($red $green $blue / $alpha)
rgba($red $green $blue / $alpha)
```

I propose to add `rgb(#fff / 0.5)` and `rgba(#fff / 0.5)` support as well.

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/3036
