### ISSUE TITLE
Versioning of the embedded protocol

### ISSUE THREAD

**Issue by stof** [sass/sass#3588]
This language spec is a living standard that has no version.

As the embedded protocol serves as the basis for generating the protobuf client code, having it unversioned makes things harder IMO. what is the plan for versioning the protocol ? And where will the changelog of the protocol be provided ?

**Comment by nex3** [comment]
The embedded protocol version lives in [`spec/EMBEDDED_PROTOCOL_VERSION`](https://github.com/sass/sass/blob/main/spec/EMBEDDED_PROTOCOL_VERSION) and the changelog lives in [`EMBEDDED_PROTOCOL_CHANGELOG.md`](https://github.com/sass/sass/blob/main/EMBEDDED_PROTOCOL_CHANGELOG.md).
