### ISSUE TITLE
flexible indentation for generated CSS

### ISSUE THREAD

**Issue by ttilley** [sass/sass#36]
I'm currently working at a shop that requires 4-space indented CSS, regardless of what's being used to work on, edit, or generate it. I took a stab at making this an option in SASS, and am curious what would be necessary for making this into an officially accepted patch. In particular, I want to make sure I'm going about this the right way.

https://github.com/ttilley/sass/commit/76881d355c3ffb3f0b378c65ac7a78945661f141

**Comment by chriseppstein** [comment]
I have no objection.

**Comment by ttilley** [comment]
...I forgot this was even still open and have long since left the scenario where I needed to care.
