### ISSUE TITLE
How can i make change in sass compiler program.

### ISSUE THREAD

**Issue by Shaik-mohd-huzaifa** [sass/sass#3616]
#### I want to add a new snippet/syntax in the Sass pre-processor how can I add that i the Sass compiler? Or if I describe that snippet will you add that to the compiler? [Enhancement]

**Comment by jathak** [comment]
If you'd like to propose a new feature for the language, you can follow [our contributing process](https://github.com/sass/sass/blob/main/CONTRIBUTING.md)
