### ISSUE TITLE
Q: ambient/global 3rd party sass variables

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sass/sass#3646]
I am currently facing a problem where I want to override sass variables from a node module. I am using old school indented syntax sass.
The sass file lives in 'quasar/dist/quasar' but starting the quasar app will automatically add that sass file to the sass-loader. So when I try to `@use` that file to override some of the variables I get `Syntax Error: Module loop: this module is already being loaded.` On the other hand, I cannot remove the `@use` because then I don't have any connection to the variable.
Is there something in sass that just tells the compiler, there is already some sass loaded that defines some variables already?
How do I handle 3rd party sass files that may or may not get injected during a build or dev process?

**Comment by jathak** [comment]
On a technical level, if the files are coming via sass-loader, that's not something we can track from within Sass itself, so this issue would need to be resolved within sass-loader.

Philosophically, we generally don't want to enable this sort of ambient/global state. If you need to configure a dependency, the better option is usually to use a mixin.

**Comment by hinogi** [comment]
The sass file comes in via a different mechanism, mainly through a cli that uses a config and automatically inject the sass files in that case.
The sass-loader thing is the manual route without that automatic injection.
How would I use a mixin in that case?
