### ISSUE TITLE
Chroma should be clamped to 0+

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#3647]
It's not possible to have a Chroma less than 0.

**Comment by nex3** [comment]
Is this also true for HSL saturation? Are there any places where Lch and OKLch differ on what "zero chroma" is exactly, like they do for lightness (https://github.com/w3c/csswg-drafts/issues/9484)?

**Comment by mirisuzanne** [comment]
> Is this also true for HSL saturation? 

The spec does not clamp… I'm not sure what it would mean to have negative saturation, though. Not sure if there's a good way to test when browsers either clamp (at parse time) or clip that value for display.

> Are there any places where Lch and OKLch differ on what "zero chroma" is exactly, like they do for lightness?

I imagine it's possible, but don't know how to track that down.

**Comment by nex3** [comment]
If the spec doesn't clamp, I don't think we should either. Even if it's not particularly meaningful, we risk losing information when serializing to CSS or during round-trips.

**Comment by nex3** [comment]
I'm going to merge this into https://github.com/sass/sass/issues/3737, because I think it's just a special case of how to handle that.
