### ISSUE TITLE
rake install fails

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#365]
$ sudo rake install
(in /root/sass)
git submodule sync
Synchronizing submodule url for 'vendor/listen'
git submodule update --init
Cloning into vendor/listen...
remote: Counting objects: 1196, done.
remote: Compressing objects: 100% (517/517), done.
remote: Total 1196 (delta 757), reused 1094 (delta 656)
Receiving objects: 100% (1196/1196), 159.32 KiB, done.
Resolving deltas: 100% (757/757), done.
Submodule path 'vendor/listen': checked out 'b48a81d58ece9e741372ed5808ec9580f8a7978e'
chmod -R a+rx bin
chmod -R a+r .
chmod a+rx test/sass/logger_test.rb
chmod a+rx test/sass/plugin_test.rb
chmod a+rx test/sass/engine_test.rb
chmod a+rx test/sass/less_conversion_test.rb
chmod a+rx test/sass/callbacks_test.rb
chmod a+rx test/sass/functions_test.rb
chmod a+rx test/sass/css2sass_test.rb
chmod a+rx test/sass/util/subset_map_test.rb
chmod a+rx test/sass/util/multibyte_string_scanner_test.rb
chmod a+rx test/sass/cache_test.rb
chmod a+rx test/sass/importer_test.rb
chmod a+rx test/sass/extend_test.rb
chmod a+rx test/sass/conversion_test.rb
chmod a+rx test/sass/script_test.rb
chmod a+rx test/sass/util_test.rb
chmod a+rx test/sass/scss/css_test.rb
chmod a+rx test/sass/scss/scss_test.rb
chmod a+rx test/sass/scss/rx_test.rb
chmod a+rx test/sass/script_conversion_test.rb
fatal: ambiguous argument 'stable..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
rake aborted!
no such file to load -- rubygems
/root/sass/Rakefile:30:in `load'
(See full trace by running task with --trace)

**Comment by nex3** [comment]
It sounds like you don't have the stable branch checked out. It's probably worth adding a check for that to the `package` task.

It also looks like you don't have rubygems installed somehow. This is definitely necessary.

**Comment by jleclanche** [comment]
I should have master checked out, this is a fresh checkout on a new machine.
    root@li ~/sass # git branch
     \* master

Installing ruby-gem worked. Would it be worth adding a check for that in the rakefile?

**Comment by nex3** [comment]
You need to also have the stable branch present on your machine.

I think the existing error message about rubygems is reasonably clear.

**Comment by TheDutchCoder** [comment]
I have the same issue on Windows 7.
Following the instructions on the SASS homepage, it gives me an error "cannot load such file -- lib/sass".

Cloning the git went fine, installing simply fails.

**Comment by nex3** [comment]
@ReinierK Can you provide a portion of the stack trace?

**Comment by TheDutchCoder** [comment]
```
C:\Users\Reinier\sass>rake install --trace
** Invoke install (first_time)
** Invoke package (first_time)
** Invoke revision_file (first_time)
** Execute revision_file
rake aborted!
cannot load such file -- lib/sass
C:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Users/Reinier/sass/Rakefile:54:in `block in <top (required)>'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:205:in `call'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:200:in `each'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:174:in `each'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:174:in `each'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
C:/Ruby/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:94:in `each'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
C:/Ruby/lib/ruby/1.9.1/rake/application.rb:63:in `run'
C:/Ruby/bin/rake:32:in `<main>'
Tasks: TOP => install => package => revision_file
```
