### ISSUE TITLE
invalid css when using "!important"

### ISSUE THREAD

**Issue by danyball** [sass/sass#3653]
Hi,

I am using Sass 1.59.3 and it is creating invalid CSS in this situation:

1. `$gutter: map-get($grid-gutters, $bp);` --> returns null in my case (which is ok)
2. `padding: $gutter !important;` --> creates invalid css `padding: !important;`
3. `padding: $gutter;` --> ignores the statement and do not create invalid css (which is ok)

**Comment by Goodwine** [comment]
This has the same behavior as writing `.x{ y: !important }`, so the question is really whether Sass should do something for that specific case.

However, this output won't break the entire CSS stylesheet, only the line declaration in which the `!important` was used, so I believe this falls into the working-as-intended bucket. You can add validation for `null` using `@if`.
