### ISSUE TITLE
Invalid when mixing @mixin and @function with CSS custom variables

### ISSUE THREAD

**Issue by b1rdfree** [sass/sass#3656]
This is a feature that dynamically generates multiple types of styles, but my following causes @ function to not execute. I am not sure why
```
$color-list: (
    primary: (
        color-1: #000,
        color-2: #111,
        color-3: #222,
        color-4: #333,
        color-5: #444,
        color-6: #555
    )
);
@function fetch-color($type, $color) {
    @return map-get(map-get($color-list, $type), $color);
}
@mixin generate-style($type: "primary") {
    --button-wave-shadow-colors: fetch-color($type, "color-2");

    --button-backgrounds: fetch-color($type, "color-5");
    --button-border-colors: transparent;

    --button-hover-backgrounds: fetch-color($type, "color-4");
    --button-hover-border-colors: transparent;


    --button-press-backgrounds: fetch-color($type, "color-6");
    --button-press-border-colors: transparent;
}
.yakit-primarys {
    @include generate-style();
}
```
- But the actual result is that the function did not execute
![image](https://github.com/sass/sass/assets/26087140/ea2ef947-c9a7-4379-85a1-30d62c54163a)

Is this an expected normal limit specification

**Comment by Goodwine** [comment]
It is expected, you must use interpolation (`#{...}`) if you must use SassScript as values of custom declarations

e.g.
```scss
.foo {
  --button: #{fetch-color(...)}
}
```

https://sass-lang.com/documentation/style-rules/declarations/#custom-properties

_“Sass parses custom property declarations differently than other property declarations. All tokens, including those that look like SassScript, are passed through to CSS as-is. **The only exception is interpolation, which is the only way to inject dynamic values into a custom property.**”_

**Comment by b1rdfree** [comment]
> It is expected, you must use interpolation (`#{...}`) if you must use SassScript as values of custom declarations
> 
> e.g.
> 
> ```css-scss
> .foo {
>   --button: #{fetch-color(...)}
> }
> ```
> 
> https://sass-lang.com/documentation/style-rules/declarations/#custom-properties
> 
> _“Sass parses custom property declarations differently than other property declarations. All tokens, including those that look like SassScript, are passed through to CSS as-is. **The only exception is interpolation, which is the only way to inject dynamic values into a custom property.**”_

Thank you for your answer. It may be because I didn't read the document carefully and didn't pay attention to the description of CSS variables in the document
