### ISSUE TITLE
Support the relative color syntax of CSS Color 5

### ISSUE THREAD

**Issue by stof** [sass/sass#3673]
CSS Color level 5 introduces the relative color syntax which allows to compute a color based on another one: https://www.w3.org/TR/css-color-5/#relative-colors

This feature is already available in Safari 16.4+ and Chrome will [ship it soon](https://groups.google.com/a/chromium.org/g/blink-dev/c/KeKBTjKEdaU/m/NCHAo8n-AgAJ).

Currently, this syntax throws an error when using it in a Sass file with a color function known by Sass (using it in `oklab` works for now due to the lack of support for `oklab` in Sass and so not treating it like a color at all, but this would change once https://github.com/sass/sass/issues/2831 will be implemented): https://sass-lang.com/playground/#MTFhJTIwJTdCJTBBJTIwJTIwYiUzQSUyMHJnYihmcm9tJTIwbWFnZW50YSUyMGNhbGMociUyMCUyQiUyMDNkZWcpJTIwZyUyMGIpJTNCJTBBJTdE

Following the design principles of Sass, this syntax should be accepted.

**Comment by stof** [comment]
Idea for a proposal:

For all global color factory functions, add a check in their single-argument syntax. If the first list item (accounting properly for the space separate list being on the left of an optional `/` separator in case the alpha channel is provided) is an unquoted string being equal to  `from` (case insensitively), emit the function as a CSS function instead of producing a Sass color.

A future proposal might want to add full support for processing relative colors in Sass itself but I don't think this is necessary for the initial support. The common use case for relative colors in the browser is anyway to use a CSS custom variable to provide the base color, which would not be resolvable in Sass (and so would still have to output it as a CSS function). Projects wanting to do color computation with known colors in Sass will probably stick to using the `sass:color` functions instead.

**Comment by nex3** [comment]
We can start thinking about handling this properly once we're closer to done with support for Color Level 4 :sweat_smile:. For now, I wouldn't be opposed to a stop-gap measure where color function invocations beginning with `from` just return strings.

**Comment by stof** [comment]
My proposal is not dependent on support for Color Level 4 (the "future proposal" part would need it, but I'm not even sure this is something that should be proposed).

**Comment by stof** [comment]
@nex3 does this initial proposal require a formal proposal or can it go through the fast track ?

**Comment by nex3** [comment]
I think it's fine to fast-track.

**Comment by stof** [comment]
This is now implemented. I don't think this needs any dedicated documentation as it is about CSS compatibility so I'm closing this issue as completed.
