### ISSUE TITLE
Logo license question

### ISSUE THREAD

**Issue by danieltroger** [sass/sass#3681]
Here https://sass-lang.com/styleguide/brand/ it says this license applies for the sass logo: https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US and there it says

> NonCommercial — You may not use the material for [commercial purposes](https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US#).

Does that mean that I'm not allowed to use the sass logo anywhere in a commercial product, or does that just mean that I'm not allowed to profit from using the sass logo?

Context is that we're building a shopify app and will include an editor where people can customise the styling using sass, and we'd love to use the sass icon so people easily recognise that they can use sass syntax in the editor.

Another question: if the shopify app in itself were to be free, but the API required to use it is not, would that change things?

**Comment by nex3** [comment]
I think the question is, are you going to be turning a profit from the app that uses the logo? If so, we'd ask that you pay a small fee to the [Sass OpenCollective](https://opencollective.com/sass) out of that profit (we can probably have a lawyer whip up a separate licensing agreement for this). If not, you're free to use it as you see fit.

**Comment by danieltroger** [comment]
Hey @nex3, thank you for your reply. That sounds really fair.

I took it up with my team and unfortunately they think that contributing for example $10/month wouldn't be an issue but we can't take a github comment as permission for doing it and as soon as we need to get our finance guys involved on this and sign a licensing agreement it isn't worth it for a logo in the UI.

We'll probably just write "SCSS" and put a border around it instead.
