### ISSUE TITLE
Proposal @including existing styles without @mixing declaration reusing existing CSS ?

### ISSUE THREAD

**Issue by MarcWeber** [sass/sass#3683]
While thinking about SASS/SCSS and Tailwind eg @apply and components I was wondering how to get best of both worlds. And the solution was if either SCSS or CSS would allow to @include styles without having to declare them as @mixin problem would be solved.

Example:

`
.red { color: red }

.my_complicated_component {
   h1 { @include .red }
}
`

Then you could use CSS classes defined from existing frameworks.
I was very surprised to learn that native @apply was dropped:
https://www.xanthir.com/b4o00#4o00-8

The problem with Tailwind is:
Copy pasting components works most of the time.
But if you mix different styles you have to fix it anyway
to get consistent look and feel. In that case not much is saved.

And you end up with SASS again #2948 

Also if you want to build styles for shadow dom whatever.

**Comment by nex3** [comment]
This is exactly what [`@extend`](https://sass-lang.com/documentation/at-rules/extend/) is for :slightly_smiling_face:. It allows you to declare that all elements matching one style rule should be styled as though they also matched another, entirely within a single stylesheet.

Doing this by literally including the styles from another class is _not_ a good idea, and something we explicitly avoided when designing `@extend`. It subverts the cascade by only looking at styles that appear in styles rules with _one exact_ selector and not rules with other related selectors, and by reordering declarations within the stylesheet. `@extend` fixes those issues.
