### ISSUE TITLE
Implemented version for protobuf or protoc 

### ISSUE THREAD

**Issue by sveetch** [sass/sass#3685]
**Description**
I'm making research and develop to implement Sass Embedded host in Python and so i've started trying Python package for protobuf with your shipped [*.proto file](https://github.com/sass/sass/blob/main/spec/embedded_sass.proto) taken from last main version ([8b0296a](https://github.com/sass/sass/commit/8b0296ab876115be26d9e5dab02e47a811487fba)). 

So i tried to compile it to a Python module using protoc but it fails on errors:

```
$ protoc --python_out=. embedded_sass.proto 
embedded_sass.proto:183:16: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
embedded_sass.proto:354:14: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
embedded_sass.proto:679:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

**Environment**
Describe your environment:

- Plateform: Ubuntu 20.04.6 LTS
- Python version: Python 3.10.7
- protoc and related packages versions:
  libprotobuf-lite17 amd64 3.6.1.3-2ubuntu5.2
  libprotobuf17 amd64 3.6.1.3-2ubuntu5.2
  libprotoc17 amd64 3.6.1.3-2ubuntu5.2
  libprotobuf-dev amd64 3.6.1.3-2ubuntu5.2
  protobuf-compiler amd64 3.6.1.3-2ubuntu5.2

**To Reproduce**
1. Install protoc;
2. Download `embedded_sass.proto`;
3. Try to build the Python module from proto file;
4. It fails with errors.

**Expected behavior**

I should be able to build Python module from `embedded_sass.proto` , if there is some version support restrictions, it should be explicitly documented.

**Additional context**
I am very new to Protocol buffers, i don't know i may have missed an obvious information or workflow.

**Comment by sveetch** [comment]
Ok so i've switched on another machine with a more recent distribution (Ubuntu 22.04.3 LTS) which have a more recent protoc version: `libprotoc 3.12.4` and it worked.

At first it required me to use a flag argument for experimental optional fields:

```
$ protoc --python_out=. embedded_sass.proto
embedded_sass.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
```

So i added it:

```
$ protoc --experimental_allow_proto3_optional --python_out=. embedded_sass.proto
```

And it worked, i got my compiled Python module.

How could we know the compatible version of protoc library ? I've searched a little on Protocol buffers documentation but did not find a proper changelog that could have informed me about this new feature for optional fields. Also i did not found informations about this breaking change in a specification changelog.

**Comment by nex3** [comment]
It's generally not a good idea to rely on language versions (including `protoc`, which is effectively an implementation of the protocol buffer language) from OS distributions, because they tend to become out-of-date quickly. For example, the most recent protoc version is 24.3, which is 12 major versions above even the newer Ubuntu version (3.12.4 has major version 12 because protoc versions are weird).

To answer your specific question: we require a protocol buffer compiler that has explicit support for optional fields, which means `protoc` 3.15/v15 or higher.

**Comment by sveetch** [comment]
I naively thought "protoc" was the reference since it is the top result in research and it was created by Google, so without any explicit information from Sass embedded protocol, i've just took it directly as the only possible solution.

Finally, i just wished the Sass embedded protocol gave all the information keys to know how to start development. Protocol buffers is something new for me and it seems it is not so common, it may be very helpful to the protocol adoption to give those details.

Something like "We support either 'protoc>=3.15.x or a Protocol buffers implementation with 'optional field' feature" would have been very helpful.
