### ISSUE TITLE
prevent map collapsing into list

### ISSUE THREAD

**Issue by nachtfunke** [sass/sass#3694]
Hello! I have a module which contains a map of font-face settings. One font-family has multiple faces in a list:

```scss
$_family-display: (
  "family": "test",
  "faces": (
    (
      "weight": 600,
      "style": "normal",
      "src": (
          "woff2": "/",
          "woff": "/"
      )
    ), (
      "weight": 700,
      "style": "normal",
      "src": (
          "woff2": "/",
          "woff": "/"
      )
    )
  )
) !default;
````
But the other one, doesn't. It only has one font-face, a variable font:

```scss
$_font-family-paragraph:  (
  "family": "whatever",
  "faces": (
    (
      "weight": "100 900",
      "style": "normal",
      "src": (
          "woff2": "/",
          "woff": "/"
      )
    )
  )
);
```

Now I'm writing a loop that based on this configuration can create `@font-face` declarations, but I am noticing something strange, which is that the `faces` map in `$_font-family-paragraph` is collapsing to a list:

```scss
@each $family, $config in map-get(fonts.$fonts, "families") {
    @each $face in map.get($config, "faces") {
        @debug type-of($face);
    }
}
```
gives me:

```
src/scss/base/_fonts.scss:17 Debug: map
src/scss/base/_fonts.scss:17 Debug: map
src/scss/base/_fonts.scss:17 Debug: list
src/scss/base/_fonts.scss:17 Debug: list
src/scss/base/_fonts.scss:17 Debug: list
```

As soon as I add another element to `faces` in `$_font-family-paragraph`, the map remains intact.

This is a somewhat significant problem, because when building my `@font-face` declaration I would like to specifically access values by key. But in the list, I cannot easily do that. This is what I am getting instead:

```
src/scss/base/_fonts.scss:17 Debug: ("weight": 600, "style": "normal", "src": ("woff2": "/", "woff": "/"))
src/scss/base/_fonts.scss:17 Debug: ("weight": 700, "style": "normal", "src": ("woff2": "/", "woff": "/"))
src/scss/base/_fonts.scss:17 Debug: "weight" "100 900"
src/scss/base/_fonts.scss:17 Debug: "style" "normal"
src/scss/base/_fonts.scss:17 Debug: "src" ("woff2": "/", "woff": "/")
```
Why is this happening? Can I somehow prevent sass from automatically collapsing maps with a single entry into a list?

**Comment by nachtfunke** [comment]
Okay so, apparently, when I just add a little comma, like this:

```scss
$_font-family-paragraph:  (
  "family": "whatever",
  "faces": (
    (
      "weight": "100 900",
      "style": "normal",
      "src": (
          "woff2": "/",
          "woff": "/"
      )
    ),
  )
);
```

It will remain a map. Is this intentional? I am afraid that tools like prettier, over which I may not have agency at all, may just interpret it as a trailing comma and remove it.

**Comment by stof** [comment]
If you don't put a comma, the outer braces don't create a single-element list but a parenthesized expression containing a map.

See https://sass-lang.com/documentation/values/lists/ for the documentation about lists. The first section mentions how to write single-element or empty lists.

**Comment by nex3** [comment]
@stof is right: parentheses in Sass aren't list brackets, they just control expression precedence. You can define a list just as well without parentheses. If you're defining a list that's not intended to be emitted directly to CSS, I strongly recommend that you use square brackets like this:

```scss
$_font-family-paragraph:  [
  "family": "whatever",
  "faces": [
    (
      "weight": "100 900",
      "style": "normal",
      "src": (
          "woff2": "/",
          "woff": "/"
      )
    )
  ]
];
```

This way, you don't need to do anything special with trailing commas for single-element lists.

**Comment by nachtfunke** [comment]
> parentheses in Sass aren't list brackets, they just control expression precedence. You can define a list just as well without parentheses.

That is very insightful, thank you!
