### ISSUE TITLE
-moz-transform:scale(1.02); 	-webkit-transform:scale(1.02);

### ISSUE THREAD

**Issue by grigio** [sass/sass#37]
These CSS3 properties in a SCSS give this error:

Syntax error: wrong number of arguments (1 for 2) for `scale'

**Comment by chriseppstein** [comment]
Ugh.

**Comment by chriseppstein** [comment]
I guess we should rename them to scale-color() and adjust-color()?

**Comment by chriseppstein** [comment]
This was implemented back in December by the following commits:

86390d0a02b943867d5ee6b1d658bc7cd6b7604c
b55c7427a33e430bad4326fa83fa8d2b5b757c9a
317ee92da092f5c8b12343c16b4b2cefdc8445ae
