### ISSUE TITLE
The proposed ordering of importers is inconsistent for the package importer proposal

### ISSUE THREAD

**Issue by stof** [sass/sass#3701]
The section `Updated importers options` in `types` says:

> If any object in `options.importers` is exactly equal to the object `nodePackageImporter`:
> 
>    - Let `pkgImporter` be a [Node Package Importer](https://github.com/sass/sass/blob/main/proposal/package-importer.d.ts.md#node-package-importer) with an associated `entryPointURL` of `require.main.filename`.
> 
>    - Replace `nodePackageImporter` with `pkgImporter` in a copy of `options.importers`.

The `Semantics` section after that says

> Package Importers must be added to the [global importer list](https://github.com/sass/sass/blob/main/spec/modules.md#global-importer-list) immediately after any user-provided importers.

This is inconsistent as the importers option allows to put them anywhere among the user-provided importers.
Is this sentence in `semantics` meant to apply only to the new `pkgImporter` option of the legacy API ? If yes, it might make sense to move it to the section describing that option instead.

**Comment by jamesnw** [comment]
@stof The sentence from the Semantics section you highlight was accidentally left in after some changes, and will be removed with https://github.com/sass/sass/pull/3699. 

Also, thanks for catching that the order was not specified for the Legacy API. The Legacy API doesn't have a global importer list, so it will be invoked immediately before the existing importer logic. I've added that change to the above Pull request as well. Thanks!

**Comment by stof** [comment]
@jamesnw you should mark your PR as closing this issue so that Github automatically closes it once merged.
