### ISSUE TITLE
Clarification about the deprecation status in the deprecation API proposal

### ISSUE THREAD

**Issue by stof** [sass/sass#3710]
https://github.com/sass/sass/blob/main/accepted/deprecations-api.d.ts.md#formally-specifying-the-deprecations says that the deprecation status is part of the specification while versions are implementation-specific.

Shouldn't the status be implementation-specific as well as it is derived from which versions are set ? Of course, the list of available statuses is part of the spec. But dart-sass could have a deprecation becoming obsolete at the time of release 2.0 while another implementation has it as an active deprecation because it has not released its next major version yet.
AFAICT, the only deprecation that has a status mandated in the spec is `user-authored`, which must have the special status `user`.

**Comment by nex3** [comment]
The status is part of the specification _to the degree that it's actually specified_. As you note, most of the statuses are left as just `extends DeprecationStatus`, so implementations can set them however they want.

If you can think of a clearer phrasing for this, feel free to send a PR.

**Comment by stof** [comment]
btw, shouldn't most deprecations exclude `user` as a valid status ?
