### ISSUE TITLE
Signature for the dispose method of shared compilers

### ISSUE THREAD

**Issue by stof** [sass/sass#3724]
the shared-resources proposal defines a `dispose` method returning `Boolean` or `Promise<Boolean>`. However, the boolean value can only ever be `true`.
Should this be changed to `void` and `Promise<void>` instead to mark the API clearer ?

**Comment by nex3** [comment]
I think this makes sense. @jamesnw

**Comment by jgerigmeyer** [comment]
Closed in #3725
