### ISSUE TITLE
Color Spaces: Representing clamped out-of-gamut colors

### ISSUE THREAD

**Issue by nex3** [sass/sass#3737]
Per https://github.com/w3c/csswg-drafts/issues/9484, it's possible for color space conversion to produce a color that's outside the gamut of the space it's represented in _even when that space is clamped at parsed-value time_. This means that `color.to-space(color(xyz 1 1 1), lab)` represents a valid and meaningful CSS color value in the Lab color space that cannot be represented with the `lab()` syntax because its lightness is `100.12`.

To handle edge cases like this, I think we should add a special case to the color serialization spec that checks whether a non-legacy color has a channel value outside its clamped range and, if so, emits an XYZ color (which has no range gamut limitations whatsoever) that's converted to the given color space via `color-mix()`. For example, `color.to-space(color(xyz 1 1 1), lab)` would be emitted as `color-mix(in lab, color(xyz-d65 1 1 1) 100%, black)`. This is a little silly in that Sass doesn't support the native CSS `color-mix()` function, but it's the only way I know of to ensure that the colors we emit represent the same colors as Sass's notion.

@jamesnw This probably means we should also allow out-of-range lightness values for Lab/OKLab/LCH/OKLCH in the JS API and the embedded protocol as well.

**Comment by nex3** [comment]
This also raises the question for _when_ we should allow users to construct these values. It's clear per the CSS spec that `lab(110% 0 0)` should be clamped, and clear that `color.to-space(color(xyz 1 1 1), lab)` _should not_ be clamped, but what about like `color.change(lab(0% 0 0), $lightness: 110%)`? If we _don't_ allow that, what do we do with `color.change(color.to-space(color(xyz 1 1 1), lab), $a: 50%)`, since it already has an out-of-gamut lightness and that's not being explicitly changed?

@mirisuzanne I'm interested in your design thoughts here. I think I'm leaning towards allowing `color.change()` _et al_ to produce out-of-gamut colors—basically going with the design principle that we never clamp except where the CSS spec explicitly mandates clamping. But I'm not strongly convinced of that yet.

**Comment by mirisuzanne** [comment]
That's my instinct as well - let it happen, and let CSS resolve the outcome if authors don't do ggamut-mapping. But I'm not sure that I've thought through all the implications of that.

**Comment by nex3** [comment]
This issue actually also exists for other channels in [the latest spec](https://drafts.csswg.org/css-color/): in legacy RGB, all three channels are clamped at parsed-value time; and in LCH and OKLCH, the lower bound of chroma is clamped at parsed-value time. We also _currently_ clamp HSL's saturation and lightness channels and HWB's whiteness and blackness channels, but these are not specified (anymore) as being clamped.

Following the principle above that we should allow out-of-gamut colors as much as possible while only clamping where the spec explicitly mandates, we should:

* Update the `rgb()` and `rgba()` functions to clamp their inputs, but _not_ clamp conversions to RGB.
* Update the `lch()` and `oklch()` functions to clamp the lower bound of their chroma.
* Remove _all_ clamping for HSL and HWB.
* Serialize out-of-gamut legacy RGB colors as `hsl()`, since this can represent those values without being clamped at parsed-value time while also being compatible with older browsers. (I'm double-checking with @tabatkins that this will work as expected.)
* Serialize LCH and OKLCH colors with negative Chroma values using the same XYZ conversion trick we use for out-of-gamut lightness in https://github.com/sass/sass/pull/3741.
