### ISSUE TITLE
Recommended way to write warnings in alternative implementations

### ISSUE THREAD

**Issue by stof** [sass/sass#3747]
Deprecation warnings (and maybe some other warnings but I haven't checked) are mentioning a version number in which the behavior will change. For dart-sass, it makes sense to mention `Dart Sass 2.0`. However, for alternative implementations, things are a bit fuzzy.
In my opinion, no alternative implementation should ever remove a deprecated feature earlier than its removal in dart-sass (here, I'm talking about deprecated features of the Sass language, not deprecated features of the host API, unless that host API is a JS one which also has a shared spec), as most libraries will (and should) target dart-sass as their main supported compiler.
In practice, this means that a deprecated feature in scssphp would be removed in the next major version of scssphp released *after* the removal in dart-sass. But this might not be the next scssphp major version in case we make BC breaks in the PHP API in the meantime.
What would be the recommended way to report the warning ? Should we mention `Dart Sass 2.0` (or whatever other major is reported by Dart Sass), our next major version, something like `in a next major version for Scssphp` not specifying which one, both `Dart Sass 2.0` and something about our own major version ?
 
> Note that I'm using scssphp as an example here because that's the implementation I'm maintaining. But this is also relevant for any other implementation, for instance rsass by @kaj

**Comment by nex3** [comment]
I don't think it's _wholly_ unreasonable to drop deprecated features in other implementations, in cases where the compatible behavior is complex to implement and writing undeprecated code is relatively straightforward. We did this when we were first implementing Dart Sass for features like color arithmetic where the value of implementing and then tearing them out just wasn't there.

That said, I don't think the policy of "always tail Dart Sass feature removals" is unreasonable either. If you're going with that policy, I'd just say "a future major version" and leave it at that.
