### ISSUE TITLE
What does "A load path `loadpath`..." mean?

### ISSUE THREAD

**Issue by davidmurdoch** [sass/sass#3759]
https://github.com/sass/sass/blob/850c7e08129defdd3b8ceea1ef602b3a9fc7d613/js-api-doc/options.d.ts#L228

**Comment by nex3** [comment]
The `loadPath` here indicates a variable that contains a single load path as a string. That variable is referred to in the equivalent `FileImporter` [immediately afterwards](https://github.com/sass/sass/blob/850c7e08129defdd3b8ceea1ef602b3a9fc7d613/js-api-doc/options.d.ts#L230-L238).

**Comment by davidmurdoch** [comment]
Ah ok. Thanks for the reply.

So

```js
loadPaths: ["my-path"];
```

and

```js
importers: [{
  findFileUrl(url) {
    // Load paths only support relative URLs.
    if (/^[a-z]+:/i.test(url)) return null;
    return new URL(url, pathToFileURL("my-path"));
  }
}]
```

are equivalent?

**Comment by nex3** [comment]
That's right.
