### ISSUE TITLE
Sass incorrectly insists that the CSS invert() function must take a color

### ISSUE THREAD

**Issue by pcantrell** [sass/sass#3765]
This correct CSS works in Sass:

```
filter: invert(100%)
```

However, when the percentage becomes a Sass expression, like this:
```
filter: invert(#{100%})
```

…then I get this error from Sass:
```
…/ruby-3.2.2/gems/sass-3.7.4/lib/sass/script/functions.rb:552:in `assert_type': $color: "100%" is not a color (ArgumentError)
```

(My own example is more complicated than `#{100%}`, but that’s a simple reduction of the problem.)

Is Sass mistaking the call to the CSS `invert` function for a call to Sass’s color function of the same name? Or is this something else?

I think this is a bug, but in the meantime, is there a way to disable Sass’s expression checking for that one line of my stylesheet?

**Comment by nex3** [comment]
It looks like you're still using Ruby Sass. Ruby Sass has reached [end of life](https://sass-lang.com/blog/ruby-sass-is-unsupported/), and is no longer supported. Please switch to another implementation as soon as possible to ensure that you'll remain up-to-date with the latest features and CSS support.

**Comment by pcantrell** [comment]
Ah, I see. Thanks.

FYI, the “end of life” link you posted is a dead link. I think I found my way to the relevant resources with a web search, but if that’s a template response, you’ll probably want to update the template!
