### ISSUE TITLE
Make sure that an ampersand in @content is not placed before class

### ISSUE THREAD

**Issue by gdm-1718-indymeer** [sass/sass#3767]
I have a mixin that is being used for creating breakpoints and where the class `body:not(.responsive-testing)` always needs to be placed first. 

 
So the ideal structure would be: `body:not(.responsive-testing) .test-class`

But sometimes inside `@content`, there is an ampersand being used so then it will render it like this: `.test-class body:not(.responsive-testing)`

This is the code of the mixin, i'm using dart-sass 

```
@mixin tablet {
  @include susy-breakpoint($tablet-width, $susy-tablet) {
    body:not(.responsive-testing) &{
      @content;
    }
  }

  @container (min-width: #{$tablet-width}) {
    body.responsive-testing & {
      @content;
    }
  }
}
```

An example using the mixin that generates this example:

```
  @include tablet {
      flex-basis: 33%;
      .test-class & {
        flex-basis: 50%;
        background: blue;
      }
    }
```

I've created a codepen so you can check by yourself while compiling the css in the pen.

[https://codepen.io/indymeermans/pen/MWxgQvX][1]

  [1]: https://codepen.io/indymeermans/pen/MWxgQvX

**Comment by nex3** [comment]
Fundamentally, the innermost style rule (in this case, `.test-class &`) has final say about what the selector looks like. So if it says "put `.test-class` outside everything else", then that's what happens. You can avoid doing this by using Sass's [built-in selector functions](https://sass-lang.com/documentation/modules/selector/) to implement your own, more complex nesting behavior. [In this example](https://sass-lang.com/playground/#eJx9VMGOmzAUvOcrnmi6CxJGzaaVWqKV8h9VDwYeiVVjI9tks1rl3/tsbBIO21NgMjOeN7bZ7Y6TRXi23NpaCuueD5sHxKLE1mlD6ObYT6p1QivwPGalaDHf+ucSttZx439RdTWoScoCPjYAW4N2kq4G0eeeWQnLGsPbv+iwm8VFCb//lJAXxcELLI7ccFqyDstUy3tke9Kx1wa2Anqjh7g0uLPR0+kcEgD9HcQS1cmdozIEeogUGHwcSZBHsJxBlTQ0kCjKVaj7c4hy83EMusmo5HzY3KisQVyFggYpKjK8oHl3Z6FOrJkca3T3nm9Tt7EpckVFsZ5CDQrfWELyeWjkLY3X6mGUeAUyj5I0Vy+MTWOFCSK1hF0wiK4RDVsSULhLUqTKCk9i6d3ms3vhveD1FTI/QlZG/SJTaF2khtZmuFwdmCXVS1F8YnAXJnYRiI9jpHLSBt6xcjXnevcyQgee3beOO2a0dvDl48HhFis9tlo5ep/Z9111vJFIvQN4iwE7wSEfhGJvonPnGn6+7MZrAZxOYj7wa4J33/e/PB7dfYW10i6v6NyMWllxQeaoADomBTxF1jrFnDpkqQz564F14hKoR6FaOXW4pAv0nipgDbfC1rDff509Fup/jmdW+SislfQZyIolzKPfj2/Rj2ahK32iC+hvfyMnXGX9BxWNYdM=), I've implemented a `before-everything-but-body()` mixin that will nest a selector _within_ the outermost parent selector if it has a `body` tag but outside everything else.

**Comment by gdm-1718-indymeer** [comment]
@nex3  Thanks for leading me in the right direction! I'm going to try implement this inside the mixin only. Otherwise it would take me a long time to adjust it and implement @include before-everything-but-body inside every file and project.

EDIT: i figured out that its impossible to see whats inside @content; so I guess i have to adjust everything
