### ISSUE TITLE
Styling parent from child

### ISSUE THREAD

**Issue by atmanali** [sass/sass#3770]
Hello,

I'm new to using sass. I wonder if we could add css properties to parent element like we can do for child elements.

My problem is that my parent element is in a package that I don't need to compile every time. So I thought it would be easier if we dispose of a selector for parent element.

Thanks for your implication

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
