### ISSUE TITLE
Write function like map.set()

### ISSUE THREAD

**Issue by sciborrudnicki** [sass/sass#3780]
Is there any chance to have the ability to write `@function` like a `map.set()` with arbitrary argument in the middle?

```scss
map.set($map, $keys..., $key, $value)
```

**Comment by sciborrudnicki** [comment]
The next "issue" - there is no ability to `@use` specific functions(also variables) as object from module. For example.

```scss
@use (set, get, insert) from 'example' as object with ($color: red);
object.set();
```

It would be good to have one object instead of `@use` multiple times if we don't want to import module.

```scss
@use 'object/set.scss' as object-set;
@use 'object/get.scss' as object-get;

object-set.set();
object-get.get();
```

Maybe `as` should be merged.

```scss
@use 'object/set.scss' as object;
@use 'object/get.scss' as object;

object.set();
object.get();
```

I think `as` should work like objects, and be independent:

```scss
@use 'object' as one;
@use 'object' as two;

one.$name: a;

two.$name: b;

@debug one.$name; // b
```


Issue #3781 - there is a problem with `@use` when module is used in one of the files with `with`. 

`This module was already loaded, so it can't be configured using "with".`

**Comment by nex3** [comment]
> Is there any chance to have the ability to write `@function` like a `map.set()` with arbitrary argument in the middle?
> 
> ```css-scss
> map.set($map, $keys..., $key, $value)
> ```

I'm not sure what you're looking for here. `map.set()` already has this signature. What specific behavior are you looking for?

> The next "issue" - there is no ability to `@use` specific functions(also variables) as object from module. For example.

In the future, please file separate issues if you have multiple requests.

There is no such thing as an "object" in Sass. It's not JavaScript. There's also no value in loading only certain names from a module—if you want to be explicit about which names you're using, or if there's a name conflict, that's what namespaces are for.

> It would be good to have one object instead of `@use` multiple times if we don't want to import module.

If you want to load multiple definitions that are defined in different files with a single `@use`, you can create an intermediate file that `@forward`s those definitions.

> I think `as` should work like objects, and be independent:

Just saying "I think it should work this way" without any reasoning or use-cases isn't very helpful.

Again, Sass doesn't have objects. Modules are not objects. If you want something that tracks state, you should use a map or a list. Modules are the wrong abstraction level for that—they're for organizing and encapsulating members, not state.
