### ISSUE TITLE
Migration from @import to @use and @forward in a scss components library. Willing to pay a consultancy

### ISSUE THREAD

**Issue by Guebbit** [sass/sass#3781]
Hello, sorry if I misuse github tickets, but I have no idea where to go, where to find a SASS expert to talk to. I find no solutions and no one willing to answer. 
I'm willing to pay a consultancy, I have no idea how to solve this problem. 

https://stackoverflow.com/questions/77848614/replacing-import-with-use-and-forward-causing-this-module-was-already-loaded

**Comment by nex3** [comment]
I've replied on StackOverflow, so I'm going to close this out here.
