### ISSUE TITLE
Allow two underscores on index files __index.scss 

### ISSUE THREAD

**Issue by jakob-e** [sass/sass#3789]
I'm a big fan of using _index.scss to create a @​forward module bundle based on folder name.
It would be nice if was also allowed to use **_two underscores_** to make it more visible when viewed in the folder tree

````
📂 font 
  └─ 📄 _face.scss
  └─ 📄 _family.scss
  └─ 📄 _height.scss
  └─ 📄 _index.scss   ⬅️  
  └─ 📄 _scale.scss
  └─ 📄 _size.scss
  └─ 📄 _space.scss
  └─ 📄 _stack.scss
  └─ 📄 _style.scss
  └─ 📄 _weight.scss

📂 font 
  └─ 📄 __index.scss  ⬅️  
  └─ 📄 _face.scss
   ...

**Comment by jathak** [comment]
The resolution logic for dependency URLs is already quite complicated and needs to be implemented in multiple places, so adding functionality like this is more trouble to implement and maintain than it is worth.
