### ISSUE TITLE
Sass is converting var(--c,) into var(--c) which leads to wrong code

### ISSUE THREAD

**Issue by Afif13** [sass/sass#3794]
Let's consider the below CSS.

```css
html {
  background: linear-gradient(90deg,red,blue) var(--c,);
}
```

It's a valid code and the comma inside the var() is not a typo. From [the Specification](https://www.w3.org/TR/css-variables-1/#using-variables):

> Note: That is, var(--a,) is a valid function, specifying that if the --a custom property is invalid or missing, the [var()](https://www.w3.org/TR/css-variables-1/#funcdef-var) should be replaced with nothing.

But Sass seems to remove the comma making the code invalid. Here a screenshot using https://www.sassmeister.com/

![image](https://github.com/sass/sass/assets/14073250/d57f1291-a488-4d84-b98d-65d13110a0f6)

**Comment by Afif13** [comment]
Someone show me that it works fine here: https://sass-lang.com/playground/#eJwzNCxOTS7JzM9TqOZSUEhKTM5OL8ovzUuxUsjJzEtNLNJNL0pMyUzNK9EoSk3RUUjKKU3VVChLLNLQ1U3W0bTmqgUA4j8Vkg

So maybe it's a version issue and it's an old bug already fixed. If so, It would be good if someone can point me to the first version that supports this fix.

**Comment by brandonmcconnell** [comment]
I'm tagging @nex3 here as they helped me resolve another Sass issue a while back— thanks again btw!

As you mentioned, a version issue could very likely be the issue here.

**Comment by nex3** [comment]
You can always check [the changelog](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1530) to see when various changes were added to Sass. In this case, support for an empty second argument for `var()` was added in 1.53.0.

**Comment by brandonmcconnell** [comment]
Thanks, @nex3!
