### ISSUE TITLE
Suggestion: Improve documentation around CSS Layers

### ISSUE THREAD

**Issue by tillsanders** [sass/sass#3796]
I upgraded a project to make use of [CSS Layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) today, and it took me a while to figure out how to do this with SASS. I eventually found this thread (https://github.com/sass/sass/issues/3240) but I think this question will pop up more often now, while browser support improves further. As a casual user of SASS, I'm not always up to date with the latest functionality, so for people like me, it would be nice to have a hint in the documentation.

What I was trying to do (without RTFM 😉) was something like this:

```scss
@layer base {
  @use "elements";
}
```

Which, of course, resulted in an error, because @use must come before any other rules.

I would also have found this syntax intuitive:

```scss
@use "elements" layer(base);
```

The solution was this:

```scss
@use 'sass:meta';

@layer base {
  @include meta.load-css('elements');
}
```

I know that you, the team around SASS, have put a lot of thought into the new module system, and I'm not at all involved enough to understand the architecture behind all of this. I would just like to point out, that the current solution is not obvious.

Thank you!

**Comment by trusktr** [comment]
What about `@layer` and `@import` syntax? Any plans there Sass team?

```css
@import "./foo.css" layer(some-layer);
```

**Comment by nex3** [comment]
We generally recommend _against_ loading entire files in nested contexts. `meta.load-css()` does exist as an escape valve, but it's much better to structure your stylesheets so that files you `@use` define mixins rather than writing all their styles out at the top level, so you can then `@include` the mixins wherever you need:

```scss
@use 'elements';

@layer base {
  @include elements.styles;
}
```

**Comment by tillsanders** [comment]
I understand, thank you for the clarification. 

I'm not sure this approach fits simple projects. It makes sense when building libraries and frameworks, but when all I have is a bunch of files that I want to combine, it feels unnecessary to put everything into mixins that I know will only be called once. I always expected SASS to be some kind of superset of CSS, meaning that I can opt in to the additional functionality that I need, but every valid CSS file is automatically a valid SASS file. With the warnings around the @import syntax, this no longer seems to be the case (maybe it never was?), making SASS harder to understand for more casual users like myself. 

Anyway, this is probably neither the time nor the place to discuss this. I just wanted to share my perspective and hopefully give some insights into the obstacle I encountered. Maybe SASS just isn't the right tool for the job and I need to look at something less powerful.

**Comment by nex3** [comment]
All[^1] valid CSS is also valid SCSS that means the same thing. You can write a plain CSS `@import` rule and it will compile to a plain CSS `@import` rule, including something like [`@import "theme.css" layer(utilities)`](https://sass-lang.com/playground/#eJwzNHTIzC3ILypRUCrJSM1N1UsuLlZSyEmsTC3SKC3JzMksyUwt1gQAAD8Nlg==). But once you start using Sass-specific features like `@use`, they'll generally play most nicely if you combine them with other Sass features like mixins. As you pointed out, you can work around this with `meta.load-css()`, but when it comes to the approach we recommend in our documentation, we're generally going to suggest the approach that we believe scales best to projects of all sizes.

[^1]: With a few _very_ minor exceptions.

**Comment by wadder12** [comment]
Remove it.

**Comment by matthew-dean** [comment]
Removing the ability in Sass to `@import` into a nested block and then adding the ability back in through a completely different mechanism via `meta.load-css` is an interesting choice. 🤔  There are lots of uses cases other than `@layer` where the contents of an import need to be scoped / wrapped uniquely.

If `@import` / `@use` must be top-level, I agree that a `layer()` in the at-rule is intuitive.
