### ISSUE TITLE
Please remove "free Palestine" banner 

### ISSUE THREAD

**Issue by Danielg212** [sass/sass#3811]
I would like to request that the banner be removed. 

The world is facing many challenges at the moment, and starting a war over open source platforms will not help anyone.
SaaS is part of the open source community, which is non-political by nature. We share ideas and help each other without asking people about their political standpoints. 

Thank you.

**Comment by Adams360** [comment]
I've been a long-time user and admirer of Sass, and I value the work you do in creating powerful CSS tools. 
However, I was disappointed to see this unnecessary banner on your website.,

 I urge the SASS TEAM  to remove the banner ASAP and reconsider using your beloved platform for political messaging. 
 
Doing so could help maintain Sass's reputation as a respected and inclusive tool for developers worldwide.

**Comment by rkh** [comment]
This is a duplicate (https://github.com/sass/sass-site/issues/971, https://github.com/sass/sass-site/issues/970) and on the wrong repo.

I also wanted to point out that the Sass website has featured "political" messages for years.

See https://github.com/sass/sass-site/issues/461 https://github.com/sass/sass-site/issues/695 https://github.com/sass/sass-site/issues/579 https://github.com/sass/sass-site/issues/564 https://github.com/sass/sass/issues/3102 https://github.com/sass/sass/issues/2971
