### ISSUE TITLE
Thoughts: `@forward 'foo' nested` Syntax

### ISSUE THREAD

**Issue by calvinjuarez** [sass/sass#3853]
I know the team are probably all super tired of answering these requests, but I want to share my thoughts.  I'd also love links to previous discussions on the topic.

I'd love to have submodules/subnamespaces that fit the module system better.  I think an addition to the `@forward` syntax would allow for opting in.

```scss
// foo.scss
@forward 'bar';

// bar.scss
@forward 'baz' nested;
@forward 'qux' nested as rab;
@forward 'oof' nested as zab with (...);
```

Which would be used like this.
```scss
@use 'foo';

.moo {
  --mar: foo.baz.$too;
  --maz: foo.rab.$tar;

  @include foo.zab.taz(true);
}
```

This would give module authors greater control over how the final code is referenced.  You could still use the prefix style where it makes sense (e.g. `@forward 'colors' as color-*;`), but you could preserve search-ability and structure where that's a higher priority.  (Which is clearly a use case people believe is valuable, since this isn't the first issue on the topic.)

### Alternates

A different keyword, like `namespaced `, `wrapped`, or `chainable` may make more sense.

```scss
@forward 'foo' namespaced;
@forward 'bar' wrapped;
@forward 'baz' enclosed;
@forward 'qux' chainable;
@forward 'oof' chained;
@forward 'rab' tucked;
```

Or you could just make another @-rule, something like `@nest`.  This has the same imperative verb structure as `@use` and `@forward` and other @-rules, but carries the semantic connotation of having an extra name.  `@namespace` feels like it'd be a mistake to use, but there are other verbs that could be used.

```scss
@nest 'foo';
@chain 'bar';
@enclose 'baz;
@wrap 'qux';
@adopt 'oof';
@tuck 'rab';
```

All of these alternates have pros and cons.  In the end, I think `nested` as a keyword on `@forward` seems the most sensible.  In the first place, nesting is already a strong enough concept for CSS devs that it makes sense, but keeping it tied to `@forward` makes it clear that it's part of Sass's module features, so there's way less risk of confusion.

I also think that generally a word on `@forward` is probably nicer than a new @-rule, but I can see the value of separating them for maintainability, since it'd be easier to add power to `@forward` later without having to be sure that it's compatible with `nested` in addition to `as foo-*`, `with (...)`, and `show/hide foo`.

Anyway, thanks for hearing me out.  Again, I'd love any links to previous discussions.  (I've seen a few in my searching but I know that my searches haven't been comprehensive.)

<hr>

_Dot Syntax, Nested Modules, Namespaced Modules_

**Comment by nex3** [comment]
I don't think this is different _enough_ from `@forward 'foo' as foo-*` to be worth the extra machinery and the conceptual duplication. I understand that there's some value in having it be 100% clear what the name of the underlying referent is, but I think a better solution to that generally is trying to avoid deep namespaces and have people `@use` different entrypoints rather than forwarding multiple entrypoints through the same file.

**Comment by WilliamStam** [comment]
not sure if this is the same thing or not but trying to do something like

```
.parent {
  background: red;
  @import "child"
}
```

but none of the forward or use works for this :(

**Comment by jathak** [comment]
@WilliamStam Your question is about nesting _styles_, not namespaces. You can do that in the module system using `@include meta.load-css` in place of a nested `@import` (though if you need Sass variables/functions/mixins from that file, you'll also need to `@use` it, which has to be at the top of the file)

**Comment by calvinjuarez** [comment]
Thanks for the kind and reasonable response, @nex3!
