### ISSUE TITLE
SassError: At-rules may not be used within keyframe blocks (In newer versions)

### ISSUE THREAD

**Issue by nitlix** [sass/sass#3859]
My code was working fine, and I was able to use tailwind @apply in keyframes all this time with no difficulties, however in the newer versions of SASS, this is no longer possible, and upon compilation, it throws out these errors:
![image](https://github.com/sass/sass/assets/66027553/20072161-fd0f-4565-a079-14cda10685bf)

**Comment by nitlix** [comment]
This basically started happening after 1.76.0 came out 23 days ago, I've had a look at the compiled code and indeed there were a few things added which made it happen

**Comment by nex3** [comment]
I agree that this behavior is incorrect. The CSS spec [allows at-rules in `<declaration-list>` productions](https://www.w3.org/TR/css-syntax-3/#typedef-declaration-list), which is what `@keyframes` blocks contain.
