### ISSUE TITLE
"orange" is not a color for `lighten'

### ISSUE THREAD

**Issue by pyronaur** [sass/sass#386]
So orange is not a color. Neither is darkorange. I very much like the color functions. Red works, blue does as well, orange for some reason is not a color :)

I see that https://github.com/nex3/sass/blob/master/lib/sass/script/color.rb has orange, and darkorange. I wonder why my compiler is complaining...

```
compass watch:
    error sass/style.scss (Line 24: "orange" is not a color for `lighten')
overwrite css/style.css 
```

Same thing at sass --watch --compass

(might this be a Compass issue instead?)

The cause is this line:
`$base_gradient_color: desaturate(lighten(orange, 25%),10%);`

**Comment by chriseppstein** [comment]
Sure.... And apple and banana are colors too. Hell, let's add grape, plum, and pear while we're at it.

**Comment by pyronaur** [comment]
haha,
Well....actually... (from [script.rb](https://github.com/nex3/sass/blob/master/lib/sass/script/color.rb) )

```
'chocolate' => 0xd2691e,
'coral' => 0xff7f50,
 ...
'honeydew' => 0xf0fff0,
'lime' => 0x00ff00,
'olive' => 0x808000,
'olivedrab' => 0x6b8e23,
'orange' => 0xffa500,
'plum' => 0xdda0dd,

# And best of all:
'tomato' => 0xff6347,
```

**Comment by mckramer** [comment]
The `color.rb` is the master version, but you need to look at the version you are using.  I have 3.1.15 in my gems folder and the `color.rb` only contains the following colors:

``` ruby
'black'   => 0x000000,
'silver'  => 0xc0c0c0,
'gray'    => 0x808080,
'white'   => 0xffffff,
'maroon'  => 0x800000,
'red'     => 0xff0000,
'purple'  => 0x800080,
'fuchsia' => 0xff00ff,
'green'   => 0x008000,
'lime'    => 0x00ff00,
'olive'   => 0x808000,
'yellow'  => 0xffff00,
'navy'    => 0x000080,
'blue'    => 0x0000ff,
'teal'    => 0x008080,
'aqua'    => 0x00ffff
```

Hence, why orange will not work.  I did look over at [RubyGems](http://rubygems.org/gems/sass) and the newest stable version  (3.1.17) hasn't seemed to pick up the changes from this [commit](https://github.com/nex3/sass/commit/5210ee04ec1040b989baa2fa2678ff9ed3bbba22#lib/sass/script/color.rb) either.

You can use `gem install sass --pre` to get the alpha version, which has picked up the changes ([3.2.0.alpha.104](http://rubygems.org/gems/sass/versions/3.2.0.alpha.104)) at this time.

**Comment by pyronaur** [comment]
That's why....
Next time I'll have to browse the correct source.

p.s. Would be great if the colors would be considered stable anyway...
