### ISSUE TITLE
static colors are not compressed

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#387]
As mentioned in #363, if a property value is completely guaranteed to be static, we do not parse it, so colors are not compressed. It's a minor thing, but if it can be done with decent performance, it would be good to get this compression.

**Comment by ghost** [comment]
I'll +1 this.  possibly only for the compressed flag, and maybe even as an option to the compressed flag.  i know the YUI compresser does it by default when it can.

Something a co-worker pointed out to me is that if you're just counting characters for compression 'red' is actually shorter than '#f00' which I believe is the only case where the color keyword is shorter than it's 3 letter color code.

What I don't know is if it's any different for browsers reading 'red' vs reading '#f00' when it comes to actual render time, but I'd guess that that difference is probably negligible at best.

**Comment by chriseppstein** [comment]
color names have well-defined hex values in the spec. red and #f00 are identical.

**Comment by electerious** [comment]
Is it correct that `white` and `black` are currently the only colors which are compressed by sass? I'm facing the same problem as in issue https://github.com/sass/sass/issues/1095 and wondering why it works fine with `blue` and `green`.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
