### ISSUE TITLE
sass-convert doesn't want to convert my files

### ISSUE THREAD

**Issue by kud** [sass/sass#388]
Did I do something wrong?

```
$ sass-convert --recursive --from css --to scss ./css                                                                                                                                
NameError: uninitialized constant Sass::Exec::Sass::Util
```

**Comment by nex3** [comment]
I can't reproduce this. What versions of Ruby and Sass are you using?

**Comment by kud** [comment]
actionmailer (3.2.3)
actionpack (3.2.3)
activemodel (3.2.3)
activerecord (3.2.3)
activeresource (3.2.3)
activesupport (3.2.3)
addressable (2.2.8, 2.2.7)
albino (1.3.3)
arel (3.0.2)
bcrypt-ruby (3.0.1)
bigdecimal (1.1.0)
bootstrap-sass (2.0.2)
bson (1.6.2)
bson_ext (1.6.2)
builder (3.0.0)
bundler (1.1.3)
cancan (1.6.7)
capybara (1.1.2)
childprocess (0.3.2)
chunky_png (1.2.5)
classifier (1.3.3)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.3.1)
compass (0.12.1)
cucumber (1.2.0, 1.1.9)
cucumber-rails (1.3.0)
database_cleaner (0.7.2)
devise (2.1.0.rc, 2.0.4)
devise_invitable (1.0.1)
diff-lcs (1.1.3)
directory_watcher (1.4.1)
email_spec (1.2.1)
erubis (2.7.0)
execjs (1.3.2, 1.3.1, 1.3.0)
factory_girl (3.2.0)
factory_girl_rails (3.2.0)
fast-stemmer (1.0.1)
ffi (1.0.11)
fssm (0.2.9)
gherkin (2.10.0, 2.9.3)
hike (1.2.1)
i18n (0.6.0)
io-console (0.3)
jekyll (0.11.2)
journey (1.0.3)
jquery-rails (2.0.2)
json (1.7.1, 1.7.0, 1.6.6, 1.5.4)
kramdown (0.13.6, 0.13.5)
launchy (2.1.0)
libwebsocket (0.1.3)
liquid (2.3.0)
machinist (2.0)
mail (2.4.4)
maruku (0.6.0)
mime-types (1.18)
minitest (3.0.0, 2.12.1, 2.5.1)
mongo (1.6.2)
mongo_mapper (0.11.1)
mongoid (2.4.9)
mongoid-rspec (1.4.4)
multi_json (1.3.4, 1.2.0)
nokogiri (1.5.2)
oily_png (1.0.2)
orm_adapter (0.0.7)
plucky (0.5.1, 0.4.4)
polyglot (0.3.3)
posix-spawn (0.3.6)
rack (1.4.1)
rack-cache (1.2)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.3)
railties (3.2.3)
rake (0.9.2.2)
rdoc (3.12, 3.9.4)
rolify (3.1.0)
rspec (2.10.0, 2.9.0)
rspec-core (2.10.0, 2.9.0)
rspec-expectations (2.10.0, 2.9.1)
rspec-mocks (2.10.1, 2.9.0)
rspec-rails (2.10.1, 2.9.0)
rubygems-update (1.8.24)
rubyzip (0.9.8)
sass (3.1.17, 3.1.16, 3.1.15)
sass-rails (3.2.5)
selenium-webdriver (2.21.2)
simple_form (2.0.2, 2.0.1)
sprockets (2.4.2, 2.1.3, 2.1.2)
sqlite3 (1.3.6, 1.3.5)
syntax (1.0.0)
term-ansicolor (1.0.7)
thor (0.15.2, 0.14.6)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.33)
uglifier (1.2.4)
warden (1.2.0, 1.1.1)
will_paginate (3.0.3)
will_paginate_mongoid (1.0.5)
xpath (0.1.4)

and

ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.3.0] // Sass 3.1.17 (Brainy Betty)

**Comment by nex3** [comment]
I still can't reproduce this. I suspect that there's something wrong with how Sass is installed, but I'm not sure what that would be.

Closing since this doesn't seem to be a Sass bug.

**Comment by kud** [comment]
I think I've got an error in one of my css files. Because if I did it file by file, it works except for one.

**Comment by nex3** [comment]
Can you gist the CSS file with the error?

**Comment by dlindenkreuz** [comment]
I have the same issue running `sass-convert --recursive --from scss --to sass css/_sass`. Converting all single .scss files manually works though.

I'm running Sass 3.2.0.alpha.237 (Bleeding Edge) and Compass 0.13.alpha.0 (Markab).

**Comment by dlindenkreuz** [comment]
Same error also occurs when running `sass-convert --recursive --from scss --to sass images` – thus, the source files disqualify as culprits.

**Comment by dlindenkreuz** [comment]
Still the same error with sass-3.1.18 and compass-0.12.1. I'm running ruby 1.8.7 (2011-12-28 patchlevel 357) [universal-darwin11.0], by the way.

**Comment by leonardteo** [comment]
Yup I have the same issue running Ruby 1.9.2.

Here is the trace:

```
scss -w --trace *.scss
/Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/lib/sass/exec.rb:455:in `probably_dest_dir?': uninitialized constant Sass::Exec::Sass::Util (NameError)
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/lib/sass/exec.rb:372:in `watch_or_update'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/lib/sass/exec.rb:302:in `process_result'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/lib/sass/exec.rb:41:in `parse'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/lib/sass/exec.rb:21:in `parse!'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/gems/sass-3.1.18/bin/scss:8:in `<top (required)>'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/bin/scss:19:in `load'
    from /Users/leonardteo/.rvm/gems/ruby-1.9.2-p290/bin/scss:19:in `<main>'
```

**Comment by nex3** [comment]
Can now reproduce. Thanks folks.
