### ISSUE TITLE
A dash or underscore at the beginning of the mixin name fails compilation with @use operator

### ISSUE THREAD

**Issue by iminside** [sass/sass#3880]
Until today, I was comfortable using a dash at the beginning of a mixin name to indicate breakpoints.

For example
```scss
// _breakpoints.scss

// medium sized screens
@mixin md {
  //...
}

// medium-sized screens and everything smaller than them
@mixin -md {
  //...
}

// medium-sized screens and everything larger than them
@mixin md- {
  //...
}
```

Today I decided to switch from using @import to @use and found that when using @use, mixins with a dash at the beginning of the name are not imported correctly, but when using @import everything still works

Works
```scss
@import './breakpoints';

.main {
  @include -md {
    //... it works
  }
}
```

This does not work
```scss
@use './breakpoints' as *;

.main {
  @include -md {
    //... not work
  }
}
```

Compilation fails with error
```
Undefined mixin.
@include -md;
```

**Comment by nex3** [comment]
This is intentional and documented. [Leading hyphens and underscores indicate private members in the module system](https://sass-lang.com/documentation/at-rules/use/#private-members), which are not accessible outside the module that defines them.

**Comment by iminside** [comment]
@nex3 thank you!
