### ISSUE TITLE
Converting Rbga to Hsla converting 

### ISSUE THREAD

**Issue by sravani805s** [sass/sass#3881]
Hello everyone, here i have issue i.e rgba(250, 250, 250, 0.92) to converting hsla (0,0%,100%,0.92) in my local but in higher environment its converting to hsla( 0,0,100%,0.92) and its compressing % in aem environment but when i tired to change in my local hsla(0,0%,100%,0.92) to hsla(0,10%,100%,0.92) but in my local its not showing any change after i updated to different hsla values .Has anyone faced the same issue

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
