### ISSUE TITLE
[Discussion/Feature Request]: @include (mixins) in Mixed Declarations Breaking Changes

### ISSUE THREAD

**Issue by webdevnerdstuff** [sass/sass#3893]
As of sass v1.77.7 there are now warnings in the console when it comes to the [breaking changes with Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/). Since I cannot find anywhere else to open up a discussion about this I thought I'd put it here.

I think this makes sense, but not in all situations. But TBH, I might just be confused about this new change and could use more clarification than what's on the Sass site. So if I'm wrong, please correct me, or help me understand why this change is going to be required moving forward.

Where I see this being a problem (maybe more an annoyance) is that it is lumping in the use of `@include`. In a simple file that does not use includes, it's easy to see where the problem is and just as easy to fix it. TBH, I would never do something like the first Sass example on the page linked above as it seems unorganized.

But when you have a much larger and more complex setup, the warnings are not as clear and starts to make the code look less organized than we have been used to for a long time.  I assume linters/formatters are also going to need to have adjustments made as well to deal with this.

For example. You have `foo.sass` which has:
```sass
.foo
  display: block
```
You also have another file `_border.scss` which has:
```sass
@mixin border($thin-width: false)
  border-color: #fff

  @if $thin-width
    &--border
      border-width: $thin-width
```
You also have another file `_rounded.sass` which has:
```sass
@mixin rounded($radius: null)
  border-radius: $radius
```
Now if you were to include them into `foo.sass` you would now have to have it as the following:
```sass
.foo
  @include rounded(4px)

  display: block

  @include border(#000)
```
Which would compile to:
```css
.foo {
  border-color: #fff;
  border-radius: 4px;
  display: block;
}
.foo--border {
  border-width: 1px;
}
```
Normally to keep things organized (at least for me, and I'm very OCD with my styles) I would use the following, keeping my includes together and not spread out. As well as knowing that this will result in exactly what I want the end result to have styles as.
```sass
.foo
  @include border(1px)
  @include rounded(4px)

  display: block
```
Which should compile to:
```css
.foo--border {
  border-width: 1px;
}
.foo {
  border-color: #fff;
  border-radius: 4px;
  display: block;
}
```
Some mixins can be rather complex, and trying to rework this new organization can get very confusing. Even with the simple example, to more green dev's the warning is not going to make much sense to them as to what is wrong since the actual styles look correct in the file, but without having memorized what the mixins they use do, it's not as evident. Now imaging (just an example, probably not likely) you have 20 mixins included, that means having to know 20 mixins, what they do, how they work, and going back and forth many times to make sure it's ordered properly in the main file they are including them in, instead of just having all your includes grouped together... knowing that they result in styles that are 100% correct for their situation. CSS also does not have `@include` currently, and I believe uses `@apply` for mixins. But I would argue for more complex code Sass/Scss would be used over CSS still.

Also if I'm understanding this all correctly (maybe I am not?) in the example on the Sass webpage for CSS, this makes it look like our code should now add unnecessary lines of code? Which in turn would also increase file size due to unnecessary duplicate selectors which has always been a bit of a "don't do that" practice.
Old way:
```css
.example {
  color: red;
  font-weight: normal;
}
.example a {
  font-weight: bold;
}
```
New way?
```css
.example {
  color: red;
}
.example a {
  font-weight: bold;
}
.example {
  font-weight: normal;
}
```

I'm all for changes that make our lives as developers easier, but I'm struggling to see how this one will, more specifically when dealing with mixins/imports. For regular simple styling, this is not a problem for me as it sounds like what I have already been doing for a long time. Or having to go back and completely rework large sites styles that have no problems, just to shut up the console. I think that this would primarily effect projects which transpile node_modules.

What's the solution? I'm not sure exactly. Perhaps a way to opt-out so we will not get warnings/errors? Perhaps not including `@import` with this change? Other ideas? More info on what problem this actually fixes, and not just a new way to force the organization of developers individual way they organize their styles? Maybe I'm just making a mountain out of a mole hill? Also very possible.

**Comment by HanabishiRecca** [comment]
Yeah, this change makes sense, but **not** for mixins. Mixins could be quite complex with their own nested declarations inside.

I think sass could simply reorder rules automatically after mixin is merged.

**Comment by nex3** [comment]
Most of my comments in sass/dart-sass#2276 apply here as well.

Specifically, no, we can't just declare that mixins work contrary to plain CSS here. For one thing, once native CSS nesting is widely supported, we'll likely switch to emitting that directly rather than resolving it at build time, at which point we're stuck with CSS semantics no matter what. But even before then, it's important that users be able to refactor their styles to freely use or stop using mixins without risking causing a bunch of side effects like re-ordering the other properties in their style rule. This principle is known as [referential transparency](https://en.wikipedia.org/wiki/Referential_transparency), and it's a key part of making a programming language comprehensible.

**Comment by webdevnerdstuff** [comment]
@nex3 I'll check out what you wrote in the other issue. Thank you.

I don't think saying to users to "stop using mixins" is really the best way to put things tbh, even if saying this it to prepare developers for what's coming down the road. Especially until CSS makes Sass no longer needed (not holding my breath on that). Mixins are one of the (many) great things about Sass and why many users never write in CSS only anymore.

**Comment by nex3** [comment]
I'm not trying to say "stop using mixins" at all. You can (and should!) keep using mixins without seeing this deprecation warning if you wrap nested their declarations in `& {}`, or if you silence the deprecation for your app.

**Comment by querkmachine** [comment]
Whilst I'm understanding and in agreement with the change in principle (Sass behaviour should mirror CSS behaviour, makes sense!), I'm finding that the stack trace provided by the deprecation warning is not particularly helpful in locating the source of the warning, primarily because it doesn't seem to account for included mixins.

Many of the warnings I'm seeing are pointing at utility mixins that include only one or two non-nested declarations. The actual 'conflict' is happening many more includes down the line, usually a place where that mixin is included after a different mixin which _does_ have nested declarations. 

I'm not familiar with the Sass internals, but if there's some way of pointing to where the actual declaration mixing is taking place, it'd be really useful.

(Alternatively, should simple utility mixins always be wrapped in `& {…}`? Would that be the 'proper' way to handle those?)

Thanks! ✌️

**Comment by webdevnerdstuff** [comment]
> Whilst I'm understanding and in agreement with the change in principle (Sass behaviour should mirror CSS behaviour, makes sense!), I'm finding that the stack trace provided by the deprecation warning is not particularly helpful in locating the source of the warning, primarily because it doesn't seem to account for included mixins.
> 
> Many of the warnings I'm seeing are pointing at utility mixins that include only one or two non-nested declarations. The actual 'conflict' is happening many more includes down the line, usually a place where that mixin is included after a different mixin which _does_ have nested declarations.
> 
> I'm not familiar with the Sass internals, but if there's some way of pointing to where the actual declaration mixing is taking place, it'd be really useful.
>
Completely agree. The error messages could use some improvements.

**Comment by nex3** [comment]
I'm happy to work on improving the deprecation warnings. Can you provide an example on [the playground](https://sass-lang.com/playground/) of a case where it's unclear?

**Comment by querkmachine** [comment]
@nex3 [Here ya go!](https://sass-lang.com/playground/#eJx1jzEOgzAMRfecwj1ABlaycJVADFhNYhQcUVRx94a0A6rEYsn6//l/N00X6EUR6tQbyawjroJOr5LHEd4KYGDPqYXeZzRl7e3wnBLn6FrwNM0yJbsbVZQuoCMLS6IolbywBYIHhYWT2CimitdL20yCf45DHUr9Cq4cULPMmHQW8iS7/gpnzshR9IZnmZLF3pmT7NntVe4oDj47vPvSXD13QeXkB0nmZwU=)

In this example, the deprecation warning is being raised against line 12, the actual nested declarations are on lines 5–8, and the point where they come into conflict with one another is lines 16–17. 

As you might imagine, in a larger project where the mixins and declarations all live in different files, pointing to the equivalent of line 12 doesn't really help to resolve the issue. The point of conflict would probably be the most useful place to point to, though I realise that's also not the "real" issue that the deprecation is about. 

Thanks for looking into it!

**Comment by nex3** [comment]
Interesting. That seems to be an issue specific to the way the playground surfaces warnings—here's what the same warning looks like on the CLI:

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
5   │ ┌   @media print {
6   │ │     color: black !important;
7   │ │     background: white !important;
8   │ │   }
    │ └─── nested rule
... │
12  │     font-weight: bold;
    │     ^^^^^^^^^^^^^^^^^ declaration
    ╵
    test.scss 12:3  some-other-utility-mixin()
    test.scss 17:3  root stylesheet
```

Note that this indicates where the nested rule is _and_ includes a stack trace so you can tell where the mixin is being included. The JS API produces essentially the same message.

I've filed sass/sass-site#1116 to track adding stack traces to the playground, but it sounds like you were seeing this error in real code. Is the fuller warning shown above still insufficient for you, or is that not displaying in the context where you're seeing warnings?

**Comment by lateek35** [comment]
It's a bit unclear for me, just updated sass version of my project and now trying to resolve thousands of warning, but as mentioned, we've got to do it. 
I got the same issue where deprecation warning doesn't provide correct information about the line concerned, I can get over it but I'm not sure how I'm supposed to update my file. 
Like for exemple, how [this](https://sass-lang.com/playground/#eJylkcsOgjAQRff9ilnqggQ0soANv9IyY2yA1vQRi4Z/t1YWRXe6vZk5Zx5V1U0ySAVGe4WE8GAAQhskUxiO0tsGqvIaWhbzbiKUHLQaZ7C9IVLAFcJu4qG4SXSXBuoyFu8T5YtzemEAFrYwtlqtM3qgTNrA8RrA6lEiiJH3wx/iOPkna2t3FFzqOGvlCivvFFvqH5fNGYdsU6FxBuGd0ypVdlL1o0dK9jYP1hdssveBWrY8AQMXhoo=) should be rewritten ?

**Comment by HanabishiRecca** [comment]
> Like for exemple, how [this](https://sass-lang.com/playground/#eJylkcsOgjAQRff9ilnqggQ0soANv9IyY2yA1vQRi4Z/t1YWRXe6vZk5Zx5V1U0ySAVGe4WE8GAAQhskUxiO0tsGqvIaWhbzbiKUHLQaZ7C9IVLAFcJu4qG4SXSXBuoyFu8T5YtzemEAFrYwtlqtM3qgTNrA8RrA6lEiiJH3wx/iOPkna2t3FFzqOGvlCivvFFvqH5fNGYdsU6FxBuGd0ypVdlL1o0dK9jYP1hdssveBWrY8AQMXhoo=) should be rewritten ?

The dev above suggests using `&{}`. I.e. you could rewrite it [like that](https://sass-lang.com/playground/#eJylkc8OgjAMh+88RU9GDySikQNceJWN1rgAK9mfODS8uwtihIQblx7a9cu3X7Os6lRQGgx7jYTwTgAOUwWQbJBMagQqbwvIzn0o42BMYqk6QiWAdTuArQ2RBqERjp0I6VOhexSQn+PCaZt1+6EibDawznBDGwIFXPsAlluFIFtRNzsl4k+2eH8TR8GtPO6sXWrVi+JqviOEJeeySEAyDiC9c6ynl5XSdeuRJpNy2ZjPtOp9gyuT8QO8BYzA).

I dislike this way though. Not because of scss syntax, but because in this case the resulting css instead of one concise declaration originally
```css
body button {
  font-size: 16px;
  border-radius: 10px;
  border: 3px solid black;
}
```
it is being split into 3 separate blocks instead.
```css
body button {
  font-size: 16px;
}
body button {
  border-radius: 10px;
}
body button {
  border: 3px solid black;
}
```
Which is suboptimal to say the least.

**Comment by nex3** [comment]
@lateek35 

> I got the same issue where deprecation warning doesn't provide correct information about the line concerned

Can you provide more information on exactly how you were running Sass that this information isn't getting printed?

@HanabishiRecca 

> Which is suboptimal to say the least.

The unfortunate but unavoidable. CSS now very specifically mandates that the order of mixed declarations appears _in between_ nested rules, and the only way to emit that while still resolving nesting is to split out the rules. This will be true whether you use the workaround or (eventually) upgrade to a new version of Sass that supports the new CSS behavior. Our hands are tied here: we can't have different behavior than plain CSS for what is essentially the same source stylesheet.

**Comment by mbomb007** [comment]
Is there a way to have it use the new CSS output, without using `&{}` around everything? I have a lot of code like this:

```scss
@mixin base {
  @include font-size.ui;
  font-weight: bold;
}
```

And I am fine if it uses the new output order. However, I don't like needing to add `&{}` everywhere. After the new norm arrives, can we resume using syntax like the above, and just assume it uses the new order?

**Comment by nex3** [comment]
> Is there a way to have it use the new CSS output, without using `&{}` around everything?

The only way to opt into the new ordering is to use `& {}`. Part of the goal during this transition period is to make the stylesheets work the same for older and newer versions of Sass.

> After the new norm arrives, can we resume using syntax like the above, and just assume it uses the new order?

Yes, once the default changes you can remove `& {}` as long as you're willing to have your stylesheets work differently with older versions of Sass.

**Comment by mbomb007** [comment]
Sounds great. Is that planned for the next major release? I'm not familiar with the Sass release schedule.

**Comment by nex3** [comment]
That's the most likely time, yes. It depends how long it takes us to get 2.0.0 ready to release. If it ends up coming together quickly, we may delay this change a bit longer to ensure users have enough time to upgrade. Note that [the Dart Sass compatibility policy](https://github.com/sass/dart-sass?tab=readme-ov-file#compatibility-policy) means that we may choose to make this release outside of a major version cycle, since it's for CSS compatibility.

**Comment by anitagraham** [comment]
Just noting: that the `@apply` css rule, mentioned in the initial post, has been [abandoned](https://caniuse.com/?search=@apply).

**Comment by AdrianFahrbach** [comment]
Is there a way to get the old behaviour back, maybe through an option or plugin?

**Comment by johnleider** [comment]
If it helps anyone, here is an example of what we had to do to fix this in a large project: https://github.com/vuetifyjs/vuetify/commit/4fd811a6cc3af2da5ba0f9ea74e4fa7e4adeda77

**Comment by nex3** [comment]
@AdrianFahrbach A core design principle of Sass is not to provide options for core language semantics, because it makes styles intrinsically unportable across different configurations. In addition, this is not the sort of behavior where multiple options make sense—"do what CSS does" is clearly the correct option in any situation where Sass uses the same syntax as plain CSS.

**Comment by AdrianFahrbach** [comment]
> @AdrianFahrbach A core design principle of Sass is not to provide options for core language semantics, because it makes styles intrinsically unportable across different configurations. In addition, this is not the sort of behavior where multiple options make sense—"do what CSS does" is clearly the correct option in any situation where Sass uses the same syntax as plain CSS.

I see. I guess we can also easily opt out of this through compression in the bundler.
Thanks for the explanations and all the work you've put into this project. Now the whole thing makes sense to me!
