### ISSUE TITLE
JS API: Expose SourceSpan.url as a string

### ISSUE THREAD

**Issue by nex3** [sass/sass#3908]
Currently, `SourceSpan.url` is exposed as a JS `URL` object. This is required to be absolute, which means that any relative URLs passed in by the user have to be converted to absolute URLs before being returned. At present, we don't even do this conversion, so relative URLs will straight up crash. But really, the correct behavior here is to return a string which can represent a relative URL. We should make this change in Dart Sass 2.0.0.

**Comment by ntkme** [comment]
> But really, the correct behavior here is to return a string which can represent a relative URL.

At the same time from a super old change log:

> `AsyncImporter.canonicalize()` and `Importer.canonicalize()` must now return
  absolute URLs. Relative URLs are still supported, but are deprecated and will
  be removed in a future release.

Probably we shouldn't change the signature to string, and we should just completely forbidden relative urls in 2.0 with https://github.com/sass/dart-sass/issues/1999. With that the only edge case is `stdin` which will be `undefined` URL, and everything else should be absolute.

**Comment by nex3** [comment]
Interesting, so the idea is that because we only ever return spans from Sass files and those files should all have canonical source URLs, we can safely assume that they're absolute? In practice we don't currently guarantee this—it's not just an issue at the importer boundary, but the parse methods (and thus `compileString()`) also don't canonicalize their inputs. But that's solvable, and you're right that if we can it's better to expose this as a `URL`.

**Comment by ntkme** [comment]
> Interesting, so the idea is that because we only ever return spans from Sass files and those files should all have canonical source URLs, we can safely assume that they're absolute?

Exactly, with 2.0 dropping the legacy importer API which returns relative paths and dropping relative url as return value from new importer API, it should be feasible to enforce everything as absolute URL (or `undefined` for compile_string without `url`).

**Comment by nex3** [comment]
Closing in favor of https://github.com/sass/dart-sass/issues/2297.
