### ISSUE TITLE
@mixin for @keyframes issue

### ISSUE THREAD

**Issue by cyclingbyte** [sass/sass#3920]
Hello, I'm not sure how to well name the issue or if this is the right place to report, because in fact the following code gets compiled and is working:

```sass
// Mixin for slide animations
@mixin slideX($from, $to) {
  0% {
    transform: translateX($from);
  }
  100% {
    transform: translateX($to);
  }
}

// Animations using the mixins
@keyframes slide-left {
  @include slideX(0, -100%);
}

@keyframes slide-right {
  @include slideX(-100%, 0);
}

@keyframes slide-left-two {
  @include slideX(0, 100%);
}

@keyframes slide-right-two {
  @include slideX(100%, 0);
}
```

But VS Code says there is a syntax error:
![VS code } expected](https://github.com/user-attachments/assets/94cc7b66-f2af-4e10-bd2b-2f4dd87f8001)
It says `} expeced` when I hover over `0%`

**Comment by nex3** [comment]
That sounds like a problem with your VSCode plugin, not with Sass.
