### ISSUE TITLE
Is ther any testing command to get to know the areas where "Breaking Change: Mixed Declarations" Deprecations needs to handle ?

### ISSUE THREAD

**Issue by raffi-46** [sass/sass#3926]
Can I ran a command or testing code to get to know the areas where "Breaking Change: Mixed Declarations" Deprecations needs to handle ?
Talking about : https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by jathak** [comment]
The compiler should emit a warning for any mixed declarations in your code. You can make these warnings errors by passing the `--fatal-deprecation=mixed-decls` option (or the equivalent in the API). If you're looking to silence the warnings, you can use `--silence-deprecation=mixed-decls`.

**Comment by raffi-46** [comment]
Is there any to do codemod fix all areas easily instead of manually debugging in every areas coz I have **"Warning: 2231 repetitive deprecation warnings omitted."**. Or silencing 2231 areas and avoid "Mixed Declarations" in future codes it still a problem in upcoming releases of sass ? @jathak @Goodwine

**Comment by Goodwine** [comment]
I suppose a migrator can be created. If so, you may want to add a feature request at https://github.com/sass/migrator.

You can silence the feature, but the nesting behavior _will_ change at some point, and it _will_ produce a different CSS output (changes CSS ordering). The different output may, or may not be an issue depending on whether that change in CSS has an effect in your app, and it could be a different story on each instance.
