### ISSUE TITLE
Codmod option or will "Mixed Declarations" deprecations will cause Issues if we silence ?

### ISSUE THREAD

**Issue by raffi-46** [sass/sass#3928]
Is there any to do codemod fix all areas easily instead of manually debugging in every areas coz I have **"Warning: 2231 repetitive deprecation warnings omitted."**. Or silencing 2231 areas and avoid "Mixed Declarations" in future codes it still a problem in upcoming releases of sass ? @jathak @Goodwine

_Originally posted by @raffi-46 in https://github.com/sass/sass/issues/3926#issuecomment-2342609440_

**Comment by Goodwine** [comment]
closing dup

**Comment by Vinnl** [comment]
The dupe, for those looking for it: https://github.com/sass/migrator/issues/261
