### ISSUE TITLE
fatalDeprecation , verbose flag not working as expected

### ISSUE THREAD

**Issue by raffi-46** [sass/sass#3931]
Expected behaviour : fatalDeprecations must throw error on very deprecations as sass mentioned and verbose flag true will show all the deprecations instead of 5

Current behaviour : shows only 5 deprecations and fatalDeprecations not shows error

IMP! : Or Is there any way to found all the list or error to fix or stop the build to fix and fix all until finished. Because I cant able to re build everytime to find this issue  as I have 2000+ deprecations to fix https://sass-lang.com/documentation/breaking-changes/mixed-decls/

my version :
![image](https://github.com/user-attachments/assets/14c22840-88e1-46ff-b460-b9d5a1080cc0)
![image](https://github.com/user-attachments/assets/9960639b-1e64-4ac2-8f28-867886276c82)

**Comment by nex3** [comment]
Are you sure this isn't an issue with `sass-loader`? Are you able to reproduce it with the Sass API on its own? Also, what version of the `sass` package are you using?
