### ISSUE TITLE
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by dmaximyuk** [sass/sass#3939]
The situation is as follows, I used the current (at that time) version of the SASS package bundled with the Vite collector. The problem is that it constantly gives the error "Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0" in the amount of x10 WARN, and it is not clear exactly where this error occurs. I went through a bunch of possible fixes, starting from changing vite.css, ending with changing package versions. I sinned on Vite, but it didn't help, even when I rolled back the version to 5.3.0. At the same time, rolling back the package version to 1.77.0 helped. It's unclear what the problem is. Perhaps someone has encountered this, I would like to find a solution to the problem! Thanks!

Platform: linux (fedora) / macos (M2, arm, 15.0)

**Comment by nex3** [comment]
This is a better question to ask of the Vite project than of Sass. Per https://github.com/vitejs/vite/issues/7116, I believe you can pass `api: "modern"` and it will use the modern API for you, but ultimately it's responsible for how it invokes the Sass API.
