### ISSUE TITLE
What's the new equivalent for transparentize(), darken(), ... ?

### ISSUE THREAD

**Issue by johandelforge** [sass/sass#3940]
Hey there, 

Sorry but I still don't understand the docs...

What would be the new equivalent for 
`background: transparentize(#000, 0.5);`
`background: darken(grey, 10%);`

Thank you very much,
Johan

**Comment by nex3** [comment]
[The deprecation warnings](https://sass-lang.com/playground/#eJwzNHRISU0qTVcoKUrMKy5ILErNK8msStVQNjAw0FEw0DPVtOaCqkhJLMpOzdNIL0qt1FEwNFDVtAYAZXgS3Q==) provide suggestions:

```
transparentize() is deprecated. Suggestions:

color.scale($color, $alpha: -50%)
color.adjust($color, $alpha: -0.5)

More info: https://sass-lang.com/d/color-functions

darken() is deprecated. Suggestions:

color.scale($color, $lightness: -19.921875%)
color.adjust($color, $lightness: -10%)

More info: https://sass-lang.com/d/color-functions
```

**Comment by johandelforge** [comment]
> [The deprecation warnings](https://sass-lang.com/playground/#eJwzNHRISU0qTVcoKUrMKy5ILErNK8msStVQNjAw0FEw0DPVtOaCqkhJLMpOzdNIL0qt1FEwNFDVtAYAZXgS3Q==) provide suggestions:
> 
> ```
> transparentize() is deprecated. Suggestions:
> 
> color.scale($color, $alpha: -50%)
> color.adjust($color, $alpha: -0.5)
> 
> More info: https://sass-lang.com/d/color-functions
> 
> darken() is deprecated. Suggestions:
> 
> color.scale($color, $lightness: -19.921875%)
> color.adjust($color, $lightness: -10%)
> 
> More info: https://sass-lang.com/d/color-functions
> ```

Sure I have seen this documentation, but I'm getting this problem, using sass latest npm version (1.79.3) :
`Error: There is no module with the namespace "color".`

**Comment by nex3** [comment]
You need to use the `sass:color` module. Please see the documentation on [built-in modules](https://sass-lang.com/documentation/modules/), or any of the examples in https://sass-lang.com/d/color-functions.

**Comment by johandelforge** [comment]
> You need to use the `sass:color` module. Please see the documentation on [built-in modules](https://sass-lang.com/documentation/modules/), or any of the examples in https://sass-lang.com/d/color-functions.

OK got it now, thank you!
