### ISSUE TITLE
Color 4 alpha can be set as missing channel (null/none) but JS API has no way to check if alpha channel is missing or not  

### ISSUE THREAD

**Issue by ntkme** [sass/sass#3941]
Currently only `channelsOrNull` can be used to check if there is a missing channel, but `channelsOrNull` does not include alpha. All other methods convert null to 0, therefore it's impossible to check if a color's alpha channel is missing or not.

**Comment by nex3** [comment]
Hold on, [`isChannelMissing()`](https://sass-lang.com/documentation/js-api/classes/sasscolor/#isChannelMissing) supports alpha!
