### ISSUE TITLE
Importing variables from another file to use in @use...with()

### ISSUE THREAD

**Issue by NightFurySL2001** [sass/sass#3945]
I am currently trying to migrate Vuetify v2 to v3, which included changes from overriding variables globally to overriding in `@use 'vuetify' with ()`. In v2, we can use multiple @import files to import variables from other files, which allow us to classify variables based on which component it override/add to. E.g. a folder structure might look like this:
```
sass/
├── index.scss
├── feature1/
│   ├── index.scss
│   ├── component1/
│   │   ├── index.scss
│   │   ├── colours.scss
│   │   └── typography.scss
│   └── component2/
│       ├── index.scss
│       └── variables.scss
...
```
and `@import sass/index.scss` will just override everything in Vuetify v2.

However this doesn't work with `@use <module> with ()` anymore.

What is the best way to export variables from subfiles up to a central file to be used? Currently I tried the following:
```scss
// sass/feature1/component1/colours.scss
$color: red;

// sass/index.scss
@use "./feature1/component1/colours.scss" as colours;

@forward "vuetify" with (
   $color: colours.$color,
);
```
but it raise an error that `colours.$color` is undefined.

**Comment by nex3** [comment]
I can't reproduce this with the following files:

```scss
// _colours.scss
$color: red;
```

```scss
// _other.scss
$color: blue !default;

@debug $color;
```

```scss
// test.scss
@use "colours" as colours;

@forward "other" with (
   $color: colours.$color,
);
```

Running `sass test.scss` produces `_other.scss:3 Debug: red`.

Can you provide a simple git repo that contains a standalone reproduction of this issue?

**Comment by NightFurySL2001** [comment]
Actually never mind, it seem that it is a problem with my sass version.

I do want to check on the current suggested practice for using `@use <module> with ()` for configuring variables. It seems to be counterintuitive and encourage developers to concentrate variables in one single file like below, which breaks the separation of concern:

```scss
// sass/feature1/component1/colours.scss
$color: red;

// sass/feature1/component1/typography.scss
$font-family: "Segoe UI";

// sass/index.scss
@use "./feature1/component1/colours.scss" as colours;
@use "./feature1/component1/typography.scss" as typography;

@forward "vuetify" with (
    $color: colours.$color,
    $body-font-family: typography.$font-family;
);
```

The main index.scss will need to grow indefinitely with the list of variables given that `@import` is being phased out and should not be used.

**Comment by nex3** [comment]
I think it generally makes sense that all the variables you're overriding in Vuetify are overridden in the same place. This is logically similar to calling an `initialize()` function on a framework and passing in the options for that framework.

**Comment by NightFurySL2001** [comment]
Given that there are almost 1k+ variables that can be configured in Vuetify, an index.scss with 1k+ line sounds like a nightmare to maintain. It would be better if at least nesting `@use` or `@forward` within `@use with` is allowed, maybe like below?
```
@use 'vuetify' with {
	@use './colors.scss as *;
	@forward './typography.scss as *;
};
```
