### ISSUE TITLE
There is no module with the namespace "color" when using the function sass.compileString(

### ISSUE THREAD

**Issue by GordonCode25** [sass/sass#3949]
Hi all, is this a bug or did I miss something?

I'm using sass@1.79.3 with node.js and I keep getting the error There is no module with the namespace "color" when using the function sass.compileString(.... Is there something different I need to do to get this to work with compileString or compileStringAsync?

```
@use "sass:color";
$color--blue:#00a8cb;
$color--light-blue:color.adjust($color--blue, $lightness:30%);
```

**Comment by GordonCode25** [comment]
It's confusing, but it looks like this should be in dart-sass.

**Comment by johandelforge** [comment]
@GordonCode25 
I'm getting the exact same problem.
How have you solved it?
Thank you.
Johan

**Comment by nex3** [comment]
@joSFD Does your stylesheet contain `@use "sass:color"`?

**Comment by GordonCode25** [comment]
@joSFD  I opened a dart-sass case. But then in testing it worked for some reason. Not sure why it failed before. Possibly saved the wrong file.

https://github.com/sass/dart-sass/issues/2364

**Comment by johandelforge** [comment]
> @joSFD Does your stylesheet contain `@use "sass:color"`?

Yes I had this line on top of everything.

Now the problem is gone.  

@GordonCode25 :

I have noticed that the error  `There is no module with the namespace "color"` shows when you are still using old stuff like transparentize().  When you fix those problems, it recognize the module color, even it was always there.

**Comment by nex3** [comment]
> I have noticed that the error There is no module with the namespace "color" shows when you are still using old stuff like transparentize(). When you fix those problems, it recognize the module color, even it was always there.

Can you reproduce this in [the Sass playground](https://sass-lang.com/playground)?

**Comment by johandelforge** [comment]
> > I have noticed that the error There is no module with the namespace "color" shows when you are still using old stuff like transparentize(). When you fix those problems, it recognize the module color, even it was always there.
> 
> Can you reproduce this in [the Sass playground](https://sass-lang.com/playground)?

I could not reproduce it in the playground. Maybe my conclusion was wrong... or tight to my gulp setup.  If I can exactly reproduce the problem I will let you know.
