### ISSUE TITLE
Color 4 missing channel is not preserved across compiler and host

### ISSUE THREAD

**Issue by ntkme** [sass/sass#3950]
- [x] Spec (https://github.com/sass/sass/pull/3951)
- [x] [Tests](https://github.com/sass/sass-spec/issues/2022) (https://github.com/sass/sass-spec/pull/2023)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/2365) (https://github.com/sass/dart-sass/pull/2366)
- [x] [Embedded Host](https://github.com/sass/embedded-host-node/issues/335) (https://github.com/sass/embedded-host-node/pull/336)

---

``` js
const { compileString, SassColor } = require('sass-embedded');

const input = new SassColor({red: null, green: 0, blue: 0, alpha: null, space: "rgb"});

let output;
compileString('a {b: out(in()) }', {
  functions: {
    'in()': () => input,
    'out($value)': (args) => (output = args[0])
  }
})

console.log(input.channelsOrNull.toArray()) // [ null, 0, 0 ]
console.log(output.channelsOrNull.toArray()) // expect [ null, 0, 0 ], but actual is [ 0, 0, 0 ]
```

In the example above, the output is `[ null, 0, 0 ]` on `sass`, but `[ 0, 0, 0 ]` on `sass-embedded`. This is because protobuf does not distinguish set or not set for number type by default. If not set, the number type will default to value 0, and thus cause the "missing channel" to be lost.

This will break the case of interpolating colors in the same space where `0` and `none` have different meaning: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#interpolation_with_missing_components

**Comment by ntkme** [comment]
https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md

Looks like we need to make channels `optional` in the protobuf definition, and also change the protofier to detect the presence.

**Comment by nex3** [comment]
kid pix voice oh no

**Comment by ntkme** [comment]
Another edge case I found is `NaN`, `infinity`, and `-infinity` channel values, but I'm not sure what the behavior should be.

For most part, users won't intentionally create colors with these special values, however, they can be created via `interpolate`. E.g. `NaN` can be created by interpolating two colors that both have `alpha = 0`.

High level programming language with abstracted number type system supporting these special values usually consider them as special float or double type. However, in low level programming language like C we don't have these values.

Due to this inconsistency, protobuf simply does not allow serialize `NaN`, `infinity`, and `-infinity` as double.

**Comment by ntkme** [comment]
Related: https://github.com/w3c/csswg-drafts/issues/8629

**Comment by ntkme** [comment]
The discussion from w3c issue actually brings another rabbit hole here - that `calc()` can take `NaN`, `infinity`, and `-infinity`. - So maybe we need to make a bigger change to make it work in general:

1. Add protobuf type `Double` that is `oneof`: native `double`, enum `NaN`, enum `infinity`, or enum `-infinity`.
2. Use `Double` to replace `double` as type of value field inside `Number`.
3. Use `optional Double` instead of `optional double` as type for color channel.

**Comment by nex3** [comment]
> High level programming language with abstracted number type system supporting these special values usually consider them as special float or double type. However, in low level programming language like C we don't have these values.

I don't think this is accurate. `NaN`, the infinities, and signed zeros are all part of the IEEE 754 floating point specification, which these days is usually implemented at a hardware level. You can [check yourself](https://codapi.org/embed/?sandbox=gcc&code=data%3A%3Bbase64%2CU87MS84pTUlVsCkuScnM18uw4%2BLKzCtRyE3MzNPQVKjmUlAoKMrMK0nTUFJNi8lT0lEw0DPQN9Az0LTGlDLELaWLLFeUWlJalKdgYM1VCwA%3D) in the C playground.

I don't see any indication in the protobuf documentation that these values aren't supported. The serialization for doubles is just a fixed-length 64-bit field, and there are bit patterns that unambiguously represent each of these.

**Comment by ntkme** [comment]
Looks like I misread the protobuf doc - it says when serializing proto object to JSON, NaN and infinity are not as numeric values, and will instead be encoded as string.
