### ISSUE TITLE
0 and 10px are incompatible

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [sass/sass#3959]
This is a pretty minor thing, but our team is trying out Stylelint, and by default it transforms `0px` into `0`. Running the autofix broke our Sass compilation, with errors like this:

![image](https://github.com/user-attachments/assets/cf6f91c0-7414-49c0-a429-8b1f24e4559e)

I think I'll just disable the rule in our project, since it's not like it's particularly important to us to remove the units from zero values.

But I feel like ideally, Sass should be able to process in its calculations that zero is nothing and, as such, it should disappear without complaints in any addition/substraction context.

**Comment by nex3** [comment]
Sass follows the CSS spec when resolving calculations. [Plain CSS doesn't allow `calc(5px + 0)`](https://codepen.io/nex3/pen/xxvRdvW), so Sass doesn't either.
