### ISSUE TITLE
"--cache false" does not disable the cache

### ISSUE THREAD

**Issue by thany** [sass/sass#396]
Regardless of why I need to disable the cache, the commandline argument "--cache false" doesn't disable it, even though the documentation suggests that putting ":cache" to false disables the cache. Instead, the cache directory is now literally called "false". This very funny of course, but it seems that the --cache argument sets the cache directory, so what argument disables it?

**Comment by chriseppstein** [comment]
I think the command line parlance for disabling a feature would be `--no-cache`

**Comment by thany** [comment]
Ah. You are right, --no-cache disables the cache.

Now for the reason: in a development environment my policy is to disable as much of all the cacheing mechanisms as possible, because no matter what, you always want the latest and greatest of everything and everyone. Sort of :)

But I'm happy to know that this is not actually a bug.

Now, where is this specified in the documentation? I searched for the word "cache" and nowhere did I find "--no-cache"... Just sayin'

**Comment by chriseppstein** [comment]
The command line documentation is `sass -h`. 

Regarding your dev concern, I would like to dissuade you from this. The cache is a development feature, if you have caching issues, that is a bug.

Chris

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by thany** [comment]
Also the cache pollutes the project directory. The cache has everything to do with the project directory, but this makes it harder to maintain the project in a source control. Yes excluding the directory can be done, but is just another step to take, and I'm trying to keep things simple and clear for me and my collegues. Also, a project can no longer be "deployed" to another server by copypasting the project directory - everytime the cache folder has be excluded manually.

Yes I know the cache location can be set as well. But that is also not desirable, because this would lead me to "invent" a common cache folder, and the caches from all projects would then start to compete with each other.
