### ISSUE TITLE
sass slow to start with `--watch` and lots of node modules

### ISSUE THREAD

**Issue by vimalloc** [sass/sass#3962]
Hi!

I was seeing that starting sass with the `--watch` option took a very long time before the initial css was compiled, which was causing some friction on our development environments (this is happening with both the js version and the dart version).

Eventually I realized that if I removed `--load-path=node_modules`, and made it more explicit such as `--load-path=node_modules/react-day-picker` then it started significantly faster. This solved the problem, but it does make it harder to parse imports in some situations. For example, with react-day-picker, due to their file structure, the import went from looking like `@import 'react-day-picker/dist/style';` to `@import 'dist/style';`, which is less clear. I also am worried about what would happen if there were two different packages that had conflicting directory structures and how they could be distinguished.

We are hoping to migrate over to `@use` in the near-ish future, which I think will help a bit as we could do something like this: `@use 'dist/style' as react_day_picker`. But even when we make that change, I think there is still the concern of conflicting directory structures causing problems, and it just doesn't feel as clean to me.

Is there a way to fix this that I am missing? If not, I'm not sure how the best way to resolve this would be. It would be nice if we could mark some load paths as not to be watched even when `--watch` is present. Maybe something like `--ignore-watch=node_modules`. Or another option might be to have a way to alias load paths, something like `--load-path=node_modules/react-day-picker:day-picker` and `@import 'day-picker/dist/style'` or something along those lines.

Thanks for all the work you do!

Edit: I did just try out the node package importer, and at a quick glance I think that might fix the issue I'm seeing. Will report back after doing more testing!

**Comment by nex3** [comment]
There's not much we can do about watching performance—we rely entirely on external libraries for that. But yes, we do strongly recommend the use of the [Node.js package importer](https://sass-lang.com/documentation/at-rules/use/#node-js-package-importer) for loading files from `node_modules`, and it will avoid watching the directory.
