### ISSUE TITLE
Forwarding globals/deep defaults for theming?

### ISSUE THREAD

**Issue by mrginglymus** [sass/sass#3964]
Hi! I've seen a number of issues around this are, but none that quite describe the situation I find myself in.

I am an author of component library that uses sass for building styles, and css modules for encapsulation and type safety of classes.

So, I may have a button:

```tsx
import classes from './styles.modules.scss';

export default () => <button className={classes.root} />
```

In the compilation and distribution process, `styles.modules.scss` is passed on exactly as is to the user, and left to their bundler to handle [^1].

Whilst css variables are a very poweful way of applying theming, I would rather avoid run-time theming if possible; in the use case I am dealing with the theme will be fixed at compile time.

Given that the machinery of styling is completely transparent to our users - they just import components and the stylesheets get conveniently pulled along with them - the standard approach of a single sass file with variables imported before library files won't work.

I have found I can achieve _some_ of what I want by doing something like this:

```scss
$button-background-color: red !default;

.root {
  background-color: $button-background-color;
}
```

and in a (e.g.) vite config:
```ts
css: {
  preprocessorOptions: {
    scss: {
      api: "modern-compiler",
      additionalData: `$button-background-color: blue;\n`
    }
  }
}
```

This works well enough, as the variables is declared in the directly imported file. However, where I have situations like this:

```scss
// _variables.scss
$button-background-color: red !default;

// styles.module.scss
@use "./variables";

.root {
  background-color: variables.$button-background-color;
}
```

it does _not_ work, as the global added by the preprocessor options is not forwarded on to the imported `variables` file.

Even something like `@use ... with ()` won't work (or at least, won't be scalable) as the number of imports between the originally loaded file and the file declaring the variable to be overriden might be a fair few, not to mention the number of variables.

## Things I've considered:

1. Writing a custom loader to inject variables into every loaded file
This is a bit of a faff, especially as the variables may be loaded via an import which means sass will complain about importing the same modules multiple times
2. Using a custom function to set variables, instead of `!default`.
`$button-background-color: get-theme-var(button-background-color, red);`
And then shipping that to our users - also a faff
3. Requesting `@use ... with *`
as a counterpoint to `@use ... as *` (import and apply all vars as globals), `@use with *` would import and apply all current globals to the import. 

Have I missed anything obvious? Do you have any suggestions?

Thanks!

[^1]: I'm well aware of the risks surrounding shipping css modules, so we do also ship a fully compiled version which just imports plain css. However, for the purposes of theming, we also ship raw scss modules.

**Comment by mrginglymus** [comment]
The most elegant workaround I have at the moment is, in files where themable variables are consumed to add a 

```
@use "my-namespace:theme" as *;
```

and then provide a custom loader to inject variables. It's not ideal, but it's the least ugly so far.

It has the disadvantage of requiring a loader to handle theming, even if you aren't applying it.

**Comment by nex3** [comment]
Depending on how exactly the `additionalData` option works, you might be able to do:

```js
css: {
  preprocessorOptions: {
    scss: {
      api: "modern-compiler",
      additionalData: `@use "pkg:your_package/variables" as _unused with ($button-background-color: blue);\n`
    }
  }
}
```

As long as `additionalData` is only prepended to _entrypoint stylesheets_ and not to partials, this will initialize your package's variables module with the chosen overrides. Sass modules are only ever loaded once per compilation, so this will mean that when `styles.module.scss` runs `@use "./variables"` it'll load the version that already has the configuration.
