### ISSUE TITLE
Deleting a directory while watching

### ISSUE THREAD

**Issue by thany** [sass/sass#397]
While watching a directory, deleting a subdirectory (which is also watched) causes the watcher to exit with an error.
Say I've got this directory structure:

```
d:\project\includes\css\
d:\project\includes\css\test\
d:\project\includes\sass\
d:\project\includes\sass\default.scss
d:\project\includes\sass\test\
d:\project\includes\sass\test\print.scss
```

Using this command started in d:\project\ :

```
sass --watch includes/sass:includes/css
```

That neatly produces the expected css files. But now delete the directory d:\project\includes\sass\test\ :

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
  overwrite includes/css/default.css
  overwrite includes/css/test/print.css
>>> Deleted template detected: d:/project/includes/sass/test/print.scss
Errno::ENOENT: No such file or directory - includes/sass/test/print.scss
  Use --trace for backtrace.
```

The error is correct, but it shouldn't be an error. Sass even detects it, but still slips and spews it out as an error...

**Comment by the-teacher** [comment]
+1
I agree.

When I delete file I have same problem. CoffeeScript watcher works fine, but Sass watcher drop down and broke my Cake file watcher task.

**Comment by nex3** [comment]
I believe this has since been fixed by changes in `guard/listen`. Feel free to re-open if you can still reproduce this.

**Comment by rasco** [comment]
I have the same issue with guard (1.3.2), listen (0.4.7) and sass (3.2.1).
It happens on saving when I remote edit a file (over SSH).
