### ISSUE TITLE
@use rule adaptability is not adaptable about integrating sass/sass-loader/sass-resources-loader for vue scss scoped style in SFC vue file?

### ISSUE THREAD

**Issue by coocoonancy** [sass/sass#3975]
error: @use rules must be written before any other rules.
@use '@/assets/styles/fonts/fonts' as *;

**Comment by coocoonancy** [comment]
A.vue file has the below code: <style lang="scss" scoped>
@use '@/assets/styles/fonts/fonts' as *;.digital-font {
  @include digital-font;
  font-family: sans-serif; // Fallback font
}</style>

**Comment by coocoonancy** [comment]
@/assets/styles/fonts/fonts has the below code: @font-face {
  font-family: 'DigitalNumbers-Regular';
  src: url('@/assets/styles/fonts/DigitalNumbers-Regular.ttf')
    format('truetype');
}
@mixin digital-font {
  font-family: 'DigitalNumbers-Regular', sans-serif;
}

**Comment by coocoonancy** [comment]
and then webpack.config.js has the config code:       {
        test: /\.scss$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 2
            }
          },
          'sass-loader',
          'postcss-loader',
          {
            loader: 'sass-resources-loader',
            options: {
              resources: './src/assets/styles/common.scss'
            }
          }
        ]
      }

**Comment by coocoonancy** [comment]
and common.scss has the config code: @use 'var.scss' as *;
@use 'sass:color' as color;

**Comment by coocoonancy** [comment]
and main.js has the code: import '@/assets/styles/common.scss';
finally i run pnpm run build it shows the above error: 
@use rules must be written before any other rules.
@use '@/assets/styles/fonts/fonts' as *;

is so difficult to migrate on a vue project which no matter  is building by vue-cli or webpack for the the latest sass? and there is no something example for reference.

**Comment by nex3** [comment]
Please use the edit button rather than spamming an issue request with many different messages. Also, consider using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for code examples.

If you're struggling with Vue-specific setup, you're going to have more luck seeking support from Vue's support channels.
