### ISSUE TITLE
Feature: option to force style on imports

### ISSUE THREAD

**Issue by TheDutchCoder** [sass/sass#398]
Maybe I'm the only one finding this worth mentioning (in that case, ignore ;-)), but it bothers me that the resulting css file can't maintain styling on imported files.

What I mean is that I always import some biolerplate stuff that is generally one-line CSS rules, for readability (you barely change stuff in that part), but I always expand my other styles for readability and structure. In this case, I sometimes wish I could do something like:

@import 'sass/boilerplate' --compact (or something along those line) so that the formatting from that partial is maintained up to a certain output style 'level' when actually converting the file. A suggestion for the parameter could be:

--nested (imported file will always be nested, unless --expanded/--compact/--compressed is used)
--expanded (imported file will always be expanded, unless --compact/--compressed is used)
--compact (imported file will always be compact, unless --compressed is used)
--compressed (imported file will always be compressed).

So in my scss file I can import boilerplate with the --compact parameter, then convert my scss file with the '--style expanded', but my outputted css file will still have the boilerplate part compacted, with the rest of the file expanded.

Just a thought.

**Comment by chriseppstein** [comment]
Why do you want this feature?

**Comment by Anahkiasen** [comment]
Well I guess the main point is, if someone crawls through your stylesheet they can easily skip all library-related styles (by making it compressed or something) and focus on the actual styles. Granted that's the only use case I can find and not one I've encountered.

**Comment by webegguk** [comment]
I am developing now and have googled this feature, finding this comment thread so I think the answer is yes!
I am converting a site I just built into SASS and split my boilerplate reset and media queries up into imports. It would help if I could compress just the reset and media query stuff so I can easily see the css in source that I am actively developing to check as I go without having to scroll through all the reset stuff to see it every time.

**Comment by TheDutchCoder** [comment]
Sorry if I wasn't clear enough, but I think I kind of explained why I wanted this feature ;-) webegguk gets the point, it's mainly because a lot of my imported styles are kind of in-the-way when checking the resulting css file, especially when converted with expanded syntax (there's no need to expand normalizr for example, or any other 'resetting' styles for that matter.

It's not a necessity at all, more a 'nice-to-have', but I never blindly follow SASS's output and I always double-check the end-result manually, so that's why skipping over those imported lines is getting in the way a little.

**Comment by chriseppstein** [comment]
Thank you for explaining. I understand your use case, but I think it introduces more complexity than is justified by the benefit.

**Comment by khawarizmus** [comment]
can you please reconsider this feature i find it very useful
