### ISSUE TITLE
CSS round() throws an error in SCSS

### ISSUE THREAD

**Issue by jcubic** [sass/sass#3980]
[round() CSS function](https://developer.mozilla.org/en-US/docs/Web/CSS/round) is in baseline (all major browsers).

But in SCSS it throws an error:

> Error: $number: var(--number) is not a number.

See demo: https://codepen.io/jcubic/pen/NWQexwe

The problem is that someone use my CSS library from NPM in his SCSS project.

I also asked on StackOverflow:
> [How to use CSS round() in SCSS, that also have round?](https://stackoverflow.com/q/79175383/387194)

**Comment by jathak** [comment]
What version of Sass are you using? This compiles fine in the latest version of Dart Sass and the [Sass playground](https://sass-lang.com/playground/#eJwzNLQqys8vUajmUgACXd280tyk1CIrBUMDa65arqT8lEqoVEFiSkpmXrqVQlF+aV6KRllikQZMtaYmUC0AA2UVrA==)

**Comment by MrSuddenJoy** [comment]
@jathak this is not isolated case as this happens to me also.

**Comment by jcubic** [comment]
@MrSuddenJoy can you provide more information about your use case? In my case, it was reported by a user of my library. Someone on StackOverflow said that Sass Dart support round in CSS. Maybe you use ruby Sass, not sure if it's also up-to-date with dart version.

**Comment by nex3** [comment]
Ruby Sass was end-of-lifed [more than five years ago](https://sass-lang.com/blog/ruby-sass-is-unsupported/), and *certainly* doesn't support plain-CSS round (and never will).

**Comment by MrSuddenJoy** [comment]
> (and never will)

@nex3 if its EOL'ed than Im sure.
