### ISSUE TITLE
Use case for @import

### ISSUE THREAD

**Issue by raythurnvoid** [sass/sass#3982]
Hello i've been using `@import` to import some css inside a `@layer`, this is very useful to import css from libraries while making it easily overridible.

Here's an example
```css
@layer material-components {
  @import '@material/textfield/styles.scss`
}

// in the app.scss
@layer my-components, material-components;
```

I'm opening this ticket because https://github.com/sass/sass/issues/3513 is locked, feel free to close it, but be advised that if you remove `@import` there will be no alternative for this specific behavior.

**Comment by jathak** [comment]
While `@import` is deprecated, you can instead use `@include meta.load-css("path")` nest CSS from another file. If you need access to Sass members (variables, functions, mixins), then you'll need to `@use` the file at the top level.

**Comment by Lionad-Morotar** [comment]
a case of tailwindcss

```sass
@use "sass:meta";

@layer app-base {
  @include meta.load-css("tailwindcss/base");
}
@layer app-cmpts {
  @include meta.load-css("tailwindcss/components");
}
@layer app-utils {
  @include meta.load-css("tailwindcss/utilities");
}
```
