### ISSUE TITLE
Stop supporting terrorists and remove "Free Palestine" from your website

### ISSUE THREAD

**Issue by zivchen** [sass/sass#3984]
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website
Stop supporting terrorists and remove "Free Palestine" from your website

**Comment by kaj** [comment]
Protesting genocide is not supporting terrorists.  Writing the same thing eight times don't make you right.
