### ISSUE TITLE
Document reuse in the context of @use and @forward

### ISSUE THREAD

**Issue by FranceBaril** [sass/sass#3987]
Please document how to this use case within the sass sandbox with the new @use and @forward:

brand-a.scss imports:
  colors-a.scss
  layout.scss // uses colors defined in colors-a
  
brand-b.scss imports:
  colors-b.scss
  layout.scss // uses colors defined in colors-b
  
The disappearance of @import and its global variables prevents the reuse of layout.scss. The .scss now requires layout-a.scss that @use colors.a and an identical layout-b.scss that @use colors-b.

I can create a process in another language that will automate the creation of layout-a.scss and layout-b.scss from layout-*.custom. However, it defeats the arguments for performance. The performance issue is delegated to another layer and adds a new level of complexity to the outer processes. Now I have to add proprietary code to transform .custom to .scss and then be processed by sass. I also have to train the whole team to use .custom. 

Maybe I am just blind here and stuck in my old paradigm, but as much as I applaud the ability to create namespaces, I see a case for cohabitation here. Or maybe there is a way to address this and it just needs to be documented?

**Comment by nex3** [comment]
I would consider it actively an anti-pattern to have `layout.scss` refer to totally different variable definitions that depend on *the context in which `layout.scss` is loaded*. This is directly contrary to [the principle of locality](https://github.com/sass/sass/blob/main/accepted/module-system.md#high-level) which was a core design goal for the module system.

If your `colors-a.scss` and `colors-b.scss` files are intended specifically to define variables that customize `layout.scss`, I'd make that explicit:

```scss
// colors-a.scss
@use "layout" with (
  $text: black,
  $background: white,
  // ...
);
```

Remember that `@use` only ever loads a file once, so you can still write

```scss
// brand.scss
@use "colors-a";
@use "layout";
```

and it will load the `layout.scss` module with the configuration applied by `colors-a`.

**Comment by FranceBaril** [comment]
Ok, my bad, I simplified my use case too much. Let me expand the example to show a n to n relationship where many component definitions use many variable definitions:

brand-a.scss imports:
-   colors-a.scss
-   fonts-a.scss
-   layout.scss // uses colors defined above
-   cards.scss // uses colors and fonts defined above
-   headings.scss // uses colors and fonts defined above
-   tables.scss // uses colors and fonts defined above

brand-b.scss imports:
-   colors-b.scss
-   fonts-b.scss
-   layout.scss // uses colors defined above
-   cards.scss // uses colors and fonts defined above
-   headings.scss // uses colors and fonts defined above
-   tables.scss // uses colors and fonts defined above

**Comment by nex3** [comment]
Try something like this:

```scss
// _colors.scss
$text: null !default;
$background: null !default;
```

```scss
// _fonts.scss
$prose: null !default;
$code: null !default;
```

```scss
// _colors-a.scss
@use "colors" with (
  $text: black,
  $background: white
);
```

```scss
// _fonts-a.scss
@use "fonts" with (
  $prose: Arial,
  $code: Consolas,
);
```

```scss
// _layout.scss
@use "colors";
@use "fonts";
```

```scss
// brand.scss
@use "colors-a";
@use "fonts-a";
@use "layout";
// ...
```

Here, you're using the `_colors.scss` and `_fonts.scss` to declare the variables of the given types, without actually giving them values (you could also give them sensible default values if you have a notion of a "default theme"). Each specific `_colors-a.scss`-style theme file then configures these, and other files use them with the assumption that their theme has been configured.

Another solution would be to avoid using top-level variables for this at all and just pass maps to mixins:

```scss
// _colors-a.scss
$theme: (
  "text": black,
  "background": white,
);
```

```scss
// _layout.scss
@use "sass:map";

@mixin layout($colors, $fonts) {
  body {
    color: map.get($colors, "text");
  }
}
```

```scss
// brand.scss
@use "colors-a";
@use "fonts-a";
@use "layout";

@include layout(colors-a.$theme, fonts-a.$theme);
```

This is somewhat more verbose, but ultimately gives you the most control over exactly what happens (and is most directly analogous to other programming languages which may make it easier to reason about).

**Comment by FranceBaril** [comment]
I'll play with it but it makes total sense at 1st glance.

Thanks!
