### ISSUE TITLE
Proposal feedback: Indented Syntax Improvements

### ISSUE THREAD

**Issue by wkillerud** [sass/sass#3991]
Hello! I couldn't find an issue template or examples of other RFC feedback issues at first glance. Hope this works OK for you 😄 

Related to [this proposal](https://github.com/sass/sass/blob/main/proposal/indented-syntax-improvements.md) and [blog post](https://sass-lang.com/blog/).

SCSS in Sass will complicate things for language servers, and I wonder if the added complexity is worth it.

Today in the language server we can use the file extension or language ID of the document to determine which syntax is in use.
Were Sass to allow SCSS syntax inside of intented documents, language servers will have to adapt features to
figure out which regions of the document have which syntax.

For instance:

- [Diagnostics to highlight inconsistent indentation](https://github.com/wkillerud/some-sass/blob/588e19ee62477c2d02af59d8ec91c5aa4f67f1a4/packages/language-services/src/features/do-diagnostics.ts#L29) would need to know whether a line is part of an SCSS block to not report false positives.
- Code actions like [extract function](https://github.com/wkillerud/some-sass/blob/588e19ee62477c2d02af59d8ec91c5aa4f67f1a4/packages/language-services/src/features/code-actions.ts#L70) would need to know whether the target area is inside an SCSS block to have correct syntax.
- Code completions/IntelliSense would also need awareness of the current syntax to provide correct snippets in some cases (with/without semicolon, whether or not linebreaks are allowed).

Language servers can adapt of course, but I wonder if the added complexity is worth it to inline SCSS code instead of using a separate file? From the proposal this seems like an alternative to the suggested changes to line breaks, not strictly required.

**Comment by HamptonMakes** [comment]
@wkillerud that's a really good point. I think the proposal itself is overall really well thought out for the multiline-in-Sass, but maybe we can break the SCSS-in-Sass into a second proposal for separate discussion?

**Comment by nex3** [comment]
Thanks for the feedback! In practice, the furthest-along Language Server Protocol implementation for Sass is https://github.com/sass/dart-sass-language-server, which uses the official parser and so will be able to handle whatever syntax we come up with, especially given that this doesn't affect the semantics of the stylesheet at all. We're also working on https://github.com/sass/dart-sass/issues/88 which will expose the official AST to JS, so it should be pretty feasible for tools to be resilient to the more complex syntax. Does that satisfy the concern?

**Comment by wkillerud** [comment]
Using `sass_api` certainly helps, but there are still things happening in the language server layer after parsing that depends on the syntax of the document. Communication between client and server in LSP use the text document (not AST), ranges in that document, and often snippets with syntax that need to match the current cursor position in the document. 

I wanted to raise awareness just in case the need for SCSS in Sass wasn't that great, in the interest of keeping the "surface" of the syntax simpler.

I don't want to block this proposal going forward though, if there is a need for SCSS in Sass. We'll handle it 😄

**Comment by nex3** [comment]
SCSS-in-Sass is definitely the _less_ critical part of this. I like that it makes it possible to write small styles substantially more tersely, as in `.foo {color: red}`, but it's possible it's not worth the hassle it would cause to an LSP implementation. @jamesnw What do you think?

**Comment by jamesnw** [comment]
Another benefit from SCSS-in-Sass is that it more directly replaces the practice of putting long variables into separate `.scss` files, and importing from there. For longer styles like `box-shadow` or `grid-template-areas`, it isn't terser than wrapping the expressions in parentheses, but it does benefit from being more familiar syntax that users may already use elsewhere.

It seems like most tooling for the indented format is colocated with SCSS tooling, so my assumption was that it wouldn't require tooling maintainers to add completely new support for the SCSS format. It would break the assumption that they are separate at the document level, and the issues raised here are valid.

The cost for implementation in Sass is relatively small (I'm guessing, I haven't started this portion). The impact to tooling I'm guessing is much bigger.

As @nex3 says, this isn't the most critical portion of the proposal. The unknown I think is the benefit to users. Is there a way we could gather that feedback? I'll post a question on the original issue.

**Comment by nex3** [comment]
I'd be fine leaving off the embedded-SCSS portion of the proposal, unless users come forward and express a strong positive desire for it.

**Comment by jamesnw** [comment]
I think that makes sense. I opened #4002 to remove it from the proposal, and #4003 to track this for potential future implementation.
