### ISSUE TITLE
`Importer::canonicalize` is called inconsistently for import specifiers starting with `/`

### ISSUE THREAD

**Issue by sapphi-red** [sass/sass#3998]
When a `@use` that has a specifier starting with `/` (e.g. `@use '/foo.scss'`), [`Importer::canonicalize`](https://sass-lang.com/documentation/js-api/interfaces/importer/#canonicalize) is called with `file:///foo.scss` only for the file loaded by `Importer::load`.

### Reproduction
1. Clone https://github.com/sapphi-red-repros/sass-importer-slash-on-windows
2. Run `npm i`
3. Run `node index.js`

### Actual behavior

The following content is output:
```
canonicalize /b.scss
canonicalize file:///c.scss
canonicalize /c.scss
.c {
  color: blue;
}
```

### Expected behavior

Either of the following content is output:
```
canonicalize /b.scss
canonicalize /c.scss
.c {
  color: blue;
}
```
```
canonicalize file:///b.scss
canonicalize /b.scss
canonicalize file:///c.scss
canonicalize /c.scss
.c {
  color: blue;
}
```

**Comment by jathak** [comment]
I'm a bit confused by what you mean by "import specifier" which isn't a term we use anywhere. If you're trying to have some indication that a given dependency URL should be processed by a particular custom importer, the recommended solution is to use a custom URL scheme (e.g. `@use "foo:some/path/file.scss"`) and then have the importer's canonicalize function return null for any dependency URL without that scheme. A leading `/` indicates an absolute path within the default `file` URL scheme.

If your custom importer is always loading files from disk, you may want to use a [`FileImporter`](https://sass-lang.com/documentation/js-api/interfaces/fileimporter/) instead of a regular custom importer.

**Comment by miguel-leon** [comment]
I think he meant to say the import url (maybe it's called specifier in loaders from other tools like vite).

The urls are indeed absolute paths, and the problem as I understand it, is that the same absolute url doesn't become the same canonical url, depending on whether the `@use` is on the main file or another sass module, on windows.

**Comment by sapphi-red** [comment]
I meant this part of the `@use` (/`@import`/`@forward`) by "import specifier".
```scss
@use "foo"
/*   ^^^^^ this part */
```

> If you're trying to have some indication that...

No, I'm not trying to do that. I'm a maintainer of Vite and trying to fix a bug. Vite has supported resolving `/something` to a different path than the absolute `/something` via legacy importers. There was a bug report (https://github.com/vitejs/vite/issues/18919) that this feature does not work when using the modern API. I found that `canonicalize` is only called once (with the raw specifier `/b.scss`) for the `@use` written in the entrypoint while `canonicalize` is called twice (with the raw specifier and the normalized specifier `file:///b.scss`) for other `@use`. I thought this was a bug because I don't find a reason why it's not called once or twice for both cases. I can just ignore that fact and implement some code relying on that fact, but that may break in future when someone changes the behavior as I guess this is not a documented behavior, and I'd like to avoid doing so.

I wrote two cases of the expected output in the OP but I think the following output is also expected:
```
canonicalize file:///b.scss
canonicalize file:///c.scss
.c {
  color: blue;
}
```

**Comment by nex3** [comment]
The first thing to note is that you're passing a string for [`StringOptions.url`](https://sass-lang.com/documentation/js-api/interfaces/stringoptions/#url), when it requires a `Url`. This actually does sort of work in practice, but it's against the expected types and may break in the future.

To the core issue: the reason you don't see `canonicalize()` being called with `file:///b.scss` is that the entrypoint file isn't associated with your custom importer. From [the `Importer.canonicalize()` documentation](https://sass-lang.com/documentation/js-api/interfaces/importer/#canonicalize) (emphasis mine):

> Relative loads in stylesheets **loaded from an importer** are handled by resolving the loaded URL relative to the canonical URL of the stylesheet that contains it, and passing that URL back to the importer's {@link canonicalize} method. For example, suppose the "Resolving a Load" example [above](https://sass-lang.com/documentation/js-api/interfaces/importer/#md:resolving-a-load) returned a stylesheet that contained `@use "mixins"`:
>
> - The compiler resolves the URL `mixins` relative to the current stylesheet's canonical URL `db:foo/bar/baz/_index.scss` to get `db:foo/bar/baz/mixins`.
> - It calls [canonicalize](https://sass-lang.com/documentation/js-api/interfaces/Importer#canonicalize) with `"db:foo/bar/baz/mixins"`.
> - [canonicalize](https://sass-lang.com/documentation/js-api/interfaces/Importer#canonicalize) returns `new URL("db:foo/bar/baz/_mixins.scss")`.

Your entrypoint isn't loaded from your custom importer, so (root-)relative loads inside it aren't routed through that importer. If you rewrite your `index.js` as so:

```js
import { compileString } from 'sass'
import fs from 'node:fs'

const importer = {
  canonicalize: (canonicalize) => {
    console.log('canonicalize', canonicalize)
    if (canonicalize.startsWith('/')) {
      const result = new URL(canonicalize.slice(1), import.meta.url)
      return result
    }
  },
  load: (load) => {
    return { contents: fs.readFileSync(load, 'utf8'), syntax: 'scss' }
  },
};

const result = compileString("@use '/b.scss'", {
  importers: [importer],
  importer,
  url: new URL('./a.scss', import.meta.url).href,
})
console.log(result.css)
```

You'll see the output is:

```
canonicalize file:///b.scss
canonicalize /b.scss
canonicalize file:///c.scss
canonicalize /c.scss
.c {
  color: blue;
}
```

which hopefully makes more sense.

**Comment by sapphi-red** [comment]
> The first thing to note is that you're passing a string for [`StringOptions.url`](https://sass-lang.com/documentation/js-api/interfaces/stringoptions/#url).

It seems I made a mistake when creating the reproduction. Please be assured that the URL is passed in the original code.

> To the core issue: the reason you don't see `canonicalize()` being called with `file:///b.scss` is that the entrypoint file isn't associated with your custom importer.

That makes sense. I thought `importer` is a shorthand for `importers` and `importer: foo` does the same with `importers: [foo]`. Thank you for explaining.
