### ISSUE TITLE
Impossible to scope a CSS imported by @use, worked with @import

### ISSUE THREAD

**Issue by GregOriol** [sass/sass#4004]
The scenario is the following: you get a css file to use in your project from an external source (either provided by a client, library, sub-project, ...), you don't want to change the css file because it is not yours and it will be difficult to update it if you change anything inside. So you want to add it to your CSS generated by SASS, but you don't want it to pollute the global scope and want it to be scoped inside some selector of yours. With @import you could simply do that by importing it where you wanted. With @use, it seems that you can't.

Example:
```
# external-form.css

form {
    background-color: #f00;
}

```

```
# current sass stylesheet with @import

#some-scoped-form-container {
    @import 'external-form.css';
}
```

```
# new sass stylesheet with @use
impossible?
```

Is there something I missed? How could we achieve this quite common use-case?

**Comment by kaj** [comment]
This is what meta.load-css is for!

```
@use "sass:meta";

#some-scoped-form-container {
  @include meta.load-css("external-form.css");
}
```

**Comment by GregOriol** [comment]
@kaj Thanks, this is what I missed!
