### ISSUE TITLE
Why `@use` must be put before everything else

### ISSUE THREAD

**Issue by rrmesquita** [sass/sass#4005]
Hi,

I'm sure this is not the place to post questions, so feel free to immediately close this issue. It's just that the discussions tab is not available and I haven't found anything similar.

I want to know why `@use rules must be written before any other rules`? What is the technical reasoning behind it?

Recently I had to refactor my code to support the new syntax, and I wanted to keep the output in the same order.

To my surprise, this doesn't compile:

```scss
@use 'foo-module';

.my-rule {
    opacity: 1;
}

@use 'bar-module';
```

While this produces the expected result:

```scss
@use 'foo-module';

@use 'the-module-containing-my-rule';

@use 'bar-module';
```
---

I'd appreciate if someone could take a couple minutes to explain. Thanks!

**Comment by nex3** [comment]
This is a great place for questions about the language design.

The reason for this has to do with one of the core guarantees of `@use`: that the CSS of each stylesheet you `@use` will appear only once in the output, even if you `@use` that stylesheet multiple times. This fixes a long-standing pain point with `@import`, but one side effect of it is that the ordering of stylesheets is not always the same as the ordering of `@use` rules. For example, if you write

```scss
@use 'foo';
@use 'bar';
```

it's not _guaranteed_ that the styles for `bar.scss` appear after those for `foo.scss`. For example, `foo.scss` could `@use 'bar'` itself, causing `bar.scss`'s files to appear first. The only guarantee is that the styles appear in [topological order](https://en.wikipedia.org/wiki/Topological_sorting), with all the styles `@use`d by a given module appearing _somewhere_ before that module's own CSS.

We don't allow style rules (or any other statements that output CSS, with the exception of comments) between `@use` rules to make it easier to reason about this ordering. When each module has a single chunk of CSS that always appears contiguously in the output, it's easier to understand the potentially-complex ordering behavior. In addition, it avoids potentially-misleading source code—in your first example, it looks like `.my-rule` is intended to appear before `bar-module`, but that's not actually a guarantee that's provided by that stylesheet and so is misleading and could potentially cause incorrectly-styled output if a reader assumed it worked the way it looked.

**Comment by rrmesquita** [comment]
Thanks for clarifying that!
