### ISSUE TITLE
Ahhh! Zombie SCSS Syntax Error Messages!

### ISSUE THREAD

**Issue by patreeceeo** [sass/sass#403]
Sass **sometimes** creates error messages that refuse to go away even when the problem is corrected. This is a problem becuase Sass displays these messages not only using STDERR but also with a _content_ attribute in the CSS, which jacks up the layout. 

**I've tried:**
- correcting the syntax error (obviously)
- deleting the .sass-cache directory 
- killing compass
- restarting compass
- intentionally inserting other syntax errors

**Some info about my situation:**

This only seems to happen when the error is in SCSS files, not SASS files.

**The latest error message is:** 
   Syntax error: Invalid CSS after "     font-size:": expected psuedoclass or psuedoelement, was " 1em !important"

**I'm using:**
- compass 0.11.7
- sass-twitter-bootstrap
- ubuntu 12.04
- ruby 1.9.3p194
- sass 3.1.15

**Workaround:**
Delete the CSS file containing the error message and re-compile.

**Possible resolutions include:**
- Making the error messages go away when the error is corrected
- Not showing error messages using the CSS _content_ attribute

Thanks,
Patrick

**Comment by nex3** [comment]
In order to fix this, we'll need to be able to reproduce it. Can you reproduce it with just Sass (that is, not Compass or Bootstrap)? Is there an SCSS file that consistently triggers it?

**Comment by patreeceeo** [comment]
Erhm, well...Looks like I was running two instances of compass. That might have something to do with it!

**Comment by patreeceeo** [comment]
On second thought, when I was trying to figure out a work-around I restarted my machine, so it might not be that I was running two instances of compass. I haven't been able to reproduce the issue, thought its happened twice. I'm leaving the issue open in case anyone else experiences it.

**Comment by rasheednyc** [comment]
I'm experiencing the same thing.

**Comment by rasheednyc** [comment]
Never mind, it was just this: https://github.com/chriseppstein/compass/issues/904
