### ISSUE TITLE
Recording the result of sass --check in a file

### ISSUE THREAD

**Issue by nhunzaker** [sass/sass#404]
I'm trying to do the following:

``` shell
sass --check ./my/scss/file.scss >> file.txt
```

I can see, very clearly, the validation errors displaying in the terminal. However they aren't transferring over into my file. Any thoughts?

**Comment by nex3** [comment]
`sass --check` prints errors to stderr. If you want to redirect both stdout and stderr, use `&>` (e.g. `sass --check ./my/scss/file.scss &> file.txt`).

**Comment by nhunzaker** [comment]
Perfect, thank you
