### ISSUE TITLE
Test to see if @content was passed

### ISSUE THREAD

**Issue by alanhogan** [sass/sass#407]
I want to be able to define a mixin that can be passed @content but that does not _require_ it.

Something like this would be good:

```
@if @content
  @content
```

**Comment by chriseppstein** [comment]
I had intended that `@content` would be a no-op if it was not passed. @nex3, you and I should sort this out.

**Comment by alanhogan** [comment]
My current work-around is this (where my-mixin expects content but I don’t want to pass any, and in fact is perhaps not even defined by myself):

```
@include my-mixin {
  -no-op: 1
}
```

That way when this is resolved I can just remove those -no-op: 1 lines.

IMO, @content as a no-op when not passed would be better than a test for seeing if it would be passed, since it would mean less code (no pointless conditionals).

But better than that is both options. I know some Compass functions do some tricky conditional stuff based on what arguments are actually passed. I can’t imagine there wouldn’t be any cases where testing for @content would not be useful, as well.

Best: Both test & no-op
Good: No-op
Fine: test

**Comment by alanhogan** [comment]
Ran into this again — wrote a mixin where I’d love to be able to make `@content` optional. It would have made the rest of the stylesheet a bit more maintainable.

**Comment by alanhogan** [comment]
Would love to see sass 3.2 with a no-op-if-none-passed @content.

**Comment by chriseppstein** [comment]
I think this is simply a bug/oversight. @nex3 this needs to be in 3.2. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by sidonath** [comment]
+1to @alanhogan's suggestion

I have `@include` in a partial that's used by two different stylesheets. I would like to make the mixin noop in one stylesheet, and to generate the appropriate code in the other one.

Right now I'm getting this error `Mixin "foo-bar" does not accept a content block.`

My current workaround is to define `foo-bar` mixin with a never-executing conditional:

``` scss
@mixin foo-bar {
  @if false {
    @content
  }
}
```

**Comment by chriseppstein** [comment]
@nex3 can we please address this before 3.2 ships?

**Comment by alanhogan** [comment]
![thumbs-up](http://openclipart.org/image/250px/svg_to_png/28688/skotan_Thumbs_up_smiley.png)

Great :)

Also, going to cc @ericam to make sure he sees this :)

**Comment by mirisuzanne** [comment]
Thanks!

**Comment by ogbaoghene** [comment]
@alanhogan want to check if `@content` is passed. How are using this? Would love to see a sample of your code.
