### ISSUE TITLE
CSS3 Gradients indented syntax

### ISSUE THREAD

**Issue by adrusi** [sass/sass#41]
is it possible to use multiple lines for the CSS3 gradient syntax? Also it would be useful for other CSS3 syntaxes, like multiple borders, box-shadows, text-shadows, backgrounds etc. Maybe some symbol to indicate a newline, possible commenting out the newline:

```
background-image: -webkit-gradient(linear, center top, center bottom,//
  from(black),//
  color-stop(33.333%, blue),//
  color-stop(66.666%, green),//
  to(red)//
)
background-image: -moz-linear-gradient(  ...
```

**Comment by nex3** [comment]
No, this is currently not possible.
