### ISSUE TITLE
filename in imported files wrong?

### ISSUE THREAD

**Issue by gettalong** [sass/sass#412]
When importing files, the filename of the current file seems to be incorrect. I.e. currently the following filename is set in `lib/sass/tree/visitors/perform.rb`, line 143:

```
@environment.push_frame(:filename => node.filename, :line => node.line)
```

This uses the current filename, not the filename of the imported file which would be `file.options[:filename]` (as used in the backtrace in case an error happens).

Is this a bug or a feature?

**Comment by nex3** [comment]
Can you provide an example of how this affects the externally-visible behavior of Sass?

**Comment by gettalong** [comment]
The use case where this is a problem is resolving relative paths in a custom function, see https://github.com/gettalong/webgen/blob/master/lib/webgen/content_processor/sass.rb#L102

In this case I would like to use `options[:filename]` to resolve a file relative to the imported one (similar to how `Importer#find_relative` works). However, since the current filename is pushed into the environment and not the imported one, this won't work.

Here is an example tree:

```
/default.scss
/custom/styles.scss
/custom/img/bg.png
```

So we assume `/default.scss` gets rendered and it imports `/custom/styles.scss`. The `relocatable` function is called in the latter with the argument `img/bg.png` and will fail because this resolves to `/img/bg.png` and not `/custom/img/bg.png`.

Such a `relocatable` function is needed in my case because since the `/custom/styles.scss` files gets included in `/default.scss`, the paths to images etc. need to be relative to `/default.scss` and not `/custom/styles.scss`.

**Comment by nex3** [comment]
I think you're mis-identifying the source of the problem. The stack isn't used in populating `options[:filename]`; that comes directly from the options passed in to the root `Sass::Engine` instance. That said, it may be possible to pass a more file-specific options hash into functions.

**Comment by gettalong** [comment]
Hmm... I don't know the Sass internals this good, however, the problem as stated does exist and is reproducible. It would be nice to have the correct filename set somewhere in the options exactly for such cases.

**Comment by gettalong** [comment]
Thanks!

**Comment by krisbulman** [comment]
This commit introduced a bug in Compass: https://github.com/chriseppstein/compass/issues/989

file paths only intermittently work now on compile, I've made an example project to show the problem noted in https://github.com/chriseppstein/compass/issues/989#issuecomment-7690898

**Comment by nex3** [comment]
@krisbulman Is there a bug in this commit that's causing errors in compass, or is it just a matter of updating Compass to use the new semantics? /cc @chriseppstein

**Comment by krisbulman** [comment]
Unfortunately I was only able to track down the source of the problem, but not determine which it is. I am assuming the latter, perhaps @chriseppstein can provide some insight?

**Comment by krisbulman** [comment]
@nex3 Forgive my amateur questions, but I appear to be the only one plugging away at this at the moment. 

Does :filename need special handling now? The only way I could patch Compass to work was by using the gsub in your test/sass/plugin_test.rb on sass_filename before it was passed to the options hash 

see here: https://github.com/krisbulman/compass/commit/3de54c895a9f7244332e60ed7a39bc9fc33b55ea

and it doesn't work on multiple imports (as noted by the comment someone posted).

**Comment by nex3** [comment]
After further investigation, this does seem to be a Sass bug.

**Comment by sascha-egerer** [comment]
The problem is not fixed by your commit... It still generates a wrong URL

**Comment by nex3** [comment]
@sascha-egerer Can you provide an example where it generates the wrong output?

**Comment by sascha-egerer** [comment]
I'm not sure why but i can't reproduce it again. I have to check this at work on monday.

**Comment by sascha-egerer** [comment]
Ok I'm sorry... It was a problem with RVM. Looks like it works correct now
