### ISSUE TITLE
Watch not working with "services.scss"

### ISSUE THREAD

**Issue by thomaspeklak** [sass/sass#415]
If you name a file `service.scss` then the watch command recognizes changes in the file but does not generate the corresponding css file, if the CSS file does already exist in the target directory.

**Example:**
- file in scss/styles/services.scss
- no css present in target

```
% sass --watch scss/styles:styles                                                                                       
>>> Sass is watching for changes. Press Ctrl-C to stop.
  overwrite styles/services.css
>>> Deleted template detected: /webapps/test-app/scss/styles/services.scss
>>> New template detected: /webapps/test-app/scss/styles/services.scss

END
```

Issue exists on Linux and Windows

**Comment by nex3** [comment]
I can't reproduce this. What versions of Sass and Ruby are you using? What's your operating system?

**Comment by thomaspeklak** [comment]
The bug was found on Windows and Linux. However I tested it today with the current Sass version and was not able to reproduce it. Seems to be fixed.
