### ISSUE TITLE
line spacing in css output

### ISSUE THREAD

**Issue by ghost** [sass/sass#42]
Hi, someone probably already asked thsi question, but after a bit of reasearch I haven't come to the solution yet.
is there a way to get rid of the line spaces between rules (for the output css) without having to nest elements one in another?

I mean, I get this:
.crowns_baron { background: url('/images/crowns.png?1296421758') 0 -27px; }

.crowns_count { background: url('/images/crowns.png?1296421758') 0 -55px; }

.crowns_count { background: url('/images/crowns.png?1296421758') 0 -55px; }

insead of this:
.crowns_baron { background: url('/images/crowns.png?1296421758') 0 -27px; } 
.crowns_count { background: url('/images/crowns.png?1296421758') 0 -55px; }
 .crowns_count { background: url('/images/crowns.png?1296421758') 0 -55px; }

thanks in advanced

**Comment by ghost** [comment]
ah, it looks in :compact mode for some reason...

I just want it to be without space, e.g.
this is a css rule
this is another css rule

and not
this is a css rule

this is another css rule

**Comment by nex3** [comment]
There's no way to do that without using the full-on `:compressed` mode. We have no plans to add a mode in between.
