### ISSUE TITLE
[Enhancement] overwritable @mixin´s

### ISSUE THREAD

**Issue by SunboX** [sass/sass#420]
Hi, I´m using large Sass templates from a third party company. Now I want to customise these templates. So I´ve to overwrite some @mixin´s but this doesn´t work by now. :( I also want to call the "parent" mixin so I just can put my changes in there, like this:

**third party template:**

``` sass
@mixin large-text {
    font-family: Arial;
    color: #FF0000;
}
```

**my customization:**

``` sass
@mixin large-text {
    @callParent;

    // overwrite color of original mixin:
    color: #0000FF;
}
```

I can´t add these changes directly to the original template, cause it gets updated time by time and I´ve to re-apply all custom changes again. That´s really frustrating ...

**Comment by SunboX** [comment]
Same will apply to @function´s

**third party template:**

``` sass
@function grid-width($n) {
    @return $n * 10;
}
```

**my customization:**

``` sass
@function grid-width($n) {
    $ret = callParent($n);

    @return $ret * 1.5;
}
```

**Comment by chriseppstein** [comment]
Something like this is needed. perhaps this might tie into a module system, @nex3?

**Comment by chriseppstein** [comment]
duplicate of #240

**Comment by SunboX** [comment]
No, it's not (!) a duplicate of #240 !

**Comment by chriseppstein** [comment]
It is from our perspective :) We'll consider both of these concepts and address them with a single solution.
