### ISSUE TITLE
undefined method `deep_copy' for ["(", "min-width", ": ", 480px, ")"]

### ISSUE THREAD

**Issue by AndrewVos** [sass/sass#422]
On ruby 1.8.7-p302 I'm getting this:

```
/usr/lib/ruby/gems/1.8/gems/sass-3.2.0.alpha.247/bin/../lib/sass/../sass/tree/visitors/deep_copy.rb:94:in `visit_media': undefined method `deep_copy' for ["(", "min-width", ": ", 480px, ")"]:Array (NoMethodError)
```

**Comment by AndrewVos** [comment]
Turns out I was using a newer version of sass, which doesn't work with compass.

This works:

```
gem install sass -v 3.2.0.alpha.244 --pre --no-rdoc --no-ri
gem install compass --pre --no-rdoc --no-ri
```

**Comment by nex3** [comment]
What styles are causing this error?

**Comment by AndrewVos** [comment]
Pretty sure it's something in compass?

On 19 Jun 2012, at 19:29, Nathan Weizenbaum
reply@reply.github.com
wrote:

**Comment by chriseppstein** [comment]
What versions didn't work?

**Comment by wardpenney** [comment]
3.2.0.alpha.244 worked for me, the latest sass 3.2.0.alpha.247 breaks it. 

Here was the css output i got when it errored:
Syntax error: Invalid CSS after "  @media ": expected "{", was "#{$query-string} {"

**Comment by nex3** [comment]
@ExtraMedium We really need to see the Sass styles that are causing the error to be able to fix it. I **can't** reproduce the error in 3.2.0.alpha.247 with the following code:

``` scss
$var: foo;

@media #{$var} {
  foo: bar;
}
```

**Comment by crofty** [comment]
I was having the same issue.  Importing susy (1.0.rc.1) was throwing an error.  Downgrading to sass 3.2.0.alpha.244 fixed it for me.

**Comment by jeef3** [comment]
I got the same error when I upgraded from .244 to .247 but not sure what CSS is causing it. My actual error message is:

```
undefined method `deep_copy' for ["print"]:Array (NoMethodError)
```

**Comment by francis-villanueva** [comment]
Yea, the issue is still there using  Compass + Susy 1.0.rc.2, which now requires Sass 3.2.0.alpha.247. It seems to happen when trying to write media queries:

``` scss
@media (max-width: 767px) {
...
}
```

**Comment by dustinwilson** [comment]
I had this same error. It was caused from an unintended `@import` loop followed by a media query. When I started deleting stuff until it stopped showing the same error I deleted the media query and it told me about the import loop:

```
@import url("ook");

@media screen and (device-aspect-ratio : 14/9)
{
 body
  {color:green;}
}
```

The second I changed the filename it parsed just fine.

**Comment by nex3** [comment]
Thanks @dustinwilson, that was enough to get a reproduction up and running.

**Comment by dustinwilson** [comment]
No problem. Glad to help. :D
