### ISSUE TITLE
Support different file extensions with --watch and --update

### ISSUE THREAD

**Issue by aprescott** [sass/sass#423]
It seems that `--watch` and `--update` only handle `.scss` (and `.sass`?) file extensions.

This works:

``` bash
$ sass --scss css/foo.css:css-compiled/foo.css
```

But this doesn't seem possible (there is no output):

``` bash
$ sass --scss --update css:css-compiled
```

(And the same for `--watch`.)

**Comment by nex3** [comment]
Without using extensions, there's no good way of telling what should be
compiled or what syntax it's using.
On Jun 21, 2012 3:30 AM, "Adam Prescott" <
reply@reply.github.com>
wrote:

**Comment by aprescott** [comment]
What's wrong with the existing `--scss` option to indicate the syntax in use?

**Comment by nex3** [comment]
Compiling all files regardless of extension means that it's impossible to use `sass --watch` on any directory that recursively contains anything other than Sass files.

**Comment by aprescott** [comment]
I'm not sure I understand what you mean. My suggestion is for there to be something like `sass --watch --scss --extension=css foo:bar` which would act the same way `sass --watch foo:bar` does now, but instead of operating on `.scss` files, operates on (in this case) `.css` files. So that the default behaviour stays as-is, but you can, for example, keep files as `.css` and simply use SCSS syntax.

**Comment by parkr** [comment]
It doesn't make much sense to use the `.css` extension if you're not writing CSS. Use `.scss` for SCSS and `.sass` for Sass.
