### ISSUE TITLE
Variable undefined error although still compiles?

### ISSUE THREAD

**Issue by Integralist** [sass/sass#430]
Hi,

I have a the following .scss content...

``` scss
// Configurations/Settings
@import "Configurations/variables";

// Mixin
@import "Modules/Mixins/border";

// Desktop Specific Styles
@import "Queries/960-home";
```

...and inside "Queries/960-home" is...

``` scss
@import "Modules/error"; // uses $variables setup within "Configurations/variables"
@import "Modules/demo"; // uses mixin setup within "Modules/Mixins/border"
```

...when I save any changes I can see in the command line (I use Terminal on the Mac) that both "Modules/error" and "Modules/demo" have errors related to access to the mixins and variables, but yet when I check the compiled CSS file the content has been processed fine (e.g. variable values have been inserted correctly and the mixins have returned relevant values and been inserted correctly also).

I _think_ SASS is incorrectly highlighting this as an error when it obviously can access the variables/mixins.

Is this a bug or am I missing something (even though it appears to work fine!)

Thanks.

**Comment by chriseppstein** [comment]
Sass compiles all files that don't start with an underscore. Add an underscore to file name that you only use for importing. The import statements themselves can remain as-is. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by Integralist** [comment]
@chriseppstein Thanks for the response but the variables.scss and borders.scss already have underscores in their file name. Sass allows you to not have to specify the underscore when importing. But be assured that the only file that is generated is the top level file (eg the file that has the above content) all other files have underscores in their file name

**Comment by Integralist** [comment]
If you want an example then please see my repo: https://github.com/Integralist/Passage

**Comment by Integralist** [comment]
By the way that repo is a little messy as Ive just noticed there are loads of files inside the Sass folder which I've winced moved into sub folders?? I need to clean that up. But open desktop.scss to see the latest file I'm working with!

**Comment by nex3** [comment]
It looks like IE.scss in that repo imports Queries/960-home without first importing the files that define the variables. Perhaps that's where your errors are coming from?

**Comment by Integralist** [comment]
@nex3 thank you! that appears to have been the problem :-)
