### ISSUE TITLE
Join Flattens Lists

### ISSUE THREAD

**Issue by Snugug** [sass/sass#434]
If I've got a list w/more than one item that is space separated, and join another space separated list using the join function and the comma separator, instead of getting a new list with two space separated lists, I get one flattened list with each item separated by a comma. Example:

``` scss
$test:();
@for $i from 0 through 5 {
  $holder: 'This is #{$i}' $i;
  $test: join($test, $holder, comma);
}
@debug $test;
@debug nth($test, 1);
```

Expected Output:

``` scss
$test: "This is 0" 0, "This is 1" 1, "This is 2" 2, "This is 3" 3, "This is 4" 4, "This is 5" 5
nth($test, 1): "This is 0" 0
```

Actual Output:

``` scss
$test: "This is 0", 0, "This is 1", 1, "This is 2", 2, "This is 3", 3, "This is 4", 4, "This is 5", 5
nth($test, 1): "This is 0"
```

This seems to run counter to the expected behavior and the description in the yardocs

**Comment by nex3** [comment]
This is the expected behavior; from the second example in the documentation:

``` scss
join((blue, red), (#abc, #def)) => blue, red, #abc, #def
```

That said, this does seem like something that should be possible. @chriseppstein, thoughts?

**Comment by nex3** [comment]
Looks like the real problem is that `#append` isn't visible in the documentation (#433). Closing.
