### ISSUE TITLE
SASS converts percentages to only 3 decimal places

### ISSUE THREAD

**Issue by djmichaelb** [sass/sass#437]
Hey quick bug it appears,

as part of a responsive design I am inputting a style into my SCSS sheet:

.example {
  left:-1.06609808102345%;
}

the output to my CSS sheet reads:

.example {
  left:-1.066%
}

The resulting pages is one pixel off in alignment as a result. Is there a reason sass is rounding long percentages when outputting? Responsive design suggests using the most accurate percentages available and letting the browser do the work.

**Comment by djmichaelb** [comment]
I should point out that frustratingly when using the following in my SCSS for the same element:

.example {
 width:102.1321961620469%;
}

the output to CSS is:

.example {
 width:102.1321961620469%;
}

so this either only happens on certain properties, or only when a 0 is encountered in the percentage? I'll try to do some more testing to determine the issue.

**Comment by nex3** [comment]
Duplicate of #319
