### ISSUE TITLE
Pass comments through to the generated css in compressed mode if they start with /*!

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#44]
Evidently this is a convention in other css preprocessors that we should adhere to.

Referenced here:
http://notundefined.tumblr.com/post/3275351226/saving-your-license-text-from-the-sass-compiler

**Comment by chriseppstein** [comment]
Patch here: https://github.com/chriseppstein/sass/commit/53c0f06eac63238934d0be5cc9bfc79108e5875a

**Comment by adam-h** [comment]
This feature will be really useful for Wordpress template "style.css" files, which require a comment at the top that describes the template.

**Comment by chriseppstein** [comment]
This is in Sass 3.1. Commit: 3af2ab397d621b42e66f55f2380b6f80103b5826
