### ISSUE TITLE
List index error

### ISSUE THREAD

**Issue by OliverJAsh** [sass/sass#444]
I have a list that looks like this:

`$step: 16px 24px;`

If I try to split this list into individual variables, like so:

```
$font-size: if(length($step) >= 1, nth($step, 1), 0);
$line-height: if(length($step) >= 2, nth($step, 2), 0);
```

Then I get the error:

`List index is 2 but list is only 1 item long for 'nth'`.

**Comment by chriseppstein** [comment]
The `if()` function is a normal function so that means all the arguments are evaluated before being passed in. We figured we'd add special parsing for it at some point if it became an issue so that we could avoid just this sort of thing.

The work around is to use the `@if` directive for now.

**Comment by OliverJAsh** [comment]
Thanks for the workaround. Keep up the awesome work!

**Comment by chriseppstein** [comment]
I have opened #470 to follow up on this.
