### ISSUE TITLE
Interpolation with integers adds a single whitespace after the integer

### ISSUE THREAD

**Issue by willthefirst** [sass/sass#446]
In SCSS:

Mixin:

``` scss
@mixin img-respond-to($media, $path) {
    @if $media == retina {
        background: url(../../images/retina/#{$path}_2x.png); 
    }
}
```

SCSS:

``` scss
@include img-respond-to(retina, 1_start/title);
```

Rendered as:

``` css
background: url(../../images/retina/1 _start/title_2x.png);
```

**Comment by nex3** [comment]
The issue here is that `1_start` is not a valid CSS identifier, but you're trying to use it as one. It parses as the number `1` followed by the identifier `_start`, and to clarify that Sass inserts a space between the two.

What you're really want to do is pass a string to your mixin:

``` scss
@include img-respond-to(retina, "1_start/title");
```

**Comment by willthefirst** [comment]
Thanks!
