### ISSUE TITLE
Sass Error: Invalid CSS after "}​": expected "{", was ""

### ISSUE THREAD

**Issue by 2bj** [sass/sass#450]
https://gist.github.com/ddf600267eb3ec46c10d

**Comment by nex3** [comment]
It looks like there are some invisible garbage characters (`0x342`, `0x200`, and `0x213`) after the final "}" in that Gist. These are what's confusing Sass.

**Comment by ZChunara** [comment]
How do we fix the above problem?

**Comment by douglasdeodato** [comment]
@ZChunara  looks like in the gist was a . in the last line check out this: http://www.sassmeister.com/gist/858d3b3bf9ec2a95dccfaa11d830b701

**Comment by Borkes** [comment]
``<style lang='sass' rel='stylesheet/scss'>`
...
</style>`
I fixed it with <style lang='scss' rel='stylesheet/scss'>

**Comment by Borkes** [comment]
`<style lang='sass' rel='stylesheet/scss'>
... 
</style>`
I fixed it with <style lang='scss' rel='stylesheet/scss'>

**Comment by YoMiao** [comment]
use : 
<style lang="scss">

</style >
