### ISSUE TITLE
* html requires space, gives following error when *html: '"html" may only be used at the beginning of a selector.'

### ISSUE THREAD

**Issue by ghost** [sass/sass#452]
Since as a language SCSS was designed such that CSS is syntactically a subset of SCSS, I wanted to make you aware that with respect to IE hacking - as facepalmingly oxymoronic as that is - SCSS is not that syntactic superset.  When you use as CSS selector *html notably without that space between the asterisk and html, the parser fails with the following error:

```
   Syntax error: Invalid CSS after "*": expected "{", was "html .widget-wr..."

   "html" may only be used at the beginning of a selector.
   on line 2279 of /<private>/sass/style.scss
```

Given the following source (SCSS):

```
   * html .clearfix, 
   * html #container, 
   *html .widget-wrapper {
          height:1%;
   }
```

Many thanks for all your fantastic work - as always.

**Comment by gbenedict** [comment]
This was not an issue for me with 3.1.15, but is in the 3.2 alphas (required by zurb-foundation 3.0.5). Consequently, we can't compile CKEditor.

ckeditor/plugins/uicolor/yui/assets/yui.css fails due to a *html hack.

**Comment by nex3** [comment]
I don't think this is a bug.

SCSS does intend to support all the CSS hacks it can, but I don't think this falls under that umbrella. The `* html` hack typically uses valid CSS syntax; the "hack" aspect is just that IE considers the selector `* html E` to match all elements E`, whereas other browsers consider it to match no elements.

However, `*html E` is not valid CSS syntax. CSS requires that there be a space between compound selectors, and does not allow both `*` and `html` to be in the same compound selector. It may be the case that IE interprets `*html` the same as `* html`, but I don't want to make SCSS parse invalid syntax where it's not necessary for the functioning of a hack, and in this instance it's not.

**Comment by ivankukobko** [comment]
Sass fails to compile css file with hacks, but why would it do that at all?

```
*** Invalid CSS after "*": expected "{", was "html .cke_uicol..."
*** "html" may only be used at the beginning of a selector.
*** (in /var/www/.../shared/bundle/ruby/1.9.1/gems/ckeditor-3.7.0.rc3/vendor/assets/javascripts/ckeditor/plugins/uicolor/yui/assets/yui.css)
```

**Comment by rafalbromirski** [comment]
If you don't care about IE6 you can use this version: https://github.com/paranoida/ckeditor

**Comment by anlek** [comment]
--- deleted ---

**Comment by anlek** [comment]
@paranoida ignore my last message, didn't see that someone else put ckeditor into the 'vendor/assets' folder in the project i'm working on.
