### ISSUE TITLE
Allow for css4 parent selector '!'

### ISSUE THREAD

**Issue by dgm** [sass/sass#455]
I know this is still way off in the future, but this jquery plugin is bringing it to the present: http://demo.idered.pl/jQuery.cssParentSelector/

but when I use it, sass generates an error.

```
.infopane legend! a:hover
```

yields

```
Invalid CSS after ".infopane legend": expected "{", was "! a:hover,.info...
```

**Comment by nex3** [comment]
This is already supported in the master branch.
