### ISSUE TITLE
Inconsistent handling of negative values in a list

### ISSUE THREAD

**Issue by thenickname** [sass/sass#457]
When using negative values (values with a minus in front) in a SASS list, they are calculated in some cases, because the minus is considered part of an arithmetic operation. Calling this a bug may be exaggerated, but I think it's at least worth mentioning:

``` sass
/* Example 1 (works as expected): */

@debug ( 0 0 4 -20 );
/*
  expected output: 0 0 4 -20
  actual output: 0 0 4 -20
*/


/* Example 2 (works as expected): */

$value: 20;
$negativeValue: -$value;

@debug ( 0 0 4 $negativeValue );
/*
  expected output: 0 0 4 -20
  actual output: 0 0 4 -20
*/


/* Example 3 is the "bug"  */

$value: 20;
@debug ( 0 0 4 -$value );
/*
  expected output: 0 0 4 -20
  actual output: 0 0 -16
*/
```

**Comment by nex3** [comment]
This is just a consequence of Sass's parser. If you want to avoid it, you can wrap the expression in parentheses (e.g. `0 0 4 (-$value)`).
