### ISSUE TITLE
Please do not bundle any libraries

### ISSUE THREAD

**Issue by voxik** [sass/sass#458]
Hi,

Could you please avoid bundling of libraries, i.e. the listen gem? Bundling makes it hard to package the gem for any Linux distribution (Fedora in my case) since it is prohibited by packaging guidelines [1] and makes compatibility issues to our users, since we need to remove the bundled libraries. Thank you for considering.

[1] https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

**Comment by nex3** [comment]
It's important to me that Sass be fully usable as-is without requiring any external dependencies. One consequence of this is that it bundles its watcher library. You're free to un-bundle it for packaging, but it's going to remain in the repository and the gems.

**Comment by voxik** [comment]
Are you aware, that if I un-bundle the watcher library, the sass will never work as expected with Bundler? Since Gemfile.lock will look different on my Fedora then on yours system? You might be right that people can add "gem 'listen'" into their Gemfile, but in the mean time, it takes them time, it might take your time as well as mine.

So what are the reasons for the bundling, if you could enlighten me please? Thank you.

**Comment by voxik** [comment]
BTW are you aware that you bundled version of Listen might very well conflict with my version of Listen installed from gem? Have you ever considered the bugs which might arise due to this?

**Comment by nex3** [comment]
> Are you aware, that if I un-bundle the watcher library, the sass will never work as expected with Bundler? Since Gemfile.lock will look different on my Fedora then on yours system?

Gemfile.lock should indeed look different if the packages being depended on are different. I'd expect it to always look different when it's pulling packages from the distro's package source than when it's pulling from the standard gem repository.

> So what are the reasons for the bundling, if you could enlighten me please? Thank you.

As I said above, Sass should be runnable from the repository or its packages without installing any other gems.

> BTW are you aware that you bundled version of Listen might very well conflict with my version of Listen installed from gem? Have you ever considered the bugs which might arise due to this?

Sass is very careful to give preference to pre-installed versions of the Listen library before attempting to load the bundled version.
