### ISSUE TITLE
@extend returning "The selector * was not found."

### ISSUE THREAD

**Issue by krisbulman** [sass/sass#459]
Sass 3.2.0.alpha.275

I have a use case for extending selectors (some of which are in media queries) which previously worked without errors, and now gives warnings. My media queries need to be in a separate stylesheet as they are loaded based on whether or not RWD is required (drupal theme). 

If the selectors do not exist in the same stylesheet, I get warnings that a selector was not found. If everything is compiled in the same stylesheet, the @extend works. 

Here is an example of how the problem arises: https://gist.github.com/fa7a5d56c56941cbb799

Compiling everything in one stylesheet does actually work without warning: https://gist.github.com/c543973ef112be0f9bec
but doesn't solve the problem of needing to separate out the media-queries as a separate stylesheet using this @extend method. 

When a selector doesn't exist, shouldn't @extend just ignore the selector?

The only workaround I have found is to somehow include every selector in some manner, in both the mq and the default stylesheets, even if the selectors are assigned an empty value, at least the method still works. 

Suggestions?

**Comment by nex3** [comment]
`@extend` warnings were added to make it easier to tell when you've made a mistake by writing an `@extend` that doesn't match any elements. See #111.

You can use the `!optional` flag to declare that an `@extend` shouldn't print a warning if it matches nothing; see [the relevant changelog entry](https://github.com/nex3/sass/blob/0db3cb6c69625af872dc39f2694ba1017516c2bb/doc-src/SASS_CHANGELOG.md#extend-warnings).
