### ISSUE TITLE
Variables in media selector don't work

### ISSUE THREAD

**Issue by jonas-jasas** [sass/sass#460]
``` scss
$stretched_layout_threshold: 1010px;
@media only screen and (min-width: $stretched_layout_threshold) {
...
}
```

Error:
Invalid CSS after "...nd (min-width: ": expected expression (e.g. 1px, bold), was "$stretched_layo..."

**Comment by dunn** [comment]
[This will work in version 3.2.](http://thesassway.com/intermediate/responsive-web-design-in-sass-using-media-queries-in-sass-32)

**Comment by chriseppstein** [comment]
you can install the lastest alpha releases if you need this feature.

**Comment by jonas-jasas** [comment]
Will variables also work like this?
$footer-height: 90px;
min-height: -moz-calc(100% - $footer-height);

**Comment by chriseppstein** [comment]
Should work.
