### ISSUE TITLE
Creating variable groups

### ISSUE THREAD

**Issue by alisalemx** [sass/sass#462]
As someone suggesting here: http://stackoverflow.com/questions/9779794/creating-variable-groups-in-sass

He says: "Variables in CSScafold can be organized in groups and used with a point-separated markup. For example I would define them as:"

``` sass
@variables vargroup1 {
    $variable1: ####;
    $variable2: ####;
    $variable3: ####;
    $variable4: ####;
}
```

And later use on the code as, for example.

``` css
body { width: vargroup1.variable1; margin: vargroup1.variable2 + 10; }
```

I think this would be ideal for something like colors. Instead of using global variables with painfully long names, you would group your colors in some manner and using the above method to link back to them.

It would also resolve the variable scope conflicts. In addition to myself, I'm sure others are finding it a bit weird that a local variable overrides a global one not just in the current selector scope, but in other selectors as well.

**Comment by nex3** [comment]
Duplicate of #440.
