### ISSUE TITLE
Allow interpolation in variable names

### ISSUE THREAD

**Issue by jcksncllwy** [sass/sass#463]
Sample use case borrowed from [discussion group](https://groups.google.com/d/msg/sass-lang/YSPdq_2NHgQ/6gfMEjk3p8sJ):

```
$red: #111
$yellow: #222
$green: #333

$button-colors: red yellow green
@each $color in $button-colors
    .#{$color}-button
        color: $#{$color}
```

Mostly posting to see if this is reasonable or not. I've seen a few discussions in the Google Group about this with no concrete conclusions about why this shouldn't be a feature. Thoughts?

**Comment by chriseppstein** [comment]
We've decided to add an association data type (aka map/hash) and it will address this use case. look for it in the release following 3.2

**Comment by jcksncllwy** [comment]
Awesome! Thanks for the quick response.
