### ISSUE TITLE
publishing dates of releases on SASS webpage

### ISSUE THREAD

**Issue by jszczypk** [sass/sass#465]
Hi,

It would be a nice addition if you could publish dates of releases on http://sass-lang.com/.
For example:
Latest Release: Brainy Betty (3.1.20 - 2012-06-30)
instead of:
Latest Release: Brainy Betty (3.1.20)

As well as in Changelog.

Kind regards,
Janusz

**Comment by nex3** [comment]
This should take effect as of the next release.
