### ISSUE TITLE
rails version checking logic wrong in rails.rb

### ISSUE THREAD

**Issue by betelgeuse** [sass/sass#466]
In lib/sass/plugin/rails.rb we have the following code

``` ruby
  # Rails 3.1 loads and handles Sass all on its own
  if defined?(ActionController::Metal)
    #3.1 > Rails >= 3.0
    require 'sass/plugin/rack'
    Rails.configuration.middleware.use(Sass::Plugin::Rack)
  elsif defined?(ActionController::Dispatcher) &&
      defined?(ActionController::Dispatcher.middleware)
    # Rails >= 2.3
    require 'sass/plugin/rack'
    ActionController::Dispatcher.middleware.use(Sass::Plugin::Rack)
  else
    module ActionController
      class Base
        alias_method :sass_old_process, :process
        def process(*args)
          Sass::Plugin.check_for_updates
          sass_old_process(*args)
        end
      end
    end
  end
```

In rails console for 3.1:

```
1.9.3p125 :002 > defined?(ActionController::Metal)
 => "constant"
```

This means that sass will run code where the comments claim to be for 3.0.x also on 3.1. Can someone knowing the history explain what the goal here is? I am thinking that if asset pipeline is enabled we don't want to load the plugin.

**Comment by nex3** [comment]
`sass/plugin` is typically not required at all in a Rails 3.1+ project, I believe.

**Comment by chriseppstein** [comment]
@nex3 it's possible to disable the asset pipeline and use the `Sass::Plugin` instead. `Sass::Plugin` can check whether the asset pipeline is enabled. In `compass-rails` we use this to check:

``` ruby
(cfg = Rails.application.config) && cfg.respond_to?(:assets) && cfg.assets.try(:enabled)
```

**Comment by nex3** [comment]
But why would `sass/plugin` be loaded in the first place if the user wants to use the asset pipeline?

**Comment by chriseppstein** [comment]
@nex3 Isn't it the default behavior?

**Comment by nex3** [comment]
No, I believe `sass/plugin` is not loaded at all in Rails >= 3.1.
