### ISSUE TITLE
filter: progid:DXImageTransform.Microsoft.gradient can not work in @mixin

### ISSUE THREAD

**Issue by ooxxnm** [sass/sass#467]
### sass code:

<pre>
@mixin linear($color1, $color2)
  background-image: -moz-linear-gradient(top, $color1, $color2)
  background-image: -ms-linear-gradient(top, $color1, $color2)
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from($color1), to($color2))
  background-image: -webkit-linear-gradient(top, $color1, $color2)
  background-image: -o-linear-gradient(top, $color1, $color2)
  background-image: linear-gradient(top, $color1, $color2)
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='$color1', endColorstr='$color2', GradientType=0)
  
.box2
  background-color: #fff
  background-repeat: repeat-x
  @include linear(#ccc, #667)
</pre>

### css code:

<pre>
.box2 {
  background-color: white;
  background-repeat: repeat-x;
  background-image: -moz-linear-gradient(top, #cccccc, #666677);
  background-image: -ms-linear-gradient(top, #cccccc, #666677);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#cccccc), to(#666677));
  background-image: -webkit-linear-gradient(top, #cccccc, #666677);
  background-image: -o-linear-gradient(top, #cccccc, #666677);
  background-image: linear-gradient(top, #cccccc, #666677);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='$color1', endColorstr='$color2', GradientType=0);
}
</pre>

**Comment by StanAngeloff** [comment]
Try double quotes `"$color"` or interpolation `#{$color}` (no quotes).

**Comment by ooxxnm** [comment]
<code>#{$color}</code> is worded
Thank you!
You blog is very cool!

**Comment by laxmanmore** [comment]
Hi All,

I have used CSS like 

.dropdown-menu>.disabled>a:hover {
    text-decoration: none;
    cursor: not-allowed;
    background-color: transparent;
    background-image: none;
    filter: progid: DXImageTransform.Microsoft.gradient(enabled=false);
}

Error:

Sass::SyntaxError: Invalid CSS after "    filter: progid": expected ";", was ": DXImageTransf..."

Please help me how to deal with this ?

**Comment by scervera** [comment]
@laxmanmore, this answer is perhaps a couple of years too late, but I just ran into the issue you experienced too. The solution is to quote the string after the filter: like this - 
`filter: "progid: DXImageTransform.Microsoft.gradient(enabled=false)";`

**Comment by itiswicked** [comment]
Plugging sass into a long running project, I also ran into a similar error the first time I compiled:

```
filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#f3c642', endColorstr='#ee6a50', GradientType=1);
```

```
Error: Invalid CSS after "... filter: progid": expected "}", was ": DXImageTransform."
        on line * of some/file.scss
>>     filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#f3c64
```

quotes worked, but you can also make this error go away by removing the space after `progid:`

```
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3c642', endColorstr='#ee6a50', GradientType=1);
```

I don't yet know if this affects the look of the element itself, but it works from a compilation standpoint.

**Comment by nex3** [comment]
All the examples in [this documentation](https://msdn.microsoft.com/en-us/library/ms532847(v=vs.85).aspx) don't include a space after `progid:`. It's possible that IE supports it without a space, but considering this syntax is only relevant to IE7 and earlier and there's a trivial workaround I don't think it's worth adding support for the version with a space.

**Comment by lusparty** [comment]
Hi All,
I have 3 serious erroreg in my CSS code and I can not fix it.
Can you help me with this ???
Thank you

```
ERROR: Unknown@rule:@-ms-keyframes.
Expected (<filter-function-list> ¡ none) but found
´progid:DXImageTransform.Microsoft.BasicImage(rotation=1)´.
Expected (<filter-function-list> ¡ none) but found
´progid:DXImageTransform.Microsoft.BasicImage(rotation=2)´.
Expected (<filter-function-list> ¡ none) but found
´progid:DXImageTransform.Microsoft.BasicImage(rotation=2)´.
Expected (<filter-function-list> ¡ none) but found
´progid:DXImageTransform.Microsoft.BasicImage(rotation=0,Mirror=1)´.
Expected (<filter-function-list> ¡ none) but found
´progid:DXImageTransform.Microsoft.BasicImage(rotation=2,Mirror=1)´.
```

**Comment by nex3** [comment]
@lusparty It looks like you're not using Ruby Sass. I suggest filing an issue against whatever Sass implementation you're using.

**Comment by jose2007kj** [comment]
@scervera your answer helped me
