### ISSUE TITLE
function isset

### ISSUE THREAD

**Issue by goncaloe** [sass/sass#47]
function isset to test if a variable exists or not

**Comment by chriseppstein** [comment]
Ruby functions don't currently have access to the Sass environment, so they cannot decide this. Either the environment would need to be exposed to the ruby code or the function would have to be implemented as a language primitive.

TL;DR: Not going to happen in Sass 3.1.

**Comment by porqz** [comment]
I think, you should use this → http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#variable_defaults_

**Comment by nex3** [comment]
I don't think this is useful enough to warrant adding.

**Comment by robwierzbowski** [comment]
A simple workaround for anyone who finds this issue: http://stackoverflow.com/questions/8512802/checking-if-a-variable-is-defined-in-sass#answer-13237776
