### ISSUE TITLE
Is it possible to leave empty classes and ids in result css?

### ISSUE THREAD

**Issue by dbashyal** [sass/sass#475]
see more info: http://stackoverflow.com/questions/11837701/how-to-include-empty-classes-and-ids-in-sass-result

If this is possible, it would make my life so much easier!!!

Thanks.

**Comment by chriseppstein** [comment]
Why is this helpful?

**Comment by dbashyal** [comment]
It's because I use firebug to write CSS. If I can leave empty class or ID I can see that in firebug then I can adjust CSS from firebug and copy paste back to sass. I believe it will help a lot of developers who use firebug. Currently I have to write something to display on firebug. Hope it makes sense.

**Comment by chriseppstein** [comment]
This is a deficiency in firebug. Chrome allows you to add new selectors:

![Chrome](https://img.skitch.com/20120808-diuts3s13nyp5qkyacn12ndp6r.png)

**Comment by dbashyal** [comment]
@chriseppstein thx, good to know that trick. also got answer from stackoverflow. just need to add /**/, so it's not empty.
