### ISSUE TITLE
sass errors on multi line definitions

### ISSUE THREAD

**Issue by dwt** [sass/sass#477]
I've got this css to be converted to sass and got a lot of errors on multi line definitions like these:

```
  background-image: -moz-linear-gradient(
      45deg, 
      rgba(0,0,0,0) 0%, 
      rgba(0,0,0,0) 50%, 
      rgba(255,255,255,0.1) 50%, 
      rgba(255,255,255,0.4) 100%
      )
```

The braces make the parsing perfectly clear, but still sass (with sass syntax) complains bitterly. (Sass 3.1.15 (Brainy Betty))

**Comment by dwt** [comment]
Another case where rules like these:

```
  box-shadow:  0px 1px 1px rgba(0,0,0,0.7) inset, 
               2px -2px 2px -3px rgba(0,0,0,0.5) inset
```

The comma should clear up the parsing, but it doesn't.

**Comment by chriseppstein** [comment]
this is not a current feature. it is a duplicate of feature request #216.
