### ISSUE TITLE
New directive: @parent

### ISSUE THREAD

**Issue by Snugug** [sass/sass#483]
Now that we have @content in Sass 3.2, I'd love the ability to know /what/ is calling my mixin. For this, I'd propose the @parent directive, which would spit back either a single string of the fully compiled parent selector, or a list of selectors in order they get added. So, something like the following:

``` scss
@mixin find-parent {
  @debug @parent;
}

#foo {
  @include find-parent;

  .bar {
    @include find-parent;
  }
}
```

``` bash
# As a single string
'#foo'
'#foo .bar'
# As a list
'#foo'
'#foo', '.bar'
```

Because I know everyone likes real world usecases when adding this kinda thing, the usecase that I have for this is media query optimizations similar to [Issue 241](https://github.com/nex3/sass/issues/241) which is highly requested for my Breakpoint compass extension. I understand the issues you have with including Issue 241 in Sass Core, but giving us Contrib people the power to work that out would be awesome.

**Comment by chriseppstein** [comment]
This use case is addressed by;

https://github.com/nex3/sass/issues/286

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by Snugug** [comment]
I skimmed that, didn't realize it was related as most of it didn't talk about this issue. I look forward to 3.3 (or can we call it 3.2.1?! It's something all of us RWD people want today!)

**Comment by chriseppstein** [comment]
closing this
