### ISSUE TITLE
Sass Coding Standards

### ISSUE THREAD

**Issue by emagnier** [sass/sass#487]
Is there today some coding standards for Sass ?

e.g. : 
- I like to write mixins, variables and functions in lowerCamelCase to get a better differentiation between the native CSS & SASS functions, and the custom elements writed in Scss.
- In nested elements, I'm always writing CSS properties first, and then in new lines the sub nested elements.

Etc.

**Comment by nex3** [comment]
I'd say the best guide is just "do what Compass does". To my knowledge, no one's written any sort of formal document, although @chriseppstein may know of one. To address your questions in particular:

> I like to write mixins, variables and functions in lowerCamelCase to get a better differentiation between the native CSS & SASS functions, and the custom elements writed in Scss.

The style for identifier names is to make them all lower-case, separated by hyphens (e.g. `my-sass-identifier`). If you're worried about being confused between Sass and CSS functions, I'd say add a vendor-style prefix (e.g. `-my-function`).

> In nested elements, I'm always writing CSS properties first, and then in new lines the sub nested elements.

This is definitely correct. Sass will always move the properties above any nested elements, so keeping them that way in the source helps make it correspond more closely to the output.
