### ISSUE TITLE
Can’t divide unitless value by value with unit?

### ISSUE THREAD

**Issue by alanhogan** [sass/sass#489]
I have a feeling that I’m forgetting something important here, but:

I tried:

```
$line-height: 1.3 
margin-bottom: $line-height / 1em
```

and got this error:

```
0.75/em isn't a valid CSS value.
```

However, this worked:

```
$line-height: 1.3 
margin-bottom: $line-height / 2 * 1em
```

**Comment by alanhogan** [comment]
My brain just remembered that, actually, in Real Life Math, the difference is that the unit would be on the denominator in the first example, and the numerator in the second: it’s the difference between a rate “per em” and a quantity of ems.

Sigh

**Comment by nex3** [comment]
Correct. Sass follows Real Life Math here.
