### ISSUE TITLE
Merge extend-only output

### ISSUE THREAD

**Issue by jacobrask** [sass/sass#491]
When importing a file with extend-only selectors, and then extending that selector in several files, I would expect it to only have one output with all the selectors merged.

At least _all_ selectors should not be repeated every time an extend-only directive is used.

Example: https://gist.github.com/3368347

**Comment by chriseppstein** [comment]
Placeholder selectors are no different from any other selector in this respect. If you include them more than once, you'll have them more than once in your output. You should take care to only import these placeholder selectors once per output file.
