### ISSUE TITLE
Getting relative paths into output when using --line-numbers flag

### ISSUE THREAD

**Issue by MaxAller** [sass/sass#493]
It looks like there are some provisions in the to_css visitor (https://github.com/nex3/sass/blob/stable/lib/sass/tree/visitors/to_css.rb#L175) to output a relative path, but this branch is never hit when running with the sass or scss binaries -- as far as I can tell, it's only hit when invoking Sass programmatically from Ruby. It'd be great if we could inject the css_filename option even when running sass or scss (when applicable, i.e. not piping to stdout).

**Comment by chriseppstein** [comment]
Compass sets this and I rarely actually compile using the sass command line... but you're right, this doesn't get set via the sass CLI.
