### ISSUE TITLE
partials with underscore cannot be imported

### ISSUE THREAD

**Issue by lauterry** [sass/sass#494]
Hi

I noticed that partials containing underscore characters (_) cannot be imported.

Example :
_mypartials.scss     OK
_my_partials.scss   KO  : <code>Syntax error: File to import not found or unreadable: _my_partials.scss.</code>

An obvious workaround is to avoid underscore characters in partials files name.

Best regards

**Comment by nex3** [comment]
I can't reproduce this on master or stable. What version of Sass are you using?

I'll re-open if I can start reproducing.
