### ISSUE TITLE
Slow CSS compilation after migrating from 3.1.20 to 3.2.1

### ISSUE THREAD

**Issue by chalofa** [sass/sass#495]
After I updated the sass dependency from 3.1.20 to 3.2.1, I have been noticing a slow recompilation of my CSS files.

With 3.1.20, changing any SASS file and recompiling took about 5 seconds.

Now, with 3.2.1, the same operation takes about 25 seconds.

The only warning I can find, is about extending a missing class, because I'm currently using a `@extend .modal` (a Twitter Bootstrap class).  
Maybe it's trying to find that class and that's causing the slowness?

Other important gems used:

```
rails, 3.2.8
sass-rails, 3.2.5
bootstrap-sass, 2.0.4.0
```

**Comment by nex3** [comment]
It's not possible to help you with this without more information. Please provide a stylesheet that demonstrates this slowness; preferably one that's as small as possible and has no external dependencies.

**Comment by GBH** [comment]
I can confirm this. In 3.2 and 3.3 alpha compiling took about 18s. Downgrading to 3.1.21 reduced it to 2.5 seconds.

I'm also abusing bootstrap and `@extend`

**Comment by nex3** [comment]
@GBH Similarly to the above, without a stylesheet that I can compile to see the slowness myself, I can't do anything about it.

**Comment by dgdavid** [comment]
I have the same problem, and only in version 3.2.1 of Sass. I uploaded a simple example of application [https://github.com/dgdavid/slow-sass] with part of assets that I'm  using. Every little change in styles involve a considerable time.

From the command line, the times are

```
sass --compass app/assets/stylesheets/application.css.scss > /dev/null  131,81s user 0,06s system 99% cpu 2:12,21 total

ruby -S sass _3.1.21_ --compass app/assets/stylesheets/application.css.scss >  6,33s user 0,07s system 99% cpu 6,417 total
```

**Comment by GBH** [comment]
@dgdavid I see you also use `@extend` to bring in bootstrap definitions instead of polluting your html with ridiculous classes like `table.table.table-striped.table-bordered.table-hover.table-condensed.table-shutthefuckup`. I like bootstrap in theory, but I really dislike how I'm forced to use it. `@extend` looked like a decent solution, but it doesn't scale (massive definitions if you have a lot of css) and incredibly slow even with version of sass that didn't make it several magnitudes slower.

**Comment by nex3** [comment]
@dgdavid Thanks for posting that repo. That'll definitely help me track down this issue.

**Comment by nex3** [comment]
`git bisect` indicates that 8f4869e608e70d7f468bb463ebfe7a939d834e27 introduced the issue.

**Comment by nex3** [comment]
It's worth noting that part of the reason this is so slow is that you're using `@extend` with very deeply nested selectors. `@extend` does a lot more work and produces a lot more output for each additional level of nesting. If you flattened out your stylesheet more, it would be faster and produce much less output.

That's not to say that I won't try to make this optimization faster, of course.

**Comment by dgdavid** [comment]
True, but the difference between one and another version is quite noticeable. However I have done some testing «un-nesting» as I much as possible and still is very slow in sass 3.2

Thanks for checking.

**Comment by nex3** [comment]
That commit should mitigate the issue until I can fix it entirely. The downside is that deeply nested `@extend`s now won't get thoroughly optimized.

**Comment by tsemana** [comment]
Even with the fix my compile time is still around 104sec. when we say 'unnest' the extends, does that mean don't nest them in the `.scss` file? or the css structure?

isn't 

``` css
#services{
  @extend .row;

  .service{
    @extend .four;
    @extend .columns;
  }
}
```

the same as

``` css
#services{
  @extend .row;
}

#services .service{
  @extend .four;
  @extend .columns;
}
```

I've tried the second format, and it still seems very long.

**Comment by nex3** [comment]
I mean the CSS structure. When you have `@extend`s in selectors like `form div.text_position .nested-fields .control-group-row input[type=text]`, Sass has to do a lot of work to get rid of extra selectors that are generated. That could probably be shortened to `.control-group-row input[type=text]` and work just fine.

**Comment by killthekitten** [comment]
How is the progress?

**Comment by nex3** [comment]
I haven't made any more progress since adding the workaround in 0ba3109a3072cf903f9e18948b81c6b0ead98d07.

**Comment by scamden** [comment]
what's the status here? comparing 3.2.7 to 3.1 my compile goes from ~38s to ~13s. i need the features in 3.2 but twice the compile time is rough..

**Comment by kamilski81** [comment]
I use RubyMine and I this slow sass compilation was occurring when i was in 'debug' mode but would go away if i just started the server in 'run' mode, that may help some of you.

**Comment by scamden** [comment]
I cut out like 70% of my slowness by only importing the compass modules I needed. Sorry for raising the alarm
—

**Comment by rafael-h-ferreira** [comment]
Same here. I have to use this code to make the spans work:

```
@for $i from 1 through 12
    .span#{$i}
        @extend [class^="span"] !optional
        @extend [class*="span"] !optional
```

After this and adding bootstrap-responsive, that uses 3 media queries, it gets too slow to work.

**Comment by unyo** [comment]
Is there a possibility of adding a flag to skip this reduction check? Compile times go from 12s to 3s when downgrading from 3.4.5/3.2.0 to 3.1.21.

I've even tried forking the repository and completely removing the trim functionality by taking the line in 0ba3109 and removing the if statement at the end, but it doesn't seem to cause the compile time to drop back down to anywhere near the 3s mark.

**Comment by nex3** [comment]
@unyo Can you provide the stylesheets that are compiling slowly for you?

**Comment by Cristialt** [comment]
Very slow here too, ~10s for a compilation, I think since I am using the newest sass versions

I am using a mb pro quad i7 2.3 with 8gb ram
ruby 1.9.3
sass 3.4.7
compass 1.0.1

I build from 
+foundation 5.4.7
+font-awesome
+normalize 
+my components

(I've had much better times with older sass, slower machine and bigger apps)

**Comment by nex3** [comment]
I'm going to merge this into #1019.
