### ISSUE TITLE
sass --watch _names 

### ISSUE THREAD

**Issue by adiktofsugar** [sass/sass#499]
Example filesystem:
- scss
  - _main.scss
  - main.scss

sass --watch scss:css -C

This won't work. Apparently _main and main are the same to sass.... I'm not sure if this is covered in the docs, but from what I understood, _main just won't actually be compiled to a new css file, whereas main will.

This bugged the crap out of me for a few hours, so I want to at least make it known that this happens.

**Comment by Anahkiasen** [comment]
Well up until here it seems logicial to me, _main won't get compiled because it's a partial, and main will because it isn't. Unless I didn't actually get what was going wrong ?

**Comment by adiktofsugar** [comment]
I guess I didn't mention why it was bad... Sass gets confused when you have a partial and a non partial with the same name like this, and won't record changes to either.

**Comment by nex3** [comment]
Why do you have this setup in the first place? If you write `@import "main"`, it's ambiguous whether you want to import the partial or the non-partial.

**Comment by adiktofsugar** [comment]
Apparently so. That is actually the issue.

Here's why. I've been writing @import '_main' in the files that I want to have whatever is in there. To me, a partial is just something that doesn't really deserve a stylesheet dedicated to it, or something that all my stylesheets will share...or a group of them or whatever.

When I write @import 'main' I expect that main.scss or main.sass is included. And when I write @import '_main', _main.sass or main.scss is included.

Also, why doesn't really have anything to do with the issue...I'm just reporting something that didn't make any sense to me. If this was a design decision that I just don't agree with, then I would hope that my reporting it would just increase the verbosity within the partial section of the documentation, or maybe an informative message on the watch output that tells me why it's not compiling the file I changed, so I'll know to rename my partials.

**Comment by chriseppstein** [comment]
This behavior is certainly by design. It's best practice for `@import` statements to never specify a partial explicitly nor to specify the extension. People who follow this best practice will find it easier to switch syntaxes or convert to/from a partial to a compiled-file.

Can you make a suggestion for what can be added to the docs to make this more clear?

**Comment by adiktofsugar** [comment]
Alright. There are two places in the docs where some explicit information could be added that explains what happens when you don't follow best practice. For the record, I don't see (at least near the @import rule declaration) anything about this best practice dealio you're talking about.

I think the most obvious place to put it is in the partials section, at the end. Something like "If you then also make a file called colors.scss, everything breaks. This is by design. Don't do it" Maybe highlighted in red with a warning sign. Depends on how serious you want to take this, I guess.
