### ISSUE TITLE
Shorthand math

### ISSUE THREAD

**Issue by Snugug** [sass/sass#502]
This is something that's been bugging me and the more Sass I write the more I really want to use shorthand math in Sass. Specifically, I'd like to be able to do the following:

```
+=
-=
/=
*=
%=
++
--
```

For `++` and `--`, I'd see them work simply as `$i++;`

I'd also like to be able to use `+=` for appending to strings, but I'd really love these for math first and foremost.

**Comment by Snugug** [comment]
Hmm, just realized that we don't use = in Sass. So maybe something like…

```
+:
-:
/:
*:
%:
```

So a variable would look something like this`$i +: 1`. That being said, maybe I can convince you to use the equals sign for these shorthand maths?

**Comment by chriseppstein** [comment]
```
$feature -: 1;
```

**Comment by Snugug** [comment]
You're a funny man Chris.

**Comment by chriseppstein** [comment]
It is a handy feature, and in a real programming language it would be a must-have, but SassScript aims to be pretty simple -- just enough to get things done. As such, I'm not convinced this is worth the additional learning curve for our non-programmer friends.

**Comment by Snugug** [comment]
Well wouldn't that be the beauty of this feature? It's something our non-programmer friends would _never_ need to use and/or see, but for us who are and really use this stuff often (especially when creating, say, frameworks and systems nudge nudge) it'd take a lot of burden off of us. Mason, Scott, and I have recently had a tendency to use Sass like a real programming language for CSS, and `$foo: $foo + 1;` gets tedious and quick.

**Comment by chriseppstein** [comment]
I'm pretty sure @scottkellum told me he learned to program via SassScript. The language being accessible and simple, the ability to dig into library code and figure it out, was core to that growth curve.

**Comment by Snugug** [comment]
Agreed there, and this wouldn't take away from that accessibility for 90% of SassScript, but would be awesome for the other 10%. Not to mention, these conventions are extremely common throughout pretty much all other languages, so coming across them in Sass and then needing to look up what it means should be fairly trivial (not to mention these would then get documented and they could Google "Sass +=" and get the answer)

**Comment by nex3** [comment]
I agree with Chris. Every feature, especially a programmery-style feature like this, has a cost in terms of learning curve. Even if you'd understand it easily, many people will not, and those people _will_ be forced to encounter it in Sass code they read. This is not worth the minor decrease in typing it would buy.
