### ISSUE TITLE
sass --watch broken on virtual box shared folders

### ISSUE THREAD

**Issue by dwt** [sass/sass#504]
Hi there,

as far as I can figure out sass is using the listen gem to watch for file system changes. Problem is that if you run sass inside a virtual box instance (e.g. via vagrant) and change files on the outside that are mounted in virtual box as a shared folder (vboxfs) sass (listen) doesn't see those changes via the native linux file system notifications library.

Thus it needs to fall back to polling.

Now this could be a bug in listen in that it should auto detect this, but untill it does, there should be a way to force this option on listen from sass.

I'd imagine something like

```
sass --watch foo:bar --force-polling
```

**Comment by nex3** [comment]
Please also file an issue for [Listen](https://github.com/guard/listen/issues?page=1&state=open).

**Comment by dwt** [comment]
https://github.com/guard/listen/issues/57

**Comment by priyeshwalunj** [comment]
Hi,
I'm developing my project in vagrant.I have a problem in sass watch(sass --watch sass/demo.scss:css/demo.css), it does't watch the changes continuously, to get changes in my demo.css I have to stop the watch & again run command of sass watch every time I make changes.Does anyone has faced this same problem & please let me know anyone has solution for this. Thank you!

**Comment by nex3** [comment]
@priyeshwalunj It's hard to say exactly what's going on without more details, but you can always pass `--poll` to tell Sass to manually poll the filesystem for changes rather than relying on the OS to notify it of changes.

**Comment by justinlopez0** [comment]
@nex3 I was in the same situation as @priyeshwalunj. I was on a Windows host machine with a Vagrant linux box and --watch was broken. Running --poll fixed it for me! Thanks!

**Comment by thomwise** [comment]
I'm running into the same issues running sass --watch inside of a vagrant virtual environment. When using --poll I'm still encountering the same issues I was having without it.
