### ISSUE TITLE
Allow global properties to be part of properties grouping

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#505]
Say you have the following properties :

``` sass
border: none
border-left: 3px solid red
border-right: 3px solid red
```

The first line being here as a reset, now currently in Sass you can do the following :

``` sass
border: none
border:
    left: 3px solid red
    right: 3px solid red
```

Now I was thinking, is there some sort of way to include the `border: none` in the group ? If not does anybody think it would be relevant or ?

``` sass
border:
    none
    left: 3px solid red
    right: 3px solid red
```

**Comment by zolotov** [comment]
According to the [documentation](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#nested_properties) you can write something like this:

``` sass
border: none
  left: 3px solid red
  right: 3px solid red
```

**Comment by Anahkiasen** [comment]
Well what do you know, you can actually do that. Kind of weird since afterwards the other properties underneath just seem to "hang there" alone but yeah, I missed that spot in the reference.
