### ISSUE TITLE
Multiple Watch, with different output styles

### ISSUE THREAD

**Issue by GaryJones** [sass/sass#507]
#301 suggests that multiple watches work, but I'd like to be able to watch a file, and have it create an expanded style output (.css) and a compressed (.min.css) file.

Something like:
`sass --watch style.scss:./../style.min.css --style compressed style.scss:./../style.css --style expanded`
This, obviously, just took the latest value for `--style` and produced two expanded format files.

Running two instances of the Windows command line with different sass --watch arguments does work in the meantime.

**Comment by nex3** [comment]
I don't think it's worth adding additional complexity to the command-line interface to replicate behavior that's easy to get by invoking the executable multiple times, or writing a wrapper script.
