### ISSUE TITLE
@import broken with absolute url without protocol

### ISSUE THREAD

**Issue by gdetrez** [sass/sass#508]
As mentioned in http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#Protocol, it is useful to omit the protocol in absolute urls but the following produce an error message in sass:

``` css
@import  '//fonts.googleapis.com/css?family=Anton&v1'
```

produce the following error message:

```
      error typography.scss (Line 23: File to import not found or unreadable: //fonts.googleapis.com/css?family=Anton&v1.
Load path: /home/gregoire/Code/django/myconf/style)
```

(note that using url() solves the problem, but since scss is supposed to be a superset of css, I figured that it could be worth looking into)

**Comment by chriseppstein** [comment]
Protocol relative urls are pretty cool, I use them too.
