### ISSUE TITLE
gray(x%) as a shortcut for rgb(80,80,80)

### ISSUE THREAD

**Issue by adius** [sass/sass#512]
I think it would be cool if there was the possibility to use the rgb function with just one value as a shortcut.
What do you think?

**Comment by chriseppstein** [comment]
gray(n%) would feel more natural to me.

**Comment by Anahkiasen** [comment]
+1 for this. I've had a `gray()` (well actually `grey`) function in my files for months, I use it all the time. Very very useful.

**Comment by nex3** [comment]
I'm definitely not willing to overload `rgb()` in a way that may end up being incompatible with the CSS spec. `gray()` may be doable, though.

**Comment by timohofmeijer** [comment]
`gray()` became part of the CSS4 draft :smile: .
`gray() = gray( [<number> | <percentage>] [, <alpha-value>]? )` 
https://drafts.csswg.org/css-color/#grays

**Comment by bkazi** [comment]
Hi,
I was hoping to get some guidance on this issue being a new contributor. I have come up with an implementation for `gray()` that is based on the way `rgb()` is done and it seems to work. I would like to know what would be the proper way to go about adding such a feature and what considerations should be taken.
Thanks

**Comment by nex3** [comment]
@bkazi Just send a pull request and we'll walk you through the process :smiley:

**Comment by nex3** [comment]
Closing this in favor of #2078.
