### ISSUE TITLE
sass-maven-plugin failure in windows platform

### ISSUE THREAD

**Issue by sureshnath** [sass/sass#513]
glob usage in plugin/compiler.rb is incorrect, resulting sass-maven-plugin fails in windows only

```
[INFO] Compiling SASS Templates
SystemCallError: Unknown error - Unknown Error (20047) - C:\Dataware\workspace\sts30\simple-spring-mvc\target\spring-1.0.0-BUILD-SNAPSHOT\static\css\C:
               mkdir at org/jruby/RubyDir.java:576
            fu_mkdir at file:/C:/Users/s.jaganathan/.m2/repository/org/jruby/jruby-complete/1.6.7.1/jruby-complete-1.6.7.1.jar!/META-INF/jruby.home/lib/ruby/1.8/fileutils.rb:243
             mkdir_p at file:/C:/Users/s.jaganathan/.m2/repository/org/jruby/jruby-complete/1.6.7.1/jruby-complete-1.6.7.1.jar!/META-INF/jruby.home/lib/ruby/1.8/fileutils.rb:217
        reverse_each at org/jruby/RubyArray.java:1695
             mkdir_p at file:/C:/Users/s.jaganathan/.m2/repository/org/jruby/jruby-complete/1.6.7.1/jruby-complete-1.6.7.1.jar!/META-INF/jruby.home/lib/ruby/1.8/fileutils.rb:215
                each at org/jruby/RubyArray.java:1615
             mkdir_p at file:/C:/Users/s.jaganathan/.m2/repository/org/jruby/jruby-complete/1.6.7.1/jruby-complete-1.6.7.1.jar!/META-INF/jruby.home/lib/ruby/1.8/fileutils.rb:201
   update_stylesheet at file:C:/Users/s.jaganathan/.m2/repository/org/jasig/maven/sass-maven-plugin/1.0.0/sass-maven-plugin-1.0.0.jar!/gems/sass-3.2.1/lib/sass/plugin/compiler.rb:334
  update_stylesheets at file:C:/Users/s.jaganathan/.m2/repository/org/jasig/maven/sass-maven-plugin/1.0.0/sass-maven-plugin-1.0.0.jar!/gems/sass-3.2.1/lib/sass/plugin/compiler.rb:202
```

**Comment by gheo21** [comment]
Hello, 

 Can I somehow workaround this problem?

Great job!

**Comment by sureshnath** [comment]
if you use without full file path, without this patch it should work!

Suresh

Date: Tue, 18 Sep 2012 05:02:12 -0700

**Comment by gheo21** [comment]
It still doesn't work with relative paths, is there a patch already for
this bug?

**Comment by gheo21** [comment]
Ist there a docu that describes how to use it as a maven plugin?

**Comment by sureshnath** [comment]
This is the documentation link http://developer.jasig.org/projects/sass-maven-plugin/1.0.0/plugin-info.html 

S
Date: Tue, 18 Sep 2012 07:39:02 -0700

**Comment by sureshnath** [comment]
I am afraid there isn't a patch that exists yet! You have to make your own build

Date: Tue, 18 Sep 2012 07:27:14 -0700

**Comment by nex3** [comment]
What makes you think the glob usage in plugin/compiler.rb is at fault here? Is there any way to reproduce this without JRuby, Maven, and Windows?

**Comment by sureshnath** [comment]
I am reasonably sure, any call through this piece code with absolute path should fail.
Please let me know, if I you want me to add an example!

Suresh

Date: Fri, 28 Sep 2012 13:43:55 -0700

**Comment by nex3** [comment]
It looks like the code that's being called is `FileUtils.mkdir_p`. This looks like a bug in JRuby, not in Sass.
