### ISSUE TITLE
 ie-hex-str outputs 8 hex digits, instead of 6

### ISSUE THREAD

**Issue by vsespb** [sass/sass#516]
(explanation of ie-hex-str is here https://github.com/nex3/sass/issues/363 )

```
$ cat sasstest
$c1: ie-hex-str(#ffffff); $c2: #000000;
div { color: $c1; background-color: $c2; }
$ scss -t compressed < sasstest
div{color:#FFFFFFFF;background-color:#000}
$ scss -v
Sass 3.2.1 (Media Mark)
```

**Comment by nex3** [comment]
That's the point of `ie-hex-str`. It exists because certain IE features are able to understand colors with an alpha channel only by tacking on two additional digits to a hex color.
