### ISSUE TITLE
a more CSS-like mixin syntax

### ISSUE THREAD

**Issue by ianstormtaylor** [sass/sass#519]
Curious to know what the decisions were for making the mixin syntax:

```
+mixin(arg, arg)
```

Seems like the more CSS-like syntax decision would be:

```
+mixin: arg arg
```

or

```
+mixin: arg, arg
```

Realized this from Chris's comment in https://github.com/nex3/sass/issues/366#issuecomment-7559687

Having previously used Stylus, I was a big fan of transparent mixins for their ease of use. Using SASS now, I actually like the `+` as an indicator of what's going on (less magic) but the parentheses are just annoying to write. Especially when changing from a normal CSS declaration to a mixin or back.

I guess there are complications between multiple variables eg. `+mixin(5px, #ddd)` and multiple groups of variables, eg. `+mixin(5px solid white, 1px solid blue)`. But wondering if there are ways to get around that, because the colon syntax feels much nicer to write and is more CSS-like.

It would also provide a nice differentiation between mixins and functions.

**Comment by nex3** [comment]
There's some tricky parsing issues with the `+mixin: arg` syntax. In particular, the following construct is ambiguous:

``` sass
.foo
  +bar:baz
    prop: val
```

`+bar:baz` there could either be a mixin with a `@content` argument or a selector beginning with the `+` combinator and ending with with the `:baz` pseudoclass. That said, we are considering alternative syntaxes that better match CSS in #366.
