### ISSUE TITLE
Compile SASS excluding certain CSS selectors defined in an external file

### ISSUE THREAD

**Issue by tinganho** [sass/sass#523]
Hi Nathan,

I wonder if you can create a feature where I can compile SASS code with the option of excluding certain CSS selectors defined in a file(semi-colon separated CSV file)?

This would be very welcomed by the market. Because using SASS you can produce a lot of CSS selectors that are unused. Like, for instance certain gridsystem or my compass plugin https://github.com/tinganho/stylewithclass. I'm creating a CLI tool that makes a semi-colon separated CSV file of unused CSS selectors.  It would be super good if you can create the compile option.

**Comment by nex3** [comment]
This runs counter to the best practices of Sass use. A well-written Sass file should include very few un-used selectors; it should use mixins and placeholder selectors to re-use styles without creating excess selectors.
