### ISSUE TITLE
Precompiling issue

### ISSUE THREAD

**Issue by cpetschnig** [sass/sass#526]
We have a Rails engine, which has the file `vendor/assets/stylesheets/engine_name.css`:

```
/*= require_tree .
 */
```

When precompiling the assets of the host app, it fails with the error message

```
Invalid CSS after " */": expected identifier, was ""
```

is shown. Our workaround is changing the file like this:

```
/*
 *= require_tree .
 */
```

**Comment by cpetschnig** [comment]
Here is the list of the relevant gems in the project:
- rails (3.2.8)
- coffee-rails (3.2.2)
- coffee-script (2.2.0)
- coffee-script-source (1.3.3)
- compass (0.12.2)
- therubyracer (0.10.2)
- sprockets (2.1.3)
- sass (3.2.1)
- sass-rails (3.2.5)
- uglifier (1.3.0)
- tilt (1.3.3)

**Comment by nex3** [comment]
What makes you think this is a Sass issue? Can you reproduce the error in plain Sass (without Rails/Sprockets)?

**Comment by cpetschnig** [comment]
The error message was generated in Sass. But after thinking of it, Sprockets might have passed invalid code to Sass. I am gonna report it to Sprockets. Thanks!
