### ISSUE TITLE
sass-convert bug with /**/ comments

### ISSUE THREAD

**Issue by SeanTAllen** [sass/sass#53]
when converting from .scss to .sass i noticed that lines like this:

```
.highlight .c { color: #999988; font-style: italic } /* Comment */
```

were converted to

```
.highlight .c
  color: #999988
  font-style: italic

/* Comment
```

this is with sass-convert run as

sass-convert file.scss file.sass

version 3.0.25

**Comment by chriseppstein** [comment]
I don't understand what the bug is. It looks right to me.

**Comment by SeanTAllen** [comment]
shouldnt that be 

`/* Comment */`

 in the sass, not just 

`/* Comment`

?

**Comment by chriseppstein** [comment]
@SeanTAllen It's whitespace sensitive so it's legal sass syntax -- try it.

**Comment by damjankuznar** [comment]
@chriseppstein This is true. However, most CSS editors do not highlight the code properly in this case. Would it be possible to to close the comment as SeanTAllen suggested?
