### ISSUE TITLE
Multiplication and division issues

### ISSUE THREAD

**Issue by vladchatware** [sass/sass#530]
I found that division and multiplication produce some weird code. I was using just --watch.

``` scss
$foo : 1px * 1px // 1px*px
```

``` bash
error 1px*px isnt a valid CSS value
```

Sass 3.2.1

**Comment by Anahkiasen** [comment]
As said in another thread, that's because Sass applies the correct math rules which means doing `1px * 1px` is basically like doing `1m * 1m` and since there's no such thing as a "square pixel" it throws an error.

**Comment by vladchatware** [comment]
I see.
