### ISSUE TITLE
Document media query merging

### ISSUE THREAD

**Issue by nex3** [sass/sass#531]
There's no documentation for the fact that Sass will merge `@media screen { @media (min-width: 200px) { ... } }`.

**Comment by sasstamas** [comment]
XD

**Comment by nex3** [comment]
This is incorrect. From the reference:

> `@media` queries can also be nested within one another. The queries will then be combined using the `and` operator. For example:
> 
> ``` scss
> @media screen {
>   .sidebar {
>     @media (orientation: landscape) {
>       width: 500px;
>     }
>   }
> }
> ```
> 
> is compiled to:
> 
> ``` scss
> @media screen and (orientation: landscape) {
>   .sidebar {
>     width: 500px; } }
> ```

I'm not sure why I couldn't find than when I filed this issue, but it was there.
