### ISSUE TITLE
Inaccurate error for `a&` selector

### ISSUE THREAD

**Issue by bradleyayers** [sass/sass#534]
I understand that this selector is invalid, however the error message is inaccurate:

> "&" may only be used at the beginning of a selector.)
>       error ./_paleblue.scss (Line 100: Invalid CSS after "        a": expected "{", was "& { @extend %pb…"

That's not strictly true, because `&` can also be used at the end of a selector. I think the message should be:

> "&" may only be used at the beginning or end of a selector

However this error wouldn't explain why `a&` is invalid. I suggest a separate error is used for that case.

**Comment by nex3** [comment]
What do you mean by the end of a selector?

**Comment by bradleyayers** [comment]
If `a &` is a selector, then `&` is the end of it.
