### ISSUE TITLE
setting list values by index

### ISSUE THREAD

**Issue by pdaoust** [sass/sass#537]
I see there's a way to get a list value by index -- `index($list, $index)` -- but is there way to _set_ a list value by index without complex joining? If not, perhaps it'd be a good thing to look at in the future -- getting/setting list values by index operator, e.g., `$list[3]` and whatnot.

**Comment by lunelson** [comment]
I was going to write a similar thing. It would be nice if we could get and set list values by index, with the shorter form notation i.e. `$list[0]` as noted above -- any chance of this?

**Comment by nex3** [comment]
All SassScript objects, including lists, are immutable. There's no way to modify it at all.
