### ISSUE TITLE
Growl notifications

### ISSUE THREAD

**Issue by hullabalooMatt** [sass/sass#54]
It would be great to be able to have a Growl notification when SASS has updated the CSS (whilst running with --watch)

**Comment by chriseppstein** [comment]
Related: this will be a feature available via a plugin in Compass v0.11.

**Comment by MoOx** [comment]
Here it is https://rubygems.org/gems/compass-growl

**Comment by hullabalooMatt** [comment]
For the benefit of anyone else who comes here, see the instructions here for use:
https://github.com/Compass/compass-growl
