### ISSUE TITLE
Check if an item is contained in a list?

### ISSUE THREAD

**Issue by lunelson** [sass/sass#543]
I'm looking at switching to SASS from Stylus and trying to figure out how the functions I depend on will carry over. I can't see a native way of checking if something is contained in a list. I was hoping for something like these examples

```
@if $var is in $list {...}
@if contains($list, $var) {...}
```

The native list functions as documented on the sass-lang site seem not do this and I'm imagining that doing it in SassScript is going to perform better--especially if it is programmed by someone other than me; but for the moment I've made it as a `@function` like this:

```
@function contains($list,$var) {
    $contains: false;
    @each $item in $list { @if $item == $var { $contains: true; } }
    @return $contains;
}
```

Is there a better way? Is there a chance of a Sass Script version of this functionality making it in, if it doesn't already exist?

**Comment by nex3** [comment]
Future versions will likely include more built-in list functions such as this.

**Comment by lunelson** [comment]
Cool. I'll use my function then. 

FWIW I corrected my function slightly to avoid possible conflict with a global variable `$contains` (should there happen to be one):

```
@function contains($list,$var) {
    $_out: false;
    @each $item in $list { @if $item == $var { $_out: true; } }
    @return $_out;
}
```

**Comment by brianmcallister** [comment]
Here's a quick and dirty solution that defines a custom Sass function: https://gist.github.com/4088394

**Comment by lunelson** [comment]
Thanks for that @brianmcallister !

**Comment by zaus** [comment]
@lunelson: You could alternately use [`index`](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#index-instance_method) to check for the item, instead of `@each`:

```
@function contains($list,$var) {
    @return (false == index($list, $var));
}
```

After looking at it, you don't really need another function, since you'll check if `contains` equals false anyway -- stick with `index`.

**Comment by lunelson** [comment]
Huh. That's an elegant solution @zaus. You are right, `index` is of course implicitly making the same check, no reason to reinvent it. Thanks for that!

**Comment by adamtomat** [comment]
@zaus: I was having an issue where this line was returning `false` for everything:

```
@return (false == index($list, $var));
```

From the [docs](http://sass-lang.com/documentation/Sass/Script/Functions.html#index-instance_method]) for `index`:

> Returns the position of a value within a list. If the value isn’t found, returns null instead. 

For me to get a `true/false` back I had to modify the statement to:

```
@return (null != index($list, $var));
```

**Comment by lolmaus** [comment]
Check out the [SassyLists](http://sassylists.com/) library by @HugoGiraudel.

``` sass
sl-contain(  (one two three), two  )
```

Demo: http://sassmeister.com/gist/17c6c7759b889374a341

**Comment by lunelson** [comment]
I wonder if they've changed the return value of index to match the way map functions work, i.e. in case of not finding the item it returns `null`, where before it used to return `false`.
In any case the simplest version used to be this:

``` scss
@function contains($list, $item) { @return index($list, $item) != false; }
```

but now I guess it must be written like this:

``` scss
@function contains($list, $item) { @return index($list, $item) != null; }
```

**Comment by lolmaus** [comment]
> index() now returns null rather than false if the value isn’t found in the list.

Source: [Sass Changelog for 3.4.0](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#backwards_incompatibilities__must_read).

Relevant ticket: [Deprecate index()'s false return value](https://github.com/sass/sass/issues/1127).

**Comment by KittyGiraudel** [comment]
> I wonder if they've changed the return value of index to match the way map functions work, i.e. in case of not finding the item it returns null, where before it used to return false.

Yes.

**Comment by lunelson** [comment]
Right, that makes sense. Libsass still returns `false` from `index()` so FWIW [a compatible set of containment functions would look like this](http://sassmeister.com/gist/633bd8db07dc30b764ab)

**Comment by nex3** [comment]
There shouldn't be any reason to explicitly compare the return value of any of these functions to `true`, `false`, or `null`.

**Comment by zaus** [comment]
@nex3 that is a good point -- confirmed (not that I doubted you) http://codepen.io/zaus/pen/Cukty

```
@if( index($list, $var) ) { /* yes */ } @else { /* no */ }
```

which you basically point out in the deprecation ticket.  Since I can't remember that far back, I'm going to assume there was a reason _then_ to compare explicitly, which was also deprecated when the function changed.
