### ISSUE TITLE
Parent selector degradation

### ISSUE THREAD

**Issue by rwz** [sass/sass#545]
In sass 3.1 this worked:

```
.blue
  color: blue

  a&
    border-bottom: 1px solid blue
```

and compiled into 

```
.blue {
  color: blue; }

a.blue {
  border-bottom: 1px solid blue; }
```

In 3.2 however the same code throws exception:

```
Syntax error: Invalid CSS after "a": expected "{", was "&"

              "&" may only be used at the beginning of a selector.
        on line 4 of sass-parent-degradation.sass
```

I believe this change was made here: https://github.com/nex3/sass/commit/face3172930b515ac2040e450d4db3ffe01c31b5

But I don't completely understand the reasoning of why it was blocked, since the mentioned example make perfect sense for me.

Was that intended to disallow this usage or to block other kind of abusement?

**Comment by nex3** [comment]
The parent selector `&` can be replaced by type selectors (e.g. `div`) or universal selectors (e.g. `*`), both of which are allowed only at the beginning of a selector. As such, we can only allow `&` itself at the beginning of a selector, even if in this particular case it wouldn't be replaced with a beginning-only selector.

**Comment by chriseppstein** [comment]
Maybe the validation should be based on how the & is applied instead of using the lowest common denominator?

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by nex3** [comment]
That makes it easier to write mixins that can cause weird semi-local failures. I'd rather just suggest `#{&}` for cases like this (once we support that).

**Comment by Lightw3ight** [comment]
I was just searching to find out how to do what rwz mentiond, sad to hear it was there but taken out

**Comment by beholdr** [comment]
It's sad because there is known [front-end methodology BEM](http://coding.smashingmagazine.com/2012/04/16/a-new-front-end-methodology-bem/) which uses construction like this (working example from LESS) a lot:

```
.block {
  &__element {
    color: red;
  }
}
```

which compiles to `.block__element { ... }`. This is very convenient. Interpolation (`&#{__element}`) does not work either. I'm hope that in future versions of SASS we could get at least interpolations to support DRY principle.
