### ISSUE TITLE
Watch fails when using vim under linux.

### ISSUE THREAD

**Issue by Zer0-** [sass/sass#548]
I've tried this under Debian and ubuntu. Using Gvim edit a scss file and "sass --watch" I get:

"Deleted template detected:"

When I save my file. This doesn't happen every time, but it happens every editing session. The result is that the modified scss file doesn't get recompiled and I have to restart sass --watch.

**Comment by nex3** [comment]
What version of Sass are you using? What RubyGems do you have installed?

**Comment by Zer0-** [comment]
$ sass -v
Sass 3.2.1 (Media Mark)

$ gem list

**\* LOCAL GEMS ***

chunky_png (1.2.6)
ffi (1.1.5)
fssm (0.2.9)
listen (0.5.3)
rb-inotify (0.8.8)
sass (3.2.1)

**Comment by nex3** [comment]
Can you post a full log of an interaction with `sass --watch` where this occurs, preferably with annotations describing your actions during that time? I'm trying to reproduce it locally.

**Comment by Zer0-** [comment]
Alright, here we go. As-detailed-as-can-be instructions to reproduce, seems to work everytime:

```
$ cd ~/Desktop
$ mkdir sasstest
$ cd sasstest
$ mkdir build
$ touch asdf.scss
$ sass --watch .:./build/
>>> Sass is watching for changes. Press Ctrl-C to stop.
  overwrite build//asdf.css
```

ok, now we open up asdf.scss in vim. edit: gvim, not vim - i'm not sure it matters though
hit i to go into insert mode. type out:

```
$stack: ();
```

then escape and :w to save
in our terminal we see:

```
>>> Change detected to: /home/zer0/Desktop/sasstest/asdf.scss
  overwrite ./build//asdf.css
```

back in vim o to open new line, type out:

```
@mixin stack_push($stack, $newvar){
}
```

hit escape, O, tab, and typey out:

```
$stack.append($newvar);
```

escape, :w to save, and in our terminal I get:

```
>>> Deleted template detected: /home/zer0/Desktop/sasstest/asdf.scss
```

**Comment by Zer0-** [comment]
Actually, and I would have saved myself time had I tested this before writing the above,
its not vim-related. Vim I guess deletes the file and creates a new one for writing when you save sometimes.

If you sass --watch a directory, delete a file, then create a new one, it does NOT say "New template detected".

In case that wasn't clear i'm doing:

```
$ sass --watch .:. &
[1] 10882
$ >>> Sass is watching for changes. Press Ctrl-C to stop.
touch asdf.scss
$ >>> New template detected: /home/zer0/Desktop/sas/asdf.scss
  overwrite ./asdf.css
rm asdf.scss 
$      delete /home/zer0/Desktop/sas/asdf.css
>>> Deleted template detected: /home/zer0/Desktop/sas/asdf.scss
touch asdf.scss
$ touch newfile.asdf
$
```

as you can see it doesn't find new files after I delete asdf.scss

**Comment by ghost** [comment]
I ran into this same issue. If you're working in VI / VIM and the watcher is not overwriting or finding a "deleted template", you might try running vim / vi   with the -n option.

-n forces it to not use a swap file. This resolved my issue.
