### ISSUE TITLE
Parser error for unquote() after !important

### ISSUE THREAD

**Issue by passy** [sass/sass#55]
I found an edge case where the latest pre-release (3.1.0.alpha.252) seems to have a parsing error:

`test.sass`:

<pre>
h1
  color: red !important unquote("/* hello */")
</pre>

Compiling with <code>sass --trace test.sass</code> results in

<pre>
/home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:589:in `+': nil can't be coerced into Fixnum (TypeError)
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:589:in `parse_property'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:573:in `parse_property_or_rule'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:554:in `parse_line'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:447:in `build_tree'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:466:in `append_children'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:465:in `each'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:465:in `append_children'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:456:in `build_tree'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:449:in `each'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:449:in `build_tree'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:466:in `append_children'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:465:in `each'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:465:in `append_children'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:322:in `_to_tree'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:291:in `_render'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/engine.rb:238:in `render'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/exec.rb:316:in `process_result'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/exec.rb:41:in `parse'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/../lib/sass/../sass/exec.rb:21:in `parse!'
    from /home/pascal/.gem/ruby/1.8/gems/sass-3.1.0.alpha.252/bin/sass:8
    from /home/pascal/.gem/ruby/1.8/bin/sass:19:in `load'
    from /home/pascal/.gem/ruby/1.8/bin/sass:19
</pre>

**Comment by chriseppstein** [comment]
That's because you can't have a value after !important and you can't have a comment on the same line as property in a .sass file. If you need that flexibility please use scss.

**Comment by passy** [comment]
Okay, I was just wondering because the code worked for previous versions. Thanks for your response.

**Comment by chriseppstein** [comment]
What changed was that Sass used to fudge !important because variables started with ! so it was just a special variable with a value of "!important". But now, the deprecated variable syntax is removed and proper parsing is occurring. So it was an accidental working before -- sorry.

**Comment by passy** [comment]
The only reason I needed this, was to get SmartSprites to work, which I gladly replaced with Compass Sprites.

**Comment by chriseppstein** [comment]
<3
