### ISSUE TITLE
Set unit for whole file

### ISSUE THREAD

**Issue by tomasteicher** [sass/sass#553]
Is it possible to set  unit  for all size properties on one place in file? 
For example, I will set some constant:

$unit = px;

then I would not need to write:

width: 45px;

but just 

width: 45;

and it would be converted to pixels (45px)

Is it possible now using Sass (or SCSS)?

I try to save typing the two chars 'px' so using variable 
width: 45 + $unit 
 is not solution for me
thanks

**Comment by chriseppstein** [comment]
This is not possible, nor is it a good idea. It saves a few keystrokes at the expense of readability and debugging costs.
