### ISSUE TITLE
Options are nil when using sass as plugin in Rails 2.3.11

### ISSUE THREAD

**Issue by graaff** [sass/sass#56]
I'm trying to use bleeding edge sass with Rails 2.3.11 as a plugin. I'm not using haml, so I 've installed the sass 3.1.0.alpha.252 gem. When I try to use this in my rails project I get the following error:

  You have a nil object when you didn't expect it!
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]
    /home/graaff/projects/wvwo/kenniscafe.git/vendor/plugins/sass/rails/../lib/sass/../sass/plugin.rb:80:in `update_stylesheets'
    /home/graaff/projects/wvwo/kenniscafe.git/vendor/plugins/sass/rails/../lib/sass/../sass/plugin.rb:54:in`check_for_updates'
    /home/graaff/projects/wvwo/kenniscafe.git/vendor/plugins/sass/rails/../lib/sass/../sass/plugin/rack.rb:51:in `call'

It looks like the default options (and by extention the options) are never set up, and thus nil.

**Comment by chriseppstein** [comment]
My rails 2.3 app is running great with the latest sass and compass. It must be something environmental. Can you reproduce this with a fresh app?

**Comment by graaff** [comment]
I guess it may have been related to using the alpha version somehow. With sass 3.1.1 things work as expected.
