### ISSUE TITLE
@export at-rule

### ISSUE THREAD

**Issue by ghost** [sass/sass#562]
While I understand it is typical in Sass usage to have multiple partials compile into a single stylesheet, for certain organizational and implementation paradigms it may be advantageous to compile into multiple files from a single.

```
@import "_partial1";
@import "_partial2";
@export "stylesheet1" {
    // styles
}
@export "stylesheet2" {
    // styles
}
```

The above example of course resulting in `styleshee1.css` and `stylesheet2.css` when compiled.

**Comment by Snugug** [comment]
This is a duplicate of https://github.com/nex3/sass/issues/241
