### ISSUE TITLE
Suggestion: @import .scss files that aren't prefixed with an underscore as if they did.

### ISSUE THREAD

**Issue by cjroth** [sass/sass#57]
The ability to import files without compiling them using the _ prefix is quite useful, but it would be nice not have to separate my settings/mixins out from the main CSS. It would be nice to be able to put everything relevant to a single stylesheet in one file, and have the ability to import it with or without including the compiled css in the parent file. Something like @borrow or what ever term is most appropriate.

**Comment by nex3** [comment]
Merging into #353.
