### ISSUE TITLE
Each with index

### ISSUE THREAD

**Issue by Snugug** [sass/sass#570]
I've been using Ruby a bit recently and just fell in love with each with index. I'd love to see this as added as an extension to the current `@each` implementation as follows.

_Current:_

``` scss
@each $animal in $zoo {}
```

_Optional Addition:_

``` scss
@each $animal in $zoo with index $i {}
```

The counter would start at `1` like list functions. While this may have limited uses, it won't break existing code, the mental model is easy enough to pick up on quickly, and the places where this would be used it would save time and easy to miss logic errors.

Please!

**Comment by nex3** [comment]
This is easy enough to do with `@for` and narrow enough in its applications that I don't think it's worth adding to the language.
