### ISSUE TITLE
Proposal: arbitrary &-inheritance.

### ISSUE THREAD

**Issue by egasimus** [sass/sass#578]
One of the main reasons I use a preprocessor is rule nesting - I really fell in love with that feature! However, it easily introduces unnecessary selector specificity, which can be a reason to entirely abandon one of the major conveniences of using a CSS preprocessor - if you care about writing optimized code, that is.

I propose extending the & operator's behavior to work at any point in the selector string. This way,

```
.lol {
    &-wut {
        ...
    }
}
```

would compile to:

```
.lol-wut {
    ...
}
```

And you wouldn't have to do this:

```
.lol {
}
    .lol-wut {
    }
```

Any opinions?

**Comment by Inkdpixels** [comment]
A possible usecase for this feature would be plugin / extension namespaces in templates.

**Comment by Anahkiasen** [comment]
This will probably be taken care of by the refactor of the & selector. At least I think (hope) so.

**Comment by nex3** [comment]
Subset of #286.
