### ISSUE TITLE
"Backwards nesting" of CSS hooks

### ISSUE THREAD

**Issue by stevenklein** [sass/sass#58]
One thing I love about CSS is nesting of styles but it makes for targeting browsers nearly impossible. Consider the following.
# divParent {

```
color:red;
#divChild {
    -moz-transform:scale(1.05);
    &prepend(.ie8) {
        width:105%;
        height:105%;
        position:relative;
        top:-5px;
    }
}
```

}

Essentially, I'd like to be able to prepend specific CSS hooks (e.g. for IE or browsers that don't support a given CSS3 property) but I would have to do those in their own separate nested style tree. Are you following me here? If I'm not making myself clear and this looks interesting to you, shoot me an email at stklein89@gmail.com and I'd be happy to talk about it further.

**Comment by ltackett** [comment]
The ampersand represents the entire selector chain up to that point. You should be able to accomplish what you're after by placing it on the other side of the class you want to prepend to the current context.

```
color:red;
#divChild {
    -moz-transform:scale(1.05);
    .ie8 & {
        width:105%;
        height:105%;
        position:relative;
        top:-5px;
    }
}
```

**Comment by stevenklein** [comment]
ah awesome. thanks for the quick reply!
