### ISSUE TITLE
gc_sweep using sass 3.2.3 and rails 3.2.9 on OS X Lion

### ISSUE THREAD

**Issue by aliibrahim** [sass/sass#581]
The issue basically seems a problem with ruby-1.8.7 then sass. 

Using the sass-gem (sass-3.2.3) and ruby-1.8.7-p371 on OS X Lion is causing the following  problem again:-

/sass/scss/parser.rb:1085: [BUG] gc_sweep(): unknown data type 0x0(0x12a0bf3f8)

Any solutions if i dont want to upgrade to ruby 1.9.2 ?

**Comment by nex3** [comment]
Do you have a way to reproduce this consistently?

**Comment by aliibrahim** [comment]
Yes, whenever i call @import "foundation"; in the application.scss the ruby server crashes with ruby-1.8.7-p371. However, i was able to solve this issue by using REE, so this is more of a ruby issue. Hope this helps.

**Comment by nex3** [comment]
I'm going to close this as a Ruby bug.
