### ISSUE TITLE
unit() doesn't like variables.

### ISSUE THREAD

**Issue by pyronaur** [sass/sass#585]
```
$some_value: 16
$base_font_size: $some_value + px
$unit: unit($base_font_size)
@debug $unit
@debug $some_value
@debug $base_font_size
```

Generates:

```
Syntax error: "16px" is not a number for `unit'
```

I don't even get to the debug messages. I've tried setting $base_font_size with quotes and interpolation, but that didn't help as well. Neither did "unquote" before running the unit.

**Comment by Snugug** [comment]
The issue is your $base_font_size is now a string not a number. Multiply it by 1px, don't add px

**Comment by pyronaur** [comment]
I figured this out just like 3 minutes ago :+1: 
Somehow it helps to complain sometimes...
