### ISSUE TITLE
Things for SASS.

### ISSUE THREAD

**Issue by ghost** [sass/sass#586]
I came up with different things for SASS.
- RegEx for post processing of variables. Examples are present.
- (1)Debug the design. This means that it is not necessary to write extra design but with some different values.
- (2)Additional reading with "calc ()". I say this not by accident. I want to make life easier for the servers and move all calculations to the client. Also make the website much (much) more flexible. And of course do not forget about backward compatibility (eg Opera, which is constantly yelling).

1) Example of this design.

```
background-image: [-moz-element(#canvas) || -webkit-canvas(canvas)];
```

2) Simple sample

```
width: 100px + 100px;
```

to:

```
//width: calc(100px + 100px); //Not needed
width: 200px;
```

2.1) Hardware sample

```
width: 100% + 100px;
```

to:

```
width: calc(100% + 100px);
//width: 200px; //SASS, BROKEN
```

**Comment by Anahkiasen** [comment]
How is it a good thing to move calculation to the client ? I mean, using cal when percentages are included I fully understand, but I don't see the point of letting everyong doing your pixels/ems/rems calculations when those could be preprocessed and never to be talked about again ?

**Comment by nex3** [comment]
We're currently not planning on compiling Sass arithmetic to `calc` expressions until we can be very confident that every major browsers supports them.
