### ISSUE TITLE
Imports using url() should be processed

### ISSUE THREAD

**Issue by bdkjones** [sass/sass#592]
The W3C specification for CSS 3 states that these two lines are exactly equivalent. See here: http://www.w3.org/TR/CSS21/cascade.html#at-import

```
@import "someFile.css";
@import url(someFile.css);
```

Currently, Sass will not attempt to compile any imported file that is brought in using the url() syntax. I propose that this be changed so that:

```
@import url(someFile.scss);
```

causes Sass to process this imported file. Sass should look for the presence of "://" and ".css" within the string contained by the parentheses. If either of those exist, THEN the import statement should be copied, verbatim, to the compiled output. The presence of a media type can also trigger the verbatim copy (as it currently does). 

The reason I propose this change is to bring Sass in line with the W3C standard. I've had numerous people email me something to the effect of "CodeKit doesn't compile the code in my file, X!" only to find that the user does not realize the subtle effect of using the url() syntax as opposed to the "" syntax.

Sass should adhere to the W3C spec when possible. In this case, it is possible.

/cc @chriseppstein

**Comment by bdkjones** [comment]
I would also add that Less _does_ process Less files brought in with the url() syntax. (Although Less's @import statement support is much more rudimentary. It does not allow comma-separated multi imports and so forth.)

Folks switching to Sass from Less stand a good chance of being caught unawares by Sass's non-standard treatment of url() imports. Unless there is an overwhelming reason for the current behavior, I strongly suggest adopting the W3C spec.

/cc @chriseppstein

**Comment by nex3** [comment]
This is a major semantic change. `url()` is one of the four means Sass uses to try to detect plain-CSS imports (along with `://`, `.css`, and media specifiers). If we change this, we'll break any stylesheet that relies on `url()` to distinguish plain-CSS imports. Even if we were to decide to make the change, it would have to go through a deprecation process that would take multiple Sass versions to end up with the semantics you suggest.

There's also a good reason for the behavior as it stands now. SCSS is advertised as a superset of CSS, and we take that very seriously. Currently the _only_ piece of syntax that can have a different meaning in SCSS than it does in CSS is `@import`. `url()` is an important criterion we use to minimize the number of cases where that distinction matters.

Ultimately, the solution to this -- as to so many of our `@import` woes -- will be our eventual revision of import semantics. This revision will include a different name that won't conflict with CSS, at which point we can have much more freedom in our interpretation of the arguments.

**Comment by bdkjones** [comment]
I disagree with this analysis. The url() and quotes styles should be interchangeable and Sass should require the .css extension for a regular CSS import. In other words, when an extension is omitted in an import statement, sass should attempt to add *.scss and *.sass only.

It's simple and clean: you can omit the extension as long as you're importing another Sass file. Anything else requires an extension.

Additionally, you cannot rightly call SCSS a superset of CSS if _any_ standard CSS behavior changes in SCSS. In CSS, quotes and url() are interchangeable, so they must also be in a superset.

I don't know what you've got planned for the import overhaul, but I would seriously reconsider the decision to close this issue simply because it's going to be a little work. The current behavior of url() is, admittedly, incorrect. I've opened the same request for Stylus and Less already treats url() correctly. Sass runs the risk of being the only major pre processed languages that handles imports incorrectly.

And lastly, just because "that's the way it's always been" doesn't mean that's the way it SHOULD be.

**Comment by nex3** [comment]
The issue isn't work on our part. It's a painful migration process for our users. Everyone who currently uses `url()` imports would get a deprecation message through Sass 3.3. The functionality you discuss wouldn't work until Sass 3.4, at which point everyone who didn't heed the deprecation message gets broken. And by then we're likely to have an alternate import syntax be recommended anyway.

I don't buy your argument that we're not following the CSS spec. Sass is not CSS. The spec says nothing about how preprocessors should treat `@imports`. It explains how `@imports` should be handled by the browser, and the current handling of the behavior of `url()` makes SCSS adhere more closely to that behavior.

Yes, Less treats `url()` as you suggest, but the other side of that coin is that fewer valid CSS documents are also valid Less documents.
