### ISSUE TITLE
Request: Command line output in JSON format

### ISSUE THREAD

**Issue by bdkjones** [sass/sass#593]
I would like Sass's command line utility to optionally return errors in a JSON format. I envision something like this:

```
errorMessage: "This is the reason Sass failed to compile."
file: "/path/to/some/file.sass"
line: 34
character: 19
code: "This is the line of Sass code containing the error"
stacktrace: "junk here"
```

The reason I ask is that having the output in a parseable format allows _infinitely_ better integration of Sass in third-party applications that want to do custom formatting of the Sass compiler's return messages. 

I strongly recommend that you adopt JSON over alternatives such as CSV and XML. JSON is cleaner, smaller, more easily read by humans (in case they need to do so), faster to parse in almost every instance and is quickly replacing XML as the default on the modern web. 

/cc @nex3 @chriseppstein

**Comment by chriscoyier** [comment]
+1

I really like the idea of third party apps being able to do more with the error data. Instead of having to parse text themselves. In a perfect world all preprocessors would standardize on an error output format!

**Comment by unr** [comment]
+1

**Comment by manovotny** [comment]
+1

**Comment by whosdustin** [comment]
+1

**Comment by andycrum** [comment]
+1

**Comment by atEverychance** [comment]
+1

**Comment by polymetis** [comment]
+1

**Comment by demogar** [comment]
+1

**Comment by MichaelArestad** [comment]
+1

**Comment by jacobdubail** [comment]
+1

**Comment by steve228uk** [comment]
:+1:

**Comment by micahgodbolt** [comment]
+1

**Comment by leng-yang** [comment]
+1

**Comment by maxhoffmann** [comment]
+1

**Comment by andimal** [comment]
+1

**Comment by jakepetroules** [comment]
+1

**Comment by ferdinandsalis** [comment]
+1

**Comment by banunn** [comment]
+1

**Comment by BeMoreDifferent** [comment]
+1

**Comment by vanjacosic** [comment]
+1

**Comment by john-riordan** [comment]
+1

**Comment by normanposselt** [comment]
+1

**Comment by kilokeith** [comment]
+1

**Comment by paulgrock** [comment]
+1

**Comment by Meroje** [comment]
:+1:

**Comment by CiTroNaK** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by baudoin** [comment]
+1

**Comment by joshlasdin** [comment]
+1

**Comment by leepowelldev** [comment]
+1

**Comment by b00y0h** [comment]
+1

**Comment by maxsteenbergen** [comment]
+1

**Comment by tiagofranco** [comment]
+1

**Comment by Vinsanity** [comment]
+1

**Comment by JohnCHarrington** [comment]
+1

**Comment by 28Bytes** [comment]
+1

**Comment by marcaube** [comment]
+10 ... why not

**Comment by chriseppstein** [comment]
Please stop adding +1s. We will review this issue on it's merits, not popularity.

**Comment by mgrn0** [comment]
+2

**Comment by petehotchkiss** [comment]
+1... Chris, surely popularity is a measure of merrit.

**Comment by paddykontschak** [comment]
+1

**Comment by stephenway** [comment]
+1

**Comment by ElmsPark** [comment]
+1

**Comment by michaelryancaputo** [comment]
+1

**Comment by JesusGarciaValadez** [comment]
+1

**Comment by nex3** [comment]
The +1s are indeed not helpful.

I do like this idea, though.

**Comment by nex3** [comment]
The [json-output branch](https://github.com/nex3/sass/tree/json-output) has the beginning of support for that. A lot more is needed:
- There's no error-specific metadata, such as the line offset for syntax errors. There is some metadata for warnings, though.
- There's no documentation.
- There are no tests for the JSON formats of the warnings with metadata.
- Warnings don't have Sass backtraces (see also #605).

**Comment by gajus** [comment]
+1

**Comment by bdkjones** [comment]
Any idea if/when this might make it into the official release? It would _really_ be handy!

**Comment by nex3** [comment]
Unfortunately, it's not especially high-priority. It might be a good thing for someone other than Chris or myself to work on.

**Comment by ghost** [comment]
+one

**Comment by eriwen** [comment]
Hey guys... I know Ruby and I :heart: Sass, so I'd like to take a crack at this. However, I was wondering if I still ought to start from the [json-output branch](https://github.com/nex3/sass/tree/json-output). It seems like there is some work there toward the feature, but the branch itself seems to have diverged significantly from stable. 

@nex3 @chriseppstein In your opinion, would it be worth it to make a new branch from stable and pull in the bits of work related only to JSON output? I really, really want to avoid an ugly merge. Thanks :)

**Comment by chriscoyier** [comment]
For use-case motivation, I'm working on inline error messaging in CodePen for Sass and I'm having to do RegEx stuff (thx @chriseppstein) on the error strings to get the numbers I need to do it. http://cl.ly/PZ7s

**Comment by bdkjones** [comment]
Chris - 

Good luck! I tried that approach with Compass in CodeKit, but found that changes from one version to the next resulted in different messages that broke my parsing. That's why CodeKit just returns the whole message; it was too much to test and keep up with as new versions came out. 

I'm super excited that someone is taking a crack at JSON output! That would be amazing!

-Bryan

**Comment by nex3** [comment]
@eriwen The json-output branch should be pretty straightforward to merge with the latest master. That's definitely the best place to start.

**Comment by eriwen** [comment]
@nex3 Thanks for the info. Couple questions:
- I see that the `sass_backtrace` in JSON has file and line number info for SyntaxErrors. Is there other metadata we need for SyntaxErrors?
- Are you also thinking we need JSON handling/metadata on other errors?
- I'm not yet sure how to add sass backtraces to warnings. Do you think this is necessary for the first implementation or can you give me any pointers? Thanks.

**Comment by bdkjones** [comment]
I would be totally happy without the backtrace. In fact, that's a huge part of why I'm looking to do custom error formatting: to get rid of the backtrace!

**Comment by eriwen** [comment]
I'm not convinced that the metadata for syntax errors is quite what the maintainers were thinking, so that should be closely reviewed. I am having a hard time writing a test for the JSON output from SyntaxErrors, that is still pending. 

Looking forward to your feedback, guys.

**Comment by chriscoyier** [comment]
I think it would be cool to publish the JSON format in a kinda neutral place at some point, so we can point every other preprocessor maintainer to it. "Hey guys, look at this format, we could standardize error output based on this and the world will rejoice." 

e.g. naming like error-line and error-message rather than anything specific to Sass (unless it's really specific to Sass, like the backtrace).

**Comment by bdkjones** [comment]
@chriscoyier Could not agree more.

I would suggest looking at the names for JSLint and JSHint error objects, as they do a pretty good job. They're generally camelCase, like this:

```
errorLine
errorColumn
errorNumber (the lints return many, many errors)
errorLevel (can be warn or error, depending on severity of problem)
etc.
```

Where possible, I would adopt the naming conventions from JSHint/JSLint.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.

**Comment by nex3** [comment]
Note that this idea is very similar to https://github.com/sass/dart-sass/issues/248.
