### ISSUE TITLE
Compound assignment operators

### ISSUE THREAD

**Issue by tomsseisums** [sass/sass#596]
I was looking for a functionality to access property values with SASS, and stumbled upon [this closed issue](https://github.com/nex3/sass/issues/521) where I also left [my thoughts on it](https://github.com/nex3/sass/issues/521#issuecomment-11435996).

After writing of the comment, I thought of an even better option - [Compound assignment operators](http://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Compound_assignment_operators).

That's a list of C / C++ op's, but those can be found in most languages.

It would come in handy for SASS in the same scenario as I specified in [my comment on 521](https://github.com/nex3/sass/issues/521#issuecomment-11435996).

Modified example:

``` sass
.row
{
    width: 200px;

    &.input
    {
        width: +=50px; // 250px
    }

    // or
    &.input
    {
        width: *=0.8; // 160px;
    }
}
```

Of course, it would be most useful, if it would expand upon issue 521, to work in case of:

``` sass
.row
{
    padding: 0 10px;

    &.input
    {
        padding-left: +=10px; // 0px 10px 0px 20px (top right bottom left)
    }
}
```

The syntax is close to one available in jQuery.

**Comment by nex3** [comment]
This has the same confusion issues as #521. There's no way to get the computed values of these properties when precompiling, so the results of the operations are going to be very difficult to reason about.
