### ISSUE TITLE
Add inline-image() to SASS core

### ISSUE THREAD

**Issue by vrubleg** [sass/sass#597]
I think that inline-image() from compass is too common and it should be a part of SASS core. Also it concerns the functions image-width and image-height. It's annoying to use compass every time when I am going to use inline images.

**Comment by MoOx** [comment]
In this case, this involve a lot of stuffs having to be merged in Sass core.
What the problem of doing `@import "compass"` ?.

btw, it's Sass not SASS

**Comment by nex3** [comment]
This requires a notion of a project's asset locations and URLs, which Compass has but Sass does not.
