### ISSUE TITLE
Variable grouping

### ISSUE THREAD

**Issue by jshb** [sass/sass#599]
I'd love to see some kind of variable grouping, perhaps working something like this:

``` sass
$colours: {
       $turquoiseblue: #00ffef;
       $sandybrown: #f4a460;
       $deeplemon: #f5c71a;
}

a {
       color: $colours.deeplemon;    // #f5c71a
}
```

**Comment by Anahkiasen** [comment]
+1

**Comment by matthewcopeland** [comment]
@jshb I see how defining your variables inside an array could dry out your code and be useful.

Do you have a gist that would help me to understand a use case for it?  The example you gave is clear, but the simplified use-case doesn't require the functionality you mentioned.

Current functionality allows you to make arrays of variables. Does that satisfy the majority of your use-cases?
https://gist.github.com/4216347
https://gist.github.com/4352329

**Comment by Snugug** [comment]
While not namespaced, this is functionally 100% doable now.

```
$colours: #00ffef, #f4a460, #f5c71a;

a {
  color: nth($colours, 3);
}
```

**Comment by Anahkiasen** [comment]
Yeah but you need to go back and forth between your property and the array all the time to remember which index is which. This can actually be solved by advanced lists and hashes but I don't know where that feature's at for the moment in terms of progress.

**Comment by Snugug** [comment]
In theory, yah, but in practice I find I rarely need to go back to my source variable to figure out what is what. In either case, I think I agree that this is probably going to be solved with the association data type they were talking about in [#463](https://github.com/nex3/sass/issues/463) but likewise I haven't found any movement on that.

**Comment by jshb** [comment]
In my case I have a large list of colours: http://pastebin.com/0cRkiDXJ

The list is long enough that I can't reliably avoid unintentionally using variable names elsewhere. 

An obvious solution would be to add colour-\* to each variable name, and while:

``` sass
$colour-lawngreen:#7cfc00;
$colour-lemon:#fff700;
$colour-lemonchiffon:#fffacd;
$colour-lemoncurry:#cca01d;
$colour-lemonglacier:#fdff00;
$colour-lemonlime:#e3ff00;

a {
      color:$colour-lemonlime;
}
```

doesn't seem as neat to me as: 

``` sass
$colour: {
      $lawngreen:#7cfc00;
      $lemon:#fff700;
      $lemonchiffon:#fffacd;
      $lemoncurry:#cca01d;
      $lemonglacier:#fdff00;
      $lemonlime:#e3ff00;
}

a {
      color:$colour.lemonlime;
}
```

this is probably an ok fix.

But where I see my proposed method really showing its worth is with packaging Sass code such that it can be reused or distributed. Particularly good if mixins could also be nested within variables.

**Comment by Snugug** [comment]
You're now moving away from variable namespacing and into general namespacing. Storing mixins in variables is a terrible idea, with that thinking in mind, what this actually sounds like (and for that matter, looks like) is the next generation @import statements that are being talked about.

**Comment by jshb** [comment]
You're right, the same could be achieved with #353.
