### ISSUE TITLE
Disabling cache results in slow Compass compilation speed

### ISSUE THREAD

**Issue by vvasabi** [sass/sass#606]
Not sure if this is a feature of caching and not a bug, but the compilation speed is much slower when caching is disabled.

For example:

```
$ cat test.scss

@import "compass";

$ time sass -C --compass test.scss > /dev/null

real    0m2.502s
user    0m2.385s
sys 0m0.056s
$ rm -rf .sass-cache
$ time sass --compass test.scss > /dev/null

real    0m1.243s
user    0m1.153s
sys 0m0.049s

$ sass --version
Sass 3.2.4 (Media Mark)
```

Note that the use of `@import "compass";` is to make it easier to illustrate the point. In my production code, having multiple `@import "compass/*/*";` statements suffers the same problem.

**Comment by anthonyshort** [comment]
That's the entire point of caching :)

**Comment by vvasabi** [comment]
Sure, but I’m curious why it would make such a difference even when there is no existing cache. :)

**Comment by nex3** [comment]
Caching is used during compilation to avoid re-parsing the same files multiple times. If it's disabled, that functionality is disabled along with it, which will cause compilation to slow down significantly when the same file is imported multiple times.

**Comment by vvasabi** [comment]
So it is indeed a feature and not a bug. Thanks for the clarification.
