### ISSUE TITLE
Bug in parser with @extend when the class to extend is used in the code

### ISSUE THREAD

**Issue by firedev** [sass/sass#607]
Example:

```
test { @extend .rc; }
.rc {color: white;}
.prices span.pill span.rc {color: red;}
```

Should produce:

```
.test, .rc {color: white;}
.prices span.pill span.rc {color: red;}
```

Instead:

```
WARNING on line 1 of style.scss: "test" failed to @extend ".rc".
  No selectors matching ".rc" could be unified with "test".
  This will be an error in future releases of Sass.
  Use "@extend .rc !optional" if the extend should be able to fail.
```

**Comment by Anahkiasen** [comment]
I think you need to define the class to extend before the extended class no ?

**Comment by firedev** [comment]
No, it works once you remove `span.rc`

However after some fiddling I found a way to make it work. I put the `test { @extend .rc; }` part in a separate file and `@import`ed it from the main `.scss`

`Sass 3.2.4 (Media Mark)`

**Comment by firedev** [comment]
Unfortunately after migrating to Compass this problem appeared again. Interesting to note that despite multiple warnings per each `@extend`, scss is compiled correctly.

**Comment by jdeblank** [comment]
I am experiencing this same issue as @firedev after upgrading from 3.1.20 to 3.2.4 (also using compass 0.12.2). Thought I was doing something wrong, but maybe it is conflicting on which selector to extend? As @firedev said, when you remove the `span.rc` then the warning disappears. If this is deliberate then maybe the warning could reflect this? I found "No selectors matching ".rc"" to be misleading.

Edit: adding in more details of my environment.

**Comment by firedev** [comment]
The fun part is - .css file is compiled correctly. But for each `@extend` it produces 3 or 4 warnings anyway.

**Comment by jdeblank** [comment]
True, but I just tested with sass-3.3.0.alpha.61, they are no longer warnings but errors, and the css is not compiled.

**Comment by gotardo** [comment]
I am having the same issue when trying to extend a selector like this:
    label     {    @extend .aClass    }
Instead, I have to extend a class:
    .aLabelClass    {    @extend .aClass    }
