### ISSUE TITLE
High CPU usage on Windows 7 64bits with --watch

### ISSUE THREAD

**Issue by pocesar** [sass/sass#608]
I've been using SCSS for quite a while now, but I used to manually execute the command line upon save, but that would sometimes not compile the scss file into the .css, so I decided to start using --watch. The problem is, when I'm dev'ing with Phpstorm, `ruby.exe` process keeps at least 25% of CPU usage on my core i3 on windows 7 64 bits, lastest sass gem, using ruby installer 1.9.3-p362, and my notebook overheats, I need to turn it off, wait a while, then try again.

I have no ruby experience, I don't know if there's any way to increase the loop "sleep" so it won't be as CPU intensive. Couldn't the "wait" inside the loop be higher? Like 50ms I guess. In the time I used to do win32 programming, I would use sleep(1) inside loops so I wouldn't use 100% of CPU, but that's not an interpreted language, so I have no clue about how it would work out in ruby.

**Comment by nex3** [comment]
Do you have the [WDM gem](https://rubygems.org/gems/wdm) installed? With that the process won't do any manual polling; it'll wait for Windows to notify it that changes have happened, and shouldn't use any substantial CPU time when there are no changes.

If you're still seeing CPU issues with WDM, that's probably an issue with [the listen library](/guard/listen), which Sass uses to watch for filesystem changes.

**Comment by pocesar** [comment]
installed WDM, that did nothing to the CPU usage, still the same... what else can I try?

**Comment by nex3** [comment]
You'll have to ask the folks who work on guard/listen.

**Comment by thibaudgg** [comment]
Can you try to increase `listen` latency? (I don't know if `sass` let you set that). @Maher4Ever have you another idea?

**Comment by pocesar** [comment]
I don't think you can set it, I decided to execute a `bat` file trigger after saving the file, but the compile time it takes around 7 seconds to start and then compile. Is this normal?

**Comment by thany** [comment]
Two and a half years later, this is still a problem.

See also [this issue](https://github.com/Compass/compass/issues/1817) I raised with Compass.
And [this issue](https://github.com/guard/listen/issues/295) I raised with Listen.

I feel like we are being sent back and forth between Sass/Compass, Listen, and WDM. Can you guys please get this problem sorted already?

**Comment by nex3** [comment]
According to @Maher4Ever on a3031856b22bc834a5417dedecb038b7be9b9e3e, the native Windows watcher is much slower than polling, so Sass [currently has it disabled](https://github.com/sass/sass/blob/stable/lib/sass/plugin/compiler.rb#L318-L320). You can try removing the `|| Sass::Util.windows?` there and seeing what that does to the latency and CPU usage.

**Comment by thany** [comment]
First of all, that's 3 years ago. Things would've changed in the mean time. Secondly, if it's a bug in some other component (I lost count), then is a bug report filed with its developers? And the status is...?

Lastly, you do agree that it doesn't really get much slower than 100% CPU usage, right? So anything "much slower" will still be using 100% CPU time.

**Comment by nex3** [comment]
No Sass developer has a Windows development machine; we rely entirely on user reports to know what works and what doesn't. The best information we have is that native watcher support doesn't work, and polling works fine for most users. If you can show us that native support is usable now, we'll start using it again, but until then we won't.

**Comment by rgelb** [comment]
This feature is still broken.  I have a pretty extensive SASS import dependency structure (https://i.imgur.com/FjHb77L.png) and sass --watch literally keeps on pounding on the entire directory structure over and over again, even if no changes are being made.  I confirmed this using the procmon tool.

Whatever library is being used to watch the disk does so by polling.  The library should subscribe to file change events instead.

**Comment by AndOne1974** [comment]
i have also tried that without much luck, there is still high cpu load.

win 7, 64bit
dart-sass --version:  1.23.0 compiled with dart2js 2.5.1
node --version:  v10.16.3
