### ISSUE TITLE
SASS regeneration on CSS error

### ISSUE THREAD

**Issue by adamcable** [sass/sass#613]
Hi,

We're using sass --watch on a directory on a FreeBSD server.
If a SCSS file is changed and has an error in it, we see sass constantly recompile the CSS until the error is fixed.

Because of this, we see high CPU load - is there a way to stop it recompiling?

Thanks,
Adam

**Comment by nex3** [comment]
Can you provide a shell script to reproduce this issue that's as simple as possible?

**Comment by adamcable** [comment]
Hi Nathan,

Thanks for the response.

We were doing a simple monitor (/usr/local/bin/ruby18 /usr/local/bin/sass --watch -l /styles:/styles) but can’t seem to replicate the issue now we’ve updated the gem.

Adam

**Comment by nex3** [comment]
Closing since it's not reproducible.
