### ISSUE TITLE
type-of() does not recognize new dppx resolution unit, returns 'string'

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#614]
The Sass function returns 'number' for strings with unit values (em, px, pt, rem, dpi, dpcm, etc.). But, right now it doesn't recognize the new `dppx` resolution unit and returns 'string'.

Breakpoint issue where this came up: https://github.com/canarymason/breakpoint/pull/31#issuecomment-11861926

Unfortunately I'm strictly scss, no ruby, so can't make a pull request. Thanks for taking a look.

**Comment by nex3** [comment]
This works for me. `type-of(5dppx)` returns `"number"`. In general, Sass is unit-agnostic; it considers any number followed by a series of letters to be a number with a unit. For example, `type-of(5asdf)` also returns `"number"`. It has some special handling for converting between units (e.g. it knows that `1in` is the same as `2.54cm`), but it should handle unknown units gracefully.

**Comment by robwierzbowski** [comment]
Huh, right you are. Looks like I got tangled trying to debug a problem.
