### ISSUE TITLE
Nesting variables

### ISSUE THREAD

**Issue by Daniel-Hug** [sass/sass#616]
This is probably a really new idea, but I really think it would improve Sass. It would be nice if we could nest Sass variables (kinda like nested selectors & properties):

<br>So This:

```
@nav-bar {
  @height: 40px;
  @link-color: blue;
}
```

<br>Would be the equivalent of this:

```
@nav-bar-height: 40px;
@nav-bar-link-color: blue;
```

Thus concatenating nested variables with a hyphen.

<br>It would make for a much cleaner set of variable declarations at the start of the file. Thoughts?

**Comment by Anahkiasen** [comment]
No it has actually already been discussed #567. A lot. #440 #599 #462

**Comment by nex3** [comment]
As @Anahkiasen mentioned, this is a duplicate of many other issues.
