### ISSUE TITLE
Unicode glyph not being compiled properly

### ISSUE THREAD

**Issue by chris-pearce** [sass/sass#620]
I'm using Sass version 3.2.4.

I have this Sass:

``` scss
/* A better looking horizontal rule */
hr {
    @extend %mrg-on;
    color: $color-grey-lighter;
    border: 0;
    border-bottom-width: 1px;
    border-bottom-style: solid;
    position: relative;
    /* Pesudo element for a more stylised `hr` */
    &:after {
        content: "§";
        position: absolute;
        top: 0;
        right: 0;
        left: 0;
        line-height: 0;
        text-align: center;
    }
}
```

Notice the Unicode glyph in the `:after` `content` value, it's being compiled too:

``` scss
content: "┬º";
```

When I'm using the actual code for Unicode characters e.g. `content: "\201D";` then no problem.

**Comment by nex3** [comment]
I'm going to guess that your system encoding is not set to the same encoding that you're using in your file. Sass (or more accurately Ruby) reads the system encoding information to determine what default encoding to use when reading files, and if the encoding that your system lists as the default isn't the same as the encoding the file actually uses you'll get weird errors like this.

There are various OS-specific ways of configuring your system encoding, but a more robust solution would probably be  to add `@charset "utf-8";` at the top of your SCSS file.

**Comment by chris-pearce** [comment]
Thanks.

I do specify the charset at the top of my style sheets:

`@charset "utf-8";`

But no dice.

I wouldn't know about looking at my system encoding, before using Sass using the `@charset` rule or setting it in my `.htaccess` file always did the job.

**Comment by nex3** [comment]
Sass should use `@charset` in preference to any other method of determining the encoding.

Another possibility is that you're using an old version of Ruby. Ruby 1.8.\* doesn't have good encoding support. Could that be it?

**Comment by chris-pearce** [comment]
Doing `ruby -v` returns:

`ruby 1.9.3p362 (2012-12-25) [i386-mingw32]`

I only set-up Sass 2 weeks ago.

**Comment by nex3** [comment]
What do you get if you run `ruby -e 'p [Encoding.default_external, Encoding.default_internal]'`?

Another thing to try is creating a small file called `test.scss` containing only `a {b: "§"}`. Then run `ruby -r sass -e 'p Sass::Engine.new(File.read("test.scss"), syntax: :scss).render.encoding'` and tell me what that prints.

**Comment by chris-pearce** [comment]
For the 1st command I get:

`[#<Encoding:CP850>, nil]`

I'll try the other thing now.

**Comment by chris-pearce** [comment]
2nd part didn't seem to work, I ran the command in the same dir as where the `test.scss` file lives (I'm on Windows), it spat out all this:

```
c:\wamp\www\Cheetah\sass>ruby
s"), syntax: :scss).render.enc
c:/wamp/www/Cheetah/sass/parti
 found or unreadable: compass/
Load path: c:/wamp/www/Cheetah
        from (sass):36
        from C:/Ruby193/lib/ru
_node.rb:67:in `rescue in impo
        from C:/Ruby193/lib/ru
_node.rb:45:in `import'
        from C:/Ruby193/lib/ru
_node.rb:28:in `imported_file'
        from C:/Ruby193/lib/ru
_node.rb:37:in `css_import?'
        from C:/Ruby193/lib/ru
rs/perform.rb:215:in `visit_im
        from C:/Ruby193/lib/ru
rs/base.rb:37:in `visit'
        from C:/Ruby193/lib/ru
rs/perform.rb:98:in `visit'
        from C:/Ruby193/lib/ru
rs/perform.rb:225:in `block in
        from C:/Ruby193/lib/ru
rs/perform.rb:225:in `map'
        from C:/Ruby193/lib/ru
rs/perform.rb:225:in `visit_im
        from C:/Ruby193/lib/ru
rs/base.rb:37:in `visit'
        from C:/Ruby193/lib/ru
rs/perform.rb:98:in `visit'
        from C:/Ruby193/lib/ru
rs/base.rb:53:in `block in vis
        from C:/Ruby193/lib/ru
rs/base.rb:53:in `map'
        from C:/Ruby193/lib/ru
rs/base.rb:53:in `visit_childr
        from C:/Ruby193/lib/ru
rs/perform.rb:107:in `block in
        from C:/Ruby193/lib/ru
rs/perform.rb:119:in `with_env
        from C:/Ruby193/lib/ru
rs/perform.rb:106:in `visit_ch
        from C:/Ruby193/lib/ru
rs/base.rb:37:in `block in vis
        from C:/Ruby193/lib/ru
rs/perform.rb:126:in `visit_ro
        from C:/Ruby193/lib/ru
rs/base.rb:37:in `visit'
        from C:/Ruby193/lib/ru
rs/perform.rb:98:in `visit'
        from C:/Ruby193/lib/ru
rs/perform.rb:7:in `visit'
        from C:/Ruby193/lib/ru
ode.rb:20:in `render'
        from C:/Ruby193/lib/ru
15:in `_render'
        from C:/Ruby193/lib/ru
62:in `render'
        from -e:1:in `<main>'
```

**Comment by nex3** [comment]
It looks like a lot of that stack trace was cut off...

**Comment by chris-pearce** [comment]
Yeah I can't run that test, is it possible you can run it as I'm not a power terminal user? I'm doing the right thing declaring the `@charset` in my style sheet so it shouldn't be mangling it when compiling, annoying as I have to remember to update in the compiled style sheet.

**Comment by nex3** [comment]
The point of the test was to diagnose what's going on in your system that's causing it to ignore the `@charset` directive, so you'll need to run it.

**Comment by chris-pearce** [comment]
Yeah sorry I just wasn't have much luck running that test, finally I think I've done it:

`#<Encoding:CP850>`

Does that look right?

**Comment by chris-pearce** [comment]
Any ideas?

**Comment by nex3** [comment]
Sorry, I was on vacation all last week so I haven't had a chance to check back until now. One more experiment to try is to do the same thing as last time but with the following in your `test.scss` file:

``` scss
@charset "utf-8";
a {b: "§"}
```

**Comment by chris-pearce** [comment]
It returns this:

`#<Encoding:UTF-8>`

Progress?

**Comment by chris-pearce** [comment]
Any ideas?

**Comment by nex3** [comment]
Okay, I have a theory as to what's going on. Sass is correctly determining the encoding of your file as UTF-8, and compiling it to a UTF-8 document, which it then saves. However, since your system has its encoding set to CP850, when you open up the file to examine the output whatever you're viewing it in treats it as CP850, causing it to look weird. Note that the UTF-8 bytes for `§`, `0xC2 0xA7`, are interpreted as `┬º` in CP850.

**Comment by chris-pearce** [comment]
OK thanks for the heads up. So is there a way around this or do I have to always make sure to use the Unicode code rather than embedding the actual glyph in my style sheet:

> When I'm using the actual code for Unicode characters e.g. `content: "\201D";` then no problem.

It's a bit of a pain always having to use the code as you cannot always get your hands on it.

**Comment by nex3** [comment]
The best way to handle this is probably to get your server to serve the CSS file as UTF-8. How to do this will vary from server to server.

**Comment by benfrain** [comment]
Not sure if it helps you but we just found a similar problem. Turned out that quotes on one of the font styles were of a different encoding (probably pasted in from elsewhere) and it caused the entire file to be encoded in a different format.

**Comment by KimvdLinde** [comment]
@charset "utf-8"; at the top of each page solved my issues with this......
