### ISSUE TITLE
bubbling up from mixin declaration to include parents as content

### ISSUE THREAD

**Issue by brewster1134** [sass/sass#621]
Not sure if there is existing functionality for this, but I am looking for a way to declare a mixin that will collect the parent properties and include it in the content.

``` sass
=forMobile
  html.mobile
    @content

body
  .foo
    @include forMobile
      a: b
```

would render as:

``` sass
html.mobile
  body
    .foo
      a: b
```

I have just begun to look at the sass code, but if someone more familiar with this codebase could comment on this. This would allow to do things like:

``` sass
body
  .foo
    @include mixinA
      a: b
    @include mixinB
      a: c
```

instead of:

```
@include mixinA
  body
    .foo
      a: b
@include mixinB
  body
    .foo
      a: c
```

From how I understand it, it would need something like `@include_tree` /  `++` directives.

**Comment by brewster1134** [comment]
Here is a quick test...

``` ruby
assert_equal <<CSS, render(<<SASS)
.foo {
  .bar {
    a: b; } } }
CSS
@mixin foo
  .foo
    @content
.bar
  @include_tree foo
    a: b
SASS
```

**Comment by nex3** [comment]
Why not just write the following?

``` scss
=forMobile
  html.mobile &
    @content
```

**Comment by brewster1134** [comment]
It's so simple!  Still have a small issue though...

When I use the mixin at the root level I get the error `Base-level rules cannot contain the parent-selector-referencing character '&'`

Looking at the `resolve_parent_refs` method in `comma_sequence` Would there be any reason it cannot return an empty string instead of raising an error?  Perhaps just a warning to alert that there is no parent?

**Comment by brewster1134** [comment]
Just found this related issue https://github.com/nex3/sass/issues/286. Will track this feature there. Thanks!

**Comment by chriseppstein** [comment]
In sass 3.3, `&` is null at the root level. So you can check if you're at the root level with:

``` sass
=forMobile
  @if &
    html.mobile &
      @content
  @else
    html.mobile
      @content
```

**Comment by brewster1134** [comment]
**EDIT**

``` sass
=mobileNav
  @at-root .mobile#{&}
    @content

.nav
  .container
    color: red
    +mobileNav
      color: blue
```

generates

``` css
.nav .container {
  color: red;
}
.mobile.nav .container {
  color: blue;
}
```

perfect!  but is there a better strategy for accomplishing this?
