### ISSUE TITLE
Custom importer implementing import-once like feature

### ISSUE THREAD

**Issue by svallory** [sass/sass#625]
Hi,

I read other questions about why sass doesn't allow `@import-once`. But I tried to create a custom importer to do it for every import anyway. It seems to be working fine but, since I'm kinda new to sass, I would like to ask you guys if you can see any problem with it.

Basically, it has a list of imported files and if a file was imported before, it returns a new engine with an empty string as the content.

Here is the code:

``` ruby
require 'pathname'

module Sass
    module Importers
        class Liftr < Filesystem

            @@imported = []

            # @see Base#find_relative
            def find_relative(name, base, options)
                if @@imported.include? name
                    return empty(options)
                end

                @@imported << name

                return super(name, base, options)
            end

            # @see Base#find
            def find(name, options)
                if @@imported.include? name
                    return empty(options)
                end

                @@imported << name

                return super(name, options)
            end

            def empty(options)
                return Sass::Engine.new("", options)
            end
        end    
    end
end
```

So, will it work? Or will it blow on my face once I reach more complex sass files?

**Comment by svallory** [comment]
First problem found: only works when forcing compilation.

**Comment by nex3** [comment]
When you're defining a new importer that grabs stuff from the filesystem, you need to be sure to get it into the load path correctly. Sass automatically converts strings in the load path to `Sass::Importers::Filesystem` instances, but that won't respect your importer. You'll need to find a way to replace all the load paths with instances of your importer for it to work correctly.

**Comment by svallory** [comment]
Sass has a `:filesystem_importer` option. Wouldn't setting this to my importer be enough to make Sass use mine instead of `Sass::Importers::Filesystem`? As far as I can tell from the searches through the code, that's all it takes. In case anyone is interested, here is a working version of the importer: https://gist.github.com/4549615#file-importer-rb

I didn't have time to write appropriate tests (actually I'm not a ruby programmer), but in manual tests compiling one or many files, forcing compilation or detecting changes, everything worked as expected. The only thing bothering me is the `staleness_check?` method below

``` ruby
def staleness_check?(options)
    # as per sass/importers/filesystem.rb : 135, 148
    # If options[:_line] exists, we're here due to an actual import in an import_node
    # Otherwise, we're here via StalenessChecker.
    # But it's only true for the first file, all subsequent imports will
    # have a :_line, so, unfortunately, for now, will have to check the stack

    Kernel.caller.each {|call|
        return true if call.include? "staleness_checker"
    }

    return false
end
```

Would it be possible to provide a `:staleness_checker` boolean in the options passed to the importer so it knows if it's being called via StalenessChecker or not? (I can make a pull request for that if it's desirable)

I think this feature of importing the file only once would be a great addition to Sass.

**Comment by nex3** [comment]
@svallory: you're correct, `:filesystem_importer` should be sufficient.

**Comment by chriseppstein** [comment]
Now available as a plugin: https://github.com/chriseppstein/compass/blob/master/import-once/README.md
