### ISSUE TITLE
Strange math errors on large numbers

### ISSUE THREAD

**Issue by nathancrank** [sass/sass#627]
I am working on creating some functions that handle various math equations, and in working on an exponential function I have found a rather odd Math error.

``` sass
@function exp($value) {
  @if $value == 0 {
    @return 1;
  }
  $result: 1;
  $prec: floor(abs($value)) * 10;
  @if $prec == 0 { $prec: 10; }
  $numerator: 1;
  $denominator: 1;

  @for $n from 1 through $prec {
    $presult: $result;
    $numerator: $numerator * $value;
    $denominator: $denominator * $n;
    $increment: $numerator / $denominator;
    $result: $result + $increment;
    @debug $increment;
    @debug $result;
    @debug $increment > 0;
    @debug $result == ( $result + $increment);
    @if $result == 1/0 {
      @debug "$presult";
      @return $presult;
    }
    @if $presult == $result {
      @debug "$result";
      @return $result;
    }
  }

  @return $result;
}

exp {
  @debug "exponential function test";
  @for $i from 0 through 128 {
    @debug "exp(#{$i/2})";
    exp-#{$i/2}: exp($i/2);
  }
}
```

On higher value test (like at exp(64)) the line `@debug line $result == ( $result + $increment);` results in true, which simply makes no sense. Anyone have any idea why this particular math fails? The funny part in my mind, is that I've seen SASS handle far larger numbers without issue. Any ideas?

**Comment by nex3** [comment]
When dealing with non-integer numbers, Sass stores them internally in [floating-point representation](http://en.wikipedia.org/wiki/Floating_point). This means that they only have a certain degree of precision: about 16 significant figures. If you try to have decimal numbers with more precision than that, the lower digits will all be treated as zero.

What's happening here in particular is that you have relatively small numbers being added to relatively large numbers. When the small numbers fall under the significant figure threshold, they're treated as all zeros, so you get `$result + $increment == $result`.

**Comment by nathancrank** [comment]
Thanks. That's pretty much what I had come to after digging into
numbers.rb, but was hoping I was wrong.

On Monday, January 14, 2013, Nathan Weizenbaum wrote:

> When dealing with non-integer numbers, Sass stores them internally in floating-point
> representation http://en.wikipedia.org/wiki/Floating_point. This means
> that they only have a certain degree of precision: about 16 significant
> figures. If you try to have decimal numbers with more precision than that,
> the lower digits will all be treated as zero.
> 
> What's happening here in particular is that you have relatively small
> numbers being added to relatively large numbers. When the small numbers
> fall under the significant figure threshold, they're treated as all zeros,
> so you get $result + $increment == $result.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nex3/sass/issues/627#issuecomment-12249234.

## 

Nathan Crank
me@nathancrank.com
