### ISSUE TITLE
Allow comma-separated multiple values in a CSS property mixin to be nested

### ISSUE THREAD

**Issue by olivierlacan** [sass/sass#63]
**Note:**
I originally posted this the [Compas Issues](https://github.com/chriseppstein/compass/issues/345#comment_1026734) but Scott Davis remarked that it was more of a Sass issue. 

With the advent of multiple values in several CSS properties (text shadow, box shadow, background-images, etc) I find myself  driven to nest each value in order to increase future legibility.

This seems adequate for Compass & Sass since we tend to write longer properties with SassScript and the new CSS3 mixins.

This:

```
+background-image(
  linear-gradient(
    darken(desaturate($blue, 15%), 20%),
    darken(desaturate($blue, 10%), 5%)
  )
)

+box-shadow(
  rgba(0,0,0,.4) -1px 0px 2px inset,
  rgba(0,0,0,.4) 1px 0px 2px inset,
  rgba(0,0,0,.5) 0 1px 4px inset,
  rgba(0,0,0,.5) 0 -1px 2px inset
)
```

is much more legible than this:

```
+background-image(linear-gradient(darken(desaturate($blue, 15%), 20%), darken(desaturate($blue, 10%), 5%)))
+box-shadow(rgba(0,0,0,.4) -1px 0px 2px inset, rgba(0,0,0,.4) 1px 0px 2px inset, rgba(0,0,0,.5) 0 1px 4px inset, rgba(0,0,0,.5) 0 -1px 2px inset)
```

What do you guys think?

**Comment by olivierlacan** [comment]
I added a better example of the syntax I find more ideal on [this Forrst post](http://forrst.com/posts/Delicious_box_shadows-LnV).

**Comment by scottkellum** [comment]
I would love to see this implemented so I can create some loops with multiple properties

Here is an idea of what I am trying to achieve, although not flushed out yet:

``` sass
=text-extrude($color, $distance, $angle, $blur: 0)
  text-shadow:
    @for $i from 1px through $distance
      0px $i $blur $color,
```

**Comment by billcolumbia** [comment]
Figured I'd add this link since it was added to compass so other people can find it too!

http://compass-style.org/examples/compass/css3/text_shadow/

**Comment by adamkiss** [comment]
+1

**Comment by chriseppstein** [comment]
I think lists do this fine. We don't need syntax sugar for this.

**Comment by Snugug** [comment]
While this may not help, this can currently be done with the `.scss` syntax
