### ISSUE TITLE
Internet Explorer interprets --debug-info annotations as style rules

### ISSUE THREAD

**Issue by timeinfeldt** [sass/sass#632]
Hi,

most versions of IE (tested IE7-IE9) wrongly interpret the annotations added by --debug-info as additional style rules.

As a result, it's very likely to hit the 4095 selector limit in IE on slightly larger output files.

I realize it's hard to change the format of debug annotations without breaking existing third party applications. 

The current workaround is not using --debug-info when testing or (god forbid) using IE, but it's a bit annoying.

**Comment by nex3** [comment]
We're moving away from `--debug-info` and towards more comprehensive source map generation, which should solve this issue. For now, just don't use `--debug-info` with IE.
