### ISSUE TITLE
Attaching !important to mixins and functions

### ISSUE THREAD

**Issue by chris-pearce** [sass/sass#634]
It would be really great if `!important` could be attached to a mixin/function when it's being called rather than having to work it into the mixin/function e.g.

`@include font-size(20) !important;`

**Comment by robwierzbowski** [comment]
How would that work—add important onto every rule in the mixin?

I think it's cleaner to add an argument to a mixin for important, and then logic to add important to the rule that it belongs on. If a mixin is returning a long list of rules importanting them all will set yourself/your team up for a lot of specificity headaches.

**Comment by nex3** [comment]
`!important` is a pretty blunt instrument, and having it propagate through mixins could cause some strange behavior, especially for more complex mixins.

**Comment by chris-pearce** [comment]
Where I was coming from with this is that `!important` can be added to **every** single CSS property so because of this it should be easy to append it rather than having to work it into **every** single mixin/function for that one edge case when it might be needed. If you're using 3rd party mixins like from Compass then it's difficult to add it in or I think not possible at all? It would just be nice to be able to add it with ease at the end of where you call the mixin.

In terms of the specificity factor I'd hope any decent CSS dev would understand when and when not to use `!important`, if you don't then you probably shouldn't be authoring CSS and you definitely shouldn't be using a pre-processor. Back in the day it was preached never to use it however in modern CSS dev there is a place for it mainly with helper/utility classes (this is backed up by CSS experts e.g. [Snook](http://snook.ca/) & [Nicole Sullivan](http://www.stubbornella.org/), etc.), here's a good explanation: http://css-tricks.com/when-using-important-is-the-right-choice/. Yeah it may be a **blunt instrument** or **the sledgehammer** as I like to call it but it's still part of CSS and like I said there's sensible use cases for it (the only way I would use it). 

Saying that, after authoring more complex mixins I could see it would be very difficult to make this work behind the scenes.
