### ISSUE TITLE
Cast from one type to another

### ISSUE THREAD

**Issue by Snugug** [sass/sass#637]
I've recently run into an interesting situation where I've gotten a string back along the lines of `400px` as a String primitive type and I need to change it into a Number primitive type. I've tried to deal w/it in Ruby, but can't seem to be able to return a united number through Sass::Script::Number.new(). I'd like to either be able to cast the string to a number, or be able to return a number w/unit in Sass::Script::Number

**Comment by nex3** [comment]
I think this is a pretty narrow use case, so it's not something I want to add support for in the language. For your Ruby function, though, the best bet is probably to just use the internal Sass parser APIs. For example:

``` ruby
Sass::Script::Lexer.new("400px", 0, 0, {}).next.value
  #=> 400px (instance of Sass::Script::Number)
```

you'll have to do some error handling, of course, but that should be roughly what you want.
