### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by karellm** [sass/sass#64]
Hi,

I'd love to be able to use media queries.

<pre><code>@media screen and (min-width: 1024px){
  @import "mobile";
}
</code></pre>

and 

<pre><code>@import "mobile" screen and (min-width: 1024px);
</code></pre>

After making some attempts, it doesn't seem to work. In case 1, I get the error 'Syntax error: Import directives may only be used at the root of a document.' and in case 2, nothing happen (which should be a shortcut to the case 1).

Thanks a lot for your help.

**Comment by chriseppstein** [comment]
This works on the current sass alpha releases. `gem install sass --pre` to get it.

chris

**Comment by karellm** [comment]
Thanks a lot for the quality of your support. Much appreciated :)
