### ISSUE TITLE
append to null list works incorrect

### ISSUE THREAD

**Issue by korywka** [sass/sass#646]
``` scss
$prefixes: null;
$prefixes: append($prefixes, webkit moz);
@debug length($prefixes); = 3
```

but:

``` scss
$prefixes: ();
$prefixes: append($prefixes, webkit moz);
@debug length($prefixes); = 2
```

**Comment by robwierzbowski** [comment]
I think this is correct behavior. `Null` is a value, while `()` is an empty list. If I'm building a list from returned values of a function it's very possible some of those values would be null and I would want to keep them.

If you want to remove false or null from a list, [Compass's `compact()` function](http://ruby-doc.org/gems/docs/c/compass-0.12.2/Compass/SassExtensions/Functions/Lists.html#method-i-compact) works well.

**Comment by korywka** [comment]
Console:
`>> $list: (1,2,null)` output: `(1, 2)`
but:
`>> length($list)` output: `3`

So why dont we see `null` element in a list from console?

**Comment by stef-rausch** [comment]
Is it not stated in the SASS Reference File that the compiler does delete / omit null values and empty list in the CSS output? Hence I am with @robwierzbowski here. I just had a small encounter of the same type, which does confirm.

**Comment by korywka** [comment]
it is not stated in reference, but they are hidden in console output (my comment above). thats why i thought it is incorrect.

**Comment by nex3** [comment]
From the [Sass reference](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#lists):

> If a list contains empty lists or null values, as in `1px 2px () 3px` or `1px 2px null 3px`, the empty lists and null values will be removed before the containing list is turned into CSS.

This is the expected behavior.
