### ISSUE TITLE
Omit units for zero values

### ISSUE THREAD

**Issue by krisbulman** [sass/sass#649]
This was incorrectly posted in the Compass queue, re-posting here on behalf of @nschonni as I see value in unit omission for zero values. 

```
A zero value in CSS is the same no matter the units.
This could improve the resulting stylesheet size.
```

https://github.com/stubbornella/csslint/wiki/Disallow-units-for-zero-values

**Comment by Anahkiasen** [comment]
+1 for that, would look cleaner also.

**Comment by robwierzbowski** [comment]
When would the unit be stripped? For math in mixins and functions a zero with units is sometimes necessary.

**Comment by Anahkiasen** [comment]
In what case does the unit of a zero matter in a multiplication/addition/else ?

**Comment by Snugug** [comment]
Just to slightly correct the premise of this suggestion, it's actually incorrect to say that zero absolutely doesn't need units inside CSS. For instance, resolution media queries [require units even if the value is zero](http://www.w3.org/TR/css3-mediaqueries/#values).
As for mixins and functions, the unit of the zero may not be required for the output, but it may be required to ensure you're working with like units even if the result of equation is zero (for instance, adding 1em or 16px).

**Comment by robwierzbowski** [comment]
As snugug says, `10em - 10em + 2px` shouldn't work. For an example in wide use, the unit removal trick 

``` scss
$var / ($var * 0) +1 
```

depends on zero with a unit.

**Comment by Anahkiasen** [comment]
Yeah but as I understood it the initial proposal was to remove units from the final CSS, not in the middle of the SASS calculus.

**Comment by nschonni** [comment]
The idea was for the end CSS, so maybe adding it to the list of optimizations in the output style. Similar to how the :compressed will optimize properties to their smallest form.

**Comment by robwierzbowski** [comment]
I thought that was probably the idea, just wanted clarification.

**Comment by Snugug** [comment]
That's fine as long as its understood that not all of CSS is cool with unit less 0s now and potentially in the future. I'd be curious how much is actually saved by this pseudo-optimization especially when you can currently just write 0 w/o units. (i.e. how often is a 0 with a unit generated that you would want it stripped out)

**Comment by nex3** [comment]
Sass doesn't have enough context information when rendering a number to a string to determine if it's safe to leave off the unit.

**Comment by chriseppstein** [comment]
I verified with @tabatkins that it is safe for Sass to omit the unit for **lengths** when the value is 0. This is true for all properties. However, there is one known ambiguity if you have a list of values for the `flex` property without specifying all the values because it mixes two `<number>`s and a `<length>`, and so in some cases you either need a unit specifier or need to follow a particular order.

We should consider adding support for this. Re-opening.

**Comment by nex3** [comment]
I'm very skeptical of any behavior here that relies on knowledge of CSS's _current_ ambiguities between numbers and lengths. I don't want to have to maintain a list of workarounds for properties like `flex`.

There are some types of optimizations that are better for a post-processor with encyclopedic knowledge of CSS properties to do, and I think this may be one of them.

**Comment by judowalker** [comment]
I created a minimal working example which demonstrates that omitting the unit for lengths when the value is 0 can affect how the content is displayed. This happens across browsers:
https://codepen.io/judowalker/pen/xrMxWj

**Comment by tabatkins** [comment]
`%` is not a unit, and never generates a `<length>`; omitting it flips you into `<length>` territory (implying `0px` or the equivalent), which can definitely be a behavior change in some circumstances.

**Comment by judowalker** [comment]
@tabatkins yes technically you are right but it's still relevant in this discussion and according to https://github.com/CSSLint/csslint/wiki/Disallow-units-for-zero-values, "the value of 0 works without specifying units in all situations where numbers with length units or percentages are allowed," which isn't true for percentages.

**Comment by tabatkins** [comment]
Ah, that CSSLint line is wrong, then.

**Comment by judowalker** [comment]
@tabatkins and the CSSLint warning that's generated as well. :P

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.

**Comment by mkasprz** [comment]
I discovered that there apparently is a difference between 0 with and without a unit. It's connected with the `transition` property. At least in some cases (like `line-height` property) an animation will not be played if there's 0 without any unit. I made a Pen to illustrate it: https://codepen.io/anon/pen/pqyjBd?editors=1100 .
I believe it may be a bug, but I experienced the same behavior in both Chromium and Firefox.

I assume there should be kind of a setting to disable removing units for 0s.

**Comment by nex3** [comment]
@mkasprz Good catch. Since we aren't aware which property a number is being serialized for, we shouldn't remove units ever.

**Comment by arthurio** [comment]
Another bug I found...

`right: max(0px, calc((100vw - 1600px)/2))` will convert to `right: max(0, (100vw - 1600px)/2)` which is invalid.

- ❌  <img width="262" alt="Notivize" src="https://user-images.githubusercontent.com/950449/144359472-45327909-5b8e-48a0-aef2-651c18b3924b.png">
- ✅  <img width="270" alt="Notivize" src="https://user-images.githubusercontent.com/950449/144359443-f2a6ed07-b7b1-462b-a270-c5de13e522cd.png">


Is there a way to tell sass not to perform this optimization?

**Comment by nex3** [comment]
@arthurio When I compile that example with Dart Sass 1.44.0 I get `max(0px, (100vw - 1600px) / 2)`. I suspect you have another tool in your pipeline which is incorrectly removing the units.

**Comment by arthurio** [comment]
@nex3 Good to know, I'll do some digging and report back. Thanks for letting me know 👍🏻

**Comment by arthurio** [comment]
@nex3 Sorry I forgot to report back, the issue was indeed further down the pipeline... Our minifier is the one which was replacing `0px` with `0`.
