### ISSUE TITLE
Question: How to modify sass debug base path?

### ISSUE THREAD

**Issue by kud** [sass/sass#650]
Hello,

I'm on a tricky context. I'm on Windows and I use a debian server virtual machine which has all my unix environment. 

When I activate sass debug, I got that;: `file:///media/sf_D_DRIVE/Sites/happy-plane/src/_assets/styles/style.scss` which is right but only for my VM. Indeed, when I'm on Windows, it should be `file:///D:/Sites/happy-plane/src/_assets/styles/style.scss`

It's a real trouble for me because I use Chrome (on windows) with direct file edit on it.

Do you have any solution?

Thank you.

**Comment by x-yuri** [comment]
I'd rather like to be able to specify base URL for sass files. That is, http scheme is preferable.

**Comment by nex3** [comment]
I assume you're referring to the `--debug-info` option? That's going to be phased out in favor of full-fledged sourcemap support, which will be smarter and more configurable about what paths it uses.

**Comment by kud** [comment]
Okay, great, thanks!
