### ISSUE TITLE
nth() function third parameter

### ISSUE THREAD

**Issue by revati** [sass/sass#653]
It would be nice if nth function had third parameter [seperator].

nth(list, n, [seperator]);

Because i'm using nested lists. 1st level lists are separated with comas but 2nd level lists are separated with white space.

Everything is cool till i have only one 1st level item which contains a list.
And when i do @each function it thinks that it is 1st level list.

Tried to append , 0 at the end to work properly but append as well as join function changes all seperators to comma or space. 
If i use something like that "#{$list}, 0" it makes $list to string and it can not be processed as list and so on.

So it would be great if i could select seperator for nth function as well it would be nice to append, join functions only handled seperator between two lists or list and appendable and didn't change any seperator with passed arguments.

**Comment by nex3** [comment]
Dealing with nested lists is awkward due to the notion that a list with one element is identical to that element. This is something we should deal with, but I don't think the right way to do so is to assume that nested lists have different separators and change behavior based on that.

**Comment by revati** [comment]
Now when i have more experience with lists and understand them beter i agree. It is only 2 weeks since i moved from less to sass, so i still learning.
Slowly migrating from less to sass and made some functions that helps me work with lists more quickly and easy [_lists.scss](https://github.com/regolv/sass/blob/master/rego/functions/_list.scss).
I am enjoying sass, more flexible and feature richer than less.
Thanks.
