### ISSUE TITLE
Interactive shell - possible to 'print' value of variables?

### ISSUE THREAD

**Issue by benfrain** [sass/sass#655]
I'm pretty sure you can't but thought it best to check...

Is it possible to 'print' the value of a variable from the interactive shell?

For example:

`$color10`

I didn't know if it was somehow possible to tell the Shell the project files you are working with (for example by moving to that folder before firing up the Interactive shell)? I realise a variable value can change but wondered if the default/initial value could be printed.

**Comment by nex3** [comment]
I'm not sure what you mean by this... the interactive shell you get by running `sass --interactive` does allow you to print variables, as so:

```
$ ./bin/sass -i
>> $var: 12
12
>> $var
12
```

There's no way to import other Sass files in that shell, though. Is that what you're requesting?

**Comment by benfrain** [comment]
Hi Nathan, it was kind of the second thing I was enquiring about. For example, if by moving to the folder of a bunch of Sass files, launching interactive shell and then referencing a variable (that was within one of the files) whether it can print the initial value of that variable. 
However, the more I have thought on this, the less value I can place on it. 
Thanks for the confirmation of what can/can't be done there though.
