### ISSUE TITLE
inline css value defaults

### ISSUE THREAD

**Issue by drrobotnik** [sass/sass#656]
It'd be really nice if you could set default css values in addition to default variables.

Form example. I have a form plug-in I use from a vendor. The vendor has the option to disable his css and include my own. 85% of it will never change but bits may on a per project basis. I've converted this to a scss partial. Since it has practical defaults it'd be nice to use them, and override them within my main style.scss if I need to.

This would help in creating scaffolds.

_forms.scss /\* very long complicated doc I can reuse */

```
.ex_form {
    li.field{
        clear: both !default;
    }
}
```

styles.scss /\* clean site specific styles and overrides */

```
@import "forms"
.ex_form {
    li.field{
        clear: none;
    }
}
```

Would compile to:

```
.ex_form li.field{
    clear: none;
}
```

instead of how it currently compiles:

```
.ex_form li.field{
    clear: both;
}
.ex_form li.field{
    clear: none;
}
```

**Comment by nex3** [comment]
This is really the job of the CSS cascade, not the pre-processor. It's not possible in general for a preprocessor to determine if a given property has been "overridden".

If something like this becomes available in the future, it'll be as an optimization a la #116.
