### ISSUE TITLE
Allow automatic imports

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#66]
Allow apps, frameworks and Sass itself to automatically import Sass files without requiring an @import directive.

**Comment by aratak** [comment]
+1

**Comment by nashbridges** [comment]
This would be great as it's frustrating that Compass allows

```
@import "icon/*.png";
@include all-icon-sprites;
```

but Sass doesn't allow to import all partials in the same way, for example, in the `layouts` directory

```
@import "layouts/*"
```

**Comment by aratak** [comment]
Inside sass file available to evaluate the ruby code, using erb syntax inliner <%%>
So, as I understood we can do the cycle by array with all needed files. 

It's not pretty good, but it's work. Am I right?

**Comment by nex3** [comment]
@nashbridges: That's not a Compass feature; it's a Rails feature. It's also dangerous in general, because Sass and CSS are order-dependent, and globbing opens the door for extremely difficult-to-track ordering bugs.

@aratak: Sass doesn't allow embedded Ruby code.

**Comment by nashbridges** [comment]
@nex3, well, `@import "icon/*.png";` is for sure Compass thing https://github.com/chriseppstein/compass/blob/stable/lib/compass/sprite_importer.rb
According to you, automatic imports feature as dangerous as globbing (BTW, nobody should rely on the order of the CSS rules, it's a bad habit)

**Comment by chriseppstein** [comment]
@nashbridges:

I don't know where you heard that that "nobody should rely on the order of the CSS rules" but that's just nonsense.

If you want a globbing feature it's available as a plugin: https://github.com/chriseppstein/sass-globbing I used it on a project recently and it cost me an hour to debug an issue related to import order -- hopefully you'll have more luck since you never rely on the order of your css rules.

@nex3, I'm having second thoughts about this feature anyway. Close it?

**Comment by nex3** [comment]
@chriseppstein: Done.
