### ISSUE TITLE
Troubles with percentage

### ISSUE THREAD

**Issue by kud** [sass/sass#661]
Hello,

It seems that there's no parameter which allows you to define how many number you will have after the comma. 

For example, I've got:

```
width: percentage(1/3); // or width: (100% / 3);
```

results:

```
width: 33.33333%;
```

Though, I would like to have

```
width: 33.33333333333333%;
```

Yes. I had a bug where with `33.33333%` my elements didn't take the whole container.

So I have read how Twitter bootstrap did, and they have some numbers like:

```
.row-fluid .span9 {
  width: 74.46808510638297%;
  *width: 74.41489361702126%;
}
```

So I have try manually to do:

```
width: 33.33333333333333%;
```

And it worked like a charm.

So my question is; is there any parameter to specify how many number you could have after comma? and if not, it could be great to implement it! :)

**Comment by kud** [comment]
Well, it seems that you can specify it there: https://github.com/nex3/sass/blob/stable/lib/sass/script/number.rb#L39

**Comment by Rydgel** [comment]
You can specify it using 2 ways:
- You can pass the `--precision` parameter to the command line.
- If you are using Compass you can change that variable inside it.

``` ruby
# config.rb
Sass::Script::Number.precision = 8
```

**Comment by kud** [comment]
Yes, it's one of the solutions, but the greatest thing could be to have a second optional param which is the precision for percentage().

**Comment by Snugug** [comment]
I disagree the greatest solution to a stylesheet wide precision option is a percentage specific variable. Additionally, I think your actual issue is a misunderstanding of cross-browser percentage rounding issues. 
In Firefox, newer Chrome, and iirc IE8+, percentage rounds are staggered up and down to to accommodate for sub pixels. In Safari (and all other WebKit for that matter, save new Chrome), it's all rounded down, leading to percentages that would add up to 100%, not. In old IE, everything is rounded up, meaning its very likely you'll overflow your 100%.

**Comment by kud** [comment]
Thank you @snugug for this explanation.

In other words, what do you advise me about how many numbers should be
there after the comma?

I mean, I was on android chrome, android browser, ios safari, ios chrome
and I had this not-full-width problem. Changing my width manually fixed my
problem.

On 19 February 2013 13:37, Snugug notifications@github.com wrote:

> I disagree the greatest solution to a stylesheet wide precision option is
> a percentage specific variable. Additionally, I think your actual issue is
> a misunderstanding of cross-browser percentage rounding issues.
> In Firefox, newer Chrome, and iirc IE8+, percentage rounds are staggered
> up and down to to accommodate for sub pixels. In Safari (and all other
> WebKit for that matter, save new Chrome), it's all rounded down, leading to
> percentages that would add up to 100%, not. In old IE, everything is
> rounded up, meaning its very likely you'll overflow your 100%.
> 
> On Feb 19, 2013, at 7:09 AM, Erwann MEST notifications@github.com
> wrote:
> 
> > Yes, it's one of the solutions, but the greatest thing could be to have
> > a second optional param which is the precision for percentage().
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nex3/sass/issues/661#issuecomment-13770352.

## 

_Erwann MEST_

www.kud.fr

**Comment by Snugug** [comment]
Each and every one of those browser are affected by the percentage rounding bug. My honest opinion is to not worry about it, it's not a question of precision it's a question of rendering behavior. John Wilkins has a good write up (http://palantir.net/blog/responsive-design-s-dirty-little-secret) about the issue and a way to "solve" it. I personally am not a fan of his proposal, as I'm ok with the rounding issues as they rarely ever bite me, but it does work.
