### ISSUE TITLE
In some locations, non-indented comments cause syntax errors or unexpected output

### ISSUE THREAD

**Issue by ben-rolfe** [sass/sass#662]
The following .sass code causes a Syntax error: Inconsistent indentation (occurs for both /**/ and // type comments)

``` sass
nav
    ol
/* Killer comment. */
        background: red
    ul
        background: lime
```

The error message blames the ul line, but removing the comment removes the error.

If the comment is indented to the level of the ol, it does not cause an error, but the output is unexpected (in this case, /\* */ and // comments cause different results, but both are unexpected)

``` sass
nav
    ol
    /* Killer comment. */
        background: red
    ul
        background: lime
```

output:

``` css
nav {
  /* Killer comment. */
   * background: red */ }
  nav ul {
    background: lime; }
```

When indented one level further, no syntax errors occur, and output is as expected. I couldn't find anything in the documentation specifying that comments must be indented?
If the comment is moved down one line, no syntax errors occur, and output is as expected.

Version: Sass 3.2.5 (Media Mark)

P.S. I  notice that the comments are even causing trouble in the sass code blocks, above!?

**Comment by nex3** [comment]
This is expected. Comments in the indented syntax are part of the document tree; anything indented beneath them is considered part of the comment. You can even see this in the syntax highlighting on your issue report. See [the indented syntax reference](http://sass-lang.com/docs/yardoc/file.INDENTED_SYNTAX.html#comments) for details.
