### ISSUE TITLE
Ternary Function IF Return Value Statement - Not Expected Bahaviour

### ISSUE THREAD

**Issue by stef-rausch** [sass/sass#664]
Have a loot at the following code snippet :

```
    // $exclude : if( $normalize-length > 1, index( $normalize, exclude ), false ); // does not work
    // $exclude : if( $normalize-length == 1, false, index( $normalize, exclude ) ); // neither this variant

    @if $normalize-length == 1 {
        $exclude : false;
    } @else {
        $exclude : index( $normalize, exclude );
    }
```

I had to revert to the above long version to have SCSS / SASS 3.2.5 ( Media Markt ) running under CodeKit 1.5.1 on a MacBook Pro OS X 10.8.2 to behave as expected.

It looks like as the index function is call before the actual checking of the condition, which obviously defies the whole exercise.

Am I missing something?

**Comment by stef-rausch** [comment]
My Assumption was:

> Lists are how Sass represents the values of CSS declarations like margin: 10px 15px 0 0 or font-face: Helvetica, Arial, sans-serif. Lists are just a series of other values, separated by either spaces or commas. In fact, individual  values count as lists, too: they’re just lists with one item.

Realising that a single value is not treated as a list with one item by the index function, one just has to `join( (), $value );` as a safeguard for the ternary if function to work as expected.

**Comment by nex3** [comment]
`index` should treat individual values as lists with a single element. That they don't is a bug. I've opened #668 to track this.

**Comment by stef-rausch** [comment]
Thanks for looking into it!
