### ISSUE TITLE
The word yellow is missing if compressed output is generated

### ISSUE THREAD

**Issue by Dehalion** [sass/sass#665]
I already posted this to the Compass project (see https://github.com/chriseppstein/compass/issues/1031), but I think the problem is with the Sass compiler itself.

I have following code

```
$colors: red #f00, yellow #ff0, green #0f0, blue #00f;
@each $entry in $colors {
    $name: nth($entry, 1);
    $color: nth($entry, 2);

    .box-#{$name} > header {
         background: $color;
    }
}
```

Which works fine as long as I do not generate compressed output. With `-output_style compressed` the yellow class is missing in the generated CSS.

My workaround was to put yellow in quotes ("yellow") which surprisingly works. Using yello would also work.

It could be that the word yellow is replaced by its hex value because it is shorter. But this should not happen with class names and file names containing the word yellow (thanks to http://stackoverflow.com/users/557612/steveax)

**Comment by chriseppstein** [comment]
The word `yellow` is a color which gets output as hex in compressed mode. This will be fixed by #363

**Comment by nex3** [comment]
In compressed mode, this will still generate `#ff0`, since that's smaller than `yellow`.

**Comment by chriseppstein** [comment]
ah good point. best to use a string here :thumbsup:

**Comment by borodean** [comment]
While this stuff looks logical when working with plain primitives and lists, it becomes confusing when starting to use keys of the newly released map feature:

``` scss
@each $name, $color in (
  blue: #7d9df9,
  yellow: #ffedaa,
) {
  .text-#{$name} {
    color: $color;
  }
}
```

Outputs to (notice the second class name):

``` scss
.text-blue{color:#7d9df9}.text-#ff0{color:#ffedaa}
```

Yes, I understand that technically those maps are lists of lists, but such conversion of _keys_ just doesn’t feel right practically.

**Comment by lolmaus** [comment]
@borodean ![meme](http://i.memeful.com/memes/d6KenVw/Joker-Mind-Loss.jpg)

**Comment by borodean** [comment]
@lolmaus Joker could have been right if unquoted key names were not technically allowed.

**Comment by lolmaus** [comment]
@borodean, well, it's technically allowed to shoot yourself in the foot. :)

Seriously though (pun not intended), it's a matter of understanding how the Sass parser interprets code. It tries to treat an item as a color before trying to treat it as a string.

It's just an unfortunate thing that every Sass newbie stumbles upon. But changing the way it works will break most existing code, so @nex3 will never go for that. So just always keep it in mind and you're good to go.

As for creating a special treatment for key names in lists, special cases are generally to be avoided. It would increase parser complexity and contribute to ambiguity. On the one hand, it will encourage newbies not to quote color-like strings. On the other hand, it will produce unexpected results when an actual color is used as a key (hardly a good practice, but still feasible).

**Comment by sapegin** [comment]
Somehow I hit the same issue after updating from node-sass 3.x to 4.x (LibSass 3.4.0). And also with `yellow`. Quotes around map keys helps!
