### ISSUE TITLE
SASS divides variables when calculation isn't desired

### ISSUE THREAD

**Issue by mplewis** [sass/sass#667]
I'm having trouble with elliptical rounded borders when using variables, and I can't figure out how to get SASS to parse the `/` in the source as a symbol instead of a mathematical operator.

SASS:

```
$oval-width: 40px

.oval
  border-radius: $oval-width / ($oval-width * 2)
```

CSS desired:

```
.oval {
  border-radius: 40px / 80px; }
```

CSS generated:

```
.oval {
  border-radius: 0.5; }
```

**Comment by chriseppstein** [comment]
this is a syntax ambiguity and a highly annoying one. here's a work around:

``` sass
.oval
  border-radius: $oval-width unquote("/") ($oval-width * 2)
```

**Comment by chriseppstein** [comment]
Or you could do this:

``` sass

@function slash()
  @return unquote("/")

.oval
  border-radius: $oval-width slash() ($oval-width * 2)
```

**Comment by chriseppstein** [comment]
@nex3 I don't know that there's much that can be done here. Do you agree?

**Comment by nex3** [comment]
I agree. Here's how I'd write this:

``` scss
$oval-width: 40px

.oval
  border-radius: #{$oval-width} / #{$oval-width * 2}
```

A relevant passage from the [Sass reference](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#division-and-slash):

> CSS allows `/` to appear in property values as a way of separating numbers. Since SassScript is an extension of the CSS property syntax, it must support this, while also allowing `/` to be used for division. This means that by default, if two numbers are separated by `/` in SassScript, then they will appear that way in the resulting CSS.
> 
> However, there are three situations where the `/` will be interpreted as division. These cover the vast majority of cases where division is actually used. They are:
> 1. If the value, or any part of it, is stored in a variable.
> 2. If the value is surrounded by parentheses.
> 3. If the value is used as part of another arithmetic expression.

**Comment by SharakPL** [comment]
Thanks @chriseppstein. Worked perfectly :)
