### ISSUE TITLE
Unexpected Behaviour of List Comparison

### ISSUE THREAD

**Issue by stef-rausch** [sass/sass#670]
Look at the following definition:

> $list-1 : ( 1 2 3 );
> $list-2 : ( 1, 2, 3 );

If I do the comparison `$list-1 == $list-2` I would expect the condition to be `true`. The compiler does treat this lists as not equal though.

Is this the expected result?

**Comment by nex3** [comment]
Yes, the separator of a list is considered when doing equality comparisons.
