### ISSUE TITLE
Sass broken?

### ISSUE THREAD

**Issue by danawoodman** [sass/sass#671]
For the life of me, I cannot get the `sass` command to compile `.sass` files.

**foo.sass:**

``` sass
.test
  color red
```

... and I run:

``` bash
sass foo.sass foo.css
```

... and an empty foo.css gets created.

I've also tried the `scss` command as well as trying combinations of `foo.sass:foo.css`.

I hope I'm missing something stupid here...

I've verified this on two different MPB with Sass 3.2.5 and 3.2.6 (Media Mark)

**Comment by Snugug** [comment]
If that is the exact contents of your `foo.sass` file, you've got a syntax error. While you don't need the semicolons or curly braces in `.sass` files, you _do_ need colons for properties. Try 

``` sass
.test
  color: red
```

Running the code as you have it produces an error for me:

```
WARNING on line 2 of foo.sass:
This selector doesn't have any properties and will not be rendered.
```

**Comment by danawoodman** [comment]
Wow. Talk about a fail on my part. Jeeze. 

![doh](http://f.cl.ly/items/3y0y3O1O1W3J0H1O381L/Image%202013.02.27%202:00:58%20PM.png)

On a related note, a more helpful error could be nice.

**Comment by danawoodman** [comment]
Oh, and thanks for pointing me in the right direction!

**Comment by jerzygangi** [comment]
The error message seems pretty helpful. It says you don't have any properties -- which you don't -- and therefore it won't be rendered -- which it isn't.

**Comment by chriseppstein** [comment]
@danawoodman It's impossible for Sass to know the difference between the selector `.test color red` and `.test div a` without creating a whitelist of all possible html elements. If we did that, we would have forward compatibility issues if a new html element is added... also Sass is designed to work with arbitrary xml document styling (as is CSS) so it's basically impossible to know what elements are legal names and decide if what we're looking at is a selector or a malformed property.
