### ISSUE TITLE
Relative @imports within namespace-isolated rails engine not found

### ISSUE THREAD

**Issue by rymohr** [sass/sass#672]
I originally opened [the issue](https://github.com/rails/sass-rails/issues/137) over at [sass-rails](https://github.com/rails/sass-rails) but they're saying this is a SASS thing.

Any ideas?

**Comment by nex3** [comment]
By default, Sass will always try to resolve an `@import` relative to the file the `@import` appears in before trying any other load path. If that's not working in `sass-rails`, that's because of their custom import configuration.
