### ISSUE TITLE
sass watch not releasing from watch/listen, and creating config.rb files

### ISSUE THREAD

**Issue by timkelty** [sass/sass#680]
Originally I thought this was a Yeoman issue, then Compass.
But then, I noticed the same thing is happening on `sass watch` with a non-compass/yeoman project.

https://github.com/yeoman/yeoman/issues/967

AFTER I kill watch in the terminal, if I edit an scss file, it continues to create config.rb files.

So it would seem something isn't releasing the listen/watch properly.

I tried uninstalling sass, compass, fssm, fsevent, and listen, and then bundle installed.

**Comment by nex3** [comment]
If you're seeing `config.rb` files being created, it's almost certainly not Sass doing it. Sass never emits any Ruby files of any kind. It only emits CSS files.

Can you reproduce this using only `sass --watch` from a clean folder? Can you paste the terminal session where that happens?

**Comment by timkelty** [comment]
Yep, still happens:

``` bash
timkelty@olly ~/Sites/test
[ruby-1.9.3]
$ ls
test.scss

timkelty@olly ~/Sites/test
[ruby-1.9.3]
$ sass --watch .
>>> Sass is watching for changes. Press Ctrl-C to stop.
  overwrite ./test.css
[Listen warning]:
  Missing dependency 'rb-fsevent' (version '~> 0.9.1')!
  Please run the following to satisfy the dependency:
    gem install --version '~> 0.9.1' rb-fsevent

  For a better performance, it's recommended that you satisfy the missing dependency.
  Listen will be polling changes. Learn more at https://github.com/guard/listen#polling-fallback.

>>> Change detected to: /Users/timkelty/Sites/test/test.scss
  overwrite ./test.css
^C%
timkelty@olly ~/Sites/test
[ruby-1.9.3]
$ ls
config.rb test.css  test.scss
```

Note the freaky part that after I kill the --watch task, if I delete the `config.rb` file and save the `test.scss` file, it still creates the `config.rb` again!

**Comment by timkelty** [comment]
Also,
If I `gem install rb-fsevent`, the results are the same.

**Comment by nex3** [comment]
This is very strange. What's the contents of config.rb? Are you sure `sass` isn't pointing to some unusual script somewhere?

**Comment by timkelty** [comment]
Super strange, I know.

``` bash
$ which sass
/Users/timkelty/.rvm/gems/ruby-1.9.3-p374/bin/sass
```

The `config.rb` ALWAYS looks like this, exactly, including the lack of spaces around the `relative_assets` equals:

```
http_path = "/"
css_dir = "."
sass_dir = "."
images_dir = "img"
javascripts_dir = "js"
output_style = :compressed
relative_assets=true
line_comments = false
```

**Comment by nex3** [comment]
That looks like a Compass configuration. Is `test.scss` importing any Compass modules?

**Comment by timkelty** [comment]
Nope, `test.scss` is just:

``` css
.test {
  color: red;
}
```

**Comment by timkelty** [comment]
I uninstalled all versions of compass and its still doing it.

I was suspicious of yeoman/node, soI also uninstalled that to no avail.

**Comment by nex3** [comment]
I'm at a loss for what could be causing this. Sass doesn't have any reference to any sort of `config.rb` file anywhere in its code, nor does it ever straight-up copy any files when doing `---watch`. I'm sure there's some explanation for this, but to find it would require debugging deep into the Sass code on your system.

Since I have no idea how to progress further on this, I'm closing the issue, but feel free to post any new information if you find it. I'll let you know if I have any brilliant flashes of insight.

**Comment by timkelty** [comment]
FINALLY figured this out.

Turns out this was all because I had the "LiveReload" package enabled in Sublime Text 2...and all my test were done in ST2. :(

**Comment by nex3** [comment]
Haha, well, I'm glad you figured it out.

**Comment by marcwiest** [comment]
I'm trying to learn Sass, I got the same issue. Could someone provide me with a tutorial on how to solve this "Missing dependency 'rb-fsevent' (version '~> 0.9.1')!" problem? Thanks. What is the "rb-fsevent"?

**Comment by hasft** [comment]
i have the same problem..

**Comment by marcwiest** [comment]
@hasft I just went out on a limb and followed the directions that the terminal presented to me and now everything works.
