### ISSUE TITLE
SASS incorrectly removes spaces from generated content

### ISSUE THREAD

**Issue by svivian** [sass/sass#686]
I am using the `content` property in this rule:

```
.nav-backward {
    >a:before {
        content: "\00ab  ";
    }
}
```

Note the two spaces at the end of the string. These are actually required - a single space does not show up as a space in browsers. SASS compiles the above down to:

```
.nav-backward > a:before {
    content: "\00ab ";
}
```

It removes the extra space! A link with that class will display as `«link` instead of `« link` as expected. SASS shouldn't be changing the strings like that.

**Comment by nex3** [comment]
I can't reproduce this. What version of Sass are you using?

**Comment by svivian** [comment]
I just updated my gems on both Windows (Vista) and Ubuntu and the problem still occurs for me. Sass is version 3.2.7.

I cut it down to just this input:

```
.nav-forward {
    font-weight: bold;
    text-align: right;

    >a:after {
        content: "  \00bb";
    }
}
.nav-backward {
    font-weight: bold;
    text-align: left;

    >a:before {
        content: "\00ab  ";
    }
}
.link-focus {
    font-size: 115%;
    font-weight: bold;
    margin-left: 20px;

    &:before {
        content: "\00bb  ";
    }
}
```

Using the command `sass --watch sasstest.scss:sasstest.css --style expanded` the output is:

```
.nav-forward {
  font-weight: bold;
  text-align: right;
}
.nav-forward > a:after {
  content: " \00bb";
}

.nav-backward {
  font-weight: bold;
  text-align: left;
}
.nav-backward > a:before {
  content: "\00ab ";
}

.link-focus {
  font-size: 115%;
  font-weight: bold;
  margin-left: 20px;
}
.link-focus:before {
  content: "\00bb ";
}
```
