### ISSUE TITLE
Improvements to the minifier

### ISSUE THREAD

**Issue by svivian** [sass/sass#687]
I found that Yahoo's YUI Compressor manages to minify my CSS to an even smaller file size. So I think there are some extra savings that SASS could be making. I compiled my SASS to vanilla CSS using `--style expanded`, then compiled that using both YUI and SASS with `--style compressed`. Here's a list of the possible savings I got from the diff:
- Remove leading zeroes from decimal values. For example SASS outputs `transition:color 0.2s` whereas YUI outputs `transition:color .2s`.
- Replace `outline:none` with `outline:0`
- Remove extra spaces in media queries. Examples:
  SASS: `@media (min-width: 778px) and (max-width: 1161px)`
  YUI: `@media(min-width:778px) and (max-width:1161px)`
  SASS: `@media handheld, only screen and (max-width: 777px)`
  YUI: `@media handheld,only screen and (max-width:777px)`
- YUI replaces `background:none` with `background:0` but I'm not sure if that's really valid.
- Remove extra spaces in font stacks.
  SASS: `font-family:"Ubuntu", "Trebuchet MS", "Open Sans", sans-serif;`
  YUI: `font-family:"Ubuntu","Trebuchet MS","Open Sans",sans-serif;`
  (Should be able to remove the unnecessary quotes around `Ubuntu` as well, right?)
- Colors are not compressed: `#ffffff` should be `#fff`, `#dddd66` should be `#dd6`.
- The space between colors in a standalone `linear-gradient` is removed, but in this rule it is not:
  
  ```
  $header-img: url("image") 20px 0 no-repeat;
  header { background: $header-img, linear-gradient(#333, #111); }
  ```

Hope this is useful! :)

**Comment by nex3** [comment]
> - Remove leading zeroes from decimal values. For example SASS outputs `transition:color 0.2s` whereas YUI outputs `transition:color .2s`.
> - Remove extra spaces in media queries. Examples:
>   SASS: `@media (min-width: 778px) and (max-width: 1161px)`
>   YUI: `@media(min-width:778px) and (max-width:1161px)`
>   SASS: `@media handheld, only screen and (max-width: 777px)`
>   YUI: `@media handheld,only screen and (max-width:777px)`
> - Remove extra spaces in font stacks.
>   SASS: `font-family:"Ubuntu", "Trebuchet MS", "Open Sans", sans-serif;`
>   YUI: `font-family:"Ubuntu","Trebuchet MS","Open Sans",sans-serif;`
>   (Should be able to remove the unnecessary quotes around `Ubuntu` as well, right?)
> - The space between colors in a standalone `linear-gradient` is removed, but in this rule it is not:
>   
>   ```
>   $header-img: url("image") 20px 0 no-repeat;
>   header { background: $header-img, linear-gradient(#333, #111); }
>   ```

These are all doable.

> - Replace `outline:none` with `outline:0`
> - YUI replaces `background:none` with `background:0` but I'm not sure if that's really valid.

This requires more knowledge of the semantics of CSS properties than we're willing to put into Sass.

> - Colors are not compressed: `#ffffff` should be `#fff`, `#dddd66` should be `#dd6`.

This already happens in most cases. However, we have a parsing shortcut that causes us to occasionally avoid fully parsing or compressing properties. This shortcut should be disabled in compressed mode.

**Comment by sturobson** [comment]
This would be really nice if it makes 3.3 or comes anytime soon. 

With developers being reminded of performance and file size at the moment with the likes of moto.oakley.com being a behemoth of a thing. Quick wins such as minifying outputted CSS would be a welcome (yet, obviously really small) assist. 

It'd also help take potential developer mindsets away from needing to have their uploaded CSS human readable, as the browser doesn't care.

**Comment by nex3** [comment]
@indrekpaas that requires knowledge of the semantics of the `font-family` property, and so isn't the sort of thing we'd do.

**Comment by kevinSuttle** [comment]
@stoyan's cssshrink.com/velocity/ has some great options.

**Comment by pickfire** [comment]
It seems like my shell script compress a css file better than the `sassc -t compress`, those leading zeros is added even if I had removed it **manually**.

https://github.com/pickfire/sssg/blob/master/bin/css.sh

**Comment by himedlooff** [comment]
Removing leading zeroes would be great. I asked my sass linter to remind me not to add them but in the compiled css they come back sometimes.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
