### ISSUE TITLE
Determine List Separator

### ISSUE THREAD

**Issue by Snugug** [sass/sass#688]
There are times when working with lists that it would be very useful to know whether a list is space or comma separated. For instance, in [Breakpoint 2.0](https://github.com/canarymason/breakpoint/tree/2.x.x) we use space separated lists for `and` media queries and comma separation for `or` queries. Currently, we use a [ruby function](https://github.com/canarymason/breakpoint/blob/2.x.x/lib/breakpoint.rb) to determine the separator, but we are interested in being able to distribute Breakpoint to a wider audience who many not have the ability to use Ruby functions in their Sass environment, and as such would like to see a native Sass way of determining this.

**Comment by chriseppstein** [comment]
`list-separator` is in sass 3.3.
