### ISSUE TITLE
Unintended color optimization when color names are used in a list

### ISSUE THREAD

**Issue by rauhryan** [sass/sass#692]
`meta`
version: 3.2.5
os: windows
not using rails

I noticed a weird issue when compiling my scss files with the compression flag,
magenta in the following css is optimized into the three digit hex.

``` scss

$color-list: red,
blue,
green,
magenta;
```

This presents a problem if I use the value with string interp to build a class name

``` scss
@each $color in $color-list {
  .#{$color}-icon {
    // do stuff here
  }
}
```

magenta is turned into #f0f

work around is 

``` scss

$color-list: "red", "blue", "green", "magenta";
```

**Comment by nex3** [comment]
Color names always refer to colors in SCSS. If you want strings, use quotes.

**Comment by rauhryan** [comment]
Ok thanks
