### ISSUE TITLE
sass-convert (sass to scss) needs double parens around mixins with multiple arguments

### ISSUE THREAD

**Issue by qaid** [sass/sass#699]
Whew - a mouthful. Say that title 5 times fast!
### The Problem: Sass error when multiple arguments in a transition function

When running sass-convert in terminal and converting a .sass file to a .scss file, sass was throwing errors NOT during the conversion, but when trying to process the resultant .scss file.
### The Error

Sass reports: `Mixin transition takes 1 argument but X were passed` (where X is the number -  greater than 1 - of arguments of the transition function).  
### The Fix That Worked for Me

After trying to blame the preprocessing / IDE software I was using, I searched and found a [StackOverflow post answered by Joseph Erickson](http://stackoverflow.com/questions/7895796/can-a-sass-mixin-accept-an-undefined-number-of-arguments) indicating that you can get Sass to pass multiple arguments as a single  argument by placing two sets of quotes around the mixin function, like: `@include transition((background 0.2s ease-out, border-color 0s ease-out, color 0.2s ease-out));`. After putting in additional parens, no sass error was reported.   
### My Assumption(s)

sass-convert can be modified to output double parenthesis around multi-argument functions when converting from .sass to .scss files. I'm also assuming you know that I know _nothing_ about how to get sass-convert to do that myself or I would have tried to offer a solution you could actually implement.
### My Environment
- Sass v 3.2.5
- Mac OS X 10.8.3

**Comment by nex3** [comment]
Can you give an example of the Sass code you're converting that caused the error?

**Comment by qaid** [comment]
Sure thing ... I was converting the sass of the [DesignModo Flat UI kit](http://designmodo.github.com/Flat-UI/) into scss  (more comfortable for me). These (from the [_pagination.sass partial](https://github.com/designmodo/Flat-UI/blob/master/sass/modules/_pagination.sass)) and a couple of other sass transition mixins caused the errors:

```
> a, > span
background: $inverse
border: 5px solid $pagination-color
border-radius: 50px
color: $inverse
line-height: 16px
margin: 7px 2px 6px
padding: 0 4px
+transition((background .2s ease-out, border-color 0s ease-out, color .2s ease-out))

&:hover, :focus
background-color: $firm
border-color: $firm
color: $inverse
+transition((background .2s ease-out, border-color .2s ease-out, color .2s ease-out))
```

Looking at it now I can see that the sass begins with the two parens, but looses them in the conversion?

Is that useful? Let me know if you need another example or more of the code / context.

**Comment by nex3** [comment]
That should be fine, thanks.
