### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dsteinbach** [sass/sass#700]
Sorry if I am posting this incorrectly under "Issues" but I am only a Git novice. I have an idea for a feature that might already exists so please forgive me if I am late to the party but here goes:

The greatest plus for me using SASS is being able to create a nested CSS structure that my brain can map easily to the markup on the page. However, deep nesting comes with serious costs to performance as I am sure you are aware of.

What if we were allowed to nest as much as we wanted but were given a little more control over how these selectors are compiled?  For instance, utilizing path routing we can do something like:

``` scss
#page {
    ../.header {
         .logo {
         }
    }
    .content {
         /.nav a {
         }
    }
    ../.footer {
    }
}
```

Would compile to:

``` css
#page {}
.header {}
.header .logo {}
#page .content {}
.nav a {}
.footer {}
```

That's my idea. Thanks!

**Comment by nex3** [comment]
If you don't want the output to be nested, just don't nest. I don't think it adds value to have a future that allows you to undo other code you've written.
