### ISSUE TITLE
Sass::Script::Number doesn't have a to_f method

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#701]
Is there any reason `Number` doesn't include `to_f`? It has `to_i`, which is helpful but not applicable in all situations, obviously. 

`var.to_s.to_f` is an acceptable workaround most of the time. But it is a workaround.

I think including it would improve dx when building custom Ruby based Sass/Compass functions (at least the one I'm currently working on).

**Comment by nex3** [comment]
The `#value` method will return the value of the number as a float. This is the default; `#to_i` exists as a convenience method for times when you want to assert that the number is an integer.

**Comment by robwierzbowski** [comment]
Thanks, @nex3. Ruby beginner.
