### ISSUE TITLE
option to output each selector on a new line

### ISSUE THREAD

**Issue by skierpage** [sass/sass#702]
Using compass 0.12.2 to invoke "Sass 3.2.6 (Media Mark)", with style :expanded, the generated CSS looks like

``` css
button.mw-ui-button, a.mw-ui-button {
```

I'd prefer each selector on a newline, thus

``` css
button.mw-ui-button,
a.mw-ui-button {
```

There doesn't seem to be an option for this.

Someone else asked for this on [stackoverflow](http://stackoverflow.com/questions/12850678/can-compass-compile-css-selectors-on-separate-lines)

**Comment by nex3** [comment]
This isn't something we intend to add to any of the default styles. At some point we may add the ability to create custom output styles, but it's not a high priority.

It's worth noting that if you include newlines in selectors your source file, they will generally be preserved in the output.
