### ISSUE TITLE
Avoid empty .css file during processing

### ISSUE THREAD

**Issue by MoOx** [sass/sass#704]
Like said [here](https://github.com/gruntjs/grunt-contrib-livereload/issues/12) & [here](https://github.com/fonzie/fonzie/issues/11) it seems that Sass is creating an empty file before putting actual content in it. When you use tools like 'livereload' you can get a flash with an empty file reloaded. It's annoying.
Is it hard to create directly the file with the content in it ?

**Comment by kud** [comment]
Gracias. :+1:

**Comment by MoOx** [comment]
AWESOME. Thanks a lot @nex3
