### ISSUE TITLE
No method `options=' for String on line ["334"]

### ISSUE THREAD

**Issue by kellydunn** [sass/sass#705]
Hello there! 

First off, thanks much for maintaining this gem, it has greatly sped up my web development in the past and continues to be helpful today :)

While updating our build servers today, I noticed an odd error that was occurring on our jenkins builds, but not in any of our other environments:

```
NoMethodError on line ["334"] of /home/jenkins/.rvm/gems/ruby-1.9.2-p180/gems/sass-3.2.7/lib/sass/engine.rb: undefined method `options=' for #<String:0x00000002bbcb08>
```

It's curious that sass's behavior would change between environments, as this was on a fresh Ubuntu 12.04 LTS image; it's very similar to our other virtualized development environments.

In an effort to debug the issue, I attempted to manually compile our scripts on the build instance.  While they compiled as expected from a manual `compass compile`, sass still resulted in errors while issuing a fresh build; it appears as though there's a bad configuration value somewhere.

I'm a little stumped as to how to further approach this~  Is this a known issue / is there a known workaround?

Thanks in advance!

**Comment by kellydunn** [comment]
Getting more explicit, it appears as though that `@options[:cache_store].retrieve(key, sha)` is returning a `String` instead of an expected instance of `Sass::CacheStore::Base`.

After some further debugging, I noticed that the return value of this call appeared to be an error message; it appears sass was attempting to marshal a previously cached file:

```
Warning.  Error encountered while reading cache /home/jenkins/workspace/path/to/project/xxx/ie-6.scssc:  incompatible marshal file format (can't be read)
format version 4.8 required; 87.97 given
```

The problem seemed to be resolved by clearing the ./sass-cache folder and re-running the build scripts.

I'll mark this issue as closed for now as it is solvable without introducing new code, but I would expect that sass should gracefully fail in these situations; it was unclear what the problem was from the initial error message.

**Comment by nex3** [comment]
I'm reopening this to track the poor error handling in this situation.

**Comment by kellydunn** [comment]
appreciate the follow-through on this!  :+1:  :dancer:
