### ISSUE TITLE
Overwrite existing css file on compile error

### ISSUE THREAD

**Issue by willytk** [sass/sass#707]
OS X 10.8.3, Sass 3.2.7 with CodeKit 1.6.1 @bdkjones

If you have a valid, generated style.css file, and then enter something erroneous in the .scss file, the exisiting style.css file will be overwritten with an empty file when sass tries to compile and fails.

**Comment by willytk** [comment]
Hm, OK, I'll try to be more specific. If you create a style.scss file containing 

``` css
h1{
    color: red;
}
```

and then compile, it will generate a valid style.css file.
If you then change it to:

``` css
h1{
    color: red;s
}
```

the compile will fail and the style.css will be overwritten with an empty file. That's the issue.

**Comment by nex3** [comment]
I believe this was fixed by a7bdf6126c32493f5a25b2cf958cc648026cf1e4.
