### ISSUE TITLE
Segmentation fault on Heroku Deploy

### ISSUE THREAD

**Issue by glorieux** [sass/sass#708]
I've got a Segmentation fault while pushing my app on Heroku. [Here is a gist with the logs.](https://gist.github.com/glorieux/a2071952f69b77fe0a4f)
I'm available if you need more details about my environment.

**Comment by nex3** [comment]
Any segfault is a bug in the Ruby interpreter, not in Sass. If you can figure out a reliable reproduction, I'll see if I can work around it, but until then I'm going to close this out. I suggest you file a bug against Ruby itself, though.
