### ISSUE TITLE
External .scss file with new @import

### ISSUE THREAD

**Issue by RaphaelDDL** [sass/sass#712]
Hello there,

I've searched for a bit but couldn't find anything about it so I made a new issue.

I've read there's a new @import (which probabbly will not be named that because of compatibility) being worked on. I'd like to know (and if not, suggest) if it will add support for including external .scss files (not .css) to be parsed.

Let me make an example to best explain:

Currently the company made a 'Standard CSS Framework' for the web products based on Twitter Bootstrap. And all CSS', images and etcetera are served from a CDN to all products. 

So, for e.g., I'd like to serve our 'standard' _mixins.scss and _bootstrap.scss to all projects, but without the developers having to actually copy the file to their project (so they would not mess with them and to keep up-to-date). Therefore using for e.g. `@import_external "http://example.com/path/sass/_mixin.scss";` (or whatever the @name would be) would download the .scss file and include in the compilation like it was in a local folder.

In reality, the SASS part of the improvement would be add a new type of `@import` for external files, that buiilders/compilers could know what to do.

Or would be Compass' `watch` job to actually download the file since it's already running on Terminal/Prompt.. Maybe using: 
- `wget` for Linux/OSX;
- `new-object System.Net.WebClient` for Win7;
- `CreateObject("MSXML2.XMLHTTP")` for older Wins.

And returning error when http timeout or fails for any reason (configurable through `config.rb` maybe?)

What you guys think?

Best Regards,
RaphaelDDL

**Comment by cimmanon** [comment]
What you describe is already part of Compass in the form of _extensions_.

**Comment by RaphaelDDL** [comment]
@cimmanon On compass website there's only a tutorial explaining how to 'create' extensions. Google showed me some lists but mostly are extensions for grid, vendor stuff and else ( https://github.com/chriseppstein/compass/wiki/Compass-Plugins , http://rubygems.org/search?query=compass ). Found some ones for bootstrap but as I said, ours are based on so can't use the plugin for the raw one.

Nothing related to external import it seems.

I believe you might be pointing me to actually create one, but I have zero knowledge of Ruby to actually write an extension myself so I'll just give up on the idea (for now, until I finish learning what I'm already studying. Too bad can't write extensions with shell/bash or PHP lol). 

Thanks for pointing the extensions, too bad seems noone made anything near.

**Comment by Snugug** [comment]
Creating Compass extensions isn't so hard, and is exactly the solution you should be aiming for for your usecase. Check out the [Compass Extension Template](https://github.com/Team-Sass/Compass-Extension-Template) to get you building one very quickly with near no Ruby knowledge needed.

**Comment by RaphaelDDL** [comment]
I still don't get it how you say 'need near no Ruby knowledge'. I think I'll really need Ruby knowledge..

So how would I code something that when compass read the sass/scss:
- see that there is an URL inside `@import` (or create a new `@` by myself);
- detect it points to a .sass/.scss file, download the file (via `wget` or similar);
- save the file in a temp folder;
- dynamically change that `@` for a common sass `@import` pointing to the temp file in a temp folder;
- let compass watch do his compiling magic.

I don't think SassScript can achieve this.

Then again, thanks for pointing that template, really nice.

**Comment by Snugug** [comment]
You're misunderstanding us. We're suggesting you build a Compass extension that you distribute to your team (that they would then be unable to touch) _instead of_ importing from an external file.

**Comment by RaphaelDDL** [comment]
Ahhhhh... Now I got what you said. Build an extension and they install as a gem for `@import` like we do with compass utilities, for e.g.?

But then again will fall in the versioning problem (they would need to open the console, check their version and then update). But that would be a workaround while I don't learn Ruby enough to do the steps I told on previous post. 

(That would be neat to release for public).

Thanks for your time, Snug!

**Comment by Snugug** [comment]
Very welcome. Also look into using [Bundler](http://gembundler.com) to manage versioning dependencies.

**Comment by nex3** [comment]
You could also create a custom [importer](http://sass-lang.com/docs/yardoc/Sass/Importers/Base.html) that imports over HTTP.
