### ISSUE TITLE
Indented syntax: support for line breaks between arguments of function/mixin declarations and calls

### ISSUE THREAD

**Issue by lolmaus** [sass/sass#715]
Hey nex3, i totally dig the indented syntax. The curly braces SCSS syntax has too much visual noise and is a nuisance to refactor.

![indented-vs-brackets](https://f.cloud.github.com/assets/200884/401073/1ab8c5a2-a8ce-11e2-8de7-0b40a79814ce.gif)

The problem with the indented SASS syntax is that declaring and calling functions and mixins with SASS produces terribly long lines. Here's an example:

``` sass
@mixin sassy-button($gradient-style: $sb-gradient-style, $border-radius: $sb-border-radius, $font-size: $sb-font-size, $first-color: $sb-base-color, $second-color: $sb-second-color, $text-color:$sb-text-color, $text-style: $sb-text-style, $auto-states: $sb-pseudo-states, $ie: $sb-ie-support)
  @include sassy-button-structure($border-radius, $font-size, $sb-padding)
  @include sassy-button-gradient($gradient-style, $first-color, $second-color, $text-color, $text-style, $auto-states, $ie)
  @include sassy-firefox-fix
```

https://github.com/jhardy/Sassy-Buttons/blob/master/stylesheets/_sassy-buttons.sass#L58

This is just wrong.

I know how conservative you are concerning any enhancements (i saw you rejecting functions that would be surely useful to many developers and absolutely harmless), but i just can't stay silent.

SASS already has support for line breaks after comma for selectors, why not add it for arguments?

And if you allowed arbitrary indenation after a comma, it would be absolutely awesome:

``` scss
@mixin sassy-button($gradient-style: $sb-gradient-style,
                    $border-radius:  $sb-border-radius,
                    $font-size:      $sb-font-size,
                    $first-color:    $sb-base-color,
                    $second-color:   $sb-second-color,
                    $text-color:     $sb-text-color,
                    $text-style:     $sb-text-style,
                    $auto-states:    $sb-pseudo-states,
                    $ie:             $sb-ie-support)
  @include sassy-button-structure($border-radius, $font-size, $sb-padding)
  @include sassy-button-gradient($gradient-style, $first-color, $second-color,
                                 $text-color,     $text-style,  $auto-states,  $ie)
  @include sassy-firefox-fix
```

PS It would also be great to follow the example of Python. It only cares about whether the current line of code is indented more/equally/less than the previous line, while any number of spaces can be used.

**Comment by nex3** [comment]
This is a duplicate of #216. This is something I'd like to support, but I haven't had the time to do it. It's more complicated than it seems, since the indented syntax parser is pretty crufty and weird.
