### ISSUE TITLE
Issue when converting scss to sass and null data type

### ISSUE THREAD

**Issue by atomicpages** [sass/sass#718]
- Sass 3.2.7
- Ruby 1.9.3

Consider the following:

```
@mixin foo($type: null) { content: "Foo has been called"; }
```

When you execute `sass-convert test.scss test.sass` your result is:

```
=foo($type: )
    content: "Foo has been called"
```

The conversion strips out the null data type

**Comment by nex3** [comment]
Duplicate of #709.
