### ISSUE TITLE
Set number precision in sass code

### ISSUE THREAD

**Issue by adambom** [sass/sass#72]
It would be nice if you were able to set the precision of numbers directly within your sass. Currently, I believe you have to edit the configuration files, which is less than optimal. e.g.

```
$num-precision: 6 // sets sass math operations to return values to 6 decimal places
```

This would come in handy in situations when you need more than three decimals for a shared project and you don't want your collaborators to have to edit their configurations.

**Comment by nex3** [comment]
I strongly dislike the idea of magic variables that affect internal configuration. In addition to the general distastefulness of having certain variables marked for special behavior, it's not at all clear what would happen if this variable were set in a local context, used as a parameter, etc.

A much cleaner solution for sharing configuration is to check in some sort of `config.rb` file that's included with the `--require` flag, or using Compass's built-in configuration support.
