### ISSUE TITLE
hex color names are compiled inconstantly in compressed mode.

### ISSUE THREAD

**Issue by allanhortle** [sass/sass#720]
I often use nested lists to create color based classes.

```
$list:
    red $red,
    yellow $yellow,
    darkgreen $darkGreen,

@each $item in $list{
    .#{nth($item,1)}{
        color:nth($item,2);
    }
};
```

modes other than compressed this would compile to 

```
.red{color:#F00}
.yellow{color:#FF0}
.darkgreen{color:#2F4F2F}
```

but for some reason in compressed it tries and fails to compile to 

```
.red{color:#F00}
.#FF0{color:#FF0}
.#2F4F2F{color:#2F4F2F}
```

the bizarre thing is that red works fine. This can of course be fixed by wrapping the color names in `" "`. But the inconstancy makes me think it's a bug.

**Comment by nex3** [comment]
Color names in Sass refer to color objects. In uncompressed mode, named colors compile to their names, but in compressed mode, they compile to the most compact representation.

If you want to use color names as strings, you should quote them. In fact, as a rule of thumb, you should pretty much always quote your strings if they're outside of properties.
