### ISSUE TITLE
The Output path seems to be something wrong...

### ISSUE THREAD

**Issue by fiv111** [sass/sass#721]
- Ruby Version : 2.0.0
- Sass Version : 3.2.8
- File               : exec.rb

line : 111
# output ||= args.shift || $stdout
output ||= open_file(args.shift, 'w') || $stdout

When I change the code, its able to output correctly...

**Comment by fiv111** [comment]
More Information.
First, there seems to be necessary to open the output path.
- FIle : exec.rb
- line : 338

# write_output(engine.render, output)
f = open_file(output, 'w')
write_output(engine.render, f)

**Comment by nex3** [comment]
What behavior are you seeing that's going wrong?

**Comment by fiv111** [comment]
Finally, I found the problem and the solution.
In version 3.2.8, the relative path (image file path) has been changed in my sass script.
Fixed to Absolute path and it works correctly now.

I'm sorry for the trouble I have hurriedly post.
And Thank you for listening.
