### ISSUE TITLE
Sometimes watch feature prints out empty css

### ISSUE THREAD

**Issue by Somebi** [sass/sass#724]
Using this version:
Sass 3.2.7 (Media Mark)

Just getting blank css file, after few attempts to re-save .scss file it's ok.

Looks like a bug. Don't know how you can reproduce it on your side.

Another bug with the watch itself. Some times it's blind to recent changes. Have to re-save few times to force it accept the changes inside file.

Guess something is really bad inside watch module.
- It's eating too much CPU
- Blind to changes _sometimes_
- Return blank css _sometimes_

Thanks.
Will help any way i can, with the information you'll request.

**Comment by Somebi** [comment]
I'm using compass. Not sure it's actually sass problem. But anyway, so let you know. I have a message SASS: >>> Compass is polling for changes. Press Ctrl-C to Stop.

Compass is polling.

**Comment by nex3** [comment]
Can you reproduce this with vanilla `sass --watch` (either without compass at all or with `--compass`)? Can you reproduce it on Sass 3.2.8?

**Comment by Somebi** [comment]
Sorry i forgot to close this issue. It's been resolved here https://github.com/chriseppstein/compass/issues/1270#issuecomment-17015418
