### ISSUE TITLE
Add an option to output a list of imported files

### ISSUE THREAD

**Issue by phihag** [sass/sass#726]
It would be nice to know which scss/sass files sass compiled something from, in order to:
- Run automatic checks to ensure all source files have been commited
- Allow using an external watcher daemon. The daemon may not even watch, but instead check whether the file needs to be updated on each request before invoking `sass`.
- Enable easier debugging/inspection of unknown code (and answer _What files does this job touch?_)

In the library, there should be an array of imported filenames (if possible, in a format that C bindings can parse relatively easily). This may or may not include those specified in the command-line.

On the command-line, there should be an option `--list-source-files` that lists all sass/scss files ; or a subset of the output of `strace -e open sass "$@" in.scss out.css 2>&1 | grep -v /`.

This could look like:

```
/*!SASS source files: [
"main.scss",
"foo.scss",
"bar.scss",
] */
```

This should be relatively easy to parse in any high-level language with regexps and JSON.

For low-level (C/asm/..., but also shell) calling applications and debugging/continuous integration, it would also be nice to let the sass exec write the output to a file. Calling programs would typically construct a named pipe or .

This feature would remove a huge hurdle to integrate SASS into [adhocracy](https://github.com/liqd/adhocracy), an online policy deliberation system (and other scalable web applications that cannot easily run `sass --watch`). Or am I missing something and this is already possible?

**Comment by nex3** [comment]
This is the sort of thing that would be better suited to using the [Ruby API](http://sass-lang.com/docs/yardoc/) than to adding surface area to the executable. [Sass::Plugin::StalenessChecker](http://sass-lang.com/docs/yardoc/Sass/Plugin/StalenessChecker.html) may meet your needs; if it doesn't, feel free to file pull requests against it.
