### ISSUE TITLE
Nice API for extracting dependencies

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#728]
http://stackoverflow.com/questions/15972352/regular-expression-to-get-sass-imports/16244940#16244940

I think we can make a nicer ruby API for this.

Note: Compass will ship with a `structure` command soon that shows the dependency structure of a project.

**Comment by nex3** [comment]
This is pretty easy to do right now using `Sass::Engine#to_tree` and creating a `Sass::Tree::Visitor`. I don't know if it's widely useful enough to add a utility function on top of that.

**Comment by chriseppstein** [comment]
I think it will help application-level integration with tools that drive the compilation process. It's not a hard API to write or support, I'll add it at some point. not urgent.

**Comment by Subash** [comment]
Thanks @chriseppstein for taking it here.

**Comment by nex3** [comment]
This is no longer planned.
