### ISSUE TITLE
Avoiding unnecessary re-compiles

### ISSUE THREAD

**Issue by cainlevy** [sass/sass#736]
In some situations, git will update the mtimes of source files even when the content hasn't changed. This can trigger many unnecessary re-compilations.

I can think of a couple possible approaches to the problem. Any ideas which, if any, might be worth pursuing?

1) Embed a SHA of the source file into the output file, similar to the sass-cache.
2) Prefer the mtime of the sass-cache files instead, if they exist.

**Comment by cainlevy** [comment]
I'm experimenting with a SHA comment in each output file. Is this something that I should put into a pull request?

**Comment by nex3** [comment]
I don't want to change the contents of the output files, and I don't want to universally prefer the sass-cache mtimes either. However, the following strategies might work:
- For `sass --watch`, keep track of the SHA of the source files in memory. If the mtime of a file has changed, validate that the SHA has changed as well before compiling.
- For `sass --update`, if the mtime of a file has changed, check whether the SHA is the same as the cached SHA. If it is, use the mtime of the cached file instead.

**Comment by chriseppstein** [comment]
I doubt the usefulness of this. I think people often save a file to force a recompile and it will slow down the common case (the file is saved with a change).

**Comment by cainlevy** [comment]
Thanks for the feedback. It sounds like my situation may be a niche. If I do more experimenting with this, I might try to think of it as an outside replacement for the `StalenessChecker` plugin. I think sass is already pretty close to making that a configurable thing.
