### ISSUE TITLE
Add warning re abuse of nesting to Tutorial

### ISSUE THREAD

**Issue by mipearson** [sass/sass#737]
I've seen this with a few developers & projects, and have made the same mistake myself, when being introduced to SASS/SCSS for the first time.

What would normally be, out of necessity of lack of nesting in plain CSS:

``` css
.help-callout b { ... }
```

ends up being, after a few revisions & additions:

``` scss
#viewpage {
  .content {
    ...
    .sidebar {
      ...
      .help {
        b { ... }
      }
    }
  }
}
```

Nesting is awesome! Look how much easier it is to write deep CSS now!

Now it's three months later, and thanks to the magic of nesting, your SCSS is kinda .. page-dependant and messy and hard to re-use.

I think a warning should be added to the tutorial, something along the lines of "if you're nesting more than three levels deep, you're probably going to have a bad time"

Referring to smacss.com might also be helpful.

**Comment by damncabbage** [comment]
+1; I ran into the same mistake when learning this.
