### ISSUE TITLE
In the website, the "sass list functions" link return 404

### ISSUE THREAD

**Issue by olistik** [sass/sass#74]
In the page: http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#lists

The link contained here "On their own, lists don’t do much, but the _Sass list functions_ make them useful."
points to a wrong page: http://sass-lang.com/docs/yardoc/file.Functions.html#list-functions

**Comment by thomaswelton** [comment]
Replicated this issue, did a google search to find the real content. But found this bug :)

**Comment by thomaswelton** [comment]
http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#list-functions
Seems to be the correct URL for anyone else googleing
