### ISSUE TITLE
Ampersand problem

### ISSUE THREAD

**Issue by ArnaudRinquin** [sass/sass#746]
Hi !

According to the documentation, "In a selector, & will be replaced verbatim with the parent selector."

I have spotted an issue while trying to compile this:

``` scss
.badge {
   border: 1px solid black;
   &-info {
      background:blue;
   }
}
```

Should compile to

``` css
.badge { border: 1px solid black; }
.badge-info { background: blue; }
```

Instead, we have this error:

```
Sass Error: Invalid CSS after "   &": expected "{", was "-info {"
"-info" may only be used at the beginning of a compound selector.
```

While I agree that this example is a misuse of the ampersand, it goes against the documentation.

Also, I stumbled upon this problem while trying to fix the [.less to .scss converter](https://github.com/maxim/bootswatch-rails/blob/master/converter#L72) form [bootswatch-rails](https://github.com/maxim/bootswatch-rails) project. As Less allows this kind of ampersand use, [some project use it](https://github.com/thomaspark/bootswatch/blob/gh-pages/cosmo/bootswatch.less#L507). There is no way to build a correct converter for this example, which is really really sad.

**Comment by nex3** [comment]
This is expected. In Sass, `&` is treated as the same sort of syntactic object as an element selector, since it cuold be replaced by one; as such `&-info` is invalid syntax. Your use case is coverred by #286, which is a high-priority feature.

**Comment by krulik** [comment]
I also have this problem with latest SASS (3.3.7).

However it does work here: http://sassmeister.com/
And here: http://codepen.io/krulik/pen/xGzFC

Any thoughts why?
