### ISSUE TITLE
@error directive

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#747]
Users should be able to create an error with `@error <message>`

**Comment by xzyfer** [comment]
:+1: At the moment we work around this issue by emitting a warning a returning null since null'd properties are omitted from output. Although comes with it's own confusion.

**Comment by danielcreid** [comment]
Any news on the status of this? Would be a great feature to have.

**Comment by manikrathee** [comment]
+1 on this - it would be a huge gain for large teams. 

Writing a complex animation mixin and I want to throw a verbose error when the mixin fails so anyone on the team can understand the issue right away.

**Comment by apfelbox** [comment]
:+1:

**Comment by battaglr** [comment]
This also would be great to avoid doing this over and over:

``` scss
@warn <message>;
@return false; // Or `null`.
```

@chriseppstein: how do you plan `@error` to work?
