### ISSUE TITLE
Make the official SASS precompiler more portable

### ISSUE THREAD

**Issue by emagnier** [sass/sass#751]
New front-end tools & languages written in JavaScript are becoming very popular (Less.js, CoffeScript, Typescript…), because they all take advantage of NodeJS: a very portable, accessible and efficient solution.

I’m personally prefer Sass rather than Less or Stylus, because I consider Sass more elegant, powerful, and the most featured language. However the dependencies on Ruby is really becoming an issue.

In my company our projects are on ASP.NET. There is some workarounds to use Sass (e.g. with IronRuby) but they are all not very efficient, and are difficult to integrate with our platforms. The [Libsass](https://github.com/hcatlin/libsass) project (a C++ port of the Sass precompiler) is also interesting, but it still lacks a lot of functionalities (and the developer behind Libsass seems to be very busy).

Some usage examples with a more portable solution:
- Better integration in IDEs, Web Platforms, CMS, etc… (as it is done with Less.js and CoffeScript) ;
- More easily integrate Sass on a lot of asset packagers & bundling tools ;
- Less painful to use it on Windows, particularly when we can't install Ruby ;
- Create standalone/automated workflows, with [Grunt](http://gruntjs.com/) or some other tools like that (and without need to control the configuration of the environment) ;
- Etc.

Thanks.

**Comment by nex3** [comment]
Porting Sass to JavaScript would be a huge undertaking that would siphon essentially all of our time away from pushing the language itself forward for many months. That isn't something we can afford.

I'd be happy to hear suggestions on how to make the Ruby implementation easier to use, but a port isn't on the horizon -- at least not one written by us.

**Comment by emagnier** [comment]
I'm totally agree with your point of view. Rewrite Sass in JavaScript is really a lot of work. And on my side I have unfortunately not enough skills and time to rewrite the Sass compiler.

You closed this issue, but I just wanted to create debate on this topic (I was thinking this was the best place to speak about that). Maybe a few are interested to create this kind of project, or contribute to an existing (Libsass). 
And also because I can see on a lot of blogs and forums many people having the same issues as me.

Thanks for your time and your great work.

(PS: sorry for my bad English, this is not my native speaking)

**Comment by cimmanon** [comment]
Popularity is rarely an indicator of quality.  Compared to NodeJS, Ruby is the lesser of two evils in the eyes of my boss, which is how I finally managed to convince him that Sass was the CSS Preprocessor to go with.

I have a hard time understanding how anyone could think Sass under Ruby is difficult to use.  Install Ruby, install Sass, run the watch command in the terminal, done.  All of the "installation is hard" topics I've come across are because of people using a mountain of other things that seem excessively convoluted from my perspective.

**Comment by bjmiller** [comment]
@cimmanon: When you use a compile-to-CSS metalanguage, such as SASS/SCSS, then the CSS that it generates becomes not code per se, but a throwaway build product.  If you don't treat it this way, then you run the risk of people directly hacking the CSS without knowing better, and having their changes thrown away when anyone modifies the original source and builds the CSS.

Where this is a problem is when both: a) You can't store CSS in your source tree, you need it to be built fresh with each deployment, and b) You aren't using Rails, and you therefore can't guarantee that Ruby is even available within your build environment.

I have this exact scenario.  Simply using "scss --watch" to generate CSS on the developer level is not an option.

We don't need to port the whole thing over to Javascript, I don't think.  One valid strategy might be to make the compile the Ruby process down to an LLVM binary, and use Emscripten to make Javascript out of it.  The whole process, if possible at all, would be entirely scriptable.  You can have it auto-generate every time you cut a release.  As long as you state up front that you're not going to support it if it fails, I don't think it would add any real extra work - outside of the initial setup.

Another strategy might be to try hammering JRuby into running it, thus extending it to at least the Java environment.  To my understanding, that doesn't work well right now for some reason.

There are a handful of abandoned projects around, where people gave an honest go at doing SCSS-in-another-language.  But, between the sheer size of it, and the fact that the development here on the core language makes it a moving target, it's easy to see why no one has been able to finish it.

**Comment by nex3** [comment]
As far as I know, Sass runs fine on JRuby.

**Comment by emagnier** [comment]
@bjmiller: Thanks for your answer. You have a very good point about the port to another language, all the SCSS-in-another-language are still very incomplete or abandoned.

I already used a version of the Sass compiler with IronRuby (.NET) but it was extremely slow. I will try to do it via JRuby. If I find a way to generate a standalone and fast compiler on Windows, this would be perfect for my needs.
