### ISSUE TITLE
@includ doesn't fail when compiling

### ISSUE THREAD

**Issue by sturobson** [sass/sass#759]
I happened upon this earlier today. I was coding something out and looked at the browser after my SCSS compiled at the @include I added wasn't there. I looked at my SCSS to see @includ where I missed the e

Should this throw an error rather than silently ignoring it?

**Comment by Snugug** [comment]
Do you have sample code? This is a bit too ambiguous without some code for context.

**Comment by sturobson** [comment]
Sure, hopefully this codepen explains it - http://codepen.io/sturobson/pen/mlihc

so the Sass -

```
@mixin border-rad($value) {
  -webkit-border-radius: $value;
  border-radius: $value;
}

ul {
   @includ border-radius(20px);
}
```

and the output -

```
ul {
  @includ border-radius(20px);
}
```

I was wondering wether it's in the scope of Sass to handle and report such an error.

**Comment by chriseppstein** [comment]
Sass doesn't pretend to know what all the possible at-rules in CSS are. This makes sass forward-compatible with any new directives that may be added. We do like to give errors when things are provably an error, but otherwise we err on the side of not breaking the future.

**Comment by bjmiller** [comment]
Does this suggest the need for a SASS linter, then?

**Comment by chriseppstein** [comment]
@bjmiller It does. I'd love to integrate such a thing into compass.
