### ISSUE TITLE
SASS @extend rule: strange output

### ISSUE THREAD

**Issue by ghost** [sass/sass#76]
Hey there,

I have a problem using the @extend rule in sass.

I have the following rules in the .scss file:

```
.box {width:100px;}
.wrapper {background:black;}

.box.wrapper {margin-right:8px;}

.box1 {@extend .box; @extend .wrapper; background:red;}
.box2 {@extend .box; @extend .wrapper; background:green;}
```

The output in the css file is as follows:

```
.box, .box1, .box2 {width: 100px; }

.wrapper, .box1, .box2 {background: black; }

.box.wrapper, .box1, .box1.box2, .box2 {margin-right: 8px; }

.box1 {background: red; }

.box2 {background: green; }
```

Everything is correct except for the combination .box1.box2 in this line:

```
.box.wrapper, .box1, .box1.box2, .box2 {margin-right: 8px; }
```

Why does the algorithm combine .box1.box2 and so forth and applys the rule that I had specified for .box.wrapper?

It gets very bloated, especially with more classes, because it should just say:

```
.box.wrapper, .box1, .box2 {margin-right:8px;}
```

Am I missing something?
Is the interpretation from scss to css correct?
Can I somehow avoid this redundant code?

**Comment by nex3** [comment]
`.box1.box2` should indeed be omitted here, since it's a subselector of both `.box1` and `.box2`. I'll look into it.
