### ISSUE TITLE
Update to listen 1.0

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#764]
Compass will be upgrading to listen 1.0. It will make it hard to install sass & compass together if we have different version requirements.

**Comment by chriseppstein** [comment]
We've found it hard to integrate with their API. I may build a wrapper on top of their API and release it as a separate gem. Maybe we can share that.

**Comment by nex3** [comment]
This is blocked on guard/listen#111. I don't think there's a good way to work around that; manually ignoring recursively-listed files isn't suffiicent.

**Comment by stephanvane** [comment]
The `listen` gem is at version 1.3.1 now where guard/listen#111 should be fixed. 
Btw, The `Middleman` gem requires `listen ~> 1.2.2` at the moment, causing incompatibility with the sass 3.3.0 alphas :(

**Comment by nex3** [comment]
@stephanvane according to @thibaudgg, that's inaccurate.

**Comment by stephanvane** [comment]
You're right @nex3, misread some comments, sorry about that. Keep up the good work! :+1:

**Comment by nex3** [comment]
Merging this with #955.
