### ISSUE TITLE
Sass feature detection

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#766]
There's a number of sass features that we will add in the future which will be syntactically valid in the old version but still not working as intended.

Sass libraries that need to support multiple versions of Sass may be able to do so if we provide a function like `sass-supports($feature-name)` which returns true if the feature is present in the sass implementation.

Hat tip: this idea came from @eoneill.

**Comment by nex3** [comment]
This is reasonable. We could add this in the current master as a function that always returns false (since there are no usefully-detectable features until we add more in a future release).

**Comment by c-lliope** [comment]
#796 resolves this issue -- can we close it?

**Comment by chriseppstein** [comment]
Yep!
