### ISSUE TITLE
Incompatible units for equality operators

### ISSUE THREAD

**Issue by robocoder** [sass/sass#767]
Expecting:  Sass Error: Incompatible units: 'pt' and 'em'.

But these don't error out:

``` scss
@if 12px == 4em {
}
@if 12px != 4em {
}
```

**Comment by chriseppstein** [comment]
These are not equal because they can't be compared. You get similar behavior with `2 == "asdf"`. Use the `comparable` function to test if two numbers can be compared:

```
>> comparable(12px, 4em)
false
>> comparable(12px, 4pt)
true
```
