### ISSUE TITLE
Compass callbacks are not fired If compass is invoked via sass command line

### ISSUE THREAD

**Issue by Subash** [sass/sass#769]
I am doing something like this

`sass style.scss style.css --compass`

config.rb

``` ruby
css_dir = 'css/'
sass_dir = 'scss/'

puts 'not saved yet'

on_stylesheet_saved do |file|
    puts 'Saved'
end
```

I get the `not saved yet` message but never get the `Saved` message.
Configuration variables work as intended but the callback function doesn't get fired.

I have also opened an issue on compass repo https://github.com/chriseppstein/compass/issues/1298

**Comment by nex3** [comment]
This seems like a Compass issue, and even then I'm not sure this isn't just working as intended. `sass --compass` is intended as a convenience flag for when you want to import Compass's libraries, but you don't need all the infrastructure that Compass offers. Once you start using that infrastructure, you really ought to be using the `compass` executable.
