### ISSUE TITLE
How do i retrieve SASS warnings and debug messages programmatically when i compile with the `sass`/`scss` methods in Ruby?

### ISSUE THREAD

**Issue by lolmaus** [sass/sass#773]
Hi!

I'm creating a tiny web app similar to http://SassMeister.com that lets one compile SASS online.

I would like to output warnings and debug messages that SASS normally outputs to console, but i don't know how to read them programmatically.

I'm using Sinatra and i borrowed the SASS compilation code [from SassMeister](https://github.com/jedfoster/SassMeister/blob/master/sassmeister.rb#L104). SASS is compiled with the `sass` and `scss` methods and syntax errors are rescued with `rescue Sass::SyntaxError => e`.

Could you please show how can i retrieve SASS warnings and debug messages programmatically when i compile with `sass`/`scss` methods in Ruby?

**Comment by chriseppstein** [comment]
Set `Sass.logger` to a class that inherits from [`Sass::Logger::Base`](https://github.com/nex3/sass/blob/stable/lib/sass/logger/base.rb) and override the `_log` method.

**Comment by lolmaus** [comment]
Thank you Chris. ^_^

You wanted to say "set to an instance of a class".

I'll leave an example here in case someone else is interested.

``` ruby
class SassLogger < Sass::Logger::Base
  def _log(level, message)
    puts message # Parse messages here
  end
end

Sass.logger = SassLogger.new
```

Note that `@warn` messages will be ignored if `:quiet` option is true.

**Comment by lolmaus** [comment]
Hey Chris, i found out that only `@warn` messages are collected, while `@debug` go straight to console.

I didn't realizes that at first because i was using `puts` to test.

How do i collect both `@warn` and `@debug` messages?

Also, it reports the line number of the Ruby code. Is it possible to report the line number of the string of SASS code passed to the `sass` method?

**Comment by chriseppstein** [comment]
@lolmaus I'm skeptical about your assertion that Sass is reporting the ruby line number. Please open an issue about that with a reproducible test case. I have opened a new bug about `@debug` using `$stderr` instead of the logger.

**Comment by chriseppstein** [comment]
```
$ scss debug.scss
debug.scss:1 DEBUG: hello world
$ echo "@debug hi" | bundle exec scss
Line 1 DEBUG: hi
```

**Comment by lolmaus** [comment]
I'm using SASS via Sinatra's `sass` method, not via the command line. It reports like this:

> WARNING: yay
>          on line 108 of /opt/sassbin/app.rb

Should i open a new ticket?

**Comment by chriseppstein** [comment]
Yes, against the sinatra folks. Happy to help them fix their sass integration. Probably they're not setting the `:filename` option or setting it incorrectly.

**Comment by lolmaus** [comment]
I've filed the issue. Thank you for your kind help, @chriseppstein.
