### ISSUE TITLE
Escape block comments in error reporting comments

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#778]
From here: http://css-tricks.com/sass-style-guide/#comment-450812

**Comment by nex3** [comment]
Copying in case that link breaks before we can fix this:

> If a block comment is near your error, it ends the block comment SASS uses for outputting the backtrace in your generated CSS file
> 
> ``` css
> /*
> Syntax error: Invalid CSS after "  border": expected ";", was ": none"
>         on line 5 of /var/www/claassen/uzb2/html/css/component/forms/_jobsearch.scss
>         from line 35 of /var/www/claassen/uzb2/html/css/basic.scss
> 
> 1: /* General form styles */ <<< This comment ends the surrounding comment
> 2: .form
> 3: {
> 4:   background: whiteSmoke
> 5:   border: none
> 6: }
> 
> Backtrace:
> ...
> */
> ```
