### ISSUE TITLE
Variable Interpolation

### ISSUE THREAD

**Issue by vinayraghu** [sass/sass#780]
I heard that Sass 3.3 has maps that makes variable-interpolation like below possible 

Variables: 

```
$primary-color: #xxx;
$primary-color-light: #yyy;
$primary-color-dark: #zzz; 
```

Compiled CSS output:

```
.blk-primary-color{background-color: #xxx;}
.blk-primary-color-light{background-color: #yyy;}
.blk-primary-dark{background-color: #zzz;}
```

Meaning, print the value of the variable (for color) but also be able to print just the variable name (for the class name).

**Comment by chriseppstein** [comment]
So you just declare variables and you magically get selectors? I'm confused.

**Comment by vinayraghu** [comment]
Hey @chriseppstein 

Thanks for the prompt reply. Let me see if I can make this clearer
I want to know if it is possible to use my **Sass variable names** as **CSS selectors** using mixins 

So I have the following variables declared

```
$primary-color: #xxx;
$primary-color-light: #yyy;
$primary-color-dark: #zzz;

$class_name: $primary-color, $primary-color-light, $primary-color-dark;

@mixin do-something ($class-names){
    @each $i in $class-names {
      .blk-*** { background-color: #{$i}; }
    }
}
```

So in the #{$i} at the end, I want it to be replaced with the actual variable value (#xxx) from above 
But in the .blk-***, I want to print the name of the variable held by $i. 

$primary-color should print primary-color 
$primary-color-light should print primary-color-light
$primary-color-dark should print primary-color-dark

I think its one level of abstraction too deep. Just wanted to know if this is currently possible or possible through maps feature. Hope this helps clarify what I am really asking for

**Comment by chriseppstein** [comment]
I see. When maps are implemented you would do it like this:

``` scss
$primary-color: (null: #333, light: #fff, dark: #000);
@each $theme: $color in $primary-color {
  .blk-primary-color#{if($theme, "-#{$theme}", null)} { background-color: $color; }
}
```

Or a better structure may be to have each theme declare all the colors. but I think you get the point.

**Comment by vinayraghu** [comment]
Thanks @chriseppstein...Yeah I get the idea...very excited about the maps feature!!
