### ISSUE TITLE
Don't remove exclamation marks from loud comments

### ISSUE THREAD

**Issue by lboecker** [sass/sass#784]
I don't know who came up with this, but it doesn't make much sense to me.
When working with Middleman, the comment on top of my main stylesheet looks like this

``` css
/*!! Copyright ... */
```

and both exclamation marks end up removed. The loud comment at the top of normalize.css gets removed completely because it contains only 1 exclamation mark rather than 3 (!). I'm not sure if saving a couple of bytes is worth the hassle. Thoughts?

**UPDATE:** https://github.com/nex3/sass/issues/784#issuecomment-18773351

**Comment by chriseppstein** [comment]
I came up with it. It's not about saving bytes. It's about supporting the use case of producing a comment that does not start with an exclamation mark. Not everyone is this excited about their copyright notices. Sass only removes one exclamation mark.

**Comment by nex3** [comment]
It's worth noting that it looks like most other minifiers don't remove the `!` from `/*!`-style comments.

**Comment by lboecker** [comment]
@chriseppstein Just to be clear: I don't care much about my own copyright either, but I believe the library authors deserve some credit and I'm legally required to leave their copyright in there anyway.

**Comment by chriseppstein** [comment]
I'm open to alternative suggestions that preserve the use case of enabling a person to have a comment that does not have a `!` in the output.

**Comment by lboecker** [comment]
@chriseppstein The use-case you're describing is relevant for all output styles but compressed, right? Maybe changing the behaviour based on the output style is the simplest solution. [Most](https://github.com/GoalSmashers/clean-css#how-to-use-clean-css-programmatically) [other](https://github.com/gruntjs/grunt-contrib-uglify#preservecomments) minifiers take some kind of options hash, but I'm not sure if thats practical since there's only one option in the first place.

**Comment by chriseppstein** [comment]
@superlukas it applies specifically to compressed mode. That is the point of loud comments.

**Comment by nex3** [comment]
I'm not sure what the problem with including `!` in the output is. It's a widely-recognized indicator that the comment shouldn't be compressed away; the desire not to compress the comment isn't something that goes away after Sass's compression pass.

**Comment by lboecker** [comment]
@nex3 has a point. I just did some testing though and @chriseppstein is right too, Sass doesn't remove the comments. It seems to be a problem with Sprockets and/or Sprockets-Sass. I guess the content is piped through Sass more than just once and the comments are lost somewhere on the way.

**Comment by chriseppstein** [comment]
@nex3 Sass cares about the output. We want it to be beautiful. To look like hand-written code. I want to enable that, but no one has specifically asked for this so I'm not going to go to the mat for it. Feel free to take out the stripping logic, the multi-processor use case is a compelling one.

**Comment by chriseppstein** [comment]
Closed by 959ac903776876458b8c6cfb5abe4af45a6359a9

**Comment by jdmarshall** [comment]
I'm in the same boat as superlukas.  It would be great to figure out why the ! gets removed twice but in the meantime I'm glad you're preserving it.

Curious why Sass gets invoked twice (if in fact it is).  I'm using Compass as well and wondering if it's the combination.

**Comment by lboecker** [comment]
@jdmarshall You shouldn't be affected by this issue if you're using Compass' or Sass' CLI. I've tested both and they're doing everything right. I blame [petebrowne/sprockets-sass](https://github.com/petebrowne/sprockets-sass) in my case (or some other part of my asset pipeline).
