### ISSUE TITLE
sass-convert makes invalid output due to comments due converting from Scss to Sass

### ISSUE THREAD

**Issue by ryanburnette** [sass/sass#785]
@nex3 Here's the issue you asked me to open based on my comment on https://github.com/nex3/sass/pull/713.

I wanted to convert some Scss files from a project I use frequently into Sass just because that's my preferred syntax. I found that some comment structures seem to render invalid output from sass-convert.

Many files in this project error out when converted. I had a brief discussion with the owner of that repo you can reference as well. Perhaps the comments are formatted in such a way that they are to blame. I just wouldn't have though it would matter.
https://github.com/jlong/sass-twitter-bootstrap/issues/75

Here's an example.

Original:
[original.scss](https://dl.dropboxusercontent.com/u/8483722/Github/Sass/sass-convert-issue/original.scss)

Command:
`sass-convert original.scss sass-output.sass`

Output:
[sass-output.sass](https://dl.dropboxusercontent.com/u/8483722/Github/Sass/sass-convert-issue/sass-output.sass)

**Comment by nex3** [comment]
This is a lot of code to sort through. Can you copy the specific piece of code that converted wrong onto this issue?

**Comment by ryanburnette** [comment]
It's super easy to see if you open them side-by-side in an editor that color where the error starts. It ends up opening a multiline comment then never closes it. Screenshot again.

![screen shot 2013-05-31 at 5 42 34 pm](https://f.cloud.github.com/assets/2252601/593566/143ac714-ca3b-11e2-91ff-ed5f2559d09f.png)

**Comment by ryanburnette** [comment]
Compare line 48 on the left side to line 43 on the right.

**Comment by nex3** [comment]
It looks like your syntax highlighter is broken.

``` sass
=ie7-inline-block
  *display: inline
  /* IE7 inline-block hack
  *zoom :1
```

is valid Sass. Comments in Sass are line-based, not block-based; they don't require a terminating `*/`.

**Comment by ryanburnette** [comment]
Gotcha. I thought only `//` was a line comment. Thanks!

**Comment by chriseppstein** [comment]
@ryanburnette Actually both of them are block based too, If you indent under them:

``` sass
=ie7-inline-block
  *display: inline
  /*
    This is commented out
    And so is this. but the comment will be in the output unless compressed.
  //
    This is commented out
    And so is this. but the comment will never be in the output.
  *zoom :1
```

**Comment by ryanburnette** [comment]
I use some Sass syntax highlighting for Sublime Text 2 that I found on Github. That's what caused the confusion for me. I'm looking for something better as we speak.
