### ISSUE TITLE
Add a to_color() function?

### ISSUE THREAD

**Issue by robocoder** [sass/sass#787]
Use case:  To explicitly cast an interpolated string to a color object.

For example, the following doesn't work:

```
$c : '89';

h3{
    color: rgba(#{"#"}#{$c}#{$c}#{$c}, 0.5);
}
```

**Comment by chriseppstein** [comment]
I don't find that use case more compelling than this:

``` scss
$c: 137; // '89' in hex
rgba($c,$c,$c,0.5)
```
