### ISSUE TITLE
Add IntelliJ to the list of editors.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#792]
Got this in an email:

Regarding the list of supporting SASS editors.. consider adding the IntelliJ IDEA family of IDEs to the list.

http://www.jetbrains.com/idea/webhelp/code-style-sass.html

IDEA has many different spin off IDEs (phpStorm, webStorm, etc), similar to eclipse, but as far as I know they're all owned and managed by JetBrains.  The community usually refers to all of them as either their proper name, as generically as all being "IntelliJ IDEA".

http://www.jetbrains.com/idea

**Comment by nex3** [comment]
Closed by 7b55c2f44276a427431972b33756da54a430ff1f.
