### ISSUE TITLE
Staleness Checker is not threadsafe

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#799]
the @dependencies ivar on the StalenessChecker class uses a hash implementation in jruby that is not threadsafe.

**Comment by thedarkone** [comment]
This can be fixed by using `ThreadSafe::Cache` from [thread_safe](https://github.com/headius/thread_safe) gem.

All that is required is to replace this:

``` ruby
@dependencies_cache = {}
```

with this:

``` ruby
require 'thread_safe'
@dependencies_cache = ThreadSafe::Cache.new
```

**Comment by chriseppstein** [comment]
@thedarkone I was just looking at that gem. What is the benefit of using `ThreadSafe::Cache` instead of `ThreadSafe::Hash`?

**Comment by thedarkone** [comment]
@chriseppstein basically both `TS::Array` and `TS::Hash` have a really naive ["toy" implementations](https://github.com/headius/thread_safe/blob/master/lib/thread_safe.rb). Whereas `TS::Cache` (a Hash like cache) is a "serious business (tm)" thing :) (truly concurrent, mostly lock-free, with custom Ruby VM dependent backends: native JRuby ext, Rubinius, MRI etc), it also has useful "cache" methods like `compute_if_absent(key, &block)`, `put_if_absent(key, value)`, `get_and_set(key, value)` and others.

I wouldn't recommend using `TS::Array` or `TS::Hash`, on other hand `TS::Cache` should be production ready (and is a Rails 4.0 dependency).

**Comment by chriseppstein** [comment]
@nex3 do you object to adding this gem as a dependency?

**Comment by nex3** [comment]
Nope.
