### ISSUE TITLE
German special chars destroyed

### ISSUE THREAD

**Issue by alexhass** [sass/sass#805]
See https://github.com/djesse/yaml4-sass/issues/18, please. Please fix this bug.

**Comment by nex3** [comment]
This is impossible to debug without more information. What is a simple input file that triggers the problem? What output does it produce for you? What encoding does the input file use? What's your system encoding?

The issue you linked contains several relevant quotes from the Sass reference. Have you tried adding a `@charset` declaration to your file?

**Comment by alexhass** [comment]
I'm not maintaining the YAML sass code.But all the code you need is in this repository and I think the hack https://github.com/djesse/yaml4-sass/commit/e2b3b5037332f30f32c62d497762abd1dba762fa is not the propper way how this need to be fixed. As noted in the other case this is a bug of SASS under Windows.

My best guess is that cmd under windows is codepage 1252. This must cause this type of issues. I cannot say anything about MacOSX, but as noted by djesse OSX does not create this type of broken code.

From my understanding you only need to add German special chars to the sass files and make them showing up in the resulting CSS files as comments to reproduce the bug.

Example chars are: 

```
äÄ
üÜ
öÖ
ß
```

In other languages there should be similar issues.

**Comment by djesse** [comment]
Hi. I am the owner of the YAML project. 

> From my understanding you only need to add German special chars to the sass files and make them showing up in the resulting CSS files as comments.

No, that's not a solution. This is what causes this bug as there are all these special chars in the Sass-files. I have to use a tricky Grunt task to replace the characters that Sass destroys during compiling the CSS.

**Comment by alexhass** [comment]
This was meant as repro case only.

**Comment by djesse** [comment]
@nex3 

Files are saved as UTF8, all files have @charset "utf8" declaration and the config sets encoding to utf8 too. It still happens when compileing Sass via Compass (I don't use Sass alone) on Windows, that these chars get destroyed.

**Comment by nex3** [comment]
> Files are saved as UTF8, all files have @charset "utf8" declaration and the config sets encoding to utf8 too. It still happens when compileing Sass via Compass (I don't use Sass alone) on Windows, that these chars get destroyed.

I'm confused. `@charset "utf8"` is invalid; the encoding's name is "utf-8". This should throw an error. If it's not throwing an error, something much deeper is going wrong.

**Comment by djesse** [comment]
Sorry, this was just a typo here. Of course @charset "utf-8" is used.

**Comment by nex3** [comment]
When I look at https://github.com/djesse/yaml4-sass/blob/master/sass/yaml/screen/typography.scss, I don't see a `@charset` declaration. Where are you declaring it exactly?

**Comment by alexhass** [comment]
I also don't see the charset declaration in the old yaml4-sass project where the chars have been broken. The project has been moved to a new location yamlcss and now I see most of not all .scss files start wirth @charset "utf-8";. Maybe the issue is now solved and the dirty string replacement workaround in the Grunt file can be removed?
