### ISSUE TITLE
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

### ISSUE THREAD

**Issue by deemytch** [sass/sass#807]
source file main.sass:

<pre>
.text-info {
  display: none;
}
</pre>

versions:

<pre>
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-linux]
Sass 3.2.9 (Media Mark)
</pre>

command output:

<pre>
$ echo $LANG
ru_RU.utf8

$ sass --watch main.sass:main.css 
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error main.sass (Line 2: Invalid CSS after "none": expected expression (e.g. 1px, bold), was ";")
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
  Use --trace for backtrace.

$ sass main.sass:main.css 
Syntax error: Invalid CSS after "none": expected expression (e.g. 1px, bold), was ";"
        on line 2 of main.sass
  Use --trace for backtrace.

$ sass -E utf-8 --watch main.sass:main.css  --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error main.sass (Line 2: Invalid CSS after "none": expected expression (e.g. 1px, bold), was ";")
/home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:193:in `sub': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:193:in `relative_to_base'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:135:in `ignored?'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:328:in `block in important_paths'
  from /usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
  from /usr/lib/ruby/2.0.0/find.rb:42:in `catch'
  from /usr/lib/ruby/2.0.0/find.rb:42:in `find'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:322:in `important_paths'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:158:in `build'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `block (2 levels) in start'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `each'
  from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `block in start'
</pre>

**Comment by nex3** [comment]
There are a couple of things going on here. First, you're using SCSS syntax in a `.sass` file. `.sass` is the extension for [the indented syntax](http://sass-lang.com/docs/yardoc/file.INDENTED_SYNTAX.html). That's where the syntax errors are coming from in the latter two invocations.

Second, in the first invocation, it looks like Ruby is unable to determine your system's default external encoding. Given that `LANG` seems to be set properly, I'm not sure why this would be. What happens when you run `ruby -e "puts Encoding.default_external"`?

**Comment by deemytch** [comment]
I renamed main.sass to main.scss

<pre>
$ sass --watch main.scss:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
  Use --trace for backtrace.
$ echo $?
1
$ cat main.scss
.text-info {
  display: none;
}
$ ruby -e "puts Encoding.default_external"
UTF-8
$ sass main.scss main.css
# return code 0, worked
$ sass --watch main.scss:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
  Use --trace for backtrace.
$ sass --watch main.scss:main.css --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:193:in `sub': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:193:in `relative_to_base'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:135:in `ignored?'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:328:in `block in important_paths'
    from /usr/lib/user/2.0.0/find.rb:43:in `block in find'
    from /usr/lib/user/2.0.0/find.rb:42:in `catch'
    from /usr/lib/ruby/2.0.0/find.rb:42:in `find'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:322:in `important_paths'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/directory_record.rb:158:in `build'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `block (2 levels) in start'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `each'
    from /home/user/.gem/ruby/2.0.0/gems/listen-0.7.3/lib/listen/multi_listener.rb:41:in `block in start'
$ cat main.sass
.text-info
  display: none
0$ sass main.sass main.css
0$ sass --watch main.sass:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
  Use --trace for backtrace.
  
1$
0$ locale -a
C
en_US.utf8
POSIX
ru_RU.utf8
0$ echo $LANG
ru_RU.utf8
0$ export LANG=ru_RU.UTF-8
0$ cal
      Июнь 2013     
Пн Вт Ср Чт Пт Сб Вс
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
0$ sass --watch main.sass:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
  Use --trace for backtrace.
1$
</pre>

My system is Archlinux, I did the fresh install about a week ago, I did not modified ruby and any others standard packages, sass is installed in $HOME/.gem/*

**Comment by deemytch** [comment]
@nex3 Thank you for the tip about scss.

**Comment by nex3** [comment]
Interesting... this looks like [guard/listen](/guard/listen) bug. I'd try posting there and see if they can help.

**Comment by chriseppstein** [comment]
it looks like this is [already fixed](https://github.com/guard/listen/issues/76). We just need to land my [listen upgrade](https://github.com/nex3/sass/pull/777).

**Comment by Flashwalker** [comment]
It's all about cyrillic symbols in path to listening directory. Shame on you, Russophobes.
