### ISSUE TITLE
--line-numbers does not always work

### ISSUE THREAD

**Issue by richardbarran** [sass/sass#81]
Hi there,
I may have found a bug with --line-numbers.
Let's create 2 test files in a folder called /test/:
## master.scss

```
h1 { color: red; }

@import "imported_file";
```
## _imported_file.scss

```
h2 { color: blue; }
```

Then I watch for changes with:
    sass --line-numbers --watch test
1. If I make a change to master.scss, both h1 and h2 are prefixed by a comment that points back to the source file.
2. If I make a change to _imported_file.scss, only the h2 is prefixed by a comment.

I am using sass version 3.0.25.

**Comment by nex3** [comment]
I can't reproduce this on the latest stable, so I'm going to close it.

**Comment by richardbarran** [comment]
Upgraded to 3.1.4 and no longer have this bug. Thanks for all the hard work!
