### ISSUE TITLE
if structure for dynamically adjusting variables based on existing variable?

### ISSUE THREAD

**Issue by Wolfr** [sass/sass#817]
Hi,

I am building a UI framework ( getclank.com ) One component is buttons:

http://getclank.com/demos/buttons.html

I want to dynamically adjust the primary button color based on the value given for a variable called $accent-color. E.g. if the accent color is light, I would want to make the primary button darker, but when the accent color is dark, I want to make my primary button brighter.

Now, if I try to do this with @if it doesn't update the $accent-color-primary value, instead I get a message that it doesn't exist:

```
$accent-color: #8216AF !default; // Accent color is supposed to be something like purple, red, blue
$accent-color-primary: adjust-saturation(adjust-lightness($accent-color, 15%),80%) !default;

@if (lightness($accent-color) > 50%) {
  $accent-color-primary: adjust-saturation(adjust-lightness($accent-color, 60%),80%) !default;
} @else {
  $accent-color-primary: adjust-saturation(adjust-lightness($accent-color, 20%),20%) !default;
}
```

Any ideas on how to achieve this within the current Sass language?

**Comment by cimmanon** [comment]
That code seems to compile to me, $accent-color-primary is set to #b913ff.  Are you sure you aren't initializing the variables within a different scope?

**Comment by Wolfr** [comment]
Hm it's compiling because it's set on line 2, if you remove that line you'll see the error

```
$accent-color: #8216AF !default; // Accent color is supposed to be something like purple, red, blue

@if (lightness($accent-color) > 50%) {
  $accent-color-primary: adjust-saturation(adjust-lightness($accent-color, 60%),80%);
} @else {
  $accent-color-primary: adjust-saturation(adjust-lightness($accent-color, 20%),20%);
}
```

**Comment by cimmanon** [comment]
Right, variables defined within an `@if` statement are only local within that block (see: scope).  If you need to use it outside the `@if` statement, you initialize it outside.  Alternatively, you could use the `if()` function:

``` scss
$accent-color-primary: if(lightness($accent-color) > 50%, adjust-saturation(adjust-lightness($accent-color, 60%),80%), adjust-saturation(adjust-lightness($accent-color, 20%),20%));
```

**Comment by Wolfr** [comment]
Thanks so much @cimmanon , this helped me underway. I haven't nailed the issue but I do have a deeper understanding of the Compass/Sass color functions now ;)

**Comment by nex3** [comment]
If I'm reading this right, the issue has been resolved.
