### ISSUE TITLE
Watch a directory, compile a single file

### ISSUE THREAD

**Issue by hlidotbe** [sass/sass#82]
Hi,

It would be nice to be able to make sass watch a directory but compile a single file (something like `--watch input-file:input-dir:output-file`)

We usually work with a single scss file @importing a bunch of "partials" scss which allows us to organize them cleanly (think chrome.scss, colors.scss, ...). This configuration make --watch useless because it can't see that the files have changed and never recompiles the "master" (which is almost never touched except when adding a new file).

Right now we use a quick and ugly Cocoa app that watches a given folder and calls sass on the master file but it would be better if it was supported natively.

If there is no interest I may try to do it when I have a bit of free time.

Thanks,
Hugues

**Comment by nex3** [comment]
You can accomplish the same purpose by adding an underscore to the beginning of your filenames (e.g. `_chrome.scss`, `_colors.scss`) and then compiling the entire directory. For more information, see [the Sass reference](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#partials).
