### ISSUE TITLE
Can you provide any assistance with Eclipse // Sass integration issues

### ISSUE THREAD

**Issue by crispen-smith** [sass/sass#820]
Apologies for contacting you in this method but I wasn't sure how else to go "to the source" as it were.  I'm sure I'm not the first person to encounter this and I'm hoping that someone may have shared a solution with you, or you may have discovered one.

The problem I'm having is outlined here: http://stackoverflow.com/questions/17285263/can-eclipse-formatter-be-customized-to-avoid-mangling-sass-scss

**Comment by bjmiller** [comment]
This isn't a SASS/SCSS problem, it's entirely within eclipse.  So, you have to solve it from the eclipse side.  You'd have to write your own brand new editor and formatter to prevent this.  The rules for CSS don't cover SCSS, it really is a different language.

Luckily, you can use Aptana, which has a pretty decent SCSS editor.  Not perfect, but syntax highlighting and Ctrl-Alt-F work, at least.

**Comment by crispen-smith** [comment]
Yes, I agree it's an Eclipse problem which is why the best I was hoping for was a referral, hoping that someone else had already solved it.  It seems very odd to me that two project with such healthy eco-systems and communities around them haven't been handshaked already with an installable. 

Aptana it is then.  I've been trying to avoid that because I've grown accustomed to my personal build of Eclipse but since it seems to solve both the GIT and SCSS/CSS problems...   

Thank you greatly for the help.

**Comment by bjmiller** [comment]
For the record... With the notable exception of the work being done by the Appcelerator team on Aptana, the Eclipse community has more-or-less stopped actively adding support for newer languages to Eclipse.  It's a shame, really.  There are ways in which it's still the best editor out there.

As far as Open Web languages go, most of the newer work is going into Orion.  I'm not really a fan of writing my code in the browser like that, though.

**Comment by crispen-smith** [comment]
That really is a shame.  Eclipse is about the best option today on a
windows box, I understand that Sublime text can give it a run for it's
money on Mac, but it's still payware and open source Eclipse seems to beat
that for price.  Ah well.   I'm not even aware of Orion, I'll need to look
into it.
