### ISSUE TITLE
Out of date doc for Sass::Plugin::Rack

### ISSUE THREAD

**Issue by bambery** [sass/sass#824]
Sass 3.2.9 (Media Mark)

`options=` was deprecated, meaning `options.merge` will fail as given in this example:

http://sass-lang.com/docs/yardoc/Sass/Plugin/Rack.html

Also, though you have to `require sass/plugin/rack`, `use Sass::Plugin::Rack` is not strictly necessary to use Sass::Plugin if you are using it just to compile multiple files or folders on a filesystem from sass to css, as one would do for a precompile rake task, and as is suggested in the engine docs:

http://sass-lang.com/docs/yardoc/Sass/Engine.html

The phrasing of the two doc pages seems somewhat contradictory as to what exactly Sass:Plugin can be used for.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
