### ISSUE TITLE
@import fails to find partials on Windows if path contains "[" character (left square bracket)

### ISSUE THREAD

**Issue by snobo** [sass/sass#827]
On Win 7/64, if a SASS file is at the path that contains any _left_ square bracket character, e.g. "c:/dev/[ web ]/my_project", @import directives can't find partials and compilation fails. Having a _right_ square bracket character in the path doesn't cause the same effect.

Trivial test:

**test.scss**

``` css
@import "partial";
```

**partial.scss**

``` css
body {
  color: black;
}
```

put it in the folder named "c:/[ test ]" and try to compile.

**Comment by chriseppstein** [comment]
I have no idea what could cause this and I don't have such an environment to use for testing. Going to need some help from the community on this one.

**Comment by gabrielfreiberg** [comment]
I am experiencing this on Mac OSX using Ant Builder in Eclipse IDE to kick off Sass

**Comment by nex3** [comment]
Fixed by 59d3e9d5197ae0c3ac14943328b1f4d3eaf7e04e.
