### ISSUE TITLE
mixin shorthand does not pass syntax check in .scss file, only .sass

### ISSUE THREAD

**Issue by kimdcottrell** [sass/sass#830]
sass --version #Sass 3.2.9 (Media Mark)

SASS FILE (.scss):
# copied from http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#mixin-content

=apply-to-ie6-only
- html
  @content

+apply-to-ie6-only
  #logo
    background-image: url(/logo.gif)

ERROR:
/*
Syntax error: Invalid CSS after "/\* END WORKS */": expected selector or at-rule, was "=apply-to-ie6-only"
        on line 25 of /var/www/dev1_html/wp-content/themes/reverie-child/sass/test.scss

Backtrace:
/var/www/dev1_html/wp-content/themes/reverie-child/sass/test.scss:25
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/scss/parser.rb:1146:in `expected'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/scss/parser.rb:1084:in`expected'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/scss/parser.rb:28:in `parse'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/engine.rb:342:in`_to_tree'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/engine.rb:315:in `_render'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sass-3.2.9/lib/sass/engine.rb:262:in`render'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:140:in `block (2 levels) in compile'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:126:in`timed'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:139:in `block in compile'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/logger.rb:45:in`red'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:138:in `compile'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:118:in`compile_if_required'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:103:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:101:in`each'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:101:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:126:in`timed'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/compiler.rb:100:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:147:in`recompile'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/path.rb:73:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/path.rb:73:in`run_callback'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/path.rb:55:in `callback_action'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/path.rb:35:in`update'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/state/directory.rb:39:in `block in modified'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/state/directory.rb:37:in`each'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/state/directory.rb:37:in `modified'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/state/directory.rb:18:in`refresh'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/backends/inotify.rb:12:in `block in add_handler'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:201:in`call'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:201:in `block in watch'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/watcher.rb:41:in`[]'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/watcher.rb:41:in `callback!'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/event.rb:128:in`callback!'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in `block in process'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in`each'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in `process'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:217:in`run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/backends/inotify.rb:20:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm/monitor.rb:26:in`run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/fssm-0.2.10/lib/fssm.rb:70:in `monitor'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:87:in`perform'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in`execute'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in`run!'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:44:in`call'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p195/bin/compass:23:in`load'
/usr/local/rvm/gems/ruby-2.0.0-p195/bin/compass:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `<main>'
_/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Syntax error: Invalid CSS after \"/_ END WORKS */\": expected selector or at-rule, was \"=apply-to-ie6-only\"\A         on line 25 of /var/www/dev1_html/wp-content/themes/reverie-child/sass/test.scss"; }

..but if I switch the file to .sass

/\* END WORKS */
- html #logo {
  background-image: url(/logo.gif); }

**Comment by Snugug** [comment]
This works as designed. The shorthand syntax is _only_ available in the .sass file format. There is an issue to bring [.sass style mixins to .scss](https://github.com/nex3/sass/issues/366), but it's not available yet.
