### ISSUE TITLE
`index` should return `null` for a non-existent element rather than `false`

### ISSUE THREAD

**Issue by nex3** [sass/sass#832]
The current API for `index` was written before SassScript had a `null` type, but now that we do we should move it to return `null`.

We could go through a deprecation process for this, which would involve detecting whenever the return value was used somewhere where the distinction between `null` and `false` matters (e.g. `index(...) == false`). It's unlikely that anyone's doing that, though, so we may be able to get away with no deprecation process.

**Comment by chriseppstein** [comment]
So we'd need to make a DeprecatedFalse class or something to that effect?

**Comment by KittyGiraudel** [comment]
Why not returning `false`? It makes sense.

**Comment by chriseppstein** [comment]
I think we should also return `null` instead of `0` for `str-index()`.

**Comment by nex3** [comment]
> @chriseppstein wrote:
> So we'd need to make a DeprecatedFalse class or something to that effect?

If we wanted to do the deprecation thing, yes.

> I think we should also return `null` instead of `0` for `str-index()`.

Agreed.

> @HugoGiraudel wrote:
> Why not returning `false`? It makes sense.

Because `null` is the standard value for indicating a lack of a result.

**Comment by pdaoust** [comment]
@chriseppstein I agree with returning `null` too -- I was just toying around with `str-index()` for the first time today, expecting it to work like `index()`, and discovered this myself. (By the way, thank you for having made `index()` return a falsy value rather than `-1` like JavaScript does.)

**Comment by nex3** [comment]
`0` isn't falsy.

**Comment by pdaoust** [comment]
@nex3 I was referring to the return value of `index()` rather than `str-index()`.
