### ISSUE TITLE
Use hyphenated names in Sass function documentation

### ISSUE THREAD

**Issue by nex3** [sass/sass#835]
Right now, the [Sass function documentation](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html) uses the Ruby-style underscored names for functions with multiple-word names rather than Sass-style hyphenated names (e.g. `scale_color` as opposed to `scale-color`). The underscored names work fine, but they're not the recommended style.

Unfortunately, if a hyphenated name is used in YARD's `@overload` tag, it cuts off the hyphen and anything after it. We're likely to need to monkey-patch YARD to get this to work as desired.

**Comment by nex3** [comment]
Pinging @lsegal to see if he has insight into the best way to hack the `@overload` tag.

**Comment by lsegal** [comment]
We're using the METHODMATCH regular expression to detect the method name:

https://github.com/lsegal/yard/blob/master/lib/yard/tags/overload_tag.rb#L52

You could alias chain that method (or #initialize), or modify the METHODMATCH regex. The latter could cause oddities in the parser when parsing legitimate Ruby code, though.

Both of these would require an extension/plugin btw. I'd be happy to whitelist your project on rubydoc.info if you end up going this route.

**Comment by nex3** [comment]
I'm closing this out because we plan to migrate away from Ruby Sass's documentation for the official function documentation (see https://github.com/sass/sass-site/issues/205).
