### ISSUE TITLE
Allowing to generate absolute path for sourcemaps

### ISSUE THREAD

**Issue by fcamblor** [sass/sass#838]
Sourcemap is working fine for me, except in case where I generate sourcemaps in a `generated tmp folder`.

I'm doing this because I consider sourcemap as being volatile dev-specific files for debugging, thus, I won't commit them in my SCM.
This is the approach made by yeoman.

I succeeded in using the grunt-contrib-sass plugin in [this pull request](https://github.com/fcamblor/technostore/pull/1) but I'm facing 2 limitations due to sourcemap path being relative to initial scss file.

It would solve my main concerns if we were able to generate some absolute paths, thus changing `--sourcemaps` to `--sourcemaps=none(default if not set)|relative(actual behaviour)|absolute(new behaviour)`
In that case, I could keep my scss files inside app/styles/ directory and reference them (with absolute file:// paths) in generated sourcemap files located in .tmp/styles/ directory

ATM, to workaround this, I copy the scss files in the .tmp/styles/ folder in order to generate a good relative url. And then, I must track modifications made on .tmp/styles/_scss files (in chrome live edit for instance) and copy them back to app/styles/_scss files.

WDYT ?

**Comment by robwierzbowski** [comment]
Why not generate sourcemaps to the css directory by default? I'm assuming maps are wiped every compile, just like the CSS, and maps aren't something you want to version, just like the CSS. 

This would work in a Yeoman workflow as well.

**Comment by fcamblor** [comment]
What is the `css directory` you're talking about ?

`.tmp/styles/` directory ? (directory where css generated files are compiled to)

**Comment by robwierzbowski** [comment]
I meant for Sass in general, generating in the Sass output directory. In Compass it's called `css_dir`.

That would cover our Yeoman workflows, because Grunt points the output directory to `.tmp/styles` for development, but also any stand alone Sass workflow.

**Comment by fcamblor** [comment]
In fact, if I take the yeoman case we have :
- `app/styles/` directory which contains SASS files
- `.tmp/styles/` directory which contains generated CSS files

This is fine (to my POV) because it allows to put `.tmp/` directory in gitignore and not synchronizing any generated file in this hierarchy.

Problem is : if we decide to generate sourcemaps in `.tmp/styles/` directory, we will have relative paths in sourcemaps which lead to `app/styles/` directory.
That is to say, something like this :

``` .tmp/styles/main.css.map
{
"version": "3",
"mappings": "AAWA,KAAM;EACJ",
"sources": ["../../app/styles/main.scss"],
"file": "main.css"
}
```

In yeoman, content is served from both `app/` and `.tmp/` directories.
So, when the browser will load the `styles/main.css.map` file below, it will try to resolve SASS file to something like `http://localhost:9000/styles/../../app/styles/main.scss` which doesn't exist from a browser POV.

A better solution, here, would be to generate an absolute sourcemap path like this :

``` .tmp/styles/main.css.map
{
"version": "3",
"mappings": "AAWA,KAAM;EACJ",
"sources": ["file:///path/to/project/app/styles/main.scss"],
"file": "main.css"
}
```

And we could achieve this by passing an `absolute` parameter in the --sourcemaps CLI, as stated in the issue description.

WDYT ?

**Comment by bestander** [comment]
:+1:

**Comment by robwierzbowski** [comment]
I see what you're saying now. :thumbsup: from me too.

**Comment by nex3** [comment]
The `sass` executable doesn't know anything about how you're serving your files. It doesn't know if `file:` URIs will work for you or not. It does the most widely useful thing it can: it assumes that you'll be accessing your CSS, SCSS, and source maps from the same server and generates relative links between them. If you aren't serving the SCSS or the source maps, this will obviously be a problem, but in that case there's no way to make a sourcemap that will work outside the context of your machine anyway.

If you want to customize the URIs that are used to link sourcemaps, input, and output together, that's reasonably straightforward using Ruby:

``` ruby
css, sourcemap = Sass::Engine.for_file(sass_path, options).
  render_with_sourcemap("file://#{sourcemap_path}")
File.open(css_path, 'w') {|f| f.write(css)}
File.open(sourcemap_path, 'w') do |f|
  f.write(sourcemap.to_json(css_uri: "file://#{css_path}"))
end
```

**Comment by timelf123** [comment]
We've been working around this one by an automatic find/replace (removing extraneous path info) every time the stylesheet is generated. Hacky, but works

**Comment by chanpory** [comment]
@nex3 confused where I should put the ruby code example to make sourcemap URLs absolute. Is there some in config.ru where I should put it?

**Comment by nex3** [comment]
@chanpory that snippet is intended to run as a standalone script (with some variables set beforehand). If you want to integrate it with an existing build process, the details of that will depend on how the build process works.

**Comment by gaboesquivel** [comment]
:+1:
