### ISSUE TITLE
Allow disabling concatenation of files

### ISSUE THREAD

**Issue by ansman** [sass/sass#842]
During development I prefer to not concatenate my javascript or CSS files so I can see which file errors occur in etc.

This doesn't seem possible at the moment when using SASS.

This could potentially be implemented using `@import` in CSS.
I don't know how the SASS compilation works at all but with sprockets it's possible to get an array of filenames back when requesting the path to a javascript file so perhaps the same is possible with SASS?

**Comment by chriseppstein** [comment]
@nex3 here's a very valid use case for alloying dynamic imports. This should be implementable in "user space" based on a conditional, but it's not.

See #739.

**Comment by chriseppstein** [comment]
Closing. This must be done by the author in Sass itself in order to work, it cannot be a magic feature.
