### ISSUE TITLE
Import Google font doesn't follow structure

### ISSUE THREAD

**Issue by ghost** [sass/sass#843]
I imported few fonts from Google API, and the Import line goes top of the page. No matter where I put the import function in scss file, the output goes at top of css(compiled) page.

To give clear view of the issue, my scss file is here where I import the code:
https://github.com/rajibmp/mak/blob/master/sass/_fonts.scss

This is the output page after compiling scss:
https://github.com/rajibmp/mak/blob/master/css/style.css

**Comment by chriseppstein** [comment]
The CSS import directive is required to be at the top of a CSS file. This is Sass saving you from yourself :four_leaf_clover:

From the [spec](http://www.w3.org/TR/CSS2/cascade.html#at-import):

>  In CSS 2.1, any `@import` rules must precede all other rules (except the `@charset` rule, if present).

**Comment by cimmanon** [comment]
Look a little closer.  Yes, `@import` must **must precede all other rules**.  The OP didn't make it clear, but the problem is that they want to have the comments appear with the import.

What they want:

``` css
/* comment here about the file that's being imported */
@import url('somefile.css');
```

What they're getting:

``` css
@import url('somefile.css');
/* comment here about the file that's being imported */
```

Comments _are_ allowed to precede imports.

**Comment by chriseppstein** [comment]
I see. Good catch.

I guess we could only move the import node if we detect it was in an illegal place.

Associating comments to selectors and directives is a tricky concept. It's not obvious that a comment is always documenting the thing below it. Sometimes it is a piece of code that is disabled, etc.
