### ISSUE TITLE
SCSS will not compile when using `--sourcemap` and `--stdin`

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [sass/sass#846]
Using: Sass 3.3.0.alpha.198 (Bleeding Edge)

When using `--stdin` and `--sourcemap` together I get this error:

```
Error: TypeError: can't convert nil into String
```

(docpad/docpad-plugin-sass#14 @balupton)

**Comment by chriseppstein** [comment]
I don't know what we can do for sass from stdin, so we should have a better error message.

**Comment by balupton** [comment]
Out of curiosity, what are the technical constraints on why using sourcemaps for stdin isn't possible?

**Comment by chriseppstein** [comment]
The source map gives a path to the source file. When the file comes from stdin, we can't know where the source file is.

**Comment by 10xLaCroixDrinker** [comment]
Couldn't you use `--loadPath`?

**Comment by chriseppstein** [comment]
load paths are where to look for the imported files, not the primary source file.

**Comment by 10xLaCroixDrinker** [comment]
You could require `--sourcemap` to be `--sourcemap FILE` when using `--stdin`

**Comment by chriseppstein** [comment]
If you know where the file is, you don't need to use stdin, right?

**Comment by 10xLaCroixDrinker** [comment]
Not quite. See docpad/docpad-plugin-sass#14

**Comment by nex3** [comment]
The command-line API is designed to accommodate common use cases. If you want to do something more complex -- for example, pass input on stdin while also providing a filename -- you should write your own wrapper script that forwards to the Ruby API.

**Comment by cyrusdavid** [comment]
Could the `--sourcemap FILE` be considered?
