### ISSUE TITLE
Sass doesn't need to include Rack middleware in Rails 3.1

### ISSUE THREAD

**Issue by josevalim** [sass/sass#85]
Maybe we could detect if Sprockets is available and skip including Sass rack middleware in Rails 3.1 forward?

**Comment by chriseppstein** [comment]
Aren't there rails 3 projects that use sprockets? Would they continue to work? It seems unlikely.

**Comment by nex3** [comment]
Closing this 'cause it belongs in [sass-rails](/rails/sass-rails) now anyway.
