### ISSUE TITLE
Sass 3.2.9 on Debian does not respect the @charset 'UTF-8' directive

### ISSUE THREAD

**Issue by danapplegate** [sass/sass#855]
Hi, I'm experiencing a strange issue.

We're using Vagrant to build and deploy our assets across our team. However, when uploading our Sass-compiled CSS files, we discovered that they were being interpreted in the wrong encoding. We use several UTF symbols and a symbol library to handle the icons on our site, and these were being rendered as strange character sequences.

Checking the output CSS files, they have a `@charset "ISO-8859-1";` directive added to the top. This does not happen on our local Mac machines.

Even after placing an explicit `@charset "UTF-8";` directive at the top of our sass files, the output CSS still has the ISO-8859-1 charset at the top.

This is using Sass v3.2.9, Ruby 1.9.3p448, on Mac OS X v10.7.5. The Vagrant virtual machine is running Ubuntu 12.04 LTS.

Any ideas on what this could be?

Thanks,
Dan

**Comment by nex3** [comment]
Can you come up with an individual file that reproduces this consistently?

Also, what's the result of running `ruby -e 'p [Encoding.default_external, Encoding.default_internal]'`?

**Comment by danapplegate** [comment]
Ah ha.

Running the ruby command on my host machine outputs `[#<Encoding:UTF-8>, nil]`, while running it on my Vagrant machine gives me `[#<Encoding:ISO-8859-1>, nil]`

Will investigate further and see if we can come up with a way to set ruby's default external encoding on our Vagrant machine.

Closed for now, will reopen if this doesn't solve the issue.

Thanks!

**Comment by nex3** [comment]
I'm still interested in getting a copy of the file that triggered this. If you write `@charset "UTF-8"`, Sass should emit UTF-8 code with a UTF-8 charset declared.

**Comment by chriseppstein** [comment]
@nex3 I've seen cases where the charset was stripped if the file had no non-ascii characters, even if it was specified explicitly. I think may be ruby version dependent.

**Comment by danapplegate** [comment]
@nex3 That might be tough to provide, as the issue is most apparent in our main.scss file with over 30 imports. I'll take some time this weekend and try to localize the issue to a certain file, or a certain combination of files.

**Comment by dominics** [comment]
@chriseppstein I definitely have a reproducible case of this. Sass seems to remove an explicitly specified `@charset` if it doesn't think it's required, which I don't think is intended. (It's certainly annoying.)

``` sh
$ scss --version
Sass 3.2.10 (Media Mark)

$ scss <<< '@charset "UTF-8";
p { background-color: red; } '
p {
  background-color: red; }
```

Happy to provide environment details. Ruby is 'ruby 1.9.3p429 (2013-05-15) [x86_64-linux] Brightbox' from the Brightbox PPA on Ubuntu 12.04. On this machine:

``` sh
$ ruby -e 'p [Encoding.default_external, Encoding.default_internal]'
[#<Encoding:UTF-8>, nil]
```

Noticed this when our asset pipeline starting coming up with different fingerprints from 1.9 and 1.8 rubies. Here's the expected output, when run with 1.8:

``` sh
$ scss <<< '@charset "UTF-8";
p { background-color: red; } '
@charset "UTF-8";
p {
  background-color: red; }
```

**Comment by dominics** [comment]
@nex3 See reproduction case above?

**Comment by nex3** [comment]
Does that still happen if you use a non-ASCII character in your input on Ruby 1.9.3?

**Comment by dominics** [comment]
No, it doesn't (which is good). Any non-ASCII character will make the charset show up. That's the workaround we're using at the moment.
