### ISSUE TITLE
Custom compass config.rg path when using --compass option

### ISSUE THREAD

**Issue by badsyntax** [sass/sass#858]
Hi there 

Are there any plans to add an option to specify the path to the compass config.rb file? 

Currently Sass (version 3.2.9) can make compass imports available via the `--compass` option, and sass will then look for a config.rb in the current directory, but we cannot specify the compass config.rb path. It would be really useful if we could specify this path as a Sass option. 

Thanks.

**Comment by nex3** [comment]
`sass --compass` is intended to be a quick-and-dirty way to get access to the Compass libraries that don't require any configuration. If you want anything more complicated, you should use the `compass` executable.
