### ISSUE TITLE
2-dimensional table with one element in outer table flattens to 1-dimensional table

### ISSUE THREAD

**Issue by jslegers** [sass/sass#859]
I created the following mixin 

``` scss

@mixin respond-to($queries...) {
   // Do something
}

@include respond-to((32em, '.content'), (60em), ((72em,'max-width'),'.test'), (90em, aside, main), ((72em,'max-width'),'.test')) {
   // Do something
}
```

Expected input :

```
* $width
* $width, $width, $width, ...
* ($width, $class)
* ($width, $class), ($width, $class), ...
* (($width, $widthType), ($width, $widthType), ...)
* (($width, $widthType), $class)
* (($width, $widthType), $class)), (($width, $widthType), $class)), ...
* any combination of the above
```

"(($width, $widthType))" isn't supported because SCSS automaticly flattens the list to "($width, $widthType)", which doesn't allow the code to distinguish it from ($width, $class).

This automatic flattening may be useful in selectors, but it should definitely not occur in mixins because the number of dimensions is relevant there.

**Comment by nex3** [comment]
We'd like to add a simple way of representing singleton lists, but that way will not be parentheses.

Duplicate of #837.
