### ISSUE TITLE
CSS Tidy and YUI Compressor integration

### ISSUE THREAD

**Issue by gmile** [sass/sass#86]
There's a [ruby-css-toolkit](https://github.com/rhulse/ruby-css-toolkit), which recently woke up from a hibernation. SASS's todo list keeps a [reminder](https://github.com/nex3/sass/blob/master/TODO#L26-27) for this two for a while already. Isn't it time to consider including ruby-css-toolkit into SASS?

**Comment by nex3** [comment]
This is something that probably doesn't belong in core Sass, especially since we do a fair amount of compression on our own anyway.
