### ISSUE TITLE
Interpolated percentages throw an error in mixins

### ISSUE THREAD

**Issue by JamesDullaghan** [sass/sass#860]
Working Keyframe mixin

```
@mixin global-keyframes($direction, $axis-start, $axis-percent-start, $axis-end, $axis-percent-end) {
  @keyframes #{$direction} {
    0% {
      transform: #{$axis-start}(#{$axis-percent-start});
    }
    100% {
      transform: #{$axis-end}(#{$axis-percent-end});
    }
  }
}
```

Not working Keyframe mixin

```
@mixin global-keyframes($direction, $start, $axis-start, $axis-percent-start, $end, $axis-end, $axis-percent-end) {
  @keyframes #{$direction} {
    #{$start} {
      transform: #{$axis-start}(#{$axis-percent-start});
    }
    #{$end} {
      transform: #{$axis-end}(#{$axis-percent-end});
    }
  }
}
```

`Warning: scss/modules/page-transitions.scss:29: error: invalid selector after 0`
`Use --force, continuing.`

Same happens with to and from, although no error is thrown, it just isn't compiled. Would be nice to be able to define a single mixin for both 0% and 100% or to and from.

Doesn't seem to be an issue on this. Any insight?

**Comment by KittyGiraudel** [comment]
I just tried this:

```
@mixin keyframes($name, $start: from, $end: to) {
    @keyframes #{$name} {
        #{$start} {
            color: blue;
        }

        #{$end} {
            color: red;
        }
    }
}

//@include keyframes(test);
@include keyframes(test, 10%, 30%);

html {
    animation: test 3s infinite;
}
```

It works like a charm. Demo here: http://codepen.io/HugoGiraudel/pen/fa62d435ccddb2ee98f84f39a8f7e75d.

Don't really see where's your issue coming from then.

**Comment by chriseppstein** [comment]
I think the problem is that you have `0` instead of `0%`. Sass is helping you out :)
