### ISSUE TITLE
Extend on empty selectors

### ISSUE THREAD

**Issue by ChristopherMeyers** [sass/sass#861]
```
.parent {}
.child {@extend .parent;}
```

throws an error.

```
.parent {color: red;}
.child {@extend .parent;}
```

compiles.

Sass 3.2.9 (Media Mark)

**Comment by chriseppstein** [comment]
We prune out any selectors with no content so there's nothing to extend. if you don't want the error add !optional to the extend directive.

**Comment by ghost** [comment]
I don't see why this would be valid behaviour: what if you want to extend a selector that could potentially have content later? I think that the empty selectors should be removed as the last step in the compilation, not the first.

**Comment by Snugug** [comment]
@Undeterminant If `.parent{}` has content later on in your Sass cascade (NOT if something's added through JavaScript, for instance), it'll extend the later one just fine.

**Comment by ghost** [comment]
Well, I was referring to the idea that you'd make a .parent selector that's empty at first but you might want to add more content to it later (as in, at a later point in time when you edit the stylesheet).

It seems kind of odd that you'd need to mark it as optional in this type of scenario when you clearly added a selector (even if it doesn't show up on the stylesheet later). Perhaps the error could be improved to mention this type of scenario?

**Comment by chriseppstein** [comment]
> It seems kind of odd that you'd need to mark it as optional in this type of scenario when you clearly added a selector.

You've added a selector that does nothing and then extended it. Everything you're telling sass is that this selector is important. But it's empty and this looks like a mistake to us. We can't know what you intend to do in the future. I suggest that you use "!optional" and add a comment near the parent selector that says "if we ever use this, go remove the optional flag from the extending selectors.". This way you'll get the desired behavior, protect yourself from future mistakes, and you're reminding yourself if what to do when the assumptions change.

**Comment by MobiusHorizons** [comment]
I think it is a mistake to consider a sass stylesheet finished just because you are compiling it. 

We ran into the same problem described above, because the selector being extended contained a mixin that was empty in some of the stylesheets and not in others. for this reason, sass claimed that the extended class didn't exist, even though it certainly did. 

Regardless of whether you will fix this bug, you should at least fix the error message so that it is possible to find the error. Something like "error: extending empty selector. use !optional"

Thanks

**Comment by ChristopherMeyers** [comment]
That was the type of code that messed us up. We had something like this.

``` scss
$definedColor: green;
$definedHeight: 20px;

body {
  color: red;
}
.colored-text {
  @if ($definedColor != red) {
    color: $definedColor;
  }
  @if ($definedHeight != auto) {
    height: $definedHeight;
  }
}
.bold-colored-text {
  @extend .colored-text;
  font-weight: bold;
}
```

Building the file multiple times with different parameters. The ifs with the optimizations would cause a problem if we happened to configure the file in a way that made colored-text return empty.
