### ISSUE TITLE
Replace quoted newlines with space

### ISSUE THREAD

**Issue by joeyhoer** [sass/sass#862]
CSS and therefore SA/CSS doesn't support newlines, even when found within a quoted string.

There are few scenarios where this would be useful, but the primary use would be raw XML/SVG data URIs, which currently have to be written into a single line, which makes the code less maintainable.

I propose that Sass detect quoted newlines and replace them with a single space when compiling, or possibly remove them altogether. I'd like to open up the discussion to see if anyone else finds value in this, and possibly has some ideas as to the best way it might be implemented.

**Comment by nex3** [comment]
Sass isn't going to do silent string rewriting. That sort of behavior can lead to serious confusion for users.

It's pretty easy to write long strings in Sass right now. You can just use `+` to spread them across lines, as so:

``` scss
$var: "Q1NTIGFuZCB0aGVyZWZvcmUgU0EvQ1NTIGRvZXNuJ3Qgc3VwcG9ydCBuZXdsaW5lcywgZXZlb" +
      "iB3aGVuIGZvdW5kIHdpdGhpbiBhIHF1b3RlZCBzdHJpbmcuCgpUaGVyZSBhcmUgZmV3IHNjZW" +
      "5hcmlvcyB3aGVyZSB0aGlzIHdvdWxkIGJlIHVzZWZ1bCwgYnV0IHRoZSBwcmltYXJ5IHVzZSB" +
      "3b3VsZCBiZSByYXcgWE1ML1NWRyBkYXRhIFVSSXMsIHdoaWNoIGN1cnJlbnRseSBoYXZlIHRv" +
      "IGJlIHdyaXR0ZW4gaW50byBhIHNpbmdsZSBsaW5lLCB3aGljaCBtYWtlcyB0aGUgY29kZSBsZ" +
      "XNzIG1haW50YWluYWJsZS4KCkkgcHJvcG9zZSB0aGF0IFNhc3MgZGV0ZWN0IHF1b3RlZCBuZX" +
      "dsaW5lcyBhbmQgcmVwbGFjZSB0aGVtIHdpdGggYSBzaW5nbGUgc3BhY2Ugd2hlbiBjb21waWx" +
      "pbmcsIG9yIHBvc3NpYmx5IHJlbW92ZSB0aGVtIGFsdG9nZXRoZXIuIEknZCBsaWtlIHRvIG9w" +
      "ZW4gdXAgdGhlIGRpc2N1c3Npb24gdG8gc2VlIGlmIGFueW9uZSBlbHNlIGZpbmRzIHZhbHVlI" +
      "GluIHRoaXMsIGFuZCBwb3NzaWJseSBoYXMgc29tZSBpZGVhcyBhcyB0byB0aGUgYmVzdCB3YX" +
      "kgaXQgbWlnaHQgYmUgaW1wbGVtZW50ZWQuCg==";
```
