### ISSUE TITLE
[Feature] Referring and extending parent selection

### ISSUE THREAD

**Issue by gnclmorais** [sass/sass#868]
```
.ui-kit {
    .button-close {
        .position-top & {
            top: 5px;
            right: 5px;
        }
    }
}
```

The snippet above translates to:

```
.position-top .uikit-tooltip .button-close {
    top: 5px;
    right: 5px;
}
```

What do you think about people being able to remove the space before the **&**, in order for the following snippet...

```
.ui-kit {
    .button-close {
        .position-top& {
            top: 5px;
            right: 5px;
        }
    }
}
```

... translate into into the following?

```
.position-top.uikit-tooltip .button-close {
    top: 5px;
    right: 5px;
}
```

Currently, compiling is not possible, as an error is raised (`Invalid CSS after "... .position-top.": expected class name, was "& {")`).

**Comment by FWeinb** [comment]
This (or something like this) should be covered in #286

**Comment by chriseppstein** [comment]
Yep. #286 is the plan for this.

**Comment by gnclmorais** [comment]
Awesome, thank you guys. :+1:
