### ISSUE TITLE
Passing arguments from a mixin to a content block

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#871]
- [x] [Proposal](https://github.com/sass/language/blob/master/proposal/content-args.md)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1299)
- [x] [Documentation](https://github.com/sass/sass-site/issues/250)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/498)
- [x] [LibSass](https://github.com/sass/libsass/issues/2723)

---

Mixin content is great and has done wonders for code implementing wrapper and context abstractions. However, there is often some setup done in the mixin and that setup needs to be available to the content when it is included. The current strategy is to use global variables, which works, but is obviously not ideal.

I'd like to introduce a way for mixins to include their content block and to pass arguments to the content.
### Calling the content with arguments

In order to pass arguments to content blocks an argument list can be passed to the content directive. This accepts positional and keyword arguments for passing to a content block. Variable argument semantics are allowed.

``` scss
@mixin accepts-content {
  @for $i from 1 to 5 {
    @content ($i, 360deg * $i / 5);
  }
}
```
### Receiving arguments within a content block

A content block receives arguments using a new directive called `@receive`. The directive allows an argument list declaration that is the same as for functions and mixins. Positional arguments, default values, and variable arguments are all allowed.

``` scss
@include accepts-content {
  @receive ($number, $hue);
  .color-#{$number} {
    background-color: hsl($hue, 75%, 90%);
  }
}
```

**Comment by Snugug** [comment]
I like this idea. :+1:

**Comment by cimmanon** [comment]
Not crazy about the syntax for `@receive`, but very interested in the concept.

**Comment by chriseppstein** [comment]
Comments of general distaste are not very useful without explanations and, ideally, alternative suggestions.

**Comment by gabrielnau** [comment]
It's really fine ! 
1. global variables are not ideal like you said 
2. it explicits what variables the nested block needs

**Comment by HamptonMakes** [comment]
At first blush, I like it.

How about @bind instead of @receive... maybe that's too nerdy?

**Comment by ghost** [comment]
Could always pull a JavaScript and make an $arguments variable. Or an arguments($n) function.

**Comment by chriseppstein** [comment]
The problem with `$arguments` is that it only work for positional arguments. I'd like consistency with all other argument passing and definitions. With `arguments(...)` I really don't like the idea of a function that sets instead of receives arguments.

Re: Naming, I'm not a fan of `@bind` for this. Maybe `@content-arguments` is better; it show's it's related to the `@content` directive.

**Comment by nex3** [comment]
I'm not a fan of `@receive` either; the directive format is not a good fit for receiving arguments. That said, I do want this feature, and I can't think of any other syntax that would be better.

**Comment by HamptonMakes** [comment]
I guess I'm not a fan of receive due to it being commonly misspelled. Just
brainstorming....

@take
@pass
@get
@->
@vars
@name

**Comment by chriseppstein** [comment]
I think I like @content-arguments best so far.

**Comment by HamptonMakes** [comment]
Hrrm... as I look at the use case more, this seems like something we think
would be pretty regularly used. Aka, I could make a Sass library that uses
this as a common API for interaction. And, with that in mind, this overall
approach of making it a directive line is odd to me. I'd much rather it
somehow work into the syntax more directly.

We could steal some Ruby syntax!

```
@include accepts-content { |$number, $hue|
  .color-#{$number} {

    background-color: hsl($hue, 75%, 90%);

  }

}
```

**Comment by cimmanon** [comment]
The part I'm not a fan of is how much additional code this adds from a reuse standpoint.  Using global variables is worse when it comes to authoring the mixins, but more convenient for using them.  Shorter is better.  If it must be a keyword, `@receive` or `@args` is better than `@receive-content` or `@content-arguments`, even though they may be better descriptors.

Borrowing a bit from Haskell here:

``` scss
@mixin foo($a, $b) {
    @content (darken($a), lighten($b), blend($a, $b));
}

.foo {
    @include foo(red, blue) -> ($c, $d, $e) {
        @include background: $e;
        @include background-image(linear-gradient($c, $d));
    }
}
```

Using a Ruby style syntax as @hcatlin suggests would also be acceptable.

**Comment by Anahkiasen** [comment]
I don't get where the red and blue come from in the above example ?

**Comment by cimmanon** [comment]
The `foo()` mixin takes 2 colors as arguments.

**Comment by nex3** [comment]
I'm more of a fan of @cimmanon's example than any of the others I've seen. Placing the arguments before the `{` puts them firmly in the context of `@include`, both from the parser's standpoint and the reader's standpoint.

I'm not a big fan of `->`. Sass tends to use words over symbols where possible, so something like `@include foo(red, blue) with ($c, $d, $e)` or `taking ($c, $d, $e)` might be better.

**Comment by chriseppstein** [comment]
I actually really like the `with` or `taking` syntax and I'm sad I didn't think of it first ;)

Leaning towards taking. I also like `receiving`, but as @hcatlin points out people always misspell that. However, we could also support `recieving` and print out a message mocking their inability to spell.

**Comment by nex3** [comment]
I don't like how much longer `receiving` is, either.

**Comment by cimmanon** [comment]
What about `as` (from SQL)?  `returning` (also SQL) or `returns` might make sense.

**Comment by ghost** [comment]
How about `@include foo(red, blue) using ($a, $b, $c)` ?

**Comment by nex3** [comment]
I think `as` is too unclear, and `returns`/`returning` are confusing given that `@return` already exists and does something different.

I like `using`. That may be my favorite so far.

**Comment by chriseppstein** [comment]
`using` :+1:

Objections to this for 3.3? Would really clean up some compass code.

**Comment by nex3** [comment]
I don't want any new features in 3.3. I want to get it out the door as soon as the existing features for it are done.

**Comment by chriseppstein** [comment]
ok.

**Comment by ghost** [comment]
From my short-lived https://github.com/nex3/sass/issues/894, since the `@mixin` is defining variables to be bound in the content block scope, the content block scope should automatically bind them, but do so with an implicit `!default` and a warning.

Optionally a `using` keyword could allow the `@mixin` caller to rename variables before they are bound ( _and thus wouldn't issue a warning_ )

```
$bar: already-defined;

// would normally bind 
// $bar to some value
@include foo ($arg) using ($bar as $qux) {
    background-color: $qux;
}
```

I just don't see a reason to force all variables to be explicitly named ( _as previously discussed_ ); it's not particularly magical if done implicitly as the mixin consumers will need to refer to argument documentation regardless.

`</2-cents>`

**Comment by nex3** [comment]
I think it's important that all the variables are named at the call site. It makes it possible to determine where each variable is coming from by inspecting the code around it.

**Comment by elisechant** [comment]
@chriseppstein passing arguments to `@content` would be incredibly useful. Can we prioritize this issue?

**Comment by cjcheshire** [comment]
Yes please! I came across this issue recently and would love this to help
tidy up some loops I've had to duplicate.

**Comment by elisechant** [comment]
For anyone interested, my workaround at the moment requires a repeating loop:

#### _config.scss

```
// Category theme settings
// ------------------------------------
// store config in an associated array so we can loop through
// and correctly assign values
//
// Use this like this:
// Note - The repeated loop cannot be abstracted to a mixin becuase
// sass wont yet allow us to pass arguments to the @content directive
// Place the loop inside the selector

$themes:
    'category-a' $color-quaternary,
    'catgeory-b' $color-tertiary,
    'catgeory-c' $color-secondary
;
```

#### _breadcrumb.scss

```
#el {
    @each $theme in $themes {
        $class: nth($theme, 1);
        $color-prop: nth($theme, 2);

        .#{$class} & {
            border: 1px solid $color-prop;
        }
    }
}
```

**Comment by cjcheshire** [comment]
Yea I have something similar but like you say you can't do the loop within
the mixin - yet :)

I wanted the loop within a mixin as then it's tidier and cleans the code up
so much.

I'm happy it's being discussed - I thought about it the other day and
figured I was asking for something mad.

**Comment by elisechant** [comment]
@cjcheshire agree. As our applications become more modular and extensible this is becoming more and more important.
Bourbon's Neat uses some interesting logic on topic (that doesn't work) at `/neat/grid/_media.scss`

```
@mixin media($query:$feature $value $columns, $total-columns: $grid-columns) {
   @if length($query) == 1 {
    @media screen and ($default-feature: nth($query, 1)) {
      $default-grid-columns: $grid-columns;      
      $grid-columns: $total-columns;                /* SET A LOCAL VAR ? */
      @content;
      $grid-columns: $default-grid-columns;      /* RESET THE VAR */
    }
  }

    // ...
}
```

**Comment by jackmahoney** [comment]
I would loove to see this feature implemented.

**Comment by petemill** [comment]
+1

**Comment by mietek** [comment]
:+1:

**Comment by jackmahoney** [comment]
![please](https://f.cloud.github.com/assets/1240270/2480582/7121d9b8-b0c2-11e3-85a2-ead3b5c3f488.gif)

**Comment by apfelbox** [comment]
I like the proposal and I like `using` - reminds me of the closure binding with `use` in PHP (both from a semantical and syntactical point of view).

**Comment by ghost** [comment]
@apfelbox No! Don't say it's like PHP, it'll never get implemented! ;-)
Kidding, of course; kinda. I like the `using` syntax too. It's trivial, but I favor it as part of the "call" than of the content body:

``` scss
@include foo($a, $b) using($c, $d) {
    // ...
}
```

Instead of:

``` scss
@include foo($a, $b) {
    @using($c, $d);
    // ...
}
```

**Comment by apfelbox** [comment]
@bracketworks I had the same thought while writing it, lol. :sweat_smile:

**Comment by jackmahoney** [comment]
@bracketworks - first example looks great.

```
@mixin foo($a, $b){
    @content($c, $d)
}

@include foo($a, $b) using($c, $d) {
    // ...
}
```

**Comment by ghost** [comment]
@jackmahoney Precisely. Very much looking forward to this feature. It's definitely going to bring about a whole new set of reusability patterns.

**Comment by ryngonzalez** [comment]
Very excited for this! Hope it gets fast-tracked sometime :smile:

**Comment by funwithtriangles** [comment]
+1

**Comment by ShimShamSam** [comment]
+1

**Comment by csszbolton** [comment]
+1

**Comment by Maximilianos** [comment]
+1 to the proposal.

``` scss
@mixin foo($a, $b) {
    @content($c, $d);
}

@include foo(red, blue) using($c, $d) {
    // stuff
}
```

Where the whole `using($c, $d)` thing is needed only if you want to use the variables in the block.

**Comment by davebeesleyarchived** [comment]
Hi @chriseppstein and co.
Has this (or similar) recently been implemented?
I have a mixin and include which previously worked using the old method of declaring an empty global variable, changing it with a mixin, then it being available in the include statement via @content

But now (in 3.4.9, ruby, windows command line, also latest version of prepros) the include statement is receiving an empty instance.

A copy of prepros using sass 3.3.8 seems to allow the variable to pass as expected

**Comment by lolmaus** [comment]
@davebeesley, try the `!global` flag.

**Comment by davebeesleyarchived** [comment]
Hey @lolmaus I'm not intentionally ignoring you. I'm not currently on that project at the moment (and have worked around it by compiling with an older version of prepros). I shall give when I next have a quiet moment.

**Comment by whaaaley** [comment]
What about..

``` scss
@include foo(red, blue) relay($c, $d) {
    // stuff
}
```

It's short, there's no "ing", it won't be confused with the new upcoming `@use` like `using` might have been, and it's not commonly misspelled.

**Comment by adjavaherian** [comment]
``` scss
@mixin foo($a, $b) {
    @content($c, $d);
}

@include foo(red, blue) using($c, $d) {
    // stuff
}
```

makes sense.  would have used it today.

**Comment by aubricus** [comment]
Adding my +1 here too. ;D

**Comment by aubricus** [comment]
I also like the 'using' syntax

**Comment by timschoch** [comment]
+1 for the feature in general and the using syntax with the posibility to alter the var name in particular

**Comment by traverseda** [comment]
+1

**Comment by ocbaker** [comment]
Damn. I really wanted to use this today. The design in the last comment of @adjavaherian is something that looks super understandable. I'd move to see this added.

**Comment by martinbavio** [comment]
What happened with this lovely idea?

**Comment by jackmahoney** [comment]
I guess no-one here has the time or technical know how to implement it. Think one of us will have to study the code, start a bounty and make a submission.

**Comment by rafegoldberg** [comment]
Any suggestions on where to start looking?

-- rg

**Comment by nex3** [comment]
This is a high-priority feature, but Sass is currently on feature-freeze to give LibSass time to catch up.

@rafegoldberg since this involves new syntax, it's going to be a change that requires modifying every layer of the implementation. You'd need to change both [the SCSS parser](https://github.com/sass/sass/blob/stable/lib/sass/scss/parser.rb) and [the indented syntax parser](https://github.com/sass/sass/blob/stable/lib/sass/engine.rb), [the AST](https://github.com/sass/sass/tree/stable/lib/sass/tree), [the runtime](https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/perform.rb), and [the convesion code](https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/convert.rb), as well as [adding tests](https://github.com/sass/sass/tree/stable/test/sass) to make sure all of that works properly.

**Comment by stereokai** [comment]
@nex3 Where can I see libsass status?

**Comment by esr360** [comment]
Really like this idea and sad to see after over 2 years it is still unimplemented. 

+1 for:

``` scss
@mixin foo($a, $b) {
    @content($c, $d);
}

@include foo(red, blue) using($c, $d) {
    // stuff
}
```

This feature would be immensely useful for modular CSS architecture.

**Comment by nex3** [comment]
@stereokai ask @xzyfer.

**Comment by xzyfer** [comment]
@stereokai there's no official status page. 

https://sass-compatibility.github.io/ gives a high level run down of what features are supported.
http://sassmeister.com/ is a good playground for checking if a feature or syntax is supported.

You can also check out our [known bugs list](https://github.com/sass/libsass/issues?q=is%3Aopen+is%3Aissue+label%3A%22Bug+-+Confirmed%22).

**Comment by frenic** [comment]
+1

**Comment by WartClaes** [comment]
+1

**Comment by stereokai** [comment]
@xzyfer a 2-months late thank you. Missed your comment. Looks like you guys definitely have a lot on your hands, but I'm glad it's finally officially acknowledged and part of milestone 4.

**Comment by ArmorDarks** [comment]
Just for the information, Jinja has quite similar solution with macros: http://jinja.pocoo.org/docs/dev/templates/#call

Transfering it into Sass would look like this:

``` Sass
@mixin foo($a, $b) {
    @content($c, $d);
}

@include($bindedC, $bindedD) foo('red', 'blue') {
    // stuff
}
```

Or for mentioned by @chriseppstein example at the beginning:

``` Sass
@include($number, $hue) accepts-content() {
  .color-#{$number} {
    background-color: hsl($hue, 75%, 90%);
  }
}
```

Very simple and clean. And fully backward compatible.

**Comment by hairarrow** [comment]
This might be a silly idea, but how about passing content as a variable? 

``` scss
@mixin foo($hover, $active) {
  color: red;

  &:hover {
    color: green;
    $hover;
  }

  &:active {
    color: blue;
    $active;
  }
}

.block {
  @include foo(
    $hover: { background: yellow; },
    $active: {
      font-size: 12px;
      background: rebeccapurple;
    }
  );
}
```

**Comment by ArmorDarks** [comment]
@hairarrow it seems to be fragile, since variable names can easily collide with already existing mixin arguments.

**Comment by giacomo-cosimato** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by entozoon** [comment]
+1

**Comment by davidjpfeiffer** [comment]
+1

**Comment by Quji** [comment]
+1

**Comment by ArmorDarks** [comment]
For those who wonders is it possible at least anyhow to pass argument from mixin to `@content` — yes, it is possible.

You would need to use temp variable and `!global` flag. Though, it is a hacky way, and not that pretty, it will do the job.

I wanted some better API to work with that temp variable, so I created few mixins and function to cover that case better till we'll have native solution.

You can check example from [Ekzo](https://github.com/ArmorDarks/ekzo.sass) here: 
- [Util temp mixins and function](https://github.com/ArmorDarks/ekzo.sass/blob/master/tools/_functions.temp.scss)
- [Example of mixin which passes argument to content](https://github.com/ArmorDarks/ekzo.sass/blob/master/tools/_mixins.breakpoint.scss#L50)
- [Example of invoking](https://github.com/ArmorDarks/ekzo.sass/blob/master/helpers/_flex.scss#L124)

**Comment by ItsJonQ** [comment]
+1 for this as well.

Thanks for sharing your solution @ArmorDarks !!

Your approach helped inspire my custom solution around this `@content`/argument craziness:
https://github.com/helpscout/seed-props

Like others have mentioned, my solution also relies on `!global`. It's not ideal, but it works.

**Comment by isaactzab** [comment]
+1 We really needed this to make more clean code! please!

**Comment by lunelson** [comment]
I suggest putting the names of the passed variables in to the `@content` rule, via named arguments or the map-as-arglist pattern, and avoid requiring additional syntax inside the content-accepting mixin. 

This would allow users of the `!global` variable set/unset technique to just adapt their mixins without needing to change any of the code where they are included.

``` scss
@mixin accepts-content {
  @for $i from 1 to 5 {
    @content ((number: $i, hue: 360deg * $i / 5)); // map as arglist
  }
}

@mixin accepts-content-alt {
  @for $i from 1 to 5 {
    @content ($number: $i, $: 360deg * $i / 5); // named arguments
  }
}

@include accepts-content-a {
  // passed named variables are just available
  .color-#{$number} {
    background-color: hsl($hue, 75%, 90%);
  }
}
```

**Comment by ArmorDarks** [comment]
@lunelson Don't forget that `@mixin` itself can have parameters too. And what if they will collide with `@content` parameters?

**Comment by lunelson** [comment]
Hmm I didn't quite realize this thread was three years old when I commented yesterday 😬. FWIW:

I think the idea of putting mixin and content arguments on the same line—whether it be as `@include foo($arg) using ($content-arg)` or `@include($content-arg) foo($arg)` (the latter conflicts with planned dynamic-mixins feature anyway)—doesn't make sense. It precludes `$arg` from affecting `$content-arg` and renders the whole exercise a bit pointless, given that when you `@include` the mixin you also write the rules for the `@content` block—and if those values are not being transformed in any way by the mixin you don't need the mixin to pass them on for you, you can write them yourself.

Supplying arguments to `@content`, imo needs to be done inside the `@mixin` block (to allow the mixin to determine or transform those values in some way), and @chriseppstein's first design accomplishes this; but I am also among those who are not fans of `@receive` or any other syntax being required inside the block during the `@include`. Reconsidering the suggestions I made above I think maybe the most intuitive syntax is to allow `@content` to _also_ be a block directive, like `@include` is for content-accepting mixins, and place variables inside it in order to expose them (echoing the well-understood behaviour of block scoping):

``` scss
@mixin bar($x, $y) {
  @content {
    $foo: $x * $y;
  }
}

@include bar(2,3) {
  z-index: $foo; // 6
}
```

P.S. @ArmorDarks I'm not sure what you mean by collision of variable names. Not withstanding the relationship between content-arguments and mixin-arguments, names could still collide with global variables to create strange effects. In the following example (imagining we are using the `!global` flag set/unset technique we have now), the color of `.baz` could turn out to be something other than `black` or `white`, depending on how `$foo` is being set in the body of the `@mixin`, which is just an inevitable complexity of this technique:

``` scss
$foo: white;
@include bar($foo: black) {
  .baz { 
    color: $foo; // what color will this be?
  }
}
```

**Comment by milewski** [comment]
+999

**Comment by ArmorDarks** [comment]
@lunelson collision of mixin's parameters with content's parameters is quite different from collision of parameters with global variables. First one is flaw of language design, second one — flaw of developer approaches in usage of that language,

**Comment by giacomo-cosimato** [comment]
I think if you declare a variable inside the mixin with the same name as a mixin parameter, you're just overwriting the variable passed through that parameter, just like it works in other languages (i.e javascript). 
The same goes for conflicts with global parameters, the local scope always take precedence.

**Comment by ArmorDarks** [comment]
This is different case. If we compare it with JavaScript, `@content` block is more like a callback inside a function (mixin). And for callbacks in JavaScript you need to explicitly export variables, they do not appear there out of air, and local scope only helps to export them to callback (by setting parameters of callback). Then you have to assign parameters during callback usage anyway.

**Comment by giacomo-cosimato** [comment]
I agree,  but since the @content block do not permit to export variables,  like you do in a javascript callback,  you need to establish precedence. 
I was thinking in terms of retaining the current syntax, but of course the best solution would be to introduce a dedicated syntax.

**Comment by tzi** [comment]
I created a small example of how to use this feature to simplify the theme generation.
https://gist.github.com/tzi/2e54c245af91769ea912fa4e5f6d3820

**Comment by indrekpaas** [comment]
@tzi Theme generation is already relatively simple with Sass: http://www.sassmeister.com/gist/39483fdd90c7c6c3e00a35cf77ec4516

**Comment by matteoantoci** [comment]
@tzi's solution would be great!
@indrekpaas I wrote something very similar for a project but that implementation has limitations.

**Comment by r3oath** [comment]
Big frickin +1

**Comment by kyleoliveiro** [comment]
+1

**Comment by ArmorDarks** [comment]
Please, stop `+1`ing in comments, use thumb up on already posted comments instead or provide meaningful comments, otherwise devs will definitely lock down this issue and we won't be able to comment it and make new proposals any further.

I think there are little chances we'll see any new features untill [Dart version of Sass](http://blog.sass-lang.com/posts/1022316-announcing-dart-sass) will be completely finished.

**Comment by 9nix00** [comment]
wow,4 years later, this feature is still not released. I miss this feature.
I vote "using", hope this feature can be release in someday. 
Thanks all contributor.😊

**Comment by trev-dev** [comment]
You can give a mixin optional args already. This kind of feels redundant to me?

**Comment by lolmaus** [comment]
@trev-dev This issue is about passing arguments not *to* mixin, but *from* mixin to its content block (which can be invoked multiple times with different args).

**Comment by signalwerk** [comment]
I like this discussion a lot! But I needed it before it lands in v4 – so I came up with a workaround to do stuff like that;

```SCSS
$tst: (
  color: green,
  width: 100%,
);

body {
  @include scontecss($tst, (
    color: "$.color",
    width: "$.width",
  ));
}
```

results in

```CSS
body {
  color: green;
  width: 100%;
}
```

If someone is interested in the workaround you can find it here: https://github.com/signalwerk/scontecss

**Comment by stereokai** [comment]
Nice work, @signalwerk

**Comment by ArmorDarks** [comment]
Beware, that string substitution isn't the fastest thing in Sass.

I've posted a solution without string substitution a year ago here https://github.com/sass/sass/issues/871#issuecomment-229387191

**Comment by nex3** [comment]
I've [written up a proposal](https://github.com/sass/language/blob/master/proposal/content-args.md) for this feature. I'll leave it [open for comments](https://github.com/sass/language/issues/new) for two weeks, then mark it accepted if nothing has come up.

**Comment by lunelson** [comment]
Cool. Does the comment thread for this already exist, or shall I create one at that link?

**Comment by nex3** [comment]
@lunelson Feel free to open new issues in sass/language for any comments you have.

**Comment by stereokai** [comment]
It's happening......!

**Comment by milewski** [comment]
Woww i lived to see this

**Comment by esr360** [comment]
Dang, too bad I already moved to css-in-js. This would have been super neat to play with.

**Comment by nex3** [comment]
I've marked [the proposal](https://github.com/sass/language/blob/master/accepted/content-args.md) as accepted, and plan to start implementing it immediately.

**Comment by CaelanStewart** [comment]
Approximately how long will it be until this feature is implemented?

This is very useful and would allow for some really neat dynamic stylesheets.

~~I'm surprised this was not implemented sooner.~~

Ignore that. I'm a miserable sod sometimes. I should not have been said.

**Comment by tzi** [comment]
> I'm surprised this was not implemented sooner.

This could be quite agressive. I know it wasn't what you mean, but there is a lot of hard work here and sentence like this is not really fun to read :cry: 

I think @nex3 work now full time on Sass. The lib was migrated from ruby to dart, and there is some good news every weeks. You can see all the new features here: https://github.com/sass/language

This one is coming too!

**Comment by signalwerk** [comment]
@tzi great words. I really appreciate the effort of @nex3 and the great proposal!

**Comment by CaelanStewart** [comment]
You are completely correct.

Loaded statements like mine are completely uncalled for.

I shouldn't let my bad mood influence my words.

I apologise for that. I should not have said it.

I wish to say that I very much appreciate the work you do, and the contributions you have made to the open source community. What you do does not deserve words like that.

**Comment by xzyfer** [comment]
This has also landed in LibSass. Should this issue be closed?

**Comment by abdullahseba** [comment]
How long would this typically take to trickle into node-sass?
Its just what I need!

**Comment by stereokai** [comment]
Woohoo! Been on the lookout for this for 3 years! Big thanks!

**Comment by CaelanStewart** [comment]
Goes to show, good things come to those who wait.

Nice work guys!

**Comment by nex3** [comment]
@xzyfer When you close out these issues, can you let me know the first LibSass release number these features are expected to land in? That way I can update the new reference docs' implementation tracker.

**Comment by entozoon** [comment]
And the subsequent node-sass release if anyone catches it. Then we can put this whole 5+ year ordeal to bed 👯 🍾

**Comment by leefernandes** [comment]
has this not landed on node-sass?

**Comment by nex3** [comment]
@ItsLeeOwen it landed in https://github.com/sass/libsass/pull/2761

**Comment by KaelWD** [comment]
Yeah and node-sass still isn't using it.

**Comment by sidelong44** [comment]
When to wait for an update for node-sass?
This is a very important feature.
I'm really looking forward to it.

**Comment by ItsLeeOwen** [comment]
It looks like node-sass may be using a version of libsass dated Nov 11, 2018.  There's probably more to it, but maybe you can fork node-sass, update the content of `node-sass/src/libsass` and cross your fingers.

https://github.com/sass/node-sass/tree/master/src/libsass

**Comment by ItsLeeOwen** [comment]
looks like this gyp file needs to reference each of the libsass/src files, and there have been some changes?

https://github.com/sass/node-sass/blob/master/src/libsass.gyp

**Comment by leefernandes** [comment]
the @content argument examples work w/ node-sass on my end with these updates:  https://github.com/sass/node-sass/pull/2714

node-sass mocha tests don't pass, I'm not sure how to reconcile node-sass tests against libsass changes between Nov 11, 2018 and libsass#2b8a17a.  Unless I'm misunderstanding the failing node-sass tests, I'm not confident that node-sass having it's own set of style tests is a good idea, it should probably depend on libsass tests if it's not.

  5935 passing (18s)
  753 pending
  143 failing

also...   @content arguments are **AMAZING**, thanks you!

😺

**Comment by nex3** [comment]
I don't know what Node Sass's release schedule is—you'd have to follow along on https://github.com/sass/node-sass/issues/2685.

**Comment by johnnyBira** [comment]
@ItsLeeOwen How? I'm using the latest version of node-sass and it seams to be using libSass `3.5.4`, ie. no **@content** arguments from what I understand it.

**Comment by esr360** [comment]
I'm using latest version of Node-Sass (4.13.0) and this doesn't seem to be working, but it's still great news that the feature is now in Sass. I'm struggling to find where to follow for updates for Node-Sass though. [This thread](https://github.com/sass/node-sass/issues/2685) mentions to follow a PR for updates, but the PR was already merged.

**Comment by nex3** [comment]
Node Sass versions are released later (sometimes substantially later) than the corresponding LibSass versions. I'm not sure if there's a central place to look for them. Maybe @xzyfer or @nschonni would know?

Alternately, you could use Dart Sass (https://www.npmjs.com/package/sass) which definitely has this feature.

**Comment by katerlouis** [comment]
What's the status on this one?

**Comment by nex3** [comment]
As the comment above indicates, this is implemented everywhere but may not yet be released in Node Sass.
