### ISSUE TITLE
portable ruby 1.9.3 issue

### ISSUE THREAD

**Issue by Nilegfx** [sass/sass#872]
Hi guys,

**system**: windows 7 
**ruby version**: 1.9.3
**ruby installation directory**: C:\ "so i have C:\Ruby193"
**sass version**: 3.2.1
**framework on top of sass**: compass

_\_these specs for both PCs*

For security reason I can't install ruby on my current PC, so i installed it in external machine on the above "c:\", then i copied the folder to my secure PC in the same path "c:\" 

now I have "C:\Ruby193" in both PC

because the installed ruby added ruby commands in my windows Environment Variables, i can navigate through CMD to the "compass" project and execute:

```
compass watch 
```

everything will work just fine, image paths, sprite images .. etc

the problem is in the secured PC I have to do the following: 
Run > CMD 

```
cd  C:\Ruby193\bin
compass watch "C:\xampp\htdocs\mainProject\css"
```

I added the require line to the config file "C:\xampp\htdocs\mainProject\css\config.rb":

``` ruby
require File.join(File.dirname(__FILE__),'customFunctions', 'functions.rb')
```

then I created a custom function file located "C:\xampp\htdocs\mainProject\css\customFunctions\functions.rb"

inside this file I added: 

``` ruby
module Sass::Script::Functions
    def listFiles(path)

        return Sass::Script::List.new(
            Dir.glob(path.value).map! { |x| Sass::Script::String.new(File.basename(x,File.extname(x))) },
            :comma
        )
    end
end
```

so in my scss files i can do: 

``` sass
@each $placeolder in listFiles("images/temp_placeholders/*.png") {
    @debug $placeolder;
}
```

this code work just fine in the installed version of ruby ( the full permission PC ) but it doesn't work at all in the secured PC

I tried to replace 

``` ruby
 Dir.glob(path.value).map!
```

with 

``` ruby
Sass::Util.glob(path.value).map!
```

but no luck

any advise ?

**Comment by chriseppstein** [comment]
This is not a bug in Sass, it is just a question about how to write ruby code. Please seek advice in a support forum.
