### ISSUE TITLE
More of a Question -E Parameter

### ISSUE THREAD

**Issue by mattclements** [sass/sass#875]
As per some issues on Prepros https://github.com/sbspk/Prepros/issues/190

Just wondering when the `-E utf-8` parameter was implemented, seems to be related to the Ruby Version?

**Comment by chriseppstein** [comment]
The `-E` option was added more than 3 years ago.

But it is only defined when running in ruby 1.9 or above. Ruby 1.8 doesn't have a concept of string encodings.
