### ISSUE TITLE
Overriden variable's value and direct/indirect calls

### ISSUE THREAD

**Issue by chikamichi** [sass/sass#876]
Hi,

_Context_: Rails 4.0.0, Sass 3.2.9.

I am working with a Rails Engine which defines a `$white` variable. For the purpose of the test, it sets its value to `yellow`.

This engine is included in a main Rails app, and the sass file defining the `$white` variable is @imported. Without anything in-between, the `$white` variable is overriden to `white`.

Later on, referencing `$white` through "direct" calls, such as `color: $white`, leads to the expected result: `white` trumping `yellow`. But, when `$white` is referenced in, say, a mixin, such as `+link-color($default: $white)`, its value is `yellow` and the overriding value, `white`, never shows up.

Is this related to the use of Engine, or a problem with sass/my usage of sass?

**Comment by chriseppstein** [comment]
> Is this related to the use of Engine, or a problem with sass/my usage of sass?

I don't know. Please reproduce this without an engine or rails and it will be a Sass bug that we can address. Happy to reopen this if/when you have attached a code example.

**Comment by chikamichi** [comment]
Thank you. At least, it's not a well-known bug. When I have a real use-case affected by this issue, I will get back to you here. For the moment, it's just lurking, doing no harm.
