### ISSUE TITLE
Sass::SyntaxError when using CSS "alpha-opacity" property

### ISSUE THREAD

**Issue by edison** [sass/sass#88]
How I posted in: https://github.com/rails/rails/issues/1134

```
Sass::SyntaxError in Main/cockpit#index
Showing /Users/edison/Sites/beta.foco/app/views/layouts/application.html.haml where line #8 raised:
Invalid CSS after "...: alpha(opacity": expected comma, was ":0);".
```

Edit: Occurs only in `production` env.

Im using the lastest gems with Rails 3.1
https://gist.github.com/980015

**Comment by nex3** [comment]
This is invalid CSS. Why would you expect it to work?

**Comment by edison** [comment]
Your right! Sorry, I swore it was right, because Uniform jQuery plugin are using this property in this way: http://uniformjs.com.

But the right syntax can be:

``` css
    filter: alpha(opacity=65); /* use '=' here, not ':' */
    opacity: 0.65;
    -moz-opacity: 0.65;
```

Thanks!
