### ISSUE TITLE
Ruby 2 support

### ISSUE THREAD

**Issue by apennebaker** [sass/sass#881]
sass doesn't appear to be listed in RubyGems for Ruby v2.0.0. Does sass support this version?

**Comment by ghost** [comment]
It shows up for me... and yes, it does work with Ruby 2.

**Comment by nex3** [comment]
The Sass gemspec lists its supported Ruby versions as anything >= 1.8.7, which is accurate. If RubyGems isn't displaying that correctly, I've got no idea why.
