### ISSUE TITLE
Sass removes spaces from CSS calc breaking + operator

### ISSUE THREAD

**Issue by dcalhoun** [sass/sass#884]
It seems that Sass removes the required whitespace from an expression passed to the [CSS calc function](https://developer.mozilla.org/en-US/docs/Web/CSS/calc). While the \* and / operators do not, the + and - operators require being surrounded by whitespace.

The following Sass:

``` sass
.test
  width: calc(100% + 1em)
```

Results in the following CSS:

``` css
.test {
  width: calc(100%+1em);
}
```

Is there a better way to format this and escape the spaces and/or + operator in Sass?

I'm utilizing Sass 3.2.10 and seeing the rejection of the invalid CSS property in Chrome 28.0.1500.95, which in theory should support CSS `calc()`.

**Comment by chriseppstein** [comment]
I cannot reproduce this in 3.2.10 or stable or master. I even went all the way back to 3.1.0. The spaces are preserved in all cases.

However, if you don't have the spaces in your Sass source, spaces are not added for you.

The only way I'd expect this to happen is if you were using Sass with a version less that 3.0.0.

**Comment by dcalhoun** [comment]
Thanks for the swift response, @chriseppstein. After further research it appears to be an [issue with the YUI compressor](https://github.com/yui/yuicompressor/issues/59). Sorry for posting a non-existent bug with Sass.

**Comment by chriseppstein** [comment]
I'm glad you got it sorted out. Hopefully this issue being in the google will help others.
