### ISSUE TITLE
A variable's default value is still evaluated even though it's been overridden

### ISSUE THREAD

**Issue by alicexyl** [sass/sass#887]
Consider the following test case:

```
        $color: transparent;
        $color2: null;
        $color: blue !default;
        $color2: lighten($color, 3) !default;
```

Since I override $color2's default value, I don't expect it to be evaluated, but I get this error:

```
    error sass/test.scss (Line 5: "transparent" is not a color for `lighten')
```

Would be better if Sass is lazy and don't evaluate it.

**Comment by chriseppstein** [comment]
`null` is the same as not having a value, so the default is applied.

**Comment by chriseppstein** [comment]
This behavior is documented [here](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#variable_defaults_).

**Comment by alicexyl** [comment]
Hi Chris, 

What would you recommend we do if we want to override the value with `null` to mean no value?

**Comment by chriseppstein** [comment]
@alicexyl I think you're asking about how to not override a variable that is `null` with `!default`. In 3.3, this will be possible with `$foo: if(variable-exists(foo),$foo,some-new-default)`

**Comment by alicexyl** [comment]
@chriseppstein So `$foo: some-new-default !default;` would need to be replaced by `$foo: if(variable-exists(foo),$foo,some-new-default);` for users to be able to override the value with `null`? I'm wondering, why doesn't `!default` already have that behavior? Currently, `$foo: null;` is equivalent to not declaring it at all, which renders it useless, but it seems a legitimate use case to me to want to override the default value with `null` sometimes. 

Any 3rd party Sass framework that have a lot of variables with default values to allow customization would now have to change how they declare those variables in order to provide their end-users the most flexibility in customization.

**Comment by chriseppstein** [comment]
> which renders it useless

This assumes your use case is the only use case and discards the use case where an author wants to use a default value after initially setting a value. However, both are valid.

> Any 3rd party Sass framework that have a lot of variables with default values to allow customization would now have to change how they declare those variables in order to provide their end-users the most flexibility in customization.

If the framework's goal is to provide a default value for things that have no value, this is what `!default` does for them right now. `null` by definition is the absence of a value. If a framework's goal is to allow a user to change a default to having no value, I contend this is a less common use case, and so the solution provided above is sufficient. If I continue to see this issue crop up over the next year, I will reconsider.

**Comment by ghost** [comment]
Is there any particular reason why this code can't have transparent as $color2 instead of null?

**Comment by gabriellecrawford** [comment]
@chriseppstein the solution provided is really going to help, happy to have it. :)  But any chance we could have a similar but different keyword? like !defaulted or !existing or something? It's not a huge deal, but my users are mostly not sass people, so something like "$foo: some-new-default !existing;" would probably confuse them less....
