### ISSUE TITLE
The sass options stored on nodes should be a weak reference

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#888]
Here's a fun one I bumped into at work:

The objects stored in the sass options has can grow very large. For example, the default cache store holds cached values in memory as well as writing them to disk

If any sass script literal gets memoized in global memory, this very small object can end up causing a very large amount of memory to be leaked.

The options reference is a strong reference in the Sass::Engine, once that engine goes away we don't need the options anymore -- the literal(s) that are stored would get new options set on them when they are returned. As such, we should store all options on a node as a `WeakRef` so that the options will get GC'd when the engine goes away.

**Comment by nex3** [comment]
To clarify, this is just something we need to do for `Sass::Script::Value` instances, right?

In the (unlikely) case that a user holds on to a Value reference and not a reference to that Value's Engine, this could result in the return value of `#to_s` changing at an unpredictable time. This is a narrow edge case, but it is pretty unfriendly behavior in that case.

One alternative to using `WeakRef` would be to stop storing a reference to the options hash in `Value` at all. The only place it's used in value nodes is to check the output style when converting to CSS. We could move from using `#to_s` for that to a new `#to_css` method that takes a mandatory options argument. `#to_s` would forward to this for custom-function backwards-compatibility, but with a default options hash.

**Comment by chriseppstein** [comment]
> To clarify, this is just something we need to do for Sass::Script::Value instances, right?

Yes, I can't think of any legitimate need to store a tree node.

> this could result in the return value of #to_s changing at an unpredictable time

This would actually result in an exception, once GC'd any attempt to access the weakref is an error.

> One alternative to using WeakRef would be to stop storing a reference to the options hash in Value at all.

This would also be fine.

**Comment by nex3** [comment]
I realized a problem with my proposal: the default implementation of most SassScript operators calls `#to_s`, and removing the access to the options hash will cause this to generate the wrong output in some cases.

Is it feasible to just manually set the options hash to nil on a node before storing it globally?

**Comment by nex3** [comment]
I'm going to close this out with the suggestion that the options has be set to nil on a node before storing it globally. That's much safer and more explicit than using a WeakRef.
