### ISSUE TITLE
Comments on the same line as selectors cause explodeyness

### ISSUE THREAD

**Issue by SimplGy** [sass/sass#895]
Works great:

```
// Comment
.subTitle
  color: $colorForegroundMild
```

Causes explosion:

```
.subTitle // Comment
  color: $colorForegroundMild
```

Message is "Properties are only allowed within rules, directives, mixin includes, or other properties. (Sass::SyntaxError)"

The happened while migrating from an older version of SASS (2.3, maybe) to the latest, 3.3.0.alpha.231

**Comment by nex3** [comment]
The indented syntax doesn't support inline comments in most cases.
