### ISSUE TITLE
Placeholder extending stopping prematurely at tag when other selectors still exist

### ISSUE THREAD

**Issue by r4j4h** [sass/sass#899]
Hi there! I am sorry if the name of this issue is weird, I am not sure quite what to call it. I am using `Sass 3.2.10 (Media Mark)` on `Mac OSX 10.7.5`.

Note that the only difference betw/ `%testfail` and `%testexpect` is the first `a` has an additional class requirement of `.hmmm`. This allows the other selectors through, if `.hmmm` is taken off the rest of them are not output.

This sample code

```
.testfail-instance {
    @extend %testfail;
}
.testexpect-instance {
    @extend %testexpect;
}

%testfail {

    a {
        @extend %testproof;
    }

    a.joe {
        @extend %testproof;
    }

    a.rawr {
        @extend %testproof;
    }
}

%testexpect {

    a.hmmm {
        @extend %testproof;
    }

    a.joe {
        @extend %testproof;
    }

    a.rawr {
        @extend %testproof;
    }
}

%testproof {
    color: blue;
}
```

Compiles down to:

```
.testfail-instance a, .testexpect-instance a.hmmm, .testexpect-instance a.joe, .testexpect-instance a.rawr {
  color: blue; }
```

But I would expect it to compile down to:

```
.testfail-instance a, .testfail-instance a.joe, .testfail-instance a.rawr, .testexpect-instance a.hmmm, .testexpect-instance a.joe, .testexpect-instance a.rawr {
  color: blue; }
```

**Comment by nex3** [comment]
This is expected. `.textfail-instance a` is a "superselector" of `.textfail-instance a.joe`, `.testfail-instance a.rawr`, and `.testfail-instance a.hmm`.  This means that it matches every element that's matched by those other selectors. As an optimization, Sass removes the redundant selectors.

**Comment by r4j4h** [comment]
I see. Thank you for the clarification. If I add a specific style aside from the @extends then all of the selectors do indeed come through. I can see why this occurs when they all extend the same selector.
