### ISSUE TITLE
Feature: Output block to separate file or different location

### ISSUE THREAD

**Issue by dalgard** [sass/sass#911]
I don't think the following is currently possible. What I'd like to do is dynamically pipe some content to a separate file or perhaps to the location of a bookmark of some sort (which could later be split out).

The use case is building stylesheets which could be lazy-loaded; the best example is exporting some stuff to an old-IE stylesheet directly via a function or mixin or other form of directive.

For instance, some media query mixins have a fallback option which basically takes `@content` and puts it inside a block with a fallback class. Using this method, the stylesheet is littered with `.no-mq` or `.oldie` classes which probably ought be put in a separate file and loaded inside a conditional comment or using YepNope/RequireJS etc.

**Comment by KittyGiraudel** [comment]
Related conversation I believe: https://github.com/nex3/sass/issues/241.

**Comment by dalgard** [comment]
Thanks.
