### ISSUE TITLE
Sass 3.3.0 alpha

### ISSUE THREAD

**Issue by zemd** [sass/sass#913]
I don't familiar with sass codebase so I want just ask some questions.
Trying to use latest compass and sass together and have several problems:
there are changes with sass script values - they changed parent for base class, and there are problems with old code, for example, 
https://github.com/nex3/sass/blob/master/lib/sass/script/value/arg_list.rb#L34 
`super` calling makes compass fail, and without it behaves normally, because there is no implementation children method in parents. 
There are more errors during building https://travis-ci.org/hunterman/compass/jobs/11091727
So my question is: Will this functions be implemented? and is it ok to remove invocation super function? :)

**Comment by nex3** [comment]
It's very difficult to tell what this issue is actually about, but it's true that the definition of `ArgList#children` is no longer needed.
