### ISSUE TITLE
scripted parent selector not working within mixin?

### ISSUE THREAD

**Issue by fexodus** [sass/sass#914]
I tried to use the parent selector within this mixin:

```
@mixin test {
  .bla {
    @at-root #{&}-bli {
      color: red;
    }
  }
}
@include test;
```

But the parent selector renders as empty string:

```
-bli {
  color: red; }
```

**Comment by gisu** [comment]
The new Ampersand and @at-root did not work with the latest Master ( expected expression).

**Comment by nex3** [comment]
Your example works for me (if I replace `@include element` with `@include modifier`). You'll need the master branch at b6f71a816b6d7fd3c54def0dbb2eb4266c1585d1 or later for this.

**Comment by fexodus** [comment]
i updated my example, so the issue is more clear
