### ISSUE TITLE
Sass ignores Compass images_dir setting

### ISSUE THREAD

**Issue by mgol** [sass/sass#916]
I have the following `config.rb`:

``` ruby
http_path = "/"
css_dir = "app"
sass_dir = "app"
images_dir = "app"
output_style = :expanded
relative_assets = true
line_comments = false
```

I use the [grunt-contrib-sass](https://github.com/gruntjs/grunt-contrib-sass) Grunt plugin to generate CSS; I use the following settings:

``` javascript
app: {
    options: {
        bundleExec: true,
        compass: 'app/config.rb',
        loadPath: ['app/vendor/compass'],
        sourcemap: true,
        style: 'expanded',
    },
    files: {
        // Use temporary file with includes created by the `preSass` task.
        'app/styles.css': ['app/_includes.scss.tmp'],
    },
},
```

However, Sass seems to ignore the `images_dir` paramter and looks for the images always in the `/images/` directory. This causes problems, forcing us to create a symbolic link `images -> app` and breaking the project for people on Windows.

**Comment by gisu** [comment]
Try grunt-contrib-compass when you use compass.

**Comment by mgol** [comment]
I can't. Compass doesn't currently support creating sourcemaps which are
absolutely essential to me.

## 

Michał Z. Gołębiowski

**Comment by nex3** [comment]
You can't have your cake and eat it too -- at least not until Compass supports sourcemaps. `config.rb` is a Compass feature. You need to compile your stylesheets with Compass in order for it to be loaded.

**Comment by mgol** [comment]
Hmm, but I use the `compass` option that makes Sass read options from `config.rb`. Do you mean it doesn't read all the options and there's no easy way to prevent that?

If so, I understand, I'll report it to `grunt-contrib-sass` to make a note under a documentation for this option that not all options are supported.

**Comment by nex3** [comment]
How `grunt-contrib-sass` supports Compass is a question for that project.

**Comment by mgol** [comment]
OK, I just thought this is native Sass functionality that is just proxied via `grunt-contrib-sass` (as most options are). Obviously, I was wrong.
