### ISSUE TITLE
Allow a trailing comma in maps

### ISSUE THREAD

**Issue by monsanto** [sass/sass#917]
That is, make declarations like

```
$map: (
  prop1: val1,
  prop2: val2,
  prop3: val3,
);
```

legal. Python does this and it very helpful.

**Comment by Anahkiasen** [comment]
+1 for this

**Comment by cimmanon** [comment]
Is there a use case for this?  Sass doesn't allow trailing commas in lists, so it doesn't make sense for it to be valid for maps.

**Comment by Anahkiasen** [comment]
It's just more maintainable that way, you can add items as you wish and reorder them without having syntax errors. And maps are not lists, so in my mind they don't necessarily follow the same rules

**Comment by monsanto** [comment]
I am using large maps, with one `k: v` pair per line. It is common for me to to add and remove lines, reorder lines, and copy/paste lines from these maps. But if any of these operations involve the end of a map, you have to manually play around with commas, which is annoying. Most of the time, these operations DO involve the end of a map.

Note since CSS `k: v` pairs are ALWAYS terminated with a semicolon, this problem doesn't arise. So it sucks that it does with a different kind of `k: v` pair.

**Comment by cimmanon** [comment]
It sounds like your problem would be better solved by adjusting your coding style, not the language:

``` scss
$icons:
    ( success $icon-ok
    , warning $icon-warning-sign
    , error $icon-exclamation-sign
    , required $icon-asterisk
    , info $icon-info-sign
    , help $icon-question-sign
    // modify
    , add $icon-plus-sign
    , remove $icon-minus-sign
    , edit $icon-pencil
    // general
    , search $icon-search
    , download $icon-download-alt
    , upload $icon-upload-alt
    , flag $icon-flag
    , bookmark $icon-bookmark
    // project specific
    , heart $icon-heart
    , heart-empty $icon-heart-empty
    , map $icon-map-marker
    , calendar $icon-calendar
    , camera $icon-camera
    , photo $icon-picture
    // social
    , phone $icon-phone
    , email $icon-envelope-alt
    );
```

The likelihood of moving the first item in the collection is exceptionally rare compared to how often one would rearrange the elements that follow or append additional elements.

@monsanto CSS doesn't _have_ maps, the `property: value` syntax is more like an imperative style collection of commands (apply this style, then apply the next style, etc.).  Just because it looks like a duck from another language doesn't mean that it _is_ a duck in this language.

**Comment by Anahkiasen** [comment]
That doesn't change a thing, now the first item would be problematic. Plus that kind of looks horrible. I don't see what the block is anyway, lots of language allow trailing commas : PHP, Javascript, etc.

**Comment by monsanto** [comment]
> CSS doesn't have maps, the property: value syntax is more like an imperative style collection of commands (apply this style, then apply the next style, etc.). Just because it looks like a duck from another language doesn't mean that it is a duck in this language.

That is your personal interpretation of the surface syntax. I think they look like maps. For whatever it is worth, @chriseppstein made this connection in the issue that inspired map support in Sass. Regardless, I never said CSS had maps. I said it had `k: v` pairs, which I think is an uncontroversial statement. Since this is a fairly tangential point I am going to avoid arguing it further in this thread.

**Comment by KittyGiraudel** [comment]
Trailing commas would be nice. Even for lists actually.

**Comment by vinayraghu** [comment]
:+1: for trailing commas for lists as well

**Comment by nex3** [comment]
I don't have a problem with this, although we'd certainly want to make maps and lists consistent. This would also probably end up supporting @eevee's proposed syntax for single-element lists in #837.

**Comment by xzyfer** [comment]
:+1: for this, and for the proposed use case in https://github.com/nex3/sass/issues/837#issuecomment-22652122

**Comment by chriseppstein** [comment]
This is a good idea.
