### ISSUE TITLE
How to skip a single line during compilation

### ISSUE THREAD

**Issue by RobinQu** [sass/sass#918]
Is there any magic syntax to tell compiler to skip some lines in SCSS files?

**Comment by cjcheshire** [comment]
Isn't that called a comment? :p

// single line

/*

Multiple

*/

**Comment by RobinQu** [comment]
I'm afraid not.

```
THIS LINE SHOULD BE KEPT HERE AND CANNOT BE WRAPPED WITHIN COMMENT

// other css rules
```

For real world example:

```
*html,*htmlbody{background-image:url(about:blank);background-attachment:fixed;}
```

This line will cause the compiler to hang. And for some reason, we cannot change the rule. 

Error

```
error app/styles/web/common/common.scss (Line 163: Invalid CSS after "*": expected "{", was "html,*htmlbody"
```

**Comment by Anahkiasen** [comment]
Well yeah but that's invalid CSS, you'll need to add some spaces here.

**Comment by RobinQu** [comment]
This line is written in favor of hacks for IE6. And we are not authorized to rewrite it.

**Comment by cjcheshire** [comment]
So if you have to do this, I'd be inclined as a work around to either have
them separate either with a condition in html or use the traditional import
in your scss file: "@import "horrible-ie6-must-have.css";" ala
http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#directives.

**Comment by cimmanon** [comment]
Why use hacks when you can use conditional comments to target IE6 specifically?

**Comment by KittyGiraudel** [comment]
I think the simplest solution would be to move this out of your Sass stylesheet.

**Comment by nex3** [comment]
Even if you want to use the `* html` hack, a space is mandated by the spec between the `*` and the `html`. Sass follows the spec's parsing rules when parsing plain CSS except where necessary to parse a common hack, and in this case that's not necessary.

There's certainly not going to be a feature to just not parse a section of the document. If you really, really need to do that you can do some sort of hack using the `unquote()` function and strings.
