### ISSUE TITLE
inline selectors in @at-root don't unquote

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#920]
Like in selectors, strings should be automatically unquoted during interpolation in an `@at-root` context.

**Comment by nex3** [comment]
This works for me:

```
$ echo '@at-root #{"foo"} {a: b}' | ./bin/sass --scss
foo {
  a: b; }
```

I can't imagine why it wouldn't work; it uses the same script infrastructure as everything else. How are you reproducing this?

**Comment by chriseppstein** [comment]
i can't repro anymore either. sigh.
