### ISSUE TITLE
rake aborted!uninitialized constant Gem::Builder

### ISSUE THREAD

**Issue by cycold** [sass/sass#927]
when:
git clone git://github.com/nex3/sass.git
cd sass
rake install

return:
rake aborted!
uninitialized constant Gem::Builder
e:/kuaipan/web/git/repository/sass/Rakefile:31:in `block in <top (required)>'
Tasks: TOP => install => package,
?

**Comment by nex3** [comment]
What version of Ruby are you using? Do you have rubygems installed?

**Comment by cycold** [comment]
thankssssss,
still from the github install sass is failure,
but, later, from the "https://github.com/rubygems/rubygems/issues/515" get some information:
using "gem install sass -r --source http://rubygems.org" replace "gem install sass" ,success.
version of Ruby:
gem -v
2.0.3
sorry, poor English..

**Comment by shepmaster** [comment]
I get the same error after I cloned the repo to make some changes.

```
$ ruby --version
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin12.5.0]
$ gem -v
2.1.5
```

```
$ ruby --version
jruby 1.7.5 (1.9.3p392) 2013-10-07 74e9291 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_10-b18 [darwin-x86_64]
$ gem --version
2.1.5
```

**Comment by shepmaster** [comment]
I switched to JRuby 1.7.4, which has an older RubyGems, which seemed to work:

```
$ ruby --version
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_10-b18 [darwin-x86_64]
$ gem --version
1.8.24
```

A quick search suggests that this error indicates RubyGems 2.x incompatibility.
