### ISSUE TITLE
scripted parent selector not working as expected

### ISSUE THREAD

**Issue by fexodus** [sass/sass#929]
I tried to use the parent selector within this mixin:

```
@mixin test {
  .bla {
    @at-root #{&}-bli {
      color: red;
    }
  }
}
@include test;
```

But the parent selector renders as empty string:

```
-bli {
  color: red; }
```

**Comment by pdaoust** [comment]
Sorry to bump this thread, but I'm just curious -- is this confirmed as a bug, then, or is it the way it's meant to work?

**Comment by nex3** [comment]
This is a bug.

**Comment by pdaoust** [comment]
Ah, good to know, thanks! I'd like to help out, although I got a bit lost last time I dug into the Sass code. I dunno if it would take just as long to give me a brief explanation of the code as it would to fix the bug, but I'm certainly willing to help fix it if I know where to start! (The lifecycle of the compiler is what really confused me -- like, in which order do the walkers tackle the source, then the tree, etc.) This is a biggie for something I'm working on at work, and the boss doesn't mind me taking a little bit of time to try to fix it.

**Comment by nex3** [comment]
You can follow the lifecycle by tracing the path of execution within `Sass::Engine#_render`. In particular, the order that the visitors are run in is defined in `Sass::Tree::RootNode#render`. This issue is likely caused by a bug in the handling of the `Sass::Environment` in `Sass::Tree::Visitors::Perform`.

**Comment by pdaoust** [comment]
Thanks, that's a good starting point. I likely won't be able to look at it for a couple of days, but I'll do my best. So the `Sass::Environment` holds the current nested context, does it? (On a related note, is there a way to find out what sort of media query context we're in, in the same way that `&` will tell us the selector context?)

**Comment by nex3** [comment]
> Thanks, that's a good starting point. I likely won't be able to look at it for a couple of days, but I'll do my best.

In that case I may just go ahead and fix it on my own.

> So the `Sass::Environment` holds the current nested context, does it?

Yes.

> On a related note, is there a way to find out what sort of media query context we're in, in the same way that `&` will tell us the selector context?

No, neither in Sass nor in Ruby.

**Comment by pdaoust** [comment]
Thanks a pile! I installed the alpha via gem, and it works great.
