### ISSUE TITLE
numbers between 0 and 1 and percentages should be interchangeable

### ISSUE THREAD

**Issue by AlexRiedler** [sass/sass#931]
Considering the case where the old documentation was:
transparentize(color, NN%)

and that you can still do:
lighten(color, NN%)

transparentize (and related functions) that take between 0 and 1, should always accept percentages between 0% and 100%; due to their mathematical equivalent.

**Comment by pdaoust** [comment]
+1 for this idea. You can use the `percentage()` function to go the other way; it'd be nice to have an `unpercentage()` function -- and to not have to use it in the first place. In the meantime, here's a couple fun functions for readers:

``` scss
@function unpercentage($value) {
    // Return the value unchanged if it's not a percentage.
    @if unit($value) != '%' { @return $value; }
    @return $value / 100%;
}

@function my-transparentize($color, $amount) {
    // Of course, you can do this for any function that you wished took percentages.
    @return transparentize($color, unpercentage($amount));
}
```

**Comment by nex3** [comment]
All functions like this take units that match the units used in HSL(A) declarations. Lightness is specified in terms of percentage, whereas opacity is specified in terms of a number between 0 and 1. Sass is just following CSS on this. Similarly, in CSS percentages are not interchangeable with decimal numbers, so in Sass they aren't either.

**Comment by AlexRiedler** [comment]
@nex3 by the same argument you should remove numbers between 0 and 1 for lighten ?

**Comment by nex3** [comment]
`lighten(#000, 0.5)` is equivalent to `lighten(#000, 0.5%)`, not `lighten(#000, 50%)`. All functions that accept arguments with a specific unit also accept unitless arguments.

**Comment by AlexRiedler** [comment]
oh thanks for the clarification nex3! that makes more sense
