### ISSUE TITLE
[wishlist] add two new color functions

### ISSUE THREAD

**Issue by jpka-** [sass/sass#935]
Hi! Is there any possibility to add to here http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html , two functions in future:

```
gray(value)
```

which works as _lighten(#000, value);_ and

```
websafe(color)
```

which works as arrange each of r, g, b values to nearest value which is multiple of 20% of full scale.
Thank you!

**Comment by Anahkiasen** [comment]
I've been adding a custom `grey` function to my projects since the dawn of time so I for one would appreciate this in the core so much.

**Comment by nex3** [comment]
I don't think it's onerous to write `hsl(0, 0, $value)`, and I don't think web-safe colors are relevant enough these days to warrant a core library function to support them.

**Comment by Anahkiasen** [comment]
Believe me when you have to use it all over the place it's pretty cumbersome to write. I gather it's not that onerous to write in the absolute, but on the other it's just a basic single function. If we follow your logic then why go to the trouble of supporting `hsl(black, 20%)` when `hsl(0, 0%, 20%)` is just a few characters more.

**Comment by nex3** [comment]
`hsl(black, 20%)` is invalid. Are you thinking of `rgba($color, $alpha)`? That was originally added to make it easy to add an alpha channel to colors which were already stored in a variable, before `set-color()` was added. The only other way to do that at the time was `rgba(red($color), green($color), blue($color), $alpha)`, which is much more verbose. If the only use case had been defining color literals, it wouldn't have been added.

If your code does end up defining enough grayscale colors to want this function, you're able to define it yourself. I don't think it's generally useful enough to be in the core libraries.

**Comment by Anahkiasen** [comment]
Yes sorry `rgba`. Well I guess I'll keep my helpers around then.

**Comment by jpka-** [comment]
Hi! I still think new function(s) always should be added when:
- it is small, easy, straightforward and intuitive.
- it is not harmful and can't introduce new bugs.
- it conforms to software philosophy.
- it can't affect existing scripts written for this software.
- it is need by more than one user.
  Gray/grey() is good example of that function.
  Thanks.
