### ISSUE TITLE
Support for namespace in CSS selector

### ISSUE THREAD

**Issue by ghost** [sass/sass#936]
I have an element with the epub:type attribute (&lt;section epub:type="bodymatter"&gt;&lt;/section&gt;) . To select i with CSS, I do this 
[epub\\:type]
{
}

But Sass does not recognize this designation, I have this error : 
Sass Error: Invalid CSS after "[epub\": expected "]", was ":type]"

Is this possible to implement this modification ?  It's important not to have attributes that does not serve the semantic and if we can style the elements on epub:type attribute, that'd be great.
![capture2](https://f.cloud.github.com/assets/2803864/1207779/8f202286-25c0-11e3-8603-05c004322561.PNG)

**Comment by nex3** [comment]
Your example is invalid CSS. If you use a single `\`, it would work, though:

``` scss
[epub\:type] { ... }
```
