### ISSUE TITLE
Create guide for writing Sass functions in ruby

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#942]
We need to create a tutorial for how to use create Sass functions in ruby and also fully document the relevant ruby API provided by Sass including marking all relevant API with `@since` documentation.

**Comment by pdaoust** [comment]
Whoa, that'd be fantastic! I'm all for that.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
