### ISSUE TITLE
Single-valued lists not evaluating properly.

### ISSUE THREAD

**Issue by kumarharsh** [sass/sass#950]
Hi,

I've been using these lines for quite some time, and it works in my system (Ubuntu), but under windows this fails:

```
body {
  $font: Verdana, Arial;
  @warn index($font, Verdana}
```

This compiles well in Ubuntu, even gives me the correct index, but in Windows (version **3.2.1 Media Mark**), it throws this error:

```
error main.scss (Line 6: "Verdana" is not a list for `index'
```

In the documentation, its specifically mentioned that

```
individual values count as lists, too: they’re just lists with one item.
```

So why is it not working?

Surprisingly, it's also throwing this same error while doing an automatic grunt-build after npm-install. But, when I run the grunt command by hand, it doesn't break.

---

As a workaround, I _can_ use this: `$a: ghij, ()` to enforce `$a` to be treated like a list, but it's hacky, and doesn't go well with rest of the css.

**Comment by nex3** [comment]
Version 3.2.1 is very old; try upgrading and see if that works. If it doesn't, see if you can find a minimal example that consistently triggers this behavior.

**Comment by kumarharsh** [comment]
The error has intermittently appeared while running an automatic `postinstall` script via `npm`.
Anyways, upgrading to 3.2.12 has solved the issue.
