### ISSUE TITLE
@debug should call to_sass instead of to_s on objects passed to it.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#953]
Also, maybe `inspect($value)` could return a string that is to_sass on the value so that strings can be constructed.

**Comment by KittyGiraudel** [comment]
It would be quite cool to have a function `inspect()` or `debug()` that returns a list as a string or something. Kind of JSON-like, I don't know.

On topic, I made my own debug helper to output the content of a list as a pseudo-element on body: http://hugogiraudel.com/2013/10/21/sass-debug/. Demo: http://codepen.io/HugoGiraudel/pen/unyBH.

It's kind of overkill, but when working on complex demo with Sass, such a helper can really come in handy. Thus I'm looking forward the inspect function. ;)
