### ISSUE TITLE
Include classes

### ISSUE THREAD

**Issue by eltiare** [sass/sass#965]
I hope to dig into the code and submit a pull request, but this would help with a major pet peeve of mine with modern CSS frameworks. 

I hate having to specify 3-8 class names for an element and would rather condense them down into one class name for a context rather than what that element is supposed to look like. CSS was designed to separate content from presentation and class names like "text-centered" and "columns large-2" are a step backwards in that regard. 

It'd be fantastic if there was some way to include classes in another class like currently happens for modules. A possible alternate way of doing this would be to deprecate modules and just have all classes be essentially modules. Since I haven't dug into the code yet I'm just throwing out random thoughts. I suppose another alternate for this problem is to petition the makers of Bootstrap and Foundation to do everything as modules that we can import into our classes - but I'd like to have a discussion here first.

**Comment by nex3** [comment]
Have you seen [`@extend`](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#extend)?

**Comment by eltiare** [comment]
Nope! Thanks for the heads up and glad to see it's already in there.

**Comment by HamptonMakes** [comment]
It's beautiful when things work out that way...
