### ISSUE TITLE
@extend and ampersand

### ISSUE THREAD

**Issue by Ti-webdev** [sass/sass#97]
SCSS:

<pre><code>.a { color: red; }
.b {
    &-c { @extend .a; }
}</code></pre>

Expected result:
`.a, .b-c { color: red; }`

 Actual result:
`.a, -c.b { color: red; }`

**Comment by nex3** [comment]
This is solved, sort of, by face3172930b515ac2040e450d4db3ffe01c31b5.

In fact what the aforementioned commit does is disallow the selector `&-c`, for reasons discussed in the commit message.
