### ISSUE TITLE
Apostrophe sign as ??? 

### ISSUE THREAD

**Issue by nicolaisi** [sass/sass#977]
At this [doc](http://sass-lang.com/documentation/) the page has its Apostrophe sign showed in ???

Maybe there's some encoding issue?

**Comment by yanandcoffee** [comment]
Works just fine for me (using latest stable Chrome browser). I searched the whole document for question marks, skimmed through it myself, and there's nothing wrong with it. Seems like it might be a browser encoding issue on your end.

**Comment by nicolaisi** [comment]
Correct, older browser issue
