### ISSUE TITLE
disrupted during sass --watch

### ISSUE THREAD

**Issue by nicolaisi** [sass/sass#978]
Hi,

I just started using sass and it's a great tool.

I'm using sass watch to monitor my scss file and convert it to css. It's all good, but at a certain point, it detected that my scss file is deleted and soon after that detected a new template (same file).

Output:

```
overwrite css/globelog.css
>>> Change detected to: /home//controller/static/sass/globelog.scss
  overwrite css/globelog.css
>>> Change detected to: /home/controller/static/sass/globelog.scss
  overwrite css/globelog.css
>>> Deleted template detected: /home/controller/static/sass/globelog.scss
      error No such file or directory - sass/globelog.scss
>>> New template detected: /home/controller/static/sass/globelog.scss
```

Of course, cancel it and restart again works. Just thought that I should share this :)

I uses GVIM to edit the scss file and I do ":w" everytime I'm saving my file.

**Comment by nex3** [comment]
If this is a bug and not just a weird one-off behavior, it's a bug with guard/listen.

/cc @thibaudgg
