### ISSUE TITLE
Allow pass-through for ERB, etc.

### ISSUE THREAD

**Issue by jtara** [sass/sass#979]
I have a problem I can't seem to solve with current Sass functionality. Perhaps I just haven't tried the right search terms, but I can't seem to find a facility for what I am trying to do.

I am using Sass as a build-time preprocessor, generating CSS files that will then be served as an ERB in a mobile app at runtime. (In RhoMobile Rhodes). I am _not_ using Sass as part of the run-time asset pipeline.

(Actually, I have a build-time asset pipeline - Mustache -> Sass -> CSS).

I want the output to be processed by ERB by the runtime system. But I can't figure out a way to convince Sass to let me include ERB without getting a syntax error.

I saw a suggestion on StackOverflow to use`unquote()` on a quoted string, but that doesn't seem to do anything - I just get the same syntax error.

Here is an example of what I would like to do:

``` erb
@media all and (min-width: <%= two_column_min_width %>px){
  background: red;
}
```

At run-time, the ERB would be expanded.

There needs to be some way to "protect" the ERB so that Sass doesn't see it as a syntax error. I suppose that Sass might somehow have to "fool itself" internally to think that there is a valid number there...

Is there any way to embed arbitrary text into the output at any point? If not, there should be.

**Comment by nex3** [comment]
There are some places where you could write `#{"<%= two_column_min_width %>"}` or whatever, but that won't work everywhere. A general mechanism for hopping out of the normal syntax is not planned.
