### ISSUE TITLE
@error directive

### ISSUE THREAD

**Issue by svallory** [sass/sass#983]
Hi,

I'm implementing a set of functions to make creating themes for our product easier, e.g., to allow the theme to get it's assets urls. Each of these functions require either a `$theme` parameter to be passed or a global variable $current-theme to be set. Here is an example from my _theme-functions.scss:

``` sass
$current-theme: "not set" !default;

@function theme-img($path, $theme: $current-theme) {
  @if $theme == "not set" {
    @warn "Either pass the theme name using $theme parameter or set the $current-theme global variable";
  }

  @return url("/assets/themes/" + $theme + "/" + $path);
}
```

The best I can do right now is give a warning. Would it be possible to implement a directive that would throw an error, pretty much like what happens when we get a syntax error?

**Comment by nex3** [comment]
Duplicate of #747.
