### ISSUE TITLE
Inaccurate large number calculation after dividing

### ISSUE THREAD

**Issue by jamiebuilds** [sass/sass#997]
**Steps to reproduce:**
1. Divide any number by any number (eg. `3 / 1`)
2. Multiply/Modulus a large number (eg. `* (10^22)`)

http://sassmeister.com/gist/7282272

``` scss
3 divided by 1 times large numbers {
    test-1: (3 / 1) * 10000000000000000000;       // 30000000000000000000
    test-2: (3 / 1) * 100000000000000000000;      // 300000000000000000000
    test-3: (3 / 1) * 1000000000000000000000;     // 3000000000000000000000
    test-4: (3 / 1) * 10000000000000000000000;    // 30000000000000000000000
    test-5: (3 / 1) * 100000000000000000000000;   // 299999999999999974834176
    test-6: (3 / 1) * 1000000000000000000000000;  // 2999999999999999949668352
    test-7: (3 / 1) * 10000000000000000000000000; // 30000000000000004865392640
}
```

**Comment by chriseppstein** [comment]
This is expected with floating point arithmetic which Sass uses internally. Javascript does similarly strange things:
![sass 2013-11-04 11-03-38](https://f.cloud.github.com/assets/1839/1467523/d217c2f0-4583-11e3-846c-aabbb19808a8.png)

It's important to keep perspective. While the errors can accumulate, usually, when dealing with very large numbers these differences are really a rounding error and wouldn't be noticeable. What are you using such large numbers for?

**Comment by jamiebuilds** [comment]
@chriseppstein different calculations can create very large numbers before reducing them to the answer, for example using wilson's theorem to calculate prime numbers uses a factorial of `n` to determine if it's prime. Which in this case would make 24 the highest number you could use.

The maclaurin series does the same thing, which is used to calculate many trigonometric functions (`cos`, `sin`, `tan`, ...)

**Comment by chriseppstein** [comment]
Ok. But let's be clear. SassScript is not a general purpose computing language. It is for generating CSS. Why do you need to do that in SassScript?

**Comment by jamiebuilds** [comment]
I wasn't trying to suggest you make any major changes, I thought this was a legitimate bug. I was doing those things (I'm assuming) for the same reason compass does.
